### ISSUE TITLE
Test build compatibility with composer 2.0

### ISSUE THREAD

**Issue by allendav** [Automattic/woocommerce-payments#1034]
On running `composer update`

> You are using an outdated version of Composer. Composer 2.0 is about to be released and the older 1.x releases will self-update directly to it once it is released. To avoid surprises update now to the latest 1.x version which will prompt you before self-updating to 2.x.

From https://github.com/composer/composer/releases/tag/2.0.0-RC2

> "The current plan is to release a 2.0 final before end of October."

and

> "The lock files from v1 can be used by v2 and vice-versa, so don't worry about that."

Hopefully a non-event for us. cc @DanReyLop 

I am running

```
allendav@Lyra woocommerce-payments % composer -V
Composer version 1.10.4 2020-04-09 17:05:50
```

the latest 1.x version is 1.10.15 released last week.

**Comment by DanReyLop** [comment]
Looking at the [upgrade guide](https://github.com/composer/composer/blob/2.0.0-RC2/UPGRADE-2.0.md), as long as the current version of `composer` doesn't throw any warnings, we should be fine.

**Comment by DanReyLop** [comment]
^^ Famous last words

```
$ composer install
Installing dependencies from lock file (including require-dev)
Verifying lock file contents can be installed on current platform.
Your lock file does not contain a compatible set of packages. Please run composer update.

  Problem 1
    - kalessil/production-dependencies-guard is locked to version dev-master and an update of this package was not requested.
    - kalessil/production-dependencies-guard dev-master requires composer-plugin-api ^1.1 -> found composer-plugin-api[2.0.0] but it does not match the constraint.

You are using Composer 2, which some of your plugins seem to be incompatible with. Make sure you update your plugins or report a plugin-issue to ask them to support Composer 2.
```

cc/ @kalessil :)

Once I remove that dependency, everything works.

**Comment by kalessil** [comment]
@DanReyLop: the issue has been fixed. We also running Composer v2.0 in Travis already.
