### ISSUE TITLE
Hide payment form when saved card is selected on Pay for Order screen

### ISSUE THREAD

**Issue by dechov** [Automattic/woocommerce-payments#1043]
As of https://github.com/Automattic/woocommerce-payments/pull/946, the payment form is properly hidden when a saved card is selected (due to the behavior of the WC core tokenization script which we load), but this is **not working on the Pay for Order screen** unless another gateway with saved cards (such as Stripe) is also present.

@luizreis in the comments of https://github.com/Automattic/woocommerce-payments/pull/946:
> the fieldset element is not hidden when a saved card is selected
> _[…]_
> Here's a quick recording of how I tested it: https://d.pr/i/qEVIdy

I think this may have to do with the order of when the DOM is ready in relation to when the tokenization script is enqueued or initialized, but couldn't pinpoint the exact cause on first try.

**Comment by chickenn00dle** [comment]
This one looks to be fixed.

Saved card selected: https://cloudup.com/cg3WElJevwM
New payment method selected: https://cloudup.com/cWVZTjPGURo

I'll go ahead and close this. Feel free to re-open if I've misunderstood.
