### ISSUE TITLE
Display original and converted charge amounts on order and transaction detail screens

### ISSUE THREAD

**Issue by dechov** [Automattic/woocommerce-payments#1054]
_Revised description:_

On the order and transaction detail screens, we need to show original and converted amounts, with the conversion used – see designs below.

_Original issue description:_
> When a charge is made in a (presentment) currency different from the (settlement) currency on the merchant account, it is automatically converted by Stripe for purposes of factoring into the merchant balance.
>
> Specifically, the _charge_ (`amount` and `currency` values) will reflect the original, while the (balance) _transaction_ will reflect the conversion. The latter will be used for aggregation on the Transactions views but for individual rows and details screens, we could and may want to display both.
>
> _How should these appear?_ c/o @LevinMedia
>
> Note that displaying the original amount and currency in the list view will require enhancing the server to cache these charge-related values, but doing so in the details view will not require this.
>
> Note also: it won’t always be true that each account has just one settlement currency (and one “balance”) but this will be the case for the time being – that is, until we support multiple bank accounts down the line.

The transaction list bit has been extracted out into https://github.com/Automattic/woocommerce-payments/issues/1202.

**Comment by dechov** [comment]
Similar design specs for order notes as for payment detail timeline events:

Charge | Refund | Dispute
-- | -- | --
<img width="189" alt="charge-order-note" src="https://user-images.githubusercontent.com/1867547/104565482-56c7b880-561a-11eb-81e3-50b7f10a5d28.png"> | <img width="191" alt="refunded-order-note" src="https://user-images.githubusercontent.com/1867547/104565485-57604f00-561a-11eb-9546-91ac0a006906.png"> | <img width="190" alt="dispute-order-note" src="https://user-images.githubusercontent.com/1867547/104565488-57f8e580-561a-11eb-838b-411b094f4163.png">

<img width="589" alt="payment-details" src="https://user-images.githubusercontent.com/1867547/104565492-58917c00-561a-11eb-9777-14044910aec1.png">

**Comment by kalessil** [comment]
@dechov , my understanding is that this ticket is depending on 498-gh-Automattic/woocommerce-payments-server, is that correct?

**Comment by dechov** [comment]
It’s only the transactions list (the scope for which I’d separated out into
#1202) that uses the cache, so it shouldn’t be necessary for this one.

I thought the data for this one should already be available in the plugin
layer, though I haven’t looked into it deeply and could be wrong.

**Comment by dechov** [comment]
This is done for the timeline details view (in https://github.com/Automattic/woocommerce-payments/pull/1241), but it was decided not to implement the order note change at the time, and instead just link from order notes to the transaction details for now (done in https://github.com/Automattic/woocommerce-payments/pull/1309).

So the only **remaining scope for this issue is getting the same info into the order notes** (trickier IIRC, since we don't have the information at the time the order note is added, only when the webhook arrives).

**Comment by jessy-p** [comment]
Pending work for Order Notes.

**Comment by jessy-p** [comment]
This issue impacts Multi-Currency, so assigning to Fractal (based on team responsibilities Pc2DNy-3z-p2) @bborman. Assigning as part of Gamma Triage process PcreKM-yM-p2.

Tagging as part of re-evaluating older issues in the backlog, please have a look and close if no longer relevant.

**Comment by vbelolapotkov** [comment]
@jessy-p  that's merchant facing MCY issue, and should be handled internally. Pinging @Automattic/pulsar as it fits orders and transactions management scope.

**Comment by KarlisJ** [comment]
I did a quick test locally setting store currency to EUR and using EUR based test card. I'm seeing both original and converted amounts both in transaction details and order page.

<img width="307" alt="image" src="https://github.com/Automattic/woocommerce-payments/assets/24650518/eb233eca-1ed8-489f-bf96-b765f3d38391">

<img width="1040" alt="image" src="https://github.com/Automattic/woocommerce-payments/assets/24650518/d870a5cf-1015-4996-ad43-a7cc1b95d082">

@kalessil My guess is that this issue has been long addressed and haven't been properly closed.

**Comment by kalessil** [comment]
Thanks for re-evaluating @KarlisJ! Closing as it is not reproducible and dated back to 3 years.
