### ISSUE TITLE
Don't attempt to submit level 3 data for non-US merchants

### ISSUE THREAD

**Issue by allendav** [Automattic/woocommerce-payments#1099]
We don't support non US merchants for WooCommerce Payments, yet, but I don't want this to get lost in the shuffle.

Same as https://github.com/woocommerce/woocommerce-gateway-stripe/issues/1366

Level 3 data is only supported for US merchants. According to Stripe, while we shouldn’t get a hard error from sending it for non-US merchants, they still recommend against it.

**Comment by vbelolapotkov** [comment]
Put on hold until decision is confirmed.

**Comment by vbelolapotkov** [comment]
Reopening as #1400 is not merged yet.
