### ISSUE TITLE
Blocks: Use options object for registering a payment method instead of callback

### ISSUE THREAD

**Issue by thenbrent** [Automattic/woocommerce-payments#1109]
Mentioned [here](https://github.com/Automattic/woocommerce-payments/issues/640#issuecomment-727681295):

> We've changed the API for registering a payment method in WooCommerce Blocks - now pass an options object (previously was a callback).

> Check this PR for more info: woocommerce/woocommerce-gutenberg-products-block#3404

**Comment by jessy-p** [comment]
Sames as #1308 and closed by PR #2070
