### ISSUE TITLE
Improve E2E setup performance

### ISSUE THREAD

**Issue by vbelolapotkov** [Automattic/woocommerce-payments#1114]
Test account has more than 4k transactions already.
Syncing them on each setup takes long time, let's skip it for e2e.
See Marcin's comment on this point (p1605639260045500-slack-CGGCLBN58)

**Comment by vbelolapotkov** [comment]
@kalessil reopened because client PR is not merged yet :)

**Comment by kalessil** [comment]
@vbelolapotkov, looks like it's get closed on any first closed PR. Thanks for re-opening.
