### ISSUE TITLE
Add CVC (card verification code) re-collection

### ISSUE THREAD

**Issue by allendav** [Automattic/woocommerce-payments#1120]
CVC (card verification code) re-collection: You can now use Stripe Elements to re-collect a CVC when accepting a payment with a saved card. Having the correct CVC can be a strong signal that the charge is being made by the cardholder. 

@bmccotter - I think this should be a setting, enabled by default. Although most merchants will welcome the likely reduction in fraud/disputes, some may balk at the slightly more complicated checkout experience for their buyers using saved cards. What do you think?

https://stripe.com/docs/payments/save-during-payment

**Comment by dechov** [comment]
Pertinent doc section: https://stripe.com/docs/payments/save-during-payment#web-recollect-cvc

With the conventional payment form markup (which we adapted to in https://github.com/Automattic/woocommerce-payments/pull/946), `<fieldset>` is hidden by WC core when a saved card is selected. I suppose we should dynamically mount/unmount an Element outside of that container when the saved card option changes.

Equivalent Stripe extension issue: https://github.com/woocommerce/woocommerce-gateway-stripe/issues/1380

**Comment by dechov** [comment]
This isn't nearly as straightforward as it kind of seemed to me at first glance, since I realize now that before we can show the input we need a Payment Intent, which we don't currently create until the form is submitted. Also, there isn't currently a place to put UI for saved cards – especially in the Checkout block, where saved cards are outside of the payment methods.

**Comment by haszari** [comment]
@dechov is this still a high priority? It looks like an enhancement to me (though maybe an important one).

**Comment by deepakpathania** [comment]
Removing the `priority:high` label based on this discussion: paJDYF-4rP-p2#comment-12564

**Comment by zmaglica** [comment]
Moving this issue from the Engineering review queue to Ready of prioritization queue since I think that we have enough context to work on this issue. This process the part of the Gamma backlog porter duty to reduce the number of the issues in the Engineering review column.

**Comment by RadoslavGeorgiev** [comment]
As a part of our prioritization call, we discussed this topic, and it seems like this is not a requirement, and based on @dechov's comment, it would be a full-blown project. We're closing the issue for now, please reopen it if this is a requirement.

@bmccotter @aheckler to verify whether this is a contractual requirement.
