### ISSUE TITLE
Ensure we display "card declined" to buyers when their card is declined

### ISSUE THREAD

**Issue by allendav** [Automattic/woocommerce-payments#1127]
And not merely "Something went wrong. Please contact us to get assistance."

**Comment by leonardola** [comment]
Steps to reproduce the error
- Install WooCommerce Block plugin
- Configure it following [this steps](https://docs.woocommerce.com/document/using-the-new-block-based-checkout/#section-2) 
- As a customer try to checkout with this credit card ```4000000000000002```

**Comment by a-danae** [comment]
This looks like a duplicate of [this other issue](https://github.com/woocommerce/woocommerce-gutenberg-products-block/issues/4870), isn't it? If it is, I've sent a PR for it.

**Comment by leonardola** [comment]
Yep that fixes it too. Tested it now

**Comment by leonardola** [comment]
Closing this in favor of https://github.com/woocommerce/woocommerce-gutenberg-products-block/issues/4870
