### ISSUE TITLE
Communicate to the merchant that they're eligible for Instant Deposits

### ISSUE THREAD

**Issue by DanReyLop** [Automattic/woocommerce-payments#1142]
If the merchant is eligible for Instant Deposits, but they don't have a debit card on file, we should tell them what they're missing. Maybe a notice in the Settings screen?

**Comment by jessepearson** [comment]
If we use `instant_payouts_eligible` like mentioned with this, we still do not have a way to tell if they have enabled it or not without another connection to the server. Would it be better to have `instant_payouts_status` with values of `eligible`, ineligible`, `enabled`?

Also, for the notice, I would have to believe we would allow for it to be dismissed. Once it's dismissed, should we bring it back later?

**Comment by DanReyLop** [comment]
Answered in private but to sum up:

> If we use instant_payouts_eligible like mentioned with this, we still do not have a way to tell if they have enabled it or not without another connection to the server. Would it be better to have instant_payouts_status instant_deposits_status with values of eligible, ineligible, enabled?

Once a merchant is "eligible", we want to notify them unless they have already used the feature (that won't happen for the initial time they're notified, but it will matter for the follow-up notification at +2 months or whenever we decide). We must **not** assume that just because a merchant has a debit card on file, they know what an "instant deposit" is. We could, however, customize the content of the notification if the merchant does/doesn't have a debit card on file. It doesn't seem high priority though.

> Also, for the notice, I would have to believe we would allow for it to be dismissed. Once it's dismissed, should we bring it back later?

The "notice" should instead be an Inbox Notification, as per the latest discussion here: paqDfi-1h5-p2

As for "bringing it back later", yes, we'll want to bring it back up every 3 months (that's subject to change).

> Edit: Changed to instant_deposits_status instead of instant_payouts_status to keep terminology the same within the client.

Yes, let's keep the `deposits` name everywhere, for consistency.

**Comment by jessepearson** [comment]
The logic for this is complete, there are Todos left in the branch, as we need the Title and Content for the notice, and then also the URL for the documentation for Instant Deposits. This was mentioned here: paqDfi-1h5-p2#comment-4085

https://github.com/Automattic/woocommerce-payments/blob/feature/instant-deposits/includes/notes/class-wc-payments-notes-instant-deposits-eligible.php#L26-L38

**Comment by jessepearson** [comment]
Closed via #1365 and #1571
