### ISSUE TITLE
Validation error upon adding payment method even when WCPay not selected

### ISSUE THREAD

**Issue by dechov** [Automattic/woocommerce-payments#1149]
When adding a payment method from the "My Account" front-end page, WooCommerce Payments appears to initiate payment method creation (triggering a validation error if invalid) even if it is not the selected payment method.

Upon clicking "Add payment method", an error shows up if valid card info is not provided in the WooCommerce Payments fields, even if they are hidden:

<img width="533" alt="validation-error-wrong-method" src="https://user-images.githubusercontent.com/1867547/100963783-29ed9500-34f5-11eb-92c9-2c30e1bdf022.png">

The error does not affect form submission but would still be misleading and confusing to the customer.

**How to simulate:**
- Have WC Payments installed and configured
- Have some other Credit Card Payment method installed and configured
- Log in as a customer
- Go to My account > Payment Methods
- Click on Add Payment Method
- Fill the other Credit Card Payment method
- Try to submit
- The error "Your card number is incomplete" will show up even though you did not select the WC Payments payment method

**Comment by vbelolapotkov** [comment]
I'm curious if it behaves the same way if WC Payments is selected but Stripe isn't?

**Comment by dechov** [comment]
@vbelolapotkov Just tested, and no, there's only an error if WCPay is not selected when the form is submitted.

I also managed to get this error somehow:
<img width="1048" src="https://user-images.githubusercontent.com/1867547/122621175-be1ee400-d062-11eb-8d42-b1cfc1c0fcaf.png">
When that happened, I believe had the WCPay form partially filled out, but other times when I had it partially filled, there was no error (so possibly a race condition).
