### ISSUE TITLE
Ensure Canadian Addresses are Properly Passed in Level III Data

### ISSUE THREAD

**Issue by allendav** [Automattic/woocommerce-payments#115]
Maybe we'll be lucky and no code changes will be needed. Perhaps at most verification that this work will be needed.

**Comment by jrodger** [comment]
Can we close this one in favour of https://github.com/Automattic/woocommerce-payments/issues/1099? i.e. if we disable sending level 3 data outside of the US, then this becomes a non-issue.

**Comment by vbelolapotkov** [comment]
Closing as per James's comment above.
