### ISSUE TITLE
Linkify the customer name in transaction details sreen

### ISSUE THREAD

**Issue by LevinMedia** [Automattic/woocommerce-payments#1154]
Add a link from the customer's name on the transaction details screen to the transaction list, filtered by the customer's name

<img width="1771" alt="Screen Shot 2020-12-07 at 2 23 47 PM" src="https://user-images.githubusercontent.com/4500952/101412694-e188fb00-3897-11eb-97cc-1486d58a8f7c.png">

links to

<img width="1771" alt="Screen Shot 2020-12-07 at 2 23 33 PM" src="https://user-images.githubusercontent.com/4500952/101412716-e9489f80-3897-11eb-9808-fac7f932591f.png">

**Comment by shendy-a8c** [comment]
@LevinMedia The link should open a new page or not?

**Comment by LevinMedia** [comment]
@shendy-a8c if by new page, you mean tab - no it shouldn't... just a link that renders in the same tab, with the filter applied, thanks!
