### ISSUE TITLE
localhost devolpment testing

### ISSUE THREAD

**Issue by jmarshall9120** [Automattic/woocommerce-payments#1176]
I'm trying to set up a development version of my site for testing.  Without having some localhost functionality of Payments it really stifles testing all the checkout features.   

I have woocommerce payments and jetpack set up with these configs:

define( 'WP_ENVIRONMENT_TYPE', 'development' );
define( 'WP_DEBUG', true );
define( 'JETPACK_DEV_DEBUG', true );

However I still get this if I try to setup payments in my dev box:
![image](https://user-images.githubusercontent.com/30184747/102663893-8c21d900-4136-11eb-8017-0d4945d026c7.png)

And if I try to test a checkout, the fact that it isn't setup still blocks:

![image](https://user-images.githubusercontent.com/30184747/102663989-b83d5a00-4136-11eb-9b78-a77f40d51d77.png)

![image](https://user-images.githubusercontent.com/30184747/102664108-f6d31480-4136-11eb-8e80-157125e56d81.png)

Is there a bypass for live features in woocommerce-payments?

**Comment by lukecav** [comment]
You can use this constant on the dev site.
`define( 'WCPAY_DEV_MODE', true );`
https://docs.woocommerce.com/document/payments/testing/dev-mode/#section-2

**Comment by vbelolapotkov** [comment]
@jmarshall9120 there is no way to bypass setup by setting `JETPACK_DEV_DEBUG`. As @lukecav correctly noticed wcpay dev mode have to be used for this purpose.

I'm closing the issue for now but will be happy to answer further questions if any.

**Comment by jmarshall9120** [comment]
@lukecav, @vbelolapotkov 

I've tried setting `define( 'WCPAY_DEV_MODE', true );`  Though JetPack is still, not installed I get this on attempted setup.  

![image](https://user-images.githubusercontent.com/30184747/103248795-1c270600-4921-11eb-8114-954e15c8f0cb.png)

Again, this is without JetPack even installed, which I understand from your docs is not a dependency.

**Comment by vbelolapotkov** [comment]
@jmarshall9120 yes, that's correct. Full Jetpack plugin is not required for WC Payments to work. However, WC Payments uses the same connection as Jetpack under the hood, hence same requirements are applied. To workaround the issue you need to launch an HTTP tunnel using tool like ngrok. This will allow you to access local site via public url and set up plugin in local environment. FYI, HTTP tunnel is needed only once to establish connection, after that you will be able run the plugin with localhost.
