### ISSUE TITLE
Issue when running unit tests in Docker Container

### ISSUE THREAD

**Issue by dmallory42** [Automattic/woocommerce-payments#1178]
When trying to run unit tests in Docker using the command `npm run test:php`, I encounter the following error:

<img width="560" alt="Screenshot 2020-12-21 at 18 48 32" src="https://user-images.githubusercontent.com/11770181/102811407-3317a680-43bd-11eb-9074-98b9378b08b1.png">

This happens repeatedly until the process is killed.

After doing some investigation, I believe it may be related to the change introduced in https://github.com/Automattic/woocommerce-payments/commit/65ab6d77fb57443bc1301f3829ec2521ac82f86b which updated some of the database connection logic in `install-wp-tests.sh`, after reverting to the prior version to this I was able to run the unit tests, but we'd need to investigate to confirm this.

**Comment by shendy-a8c** [comment]
I can reproduce this problem.

The solution I can think of is either:
1. To separate host and port from `default.env`, or
2. `wait_db()` in `install-wp-tests.sh` parses `$DB_HOST`.

**Comment by shendy-a8c** [comment]
cc-ing @kalessil maybe he can give quick insight before AFK. Otherwise, when he's back.

**Comment by dmallory42** [comment]
Thanks for confirming you can reproduce this @shendy-a8c!

I think your suggested solutions would work but let's see what @kalessil thinks as I don't have the context on the project yet as I've only just started looking at it.

**Comment by kalessil** [comment]
@shendy-a8c @dmallory42 : thanks for raising the issue. Replicating host parsing logic from `install_db` in `wait_db` would be the best solution for now. Working on a quick PR to unblock you.

**Comment by dmallory42** [comment]
Thanks a lot @kalessil! Happy to take a look at the PR when it's ready if you need a pair of eyes on it.

**Comment by kalessil** [comment]
No problems @dmallory42 , meanwhile (while GitHub jobs are running) would you please give a try to fix from https://github.com/Automattic/woocommerce-payments/pull/1179 ?
