### ISSUE TITLE
Add support for recurring SCA transactions

### ISSUE THREAD

**Issue by allendav** [Automattic/woocommerce-payments#118]
including 3D Secure 1 and 2 transactions.

Update ( @dwainm ) Make sure we  send metadata with intent as per:
https://github.com/woocommerce/woocommerce-gateway-stripe/blob/4.3.1/includes/abstracts/abstract-wc-stripe-payment-gateway.php#L352-L365

**Comment by thenbrent** [comment]
Should this be closed now that https://github.com/Automattic/woocommerce-payments/issues/2002 has been created?

**Comment by allendav** [comment]
Probably. This issue seems broader in scope, as it was meant to be epic-like - i.e. it encompasses not just renewals, but I suspect the work needed for #2002 will cover the same territory.

**Comment by dwainm** [comment]
I'll add it to the epic just in case, but I think it will be closed in any case.

**Comment by dwainm** [comment]
cc @DanReyLop

**Comment by DanReyLop** [comment]
Yes, it will be covered by #2002 

> Make sure we send metadata with intent as per...

We don't need that. The metadata we were including was there to allow the merchant to better identify a transaction in the Stripe Dashboard as being part of a subscription. That's only useful if the merchant has to do the transaction management in the Stripe Dashboard. It doesn't apply to WCPay.

**Comment by dwainm** [comment]
In that case, I'll close it.
