### ISSUE TITLE
Handle when a recurring payment fails

### ISSUE THREAD

**Issue by allendav** [Automattic/woocommerce-payments#119]
and the subscriber has to "return to session" to correct it

See also (should build upon) https://github.com/Automattic/woocommerce-payments/milestone/7

**Comment by jessy-p** [comment]
@Automattic/helix Could you test and close if already handled?

**Comment by haszari** [comment]
@jessy-p I'm not clear what the specific issue / enhancement is here. Perhaps this is a stale task, and we can just close. If there's a specific bug or enhancement then it should come up via support (etc) and can be prioritised as normal.

If there's specific testing you'd like us to do before closing let me know :)

**Comment by shendy-a8c** [comment]
I think this issue can be closed.

I did a quick test to fail recurring payment and confirm customer can 'return to session' to correct the failed payment.

How I tested the flow:
1. Purchase a subscription product with a valid payment, 4242424242424242.
2. Go to My Account > Subscriptions and update the payment for the newly purchased subscription with a 'Decline after attaching' payment I get from https://stripe.com/docs/testing#declined-payments, 4000000000000341.
3. Edit the subscriptions from admin and 'Process Renewal'.
4. Renewal will fail.
5. An 'payment failed' email will be sent to the customer. In it, it says 'To reactivate the subscription now, you can also log in and pay for the renewal from your account page: Pay Now »'. Clicking on the 'Pay Now' will bring the customer to a login form and checkout form to input a new payment.
