### ISSUE TITLE
Incorrect currency could be shown on order notes added outside customer session

### ISSUE THREAD

**Issue by dechov** [Automattic/woocommerce-payments#1200]
[This is a gap in the _customer currency support_ feature set, not a bug in any current release.]

The [`capture_charge`](https://github.com/Automattic/woocommerce-payments/blob/23636872b1df929d3e58ab33a7de4064a617c64f/includes/class-wc-payment-gateway-wcpay.php#L1076-L1163) and [`process_refund`](https://github.com/Automattic/woocommerce-payments/blob/23636872b1df929d3e58ab33a7de4064a617c64f/includes/class-wc-payment-gateway-wcpay.php#L744-L803) gateway methods (as well as the [refund failure webhook handler](https://github.com/Automattic/woocommerce-payments/blob/23636872b1df929d3e58ab33a7de4064a617c64f/includes/admin/class-wc-rest-payments-webhook-controller.php#L184-L196) and [subscription renewal hook](https://github.com/Automattic/woocommerce-payments/blob/23636872b1df929d3e58ab33a7de4064a617c64f/includes/compat/subscriptions/class-wc-payment-gateway-wcpay-subscriptions-compat.php#L143-L158)) use `wc_price` for formatting but do not supply a currency, which can result in incorrect formatting depending on the order currency:

<img width="308" src="https://user-images.githubusercontent.com/1867547/104542590-cc6b5e80-55f1-11eb-8697-0e4de42afb63.png">
<img width="308" src="https://user-images.githubusercontent.com/1867547/104542585-cb3a3180-55f1-11eb-8e70-d33aa6b117ad.png">
(For that latter case, I'd changed the currency on the admin user session's front-end using the Multi-currency extension.)

**Comment by dechov** [comment]
Haven't tested but this issue is likely to also be present in the Stripe extension, based on glancing at the refund code [here](https://github.com/woocommerce/woocommerce-gateway-stripe/blob/09e2c2871ceb48b34af90b0dad212d08d8d1fe2a/includes/abstracts/abstract-wc-stripe-payment-gateway.php#L899-L912).

**Comment by shendy-a8c** [comment]
@dechov Do I just have to pass order's currency to `wc_price()`, or is there anything else I need to consider?

**Comment by dechov** [comment]
@shendy-a8c Yup, that's all we need AFAIK. There's an edge case where the order currency is changed (via a UI provided by the Multi-currency extension, for instance), and then the currency in the order notes could be incorrect, but I'm not sure how much effort it would be worth to accommodate this case.

**Comment by shendy-a8c** [comment]
@dechov I try to handle the case where order currency is changed later on by some plugin (for example Multi-currency) by hooking before order is saved and when order currency is present, I set the original value to certain meta data.
That serves this issue right. However, I see another problem that might be out of the scope of this issue.

This is how the order that was originally created in EUR but then changed to USD with Multi-currency from the order admin page. Order note is correct but the order line items, currency within the refund buttons, etc are showing 'current' order currency.
<img width="1218" alt="Screen Shot 2021-01-24 at 03 35 07" src="https://user-images.githubusercontent.com/73803630/105613631-48d21e80-5df6-11eb-8399-63d9da103f34.png">


The plugin clearly states this though.
<img width="687" alt="Screen Shot 2021-01-24 at 03 40 00" src="https://user-images.githubusercontent.com/73803630/105613628-466fc480-5df6-11eb-970a-bd7ca3d47a0b.png">
