### ISSUE TITLE
Transactions list: Display customer currency conversion alongside amount

### ISSUE THREAD

**Issue by dechov** [Automattic/woocommerce-payments#1202]
Depends on 498-gh-Automattic/woocommerce-payments-server

- Show an icon next to the amount when the customer currency is different
- When it's hovered, show the customer currency (and amount, optionally)

<img width="214" alt="transactions-list" src="https://user-images.githubusercontent.com/1867547/104567861-4a912a80-561d-11eb-8fcb-5ffcba6c1fdc.png">

_[Edited to extract advanced filter out into #1278]_

**Comment by dechov** [comment]
@LevinMedia Should the filter dropdown contain all currencies the merchant is ever likely to need – as in, a comprehensive list of supported presentment currencies?

**Comment by LevinMedia** [comment]
The drop down filter should only list currencies that have been used by customers on the store - IE there's a transaction record of such and such a currency.

**Comment by dechov** [comment]
The basic task then is to query all of the orders for distinct currencies, either on page load or when the filter is added. I'm not sure if there's any precedent for the filters UI in that component being dynamically computed (and depending on other filters that have been added) though it seems like it should be _possible_ via the [`onAdvancedFilterAction` prop](https://github.com/woocommerce/woocommerce-admin/blob/d830378e8ca783449c739ab5b770fa819542ade4/packages/components/src/filters/index.js#L192-L195).

We may want to track the filter in a separate issue from the indicator + tooltip in the list – @LevinMedia would it be considered a blocker for initial customer currency support? cc/FYI @kalessil

**Comment by dechov** [comment]
Split the advanced filter out into its own issue: https://github.com/Automattic/woocommerce-payments/issues/1278
