### ISSUE TITLE
Trim refund reason to a max of 500 characters?

### ISSUE THREAD

**Issue by aheckler** [Automattic/woocommerce-payments#1206]
See this issue over in the Stripe repo: 

https://github.com/woocommerce/woocommerce-gateway-stripe/issues/1446 

WC Pay seems like it might have the same problem.

It's hard to be certain though, since I'm unable to locate the Stripe account we're using on our WC Pay test site, so I can't check the logs.

**Comment by jessepearson** [comment]
At present we are only sending the charge id and the amount to Stripe for the refund, the reason is not included.
https://github.com/Automattic/woocommerce-payments/blob/2.2.0/includes/wc-payment-api/class-wc-payments-api-client.php#L206-L212

Closing for now.
