### ISSUE TITLE
WooCommerce plugin installation fails while preparing dev environment

### ISSUE THREAD

**Issue by dmvrtx** [Automattic/woocommerce-payments#1226]
**Goal**

Prepare WooCommerce environment for development

**Description**

Environment preparation script `bin/docket-setup.sh` fails while preparing a container environment with the following error:

```
Enabling WordPress debug flags
Enabling WordPress development environment (enforces Stripe testing mode)
Updating permalink structure
Installing and activating WooCommerce...
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! woocommerce-payments@1.8.0 up: `docker-compose up --build --force-recreate -d && ./bin/docker-setup.sh`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the woocommerce-payments@1.8.0 up script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

**Steps to reproduce:**

 1. Clone this repository
 2. Install dependencies with `npm install && composer install`
 3. Build JS: `npm run build:client && npm run build`
 4. Try to start-up containers: `npm run up`
 
**Workaround:**

 1. Open bash inside the container with `docker exec -it woocommerce_payments_wordpress bash`
 2. Install required plugins manually:
 ```bash
 wp plugin install woocommerce --activate --allow-root
 wp theme install storefront --activate --allow-root
 wp plugin install wordpress-importer --activate --allow-root
 ```
 3. Restore proper user/group ownership with `chown -R www-data:www-data .`
 4. Exit the container environment
 5. Run `npm run up` again

This will lead to another error:

```
Installing dev tools plugin...
fatal: could not create work tree dir 'docker/wordpress/wp-content/plugins/woocommerce-payments-dev-tools': Permission denied
WARN: Could not access the dev tools repository. Skipping the install.
```

Workaround here is to clone https://github.com/Automattic/woocommerce-payments-dev-tools and place it contents under `docker/wordpress/wp-content/plugins/woocommerce-payments-dev-tools`. Note, that in the end directory with its contents should also belong to `www-data:www-data`.

My hunch is something going wrong with the users and groups between a host and a container.

**Comment by jrodger** [comment]
> My hunch is something going wrong with the users and groups between a host and a container.

I think you're probably right.

Unfortunately, I've not seen this particular error before. What OS and version of Docker are you running?

**Comment by dmvrtx** [comment]
I am using Ubuntu 20.04 as a host and Docker version 20.10.2, build 2291f61 (from docker.com repository as described in https://docs.docker.com/engine/install/ubuntu/)

**Comment by kalessil** [comment]
Adding a link to related discussion in Slack as well: p1611041020081200-slack-CGGCLBN58

**Comment by htdat** [comment]
I am having the same issue today. I am using Mac OS Big Sur and Docker Desktop 2.5.0.1 (49550)
Here is my debug.log right after running `npm run up`

```
PHP Warning:  An unexpected error occurred. Something may be wrong with WordPress.org or this server&#8217;s configuration. If you continue to have problems, please try the <a href="https://wordpress.org/support/forums/">support forums</a>. (WordPress could not establish a secure connection to WordPress.org. Please contact your server administrator.) in /var/www/html/wp-includes/update.php on line 175

PHP Warning:  An unexpected error occurred. Something may be wrong with WordPress.org or this server&#8217;s configuration. If you continue to have problems, please try the <a href="https://wordpress.org/support/forums/">support forums</a>. (WordPress could not establish a secure connection to WordPress.org. Please contact your server administrator.) in /var/www/html/wp-admin/includes/plugin-install.php on line 183
``` 

Sounds like an issue with SSL or at least the network issue inside the WordPress container, or the way we construct `cli` in `bin/docker-setup.sh`: 

https://github.com/Automattic/woocommerce-payments/blob/84d0801b545ad4531527b358ed7c32311a61be64/bin/docker-setup.sh#L19-L26

Slack convo p1623818353277300-slack-C01BPL3ALGP

**Comment by leonardola** [comment]
Is this still relevant? We've been using docker for a while now

**Comment by dmvrtx** [comment]
It might be closed, but as a remark for posterity: issue seems to be related to user groups. When running setup scripts under Linux one should be in the `www-data` and `docker` groups for it to work properly. Maybe it is worth adding this check to the setup script.

**Comment by kalessil** [comment]
Closing in favour of https://github.com/Automattic/woocommerce-payments-server/issues/4234 (cross-linked)
