### ISSUE TITLE
JS tests: Enable running JS tests against different versions of npm packages

### ISSUE THREAD

**Issue by v18** [Automattic/woocommerce-payments#1232]
We'd like to be able to run the JS tests using different versions of various `@wordpress/*` packages, including the current version and the version that will be used in the next WordPress core release.

**Comment by jessy-p** [comment]
We have E2E tests fetching the latest version available. When we do update manually to the latest version, we have manual QA testing. Closing this as after prioritization discussion, we decided not to automate this at this time
