### ISSUE TITLE
E2E: Use the latest Gutenberg plugin

### ISSUE THREAD

**Issue by v18** [Automattic/woocommerce-payments#1234]
Similar to the other [plugins we install like woocommerce](https://github.com/Automattic/woocommerce-payments/blob/40afcc1c23dc9037b8fc9c170355bafc7bcd2d4e/tests/e2e/env/setup.sh#L132), let's also install the latest gutenberg plugin. Installing the latest version of the gutenberg plugin will use newer versions of the `@wordpress/*` libraries, ahead of their use in WordPress core. This will help with testing while using the upcoming library changes.

If an RC version is available, let's also test against the RC version.

**Comment by ismaeldcom** [comment]
Already taken care in #1262, I'll close this.
