### ISSUE TITLE
Fix Puppeteer Issue with E2E tests

### ISSUE THREAD

**Issue by dmallory42** [Automattic/woocommerce-payments#1245]
It seems that occasionally, the E2E tests can fail with the following error message:

`Error: Cannot find module 'puppeteer'`

This is seemingly related to https://github.com/WordPress/wordpress-develop/pull/347#discussion_r446089730 and can be fixed by adding the alias used by `wp-scripts`. Upon doing this, a further issue occurs related to puppeteer not being able to find the correct build of Chromium. The only way to then resolve this and get the E2E tests working is to delete `package-lock.json` and `node_modules/` and re-install with `npm ci`, followed by `npm install`. 

We should look into implementing this fix, which should prevent this issue from happening again: https://github.com/WordPress/wordpress-develop/pull/347/commits/a931153db233bad5acf779eac183bb303a922bd5

**Comment by alefesouza** [comment]
I couldn't replicate it on my machine, I believe that it was fixed and the issue wasn't closed, could someone else test it?

**Comment by jessy-p** [comment]
Yes, this seems to be working fine now. Closing
