### ISSUE TITLE
Support non-USD currencies in fees on the settings screen

### ISSUE THREAD

**Issue by jrodger** [Automattic/woocommerce-payments#1257]
Ensure fees with non-USD fixed rates are displayed correctly on the WCPay settings page (including discount fee structures).

**Comment by jrodger** [comment]
Did you re-open this because of the "including discount fee structures" part @vbelolapotkov?

**Comment by vbelolapotkov** [comment]
> Did you re-open this because of the "including discount fee structures" part @vbelolapotkov?

This was automated action by ZH because of the link with server PR. I think it's fine to keep it open for a bit, server part should be ready soon.

**Comment by vbelolapotkov** [comment]
Closing since server part is deployed as well.
