### ISSUE TITLE
Handle accounts with multiple settlement currencies

### ISSUE THREAD

**Issue by jrodger** [Automattic/woocommerce-payments#1258]
This will likely get broken down into some child issues, but for now:

In many countries outside of the US it’s possible to have multiple balances on a Stripe account in different currencies.

Stripe handle this by only showing one currency at a time and giving the merchant a way to toggle between all their currencies. I think something similar would work for us.

Apart from the UI considerations, we also need to look at:

- How we group transactions into future payouts
- Providing an estimated payout for every settlement currency

**Comment by dechov** [comment]
> Stripe handle this by only showing one currency at a time and giving the merchant a way to toggle between all their currencies.

From what I've seen, that's true for some aggregate figures (e.g. [Home](https://cloudup.com/iLbU6XwnCne), [Balances](https://cloudup.com/irl4UosPYUN)) but not list views (e.g. [Payouts](https://cloudup.com/ifsqUQ6k8X0), [All transactions](https://cloudup.com/i9l_WZgzXsW)).

**Comment by jrodger** [comment]
> From what I've seen, that's true for some aggregate figures (e.g. [Home](https://cloudup.com/iLbU6XwnCne), [Balances](https://cloudup.com/irl4UosPYUN)) but not list views (e.g. [Payouts](https://cloudup.com/ifsqUQ6k8X0), [All transactions](https://cloudup.com/i9l_WZgzXsW)).

Yeah, that's right. They get around some of the issues we have by not having summary sections on the tables that have a mix of currencies.

**Comment by thenbrent** [comment]
Removing `needs design` label from this issue now as designs are now available in paJDYF-13A-p2 with an i2 of the Overview screen here paJDYF-15w-p2.

**Comment by jrodger** [comment]
This issue has been broken down into smaller ones, I don't think there's much value in keeping it open.
