### ISSUE TITLE
Migrate the deposits data layer to TypeScript

### ISSUE THREAD

**Issue by reykjalin** [Automattic/woocommerce-payments#1273]
Child of #1249

Migrate everything in `client/data/deposits` to TypeScript.

Considered blocked until #1230 has been merged.

See #1198 for some prior art on how the migration can be done. Keep in mind that PR was a test, so some things may need to change.

**Comment by jessy-p** [comment]
This issue impacts Deposits, Disputes, Capital Loans, so assigning to Helix (based on team responsibilities Pc2DNy-3z-p2) @haszari. Assigning as part of Gamma Triage process PcreKM-yM-p2.

Tagging as part of re-evaluating older issues in the backlog, please have a look and close if no longer relevant.

**Comment by haszari** [comment]
@Jinksi  - what's the status of our deposits front end code re TypeScript and the goals of this issue? Do you think this is worth keeping open and/or prioritising, or is there a specific aspect we should spin off and prioritise?

**Comment by Jinksi** [comment]
The `hooks.ts` file has been migrated to TS, but nothing else. It makes sense that the hooks were migrated first, as they are the primary point of interaction with the data layer.

<img width="253" alt="image" src="https://github.com/Automattic/woocommerce-payments/assets/3147296/d077e972-9b0f-4442-acf3-5c22654b3912">

I think we should move this to our backlog as low priority, as it will improve code quality and consistency.

Note in #1249, there is an issue for migrating the disputes data as well, which also has `hooks.ts` but nothing else migrated. I'll move it to the backlog as well.

**Comment by haszari** [comment]
> I think we should move this to our backlog as low priority, as it will improve code quality and consistency.

How do you think we should prioritise it? How much time do you think would be needed to close this issue? 

How long (months) would you leave this open if we didn't get to it due to other priorities?

**Comment by Jinksi** [comment]
> How do you think we should prioritise it?

Low-priority, as it is not user-facing but is a code quality improvement to help us write fewer bugs. I'd consider it similar in priority to code-quality issues such as #8047 and #7085.

> How much time do you think would be needed to close this issue?

This may be a small-medium issue to work on since it is self-contained and simple to test/review as no functional changes are expected. I'd estimated 0.5 - 1 day of dev capacity.

> How long (months) would you leave this open if we didn't get to it due to other priorities?

💭 I think it remains relevant unless the code is deleted (e.g. shift to react-query 😉) so it should remain open until it is resolved, right?

**Comment by haszari** [comment]
Thanks – happy to keep it around for now.

> Low-priority, as it is not user-facing but is a code quality improvement to help us write fewer bugs. I'd consider it similar in priority to code-quality issues such as https://github.com/Automattic/woocommerce-payments/issues/8047 and https://github.com/Automattic/woocommerce-payments/issues/7085.\

Interestingly, those issues are both much more focused and actionable - fix a specific issue in the code.

> > How long (months) would you leave this open if we didn't get to it due to other priorities?

> 💭 I think it remains relevant unless the code is deleted (e.g. shift to react-query 😉) so it should remain open until it is resolved, right?

Personally I would like to avoid long-lived stale issues. This is an aspirational goal.

**Comment by haszari** [comment]
@Jinksi I'm going to close this, we're unlikely to prioritise TypeScript adoption over merchant-facing fixes/problems. However, this code can still be improved by migrating to TypeScript, e.g. when next someone touches data layer.

If it's helpful for you to keep this open, feel free to reopen 😁
