### ISSUE TITLE
Migrate the disputes data layer to TypeScript

### ISSUE THREAD

**Issue by reykjalin** [Automattic/woocommerce-payments#1274]
Child of #1249

Migrate everything in `client/data/disputes` to TypeScript.

See #1198 for some prior art on how the migration can be done. Keep in mind that PR was a test, so some things may need to change.

**Comment by Jinksi** [comment]
> [!NOTE]  
> Moving this to the Helix backlog as it is a disputes-related issue.

**Comment by haszari** [comment]
Shifting this to disputes, since it will benefit disputes.

**Comment by haszari** [comment]
@Jinksi I'm going to close this, we're unlikely to prioritise TypeScript adoption over merchant-facing fixes/problems. However, this code can still be improved by migrating to TypeScript, e.g. when next someone touches data layer.

If it's helpful for you to keep this open, feel free to reopen 😁
