### ISSUE TITLE
webhook controller temporary variable overwritten by tos controller (copypasta)

### ISSUE THREAD

**Issue by allendav** [Automattic/woocommerce-payments#1282]
Probably not a problem, since the variable appears to only be used long enough to register the routes, but should probably still be fixed :)

https://github.com/Automattic/woocommerce-payments/blob/98ab3e60077be7aac1d468575c894d4e3dd81be1/includes/class-wc-payments.php#L468-L473

**Comment by vbelolapotkov** [comment]
Thanks for spotting it @allendav !
