### ISSUE TITLE
Address deprecation warning for WordPressExternalDependenciesPlugin use in webpack config

### ISSUE THREAD

**Issue by reykjalin** [Automattic/woocommerce-payments#1287]
It [was] necessary to update `@wordpress/dependency-extraction-webpack-plugin`, which introduced some soon-to-come deprecations that I'm not sure how to fix. The warning is visible when running webpack, e.g. via `npx webpack`.

I think we need to change how we use `WordPressExternalDependenciesPlugin` in `webpack.config.js`, I'm just not sure what changes are required.

_Originally posted by @reykjalin in https://github.com/Automattic/woocommerce-payments/pull/1263#discussion_r569644261_

**Comment by leonardola** [comment]
@reykjalin When I run ```npx webpack``` I don't get any deprecation warnings. Only warnings that some components were not found which is related to ```@woordpress/components``` or are does the warnings you are referring to?

Does the warnings still popup to you?
Can you paste here what is being logged? just so I know I am look at the right thing

**Comment by leonardola** [comment]
I talked to @reykjalin and the problem does not seem to happen anymore. Probably some update fixed the warnings described. Closing the issue for now
