### ISSUE TITLE
Create E2E test for covering integration of WC Payments and WooCommerce Subscriptions.

### ISSUE THREAD

**Issue by shendy-a8c** [Automattic/woocommerce-payments#1296]
This issue is a continuation of #1185. Focus is to create integration test between wcpay and WooCommerce Subscriptions.

### TODO

- [ ] Create E2E test covering integration scenario below.

### Test scenario

Steps used to reproduce issue in #1185 (issue was fixed already):

1. Purchase subscription product.
2. Go to My account > Add one more payment method.
3. Go to My account > Subscription > Purchased subscription.
4. Try to change payment method to saved on step 2.
5. Success message is displayed but payment method is not changed.

**Comment by haszari** [comment]
@shendy-a8c @vbelolapotkov if you remember the details here – would you mind fleshing out the description and title so we have a clear outcome/goal? This issue is very open ended so hard to prioritise. 

@shendy-a8c Are there any e2e tests running with WCPay + WC Subscriptions right now? If not, maybe we can refocus this issue on getting one test working. For example the simplest WCPay + WC Subscriptions flow, or the most critical one ([shopper purchase subscription](https://github.com/Automattic/woocommerce-payments/wiki/Testing-instructions-for-critical-flows#purchase-subscription-product)?).

**Comment by vbelolapotkov** [comment]
@haszari updated title and description with more details from #1185

Only tests need to be created because the issue itself was fixed.

> Are there any e2e tests running with WCPay + WC Subscriptions right now? 

IIRC there were some tests for this. I think @achyuthajoy has the most fresh understanding of our E2E tests today.

**Comment by haszari** [comment]
Thanks @vbelolapotkov ! Looks like this is [WC Subscriptions integration > Change payment method to saved card](https://github.com/Automattic/woocommerce-payments/wiki/Testing-instructions-for-critical-flows#change-payment-method-to-saved-card) flow.

**Comment by vbelolapotkov** [comment]
Yes, looks so.

**Comment by htdat** [comment]
@shendy-a8c and @Automattic/quark - could have a look if we should still do this issue? 

Based on https://github.com/Automattic/woocommerce-payments/issues/1296#issuecomment-1193391119, I think it would be closed now? 

--- 

FYI. I am doing triage as part of Gamma Triage process PcreKM-yM-p2.

**Comment by shendy-a8c** [comment]
@htdat I don't think what this issue require is implemented yet.

https://github.com/Automattic/woocommerce-payments/issues/1296#issuecomment-1193391119 mentioned about the manual testing flow to change payment of a specific subscription.

![Screenshot 2023-07-31 at 12 00 11](https://github.com/Automattic/woocommerce-payments/assets/73803630/60ada248-91f0-4c21-b5df-d5a256bbde07)


Also covered in this [e2e test](https://github.com/Automattic/woocommerce-payments/blob/develop/tests/e2e/specs/subscriptions/shopper/shopper-subscriptions-manage-payments.spec.js).


This issue is to create e2e test by selecting a payment that is added from slighting different step.

![Screenshot 2023-07-31 at 12 02 25](https://github.com/Automattic/woocommerce-payments/assets/73803630/63c9f375-2180-4131-a327-3334b04ee145)

and then select the newly added payment to be used by a purchased subscriptions.

The idea to have an e2e test for it is to catch when that flow is buggy like when it happened with https://github.com/Automattic/woocommerce-payments/issues/1185.

**Comment by zmaglica** [comment]
@shendy-a8c can we close this issue?

**Comment by htdat** [comment]
@shendy-a8c - I am closing this issue. Feel free to re-open it if needed.
