### ISSUE TITLE
Disambiguate between currencies with same symbol

### ISSUE THREAD

**Issue by dechov** [Automattic/woocommerce-payments#1301]
There are some cases of currencies that share symbols (e.g. `$` for USD, CAD, MXN, AUD, and others) which will be ambiguous if we rely on numeric formatting alone. We should **show the currency code** when the currency could be (or is likely to be) unclear.

Since the designs do not currently have the code annotating _every_ currency amount, we may want to attempt to avoid the most basic solution of just showing the code everywhere. (As discussed in p1610484625305000/1610483268.300900-slack-CGGCLBN58) we could consider providing this as an option, or trying to detect when currencies with the same symbol are present in the same context, but it might be a good compromise to just always show the code whenever it doesn't match the _store currency_.

We are already showing the currency code in some cases (always in the Payment details header and possibly others, and as a fallback when the formatting is unknown) – we could instead only show the code when necessary, or we could pass an extra prop to the `formatCurrency` to flag that it should force displaying the currency code. (Note that the payment details header has extra visual structure beyond string formatting, however.)

**Comment by dechov** [comment]
See also https://github.com/Automattic/woocommerce-payments/issues/1389

**Comment by jessy-p** [comment]
Most of this has been addressed in https://github.com/Automattic/woocommerce-payments/pull/2395, and the only open issue linked here is [Checkout total shows EUR alongside the sign](https://app.zenhub.com/workspace/o/automattic/woocommerce-payments/issues/4046) which is being prioritized and worked on separately. So, closing this issue.
