### ISSUE TITLE
Sentence fragment in dev mode setup doc

### ISSUE THREAD

**Issue by allendav** [Automattic/woocommerce-payments#1331]
In https://docs.woocommerce.com/document/payments/testing/dev-mode/#section-2 we have:

> Note: Dev Mode must be enabled before completing the account set up and verification process in order to create a test account. If it is enabled after, the

the suspense is killing me :)

**Comment by thenbrent** [comment]
Fixed, thanks for flagging. Though I think the conclusion will be disappointing for you @allendav - I just deleted the part: `If it is enabled after, the`. :)
