### ISSUE TITLE
Card number and Expiration date field not visible in the Checkout page

### ISSUE THREAD

**Issue by Spacepol** [Automattic/woocommerce-payments#1338]
# Issue
The **Card number** and **Expiration date** field don’t have an outline to differentiate the input space. This issue is found across all themes. 

![Frame 119](https://user-images.githubusercontent.com/69914963/107649528-50018500-6c5c-11eb-9488-86053327372a.png)
![Frame 118](https://user-images.githubusercontent.com/69914963/107649533-5132b200-6c5c-11eb-85bb-acdfbe0987ca.png)

## Solution
We should show an input rectangle for the card number and the expiration date. 

<img width="1039" alt="Screen Shot 2021-02-15 at 11 50 44" src="https://user-images.githubusercontent.com/69914963/107960966-0d091f80-6f84-11eb-9952-d7c35f70497b.png">

**Comment by LevinMedia** [comment]
Thanks for noting this @Spacepol I'm going to close this issue since we're already tracking it here: https://github.com/Automattic/woocommerce-payments/issues/1152
