### ISSUE TITLE
Create Overview Page

### ISSUE THREAD

**Issue by jrodger** [Automattic/woocommerce-payments#1339]
Add a new "Overview Page" to the top level navigation.

The page will contain the account status information currently found on the settings page, as well as balance and deposit details for all the merchant's settlement currencies (details paJDYF-13A-p2).

This page should be the default page show when clicking on the "Payments" menu option. Where before we might have sent a merchant to the settings page after onboarding, we should now send them here.

The existing "Deposit schedule" information on the deposits page should also be removed.

**Comment by jrodger** [comment]
Some updated designs and MVP suggestions in paJDYF-15w-p2

**Comment by vbelolapotkov** [comment]
@dmvrtx @jrodger I see this one is marked as large. Can we cut into smaller chunks and ship them one by one for the sake of smaller PRs? Creating empty page and hiding it behind the flag could be a first PR.

**Comment by dmvrtx** [comment]
> Creating empty page and hiding it behind the flag could be a first PR.

Sounds good to me. Also a good task to identify required steps in FE infra. Will work on it.

**Comment by vbelolapotkov** [comment]
Yes, sounds good to me

**Comment by vbelolapotkov** [comment]
Updated the size and estimate on the issues since its scope was split into smaller pieces
