### ISSUE TITLE
Smarter error messages for faster troubleshooting

### ISSUE THREAD

**Issue by jessepearson** [Automattic/woocommerce-payments#1346]
I mentioned to @DanReyLop in #1335 that if an error message could check to see if logging was enabled, it could help speed up the process of merchants and support troubleshooting issues. 

If the component could test to see if logging is enabled, it could direct/link the merchant to enable logging and then try X again. Once X is done again, the error could direct/link them to either the logs page, or the current log for review.

This speeds up the process since some merchants may understand what needs to be done from the logs, but for those who don't, the logs will be ready to go for support to assist.

**Comment by a-danae** [comment]
Looks like this needs to be scoped and detailed further, p1632859274093000-slack-C0208C3BXHP . I'm removing myself as the assignee in the meantime.

**Comment by vbelolapotkov** [comment]
I'm moving this into engineering excellence backlog as a project idea.

**Comment by haszari** [comment]
👀 because I'm not clear on the goal / problem / solution / idea. Needs fleshing out.

**Comment by dwainm** [comment]
We'll close this due to no action or a clear list of errors requiring attention.  If there are still known "unactionable" errors, we should open an issues for them with a link to where it occurs.
