### ISSUE TITLE
Report correct currency on discount volume progress bar and associated text

### ISSUE THREAD

**Issue by jrodger** [Automattic/woocommerce-payments#1376]
We correctly show the currency for fees on the settings page. The last outstanding part is adding the same functionality to the volume limit progress bar.

![image](https://user-images.githubusercontent.com/686419/110126140-053adf00-7dbc-11eb-89bf-5600a6f5465d.png)

The first line is correct, but the values on the progress bar and the text below need updating.

**Comment by naman03malhotra** [comment]
Accidently solved it with https://github.com/Automattic/woocommerce-payments/pull/1966
Ref: https://github.com/Automattic/woocommerce-payments/pull/1966#issuecomment-851472618

Thanks to @dmvrtx for noticing this. 😄
