### ISSUE TITLE
Save customer payment methods to platform for future purchases

### ISSUE THREAD

**Issue by dechov** [Automattic/woocommerce-payments#14]
Support saving customers' payment method references in the store, choosing among them at checkout, and managing them.

Look into integrating with WooCommerce core's accommodations for "token" management [[wiki](https://github.com/woocommerce/woocommerce/wiki/Payment-Token-API)], and the token class in particular [[doc](https://docs.woocommerce.com/wc-apidocs/class-WC_Payment_Token_CC.html)] (not to be confused with tokenization of card details, tracked in https://github.com/Automattic/woocommerce-payments/issues/11).

_(Not currently in v1 scope)_

**Comment by vbelolapotkov** [comment]
Not sure if the issues is still relevant. Asked internally here: p1635781961051200-slack-C022WMN88KG

**Comment by vbelolapotkov** [comment]
Closing as discussed in the slack thread above.
