### ISSUE TITLE
Add performance metrics for API calls

### ISSUE THREAD

**Issue by coderkevin** [Automattic/woocommerce-payments#140]
Right now, we've got a system that goes 3 servers deep for each API call:

`browser -> self-hosted site -> wordpress.com server -> stripe server`

This will affect performance, but we're not exactly sure how much. We need a way to measure these round-trip times. It would be ideal to measure these from the browser itself if possible, but barring that, measuring from wordpress.com server would be acceptable as well. Regardless the data will need to be available in kibana for analysis.

**Comment by vbelolapotkov** [comment]
Tracking is available on the server side.
