### ISSUE TITLE
Deposit information block for the Account Overview page

### ISSUE THREAD

**Issue by dmvrtx** [Automattic/woocommerce-payments#1410]
Dervied from #1339 

Implement data retrieval and display for deposit information block (details paJDYF-18j-p2 ). There may be multiple blocks, one for each settlement currency.

Feature toggle is located in `is_account_overview_page_enabled` method of `WC_Payments_Admin` class.

**Comment by kalessil** [comment]
As part of this ticket, we need to turn off/drop deposit summary rendering on the deposits list page - so we have graceful migration.

**Comment by LevinMedia** [comment]
Noting that the current deposit overview UI has lost some functionality along the line - the designs call additional details below summary number. 

**Current experience**

<img width="1056" alt="Screen Shot 2021-04-21 at 10 01 52 PM" src="https://user-images.githubusercontent.com/4500952/115658262-527ffb00-a2ed-11eb-8391-c99bbb08c1ff.png">

**Designs for the current experience**

<img width="991" alt="Screen Shot 2021-04-21 at 10 05 28 PM" src="https://user-images.githubusercontent.com/4500952/115658496-b9051900-a2ed-11eb-8617-8b587dd73849.png">


**Designs for the overview screen**

<img width="595" alt="Screen Shot 2021-04-21 at 10 06 13 PM" src="https://user-images.githubusercontent.com/4500952/115658550-d3d78d80-a2ed-11eb-9724-ec05817bee8b.png">

**Comment by jrodger** [comment]
> Noting that the current deposit overview UI has lost some functionality along the line - the designs call additional details below summary number.

I looked into this quickly, as far as I can tell we haven't changed anything in our code. So we're still passing the `SummaryNumber` component the same props. The next thing to check would be whether the behaviour of the `SummaryNumber` component has changed due to an upgrade of `@woocommerce/components` or similar.

**Comment by jrodger** [comment]
Nothing here that the dates have been added back by https://github.com/Automattic/woocommerce-payments/pull/1611
