### ISSUE TITLE
Enable Account Overview page

### ISSUE THREAD

**Issue by dmvrtx** [Automattic/woocommerce-payments#1412]
Depends on completion of #1409, #1410, #1411

This page should become the default page show when clicking on the "Payments" menu option. Where before we might have sent a merchant to the settings page after onboarding, we should now send them here.

The existing "Deposit schedule" information on the deposits page should also be removed.

Feature toggle is located in `is_account_overview_page_enabled` method of `WC_Payments_Admin` class.

*Note:* `wc_admin_register_page` tries to be helpful and if a top-level item in the sub-menu has a slug that is different from the parent (top level menu item) it would create an entry in the sub-menu duplicating the parent. Existing code avoids it because top level link is directing to the Deposits page. When Overview page becomes a main entry point top level link should be updated as needed to avoid sub-menu items duplication.

**Comment by naman03malhotra** [comment]
>Where before we might have sent a merchant to the settings page after onboarding, we should now send them here.
Can we confirm if this behavior needs to be shipped in this PR?
cc @LevinMedia @vbelolapotkov @RadoslavGeorgiev

**Comment by LevinMedia** [comment]
@naman03malhotra it would be preferable, as the account status has moved from the settings to the overview page. 

That said, it's not in every case that the merchant is directed back to the settings screen after completing onboarding (or in this case, the overview screen). This only happens if the merchant kickoff the activation flow from the preview screen. 

If they kick off the activation flow from the onboarding task list, they're returned to the onboarding task list when activation is complete.

**Comment by naman03malhotra** [comment]
>it would be preferable, as the account status has moved from the settings to the overview page.

Hi @LevinMedia, I have implemented this functionality. Please test it at your convenience.

Also, there are some common components between the settings page and the new overview page, please let me know what all needs to removed from the settings page? If at all.

IMO, from the settings page we can remove the following common components:
- Account status
- Base fee

cc @RadoslavGeorgiev @vbelolapotkov

**Comment by naman03malhotra** [comment]
Hi @becdetat,

I came across the PR https://github.com/Automattic/woocommerce-payments/pull/1759 and wanted to let you know that we'll be directing the user to the new overview page after successful KYC.

**Comment by LevinMedia** [comment]
>Hi @LevinMedia, I have implemented this functionality. Please test it at your convenience.

I'll give it another test this afternoon, thanks for the ping! 

>IMO, from the settings page we can remove the following common components:

That's correct - those can be removed!  We should double check to ensure that anyone who's seeing the promo rate UI alongside their base fee is able to see that in the account overview screen as well.

**Comment by naman03malhotra** [comment]
>We should double check to ensure that anyone who's seeing the promo rate UI alongside their base fee is able to see that in the account overview screen as well.

@dmvrtx have we migrated this behaviour in the new `AcountFees` component?  AFIK, we are yet to do that. Please let me know if that is other way round.

**Comment by naman03malhotra** [comment]
>That's correct - those can be removed! We should double check to ensure that anyone who's seeing the promo rate UI alongside their base fee is able to see that in the account overview screen as well.

@LevinMedia this is being done in https://github.com/Automattic/woocommerce-payments/pull/1966, this is yet to be reviewed. We'll try and see if we can send it with the 2.5 release.

**Comment by naman03malhotra** [comment]
Also, @LevinMedia if you please have a final look at the changes we are going to ship with https://github.com/Automattic/woocommerce-payments/pull/1895 along 2.5 release.
