### ISSUE TITLE
Payment Request Buttons: Allow for US-based merchants only

### ISSUE THREAD

**Issue by v18** [Automattic/woocommerce-payments#1414]

**Comment by jrodger** [comment]
We're adding the ability to see the store's Stripe account country as part of https://github.com/Automattic/woocommerce-payments/pull/1400

Might be of use here as well.

**Comment by ricardo** [comment]
> We're adding the ability to see the store's Stripe account country as part of #1400

Hey @jrodger, do you know in which case it would default to 'US'? ([Ref](https://github.com/Automattic/woocommerce-payments/blob/96024da245de0203cb29d9e16810933caa23576b/includes/class-wc-payments-account.php#L767))

Before looking at this, I was thinking about using the WC base country value.

**Comment by jrodger** [comment]
> Do you know in which case it would default to 'US'? (Ref)

It shouldn't really. I think that code is just being defensive and giving us the option of deploying the change in the plugin before we deploy the associated change on the server.

> Before looking at this, I was thinking about using the WC base country value.

I see you've put a PR together, I don't think there's any problem with using the base country value. I just wanted to present all the options. What's the reasoning for restricting the payment request button to US merchants only? Are we managing the rollout of the feature, or will it just not work for non-US Stripe accounts?

**Comment by ricardo** [comment]
@jrodger Thanks for clarifying.

> What's the reasoning for restricting the payment request button to US merchants only?

There's a long discussion around blocker issues (paJDYF-12m-p2#comment-5117), but in short, it was decided that we're going to limit the Geo for now to avoid some issues with the Payment Request API and address validation.

**Comment by jrodger** [comment]
OK, so it seems the important thing is what country WooCommerce thinks it's running in? So I think using the WooCommerce store country makes sense.

**Comment by ricardo** [comment]
> OK, so it seems the important thing is what country WooCommerce thinks it's running in? So I think using the WooCommerce store country makes sense.

Yes. Ok! 👍
