### ISSUE TITLE
Payment Intent: Update the intent when payment fails 

### ISSUE THREAD

**Issue by v18** [Automattic/woocommerce-payments#142]
@RadoslavGeorgiev mentioned it here: https://github.com/Automattic/woocommerce-payments/pull/133#discussion_r302504950

> Then if the payment fails the first time, the user might reload the page, enter a working payment method, in which case the intent ID should be included throughout the process, and updated with the right [payment method].

### Some docs:

Updating a payment intent:

https://stripe.com/docs/api/payment_intents/update

last payment error:

https://stripe.com/docs/api/payment_intents/object#payment_intent_object-last_payment_error

## Misc

Possibly related: #59

**Comment by sommailaria** [comment]
The user in 4222852-zen is experiencing the same issue. Users who purchase as guests and use an incorrect postal code get the following error:

`    Error: You cannot modify customer on a PaymentIntent once it already has been set. To fulfill a payment with a different Customer, cancel this PaymentIntent and create a new one.
`

When they try again with the correct info they then get this.

   ` When a customer goes to click place order the error code “your postal code and card number don’t match” then if you try again this error code pops up Error: You cannot modify customer on a PaymentIntent once it already has been set. To fulfill a payment with a different Customer, cancel this PaymentIntent and create a new one.
`

**Comment by allendav** [comment]
@ctarda - something for us to keep in mind - not sure if this is also a problem for mobile, but it seems like it could be

**Comment by daquinons** [comment]
Fixed by #2717
