### ISSUE TITLE
Payment details blanked on checkout page when WooCommerce reloads the payment section

### ISSUE THREAD

**Issue by jrodger** [Automattic/woocommerce-payments#143]
The cause of this issue and the reproduction steps are the same as https://github.com/woocommerce/woocommerce-gateway-stripe/issues/507.

It's quite easy for a customer to enter their card details and then have to re-enter because they changed something else on the form.

Our options for fixing it are a little limited since we don't have access (for good reason) to the contents of the iframe that the user enters their payment details into. Attempting to move the iframe and re-attach it later don't work since this causes the iframe to reload.

A possible solution suggested by @dechov might be to tweak the code in core so that this fragment of the checkout is really only refreshed if totally necessary (see https://github.com/woocommerce/woocommerce/blob/d03413178144097e4f7903592da41a35ce2ef419/assets/js/frontend/checkout.js#L363).

**Comment by vbelolapotkov** [comment]
Fix PR #151 was merged but the issue didn't close automattically.
