### ISSUE TITLE
Payment Request Button: Display notice in WC shipping settings for UK and CA shipping zones

### ISSUE THREAD

**Issue by ricardo** [Automattic/woocommerce-payments#1430]
Apple Pay redacts the postal code information for the UK and Canada when calculating shipping methods.

According to [their docs](https://developer.apple.com/documentation/apple_pay_on_the_web/applepaysession/1778009-onshippingcontactselected):

> The data returned may differ based on the user's geographic region. For Canada and United Kingdom, a redacted shipping address contains only the first three characters of the postal code. For US addresses, the redacted zip code contains the first five digits.
> 
> The full postal code is provided after the user authorizes the transaction.

This makes it impossible to calculate shipping zones for postal codes (wildcard or full postal codes) with more than 3 characters.

We need to make that issue explicit to the merchant by displaying an error notice in case the Payment Request Button setting is enabled and that type of shipping zone is included.

**Comment by v18** [comment]
@ricardo can this be marked as solved now that https://github.com/Automattic/woocommerce-payments/pull/1528 is merged?

**Comment by ricardo** [comment]
Solved in #1528.
