### ISSUE TITLE
WC Payments setup: add a red badge to the Payments menu item

### ISSUE THREAD

**Issue by pmcpinto** [Automattic/woocommerce-payments#1435]
**Description:** we're going to test adding a badge to the Payments menu item, indicating that there is a task to be completed for stores that have downloaded but not finished setting up WCPay. This is to guide users that may not know what to do after they've installed WCPay.

![wcpay-experiment-event-bubble-next-to-payments.png](https://images.zenhubusercontent.com/5d84fe8e1201de0001b6ab61/deb1c2a6-084e-4154-a2c3-c97b061deb8a)

**Acceptance criteria:**

- [ ] Show a red badge next to the Payments menu item if a store has installed WCPay but has not started to set it up
- [ ] Remove the badge when the user clicks on the Payments section or starts the setup process.

**Comment by ilyasfoo** [comment]
Estimate: 1

**Comment by ilyasfoo** [comment]
Short update: This is done in my local, however, there's a blocker with utilizing `woocommerce/data@1.1.1`, the package is incompatible with Webpack 5 due to [no longer ships with node.js polyfills](https://webpack.js.org/blog/2020-10-10-webpack-5-release/#automatic-nodejs-polyfills-removed). I'm planning to release a new version with a fix, but pending confirmation.

**Comment by ilyasfoo** [comment]
Hi @pmcpinto, can you help to confirm this behaviour:

> Remove the badge when the **user clicks on the Payments section** or starts the setup process.

If the user clicks without starting the setup process, would it be desirable if the notification badge disappear?

An example scenario if a user misclicked and didn't mean to navigate to payment menu, and navigated out immediately after, the notification will also disappear.

**Comment by pmcpinto** [comment]
Hey @ilyasfoo I'd disable the badge when the user clicks to start the setup. Just doing it when they finish the setup can be annoying.
