### ISSUE TITLE
WooCommerce Payments setup: wpcom account creation/connection flow - tweak copy

### ISSUE THREAD

**Issue by pmcpinto** [Automattic/woocommerce-payments#1438]
**Description:** we're seeing a significant % of users dropping during the wpcom account creation/connection flow. We have some limitations in what we can do in this flow, but we should at least try to tweak the copy

![Captura de ecrã 2021-03-26, às 15.39.09.png](https://images.zenhubusercontent.com/5d84fe8e1201de0001b6ab61/1f872ebc-3834-4d2a-aa84-bf1457afe759)

![Captura de ecrã 2021-03-26, às 15.41.53.png](https://images.zenhubusercontent.com/5d84fe8e1201de0001b6ab61/0e91bc59-1cce-47bb-9501-84004f8e46e1)

**Acceptance criteria:**

- [ ] Update the sub-title on the sign up page to:  Enter your email address to get started. Your account will enable you to start using the features and benefits offered by WooCommerce Payments.
- [ ] Update the sub-title on the connection page to:  Approve your connection. Your account will enable you to start using the features and benefits offered by WooCommerce Payments.

**Comment by timmyc** [comment]
@pmcpinto this screen actually the `jetpack-connect` portion of calypso [#](https://github.com/Automattic/wp-calypso/tree/trunk/client/jetpack-connect) Should we move this issue there?

**Comment by pmcpinto** [comment]
👍 I just want to make sure that we don't miss it, as usually the team doesn't work on wp-calypso :)

**Comment by moon0326** [comment]
Estimate: 3 -- I think we need a little bit of research as this copy change should be applied to WooCommerce Payments only.

**Comment by timmyc** [comment]
I think that is a fair estimate Moon - IIRC there is test coverage around this page that would need to be tweaked, or if there isn't a specific test case yet, it would be great to take the time and add it in. This is a very critical flow for so many services around a8c we need to take care when working in it.

**Comment by moon0326** [comment]
@timmyc I will make sure to cover the change with a test 👍

**Comment by pmcpinto** [comment]
@moon0326 do you know when this is going to be released? I want to keep an eye in the conversion rate of this flow
