### ISSUE TITLE
[Card Present Payments] Allow merchants to set account logo, icon and colors

### ISSUE THREAD

**Issue by allendav** [Automattic/woocommerce-payments#1440]
Allow the merchant to set the account logo, icon and colors for issuer compliant email receipts for card present payments

This will require changes to settings, updating the wcpay/accounts REST API controller and possibly server side changes as well. This also will require handling file uploads similar to how disputes does.

https://stripe.com/docs/terminal/checkout/receipts#prebuilt

p91TBi-4Ob-p2

**Comment by beaulebens** [comment]
Is there any consistent way we can share/inherit this information from the rest of the store, at least as a default? It feels redundant that we end up asking merchants to do things like this repeatedly (in emails, in theme config, in Gutenberg, etc etc).

**Comment by allendav** [comment]
Great idea @beaulebens !

**Comment by kalessil** [comment]
@allendav @ctarda: with current deadlines, this falls under "post-live" batch of issues, any concerns about this (is it blocking anything on your end)?

**Comment by ctarda** [comment]
👋🏼  @kalessil ! Yep, this can definitely wait until after general availability. I am not sure I share @allendav 's urgency though 😉 We've had also several merchants mention that they don't really care about receipts. 

This is a bit on a side note, but what I think would be really helpful for us would be to be able to get a link to the actual receipts Stripe store. I know there is an issue for that as well, but I can't find it now 😊

**Comment by anu-rock** [comment]
This task is now being tracked in the epic 1205-gh-Automattic/woocommerce-payments-server

**Comment by anu-rock** [comment]
Closing the issue as all changes discussed here were shipped last week with v3.4 release hidden behind a feature flag `_wcpay_feature_card_readers`. See paJDYF-2AY-p2#comment-9052.

Also created a new issue (#3512) to track the removal of the said feature flag.
