### ISSUE TITLE
WCPayments inbox message - qualitative feedback new users

### ISSUE THREAD

**Issue by pmcpinto** [Automattic/woocommerce-payments#1443]
**Description:** we want to have an ongoing feedback loop about the WCPayments setup experience through an inbox message that's going to redirect users to a qualitative survey.

**Title:** WooCommerce Payments setup - let us know what you think
**Copy:** Congrats on enabling WooCommerce Payments for your store. Please share your feedback in this 2 minute survey to help us improve the setup process.
**Segmentation:** new WCPayments users that completed the setup
**Timing:** right after they complete the setup
**Cadence:** Once
**CTA leads to:** https://automattic.survey.fm/wc-pay-new
**CTA label:** Share feedback

**Comment by moon0326** [comment]
Estimate: 1
