### ISSUE TITLE
WCPayments inbox message - qualitative feedback existing users

### ISSUE THREAD

**Issue by pmcpinto** [Automattic/woocommerce-payments#1444]
**Description:** we want to collect feedback about how WCPay users perceive the existing product experience and uncover pain points. 

**Title:** Help us make improvements to WooCommerce Payments
**Copy:** Share your feedback in this 2 minute survey about how we can make the process of accepting payments more useful for your store.
**Segmentation:** users that received at least one transaction through WCPayments
**Timing:** 60 days after they complete the setup
**Cadence:** Once
**CTA leads to:** http://automattic.survey.fm/wc-pay-existing
**CTA label:** Share feedback

**Comment by pmcpinto** [comment]
@becdetat do you think it's possible to implement this message and #1443 using the remote inbox? I'm assuming that using the completing setup as the trigger makes it difficult, but I'd like to confirm with you.

**Comment by moon0326** [comment]
Estimate: 1

**Comment by becdetat** [comment]
@pmcpinto completing WC Payments setup isn't supported, so the closest it could come is a 60+ day old store with WC Payments activated, which doesn't really cover what you're trying to achieve. IMO the best way to get this out would be within WC Admin.

**Comment by pmcpinto** [comment]
Can we take advantage of the inbox extensibility and release it in wcpayments? We'd be able to ship if faster if we don't rely on the core release train

**Comment by moon0326** [comment]
@becdetat Can't we use `woocommerce_task_list_tracked_completed_tasks` option to check it? 

When a user completes WC Payments task, we updates the option with `woocommerce-payments`

**Comment by moon0326** [comment]
@pmcpinto I think it's going to be a bit tricky to work on this change in WC Payments codebase as we don't have note related to codebase in WC Payments. I think it's best to work on this feature in WC Admin for this round. We're also missing a timestamp for the setup completion as @becdetat mentioned.

I think the best we can do is 

1. 60 days old store
2. Store has at least 1 transaction.

What do you think?

cc @becdetat for feedback.

**Comment by pmcpinto** [comment]
@moon0326 what do you mean by this? :) 

> as we don't have note related to codebase in WC Payments

**Comment by moon0326** [comment]
> @moon0326 what do you mean by this? :)
> 
> > as we don't have note related to codebase in WC Payments

My bad. I think my grammar corrector fixed it incorrectly 🤦 

I think it's going to be a bit tricky to work on this feature in WC Payments because we don't have required inbox message classes in WC Payments. CCing @becdetat to confirm.

**Comment by moon0326** [comment]
@pmcpinto actually..it looks like there are classes. I will look into it again later today. My apologies for not checking it throughly.

**Comment by moon0326** [comment]
@pmcpinto I was able to add a new note in WC Payments repository, but I still don't have a way to accurately check when the user finished WC Payment setup. Is it okay if we use "60 days+ old store" instead of "60 days after they complete the setup?"?

**Comment by pmcpinto** [comment]
> @pmcpinto actually..it looks like there are classes. I will look into it again later today. My apologies for not checking it thoroughly.

👍 no problem!

> @pmcpinto I was able to add a new note in WC Payments repository, but I still don't have a way to accurately check when the user finished WC Payment setup. Is it okay if we use "60 days+ old store" instead of "60 days after they complete the setup" ?

Great. Sure, "60 days+ old store" works well as I assuming that we'll be able to reach older stores, which is going to be helpful.

**Comment by thenbrent** [comment]
> do you think it's possible to implement this message and #1443 using the remote inbox?

The way we've used the remote inbox in the past for specific targeting is to use the [`option` rule](https://github.com/woocommerce/woocommerce-admin/blob/v1.9.0/src/RemoteInboxNotifications/README.md#option). For example, you can see notes for sites with the `option_name` of `wcpay_is_apple_pay_enabled` in the [WooCommerce JSON](https://woocommerce.com/wp-json/wccom/inbox-notifications/1.0/notifications.json).

That gives all the advantages of the remote inbox over notes deployed in plugin code, and avoids having to board the core release train with changes to WC Admin.

For example, in this case, a new option could be added for the account's creation time, then that can be used with an `option_rule` to target based on that (I'm not sure how easy it is to access the account's creation time though.)
