### ISSUE TITLE
Spike: Feasibility on showing multiple payment methods in the classic checkout flow (Gutenberg block)

### ISSUE THREAD

**Issue by harriswong** [Automattic/woocommerce-payments#1445]
### Summary
This spike is to investigate if it is possible to implement the following design to the checkout flow (Gutenberg block theme)
Code: https://github.com/Automattic/woocommerce-payments/tree/develop/client/checkout/blocks

### Scope
- How are we going to add SEPA in here?
- How do we "save card" so that customer can use it next time without re-entering it every time.

### Screenshots
![image](https://user-images.githubusercontent.com/572862/112895317-34323100-909a-11eb-83fa-b6b026e2ffb3.png)

### Relates
https://github.com/Automattic/woocommerce-payments/issues/1441

**Comment by bborman22** [comment]
The move to UPE closes this issue as no longer needed.
