### ISSUE TITLE
Activation: Add admin note when skipping WC Payments activation

### ISSUE THREAD

**Issue by becdetat** [Automattic/woocommerce-payments#1461]
Triggered when clicking "Set up later" from the Log in to WordPress.com account #1458 step.

Trigger an inbox notification one day after the user clicker "set up later" with the following copy:

- Title: Complete the WooCommerce Payments setup
- Description: You need to provide more information to enable deposits and start receiving payouts.
- CTA: Complete Setup
- The CTA redirects to the stepper

Check the [parent issue](https://github.com/Automattic/woocommerce-payments/issues/1439) for any updates that might have been missed in this issue.

**Comment by ilyasfoo** [comment]
Estimate: 1

**Comment by jessy-p** [comment]
From paJDYF-1eN-p2, it appears that the Stepper page is paused and this issue is no longer relevant. Please reopen if I am mistaken and this is something we need to work on.
