### ISSUE TITLE
Use Renovate to manage npm dependencies?

### ISSUE THREAD

**Issue by jrodger** [Automattic/woocommerce-payments#147]
As suggested here: https://github.com/Automattic/woocommerce-payments/pull/122#issuecomment-513045892

Do we want to use Renovate to manage our npm dependencies in this project? I like the idea of having a specific and constant process for doing this, but appreciate it could be noisy.

**Comment by reykjalin** [comment]
Closing this since we've already added Renovate bot 🎉
