### ISSUE TITLE
Enable the use of saved SEPA payments

### ISSUE THREAD

**Issue by superdav42** [Automattic/woocommerce-payments#1471]
When working on https://github.com/Automattic/woocommerce-payments/pull/1452 I found that checking the " Save payment information to my account for future purchases." did not work for SEPA payments. I have not investigated what the issue is. 
We need to allow customer to save their IBAN so they can more easily checkout in future orders.

Should probably be done after #1468

**Comment by c-shultz** [comment]
It looks like this could be a good one to save for sprint 2. SEPA will work without this, right @superdav42 ?

**Comment by superdav42** [comment]
Yes, it will work but we need to either disable the option or fix it before we try to launch SEPA. I'm guessing it won't take much to fix it but I haven't tried yet.

**Comment by harriswong** [comment]
Notes:
- In order for the "Save payment information..." checkbox to show, make sure you are logged in as a customer (not inside wp-admin). 
![image](https://user-images.githubusercontent.com/572862/113913433-90cbd500-9799-11eb-8767-b019a2a70648.png)
- If we have both "Credit Card" and "SEPA" showing, while store's currency is USD, it will fail with this error: 
![image](https://user-images.githubusercontent.com/572862/113913948-2a938200-979a-11eb-8f2d-492b861334a9.png)
Change currency to EUR and it will be okay. Ideally, if the store is set to USD, "SEPA" should be hidden but I think this is something to be handled in Settings. We should test both USD/EUR when we roll this out.
