### ISSUE TITLE
Add refund failures info to transaction timeline

### ISSUE THREAD

**Issue by vbelolapotkov** [Automattic/woocommerce-payments#1476]
Refunds failures are not displayed on the transaction timeline.
Although we have order notes on the order page, it's based on webhooks forwarding and unreliable sometimes. This leads to confusing look of transaction timeline displaying a successful refund:

![image (6)](https://user-images.githubusercontent.com/3139099/113264975-46031680-92dc-11eb-9c96-9c546652a7e9.png)

This need to be fixed to match. Here is the timeline on Stripe dashboard for reference:

![image (7)](https://user-images.githubusercontent.com/3139099/113265215-895d8500-92dc-11eb-9b3e-71377d4b3f4e.png)

Initial discussion and a bit more context (regarding ARN) is in slack (p1617090705365000-slack-CGGCLBN58)

**Comment by htdat** [comment]
I am interested in working on this issue, however, it seems that we need some design updates here.

@LevinMedia - can you have a look here? Or we may simply use the same format like what Stripe is showing?

**Comment by LevinMedia** [comment]
@htdat what stripe is doing looks good to me - can we update it slightly so that it better matches our own style requirements? 

<img width="1491" alt="Screen Shot 2022-01-05 at 2 12 35 PM" src="https://user-images.githubusercontent.com/4500952/148296957-943381bc-33c9-409e-9b66-075355db6dec.png">

also note that we're updating the status in the overview component as well.

**Comment by deepakpathania** [comment]
This is blocked on Stripe adding ARN in the API response, we have a [support ticket](https://dashboard.stripe.com/support/sco_LIPuNgXMbNF1YI) with them, slack discussion around the same can be seen [here](https://a8c.slack.com/archives/CGGCLBN58/p1646902042465929?thread_ts=1617090705.365000&cid=CGGCLBN58).

**Comment by deepakpathania** [comment]
Revising story points to 4 due to the collaboration involved with Stripe to enable some features.
