### ISSUE TITLE
Activation: New welcome screen: randomly assign users

### ISSUE THREAD

**Issue by pmcpinto** [Automattic/woocommerce-payments#1477]
**Description:** considering that implementing the [A/B test package in wcadmin ad wc payments](https://github.com/woocommerce/woocommerce-admin/issues/6660) is still a wip, we need to find a simple way to release some of the changes that we're making to just a small subset of users, namely #1439 and #1436. My suggestion is to randomly assign 50% of users to the existing flow and 50% to the new flow. We implemented something similar last year in core when we started the rollout of the new onboarding experience.

Note: This ticket needs to be considered when doing #1457 which creates the new flow in WC Payments, this ticket should probably be done in parallel with #1457 as the existing flow needs to remain in order to a/b test the flows.

**Acceptance criteria:**

- [ ] When a new user clicks on the Payments menu item, 50% are redirected to the existing welcome screen, and 50% are redirected to the new welcome screen (#1436) that will redirect a user to the stepper page (#1439)

**Event tracking:** 
The tracking to distinguish the new welcome screen will be implemented in #1436

**Comment by pmcpinto** [comment]
@timmyc @becdetat considering that Mothra is working on  #1439 and #1436, probably it makes sense to take care of this one as well. WDYT?

**Comment by timmyc** [comment]
Yeah seems like a simple dice roll, random number generate odd/even sort of thing could suffice. I suppose the one thing we need to be mindful of is after that initial dice role, persisting the a/b tests chosen for the given site as a site option so we con't accidentally show two different UIs to different users on the site.

**Comment by becdetat** [comment]
@pmcpinto I've noted in #1457 and here that these two tickets probably need to be done in parallel as the new flow needs to be created while retaining the existing flow in order to do the a/b test. I've also pulled this into Mothra's backlog.

**Comment by pmcpinto** [comment]
I'm going to close this as now we can use ExPlat
