### ISSUE TITLE
Search on Payments > Transactions returns a blank screen and browser console error

### ISSUE THREAD

**Issue by dougaitken** [Automattic/woocommerce-payments#1480]
Semi redacted [Status Report](https://docs.woocommerce.com/document/understanding-the-woocommerce-system-status-report/).

internal 3870413-zen

<details>
<summary>
SSR
</summary>
`
### WordPress Environment ###

WordPress address (URL): 
Site address (URL):
WC Version: 5.1.0
REST API Version: ✔ 5.1.0
WC Blocks Version: ✔ 4.4.3
Action Scheduler Version: ✔ 3.1.6
WC Admin Version: ✔ 2.0.2
Log Directory Writable: ✔
WP Version: 5.7
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: –
WP Cron: –
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache
PHP Version: 8.0.3
PHP Post Max Size: 40 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.75.0
OpenSSL/1.1.1k

SUHOSIN Installed: –
MySQL Version: 5.5.5-10.3.28-MariaDB
Max Upload Size: 20 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 5.1.0
WC Database Prefix: wp_
Total Database Size: 9808.37MB
Database Data Size: 7004.92MB
Database Index Size: 2803.45MB

### Post Type Counts ###

product: 119183
product_variation: 2

shop_order: 3931
shop_order_refund: 275

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (81) ###

WooCommerce Payments: by Automattic – 2.2.0
WooCommerce: by Automattic – 5.1.0

### Dropin Plugins (1) ###

advanced-cache.php: advanced-cache.php

### Must Use Plugins (1) ###

nh-equipment-boost.php: by  –
</details>

When navigating to Payments > Transactions, search for an order number that you can see or a customer name you know exists. Click on the result or hit return. 

A blank results page loads. Open browser console to show this:

<details>
<summary>
Console errors - very long!
</summary>
14:10:33.335 Cookie “wp-settings-1075” has been rejected because it is already expired. admin.php
14:10:34.015 This page uses the non standard property “zoom”. Consider using calc() in the relevant property values, or using “transform” along with “transform-origin: 0 0”. admin.php
14:10:34.095 JQMIGRATE: Migrate is installed, version 3.3.2 jquery-migrate.min.js:2:709
14:10:34.351 getCurrencyData is deprecated and will be removed from WooCommerce Admin in version 3.1.0. Please use CurrencyFactory.getDataForCountry instead. Note: Pass in the country, locale data, and symbol info to use getDataForCountry index.js:1:6262
14:10:34.476 downloadable font: no supported format found (font-family: "jetpack" style:normal weight:400 stretch:100 src index:1) source: (end of source list)
14:10:34.485 Some cookies are misusing the recommended “SameSite“ attribute 5
14:10:34.485 Cookie “tk_tc” has been rejected for invalid domain. w.js:1:1557
14:10:34.637 downloadable font: OS/2: Bad sTypoLineGap, setting it to 0: -64 (font-family: "code-snippets" style:normal weight:400 stretch:100 src index:1) source: wp-content/plugins/code-snippets/css/font/code-snippets.ttf
14:10:35.106 Content Security Policy: The page's settings blocked the loading of a resource at eval ("script-src").
14:10:35.106 Content Security Policy: The page's settings blocked the loading of a resource at inline ("script-src"). common.js:2:319
14:10:35.403 Content Security Policy: The page's settings blocked the loading of a resource at eval ("script-src").
14:10:50.114 Uncaught (in promise) TypeError: r is null
    getOptionLabel wp-content/plugins/woocommerce-payments/dist/index.js?ver=2.2.0:2
    value wp-content/plugins/woocommerce/packages/woocommerce-admin/dist/components/index.js?ver=2.0.2:2
    value wp-content/plugins/woocommerce/packages/woocommerce-admin/dist/components/index.js?ver=2.0.2:2
    e wp-content/plugins/woocommerce/packages/woocommerce-admin/dist/components/index.js?ver=2.0.2:2
    s wp-content/plugins/woocommerce/packages/woocommerce-admin/dist/components/index.js?ver=2.0.2:2
    _invoke wp-content/plugins/woocommerce/packages/woocommerce-admin/dist/components/index.js?ver=2.0.2:2
    g wp-content/plugins/woocommerce/packages/woocommerce-admin/dist/components/index.js?ver=2.0.2:2
    n wp-content/plugins/woocommerce/packages/woocommerce-admin/dist/components/index.js?ver=2.0.2:2
    c wp-content/plugins/woocommerce/packages/woocommerce-admin/dist/components/index.js?ver=2.0.2:2
    exports wp-content/plugins/woocommerce/packages/woocommerce-admin/dist/components/index.js?ver=2.0.2:2
    exports wp-content/plugins/woocommerce/packages/woocommerce-admin/dist/components/index.js?ver=2.0.2:2
    value wp-content/plugins/woocommerce/packages/woocommerce-admin/dist/components/index.js?ver=2.0.2:2
    promise callback*value wp-content/plugins/woocommerce/packages/woocommerce-admin/dist/components/index.js?ver=2.0.2:2
    value wp-content/plugins/woocommerce/packages/woocommerce-admin/dist/components/index.js?ver=2.0.2:2
    Lodash 10
    value wp-content/plugins/woocommerce/packages/woocommerce-admin/dist/components/index.js?ver=2.0.2:2
    value wp-content/plugins/woocommerce/packages/woocommerce-admin/dist/components/index.js?ver=2.0.2:2
    ki wp-includes/js/dist/vendor/react-dom.min.js?ver=16.13.1:176
    ji wp-includes/js/dist/vendor/react-dom.min.js?ver=16.13.1:13
    mi wp-includes/js/dist/vendor/react-dom.min.js?ver=16.13.1:13
    lf wp-includes/js/dist/vendor/react-dom.min.js?ver=16.13.1:13
    wi wp-includes/js/dist/vendor/react-dom.min.js?ver=16.13.1:187
    Kd wp-includes/js/dist/vendor/react-dom.min.js?ver=16.13.1:32
    pc wp-includes/js/dist/vendor/react-dom.min.js?ver=16.13.1:32
    Wf wp-includes/js/dist/vendor/react-dom.min.js?ver=16.13.1:34
    <anonymous> wp-includes/js/dist/vendor/react-dom.min.js?ver=16.13.1:236
    uf wp-includes/js/dist/vendor/react-dom.min.js?ver=16.13.1:15
    Qd wp-includes/js/dist/vendor/react-dom.min.js?ver=16.13.1:42
    sc wp-includes/js/dist/vendor/react-dom.min.js?ver=16.13.1:41
    unstable_runWithPriority wp-includes/js/dist/vendor/react.min.js?ver=16.13.1:25
    Da wp-includes/js/dist/vendor/react-dom.min.js?ver=16.13.1:60
    <anonymous> wp-includes/js/dist/vendor/react-dom.min.js?ver=16.13.1:236
    Ei wp-includes/js/dist/vendor/react-dom.min.js?ver=16.13.1:41
    Cb wp-includes/js/dist/vendor/react-dom.min.js?ver=16.13.1:41
    w wp-includes/js/dist/vendor/react-dom.min.js?ver=16.13.1:40
    Md wp-includes/js/dist/vendor/react-dom.min.js?ver=16.13.1:35
    oa wp-includes/js/dist/vendor/react-dom.min.js?ver=16.13.1:44
    hj wp-includes/js/dist/vendor/react-dom.min.js?ver=16.13.1:116
    Sh wp-includes/js/dist/vendor/react-dom.min.js?ver=16.13.1:152
    Th wp-includes/js/dist/vendor/react-dom.min.js?ver=16.13.1:152
    tj wp-includes/js/dist/vendor/react-dom.min.js?ver=16.13.1:152
    Te wp-includes/js/dist/vendor/react-dom.min.js?ver=16.13.1:146
    Ja wp-includes/js/dist/vendor/react-dom.min.js?ver=16.13.1:224
    md wp-includes/js/dist/vendor/react-dom.min.js?ver=16.13.1:173
    nd wp-includes/js/dist/vendor/react-dom.min.js?ver=16.13.1:175
    Rh wp-includes/js/dist/vendor/react-dom.min.js?ver=16.13.1:147
    nd wp-includes/js/dist/vendor/react-dom.min.js?ver=16.13.1:175
    render wp-includes/js/dist/vendor/react-dom.min.js?ver=16.13.1:238
    295 wp-content/plugins/woocommerce/packages/woocommerce-admin/dist/app/index.js?ver=2.0.2:2
    295 wp-content/plugins/woocommerce/packages/woocommerce-admin/dist/app/index.js?ver=2.0.2:2
    a wp-content/plugins/woocommerce/packages/woocommerce-admin/dist/app/index.js?ver=2.0.2:2
    app wp-content/plugins/woocommerce/packages/woocommerce-admin/dist/app/index.js?ver=2.0.2:2
    <anonymous> wp-content/plugins/woocommerce/packages/woocommerce-admin/dist/app/index.js?ver=2.0.2:2
index.js:2:309950
14:11:20.527 Uncaught (in promise) TypeError: r is null
    getOptionLabel wp-content/plugins/woocommerce-payments/dist/index.js?ver=2.2.0:2
    value wp-content/plugins/woocommerce/packages/woocommerce-admin/dist/components/index.js?ver=2.0.2:2
    value wp-content/plugins/woocommerce/packages/woocommerce-admin/dist/components/index.js?ver=2.0.2:2
    e wp-content/plugins/woocommerce/packages/woocommerce-admin/dist/components/index.js?ver=2.0.2:2
    s wp-content/plugins/woocommerce/packages/woocommerce-admin/dist/components/index.js?ver=2.0.2:2
    _invoke wp-content/plugins/woocommerce/packages/woocommerce-admin/dist/components/index.js?ver=2.0.2:2
    g wp-content/plugins/woocommerce/packages/woocommerce-admin/dist/components/index.js?ver=2.0.2:2
    n wp-content/plugins/woocommerce/packages/woocommerce-admin/dist/components/index.js?ver=2.0.2:2
    c wp-content/plugins/woocommerce/packages/woocommerce-admin/dist/components/index.js?ver=2.0.2:2
    exports wp-content/plugins/woocommerce/packages/woocommerce-admin/dist/components/index.js?ver=2.0.2:2
    exports wp-content/plugins/woocommerce/packages/woocommerce-admin/dist/components/index.js?ver=2.0.2:2
    value wp-content/plugins/woocommerce/packages/woocommerce-admin/dist/components/index.js?ver=2.0.2:2
    promise callback*value wp-content/plugins/woocommerce/packages/woocommerce-admin/dist/components/index.js?ver=2.0.2:2
    value wp-content/plugins/woocommerce/packages/woocommerce-admin/dist/components/index.js?ver=2.0.2:2
    Lodash 6
    value wp-content/plugins/woocommerce/packages/woocommerce-admin/dist/components/index.js?ver=2.0.2:2
    value wp-content/plugins/woocommerce/packages/woocommerce-admin/dist/components/index.js?ver=2.0.2:2
    ki wp-includes/js/dist/vendor/react-dom.min.js?ver=16.13.1:176
    ji wp-includes/js/dist/vendor/react-dom.min.js?ver=16.13.1:13
    mi wp-includes/js/dist/vendor/react-dom.min.js?ver=16.13.1:13
    lf wp-includes/js/dist/vendor/react-dom.min.js?ver=16.13.1:13
    wi wp-includes/js/dist/vendor/react-dom.min.js?ver=16.13.1:187
    Kd wp-includes/js/dist/vendor/react-dom.min.js?ver=16.13.1:32
    pc wp-includes/js/dist/vendor/react-dom.min.js?ver=16.13.1:32
    Wf wp-includes/js/dist/vendor/react-dom.min.js?ver=16.13.1:34
    <anonymous> wp-includes/js/dist/vendor/react-dom.min.js?ver=16.13.1:236
    uf wp-includes/js/dist/vendor/react-dom.min.js?ver=16.13.1:15
    Qd wp-includes/js/dist/vendor/react-dom.min.js?ver=16.13.1:42
    sc wp-includes/js/dist/vendor/react-dom.min.js?ver=16.13.1:41
    unstable_runWithPriority wp-includes/js/dist/vendor/react.min.js?ver=16.13.1:25
    Da wp-includes/js/dist/vendor/react-dom.min.js?ver=16.13.1:60
    <anonymous> wp-includes/js/dist/vendor/react-dom.min.js?ver=16.13.1:236
    Ei wp-includes/js/dist/vendor/react-dom.min.js?ver=16.13.1:41
    Cb wp-includes/js/dist/vendor/react-dom.min.js?ver=16.13.1:41
    w wp-includes/js/dist/vendor/react-dom.min.js?ver=16.13.1:40
    Md wp-includes/js/dist/vendor/react-dom.min.js?ver=16.13.1:35
    oa wp-includes/js/dist/vendor/react-dom.min.js?ver=16.13.1:44
    hj wp-includes/js/dist/vendor/react-dom.min.js?ver=16.13.1:116
    Sh wp-includes/js/dist/vendor/react-dom.min.js?ver=16.13.1:152
    Th wp-includes/js/dist/vendor/react-dom.min.js?ver=16.13.1:152
    tj wp-includes/js/dist/vendor/react-dom.min.js?ver=16.13.1:152
    Te wp-includes/js/dist/vendor/react-dom.min.js?ver=16.13.1:146
    Ja wp-includes/js/dist/vendor/react-dom.min.js?ver=16.13.1:224
    md wp-includes/js/dist/vendor/react-dom.min.js?ver=16.13.1:173
    nd wp-includes/js/dist/vendor/react-dom.min.js?ver=16.13.1:175
    Rh wp-includes/js/dist/vendor/react-dom.min.js?ver=16.13.1:147
    nd wp-includes/js/dist/vendor/react-dom.min.js?ver=16.13.1:175
    render wp-includes/js/dist/vendor/react-dom.min.js?ver=16.13.1:238
    295 wp-content/plugins/woocommerce/packages/woocommerce-admin/dist/app/index.js?ver=2.0.2:2
    295 wp-content/plugins/woocommerce/packages/woocommerce-admin/dist/app/index.js?ver=2.0.2:2
    a wp-content/plugins/woocommerce/packages/woocommerce-admin/dist/app/index.js?ver=2.0.2:2
    app wp-content/plugins/woocommerce/packages/woocommerce-admin/dist/app/index.js?ver=2.0.2:2
    <anonymous> wp-content/plugins/woocommerce/packages/woocommerce-admin/dist/app/index.js?ver=2.0.2:2
index.js:2:309950
14:11:23.040 Error: Minified React error #185; visit https://reactjs.org/docs/error-decoder.html?invariant=185 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    Ja wp-includes/js/dist/vendor/react-dom.min.js?ver=16.13.1:224
    ch wp-includes/js/dist/vendor/react-dom.min.js?ver=16.13.1:93
    e wp-includes/js/dist/data.min.js?ver=943087ae96d075f126df689839bb96b9:2
    Ge wp-includes/js/dist/data.min.js?ver=943087ae96d075f126df689839bb96b9:2
    Bh wp-includes/js/dist/vendor/react-dom.min.js?ver=16.13.1:126
    oj wp-includes/js/dist/vendor/react-dom.min.js?ver=16.13.1:126
    Aj wp-includes/js/dist/vendor/react-dom.min.js?ver=16.13.1:160
    unstable_runWithPriority wp-includes/js/dist/vendor/react.min.js?ver=16.13.1:25
    Da wp-includes/js/dist/vendor/react-dom.min.js?ver=16.13.1:60
    ab wp-includes/js/dist/vendor/react-dom.min.js?ver=16.13.1:154
    Te wp-includes/js/dist/vendor/react-dom.min.js?ver=16.13.1:146
    Pg wp-includes/js/dist/vendor/react-dom.min.js?ver=16.13.1:61
    unstable_runWithPriority wp-includes/js/dist/vendor/react.min.js?ver=16.13.1:25
    Da wp-includes/js/dist/vendor/react-dom.min.js?ver=16.13.1:60
    Pg wp-includes/js/dist/vendor/react-dom.min.js?ver=16.13.1:61
    ha wp-includes/js/dist/vendor/react-dom.min.js?ver=16.13.1:60
    <anonymous> wp-includes/js/dist/vendor/react-dom.min.js?ver=16.13.1:236
    Ei wp-includes/js/dist/vendor/react-dom.min.js?ver=16.13.1:41
    Cb wp-includes/js/dist/vendor/react-dom.min.js?ver=16.13.1:41
    w wp-includes/js/dist/vendor/react-dom.min.js?ver=16.13.1:40
    Md wp-includes/js/dist/vendor/react-dom.min.js?ver=16.13.1:35
    oa wp-includes/js/dist/vendor/react-dom.min.js?ver=16.13.1:44
    hj wp-includes/js/dist/vendor/react-dom.min.js?ver=16.13.1:117
    Sh wp-includes/js/dist/vendor/react-dom.min.js?ver=16.13.1:152
    Th wp-includes/js/dist/vendor/react-dom.min.js?ver=16.13.1:152
    tj wp-includes/js/dist/vendor/react-dom.min.js?ver=16.13.1:152
    Te wp-includes/js/dist/vendor/react-dom.min.js?ver=16.13.1:146
    Ja wp-includes/js/dist/vendor/react-dom.min.js?ver=16.13.1:224
    md wp-includes/js/dist/vendor/react-dom.min.js?ver=16.13.1:173
    nd wp-includes/js/dist/vendor/react-dom.min.js?ver=16.13.1:175
    Rh wp-includes/js/dist/vendor/react-dom.min.js?ver=16.13.1:147
    nd wp-includes/js/dist/vendor/react-dom.min.js?ver=16.13.1:175
    render wp-includes/js/dist/vendor/react-dom.min.js?ver=16.13.1:238
    295 wp-content/plugins/woocommerce/packages/woocommerce-admin/dist/app/index.js?ver=2.0.2:2
    295 wp-content/plugins/woocommerce/packages/woocommerce-admin/dist/app/index.js?ver=2.0.2:2
    a wp-content/plugins/woocommerce/packages/woocommerce-admin/dist/app/index.js?ver=2.0.2:2
    app wp-content/plugins/woocommerce/packages/woocommerce-admin/dist/app/index.js?ver=2.0.2:2
    <anonymous> wp-content/plugins/woocommerce/packages/woocommerce-admin/dist/app/index.js?ver=2.0.2:2
react-dom.min.js:125:24
14:11:23.041 Uncaught Error: Minified React error #185; visit https://reactjs.org/docs/error-decoder.html?invariant=185 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    Ja wp-includes/js/dist/vendor/react-dom.min.js?ver=16.13.1:224
    ch wp-includes/js/dist/vendor/react-dom.min.js?ver=16.13.1:93
    e wp-includes/js/dist/data.min.js?ver=943087ae96d075f126df689839bb96b9:2
    Ge wp-includes/js/dist/data.min.js?ver=943087ae96d075f126df689839bb96b9:2
    Bh wp-includes/js/dist/vendor/react-dom.min.js?ver=16.13.1:126
    oj wp-includes/js/dist/vendor/react-dom.min.js?ver=16.13.1:126
    Aj wp-includes/js/dist/vendor/react-dom.min.js?ver=16.13.1:160
    unstable_runWithPriority wp-includes/js/dist/vendor/react.min.js?ver=16.13.1:25
    Da wp-includes/js/dist/vendor/react-dom.min.js?ver=16.13.1:60
    ab wp-includes/js/dist/vendor/react-dom.min.js?ver=16.13.1:154
    Te wp-includes/js/dist/vendor/react-dom.min.js?ver=16.13.1:146
    Pg wp-includes/js/dist/vendor/react-dom.min.js?ver=16.13.1:61
    unstable_runWithPriority wp-includes/js/dist/vendor/react.min.js?ver=16.13.1:25
    Da wp-includes/js/dist/vendor/react-dom.min.js?ver=16.13.1:60
    Pg wp-includes/js/dist/vendor/react-dom.min.js?ver=16.13.1:61
    ha wp-includes/js/dist/vendor/react-dom.min.js?ver=16.13.1:60
    <anonymous> wp-includes/js/dist/vendor/react-dom.min.js?ver=16.13.1:236
    Ei wp-includes/js/dist/vendor/react-dom.min.js?ver=16.13.1:41
    Cb wp-includes/js/dist/vendor/react-dom.min.js?ver=16.13.1:41
    w wp-includes/js/dist/vendor/react-dom.min.js?ver=16.13.1:40
    Md wp-includes/js/dist/vendor/react-dom.min.js?ver=16.13.1:35
    oa wp-includes/js/dist/vendor/react-dom.min.js?ver=16.13.1:44
    hj wp-includes/js/dist/vendor/react-dom.min.js?ver=16.13.1:117
    Sh wp-includes/js/dist/vendor/react-dom.min.js?ver=16.13.1:152
    Th wp-includes/js/dist/vendor/react-dom.min.js?ver=16.13.1:152
    tj wp-includes/js/dist/vendor/react-dom.min.js?ver=16.13.1:152
    Te wp-includes/js/dist/vendor/react-dom.min.js?ver=16.13.1:146
    Ja wp-includes/js/dist/vendor/react-dom.min.js?ver=16.13.1:224
    md wp-includes/js/dist/vendor/react-dom.min.js?ver=16.13.1:173
    nd wp-includes/js/dist/vendor/react-dom.min.js?ver=16.13.1:175
    Rh wp-includes/js/dist/vendor/react-dom.min.js?ver=16.13.1:147
    nd wp-includes/js/dist/vendor/react-dom.min.js?ver=16.13.1:175
    render wp-includes/js/dist/vendor/react-dom.min.js?ver=16.13.1:238
    295 wp-content/plugins/woocommerce/packages/woocommerce-admin/dist/app/index.js?ver=2.0.2:2
    295 wp-content/plugins/woocommerce/packages/woocommerce-admin/dist/app/index.js?ver=2.0.2:2
    a wp-content/plugins/woocommerce/packages/woocommerce-admin/dist/app/index.js?ver=2.0.2:2
    app wp-content/plugins/woocommerce/packages/woocommerce-admin/dist/app/index.js?ver=2.0.2:2
    <anonymous> wp-content/plugins/woocommerce/packages/woocommerce-admin/dist/app/index.js?ver=2.0.2:2
react-dom.min.js:224:290
</details>

**Comment by ismaeldcom** [comment]
This is related to what @jrodger discovered today, a console error with `Uncaught Error: Maximum update depth exceeded`.

We have been researching and so far what we discovered is:

* Doesn't work with any version of WC
* Works with WP 5.6 but not with 5.7
* Works with Gutenberg 9.6.2 but not with 9.7.0

Seems to be related with the search param from query returning an array. And using that array in dependencies of transactions useSelect hooks. Like this one:
https://github.com/Automattic/woocommerce-payments/blob/39ccdf1407dc1e482453446351997fd4ea9fdf71/client/data/transactions/hooks.js#L83-L130

If I'm not wrong. Using an array within the hook dependencies might cause an infinite loop because React uses referential equality to check dependencies.

I tried a quick workaround joining the array and everything works. Don't use this, is just for reference ⚠️
<img height=300 src="https://user-images.githubusercontent.com/7670276/113319145-7022fb80-9311-11eb-8e90-edda514c4743.png" />

Digging a bit more I found that wc-admin are using a comma separated string instead of an array for the search param, maybe we need to research more in this direction.

**Comment by jrodger** [comment]
We have a variation on this theme here https://github.com/Automattic/woocommerce-payments/issues/1499.

Note, filtering by a single date works. We only hit this problem with the "between" filter, presumably because that then adds more than one parameter to the URL and we hit the array / string issue.
