### ISSUE TITLE
Extend transactions CSV export

### ISSUE THREAD

**Issue by ismaeldcom** [Automattic/woocommerce-payments#1484]
Parent issue #689

With #1479 we provided a basic CSV export, you can download the visible rows. But we need to discuss how to approach a more advanced solution. Like full transactions export using a new server request or email report link like wc-admin.

This also depends on issue #1483 to decide if we create a custom implementation or opt for migrating to wc-admin report table.

We can check now the event `wcadmin_wcpay_transactions_download` to have more information and evaluate the priority of this issue.

**Comment by dechov** [comment]
Opened an issue for Deposits table download as well (https://github.com/Automattic/woocommerce-payments/issues/2548), so we could potentially consider this issue to be generalized beyond Transactions.

**Comment by jobthomas** [comment]
A similar issue was reported in #2629 and I've closed that one in favour of the discussion here. I want to emphasise that as we see more and more larger WooCommerce Payments stores, this is likely going to become a recurring request. I'm not sure what the solution for that should be, but we should find one. 

For posterity. One of the nuisances that comes with the current approach is that whenever a new transaction comes in, the 100th transaction will be shown again on page 2. If that happens in the middle of exporting page 1 and page 2, it'll cause duplicates being in the export files. 

A workaround for that is to download after using "Advanced filters" and then choose a date range that doesn't include current day. Note that this only solves the nuisance issue, not the size of the export issue.

<img width="1257" alt="Screenshot 2021-09-03 at 13 31 48" src="https://user-images.githubusercontent.com/8783673/131998675-43c82cbd-871c-407c-ab64-af5d8b411e33.png">

**Comment by naman03malhotra** [comment]
Quick update here:
We received [a request](p1627521386016500-slack-C7U3Y3VMY) in #woo-devs channel where a user requested to bulk export their transactions. As of now, our APIs are limited to fetch a maximum of 100 records per request which prevent user to download their transaction data in bulk.

As this request is pending for a couple of weeks now, we can solve this for this user by manually downloading the reports from the stripe dashboard and send them to the customer. This is not a scalable solution, it's more of temporary relief for the users who absolutely need it. A proper solution needs to be discussed and implemented.

There is an ongoing discussion here: p1630617247298300-slack-C01BPL3ALGP

**Comment by csmcneill** [comment]
I wanted to add to this discussion with some information provided by a WooCommerce Payments user:

> The current implementation of WooCommerce Payments does not support a use case for a typical bank reconciliation. Where reconciling the bank for other payment methods takes minutes, it takes hours for WooCommerce Payments.

The user also suggests the following enhancements would be ideal for bank reconciliation:

> 1. Add columns to the deposit list or a deposit download that at a minimum it contains:
> a. Deposit Date
> b. Deposit Gross Sales
> c. Deposit Net Deposit
> d. Unique Deposit Id (Ideally so a quick view is useful without a spreadsheet helper)
> e. Deposit Fees (Ideally so a quick view is useful without a spreadsheet helper)
> f. Deposit # transactions (ideally. To identify deposits with refunds that sorted to a different day in the spreadsheet helper) This simple change alone would make the process usable (at least by me).
> 2. Provide a transaction list with a full month of transactions. Include a unique deposit id, deposit date and transaction date. These would help resolve refunds issued on days subsequent to the original sale.

I've shared a full copy of this user's findings with the ongoing discussion happening here: p1630617247298300-slack-C01BPL3ALGP

**Comment by gabrielbonifacio** [comment]
Another WooCommerce Payments user has requested this feature at the [WordPress.org forum](https://wordpress.org/support/topic/processes-well-but-nearly-0-reporting-capabilities/):

> I can’t get a monthly statement using Woocommerce Payments. In order to see last month’s total transactions, returns, and deposits, I would have to download download 100 transactions at a time to excel (because this is the limit to download), then combine them in a spreadsheet, then sum the totals.
> 
> Not ready for primetime yet.
>
