### ISSUE TITLE
Write new e2e test: Merchant / Subscriptions / Renewal on subscription page

### ISSUE THREAD

**Issue by zhongruige** [Automattic/woocommerce-payments#1493]
Write a new e2e test that covers the following flow:
* Merchant / Subscriptions / Renewal on subscription page

**Comment by zhongruige** [comment]
> Hi @zhongruige
> So far I haven't found the possibility to renew a subscription in a merchant area. This should be possible only for a shopper to renew. No matter which status is of a subscription in `WooCommerce > Subscriptions` whether it is On Hold, Active, Expired, Cancelled... there's no Renew option or something.

Hi @veljkho! Great question! I tried a few combinations but so far I haven't seen the option to renew from within the WooCommerce > Subscriptions page:

* Changing the payment method for the subscription from automatic to manual following [these instructions](https://docs.woocommerce.com/document/change-subscription-from-automatic-to-manual-payments/)
* Marking the subscription as expired
* Following the setup in the [Early Renewal Guide](https://docs.woocommerce.com/document/subscriptions/early-renewal/)

So, I think for us to test this flow, we will need to open up the individual subscription details, like this:

* Click the subscription ID on the `WooCommerce > Subscriptions` page:

<img width="1413" alt="Screen Shot 2021-06-01 at 1 47 54 PM" src="https://user-images.githubusercontent.com/71906536/120382130-84b74c00-c2e0-11eb-9925-9f52612b413e.png">

* View the subscription details and find the `Subscription actions` dropdown on the upper-right of the page:

<img width="309" alt="Screen Shot 2021-06-01 at 1 52 43 PM" src="https://user-images.githubusercontent.com/71906536/120382277-af090980-c2e0-11eb-943f-b71115c68d67.png">

* From the dropdown, select `Process renewal`:

<img width="315" alt="Screen Shot 2021-06-01 at 1 53 28 PM" src="https://user-images.githubusercontent.com/71906536/120382348-c47e3380-c2e0-11eb-97ab-1e5dd65e9ad2.png">

* This will trigger a dialog confirming a charge will be made:

<img width="524" alt="Screen Shot 2021-06-01 at 1 45 11 PM" src="https://user-images.githubusercontent.com/71906536/120382396-d233b900-c2e0-11eb-906c-6e95bd683dbd.png">

The challenge from here, I think, will be finding the latest order (the one we manually triggered), as the ID linked on the `WooCommerce > Subscriptions` page won't be updated. Once we click on `Process renewal` and confirm the dialog window, the page will refresh. We can scroll to the bottom and find the renewal order at the bottom under `Related orders`:

<img width="1112" alt="Screen Shot 2021-06-01 at 1 56 54 PM" src="https://user-images.githubusercontent.com/71906536/120382764-49694d00-c2e1-11eb-9ea1-0a2761fde2d3.png">

Alternatively, there's a few other ways to find it:

* Click the subscription ID on the `WooCommerce > Subscriptions` page and find the renewal order at the bottom under `Related orders`:

* Open the single order view and also find it under `Related Orders` at the bottom.

Once have that, we can get the order details and verify there was a successful payment, open the transaction details, etc. to verify the renewal was processed (and paid) successfully via WooCommerce Payments.

**Comment by veljkho** [comment]
Many thanks for this @zhongruige , I will then tackle this task this Thursday instead of [this one](https://github.com/Automattic/woocommerce-payments/issues/1494). Will follow your guidelines above.
