### ISSUE TITLE
Ensure card holder zip code is passed for each transaction

### ISSUE THREAD

**Issue by v18** [Automattic/woocommerce-payments#1496]
Reference: pbUcTB-dh-p2

Tasks:
- [x] Ensure card holder zip code is passed for each transaction. Note that we already ensured that zipcode is passed for all payment request button & Apple Pay transaction.
- [ ] Ensure our documentation reflects that Zip Codes are passed

**Comment by RadoslavGeorgiev** [comment]
Based on the original thread, we are already passing card holders' zip codes during transactions.

I'm keeping the issue open, because it still requires our docs to reflect that.

**Comment by jessy-p** [comment]
Closing as obsolete. Please create a new issue if required.
