### ISSUE TITLE
Add payment methods list box in settings screen

### ISSUE THREAD

**Issue by Ferdev** [Automattic/woocommerce-payments#1501]
Implement in the new WooCommerce Payments settings screen, a new info box with a list of all the supported payment methods: Credit card, SEPA, GiroPay and Sofort.

### Header
- Box title: `Payment methods`
- Box description: `Increase your store’s conversion by offering your customers preferred and convenient payment methods. Drag and drop to reorder on checkout.`
#### First section
- Between horizontal separators, a button too add new payment methods. Copy: `Add payment method`
- Icons representing additional payment methods.
- Should be hidden if all payment methods are already added to the list.
#### Second section
- List with all added payment methods. For each payment method:
  - Handle to sort the payment method in the list. Its functionality will be implemented in another issue.
  - Payment method's icon.
  - Payment method's name.
  - Payment method's description, below the name.
  - Link to edit the payment method info. Copy: `Manage`.
  - Button to remove the payment method.
##### Payment methods names & descriptions
- Name: `Credit card / debit card` - Description: `Let your customers pay with major credit and debit cards without leaving your store.`
- Name: `giropay` - Description: `Expand your business with giropay — Germany’s second most popular payment system.`
- Name: `Sofort` - Description: `Accept secure bank transfers from Austria, Belgium, Germany, Italy, and Netherlands.`
- Name: `Direct debit payment` - Description: `Reach 500 million customers and over 20 million businesses across the European Union.`

## Screenshot
![shot-2021-04-05-17-57-19](https://user-images.githubusercontent.com/130142/113598082-e5a60900-963c-11eb-9547-5449ab2321c0.png)

**Comment by waclawjacek** [comment]
I have extracted smaller issues from this one:

- Implementing the list front-end. #1524
- Implementing the modal displayed after clicking *Add payment method*. #1554.

After these are implemented, this issue should focus on just adding the *Payment methods* card and linking the above together.

**Comment by waclawjacek** [comment]
Mobile design screenshot:

![Markup on 2021-04-16 at 14:57:33](https://user-images.githubusercontent.com/1759681/115027516-1c451480-9ec4-11eb-8316-d69c3dac2b83.png)
