### ISSUE TITLE
Payment Request button: Redirect customers to authentication when guest checkout is not possible

### ISSUE THREAD

**Issue by ricardo** [Automattic/woocommerce-payments#1502]
Currently, the Payment Request button does not show up when authentication is required for checkout.

It might be required either because the given product type requires sign up (e.g subscription), or because WC settings require it.

From what I have seen, some extensions, and even the checkout page in core, does not redirect nor offer a link to authenticate or sign up.

We might want to give some clue to the customer as to why the Payment Request button did not show up.

This needs a design and further discussion.

**Comment by ricardo** [comment]
@LevinMedia We'd like to open up a discussion about this.

Basically, the payment request button is not supported depending on a combination of settings under **WooCommerce > Settings > Accounts and Privacy**. Or the product chosen requires authentication or account creation (e.g Subscription).

![Guest checkout/Account creation settings](https://user-images.githubusercontent.com/5509901/117092931-f7f78d80-ad35-11eb-8606-ee712157cb08.png)

Right now we are hiding the payment request button when it's not supported due to authentication requirements:

<table>
<tr>
<td>Checking out with PRB is supported</td>
<td>Checking out with PRB is not supported</td>
</tr>
<tr>
<td>
<img src="https://user-images.githubusercontent.com/5509901/117093257-ce8b3180-ad36-11eb-957c-a83223b80261.png">
</td>
<td>
<img src="https://user-images.githubusercontent.com/5509901/117093260-d0ed8b80-ad36-11eb-8c21-8806c2a07bdd.png">
</td>
</tr>
</table>

This has a few downsides:

- Merchants and users might get confused as to why the button is not showing up.
- Some merchants want to disable username and password to be auto-generated upon checkout ([Reference](https://github.com/woocommerce/woocommerce-gateway-stripe/issues/1194#issuecomment-824857694)). The Payment Request API doesn't offer a way to set username/password, so the only way to allow it is when username/password are automatically generated or the user is already authenticated.

We are considering changing the current approach by displaying the button, but somehow guiding customers to account creation or authentication before using the payment request button.

That could be done by adding some sort of info notice when the button is clicked, with a link to "My account" when authentication is required.

@LevinMedia do you have any opinions about this? Any suggestions on how we could do this differently to fix the downsides of not displaying the button? Or any suggestions about what to say on that notice?

**Comment by LevinMedia** [comment]
@ricardo I'll look into a flow for this today and come back with some design options.
