### ISSUE TITLE
 Implement sorting mechanism for the checkout options list in settings 

### ISSUE THREAD

**Issue by Ferdev** [Automattic/woocommerce-payments#1505]
The items in the checkout options list can be sorted in the WooCommerce Payments settings screen. Users will be able to drag an element in the list and drop it in the desired position.

The checkout options will be displayed in this order on the checkout screen.

## Screen elements
- An icon at the beginning of each item representing the handle the user will press to drag the element.

## Screenshot
![shot-2021-04-06-13-26-24](https://user-images.githubusercontent.com/130142/113703903-bc888580-96db-11eb-8f4a-b84e0619aa49.png)

**Comment by frosso** [comment]
I am planning on creating a reusable component/mechanism for both the express checkout options and the [payment methods](https://github.com/Automattic/woocommerce-payments/issues/1504).

**Comment by Ferdev** [comment]
That sounds perfect to me! :+1:

**Comment by frosso** [comment]
No longer needed, based on the newer designs. Most of the work can be handled in https://github.com/Automattic/woocommerce-payments/issues/1503
Sorting mechanism in this section is no longer present.
