### ISSUE TITLE
Implement checkout preview

### ISSUE THREAD

**Issue by Ferdev** [Automattic/woocommerce-payments#1506]
The user will find a button in the WooCommerce Payments settings screen that will allow him to preview the checkout screen according to the configuration entered in the settings screen.

## Screen elements
- Button to open the preview screen modal. Copy: `Preview checkout`
- Modal popup containing the checkout screen preview.

## Screenshot
![shot-2021-04-06-13-33-25](https://user-images.githubusercontent.com/130142/113705076-4ab13b80-96dd-11eb-831d-116c51c89952.png)
![shot-2021-04-06-13-34-24](https://user-images.githubusercontent.com/130142/113705086-4d139580-96dd-11eb-8666-5c023075e734.png)

**Comment by c-shultz** [comment]
Thanks for creating this story! I'm moving this to the backlog. This one isn't a priority yet.

**Comment by frosso** [comment]
Update Jun 09 - we'll still keep this with low priority, not strictly necessary for the new settings view

**Comment by LevinMedia** [comment]
Closing this issue
