### ISSUE TITLE
Ensure WooCommerce Subscriptions works with SEPA

### ISSUE THREAD

**Issue by superdav42** [Automattic/woocommerce-payments#1518]
The `WC_Payment_Gateway_WCPay_Subscriptions_Compat` is conditionally loaded instead of `WC_Payment_Gateway_WCPay`. Since we are extending WC_Payment_Gateway_WCPay by the SEPA gateway there are likely to be issues with subscriptions. 
I believe the correct course of action is to move the code which can be always loadad from `WC_Payment_Gateway_WCPay_Subscriptions_Compat` to `WC_Payment_Gateway_WCPay`. Code that should be conditionally loaded in WooCommerce Subscriptions is installed should be moved to a new class and not part of a Gateway class at all.

p1617748823068500-slack-C01SB4X2KB5

**Comment by bborman22** [comment]
The move to UPE closes this issue as no longer needed. The compatibility with subscriptions and UPE is still an area to investigate / ensure and captured in #1845.
