### ISSUE TITLE
Payment Request: Fix UK and CA shipping zones + redacted postal codes from Apple Pay

### ISSUE THREAD

**Issue by ricardo** [Automattic/woocommerce-payments#1525]
Apparently, Apple Pay has changed its rules for UK and CA postal codes and is now returning the first 4 characters instead of only the first 3. I'm in contact with their support and I still need to get confirmation from them, but if that's the case, we can properly fix the long lived issue in 1198-gh-woocommerce/woocommerce-gateway-stripe, instead of just showing a warning that it may not work with 4+ characters postal codes, as proposed in #1430

There's also a problem when calculating shipping options while passing a redacted UK postal code specifically. The `woocommerce_validate_postcode` filter which is used to ignore the postal code validation for the UK and Canada doesn't seem to be working.

**Comment by ricardo** [comment]
@LevinMedia I asked for your input a few days ago about displaying that warning which says wildcard shipping zones are not supported in the UK.

But apparently, Apple Pay is now able to provide the first 4 characters of the postal code to us, instead of the first 3.

Do you see any problems if we don't display the warning anymore? The only way this could generate an issue is if the merchant tries to use a 5+ character postal code in the UK. But it looks like nobody wants to do that from 1198-gh-woocommerce/woocommerce-gateway-stripe.

**Comment by LevinMedia** [comment]
👍 That's great news! I think we can skip it now.
