### ISSUE TITLE
Payment Methods only appear for relevant countries/currencies

### ISSUE THREAD

**Issue by c-shultz** [Automattic/woocommerce-payments#1526]
SEPA, Giropay, and Sofort should only appear if the presentment currency is Euros and for the correct customer locale.

[One possible approach](https://github.com/woocommerce/woocommerce-gateway-stripe/blob/64afc2727f3b6ce1b4dc644f4f526ebc99310ef1/includes/payment-methods/class-wc-gateway-stripe-sepa.php#L152) ( thanks @brezocordero )

**Comment by bborman22** [comment]
The move to UPE closes this issue as no longer needed. This should be handled within the UPE and if not, will be bubbled up at the time these payment methods are added to UPE.
