### ISSUE TITLE
Fix Add payment method on My Account for SEPA

### ISSUE THREAD

**Issue by brezocordero** [Automattic/woocommerce-payments#1538]
Using the branch https://github.com/Automattic/woocommerce-payments/compare/sepa/1441-sepa-classic when you enter the test IBAN number and click on 'Add Payment Method', there is an error and the SEPA payment is not added:

`Missing required param: billing_details[name].`

![SEPAAddPaymentError](https://user-images.githubusercontent.com/8002881/114212593-a242e780-9927-11eb-8f91-b4ea4d73d549.png)

You should be able to add a SEPA direct debit payment.

**Comment by brezocordero** [comment]
This issue also needs to address:
1) Set as default
2) Delete payment method

**Comment by harriswong** [comment]
👀
