### ISSUE TITLE
Payment Request button + Block checkout compatibility with 3D Secure cards

### ISSUE THREAD

**Issue by ricardo** [Automattic/woocommerce-payments#1544]
Implement compatibility with Payment Request buttons + 3D Secure cards in the block checkout.

**Comment by kalessil** [comment]
Seems to be a duplicate of #1330.

**Comment by ricardo** [comment]
@kalessil, It is. Thanks for flagging! I've looked for the issue but didn't find.

I'll repurpose this issue to fix 3DS compatibility for Payment Request Buttons + Block checkout.
