### ISSUE TITLE
Add "Add payment methods" modal

### ISSUE THREAD

**Issue by waclawjacek** [Automattic/woocommerce-payments#1554]
After the *Add payment method* button is clicked in the card implemented in #1501, a modal should be displayed.

The checkbox list component will be implemented in #1552. This issue only regards the specific use case of displaying the modal and adding payment methods after they are selected in the checkbox list component.

## Screenshot

![Markup on 2021-04-09 at 16:40:57](https://user-images.githubusercontent.com/1759681/114197415-9d475d80-9952-11eb-9bb9-d1d70a9c55f5.png)

**Comment by naman03malhotra** [comment]
AFAIK, this is already implemented right, can we close this? please correct me if I am wrong.

**Comment by waclawjacek** [comment]
Yes! Looks like super-leftover. Thanks for catching this, @naman03malhotra!
