### ISSUE TITLE
Payment Request button: Support multiple shipping packages

### ISSUE THREAD

**Issue by ricardo** [Automattic/woocommerce-payments#1563]
Related to 1504-gh-woocommerce/woocommerce-gateway-stripe

This is an issue with the shortcode implementation and the blocks implementation. I'm not sure if it's possible to add multiple shipping packages to the Payment Request API, but at least there are some inconsistencies with the shipping descriptions in the PRB which needs to be fixed.

Steps to reproduce are detailed in the Stripe issue above.

**Comment by reykjalin** [comment]
This will be solved by https://github.com/woocommerce/woocommerce-gateway-stripe/pull/1591, and we should be able to port that fix over relatively easily. The critical piece of code there is in [`allowed_items_in_cart()`](https://github.com/woocommerce/woocommerce-gateway-stripe/pull/1591/files#diff-e2b9a082adab276b037cd70074b84f278c903bfed3c4b3d77a46aa04bcbfb78aR542-R549).

Once that's done it's just a matter of exposing that setting to both the Cart & Checkout block PRB integration and the shortcode flow — those are also addressed for Stripe in the same PR, so this should be a pretty easy copy-paste job 🙂
