### ISSUE TITLE
feat: disable WCPay confirmation dialog

### ISSUE THREAD

**Issue by frosso** [Automattic/woocommerce-payments#1564]
## Description
In the [new designs for the settings page](paJDYF-1cQ-p2), we want to display a confirmation dialog when the merchants wants to disable WCPay: paJDYF-1cQ-p2#disable-wcp

The warning should be displayed when the main WCPay payment method is going to be disabled in the list of gateways.

Please also implement the WC core changes: https://github.com/woocommerce/woocommerce/issues/29662

Please implement this behind the `WC_Payments_Features::is_grouped_settings_enabled()` feature flag.
Please note that it is acceptable to show the warning only after a WC core update.

One possible approach could be to trigger a DOM event, which WCPay could be listening to.
Another possible approach could be to use actions from `@wordpress/hooks`, which WCPay could be listening to.

## Related issue
~Blocked by https://github.com/woocommerce/woocommerce/issues/29662~

**Comment by c-shultz** [comment]
>I wanted to see how @c-shultz and @Ferdev feel about this implementation before I take it much further. It is future proof provided wc core keeps using jQuery and does not change the gateway_id parameter name.

Yeah, this looks like a good approach to me. My only concern would be that it fails gracefully if they changed something in WC core. It looks like this would just do nothing if something was reworked on the WC core end? If the confirmation just doesn't appear, that's not a major problem, so we should be good.
