### ISSUE TITLE
Order should be completed when SEPA payment is processed

### ISSUE THREAD

**Issue by harriswong** [Automattic/woocommerce-payments#1565]
### Summary
The order should be marked as "Completed" when the SEPA payment is processed.

### To reproduce
1. Place an order and checkout with SEPA payment
2. Go to WooCommerce order page `wp-admin/edit.php?post_type=shop_order&paged=1`, the order that was paid with SEPA payment is in "On Hold" instead of "Completed". 
![image](https://user-images.githubusercontent.com/572862/114620865-3f27bc80-9c69-11eb-92c6-f491ec705408.png)

**Comment by superdav42** [comment]
I'm pretty sure it's supposed to be 'on-hold' once the payment is made as this is how the stripe plugin works. We need to make sure that it does transition to processing when the funds are received.

**Comment by harriswong** [comment]
Instead of investigate, I updated the issue description to make sure order status is updated when payment is processed successfully.

**Comment by harriswong** [comment]
When we purchase with SEPA payments, the response will come back as `processing` and it is going to be put [on hold](https://github.com/Automattic/woocommerce-payments/blob/f2c134e1f7b4aaa7d0aa6de43a19284580bddee1/includes/class-wc-payment-gateway-wcpay.php#L829-L845). I see 2 ways of doing this, 

1. Explore webhook and add a hook to update the order status when the payment is updated from "processing" to "Succeeded".
2. We ping the server everytime we load the page.

Our existing gateway stripe addon requires a webhook to be configured. I am going to explore in the webhook direction next.
![image](https://user-images.githubusercontent.com/572862/114950678-cd8a7280-9e10-11eb-9bf5-eeeaa8b1a1ae.png)

**Comment by jrodger** [comment]
> Our existing gateway stripe addon requires a webhook to be configured. I am going to explore in the webhook direction next.

This is one of the advantages of WCPay over the Stripe gateway. The merchant can receive webhooks from the WCPay server with no extra setup, we handle incoming webhooks here:
https://github.com/Automattic/woocommerce-payments/blob/420e87346a5cddbbccd9dfb2749f0ee9e97c3c9d/includes/admin/class-wc-rest-payments-webhook-controller.php#L97

It should just be a case of configuring the WCPay server to forward the webhook you need, then handling it there (ping me if you can't find that bit on the server).

I think there might be some crossover with this issue as well https://github.com/Automattic/woocommerce-payments/issues/770. We might be able to fix both, or at least forwarding the event for this issue will make fixing the other one easier.
