### ISSUE TITLE
Connect more complex queries through to WPCOM transactions layer

### ISSUE THREAD

**Issue by allendav** [Automattic/woocommerce-payments#157]
Change WC_Payments_API_Client to pass more complex queries through to WPCOM; wire up filtering controls in SPA through to WC_REST_Payments_Transactions_Controller

Depends on https://github.com/Automattic/woocommerce-payments-server/issues/38

paJDYF-dc-p2

**Comment by jrodger** [comment]
We now have advanced filter controls on the transaction page, any other specific requirements can be created as new, separate, issues.
