### ISSUE TITLE
Provide more information to merchant about eligibility and deposits for Instant Deposits

### ISSUE THREAD

**Issue by ismaeldcom** [Automattic/woocommerce-payments#1586]
After some internal chats, we (@jessepearson and I) decide to create an issue to keep track of this, to debate the importance to have in the first version or pospone it, and the different approaches.

Related issue #1135

## The issue

For now, we only check if the user is elegible for instant deposits to show/hide the button. It's checked in the client [here](https://github.com/Automattic/woocommerce-payments/blob/fix/1140-inst-deposits-wpdata/client/deposits/overview/index.js#L181) and provided by the server [here](https://github.com/Automattic/woocommerce-payments-server/blob/add/instant-deposits-eligibility/server/wp-content/rest-api-plugins/endpoints/wcpay/class-deposits-controller.php#L310-L313).

For example, if the merchant already exceeded the daily limit, don't have enough instant deposit balance available, or are not elegible anymore only see a disable button (or hidden one) without any other information. And this could lead to support requests.

## How we can improve this

I have a suggestion for that, after reviewing some PR. But after talking with @jessepearson about this, he bring better idea, that makes more sense. We could leave the button enabled all the time and use the modal to show more information to the merchant. Like why they aren't elegible anymore or why they can't make another instant deposit.

### Eligibility
We already have a well defined `is_eligible_for_instant_deposits` method in the server, that returns true/false. But we can change it to return a message instead, so we can then show more information about eligibility to the merchant in the modal.

### Unable to use instant deposit

- Maybe show another overview card with the current available instant deposit balance and last date.
- Show why they are unable to make an instant deposit now. For example, not enough balance, already exceed daily limit...

**Comment by dwainm** [comment]
@ismaeldcom if you look at the number of IDs we're currently processing, do you still think investing more effort into the feature will be worth it?

**Comment by ismaeldcom** [comment]
Agree with you Dwain, not a priority with those numbers, we can always revisit it again if there is a need for it.
