### ISSUE TITLE
Fix Giropay transaction page

### ISSUE THREAD

**Issue by bborman22** [Automattic/woocommerce-payments#1587]
The transaction page for a Giropay transaction has several JS errors preventing it from loading. This is identical to the [Sepa issue](https://github.com/Automattic/woocommerce-payments/issues/1472) and the fix can be built out based on the [Sepa fix](https://github.com/Automattic/woocommerce-payments/pull/1579).

The goal of this issue is to successfully display the transaction page for Giropay transactions.

**Comment by c-shultz** [comment]
I'm bumping this back to the backlog since it's not a blocker for seeing a working checkout flow.
