### ISSUE TITLE
Update payment method icons

### ISSUE THREAD

**Issue by jarekmorawski** [Automattic/woocommerce-payments#1599]
Hi there!

While working on new payment methods in WooCommerce Payments I updated some that have already existed in the [repository](https://github.com/Automattic/woocommerce-payments/tree/develop/assets/images/cards).

To be more specific, I adjusted sizes (now they're consistent with each other and the upcoming icons for alternative payment methods) and swapped some outdated logos for new ones (Discover, Visa).

Do I have a green light to upload updated icons to the main repository? Are there any risks or dependencies I should be aware of?

![image](https://user-images.githubusercontent.com/79307566/115034450-cf653c00-9ecb-11eb-9dae-960d6a33b22e.png)

**Comment by RadoslavGeorgiev** [comment]
Hey @jarekmorawski

> Are there any risks or dependencies I should be aware of?

I don't think so. Code-wise, those icons are linked in a single (CSS) place, and used throughout the gateway. Replacing them should work without issues.

> Are there any risks or dependencies I should be aware of?

I cannot think of any, but I'm not sure what you have in mind. Could you provide an example of a dependency you have suspicions of? Maybe this will prompt me to check some other place.

> Do I have a green light to upload updated icons to the main repository?

Yes! Open a PR and we'll be glad to review it.

**Comment by zmaglica** [comment]
Looks like we have enough information to move this issue from the Engineering review queue. Moving it to the Ready for prioritization queue, as the part of the Gamma backlog porter duty to reduce the number of the issues in the Engineering review column.

**Comment by RadoslavGeorgiev** [comment]
**Note:** Seems like the SVGs can be found here: p1628873812040900-slack-C01TNBRTMEU

**Comment by jessy-p** [comment]
Closing as obsolete. Please create a new issue if required.
