### ISSUE TITLE
`Jest encountered an unexpected token` when running tests

### ISSUE THREAD

**Issue by jessepearson** [Automattic/woocommerce-payments#1602]
Getting errors when running tests locally:

```
    Jest encountered an unexpected token

    This usually means that you are trying to import a file which Jest cannot parse, e.g. it's not plain JavaScript.
...
    Details:

    /Users/j/sites/wcpay/wp-content/plugins/woocommerce-payments/client/tracks/index.js:25
      var recordFunction = window.wc?.tracks?.recordEvent ?? window.wcTracks.recordEvent;
                                     ^

    SyntaxError: Unexpected token '.'

      40 | import TransactionsFilters from '../filters';
      41 | import Page from '../../components/page';
    > 42 | import wcpayTracks from 'tracks';
         | ^
```

It appears to not be liking the [change introduced here](https://github.com/Automattic/woocommerce-payments/commit/8ca39d3df4314d878630d9fde43513a80ae6c63c#diff-4f2a4d45f09807deba2600a2226ca812b4a30912507adc1bd0c0bf2ffd6e3681R18). I brought this up in Slack ( ) and @jrodger mentioned it looks like it's the Node version that needs to be updated in `.nvmrc` from 12 to 14. 

This didn't affect what I was working on at the time, but James mentioned:

> We should update `.nvmrc` if the minimum version of node has changed (also assuming that syntax is transpiled properly and we haven’t affected our browser support)

**Comment by jrodger** [comment]
> also assuming that syntax is transpiled properly and we haven’t affected our browser support

This part is fine. I tested on a few browsers that wouldn't support it without our build doing the transpiling.

**Comment by jessepearson** [comment]
Closing due to this is outdated and I haven't seen it again for some time.
