### ISSUE TITLE
Payment intention: what happens if amount is 0 or less

### ISSUE THREAD

**Issue by v18** [Automattic/woocommerce-payments#161]
We are currently checking if the amount is greater than 0, and only then allowing the payment intention creation to go through.

Do we need to check for this amount at all? The server will respond with an error if the amount is 0, no?

If we do want to check, what should be the appropriate action to take instead of nothing? Ref: 

Before #133:

https://github.com/Automattic/woocommerce-payments/blob/0e650426d400e032703f8b7419d4b982a07e3443/includes/class-wc-payment-gateway-wcpay.php#L239

In #133 we silently fail:

https://github.com/Automattic/woocommerce-payments/blob/694124a4a34ce976253254b1b1fb7d3030295d62/includes/class-wc-payment-gateway-wcpay.php#L220

**Comment by vbelolapotkov** [comment]
The case for zero amount is handled here: https://github.com/Automattic/woocommerce-payments/blob/8ddd87061a9bdffac4ff30ac4dddd6a37ccf9438/includes/class-wc-payment-gateway-wcpay.php#L978-L978

However, there is potentially wrong assumption that if $amount is not > 0 it is 0. I.e. it will handle negative amounts in a wrong way. Not sure if negative amounts are possible at all, but this would need to be double-checked as part of this issue.

**Comment by vbelolapotkov** [comment]
depends on investigation with #712

**Comment by jrodger** [comment]
Our handling of 0 amount checkouts has matured a lot since this issue was opened. I'm closing this one and would suggest any new queries / bugs on this topic can be logged on new issues.
