### ISSUE TITLE
`WC_Payment_Gateway_WCPay` constructor runs twice when SEPA enabled

### ISSUE THREAD

**Issue by jrodger** [Automattic/woocommerce-payments#1614]
This causes issues like #1604, mainly due to all the filters that get setup at the end of the constructor.

I'm creating a separate issue to look at these as a whole because the solution is going to be different in each case.

* Some should only run for the "Card" gateway, these could be moved to the new sub-class.
* Some should run once regardless of the gateways enabled, like the test mode notification. These could be bumped up a level, or de-dupped some other way.
* I haven't looked at all the filters, there might be other scenarios we need to consider.

**Comment by htdat** [comment]
I think this issue is ready to prioritize?

**Comment by jessy-p** [comment]
It looks like the code has been refactored and this should not be happening anymore. We have to test and confirm that.
