### ISSUE TITLE
SEPA-specific settings screen

### ISSUE THREAD

**Issue by c-shultz** [Automattic/woocommerce-payments#1628]
Add settings screen (if needed) for Sepa

Blocked until https://github.com/Automattic/woocommerce-payments/issues/1507 finishes

**Comment by waclawjacek** [comment]
I am removing the `status: blocked` label because #1507 was merged today.

**Comment by brezocordero** [comment]
Blocked until decision on UPE

**Comment by frosso** [comment]
No longer needed - with UPE we don't need setting screens for each payment method anymore.
