### ISSUE TITLE
After a failed payment, handle the user resubmitting the checkout form

### ISSUE THREAD

**Issue by v18** [Automattic/woocommerce-payments#163]
This is related to a bug (?) on checkout. Try these steps to repro:

1. Make sure that an exception will be caught in `process_payment`
2. Submit the checkout form
3. See that an error is displayed
4. Without reloading the page or using new credit card details, submit the checkout form
5. See that the cart was submitted immediately, with the previous paymentIntention details still in the form.

Instead we should update the payment intention with the new payment attempt.

**Comment by vbelolapotkov** [comment]
Closing since cannot reproduce. Intent id changes with every submit attempt.
