### ISSUE TITLE
Spike: Sepa emails

### ISSUE THREAD

**Issue by c-shultz** [Automattic/woocommerce-payments#1631]
We need to ensure that Stripe is correctly handling the requirement to email Sepa customers after a payment is charged.

As part of this effort, we should also determine if emails are correctly translated depending on user locale.

**Comment by harriswong** [comment]
More info here: https://stripe.com/docs/payments/sepa-debit#debit-notification-emails

**Comment by harriswong** [comment]
According to the [Stripe doc](https://stripe.com/docs/payments/sepa-debit#debit-notification-emails), emails should be sent automatically. I am not sure why I am not seeing the email even though the order is received. 

**Is email address valid? Is Stripe not sending email for our test payments?**
If I go into Stripe dashboard and manually click the "send receipt" link, I do get a receipt email. Maybe "receipt" is not the same as "debit notification". 

**Next step**
I'm going to check if there are specific settings that is required to enable debit nofitication.

**Comment by harriswong** [comment]
From Stripe's [receipt doc](https://stripe.com/docs/receipts), it seems like emails are sent automatically in test mode:
![image](https://user-images.githubusercontent.com/572862/116124694-dafdf300-a681-11eb-9fac-c23dc83b883d.png)

**Comment by harriswong** [comment]
#### Spike output
Stripe sends SEPA debit notification automatically by [default](https://stripe.com/docs/payments/sepa-debit#debit-notification-emails).

Stripe only supports [these languages](https://support.stripe.com/questions/language-options-for-customer-emails) for email. 

ref: paJDYF-1us-p2

**Comment by c-shultz** [comment]
Closing this since the spike is done
