### ISSUE TITLE
Transactions and deposits counts on the table summary are rendered as "undefined" while the data is loading.

### ISSUE THREAD

**Issue by naman03malhotra** [Automattic/woocommerce-payments#1639]
The following behavior is applicable for both Transactions and Deposits tables.

Presently we render the number of transactions and deposits in the summary section of the respective tables. While the data is being fetched from the server the count is rendered as `undefined`.

<img width="973" alt="Screenshot 2021-04-21 at 3 42 00 AM" src="https://user-images.githubusercontent.com/15019298/115471350-7263e000-a255-11eb-977d-4332c19c7ca1.png">
<img width="977" alt="Screenshot 2021-04-21 at 3 56 33 AM" src="https://user-images.githubusercontent.com/15019298/115471523-be168980-a255-11eb-8ecd-831a67aa6139.png">

The same issue can be replicated if the WCPay server is not running and still being proxied by WCPay dev plugin, i.e When API call is failing which results in `depositsSummary` being an [empty object](https://github.com/Automattic/woocommerce-payments/blob/cbfc71927444732ac01e973f9c8ebda8f399611d/client/deposits/list/index.js#L73).

**Steps to reproduce:**
- goto `develop` branch.
- try loading deposits or transactions page, and watch the table summary (bottom of the table).
- you should see `undefined` transaction while the table data is being loaded.

**Potential solutions:**
1. We can hide the summary from being rendered all together, until we have the final data to display.
2. We can keep the default count as Zero always.

**Comment by naman03malhotra** [comment]
As discussed in the slack thread p1618933953413800/1618863954.403900-slack-CGGCLBN58 and https://github.com/Automattic/woocommerce-payments/issues/97#issuecomment-823371878 we are leaning toward displaying zero while empty state, which is consistent with our other analytics screen. I am thinking the same, wanted to confirm before I implement the fix.

cc @jrodger @LevinMedia

**Comment by jrodger** [comment]
> which is consistent with our other analytics screen

This makes sense as a general approach to me.

**Comment by LevinMedia** [comment]
@naman03malhotra while we're showing the loading state - can we use the preview shape with the pulse to represent that data until it loads? (just like the data in the table above)

**Comment by naman03malhotra** [comment]
>can we use the preview shape with the pulse to represent that data until it loads? (just like the data in the table above)

@LevinMedia I went through the codebase and came to know that component responsible to render the footer of the table is `TableSummary` which doesn't support skeleton loading at the moment. Right now it just takes whatever data is being passed to it and renders it, including falsy data (`undefined`, `null` etc).

We can take one of the following approaches to fix this issue.
1.  Render zero until the data is being loaded. 
2. We do not render the summary (footer content) at all unless the data to render is available.
3. We can make changes to the `TableSummary` and add the support for the skeleton loader while the data is being fetched.

1st & 2nd are relatively faster to implement and push than 3rd.

IMO, we can go with either 1st or 2nd to fix this issue immediately and eventually go for 3rd. I can create a separate issue in WCAdmin repo(as components reside there) and work on it, meanwhile, I can work on the quick fix.

I like the suggestion for the 3rd, as it is consistent with the rest of the loading pattern. The fix for 3rd will look something like this:
<img width="888" alt="Screenshot 2021-04-23 at 2 47 28 AM" src="https://user-images.githubusercontent.com/15019298/115788343-1d54d500-a3e1-11eb-8a9a-ad030774d814.png">
