### ISSUE TITLE
Payment Intent: Update the intent on every submission of the form

### ISSUE THREAD

**Issue by RadoslavGeorgiev** [Automattic/woocommerce-payments#164]
Context: https://github.com/Automattic/woocommerce-payments/pull/133#discussion_r309291452 

> We should update the intention before every submission of the form (which is not done by us), because in the meantime the data in the form could change and we'll need to update either the amount (at least because of shipping options) or user details (in case they changed their input).

**Comment by vbelolapotkov** [comment]
@RadoslavGeorgiev correct me if I'm wrong but I think this was fixed. Closing for now
