### ISSUE TITLE
fix: z-index when drag & dropping items

### ISSUE THREAD

**Issue by frosso** [Automattic/woocommerce-payments#1652]
## Description

Applies to the redesign of the settings.
Discussed here: p1618262788012300-slack-C01RTUVR81K

When dragging an element in a list, the siblings that are in the DOM after the element being dragged will appear on top.
Tried many things: z-index, translate3d on the z-axis - nothing. And the thing is, this problem does not persist itself when I isolate the code to a JSFiddle.
Because of that, I think it’s related to some other CSS being applied and I’m going to write a separate ticket (since it seems pretty minor).

![2021-04-12 16 22 50](https://user-images.githubusercontent.com/273592/115629248-a11a9e80-a2c7-11eb-9769-da6e13e80d7d.gif)

**Comment by tpaksu** [comment]
Hi @frosso, 

I couldn't reproduce this, what I see is this:

![Screen Capture on 2021-06-03 at 11-19-23](https://user-images.githubusercontent.com/3295/120620109-4eefa000-c465-11eb-9573-7a37b2c8f19f.gif)

And this doesn't have a z-index issue. Can you confirm if this is fixed or there's some extra steps to do to reach to that interface?

Thanks.

**Comment by frosso** [comment]
Thanks for checking @tpaksu - The drag & drop library has been removed from WCPay - this can be closed :)
