### ISSUE TITLE
Dispute resolution task

### ISSUE THREAD

**Issue by samueljseay** [Automattic/woocommerce-payments#1658]
This is to implement the new dispute resolution task as part of the task list in the WC Pay overview screen. (For detailed designs see paJDYF-18j-p2)

![Screenshot 2021-04-22 at 1.36.16 PM.png](https://images.zenhubusercontent.com/5ef92fa5c1c43622578a0d39/076640cc-c0c2-4eed-aa35-b24df49690d1)

It is dependent on the task list being implemented in #1656

Requirements:

- [ ] Required analytics tracking TBD
- [ ]  categorized as an L3 task
- [ ] If merchant doesn’t respond to a dispute in the specified time frame, the task should be marked as complete with a slight change to the description line to indicate that it was accepted automatically. TBD copy and time frame for this.
- [ ] Clicking the task takes you to the specific dispute for resolution. 

cc @pmcpinto 

Question: does completing the dispute redirect you back to the overview? We'll have to investigate the current behaviour in wc-pay

**Comment by louwie17** [comment]
There is a [disputes wp data package](https://github.com/Automattic/woocommerce-payments/tree/develop/client/data/disputes) that provides a selector to `getDisputes`.

**Comment by jeffstieler** [comment]
This looks really straightforward to me. Estimate: 1

**Comment by jeffstieler** [comment]
Removed my assignment for now since I'll be picking up the task list item expansion (and A/B test) work again.

**Comment by LevinMedia** [comment]
@octaedro good questions!

>As far as I can see, this card shows one dispute, which means that the user will see a dispute card for each dispute that they have. Am I correct?

Correct, for now. We may need to re-think this in the future and roll multiple disputes into a single notice. 

>Also I'm seeing that the design is showing the numbers in the date as an ordinal (E.g.: February 28th) but on the dispute's page, we're showing the date with a cardinal number (just the number). In order to show the same information always in the same way, what do you think about showing the numbers in the date with a cardinal number?

That's a good catch - can you use the string that's in the dispute response overview screen - it also includes time of day:

`Respond by: Jun 20, 2021 - 4:59PM`

>Should the click on the task have the same behavior as a click on an item, on the Disputes table in the Disputes section?

Yes please! It should link directly to the dispute's overview screen - same behavior as clicking a dispute in the table.

**Comment by octaedro** [comment]
Great @LevinMedia,
I'll apply the changes you suggested.
Thank you 🙂

**Comment by octaedro** [comment]
Hi @LevinMedia
I have another question to ask:
- Just to confirm, will we show only disputes with status `warning_needs_response` and `needs_response`?

If that would be the case we never will show a dispute resolution task as `complete`, (like the image below) is that expected?
![screenshot-fermarichal jurassic tube-2021 06 11-13_16_16](https://user-images.githubusercontent.com/1314156/121717233-56dbbf80-cab7-11eb-9c9e-94a7f936d7aa.png)

**Comment by LevinMedia** [comment]
Hi @octaedro ! Once a task is completed, it should no longer appear in the main "things to do" section, however, it should appear as you have it shown above in the "completed tasks" view of the component, along with any other tasks that have been completed. 

"Show completed tasks" should be available through an elipsis menu in the header of the section, of the component. That said, it doesn't look like that functionality is in the build yet, at least going by the screen shot you provided above. The @elizaan36 covered designs for this functionality in pbIJXs-IQ-p2

**Comment by elizaan36** [comment]
ah yep @LevinMedia to start out we decided to keep the completed tasks in the list but moved to the bottom, rather than creating a new view for completed tasks. So in this case each dispute would appear as a completed task in the list until deleted.

(In the call this morning I mistakenly thought we had implemented the ellipses menu with completed tasks view but that's going to be saved for a future update.)

Here's the design:
<img width="524" alt="Screen Shot 2021-06-14 at 4 22 16 PM" src="https://user-images.githubusercontent.com/5121465/121961206-ba225780-cd2c-11eb-917a-3f84cb81230a.png">

The ellipses menu only has the "Hide" action for the card. @octaedro so the only updates to the screenshot you shared would be:
- Ellipses for each task (Remind me later, Dismiss for incomplete tasks) (Delete for complete tasks)
- Ellipses for card menu (Hide) unless we don't want to allow hiding the task list on the payments overview
- Completed tasks are moved to the bottom of the list

**Comment by octaedro** [comment]
Hi @samueljseay,
I'm adding the latest changes for this functionality and I have a question related to this point:

> If merchant doesn’t respond to a dispute in the specified time frame, the task should be marked as complete with a slight change to the description line to indicate that it was accepted automatically. TBD copy and time frame for this.

Do we have the code to mark the dispute as `Accepted` automatically? (I mean, when the merchant doesn’t respond to the dispute in the specified time frame).

I thought that it was done but I couldn't find the code that does that.

**Comment by mattsherman** [comment]
Closing this in favor of #2712, which reflects the change in requirements and design (from a single task per dispute to one task for all open disputes).
