### ISSUE TITLE
"Setup Apple Pay for WooCommerce Payments" task

### ISSUE THREAD

**Issue by samueljseay** [Automattic/woocommerce-payments#1659]
This is to implement a new task list item for setting up Apple Pay. (For detailed designs see paJDYF-18j-p2)

It is dependent on the task list being implemented in #1656

![Screenshot 2021-04-22 at 1.41.20 PM.png](https://images.zenhubusercontent.com/5ef92fa5c1c43622578a0d39/a4ebcd88-f460-44db-a555-30ae87c54929)

Requirements
- [ ] Only show in US stores
- [ ] TBD what clicking this task item does
- [ ] TBD what analytics tracking is required
- [ ] TBD what conditions determine the task is "complete"

**Comment by louwie17** [comment]
Does this task have any limitations on when it could be shown? only specific countries? etc?

**Comment by timmyc** [comment]
Great question @louwie17 - the one resource I know of about payment methods that details what should be shown to which country is [this spreadsheet](https://docs.google.com/spreadsheets/d/1bpSWxumWp3Sfo9yho4Nf18TIJsJfmE95PpGx2EdSCfU/edit?usp=sharing) but the ApplePay portion of wcpay is not detailed there. cc @bmccotter for any direction on this.

**Comment by bmccotter** [comment]
Apple Pay isn't included on this list @timmyc @louwie17 since it is a Payment Option / Method accessed or unlockable via a PSP, such as WCPay. I'm all for including this in the task list. US to start, and then we can add more markets once we go international. Does that work?

**Comment by samueljseay** [comment]
> US to start, and then we can add more markets once we go international. Does that work?

Sounds great to me, I'll update the details to reflect this.

@pmcpinto @elizaan36 pinging you, because a lot of these tasks have TBD around analytics tracking, and behaviour, could we get some more fleshed out details on these.

**Comment by elizaan36** [comment]
Just a note that Apple Pay is already getting some love with an Inbox note - imo including the setup task as well would be redundant considering they'd both appear on the same screens (WC home and Overview.)

<img width="882" alt="image" src="https://user-images.githubusercontent.com/5121465/116962731-6d972700-ac6c-11eb-8e1c-e8466bfa9996.png">

The CTA "Add Apple Pay" takes you to the WCPay welcome screen if it's not set up, and to WCPay Settings when it is enabled.

**Comment by samueljseay** [comment]
@elizaan36 ok cool. Shall we shelve this one then?

**Comment by elizaan36** [comment]
Yeah, since Apple pay is a feature announcement/ informational it should be an Inbox note anyway. It's not technically "extension activity".
