### ISSUE TITLE
"Finish setting up WooCommerce Payments" task

### ISSUE THREAD

**Issue by samueljseay** [Automattic/woocommerce-payments#1660]
This is to implement the "Finish setting up WooCommerce Payments" task in the new task list. (For detailed designs see paJDYF-18j-p2)

This is dependent on completion of #1656

![Screenshot 2021-04-22 at 1.49.42 PM.png](https://images.zenhubusercontent.com/5ef92fa5c1c43622578a0d39/1a3c83ae-b181-4767-9fa7-82c00e0f0ac0)

Requirements:

- [ ] TBD what analytics tracking we should do
- [ ] TBD what happens when clicking this task
- [ ] Should be styled as L2 priority

**Comment by samueljseay** [comment]
@elizaan36 @pmcpinto pinging you, I'm keen to get some more detail here, specifically, the behaviour when clicking the task and also what analytics tracking we need.

**Comment by elizaan36** [comment]
This task will overlap with the new "Finish setup" card that would appear on the overview screen when the user hasn't finished setup, so imo we can remove. Example of the potential design in "preview mode".

![WCPay overview](https://user-images.githubusercontent.com/5121465/116963227-df23a500-ac6d-11eb-9102-de6f77ad611a.png)

**Comment by samueljseay** [comment]
@elizaan36 Ok I'll shelve this one then
