### ISSUE TITLE
Inbox notifications in overview screen (as part of WCPay overview v2)

### ISSUE THREAD

**Issue by samueljseay** [Automattic/woocommerce-payments#1662]
This covers the work needed to display wc pay specific notifications in the overview screen. (For detailed designs and discussion see paJDYF-18j-p2). **Note that the designs are out of date now because the intent is to display this inline on the page. If you want a design to work from, assume the look and feel should match the inline notifications in wc-admin.**

I think we need to do some exploration work or a spike to determine how this will be integrated with or share code from the woocommerce-admin notifications.

cc @pmcpinto 

Requirements

- [ ] Display wc-pay specific notifications inline in the new wc pay overview screen
- [ ] TBD analytics required?

**Comment by samueljseay** [comment]
A brief look at this reminds me that we have the notes store available in `@woocommerce/data`. (thank you @joshuatf !) I think its probably perfect for this. The markup for the list of inbox items is quite simple, so I'm hesitant to publish more components just yet.  So this would be a matter of a couple new components in `@woocommerce/payments` and an integration with the `@woocommerce/data` notes store.

There are just a couple things we need to resolve here:

1. This **will** need to be switched off if wc-admin version is not recent enough, because notes relies on a wc-admin rest API so even if we bundled this component it wouldn't be able to get access to the notes API. **Although** one other way around this could be to adjust the notes data store to make sure it returns no data instead of crashing if it tries to get data from a non-existent API.

2. We need to filter by wc pay specific notes, We just need to investigate if the data structure of notes supports this kind of filtering.

**Comment by elizaan36** [comment]
👋 The Inbox (filtered to show only WC Pay-related) would appear in-line on the overview screen but the Inbox panel wouldn't also appear as it would be redundant.

**Comment by samueljseay** [comment]
Thanks @elizaan36 I'll update the description to reflect this.

**Comment by louwie17** [comment]
@elizaan36 what is potential likely hood of the Inbox 2.0 designs going through and these designs also being used in the WC pay overview screen for the inbox notifications?
As these designs overlap a lot with the task list, and don't want to put all the effort into using the old designs, when the new designs are coming.
cc: @LevinMedia

**Comment by elizaan36** [comment]
Good question! @pmcpinto, do you see any potential bandwidth in the near future to tackle the Inbox updates in `pbIJXs-OX`? 

@louwie17 I know we're doing some backlog grooming tomorrow and will discuss the Inbox update as it relates to promoting WCPay. To be safe I'd say move forward with the old Inbox note design but I think we'll have a more definitive answer tomorrow.

**Comment by louwie17** [comment]
*I asked this in Slack as well (p1623775742051000-slack-CGGCLBN58 ), but will do here as well:
@LevinMedia currently the WC Pay notes are configured to stay displayed after a [user clicks on an action](https://github.com/Automattic/woocommerce-payments/blob/develop/includes/notes/class-wc-payments-notes-set-https-for-checkout.php#L61), meaning the note will only disappear if it specifically dismissed.
I was curious if this is expected behaviour?

We usually default to the note being set to `actioned` upon the action click, which makes the note disappear.
