### ISSUE TITLE
Instant Deposits design tweaks

### ISSUE THREAD

**Issue by jessepearson** [Automattic/woocommerce-payments#1666]
@DanReyLop, I spoke with @LevinMedia about the look and flow of submitting an instant deposit and he had some feedback:

1. Instant Deposit should always show and just be disabled when not available.
2. The close button on the modal isn't needed.
3. The percentage shown in the modal and deposit overview should match the amount on the server.
4. ~Single deposit overview should match design. This may be in progress elsewhere.~ Moved to https://github.com/Automattic/woocommerce-payments/issues/1678

![Screen Shot 2021-04-22 at 12 57 28 PM](https://user-images.githubusercontent.com/4634416/115746051-6289f000-a36a-11eb-90ba-d35fd2f13344.png)

I will get working on 1 & 2.
For 3, I can set the value in the client to be static for now, but can create a PR to be merged once the server can pass a variable for it.

For 4, I am going to need to find out if someone is already working on this.

**Comment by DanReyLop** [comment]
> For 3, I can set the value in the client to be static for now, but can create a PR to be merged once the server can pass a variable for it.

The server can pass the fee % to the client, or the client can just calculate it (`100 * fee / total`). Any of those solutions will work if we don't get "creative" with the fee :)

**Comment by jessepearson** [comment]
@LevinMedia moved number 4 above to https://github.com/Automattic/woocommerce-payments/issues/1678

**Comment by LevinMedia** [comment]
> Instant Deposit should always show and just be disabled when not available.

To clarify this - it should always be visible **only after** the merchant qualifies for and has enabled instant deposits. 👍 Merchants that aren't eligible for instant deposits should never see the button. 

@jessepearson @DanReyLop

**Comment by DanReyLop** [comment]
@LevinMedia Thanks for clarifying, it was definitely needed :)

So, the only times when a merchant will see a disabled button is when they're eligible, have a debit card as a payout destination, **but** they don't have any pending transactions or they already deposited the maximum amount today. Is that correct?

**Comment by LevinMedia** [comment]
@DanReyLop That's correct!
