### ISSUE TITLE
Empty States Preview Mode

### ISSUE THREAD

**Issue by pmcpinto** [Automattic/woocommerce-payments#1679]
*Note: See the Preview Mode project thread (paJDYF-1rg-p2), as well as individual stories in this epic, for more details.*

**Comment by mattsherman** [comment]
Thanks @pmcpinto !

**Comment by jrodger** [comment]
Just throwing out a wild idea, but we already have a way to inject different clients for fetching data. We have the "normal" Jetpack one, but then if the plugin is running on WPCOM that gets filtered to use something slightly different ([src](https://github.com/Automattic/woocommerce-payments/blob/e1da77811acfc3488ffef85c0a777f81a93807a6/includes/class-wc-payments.php#L505)).

I'm wondering if we can swap that out for this use case and have a "preview" client return hard coded data or data derived from other local data.

I can't decide if this idea is abusing that filter or not just yet...anyway, something to think about perhaps.

**Comment by mattsherman** [comment]
@jrodger Thanks for sharing that idea. I'll be sure to give it some thought! @timmyc had a somewhat similar thought when he did the initial investigation, injecting some logic in [`WC_Payments_REST_Controller::forward_request`](https://github.com/Automattic/woocommerce-payments/blob/develop/includes/admin/class-wc-payments-rest-controller.php#L48-L56) to detect when preview mode is active and act accordingly.

**Comment by mattsherman** [comment]
I've updated the main description and added child stories to this epic. It is still a draft, as we are still finalizing the scope and design for this project.

**Comment by deepakpathania** [comment]
Closing this since all the linked issues for the epic have been closed, please feel free to re open in case there are more stories to be tracked as a part of this.
