### ISSUE TITLE
Payment intent should accept 'card' as payment method types without SEPA feature flag

### ISSUE THREAD

**Issue by harriswong** [Automattic/woocommerce-payments#1683]
### Description

It makes more sense that `Payment_Method::CARD` is outside of the SEPA feature flag code: https://github.com/Automattic/woocommerce-payments/blob/develop/includes/wc-payment-api/class-wc-payments-api-client.php#L188

According to [Stripe doc](https://stripe.com/docs/api/payment_intents/create#create_payment_intent-payment_method_types):

> If this is not provided, defaults to [“card”].

The existing code does not introduce any bugs since It defaults to use `'card'`. 

### Propose change
From
```
if ( WC_Payments_Features::is_sepa_enabled() ) {
			$request['payment_method_types'] = [ Payment_Method::CARD, Payment_Method::SEPA ];
...
```

To:
```
$request['payment_method_types'][] = Payment_Method::CARD;
if ( WC_Payments_Features::is_sepa_enabled() ) {
			$request['payment_method_types'][] = Payment_Method::SEPA ;
...
```

**Comment by harriswong** [comment]
We should also make sure that if SEPA is the only payment method, the payment_intent will work. In this case, it makes sense to me to not include `Payment_Method::CARD`.

**Comment by bborman22** [comment]
The move to UPE closes this issue as no longer needed.
