### ISSUE TITLE
Add new payment methods as source in transactions page

### ISSUE THREAD

**Issue by superdav42** [Automattic/woocommerce-payments#1711]
SEPA, Giropay etc icon should appear in the source field on the transaction page. Right now it's just blank for these payment methods.
![image](https://user-images.githubusercontent.com/1534605/116930647-436a4880-ac1d-11eb-8fa3-be6c4004ed84.png)

**Comment by FangedParakeet** [comment]
This appears to be resolved for me right now: perhaps this was achieved with Automattic/woocommerce-payments-server#819, but I can see the correct icons appearing for new payment methods (specifically giropay, Sofort, & SEPA) on my local environment.
