### ISSUE TITLE
[GlobalStep] Columns are misaligned on Payments->Transactions/Disputes page

### ISSUE THREAD

**Issue by gglobalstep** [Automattic/woocommerce-payments#1719]
## Bug Description:
"Fees/Net/Order#/Source/Deposit" columns are misaligned on "Payments->Transactions" page
"Status/Reason/Order #/Source/Respond by "columns are misaligned on "Payments->Disputes" page

## Environment:
Woocommerce Version : WooCommerce 5.2.2 
WooCommerce Payments: v2.4.0
WooCommerce Subscriptions: v3.0.12
WordPress version: (v5.7)

**PC**:
Windows 10, Mac 10.14.6
Chrome(Version 90.0.4430.93) 
Firefox(Version 87.0)
Safari: v13.1.1

## Steps To Reproduce:
1. Create any test site using JN site.
1. Install and activate all the required plugins 
1. Complete the onboarding setup wizard setup 
1. Go to Plugins->Add New and upload the zip files for WooCommerce Payments v2.4.0 plugin
1. Activate WooCommerce Payments v2.4.0 
1. Complete the wooCommerce Payments setup
1. Complete "Get ready to start selling" section on WooCommerce->Home Page
1. Purchase products from front-end
1. Go to WooCommerce->Orders page and check all the orders are with "Processing" status
1. Go to the "Payments->Transactions" page
1. Note that "Fees/Net/Order#/Source/Deposit'" columns are misaligned on the "Payments->Transactions" page
1. Go to the "Payments->Disputes" page
1. Observe that "Status/Reason/Order #/Source/Respond by "columns are misaligned on "Payments->Disputes" page

## Actual Result:
 Columns are misaligned on Payments->Transactions/Disputes page

## Expected Result:
Columns should be properly aligned on the Payments->Transactions/Disputes page

## ScreenShot:
![#1719_Disputes](https://user-images.githubusercontent.com/41110392/117022977-5280f180-ad16-11eb-806f-fb20230394af.png)
![#1719_Transactions](https://user-images.githubusercontent.com/41110392/117022992-54e34b80-ad16-11eb-8dc4-2cc68db4155d.png)

**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Comment by naman03malhotra** [comment]
Thanks, @gglobalstep for reporting this.

I took a closer look at this, and some items are misaligned, to fix this I'll align the table items in the center except the numeric values (cost and fees) which should be right aligned as they are more readable that way.

**Comment by gglobalstep** [comment]
The same issue is observed on the **"Transactions->Deposits" Page** as well 

**Environment:**
Woocommerce Version : WooCommerce 5.2.2 and 5.3 RC 2
WooCommerce Payments: v2.4.0-test-3
WordPress version: (v5.7)

**PC:**
Windows 10, Mac 10.14.6
Chrome(Version 90.0.4430.93) 
Firefox(Version 87.0)
Safari: v13.1.1

**Attachment:** 
![Screen Shot 2021-05-11 at 6 37 44 PM](https://user-images.githubusercontent.com/41110392/117826630-f0803900-b28d-11eb-9619-a2cae35d35a2.png)
