### ISSUE TITLE
Spike: UPE - Applying CTA styles to payment tabs

### ISSUE THREAD

**Issue by bborman22** [Automattic/woocommerce-payments#1722]
One area that needs more exploration is the styling of the "Tabs" or payment type selectors on the UPE. The current [iteration](https://github.com/Automattic/woocommerce-payments/pull/1703) just uses the input styles for the tabs and it could use more refinement. The current suggestion was to use a CTA, the Place Order button in particular, to get some styles for the currently selected payment tab.

@jarekmorawski's suggestions are below:

- Selected tab
    - Uses theme’s CTA button background color
    - Uses theme’s CTA button border style
    - Uses source font (same as unselected tab but increased weight)
    - Unselected tab
- Hardcoded background color (in case we’d have some ready-made themes, it’d probably have a few different hardcoded values, f.e. light or dark).
    - Hardcoded border style
    - Uses source fonts 

![payment-tabs](https://user-images.githubusercontent.com/68524302/117037665-be426a80-acd4-11eb-9a10-347fc2d5d663.png)

The CSS selector to target these tabs are:
- .Tab for unselected
- .Tab--selected for selected 
- Also accepts :hover, :focus, :active, :disabled, but there is another spike to explore how best to handle the state styles, so these states should not be a :focus on this issue.

The [draft PR](https://github.com/Automattic/woocommerce-payments/pull/1703) should provide a good starting point to work from with minimal set up required.

**Comment by brezocordero** [comment]
Closed with paJDYF-1vP#comment-5865
