### ISSUE TITLE
Spike: UPE - Getting element state styles

### ISSUE THREAD

**Issue by bborman22** [Automattic/woocommerce-payments#1724]
While researching the ability to style the UPE elements to match the store's theme, a gap was found in trying to get the element styles for different states. Our baseline automated approach relies on [getComputedStyle](https://developer.mozilla.org/en-US/docs/Web/API/Window/getComputedStyle) which essentially [takes in an element and returns the styles](https://github.com/Automattic/woocommerce-payments/blob/dab57024c7d27d8919a8bf0e91c4cf2579a799f6/client/checkout/classic/index.js#L576-L592) that are currently applied to that element. This spike is focused on getting the element's styles for different states like :hover, :focus, :active, :disabled. Unfortunately, unless the element passed into getComputedStyle is currently in that state, these styles are not returned.

Some ideas to get things started, though other ideas are more than welcome:

- Briefly spoofing the state, grabbing the styles and then removing the state.
- Using a hidden element or container of elements with all the states applied to pull from.
- Having another page act as a style guide to pull the styles from.
- Parsing the styles using something like [document.styleSheets](https://developer.mozilla.org/en-US/docs/Web/API/Document/styleSheets)

The other part to this spike would be in getting error or invalid state styles as well. While the above states are a little bit easier to spoof with a pseudo class, the error state could be a little bit trickier depending on how the theme handles error classes. The end goal would be the same, but some of the ideas above might need modification to get the error state as well.

The following are the possible selectors we can target within the UPE:

| Class Name | States | Psuedo Classes | Psuedo Elements |
| --- | --- | --- | --- |
| .Label | --empty, --invalid | | |
| .Input | --empty, --invalid | :hover, :focus, disabled, autofill | ::placeholder, ::selection |
| .Error | | | |
| .Tab | --selected | :hover, :focus, disabled, autofill | |
| .TabIcon | --selected | :hover, :focus, disabled, autofill | |
| .TabLabel | --selected | :hover, :focus, disabled, autofill | |

The [draft PR for styling UPE](https://github.com/Automattic/woocommerce-payments/pull/1703) is a good starting point to minimize any set up time.

**Comment by brezocordero** [comment]
Closed with paJDYF-1vP-p2#comment-5997
[Draft PR](https://github.com/Automattic/woocommerce-payments/pull/1765/files).
