### ISSUE TITLE
Buttons and modals for auth capture and cancel

### ISSUE THREAD

**Issue by dechov** [Automattic/woocommerce-payments#173]
As presented by @LevinMedia in paJDYF-dz-p2, for "On Hold" orders with an uncaptured charge:

- “Void Authorization” and “Capture Charge” buttons in order details pane
- Modals
  - Capture confirmation (with status change dropdown)
  - "Capture amount too high" error
  - Void confirmation
- Capture & cancel actions _triggered by_ status change, for consistency with existing gateways?

**Comment by vbelolapotkov** [comment]
@LevinMedia do you know if this is still relevant?

**Comment by LevinMedia** [comment]
@vbelolapotkov yes indeed, I think they're still quite relevant!

**Comment by vbelolapotkov** [comment]
Ok, sending issue to prioritization then.

**Comment by kalessil** [comment]
Closing in favor of #5712: we are handling the status transition into 'cancelled', but the referenced ticket additionally suggests to do similar for 'complete' status (superseding this issue).
