### ISSUE TITLE
Use @wordpress/data in Add payment method modal

### ISSUE THREAD

**Issue by waclawjacek** [Automattic/woocommerce-payments#1732]
Use the data store from `@wordpress/data` to retrieve the list of enabled payment methods in the Add payment method modal.

![Markup on 2021-05-05 at 18:19:30](https://user-images.githubusercontent.com/1759681/117174845-730c8280-adce-11eb-8864-cba53eed25ab.png)

The work here can be based on #1647.

## Additional matters

While working on this issue, answers to the following questions should also be included:

1. Should all available payment methods be displayed in the modal or just the ones that aren't yet enabled? Currently all methods are displayed but the designs seem to only display methods that are disabled. Maybe this should be changed?

![Markup on 2021-05-05 at 18:24:20](https://user-images.githubusercontent.com/1759681/117175425-21182c80-adcf-11eb-89f6-b6c6f09b2b22.png)

2. Where in the list should the newly enabled methods be added? (At the end?)

**Comment by brezocordero** [comment]
@jarekmorawski 
A couple of questions about the "Add Selected" Payment methods modal:

1) When user adds a new payment method, current behavior is to add it at the end of the list.
Should this be changed? If yes, in which order should the methods be displayed?

2) The modal to add new payment methods displays all available methods. Those that are already active are checked.
Should we display instead only those payment methods that are not yet active?

Thanks!

**Comment by jarekmorawski** [comment]
Thanks for the questions, @brezocordero!

> When user adds a new payment method, current behavior is to add it at the end of the list.
Should this be changed? If yes, in which order should the methods be displayed?

We no longer can control the order of payment methods on checkout so in settings, they should be displayed chronologically: recently added last. Every newly added payment method should appear at the end of the list.

> The modal to add new payment methods displays all available methods. Those that are already active are checked.
Should we display instead only those payment methods that are not yet active?

Yes, please! In the design, I've checked items which have already been selected by merchant. By default the modal should only show payment methods which have not been added to the list in settings (= they're not enabled). In the modal, I can select several methods that I want to add to the list (they'll be placed at the end of the list afterwards).

Let me know if you have any other questions! 👋
