### ISSUE TITLE
[Mobile Payments] Orders paid for by in-person / card present payments show "via Pay on Delivery"

### ISSUE THREAD

**Issue by allendav** [Automattic/woocommerce-payments#1757]
Orders paid  for by in-person / card present payments show "via Pay on Delivery"

<img width="843" alt="Screen Shot 2021-05-10 at 5 42 27 PM" src="https://user-images.githubusercontent.com/1595739/117741479-74b3bd00-b1b7-11eb-9908-a1a89a21f27a.png">

Could we change that to In-Person Card Payment or at least "via Credit Card" like we do for other WCPay orders?

<img width="551" alt="Screen Shot 2021-05-10 at 5 44 13 PM" src="https://user-images.githubusercontent.com/1595739/117741486-79787100-b1b7-11eb-9100-f9afdf31f082.png">

**Comment by allendav** [comment]
cc @bmccotter for what term you'd like to appear in wp-admin > WooCommerce > Orders

**Comment by bmccotter** [comment]
I agree, clarifying "In-Person Card Payment" will be helpful.

**Comment by mgascam** [comment]
Hi @bmccotter, 
In the PR review, @kalessil suggests to use "WooCommerce In-Person Payments". I think it makes sense, since it is aligned with https://woocommerce.com/in-person-payments/. What do you think?

**Comment by bmccotter** [comment]
Hi @mgascam this works great for me! WooCommerce In-Person Payments
