### ISSUE TITLE
Legacy widget for customer multi-currency

### ISSUE THREAD

**Issue by jessepearson** [Automattic/woocommerce-payments#1766]
Standard legacy widget for WordPress needs to be added for allowing store customers to select the currency they would like to view and pay in. 

### Admin
* Create widget and add it to the Widgets section of WordPress.
* Widget will list the currencies the merchant has enabled.
* Options: 
  * Enable/disable country flags.
  * Enable/disable currency symbols.

### Frontend
* Widget will display a select input that inherits styling from the theme.
* Must work for logged in and logged out users.
* Update customer/user session to reflect the selected currency.
  * May need to use cookies for logged out users, but session would be best.
* There will be a default currency setting within the My Account area that could adjust the currency in use.

![Screenshot on 2021-05-11 at 14-52-16](https://user-images.githubusercontent.com/4634416/117862058-9325c100-b268-11eb-8c1b-44b0909fc913.png)

![legacywidgetfrontend](https://user-images.githubusercontent.com/4634416/117862111-aafd4500-b268-11eb-9d7e-b1602067f86f.jpg)

**Comment by ismaeldcom** [comment]
>Widget will display a select input that inherits styling from the theme.

We have a little hiccup here. Because we can't use an image inside an `<option>`. Maybe the best approach is to implement a custom select trying to inherit styles from the theme. What do you think?

cc @dmallory42 @jessepearson  @luizreis
