### ISSUE TITLE
Gutenberg block for currency switcher

### ISSUE THREAD

**Issue by jessepearson** [Automattic/woocommerce-payments#1767]
Block base widget for WordPress needs to be added for allowing store customers to select the currency they would like to view and pay in. 

I dug around for quite a bit to try to determine if this is something that _must_ be done for the initial release of this feature and I wasn't able to find conclusive information if the block based widget editor will be available in June, July, or December of 2021.

### Admin
* Create widget and add it to the Widgets section of WordPress.
* Widget will list the currencies the merchant has enabled.
* Options: 
  * Enable/disable country flags.
  * Enable/disable currency symbols.

### Frontend
* Widget will display a select input that inherits styling from the theme.
* Must work for logged in and logged out users.
* Update customer/user session to reflect the selected currency.
  * May need to use cookies for logged out users, but session would be best.

**Comment by ismaeldcom** [comment]
>I dug around for quite a bit to try to determine if this is something that must be done for the initial release of this feature and I wasn't able to find conclusive information if the block based widget editor will be available in June, July, or December of 2021.

If I'm not wrong. Brent mentioned in the planning doc that the MVP would be settings functionality and legacy widget. And in later versions add onboarding flow, block widgets and analytics.

And David mentioned in paJDYF-1kA-p2:

- **As a block via the block enabled widget screen**: we should aim to have a currency switcher block available no later than time the block enabled widget screen ships to core. (This screen is already available to merchants using the Gutenberg plugin)
- **As a block via the editor**: becomes much more useful once full site editing has landed

Hope it helps!

**Comment by dmallory42** [comment]
> If I'm not wrong. Brent mentioned in the planning doc that the MVP would be settings functionality and legacy widget. And in later versions add onboarding flow, block widgets and analytics.

Yep, this matches my thinking. I think the legacy widget will definitely be required for the MVP as that would allow the majority of merchants to use the multi-currency features, and I think the block widget could either be a nice to have for the MVP if we find we have time/are ahead of schedule, but more likely it can go into phase 2.

**Comment by jessepearson** [comment]
There's info about migrating blocks, which shouldn't be hard in our case, in the developer handbook:
https://developer.wordpress.org/block-editor/how-to-guides/widgets/legacy-widget-block/#allowing-migration-to-a-block

**Comment by dwainm** [comment]
@jessepearson Since this will be part of V2 I'd like us to not use the hacky widget convert method. We'll have some time to do this properly and add a native currency conversion block, which will probably take a little more time, but will result in a better experience and easier to maintain solution. We should also take the opportunity to improve the API that will make it easier for themes to integrate the dropdown see https://github.com/Automattic/woocommerce-payments/issues/2265#issuecomment-887214404

I'm moving this to an 8 in estimation as no one in Sigma really has solid experience with blocks and there may be a learning curve.

cc @LevinMedia

**Comment by ismaeldcom** [comment]
I think [Allowing migration to a block](https://developer.wordpress.org/block-editor/how-to-guides/widgets/legacy-widget-block/#allowing-migration-to-a-block) might be useful. Allow users to migrate a Legacy Widget block to a block. Discovered it yesterday reading the new changes for widgets on WP v5.8.
