### ISSUE TITLE
Legacy settings pages for customer multi-currency

### ISSUE THREAD

**Issue by jessepearson** [Automattic/woocommerce-payments#1768]
Three pages are needed based on the design thread ( paJDYF-1gf-p2 ) and the screenshots below.

### Currencies
* Currencies will list current enabled currencies with edit/remove links with the items (React components suggested here).
* Add currency button will open modal. Modal will have:
  * List of _all_ currencies available to be checked off and added.
  * List of recommended currencies.
  * Search to narrow down currency list.
* Screenshot shows Save button, but this will not be needed if React components are used. We can just double verify before removing a currency.

### Single currency
* Exchange rate, automatic or manual selection.
  * Manual selection will need dynamic input field, if chosen. 
* Formatting rules:
  * Price rounding - the amount to round up to once conversion is done. Should this be a select or a numeric input?
  * Charm pricing - the amount to reduce the price by after the conversion and price rounding. Example: 20.00 goes to 19.99. Should this be select or numeric input?
* Preview - allow merchant to enter price to see how it displays with the above rules and conversion.
* [Zero decimal currencies](https://stripe.com/docs/currencies#zero-decimal) will need to be accounted for.

### Store settings
* Automatically switch customers to local currency (checkbox)
* Add currency switcher to cart widget (checkbox)

### Notes
* What if the default currency is not USD? If in doubt, we can use the default store currency.
* Automatically switch customers to their local currency if it's enabled above - Will be using language or geolocation? 

### Screenshots
![Screenshot on 2021-05-10 at 12-52-40](https://user-images.githubusercontent.com/4634416/117857904-ab471180-b263-11eb-8cfe-a97055a9488c.png)
![Screenshot on 2021-05-11 at 14-03-34](https://user-images.githubusercontent.com/4634416/117857927-b306b600-b263-11eb-9e2e-f9f236f88d20.png)
![Screenshot on 2021-05-10 at 12-52-54](https://user-images.githubusercontent.com/4634416/117857947-bbf78780-b263-11eb-9cf6-cddd4cc2ffb5.png)
![Screenshot on 2021-05-10 at 12-53-09](https://user-images.githubusercontent.com/4634416/117857956-bf8b0e80-b263-11eb-9615-30791e1a8a9c.png)

**Comment by LevinMedia** [comment]
>What if the default currency is not USD? If in doubt, we can use the default store currency.

@jessepearson that is the expected behavior -whatever the store's default currency is would appear on that row. I just used USD for the example 👍

**Comment by jessepearson** [comment]
Closed via #1762
