### ISSUE TITLE
Customer facing prices for customer multi-currency

### ISSUE THREAD

**Issue by jessepearson** [Automattic/woocommerce-payments#1769]
Prices in all the places like shop, single prod page, widgets, will need to be adjusted according to the current currency selected. The widget (#1766) will set the currency to be used, and then the values from the settings (#1768) will be used to convert the price(s) of the product accordingly.

* As noted for the widget, this needs to work both for logged in and logged out users.
* Filters can be used to change the prices.
* Compatibility with extensions will need to be planned out, such as Product Add-Ons, Bookings, and possibly Subscriptions.
* [Zero decimal currencies](https://stripe.com/docs/currencies#zero-decimal) will need to be accounted for.

**Comment by dmallory42** [comment]
> Zero decimal currencies will need to be accounted for.

It looks like the conversion code we have in the server ( https://github.com/Automattic/woocommerce-payments-server/blob/trunk/server/wp-content/rest-api-plugins/endpoints/wcpay/services/class-foreign-exchange-service.php ) has some functionality to handle zero-decimal currency conversion, so it may be possible to utilise this for this purpose.

**Comment by ismaeldcom** [comment]
> As noted for the widget, this needs to work both for logged in and logged out users.

WooCommerce Multicurrency uses a cookie named `woocommerce_multicurrency_forced_currency` to store the setting. But also have a detect behaviour based on: url param, language, cookie and geolocation, before using the fallback.
And have some compatibility code with WP Super Cache to avoid problems with the cookie.
