### ISSUE TITLE
Documentation for customer multi-currency

### ISSUE THREAD

**Issue by ismaeldcom** [Automattic/woocommerce-payments#1780]
Add a new section about Multi Shopper Currencies to the docs, including:

- How this new feature works:
  - Onboarding process
  - Settings
  - Widget and block
  - Analytics
- Disclaimers about the currency conversion rates.
- Explaining the link between merchant account currency and shopper payments currency.

#### (TODOs) Links to documentation:
- `class-settings.php` `// TODO: Learn more documentation link, to be done on #1780`

**Comment by thenbrent** [comment]
The best doc/location for this to go is to replace the content here: https://docs.woocommerce.com/document/payments/currencies/multi-currency-setup/
