### ISSUE TITLE
Insert payment methods after main gateway instead of replacing in woocommerce_gateway_order

### ISSUE THREAD

**Issue by waclawjacek** [Automattic/woocommerce-payments#1782]
Once the credit card payment processing logic is separate from the main WooCommerce Payments gateway (work is underway in #1615), update the payment method reordering logic to insert payment methods after the main gateway instead of replacing it:

Solution example:

Instead of [what is currently in place](https://github.com/Automattic/woocommerce-payments/pull/1647/files#diff-57ee486c4a3ba4bae478eb31255c9a968b5b4eccd04b27f512e4003440d6f821R554):

```php
array_splice( $ordering, $wcpay_index, 1, $method_order );
```

Do this:

```php
array_splice( $ordering, $wcpay_index + 1, 0, $method_order );
```

The current replacing logic is in place because the CC gateway ID is the same as the main gateway.

**Comment by frosso** [comment]
Confirmed and closing - with UPE we don't need separate payment methods. They are all handled within the main WCPay payment method.
