### ISSUE TITLE
Testing API calls on WC 4.0.0 and 4.3.0 calls _doing_it_wrong()

### ISSUE THREAD

**Issue by waclawjacek** [Automattic/woocommerce-payments#1784]
When writing API tests using `rest_do_request()` in #1647, I discovered that some of WC Blocks' calls to `register_rest_route()` cause `_doing_it_wrong()` when testing on WC 4.0.0 and 4.3.0. This causes tests to fail.

I worked around this issue by [disabling WC Blocks' REST routes in the controller's tests](https://github.com/Automattic/woocommerce-payments/pull/1647/files#diff-8bea0e64492f14e71ce226e259d9bd99ee3fc3bb47b503464610331b4aea66ffR47) but a better solution would be nice.

**Comment by RadoslavGeorgiev** [comment]
@waclawjacek I'm not aware why `_doing_it_wrong` was there in the first place, but I see that we have changed the way we de-register blocks' routes through [this commit](https://github.com/Automattic/woocommerce-payments/commit/a36d0fdf87413d50c166b911f8e37c92a28a2857#diff-02275d622ead92041762f5decdcb01e6d29357449b062c1fb8cf7206f372d4ea) in [#3481](https://github.com/Automattic/woocommerce-payments/pull/3481). Does that change address this issue?
