### ISSUE TITLE
Avoid using the array index as the key

### ISSUE THREAD

**Issue by luizreis** [Automattic/woocommerce-payments#1789]
We're using the array index as the `key` prop in a few places, such as https://github.com/Automattic/woocommerce-payments/blob/develop/client/transactions/list/index.js#L181.

We should fix this when a better choice than the index is available, because if the order of the elements changes [things can get messy behind the scenes](https://robinpokorny.medium.com/index-as-a-key-is-an-anti-pattern-e0349aece318).

h/t @nb

**Comment by oaratovskyi** [comment]
Hey @luizreis, the link to the file is outdated.
The file type was changed to .tsx (`client/transactions/list/index.tsx`).
I've checked the file and don't see using array keys as indexes except for this place
https://github.com/Automattic/woocommerce-payments/blob/develop/client/transactions/list/index.tsx#L211

Which are the read-only subscription order links, that is fine (as they won't be added/removed).

I guess we could close this one as something can't be reproduced.
@luizreis would appreciate your feedback on this one.

cc @DanReyLop

**Comment by DanReyLop** [comment]
You're right @oaratovskyi , I've made a quick search throughout the whole project and it doesn't look we're using `key` in any "wrong" way. The [`<Paragraphs>`](https://github.com/Automattic/woocommerce-payments/blob/develop/client/components/paragraphs/index.js#L11) component, for example, uses the index as the `key`, but it's never being used with text that can be rearranged/deleted.

Can you please check the whole project, see if I missed anything? If you don't see any problematic usage of `key`, you can close this issue.

**Comment by luizreis** [comment]
> I've checked the file and don't see using array keys as indexes except for this place
> https://github.com/Automattic/woocommerce-payments/blob/develop/client/transactions/list/index.tsx#L211
> 
> Which are the read-only subscription order links, that is fine (as they won't be added/removed).

Yep, that was the place. IMO, if there's a better choice of `key` to be used in those cases, we'd be better off using it. Right now, those aren't modified at runtime but it would be easy to miss this if we start modifying them. That said, I agree that we probably won't have any issues here, so feel free to close this issue if you can't find any problematic usage in the project.

**Comment by oaratovskyi** [comment]
I've double-checked the project and haven't found any problematic usages of key.
Closing the issue.
Thanks @DanReyLop @luizreis !
