### ISSUE TITLE
Implement a feature flag to allow us to gate this feature if necessary

### ISSUE THREAD

**Issue by dmallory42** [Automattic/woocommerce-payments#1793]
I'm not totally sure if this is necessary yet, but I thought we should have an issue for it so that we don't forget. 

Similar to instant deposits, it may be a good idea to implement a feature flag for Multi-Shopper Currencies so that we can turn the feature on when it's ready, and be able to have control over this if needed.

cc. @dwainm @ismaeldcom @jessepearson @luizreis

**Comment by luizreis** [comment]
Just my 2 cents: It looks like we'll be able to have Multi-Shopper Currencies isolated from most/all WC Pay code, so it should be pretty straightforward to add a feature flag check before importing its main/bootstrap file.

**Comment by dwainm** [comment]
Moving this into the current sprint and marking it as a high priority. I think we should aim to ship what we have ready into the next release and avoid having everything in one branch right until the end.  cc @jessepearson  @dmallory42

**Comment by dwainm** [comment]
This will also allow us to create instruction for the testing team to run through and have certain parts tested as part of the next release.
