### ISSUE TITLE
Filter wc_privacy_policy_content to add WooCommerce Payments

### ISSUE THREAD

**Issue by allendav** [Automattic/woocommerce-payments#18]
For example, we could do something similar to what we do today for [PayPal](https://github.com/woocommerce/woocommerce/blob/d0491072e8a7d0a4535db0ec2bae4a6d43ff64fd/includes/class-wc-privacy.php#L116):

> We accept payments through PayPal. When processing payments, some of your data will be passed to PayPal, including information required to process or support the payment, such as the purchase total and billing information. Please see the PayPal Privacy Policy for more details.

The content should link to https://automattic.com/privacy/ - ideally to a fragment identifier specific to WooCommerce Payments - see #17

**Comment by jessy-p** [comment]
I believe this is already addressed, can we close this @bmccotter

**Comment by bmccotter** [comment]
@jessy-p where did we address it?

**Comment by jessy-p** [comment]
I found a privacy policy link on the [plugin page](https://woocommerce.com/products/woocommerce-payments/), similar to the PayPal plugin, and it links to the Automattic Privacy page.  @bmccotter Can you tell us where the Privacy policies still need to be added, so we can implement it?

**Comment by jessy-p** [comment]
Implement according to comment [here](paJDYF-3J0-p2#comment-10985)

**Comment by htdat** [comment]
Waiting for the legal text here paJDYF-3J0-p2#comment-11775

I am temporarily adding `status: blocked` label until the legal team can give the text.
