### ISSUE TITLE
Country flags for customer multi-currency

### ISSUE THREAD

**Issue by ismaeldcom** [Automattic/woocommerce-payments#1802]
After a quick internal conversation p1620988829329600-slack-C01B8KNUYSW we are considering the use of emojis for country flags rather than image files.

WC Admin already use them. They have the [`<Flag/>`](https://github.com/woocommerce/woocommerce-admin/tree/main/packages/components/src/flag) component. And some time ago the made the switch from images to emojis, in this PR https://github.com/woocommerce/woocommerce-admin/pull/1384 they discuss the impact on size and support for older OS and browsers.

In our case, using emoji will let us implement the legacy widget using an HTML `<select>` element. Otherwise, we will need to create a custom one, because `<option>` only allow text. Losing the ability to inherit style from theme.

@LevinMedia What do you think about using emojis from a design perspective? In the previous links you can see how they look. And I attach a quick couple of capture of how the result would be:

| Settings (I changed only the Europe one to compare) | Legacy widget |
| - | - |
| <img width="300" src="https://user-images.githubusercontent.com/7670276/118270354-3cb2bf80-b4c0-11eb-825a-563cee6a111f.png" /> | <img width="169" src="https://user-images.githubusercontent.com/7670276/118270919-f27e0e00-b4c0-11eb-8c04-1a3bb35e14fa.png" /> |

---

We need to do a proper investigation on this. But I think that we take advantage of `<Flag/>` implementation from `@woocommerce/components` or implement a custom solution. After that, we can then add a getter to the new `WCPay\Multi_Currency\Currency` class, to get the flag of the currency.

**Comment by LevinMedia** [comment]
@ismaeldcom I know this seems like a small thing and it looks like I missed the ping back in 2019. I'd prefer the rectangular flags over the emoji wavy flags. 

It would be a bit of a task for me, but I have an extension that can generate all the world flags as SVG images. Would it be possible to update the wc-admin flags component to use those instead, assuming the generated SVGs don't blow up the size of it?

**Comment by ismaeldcom** [comment]
Thanks for your quick reply @LevinMedia! I had to admit that the rectangular ones you used in Figma files are more beautiful 😄

For WC Admin. From a dev perspective, I don't found any issue to not use SVG files, apart from the increase in size. But I think we should ask them about that. 

On the other side. If we use any type of image, we lose the possibility to use an HTML `<select>` and to inherit theme styles. I think it's important to note that, because the custom select will force the user to have a "different input". You can check what I say looking at the input from https://woocommerce.com/products/multi-currency/ and any "native" one in different browsers or platforms.

Here are some examples:
| Chrome Storefront | Firefox Storefront | Chrome Twenty Twenty-One |
| - | - | - |
| <img width="225" src="https://user-images.githubusercontent.com/7670276/118285407-af786680-b4d1-11eb-8b96-6e792c43b6a3.png" /> | <img width="256" src="https://user-images.githubusercontent.com/7670276/118285495-cae37180-b4d1-11eb-9fc7-419edb77186f.png" /> | <img width="846" src="https://user-images.githubusercontent.com/7670276/118285635-f7978900-b4d1-11eb-854e-27b3b6ee2ba0.png" /> |

**Comment by LevinMedia** [comment]
heya @ismaeldcom per our convo at p1621348556007300-slack-CGGCLBN58 - lets proceed with the emoji's for now, and assess how it looks when it's functional. We can keep the discussion open for the block portion of this. 

Thanks!

**Comment by luizreis** [comment]
https://github.com/Automattic/woocommerce-payments/pull/1852 implemented the flags for the legacy Widget using emojis. We'll create a new issue or reopen this one if we're not satisfied with how they look when the extension is functional.
