### ISSUE TITLE
Add digital wallet buttons previews to settings page

### ISSUE THREAD

**Issue by bborman22** [Automattic/woocommerce-payments#1808]
This issue is a branch off from #1730. The goal is to display a preview of the 1-click checkouts like Google pay and Apple pay in the settings as theming is adjusted.

Example of the previews being displayed: paJDYF-1x5-p2

**Comment by harriswong** [comment]
The preview should look something like this: 
![image](https://user-images.githubusercontent.com/572862/121424701-dab67000-c92e-11eb-9349-9395dbb40ed9.png)

**Comment by harriswong** [comment]
There are 2 different ways to generate the Google Pay button in the existing code. One is through `paymentRequest`([code](https://github.com/Automattic/woocommerce-payments/blob/801d2e64204d1b0930a7ca4e0f72ee8a989e07b7/client/payment-request/index.js#L317-L326)), which is what Storefront uses; the other is through block's [branded-buttons.js](https://github.com/Automattic/woocommerce-payments/blob/801d2e64204d1b0930a7ca4e0f72ee8a989e07b7/client/payment-request/blocks/branded-buttons.js#L49-L64).

I would love to use the branded-button react component given the settings page is built with React. However, the branded-buttons isn't created through Stripe's `paymentRequestButton`. It has its own `<button>`, loads .svg directly and with its own styles. As a result, it doesn't seem to support all our text options (Donate, Buy, Book).  I also haven't checked how Apple Pay will render in this. 

I think there are 2 solutions to this. 
1. Extend [branded-buttons](https://github.com/Automattic/woocommerce-payments/blob/develop/client/payment-request/blocks/branded-buttons.js) to support custom text, and Apple Pay. 
2. Create a React component for Preview that uses `paymentRequestButton` similar to what [this](https://github.com/Automattic/woocommerce-payments/blob/801d2e64204d1b0930a7ca4e0f72ee8a989e07b7/client/payment-request/index.js#L317-L326) does. I wonder if this wasn't possible in React and so we have to create our own <button>.

**Comment by harriswong** [comment]
@jarekmorawski, are we okay with displaying Google Pay under “Preview” in Chrome, and Apple Pay in Safari? Or do we need to display both Apple Pay and Google Pay regardless of browser?

**Comment by harriswong** [comment]
After some discussions offline, we lean towards using Stripe to render the button. The problem with Stripe's Payment Request Button is that it can't display both Apple Pay and Google Pay at the same time. We will need some messaging to tell our merchant that they need to open Safari to see a Apple Pay preview, etc. 

Marking as block for now.

**Comment by harriswong** [comment]
**Updates**
- Use Stripe to render the image.
- Add a background card underneath the Stripe rendered button.
- Clicking the "preview" Stripe's button would popup a payment dialog because it uses the actual button. Maybe find a way to disable it. Or change the amount to $1 or something. 
- Display the text to explain why Apple Pay can't be displayed on Chrome; Google Pay can't be displayed on Safari.
- Screenshot below:
![image](https://user-images.githubusercontent.com/572862/122429680-321c9780-cf50-11eb-8164-370d9ceaffd5.png)
