### ISSUE TITLE
Show empty state Transactions screen

### ISSUE THREAD

**Issue by mattsherman** [Automattic/woocommerce-payments#1817]
*Note: This is a part of the larger Preview Mode project (paJDYF-1rg-p2).*

## User story

As a merchant who has installed WCPay but not completed the KYC, I want to find out more about how to finish setting up WCPay when I click on the Transactions menu item, so that I can start accepting payments and start earning money.

## Design

TODO: Replace screenshot and Figma with final design.

![Transactions](https://user-images.githubusercontent.com/2098816/118379053-db651c00-b5a5-11eb-8dc3-3875468007f6.png)

[Figma prototype](https://www.figma.com/proto/7QOkvxzz1ylS3QBS4zqW8R/Payments-experiments?page-id=4690%3A13324&node-id=7764%3A0&viewport=-4053%2C-545%2C0.125&scaling=min-zoom)

## Acceptance criteria

- When assigned the `empty_states` experience, clicking on the Transactions menu item shows the empty state Transactions screen as detailed in the design
	- Clicking "Finish setup" button takes the merchant to the KYC
- When the merchant has completed the KYC, clicking the Transactions menu item shows the regular Transactions screen

## Tasks

- [ ] Implement empty state for Transactions screen
- [ ] Implement Tracks event when clicking on "Finish setup" button

**Comment by adrianduffell** [comment]
Closing, this was included in PR #1963
