### ISSUE TITLE
Launch WCPay Empty States Preview Mode experiment

### ISSUE THREAD

**Issue by mattsherman** [Automattic/woocommerce-payments#1818]
*Note: This is a part of the larger Preview Mode project (paJDYF-1rg-p2).*

Once the `wcpay_empty_state_preview_mode` experiment has been reviewed and the `empty_states` experience is fully implemented and available in a release for merchants, we are ready to launch it and begin collecting data to analyze.

## Acceptance criteria

- The `wcpay_empty_state_preview_mode` experiment is launched and merchants are being assigned either the `control` or `empty_states` experiences

## Tasks

- [ ] [Launch the experiment](https://github.com/Automattic/experimentation-platform/wiki/Experimenter's-Guide#launching-your-experiment)
- [ ] Post on P2s about launch

**Comment by pmcpinto** [comment]
@mattsherman I just want to confirm that the experiment will automatically start on the date defined as the start date on Abacus: July 19

**Comment by mattsherman** [comment]
@pmcpinto I haven't been involved with the implementation of this experiment (due to the reorg). I'll defer to @samueljseay and @adrianduffell on this!

**Comment by adrianduffell** [comment]
@pmcpinto Yes this is scheduled to automatically start on July 19 however @oneillo is considering launching it sooner. The supporting code was shipped in the latest WC Pay release on Wednesday.

**Comment by oneillo** [comment]
@pmcpinto @adrianduffell I just launched the experiment today.
