### ISSUE TITLE
Add new page for viewing transfer details

### ISSUE THREAD

**Issue by dwainm** [Automattic/woocommerce-payments#1820]
Clicking on a row for an instant deposit transaction loads a broken page as the data for the new transaction type does not match standard transactions.

Add a new page for viewing instant deposit transfer details. An example of the data to be viewed can be seen here: 
paJDYF-V6-p2#comment-6078

The example above is a guide, but we could make it a bit more detailed, like say that it was a free transfer to WCPay for an instant deposit.

**Comment by DanReyLop** [comment]
There's already an issue to track this. Instead of a whole new transaction page, the fee will be presented in the Deposit Overview header: https://github.com/Automattic/woocommerce-payments/issues/1678
