### ISSUE TITLE
Update UPE Payment Intent with checkout updates

### ISSUE THREAD

**Issue by bborman22** [Automattic/woocommerce-payments#1830]
As part of the UPE checkout, a payment intent needs to be created early on to display the UPE. As changes are made during checkout, primarily thinking about choosing a shipping rate, the amount to be charged may need to be updated. The goal of this issue is to make sure that the UPE is always loading a relevant payment intent by creating a process to update the payment intent used in the UPE with any updates during checkout. The end result of this issue is to have a flow of updating the order in checkout, updating the payment intent, then remounting the UPE with the updated payment intent as necessary. Further discussion and possible solutions on this need can be found paJDYF-1wJ-p2.

**Comment by superdav42** [comment]
I'm not sure I see the value in making this change. Right now as @FangedParakeet described:

> We prevent the form from actually submitting, but submit an AJAX request to create the Order, calculate totals, update the Payment Intention with the final totals to be charged, and finally return a redirect URL to the Order Complete page, securing the Order ID in a query parameter.

We can update the payment intention as we go or update it when everything is finalized. I think in either case we still need to have a final check on submission to ensure everything is correct. Remounting UPE seems like it should be avoided if it's not necessary.

**Comment by bborman22** [comment]
>  I think in either case we still need to have a final check on submission to ensure everything is correct. Remounting UPE seems like it should be avoided if it's not necessary.

I totally agree. If we're able to update the payment intent after collecting the payment information in the UPE that would be perfect! What I wasn't sure of is if updating the payment intent would in any way invalidate the client secret used to load the UPE.

I think I got lost in the weeds in the details of the issue. To clarify, the goal of the issue is to have the ability to update a payment intent whether on checkout updates or just once at the end.
