### ISSUE TITLE
Remove SEPA payment gateway dependencies for saved payments 

### ISSUE THREAD

**Issue by harriswong** [Automattic/woocommerce-payments#1872]
Instead of building payment gateway for each payment method, we are going in the direction of UPE. In the future, we are also [planning](https://github.com/Automattic/woocommerce-payments/pull/1848) on removing all the EUR payment gateways (sepa, sofort, giropay, etc)we added. 

In [this PR](https://github.com/Automattic/woocommerce-payments/pull/1540/), there are parts of the code that relies on SEPA payment gateway to save the payment info via tokens. Given that SEPA payment gateway is going away, we should remove the dependency while making sure saved payment still works.

**Comment by frosso** [comment]
This doesn't seem relevant anymore - with the Split UPE we'll keep the SEPA gateway class (and others). Closing.
