### ISSUE TITLE
Customer facing prices compatibility with WooCommerce Deposits

### ISSUE THREAD

**Issue by luizreis** [Automattic/woocommerce-payments#1902]
Follow up from #1769

We need to ensure compatibility with Customer multi-currency prices and WooCommerce Deposits.

**Comment by tpaksu** [comment]
Putting this on-hold because #3067 got higher priority.

**Comment by jessepearson** [comment]
This seems like it's likely going to need some modifications to Deposits, as well. 
* 286-gh-woocommerce/woocommerce-deposits
*281-gh-woocommerce/woocommerce-deposits

That second issue is the larger one, as we need to make sure that follow up orders for deposit payments, along with payment plan orders, are created in the same currency as the original order.
