### ISSUE TITLE
Add E2E tests for the UPE

### ISSUE THREAD

**Issue by FangedParakeet** [Automattic/woocommerce-payments#1903]
The previous WCPay credit card gateway has end-to-end test coverage for the card element at checkout--I'm aware of this, because I temporarily broke all these tests while developing the UPE payment gateway and checkout implementation for #1826. Currently, in #1890 pending review, I have added PHP unit test coverage for the gateway and its payment fields; however, the mounted UPE element is missing E2E coverage. 

I wouldn't consider myself tremendously excited about this prospect, but if the UPE gateway will eventually replace the card gateway, I think we are going to need to develop some E2E test coverage for this feature eventually. Here lies this issue to let it be known.

**Comment by frosso** [comment]
Closing. The legacy card tests are going to be migrated to UPE. So, once the Deferred Intent UPE migration is completed, we'll have better coverage.
