### ISSUE TITLE
[Mobile Payments] Add an Endpoint that Creates/Returns WCPay Customers for an Order

### ISSUE THREAD

**Issue by allendav** [Automattic/woocommerce-payments#1918]
For the Mobile Payments MVP, we need a endpoint (POST?) at something like `payments/orders/<ID>/create_customer ` that...

- for an order placed by a registered buyer
    - returns the WCPay (Stripe) Customer ID for that buyer, creating it for them if needed
- for an order placed by a guest buyer
    - creates and returns a WCPay (Stripe) Customer ID based on the buyer’s data in the order

NOTE: This also opens the door to updating a return registered buyer if we wanted to from the billing information on their newest order

NOTE: In either case, this endpoint does NOT have to add the customer WCPay (Stripe) ID to the order. The `payments/orders/<ID>/capture_terminal_payment` endpoint (added by @marcinbot in #1689 ) will do that when the payment intent is later captured.

Related mobile issues: https://github.com/woocommerce/woocommerce-ios/issues/4298 https://github.com/woocommerce/woocommerce-ios/issues/4299 https://github.com/woocommerce/woocommerce-ios/issues/4300

cc @ctarda @laurendavissmith @bmccotter

**Comment by kalessil** [comment]
@shendy-a8c, more context here:
- `\WC_Payments_Customer_Service` provides API (hopefully everything is in place already)
- We'll likely need a new controller class, something like `\WC_REST_Payments_Orders_Controller`
