### ISSUE TITLE
Upon plugin activation, display notification stating jetpack requirement if jetpack is not installed and connected

### ISSUE THREAD

**Issue by LevinMedia** [Automattic/woocommerce-payments#195]
Do not allow plugin activation If a WordPress.com account is not connected via Jetpack. 

The merchant is alerted that they must install and or connect to Jetpack via a standard wordpress notification.

(JetPack plugin requirement is temporary and will be replaced by Jetpack DNA connection module, and passwordless wp.com account creation / detection detailed in ... )

**Comment by dwainm** [comment]
Closing as it was fixed in https://github.com/Automattic/woocommerce-payments/pull/638
