### ISSUE TITLE
UPE automatic theming selector choice

### ISSUE THREAD

**Issue by bborman22** [Automattic/woocommerce-payments#1960]
As part of the automatic theming of the UPE, we had to pick a selector for an element to base the styles on. After some less specific attempts, the first name field seemed like a good first candidate. With the understanding that we likely won't cover 100% of scenarios, there is some room to make this selector more robust in case the first name field (or any other choice in fields) is not present. One suggestion would be to use a list of fields to check until one is found, but perhaps it would be possible to find a more generic selector approach that still gets the field with the styles we need.

For an example, using just `.woocommerce-checkout .form-row input` with the Astra theme got the incorrect input padding as it grabbed the coupon code field which overrides the other input fields padding. The ultimate fallback solution to this problem is the ability for the merchant to specify which field to use as a source, but we are looking to limit the amount of effort required from merchants to get themes matching.

**Comment by LevinMedia** [comment]
@bborman22 I've added the needs design label - let me know if this no longer an issue, and we can close.

**Comment by bborman22** [comment]
Thanks for tagging this @LevinMedia! I don't think this will require any design input at the moment, the goal with this issue was just to allow the merchant to pick from an existing field on their site to base the UPE styles on. This issue was just my narrow solution to the broader issue explained in #3604. 

@melek with #3604 being a broader identification of the issue with linked examples from merchants questions, do you think we could close this issue for now as it's well captured in #3604?

**Comment by frosso** [comment]
It looks like at this time the solution implemented leverages the creation of a "visually hidden" field, from which we grab the styles from.
Since this seems a bit more reliable than the initial approach, and since we're planning on adding custom fiters, I'm going to close this.
