### ISSUE TITLE
[Mobile Payments] Add an Endpoint that Returns Level 3 Data for Order

### ISSUE THREAD

**Issue by allendav** [Automattic/woocommerce-payments#1962]
For the Mobile Payments MVP, we need a endpoint (GET?) at something like payments/orders/<ID>/level_three_data that...

- returns the level 3 data that should be passed to a payment intent creation request

Related mobile issues: https://github.com/woocommerce/woocommerce-ios/issues/4297

cc @ctarda @laurendavissmith @bmccotter

**Comment by allendav** [comment]
BTW, I noticed a new field in the Stripe docs for level3, customer_reference. It is the only field in the docs we don't include in the plugin level3 handling. I checked with Karl/Stripe and he assures us we can ignore that field.

**Comment by kalessil** [comment]
@allendav, @ctarda: what is the workflow for this endpoint?

I asking as we could enhance `payments/orders/<order_id>/capture_terminal_payment` [endpoint](https://github.com/Automattic/woocommerce-payments/blob/develop/includes/admin/class-wc-rest-payments-orders-controller.php#L67), and [inject](https://github.com/Automattic/woocommerce-payments/blob/develop/includes/wc-payment-api/class-wc-payments-api-client.php#L267) level-3 data into intent here.

We have an order there and can generate level-3 data consistently and proof to future changes.

**Comment by allendav** [comment]
I am fairly certain Stripe expects the level 3 data to be provided when the payment intent is initially created, as a means of evaluating fraud risk. On Terminal, we have to use the Terminal SDK to create the intent. Waiting until capture is probably too late. I'll double check this.

**Comment by allendav** [comment]
Update: Karl/Stripe says it is OK to add level3 at the time of capture

**Comment by kalessil** [comment]
Awesome :tada: ! Then I'll start implementing the proposed way.

**Comment by allendav** [comment]
Thanks! Looks like we cannot, however, create/update customers that late. They will still need to have endpoints we can hit from the mobile app - but that's for the other issue, not this one.

**Comment by kalessil** [comment]
Note fo myself: see if we can fix #1944 on the way - same context.

**Comment by kalessil** [comment]
> Looks like we cannot, however, create/update customers that late. They will still need to have endpoints we can hit from the mobile app - but that's for the other issue, not this one.

Yep, customers creation is clearly a dedicated endpoint. Thanks for clarifying!

**Comment by allendav** [comment]
Just wanted to mention that we've tested this from the iOS mobile app and it works great. Thank you!

Closed https://github.com/woocommerce/woocommerce-ios/issues/4297
Closed https://github.com/woocommerce/woocommerce-ios/issues/3863

**Comment by kalessil** [comment]
Awesome, thanks for keeping us in loop @allendav !
