### ISSUE TITLE
TypeScript: declaration.d.ts is not loaded for `lint-staged` phase

### ISSUE THREAD

**Issue by dmvrtx** [Automattic/woocommerce-payments#1970]
Unless `declaration.d.ts` is modified with other code it is not loaded for a `lint-staged` phase during pre-commit checks. As a result TypeScript check fails and change cannot be committed.

It is possible that `incremental` flag could be of help here. Otherwise a better solution for `lint-staged` check should be found.

**Comment by vbelolapotkov** [comment]
Closing in favor of #1967
