### ISSUE TITLE
Update WCPay title/description on gateways list page

### ISSUE THREAD

**Issue by frosso** [Automattic/woocommerce-payments#1989]
## Description

In a previous spike we investigate the possibility to update the WCPay name in the gateway settings list: https://github.com/Automattic/woocommerce-payments/issues/1433

We now need to do the work to update the icon (and name/description) on the list itself.

We need to ensure that the icons displayed are accurate with the payment methods available to the merchant.
The description needs to be updated only when the "grouped settings" flag is enabled.
![Screen Shot 2021-06-01 at 12 33 03 PM](https://user-images.githubusercontent.com/273592/120366688-947d6300-c2d5-11eb-8685-08685e5f0d00.png)

**Comment by harriswong** [comment]
An [alternative implementation](https://github.com/Ferdev/woocommerce-payments/pull/1#issuecomment-853333798) of "logos" was brought up. With the suggested approach, the logos can be presented on the right as a "logo column":
![image](https://user-images.githubusercontent.com/572862/120834391-2ed0e700-c520-11eb-8f55-e980d5788ba6.png)

I am moving this to blocked. I'm going to check with @jarekmorawski .

**Comment by harriswong** [comment]
Linking the latest screenshot from design:
![image](https://user-images.githubusercontent.com/572862/121235772-745c1f80-c852-11eb-9c96-0087208a2e32.png)

- Moving logos to the right
- Updating title to "Popular payment methods"

**Comment by harriswong** [comment]
Updating screenshot from new design:
![image](https://user-images.githubusercontent.com/572862/122131252-20bf7800-cdf6-11eb-9c65-d260e3fc7e60.png)

- Update title to "Credit card/ debit card".
