### ISSUE TITLE
Enable the "Grouped settings" flag for all users

### ISSUE THREAD

**Issue by frosso** [Automattic/woocommerce-payments#1990]
## Description

To be done by the very end of the sprint (not merged before).

- Ensure changelog entry is added for UI changes
- Ensure changelog entry is added for "Express checkout" settings migration

Cleanup of the code behind the feature flag to be done separately.

**Comment by frosso** [comment]
See https://github.com/Automattic/woocommerce-payments/issues/2013#issuecomment-854841689 to figure out how to fix the failing unit test.

**Comment by frosso** [comment]
Please consider this comment for implementation: p1623130634018200/1623089514.016900-slack-C01RTUVR81K

**Comment by harriswong** [comment]
@frosso , I have some questions regarding these: 

> Ensure changelog entry is added for UI changes

I added an entry for "Introduce new settings layout for WooCommerce Payments".  Is there a specific copy you would like to use instead?

> Ensure changelog entry is added for "Express checkout" settings migration

Do you mean there is a migration script we need to advice our users to run and we should add that to the changelog?

**Comment by frosso** [comment]
> > Ensure changelog entry is added for UI changes
> 
> I added an entry for "Introduce new settings layout for WooCommerce Payments".  Is there a specific copy you would like to use instead?

I think that's good! (minor) the "for WooCommerce Payments" might be redundant, since the changelog _is_ part of the WooCommerce Payments plugin - but looks good 👍 

> > Ensure changelog entry is added for "Express checkout" settings migration
> 
> Do you mean there is a migration script we need to advice our users to run and we should add that to the changelog?

Some settings for the Express Checkouts are no longer valid - @waclawjacek is working on [this ticket](https://github.com/Automattic/woocommerce-payments/issues/1991) to create a migration script for them. Since we're not planning on displaying any notification about the settings being migrated, I was thinking a changelog entry might be the best option.
Maybe something like:
> * Update - Removed "Branded" and "Custom label" options on Payment request buttons to align with design guidelines.
> * Update - Converted payment request button size value to distinct options to align with design guidelines.

Not sure if that's too long, but I'm open to other suggestions :)
