### ISSUE TITLE
Migrate "Express checkout" settings

### ISSUE THREAD

**Issue by frosso** [Automattic/woocommerce-payments#1991]
## Description

Some of the "express checkout" settings are not valid anymore because they don't align with the Stripe/Apple Pay guidelines.
Here's some background info: paJDYF-1x5-p2

We need to ensure that invalid settings (e.g.: ~"button style > light-outline"~ "button type > branded") are migrated and no longer available in the UI.
Please also ensure that the options are migrated during checkout.

So far we have the following:
- `payment_request` => `is_digital_wallets_enabled` | Enabled/disabled button
- `payment_request_button_type` => `digital_wallets_button_type` | Button type: Only icon, Buy, Donate, Book
- `payment_request_button_theme` => `digital_wallets_button_theme` | Button theme: Dark, Light
- ***NEW*** `payment_request_button_size` | Size of the button: Default, Medium, Large

Attributes no longer valid:
- `payment_request_button_branded_type`
- `payment_request_button_label`
- `payment_request_button_height`

Options no longer valid:
- ~`payment_request_button_theme.light-outline`~
- `payment_request_button_type.branded`
- `payment_request_button_type.custom`

Additional notes:
- For customers that had `payment_request_button_branded_type.short` => Set `payment_request_button_type.default`
- For customers that had `payment_request_button_type.[branded|custom]` => Set `payment_request_button_type.buy`

**Comment by waclawjacek** [comment]
If I understand correctly, what needs to be done here is renaming the corresponding setting fields, plus adjusting the values wherever necessary?

My approach here would be to run a migration once, preferably right after the plugin is updated. This way we will not have to worry about verifying if settings have been migrated in the admin area or during checkout.

If the above sounds good, I have some questions regarding the implementation:

1. Should `digital_wallets_button_action_type` be renamed, e.g. to `digital_wallets_button_type`, given [the recent rename in #1933?](https://github.com/Automattic/woocommerce-payments/pull/1933#discussion_r645800773)
2. Should we display a notice for some users after the migration runs? Maybe it would be beneficial at least in some cases, e.g. display a notice if the button text was changed, but not if the only change was mapping `light-outline` to `light`? I'm not sure but this would be a means of letting users know things might need to be adjusted.
3. Should the old option names be removed after they are stored under the new names?

**Comment by frosso** [comment]
@waclawjacek the settings fields have already been renamed, but their values should be adjusted.

> My approach here would be to run a migration once, preferably right after the plugin is updated. This way we will not have to worry about verifying if settings have been migrated in the admin area or during checkout.

That was my line of thinking as well, but I'm also open to other options. We could create a class that does the migration on the DB values directly. And once the migration of the values is done, we can save some DB option to ensure we're not doing the migration again (or, as an alternative to the DB option being saved, check the values again - whatever you think it's easiest).

> 1. Should `digital_wallets_button_action_type` be renamed, e.g. to `digital_wallets_button_type`, given [the recent rename in #1933?](https://github.com/Automattic/woocommerce-payments/pull/1933#discussion_r645800773)

Thanks, I updated the description in the ticket 👍 

> 2. Should we display a notice for some users after the migration runs? Maybe it would be beneficial at least in some cases, e.g. display a notice if the button text was changed, but not if the only change was mapping `light-outline` to `light`? I'm not sure but this would be a means of letting users know things might need to be adjusted.

I asked about this as well, we won't display a notice after the mgiration

> 3. Should the old option names be removed after they are stored under the new names?

I think we can go with either option.
If we delete them, we could determine whether or not we performed the migration based on the presence of the invalid keys.
If we don't delete them, it would be easier to potentially roll back.
I'm open to any suggestion :)

**Comment by frosso** [comment]
Update Jun 8: we will keep "light outline" for the new settings, so no need to migrate that value anymore.
In [this PR](https://github.com/Automattic/woocommerce-payments/pull/2082) I am re-adding it to the page.

**Comment by waclawjacek** [comment]
Thanks so much!

> We could create a class that does the migration on the DB values directly. And once the migration of the values is done, we can save some DB option to ensure we're not doing the migration again (or, as an alternative to the DB option being saved, check the values again - whatever you think it's easiest).

I think it will be more reliable (no guessing) and performant (no repeated checks) to explicitly store an indication of having performed the migration in the DB. It will probably also be more flexible if we will be implementing other types of migrations in the future that would reuse some of the code implemented for this issue.

>> 3. Should the old option names be removed after they are stored under the new names?

I didn't think of this earlier but I am wondering if we will break any third-party plugins that assume these settings exist and are what is used to style the buttons. Do you see any scenarios where this would be problematic?

**Comment by frosso** [comment]
> I think it will be more reliable (no guessing) and performant (no repeated checks) to explicitly store an indication of having performed the migration in the DB. It will probably also be more flexible if we will be implementing other types of migrations in the future that would reuse some of the code implemented for this issue.

That's perfectly fine 👍 

> I didn't think of this earlier but I am wondering if we will break any third-party plugins that assume these settings exist and are what is used to style the buttons. Do you see any scenarios where this would be problematic?

That's a good point! In the past we identified the changelog to be a good place to communicate these changes. Here's a discussion on what can be added to the changelog: https://github.com/Automattic/woocommerce-payments/issues/1990#issuecomment-857207095

**Comment by waclawjacek** [comment]
This is temporarily blocked by #2153 due to the inability to run post-upgrade code outside of wp-admin.

**Comment by ricardo** [comment]
With this change we're removing support for branded and custom button types, right?

#1640 and #1641 are related. We can close them when the migration PR gets merged.

**Comment by frosso** [comment]
> With this change we're removing support for branded and custom button types, right?

@ricardo that's correct! Thanks for the note!

**Comment by waclawjacek** [comment]
Fixes #1640, fixes #1641 (actually @frosso's [previous PR](https://github.com/Automattic/woocommerce-payments/commit/c9ad55aee62d6a1a0c466d7d85b6aa9a3444d5ac#diff-bcfd303d507c33a27671935e724ee64d0df30ff2a18bb6ef4c94f28d48190124R293-R295) did, this one just migrates existing settings but linking it as closing this one will resolve these issues entirely).

**Comment by waclawjacek** [comment]
Unblocked - the blocking issue #2153 will be resolved separately in the same milestone (`2.6`).
