### ISSUE TITLE
Update documentation for WooCommerce Payments new settings page

### ISSUE THREAD

**Issue by frosso** [Automattic/woocommerce-payments#2035]
## Description

After the flag is enabled and the product is released, we need to updated the WC docs.

Example:
- https://docs.woocommerce.com/document/payments/apple-pay/
- https://docs.woocommerce.com/document/payments/faq/access-stripe-account/
- https://docs.woocommerce.com/document/payments/faq/add-debit-card/
- https://docs.woocommerce.com/document/payments/faq/clear-account-cache/
- https://docs.woocommerce.com/document/payments/faq/tax-id-changes/
- https://docs.woocommerce.com/document/payments/faq/name-changes/
- https://docs.woocommerce.com/document/payments/faq/change-deposit-account/
- https://docs.woocommerce.com/document/payments/
- https://docs.woocommerce.com/document/payments/instant-deposits/
- https://docs.woocommerce.com/document/payments/testing/

Possibility: try and update the docs in draft mode, so that they can be released when 2.6.0 is released.

A few things to update:
- Screenshot(s) of settings page
- "View and edit account details" is now "Manage and update your deposit account information to receive payments and payouts. Manage in Stripe (opens in a new tab)"

**Comment by harriswong** [comment]
**Note**
- Go through https://docs.woocommerce.com/documentation/woocommerce-payments/ and update all pages that touches woocommerce payments settings so that they are up-to-dated.
- The new settings page refers to this one:
![image](https://user-images.githubusercontent.com/572862/122128122-72193880-cdf1-11eb-89a1-28647805f05e.png)

**Comment by harriswong** [comment]
I went through the documentation pages and identified the following pages that needs updating. I compared the following list with the ones listed in the issue's description, they are the same exception for https://docs.woocommerce.com/document/payments/faq/clear-account-cache/; this page does not need updating.

I have updated all these links below and the they are pending editorial review:
- [] https://docs.woocommerce.com/document/payments/
- [] https://docs.woocommerce.com/document/payments/#section-10
- [] https://docs.woocommerce.com/document/payments/apple-pay/
- [] https://docs.woocommerce.com/document/payments/testing/
- [] https://docs.woocommerce.com/document/payments/faq/access-stripe-account/
- [] https://docs.woocommerce.com/document/payments/faq/name-changes/
- [] https://docs.woocommerce.com/document/payments/faq/tax-id-changes/
- [] https://docs.woocommerce.com/document/payments/instant-deposits/#section-4
- [] https://docs.woocommerce.com/document/payments/faq/add-debit-card/
- [] https://docs.woocommerce.com/document/payments/faq/change-deposit-account/

**Comment by frosso** [comment]
Went through the revision changes, FWIW the changes look good! 👍 
With 2.6.0 now released, we just need to have them published 👍

**Comment by harriswong** [comment]
Nice, I will check on the editor's reviews and then I will proceed with publishing.

**Comment by harriswong** [comment]
Pinged guild to check on status.

**Comment by harriswong** [comment]
Documentation reviewed and published. Done!
