### ISSUE TITLE
Red badge: only show it 7 days after the plugin activation

### ISSUE THREAD

**Issue by pmcpinto** [Automattic/woocommerce-payments#2071]
**Description:** while the red badge in the WCPayments menu item is driving more attention, we think that it's having a negative impact on the WCPayments activation rate. More context here: p7Ldg5-11r#comment-4596-p2
In order to avoid this, the best solution is to start showing the red badge 7 days after the plugin activation. Our goal is to find a good balance between taking advantage of the red badge effectiveness to increase the focus on WCPayments without distracting users or hurting the WCPayments activation.

**Acceptance criteria:**

- [ ] Start showing the red badge 7 days after the plugin activation if the user still needs to complete the WCPayments setup. Don't show it if the user already created a WCPayments account.

**Comment by moon0326** [comment]
Estimate: 3

There isn't an easy way to know the activation date of WC Payments as far as I know, unlike WC Admin. I think this is a good chance to add an option to store plugin activation timestamp.

Estimating it 3 as we need to implement adding activation timestamp and test.

[add_menu_notification_badge()](add_menu_notification_badge) has check for the WC Payments account already.
