### ISSUE TITLE
New welcome screen: stop a/b test and deploy variant 

### ISSUE THREAD

**Issue by pmcpinto** [Automattic/woocommerce-payments#2072]
**Description:** we've started running the experiment ~3 weeks ago and the result is still inconclusive (#1612). We're evaluating if we should keep the experiment running until WCPayments 2.7 (final date tbd) or stop it in WCPayments 2.6 (release date June 23). We want to assess how much time & effort is required to stop the experiment and deploy the variant to 100% of users, to understand when do we need to make a decision to stop it or not in 2.6.

**Comment by jessy-p** [comment]
This looks to be part of ongoing project paJDYF-1eN-p2, so moving to Projects pipeline.
