### ISSUE TITLE
Default settings and additional options for price rounding and charm pricing

### ISSUE THREAD

**Issue by LevinMedia** [Automattic/woocommerce-payments#2091]
### **General updates:**

Update the "Charm pricing label to read "Price charm"
Remove the tool tips before the select menus
remove the "learn more" links from the select menu helper text. I think it should be easy enough to figure it out by playing with the settings and viewing the preview. 

### **Decimal currencies**

**Price rounding options**

None
0.25
0.50
1.00 (recommended) *default
5.00
10.00

**Price charm options**

None *default
-0.01
-0.05

Lets be sure we remove the (recommended) label from the -0.01 in charm pricing

### **Non-decimal currencies**

**Price rounding options**

None
10
25
50
100 (recommended) *default
500
1000

**Price charm options**

None *default
-1
-5
-10
-20
-25
-50
-100

**Comment by luizreis** [comment]
Just noting here that these rounding options will require some small changes to the rounding logic, which works currently by specifying the decimal place we should round to. I think we can support them by simplifying the current rounding logic to be something like `ceil( $price / $rounding ) * $rounding`.
