### ISSUE TITLE
Add currency code suffix to key prices

### ISSUE THREAD

**Issue by LevinMedia** [Automattic/woocommerce-payments#2098]
In order to disambiguate and clarify the customer's choice of currency, we should suffix key prices through out the experience with the selected currency code. 

please follow the guidelines at paJDYF-20W-p2

**Comment by LevinMedia** [comment]
Related: https://github.com/Automattic/woocommerce-payments/pull/2171

**Comment by tpaksu** [comment]
Hi @LevinMedia, just to be sure, we only need this if MC is enabled on WCPay, right? If MC isn't enabled, we won't change anything.
