### ISSUE TITLE
Zip +4 causes validation failure and confusing error message

### ISSUE THREAD

**Issue by WillBrubaker** [Automattic/woocommerce-payments#2101]
While I was testing 4054340-zen I found that a payment will fail if using a zip+4 at checkout.

To reproduce:

1. Add an item to the cart
2. At checkout, use the following address
123 MAIN ST
LEBANON, NJ 08833-2162

Attempt to complete the transaction. Get an error message that the resource can not be accessed:
![see screen shot](https://d.pr/i/046LDn+)

**Comment by leonardola** [comment]
I could not simulate this error. And it is apparently [being generated by stripe.](https://github.com/Automattic/woocommerce-payments/blob/develop/includes/wc-payment-api/class-wc-payments-api-client.php#L1388). Maybe stripe fixed the problem
