### ISSUE TITLE
Customer facing prices compatibility with WooCommerce Subscriptions

### ISSUE THREAD

**Issue by jessepearson** [Automattic/woocommerce-payments#2117]
We are aiming to have Subs support for the MVP. The issues in this epic are what have been found so far that need to be fixed to be compatible.

**Comment by jessepearson** [comment]
Things that still need to be tested:
* Coupons (all types)
* Resubscriptions
* Coupons with early renewals
* Coupons with switches
* Coupons with resubs

**Comment by dwainm** [comment]
Closing this epic as all the issue for it has been closed, cc @jessepearson .
