### ISSUE TITLE
Deposits: when no deposits, inform about regular payout time and possible delays of very first one

### ISSUE THREAD

**Issue by kalessil** [Automattic/woocommerce-payments#2121]
From 2 support rotation sounds, I noticed a bunch of requests related to deposit delays.

While regular payout arrives within 2-3 business days, the initial one might take a longer time to reach the merchant's bank account.

Wondering if we could notify merchants getting the very first payout about possible delays, without causing more support tickets.

**Comment by kalessil** [comment]
Ping @LevinMedia, would like to hear your thought on that.

**Comment by LevinMedia** [comment]
@vbelolapotkov This has been partially solved through better messaging on the WCpay overview screen however, I think we could probably create a better experience on the deposits screen as well.

**Comment by bradyv** [comment]
I P2d a couple of ideas for improving this messaging on the Overview screen: https://wcpay.wordpress.com/2022/05/19/notifying-merchants-of-potential-delays-to-an-upcoming-deposit/

**Comment by vbelolapotkov** [comment]
I think we have all the answers in p2, so moving this one for prioritization.

**Comment by naman03malhotra** [comment]
@kalessil are you folks already working on it?

**Comment by naman03malhotra** [comment]
@Automattic/helix checking if this is under your radar, as part of the prioritization call.

**Comment by haszari** [comment]
I think we should close this issue. There are projects in the backlog to improve communication of deposit timing, and the deposit UI generally, so we don't need this issue.

**Comment by shendy-a8c** [comment]
I thought we are showing deposit schedule in a notice on the deposits list page in this PR https://github.com/Automattic/woocommerce-payments/pull/7883 but after testing with a clean site, the notice does not show up, so maybe we just need to do some tweaking [here](https://github.com/Automattic/woocommerce-payments/blob/c8c3240dc376188f1a822cefd3934cc4970ad849/client/deposits/index.tsx#L78-L87).

Adding to Helix's board.

**Comment by haszari** [comment]
@shendy-a8c when you get a moment, can you update the title and description to explain the specific buggy behaviour you observed? 

My understanding is that we have fixed the issue originally reported, but that there may be some edge cases to fix (i.e. you found one when testing #7883).

**Comment by haszari** [comment]
Closing, we have a notice that explains that the first payout takes longer. If there is a specific gap please open a new issue.
