### ISSUE TITLE
Some Flags not displaying in the Add Currencies modal

### ISSUE THREAD

**Issue by dmallory42** [Automattic/woocommerce-payments#2126]
As part of #2042 we are now pulling all the currency rates from the server using the list provided by `get_woocommerce_currencies()`. However, there are some countries which do not seem to have a corresponding emoji flag. 

<img width="555" alt="Screenshot 2021-06-10 at 11 35 04" src="https://user-images.githubusercontent.com/11770181/121554536-2427bd80-ca0a-11eb-90e3-c700a08b1e4a.png">

An example is West African CFA franc, seen in this screenshot.

To reproduce this behaviour, check out the branch in #2042 and follow the instructions in that PR to test it.

We need to decide how we want to handle these currencies, whether we do in fact want to support them, and whether we need to use a placeholder flag or reconsider what we display here.

Also, we should check the flag for BitCoin (BTC) because currently it is displaying the flag for Bhutan.

**Comment by luizreis** [comment]
As per p1626465307246300/1626373853.199800-slack-C01B8KNUYSW, we're going to add a mock "flag" with the same proportions and border radius as the others, but a solid, gray background with just the code printed on top.
