### ISSUE TITLE
Consider which currencies we want to include in the currencies list

### ISSUE THREAD

**Issue by dmallory42** [Automattic/woocommerce-payments#2127]
Currently, in #2042 we rely on `get_woocommerce_currencies()` to fetch the currency list. However, we should consider whether we want to make all of these currencies available for use in the Multi Currency plugin. For example, should we allow BitCoin? 

If we do allow BitCoin, there's also a visual issue where the flag of Bhutan appears next to  BitCoin in the Add Currencies list.

<img width="310" alt="Screenshot 2021-06-10 at 16 39 23" src="https://user-images.githubusercontent.com/11770181/121554894-6fda6700-ca0a-11eb-9fd5-801b748c1430.png">

**Comment by dmallory42** [comment]
After discussion in team chat: We should leave BitCoin in because some other plugins may support it, even if we don't. But we need to fix which icon appears for BTC and consider a placeholder for unsupported currencies.

**Comment by jessepearson** [comment]
Closing in favor of #2126
