### ISSUE TITLE
Signup fee for subscription not converted 

### ISSUE THREAD

**Issue by jessepearson** [Automattic/woocommerce-payments#2130]
Subscription signup fees are not being converted into the selected currency.
May be related to: #2122

Steps to replicate:

1. Create simple subscription product with a signup fee.
2. View the product, the signup fee is not converted.
3. When adding to the cart, the fee is still not converted.

![Markup 2021-06-10 at 13 58 49](https://user-images.githubusercontent.com/4634416/121566595-09e2e500-c9f4-11eb-8ac0-4d33d8de9a01.png)

**Comment by luizreis** [comment]
Closed by https://github.com/Automattic/woocommerce-payments/pull/2189
