### ISSUE TITLE
Improve overflow scroll on add currencies modal

### ISSUE THREAD

**Issue by ismaeldcom** [Automattic/woocommerce-payments#2145]
The **Add currencies** modal scroll all the modal content except the header on overflow. As per paJDYF-1gf-p2 it should scroll only the currencies list, being the search bar and buttons toolbar sticky.

#### How it looks now
![Screen Recording 2021-06-11 at 14 59 17](https://user-images.githubusercontent.com/7670276/121690618-5dbdfe80-cac6-11eb-9929-7818e1f84caf.gif)

**Comment by tpaksu** [comment]
Hi @ismaeldcom, @dmallory42, do we have any thoughts on having a `max-height` for the currency list? I will need a max height for the inner container to make that scrollable.

**Comment by ismaeldcom** [comment]
Yes, I think we need it. Looks a bit weird having a modal too tall too.
