### ISSUE TITLE
Can't save settings with multiple snackbar notifications open

### ISSUE THREAD

**Issue by waclawjacek** [Automattic/woocommerce-payments#2156]
When there are enough snackbar notifications so that one is horizontally in line with the save button, the button can no longer be clicked.

Tested in Firefox and Chrome.

![Screen Capture on 2021-06-12 at 01-02-02](https://user-images.githubusercontent.com/1759681/121756413-46a8fc00-cb1a-11eb-8314-45826c205d88.gif)

**Comment by frosso** [comment]
FWIW, I noticed the same thing while on the WC core onboarding.
Maybe we can dismiss the notification after a few seconds? Or just preventing adding multiple alltogether?

**Comment by leonardola** [comment]
@waclawjacek  I could not simulate this bug. Does it still happens with the latest version of both WooCommerce and WC Payments for you?

Tested with:
Wordpress: 5.8.1
Woocommerce: 5.7
Wc Payments: Develop Branch
Browser: Firefox, Safari, Chrome


<img width="1500" alt="Captura de Tela 2021-09-24 às 16 44 17" src="https://user-images.githubusercontent.com/6342964/134731506-5faa0722-3707-4c4f-8474-7a8f1c267173.png">

**Comment by waclawjacek** [comment]
Nope! Tested on:

WP 5.8.1
WC 5.4.2
WCPay: develop

Looks like one of the DOM nodes in the hierarchy now has this CSS so even though the notice container extends over the "Save changes" button, the click passes through the container:

```css
.components-snackbar-list {
    pointer-events: none;
}
```

Thank you for looking into this one! Closing because this is no longer an issue.
