### ISSUE TITLE
UPE payment methods task - placeholder

### ISSUE THREAD

**Issue by frosso** [Automattic/woocommerce-payments#2169]
## Description

Display a task in the WCPay home, as well as WC Home to enable additional payment methods.

This ticket's purpose is _only_ to display the task with the correct criteria. Clicking the task can display some placeholder text for the UI work.

See `accountOverviewTaskList`/`_wcpay_feature_account_overview_task_list` feature flag for more details about the existing task list in the WCPay home - p1623726800065300-slack-C01RTUVR81K.

![Screen Shot 2021-06-14 at 7 37 38 PM](https://user-images.githubusercontent.com/273592/121976077-b3094280-cd48-11eb-8525-0c3c8552fcb4.png)

## Acceptance criteria
- ~Task is displayed when https://github.com/Automattic/woocommerce-payments/issues/2154 is enabled~ - DONE IN https://github.com/Automattic/woocommerce-payments/issues/2178
- ~Task is displayed on WC Home~ - DONE IN https://github.com/Automattic/woocommerce-payments/issues/2178
- Task is displayed in WCPay
- ~Task is "completed" when the merchant has interacted with it and/or added the UPE payment methods~ - DONE IN https://github.com/Automattic/woocommerce-payments/issues/2178
  - ~Task is **not** "completed" when UPE is disabled~
  - ~Task is **not** "completed" when UPE is enabled and the merchant has not interacted with it nor added the UPE payment methods~
- ~Clicking the task shows some placeholder text~ - DONE IN https://github.com/Automattic/woocommerce-payments/issues/2178

**Comment by waclawjacek** [comment]
Thanks so much for the pointer towards the two variables: `accountOverviewTaskList`/`_wcpay_feature_account_overview_task_list`! This allowed me to hit the ground running when starting the work on this task.
