### ISSUE TITLE
"Payment methods" section tweaks

### ISSUE THREAD

**Issue by frosso** [Automattic/woocommerce-payments#2175]
## Description

We need to do a few tweaks to the "Payment methods" section

![Screen Shot 2021-06-14 at 8 36 35 PM](https://user-images.githubusercontent.com/273592/121979994-cb7d5b00-cd50-11eb-87c8-fbfd3d9df614.png)

## Acceptance criteria
- Section is displayed when UPE settings flag ( https://github.com/Automattic/woocommerce-payments/issues/2154 ) is enabled (it is currently displayed when "UPE" flag is enabled) - this should already be tackled by https://github.com/Automattic/woocommerce-payments/issues/2154
- When UPE flag is enabled (NOT this one https://github.com/Automattic/woocommerce-payments/issues/2154, but `_wcpay_feature_upe` ):
  - Section has a "Payment methods" heading with "pill" and burger menu
  - Burger menu has 2 items
    - "Provide feedback" item - just a placeholder to display the modal
   - "Disable" item - actionable, allows to disable UPE feature flag
 - When `_wcpay_feature_upe` flag is disabled, https://github.com/Automattic/woocommerce-payments/issues/2174 is displayed instead - just display a placeholder for the time being while the task is being worked on

**Comment by tommyshellberg** [comment]
@frosso regarding the Burger menu's "disable" item:

_"Disable" item - actionable, allows to disable UPE feature flag_

Do we want this to be fully functional(disable the feature flag in the DB) or just affect local state to hide/show the signup banner?
Scrolling through the plugin code, I didn't see any setters for the `upe` feature flag on the PHP side, just getters:

https://github.com/Automattic/woocommerce-payments/blob/f2175e44b1776d59cc518646525d06978e4fb6da/includes/class-wc-payments-features.php#L57

**Comment by tommyshellberg** [comment]
The other thing I'm wondering is if we should really tie the burger menu to the UPE flag. I can see a case in which someone tries UPE, it doesn't go well, they disable it, and _then_ they'd want to send feedback. If it was hidden by the UPE flag it wouldn't be possible to submit feedback 🤔

**Comment by frosso** [comment]
@tommyshellberg thanks for asking! It looks like the mechanism to toggle the feature flag is still under review: https://github.com/Automattic/woocommerce-payments/pull/2239
And the UI for the modal will be handled here: https://github.com/Automattic/woocommerce-payments/issues/2311
So having mocked values is good for now👍

**Comment by jarekmorawski** [comment]
@tommyshellberg, thanks for the ping!

> The other thing I'm wondering is if we should really tie the burger menu to the UPE flag. I can see a case in which someone tries UPE, it doesn't go well, they disable it, and then they'd want to send feedback. If it was hidden by the UPE flag it wouldn't be possible to submit feedback 🤔

The feedback option in the kebab menu is not the key way to share feedback. It's only meant for people who want to share their thoughts before disabling UPE. With UPE turned off, it would be the only option there but we'd have to leave the table header to make space for the kebab menu. The header, on the other hand, is not part of the final UPE experience and we don't really need it there. The idea is to remove the header when UPE is disabled.

> what if we prompt for feedback in a modal after UPE is disabled rather than provide a direct option?

We do! Here is how it works ATM: https://video.wordpress.com/v/qWnNvgEi. Let me know if that's what you had in mind. 😃
