### ISSUE TITLE
Write new e2e test: Shopper / Checkout / Checkout with Payment Request

### ISSUE THREAD

**Issue by veljkho** [Automattic/woocommerce-payments#2207]
Write a new e2e test that covers the following flow:
- Shopper / Checkout / Checkout with Payment Request

**Comment by veljkho** [comment]
Not doable for now. This test requires a Safari browser in order to pay via Apple Pay. Also for Google Pay has problems with automation.

**Comment by vbelolapotkov** [comment]
Closing this since there is no way to automate this.
