### ISSUE TITLE
Write new e2e test: Shopper / Payment methods / Add new payment method

### ISSUE THREAD

**Issue by veljkho** [Automattic/woocommerce-payments#2210]
Write a new e2e test that covers the following flow:
- Shopper / Payment methods / Add new payment method

**Comment by rodelgc** [comment]
Just some notes for myself:

Starting point of test is this:
![Screen Shot 2021-07-07 at 4.57.30 PM.png](https://images.zenhubusercontent.com/60a2535d3762da5e2703d6dd/7f136213-4982-4ac7-b1de-4feda637d4ba)

I'll see if I can reuse the utility function `fillCardDetails()` in the test steps here.
