### ISSUE TITLE
Write new e2e test: Merchant / Order / Manual capture

### ISSUE THREAD

**Issue by veljkho** [Automattic/woocommerce-payments#2211]
Write a new e2e test that covers the following flow:
- Merchant / Order / Manual capture

**Comment by rodelgc** [comment]
Hi @veljkho. In this flow, I realized that I will need to enable this setting in WC Payments:
![Screen Shot 2021-07-31 at 1.44.32 AM.png](https://images.zenhubusercontent.com/60a2535d3762da5e2703d6dd/8f4c0aee-9624-4f4f-a770-b4deef0a39ed)

Is it safe to do so? Or will it affect other tests? Thanks!

**Comment by veljkho** [comment]
Hi @rodelgc 
Can you make the function in afterAll to deselect at the end? I do that when turning ON some settings.

**Comment by rodelgc** [comment]
Thanks @veljkho. I'll make sure to disable that option in afterAll.
