### ISSUE TITLE
Write new e2e test: Merchant / Disputes / Dispute created notifications

### ISSUE THREAD

**Issue by veljkho** [Automattic/woocommerce-payments#2214]
Write a new e2e test that covers the following flow:
- Merchant / Disputes / Dispute created notifications

**Comment by veljkho** [comment]
Hi @vbelolapotkov 
I was about to start automating this E2E flow, but haven't found a way to do that. Could you please let me know if you know what is this flow about? I thought it is about receiving an email for a customer after losing or winning dispute, but was not the case. Feel free to respond anytime, this will be on hold until we figure out what's the flow about. Thanks!

**Comment by vbelolapotkov** [comment]
Hey @veljkho ! Here is the flow description: https://github.com/Automattic/woocommerce-payments/wiki/Testing-instructions-for-critical-flows#dispute-created-notifications

Apparently this one includes checks for dispute email content as well as for dispute overview page.

To automate this one you'd definitely need webhooks working in e2e environment. Some additional tooling might be needed as well.

**Comment by veljkho** [comment]
Hey @vbelolapotkov 
I have solution for receiving emails and checking the content inside.. but did you mean that I should have Stripe webhooks working in the env? If that's the case, isn't that the same issue that we have with showing data for Transactions/Deposits, we need webhooks also there?

I have now 7 blocked flows due to that problem and this Dispute Created Notification could be the 8th blocked flow.

**Comment by vbelolapotkov** [comment]
With that said sounds like it's time to create a solution for that problem :) Is there an option to create some tunneling solution or mock Stripe hooks as workaround?

**Comment by veljkho** [comment]
@vbelolapotkov There's an open discussion on Slack [here](https://a8c.slack.com/archives/C01B82V67DL/p1625580563174600), please visit it and if you have any thoughts on that, feel free to join the discussion. For now, all the rest flows will be automated and we can continue on blocked flows (8) after we have the solution for webhooks.

**Comment by haszari** [comment]
Closing as task from previous project. There are many e2e tests we could add or improve, this is just one specific example.

If this test is critically important to add soon, please add comment with rationale and reopen.
