### ISSUE TITLE
Write new e2e test: Merchant / Admin / Download transactions as CSV file

### ISSUE THREAD

**Issue by veljkho** [Automattic/woocommerce-payments#2217]
Write a new e2e test that covers the following flow:
- Merchant / Admin / Download transactions as CSV file

**Comment by veljkho** [comment]
Blocked flow: There's a [Slack discussion](https://a8c.slack.com/archives/woo-transact/p1625580563174600) about this problem. In short, we do not display data from Transactions & Deposits within the local environment so the pages are empty (no data at all), and that's why we can't automate the flow since no data to deal with. The reason behind might be in the fact that the webhook listener doesn’t run, more in this [Slack discussion](https://a8c.slack.com/archives/wcpay-e2e/p1625123905011400). And lastly, noting one finding from a developer in this [Slack discussion](https://a8c.slack.com/archives/wcpay-e2e/p1630049370004900) which is about enabling Stripe account to be synced with the e2e environment in which case it would work.

**Comment by naman03malhotra** [comment]
Asked follow-up question here: p1640089119060000-slack-C026J0AL8NS

**Comment by haszari** [comment]
Closing as task from previous project. There are many e2e tests we could add or improve, this is just one specific example. 

If this test is critically important to add soon, please add comment with rationale and reopen.
