### ISSUE TITLE
Write new e2e test: Shopper / Subscriptions / Purchase subscription product

### ISSUE THREAD

**Issue by veljkho** [Automattic/woocommerce-payments#2220]
Write a new e2e test that covers the following flow:
- Shopper / Subscriptions / Purchase subscription product

**Comment by dechov** [comment]
Is this separate from what's already in place [here](https://github.com/Automattic/woocommerce-payments/blob/develop/tests/e2e/specs/merchant/merchant-subscriptions-purchase-sign-up-fee.spec.js) and [here](https://github.com/Automattic/woocommerce-payments/blob/develop/tests/e2e/specs/merchant/merchant-subscriptions-purchase-no-sign-up.spec.js)?

**Comment by veljkho** [comment]
No, it isn't. Looks like we have it already in the test suite. I closed many issues already since we have had them covered already. I'll check again when it comes to place.
