### ISSUE TITLE
Write new e2e test: Shopper / WooCommerce Blocks / Checkout with Payment Request

### ISSUE THREAD

**Issue by veljkho** [Automattic/woocommerce-payments#2230]
Write a new e2e test that covers the following flow:
- Shopper / WooCommerce Blocks / Checkout with Payment Request

**Comment by veljkho** [comment]
Not doable for now. This test requires a Safari browser in order to pay via Apple Pay. Also for Google Pay has problems with automation.

**Comment by veljkho** [comment]
Flow blocked, Slack discussion is [here](https://a8c.slack.com/archives/triage/p1625126056016800). We need to find a way to automate this but obstacles are:
- Test site must have SSL (https)
- Using real AppleID and Apple Wallet Card (also for GooglePay)
- ApplePay is working on Safari browser only, but with Puppeteer we're using Chromium

**Comment by naman03malhotra** [comment]
Hi @veljkho, is there a follow-up issue that fixes the above-mentioned obstacles? Seems like an important flow, do we have any plans to take it forward?
FYI: I am in process of triaging the issues for WCPay repo.

**Comment by veljkho** [comment]
Hi @naman03malhotra 
As far as I know, after we [Solarians left WCPay](https://wp.me/paJDYF-2I5) project about implementing E2E tests, I don't think there is anything done regarding it, and it might be still a question if it is doable at all. You can try asking someone from WCPay or in Slack channel `#wcpay-e2e` about the status of the issue.

**Comment by naman03malhotra** [comment]
Asked follow-up question here: p1640089119060000-slack-C026J0AL8NS

**Comment by vbelolapotkov** [comment]
Closing this one since it's not possible.
