### ISSUE TITLE
Display fee breakdown in transaction timeline.

### ISSUE THREAD

**Issue by jrodger** [Automattic/woocommerce-payments#2233]
All transactions are subject to a base fee (determined by the merchant's country) plus a number of additional fees (like international card processing, FX fees etc).

We currently only show the total fee. We want to break this number down to make it clearer how the final rate was calculated.

**Timeline**
![image](https://user-images.githubusercontent.com/686419/122224503-152e8880-ceac-11eb-8a8a-273ea22cc64a.png)

cc @LevinMedia

**Comment by vbelolapotkov** [comment]
⚠️ Note: releasing solution for this issue needs to be synced with communication discussed here: pbUcTB-eC-p2#comment-1290 . So double check it before merging.

cc @kalessil for awareness.

**Comment by naman03malhotra** [comment]
Created a separate issue to track, display fee breakup in order notes: https://github.com/Automattic/woocommerce-payments/issues/2522
