### ISSUE TITLE
Move completed task to the bottom

### ISSUE THREAD

**Issue by octaedro** [Automattic/woocommerce-payments#2238]
As a follow-up of [PR 2148](https://github.com/Automattic/woocommerce-payments/pull/2148).
Every completed task should be moved to the bottom of the list.

![screenshot-fermarichal jurassic tube-2021 06 16-14_52_36](https://user-images.githubusercontent.com/1314156/122268573-99840a00-ceb2-11eb-9fbe-4c29a20eabbe.png)

**Comment by mattsherman** [comment]
Closing this -- implemented in #2328.
