### ISSUE TITLE
Basic support for analytics

### ISSUE THREAD

**Issue by luizreis** [Automattic/woocommerce-payments#2249]
As part of the MVP, we should provide basic support for analytics (paJDYF-1C7-p2#comment-6458). The original designs can be significantly simplified for the MVP scope. In short, we would remove all filtering functionality (IE: filtering by customer currency, and viewing analytics in a single customer currency).

Data in orders that are processed using a customer currency would simply be converted to the store’s default currency at the time of the transaction, then the converted data would populate the analytics tables. This approach preserves the accuracy of the merchant’s analytics data. 

Design thread: paJDYF-1l7-p2

-----

It looks like the order sync exposes [a filter](https://github.com/woocommerce/woocommerce-admin/blob/f6155f3cf1a7e414e81b93551a7e13860a5c5ce1/src/API/Reports/Orders/Stats/DataStore.php#L509) that can be used to convert the prices before they're stored in the lookup tables. However, not every analytics controller implements those, so we'd have to find a workaround. E.g. [coupon sync](https://github.com/woocommerce/woocommerce-admin/blob/f6155f3cf1a7e414e81b93551a7e13860a5c5ce1/src/API/Reports/Coupons/DataStore.php#L393) and [product sync](https://github.com/woocommerce/woocommerce-admin/blob/f6155f3cf1a7e414e81b93551a7e13860a5c5ce1/src/API/Reports/Products/DataStore.php#L434).

**Comment by dwainm** [comment]
Adding this text tag:  **must-have for MVP** so it can easily be searched for.
