### ISSUE TITLE
Implement a captcha in the WCPayments setup flow to prevent bad actors from creating account

### ISSUE THREAD

**Issue by pmcpinto** [Automattic/woocommerce-payments#2256]
**Description:** we want to start exploring the possibility of implementing a captcha in the WCPayments setup flow as a way to block bad actors to create an account.

**Comment by pmcpinto** [comment]
@elizaan36 where do you think we could show the captcha? We have 4 main entry points to the KYC flow:

- Welcome screen
- Payments task
- WCPayments task
- WPCOM account flow

**Comment by elizaan36** [comment]
The only thing is that we'd have to implement it on all of these entrypoints, since they are different pathways to create an account. The only common denominator is the KYC - is there any way to implement it in the flow there, either on the first step or at the very end?

**Comment by pmcpinto** [comment]
@elizaan36 thanks for your feedback. In the meantime, it was decided not to move forward with this, as it would have a negative impact on the conversion rate. The team is exploring different alternatives to stop bad actors

**Comment by naman03malhotra** [comment]
Closing this issue as per: https://github.com/Automattic/woocommerce-payments/issues/2256#issuecomment-866860072
