### ISSUE TITLE
Customer currency detection by geolocation

### ISSUE THREAD

**Issue by ismaeldcom** [Automattic/woocommerce-payments#2257]
Detect the customer local currency using geolocation. This will allow us to use the Multi-currency store settings _"Automatically switch customers to the local currency if it is enabled above"_.

The detection is thigh related with #2247

**Comment by luizreis** [comment]
#2312 adds a country detection based on the customer address, which should be used as a fallback when geolocation is not configured or the customer country cannot be identified.

**Comment by jessepearson** [comment]
Noting here that a Maxmind account has been created for us, more info in Slack: p1625577596398500-slack-C01B8KNUYSW
