### ISSUE TITLE
Alert customers about automatic currency update

### ISSUE THREAD

**Issue by ismaeldcom** [Automattic/woocommerce-payments#2258]
If the merchant has enabled _"Automatically switch customers to the local currency if it is enabled above"_ in Multi-currency store settings. We should show an alert message to customers when we update their currency based on geolocation.

❕Include and anchor at the end of the alert text with `Use [store currency name] instead`, to allow the customer to switch back to default store currency.

The preview link will be handled in https://github.com/Automattic/woocommerce-payments/issues/2523.

### Design
<img width="1440" alt="Screenshot 2021-06-18 at 11 09 45" src="https://user-images.githubusercontent.com/7670276/122537378-cad11700-d025-11eb-9184-85dbc39b4fe4.png">

**Comment by LevinMedia** [comment]
@ismaeldcom would it be possible to add a link to the end of the text string that reads `Use [store currency name] instead` ?

This will smooth out the experience for stores that might have issues getting the switcher widget set up.

**Comment by ismaeldcom** [comment]
Sound good @LevinMedia, edited to first comment to add it 🙂

**Comment by luizreis** [comment]
> Also need to update Settings class to complete // TODO: Preview link, to be done on #2258.

@LevinMedia - Should this preview link be a link to our docs with a screenshot of the notice? Or should we somehow reproduce the note on the merchant's site?

If the latter, I think it'd be better to handle it in a separate issue, as it's not going to be that straightforward.

**Comment by ismaeldcom** [comment]
Hey @luizreis I think it's the latter, specially cause of the last addition: `❕Include and anchor at the end of the alert text with Use [store currency name] instead, to allow the customer to switch back to default store currency.`

**Comment by LevinMedia** [comment]
@luizreis I was thinking it would be the latter - if it's going to be significantly more work, we can split it out into it's own issue as you've suggested. For now we can simply leave the "preview" feature off of the MVP.
