### ISSUE TITLE
Create documentation for integrating the currency switcher widget directly into a theme

### ISSUE THREAD

**Issue by LevinMedia** [Automattic/woocommerce-payments#2265]
Related https://github.com/Automattic/woocommerce-payments/issues/2264

Use the related issue as a guide for creating documentation that explains how to integrate the currency switcher widget into a theme. The doc should be geared towards theme builders.

**Comment by dwainm** [comment]
We will not have this ready as part of the MVP as the current implementation doesn't lend itself to be easily extensible or integrated into another theme. We need to rework our solution to allow for a simpler API.

I'm thinking about a function that a theme provider can call that would take care of everything:

```
wcpay_show_currency_switcher()
```

A function like this should:

1 - Hide the complexity
2 - Output the widget
3 - Take care of any base styling
4 - Take care of the form functionality
5 - Include all the filters and actions needed for full control of the display.

After doing the above our guide could be around styling and customization options.


cc @LevinMedia

**Comment by tpaksu** [comment]
This issue is dependent on #1767, right?

**Comment by jessepearson** [comment]
@tpaksu Yes, it is 😁

**Comment by daquinons** [comment]
Added the documentation here https://docs.woocommerce.com/document/payments/currencies/multi-currency-setup/#section-14
