### ISSUE TITLE
Improve Transactions list header overflow styling

### ISSUE THREAD

**Issue by dechov** [Automattic/woocommerce-payments#2269]
The Download button and dropdown menu seem to be shifted off screen to the right there is too large of a search query, and the query terms (and placeholder) themselves don't seem to wrap in an ideal way. (Also, there's an odd line under the search field 'X' button.)

Placeholder text cut off:
<img width="867" alt="Screen Shot 2021-06-18 at 2 38 19 PM" src="https://user-images.githubusercontent.com/1867547/122604970-c9fbad80-d044-11eb-88a0-a32beaeb00d1.png">

Wrapped terms but box doesn't adjust, and input box no longer visible (no Download button because there are no results):
<img width="866" src="https://user-images.githubusercontent.com/1867547/122605861-07146f80-d046-11eb-9395-28d9556bb140.png">

Same query at various screen widths:
<img width="912" alt="Screen Shot 2021-06-18 at 2 37 44 PM" src="https://user-images.githubusercontent.com/1867547/122604971-ca944400-d044-11eb-911b-fb7c9c5a6ce3.png">
<img width="795" alt="Screen Shot 2021-06-18 at 2 36 57 PM" src="https://user-images.githubusercontent.com/1867547/122604972-ca944400-d044-11eb-94e4-6d89195d0beb.png">
<img width="727" alt="Screen Shot 2021-06-18 at 2 36 41 PM" src="https://user-images.githubusercontent.com/1867547/122604976-cb2cda80-d044-11eb-9292-85bc72ac5c26.png">
<img width="715" alt="Screen Shot 2021-06-18 at 2 36 24 PM" src="https://user-images.githubusercontent.com/1867547/122604978-cb2cda80-d044-11eb-8c59-7da25494d842.png">
<img width="582" alt="Screen Shot 2021-06-18 at 2 36 13 PM" src="https://user-images.githubusercontent.com/1867547/122604979-cb2cda80-d044-11eb-83d4-f92b6b4e0342.png">
<img width="511" alt="Screen Shot 2021-06-18 at 2 36 00 PM" src="https://user-images.githubusercontent.com/1867547/122604981-cbc57100-d044-11eb-8e5c-b708145af228.png">
<img width="428" alt="Screen Shot 2021-06-18 at 2 35 39 PM" src="https://user-images.githubusercontent.com/1867547/122604982-cbc57100-d044-11eb-816d-8c0866990c2d.png">

**Comment by LevinMedia** [comment]
@Mayisha thanks for bringing this issue to my attention. When I originally designed this feature, I intended it to only support a single query. So I think we can start by limiting the query to one parameter. 

We still may have to deal with overflow however. If the chip containing the query param extends past the confines of the input field, you can make the overflow hidden. You'd have to scroll to the right in the input to see the X button that's attached to the chip containing the query param.

**Comment by naman03malhotra** [comment]
PR in progress: https://github.com/woocommerce/woocommerce-admin/pull/7972

**Comment by nagpai** [comment]
#8996 fixes this issue. Closing it, thanks.
