### ISSUE TITLE
Update Wooniversity docs

### ISSUE THREAD

**Issue by frosso** [Automattic/woocommerce-payments#2270]
## Description

With the release of the newer version of the settings screen, we need to update the Wooniversity docs.

Example of page: PbTz5e-LH-p2#manual-capture

## Acceptance criteria
- Wooniversity docs are updated
  - Screenshots referring to the settings page(s) are updated to reflect the new designs
  - Wording describing settings pages is updated to reflect the new designs

**Comment by naman03malhotra** [comment]
Verify and close it

**Comment by frosso** [comment]
Done.
