### ISSUE TITLE
Check if grouped settings are enabled before migrating express checkout settings

### ISSUE THREAD

**Issue by waclawjacek** [Automattic/woocommerce-payments#2301]
Currently [there is a migration](https://github.com/Automattic/woocommerce-payments/blob/0b9f113a0ce2b971a4c7458eded714f41caf0ee3/includes/migrations/class-allowed-payment-request-button-types-update.php#L28) that is programmed to run after the plugin is updated to version 2.6.0.

With some uncertainty about whether grouped settings will be released in 2.6.0, an extra check should be added to the migration so it doesn't run if grouped settings aren't actually enabled. 

This can be achieved by checking if the `_wcpay_feature_grouped_settings` feature flag is set to `true`.

**Comment by frosso** [comment]
Closing, since we released with the flag enabled
