### ISSUE TITLE
Clicking "Enable in your store" links to the onboarding wizard

### ISSUE THREAD

**Issue by harriswong** [Automattic/woocommerce-payments#2323]
## Description
A follow up from https://github.com/Automattic/woocommerce-payments/issues/2174#issuecomment-867939824. Clicking the "Get started" will link to this onboarding wizard (https://github.com/Automattic/woocommerce-payments/issues/2169). 

See https://github.com/Automattic/woocommerce-payments/issues/2174#issuecomment-867928885

**Comment by harriswong** [comment]
@frosso Just want to check with you regarding [this comment](https://github.com/Automattic/woocommerce-payments/issues/2174#issuecomment-867928885).

Clicking on "Get started" should just redirect to [this link](wp-admin/admin.php?page=wc-admin&task=woocommerce-payments--additional-payment-methods) right?

**Comment by frosso** [comment]
@harriswong to clarify, the task redirects to `wp-admin/admin.php?page=wc-admin&task=woocommerce-payments--additional-payment-methods`.
Clicking "Get started" should activate the feature flag and then redirect to `wp-admin/admin.php?page=wc-admin&task=woocommerce-payments--additional-payment-methods` with the second task activated.

The step that "pre-selects" the task is already done: https://github.com/Automattic/woocommerce-payments/blob/ac8066be6b6d5ec620c2d8eeb208105f29787254/client/additional-methods-setup/upe-preview-methods-selector/index.js#L26-L31
And the code that activates the feature flag also exists (you can either use the existing hook or activate the feature as a side effect on the server): https://github.com/Automattic/woocommerce-payments/blob/ac8066be6b6d5ec620c2d8eeb208105f29787254/client/settings/wcpay-upe-toggle/hook.js#L11-L15

So now it's a matter of ensuring that on click of the "Get started" button all that happens :)

**Comment by harriswong** [comment]
Some of these codes are added in develop. It would be easier to cherry pick line of codes into this other PR instead (commit: 62062c3)

Closing this as this issue will now be resolved by https://github.com/Automattic/woocommerce-payments/pull/2314.
