### ISSUE TITLE
"Payments" settings not accessible in navigation when WCPay not connected

### ISSUE THREAD

**Issue by dechov** [Automattic/woocommerce-payments#2327]
When WCPay is active, navigating to **WooCommerce » Settings » Payments** (WC core settings tab) now yields this screen:

<img width="1118" src="https://user-images.githubusercontent.com/1867547/123558066-623f1400-d762-11eb-89a9-699f3bcf7228.png">

While the list of available payment gateways is still accessible by clicking "All payment methods", that is not the case **when WCPay is not connected**, in which case this screen is shown:

<img width="1121" src="https://user-images.githubusercontent.com/1867547/123558065-61a67d80-d762-11eb-8b23-2bd7a14ec00e.png">

**Comment by shohanhossainnab** [comment]
The only way to get past this screen is to disable WC Payment.
