### ISSUE TITLE
Terminal Locations API: client endpoints

### ISSUE THREAD

**Issue by allendav** [Automattic/woocommerce-payments#2334]
Stripe Terminal SDK version 2 (and higher) requires ALL card readers to have locations, not just the Verifone reader. When 2.0 becomes required later this year, the mobile apps will need to be able to use the Locations API for readers.

The Locations API is detailed here: https://stripe.com/docs/api/terminal/locations

This issue is a somewhat large epic and the work could be broken down with separate pushes for List all Locations, Create a Location, Retrieve a Location, Update a Location and, if needed Delete a Location.

In addition to work in the mobile apps, this effort has a related server effort.

Requirements:
- client to provide a set of endpoints, proxying calls to the server side

**Comment by kalessil** [comment]
Related to 934-gh-Automattic/woocommerce-payments-server

**Comment by kalessil** [comment]
See also: pdfdoF-4b-p2

**Comment by kalessil** [comment]
Depends on endpoints tickets for server part.

**Comment by deepakpathania** [comment]
Server endpoints for creating and retrieving locations were added in this [PR](https://github.com/Automattic/woocommerce-payments-server/pull/1145). Will add the corresponding calling logic for these two in the client. cc @jessy-p
