### ISSUE TITLE
Update logo on connection screen

### ISSUE THREAD

**Issue by dechov** [Automattic/woocommerce-payments#2345]
Use standardized WCPay logo (with proportionally larger "Payments") in connection screen banner.

See PaqDfi-1me-p2 » Brand Guidelines PDF » Logo » Standard Lockup

Current appearance:
<img width="723" src="https://user-images.githubusercontent.com/1867547/124186758-c4fa1d80-da8a-11eb-848e-25a749aaf1db.png">

Looks like the current logo is an SVG (originally added in https://github.com/Automattic/woocommerce-payments/pull/1600 – cc @adrianduffell)

cc @elizaan36 @LevinMedia

**Comment by LevinMedia** [comment]
The correct SVG version of the logo is available in p1628519670089900-slack-C2CM2ELTG

The card brands we should be displaying are Visa, Mastercard, Amex, Discover, and Diners Club

**Comment by dechov** [comment]
Thanks! Specifically in p1628527324102900/1628519670.089900-slack-C2CM2ELTG it looks like

**Comment by dechov** [comment]
Also FYI this logo shows up on the Settings screen now as well
