### ISSUE TITLE
Align table items according to the design.

### ISSUE THREAD

**Issue by naman03malhotra** [Automattic/woocommerce-payments#2351]
### Issue description
Presently all the items in the table (transactions, deposits, dispute page) are centrally aligned. Text fields should be left-aligned and numeric values should be right-aligned.

Design link: cGBqV73qDcMXwRDI5JSy4nH8-fi-2%3A258
More context on slack thread: p1623882603153200-slack-CGGCLBN58

**Comment by htdat** [comment]
Note to myself: 

- On Deposists page `isLeftAligned` used here.  We can simply declare this option to `true` then the relevant field will be aligned correctly! 
https://github.com/Automattic/woocommerce-payments/blob/5e12c8a7f031778eaa79001232479c9395c29065/client/deposits/list/index.js#L39-L39

- This option `isLeftAligned` is consumed in the upstream here 
https://github.com/woocommerce/woocommerce-admin/blob/015e2c0a736bed46b64a3385f63226ac5be81dda/packages/components/src/table/table.js#L310

- [ ] Update column to reflect isLeftAligned in WCPay. 
- [ ] Maybe remove these CSS in WCPay too: 
https://github.com/Automattic/woocommerce-payments/blob/5e12c8a7f031778eaa79001232479c9395c29065/client/transactions/list/style.scss#L22-L24
- [ ] In woo-admin, if `isLeftAligned` is not provided, we can fallback to check if `isNumeric`. This seems to work `isLeftAligned || ! isNumeric `?
