### ISSUE TITLE
Clarify presentation of "Temporarily Suspended" message for deposits on new merchant signups.

### ISSUE THREAD

**Issue by evanzi** [Automattic/woocommerce-payments#2383]
When merchants signup for a new account, upon acceptance by the payment processor most accounts have a 7-day waiting period for payouts to become enabled. During this same 7 day period some accounts are flagged for review based on risk, and receive human-review within that initial 7 day period. 

Merchants are presented with this message:
<img width="417" alt="image" src="https://user-images.githubusercontent.com/6063624/124969622-eb710900-dff4-11eb-88bb-76fe9ead6c87.png">

In practice this has generated support inquiries and concern even though any account review will be completed before the initial 7-day waiting period has ended. 

We'd recommend changing this so that it does not appear in this manner during the initial 7-day waiting period after approval by the payment processor. We expect this will reduce concern from merchants and unnecessary support inquiries.

**Comment by aheckler** [comment]
We should also avoid saying "Temporarily suspended" when payouts are set to be done manually, as opposed to on an automated schedule.

**Comment by anant1811** [comment]
Also reported in 4625665-zen

**Comment by aheckler** [comment]
4828336-zen

**Comment by aheckler** [comment]
4859750-zen

**Comment by aprea** [comment]
I am closing this issue as we have completed this work as part of the Custom Deposit Schedules project (pdjTHR-1c8-p2). Please see 2192-gh-Automattic/woocommerce-payments-server.
