### ISSUE TITLE
Maybe add `currency_format` data to transient

### ISSUE THREAD

**Issue by jessepearson** [Automattic/woocommerce-payments#2397]
The `load_locale_data` method in `FrontendCurrencies` will load all of the locales available and loop through them, and that array appears to be ~248 items at the moment. Would it be worthwhile to add that data to a transient for an hour (or longer) to help speed up the process?

The file I am referring to is here:
https://github.com/Automattic/woocommerce-payments/blob/develop/includes/multi-currency/FrontendCurrencies.php

**Comment by dmallory42** [comment]
I think this would definitely be worth exploring.

Just to add a quick note about transients, when I was working on caching the server side rates, @marcinbot mentioned the following: 

> Also a note: don't use transients for caching in the client. We learned this the hard way with the account caching :) Using get/set_option should be sufficient, and works pretty much the same behind the scenes.

We should check with @marcinbot whether the issues he referred to with transients could apply here. If they do, we can use an option value with a check to see if it has expired, similarly to how we ended up implementing the[ server-side caching of rates.](https://github.com/Automattic/woocommerce-payments/blob/d7ee77badd02f0f69aa848b8f98b041af37b1598/includes/multi-currency/MultiCurrency.php#L717-L733)
