### ISSUE TITLE
Allow the merchant to enable ApplePay for their store

### ISSUE THREAD

**Issue by allendav** [Automattic/woocommerce-payments#24]
The scope of this is to enable core functionality without more advanced branding options.

cc @LevinMedia some design feedback based on experience with Stripe plugin would be helpful here.

More context is here: paJDYF-P1-p2#comment-3493

**Comment by dechov** [comment]
The Stripe extension [handles domain verification automatically](https://github.com/woocommerce/woocommerce-gateway-stripe/blob/master/includes/class-wc-stripe-apple-pay-registration.php) and we'll want to do the same (maybe on the server, maybe not). Doesn't seem like we'll need to worry about a domain association file, just the domain registration, according to [this "Use the Payment Request Button with Stripe Connect" doc section](https://stripe.com/docs/stripe-js/elements/payment-request-button#html-js-using-with-connect).

**Comment by jerrysarcastic** [comment]
Another request here on Facebook:  https://www.facebook.com/154986584179/posts/10159020371989180?comment_id=10159034535209180

**Comment by dechov** [comment]
Opened child issues for:
- Domain verification: https://github.com/Automattic/woocommerce-payments/issues/1071
- Payment Request Button integration: https://github.com/Automattic/woocommerce-payments/issues/1072

Focusing on the latter this week and part of last, I'm making an attempt to migrate and adapt the Stripe extension's Payment Request module.

Haven't considered product or cart **block** integration yet, which is likely worth another issue prioritized separately. There is a cart block integration with the Stripe gateway in the WooCommerce Blocks package bundled in core, for reference.

**Comment by ricardo** [comment]
Just as a quick comment, before #1175 gets merged, there are a few issues that need to be addressed:

* The settings page doesn't match the `wp_options` settings. We need to make sure the Payment Request is enabled by default and make the default match the missing settings.
* Fix Custom and Branded buttons settings.
* Import styles for custom Payment Request button from Stripe Gateway Extension.
* Add tests.

**Comment by ricardo** [comment]
Closing, as it was released in 2.2.0.
