### ISSUE TITLE
E2E: Add file upload to a dispute evidence submission test

### ISSUE THREAD

**Issue by dechov** [Automattic/woocommerce-payments#2406]
Verify that file upload is working by including a file upload in the evidence submission flow (perhaps in [this existing test](https://github.com/Automattic/woocommerce-payments/blob/develop/tests/e2e/specs/merchant/merchant-disputes-submit-winning.spec.js)).

**Comment by haszari** [comment]
Unclear how to prioritise issues for specific e2e tests – I think we should drive e2e coverage from flows, and suspect this is not the only gap. Labelling as medium priority for now.

**Comment by haszari** [comment]
I'm going to close this – we need to drive our e2e coverage from flows holistically. Specific issues to add individual test scenarios are hard to prioritise, and may not represent the most pressing needs.
