### ISSUE TITLE
Clicking the Back button in the APM setup tasks always goes to WC > Home

### ISSUE THREAD

**Issue by waclawjacek** [Automattic/woocommerce-payments#2454]
After clicking the button to start the setup on WCPay > Overview, the code redirects to the task's WC > Home page. This has the consequence that clicking the "Back" button in the top-left corner of the page results in going to WC > Home even if you initiate the wizard on the WCPay > Overview page.

The "Back" button should lead back to the page initiating the setup.

**Solution ideas:** If possible, adding a `redirect_to` param to the back button should resolve this. If not, displaying the task in a custom view without a redirect is another option.

**Comment by htdat** [comment]
> After clicking the button to start the setup on WCPay > Overview, the code redirects to the task's WC > Home page. 

I've tested clicking "Finish Setup" in WP Admin > Payments right after installing WCPay in a fresh site, and this seems not an issue anymore.

@waclawjacek - can you check and see if it's still an issue? If it is, some more detailed steps to replicate the issue would be helpful. 

A side note: I am doing triage for WCPay repos.

**Comment by htdat** [comment]
Thank you! Closing this issue.
