### ISSUE TITLE
Hide button from APM setup task on WCPay > Overview

### ISSUE THREAD

**Issue by waclawjacek** [Automattic/woocommerce-payments#2455]
Currently a button is displayed for every task on the WCPay > Overview task list.

![Markup on 2021-07-06 at 12:17:09](https://user-images.githubusercontent.com/1759681/124585587-b8dcda00-de55-11eb-976d-bd4e8b75e6a2.png)

Work is underway to allow these buttons to be hidden: https://github.com/woocommerce/woocommerce-admin/pull/7263 Once this is implemented, utilize the `showActionButton` prop to hide the button to match the Figma design.

**Comment by frosso** [comment]
Do you think we can just pass `showActionButton={false}` now, so that when we upgrade we won't need to remember to do this?
The prop doesn't exist, but once it does after the upgrade the component will get the correct behavior.

**Comment by waclawjacek** [comment]
I guess we will have to check if everything is working once that prop is available anyway so the issue should probably stay here. Just in case something changes in the meantime (especially the prop name), we could wait with the implementation so we're not left with a prop that does nothing. :shrug: WDYT?

**Comment by frosso** [comment]
Sounds like a good plan 👍

**Comment by waclawjacek** [comment]
@LevinMedia Done in #2678.

After implementing that, I've realized that we can actually now update `@woocommerce/experimental` to `1.4.0` and hide the buttons as initially planned. Doing so makes the list look like this:

![Markup on 2021-08-05 at 19:05:31](https://user-images.githubusercontent.com/1759681/128391738-86b7eaaa-483d-4023-84a7-8dbfe3cac163.png)

Should I do that instead?

**Comment by waclawjacek** [comment]
@LevinMedia I have published this alternative PR that hides the buttons instead: #2680. Please let me know which one we should go with and I'll remove the other one.

**Comment by LevinMedia** [comment]
@waclawjacek I just had a quick chat with @elizaan36 about these - the button was actually introduced as an option for the highest priority tasks, so we'd like to keep the button for the "Update WooCommerce Payments business details" task and the "Reconnect WooCommerce Payments" task as well. The CTA's on the buttons would be "Update" for the first and "Reconnect" for the latter. 

The lower priority tasks should not have a button.

**Comment by octaedro** [comment]
Thank you @mattsherman for the ping. No, it's completely done. I'm going to close this issue.
