### ISSUE TITLE
Expose ability to reonboard with live account

### ISSUE THREAD

**Issue by dechov** [Automattic/woocommerce-payments#2459]
After an account is connected, we could reduce friction in some cases by allowing re-onboarding. For instance, if a site builder has connected an account with their own details, but then wishes to allow the merchant to create their own account, there is currently no path within the product that supports this.

If we were to **allow disconnecting (and perhaps deleting) a connected Stripe account** via the admin, a new account could then be onboarded and linked to the same WPCOM site ID. We should **restrict this to "new" accounts**, i.e. those with no live transactions.

(Discussed a bit in p1626406463393500-slack-CGGCLBN58)

Will require a server change to:
- trigger disconnecting (and/or possibly deleting) a Stripe account
- (probably) include in the account info an indication of whether there are any live transactions yet

**Comment by dechov** [comment]
@LevinMedia I added a "needs design" label but I don't think it needs to wait on anything fancy – would a simple "Remove account" link/button on the overview screen suffice?

**Comment by LevinMedia** [comment]
@dechov perhaps this is something we could add to the "advanced settings" section. We'll take a look at it in design this week.

**Comment by dechov** [comment]
I'd opened this issue prior to remembering that the "dev mode" implementation was intended to accommodate that "site builder" use case (as discussed in p1627671672020700-slack-CGGCLBN58), so making that option _more available_ to site builders would get us most of the way to a solution.

However, we're still missing an entry point for that in the product itself @LevinMedia – and I like the kebab option since it's an account action and not a gateway setting – but whatever ya'll decide is fine by me.

In any case, **I think "reonboarding" is probably better than just "disconnecting" as a way to consider this feature**  – we already "support" reonboarding in the case of a test account being replaced with a live account, but need UI for it. We can also _consider_ broadening that condition (on the server) to allow _any account with no live transactions_ to be replaced – again, _perhaps_ deleting the old account as well – but if _test accounts_ entirely fit the needs of site builders, there's little reason to make this change.

(Do let me know of any objection / disagreement but changing title to reflect the above for now.)

**Comment by dechov** [comment]
This could possibly be closed in favor of https://github.com/Automattic/woocommerce-payments/issues/3469. (I think I forgot this one existing when opening that one.)
