### ISSUE TITLE
Payment method checkboxes mobile view

### ISSUE THREAD

**Issue by frosso** [Automattic/woocommerce-payments#2466]
## Description

The checkboxes for the payment methods are not looking great on mobile view.
Can we improve them?

They are displayed in a few places:
- "Add payment methods" modal
- Onboarding task

![2021-07-16 15 19 34](https://user-images.githubusercontent.com/273592/126004544-e7d37e2c-11c7-4de6-9b2a-41490d1a6122.gif)

A patch has been added here to ensure that the whole thing doesn't fully break: https://github.com/Automattic/woocommerce-payments/pull/2468

**Comment by frosso** [comment]
Removed from the milestone.
This would be a nice-to-have, but mobile screen size is not a big priority at the moment.
If we get to it for the release, great!

**Comment by jarekmorawski** [comment]
Hi @frosso! I think we can rearrange the elements a little bit to make the design more responsive. If we removed the icons and split checkbox items in two lines, we'd get the space we need to make the screen more legible.

For example, on mobile it could look like this.

![image](https://user-images.githubusercontent.com/79307566/127535400-38ea81a3-6f6e-4856-9cc3-69bafcc08113.png)


Let me know if you have any questions!
