### ISSUE TITLE
Sofort and Giropay orders completing when payment fails

### ISSUE THREAD

**Issue by FangedParakeet** [Automattic/woocommerce-payments#2469]
For some reason, if I decide to cause a test payment for either Giropay or Sofort (I believe there is a way to do this with cards as well, but I haven't tried yet) to fail at checkout, for some reason the checkout flow still continues as per usual and completes the order. The order is instead updated with a status of `Pending payment`. I believe we should be redirecting users back to the checkout page instead, which is how our previous test gateways operated.

*Steps to reproduce*

1. Pull latest version of develop branch for this plugin, enable UPE and additional UPE payment methods through WCPay Dev Tools or by adding `_wcpay_feature_upe` to your `wp_options` table, and run the latest version of the Payment Server.
2. Add an item from your store to cart and proceed to checkout.
3. Complete the checkout details and from the UPE select either Giropay or Sofort.
4. Once you are redirected to Stripe's transaction page, select `Fail test transaction`.
5. Notice with bemusement and mild horror that you have now found yourself on the Order Complete page instead of back on the checkout page looking at an error.

Here is a little GIF I made running through the above scenario using Giropay.

![Giropay not failing](https://cdn-std.droplr.net/files/acc_1104206/Ki4tTI)
_Giropay cannot fail_

Note that the completed order gets set to a status of `Pending payment` and there are no notes on the order. This suggests to me that we are returning too early in one of our redirection handlers inside the UPE gateway, when we should be throwing an error and redirecting the user back to the checkout page instead.

![Order pending payment](https://cdn-std.droplr.net/files/acc_1104206/1f7p9n)
_Order pending payment_

**Comment by bborman22** [comment]
Good catch! It seems that some of the logic from the Giropay and Sofort gateways didn't make the jump to UPE. One thing we should do is pull in the status checks from [Giropay gateway](https://github.com/Automattic/woocommerce-payments/blob/e6dcd9b507bb6a02c0d484726db824a15f4b8079/includes/payment-methods/class-giropay-payment-gateway.php#L95-L120) and [Sofort gateway](https://github.com/Automattic/woocommerce-payments/blob/e6dcd9b507bb6a02c0d484726db824a15f4b8079/includes/payment-methods/class-sofort-payment-gateway.php#L87-L111).

I also found that if we replace this line:
https://github.com/Automattic/woocommerce-payments/blob/e6dcd9b507bb6a02c0d484726db824a15f4b8079/includes/payment-methods/class-upe-payment-gateway.php#L431
With:
```javascript
wp_safe_redirect( wc_get_checkout_url() );
exit;
```

That also addresses this flow.
