### ISSUE TITLE
Authorizations not listed in transactions

### ISSUE THREAD

**Issue by WillBrubaker** [Automattic/woocommerce-payments#2475]
The documentation on [Transactions](https://docs.woocommerce.com/document/payments/?_ga=2.196817892.91730033.1626549312-436098468.1616966789&_gac=1.219536875.1625520991.Cj0KCQjw24qHBhCnARIsAPbdtlLowUbzPHk3Ikbm7uHvorrSu2xdLIUiARqe2anP7HCa_SuJ5ru5NK4aAqL_EALw_wcB#section-6) mentiions:

>Many different types of transactions can occur with your site, including the **authorization** or capture of a charge

emphasis mine...but the visual feedback I get on the transactions screen does not match what the words there lead me to believe, i.e. authorizations do not show up in the transactions list as reported in 4154252-zen. 

As soon as the charge is captured, it does show up in the list.

What is "correct"?

**Comment by dechov** [comment]
Thanks for calling that out – it's a mistake in the docs. We should adjust our documented definition of a transaction to reflect that it doesn't include uncaptured payments. There was some related discussion in https://github.com/Automattic/woocommerce-payments/issues/1063

**Comment by htdat** [comment]
https://woocommerce.com/document/payments/#h-transactions is showing this text: 

> This page includes transactions including the capture of a charge, payment, payment failure refund, refund, refund failure, dispute, and dispute reversal.

It no longer mentions "authorizations" so I am closing this as it can be considered "fixed".
