### ISSUE TITLE
Currency switcher shouldn't affect Order confirmation screen prices

### ISSUE THREAD

**Issue by LevinMedia** [Automattic/woocommerce-payments#2486]
After completing a purchase, changing the currency in the currency switcher widget changes the format of the prices on the order confirmation screen. 

To recreate - activate Yen, Euro, and USD currencies. I made the purchase in Yen, since it's easier to see the format switching because of the large numbers it generates. 

after completing the purchase, on the order confirmation screen, switch from Yen, to Euro, to Dollar. Note the currency symbol remains correct, however currency formatting changes. 

![confirmationswitch](https://user-images.githubusercontent.com/4500952/126255044-19b74fb4-e345-4a1b-875a-d61783c11620.gif)

**Comment by ismaeldcom** [comment]
@LevinMedia 🤔  Should this also apply to **My account > Orders**?

![Screen Recording 2021-09-02 at 10 14 06](https://user-images.githubusercontent.com/7670276/131808099-090a3b19-aab8-4a9b-9e71-632cb0c5deaa.gif)

**Comment by LevinMedia** [comment]
@ismaeldcom good catch! you're right, it should apply there too!
