### ISSUE TITLE
Update public-facing Woo docs

### ISSUE THREAD

**Issue by frosso** [Automattic/woocommerce-payments#2491]
## Description

The designs need some updated documentation.
The bullet points in the design outline what the takeaways should be: Li3cAa1Y2uSklkek0axmyu-fi-3773%3A3298

Please update the documentation page that has already been created: pbDlC7-ki-p2
If new pages are needed, please also update the plugin's code/links.

**Comment by frosso** [comment]
Published a first draft

**Comment by htdat** [comment]
@frosso - I am doing triage for WCPay repos. Can you have a quick look at this issue and see if it has been resolved or not?

**Comment by frosso** [comment]
@htdat thanks for the ping, I thought we closed this - it's done :)
