### ISSUE TITLE
Newly onboarded account connection occasionally not being finalized

### ISSUE THREAD

**Issue by dechov** [Automattic/woocommerce-payments#2513]
While testing a different PR, @ricardo and I noticed an issue where it sometimes takes you **back to the "Finish setup"** screen (instead of "Overview") immediately **after fully completing the onboarding** flow.

It appears that the hook [here](https://github.com/Automattic/woocommerce-payments/blob/aabf276642607ea26491dac05babadf29927b63a/includes/admin/class-wc-payments-admin.php#L68) is triggered prior to the hook [here](https://github.com/Automattic/woocommerce-payments/blob/aabf276642607ea26491dac05babadf29927b63a/includes/class-wc-payments-account.php#L43), causing the plugin to not recognize the onboarded account. It seems to happen _intermittently_, perhaps due to a race condition with the webhook handled [here](https://github.com/Automattic/woocommerce-payments/blob/aabf276642607ea26491dac05babadf29927b63a/includes/admin/class-wc-rest-payments-webhook-controller.php#L123-L125).

**Comment by ricardo** [comment]
Not sure if I tested this correctly, but handling webhooks didn't seem to help. I stopped seeing the issue when I changed the hook and its priority in #2514.
