### ISSUE TITLE
Display fee breakdown in order notes.

### ISSUE THREAD

**Issue by naman03malhotra** [Automattic/woocommerce-payments#2522]
Splitted from: https://github.com/Automattic/woocommerce-payments/issues/2233
All transactions are subject to a base fee (determined by the merchant's country) plus a number of additional fees (like international card processing, FX fees etc).

We currently only show the total fee. We want to break this number down to make it clearer how the final rate was calculated.

**Order Notes**
![image](https://user-images.githubusercontent.com/686419/122224470-0c3db700-ceac-11eb-8b4b-eedaf607a406.png)

**Comment by kalessil** [comment]
Cross-referencing: https://github.com/Automattic/woocommerce-payments/issues/1054

**Comment by RadoslavGeorgiev** [comment]
Asked David if this is a necessary feature here: p1649756442805279-slack-C02L752DS0G

**Comment by naman03malhotra** [comment]
@LevinMedia we have taken this issue on priority, we'll be working on this issue this sprint.

**Comment by naman03malhotra** [comment]
cc @htdat

**Comment by htdat** [comment]
For your awareness @deepakpathania as you're the current sprint lead.
