### ISSUE TITLE
Multi-Currency Analytics: Add support for filtering the currency

### ISSUE THREAD

**Issue by dmallory42** [Automattic/woocommerce-payments#2535]
For phase 2 of Multi-Currency, we'll need to add support for filtering options for currency in analytics as described here: https://wcpay.wordpress.com/2021/04/16/multi-currency-analytics/

Based on the work in #2457, I think this will hopefully be quite straightforward. We will need to add a filter to the front-end as described here: https://developer.woocommerce.com/2020/02/20/extending-wc-admin-reports/, and then in the backend pick up the `?GET` parameters and apply a `WHERE` clause to the query using the available filters.

The other thing we'll need to do is adjust the existing logic which converts the order amounts in place as part of the SQL query. If we only want orders matching a certain currency, then we don't need to do these conversions because we can just use the WHERE clause to filter out orders which do not match the selected currency. 

The only case where we would still want to do the conversions is if the user wants to filter by multiple currencies and display it in their store currency.

**Comment by dwainm** [comment]
Needs to be broken up further.

**Comment by dmallory42** [comment]
Created two follow on issues: 

#4446 
#4447
