### ISSUE TITLE
Consider adding basic E2E tests for the multi-currency analytics

### ISSUE THREAD

**Issue by dmallory42** [Automattic/woocommerce-payments#2536]
It would be great to have an E2E test which validates the multi-currency analytics work done in #2457, as this will ensure we stay compatible with any changes that may get made to the WC Admin side of things.

**Comment by jessepearson** [comment]
Tests should cover transactions and refunds.

**Comment by oaratovskyi** [comment]
@dmallory42 🤔 I wonder if it's a good time to pick the issue now? What I can see E2E situation is better now. What do you think? 🙂

**Comment by dmallory42** [comment]
Yep, I think that we're in a much better state with the E2E tests now, and they're a lot more stable - so now could be a good time to pick this up!

**Comment by dmallory42** [comment]
Just noting here that I created  #4770 which is to expand on the E2E tests developed in #4717.
