### ISSUE TITLE
Update opt-out survey notices

### ISSUE THREAD

**Issue by frosso** [Automattic/woocommerce-payments#2545]
## Description

From p1627051639006200-slack-C01RTUVR81K

![Screen Shot 2021-07-23 at 12 07 24 PM](https://user-images.githubusercontent.com/273592/126817167-44fe5312-7cc3-4797-9bc6-7480f6c4143f.png)

![Screen Shot 2021-07-23 at 12 07 10 PM](https://user-images.githubusercontent.com/273592/126817142-79674b79-8b44-43d9-aac5-1cb23262b228.png)

![Screen Shot 2021-07-23 at 12 06 13 PM](https://user-images.githubusercontent.com/273592/126817050-5c35c4fd-b431-4f85-882f-533971bfe2a4.png)

> This notice doesn't have the background in my setup. 🤔

> Can we adjust the paddings on the blue notice? Optically it looks a little on the big side so maybe we could tweak it to 8px 16px 8px 16px?

> I also noticed a small shift in size when going from one modal to the other. Is there an easy and responsive way to make them the same size? I'd also consider adding min-height to the modal so the blue part sits and the bottom and there's a little bit of breathing room above it.

> Bonus question: can we remove the 2em padding around the body text? 🤔

> Can we make the icon smaller (24px) and remove the paddings? We also don't really need the line separators (below) unless you checked and it looks baaad.

> Please align the icon and text vertically and adjust paddings like in the blue notice.

### Acceptance criteria
- New Notice component has been created
- Component has 3 variations: info (blue), success (green), error (red)
- Icon is displayed for each variation
- Component is reused in the settings pages (opt-out survey modals, multi-currency info notice, error notice on account statement descriptor submission)

**Comment by frosso** [comment]
See p1627070641015800/1627051639.006200-slack-C01RTUVR81K and p1627070913016900/1627051639.006200-slack-C01RTUVR81K for the latest updates

**Comment by LevinMedia** [comment]
@frosso - @jarekmorawski and I had a follow up chat on this one - for now could we use an alternate state of the gutenberg component, so that we don't have to create a new one from scratch? 

We could use the "warning" prop from Gutenberg to get the yellow color for the disabled notice, and the "we added a currency notice" and the "success" prop for the green, you've disabled notice.

**Comment by LevinMedia** [comment]
If we want to add icons to these notices, we should investigate contributing it as a prop to the core component as a follow up issue.

**Comment by frosso** [comment]
All right, so to recap:
- Use `Notice` from Gutenberg
- Ensure that `info` notice has blue background
- No icons
