### ISSUE TITLE
Add empty state when user removes all payment methods from checkout

### ISSUE THREAD

**Issue by jarekmorawski** [Automattic/woocommerce-payments#2560]
Hi folks!

In UPE, when merchant removes all payment methods from checkout (which could be the case if they want to use a different payment method alongside WCP), we could display an empty state picture below ([view in Figma](https://www.figma.com/file/Li3cAa1Y2uSklkek0axmyu/Local-payment-methods?node-id=4575%3A202591)).

Clicking the "Add payment method" would launch the modal.

![image](https://user-images.githubusercontent.com/79307566/126980937-20cda840-cc1d-412c-aa78-717eac70577d.png)

**Comment by jarekmorawski** [comment]
For context, we've received feedback from merchants who only wanted to use Apple/Google Pay and disable all other payment methods.

![image](https://user-images.githubusercontent.com/79307566/128915825-f3035365-7fac-4996-810d-3e52bce470ec.png)

**Comment by mdmoore** [comment]
It looks like #3300 nullifies this issue as all payment methods are always displayed now.
