### ISSUE TITLE
Display icons of added payment methods at the end of onboarding step

### ISSUE THREAD

**Issue by frosso** [Automattic/woocommerce-payments#2562]
## Description

From UX:
> Can we show here icons of payment methods added to checkout?

**Comment by jarekmorawski** [comment]
If possible, please also update the copy like in the design below.

![image](https://user-images.githubusercontent.com/79307566/127123686-6f9813ba-a79a-4ff1-9629-7d1892eb6aad.png)

> Setup complete! X new payment methods and Y currency are now live in your store.

The idea is to have the copy update dynamically. So, if we enabled 2 payment methods and 2 currencies, it'd look like this.

> Setup complete! 2 new payment methods and 2 currencies are now live in your store.

Please let me know if making the words "payment method/payment methods" and "currency/currencies" adjust automatically is too much effort. As an alternative, we could try:

> Setup complete! New payments methods are now live in your store.

**Comment by frosso** [comment]
@jarekmorawski the messaging is indeed dynamic, indicating the number of payment methods being added in both singular/plural form.
The messaging doesn't include the currencies being added, since the logic for the currency is very isolated at the moment.
We _could_ try and do it, but I think it would be pretty challenging for translations, at that point 😬

**Comment by jarekmorawski** [comment]
> The messaging doesn't include the currencies being added, since the logic for the currency is very isolated at the moment.
We could try and do it, but I think it would be pretty challenging for translations, at that point 😬

Good point! Let's leave it out for now. 👍
