### ISSUE TITLE
Store the Exchange Rate Stripe used in the transaction in the order to use for the analytics conversions

### ISSUE THREAD

**Issue by dmallory42** [Automattic/woocommerce-payments#2567]
Currently, we use the exchange rate that was used to calculate the amount to show on the frontend to make our analytics calculations for multi currency.

I spoke to @LevinMedia about this and he would prefer it if we used the exchange rate that Stripe actually used in the transaction to calculate the figures we display in analytics. I think we can do this by hooking into the transaction we make with Stripe and attaching the rate to the order as meta data, and then using it in the same way we use the conversion rate currently.

**Comment by daquinons** [comment]
As we spoked on Slack, this issue is going to take care of storing the exchange rate into a new key called `_wcpay_multi_currency_stripe_exchange_rate`.
