### ISSUE TITLE
Currency switcher widget's settings do not work everywhere

### ISSUE THREAD

**Issue by RadoslavGeorgiev** [Automattic/woocommerce-payments#2575]
The currency switcher widget's settings do work in the customizer:

![customizer-widget](https://user-images.githubusercontent.com/5311119/127136213-f5fd7a45-bc48-4121-88c9-45cfcdfe4790.gif)

However they don't get applied through WP Admin > Widgets:

![admin-widget](https://user-images.githubusercontent.com/5311119/127136319-8c9e37e7-d80d-4716-9e9c-afeb50273729.gif)

cc @ismaeldcom @dmallory42

**Comment by ismaeldcom** [comment]
Thanks for catch this @RadoslavGeorgiev! Had not tried v5.8 version yet, I'll take care of this.
