### ISSUE TITLE
Multi Currency Analytics: Consider whether to add filters for extensibility

### ISSUE THREAD

**Issue by dmallory42** [Automattic/woocommerce-payments#2576]
We should consider whether we want to add filters to the functions in Multi-Currency analytics which modify the select/join clauses to allow these to be extensible/overridden by any other plugins which may want to modify the analytics display.

As mentioned here: https://github.com/Automattic/woocommerce-payments/pull/2457#discussion_r675530997

**Comment by jessepearson** [comment]
@dmallory42 I think I know what you were referring to here. Can you take a look at https://github.com/Automattic/woocommerce-payments/pull/3286 and see if that covers what you were thinking? Seems like it's something simple like this. Allow disabling completely, or filtering of the new clauses.

**Comment by dmallory42** [comment]
Yep, I looked at the PR and that's exactly what I was thinking here. I can give the PR a proper review when it's ready, thanks for picking this up!
