### ISSUE TITLE
Unexpected Developer Error when using branded Google Pay button

### ISSUE THREAD

**Issue by billrobbins** [Automattic/woocommerce-payments#2596]
In Chrome, two different payment request buttons are displayed depending on if the user is logged into Google Pay or not.  The basic payment request button works fine for me.  I can test that in an incognito window.

Using the branded "G Pay" button results in this error:

```
Uh oh, something went wrong.  
Unexpected developer error, please try again later.
```

To reproduce:
1. Make sure you are logged into https://pay.google.com/
2. Attempt to purchase a product via the branded "G Pay" button.
3. Notice the error message.

The console in the Google Pay modal shows this error *prior* to trying to pay:

```
224.32.32.131/38296:1 Failed to load resource: net::ERR_ADDRESS_UNREACHABLE
224.32.32.131/38297:1 Failed to load resource: net::ERR_ADDRESS_UNREACHABLE
```

**Screenshots**
![branded-button](https://user-images.githubusercontent.com/1138631/127496071-aa5f0b44-9cd8-4ce5-a9c2-d8bf73dd45df.png)

![payment-window](https://user-images.githubusercontent.com/1138631/127496099-c3c9a946-d8fc-43e8-bf5e-e52c7389d0a8.png)

![error](https://user-images.githubusercontent.com/1138631/127496111-0676bd38-c0e7-44d8-a389-c804d31cbe1b.png)

![console](https://user-images.githubusercontent.com/1138631/127496125-5bbab292-3170-4f37-916d-461444eed583.png)

**Tickets**
4135275-zen

**Comment by pdfrequest3** [comment]
Any Update on this?

**Comment by pdfrequest3** [comment]
@billrobbins billrobbins, Just want to ask if the issue still persists? Perhaps you can try to reproduce whether the error still exists.

**Comment by billrobbins** [comment]
@pdfrequest3, I am still able to reproduce this.  The developers have been looking at it and trying to pin down why it happens to some users and not to others.  When we know more, they'll update this issue.  Thanks for bringing this issue up!

**Comment by billrobbins** [comment]
One more example of this in 4439526-zen

This is a live account running in test mode.
