### ISSUE TITLE
Run WC Core tests with our code periodically

### ISSUE THREAD

**Issue by v18** [Automattic/woocommerce-payments#26]
It would be nice to run WC core test suite on a daily basis to make sure our code doesn't break core features.

**Comment by vbelolapotkov** [comment]
Renamed issue to make it more relevant to the current context.

**Comment by RadoslavGeorgiev** [comment]
In order not to slow down CI/CD for every PR, it would be a good idea to run those tests on release/testing tags or branches.

**Comment by RadoslavGeorgiev** [comment]
We're not sure about the required mechanics, and how this would be executed. It's likely that because of actions or filters, we're _intentionally_ breaking some tests. We need some practical research before we decide how to proceed.

**Comment by vbelolapotkov** [comment]
Closing in favor of integration with compatibility dashboard. https://github.com/Automattic/woocommerce-payments-meta/issues/334
