### ISSUE TITLE
Change log is not updated on WooCommerce.com

### ISSUE THREAD

**Issue by stephhjacq** [Automattic/woocommerce-payments#2600]
Issue: The change log on the product page has not been updated since version 2.5.

Links:
https://woocommerce.com/products/woocommerce-payments/
https://dzv365zjfbd8v.cloudfront.net/changelogs/woocommerce-payments/changelog.txt

Expected outcome: the change log reflects the current version.

**Comment by naman03malhotra** [comment]
Update:
Slack thread discussion: p1627556628181000-slack-CGGCLBN58

**Comment by naman03malhotra** [comment]
We've updated the changelog and I shall be updated with every release. Thanks again, for bring this up.
