### ISSUE TITLE
Blocks Checkout should pass dynamic styling to UPE

### ISSUE THREAD

**Issue by FangedParakeet** [Automattic/woocommerce-payments#2603]
To ensure that the styling of the UPE is passed onto the Stripe UPE, on the regular checkout page we create a fake hidden element on the page, read computed styles from this element, pass these styles into the UPE in an `appearance` parameter when the UPE is created, and then remove this temporary element. These parameters are also stored in a transient, which the Blocks checkout is currently able to parse (with #2530 ). 

However, we have not added this dynamic hidden element into the Blocks checkout, so the UPE is unable to read any new computed styles or Dark Mode styles during the Blocks checkout. This issue is to make sure that the Blocks checkout is able to compute styles from the theme within which it lives, just like the regular checkout.

**Comment by pierorocca** [comment]
@FangedParakeet still relevant based on some of your recent enhancement to styling?

**Comment by FangedParakeet** [comment]
I believe this functionality was actually added long ago in #4211 (I apparently even reviewed this myself lol), but has since been enhanced by #8230. Cheers for reminding me of this, @pierorocca, but closing since it has now been quite thoroughly resolved. 🚀
