### ISSUE TITLE
Prices on order notes not displayed in explicit format

### ISSUE THREAD

**Issue by tpaksu** [Automattic/woocommerce-payments#2607]
Follow-up work of https://github.com/Automattic/woocommerce-payments/pull/2395

Stated in the price formatting guideline paJDYF-20W-p2, prices in sentences should be displayed in explicit formats. Prices in order notes are displayed in their short formats and it should be converted before the text gets into the database. 

![image](https://user-images.githubusercontent.com/3295/127566783-baa34305-8cb0-4b5b-b980-1588ebfb059f.png)

The places I've found that creates a note with a price are:

https://github.com/Automattic/woocommerce-payments/blob/339108fcf2b33416accee14df5bf67dc84baebef/includes/class-wc-payment-gateway-wcpay.php#L860
https://github.com/Automattic/woocommerce-payments/blob/339108fcf2b33416accee14df5bf67dc84baebef/includes/class-wc-payment-gateway-wcpay.php#L1155
https://github.com/Automattic/woocommerce-payments/blob/339108fcf2b33416accee14df5bf67dc84baebef/includes/class-wc-payment-gateway-wcpay.php#L1193
https://github.com/Automattic/woocommerce-payments/blob/339108fcf2b33416accee14df5bf67dc84baebef/includes/class-wc-payment-gateway-wcpay.php#L1308
https://github.com/Automattic/woocommerce-payments/blob/339108fcf2b33416accee14df5bf67dc84baebef/includes/class-wc-payment-gateway-wcpay.php#L1331
https://github.com/Automattic/woocommerce-payments/blob/339108fcf2b33416accee14df5bf67dc84baebef/includes/class-wc-payment-gateway-wcpay.php#L1625
https://github.com/Automattic/woocommerce-payments/blob/339108fcf2b33416accee14df5bf67dc84baebef/includes/class-wc-payment-gateway-wcpay.php#L1643
https://github.com/Automattic/woocommerce-payments/blob/339108fcf2b33416accee14df5bf67dc84baebef/includes/class-wc-payment-gateway-wcpay.php#L1653
https://github.com/Automattic/woocommerce-payments/blob/339108fcf2b33416accee14df5bf67dc84baebef/includes/class-wc-payment-gateway-wcpay.php#L1881
https://github.com/Automattic/woocommerce-payments/blob/339108fcf2b33416accee14df5bf67dc84baebef/includes/class-wc-payment-gateway-wcpay.php#L1905
https://github.com/Automattic/woocommerce-payments/blob/339108fcf2b33416accee14df5bf67dc84baebef/includes/class-wc-payment-gateway-wcpay.php#L1929
https://github.com/Automattic/woocommerce-payments/blob/339108fcf2b33416accee14df5bf67dc84baebef/includes/class-wc-payment-gateway-wcpay.php#L1957
https://github.com/Automattic/woocommerce-payments/blob/339108fcf2b33416accee14df5bf67dc84baebef/includes/admin/class-wc-rest-payments-webhook-controller.php#L200
https://github.com/Automattic/woocommerce-payments/blob/339108fcf2b33416accee14df5bf67dc84baebef/includes/compat/subscriptions/trait-wc-payment-gateway-wcpay-subscriptions.php#L272
https://github.com/Automattic/woocommerce-payments/blob/339108fcf2b33416accee14df5bf67dc84baebef/includes/payment-methods/class-giropay-payment-gateway.php#L260
https://github.com/Automattic/woocommerce-payments/blob/339108fcf2b33416accee14df5bf67dc84baebef/includes/payment-methods/class-sofort-payment-gateway.php#L251

**Comment by jessepearson** [comment]
Just want to note here that even thought MC is providing the exchange, other gateways are going to add notes, so we should probably just filter during note creation.
