### ISSUE TITLE
UPE alignment accidents

### ISSUE THREAD

**Issue by FangedParakeet** [Automattic/woocommerce-payments#2609]
This is a bit of a general issue to sort out general alignment issues surrounding the UPE. A few of these are to do with dynamic styling from themes parsed into the UPE clashing with static CSS outside the element and the rest are just weird looking things that can look a bit cleaner. I think individually these will be pretty small fixes, so hopefully we can track them all in this one issue and eventually sort them out in one shot. Perhaps this issue will veer wildly out of control and will need to be split into a few smaller issues, but we can cross that bridge when we and if we come to it.

Here are the issues I am aware of, but this issue is a safe space where all are welcome to gather and discuss things in and around the UPE that look a bit wonky.

 - In the classic checkout, static padding on the save payment checkbox and label does not match dynamic padding on the UPE, leading to some misalignment.
 ![Mismatched padding](https://cdn-std.droplr.net/files/acc_1104206/hcA6Cb)
 _Mismatched padding_
 
  - In the blocks checkout, the save payment method checkbox doesn't seem to fit into the container properly. It looks its own label element is too short for it and, whether as a result of that or not, it's also being pushed out of its UPE container.
  ![Checkbox out of container](https://cdn-std.droplr.net/files/acc_1104206/ZX4dQk)
  _Save payment information section does not fit in container_
  ![Checkbox shunted](https://cdn-std.droplr.net/files/acc_1104206/1uMQc5)
  _UPE container jostling with the save payment information section_
  ![Checkbox outside label](https://cdn-std.droplr.net/files/acc_1104206/UpvCMt)
  _Save payment information too big for label_

**Comment by achyuthajoy** [comment]
Blocks checkout alignment issues seems to be solved. Only classic checkout issues are present.

<img width="501" alt="Screenshot 2022-04-13 at 9 53 16 AM" src="https://user-images.githubusercontent.com/1161872/163100099-e62d685a-1fe7-4159-907a-af66dcf78c7b.png">

<img width="495" alt="Screenshot 2022-04-13 at 9 53 40 AM" src="https://user-images.githubusercontent.com/1161872/163100106-35c6c728-a763-4e16-9005-b51ace4bb0ab.png">

<img width="703" alt="Screenshot 2022-04-13 at 9 54 14 AM" src="https://user-images.githubusercontent.com/1161872/163100112-eda6df27-295f-4b8e-ac56-71e9ad0f3cfe.png">
