### ISSUE TITLE
Enqueue admin JS and CSS for Multi-Currency only when needed

### ISSUE THREAD

**Issue by jessepearson** [Automattic/woocommerce-payments#2621]
Need to fix it so that Multi-Currency JS and CSS is only enqueued in the admin when needed.

**Comment by jessepearson** [comment]
@RadoslavGeorgiev Can you add a reason why this was reopened? Are the assets being enqueued in places/times they should not be?

**Comment by RadoslavGeorgiev** [comment]
I was triaging issues in the WCPay backlog, and I have no idea how I reopened this one. Hopefully it's an isolated mistake. Closing again...
