### ISSUE TITLE
Store settings don't appear after adding currencies for the first time. 

### ISSUE THREAD

**Issue by LevinMedia** [Automattic/woocommerce-payments#2627]
Today while testing on develop, I noticed that the store settings on the multi-currency settings page didn't appear after I added my first currencies to the store. It was only after I hard refreshed the page that the settings appeared. 

<img width="1582" alt="Screen Shot 2021-07-30 at 3 46 44 PM" src="https://user-images.githubusercontent.com/4500952/127718780-223f2b8a-adfb-4348-976c-669fc474e1e4.png">

You can see the bug in action in the video walk through from @dmallory42 posted here paJDYF-1C7-p2#comment-7375

After adding the currencies, the auto currency switching feature, and auto widget placement (if using storefront) should appear below the currencies list:

<img width="1627" alt="Screen Shot 2021-07-30 at 3 50 45 PM" src="https://user-images.githubusercontent.com/4500952/127718883-2b93e623-8517-44a9-9955-6ae5a59253b6.png">

**Comment by dmallory42** [comment]
Hi @LevinMedia, myself and @ismaeldcom both tried to reproduce the issue this morning using the latest `develop` and were not able to. I've shared a video Ismael created showing the behaviour for him, and I also get the same behaviour (however, I'm not sure what happened on Friday when I recorded the demo). 

https://user-images.githubusercontent.com/11770181/127826195-ef2f8054-6f9a-4656-b01f-77a614fd68b7.mov

Could you check again to see if you can reproduce this, please?

**Comment by LevinMedia** [comment]
I think potentially the issue was, I had added a bunch of currencies, then removed them to start over, and when I re-added them, the settings didn't appear. I'll give that scenario a test again.

**Comment by LevinMedia** [comment]
@dmallory42  it looks like @ismaeldcom is on a different branch, because the second setting says "add a currency switcher to the cart widget." which is incorrect.  

I just tested it again on a fresh JN site. the first setting appeared after I added the currencies, but the second setting didn't appear on the initial load. I had to refresh the page, then it appeared. 

Video at paJDYF-1C7-p2#comment-7387

**Comment by ismaeldcom** [comment]
Thanks @LevinMedia! Checked again, refreshing after removing all currencies and before adding new ones. The switcher settings don't appear until you refresh. I think this comes from the last PR where we moved this option into another class. Probably this ended creating it out of the wrapper.

Pretty sure, we just need to update the JS code or modify the PHP to keep it compatible.
