### ISSUE TITLE
Limitation to fetch bulk transaction records

### ISSUE THREAD

**Issue by battouly** [Automattic/woocommerce-payments#2629]
Currently, the maximum number of transactions users can fetch in a single request is **100**, for that they can change the query param value `pagesize` to 100.

In our pre-sales documentation, or any documentation, it  does not say that the maximum number of transactions that users can fetch in a single query is 100.

This was reported in 4169253-zen and the user's comment include:

> This whole thing indicates that this gateway is intended to support only small users with simple back end accounting. If this is an explicit decision, why don't you make that clear? If it isn't, why don't you want to understand what I'm saying? Who there is able to understand and weigh requirements at a business function level?
>
>Please check with the product manager and tell them that I would like to explain all the implications of not having at least one of:
>- the gross sales and the fees column on the deposit list
>OR
>- a download of all transactions for a month (not 100 at a time where duplications can occur among downloads)
>OR
>- a monthly report of deposits to reconcile the bank
>OR
>- provide credentials to the Stripe dashboard where all three are available.

**Comment by jobthomas** [comment]
Closing in favour of #1484. This is a question about architecture and scale and that previously recorded issue would address this one as well.
