### ISSUE TITLE
"Subscriptions" column missing in Transactions table

### ISSUE THREAD

**Issue by senff** [Automattic/woocommerce-payments#2630]
Although the documentation states that in the site's list of transactions, there should be a [Subscriptions column]( https://docs.woocommerce.com/document/payments/#prettyPhoto/13/), it does not actually appear (anymore).  Example on my test site (the top transaction should be showing that it's related to a subscription):

![subscriptions](https://user-images.githubusercontent.com/1710669/127770347-32f29eec-eb36-49e9-a5ff-ed979f9a984c.png)

Originally reported in #30885950-HC.

Note: when addressed in Slack, @naman03malhotra requested I create this issue and also mentioned:

> 'isSubscriptionsActive'  => class_exists( 'WC_Payment_Gateway_WCPay_Subscriptions_Compat' ) is returning false when the plugin is installed. Needs to be further investigated.

**Comment by tpaksu** [comment]
This commit removed the only reference to `WC_Payment_Gateway_WCPay_Subscriptions_Compat` class, and thus that `isSubscriptionsActive` flag never gets to true. 

One possible solution might be moving away from `WC_Payment_Gateway_WCPay_Subscriptions_Compat` check and use: 

```php
class_exists( 'WC_Subscriptions' ) && version_compare( WC_Subscriptions::$version, '2.2.0', '>=' )
```

instead (like the previous version of the code loaded that compat file).

```php
// TODO: Remove admin payment method JS hack for Subscriptions <= 3.0.7 when we drop support for those versions.
if ( class_exists( 'WC_Subscriptions' ) && version_compare( WC_Subscriptions::$version, '2.2.0', '>=' ) ) {
    include_once __DIR__ . '/compat/subscriptions/class-wc-payment-gateway-wcpay-subscriptions-compat.php';
    $gateway_class = 'WC_Payment_Gateway_WCPay_Subscriptions_Compat';
} elseif ( WC_Payments_Features::is_upe_enabled() ) {
    $gateway_class = UPE_Payment_Gateway::class;
}
```
