### ISSUE TITLE
[In-person payments] Improve declarations for endpoints used by mobile apps.

### ISSUE THREAD

**Issue by kalessil** [Automattic/woocommerce-payments#2638]
Goals:
- proper response specification
- observability for endpoints used by mobile apps

Examples of documenting endpoints and arguments and further reading can be [found here](https://developer.wordpress.org/rest-api/extending-the-rest-api/adding-custom-endpoints/#examples).

**Comment by htdat** [comment]
@kalessil and @dmvrtx - does this issue belong to any project or are you working on it soon? 
Based on the answer, I will put it to the proper triage queue.

**Comment by kalessil** [comment]
@htdat, yes, it belongs to In-Person Payments (note component label) project.

**Comment by dmvrtx** [comment]
I was checking through documentation, but I can't find any guide related to documenting WordPress REST API extensions with Swagger. Do you have any link or example here, @kalessil?

**Comment by kalessil** [comment]
@dmvrtx, nope. I'd say go for an initial approach.

**Comment by dmvrtx** [comment]
Closed in favour of a separate documentation for In-Person Payments project.

**Comment by anu-rock** [comment]
Reopening in response to a renewed interest in documenting endpoints with the intention of auto-generating the docs (eg. in Swagger format).

**Comment by anu-rock** [comment]
This issue was closed by PR #3912.
