### ISSUE TITLE
Replace temporarily suspended deposits initially

### ISSUE THREAD

**Issue by ismaeldcom** [Automattic/woocommerce-payments#2642]
Fraud squad requested (p1627496060174900/1627469014.162100-slack-C016TMBQEV7) to replace the `Temporarily suspended` deposits message with `Pending` in green for the first 7 days. To avoid users confusion and Woo support requests during the waiting period.

<img width="660" alt="Screenshot 2021-08-03 at 10 33 08" src="https://user-images.githubusercontent.com/7670276/127984503-96b6737c-53f9-415b-a224-b7f7143c380a.png">

**Comment by aheckler** [comment]
This is basically a copy of #2383?

**Comment by ismaeldcom** [comment]
Thanks @aheckler! I missed that. I'll close this in favor of #2383
