### ISSUE TITLE
Add SEPA payment method to UPE

### ISSUE THREAD

**Issue by bborman22** [Automattic/woocommerce-payments#2645]
The goal of this issue is to allow checkouts and payments using SEPA within UPE. From a high level this will involve:
- Creating a new payment method class
- Handling any special cases with the checkout flow
- Able to save payment method
- Confirming transaction details are recorded and displayed properly

Details on the [features of SEPA](https://stripe.com/payments/payment-methods-guide#sepa-direct-debit) can be found here and special callouts relevant to us:
- Uses the Euro currency
- Accepts recurring payments, disputes, and refunds

**NOTE**: Keep in mind this discussion when working on the issue: paJDYF-2oJ-p2

**Comment by vbelolapotkov** [comment]
Marking as blocked due to discussion in this thread: paJDYF-2oJ-p2
