### ISSUE TITLE
attach_intent_info_to_order susceptible to errors saving orders

### ISSUE THREAD

**Issue by aheckler** [Automattic/woocommerce-payments#2656]
Sometimes WC Pay users contact support because orders are seemingly not refundable. When you try to refund it, there's no actual button:

![Screen Capture on 2021-08-04 at 08-12-52](https://user-images.githubusercontent.com/5512652/128178717-35ed9cfe-8936-4dcd-93c5-96c07fa22076.gif)

@luizreis and I ran into this in ticket 4091861-zen (which is now solved, only linking here for historical reasons/context). The telltale sign is that the charge is linked in the order notes, but not in the subtitle thing below the order ID:

![Markup on 2021-08-04 at 08:11:52](https://user-images.githubusercontent.com/5512652/128178548-f7c02d86-ccb2-4709-89e6-06d412ca40fb.png)

This happens because `attach_intent_info_to_order()` fails/errors during `$order->payment_complete( $intent_id );`, but crucially, it fails _after_ adding the order note. This results in the `_intent_id` meta missing from the postmeta for the order. Link to that line:

https://github.com/Automattic/woocommerce-payments/blob/2.8.0/includes/class-wc-payment-gateway-wcpay.php#L1151

In the case of 4091861-zen, the problem was that Xero and Google Listings & Ads were conflicting and throwing errors during the order save process, but in this current ticket (4184182-zen), there are no fatal error logs to find. However, the same problem exists for their order number 338318:

<img width="906" alt="Markup 2021-08-04 at 08 04 53" src="https://user-images.githubusercontent.com/5512652/128179920-74def50b-9914-46bd-a764-6b61a96a5ee4.png">

Is there any way to fix, detect, or work around this? We have creds for the staging site in 4184182-zen, and I installed a phpMyAdmin plugin so we can look at the db using that.

cc @tpaksu

**Comment by zhollenbeak** [comment]
Another report of this 4201476-zen

**Comment by aheckler** [comment]
4201476-zen is the same dude as 4184182-zen it looks like.

**Comment by nicholasjeberlin** [comment]
The user reporting above came back and said that they now see the refund buttons.

They noted they still didn't see a refund button on Thursday, August 5th. Appears we also released an unrelated update on the 5th and they are up to date. Not sure if that fixed it for them.

**Comment by nicholasjeberlin** [comment]
The user came back and let us know that the refund button appeared with two orders where it previously didn't. Still having trouble with one order, however.

**Comment by aheckler** [comment]
4244962-zen possibly.

**Comment by darcie** [comment]
Possibly in 4287589-zen also.

**Comment by oaratovskyi** [comment]
See p1627602573000100-slack-C7U3Y3VMY for initial details.

**Comment by oaratovskyi** [comment]
The ticket should be shipped with WCPay 3.1.0 release and the issue will be fixed for new orders. It will be hard to fix it for existing orders due to missing metadata.
