### ISSUE TITLE
Can't checkout

### ISSUE THREAD

**Issue by WillBrubaker** [Automattic/woocommerce-payments#2688]
Since 2.8.2 (maybe before) we're seeing some reports from folks who are having problems with checking out. The message displayed is "You specified "never" for fields.billing_details.address.line2 when creating the payment Element, but did not pass confirmParams.payment_method_data.billing_details.address.line2 when calling stripe.confirmPayment or stripe.confirmSetup. If you opt out of collecting data via the payment Element using the fields option, the data must be passed at confirm-time."

https://wordpress.org/support/topic/after-las-update-customers-unable-to-pay/
4207704-zen
4207559-zen

That forum one provided some helpful details. I am able to reproduce with the following:

1. Use the customizer to hide the billing address 2 field
2. Try to checkout with wcpay
3. Sadness :(

**Comment by melek** [comment]
Also present in https://wordpress.org/support/topic/error-fields-billing_details-address-line2/

**Comment by chrism245** [comment]
30712805-hc

**Comment by orhanfernandes** [comment]
Also seen in 4221356-zen

**Comment by gabrielbonifacio** [comment]
Seen on 58607903-zen

**Comment by gabrielbonifacio** [comment]
Seen on 4224273-zen

**Comment by WillBrubaker** [comment]
4241638-zen

**Comment by nicholasjeberlin** [comment]
31399449-hc

**Comment by jpstones** [comment]
Hi all, 

I have this issue as well. Opting out of the UPE fixes the problem. But it not ideal.

Displaying the address or phone fields has no effect. It still shows 'never' error.

Has anyone got an update to this?

**Comment by simplysaru** [comment]
Another report of this issue was reported in the forums thread [here](https://wordpress.org/support/topic/woocommerce-credit-debit-not-working-2/).

**Comment by vbelolapotkov** [comment]
Closed with #2853
