### ISSUE TITLE
Update grouped card icon

### ISSUE THREAD

**Issue by jarekmorawski** [Automattic/woocommerce-payments#2695]
Hi there!

Can we please update the grouped card icon that appears in WooCommerce Payments settings? The new version replaces CB with DC which is currently supported.

[cards_grouped.zip](https://github.com/Automattic/woocommerce-payments/files/6959776/cards_grouped.zip)

Bonus: wherever you can, please remove the CB icon for now. Thank you!

**Comment by htdat** [comment]
> The new version replaces CB with DC which is currently supported.

Would you mind clarifying `CB` and `DC`? Also, it would be great if you have internal links to refer this decision? 

I am doing triage for WCPay repos and would like this issue ready for priotisation.

**Comment by jarekmorawski** [comment]
> Would you mind clarifying CB and DC? Also, it would be great if you have internal links to refer this decision?

CB is `Groupement des cartes bancaires CB` (French card issuer) and DC is `Dinner Club` (US card issuer). [Here's the Slack discussion for context](https://a8c.slack.com/archives/C2CM2ELTG/p1628523873098800?thread_ts=1628519670.089900&cid=C2CM2ELTG).
