### ISSUE TITLE
UPE payment intent errors at checkout are not reflected on order status

### ISSUE THREAD

**Issue by FangedParakeet** [Automattic/woocommerce-payments#2702]
When completing a checkout using credit/debit cards with the UPE, if the payment information provided causes an error, we do not update the order with this event. The previous, parent payment gateway would update the order's status to `Failed` at this stage and a note would be left on the order explaining the specific error message. With the UPE, in this case, we simply display the error at checkout to the user, without sending any request to update the order. This could be confusing to a site owner, since the order's status remains as `Pending payment` and is not associated with other failed orders. 

The reason why this happens is because all of our error handling occurs for UPE transactions occurs after redirection. This works acceptably for giropay and Sofort, but it appears that credit/debit cards return errors immediately upon intent confirmation, stalling before the redirection process. We need to add some logic to our client side JS to update the order status if there is an error while attempting to confirm the intent, but not at any earlier stage, such as when validating payment fields during checkout. 

*Testing instructions*

1. Pulling the latest changes from `develop` branch of this repo, as well as the latest version of the Payments Server, enable UPE checkouts and additional payment methods on your test site.
2. Add an item to your cart and proceed to checkout and wait for the UPE to load.
3. Select credit/debit card within the UPE and use the details from one of [these test cards](https://stripe.com/docs/testing#cards-responses) to effect a failing response. Note that an error is displayed at checkout. 
4. From your site's admin section, view your latest orders and find the corresponding order for your checkout. Note that the status is still `Pending payment` with no notes added to the order.
5. You can repeat these steps with the UPE disabled to see how the order should be reflecting the error instead. The order should be updated to `Failed` and there should be notes on the order explaining the error.

**Comment by naman03malhotra** [comment]
P2 discussion: https://wcpay.wordpress.com/2021/09/03/upe-merchants-cant-see-error-notes-for-failed-transactions/
