### ISSUE TITLE
Add a "Deposit status" column to the transactions CSV export

### ISSUE THREAD

**Issue by aprea** [Automattic/woocommerce-payments#2715]
Related to #2705

The transactions CSV export contains a "Deposit date" column though it's not clear whether this date refers to the estimated deposit date or the actual deposit date.

We should add a "Deposit status" column to indicate the current status of the deposit for each transaction.

This column should contain the deposit status as per our existing options - https://github.com/Automattic/woocommerce-payments/blob/develop/client/deposits/strings.js#L13

At the time of writing these are:

- Paid
- Pending
- In transit
- Canceled
- Failed
- Estimated

**Comment by malithsen** [comment]
Hi @aprea 
It looks like deposit status is not being sent in the API response for transactions. Right now, frontend simply looks for the presence of `wcpay_estimated_` prefix in the `deposit_id` field. This approach does not extend to other statuses.

For exports, I am wondering whether the server change to extend the API response to include deposit status in transaction API is necessary here given that actual statuses are not shown on UI at the moment, what do you think?

Alternative approaches would be to have an Estimated Deposit Date column with yes/no values
