### ISSUE TITLE
Better notice when adding currencies automatically upon UPE method selection

### ISSUE THREAD

**Issue by jessepearson** [Automattic/woocommerce-payments#2720]
When selecting an UPE method that requires a currency that is not presently enabled, there is a notice that stated the currency is being added. Initially this notice was for multiple methods and a single currency, however, as of https://github.com/Automattic/woocommerce-payments/pull/2652 there are now four different states:

One method with one currency: 
> Sofort require additional currencies, so we’ll add Euro (€) to your store. You can view & manage currencies later in settings.

One method with two (or more) currencies:
> Przelewy24 (P24) require additional currencies, so we’ll add Euro (€) and Polish złoty (zł) to your store. You can view & manage currencies later in settings.

Two (or more) methods with one currency:
> Sofort and giropay require additional currencies, so we’ll add Euro (€) to your store. You can view & manage currencies later in settings.

Two (or more) methods with two (or more) currencies:
>  Sofort and Przelewy24 (P24) require additional currencies, so we’ll add Euro (€) and Polish złoty (zł) to your store. You can view & manage currencies later in settings.

The wording here should be updated to handle plurals better.

**Comment by jessepearson** [comment]
@jarekmorawski Would you be able to take a look at this and let us know if the copy phrasing should be any different than what it is other than the plurals?

**Comment by jarekmorawski** [comment]
Hi there! It looks great to me. The idea is to keep the wording the same no matter the situation and only adjust the plurals.

I know this is far fetched at the moment, but what would happen if I enabled more than 2 payment methods and currencies? Boiling the copy down to variables, I think the message could go like this:

> `[payment method name 1]`, `[payment method name 2]`, `[payment method name 3]`, and `[payment method name 4]` require additional currencies, so we’ll add `[currency name 1]`, `[currency name 2]`, and `[currency name 3]` to your store. You can view & manage currencies later in settings.

What do you think?

**Comment by tpaksu** [comment]
It's currently worded as you templated it @jarekmorawski (except the `,`'s before the `and` words), but I guess @jessepearson wants them to show it like:

> Sofort and giropay require an additional currency, so we’ll add Euro (€) to your store. You can view & manage currencies later in settings.

and

> Sofort requires an additional currency, so we’ll add Euro (€) to your store. You can view & manage currencies later in settings.

another 

> Przelewy24 (P24) requires additional currencies, so we’ll add Euro (€) and Polish złoty (zł) to your store. You can view & manage currencies later in settings.

The missing points there are: 

- `require` when talking about multiple providers / `requires` when talking about a single provider
- `an additional currency` when talking about a single currency, `additional currencies` when talking about multiple currencies
