### ISSUE TITLE
Currency format incorrect in refund button in admin

### ISSUE THREAD

**Issue by jessepearson** [Automattic/woocommerce-payments#2722]
When refunding an order, the currency listed in the button to perform the refund is not the proper format.

To replicate:
* Set the store currency to USD.
* Enable Euros under WooCommerce > Settings > Multi-Currency.
* Make a purchase on the front end of the store using EUR.
* Go to the order in the admin.
* Click the _Refund_ button.
* Add a line item to the refund.
* The format of the currency in the _Refund via WooCommerce Payments_ button will be incorrect.

![Markup 2021-08-12 at 10 28 31](https://user-images.githubusercontent.com/4634416/129205194-179fb59a-f052-4145-9323-d33bf5344852.png)

**Comment by ismaeldcom** [comment]
Already fixed? I tried to replicate it, but couldn't see the incorrect format.
<img width="363" alt="Screenshot 2021-08-30 at 09 18 04" src="https://user-images.githubusercontent.com/7670276/131300937-818ae85a-0f32-4292-a687-d6631494ef3d.png">

**Comment by jessepearson** [comment]
@ismaeldcom I just checked with the latest `develop`, and I am still seeing it. I read over my replication steps again and I noticed I didn't mention that the store currency should be USD with EUR as an additional currency, which I believe is the determining factor here.

**Comment by jessepearson** [comment]
@ismaeldcom I am not sure if there was something cached on my end that made it happen prior to adding the line item to the refund, but now it requires you to add the line item to the refund and then it shows.

![Screen Capture on 2021-09-02 at 08-20-32](https://user-images.githubusercontent.com/4634416/131835075-70c5c429-63f0-41ea-a7af-a253e637e740.gif)

**Comment by ismaeldcom** [comment]
Oh, I see it now! Haven't thought on changing QTY. Thanks for double checking it! 🙂

**Comment by jessepearson** [comment]
Ya, it's weird I was seeing it initially without adding the line item, but now I have to add the line item. ¯\_(ツ)_/¯
