### ISSUE TITLE
Communicate to the merchant when Stripe is holding/releasing funds

### ISSUE THREAD

**Issue by DanReyLop** [Automattic/woocommerce-payments#2730]
See this thread for more context: p1626404762393500-slack-woo-devs

Sometimes Stripe will hold some amount of money from a new merchant account, to better protect itself from fraud. That amount is released when it's clear the merchant is not fraudulent.

That means the total of a Deposit may not match the total of the transactions in said deposit. Internally, Stripe represents that "holding" and "releasing" of funds as transactions, but we aren't caching them in the server so we can't show them in the UI.

For example, if a merchant had $200 in transactions yesterday, but Stripe holds $50 in funds, today's deposit will be of just $150, even if all the transactions added together sum $200. If today there are no new transactions, and Stripe decides to release those funds, tomorrow's deposit will be of $50, even though there are no transactions in it. That makes a poor UX.

We can either:
- Start caching those "hold" and "release" transactions in the server, and surface them in the UI.
- Assume that any difference between the Deposit amount and the sum of the transactions in said deposit is due to Stripe holding or releasing funds, and surface that in the UI. Is that a fair assumption? Are there any other circumstances where a mismatch can happen?

**Comment by csmcneill** [comment]
4870609-zen

**Comment by htdat** [comment]
Another case: 4891922-zen 
Relevant convo: p1648277945018259-slack-CGGCLBN58 - cc @wyter

**Comment by csmcneill** [comment]
5235294-zen / 5228586-zen

**Comment by chrism245** [comment]
35139339-hc

**Comment by wyter** [comment]
5349261-zen

**Comment by Brianmitchtay** [comment]
A merchant asking us about this again in 5509879-zen

**Comment by rogermattic** [comment]
👋 Thanks for bringing this to my attention! 

@DanReyLop  If you don't mind I just wanted to clarify a few issues, so that I understand this clearly.
When you said:

> That means the total of a Deposit may not match the total of the transactions in said deposit. (...) For example, if a merchant had $200 in transactions yesterday, but Stripe holds $50 in funds, today's deposit will be of just $150, even if all the transactions added together sum $200.

Does that mean that the _real_ total of a deposit won't be reflected at all in any of these values – not in the `next deposit` (as this will just display $150 in the example you've described) or even the `pending balance` or `available balance`:
<img width="710" alt="Screenshot 2022-09-30 at 10 54 24" src="https://user-images.githubusercontent.com/94967682/193234378-b62b6bf8-0a20-4bb6-96bf-091f6a266853.png">

So the only way for the user to know about the $50 on hold is to look at the Transactions list, and that's where the confusion arises. 

- Are we getting any message from Stripe for that case that we could re-shape and surface in our dashboard?
- Do we know how long Stripe holds the funds for? 
- Are there different reasons for Stripe to put the funds on hold, or is this always just suspected `fraud`?
- Is there any action that the user can do to speed the process up (do some extra verification or whatever)?


CC: @elizaan36  @bradyv 
[More context & the discussion here](https://wcpayoperations.wordpress.com/2022/09/30/lets-talk-about-expeditedpassportsandvisas-com/)

**Comment by darcie** [comment]
5661964-zen

**Comment by darcie** [comment]
5710936-zen

**Comment by lynnjat7** [comment]
38765472-hc

**Comment by haszari** [comment]
Labelled `category: projects` - this is directly related to our upcoming project to make deposits UI and process easy for merchants to understand.

**Comment by zoupkat** [comment]
@haszari or anyone else from the team that knows, would it be best if in the meantime we send the users to Stripe support in order for them to get a more detailed report related to the reserve funds?
Or is it best to generate that for the user? If so, is there a best way to do that on our end that you can recommend?
FYI, Stripe support had sent this customer our way for some reason but when we reached out to them internally they revealed the info needed. See 5989489-ZD and the related ticket with Stripe 5997622-ZD.

**Comment by haszari** [comment]
> @haszari or anyone else from the team that knows, would it be best if in the meantime we send the users to Stripe support in order for them to get a more detailed report related to the reserve funds?
Or is it best to generate that for the user? If so, is there a best way to do that on our end that you can recommend?
FYI, Stripe support had sent this customer our way for some reason but when we reached out to them internally they revealed the info needed. See 5989489-ZD and the related ticket with Stripe 5997622-ZD.

Ideally we'd avoid the need for merchants to ask / reach out when this happens – make the reserves and holds clear in the UI and docs. Case-by-case reports of where money is held aren't scalable, and I don't personally know what our options are there (e.g. Woo or Stripe compiling that data). 

@souravdebnath1986 @bradyv - let's keep this in mind for current deposits project. Although this scenario is more of an edge case, the deposits UX improvements may help make reserves etc clearer.

**Comment by Brianmitchtay** [comment]
Seeing this again in 6670503-zen

**Comment by darcie** [comment]
6797436-zen

**Comment by darcie** [comment]
7163823-zen

**Comment by brucealdridge** [comment]
@elizaan36 this looks like an ongoing issue. It would be good to have design look into ways to solve this issue.

**Comment by brucealdridge** [comment]
@elizaan36 it looks like there was design done as part of the simplify deposits project (screenshots are in #5774)

@souravdebnath1986 it looks like we cannot access this information currently via the Stripe API. We will need to resolve this as part if we want to add to the roadmap.

**Comment by brucealdridge** [comment]
Closing this issue. We're aware of the issue it's on the roadmap with @souravdebnath1986 for prioritization and once the resolution of lack of API access is resolved.

**Comment by EjayhanFernandes** [comment]
8227527-zd-a8c - Just adding this user. They would like something implemented in the future to address this issue.

**Comment by rogermattic** [comment]
>Closing this issue. We're aware of the issue it's on the roadmap with @souravdebnath1986 for prioritization and once the resolution of lack of API access is resolved.

Just wanted to double-check - is design needed for this?
