### ISSUE TITLE
Let merchants with live account know their dev mode isn't going to work when continuing to onboard

### ISSUE THREAD

**Issue by v18** [Automattic/woocommerce-payments#2734]
When a merchant has already started onboarding and created a new account (using the new flow with account links - 914-gh-Automattic/woocommerce-payments-server), and then later starts using dev mode, they won't able to onboard using dev mode. However, we also don't let them know that dev mode isn't work so it can be a bit confusing.

**Steps to repro:**
1. Update environment to use new Account Links from 914-gh-Automattic/woocommerce-payments-server
2. As a new merchant, click on 'Finish setup' in live mode, and go through at least the phone number step
3. Add dev mode using `define( 'WCPAY_DEV_MODE', true );`
4. Click on 'Finish setup'
5. See that you're not in "test mode" in KYC, and you're back on the KYC step from item 2 above - e.g. you're continuing to onboard with the live account

Some possible solutions:

**Possible solution 1: notice about dev mode**
We could add a notice about dev mode not working somewhere on the onboarding page:
<img width="1021" alt="Screen Shot 2021-08-14 at 8 09 06 AM" src="https://user-images.githubusercontent.com/11487924/129426097-79bc1124-dc4e-4247-9314-c39555c57f8d.png">

I tried a couple options ([1](https://user-images.githubusercontent.com/11487924/129426416-35cc7847-ac96-4eba-8639-3b9eac14b902.png),[2](https://user-images.githubusercontent.com/11487924/129426419-065694a6-2355-4ce4-9355-c4cb0e203f3d.png)), but I'm not sure they'll be helpful if we're prioritizing the live account onboarding experience. For one - it adds noise to the page.

**Possible solution 2: add note about this in dev mode**
I think we should add a note regardless if we implement any visual indicators:
https://docs.woocommerce.com/document/payments/testing/dev-mode/

**Comment by ricardo** [comment]
Just to make it clear, this may also be an issue in the current onboarding process, the difference is that the merchant now doesn't need to finish live KYC.

In addition to letting them know, we could perhaps offer the previous behavior by changing how WCPay handles unonboarded accounts when switching modes. We could check if a live account didn't finish KYC and remove it if the merchant is switching back to dev mode.

**Comment by LevinMedia** [comment]
closing this issue in favor of the other issues surrounding KYC resets / deletes.

**Comment by LevinMedia** [comment]
Related to #3468

**Comment by oaratovskyi** [comment]
I've made a quick spike on how it works now:
- we have notices about test mode in the overview and settings pages (both current KYC - image 1 and Progressive onboarding with new onboarding UX - image 2). Settings page would be image 3.
- it indeed continues to proceed with live KYC, but with test mode enabled for live account

<img width="300" alt="image" src="https://github.com/Automattic/woocommerce-payments/assets/79862886/77716ad6-a377-4e4b-bcdf-5262f2aeb030">
<img width="300" alt="image" src="https://github.com/Automattic/woocommerce-payments/assets/79862886/d996a72e-7617-4834-8104-ccc117002674">
<img width="300" alt="image" src="https://github.com/Automattic/woocommerce-payments/assets/79862886/423c6b94-6bcf-4c81-b29f-61ff1fd477d5">

I didn't try to finish live KYC with bank account etc, but I guess it'll work fine, though it'll be in test mode. To confirm my guess we'd need some account that we use to test full live KYC flow. Is this possible?

cc @daquinons

**Comment by daquinons** [comment]
@oaratovskyi Thank you for taking a look and doing a refresher! 

This issue has been open for a long time without progress and additional user requests on it. Because #6429 is adding pointers around this same scenario in our new onboarding experience, I'm closing this one to prioritize the new flow improvements.
