### ISSUE TITLE
Use store country instead of user country in Preview Mode experiment

### ISSUE THREAD

**Issue by adrianduffell** [Automattic/woocommerce-payments#2742]
A new "custom segment" is planned in ExPlat to allow experiment segmentation based on the WooCommerce country setting.

The `Experimental_Abtest` class should be updated to send a `woo_country_code` param automatically in the API request. To do this, I think we could apply a filter on `$args` in `request_variation` here allowing additional params/args to be added

https://github.com/Automattic/woocommerce-payments/blob/3b64aca27eea3319b5f72395ee5b32ce491b2f4c/includes/class-experimental-abtest.php#L159-L167

A filter would then be made that adds the `woo_country_code` param. The param value should be in the form of `en_US`. I _think_ this can be retrieved using `get_locale`.

Once in place, this should make testing PR #2556 easier for those outside of the US.

### Context

The Preview Mode experiment implementation uses both the PHP and JS clients to delivery functionality. However a flaw was discovered where the ExPlat server will determine the country’s segment differently for each:

- **JS**: The user’s country will be used.
- **PHP**: The server’s country will be used. This might even be different to the store’s country In WooCommerce settings.

**Comment by adrianduffell** [comment]
I've updated the description with the new approach planned for this.

**Comment by ilyasfoo** [comment]
@adrianduffell Sorry, an eligible value should be in the form of 'US:GA'. `en_US` value was the language locale, not store country. The value is stored in `woocommerce_default_country` option.
