### ISSUE TITLE
Update settings UI to match WCpay settings

### ISSUE THREAD

**Issue by LevinMedia** [Automattic/woocommerce-payments#2745]
Update the MC settings page to use the same layout/style/functionality as the new 2 column payments grouped settings page.

**Comment by daquinons** [comment]
Figma screens here https://wcpay.wordpress.com/2021/03/31/introducing-multi-currency-for-wcpay/

**Comment by daquinons** [comment]
Putting #2832 on hold as per discussion in p1630659640146600-slack-C01B8KNUYSW
