### ISSUE TITLE
[GlobalStep] "Amount", "Status" and "Bank Account" columns are not center aligned on Payments->Deposits screen.

### ISSUE THREAD

**Issue by gglobalstep** [Automattic/woocommerce-payments#2752]
## Bug Description:
"Amount", "Status" and "Bank Account" columns are not center aligned on Payments->Deposits screen.

## Environment:
Woocommerce Version : WooCommerce 5.5.2
WooCommerce Payments - 2.9.0-test-2.

PC:
Windows 10, Mac 10.14.6
Chrome(Version 92.0.4515.131) 
Firefox(Version 90.0.2)
Safari: v14.1.2

## Steps To Reproduce:
1. Create any test site using JN site.
1. Install and activate all the required plugins.
1. Upload and activate the WooCommerce Payments v2.9.0-test-2 plugin. 
1. Complete the setup wizard.
1. Complete the KYC flow.
1. Go to Store page and add any product to the cart.
1. Complete the checkout process.
1. Go to Payments-> Deposits.
1. Observe that "Amount", "Status" and "Bank Account" columns are not center aligned.

## Actual Result:
"Amount", "Status" and "Bank Account" columns are not center aligned on Payments->Deposits screen.

## Expected Result:
"Amount", "Status" and "Bank Account" columns should be centerally aligned on Payments->Deposits screen.

## Screenshot:

![#2752](https://user-images.githubusercontent.com/41110392/129757666-6882caf8-56c5-46b3-86b2-8320c24a451d.png)

*Isolating the problem (mark completed items with an [x]):*
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Comment by dechov** [comment]
Thanks for the report – this was a deliberbate change, see https://github.com/Automattic/woocommerce-payments/issues/2351. Is there reason for keeping them centrally aligned, or is that expectation based on how it appeared in previous versions?

**Comment by gglobalstep** [comment]
> Thanks for the report – this was a deliberbate change, see #2351. Is there reason for keeping them centrally aligned, or is that expectation based on how it appeared in previous versions?

Yes, we have reported this based on the previous versions.

**Comment by naman03malhotra** [comment]
The current alignment is as per the design, text to be left-aligned and numbers to be right.
