### ISSUE TITLE
MC tracks: Inbox note funnel completion

### ISSUE THREAD

**Issue by jessepearson** [Automattic/woocommerce-payments#2760]
* Percentage of merchants who click note then add at least 1 customer currency within 1 day, 7 days and 30 days

This can and should be broken down into individual events for Tracks to track, e.g.
* Inbox note click – with timestamp
* Currencies added – with timestamp

Then the funnel can be built afterwards using those events.

Edit: Updated scope per comment: paJDYF-2o5-p2#comment-7834

**Comment by jessepearson** [comment]
Placed on hold per paJDYF-2o5-p2#comment-7822

**Comment by ismaeldcom** [comment]
Increased estimation to 3, due to changes in scope/implementation and multiple reviews.
