### ISSUE TITLE
MC tracks: Settings page views

### ISSUE THREAD

**Issue by jessepearson** [Automattic/woocommerce-payments#2763]
* Multi-Currency main settings page views
* Page views on individual currency management screens
  * Filter by currency

We may already have access to this data through WC-admin tracking – can we confirm?

**Comment by ismaeldcom** [comment]
I can confirm that those events are being tracked with `wcadmin_page_view`:
<img width="765" alt="Screenshot 2021-08-31 at 10 22 50" src="https://user-images.githubusercontent.com/7670276/131468763-ad1e926b-a372-4a71-abc3-e43446e4dd44.png">
<img width="840" alt="Screenshot 2021-08-31 at 10 22 58" src="https://user-images.githubusercontent.com/7670276/131468767-a0e223fc-57f0-4d26-bfe0-afd15d6a4981.png">

**Comment by LevinMedia** [comment]
@jessepearson - what's currently being tracked should suffice.
