### ISSUE TITLE
Currency position mismatch

### ISSUE THREAD

**Issue by chrism245** [Automattic/woocommerce-payments#2766]
**Steps to reproduce**:

1. Any WooCommerce Payment release above 2.7.1
2. Select Euro as currency.
3. Change the currency position from right to left and the change won't be saved.
4. If you disable WooCommerce Payments, it will work as expected.

![Markup 2021-08-19 at 09 35 09](https://user-images.githubusercontent.com/47186013/130098835-cf692630-f22c-424c-9d18-b4770ad95acc.png)

![Markup 2021-08-19 at 09 36 18](https://user-images.githubusercontent.com/47186013/130098992-f73e985c-1de3-469f-9f05-de35d86648f1.png)

**Expected**:
It should place the currency symbol based on the WooCommerce options. It worked with the 2.7.1 release.

![Markup 2021-08-19 at 09 32 12](https://user-images.githubusercontent.com/47186013/130099073-9ca58495-21bf-4c22-81ef-ab7fd76acbd4.png)

Reported on 30427377-hc

**Comment by malithsen** [comment]
This is fixed with #2660 and not reproducible in the latest WooCommerce Payments (3.0.0) version.

**Comment by chrism245** [comment]
Thanks for that! 👍
