### ISSUE TITLE
UPE is removed when payment fragment is overwritten

### ISSUE THREAD

**Issue by bborman22** [Automattic/woocommerce-payments#2799]
### Describe the bug

When there is a payment method that might have an updated fragment, the payment area markup may get overridden. When this happens UPE will be removed and is not remounted leaving the customer unable to checkout using UPE. This was discovered when working with the Stripe gateway plugin and was addressed in https://github.com/woocommerce/woocommerce-gateway-stripe/pull/1748 and a similar approach could be used here. This could also be considered a compatibility issue as the plugin itself does not require an updated fragment, but other payment method plugins might as in the case of the Stripe gateway.

### To Reproduce

- Start with a connected store with UPE enabled.
- Enable at least 2 shipping methods (ex. Flat Rate - $10 and Free Shipping)
- Modify the `payment_fields` function so that some part of the markup is updated on every call.
    - I added a data-time attribute to an element with a value of a PHP time call (`data-time="<?php echo time(); ?>"`)
    - This modification is to simulate another plugin possibly forcing a fragment overwrite.
- Add a product to the cart and go to the checkout
- Confirm the UPE loaded and displays correctly.
- Change the shipping method to force an `update_order_review` call.
- See that the UPE was removed and is not remounted.

### Actual behavior

The UPE is removed when the `update_order_review` call returns updated markup for the payments area and is never remounted.

### Screenshots

![WCPay-UPE-Before](https://user-images.githubusercontent.com/68524302/130858218-ecbf5020-ed66-4760-bb3f-cb58dc40c9a0.gif)

### Expected behavior

The UPE should be remounted when removed by an update using the already created `upeElement` rather than creating a new element entirely.

**Comment by malithsen** [comment]
Addressed with https://github.com/Automattic/woocommerce-payments/pull/3331/files
