### ISSUE TITLE
WC_Payments_Fraud_Service::send_forter_token() related error when syncing site with WCPay 2.9.0 in ManageWP.

### ISSUE THREAD

**Issue by melek** [Automattic/woocommerce-payments#2805]
### Describe the bug
When using ManageWP, trying to sync a site with WooCommerce Payments 2.9.0 installed (even when inactive, according to a user) causes this error when trying to sync the site:

> Argument 1 passed to WC_Payments_Fraud_Service::send_forter_token() must be of the type string or null, array given, called in /var/www/wp-includes/class-wp-hook.php on line 303 occurred in wp-content/plugins/woocommerce-payments/includes/class-wc-payments-fraud-service.php on line 202 please make sure that your website is accessible

ManageWP told one user that this is the fault of the plugin (and that we are "working on it"), but I've found nothing related to this issue in the repository.

A [forum user](https://wordpress.org/support/topic/problem-with-2-9-0/) with the issue reports that downgrading to 2.8.4 fixed the issue for them.

### To Reproduce
According to ManageWP users:

* Connect a WooCommerce site to a ManageWP instance
* Install or upgrade to WooCommerce Payments 2.9.0
* Attempt a sync on ManageWP
* See error

### Actual behavior
Errors appear - see bug description and screenshot. 

### Screenshots
From 4248910-zen:
<img src="https://d.pr/i/2IBQ7F+" width="400">

### Expected behavior
WooCommerce Payments should not return an error.

### Additional context
I set to Priority High because the error appears to me that it may affect other services as well, and because the ManageWP Worker plugin is [extremely popular](https://wordpress.org/plugins/worker/) among firms/developers to manage clients at over 1 million installs.

* Ticket: 4248910-zen 
* [Community forum post](https://wordpress.org/support/topic/problem-with-2-9-0/)

**Comment by fylgjur** [comment]
Affected customer in 4257386-zen asked for the previous version while awaiting the version release, which I sent them.

**Comment by sukafia** [comment]
Another issue here: 30778882-hc

**Comment by rashedripon** [comment]
Another one here 24831592-hc

**Comment by WillBrubaker** [comment]
I'll point out that the ticket @shrutimoorthy highlights is on 2.9.1. Also, a forum user is experiencing the same behavior after updating to 2.9.1 see https://wordpress.org/support/topic/problem-with-2-9-0/#post-14848547

**Comment by ismaeldcom** [comment]
Hey @WillBrubaker! The fix will be included on 3.0.0, I couldn't find where we told the user that it will be fixed on 2.9.1 🤔  AFAIK the only reference to when it will be included was here p1630303347049000/1629932831.342400-slack-C7U3Y3VMY

I'm closing it again, feel free to reopen if the issue persist on 3.0.0 🙂

**Comment by mgc2865** [comment]
@ismaeldcom here's where I, the poster in the forum, was told it was fixed (the bolding is mine):

Thu P. a11n (@thup90)
1 week, 2 days ago
Hi @mgc ,

With our premium support channel, we are able to check the issue for you and update you when the fix is released.

**I’ve just checked the issue and it looks like a fix is coming in the next version of the plugin, so you can just keep an eye out for an update.**

Feel free to get back to us in case you have any additional questions!

**Comment by ismaeldcom** [comment]
Thanks for pointing it out @mgc2865. Pretty sure @thup90 was referring to the next major/minor release (3.0.0), 2.9.1 is a patch release for 2.9.0. Apologies for the confusion! You should be able to update to 3.0.0 without issues 🙂

**Comment by mgc2865** [comment]
Awesome! Thank you, @ismaeldcom!

**Comment by mgc2865** [comment]
ManageWP issued a new release of the Worker plugin and that fixed the issue for me.

**Comment by mgc2865** [comment]
Spoke too soon. It's disconnecting again. :(
