### ISSUE TITLE
The "Finish setup" page is not visible, as it is showing a white page.

### ISSUE THREAD

**Issue by chrism245** [Automattic/woocommerce-payments#2806]
### To Reproduce
WooCommerce + WooCommerce Payments 2.9.0

### Actual behavior
1. Install WooCommerce Payments 2.9.0
2. Once you activate the plugin, it will send you to a white page.
3. Click on the “Settings”, it will send you to the white page.
<img width="1237" alt="Markup 2021-08-26 at 23 24 40" src="https://user-images.githubusercontent.com/47186013/131077186-f3c40e62-02c5-4ca0-930c-1390358583b0.png">
4. Click to “Manage” it will send you to a white page.
<img width="1243" alt="Markup 2021-08-26 at 23 27 58" src="https://user-images.githubusercontent.com/47186013/131077233-a12945fd-823d-49ca-aba5-e0502005531c.png">

### Expected behavior
It should show the “Finish setup” page. The previous extension release used the following path to show the Finish Setup page: **https://wordpresssite.com/wp-admin/admin.php?page=wc-admin&task=payments**.

The 2.9.0 version is using **https://wordpresssite.com/wp-admin/admin.php?page=wc-admin&path=%2Fpayments%2Fconnect** instead. If you modify the path, it will show the page correctly.

<img width="1124" alt="Markup 2021-08-26 at 23 33 07" src="https://user-images.githubusercontent.com/47186013/131077507-557a9c7d-578c-4017-b51d-02e01484f922.png">
<img width="1127" alt="Markup 2021-08-26 at 23 34 05" src="https://user-images.githubusercontent.com/47186013/131077511-2072db08-108e-48e7-bdd6-dcec55c6e57d.png">

This happens with an AT and Self-Hosted site.

**Comment by leonardola** [comment]
I could not reproduce the bug. 

**2.9.1 on develop branch:**

**Right after a fresh install**
- /wp-admin/admin.php?page=wc-admin&path=%2Fpayments%2Fconnect is a **working** page
- /wp-admin/admin.php?page=wc-admin&task=payments is a **working** page
-  /wp-admin/admin.php?page=wc-settings&tab=checkout&section=woocommerce_payments **redirects** to /wp-admin/admin.php?page=wc-admin&path=%2Fpayments%2Fconnect 

- Activating the plugins redirects to wp-admin/admin.php?page=wc-admin&path=%2Fpayments%2Fconnect
-  Clicking on settings inside Plugins page redirects to /wp-admin/admin.php?page=wc-admin&path=%2Fpayments%2Fconnect
- Clicking on WooCommerce > Settings > Payments > WooCommerce Payments > Setup redirects to /wp-admin/admin.php?page=wc-admin&path=%2Fpayments%2Fconnect

**After configuring**
- /wp-admin/admin.php?page=wc-admin&path=%2Fpayments%2Fconnect is **broken** page
- /wp-admin/admin.php?page=wc-admin&task=payments is a **working** page
- /wp-admin/admin.php?page=wc-settings&tab=checkout&section=woocommerce_payments **redirects** to /wp-admin/admin.php?page=wc-admin&path=%2Fpayments%2Fconnect

- Deactivating and activating does not redirect to another page
- Clicking on settings inside Plugins page redirects to /wp-admin/admin.php?page=wc-settings&tab=checkout&section=woocommerce_payments
- Clicking on WooCommerce > Settings > Payments > WooCommerce Payments > Manage redirects to /wp-admin/admin.php?page=wc-settings&tab=checkout&section=woocommerce_payments



**Production plugin:**
**Before configuring**
- /wp-admin/admin.php?page=wc-admin&path=%2Fpayments%2Fconnect is a **working** page
- /wp-admin/admin.php?page=wc-admin&task=payments is a **working** page
- /wp-admin/admin.php?page=wc-settings&tab=checkout&section=woocommerce_payments **redirects** to /wp-admin/admin.php?page=wc-admin&path=%2Fpayments%2Fconnect

- Activating the plugin redirects to /wp-admin/admin.php?page=wc-admin&path=%2Fpayments%2Fconnect
- Clicking on settings inside plugins page redirects to /wp-admin/admin.php?page=wc-admin&path=%2Fpayments%2Fconnect
- Deactivating and reactivating the plugin redirects to /wp-admin/admin.php?page=wc-admin&path=%2Fpayments%2Fconnect


**After configuring**
- /wp-admin/admin.php?page=wc-admin&path=%2Fpayments%2Fconnect is a **broken** page
- /wp-admin/admin.php?page=wc-admin&task=payments is a **working** page
- /wp-admin/admin.php?page=wc-settings&tab=checkout&section=woocommerce_payments is **working** page

- Deactivating and activating does not redirect to another page
- Clicking on settings inside plugins page redirects to  /wp-admin/admin.php?page=wc-settings&tab=checkout&section=woocommerce_payments
- Clicking on WooCommerce > Settings > Payments > WooCommerce Payments > Manage /wp-admin/admin.php?page=wc-settings&tab=checkout&section=woocommerce_payments



**I did not get redirected to a blank page when clicking on buttons or links. I could see broken pages when accessing them directly in some cases**

**Comment by chrism245** [comment]
Hi @leandroalonso, thanks for checking this out! It is weird that I was able to reproduce it, but now I am not able to get that error again.  I think this can be closed.
