### ISSUE TITLE
WCPay Subscriptions phase 3: Testing

### ISSUE THREAD

**Issue by chickenn00dle** [Automattic/woocommerce-payments#2815]
Epic for tracking issues while testing subscriptions feature. 

See paJDYF-2rf-p2

**Comment by chickenn00dle** [comment]
- https://github.com/Automattic/woocommerce-payments/issues/2925
- https://github.com/Automattic/woocommerce-payments/issues/2917

**Comment by james-allan** [comment]
Testing has been ongoing with GS, Axiom and ourselves. Testing will continue as an ongoing thing.
