### ISSUE TITLE
Disputes list: add filters

### ISSUE THREAD

**Issue by dechov** [Automattic/woocommerce-payments#282]
There are filters for transactions and deposits available, similar filters could be added for disputes.

Potential fields for filtering (to be discussed):

- Status
- Disputed on
- Respond by
- Order number (search bar)
- Customer (search bar)

Initial disputed designs in paJDYF-gH-p2 (see Figma file)

> Should "Needs Response" dispute rows link directly to the evidence form?

No. This was answered in [comments below](https://github.com/Automattic/woocommerce-payments/issues/282#issuecomment-566667201).

There is also a special note on where row link should point depending on dispute status. Probably should handled in another issue.

**Comment by jrodger** [comment]
This can likely be closed since we now have advanced filters on this page. However, I've added it to the product review backlog so that we can double check we have all the filters and functionality we would like.

**Comment by jrodger** [comment]
Related: https://github.com/Automattic/woocommerce-payments/issues/4124

**Comment by haszari** [comment]
Adding some new info from team investigation:

> It’s unclear if the Payments -> Disputes filters will work for our needs. eg it’s currently only possible to filter by a single status and there are 2 needs response statuses ('needs_response' and 'warning_needs_response'). If we plan on [navigating to these statuses by default](https://github.com/Automattic/woocommerce-payments/issues/4124), we’ll need to look at how that will be possible. – @james-allan 

Looks like we'll need to improve the filtering UI / mechanism to show disputes with either `needs_response` or `warning_needs_response`.

**Comment by haszari** [comment]
Update: as I understand it, we have appropriate filtering in disputes list now. 

- We have general purpose filtering (has been in place for a while) - #3609 #3591
- We also have a new preset filter for disputes that need attention (`needs_response` or `warning_needs_response`) - #4124 #4361

So we might be ok to close this. @dechov @Jinksi  @jrodger @james-allan any reason to keep this issue open? I figure we can open a new issue if there's any specific follow up.

**Comment by haszari** [comment]
Closing, we are working on a project related to this. See new [epic here](https://github.com/Automattic/woocommerce-payments/issues/6355), and if there's any useful info in this issue, let me know and/or comment on the epic.

https://github.com/Automattic/woocommerce-payments/issues/6355

Note the above epic is phase 1 and there may be other updates (more filtering etc). These ideas are captured in roadmap plans, so I don't think we need to keep this issue open. If not, let me know!

FYI @souravdebnath1986  – closing an old enhancement idea for disputes list.
