### ISSUE TITLE
Remove unneeded methodID parameter for payment request button customizer

### ISSUE THREAD

**Issue by tommyshellberg** [Automattic/woocommerce-payments#2863]
### Description

When rendering the Payment Request(Express Checkouts) customizer page, we generate a methodID of 'payment_requests' and pass that to React. There aren't any other ids other than payment_requests, though, so it doesn't make sense to use it anymore. I believe it was created with a plan in mind to use additional methods which has been scrapped.
Some examples of where it's used:

https://github.com/Automattic/woocommerce-payments/blob/4e52a889a39a3498ae98a3fd76412e984479f381/client/settings/payment-method-settings/test/index.js#L41

https://github.com/Automattic/woocommerce-payments/blob/f4f9491e63b185e63fd7be99ace52a68c6c53ef7/client/settings/index.js#L35

https://github.com/Automattic/woocommerce-payments/blob/4e52a889a39a3498ae98a3fd76412e984479f381/client/settings/payment-method-settings/index.js#L21

**Comment by ismaeldcom** [comment]
Closing this as the code changed since then, and now we're using other method ID apart from `payment_requests`.
