### ISSUE TITLE
Missing file error for `payment-request.css`

### ISSUE THREAD

**Issue by c-shultz** [Automattic/woocommerce-payments#2876]
### Describe the bug
https://github.com/Automattic/woocommerce-payments/pull/2776 removed `payment-request.css` but left the [related enqueue](https://github.com/Automattic/woocommerce-payments/blob/2.9.1/includes/class-wc-payments-payment-request-button-handler.php#L668-L669) so a missing file error is being generated on the checkout screen.

### To Reproduce

1. Open browser console
2. Go to checkout 
4. See error for missing file `/woocommerce-payments/dist/payment-request.css?ver=2.9.1`

**Comment by helgatheviking** [comment]
Has this been published yet? I am still seeing it and just downloaded the plugin from .org just now.

**Comment by brettshumaker** [comment]
@helgatheviking No, this will be included in the next release.

**Comment by helgatheviking** [comment]
Sounds good, thank you! I was about to report the same since I was trying to do some compatibility testing with this.

**Comment by csmcneill** [comment]
Encountered a user with this issue in 4337263-zen. Informed them that a fix will be included in the 3.1.0 release.
