### ISSUE TITLE
A function to upgrade Stripe billing to tokenized subscriptions.

### ISSUE THREAD

**Issue by shendy-a8c** [Automattic/woocommerce-payments#2880]
### Description
Sub-task of https://github.com/Automattic/woocommerce-payments/issues/2868.
Implement a way to upgrade a subscription from Stripe Billing to tokenized subscriptions.

When upgrading, do the following:
1. Cancel the billing subscription at Stripe.
2. Archive the `_wcpay_subscription_id` subscription meta.
3. Copy the current payment method ID from the billing subscription into a token and set that as the WC subscription’s payment method. This shouldn't be necessary given the token should have been kept in sync while a Stripe billing subscription.

### Testing instructions

WIP

**Comment by james-allan** [comment]
In line with the comment above about this being deprioritised for v1. I'm going to close this. We can reopen or recreate this issue if we revisit upgrading Stripe billing subscriptions into tokenised subscriptions.
