### ISSUE TITLE
Hide incorrect default payment gateway title on page load

### ISSUE THREAD

**Issue by FangedParakeet** [Automattic/woocommerce-payments#2891]
### Describe the bug

> We’ve received feedback from a user who claims that the UPE is displayed as WooCommerce Payments on checkout. 
> 
> "Changing the payment gateway name to \“Woocommerce Payments\” is confusing my customers who think they need to  have a woocommerce account to pay with this method. Please change it or allow us to change it."

If there's a single payment method enabled, the gateway is titled after the name of that payment method; if there are multiple methods enabled, we title the gateway "Popular payment methods". However, we need to filter enabled payment methods by currency first to figure out which payment methods are enabled, so while that is happening, there is a brief flicker state, where the title uses the default value from the gateway's title property.

A WC payment gateway has two title properties: `method_title` and `title.` `method_title` is the main title, while `title` is a subtitle and the title at checkout. 

![Payment gateway titles in settings](https://cdn-std.droplr.net/files/acc_1104206/8Bw380)
_Payment gateway titles in settings_

If `method_title` and `title` have the same value, that subtitle gets hidden. This is the existing and desired functionality for this title and consequently the default checkout title takes this value ("WooCommerce Payments").

![Hidden gateway title](https://cdn-std.droplr.net/files/acc_1104206/D4r3JR)
_Gateway title/subtitle is hidden_

The goal here is to hide this temporary gateway title until we have the correct value, after checking whether multiple payment methods are enabled. This cannot be triggered by JS, because the gateway title appears before any of our scripts are queued and loaded in the page. Consequently, I think the only way this can be achieved is to hide the element with CSS. Below is an example of what that would look like.

![Hiding gateway title](https://cdn-std.droplr.net/files/acc_1104206/li8lJl)
_Using CSS to hide gateway title while preloading_

I have created a draft PR at #2892, which shows an example of how this could be implemented. However, due to the way that webpack scripts and stylesheets are loaded, the UPE gateway and legacy gateway share the same stylesheets. We need to hide the gateway title when the UPE is enabled, but we must not hide it when the legacy gateway is enabled. This is not yet resolved in the aforementioned gateway, since the SCSS file that hides the gateway title is loaded for both payment gateways. 

### To Reproduce

1. Enable UPE and visit checkout.
2. Notice that while payment gateway is in preloading state, while initial payment intent is being created, gateway is titled "WooCommerce Payments".
3. User should ideally not ever see "WooCommerce Payments" at checkout.

### Actual behavior

User briefly sees "WooCommerce Payments" as UPE gateway title, while gateway is in preloading state.

### Expected behavior

User should never see "WooCommerce Payments" as a gateway title at checkout.

### Desktop (please complete the following information):

* OS: [e.g. iOS]
* Browser [e.g. chrome, safari]
* Version [e.g. 22]

### Smartphone (please complete the following information):

* Device: [e.g. iPhone6]
* OS: [e.g. iOS8.1]
* Browser [e.g. stock browser, safari]
* Version [e.g. 22]

### Additional context

Relevant Slack thread: p1630332366014100-slack-C02BHNRN6R1

**Comment by ryanr14** [comment]
Had a ticket running into this issue I believe. 4292501-zen

**Comment by carles-matamartinez** [comment]
Hi!

We are the ones that opened ticket 4292501-zen. The issue we have is more serious than just a change on the title. On the checkout page, the fields to insert the cart details just disappear, making the payment impossible.

![image](https://user-images.githubusercontent.com/79193656/136707296-52dfe214-d60c-4534-8f1f-28569f42d16e.png)

Any updates on this issue? Is there any workaround? Not being able to pay is serious for a payment plugin and the issue has been identified weeks ago.

Thank you!
