### ISSUE TITLE
Use Stripe `Product`s for misc subscription costs such as shipping or fees, instead of ad-hoc invoice items

### ISSUE THREAD

**Issue by chickenn00dle** [Automattic/woocommerce-payments#2893]
### Description
Right now, we are creating ad-hoc invoice items prior to each renewal in Stripe. We were taking this approach because we believed there was too much overhead with adding these items directly to the subscription. For example, we thought we would need to maintain a separate product and price object for each different shipping, fee, etc. in WC. 

After some discussion with Stripe, it turns out there is a workaround to avoid all of this overhead. Mainly, creating a sort of generic product for each of the item types and adding them to the subscription with ad-hoc price data.

### Acceptance criteria

* Invoice items should be added directly to subscriptions
* Subscription items should remain flexible to account for changes in WC
* Subscription behavior and functionality should remain unchanged

### Additional context
See pdi1mn-11-p2 for meeting notes.

**Comment by chickenn00dle** [comment]
Noting some thoughts about implementation.

This can probably be broken down into 3 parts:

**1. Creating and storing product IDs for the generic products in Stripe.**

Since there will only be 1 product ID per item type in a store, we can store these in `wp_options`. As for creating, since this should be a 1-time thing for each item type, we can do this at checkout.

**2. Preparing and sending the item data to Stripe on subscription create**

This is the most straightforward part of this. We just need to get the relevant item data in `prepare_wcpay_subscription_data`. See https://stripe.com/docs/api/subscriptions/create#create_subscription-items-price_data

**3. Validate subscription items prior to renewal**

I'm thinking we need to verify WC and Stripe item data matches at one of the invoice events to make sure nothing needs to be changed in Stripe prior to the actual renewal. Theoretically, if we have locked editing of subscriptions, this might not be necessary. But similar to other gateways, we probably need to have some mechanism for correcting discrepancies just in case.

cc @mattallan and @james-allan for your thoughts.

**Comment by james-allan** [comment]
This sounds a lot more straightforward than I had originally thought. 😅 For some reason I thought there would be some need for new WC Pay Server endpoints etc. 

That description of the 3 parts sounds good to me. Part 3 is likely to be the more difficult part right? I don't know how we can update line items though.

**Comment by chickenn00dle** [comment]
>  Part 3 is likely to be the more difficult part right? I don't know how we can update line items though.

Yeah. I think so. I briefly tinkered with this in Postman and saw that each item has an associated id with it that we can map to WC subscription items. With this, we should be able to update individual items via the subscriptionitems endpoint: https://stripe.com/docs/api/subscription_items/update#update_subscription_item-price_data

I started working on this in #2899 but haven't gotten this far yet 😟

**Comment by chickenn00dle** [comment]
I've run into a problem dealing with coupons/discounts. It looks like `item.price_data.unit_amount` can't be negative: https://stripe.com/docs/api/subscriptions/create#create_subscription-items-price_data-unit_amount

And so, from my understanding, we would have to implement [coupons](https://stripe.com/docs/api/coupons) to make discounts work.

I should note that aside from this, everything else is working perfectly in #2899. So I'm gonna post a question for Xiao to see if there is a way to work around this just in case.
