### ISSUE TITLE
Enforce dispute evidence text length maxima

### ISSUE THREAD

**Issue by dechov** [Automattic/woocommerce-payments#290]
As documented in https://stripe.com/docs/api/disputes/update#update_dispute-evidence, several of the dispute evidence fields have "a maximum character count of 20,000", and the "combined character count of all fields is limited to 150,000".

Should we be enforcing this, and how?
- Check after every keystroke, and display character counts?
- Just check before save/submission?
- Check on server?
- Don't check – just await and report error from Stripe?

**Comment by vbelolapotkov** [comment]
Please note, copy/paste should be taken into account either. I doubt many merchants will type 20k characters reply directly into the field (without creating a draft somewhere else).
