### ISSUE TITLE
Persist unsaved evidence form changes to client-side storage

### ISSUE THREAD

**Issue by dechov** [Automattic/woocommerce-payments#291]
The dispute evidence form could take a while to fill out, and – despite the ability to "Save For Later" – has significant potential for frustration if the browser tab is closed or navigated unintentionally.

We could mitigate the chance of losing changes by caching them frequently in the browser.

**Comment by haszari** [comment]
This is a specific enhancement suggestion that we could consider as part of a future project, e.g. `Improve dispute challenge form`. 

@souravdebnath1986 I'm thinking we can close this and consider as part of the requirements for `Improve dispute challenge form` project. Closing, feel free to reopen if you think we should prioritise this as maintenance.
