### ISSUE TITLE
[Mobile Payments] Update capture warning to indicate in-person payments must be captured in 48 hours

### ISSUE THREAD

**Issue by allendav** [Automattic/woocommerce-payments#2921]
@laurendavissmith - please prioritize this text change highly

Right now we have this warning in settings for merchants who elect to auth without capture:

`Charge must be captured on the order details screen within 7 days of authorization, otherwise the authorization and order will be canceled.`

Xiao/Stripe noted today that, for in-person payments, authorizations must be captured within **48 hours**.

At a minimum, we should update that text to reflect that. Additional issues may be considered for warning merchants in wp-admin that they have un-captured authorizations nearing their expiration time, or disallowing auth-only for in-person payments. Feel free to comment below or open additional issues.

Edit: I am assuming this checkbox also controls auth/capture for in-person payments. I could be mistaken.

cc @juliacallicrate @astralbodies @ctarda 

Related: pdfdoF-9o-p2

<img width="1305" alt="must-be-captured" src="https://user-images.githubusercontent.com/1595739/133470833-2cfd44c6-48e6-4d17-812f-9d30aacb9de1.png">

**Comment by laurendavissmith** [comment]
@kalessil Will you take a look at prioritizing this one

@allendav FYI for these you can ping @kalessil who is leading the team responsible for the in-person payments work on our side so he can help you get this stuff prioritized

**Comment by allendav** [comment]
Update from Xiao/Stripe:

> https://stripe.com/docs/payments/capture-later
> When a payment is authorized, the bank guarantees the amount and holds it on the customer's card for up to seven days, or **two days** for in-person payments using Terminal.

**Comment by kalessil** [comment]
@laurendavissmith @allendav: sounds like a thing to be addressed before going live. Taking this into Pulsar-scope for the next sprint.

**Comment by kalessil** [comment]
Note: please report back in pdfdoF-9o-p2o close the loop there once merged.
