### ISSUE TITLE
Update 3DS flow for recurring transactions on Indian CCs

### ISSUE THREAD

**Issue by vbelolapotkov** [Automattic/woocommerce-payments#2935]
### Description
New regulations for processing recurring transactions in India are going live on September 30.
Changes to the 3DS flow are needed.

### Acceptance criteria

* Transactions on India issued CCs use correct flow and APIs.
* Transactions work in shortcode checkout.
* Transactions work in UPE checkout.
* Transactions work in blocks checkout.

### Designs
N/A

### Testing instructions

1. Purchase subscription product.
2. Trigger renewal.
3. Check new flow is applied.

### Dev notes

Not available yet.

### Additional context

Internal discussion and context: pc4etw-ky-p2

**Comment by iMazed** [comment]
4361013-zen has come in again asking what the status is, in particular now that their orders are starting to fail. What can we tell them?

**Comment by ismaeldcom** [comment]
We're still waiting for Stripe, looks like the transition is taking banks more time than expected. Unfortunately, there is no ETA.

**Comment by puntope** [comment]
Hey there! Any alternative to offer until Stripe is ready?

**Comment by ismaeldcom** [comment]
AFAIK, until it got fixed, the customer needs to come back on-site to manually renew the subscription.

**Comment by ismaeldcom** [comment]
**On-Hold at least until January**, when we get more input from Stripe about their API update being fully enabled.
More info: pc4etw-ky-p2#comment-1063

**Comment by pauljacobson** [comment]
Hi there @ismaeldcom 👋

Do we have an update on this issue?

**Comment by ismaeldcom** [comment]
I saw that you already got an answer on the project P2. Unfortunately we are still waiting for Stripe.

**Comment by ismaeldcom** [comment]
🔴  On-Hold until Stripe solves Discover issue. More info: paJDYF-3ZC-p2

**Comment by ismaeldcom** [comment]
🔴 On-Hold for an unknown amount of time. Stripe finally transitioned all the missing merchants to the new processor, but now there is another new requirement from India. So we're at the start point again, will need to wait for them to come with a solution until we can start looking at it. More details in pc4etw-ky-p2#comment-1160

We've also decided to not work on this issue until recurring payments for Indian CCs could be fixed. Issue thread: paJDYF-3ZC-p2

**Comment by ismaeldcom** [comment]
We can finally proceed with the implementation, being sure to update the code to use [the generally available version of the eMandate API](https://stripe.com/docs/india-recurring-payments). Looks similar to the beta documentation, but I see `supported_types` param being added.
