### ISSUE TITLE
Fatal Error when trying to checkout using the Multi-Currency Switcher extension

### ISSUE THREAD

**Issue by joashrajin** [Automattic/woocommerce-payments#2938]
### Describe the bug
When using the Multi-Currency Switcher extension on a site, you will get a fatal error when trying to checkout. I haven't encountered this issue with other payment gateways. 

`CRITICAL Uncaught TypeError: WCPay\MultiCurrency\FrontendCurrencies::get_price_decimal_separator(): Return value must be of type string, null returned in /srv/htdocs/wp-content/plugins/woocommerce-payments/includes/multi-currency/FrontendCurrencies.php:106`

Full Logs: https://d.pr/n/HFoqjl

### To Reproduce

1. Install [Multi-Currency Switcher](https://woocommerce.com/products/multi-currency-switcher/) on your site
2. Go to WooCommerce > YayCommerce > Currencies > Add a new currency, then select any currency that you want, such as EURO
3. Save changes, then try to checkout
4. You will then see the Fatal Error

### Actual behavior
A Fatal Error is triggered

### Screenshots
![image](https://user-images.githubusercontent.com/16253818/133801929-bec3bea1-51a2-444d-aed6-8931c36dd394.png)

### Expected behavior
You wouldn't expect to see a fatal error

### Desktop (please complete the following information):

* OS: MacOS 11.5.2
* Browser: Chrome
* Version: Version 93.0.4577.82

### Screen Recording

https://user-images.githubusercontent.com/16253818/133803592-1244bdba-1628-4497-9978-06c7bc2847a4.mp4

**Comment by htdat** [comment]
Thanks for reporting this @joashrajin. 

Hi @Automattic/sigma, can you have a look at this issue?

**Comment by tpaksu** [comment]
Hi @htdat @joashrajin , this seems to be related with a 3rd party multi currency plugin, not ours. Maybe they can disable the WCPay multi currency feature on Payments > Settings > Advanced Settings pane below > Uncheck "Enable Multi-currency" checkbox.

**Comment by ismaeldcom** [comment]
Yes, both WC Pay Multi-Currency and "Multi-Currency Switcher" (YayCurrency) do pretty much the same and use common filters and hooks. I think making them compatible could be really hard.

🤔 Not sure if we should check or notify the customer about our Multi-Currency implementation being enabled by default.

**Comment by joashrajin** [comment]
@ismaeldcom Just noting, this was reported by myself and not a customer. I noticed it when suggesting this extension to a customer and then noticing it broke my Checkout Page. 

The reason why I reported it was since Stripe was working fine, but not WC Pay. If it's not an easy one to fix, I guess we can close it.

**Comment by jessepearson** [comment]
I am pretty sure this was fixed by https://github.com/Automattic/woocommerce-payments/pull/2824
I just went through the steps of testing it out, and I couldn't replicate the issue.

**Comment by ismaeldcom** [comment]
As @jessepearson mentioned, with the latest `develop` branch it doesn't throw any error. But as I mentioned before it's incompatible. Even if you select EUR with YayCurrency switcher on a product page, it doesn't do anything.
