### ISSUE TITLE
Spike: explore ways to speed up E2E suite

### ISSUE THREAD

**Issue by vbelolapotkov** [Automattic/woocommerce-payments#2946]
### Description
E2E suite takes 30 mins to run. It's too much.
We need to explore it and find areas for improvement to keep suite run time under 10 mins.

Some known issues:

* Some pages load to long (Transactions, Disputes, etc.)
* There are lots of tests in the suite. Maybe find a way to run them in parallel.

### Acceptance criteria

* There is a list of ideas on how to achieve E2E suite run time of 10 mins.
* There are well-defined issues created.
* There is a plan on how to maintain run time under 10 mins with growing number of E2E tests.

### Additional context

p1632144097453500-slack-CGGCLBN58

**Comment by deepakpathania** [comment]
Created a P2 documenting all the known issues and proposed solutions: paJDYF-2PM-p2
Tracking all the open issues in the epic:  #3289 
cc @achyuthajoy @vbelolapotkov

**Comment by vbelolapotkov** [comment]
Closing this one, then.
