### ISSUE TITLE
WCPay Subscriptions: Create WC Pay subscriptions by paying for manual/failed renewal

### ISSUE THREAD

**Issue by james-allan** [Automattic/woocommerce-payments#2960]
Part of https://github.com/Automattic/woocommerce-payments/issues/2868 

### Description

When a merchant downgrades their site from the WC Subscriptions plugin, existing subscriptions will be treated as manual renewal and will require the customer to sign up to a WC Pay Subscription via Stripe Billing. This customer flow will be in the form of 1 of 2 approaches. 

1. Paying for a failed/pending renewal order. _Reactivate customer approach_
2. Add/changing the payment method. _Proactive customer approach. See [#2961](https://github.com/Automattic/woocommerce-payments/issues/2961)_

This issue will handle the **first** of those two approaches.  

### Testing instructions

1. Create a manual subscription by:
     - **Via plugin** 
       - Install the WC Subscriptions plugin
       - Purchase a subscription with a payment method like Stripe. 
       - Deactivate the plugin
       - If you have the latest _subscriptions-core_ with [this change](https://github.com/woocommerce/woocommerce-subscriptions/pull/4201 
) included in WC Payments, renewing this subscription will be treated as manual. 
     - **Via Admin**
     - Go to **WooCommerce > Subscriptions > Add new**
     - Add line items
     - Set the billing schedule
     - Set the customer and address fields
     - Save.
2. Renew the subscription manually via the edit subscription actions dropdown. https://d.pr/i/UqsRa2
3. This should place the subscription on-hold and create a pending renewal order. 
4. Paying for that order should set up a Stripe billing subscription.

**Comment by chickenn00dle** [comment]
@james-allan I started working on this and have a rough implementation in #3065 

I wanted to clear up one point before continuing though. In the case of the `Paying for a failed/pending renewal order` approach we are addressing here, I would like to confirm that the resulting subscriptions in Stripe and WC will both have a next payment date that is one billing interval from the date in which the manual renewal is complete.

More specifically, I want to confirm whether there are any edge cases in which this might not be true. From what I understand, we won't be allowing customers to renew early, even for downgraded subscriptions, so there shouldn't be a need to create the Stripe subscription with any other date than the one that it's being renewed on.

Let me know if I'm misunderstanding this.

Thank you!

**Comment by haszari** [comment]
@james-allan – are you handling wrapping this up or is it available for someone on the team? 

Let's reassign Raz's PRs & issues so they have a new owner while he's AFK.
