### ISSUE TITLE
WCPay Subscriptions: Create WC Pay Subscriptions from the add/change payment method flow

### ISSUE THREAD

**Issue by james-allan** [Automattic/woocommerce-payments#2961]
Part of https://github.com/Automattic/woocommerce-payments/issues/2868 

### Description

When a merchant downgrades their site from the WC Subscriptions plugin, existing subscriptions will be treated as manual renewal and will require the customer to sign up to a WC Pay Subscription via Stripe Billing. This customer flow will be in the form of 1 of 2 approaches. 

1. Paying for a failed/pending renewal order.  _Reactivate customer approach. See [#2960](https://github.com/Automattic/woocommerce-payments/issues/2960)_
2. Add/changing the payment method. _Proactive customer approach._

This issue will handle the **second** of those two approaches. 

### Testing instructions

1. Create a manual subscription by:
     - **Via plugin** 
       - Install the WC Subscriptions plugin
       - Purchase a subscription with a payment method like Stripe. 
       - Deactivate the plugin
       - If you have the latest _subscriptions-core_ with [this change](4201-gh-woocommerce/woocommerce-subscriptions 
) included in WC Payments, renewing this subscription will be treated as manual. 
     - **Via Admin**
     	- Go to **WooCommerce > Subscriptions > Add new**
     	- Add line items
     	- Set the billing schedule
     	- Set the customer and address fields
     	- Set the status to active.
     	- Save.
2. Go to the customer's **My account > Subscriptions > View subscription** page. 
4. Click **Add payment**
5. On that Add payment method page, the customer should only be able to sign up with WC Payments and doing so will create a WC Pay subscription via Stripe Billing. 

<img width="865" alt="Screen Shot 2021-09-22 at 3 24 51 pm" src="https://user-images.githubusercontent.com/8490476/134287840-e08b359f-2222-4b1c-851f-c6d3ae6928bd.png">

link: https://d.pr/i/a6CwOH

Note: IIRC, the add payment method page is the same as a change payment method page. It's just labelled differently.

### Dev notes

Because we will be creating a Stripe Billing subscription mid-term, we will need to make sure the Stripe Billing prices match the line items in WC. 

We will also need to make sure the next payment date matches the current subscription. With advice from Xiao, we should be using the following args when creating the Stripe Billing Subscription.

```
billing_cycle_anchor => next_payment_time,
backdate_start_date => last payment time
proration/proration_behaviour = false/none?
``` 

**API references**
https://stripe.com/docs/api/subscriptions/create#create_subscription-billing_cycle_anchor
https://stripe.com/docs/api/subscriptions/create#create_subscription-backdate_start_date
https://stripe.com/docs/api/subscriptions/create#create_subscription-proration_behavior

To make sure the subscription line items in Stripe match the line items in WC we will need to change [`WC_Payments_Subscription_Service::get_recurring_item_data_for_subscription()`](https://github.com/Automattic/woocommerce-payments/blob/feature/stripe_billing/includes/subscriptions/class-wc-payments-subscription-service.php#L613) and pass price data ([API ref](https://stripe.com/docs/api/subscriptions/create#create_subscription-items-price_data)) if the line item amount doesn't match the product price. This also applies to the recurring interval and period. If the product is monthly but for some reason, the WC SUbscription is yearly, we will need to pass price data so the Stripe Subscription is renewed yearly.

### Additional context

pdi1mn-17-p2#comment-40

**Comment by haszari** [comment]
Labelled this as `large` to signal the complexities with tax/pricing that we're working through.
