### ISSUE TITLE
WCPay Subscriptions: Admin can create new manual subscriptions from the edit subscription screen

### ISSUE THREAD

**Issue by james-allan** [Automattic/woocommerce-payments#2962]
**Update** Based on @james-allan comment, the scope of this issue has been simplified. 

- Admin should be able to create subscriptions for a customer (i.e. sign up customers).
- These subscriptions should be created with manual gateway only.

# old description follows (for context)

### Description

When admin create or edit a subscription via admin, **only** allow them to choose WooCommerce Payments, select a payment method and create WC Pay subscriptions. 

<img width="503.25" alt="Screen Shot 2021-09-22 at 3 47 00 pm" src="https://user-images.githubusercontent.com/8490476/134289661-421b0a07-8f6c-43a9-b453-e7599c263f0b.png">

### Acceptance criteria

* Manual renewal is the only option if the customer doesn't have any saved cards. 
* WooCommerce Payments is the only option shown if WC Subscriptions (plugin) isn't active.
* The WC Pay subscription will need to:
    1. Take the billing period and interval from the one admin choose or those billing schedule fields will need to be disabled and the billing periods and interval taken from the Stripe products.  
    2. Have the same next payment date that the admin entered, or those fields will need to be disabled and the subscription's next payment date will be taken from Stripe - as if the subscription was purchased today.

### Testing instructions

**Creating subscription:**
1. Go to **WooCommerce > Subscriptions > Add new**
2. Click the pencil icon in the billing fields section. 
3. Choose WooCommerce Payments
4. Select the saved payment method. 
5. Add products to the subscription.
6. Optionally, set a custom billing period, interval, and next payment date.
5. Save
6. The WC Pay subscription should be created.

**Comment by shendy-a8c** [comment]
@james-allan when I purchased a subscriptions product, paid it with wcpay, and edit the billing details of that subscription, I see `Credit card / debit card` as payment method and not `WooCommerce Payments`.

<img width="403" alt="Screen Shot 2021-10-04 at 02 23 30" src="https://user-images.githubusercontent.com/73803630/135768533-5d226e1c-df88-474f-a54e-55b663e55ca9.png">

Also, when I create a subscriptions from admin then choose a user with wcpay saved payment methods, I can already select `Credit card / debit card` as payment method and can choose one of the saved payments.

<img width="427" alt="Screen Shot 2021-10-04 at 02 25 44" src="https://user-images.githubusercontent.com/73803630/135768576-1d55901f-f50c-4404-a39a-414841b12da9.png">

What needs to be implemented for this issue then? Is it just to change the label from `Credit card / debit card` to `WooCommerce Payments`?

**Comment by james-allan** [comment]
> I see Credit card / debit card as payment method and not WooCommerce Payments

That's the payment method title being used. So if you're WCPayments gateway is titled that, that is what will be displayed. From what I have found, the [standard gateway instance has "Credit card / debit card" as its title](https://github.com/Automattic/woocommerce-payments/blob/trunk/includes/class-wc-payment-gateway-wcpay.php#L126) whereas the [UPE gateway has WooCommerce Payments as its title](https://github.com/Automattic/woocommerce-payments/blob/trunk/includes/payment-methods/class-upe-payment-gateway.php#L75) which is why we might be getting different things displayed there. 

> What needs to be implemented for this issue then?

Taking a step back for a moment. Initially, it was planned that Admin users would be able to create subscriptions manually via the admin interface, and if the customer already had saved payment methods, they would be able to select one and a Stripe billing subscription would be created. This would involve us effectively creating a stripe billing subscription from an existing subscription and to attach the selected payment method as the payment method in Stripe. 

Given we've been cutting the scope for MVP, we had a fallback approach of allowing admin to create subscriptions but forcing them to be manual renewal. 

Given what you mentioned about the tokens belonging to the admin users and not the customer, that's even further evidence that we should implement the base case first.

**So what needs to be done for this issue?** 

When creating a subscription manually, the only available payment method will need to be manual renewal. WooCommerce payments and other gateways will need to be hidden.

**Comment by shendy-a8c** [comment]
Created https://github.com/Automattic/woocommerce-payments/issues/3101 for this bug:

> actually, I just realized the shown saved payments the dropdown from the above screenshot are the saved payments of the admin who creates the subscription and not of the selected customer for that to-be-created subscriptions, so that's at least one thing that needs fixing.

**Comment by leonardola** [comment]
Hi there. This sprint I won't be working with WC Pay subscriptions so I have to hand off this issue. 

So far I have done this:
- added an ajax call to load the selected customer credit cards [here](https://github.com/Automattic/woocommerce-payments/pull/3221) 
- added an ajax call to load the selected customer valid payment gateways [here](https://github.com/Automattic/woocommerce-subscriptions-core/pull/31)

What still needs to be done:
- Create a subscription on stripe and a parent order when saving a new subscription via wp-admin

**Comment by haszari** [comment]
Thanks the help and the handover @leonardola ! 🏅

**Comment by haszari** [comment]
Adding this to sprint backlog. Note that the scope of this issue is smaller [based on comment above](https://github.com/Automattic/woocommerce-payments/issues/2962#issuecomment-934058662) from @james-allan:

> When creating a subscription manually, the only available payment method will need to be manual renewal. WooCommerce payments and other gateways will need to be hidden.

**Comment by leonardola** [comment]
> Given what you mentioned about the tokens belonging to the admin users and not the customer, that's even further evidence that we should implement the **base case first**.

@haszari to my understanding the scope was reduced to fit into MVP. But as it was removed from the MVP we could work on a more complete solution here. 

@james-allan can you confirm this?

**Comment by haszari** [comment]
> to my understanding the scope was reduced to fit into MVP. But as it was removed from the MVP we could work on a more complete solution here.

Aha, I see @leonardola ! Let's implement the simpler, base case first. Then we can discuss what to add to scope in future iterations.

**Comment by james-allan** [comment]
We moved away from prioritising this before shipping v1. I'm going to close this and we can reopen if this becomes a priority.
