### ISSUE TITLE
Preview mode a/b test not working as expected

### ISSUE THREAD

**Issue by pmcpinto** [Automattic/woocommerce-payments#2969]
### Describe the bug
The Deposits and Transactions empty states are not working as expected. I'm not seeing the Finish setup CTA + additional copy and illustrations.

### To Reproduce
1. Create a new store (I was using WC 5.7 rc2)
2. Install WCPayments
3. Visit the Deposits or Transactions empty screens if you're in the treatment version (if not, follow the instructions on Abacus to enable treatment)
4. Confirm that the Finish setup CTA + additional elements are missing

### Screenshots
https://d.pr/v/B9hLMw

**Comment by ilyasfoo** [comment]
@pmcpinto Thanks for the reproducible steps! I've just retested on the same site you've had this issue, but worked in my case. I suspect it could be something of your setup. Let's resume the discussion in slack.

![image](https://user-images.githubusercontent.com/3747241/134489559-c7a94161-5919-41d5-908f-c9fc6c9ca0ac.png)

**Comment by pmcpinto** [comment]
It's working as expected after clearing the application cache
