### ISSUE TITLE
Customer facing prices compatibility with Name Your Price

### ISSUE THREAD

**Issue by helgatheviking** [Automattic/woocommerce-payments#2973]
### Description

The [Name Your Price](https://woocommerce.com/products/name-your-price) plugin enables a customer to enter a custom price for a product. Ideally, I'd like to see this price entered be the price that the payment request buttons use.. and enable/disable the request buttons when the price is not valid. 

In the short-term, I could get by with a way to disable the display of the request buttons on products that do not support them.

### Acceptance criteria

Long term
- [ ] Enable/disable buttons when price is/not valid
- [ ] Send dynamic price to payment processor

Short term
- [ ] PHP filter to disable display of buttons where not supported

### Testing instructions

1. Create a name your price product
2. Click on request buttons (apple/google pay) on single product page
3. see $0 price regardless of what price you've entered. 

### Additional context
https://woothemes.zendesk.com/agent/tickets/4313225 - while not much info is provided there, they've submitted a new ticket to contact me directly and explained their issue as $0 payments no matter what price is entered.

**Comment by helgatheviking** [comment]
Should this be closed? The short-term solution is the filter in #3325. The long-term goal would be actually allowing the two plugins to work together so that the request buttons would support the customer-entered price.

**Comment by htdat** [comment]
> The long-term goal would be actually allowing the two plugins to work together so that the request buttons would support the customer-entered price.

Yes, agreed! I've created this issue so that we can continue the long-term approach there:
https://github.com/Automattic/woocommerce-payments/issues/3417
