### ISSUE TITLE
Implement Stripe multiple coupons when creating subscriptions

### ISSUE THREAD

**Issue by chickenn00dle** [Automattic/woocommerce-payments#2977]
### Describe the bug
Related to this PR: https://github.com/Automattic/woocommerce-payments/pull/2899

We moved from invoice items to adding items directly to subscriptions in the above, but were unable to verify whether coupons work as this functionality has not been added to our account yet. (See pdi1mn-15-p2#comment-35)

We'll need to work out adding coupons to subscriptions once this has been resolved with Stripe.

### To Reproduce
1. Add a subscription to the cart
2. Apply a recurring/fixed coupon to the cart
3. Checkout. This should give you an error because at the moment our dev Stripe account is not accepting the `discounts` param.

### Expected behavior
You should be able to checkout subscriptions with coupons and they should correctly be added in Stripe.

### Additional context
pdi1mn-15-p2#comment-35

**Comment by haszari** [comment]
FYI @chickenn00dle – When I was testing on a new test site (using WCPay in test mode, dev-tools plugin, with production server) I hit issues when trying to purchase a subscription with a coupon. 

The coupon is a 50% off coupon:

The error in the UI is generic: `There was a problem creating your subscription. Please try again or contact us for assistance.`

<img width="1453" alt="Screen Shot 2021-10-01 at 3 57 41 PM" src="https://user-images.githubusercontent.com/4167300/135558569-54852e51-b6ef-45e1-bfb5-0bd737d19884.png">

Is this expected - or is there something wrong with my store setup? I didn't see any relevant info in Woo logs or network requests.

**Comment by chickenn00dle** [comment]
Hey @haszari 

Thanks for the feedback!

Hmm. This is strange. I've been testing using our WCPay dev account with no issues.

I wonder if this is an issue with our WCPay production account. I've pinged Xiao here to confirm: pdi1mn-1w-p2#comment-49

In the meantime can you let me know if this works for you on our dev account with local server?

Thank you!

**Comment by haszari** [comment]
> I wonder if this is an issue with our WCPay production account. 
> In the meantime can you let me know if this works for you on our dev account with local server?

Looks like that was it, I see that it's been enabled for the WCPay production account too now. 🎉 I'll retest some more this week.
