### ISSUE TITLE
Add support for other payment methods to transaction list and details

### ISSUE THREAD

**Issue by luizreis** [Automattic/woocommerce-payments#299]
Currently, the transaction list and payment details view expect payment method to be a card. If we expect to receive payments using other methods, they would have to be addressed on those views as well.

**Comment by jessepearson** [comment]
Unsure when this was addressed, but the transaction list and detail view show the different payment method icons.

![Screen Shot 2021-11-26 at 11 57 46 AM](https://user-images.githubusercontent.com/4634416/143606597-9f1c7a9f-913a-4b3f-aff9-e69872ace73b.png)

![Screen Shot 2021-11-26 at 11 59 05 AM](https://user-images.githubusercontent.com/4634416/143606611-a46d3c22-e035-4dca-9502-808fd8560cdb.png)

Closing this issue.
