### ISSUE TITLE
Remove the redundant Enable grouped settings flag 

### ISSUE THREAD

**Issue by oaratovskyi** [Automattic/woocommerce-payments#2991]
### Description

Currently, the flag Enable grouped settings in WCPay Dev -> Util settings does not work.
It was removed in https://github.com/Automattic/woocommerce-payments/pull/2776.
It should be removed from WCPay dev tools as well.

### Additional context
p1632209491489100-slack-CGGCLBN58

**Comment by RadoslavGeorgiev** [comment]
Closing in favor of the issue in the dev-tools repo.
