### ISSUE TITLE
Woo Subscriptions (pro) welcome notice could be confusing

### ISSUE THREAD

**Issue by haszari** [Automattic/woocommerce-payments#3024]
### Describe the bug
There's a welcome admin notice for WooCommerce Subscriptions:

<img width="1183" alt="Remove or clarify subscriptions welcome notice" src="https://user-images.githubusercontent.com/4167300/135557328-536501a7-73b2-4b1c-8d51-2ebaed860d3b.png">

This is displayed when WCPay is active and WCPay Subscriptions is enabled (via wp option `_wcpay_feature_subscriptions`). 

We'll need to either remove this or adjust the wording before release to reflect that subs is a feature in WCPay.

### To Reproduce
1. Clone `feature/stripe_billing` branch get subscriptions active. (`composer update`, build, set `_wcpay_feature_subscriptions` option to `1`)
2. See admin notice in plugins screen and possibly elsewhere in admin.

### Expected behavior
Depends on how we handle welcome/onboarding guidance. The current notice could be removed or adjusted/replaced.

**Comment by haszari** [comment]
> Do we have any position about the proper solution for this?

The simplest thing to do next would be to remove or disable the notice for WCPay Subscriptions, i.e. only show it for Subs extension. That might be all we need for the MVP release.

Related: We plan to include a welcoming onboarding UI in the `Admin > Woo > Subscriptions` screen empty state, though this may not be included in the MVP release. 

cc @james-allan

**Comment by leonardola** [comment]
Issue created here: https://github.com/Automattic/woocommerce-subscriptions-core/issues/8

**Comment by haszari** [comment]
Thanks for tidying this up @leonardola !

> The solution would involve removing the function from WC Subscriptions core (this section) and port it over to the WC Subscriptions extension by including that code in the WC Subscriptions Plugin class (here). Note that the change is required to go into the 4-0-bleeding branch, not trunk.

Has the notice code been moved into [WC Subscriptions](https://github.com/woocommerce/woocommerce-subscriptions) (as suggested by @james-allan above), or has it just been removed from subs-core (https://github.com/Automattic/woocommerce-subscriptions-core/issues/8)? 

We'll either need a PR in subs repo or an issue to follow up later, to ensure the welcome message is displayed for new users of WC Subscriptions extension.
