### ISSUE TITLE
Payment fields disappear after changing country while another payment method is selected

### ISSUE THREAD

**Issue by billrobbins** [Automattic/woocommerce-payments#3028]
### Describe the bug
~When the WP Google Maps plugin is active and WooCommerce Payments has payment methods in addition to credit cards, this can cause the payment fields to disappear.~ If another payment method is selected while the billing address gets changed, this causes UPE fields to no longer appear.

### To Reproduce
1. In WooCommerce Payment Settings, enable the "early access" for additional payment methods, ~like Sofort and giropay~ you don't even need to enable any of those methods.
2. Make sure at least one additional (non-WCPay) payment gateway is active.
3. Add an item to the cart and go to checkout.
4. Enter a billing address and notice how the payment methods are available.
5. ~Select "sofort" as the payment method.~
6. Select the non-WooCommerce Payments gateway.
7. Change the country on the billing address.
8. Click on WooCommerce Payments.  

### Actual behavior
Following the steps above, the user will not be able to interact with the payment fields with WooCommerce Payments.  They won't load unless the page is refreshed.

### Screenshots
![disappearing-payments](https://user-images.githubusercontent.com/1138631/135648319-58282369-83a3-4a64-95ea-d27f662c3b2c.gif)

### Expected behavior
I expect that changing the billing address won't affect the loading of the payment methods.  

### Desktop (please complete the following information):

* OS: MacOS 11.5.2
* Browser: Chrome
* Version: 93.0.4577.82 (Official Build) (x86_64)

### Additional context
4288818-zen

**Comment by RadoslavGeorgiev** [comment]
I tried to replicate this behavior and found out that this issue is not specific to either:

- Additional WCPay payment methods (SEPA, Sofort, etc.). As long as UPE/early access is enabled, the bug will appear.
- No need to install _WP Google Maps_. This is not a compatibility issue, but an issue with WCPay itself.

**Comment by RadoslavGeorgiev** [comment]
After none of us managed to reproduce the issue in p1639658360195600-slack-C01BPL3ALGP, it turned out to have been fixed here: https://github.com/Automattic/woocommerce-payments/pull/3331
