### ISSUE TITLE
UPE confirm inactive state and enabling previously disabled UPE methods

### ISSUE THREAD

**Issue by dwainm** [Automattic/woocommerce-payments#3067]
## Preliminary information:

Some related or maybe related convos for the issue (for those directly jumping in to the issue, like me): 

p1630537567054800-slack-C9976E5MJ
p1632328685204500-slack-C9976E5MJ
p1632950108237200-slack-C9976E5MJ
p1632958525241500-slack-C9976E5MJ

UPE capabilities have those states:

- **Unrequested:** This means that the capability has not been requested for the merchant, thus the payment method won't be avaiable for the customers. 
- **Pending:** This status show that some verification is ongoing, still the payment method won't be available for the customers.
- **Active**: The payment method is ready to use.
- **Inactive**: The payment method is not available for customers, because of a validation error. 

### Part 1/2:
The question is, what does the customer see when their UPE capability is `inactive`? Does the payment method show up in the payments list? Does the user experience an error after paying with the inactive payment method? Or it doesn't show and prevent all?

Can we hide the UPE payment methods when they are not `active`?

### Part 2/2:
According to the first step, the disabled UPE methods (Bancontact, iDeal and Przelewy24) might be enabled back, after merging with the latest changes and testing the base, additional, and FX fee's for all three.

---

The tests will be conducted on a new JN site: https://alert-hedgehog.jurassic.ninja/wp-admin/

Credentials: https://mc.a8c.com/secret-store/?secret_id=8625

Stripe Account: https://dashboard.stripe.com/connect/accounts/acct_1Ji1DW2EGoaSBhgm

**Comment by tpaksu** [comment]
As Stripe express test accounts seem to directly enable the capabilities, I think I need a live mode account to test the capability statuses. And I think I've found a way to get an US checking account, hope it gets verified. I had a Payoneer account from before, which gave me one US Bank account for the transactions (Actually, I didn't care about it until now) and I used that information to pass the Stripe onboarding flow. Waiting for verification now.

In its current state, any payment methods are shown to the user, even the WooCommerce Payments one isn't active yet. 

## WooCommerce Payments Home Screen:

<img src='https://user-images.githubusercontent.com/3295/136466562-4f161a4c-0593-4b29-83ea-3963bb9e83b2.png' width=600>

## WooCommerce Checkout Page:

<img src='https://user-images.githubusercontent.com/3295/136466475-45599f89-c22b-4b5c-bee0-ff3632d801ec.png' width=300> 

## Stripe Dashboard > Account overview

![image](https://user-images.githubusercontent.com/3295/136466369-37b2ce7f-5fa5-4c5d-8210-cc0642c5f67e.png)

**Comment by tpaksu** [comment]
The capabilities are still `inactive`, so I tried to remove the Sofort cap, and re-request it to see if something changes, but it fell to the `disabled_reason="rejected.other"` state again.

```json
{
  "id": "sofort_payments",
  "object": "capability",
  "account": "acct_1Ji1DW2EGoaSBhgm",
  "future_requirements": {
    "alternatives": [],
    "current_deadline": null,
    "currently_due": [],
    "disabled_reason": null,
    "errors": [],
    "eventually_due": [],
    "past_due": [],
    "pending_verification": []
  },
  "requested": true,
  "requested_at": 1633666629,
  "requirements": {
    "alternatives": [],
    "current_deadline": null,
    "currently_due": [],
    "disabled_reason": "rejected.other",
    "errors": [],
    "eventually_due": [],
    "past_due": [],
    "pending_verification": []
  },
  "status": "inactive"
}
```


I've asked the Stripe channel to check what `rejected.other` state means. p1633646558293100/1632958525.241500-slack-C9976E5MJ

**Comment by tpaksu** [comment]
FYI, #3077 has been created to add checks for handling the inactive states (unrequested, pending, inactive) and taking action for them by @naman03malhotra.
