### ISSUE TITLE
Location caching causes a bug

### ISSUE THREAD

**Issue by kidinov** [Automattic/woocommerce-payments#3072]
### Describe the bug

We cache locations, so when a user removes its location via the Stripe dashboard, we still return the incorrect location id. This location id is discarded by stripe. 

### To Reproduce

Steps to reproduce:

1. Connect to a reader for the first time
2. A new location will be created and a reader will be attached to it
3. Go to the Stripe dashboard and remove a location (you have to remove a reader too)
4. Try to connect to a reader shortly again

### Actual behavior

```
StripeTerminal: Invalid param: register_to_location, found: tml_***, Cannot activate reader because it is registered to a deleted location LocationId: [tml_***]
```

### Expected behavior

We should create a new location

**Comment by kalessil** [comment]
@dmvrtx: can you check if we have webhooks around terminal locations, please?

**Comment by kalessil** [comment]
Ok, should we close this one then, or do we want to reduce the caching time perhaps?

**Comment by kalessil** [comment]
Oh, even so. Got it @kidinov.

**Comment by kidinov** [comment]
Closed because at the moment it's safe to have it's cached. For more info please visit pdfdoF-cc-p2
