### ISSUE TITLE
Improve recurring payments order notes on Indian CCs

### ISSUE THREAD

**Issue by ismaeldcom** [Automattic/woocommerce-payments#3075]
Follow-up issue from #3011.

With the new requirements for 3DS enforcement renewals from cards issued by Indian banks need to attach a mandate. For now, if that mandate is wrong, we attach a generic message with the error Stripe to provide us:

<img width="269" alt="Screenshot 2021-10-07 at 11 11 58" src="https://user-images.githubusercontent.com/7670276/136355550-3beec1b4-ca97-4ba2-a4a1-6888607c05c8.png">

We agree that it would be better to provide something more meaningful. We can use the message from the Stripe plugin that will be added soon https://github.com/woocommerce/woocommerce-gateway-stripe/pull/1981#discussion_r724786025.

To do it, we need to handle the error in the following method:
https://github.com/Automattic/woocommerce-payments/blob/21fbe37a1cc116cfe8ca16923ce20fc1e89e73d9/includes/class-wc-payments-webhook-processing-service.php#L675

**Comment by zmaglica** [comment]
I think that we have enough context to move this issue from the Engineering review queue. Moving this issue from the Engineering review queue is the part of the Gamma backlog porter duty to reduce the number of the issues in the Engineering review column.

**Comment by zmaglica** [comment]
This issue impacts recurring payments, so assigning to Quark (based on team responsibilities Pc2DNy-3z-p2) @diegocurbelo . Assigning as part of Gamma Triage process PcreKM-yM-p2.

Feel free to ping other teams if you think that this issue belongs to a different team.

**Comment by vbelolapotkov** [comment]
@deepakpathania routing this one to you since it relates to order notes in payment processing flow.

**Comment by deepakpathania** [comment]
Since this is related to order notes for recurring payments, might not be the best fit for us. Removing from our board to request re-triage.

**Comment by deepakpathania** [comment]
Added back to our board based on Slack thread.

**Comment by haszari** [comment]
~~Marking as `Triaged` since this is on Gamma board.~~ Actually, leaving as `Triage in progress` as this needs a priority. I think this is low or medium.
