### ISSUE TITLE
UPE: inactive payment methods are being rendered resulting in an error while checkout

### ISSUE THREAD

**Issue by naman03malhotra** [Automattic/woocommerce-payments#3077]
### Describe the bug

Presently we do not apply any filter for `inactive` payment methods for the UPE element, which results in the rendering of all the enabled payment methods irrespective of their status. While checking out it throws an error as stated below

![image](https://user-images.githubusercontent.com/15019298/136574337-e1d3ddd1-3b2a-4274-a3bb-6b2d9de8fcc3.png)

### To Reproduce

You'll need a live account to reproduce this, as all the PMs are enabled by default for the test account.
1. Onboard a merchant
2. Disable a payment method for that account, say `Sofort`.
3. Now add some items to the cart and try checking out with `Sofort`.
4. You should see an error as mentioned above.

### Additional context
Slack threads and P2 links:
- p1633143259258000/1632958525.241500-slack-C9976E5M
- p1633385342439400-slack-C02BHNRN6R1
- pcqRLn-mc-p2

**Comment by tpaksu** [comment]
Another related issue about this topic: #3067

**Comment by laurendavissmith** [comment]
Overall I agree with where you're thinking, lets see if @LevinMedia can chime in on that side of things since "Pending activation" is a tiny bit misleading since technically they are in more of "Stuck" state but in general yeah lets get started while we're waiting for that

**Comment by tpaksu** [comment]
### Today's update:

Found that capability object has separate reasons, missing document and deadline for sending it in properties in capability object.

**Details:** https://stripe.com/docs/api/capabilities/object#capability_object-requirements

Also overall account has the same properties to indicate the same.

**Details:** https://stripe.com/docs/api/accounts/object#account_object-requirements

So, after completing the capabilities verification, it'll be helpful to learn how the main account requirements affect the capability statuses, and add checks for those scenarios too. Asked in p1633979737304400/1632958525.241500-slack-C9976E5MJ.

Started preparing the infra for cap requirement checks on #3093.
