### ISSUE TITLE
Sofort and giropay failure on Pay for order page returns the user to the checkout or cart page

### ISSUE THREAD

**Issue by a-danae** [Automattic/woocommerce-payments#3083]
### Describe the bug

When Sofort or giropay payment fails on the "Pay for order" page, the user gets returned to the checkout page (or the cart one if there aren't products in the cart). As a user, I'd find this confusing.

### To Reproduce

1. Enable UPE and add giropay and Sofort payment methods
2. Add a product to the cart and checkout with a card that fails, like `4000000000000002`
3. Go edit the order in WC, and go to the "Pay for order" page for that order
4. Pay with giropay
5. After you get redirected to Stripe, click on "Fail test payment"
6. Notice you get redirected to the Cart page, instead of the Pay for order one

### Actual behavior

After Giropay or Sofort payment fails on the Pay for order page, the user gets redirected to the Cart page.

### Screenshots

Video of the described behavior https://d.pr/v/X8oKla

### Expected behavior

As a user, I'd expect to go back to the Pay for order page to try again. I'd find it confusing to get returned to the cart page.

### Desktop (please complete the following information):

* OS: macOS
* Browser: chrome
* Version: 94.0.4606.61

### Additional context

This might be the expected behavior or a technical limitation. I haven't dug there.

**Comment by htdat** [comment]
@a-danae The following is what I am seeing after a failed payment. IMO, it looks reasonable as: 

1, The order info is still there. 
2, I can try to pay again if I want. 

Can you check and see if it's still an issue with the `develop` branch?

![Markup on 2021-11-02 at 15:17:19](https://user-images.githubusercontent.com/10045087/139810126-83e51fb4-2e98-4e98-9f45-f5db995befe3.png)


Here is my screen recording: https://user-images.githubusercontent.com/10045087/139809974-3b197ce4-c948-46cd-b8f5-5c4cf3036a43.mp4

**Comment by a-danae** [comment]
I'm not getting the behavior I described on the issue anymore 🙂  I'm getting what you describe instead, which looks fine to me as well.

I'm closing this. Thanks for checking the issue out @htdat!

**Comment by htdat** [comment]
> I'm not getting the behavior I described on the issue anymore 

Thanks for your confirmation, @a-danae! It's probably that the issue has been fixed.
