### ISSUE TITLE
Investigate potential impacts to WCPay Subscriptions if a store disables/deletes WC Payments or switches off the feature

### ISSUE THREAD

**Issue by james-allan** [Automattic/woocommerce-payments#3117]
Because subscriptions functionality is hidden behind a feature flag and eventually via an advanced setting https://github.com/Automattic/woocommerce-payments/issues/3064, i's possible that Subscriptions functionality can be switched off with any explanation or warning. 

We will need to investigate: 

- Possible ways WC Payments could be disabled.
     - The plugin is disabled.
     - The payment method is disabled. 
     - The account disconnected.
- Possible ways WC Subscriptions core wouldn't be loaded effectively disabling subscriptions functionality
    - Via the advanced setting #3064

In those scenarios:
- **what impact does it have on existing Subscriptions and subscription products?**
- **What is the best way to communicate that to the merchant?**

**Comment by haszari** [comment]
Sized this as small for now. As I understand it, this requires some testing to confirm behaviour and then maybe some documentation changes.
