### ISSUE TITLE
Use the PaymentIntent ID in the Transaction Details URL instead of the Charge ID

### ISSUE THREAD

**Issue by a-danae** [Automattic/woocommerce-payments#3122]
### Description

This issue is created for [this comment](https://github.com/Automattic/woocommerce-payments/issues/540#issuecomment-607588704) on #540 

Right now, URLs for Transaction Detail screens use the charge ID (e.g. `admin.php?page=wc-admin&path=%2Fpayments%2Ftransactions%2Fdetails&id=ch_xxxx`). [This PR](https://github.com/Automattic/woocommerce-payments/pull/2937) replaces the Charge ID at the top of the card with the Payment Intent ID. So, it makes sense that the Payment Intent ID should be used in the URL too.

### Acceptance criteria

* The Transaction Details page must have the Payment Intent `pi_xxx` in the URL instead of the Charge ID `ch_xxx`
* Accessing the Transaction Details page using the Charge ID `ch_xxx` should redirect to the URL using the Payment Intent ID `pi_xxx`
* The plugin's links pointing to the Transaction Details page should use the Payment Intent
* Of course, everything should continue to load and work fine after the switch

### Testing instructions

1. Go to the Transactions page
2. Click on a transaction to go to its Transactions Details page
3. The URL should have the Payment Intent ID `pi_xxx` instead of the Charge ID `ch_xxx`

There are other scenarios to test. To be added.

### Dev notes

Extracted from the original issue:
* Related #353
* When updating the URL we should also update the gateways get_transaction_url method as added in [this PR](https://github.com/Automattic/woocommerce-payments/pull/837)

### Additional context

Quoting Brent's comment:

> Of note, in the Stripe dashboard:
> 
> * The Connect Accounts dashboard uses a Charge ID under the Payments tab, e.g. https://d.pr/i/pZRNRM
> * Clicking one of those rows takes you to a URL for the account with the Charge ID, e.g. `https://dashboard.stripe.com/acct_xxxx/test/payments/ch_xxxx`
> * Stripe redirects that URL to a URL using the Payment Intent ID, e.g. `https://dashboard.stripe.com/acct_xxxx/test/payments/pi_xxxx`
> * The dashboard for an individual account display's Payment Intent IDs under the Payments section e.g. https://d.pr/i/lU3PxC

Also, we should add a redirect for backward compatibility. When going to the Transaction Details URL using the Charge ID `ch_xxx`, the user should be redirected to the URL using the PaymentIntent URL `pi_xxx`.

That's an old issue, but I've confirmed with the team in slack p1631830055418100-slack-CGGCLBN58 that we still want to do this move.

**Comment by EduardoUmpierre** [comment]
Reopening the issue as it still has some work left.

The issue was broken into 3 different PRs:
- [x] Update `WC_Payments_API_Intention` to receive a `WC_Payments_API_Charge` instance on constructor
#4336

- [x] Redirect charge id requests to the payment intent id equivalent
#4348 

- [ ] Update links to point to the payment intent id instead of using the charge id
