### ISSUE TITLE
Pay for order page error when Early Access payment methods are enabled

### ISSUE THREAD

**Issue by nicdwilson** [Automattic/woocommerce-payments#3136]
### Describe the bug

An order paid for on the "pay for order" page errors when the gateway has early access enabled

### To Reproduce

With Early Access payment methods enabled for cred cards / debit cards

<img width="1164" alt="Markup 2021-10-18 at 15 27 41" src="https://user-images.githubusercontent.com/3624025/137660284-7fdc0bd7-1823-417d-bb87-be03e2ce6c03.png">

Create a new order in pending payment status, use the pay for order link to pay for the order.

### Actual behavior

The following error occurs, and payment cannot be made:

`Unhandled Promise Rejection: IntegrationsError: stripe.ConfirmPayment(); The confirmParams.return_url argument is required unless passing 'redirect: if_required'`

### Screenshots

<img width="1275" alt="Markup 2021-10-09 at 21 38 55" src="https://user-images.githubusercontent.com/3624025/137660340-95c18bd5-53ef-46ae-a554-4d63bdab54ac.png">

### Expected behavior

The payment should go through.

### Desktop (please complete the following information):

* OS: macOS
* Browser Firefox/Chrome
* Version 94/94

### Additional context

Could not replicate in test mode

4364438-zen
[Forum post](https://wordpress.org/support/topic/woocommerce-payments-checkout-with-credit-card-return_url-error/)

**Comment by malithsen** [comment]
Hi @nicdwilson I was not able to reproduce this error, would you be able to verify whether this still exists. https://github.com/Automattic/woocommerce-payments/pull/3229 that went out with 3.2.0 addressed the UPE error in the screenshot above

**Comment by RadoslavGeorgiev** [comment]
Yes, #3229 was opened in the context of the _Add Payment Method_ page, but touched on a couple of other places where the issue was happening, including _Pay for Order_, which this issue is about.

I think it is safe to close this issue, but I'll let @nicdwilson take a look first.

**Comment by nicdwilson** [comment]
Yup, I think events have overtaken this one
