### ISSUE TITLE
Wrong international fees applied using testing cards

### ISSUE THREAD

**Issue by ismaeldcom** [Automattic/woocommerce-payments#3160]
After merging #2979 UPE purchases using testing cards will apply international fees incorrectly, because Stripe testing cards don't return the appropriate country.

This can lead to some confusion while developing other features, as @shendy-a8c @aprea noticed when testing WCPay Subscriptions with UPE (see issue 1244-gh-Automattic/woocommerce-payments-server and p1634729477083800-slack-CGGCLBN58). So we should do something to prevent this to happen on local while using testing cards.

**Comment by shendy-a8c** [comment]
Also, something I just realized, why the 1% international fee isn't showing under the fee breakdown on the transaction details page. It's inconsistent that the fee is applied but not displayed. Not sure if it's only specific for testing card or not.

To whoever will work on this issue, please also investigate that problem as well, or if it should be a separate issue, let me know.
