### ISSUE TITLE
Can't resume subscription

### ISSUE THREAD

**Issue by leonardola** [Automattic/woocommerce-payments#3169]
### Describe the bug
After Suspending a subscription it can no longer be resumed

### To Reproduce

- Navigate to WooCommerce -> Subscriptions.
- Hover an active subscription and click the “Suspend” button.
- Ensure the subscription status has transitioned to “On hold”.
- Hover over the suspended subscription and click the “Reactivate” button.
- Navigate to WCPay Dev and copy the Stripe Connect account ID to your clipboard.
- Navigate to https://dashboard.stripe.com/
- Ensure you’re viewing the WCPay Dev account in test mode.
- Navigate to your Connect account by searching for the account ID obtained above.
- Navigate to Subscriptions.
- The subscription status is still “Paused”

### Expected behavior
After resuming the subscription it should not show as paused on Stripe Panel

**Comment by james-allan** [comment]
Fixed via 1260-gh-Automattic/woocommerce-payments-server
