### ISSUE TITLE
Automattic\Jetpack\Connection\Manager::is_registered is deprecated since version 1.12.1

### ISSUE THREAD

**Issue by shendy-a8c** [Automattic/woocommerce-payments#3178]
### Describe the bug

When trying to connect to Stripe account (Admin > Payments > Finish Setup), a warning message shows up:
```
Deprecated: Automattic\Jetpack\Connection\Manager::is_registered is deprecated since version 1.12.1 with no alternative available. in <www path>/wp-includes/functions.php on line 5222
```

I added a call to `debug_print_backtrace()` and found out the error is triggered by `is_registered()` call from [this line](https://github.com/Automattic/woocommerce-payments/blob/develop/includes/wc-payment-api/class-wc-payments-http.php#L170).

### To Reproduce

The warning might be reproduced by other steps but this is what I did when I saw the warning:
1. Start a clean JN site.
2. Install WCPay Dev Tool. Do not do anything with its default settings, so `Proxy WPCOM requests` option will still be enabled.
3. Install WCPay (I installed a snapshot from `develop` branch when I write this issue).
4. Try to connect to a Stripe account by clicking Admin > Payments > Finish Setup. It won't work because it will try to proxy to an unknown host:
```
There was a problem connecting this site to WordPress.com: "cURL error 6: Could not resolve host: host.docker.internal"
```

### Actual behavior

Notice at around the top, there is a warning:
```
Deprecated: Automattic\Jetpack\Connection\Manager::is_registered is deprecated since version 1.12.1 with no alternative available. in <www path>/wp-includes/functions.php on line 5222
```

### Screenshots

<img width="754" alt="Screen Shot 2021-10-21 at 14 42 15" src="https://user-images.githubusercontent.com/73803630/138225140-ae8c9f4e-d984-4f57-ad3c-b6f7a9fe3349.png">

### Expected behavior

No warning.

**Comment by htdat** [comment]
Have been fixed in https://github.com/Automattic/woocommerce-payments/pull/3340/files#diff-e68adedfe5f98b3d651bbefe89c927bce526a97722cc0984c453167e422e0173R170

I also checked in the current codebase and there is no other usage of `Automattic\Jetpack\Connection\Manager::is_registered`.

Closing this issue.
