### ISSUE TITLE
After disabling Subscriptions in "Advanced Settings", menu item is still visible

### ISSUE THREAD

**Issue by jorgeatorres** [Automattic/woocommerce-payments#3183]
### Describe the bug

When Subscriptions is disabled in "Advanced Settings", and because the changes are saved via AJAX, the "Subscriptions" menu item is still visible. Clicking it results in an error.

### To Reproduce

1. Go to Payments > Settings.
2. Scroll to the bottom of the page and click "Advanced Settings" to expand the panel.
3. Uncheck "Enable Subscriptions with WooCommerce Payments".
4. Click "Save Changes".
4. Confirm that menu item "Subscriptions" appears inside the WooCommerce menu.
5. Click the menu item above and see an error.

### Actual behavior

Clicking the menu item results in an error, because Subscriptions support is now disabled.

### Screenshots

Screencast:

![screencast1](https://user-images.githubusercontent.com/184724/138255140-1332884a-1176-4ded-a15b-114fa45bf0b6.gif)

### Expected behavior

Disabling Subscriptions should either manually hide the menu item or trigger a page refresh so that the item is no longer visible.

### Desktop (please complete the following information):

* OS: macOS 11.6
* Browser: Firefox
* Version: 93.0

**Comment by haszari** [comment]
I'm thinking we can close this – it's very low impact, and the checkbox to disable the feature may not stay around forever. 

Feel free to reopen if we get customer reports or if there's something I've missed 🙂
