### ISSUE TITLE
Multi-Currency compatibility with WooCommerce Shipping and Tax extension

### ISSUE THREAD

**Issue by jessepearson** [Automattic/woocommerce-payments#3191]
Tested WooCommerce Shipping and Tax with Multi-Currency:
* Legacy shipping rates in cart/checkout convert correctly
* Taxes convert correctly
* Amounts show in order correctly
* When creating a shipping label:
  * The amount the customer paid is in USD, not the currency of the order.
  * The amount the merchant will need to pay for the label is in USD, as it should be, but not explicit format. Meaning USD is not shown after the amount. 

The amount the customer has paid is hardcoded to USD here:
https://github.com/Automattic/woocommerce-services/blob/1.25.19/client/extensions/woocommerce/woocommerce-services/views/shipping-label/label-purchase-modal/rates-step/index.js#L120

The amount the merchant needs to pay is also hardcoded to USD, which is fine since it should always be USD, however, it is not in explicit format.
https://github.com/Automattic/woocommerce-services/blob/1.25.19/client/extensions/woocommerce/woocommerce-services/views/shipping-label/label-purchase-modal/rates-step/shipping-rate.js#L160

It appears it is possible to pass additional values to the `formatCurrency` function that is used for both instances to allow for explicit formatting in different currencies. 
https://github.com/Automattic/wp-calypso/blob/trunk/packages/format-currency/src/index.js#L7-L38

I don't believe there's anything we can do in MC to allow for this to happen, the changes would need to happen in WC Shipping and Tax in order to facilitate the change. Something like a check of the order currency to see if it matches the store currency, then change how the currencies are displayed based on the result should solve the issue. 

![Markup 2021-10-22 at 09 01 32](https://user-images.githubusercontent.com/4634416/138450314-55c69d0a-809e-485c-9d09-17a009966cec.png)

**Comment by deepakpathania** [comment]
@jessepearson Triaging currently open issues, so just wanted to confirm if we can close this issue in favor of the one you created in the `woocomerce-services` repo?

**Comment by jessepearson** [comment]
@deepakpathania We still need to keep this open on our end for tracking purposes 😀

**Comment by jessepearson** [comment]
This has been resolved in https://github.com/Automattic/woocommerce-services/pull/2496
Removed estimate for this since Sigma wasn't responsible for the fix.
