### ISSUE TITLE
Calculate charge status on the server

### ISSUE THREAD

**Issue by luizreis** [Automattic/woocommerce-payments#320]
The client application has some code to calculate charge status ([link](https://github.com/Automattic/woocommerce-payments/blob/3a958f7c4e7399b7acde0700612bb3a1fa389fbe/client/utils/charge/index.ts#L51-L51)). 

We should consider having this logic on the server (see #300 for more details).

**Comment by vbelolapotkov** [comment]
Sending for engineering review to get better understanding of the pros and cons from such move.

**Comment by jrodger** [comment]
Moving this logic to the server would be a valid thing to do, however, I'm going to close this issue until we have a concrete use case for it.

Please feel free to reopen if something comes up in the future (or if there's an existing requirement that I've missed).
