### ISSUE TITLE
WCPay Plugin Could Mention Mobile Payments

### ISSUE THREAD

**Issue by allendav** [Automattic/woocommerce-payments#3202]
Both in wp-admin

<img width="1173" alt="Screen Shot 2021-10-25 at 6 14 11 AM" src="https://user-images.githubusercontent.com/1595739/138702292-fadbbbd7-8ebf-4f3e-a0b4-ab2be0168dfa.png">

and on wordpress.org:

<img width="830" alt="Screen Shot 2021-10-25 at 6 14 20 AM" src="https://user-images.githubusercontent.com/1595739/138702319-d4a0778f-ba2b-42b6-a034-dc75b966b75d.png">

**Comment by vbelolapotkov** [comment]
There is an internal discussion without decision yet: pdfdoF-dB-p2
Marking as "needs feedback" to update the issue once there is agreement on way forward.

**Comment by jessy-p** [comment]
Any updates on the discussion pdfdoF-dB-p2 @bmccotter

**Comment by bmccotter** [comment]
This is the first I've heard or seen this @jessy-p. @vbelolapotkov can you help me wrangle please?

**Comment by vbelolapotkov** [comment]
@bmccotter you replied on the p2 that we won't do this due to limited availability of in-person payments across the countries. I've sent the link to you in slack. Closing this for now.
