### ISSUE TITLE
[IPP] Incomplete transaction data in listing

### ISSUE THREAD

**Issue by kalessil** [Automattic/woocommerce-payments#3228]
In `\WCPay\Payment_Methods\UPE_Payment_Gateway::process_payment` we extending intentions with meta-data:` -> $updated_payment_intent  = $this->payments_api_client->update_intention( ..., $this->get_metadata_from_order( $order, $payment_type ), ... )`

Investigate `\WC_REST_Payments_Orders_Controller::capture_terminal_payment` - it should supply the meta-data in the same way.

If not: the meta-data injection needs to be implemented (after merge ask in https://github.com/woocommerce/woocommerce-ios/issues/4282 to close it).
If the meta-data is supplied, investigate why transactions from https://github.com/woocommerce/woocommerce-ios/issues/4077 have empty values

**Comment by anu-rock** [comment]
@kalessil As per https://github.com/woocommerce/woocommerce-ios/issues/4077, all required metadata except `order_key` is now successfully captured on a payment intent by the mobile app itself. I'm assuming `order_key` is not available in mobile and, thus, needs to be captured in WCPay Client. I can confirm that at present no metadata is being set for an in-person payment in Client.

This is different from the behavior in `UPE_Payment_Gateway::process_payment`, where ALL metadata is being captured in WCPay Client. I guess this is because UPE is a fully web-driven payment flow where there's no mobile app to supply Stripe metadata on WCPay's behalf.

If my understanding is correct, we'll probably need to call `WC_Payments_API_Client::update_intention` to set `order_key` before capturing the charge.

But do we want to do it? As per @allendav's [comment](https://github.com/woocommerce/woocommerce-ios/issues/4282#issuecomment-952035448):

> Let's double check this is still needed by Transact. I think order key is only needed for fraud scoring which far less of a concern for in-person payments than web payments.

**Comment by allendav** [comment]
Thanks for looking into this @anu-rock

> But do we want to do it? As per @allendav's comment:

>> Let's double check this is still needed by Transact. I think order key is only needed for fraud scoring which far less of a concern for in-person payments than web payments.

Whether we should have the plugin add order key to the intent is up to y'all and @bmccotter @astralbodies @ctarda - to my knowledge it can't affect the mobile app / in-person payments and fraud is much less likely, but that's more a business decision than an engineering one fwict.

See also https://github.com/woocommerce/woocommerce-ios/issues/4282 - if the mobile app can get out of supplying any of the metadata that would also be a positive outcome - i.e. DRY it up so metadata is ONLY supplied by the plugin. Then we would have one fewer place to fix things.

**Comment by anu-rock** [comment]
> See also woocommerce/woocommerce-ios#4282 - if the mobile app can get out of supplying any of the metadata that would also be a positive outcome - i.e. DRY it up so metadata is ONLY supplied by the plugin. Then we would have one fewer place to fix things.

That's very much doable in Client. We have a method just for that:

https://github.com/Automattic/woocommerce-payments/blob/8b72b2497d800c28f4f7ed5f880bb95dd852a6a5/includes/class-wc-payment-gateway-wcpay.php#L1157-L1182

It also makes sense to have only one source of truth for all metadata. I will start working on it soon then. But that's require undoing the metadata changes in mobile app, right?

cc @allendav @kalessil @dmvrtx

**Comment by dmvrtx** [comment]
Thanks for looking into this @anu-rock. I agree with the suggestion, let's re-use what we have to pre-process orders coming from mobile endpoints.

**Comment by allendav** [comment]
> But that's require undoing the metadata changes in mobile app, right?

It does, and ensuring that older versions of the app that supply metadata don't suffer adverse consequences.

If @ctarda is OK with it, we'll need to open issues for iOS and Android to stop populating this metadata in the mobile apps.

**Comment by kalessil** [comment]
@anu-rock: `But that's require undoing the metadata changes in mobile app, right?`, can you elaborate please why? It looks like changes on client side are only required.

**Comment by anu-rock** [comment]
@kalessil Moving the metadata setting responsibility from mobile app to plugin will:

1. Make plugin the single source of truth for metadata (mobile app cannot set `order_key`, so it'll need to be supplied by the plugin anyway).
2. Make the mobile app code [DRY](https://github.com/Automattic/woocommerce-payments/issues/3228#issuecomment-956257847).

**Comment by kalessil** [comment]
@anu-rock: thanks for clarifying!

**Comment by anu-rock** [comment]
@ctarda, @allendav I'm not sure if you received a notification for this issue's closure. Apologies for not pinging you in time, but now you know :)

**Comment by ctarda** [comment]
Thanks @anu-rock !
