### ISSUE TITLE
Fees: Update how fees per payment method are displayed on the overview page

### ISSUE THREAD

**Issue by RadoslavGeorgiev** [Automattic/woocommerce-payments#3241]
We've got plenty of payment methods available through UPE (7 and counting), most of which have different fee structures. Their fees need to be displayed on the Overview page of the plugin, as initially noted in https://github.com/Automattic/woocommerce-payments/issues/2377.

PR https://github.com/Automattic/woocommerce-payments/pull/3055 addressed this issue based on [these Figma designs](35wcSfexs3z8pxrj4daJnH-fi-0%3A1). However, before releasing `3.2.0` we realized that there's a bug, and even if the bug were fixed, the results are not ideal.

## Initial bug 

h/t @htdat for discovering this and suggesting a [fix for it](https://github.com/Automattic/woocommerce-payments/pull/3239):

![Markup on 2021-10-28 at 10_22_28](https://user-images.githubusercontent.com/5311119/139212125-e86ee727-8c29-48fc-8d85-eb6a623b5a15.png)

The fix included:

- Making sure that fees are displayed even when there are no discounts.
- Adding translations for all available payment methods.
- Fixing a small conditional logic issue.

## After the fix

![Screenshot 2021-10-28 at 8 54 14](https://user-images.githubusercontent.com/5311119/139212577-a2814b88-7f26-4016-a059-483d65882b8b.png)

- All PMs are displayed: This includes payment methods, which are not added to the particular store. h/t @aprea for noticing this. I did not, because I had already enabled all payment methods.
- With multiple payment methods, and without discounts, it looks like someone copy-pasted the data from Notepad 😆 
- There are repeating `Learn more` links, which point to the same page. Seems like we might want to add a top-level link to the page with all fees, and then only display `Learn more` whenever there is a promotion.

**Comment by dpaun1985** [comment]
this item is blocked by #3300
