### ISSUE TITLE
Fatal error when Wcpay is active but Woo core is not

### ISSUE THREAD

**Issue by shendy-a8c** [Automattic/woocommerce-payments#3265]
### Describe the bug

When wcpay is active but woo core isn't an uncaught fatal error is thrown. Likely it's caused by the use of `Automattic\WooCommerce\Admin\PluginsHelper::is_plugin_active()` assuming `Automattic\WooCommerce\Admin\PluginsHelper` is defined.

A simple fix would be to check if `Automattic\WooCommerce\Admin\PluginsHelper` exists or if Woo core / admin is installed.

### To Reproduce

1. Install WooCommerce
2. Install WooCommerce Payments
3. Deactivate WooCommerce

### Actual behavior

An uncaught fatal error is thrown. Something like:
```
Fatal error: Uncaught Error: Class 'Automattic\WooCommerce\Admin\PluginsHelper' not found in {plugins path}/woocommerce-payments/woocommerce-payments.php:131
...
```

### Expected behavior

There shouldn't be a fatal error.

Note that there is already an existing warning when WooCommerce is not active:
```
WooCommerce Payments

WooCommerce Payments requires WooCommerce to be installed and active. Activate WooCommerce
```

### Additional context

Thanks, @htdat, for catching this bug. Thread: p1635759035320500-slack-CGGCLBN58.
He also mentioned there is [a PR](https://github.com/Automattic/woocommerce-payments/pull/3130) to refactor `WC_Payments::check_plugin_dependencies` which might be related to this issue.

**Comment by nicdwilson** [comment]
23481569-hc AT site

**Comment by haszari** [comment]
This is unlikely to affect many stores in practice, but we should tidy this up.

**Comment by WillBrubaker** [comment]
4427961-zen experiencing this as well.
