### ISSUE TITLE
[GlobalStep] "400 Bad Request" error triggers at Query Monitor after placing the order when using new credit card.

### ISSUE THREAD

**Issue by gglobalstep** [Automattic/woocommerce-payments#3273]
# Bug Description:
"400 Bad Request" error triggers at Query Monitor after placing the order when using new credit card.

# Environment:
Woocommerce Version : WooCommerce 5.8.0 
WooCommerce Payments 3.3.0-test-1
WordPress version: v5.8.1

PC:
Windows 10, Mac 10.14.6
Chrome(Version 95.0.4638.69) 
Firefox(Version 93.0)
Safari: v14.1.2

# Steps To Reproduce:
1. Create any test site using JN site.
1. Install and activate all the required plugins.
1. Upload and activate the WooCommerce Payments v3.3.0-test-1 plugin. 
1. Complete the setup wizard.
1. Go to Store page and add "subscription product" to the cart.
1. Complete the checkout using credit card.
1. Again go to Store page and "subscription product" product to the cart.
1. Go to checkout page.
1. This time click "use new payment method" and add new credit card.
1. And click on "Sign Up"
1. Observe that "400 Bad Request" error triggers at Query Monitor after placing the order when using new credit card.

# Actual Result:
"400 Bad Request" error triggers at Query Monitor after placing the order when using new credit card.

# Expected Result:
User should be able to complete checkout without any error.

# Screenshot

![#3273](https://user-images.githubusercontent.com/41110392/139879868-6b87e0a0-b8e2-489a-a8cd-0515dc98c932.jpg)

*Isolating the problem (mark completed items with an [x]):*
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

<details>
`
### WordPress Environment ###

WC Version: 5.8.0
REST API Version: ✔ 5.8.0
WC Blocks Version: ✔ 5.9.1
Action Scheduler Version: ✔ 3.3.0
WC Admin Version: ✔ 2.7.2
Log Directory Writable: ✔
WP Version: 5.8.1
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache/2.4.51 (Unix) OpenSSL/1.0.2g
PHP Version: 7.4.25
PHP Post Max Size: 1 GB
PHP Time Limit: 30
PHP Max Input Vars: 5000
cURL Version: 7.47.0
OpenSSL/1.0.2g

SUHOSIN Installed: –
MySQL Version: 5.7.33-0ubuntu0.16.04.1-log
Max Upload Size: 512 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 5.8.0
WC Database Prefix: wp_
Total Database Size: 7.09MB
Database Data Size: 5.15MB
Database Index Size: 1.94MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 0.09MB + Index: 0.09MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 0.11MB + Index: 0.13MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 0.09MB + Index: 0.03MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 0.08MB + Index: 0.09MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_options: Data: 3.47MB + Index: 0.06MB + Engine InnoDB
wp_postmeta: Data: 0.45MB + Index: 0.48MB + Engine InnoDB
wp_posts: Data: 0.09MB + Index: 0.06MB + Engine InnoDB
wp_snippets: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.05MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB

### Post Type Counts ###

attachment: 35
page: 7
post: 2
product: 36
product_variation: 7
revision: 2
shop_coupon: 3
shop_order: 42
shop_order_refund: 1
shop_subscription: 37

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (6) ###

Query Monitor: by John Blackbourn – 3.7.1
Code Snippets: by Code Snippets Pro – 2.14.2
Companion Plugin: by Osk – 1.18
WooCommerce Payments Dev Tools: by Automattic –
WooCommerce Payments: by Automattic – 3.3.0-test-1
WooCommerce: by Automattic – 5.8.0

### Inactive Plugins (3) ###

Akismet Anti-Spam: by Automattic – 4.1.12
Hello Dolly: by Matt Mullenweg – 1.7.2
WooCommerce Subscriptions: by WooCommerce – 3.1.6

### Dropin Plugins (1) ###

db.php: Query Monitor Database Class

### Settings ###

API Enabled: –
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
subscription (subscription)
variable (variable)
variable subscription (variable-subscription)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –

### WC Pages ###

Shop base: #6 - /shop/
Cart: #7 - /cart/
Checkout: #8 - /checkout/
My account: #9 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Storefront
Version: 3.9.1
Author URL: https://woocommerce.com/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Subscriptions ###

WCS_DEBUG: ✔ No
Subscriptions Mode: ✔ Live
Subscriptions Live URL: https://magellanic-koi.jurassic.ninja
Subscription Statuses: wc-active: 34
wc-pending: 2
wc-cancelled: 1

WooCommerce Account Connected: ❌ No

### Store Setup ###

Country / State: United States (US) — California

### Subscriptions by Payment Gateway ###

WooCommerce Payments: wc-active: 34
wc-cancelled: 1
wc-pending: 2

### Payment Gateway Support ###

WooCommerce Payments: products
refunds
subscriptions
subscription_cancellation
subscription_suspension
subscription_reactivation
subscription_amount_changes
subscription_date_changes
subscription_payment_method_change
subscription_payment_method_change_customer
subscription_payment_method_change_admin
multiple_subscriptions
tokenization
add_payment_method

### Action Scheduler ###

Complete: 267
Oldest: 2021-11-02 10:47:07 +0000
Newest: 2021-11-02 15:33:43 +0000

Pending: 39
Oldest: 2021-11-02 16:57:32 +0000
Newest: 2021-12-02 14:21:40 +0000

### Status report information ###

Generated at: 2021-11-02 15:36:53 +00:00

</details>

**Comment by jrodger** [comment]
Associated order notes:

![image](https://user-images.githubusercontent.com/686419/140052871-08a60de4-37aa-4eee-9b2e-1789d88d79ff.png)

Possible that the payment completed quicker than our code could make it's first attempt at processing it synchronously?

**Comment by james-allan** [comment]
I wasn't able to replicate this on my local site, however, I could on the JN site. Looking at the order notes, it looks like the issue is caused by two paid status transitions. `'Pending -> Processing'` x 2 notes. 

We can patch the 400 bad request and `Error during status transition. Error: Invoice is already paid` issue by making sure we don't try to pay the first invoice twice. However, we will want to find what is causing the double status transition and fix that too.

**Comment by james-allan** [comment]
> I wasn't able to replicate this on my local site

nvm I was able to replicate once I realised webhook listening had stopped.

> However, we will want to find what is causing the double status transition and fix that too.

I believe you're right with your theory @jrodger. I think there's a race condition with the order eventually getting being paid during the client request, and midstream the site receives the `payment_intent.succeeded` webhook.

**Comment by james-allan** [comment]
I've confirmed the race condition. There are two stack traces that lead to the order status changing from pending to processing. 

**Via the `payment_intent.succeeded` webhook.**

```
#0 wp-content/plugins/woocommerce/includes/class-wc-order.php(222): WC_Order->status_transition()
#1 wp-content/plugins/woocommerce/includes/class-wc-order.php(120): WC_Order->save()
#2 wp-content/plugins/woocommerce-payments/includes/admin/class-wc-rest-payments-webhook-controller.php(291): WC_Order->payment_complete()
#3 wp-content/plugins/woocommerce-payments/includes/admin/class-wc-rest-payments-webhook-controller.php(131): WC_REST_Payments_Webhook_Controller->process_webhook_payment_intent_succeeded(Array)
#4 wp-includes/rest-api/class-wp-rest-server.php(1140): WC_REST_Payments_Webhook_Controller->handle_webhook(Object(WP_REST_Request))
#5 wp-includes/rest-api/class-wp-rest-server.php(987): WP_REST_Server->respond_to_request(Object(WP_REST_Request), '/wc/v3/payments...', Array, NULL)
#6 wp-includes/rest-api/class-wp-rest-server.php(414): WP_REST_Server->dispatch(Object(WP_REST_Request))
#7 wp-includes/rest-api.php(370): WP_REST_Server->serve_request('/wc/v3/payments...')
#8 wp-includes/class-wp-hook.php(303): rest_api_loaded(Object(WP))
#9 wp-includes/class-wp-hook.php(327): WP_Hook->apply_filters(NULL, Array)
#10 wp-includes/plugin.php(518): WP_Hook->do_action(Array)
#11 wp-includes/class-wp.php(388): do_action_ref_array('parse_request', Array)
#12 wp-includes/class-wp.php(750): WP->parse_request('')
#13 wp-includes/functions.php(1291): WP->main('')
#14 wp-blog-header.php(16): wp()
#15 index.php(17): require('/Users/jamesall...')
#16 {main}
```

**via the order received page**

```
#0 wp-content/plugins/woocommerce/includes/class-wc-order.php(222): WC_Order->status_transition()
#1 wp-content/plugins/woocommerce/includes/class-wc-order.php(120): WC_Order->save()
#2 wp-content/plugins/woocommerce-payments/includes/class-wc-payment-gateway-wcpay.php(1258): WC_Order->payment_complete('pi_3Jrvbj2HTmZd...')
#3 wp-content/plugins/woocommerce-payments/includes/payment-methods/class-upe-payment-gateway.php(532): WC_Payment_Gateway_WCPay->attach_intent_info_to_order(Object(Automattic\WooCommerce\Admin\Overrides\Order), 'pi_3Jrvbj2HTmZd...', 'succeeded', 'pm_1Jrvc12HTmZd...', 'cus_K5gxHfic0fw...', 'ch_3Jrvbj2HTmZd...', 'USD')
#4 wp-content/plugins/woocommerce-payments/includes/payment-methods/class-upe-payment-gateway.php(455): WCPay\Payment_Methods\UPE_Payment_Gateway->process_redirect_payment('1976', 'pi_3Jrvbj2HTmZd...', true)
#5 wp-includes/class-wp-hook.php(303): WCPay\Payment_Methods\UPE_Payment_Gateway->maybe_process_upe_redirect(Object(WP))
#6 wp-includes/class-wp-hook.php(327): WP_Hook->apply_filters(NULL, Array)
#7 wp-includes/plugin.php(518): WP_Hook->do_action(Array)
#8 wp-includes/class-wp.php(763): do_action_ref_array('wp', Array)
#9 wp-includes/functions.php(1291): WP->main('')
#10 wp-blog-header.php(16): wp()
#11 index.php(17): require('/Users/jamesall...')
#12 {main}

```

Both functions run simultaneously. ie Both requests get their own instance of the order while it still has a pending status and then both call payment complete on their respective instances.

**Comment by jrodger** [comment]
Thanks for investigating @james-allan!
