### ISSUE TITLE
E2e tests related to the WooCommerce blocks checkout fail

### ISSUE THREAD

**Issue by a-danae** [Automattic/woocommerce-payments#3274]
### Describe the bug

The e2e tests related to the WooCommerce blocks checkout fail with `Timeout - Async callback was not invoked within the 100000ms timeout specified by jest.setTimeout.Error: Timeout - Async callback was not invoked within the 100000ms timeout specified by jest.setTimeout.`

### To Reproduce

1. Checkout the 'develop' branch
2. Run `npm run test:e2e ./tests/e2e/specs/shopper/shopper-wc-blocks-checkout-failures.spec.js` or `npm run test:e2e ./tests/e2e/specs/shopper/shopper-wc-blocks-checkout-purchase.spec.js`
3.  Notice all of the e2e tests fail with `Timeout - Async callback was not invoked within the 100000ms timeout specified by jest.setTimeout.Error: Timeout - Async callback was not invoked within the 100000ms timeout specified by jest.setTimeout.`

### Actual behavior
All of the WCB checkout-related tests fail with the same error.

### Expected behavior
The tests shouldn't fail so consistently.

### Additional context

Looks like this is related to us trying to fill the shipping fields instead of the billing fields, and WCB not having a default value for the state field, and the checkout process not being able to continue because this required field is missing.

**Comment by htdat** [comment]
Thanks for the report @a-danae! 

@achyuthajoy and @deepakpathania - can you have a look and see if this fits into your current work in this epic https://github.com/Automattic/woocommerce-payments/issues/3289?

**Comment by achyuthajoy** [comment]
Sure @htdat We'll take a look

**Comment by a-danae** [comment]
My pleasure!

I requested Veljkho to review the PR but please feel free to grab it, or to close it if you're on it already.
