### ISSUE TITLE
Creating a WCPay Subscription for free subscriptions

### ISSUE THREAD

**Issue by james-allan** [Automattic/woocommerce-payments#3279]
### Describe the bug

We're currently creating subscriptions for all subscriptions created on checkout using the `woocommerce_checkout_subscription_created` hook. This means that we're also creating subscriptions for free subscriptions which don't require any payment method. 

### To Reproduce

1. Disable shipping or have a free shipping method available.
1. Create a free subscription product. 
2. Add the free product to your cart.
4. Notice on checkout that no payment method fields are displayed. 
5. Complete the checkout
6. Go to your Stripe connect account dashboard and notice that the free subscription has been created there. (see screenshots below). 

### Actual behavior

We're creating WCPay Subscriptions for all subscriptions created on checkout.

### Screenshots

<img width="1437" alt="Screen Shot 2021-11-03 at 9 53 43 am" src="https://user-images.githubusercontent.com/8490476/139967390-aebec5c1-93eb-4f5f-84e4-38c5252f1d15.png">

<img width="1426" alt="Screen Shot 2021-11-03 at 9 55 53 am" src="https://user-images.githubusercontent.com/8490476/139967540-df6848cf-0487-49fc-9f11-13578467e4b3.png">

<img width="703" alt="Screen Shot 2021-11-03 at 9 55 58 am" src="https://user-images.githubusercontent.com/8490476/139967557-86b7dbdb-f0cb-4ffb-8602-40f93e98e3fb.png">

### Expected behavior

WC Subscriptions core determines if the subscription needs a payment method on the checkout using the `WC_Subscriptions_Cart::cart_needs_payment()` function. It's somewhat complicated, however, it can be boiled down to whether the subscription will have a non $0 recurring payment in the future. 

We should avoid creating a subscription in Stripe if it doesn't require payment.

**Comment by haszari** [comment]
Do we need to support free subscriptions in WCPay Subscriptions? This seems like an edge case for WCPay, maybe free subs should be only supported with WooCommerce Subscriptions extension.

@james-allan do you have a use case in mind, and/or did this come from a merchant that needs free subscriptions? I'm curious to understand who's impacted by this and how.

@thenbrent What do you think about free subscriptions in WCPay Subscriptions – do we need to support this or could we have a minimum? I think we need a minimum sub/transaction $ for non-free subscriptions to address #3297.

> We should avoid creating a subscription in Stripe if it doesn't require payment.

Why - would this cause problems or is it just unnecessary/untidy?

**Comment by thenbrent** [comment]
@haszari good question. @james-allan leaving free subscriptions as a WC Subscriptions only feature is the better approach.

WC Pay Subscriptions is intended to become the entry point for folks to start collecting automatic recurring payments. Free subscriptions are one of those corner use cases that is better served by WC Subscriptions.

In a few ways, support for subscriptions that do not require any payment is also analogous to manual renewals (i.e. subscriptions without any specific automatic payment method) which is a WC Subscriptions only feature for similar reasons. So making $0 subscriptions WC Subscriptions only is aligned with that precedent.

I'm not sure of the best way to enforce that requirement. Could it be a similar approach to the notice given on the **Add/Edit Product** screen when attempting to create a product with an annual billing interval >1? And/or should we not allow products without a price to be published?

If we need something more than that, let me know and we can loop in folks from design.

**Comment by james-allan** [comment]
>  leaving free subscriptions as a WC Subscriptions only feature is the better approach.

Alrighty. That makes sense to me. :) 

We'll have consider a few extra scenarios like coupons which discount the subscription by 100% (low chance but possible) and manually created subscriptions which are created as $0. The only use case I can imagine where either of this situations might occur is store managers creating subscriptions for family or friends or 1 off promotional things. 

I'll create separate issues for those.

**Comment by thenbrent** [comment]
> We'll have consider a few extra scenarios like coupons which discount the subscription by 100% (low chance but possible)

@james-allan  I hadn't considered that case. Thanks for flagging it.

Ideally, we'd prevent all $0 subscription situations on the merchant side e.g. don't allow $0 subscription products, don't allow manual creation of $0 subscriptions etc.

I'm not sure it would be (sanely) possible to prevent coupons which discount the subscription by 100% though. For example, we're not going to check if the _**Recurring Product Discount**_ amount is > any subscription products (both when the coupon is created and when any product is created) and either prevent that object being published or display a notice whenever an invalid combination is created that it won't be usable for certain products.

Any ideas how we could enforce it on the merchant side?

If we can't, we're inevitably going to create a bad experience on checkout for the customer/shopper who ends up not being able to checkout if we just enforce it there (maybe by not allowing the coupon to be applied?) and I'd like to avoid that.

**Comment by james-allan** [comment]
> Any ideas how we could enforce it on the merchant side?

I don't have any good ideas. The only approach I really had in mind was the notice displayed to the customer on checkout, when trying to complete the purchase. 

We're likely going to have a minimum spend notice at some point to get around the issues raised in #3297 and to avoid the Stripe Account balances concerns raised in this P2 pdi1mn-2q-p2. Having said that, a minimum spend notice does feel different to a "you can purchase that free subscription" when there's no payment processor involved. 

🤔

**Comment by thenbrent** [comment]
> a minimum spend notice does feel different to a "you can purchase that free subscription" when there's no payment processor involved.

Yeah, agreed. I'll flag this with @LevinMedia and see if he has any good ideas.

**Comment by aprea** [comment]
FYI this issue was closed automatically when #3308 was merged. Please feel free to reopen it if you'd like to continue the conversation around allowing/disallowing free subscriptions in WCPay.

**Comment by james-allan** [comment]
@thenbrent just so I have a sense of your current thinking, is there a chance that we would allow free subscriptions to be purchased by shoppers just not created by merchants? 

OR would we aim to catch as many merchant flows as possible but fall back on a customer notice on checkout to catch any that fall through? 

OR is the whole free subscriptions functionality in WCPay a question if it will lead to a poor customer experience? 

Just want to make sure to include a note on the individual issues if we need to put them on hold pending an outcome or whether we can look into the merchant flows and just avoid the customer experience for now.

**Comment by thenbrent** [comment]
Closing the loop here after Slack discussion in p1636432118089500-slack-C02851ELV4P

WC Pay Subscriptions should:

* Support customers signing up to $0 subscriptions, so I'll close [this issue](https://github.com/Automattic/woocommerce-payments/issues/3310).
* Not allow $0 subscription products - covered in this [issue](https://github.com/Automattic/woocommerce-payments/issues/3309).
* Not allow manually creating $0 subscriptions - covered in this [issue](https://github.com/Automattic/woocommerce-payments/issues/3311).
