### ISSUE TITLE
Fix E2E tests

### ISSUE THREAD

**Issue by dpaun1985** [Automattic/woocommerce-payments#3283]
At this point E2E tests fails on github. 
![Screenshot 2021-11-03 at 11.55.40.png](https://images.zenhubusercontent.com/61235c8edec55544ecd78034/1c83a982-197c-4f91-a16c-89f706bcbee7)
We need to check why these tests fail on github and fix them.

**Comment by htdat** [comment]
Sounds like a duplicate issue of this. 
https://github.com/Automattic/woocommerce-payments/issues/3274

I am going to close this issue.
