### ISSUE TITLE
Display fees on Settings page

### ISSUE THREAD

**Issue by dpaun1985** [Automattic/woocommerce-payments#3285]
The fees were removed from the overview page in #3239, and only the discounts are displayed. Since the fees should be displayed, we need to move the fees, per payment method, in the settings screen.
Design should be provided.
Related PRs: #3239 #3055
Discussions on #3241 and p1635391455166700-slack-CGGCLBN58

**Comment by dpaun1985** [comment]
@LevinMedia could you please share with us the UI mentioned in https://github.com/Automattic/woocommerce-payments/issues/3241#issuecomment-954072113 ?

**Comment by LevinMedia** [comment]
@dpaun1985 I think we can close this issue out. It's being tracked at https://github.com/Automattic/woocommerce-payments/issues/3300 - @tpaksu has a PR open for it.

**Comment by kalessil** [comment]
Thanks for the ping @LevinMedia !
@dpaun1985: I'll close this for now, let me know please if you have any concerns.
