### ISSUE TITLE
Update all docs.woocommerce.com links

### ISSUE THREAD

**Issue by ricardo** [Automattic/woocommerce-payments#3294]
Internal reference: p1636037526141700-slack-C07418EA0

### Description
Links such as https://docs.woocommerce.com/document/payments now get redirected to https://woocommerce.com/document/payments/.

We might want to update all our existing links, since the domain for documents has changed.

### Acceptance criteria
All docs.woocommerce.com links are updated.

**Comment by MukulKolpe** [comment]
Hey @ricardo, can I work on this issue?

**Comment by ricardo** [comment]
@MukulKolpe Yeah, feel free 👍

**Comment by MukulKolpe** [comment]
I don't have permission. Can you assign this to me?

**Comment by ricardo** [comment]
Assigned you, so other people don't take the same issue.

**Comment by iusamahub** [comment]
@ricardo is the issue closed

**Comment by ricardo** [comment]
@iusamahub, @MukulKolpe is working on it.

@MukulKolpe let me know when the PR is ready for review.

**Comment by MukulKolpe** [comment]
@ricardo can you please review the PR and suggest changes if required and is there any type of testing involved for this issue?
If everything seems correct I think I will need to update the changelog entry.
