### ISSUE TITLE
WCPay Subscription application fees on subscriptions less than 30c 

### ISSUE THREAD

**Issue by james-allan** [Automattic/woocommerce-payments#3297]
### Describe the bug

Because of the way we apply application fees to subscriptions as a combined %, including the flat component, it's possible that we reach the upper limits on the `application_fee_percent`. eg when you purchase a product less than 30c the fee % goes above 100% and you reach this error:

```
This value must be less than or equal to 100 (it currently is '375.0').
```

### To Reproduce

1. Create a subscription product that is 20c.
2. Have a standard WC simple product with a price above 50c
2. Attempt to purchase the 20c subscription with the simple product via the checkout. 
     - The simple product is simply in the cart to get us over the 50c transaction limit.
3. You will get the error above in your WC Pay logs. 
4. If you look at the subscription request logs in Stripe, you will also see this error.

<img width="706" alt="Screen Shot 2021-11-05 at 9 28 51 am" src="https://user-images.githubusercontent.com/8490476/140434070-43e6824a-87e0-4ec1-94dc-f536c9e6f350.png">

### Actual behaviour

The application fee on subscriptions get calculated as an effective %, for example, we calculate the fee amount (in $) and then convert that to a %. 

```php 
// Base fee is 1.75% + .30
$fee_amount = (.20 * 1.75%) + .30; // = 0.3035
$fee_percent = (0.3035 / .20) * 100; // = 151.75%
```

### Screenshots

<img width="478" alt="Screen Shot 2021-11-05 at 9 36 59 am" src="https://user-images.githubusercontent.com/8490476/140434692-a549755e-0c35-46b3-ae99-fb52116efd2e.png">

### Expected behavior

We should prevent the purchasing of subscriptions with less than the minimum purchase amount. 

### Desktop (please complete the following information):

* OS: [e.g. iOS]
* Browser [e.g. chrome, safari]
* Version [e.g. 22]

### Smartphone (please complete the following information):

* Device: [e.g. iPhone6]
* OS: [e.g. iOS8.1]
* Browser [e.g. stock browser, safari]
* Version [e.g. 22]

### Additional context

Stripe handle transactions below the minimum charge amount in ways that may be incompatible with WCPay Subscriptions. They also convert the amount into the account's base currency before determining if that amount falls below the charge limit. This has been raised in this external Stripe P2 pdi1mn-2q-p2

**Comment by aprea** [comment]
I have a few questions about this bug. The expected behaviour in the GH issue description is:

>We should prevent the purchasing of subscriptions with less than the minimum purchase amount.

**Questions:**
- Do we have a clear way forward on this? i.e. have we decided on an approach? (remove WCPay as a payment gateway when the cart is below minimum purchase amount vs error message on checkout)
- Do we know what the actual minimum purchase amount is? Is it a particular dollar amount or will it depend on a combination of the cart items (normal items & subscription items) + shopper currency + other factors?
- Are we waiting to hear back from the Stripe team on the P2? pdi1mn-2q-p2
- Do we need product/design input for the expected behaviour?

This issue is sitting in the WCPay 3.3 fast follows milestone and is currently unassigned. I'm thinking we should remove it from this milestone as it's looking unlikely that we'll be able to pick it up and complete it by this Friday. Unless it's a pretty trivial fix? Keen to hear your thoughts on this.

cc @james-allan

**Comment by james-allan** [comment]
Those are all great questions @aprea. I don't have clear answers for them but here's what I'm thinking. 

> Do we have a clear way forward on this? i.e. have we decided on an approach?

No, not yet. There are a few ideas floating around. Having a minimum transaction amount was one idea floating around because it also fixes the issue of account balances. But that hasn't been decided. 

> Do we know what the actual minimum purchase amount is?

I think it is variable as you mentioned. It would be depending on the application fee. The reason 20c in my example above causes an error is because the flat fee component is 30c which immediately results in a fee greater than 100%. So if aim to avoid this error by setting a minimum purchase amount, we would need it to be some amount that is larger than any flat fee component we charge.

If we aim to also avoid Stripe Account balances by setting a minimum purchase amount, then we would need to also choose an amount that takes into consideration the currency. 

> Do we need product/design input for the expected behaviour?

Yeah, we should.
 
> Unless it's a pretty trivial fix? Keen to hear your thoughts on this.

I think it's pretty unlikely we get this into 3.3 at this point given the ongoing discussions and desire to get product/design feedback.

**Comment by aprea** [comment]
Perfect, thanks @james-allan! I have removed this from the fast follows milestone and added the "needs design" label.

**Comment by haszari** [comment]
@aprea What's the next step here?

I'm thinking we should propose a minimum transaction value and implement to avoid issues like this and others with free or heavily discounted subscriptions. I think this area is worth prioritising for 3.4 and I think we should come up with a proposal and then get product + design feedback. See also related issues:

- #3309 
- #3311

**Comment by haszari** [comment]
See related issue for a path forward: https://github.com/Automattic/woocommerce-payments/issues/3309#issuecomment-994026963

I'm thinking we tackle product creation first and then follow up with appropriate error handling for purchase (this issue) and manual admin subscriptions (#3311).

**Comment by james-allan** [comment]
There's a great deal of additional implementation details mention in this P2 thread (pdjTHR-mc-p2#comment-458), to summerise: 

We can use a WC Pay Server function `verify_minimum_amount()` to verify during subscription creation on the checkout, that the subscription's recurring amount meets the minimum amount for the given currency. 

If the subscription doesn't meet the requirement, the server will throw a `WCPay\Exceptions\Amount_Too_Small_Exception` which we will just need to add a catch for. 

With that in mind there will be two sub-components to this issues:

1. Implement the server changes necessary to verify the the subscription amount during creation. 
2. Add error handling on client side to add a customer facing error on checkout.

**Comment by james-allan** [comment]
WIP validation changes proposed to server can be found here: 1446-gh-Automattic/woocommerce-payments-server

**Comment by mattallan** [comment]
Server changes have been deployed ahead of WCPay 3.6. Closing this 🙌
