### ISSUE TITLE
WC Pay Subscriptions - rename application fee

### ISSUE THREAD

**Issue by thenbrent** [Automattic/woocommerce-payments#3298]
### Description

PR #3108 introduced the [1% fee](https://woocommerce.com/document/payments/faq/fees/) for subscription related transactions processed through WC Pay Subscriptions.

At the time, the guidance from design was to name this fee "_Recurring transaction fee_" on the Transaction timeline:

<img width="1181" alt="Screen Shot 2021-11-05 at 10 36 18 am" src="https://user-images.githubusercontent.com/235523/140439145-3c0c04d8-125a-4674-a280-75967961e6a8.png">

However, it was later determined that these fees need to be levied on any WC Pay Subscription transaction, including the initial sign-up.

This fee needs to be renamed to better reflect that it is not applied only to recurring payments. It should be renamed to "_Subscription transaction fee_".

### Acceptance criteria

* Transactions with subscription related fees that are processed after the release of the patch display the fee name on the timeline as "_Subscription transaction fee_".
* Existing transactions with subscription related fees that were processed _before_ the release of the patch display the fee name on the timeline as "_Subscription transaction fee_".

### Designs

<img width="1180" alt="Screen Shot 2021-11-05 at 10 38 47 am" src="https://user-images.githubusercontent.com/235523/140439305-cd71e76b-10cc-4687-b1df-3aae57f34500.png">

**Comment by haszari** [comment]
Nice easy fix!
