### ISSUE TITLE
Internationalization of Credit Card payment method title

### ISSUE THREAD

**Issue by giacomocamerano** [Automattic/woocommerce-payments#3299]
With reference to: 

https://github.com/Automattic/woocommerce-payments/blob/1e99d3aeb9674869c3b05c9a1e35ceb5a3e0bd41/includes/payment-methods/class-cc-payment-method.php#L25

I understand the need to not internationalize other payment methods as they're brand names/trademarks (e.g. giropfay, Sofort) but the default credit card payment could be internationalized.

I simply suggest:

```
$this->title       = __('Credit card / debit card', 'woocommerce-payments'); 
```

**Comment by joashrajin** [comment]
This string does not seem translatable with Loco Translate and can cause issues for non-English sites. For further information, please refer to p1628785357363600-slack-C3NCP7ZJ6

4465007-zd-woothemes

**Comment by htdat** [comment]
@giacomocamerano - that's a good point. Would you like to create a new PR to fix this issue? ;)

**Comment by giacomocamerano** [comment]
@htdat added my first PR, hope I followed all the guidelines correctly :)
