### ISSUE TITLE
Update UPE payment method selection and fees

### ISSUE THREAD

**Issue by LevinMedia** [Automattic/woocommerce-payments#3300]
Update the payment method selection and fees per paJDYF-2rk-p2

This update makes each payment method selectable from the main settings screen. 

<img width="929" alt="Screen Shot 2021-11-05 at 8 41 33 AM" src="https://user-images.githubusercontent.com/4500952/140538046-2504b172-49ef-49aa-83d9-a26dd459598b.png">

The pill that displays the fees should show the aggregate total of the fees that the merchant will pay for each payment method. Hovering over the pill will provide a breakdown of the components of the fee. 

<img width="926" alt="Screen Shot 2021-11-05 at 8 41 20 AM" src="https://user-images.githubusercontent.com/4500952/140538069-a50fbef3-9eb3-4d2a-8789-22d42b6bc587.png">

**Comment by tpaksu** [comment]
@LevinMedia do you also want this link on the tooltip? If yes, where should it redirect the user? Source: paJDYF-2rk-p2#comment-7996

![image](https://user-images.githubusercontent.com/3295/140659349-4ceedbc0-f381-40a9-90b2-e072cc933b3f.png)

**Comment by LevinMedia** [comment]
@tpaksu if we can add that link it would be great - it should direct the merchant to the fees page for their specific country. For example a german merchant would be directed to: https://woocommerce.com/document/payments/faq/fees/#section-6

However to simplify things, I think we should update that copy to read  "[Learn more](url) about WooCommerce Payments Fees in your country"

**Comment by LevinMedia** [comment]
One additional thing to consider here - we should ensure these fees display for credit card payments regardless of whether or not the merchant has enabled UPE.

**Comment by tpaksu** [comment]
> One additional thing to consider here - we should ensure these fees display for credit card payments regardless of whether or not the merchant has enabled UPE.

Yep, It shows when UPE is disabled too. It's not bound to the UPE flag.

![image](https://user-images.githubusercontent.com/3295/141056506-75106d55-0446-4c6b-bd2c-35f309923693.png)
