### ISSUE TITLE
Prevent admin users from creating subscription products that are $0 

### ISSUE THREAD

**Issue by james-allan** [Automattic/woocommerce-payments#3309]
### Describe the bug

In line with [this comment](https://github.com/Automattic/woocommerce-payments/issues/3279#issuecomment-962742556), we are moving to prevent admin users from creating subscriptions that are $0. Implementing this will require a number of separate changes. 

1. Preventing admin from creating free subscription products. (This issue). 
2. Validating subscription creation on checkout if you've managed to get a $0 subscription product - via a 100% coupon or otherwise. https://github.com/Automattic/woocommerce-payments/issues/3310
3. Creating free subscriptions via admin. Admin users shouldn't be able to create subscription products manually which have a $0 total.  #3311

### To Reproduce

1. Disable WC Subscriptions extension.
2. Go to **Products > Add new**
3. Select the "Simple subscription product" type. 
4. Enter the price of $0.
5. Press **save**.

### Actual behavior

In this scenario, the subscription is created with a $0. 

### Expected behavior

This should result in an error admin notice suggesting that you cannot create a subscription product with a price.

**Comment by james-allan** [comment]
@brucealdridge Does this one have a PR or did you mean to reference https://github.com/Automattic/woocommerce-payments/issues/3309 instead? 

Automattic/woocommerce-subscriptions-core#48 prevents admin from manually creating free subscriptions, whereas this is about free products.

**Comment by brucealdridge** [comment]
> @brucealdridge Does this one have a PR or did you mean to reference #3309 instead?

Yes, I referenced the wrong issue. I think I updated the PR but didn't unlink from this issue.

**Comment by haszari** [comment]
Next steps for this issue:

- Find out [minimum transaction values for supported currencies for WCPay (Stripe)](https://stripe.com/docs/currencies#minimum-and-maximum-charge-amounts).
- Define a minimum subscription product price based on that - for example, double. We may need to confirm this with product / biz team.
- Implement validation and guidance for merchants creating products, e.g. error messages.

If that works out, we can look at the related issues as follow up.

**Comment by haszari** [comment]
Reopening - FYI @james-allan @brucealdridge 

Reopening because this issue shouldn't be closed until subscriptions-core changes are merged into WCPay, e.g. version bump composer PR.

Also, see the above comment about using minimum transaction value (rather than zero). If we're not implementing that as part of this issue can you log a new issue? Thanks 😁

**Comment by james-allan** [comment]
> If we're not implementing that as part of this issue can you log a new issue?

Yep, I'll write up a new issue.

**Comment by james-allan** [comment]
Closing the loop. Heres the new issue for warning merchants about subscription products below a certain amount. 

- https://github.com/Automattic/woocommerce-payments/issues/3542

**Comment by haszari** [comment]
Thanks @james-allan ! Just realised this fix might get shipped in WCPay 3.5 (FYI @shendy-a8c). I've shifted it to 3.5 milestone - James, let me know or work with Shendy if you don't want this going out in 3.5.

**Comment by shendy-a8c** [comment]
Closed by https://github.com/Automattic/woocommerce-payments/pull/3550.
