### ISSUE TITLE
Use wp.data for dispute views

### ISSUE THREAD

**Issue by dechov** [Automattic/woocommerce-payments#331]
Migrate the _disputes list_ and _evidence form_ from component-local state to the client-side persistence layer introduced in https://github.com/Automattic/woocommerce-payments/pull/324.

**Comment by vbelolapotkov** [comment]
All related PRs are merged.

**Comment by dechov** [comment]
The dispute evidence form is still using a [data wrapper component](https://github.com/Automattic/woocommerce-payments/blob/5f86a934918139be417df6ba2fa6d526bd69a297/client/disputes/evidence/index.js#L316-L560) and has yet to be upgraded – opened a new issue: https://github.com/Automattic/woocommerce-payments/issues/903
