### ISSUE TITLE
Prevent customers from signing up to $0 subscriptions

### ISSUE THREAD

**Issue by james-allan** [Automattic/woocommerce-payments#3310]
### Describe the bug

In line with [this comment](https://github.com/Automattic/woocommerce-payments/issues/3279#issuecomment-962742556), we are moving to prevent customers from purchasing subscriptions that are $0. Implementing this will require a number of separate changes. 

1. Preventing admin from creating free subscription products. 
    - https://github.com/Automattic/woocommerce-payments/issues/3309. 
2. Validating subscription creation on checkout if you've managed to get a $0 subscription product - via a 100% coupon or otherwise. (This issue)
3. Creating free subscriptions via admin. Admin users shouldn't be able to create subscription products manually which have a $0 total. https://github.com/Automattic/woocommerce-payments/issues/3311

### To Reproduce

1. Create a 100% off recurring coupon. https://d.pr/i/QUKv5g
2. Disable shipping calculations or add a free shipping method. 
1. Disable WC Subscriptions extension.
3. Add any subscription to your cart. 
4. Add the 100% off coupon. https://d.pr/i/1foyDh
5. Attempt to purchase the subscription. 

### Actual behavior

In this scenario, the checkout will display no shipping methods since there is no payment required and placing the order is successful. 

### Expected behavior

Customers purchasing subscriptions reduced to $0 should be prevented.

**Comment by thenbrent** [comment]
Closing based on discussion here: https://github.com/Automattic/woocommerce-payments/issues/3279#issuecomment-963823277
