### ISSUE TITLE
Renovate: No PR for new PHP jetpack-config package versions

### ISSUE THREAD

**Issue by htdat** [Automattic/woocommerce-payments#3316]
### Describe the bug

jetpack-config's latest version is `1.5.3` - source https://github.com/Automattic/jetpack-config/blob/master/CHANGELOG.md

composer.json uses `1.4.3`:
https://github.com/Automattic/woocommerce-payments/blob/410364925237641893c25c804a7b403ab42880c4/composer.json#L17

No PR from Renovate about new versions for this package: https://github.com/Automattic/woocommerce-payments/pulls?q=is%3Apr+%22jetpack-config%22+is%3Aopen+

### Additional context

https://packagist.org/packages/automattic/jetpack-config

**Comment by jrodger** [comment]
The only explaination I can think of is Renovate pausing the creation of new PRs because we already have so many open.

The docs suggest the default on that setting is `0` (no limit) though, so this is a bit of a guess.

**Comment by htdat** [comment]
> The only explanation I can think of is Renovate pausing the creation of new PRs because we already have so many open.

This seems not reasonable. 
We're still having new PRs from Renovate https://github.com/Automattic/woocommerce-payments/pulls?q=is%3Apr+author%3Aapp%2Frenovate

But the last PR Renovate created for this package was in January 2021 - https://github.com/Automattic/woocommerce-payments/pulls?q=is%3Apr+%22jetpack-config%22+is%3Aclosed

**Comment by jrodger** [comment]
> We're still having new PRs from Renovate

Good point 🤔

`composer require automattic/jetpack-config:1.5.3` works fine in my local environment, it upgrades cleanly and there are no issues with other dependencies. So I'm not sure why Renovate isn't opening a PR.

**Comment by jrodger** [comment]
The Renovate debug logs at app.renovatebot.com have this:

```
DEBUG: Setting current branch to develop(branch="renovate/automattic-jetpack-config-1.x")
DEBUG: latest commit(branch="renovate/automattic-jetpack-config-1.x")
{
  "branchName": "develop",
  "latestCommitDate": "2021-11-09T14:52:49+11:00"
}
DEBUG: getBranchPr(renovate/automattic-jetpack-config-1.x)(branch="renovate/automattic-jetpack-config-1.x")
DEBUG: findPr(renovate/automattic-jetpack-config-1.x, undefined, open)(branch="renovate/automattic-jetpack-config-1.x")
DEBUG: findPr(renovate/automattic-jetpack-config-1.x, undefined, closed)(branch="renovate/automattic-jetpack-config-1.x")
DEBUG: branchExists=false(branch="renovate/automattic-jetpack-config-1.x")
DEBUG: dependencyDashboardCheck=undefined(branch="renovate/automattic-jetpack-config-1.x")
DEBUG: recreateClosed is false(branch="renovate/automattic-jetpack-config-1.x")
DEBUG: findPr(renovate/automattic-jetpack-config-1.x, Update dependency automattic/jetpack-config to v1.5.3, !open)(branch="renovate/automattic-jetpack-config-1.x")
DEBUG: prAlreadyExisted=false(branch="renovate/automattic-jetpack-config-1.x")
DEBUG: Reached branch limit - skipping branch creation(branch="renovate/automattic-jetpack-config-1.x")
```

So I think it is the branch limit somehow? Despite those other PRs getting created, maybe we closed enough for those new ones to get created but it didn't get as far as making this one? Seems a little strange since I don't think we closed that many Renovate PRs recently.

Let's leave this issue open and revisit it once we're more onto of the outstanding PRs.

**Comment by htdat** [comment]
> So I think it is the branch limit somehow? 

Do you have more details what exactly it is? I am not able to find references for "Reached branch limit" on https://docs.renovatebot.com/

> Let's leave this issue open and revisit it once we're more on top of the outstanding PRs.

Yeah, agreed to leave it here. I've added the low priority for this issue too.

**Comment by jrodger** [comment]
> Update: is that a limit set by Renovate or GitHub? Can we have a way to remove or increase it?

All the Renovate docs suggest that the default is "no limit". So I'm wondering if the limit is introduced by GitHub, or maybe Renovate when it's running as a GitHub app?

I don't think we need to worry about it too much, we just need to stay on top of merging Renovate PRs.

**Comment by vbelolapotkov** [comment]
Closing this one, since renovate bot is suspended in the org. More context here: p3btAN-1Ks-p2
