### ISSUE TITLE
npm install fails

### ISSUE THREAD

**Issue by helgatheviking** [Automattic/woocommerce-payments#3324]
### Describe the bug
`npm install` fails 

The readme says 
>If you run into errors with npm install it may be due to node version, try nvm install followed by nvm use then try again.

But it doesn't say which version to actually use. The package.json file says 12.16.0 so I tried all the following:

v12.16.0
v12.22.7
and v14.18.1

but they all fail as it can't seem to find files in the `node_modules/.staging` folder. 

>npm WARN tar ENOENT: no such file or directory, lstat '/home/cabox/workspace/wp-content/plugins/woocommerce-payments/node_modules/.staging/@wordpress/components-538d7e00/src/toggle-group-control'

### To Reproduce

`npm install`

### Desktop (please complete the following information):

Using a command prompt in a cloud linux install:

NAME="Ubuntu"
VERSION="16.04 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04 LTS"
VERSION_ID="16.04"
UBUNTU_CODENAME=xenial

**Comment by zmaglica** [comment]
Hi there!

I had similar problem like you and I manage to fix it.

Could you please try the following steps:

1. Delete `node_modules` folder
2. Execute `nvm install`
3. Execute `nvm use`. The correct NodeJS version should be installed and configured after this step.
4. Execute `npm install` to install all dependencies. 

I am on Ubuntu too (Ubuntu 21.10) and I had a similar error like you. NPM version that was installed on my machine was the latest LTS version (v16.x). To make it even worse, after I got an error, I used `nvm` to set the correct version but all dependencies inside node_modules were installed with version 16.x. To overcome this issue, I had to delete `node_modules` folder and install/configure correct version by `nvm` and at last, execute `npm install`.

**Comment by zmaglica** [comment]
@helgatheviking Yesterday I had the same issue as you. Make sure to run NPM commands from root of the plugin directory. You will have this error if you position your self inside one of the packages and execute `npm install` from there.

Make sure to run `npm start` or any NPM command you wish to from the root directory.

**Comment by helgatheviking** [comment]
Thanks @zmaglica !! I do always run the command from the root, but I gave it another shot after deleting the `package-lock.json` and `composer-lock.json` files. 

I ended up using 
`nvm install v12.16.0` and `nvm use v12.16.0`

since that's the version listed in `package.json`

```
"node": ">=12.16.0",
```

though if it supports _greater than_ 12.6.0 I would have expected 14 or whatever I was on to also work. 🤷‍♀️
