### ISSUE TITLE
Add basic multisite flows to the critical flows

### ISSUE THREAD

**Issue by aprea** [Automattic/woocommerce-payments#3328]
### Description
We currently do not have critical flows that cover WordPress multisite installations. We should add some basic multisite flows to the [critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Critical-flows) and [testing instructions](https://github.com/Automattic/woocommerce-payments/wiki/Testing-instructions-for-critical-flows) pages to ensure that WooCommerce Payments works as expected in multisite environments.

### Acceptance criteria

Add the following flows to the [critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Critical-flows) and [testing instructions](https://github.com/Automattic/woocommerce-payments/wiki/Testing-instructions-for-critical-flows) pages:

- Manual plugin installation and setup
- Checkout with normal credit card

The "Manual plugin installation and setup" flow can be adapted from the [existing flow](https://github.com/Automattic/woocommerce-payments/wiki/Testing-instructions-for-critical-flows#manual-plugin-installation-and-setup) but with the necessary changes to ensure WooCommerce and WooCommerce Payments are installed and activated at the network level on a WordPress multisite installation.

### Additional context
Incident report where this was originally proposed and discussed - paJDYF-2ON-p2

**Comment by RadoslavGeorgiev** [comment]
For GS testing, we should keep this comment in mind: paJDYF-2ON-p2#comment-8766

**Comment by naman03malhotra** [comment]
@deepakpathania can you please handle this during your release lead cycle for 3.7

**Comment by deepakpathania** [comment]
#### Manual plugin installation and setup
1. Add a new site to your multisite network following this guide: PbPjnJ-1x-p2#multisite.
2. Install the required plugins like WooCommerce and WooCommerce Payments at a network level.
    1. Go to the network dashboard by selecting `My Sites` -> `Network Admin` -> `Dashboard`.
    
     ![Markup 2022-01-31 at 15 00 50](https://user-images.githubusercontent.com/68396823/151774051-90450f6d-c82f-4b12-b41d-f0d22c58849c.png)
    2. From here, select the `Plugins` sub menu and upload the plugin zip to install a plugin at a network level. 
    
![Markup 2022-01-31 at 15 04 38](https://user-images.githubusercontent.com/68396823/151774069-b7a08ea2-acec-41dd-857b-53a750b0542c.png)
    3. In the plugin listing page, you'll be able to see `Network` at the bottom of the plugin.
    
![Markup 2022-01-31 at 15 13 45](https://user-images.githubusercontent.com/68396823/151774089-b9be2a29-646c-4708-a910-ff734ae7cf0d.png)

3. Once done, follow the [manual plugin installation steps](https://github.com/Automattic/woocommerce-payments/wiki/Testing-instructions-for-critical-flows#manual-plugin-installation-and-setup) listed for the single site flow.

**Comment by deepakpathania** [comment]
@aprea Could you verify if the format of this comment makes sense to be added in the testing instructions?

**Comment by aprea** [comment]
Hi @deepakpathania, this looks good to me thanks!

**Comment by deepakpathania** [comment]
Updated [testing instructions](https://github.com/Automattic/woocommerce-payments/wiki/Testing-instructions-for-critical-flows#multi-site-flows) and [critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Critical-flows). ✅
