### ISSUE TITLE
No conversion after switching currency on manual order payment page

### ISSUE THREAD

**Issue by ismaeldcom** [Automattic/woocommerce-payments#3329]
### Describe the bug
When a failed or manual order is paid through **My Account > Orders > Pay** we use a different page to the checkout. If we use the current switcher to update the selected currency the order will use the new selected currency without any conversion.

### To Reproduce
- Add item to cart and proceed to checkout.
- Use any test declined card like 4000000000000002.
- After order fails, go to **My Account > Orders**, and click the **Pay** button.
- Change the currency switcher widget.
- Check your account Stripe dashboard payments to see the issue.

### Expected behavior
Order amounts should not be converted after switching the selected currency and the order currency should be used to make the payment.

### Screenshots
|Order pay screen|
|-|
|<img width="1097" alt="Screenshot 2021-11-09 at 09 12 06" src="https://user-images.githubusercontent.com/7670276/140887423-067ce399-3232-44d9-9191-64d89b43a192.png">|

|Created payments on Stripe after switching selected currency|
|-|
|<img width="1173" alt="Screenshot 2021-11-09 at 09 12 22" src="https://user-images.githubusercontent.com/7670276/140887431-c19e75bc-7aa6-4d92-b275-1fa195f3d85d.png">|

**Comment by jessepearson** [comment]
@ismaeldcom Can you see if https://github.com/Automattic/woocommerce-payments/pull/3323 fixes the issue you're referring to here? It sounds like it's the same thing I found yesterday. The problem is specifically here:
https://github.com/Automattic/woocommerce-payments/pull/3323/files#diff-b541c0a287f40f82a1d0e43c52c7c7a2b67ae233f261655cbb437726fec83feeL246

**Comment by ismaeldcom** [comment]
Thanks @jessepearson I missed that! I'm going to close this as it is the same issue, it's just that not only the formatting is affected, but the currency used for the payment too.
