### ISSUE TITLE
Add automated compatibility tests for common WooCommerce payment gateways [Investigation]

### ISSUE THREAD

**Issue by aprea** [Automattic/woocommerce-payments#3337]
### Description
WooCommerce Payments 3.2.0 shipped with [a bug](https://github.com/Automattic/woocommerce-payments/issues/3245) that affected stores using the PayPal Standard gateway. A fatal error would occur when viewing the payments settings page (**WooCommerce → Settings → Payments**).

The bug was resolved in this PR https://github.com/Automattic/woocommerce-subscriptions-core/pull/27

We should investigate whether it's possible to add automated tests to check that WooCommerce Payments is compatible with other common WooCommerce Payments gateways, e.g. Stripe, Braintree, PayPal, etc.

"Compatible" could mean a number of things, but at a minimum, the following should be tested:
- No fatal errors or warnings when WooCommerce Payments is enabled alongside other payment gateways.
- Checkout works as expected when WooCommerce Payments is enabled alongside other payment gateways.

### Acceptance criteria

* Investigate the possible approaches to add automated compatibility tests for common WooCommerce payment gateways (e.g. Stripe, Braintree, PayPal, etc.)
* Decide on the best approach.
* Create a new GitHub ticket detailing this approach.
* Close this GitHub ticket.

If automated tests are not viable, we should consider adding manual compatibility flows to the [critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Critical-flows) and [testing instructions](https://github.com/Automattic/woocommerce-payments/wiki/Testing-instructions-for-critical-flows) pages.

### Additional context
Incident report where this was originally proposed and discussed - paJDYF-2ON-p2

**Comment by vbelolapotkov** [comment]
Closing this one in favor of integration with compatibility dashboard and QIT https://github.com/Automattic/woocommerce-payments-meta/issues/334
