### ISSUE TITLE
Add a test mode warning notice to order details screen

### ISSUE THREAD

**Issue by reykjalin** [Automattic/woocommerce-payments#334]
I realized while working on #242 that adding test mode notices to the WC Order Details screen will take a significant amount of effort because it's directly controlled by WooCommerce, and it's really hard — at least AFAICT — to hook into _only_ that screen and add a notice. We could add a wp-admin wide notice, but I don't think that's what we want here.

We may even want to wait for upstream changes in WooCommerce that will store information on whether an order was made in test mode or not, as has been discussed in the past. For now we'll make do with waiting until further down the line to implement this.

**Comment by vbelolapotkov** [comment]
I have a feeling we'd need to review design vs implementation effort of this and reprioritise based on it.

**Comment by zoupkat** [comment]
Hey team! We know that this is a very old issue but as we are perfecting the service and gaining more users, we would love to see some solutions for issues like that ⬇️
While troubleshooting 7223757-zen, we found out that the user's customers had completed some purchases while the PG was on Test Mode.
There is no indication within the order from the Order tab that the order was placed on Test Mode which confused the user into thinking it was a legit/successful payment and was waiting for a deposit for it.
Another downside here is that all of the purchases were made with Apple Pay, which **doesn’t** show any kind of test mode warning(Google Pay does). Therefore, the customers thought they were paying.
Same happened in 7113687-zen and the user was really confused and frustrated.
Your 2 cents please! Thank you!

**Comment by htdat** [comment]
Thanks @zoupkat for raising this issue again. Gamma team will re-evaluate the priority for this issue.

**Comment by zoupkat** [comment]
Sounds good! Thanks @htdat !
FYI, there is an enhancement issue/suggestion opened for this: https://github.com/Automattic/woocommerce-payments/issues/7615

**Comment by htdat** [comment]
@zoupkat - we have moved it to `Priority 3 (Medium)` (see what it means PaJDYF-2R4-p2 ) for our backlog. Feel free to reach out to Gamma on Slack if necessary.

**Comment by htdat** [comment]
FYI. Relevant project: paJDYF-bnR-p2

**Comment by bradyv** [comment]
@htdat I'm going to drop a quick screenshot here as a discussion starter for a possible solution, though I have not fully evaluated it yet. Adding an item to the _order notes (#7615)_ may be an easier engineering effort but my instinct is that it's not visible enough for the problem we're trying to solve.

I think having a persistent banner attached to the order is the better option.

![WooCommerce -_ Order Details](https://github.com/Automattic/woocommerce-payments/assets/889872/4a895367-b39c-496b-8fc7-2d07cb240d22)

**Comment by Jinksi** [comment]
Note that if we introduce some way of determining the WooPayments test/live mode state of an order (e.g. as order meta), this will help resolve issues related to test/live mode orders such as #7076.

**Comment by zoupkat** [comment]
@bradyv & @Jinksi I totally agree! That's great.
That banner could perhaps include a permalink to the [Test Mode doc](https://woo.com/document/woopayments/testing-and-troubleshooting/testing/) so that users can easily see what it means.

**Comment by bradyv** [comment]
@zoupkat That's a great suggestion. Here's a slightly updated mockup that includes the helper link

![WooCommerce -_ Order Details](https://github.com/Automattic/woocommerce-payments/assets/889872/ddfe108b-bb02-4c93-abb8-350da9e4b66a)

I think design wise this is a viable solution and it aligns with other efforts to include inline notices on the order details page. A question for @zoupkat or maybe @htdat – is there a substantial engineering effort to determine live/test state for WooPayments and communicate it to the order details?

**Comment by zoupkat** [comment]
That looks awesome @bradyv !
As for your question, I think that @htdat has better insights than me.
Tagging also @csmcneill since he had opened the similar issue and might have some valuable info to share.

**Comment by htdat** [comment]
👋 Hi @bradyv, thanks for working on this and proposing an elegant solution! 

> is there a substantial engineering effort to determine live/test state for WooPayments and communicate it to the order details?

We have already had `_wcpay_mode` order meta for each order so this is totally possible without much effort https://github.com/Automattic/woocommerce-payments/blob/3ff92105f9db308b65ab7073b4477a644f9a40fa/includes/class-wc-payment-gateway-wcpay.php#L1210 

--- 

Regarding the notice yellow box, it sounds like this PR https://github.com/Automattic/woocommerce-payments/pull/6373 has already laid out the foundation for it.

**Comment by bradyv** [comment]
@htdat Terrific! In that case I'll leave it in your hands for prioritization / implementation, and feel free to reach out if there's any design questions or testing that you need help with.
