### ISSUE TITLE
Display an onboarding modal when merchants create subscription products before onboarding

### ISSUE THREAD

**Issue by james-allan** [Automattic/woocommerce-payments#3379]
### Description

Display a modal when a merchant attempts to create a subscription product before they have completed the WCPay onboarding.

Part of #3356
Originally proposed here pdjTHR-he-p2#comment-402

### Acceptance criteria

**Prerequisites:**
- WooCommerce Subscriptions is **not** active.
- The subscriptions feature is enabled (via **Payments → Settings**).
- WooCommerce Payments is active but the setup/onboarding is **not** completed.

**Criteria:**
- If a merchant attempts to publish a subscription product before onboarding they are shown with the following modal.
- Clicking the "Finish setup" button in the modal will navigate to the merchant to the WCPay onboarding flow.

### Designs

![image](https://user-images.githubusercontent.com/8490476/141723016-fd6e3968-f1f7-4f09-9578-34b0fef9fa09.png)

### Testing instructions

1. Go to **Products > Add New**
2. Select either **Simple subscription** or **Variable subscription**. 
3. Create variations (if applicable), enter a price and a name.
4. Hit **Publish**. 
4. You should be greeted with the modal above requesting that you onboard. 

### Additional context

This issue is one step in a whole flow to catch Subscription products being created before onboarding. The product will also be set to a draft status and get automatically published after onboarding. See #3356 for more context.

**Comment by james-allan** [comment]
I've been looking over the designs for this one and I'm not 100% sure how to achieve this. 

The designs show the user clicking the publish product button, that button being intercepted conditionally if the store hasn't onboarded and the product is a subscription, the product is saved as a draft (with a spinner in the modal), there's a finish set up button to direct the user to onboard.

In the normal saving product flow, saving the product is tied to the form being submitted and the `save_post` hook running. I'm not sure how to simulate the product form being submitted via a client-side (js, react, ajax style) request. @aprea have you got any ideas? I'm not sure if you still planned on picking this one up.

**Comment by haszari** [comment]
> In the normal saving product flow, saving the product is tied to the form being submitted and the save_post hook running. I'm not sure how to simulate the product form being submitted via a client-side (js, react, ajax style) request.

I see - so this design assumes we can intercept the `Publish` button early and change to save as draft, show the modal, etc. Good question, we'll need to look at how we can achieve this flow - might need some tweaks to the flow.

**Comment by aprea** [comment]
@james-allan I think saving the subscription product via AJAX will need to be out of scope for this issue. This is simply not how the classic editor works. Posts are saved via a regular form submit / page request. Transitioning to saving the post via AJAX is not trivial.

Could we do the following instead:
- The merchant clicks the "Publish" button for a subscription product.
- During this request we determine whether or not the merchant has completed WCPay onboarding:
	- If they have: Do nothing, i.e. regular publish flow.
	- If they have not: Do not publish the product, instead save it as a draft. When the page request completes display the following modal to the merchant.
<img width="1440" alt="Frame (4)" src="https://user-images.githubusercontent.com/1527164/143149107-cdbd6607-e53d-4e71-848a-43683adbfc33.png">

**Comment by james-allan** [comment]
That seems like a reasonable compromise.

**Comment by aprea** [comment]
Do I dare ask how to handle the scheduled publish scenario? 😅

**Comment by james-allan** [comment]
> Do I dare ask how to handle the scheduled publish scenario?

No, you may not. 😆

**Comment by haszari** [comment]
That's a good approach to try Chris – though the modal being delayed until after page load will be a clunky experience. 

> Do I dare ask how to handle the scheduled publish scenario?

I think it's worth a zoom call to brainstorm this design and validate it from a technical point of view. If the design is pushing us towards compromises then we should review our options. We should also feedback on the design if we can't practically deliver what's intended.
