### ISSUE TITLE
Subscription products created before onboarding should be automatically published after set up

### ISSUE THREAD

**Issue by james-allan** [Automattic/woocommerce-payments#3380]
### Describe the change

Subscription products created before merchants have completed WCPay onboarding will be set to draft. See #3378. This issue is to make sure that products set to draft in this way get published after the store completes the onboarding. 

Part of https://github.com/Automattic/woocommerce-payments/issues/3356
Originally proposed here pdjTHR-he-p2#comment-402

### Acceptance criteria

**Prerequisites:**
- WooCommerce Subscriptions is **not** active.
- The subscriptions feature is enabled (via **Payments → Settings**).
- WooCommerce Payments is active but the setup/onboarding is **not** completed.
- https://github.com/Automattic/woocommerce-payments/issues/3378 issue completed as that issue will set products to draft. 

**Criteria:**
- Products which are set to draft before completing the onboarding should get published automatically afterwards.

### Additional context

This issue is one step in a whole flow to catch Subscription products being created before onboarding. The product will also be set to draft status and there will be a modal to direct merchants to onboard. See #3356 for more context.

**Comment by haszari** [comment]
Will these draft products have a flag or metadata to distinguish them from regular drafts? If the merchant has other draft products, or intentionally-draft subscription products, we shouldn't publish them automatically after WCPay onboarding.

**Comment by james-allan** [comment]
yeah, something like that or a wp option containing the list. Querying for a set of products by a piece of meta would require a direct database query as there isn't a core function for doing anything like that as far as I know.
