### ISSUE TITLE
Adjust `Recurring Payments` copy in payment gateways page when only using WCPay Subscriptions

### ISSUE THREAD

**Issue by haszari** [Automattic/woocommerce-payments#3402]
This issue will be addressed in the Subscriptions Core repository, please post any comments related to this issue here: https://github.com/Automattic/woocommerce-subscriptions-core/issues/52

---

### Describe the bug
In the payment gateways settings screen, there's a section prompting merchant to install other gateways for more auto-renew payment options.

This should only be displayed when store has WooCommerce Subscriptions active. With WCPay Subscriptions only WCPay gateway is supported.

<img width="2074" alt="Screen Shot 2021-11-22 at 1 47 43 PM" src="https://user-images.githubusercontent.com/4167300/142786287-137b40fc-590d-4b0a-8746-c290d7ab131d.png">

Closely related to #3234 - these can probably be handled at the same time.

**Comment by shendy-a8c** [comment]
Closed by https://github.com/Automattic/woocommerce-payments/pull/3550.
