### ISSUE TITLE
Multicurrency - Price not updating in All Products block to match country of user

### ISSUE THREAD

**Issue by damiannep** [Automattic/woocommerce-payments#3406]
### To Reproduce

1. On a WC Pay test site, create a page of products using the "All Products" block.
2. Visit the page from a location for which the currency should change.
3. Notice that the currency on the page created in step 1 doesn't match the currency of the shop page.

### Actual behavior

The currency of the products in the All Products block never switches from the store currency.

### Screenshots
Tested:

Shop page: https://wcpayhappiness.mystagingwebsite.com/shop/

All products page:
![Screen Shot 2021-11-22 at 10 52 10 AM](https://user-images.githubusercontent.com/30090682/142848842-1c55951d-3d6b-46d0-a7aa-75c261338020.jpg)

 https://wcpayhappiness.mystagingwebsite.com/all-products-page/
![Screen Shot 2021-11-22 at 10 52 53 AM](https://user-images.githubusercontent.com/30090682/142848935-c007f977-e014-4b8c-9512-90b1d0f61643.jpg)

### Expected behavior
I expect the price of products/currencies to always match when browsing a site.

### Additional context
Reported in 4533075-zen

**Comment by damiannep** [comment]
I wasn't sure where to put this issue but judging from some other issues, I thought I'd start here.

**Comment by htdat** [comment]
@Automattic/sigma - may you have a look at this issue?

**Comment by ismaeldcom** [comment]
Thanks @htdat for the ping and @damiannep for creating the issue. I was able to reproduce the issue, I'll add it to our sprint work 🙂
