### ISSUE TITLE
`attach_intent_info_to_order` does things out of its responsibility

### ISSUE THREAD

**Issue by daquinons** [Automattic/woocommerce-payments#3407]
We can split [attach_intent_info_to_order](https://github.com/Automattic/woocommerce-payments/blob/60c79b029cbafc23e93606a9ad79183ec6e07a21/includes/class-wc-payment-gateway-wcpay.php#L1259) into two parts, first part will only attach it, and the second part only will include the processing part. 

When we moved that function higher in the processing flow there were unintended results because that method is also processing the payment, going out of its responsibility (see #3405 ).

This method is invoked in 7 other parts, so we need to make sure that the refactor doesn't affect those different places.

Conversation about this p1637570261077700-slack-C01B8KNUYSW

**Comment by daquinons** [comment]
When this refactor occurs it would be a good idea to revert #3405

**Comment by xlplugins** [comment]
@daquinons Thanks for making the change in #3405 , it seems fine. 
However, after the refactor the only thing to make sure with respect to our issue is tokens are successfully inserted in meta before payment_complete() runs. I suggest you please mention us once refactoring is done. 
Also, is there any ETA we could tell our customers to expect an update of WC payment with this tweak?

**Comment by daquinons** [comment]
> @daquinons Thanks for making the change in #3405 , it seems fine. However, after the refactor the only thing to make sure with respect to our issue is tokens are successfully inserted in meta before payment_complete() runs. I suggest you please mention us once refactoring is done. Also, is there any ETA we could tell our customers to expect an update of WC payment with this tweak?

👋 Hey there, sorry for the late response, I've been away.

This change will be released in 3.4, scheduled for Dec 8th.
