### ISSUE TITLE
Filtering the WooCommerce > Subscriptions table to 0 results displays confusing phrasing

### ISSUE THREAD

**Issue by james-allan** [Automattic/woocommerce-payments#3412]
#### 🛑 This is a WC Subscriptions core issue. Please track it here https://github.com/Automattic/woocommerce-subscriptions-core/issues/51

If you filter your WooCommerce > Subscriptions table in such a way that 0 results are returned, it displays the _empty state messaging_ rather than the _no results found_ message.

### To Reproduce

1. Go to **WooCommerce > Subscriptions**
2. Filter your table by searching for a string that won't exist or by filtering by a payment method you won't have subscriptions with (eg PayPal on a WCPay Subscriptions store). 
3. You should see 0 results returned and the following message. 

<img width="964" alt="Screen Shot 2021-11-23 at 11 06 53 am" src="https://user-images.githubusercontent.com/8490476/142961136-29ddcc88-2b73-43db-a3f1-32d77befa8f8.png">

### Additional context

Subscriptions core issue: https://github.com/Automattic/woocommerce-subscriptions-core/issues/51

**Comment by shendy-a8c** [comment]
Closed by https://github.com/Automattic/woocommerce-payments/pull/3550.
