### ISSUE TITLE
Add WC Pay Subscriptions flows to critical flows

### ISSUE THREAD

**Issue by haszari** [Automattic/woocommerce-payments#3422]
### Description
WC Pay maintains a list of critical flows for release testing and general QA purposes: https://github.com/Automattic/woocommerce-payments/wiki/Critical-flows

We recently shipped WC Pay Subscriptions, so this feature should be included in critical flows.

Also there are existing flows for WC Subscriptions integration, so these need to be clarified so it's clear which flows are native to WCPay and which require WC Subscriptions installed and active. 

I've started working on adapting these flows [from 3.2 testing instructions](https://github.com/Automattic/woocommerce-payments/wiki/Release-testing-instructions-for-WC-Payments-3.2.0), so I'm logging this issue for visibility and feedback :)

**Comment by haszari** [comment]
Added to milestone for visibility - this doesn't block 3.4, but we may want to adjust the flows.

**Comment by haszari** [comment]
Working on these in a dedicated file linked from main flows page: 

- https://github.com/Automattic/woocommerce-payments/wiki/Critical-flows 
- https://github.com/Automattic/woocommerce-payments/wiki/WC-Pay-Subscriptions-critical-flows-testing-instructions

Note also I have added a custom sidebar to declutter - the release testing instructions were hiding later items (like main critical flows testing doc). Everything should be linked from home page and side bar, let me know if something's inaccessible!

**Comment by haszari** [comment]
I've now adapted an initial list of critical WC Pay Subscriptions flows from the larger testing docs for WCPay 3.2 (hat tip @aprea !).

Tagging in @aprea  and @shendy-a8c  who have been involved in flows in the past, and GlobalStep testing. Can you take a look and review and feedback before we close this issue?

- [ ] Is this a good base set of critical functionality? Comment if anything is missing, or not critical.
- [ ] Are the docs for each flow clear and easy to follow? Comment, or feel free to make changes to the the wiki directly. 
- [ ] Is there anything new we should incorporate from WCPay 3.4?

When y'all are happy let's close this!

**Comment by shendy-a8c** [comment]
LGTM.

**Comment by haszari** [comment]
Thanks @shendy-a8c ! I'm going to close this issue - the flows are now documented.

I'm still open to feedback on the flows and the docs. @aprea if you have time to take a look I'd appreciate your thoughts too.

**Comment by aprea** [comment]
Hey @haszari, apologies for the late reply. I just checked the new page and it LGTM 👍
