### ISSUE TITLE
Spike: A redundant payment intent is created for every in-person payment

### ISSUE THREAD

**Issue by anu-rock** [Automattic/woocommerce-payments#3430]
We have two intents created for every IPP transaction. I'm certain that the second one (succeeded) is created by the mobile app. The first one (incomplete) seems to be created by the payments plugin, judging by the description pattern which is the same as can be found in `WC_Payments_API_Client::get_intent_description`.

### Steps to Reproduce

1. Create a new order with "Cash on delivery" as the payment method.
2. Capture payment for the above order via the Woo mobile app.
3. Visit the Stripe Dashboard at `https://dashboard.stripe.com/test/connect/accounts/<account_id>/payments/` and verify that there are two intents for the same order ID.

### Actual behavior

An extra, apparently unutilized payment intent is created.

### Screenshots

![image](https://user-images.githubusercontent.com/1288616/143543589-dbb62f91-0374-4110-848f-2c3273d2753c.png)

### Expected behavior

Only one intent should be created.

**Comment by anu-rock** [comment]
Created a new issue at #3602 to address this.

**Comment by kalessil** [comment]
Thanks, @anu-rock for looking into it!
