### ISSUE TITLE
Add a new endpoint for payment intent creation

### ISSUE THREAD

**Issue by anu-rock** [Automattic/woocommerce-payments#3431]
In order to support Wifi-only card readers for in-person payments, it is desirable to expose an endpoint that would allow the mobile app to create a server-side intent.

We could create it in `WC_REST_Payments_Orders_Controller` leveraging the existing `WC_Payments_API_Client::create_intention` method.

Reference: https://stripe.com/docs/terminal/payments/collect-payment?terminal-sdk-platform=ios#create-client-side

Related: 1279-gh-Automattic/woocommerce-payments-server
See also: pdfdoF-dj-p2

**Comment by kalessil** [comment]
@dmvrtx, I guess this landing into post-live scope? If so, please update the pproject thread.

**Comment by dmvrtx** [comment]
> @dmvrtx, I guess this landing into post-live scope? If so, please update the pproject thread.

It's already there.

**Comment by kalessil** [comment]
Awesome, thanks!
