### ISSUE TITLE
Add a new endpoint to register card readers

### ISSUE THREAD

**Issue by anu-rock** [Automattic/woocommerce-payments#3432]
Some new card readers (for in-person payments), especially the counter-top Wifi-only ones, need to be registered against a terminal location. Terminal location APIs were added in #2334.

We recently added a new controller `WC_REST_Payments_Reader_Controller`. We could add reader registration endpoint in it. So, the route to register a reader could be something like `POST /payments/readers`.

Related: 1279-gh-Automattic/woocommerce-payments-server
See also: pdfdoF-dj-p2

**Comment by kalessil** [comment]
@dmvrtx, I guess this landing into post-live scope? If so, please update the project thread.
