### ISSUE TITLE
Unable to access Subscription details when purchased via SEPA Direct Debit

### ISSUE THREAD

**Issue by csmcneill** [Automattic/woocommerce-payments#3442]
### Describe the bug
When a new subscription is purchased using SEPA Direct Debit, a merchant is unable to access the subscription details via WooCommerce > Subscription because it generates a fatal error, and the console shows a 500 error.

### To Reproduce

1. Create a subscription with [WooCommerce Subscriptions](https://woocommerce.com/products/woocommerce-subscriptions/?aff=10486&cid=1131038)
2. Enable SEPA Direct Debit as a payment option.
3. Purchase the subscription in step 1 with [a test account number](https://stripe.com/docs/testing#sepa-direct-debit).
4. Navigate to WooCommerce > Subscriptions and select the subscription purchased in step 3.

### Actual behavior
1. The subscription details do not all load properly, and you'll see a 500 error in the console.
2. You'll receive an email that a fatal error occurred on the site, and this error will show up in the fatal error logs:

```
2021-11-29T17:11:09+00:00 CRITICAL Uncaught Error: Call to undefined method WC_Payment_Token_WCPay_SEPA::get_card_type() in /srv/htdocs/wp-content/plugins/woocommerce-payments/includes/class-wc-payment-gateway-wcpay.php:2374
Stack trace:
#0 [internal function]: WC_Payment_Gateway_WCPay->{closure}(Object(WC_Payment_Token_WCPay_SEPA))
#1 /srv/htdocs/wp-content/plugins/woocommerce-payments/includes/class-wc-payment-gateway-wcpay.php(2382): array_map(Object(Closure), Array)
#2 /srv/htdocs/wp-content/plugins/woocommerce-payments/includes/compat/subscriptions/trait-wc-payment-gateway-wcpay-subscriptions.php(483): WC_Payment_Gateway_WCPay->get_user_formatted_tokens_array(140558371)
#3 /wordpress/core/5.8.2/wp-includes/class-wp-hook.php(305): WC_Payment_Gateway_WCPay->render_custom_payment_meta_input(Object(WC_Subscription), '_payment_method...', '3')
#4 /wordpress/core/5.8.2/wp-includes/class-wp-hook.php(327): WP_Hook->apply_filters('', Array)
#5 /wordpress/core/5.8.2/wp-includes/plugin.php(470): WP_Hook->do_action(Array)
#6 /srv/htdocs/wp-content/plugins/woocommerce-subscriptions/includes/class-wcs-change-payment-method-admin.php(83): do_action('woocommerce_sub...', Object(WC_Subscription), '_payment_method...', '3', Array)
#7 /srv/htdocs/wp-content/plugins/woocommerce-subscriptions/includes/admin/meta-boxes/class-wcs-meta-box-subscription-data.php(202): WCS_Change_Payment_Method_Admin::display_fields(Object(WC_Subscription))
#8 /wordpress/core/5.8.2/wp-admin/includes/template.php(1395): WCS_Meta_Box_Subscription_Data::output(Object(WP_Post), Array)
#9 /wordpress/core/5.8.2/wp-admin/edit-form-advanced.php(688): do_meta_boxes(Object(WP_Screen), 'normal', Object(WP_Post))
#10 /wordpress/core/5.8.2/wp-admin/post.php(206): require('/wordpress/core...')
#11 {main}
  thrown in /srv/htdocs/wp-content/plugins/woocommerce-payments/includes/class-wc-payment-gateway-wcpay.php on line 2374
```

### Screenshots
![Markup on 2021-11-29 at 11:20:15](https://user-images.githubusercontent.com/82999806/143913779-357be673-0608-4f63-98ee-5ef11bceab3a.png)

### Expected behavior
Merchants should be able to access a subscription purchased with SEPA Direct Debit without fatal errors or a 500 error.

### Desktop (please complete the following information):

* OS: macOS 12.0.1
* Browser: Chrome
* Version: 96.0.4664.55 (Official Build) (x86_64)

### Additional context
Reported in 32523474-hc / 4554412-zen

* WooCommerce Subscriptions: by WooCommerce – 3.1.6
* WooCommerce Payments: by Automattic – 3.3.0
* WooCommerce: by Automattic – 5.9.0

**Comment by htdat** [comment]
@harriswong - would you mind having a look at this issue? 
Relevant PR https://github.com/Automattic/woocommerce-payments/pull/1540

**Comment by htdat** [comment]
> or pointing to a team owning this?

It sounds like it's Gamma p1638258169198600/1638257980.198400-slack-C01BPL3ALGP 
I am moving it to Gamma sprint board.

**Comment by htdat** [comment]
When testing with the current `develop` branch, I am seeing this error:

```
[22-Dec-2021 04:58:00 UTC] PHP Fatal error:  Uncaught TypeError: Argument 1 passed to WC_Payment_Gateway_WCPay::{closure}() must be an instance of WC_Payment_Token_CC, instance of WC_Payment_Token_WCPay_SEPA given in /var/www/html/wp-content/plugins/woocommerce-payments/includes/class-wc-payment-gateway-wcpay.php:2612
```

That's because of the recent PR https://github.com/Automattic/woocommerce-payments/pull/3484/files#diff-bcfd303d507c33a27671935e724ee64d0df30ff2a18bb6ef4c94f28d48190124R2560. However, reverting this line/change, the same error above happens.
