### ISSUE TITLE
Outdated Payment Element beta notice in console

### ISSUE THREAD

**Issue by jessepearson** [Automattic/woocommerce-payments#3448]
If you have UPE enabled, then add a product to your cart and head to checkout, you will see the below in your console:

> You are using payment_element_beta_1, an outdated beta version of the Payment Element. To upgrade: https://stripe.com/docs/payments/payment-element/upgrade-from-beta

The [page listed](https://stripe.com/docs/payments/payment-element/upgrade-from-beta) outlines what needs to be updated in order to correct the notice.

**Comment by htdat** [comment]
Ref p1638340684236100/1638257980.198400-slack-C01BPL3ALGP
