### ISSUE TITLE
Add loan paydown transactions in transactions page

### ISSUE THREAD

**Issue by jessepearson** [Automattic/woocommerce-payments#3458]
The loan paydown and payout transactions needs to be visible and filterable in the transactions page. 

The table needs to be filterable by:

Loan ID
Transaction type: Pay down
Transaction type: Pay out

![image](https://user-images.githubusercontent.com/3295/147825911-19ed3189-5635-41e6-b8f6-aaf3516bbfc4.png)

**Comment by jessepearson** [comment]
After discussion, this may not be the best approach with how the loan payments happen. It may be better to have each payment transaction as its own row with a link to the related order, if there is one.

**Comment by tpaksu** [comment]
Updated the issue description as we won't need a separate column for the loan data, we'll show each transaction in their own row.
