### ISSUE TITLE
Tracks event not sent consistently: `wcadmin_wcpay_subscriptions_account_not_connected_publish_products`

### ISSUE THREAD

**Issue by shendy-a8c** [Automattic/woocommerce-payments#3460]
### Describe the bug
Follow up to #3449.

One of the events is not firing consistently: `wcadmin_wcpay_subscriptions_account_not_connected_publish_products`. 

#### Prerequisites
* WC Subscriptions is **not** installed / active.
* Fresh site where WCPay onboarding is **not completed** or enable `Force the plugin to act as disconnected from WCPay` setting in WCPay Dev Utils.
* Enable tracking under `WC settings > Advanced > WooCommerce.com` (/wp-admin/admin.php?page=wc-settings&tab=advanced&section=woocommerce_com).

#### Reproduce steps
* Navigate to `Products → Add New`.
* Add product name and switch the product type to "Simple subscription".
* Add subscription price.
* Click `Publish`.
* Wait for the page request to complete.
* Observe the "One more step..." modal appears and the product remains in the draft status.
* Click the "Finish setup" button.
* Complete the WCPay onboarding.
* Observe you are redirected back to the product edit page.
* Observe the product is now published.
   - The tracks event should fire some time after here. 
* Observe the toast notification "Thank you for setting up WooCommerce Payments! We’ve published your first subscription product.".

Note: tracks events can be viewed in `Network` tab in browser tools, as requests for a `gif` image file with request params for event name and props.

### Actual behavior
The event doesn't fire consistently.

**Comment by haszari** [comment]
We could remove this event - it's not essential to answer current questions, and doesn't track a user action.
