### ISSUE TITLE
Expose onboarding of test accounts to store builders

### ISSUE THREAD

**Issue by dechov** [Automattic/woocommerce-payments#3469]
If someone is setting up a store with WooCommerce Payments on behalf of the merchant, it was intended to offer them to set up a _test account_ rather than a live account.

The original solution (see change [here](https://github.com/woocommerce/woocommerce-admin/pull/3978/files#diff-41d248373517bdd47e2913031c903ec148c51c1c5c018a9331ad331574d9bd05R115)) was to show a doc link (later changed to [this URL](https://docs.woocommerce.com/document/payments/testing/dev-mode/) for the "WooCommerce Payments Test Account Setup Guide") in the WCPay onboarding task to those who select the "setting up for a client" option in WC core onboarding – but it appears to have been lost in subsequent WC Admin onboarding changes.

Since then, we have seen a number of account deletion requests from store builders that simply want to allow their clients to onboard with their own account. (Not sure how many but I've personally seen several – [here](https://wordpress.org/support/topic/testing-stripe-with-woocommerce-payments-and-cant-delete-stripe-account/#post-14914362)'s one report from the forums.)

The server currently allows re-onboarding _only_ in this one case of going from a test account to live account, which is to say that the server endpoint was already written to anticipate this case.

However (and to point out a closely related secondary issue – see also https://github.com/Automattic/woocommerce-payments/issues/666), the [aforementioned doc](https://woocommerce.com/document/payments/testing/dev-mode/) – not to mention the name of the constant itself – is oriented exclusively towards test stores, and discourages the store builder use case:

> If you are setting up WooCommerce Payments for someone else, like a client, on a store that will process real payments **you should have the site owner complete the WooCommerce Payments setup**.

> If you are setting up WooCommerce Payments on a test **site that will never need to process real payments**, you can use Dev Mode.

I believe we should:
- [ ] modify that wording on the doc
- [ ] present it (on the WCPay side now) to those who selected the "setting up for a client" option in WC core onboarding
- [ ] perhaps consider a more inviting way to create a test account (UI toggle within the flow, or at least a different constant name?)

cc @LevinMedia

**Comment by daquinons** [comment]
Closed by https://github.com/Automattic/woocommerce-payments-server/issues/2935
