### ISSUE TITLE
Error on Pay Order page with non UPE method after failed Blocks Checkout

### ISSUE THREAD

**Issue by leonardola** [Automattic/woocommerce-payments#3495]
### Describe the bug
"Your payment was not processed." Error when trying to pay on Pay order Page with non UPE method after invalid card on Blocks checkout

### To Reproduce
- With UPE inactive
- Add any product to cart
- Go to blocks checkout
- Pay with invalid card (4000000000000002)
- Go to My account > Orders > Click on Pay > Pay with Valid card (4242 4242 4242 4242) 
- The error "Your payment was not processed." will show up

### Expected behavior
"Your payment was not processed." Error should not show up and the order should be successful

**Comment by achyuthajoy** [comment]
Hey @leonardola 👋 !

I'm able to replicate this behavior. Followed the steps mentioned and can confirm that the payment is successful when paid via My Account after using an invalid card on checkout.

Can you try replicating the bug on your end? If not present we can close this issue 😄

**Comment by leonardola** [comment]
I am unable to reproduce the error too. Closing this issue.
