### ISSUE TITLE
Optimize `is_call_in_backtrace` within Multi-Currency more

### ISSUE THREAD

**Issue by jessepearson** [Automattic/woocommerce-payments#3502]
`is_call_in_backtrace` calls the `wp_debug_backtrace_summary` function in WordPress, which is resource intensive. We need to make sure that when we are using it that we actually need to be using it, meaning we should check other methods, variables, etc to see if we are at the point of needing to call the method. An example would be the change to `should_use_order_currency` in https://github.com/Automattic/woocommerce-payments/pull/3466 .

**Comment by thenbrent** [comment]
I'm looking to prioritize this for the upcoming Moltres sprint. Do we have any estimate on the negative impact of calling `wp_debug_backtrace_summary`? e.g. is it going to slow down front-end page load speed by 1 second etc. That kind of info will help me with prioritization.

**Comment by daquinons** [comment]
Thanks, @millerf! We are closing this then
