### ISSUE TITLE
Remove scheduling of product create/update from woocommerce_save_product_variation hook

### ISSUE THREAD

**Issue by chickenn00dle** [Automattic/woocommerce-payments#3510]
https://github.com/Automattic/woocommerce-payments/pull/3509

**Comment by naman03malhotra** [comment]
@chickenn00dle since this issue is referencing to #3509, can we close this?

**Comment by chickenn00dle** [comment]
Yeah! I actually don't recall opening this issue... It was likely an accident. I'll close this now. Sorry for the confusion!
