### ISSUE TITLE
Remove the feature flag _wcpay_feature_card_readers

### ISSUE THREAD

**Issue by anu-rock** [Automattic/woocommerce-payments#3512]
Related to #1440

Card Readers is a new, upcoming page that will:

* list all readers linked to an account
* allow customizing reader receipt branding/settings

A basic code implementation of the page was recently added, but the page itself is currently hidden in the WP Admin frontend until it is tested well.

Once the page is fully ready, its feature flag `_wcpay_feature_card_readers` should be removed to make the page visible (owing to restrictions imposed by the `card_present_eligible` flag).

**Comment by vbelolapotkov** [comment]
asked for feedback in p1639410804221400/1639399547.217200-slack-C02C00HCJ8J

**Comment by kalessil** [comment]
Please do not merge without group discussion.
