### ISSUE TITLE
Build WCPay release package independent of local machine.

### ISSUE THREAD

**Issue by naman03malhotra** [Automattic/woocommerce-payments#3515]
### Description
As of today, the test package which gets published to [wordpress.org](https://wordpress.org/plugins/woocommerce-payments/) and [woocommerce.com](https://woocommerce.com/products/woocommerce-payments/) during the release gets built on a local machine by woorelease, which can result in discrepancy when built on different machines/OS. We'd like the release package to be built independently of the local machine ideally using the Github Action or Docker.

Please checkout the client deployment process in FG for more context.

**Comment by htdat** [comment]
Note: currently we have this workflow to build prelease versions for our weekly testings.
https://github.com/Automattic/woocommerce-payments/blob/develop/.github/workflows/pre-release-publish-on-tag.yaml

**Comment by RadoslavGeorgiev** [comment]
@jbordonado AFAICT this is already happening in GitHub workflows. Would you like the honor of closing this issue?

**Comment by jbordonado** [comment]
Correct, we have the [Build zip file & Run smoke tests](https://github.com/Automattic/woocommerce-payments/actions/workflows/build-zip-and-run-smoke-tests.yml) workflow for this.

Executed automatically during the code freeze after the release branch is prepared.
It can also be triggered manually in case additional changes are required after the code freeze.

We can close this one
