### ISSUE TITLE
WCPay Subscriptions compatibility with Subscriptions Downloads

### ISSUE THREAD

**Issue by aprea** [Automattic/woocommerce-payments#3526]
### Description
Determine the level of compatibility between WCPay Subscriptions and [Subscriptions Downloads](https://woocommerce.com/products/woocommerce-subscription-downloads/). Then, either fix any compatibility issues (if straightforward), or work with other teams to get fixes prioritised (if more complex).

product | maintainer | status | comments
--- | --- | --- | --- 
[Subscriptions Downloads](https://woocommerce.com/products/woocommerce-subscription-downloads/) | @Automattic/helix  | 🟡 | WC Subscription Downloads doesn’t load at all. An admin notice is displayed.

Related issues:
- https://github.com/Automattic/woocommerce-payments/issues/3523
- https://github.com/Automattic/woocommerce-payments/issues/3524
- https://github.com/Automattic/woocommerce-payments/issues/3525

**Note:** Before working on this issue, please check whether any of the above issues are started/completed and work with the assignee to discuss the best approach for these compatibility issues.

### Acceptance criteria

* Determine how the extension builds on subscriptions - what functionality it adds, and if there are any differences in WCPay Subscriptions.
* Test and log issues for any fixes needed.
* Implement PRs for those fixes (if straightforward), or work with other teams to get fixes prioritised (if more complex).
* Note down any issues or opportunities with extensibility APIs. E.g. if a hook needs to be added or changed for a compatibility fix.

From there, we can build on this to provide guidance for third-party extensions integrating with Subscriptions. For example, documentation and or sample code answering questions like these:

* What behaviour can be extended and any differences between WCPay Subscriptions and WC Subscriptions.
* How to detect subscriptions functionality and initialise support code - best practice recommendations.
* How to test an extension alongside subscriptions - e.g. what flows might break.

### Additional context
Split from https://github.com/Automattic/woocommerce-payments/issues/2816

P2 pdjTHR-fI-p2

**Comment by shendy-a8c** [comment]
Linking this issue to 79-gh-woocommerce/woocommerce-subscription-downloads.
+cc DRI @brucealdridge.

**Comment by brucealdridge** [comment]
This was fixed in WooCommerce Subscription Downloads v1.1.32
No changes required to WCPay.
