### ISSUE TITLE
Apple Pay and Google Pay buttons not showing correct dollar amount on product page

### ISSUE THREAD

**Issue by rlmajcom** [Automattic/woocommerce-payments#3536]
### Describe the bug
Using a variable subscription product of WooCommerce Subscriptions, say with options for $4, $5, and $9 per month, the Apple Pay and Google Pay (aka Express Checkout) buttons always show the $4 amount.  I am using WooCommerce, WooCommerce Payments and WooCommerce Subscriptions.

### To Reproduce
1.  Go to a Woo product page that has several payment levels.
2.  Select a non-default option from the product drop-down (e.g. $9)
3. Click G Pay or Apple Pay.  $4 or some other default will be shown in the Apple Pay / G Pay preview rather than the $9 amount you just picked.
4. If you complete the purchase anyway, the $9 amount (whatever you picked in step 2 above) will be correctly charged to your Apple Pay/ G Pay, so this appears to be a display-only issue on the product page.
Note this issue is specific to the Apple Pay and Google Pay buttons on the Product page, NOT the Checkout Page. 
Tested on both iPhone Safari with Apple Pay and desktop Chrome with G Pay.  Same behavior in both instances.
Not clear if this is a WooCommerce Payments bug and/or a WooCommerce Subscriptions bug.

### Expected behavior
Dollar amount shown in G Pay / Apple Pay should stay synchronized with the amount picked by the user from the product drop-down.

### Desktop (please complete the following information):

* OS: [e.g. iOS]
* Browser [e.g. chrome, safari]
* Version [e.g. 22]

### Smartphone (please complete the following information):

* Device: [e.g. iPhone6]
* OS: [e.g. iOS8.1]
* Browser [e.g. stock browser, safari]
* Version [e.g. 22]

**Comment by brianyu28** [comment]
I've reproduced this for variable subscription products (it doesn't seem to happen for variable non-subscription products), so I'm adding the WCPay Subscriptions label here.

**Comment by jessy-p** [comment]
@brianyu28  I've tested this with both WCPay Subscriptions and WooCommerce Subscriptions and a variable subscription product. I used Google Pay on Chrome on the product page, and it seems to be working as expected now. i.e. if I choose a variation from the dropdown, there is an ajax refresh. When I click on the Google Pay button after that, I get the updated price on the Google Pay preview. Maybe some other code change has fixed this issue, could you test and confirm that it's not reproducible?

**Comment by jessy-p** [comment]
Thanks @brianyu28 I am able to replicate the issue. It was a mistake I made while setting up the product.
