### ISSUE TITLE
Indicate number of disputes needing review in sidebar navigation

### ISSUE THREAD

**Issue by dechov** [Automattic/woocommerce-payments#354]
I recall @LevinMedia mentioning that we should have a little number badge next to Disputes in the nav, indicating the number of disputes that currently need review, like this:

<img width="176" alt="disputes-nav-count-mock" src="https://user-images.githubusercontent.com/1867547/73108016-3ebccd80-3ecd-11ea-8c61-68d06986ac61.png">

[Here](https://github.com/woocommerce/woocommerce/blob/99d957dd2d3f68be4133f5f71b5775522a742fac/includes/admin/helper/class-wc-helper-updater.php#L290-L303) is an example of how WooCommerce core adds this count to the sidebar.

We'll have to expose the number that need review via the WCPay API, though I'm not sure how and when we want to compute that.

Most likely we'll listen on dispute-related webhooks and insert/update corresponding records on the server, though an alternative solution in the short-term would be to track the number of such disputes in a new accounts table column.

Or it might be best to keep track of this number on the store backend, avoiding the extra WPCOM request on page load.

**Comment by dechov** [comment]
Related to https://github.com/Automattic/woocommerce-payments/issues/280

**Comment by haszari** [comment]
If we implement this we'll need something like #4124 so when the merchant clicks the badge, they can easily drill down to the highlighted disputes that need a response.

Not sure if that blocks this badge from shipping, but adding `needs design` label for now to indicate that this might need some design attention.
