### ISSUE TITLE
"The link you followed has expired". Thank you page (order-received) doesn't load after trying to make a payment.

### ISSUE THREAD

**Issue by jordan-enev** [Automattic/woocommerce-payments#3552]
### Describe the bug

1. A week ago - we connected our website with Wordpress and verify our business details to Stripe.
2. Yesterday I enabled WooCommerce payments + Multi-currency option for the first time.
3. When I tried to make both real and a test purchase via card (enabling Test mode and using a test VISA card) - both times I'm redirected to Thank you page (order-received), but receiving the below error - "The link you followed has expired".
4. Both Orders were successfully created and their statuses were set to Paid.
5. There aren't any erros in the log files - WooCommerce / Wordpress / PHP. In WooCommerce log - we only have a log file of the completed purchase.
6. When I disable WooCommerce Payments plugin, the bellow URL starts showing the Thank you page. 

Here is the full URL query: https://mydomain.com/checkout/order-received/4085/?key=wc_order_C9nnHk1t8Bme6&alg_wc_ev_activate_account_message=100&order_id=4085&wc_payment_method=woocommerce_payments&_wpnonce=9d5b7323a5&save_payment_method=no&payment_intent=pi_****&payment_intent_client_secret=pi_****_secret_****&redirect_status=succeeded

### Screenshots

**The link you followed has expired:**
![The link you followed has expired](https://user-images.githubusercontent.com/3863376/146795223-011e1821-54f2-4f18-bce9-8b65abd13001.jpg)

**The payment was successful:**
![New Project (4)](https://user-images.githubusercontent.com/3863376/146799252-6f3f86a4-e148-4212-a718-22cedfc0575c.jpg)

### Desktop (please complete the following information):
* OS: Ubuntu
* Browser: Chrome
* Version: Version 95.0.4638.69 (Official Build) (64-bit)

### Additional context

* WooCommerce version: 5.5.0
* Wordpress version: 5.7.2
* WooCommerce payments: 3.4.0
* Wordpress boilerplate: roots/bedrock

**Comment by jessy-p** [comment]
Prioritizing to look into `check_admin_referer` of `maybe_process_upe_redirect` in UPE payments, in case there is any issue.

**Comment by jessy-p** [comment]
This issue impacts  checkout UI, so assigning to Heisenberg (based on team responsibilities Pc2DNy-3z-p2) @FangedParakeet. Assigning as part of Gamma Triage process PcreKM-yM-p2.

Tagging as part of re-evaluating older issues in the backlog, please have a look and close if no longer relevant.

**Comment by pierorocca** [comment]
@jordan-enev apologies this is now 3 years old. Is this issue still relevant for your?

**Comment by gpressutto5** [comment]
I followed the reported steps but couldn’t reproduce the error. I believe this is an old issue that no longer occurs, so I’m closing it. Feel free to reopen if the error still happens.
