### ISSUE TITLE
Custom email receipt for terminal card reader

### ISSUE THREAD

**Issue by anu-rock** [Automattic/woocommerce-payments#3558]
Currently, email receipts are sent out by Stripe on the successful completion of payment (see #1210). A screenshot of the receipt template can be found here: https://stripe.com/docs/terminal/features/receipts#prebuilt.

We have limited control over what we can customize in Stripe’s receipt template. Eg. Stripe branding (like seen in the footer) cannot be changed. For full control over email receipts, we must design and implement them from scratch.

We will need to:

- Create an HTML/CSS template for WCPay-branded email receipt*
- Add function(s) to combine template and relevant data to send out email receipts*
- Trigger sending of email on payment capture (see `WC_Payment_Gateway_WCPay::capture_charge`)

_\*See #3433 for reference implementation of print receipts_

**Comment by LevinMedia** [comment]
@anu-rock is there any way we could offload this template to the WooCommerce email system, and send the customer the receipt (order confirmation email) that they'd get if they placed an order online at the same store?

**Comment by anu-rock** [comment]
@LevinMedia That sounds like a good idea. We'll explore more on this once we start working. If WooCommerce's email system cannot be leveraged, we'll fall back to our custom template.

**Comment by anu-rock** [comment]
Created a spike at #3640 to validate David's suggestions.

**Comment by anu-rock** [comment]
@LevinMedia We'll be picking up the aforementioned spike soon (using Woo's emailing system). I'm wondering whether we would need a design/template if are indeed able to leverage Woo's email.

**Comment by LevinMedia** [comment]
Hi @anu-rock we should be able to leverage the built in order confirmation email template.

**Comment by mgascam** [comment]
@anurag After [this spike is closed](https://github.com/Automattic/woocommerce-payments/issues/3640) we determined that we will be able to reuse / extend the WooCommerce email capabilities. The next steps would be:

- Extend the existing 'new order' HTML/CSS template for email receipt
- Add function(s) to combine template and relevant data to send out email receipts. Please check the spike for more details about this
- Trigger sending of email on payment capture (see WC_Payment_Gateway_WCPay::capture_charge)
