### ISSUE TITLE
Terminal card reader print receipt branding

### ISSUE THREAD

**Issue by anu-rock** [Automattic/woocommerce-payments#3559]
Building upon the print receipt template created in #3224, we need to add:

* A “Powered by WooCommerce” message
* Merchant's logo

**Comment by anu-rock** [comment]
@LevinMedia What are your thoughts about this?

**Comment by LevinMedia** [comment]
Hi @anu-rock I've updated the figma file the printed template to include the logo At the very top, and the Powered by WooCommerce at the very bottom. Here's a screen shot of the update:

<img width="318" alt="Screen Shot 2022-01-19 at 9 26 28 AM" src="https://user-images.githubusercontent.com/4500952/150182692-f48e7324-739b-4d91-9cbc-c5d005824c85.png">

**Comment by anu-rock** [comment]
Thanks, @LevinMedia. This looks great!
