### ISSUE TITLE
Display a preview of uploaded logo and icon on terminal card reader receipt settings page

### ISSUE THREAD

**Issue by anu-rock** [Automattic/woocommerce-payments#3564]
Pre-requisite: #3595

Currently, the upload logo and icon functionality works but no previews of the uploaded images are shown. Previews are good for historic reference and correcting accidentally uploaded images.

**Comment by anu-rock** [comment]
Hey @LevinMedia 👋 The team is soon going to pick this up once the prereqs are complete. We look forward to your inputs. This should be a quick one :)

**Comment by LevinMedia** [comment]
@anu-rock I'll have to put together designs for this, since we don't have a component that does this yet. For the time being, can you use the upload component that we're using in the disputes section of WCpay?

**Comment by anu-rock** [comment]
> I'll have to put together designs for this, since we don't have a component that does this yet.

Sounds great!

> For the time being, can you use the upload component that we're using in the disputes section of WCpay?

That's what we are using at the moment. Uploading files works fine. It's just that it feels a bit unintuitive since the users cannot preview their previously uploaded images.

If it'll take you some time to put together designs for this, we can add a reasonable enough preview in the interim.
