### ISSUE TITLE
Consistently use namespaces

### ISSUE THREAD

**Issue by vbelolapotkov** [Automattic/woocommerce-payments#3581]
This part of #611 deserves own issue and might even become an epic after initial review.

Anyway, it's a good idea to consistently use namespaces in the plugin codebase.

**Comment by RadoslavGeorgiev** [comment]
@vbelolapotkov we took a look at this issue during the prioritization call. The current set of classes we have within `includes` are not strictly marked as internal, and changing namespaces there should involve a long deprecation process in addition to the significant required effort.

We are introducing a new `src` directory as a part of the Payment Process Re-engineering, and PR authors will be able to gradually move classes into the new structure soon, potentially replacing them with a facade for backwards compatibility.

I'm closing this issue for now, feel free to reopen it in case it was misjudged.
