### ISSUE TITLE
The currency name in the Overview card title is not translated

### ISSUE THREAD

**Issue by diegocurbelo** [Automattic/woocommerce-payments#3593]
### Describe the bug
The currency name in the Overview card title is not translated; it's always in english.

The problem is here (the translation strings extractor does not support variables):
https://github.com/Automattic/woocommerce-payments/blob/7e5c7186df90081ccbd2f8077387b30cd7ddf063/client/utils/currency/index.js#L34-L35

One possible solution would be to move the `__()` function should be used here instead:
https://github.com/Automattic/woocommerce-payments/blob/7e5c7186df90081ccbd2f8077387b30cd7ddf063/client/utils/currency/index.js#L10-L21

### To Reproduce

1. Go to **Settings** and change the **Site Language** to any supported languages.
2. Go to **Dashboard > Updates** and click **Update translations** (this will be shown in the selected language).
3. Go to **Payments > Overview** and verify that the currency name in the card title is not translated.

### Actual behavior
The currency name in the Overview card title is not translated; it's always in english.

### Screenshots
<img width="726" alt="Screen Shot 2022-01-03 at 18 20 21" src="https://user-images.githubusercontent.com/407542/147982731-93ab4c03-9c68-4836-8e6c-9f756c1befb4.png">

### Expected behavior
The currency name should be translated.

**Comment by dechov** [comment]
Just pointing out that this doesn't only affect the overview page – that `formatCurrencyName` util is used in the transaction and deposit currency filtering UI as well.
