### ISSUE TITLE
Add an endpoint to retrieve an uploaded file

### ISSUE THREAD

**Issue by anu-rock** [Automattic/woocommerce-payments#3595]
Currently, there's an endpoint to upload a file that until recently was used on the new dispute form for upload evidence functionality. Now, the [card reader receipt settings page](https://github.com/Automattic/woocommerce-payments/issues/3212) also uses it to upload a merchant's icon and logo.

Until now, we didn't need to preview uploaded files. But previewing files on the receipt settings page is highly desirable. For this, we'll need to add a new endpoint to retrieve uploaded files.

I suggest that we create a new controller - `WC_REST_Payments_Files_Controller` - to add the new endpoint.

**Bonus:** The file upload endpoint `POST /payments/file` is presently inside `WC_REST_Payments_Disputes_Controller`, which made sense when it was the only place where file upload functionality was being used. Now that we have more consumers of this API, IMHO we should move this endpoint into the new Files controller. That will require us to refactor all usages of the endpoint:

* https://github.com/Automattic/woocommerce-payments/blob/d184f4611a2db4bb67608092cba9427c022b7e9b/includes/wc-payment-api/class-wc-payments-api-client.php#L787

* https://github.com/Automattic/woocommerce-payments/blob/8613c7a8c4b6d15a3e9642d0b3ca085a8e2cd5af/client/card-readers/settings/file-upload.js#L17

**Comment by brianyu28** [comment]
@dpaun1985 I started looking into this and noticed that you've already begun work on the server side of this. If you were also planning to handle the client, I'm happy to unassign myself from this one instead.

**Comment by dpaun1985** [comment]
> @dpaun1985 I started looking into this and noticed that you've already begun work on the server side of this. If you were also planning to handle the client, I'm happy to unassign myself from this one instead.

Hey, yes I almost finished the server side and I wanted to start the client side tomorrow. But if you want, you can start working on it.

**Comment by brianyu28** [comment]
Sure, no problem, I'll unassign myself here!
