### ISSUE TITLE
Add filters to modify the css styling for credit card fields

### ISSUE THREAD

**Issue by melek** [Automattic/woocommerce-payments#3604]
### Description
There are no filters to manually modify the fields on WooCommerce Payments UPE or legacy card fields. 

Currently, WCPay fields use Stripe's Universal Payment Element (UPE) as opposed to the previous card element and scans fonts and styles from existing inputs on the page in order to match existing themes as much as possible - but for some users they will want more control over the display.

For Legacy checkout, WC Pay lacks an equivalent to the Stripe plugin's `wc_stripe_elements_styling` filter ([described in the Stripe docs here](https://woocommerce.com/document/stripe-styling-fields/#section-4)), which allows site owners to add their own styling to the legacy form. In other words, disabling UPE doesn't allow for more styling options, unlike Stripe.

### Acceptance criteria
Having a filter to either change the CSS selector used to compute styles and/or a filter to manually set styling properties for the Stripe element.

Though I'm sure some developers would like this for the legacy fields, I think it would be acceptable to focus on the UPE for this request.

### Dev notes
For reference, Stripe's card element allows styling options in a [different format](https://stripe.com/docs/js/appendix/style) to the newer [UPE styling format](https://stripe.com/docs/stripe-js/appearance-api#rules), so it's not trivial to copy the legacy filter over the the new checkout. 

#1960 would allow merchants to choose the CSS selector that we use to dynamically scan CSS properties; however, this would still not allow merchants to manually set individual properties themselves, without changing the theme.

### Additional context
* 4647359-zen
* p1640947060027100-slack-C7U3Y3VMY

**Comment by aheckler** [comment]
4849853-zen

**Comment by kaushikasomaiya** [comment]
5554691-zen

**Comment by ryanr14** [comment]
In the ticket below, we'd benefit from having this filter. Just to make things a bit easier to style.

6029140-zen

**Comment by csmcneill** [comment]
[WPorg thread](https://wordpress.org/support/topic/how-change-input-text-color/)

**Comment by csmcneill** [comment]
https://github.com/Automattic/woocommerce-payments/issues/5958

**Comment by csmcneill** [comment]
p1692046623834939-slack-C0E1AV8T0

**Comment by eoinsav** [comment]
We have a site with a dark blue background, which makes the grey text hard to read (card number, expiration, cvc). It would be great if we had more control over the color of that text or if it could autodetect when there is darker text on a dark background.

<img width="600" alt="263425334-e1beaf24-730d-4918-9c27-4feab83fd19b" src="https://github.com/Automattic/woocommerce-payments/assets/35590156/f1eb839c-21c2-4d0a-ac66-b41cc8e64185">

**Comment by seanbelly** [comment]
6775079-zd-a8c
Another ticket here.

**Comment by grig-23** [comment]
7138169-zen

**Comment by CGA8C** [comment]
7137973-zen

**Comment by ryanr14** [comment]
7193964-zen

**Comment by shameemreza** [comment]
Another report here: 7240520-zen

**Comment by thuautp** [comment]
Reported in 7256441-zen

**Comment by kdingsa8c** [comment]
Reported in 7252783-zd-a8c

**Comment by shameemreza** [comment]
Another report here: 7275900-zen.

**Comment by csmcneill** [comment]
Once this is live, we can update the following feature request: https://woo.com/feature-request/style-credit-card-fields/

**Comment by battouly** [comment]
Another one here: 7328330-ZD

**Comment by FangedParakeet** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Heisenberg-63586f2ec60359001310fa6a/issues/Automattic/woocommerce-payments/3604?planning-poker) with Zenhub @frosso
