### ISSUE TITLE
Allow testing of payments on live site

### ISSUE THREAD

**Issue by jobthomas** [Automattic/woocommerce-payments#361]
Feature request.

During the demo of @LevinMedia, I saw that the data changed when he switched from live mode to test mode. This is great!

It also made me think further. One of the bigger challenges we currently have with supporting payment gateways is that we can't test payments on a live site unless we're using real money. The only other option is to create a staging/test site.

So this is the feature request.

**Allow for an admin to enable test mode on WooPay while customers on the front end can still use the live mode.**

A bit similar to how [Health Check](https://wordpress.org/plugins/health-check/) works with disabling plugins/theme but for payments. 

@WillBrubaker has been toying around with this for Stripe - see p6q7sZ-6Dx-p2#comment-19632 - this whole post is by the way a good read as background for why I'm requesting this feature. 

cc @allendav (had a quick chat with him about this)

(ccing Ohana members @madeincosmos @Luminus @johndcoy @jessLundie @treibalen @grigorijurasov)

**Comment by jessepearson** [comment]
I don't have an exact date or PR for when test mode was added, but it exists in the current version, so I am closing this issue.
