### ISSUE TITLE
Updated UPE fails to load on block checkout

### ISSUE THREAD

**Issue by brianyu28** [Automattic/woocommerce-payments#3613]
### Describe the bug

Now that we've moved to the non-beta version of UPE (#3534), I'm getting an error "The checkout has encountered an unexpected error." when loading UPE on a block checkout page.

### To Reproduce

1. Enable UPE.
2. Install the WooCommerce Blocks plugin.
3. Create a new page with a checkout block.
4. Add a product to the cart.
4. Visit the page with the checkout block.

### Actual behavior

I observe the error "The checkout has encountered an unexpected error." In the console, I see:

```
Uncaught IntegrationError: In order to create a payment element, you must pass a valid PaymentIntent or SetupIntent client secret when creating the Elements group.
```

### Screenshots

<img width="1392" alt="Screen Shot 2022-01-10 at 5 03 53 PM" src="https://user-images.githubusercontent.com/16066224/148846276-8e3738ed-b578-4d45-95e8-d68964a64a40.png">

### Expected behavior

UPE loaded without errors.

### Desktop (please complete the following information):

* OS: [e.g. iOS]
* Browser [e.g. chrome, safari]
* Version [e.g. 22]

### Smartphone (please complete the following information):

* Device: [e.g. iPhone6]
* OS: [e.g. iOS8.1]
* Browser [e.g. stock browser, safari]
* Version [e.g. 22]

**Comment by brianyu28** [comment]
This may have actually been a configuration issue on my end, after trying this on a new setup I'm no longer reproducing this error. Closing for now.

**Comment by aheckler** [comment]
Possibly related: https://wordpress.org/support/topic/error-sorry-you-cannot-access-this-resource/
