### ISSUE TITLE
Local testing environment error `sed: 1: "/var/folders...": invalid command code f`

### ISSUE THREAD

**Issue by jessepearson** [Automattic/woocommerce-payments#3632]
### Describe the bug
When trying to run tests, or set up test site, error is given:

```
$ bin/install-wp-tests.sh wcpay-tests root root
Downloading WordPress 5.8.3 (en_US)...
md5 hash verified: 9abc51309a31a0d5846ec40ce475cb86
Success: WordPress downloaded.
mysqladmin: [Warning] Using a password on the command line interface can be insecure.
mysqladmin: [Warning] Using a password on the command line interface can be insecure.
mysqladmin: [Warning] Using a password on the command line interface can be insecure.
Success: Generated 'wp-config.php' file.
sed: 1: "/var/folders/g9/jxpj_7d ...": invalid command code f
```

### To Reproduce
Run `bin/install-wp-tests.sh`
It doesn't seem to happen to everyone, so it may be dependent on the environment. 

### Additional context
Seems to have been introduced in this PR: https://github.com/Automattic/woocommerce-payments/pull/3479

**Comment by haszari** [comment]
My understanding of the test suite is that it is usually run inside a container, so we can control the environment (and isolate it).

Those `sed` commands are adjusting settings in `wp-config.php`, so it makes sense to me that we'd run the suite inside a container, and that it's potentially ok to assume a particular flavour of the `sed` command. 

@jessepearson Are you running this on your host OS or in a dedicated testing container?

cc @mattallan @james-allan  who are also experiencing this issue.

Alternatively, perhaps we can dig into the [rationale for this change](https://github.com/Automattic/woocommerce-payments/pull/3479/files). @kalessil, can you clarify why we need to change the MySQL config, and if there are any alternative workarounds we could use?

**Comment by jessepearson** [comment]
@haszari I am running the client in Valet and not in Docker due to limitations found with using Docker. From what I have heard, as well, Docker and M1 MacBooks do not work well together.

**Comment by KarlisJ** [comment]
@jessepearson You can install [gsed](https://formulae.brew.sh/formula/gnu-sed) and add it to the path to use `gsed` as a replacement of `sed`. This helped me on M1.

**Comment by jessepearson** [comment]
@KarlisJ Thanks for the tip. Presently I do not have a M1 MacBook, I was just noting what I had heard from teammates. 

What I currently do is just comment out those `sed` lines in the setup file whenever I need to run the install file again.

**Comment by kalessil** [comment]
@haszari: MySQL default error level was changed in PHP 8.1 and the change aligns the level along with all PHP versions.

It's also a good reminder that the script is intended for use in the dockerized environment, hence IMO we don't need to address this.

**Comment by ismaeldcom** [comment]
I think this issue makes sense because we already supported GNU and macOS `sed` until now. And only the mentioned change breaks the compatibility.

There is a variable called `ioption` that we use for this:
https://github.com/Automattic/woocommerce-payments/blob/0fd92cf70a3d02e24f6313ad73fef26fa336fc9b/bin/install-wp-tests.sh#L135-L140

Anyway, is not a big deal for those who use a local setup, as it can be solved with `gsed` like @KarlisJ  mentioned 🙂

**Comment by kalessil** [comment]
:+1: , on it!

**Comment by kalessil** [comment]
@jessepearson, I created a PR that addresses this. Let me know please if it solved the issue for you.
