### ISSUE TITLE
Subscriptions with intervals over one year not allowed even if the Subscriptions extension is active

### ISSUE THREAD

**Issue by billrobbins** [Automattic/woocommerce-payments#3648]
### Describe the bug
WooCommerce Payments' subscriptions can't have a renewal interval longer than one year.   With the Subscriptions extension active, this limitation remains.  

### To Reproduce

1. On a site with WC Pay subscriptions enabled, install and activate the WooCommerce Subscriptions extension.
2. Edit/create a subscription product and try to add a renewal interval longer than one year.
3. Update the product and notice the error message saying the interval must be one year or less.
4. Disable the WooCommerce Subscriptions extension.
5. Disable WC Pay subscriptions.
6. Enable the WooCommerce Subscriptions extension again.
7. Edit/create a subscription product and try adding a renewal interval longer than one year.  Notice there is no error message now.

### Actual behavior
It's not possible to have a subscription interval longer than one year if WC Pay Subscriptions were enabled at the time WooCommerce Subscriptions was enabled.  

### Expected behavior
I expect that enabling the WooCommerce Subscriptions extension would allow terms longer than one year.  

### Desktop (please complete the following information):

* OS: MacOS
* Browser: Chrome
* Version: 97.0.4692.71

### Additional context
4685596-zen

**Comment by jrick1229** [comment]
Just noting that I was able to duplicate this as well on my own JN site.
