### ISSUE TITLE
UPE: Sometimes order notes don't get properly updated

### ISSUE THREAD

**Issue by dmallory42** [Automattic/woocommerce-payments#3649]
### Describe the bug

As described in #3624, there are some cases where an order would not have the corresponding transaction. This will be fixed by #3624, however as mentioned in the comments there is an additional problem where the WCPay specific order notes will not get correctly added for an order which meets these conditions. 

The fix would be as described in this comment from the PR:

> However, since we want to ship this quickly, I wonder if there's even a need to change that line, still rely on the order status, and make the change separately.

> If the duplicate notes are a concern (I see that process_redirect_payment does some extra things, but looks like there's no harm in doing them again), we could modify the update_order_status_from_intent to check if the intent status on the order is already the same as the status passed in and return early if so. This would make the function idempotent and allow us to call it repeatedly with the same intent data and order.

### To Reproduce

- Run `npm run listen` on your local server
- Make an order using UPE checkout (may need to be using a newly added card)
- Add a breakpoint to the first line of `process_redirect_function` in the UPE Payment Gateway code and wait until it gets hit.
- Wait until the `payment_intent.succeeded` and `charge.succeeded` webhooks get run (they should appear in the listener console window).
- Continue running the code.
- Check the order notes in WP Admin, you should see that no note "Payment of $xx.xx has been successfully completed using WooCommerce Payments" has appeared.

### Actual behavior

The note doesn't appear in the Order notes section.

### Desktop (please complete the following information):

* OS: [e.g. iOS]
* Browser [e.g. chrome, safari]
* Version [e.g. 22]

### Smartphone (please complete the following information):

* Device: [e.g. iPhone6]
* OS: [e.g. iOS8.1]
* Browser [e.g. stock browser, safari]
* Version [e.g. 22]

**Comment by jessy-p** [comment]
This is working now and order notes are getting updated. Discussed with @jessepearson  and this was closed by work done on #3675.
