### ISSUE TITLE
Listed rate fees appear incorrect

### ISSUE THREAD

**Issue by billrobbins** [Automattic/woocommerce-payments#3661]
### Describe the bug
In WooCommerce Payment settings, the rate is listed next to the payment method.  It displays as 4.9% + $0.30 which is higher than the quote rates.  The tooltip explains that this includes additional fees that may not apply.  If the user doesn't click on the rate, they will believe their fees will be much higher.

### To Reproduce
1.  Go to Payments > Settings.
2. Look at the list of available payment methods.
2.  Notice the quoted rate includes possible fees that may not apply

### Screenshots
<img width="732" alt="rate" src="https://user-images.githubusercontent.com/1138631/150014631-abb676ce-a3dd-4cab-a3a9-4d6546f3dc76.png">

### Expected behavior
I expect rates to be accurate and transparent but not make it appear as these fees are going to apply on every order.

**Comment by LevinMedia** [comment]
Thanks for logging this one @billrobbins - another issue regardin the same bug was created [here](https://github.com/Automattic/woocommerce-payments/issues/3666) and I already followed up there, so i'm going to close this issue in favor of that one
