### ISSUE TITLE
Fee Display Causing Confusion for Merchants

### ISSUE THREAD

**Issue by dmallory42** [Automattic/woocommerce-payments#3666]
### Description

While on janitorial, I've encountered two instances of merchants who are confused by how we display credit card fees in WCPay. I wanted to open an issue for discussion and consideration of whether we should adjust how we display this.

Links to the relevant issues:
p1642143941000300-slack-C7U3Y3VMY 
p1642564542115300-slack-C7U3Y3VMY 

In both instances, merchants who were only selling domestically saw the following:

<img width="1009" alt="Screenshot 2022-01-19 at 10 21 44" src="https://user-images.githubusercontent.com/11770181/150111534-98e561af-77a6-4af1-a731-80e0bfb403c8.png">

The merchants were both only selling domestically, and were confused at why the rate was so high (it should be 2.9% + $0.30 in both the US and Canada). They also thought it may somehow be related to the new checkout experience.

The rate displayed on the interface includes international charges, and while a breakdown can be displayed by hovering over the rate, both merchants did not realise this and thought this rate was too high/incorrect. I worry this could put some merchants off, as in this case the merchant asked us about the rate, but other merchants may see this rate and think it is a blocker to using WCPay.

I wonder whether we should either:
a. Only display the domestic rate if the user is *not* using Multi Currency
b. Display the rate in a way that makes it more clear what the *domestic* rate is for the user's country, with some additional design to show that additional rates would be incurred for international payments.

Would appreciate any thoughts on this. Thanks!
 
cc @LevinMedia @jarekmorawski

**Comment by LevinMedia** [comment]
Thanks for noting this, @dmallory42 I'll put some thought into this today - I think the latter will be the approach we take here.

**Comment by LevinMedia** [comment]
@dmallory42 I think the pill should always show the base rate for a payment method, I've added a "From" label to the front of it to further clarify that's the "base" rate. 

On hover the fees are broken into two sections - the top shows the base rate, and below, each additional component of the fee is listed. 

<img width="1180" alt="Screen Shot 2022-01-19 at 12 27 05 PM" src="https://user-images.githubusercontent.com/4500952/150208887-33badbf4-7422-476d-a305-7ca38889b66f.png">

We should give this issue high priority cc @vbelolapotkov

**Comment by apmwebdev** [comment]
More confusion about this in 4727098-zd-woothemes

**Comment by thisissandip** [comment]
Another one: 4754909-zen

**Comment by simplysaru** [comment]
Another one in 4946726-HC. Screenshot is [here](https://drive.google.com/file/d/1QeFtMvnpKMCZnnTNPt77ywmPET5IkL5B/view).

**Comment by zmaglica** [comment]
The issue is well described, but solution/approach in addressing the issue is not yet described. I asked for more details [here](https://a8c.slack.com/archives/CGGCLBN58/p1646318023018419).

**Comment by csmcneill** [comment]
4833606-zen

**Comment by thesacredpath** [comment]
Another confused user here: 34715741-hc
