### ISSUE TITLE
"Save payment information" checkbox shows for non-reusable methods on block checkout

### ISSUE THREAD

**Issue by jessepearson** [Automattic/woocommerce-payments#3667]
### Describe the bug
The "Save payment information to my account for future purchases." box to save a payment method for a user shows on the block checkout when a method that is not reusable is selected.

### To Reproduce

1. Enable _giropay_ under Payments > Settings.
  2. This _should_ have enabled Euros in Multi-Currency automatically, but if not, go to WooCommerce > Settings > Multi-Currency and enable Euros as an additional currency.
3. Add item to your cart and go to the page with the checkout block.
  4. If you do not have a page with the checkout block, create a new page and add a checkout block. You may need the WooCommerce Blocks plugin installed.
5. Under _Use another payment method_ select _giropay_.
6. The "Save payment information to my account for future purchases." box will show and it should not.

### Screenshots
![Markup 2022-01-19 at 08 38 53](https://user-images.githubusercontent.com/4634416/150132704-245f0549-cd4f-4ded-b11e-0b98109384eb.png)

### Expected behavior
* For the checkbox to hide for methods that cannot be reused.

### Additional context
Related issues:
* https://github.com/Automattic/woocommerce-payments/issues/3670
* https://github.com/Automattic/woocommerce-payments/issues/3671

**Comment by dechov** [comment]
Just noticed this today and was going to open an issue. For reference, the relevant shortcode checkout code is [here](https://github.com/Automattic/woocommerce-payments/blob/3a95b2f55efc88fb12eedff8c142c3c5ae01e4da/client/checkout/classic/upe.js#L354), and the equivalent block checkout handler is [here](https://github.com/Automattic/woocommerce-payments/blob/3a95b2f55efc88fb12eedff8c142c3c5ae01e4da/client/checkout/blocks/upe-fields.js#L145-L150).

Also, this isn't the core issue but it shows me two error notices when checking that box for a non-reusable method [[screenshot](https://user-images.githubusercontent.com/1867547/150221253-94c6488d-5206-4898-bfc4-78f0903e1ad1.png)].

**Comment by malithsen** [comment]
> Also, this isn't the core issue but it shows me two error notices when checking that box for a non-reusable method

Just noting that this was [fixed](https://github.com/woocommerce/woocommerce-gutenberg-products-block/pull/5476) on the checkout block and is included in the most recent [release](https://github.com/woocommerce/woocommerce-gutenberg-products-block/releases/tag/v6.8.0).
