### ISSUE TITLE
Saving payment methods in UPE not working correctly on block checkout

### ISSUE THREAD

**Issue by jessepearson** [Automattic/woocommerce-payments#3670]
### Describe the bug
If there is a method that allows reuse, and a method that does not allow reuse enabled, you are not able to save the reusable method when in the block checkout and using UPE.

### To Reproduce

* Enable _giropay_ and _SEPA_ under Payments > Settings.
  * This _should_ have enabled Euros in Multi-Currency automatically, but if not, go to WooCommerce > Settings > Multi-Currency and enable Euros as an additional currency.
* Add item to your cart and go to the page with the checkout block.
  * If you do not have a page with the checkout block, create a new page and add a checkout block. You may need the WooCommerce Blocks plugin installed.
* Under _Use another payment method_ select _SEPA_ and enter `AT611904300234573201`.
  * Other test numbers available here: https://stripe.com/docs/testing#sepa-direct-debit
* Select the _Save payment information to my account for future purchases._ box.
* Upon clicking _Place Order_ an error will show:

> Error: `setup_future_usage` cannot be used with one or more of the values you specified in `payment_method_types`. Please remove `setup_future_usage` or remove these types from `payment_method_types`: ["giropay"].

### Expected behavior
Reusable payment method should be able to be saved.

### Additional context
Related issues:
* https://github.com/Automattic/woocommerce-payments/issues/3667
* https://github.com/Automattic/woocommerce-payments/issues/3671

**Comment by RadoslavGeorgiev** [comment]
@achyuthajoy could you add an estimate to this issue when you figure out which approach to take?

**Comment by achyuthajoy** [comment]
@RadoslavGeorgiev Estimated added.
