### ISSUE TITLE
UPE payment methods saved do not display properly in block checkout

### ISSUE THREAD

**Issue by jessepearson** [Automattic/woocommerce-payments#3671]
### Describe the bug
If a UPE method, like _SEPA_, is saved to the customer's account, it does not show correctly in the block checkout payment method selector.

### To Reproduce

* Enable _SEPA_ under Payments > Settings.
  * This _should_ have enabled Euros in Multi-Currency automatically, but if not, go to WooCommerce > Settings > Multi-Currency and enable Euros as an additional currency.
* Save SEPA account to your customer account in one of two ways:
  * Add item to your cart and go to the classic checkout page, select _SEPA_, enter the account, and choose _Save payment information to my account for future purchases._, then check out.
  * Go to My Account > Payment Methods, and add the _SEPA_ method there.
  * _SEPA_ account to use`AT611904300234573201` or other test numbers available here: https://stripe.com/docs/testing#sepa-direct-debit
* Once the _SEPA_ method is saved, add an item to your cart and go to the page with the checkout block.
  * If you do not have a page with the checkout block, create a new page and add a checkout block. You may need the WooCommerce Blocks plugin installed.
* Under _Payment options_ you will see `Saved token for woocommerce_payments` instead of `SEPA IBAN ending in 3201`

### Screenshots
![Screenshot on 2022-01-19 at 10-36-14](https://user-images.githubusercontent.com/4634416/150152023-17ad1e14-91ca-4958-86a2-5bd7c6c22563.png)

### Expected behavior
The proper saved payment text would show.

### Additional context
Related issues:
* https://github.com/Automattic/woocommerce-payments/issues/3667
* https://github.com/Automattic/woocommerce-payments/issues/3670

**Comment by achyuthajoy** [comment]
Closing against PR - https://github.com/woocommerce/woocommerce-gutenberg-products-block/pull/6177
