### ISSUE TITLE
WooCommerce Payments Plugin is not translating content as expected in the Admin

### ISSUE THREAD

**Issue by piinthecloud** [Automattic/woocommerce-payments#3690]
### Describe the bug
We received a contact from a client at `ZN-4707279` stating that they had changed their WP site language to FR, however their admin pages still display WooCommerce Payments Plugin information in English. 

### To Reproduce

1. Go to the adming panel of a Wordpress site with WooCommerce enabled
2. Go to Settings > Site Language and update the field to French (also tested with Spanish) 
3. Click on Payments in the left nav
4. Observe that the WooCommerce Payment content is not translated to the site's language. 

### Actual behavior
The WooCommerce Payments plugin is not respecnting the WordPress Settings Site Language as expected. 

### Screenshots
<img width="800" alt="Screen Shot 2022-01-21 at 12 22 58" src="https://user-images.githubusercontent.com/6187313/150520755-bad7c3d2-a823-4a7c-b3cf-10b31d159608.png">

### Expected behavior
WP-Admin should have a consistent experience and all parts of the site should be translated as expected. 

### Desktop (please complete the following information):

* OS: OSX
* Browser: Chrome
* Version 97.0.4692.71 (Official Build) (arm64)

### Additional context
I have tested other parts of the site which might also be related to WooCommerce Payments and also found translation inconsistencies there. 

WooCommerce > Settings > Multi Currency
Inconsistent translation
<img width="858" alt="Screen Shot 2022-01-21 at 12 39 32" src="https://user-images.githubusercontent.com/6187313/150521003-8ffd51c9-b8da-41f4-901a-6cb4e0d34fd1.png">

WooCommerce > Settings > Payments
Inconsistent translation
<img width="858" alt="Screen Shot 2022-01-21 at 12 40 40" src="https://user-images.githubusercontent.com/6187313/150521157-67afb4ec-8cc5-40ac-a484-4cd07488bb0b.png">

WooCommerce > Taxes
Inconsistent translation
<img width="869" alt="Screen Shot 2022-01-21 at 12 41 19" src="https://user-images.githubusercontent.com/6187313/150521241-6de58504-3125-44ec-aba6-c6b7037b788d.png">

**Comment by RadoslavGeorgiev** [comment]
@piinthecloud this looks like a typical case of pending translation updates/downloads. When you switch the site language, WP automatically downloads the translations needed for core. Afterwards, you have to either wait, or go to Dashboard > Updates, and click the only button on the page. Then WP will download WCPay's translations, and every translated string will appear.

Keep in mind that not 100% of the text will be in the given language, as we don't have 100% translations coverage.

Closing the issue for now, please reopen it if this happens again.
