### ISSUE TITLE
Qualitative feedback inbox note will not appear unless there are saved cards

### ISSUE THREAD

**Issue by dechov** [Automattic/woocommerce-payments#3693]
The feedback inbox note (added in https://github.com/Automattic/woocommerce-payments/pull/1541) is intended to appear after there has been a WCPay transaction, but based on the condition querying the `wp_woocommerce_payment_tokens` table, it would appear if (and only if) there are any saved cards on the store (using any payment gateway).

Also, it would improve performance (especially on large stores) to avoid the DB query on every `admin_init` hook – this will be partially addressed in https://github.com/Automattic/woocommerce-payments/pull/3692.

An approach to checking for WCPay transactions (without a server request querying for transactions) might be to cache the state of there _having been a WCPay transaction_ in the DB (transient?), in `process_payment` perhaps.

**Comment by jrodger** [comment]
If we were more comfortable that the note code was only going to be called once (or a limited number of times), I'd suggest just calling the WCPay API to see if there have been any transactions. As things stand that probably isn't a good idea.

**Comment by zmaglica** [comment]
@dechov @jrodger Is this issue something we consider to work on? Can I close it if not?

**Comment by jessepearson** [comment]
I came across this issue because of this request: p1701350589837039-slack-C7U3Y3VMY

Basically it states that the query used is slow and can be made better. A similar query was used in Multi-Currency Analytics and was fixed in this PR: https://github.com/Automattic/woocommerce-payments/pull/6829

Going off of that query, I believe we can do this to fix both issues:

```diff
diff --git a/includes/notes/class-wc-payments-notes-qualitative-feedback.php b/includes/notes/class-wc-payments-notes-qualitative-feedback.php
index 266e1dd70..031fbd6b4 100644
--- a/includes/notes/class-wc-payments-notes-qualitative-feedback.php
+++ b/includes/notes/class-wc-payments-notes-qualitative-feedback.php
@@ -38,8 +38,27 @@ class WC_Payments_Notes_Qualitative_Feedback {
 		}
 
 		// We should have at least one transaction.
-		$token_count = $wpdb->get_var( "select count(*) from {$wpdb->prefix}woocommerce_payment_tokens" );
-		if ( 0 === (int) $token_count ) {
+		if ( WC_Payments_Utils::is_hpos_tables_usage_enabled() ) {
+			$result = $wpdb->get_var(
+				"SELECT EXISTS(
+					SELECT 1
+					FROM {$wpdb->prefix}wc_orders_meta
+					WHERE meta_key = '_wcpay_transaction_fee'
+					LIMIT 1)
+				AS count;"
+			);
+		} else {
+			$result = $wpdb->get_var(
+				"SELECT EXISTS(
+					SELECT 1
+					FROM {$wpdb->postmeta}
+					WHERE meta_key = '_wcpay_transaction_fee'
+					LIMIT 1)
+				AS count;"
+			);
+		}
+
+		if ( 1 !== intval( $result ) ) {
 			return;
 		}
 
```

This should work since `_wcpay_transaction_fee` should be on every order through WooPayments, and it also reduces the overhead of using `count`.
