### ISSUE TITLE
subscriptions-core uses deprecated is_ajax

### ISSUE THREAD

**Issue by shendy-a8c** [Automattic/woocommerce-payments#3695]
### Describe the bug

From https://developer.woocommerce.com/2022/01/11/woocommerce-6-1-released/:
> The is_ajax function has been deprecated. The WordPress function wp_doing_ajax should be used instead.

subscriptions-core uses `is_ajax()`. A fix needs to be done [there](https://github.com/Automattic/woocommerce-subscriptions-core/issues/102). This issue should be closed after subscriptions-core version bump.

### To Reproduce

1. Install WooCommerce 6.1.
2. Make sure woocommerce-subscriptions-core and woocommerce-subscriptions are not active as a plugin, so we can be sure that the behavior comes from subscriptions-core loaded by wcpay.
3. Enable debugging by setting this constant in `wp-config.php`.
```
define( 'WP_DEBUG', true );
```
4. Purchase something so there is an order created in your store. If there is already an order, skip this step.
5. Edit an order and click the update button (no need to change anything).

### Actual behavior

The deprecation warning comes up:
```
Deprecated: is_ajax is deprecated since version 6.1.0! Use wp_doing_ajax instead. in {wordpress_path}/wp-includes/functions.php on line 5211
```

### Expected behavior

No `is_ajax()` used, so no deprecation warning.

### Desktop (please complete the following information):

* OS: macOS.
* Browser Chrome

**Comment by zmaglica** [comment]
The [fix](https://github.com/Automattic/woocommerce-subscriptions-core/issues/102) is implanted. Closing this one.
