### ISSUE TITLE
Add WooCommerce Payments payout details to Edit Order 

### ISSUE THREAD

**Issue by jrodger** [Automattic/woocommerce-payments#37]
Where the total value of an order is displayed, add WooCommerce Payments fee and payout information.

**Comment by LevinMedia** [comment]
Removing needs design - this should be displayed in the order notes. We've got design files for it.

**Comment by jessepearson** [comment]
@jrodger Would we consider this done at this point?

![Screenshot 2023-06-26 at 11 16 34 AM](https://github.com/Automattic/woocommerce-payments/assets/4634416/6e50e9d4-d700-4e85-a805-0d732067cec1)

**Comment by jrodger** [comment]
Blast from the past! Yes, I think what we have now covers everything we were asking for in this issue.

Thanks for doing some clean up :) I'll go ahead and close it, but feel free to reopen if anyone thinks we missed something.
