### ISSUE TITLE
Add new `Payment_Type` to track recurring WCPay Subscriptions (Stripe Billing) payment volume

### ISSUE THREAD

**Issue by haszari** [Automattic/woocommerce-payments#3715]
### Description
WooCommerce payments has a [`Payment_Type` enumeration](https://github.com/Automattic/woocommerce-payments/blob/ab60ad2e73c2c8a4a070c64704a9225f26958c6d/includes/constants/class-payment-type.php#L22) which we use to track different kinds of payments. 

It currently has two values – `single` for regular payments and `recurring` for subscription payments. The `recurring` value covers both WC Subscriptions integration and WCPay built-in subscriptions functionality.

To support the rollout of WCPay Subscriptions we need a way to track usage and payment volume. Adding a new value to track WCPay Subscriptions recurring payments will help with this.

### Acceptance criteria
- New payment type metadata value for WCPay Subscriptions payments (initial payment and renewals).
- Ensure this value is used for all relevant payments.
- Confirm impact on existing `recurring` value - its meaning changes slightly. 

Ultimately when this is in place we should be able to measure WCPay Subscriptions revenue directly.

### Testing instructions
TBC

### Additional context
pdjTHR-vP-p2#comment-710

**Comment by aprea** [comment]
We add `payment_context` Stripe metadata with a value of `wcpay_subscription` when using WCPay Subscriptions.

This metadata **is not** present on subscription transactions when WCS is active.

I'm wondering if we can use this existing metadata to differentiate between WCPay Subscriptions / WCS transactions?

**Comment by haszari** [comment]
> We add `payment_context` Stripe metadata with a value of `wcpay_subscription` when using WCPay Subscriptions.

Confirming this metadata is coming through and should meet our needs for now. It still needs to be piped through to Looker (BI system). 

I'll leave this issue open for now for context and to track the need, we can close when it's wrapped.

**Comment by haszari** [comment]
Closing - we now have `payment_context` available in BI system so we can start tracking WCPay Subscriptions usage. 🎉 📈 💃
