### ISSUE TITLE
Rows per page dropdown misaligned on pagination controls

### ISSUE THREAD

**Issue by jrodger** [Automattic/woocommerce-payments#3727]
### Describe the bug
The dropdown list used to configure the number of results to show on a page is misaligned.

<img width="800" alt="Screenshot 2022-01-28 at 17 12 47" src="https://user-images.githubusercontent.com/686419/151592172-e5b6c609-680c-4164-8bae-5d22ca6c6114.png">

Tested against the transactions page, but probably happens on other screens as well.

Tested on:
* WP 5.9
* WC 6.1.1
* WCPay 3.6.1

### To Reproduce
1. Open a page (for example, transactions) that has enough results for a single page (or temporarily hard code the summary endpoint to return a high record count)
2. See the dropdown is misaligned.

### Desktop (please complete the following information):
Tested on, but probably present on other configurations:
* OS: iOS
* Browser: Chrome
* Version: 97

Possibly related to https://github.com/Automattic/woocommerce-payments/issues/3728

**Comment by LevinMedia** [comment]
appears to be a duplicate with #3728

**Comment by jrodger** [comment]
I think the misaligned dropdown list (this issue) and the number formatting (#3728) are probably caused by different bugs, so I think there's value in keeping these as separate issues.

I should have added some annotations to the image to make it clear.

**Comment by alefesouza** [comment]
Hi there.

This issue was fixed in woocommerce/woocommerce-admin#8113.
