### ISSUE TITLE
Number of results and page count isn't formatted correctly

### ISSUE THREAD

**Issue by jrodger** [Automattic/woocommerce-payments#3728]
### Describe the bug
On pages with tables, the number of results and the page count aren't formatted correctly.

<img width="800" alt="Screenshot 2022-01-28 at 17 12 47" src="https://user-images.githubusercontent.com/686419/151593422-e7434dc4-8289-4173-b45f-42eca4ded8c8.png">

In this screenshot I would expect the number of transactions and the number of pages to have thousand separators in them.

### To Reproduce
Tested against the transactions page, but probably happens on other screens as well.

Tested on:
* WP 5.9
* WC 6.1.1
* WCPay 3.6.1

### To Reproduce
1. Open a page (for example, transactions) that has enough results to cause more than 10,000 pages to be displayed (or temporarily hard code the summary endpoint to return a high record count)
2. See the numbers lack thousand separators

### Desktop (please complete the following information):
Tested on, but probably present on other configurations:
* OS: iOS
* Browser: Chrome
* Version: 97

Potentially related to https://github.com/Automattic/woocommerce-payments/issues/3727

**Comment by LevinMedia** [comment]
Just wanted to drop a note that this issue is probably not exclusive to WCpay - We should also investigate it's behavior in the WCadmin analytics reports as it should be using the same component in both places.

**Comment by alefesouza** [comment]
I've checked and noticed that these formatted number are currencies so we should expect to have thousands separators, it's not common to see non currency numbers such as pagination number and total formatted, what do you think about that?

**Comment by dechov** [comment]
The unformatted transactions count is from [here](https://github.com/Automattic/woocommerce-payments/blob/aa680dbd48b4feab00bfa2e19103bf15559ea8ef/client/transactions/list/index.tsx#L563), and it's the same for deposits and disputes – we should probably format it using the [number package](https://github.com/woocommerce/woocommerce/tree/trunk/packages/js/number) (which is what the currency package itself uses).

Looks like the unformatted page number is from core ([here](https://github.com/woocommerce/woocommerce/blob/59427def8446f04d2a1019ec0f069cf68404c524/packages/js/components/src/pagination/index.js#L112)).

**Comment by dechov** [comment]
@fashuvo Thanks for taking care of that! Looks like we should still have an issue for the page number, is that right? @jrodger Should we open an issue in WC core for that?

**Comment by fashuvo** [comment]
> Looks like we should still have an issue for the page number, is that right?

Yeah, the page number doesn't have the thousand separator yet. And I think it demands an issue in WC core.
