### ISSUE TITLE
Customer (subscriber) should be able to easily update default payment method for all subscriptions

### ISSUE THREAD

**Issue by dhjw** [Automattic/woocommerce-payments#3729]
### Describe the bug
Managing payment methods in My Account > Payment Methods is not updating active subscriptions as expected.

### Reproduction / Behavior
1. Set up a subscription using a saved credit card.
2. Save a second credit card using a different expiry date so you can tell them apart.
3. In My Account > Payment Methods, click Make Default until you choose the card not applied to the subscription. Click Yes to update the subscription payment method to the new default. View the subscription details and see that nothing changed - it's still using the original card.
4. In My Account > Payment Methods, delete the card that is currently used for the subscription. A notice says the subscription was automatically updated to the _deleted_ card instead of the remaining card. The subscription then has no payment method applied and just says "Via credit card / debit card" instead of "Visa ending in ..." and renewal will surely fail.

### Expected behavior
When changing the default card and clicking Yes the subscription should change to use the new default.
When deleting the card currently in use the subscription should change to use the remaining card.

### Screenshots

Clicking `Make Default` on the Amex card ending in 0005. Presents the prompt.
![Screen Shot 2022-03-23 at 12 59 15 PM](https://user-images.githubusercontent.com/57298/159597470-55b65ab8-1eeb-4254-b253-049000b26218.png)
Clicking `Yes` does not update the payment method for the subscription
![Screen Shot 2022-03-23 at 12 59 35 PM](https://user-images.githubusercontent.com/57298/159597584-3cb09261-115b-42f3-8d56-0b451c4f4838.png)

**Comment by haszari** [comment]
Labelling as high priority as this is silently failing, and changing payment method is a pretty fundamental subscriber flow.

**Comment by haszari** [comment]
@zmaglica @dhjw – Do you recall if this is affecting WCPay Subscriptions (built in) or WC Subscriptions (extension integration) or both? Please update labels/reproduce steps to clarify. 

Assuming both for now.

**Comment by dhjw** [comment]
My report is based on WCPay Subscriptions. I did not pay for and can't use WC Subscriptions and don't know if it's affected.

**Comment by haszari** [comment]
Thanks for the info @dhjw – and thanks also for reporting 🙌

**Comment by melek** [comment]
Report in 5454898-zen. The merchant is using WC Subscriptions.

**Comment by alexander7567** [comment]
> Report in 5454898-zen. The merchant is using WC Subscriptions.

This is me if you need any more information.

**Comment by mattallan** [comment]
Related issue in subscriptions-core: https://github.com/Automattic/woocommerce-subscriptions-core/issues/128
Fixed by PR: https://github.com/Automattic/woocommerce-payments/pull/5254
