### ISSUE TITLE
Card reader settings page file upload throws error file cannot be found

### ISSUE THREAD

**Issue by mordeth** [Automattic/woocommerce-payments#3730]
Currently saving the Card Readers settings page doesn't work as expected if a file is uploaded via Branding Settings. The file is uploaded, but Save Settings API returns the error "No such file uploaded". The cause of the error is the file upload endpoint `as_account` param is set to `true` which makes it invalid for the `update_settings` endpoint.

Slack discussion: p1638277763489000-slack-C02C00HCJ8J

### Testing instructions
- Update the `_wcpay_feature_card_readers` option to `1`.
- Update the `card_present_eligible` to `true`.
- Update `isBrandingEnabled` feature flag to `true` in `client/card-readers/settings/index.js`.
- Navigate to `Payments` -> `Card Readers page` -> `Receipt details`.
- Scroll down to `Branding` and upload image file to `Logo` field.
- Save settings and even saved successfully the `Logo` setting is empty.

**Comment by kalessil** [comment]
@anu-rock: looks like this one is causing blockers, would you please add it to the sprint and prioritize it?

**Comment by anu-rock** [comment]
@kalessil Added it to our sprint and updated dependencies.
