### ISSUE TITLE
Unable to checkout with block based theme on WordPress 5.9

### ISSUE THREAD

**Issue by brucealdridge** [Automattic/woocommerce-payments#3743]
### Describe the bug

When setting up a new store with WC Pay a customer is unable to checkout due to stripe payment element not being populated.

### To Reproduce

1. On a fresh install with WP 5.9, WC & WC Pay. (NB this defaults to Twenty Twenty Two block based theme)
2. Onboard w/ WC Pay.
2. Try to checkout.
4. See missing credit card details fields.

### Actual Behaviour

Stripe payment element is not rendered with block based themes. Screenshot is from Twenty Twenty Two Theme.
This happens regardless of UPE setting.

![image](https://user-images.githubusercontent.com/57298/152250181-dd2e46d6-35f6-4d90-a72a-44cc84fb32d2.png)

### Expected behavior

Stripe payment element is rendered. Screenshot from Twenty Twenty One Theme.

![image](https://user-images.githubusercontent.com/57298/152250433-33aadc88-e0db-4080-9953-c2d39248900e.png)

**Comment by vbelolapotkov** [comment]
Closing since the PR was merged.
