### ISSUE TITLE
Clarify the specific email that reports are being sent to

### ISSUE THREAD

**Issue by aheckler** [Automattic/woocommerce-payments#3751]
Not a true bug _per se_, but when emailed reports are sent to merchants, it's unclear which email address we're sending to. There are several possibilities in play:

- The WordPress admin email
- The currently logged-in user's email
- The WooCommerce Payments account email
- The WordPress.com email

The correct answer is that reports get sent to the WordPress.com account email, but yeah, it's not obvious.

More context here: p1643675501909209-slack-C7U3Y3VMY

cc @chickenn00dle

**Comment by zmaglica** [comment]
@aheckler How should we solve this particular problem? Shall we create P2 post about it or update in WooCommerce Payments dashboard or somewhere lese?

**Comment by aheckler** [comment]
@zmaglica There's some discussion of that in the Slack thread here:

p1644018469682429/1643675501.909209-slack-C7U3Y3VMY

**Comment by zmaglica** [comment]
> @zmaglica There's some discussion of that in the Slack thread here:
> 
> p1644018469682429/1643675501.909209-slack-C7U3Y3VMY

Yes, sorry. I missed slack part.

**Comment by chickenn00dle** [comment]
To summarize the discussion so far in Slack, we have a couple of options:

1. Specify the email address in the notice that appears when an async export is triggered

This option would require the least amount of work. However, it isn't an ideal flow for some merchants as there are times when a store might have multiple admins, and merchants might not want exports to be sent to the owner's account.

2. Send exports to the logged-in users email address based on Jetpack connection

This option is a bit more involved, and would probably need some deeper investigation. Also, as David noted in the Slack convo, we would probably need to incorporate permission when determining who can actually download an export.

**Comment by LevinMedia** [comment]
@aheckler @chickenn00dle let's do a combination of things to solve this issue. 

1. we should indicate in the notice which email address the report will be sent to
2. We should email the report to the email address of the _**WPuser**_ who requested it in the admin - regardless of the email that's associated with the jetpack connection. 

Given that only admins and store managers can see these reports, we shouldn't have to do anything extra with permissions

CC: @thenbrent

**Comment by jessepearson** [comment]
Client updated in https://github.com/Automattic/woocommerce-payments/pull/3839
