### ISSUE TITLE
Examine Setting Cookies with Multi-Currency

### ISSUE THREAD

**Issue by billrobbins** [Automattic/woocommerce-payments#3761]
### Describe the bug
When multi-currency is enabled, visiting the site while logged out will set a cookie.  This can affect performance since platforms like Pressable and Atomic will skip the page cache if a cookie that starts with `wp` or `wordpress` is set.

### To Reproduce
1. Go to Payments > Settings and enable multi-currency.
2. Next go to WooCommerce > Settings > Multi-currency and make sure the "Automatically switch customers to their local currency if it has been enabled" option is enabled.
3. Open up the site in a private browser window and observe that a cookie is set.

### Actual behavior
With these settings, a `wp_woocommerce_session` cookie will be set when logged out customers first visit the site.  

### Screenshots
![automatically-switch-currency](https://user-images.githubusercontent.com/1138631/152822040-47e3369e-ebe4-48fa-b171-6343ad533fc8.png)

<img width="1292" alt="cookie" src="https://user-images.githubusercontent.com/1138631/152821022-40a4dded-f706-4a3f-a3e2-c51b296c9a02.png">

### Expected behavior
It would be great if cookies weren't set until the customer selects a different currency from the store or is needed in some other way.  

### Desktop (please complete the following information):

* OS: MacOS
* Browser: Chrome
* Version: 97.0.4692.99

### Additional context
4726637-zen
https://a8c.slack.com/archives/C4JPKKQBF/p1644245890344629

**Comment by zmaglica** [comment]
@billrobbins Hmm, I was thinking about the implementation and how to resolve this issue. What do you think about storing the local currency info in local storage? Or do you have any other suggestions?

**Comment by billrobbins** [comment]
Local storage sounds like a good alternative to me.  AFAIK, it shouldn't invalidate the cache on those platforms.

**Comment by mouligreenlaw** [comment]
User on 4726637-zen came back to confirm that having disabled `Automatically switch customers to their local currency if it has been enabled`, the site performance has improved
