### ISSUE TITLE
Allow registering an already captured payment through the API

### ISSUE THREAD

**Issue by koke** [Automattic/woocommerce-payments#3764]
The existing `capture_terminal_payment` endpoint allows registering an authorized payment intent, which WooCommerce Payments will then attempt to capture. The endpoint will reject any intents that are not in the `processing` or `requires_capture` status.

As we prepare to support In-Person Payments in Canada and add support for Interac payments, we'll need to support the case where the intent is both [authorized and captured in the client in a single step](https://stripe.com/docs/terminal/payments/regional?integration-country=CA#capture-and-reconcile):

> Unlike Visa, Mastercard, and American Express transactions, Interac transactions are authorized and automatically captured in a single step. Your application shouldn’t continue to capture the PaymentIntent – if you attempt to capture an interac_present payment, the Stripe API returns an error. Be careful to prevent unintended and duplicate payments in your integration; if failures or declines occur while processing Interac, you can attempt to re-use the same PaymentIntent from the original transaction to safeguard against double-charging.

I’m not sure what’s the best option for this but I can think of a couple solutions:

1. Implement another endpoint similar to `capture_terminal_payment` that registers a payment without capturing it.
2. Modify the existing `capture_terminal_payment` so that it only attempts the capture if the intent status is `requires_capture`.

**Comment by zmaglica** [comment]
@koke Since you are not 100% about the solution, I will put this issue in triage status, so other team members can take a look at it and provide additional feedback.

If you ask me, option 1 looks like a nice solution because we don't touch/refactor existing endpoint, and we can fine-tune new endpoint as we want.
