### ISSUE TITLE
"Deposit Transaction" reports get replaced with "All Deposits" report upon download request

### ISSUE THREAD

**Issue by thracefulton** [Automattic/woocommerce-payments#3777]
### Describe the bug

The issue began at the same time that WooCommerce Payments began _emailing_ the "All Deposits" instead of directly downloading it in the browser (about 4 weeks ago for this user). I believe that transition is based on file size or total number of transactions.

Instead of giving a CSV of the `Deposit Transactions` report showing the data for a single deposit, they are emailed the full `Deposits` report. 

e.g. The `Deposits Transaction` view shows a total of $3,000, with 10 `transactions` making up the deposit. The report that gets emailed upon request to download does not match this data (i.e. Contains no customer transactions) and only shows all 8000 `Deposits` from WooCommerce Payments instead. 

### To Reproduce

I am personally unable to reproduce it since I don't have a site with enough WooCommerce Payments transactions to trigger the changeover from direct download to emailing of reports.

To download a `Deposit Transactions` report: 
1. Navigate to **Payments → Deposits**
2. Click on the date for the Deposit in question to open the `Deposit Transactions` view.
3. Click the `Download` link in the top right of the list.
4. Review the CSV file that is downloaded or emailed, and confirm it does not match the data in the view.

### Actual behavior

The wrong report is emailed when requesting a download of a "Deposit Transactions" view.

### Screenshots

<img width="1481" alt="WCPay-deposit-transactions-example" src="https://user-images.githubusercontent.com/88570946/153324153-519ae4fb-9544-4c6b-a161-fc6d2394b9a5.png">

### Expected behavior

A report containing only the data from that view should be downloaded (or emailed). Considering the small amount of data contained in a single `Deposit Transactions` view on average, I would think direct download should be possible.

### Additional context

4766625-zen

**Comment by jessepearson** [comment]
> The issue began at the same time that WooCommerce Payments began emailing the "All Deposits" instead of directly downloading it in the browser (about 4 weeks ago for this user). I believe that transition is based on file size or total number of transactions.

The trigger for the download is the count of rows on the page being greater than the "Rows per page" selector at the bottom. For example, my test store has 27 transactions in the last deposit, and the default "Rows per page" is 25. This means that if I click the download button it will email me the data. If I update the "Rows per page" selector to 50, it downloads the data instead.

A possible work around may be to choose 100 from the drop down at the bottom of the page. If their list exceeds that amount, they may be able to modify the number in the address bar of the browser to be higher than their transaction count to make it work. I haven't tested this, as I don't have a store with that many transactions in a deposit, but it may work.

With that being said, this isn't a simple fix but we are working on it and hope to have a fix in the next release. It requires changes in both the client plugin and in the server, as the deposit info needs to be passed to the server to initiate the proper data to be downloaded.
