### ISSUE TITLE
Investigate use of `__experimental_woocommerce_blocks_hidden` (subscriptions in cart/checkout) and confirm if this is needed/essential

### ISSUE THREAD

**Issue by haszari** [Automattic/woocommerce-payments#3778]
This issue is a placeholder – please use the issue subscriptions-core for discussion and comments: 

https://github.com/Automattic/woocommerce-subscriptions-core/issues/113

[ Description below is pasted from the above issue ]

## Describe the bug
Currently we're using an [experimental flag](https://github.com/Automattic/woocommerce-subscriptions-core/blob/97c279bdb6131462de9e90161a6a172ce0447293/includes/class-wc-subscriptions-cart.php#L2486-L2506) to "unhide" various cart item data relating to subscriptions when displaying in cart or checkout (blocks). 

The item data is hidden in the shortcode checkout, and unhidden specifically for blocks.

The item data includes information such as:

- Free trial period
- Sign up fee
- Synched renewal date

https://github.com/Automattic/woocommerce-subscriptions-core/blob/97c279bdb6131462de9e90161a6a172ce0447293/includes/class-wc-subscriptions-cart.php#L2486-L2506

This was introduced as part of initial blocks support - hat tip @senadir @james-allan @jorgeatorres.

Rubik and checkout team are [reviewing this experimental flag](https://github.com/woocommerce/woocommerce-gutenberg-products-block/issues/4999) and reached out to ask for feedback from us (as maintainers of Subscriptions).

Specifically:

- It's not used anywhere else – WC Subscriptions (now also WCPay Subscriptions) is the only client of this API.
- It may not strictly be needed – we may be able to solve this in different ways which are better or more maintainable overall. 

See this comment from @mikejolley for more details of the options: https://github.com/woocommerce/woocommerce-gutenberg-products-block/issues/4999#issuecomment-969059914

The goal of this issue is to confirm if we need (require) `__experimental_woocommerce_blocks_hidden`. Once that's decided we can log follow up issues as needed:

- If we stick with `__experimental_woocommerce_blocks_hidden`, switch to stable variation when appropriate/shipped.
- If we abandon it, implement improved approach.

**Comment by aprea** [comment]
I have replied to the original GitHub issue here - https://github.com/woocommerce/woocommerce-gutenberg-products-block/issues/4999#issuecomment-1068773156

>I like the idea of deprecating the `__experimental_woocommerce_blocks_hidden` property in favour of one of your alternative solutions. I don't see any red flags in the approaches you have outlined. The slot fill option sounds promising!
>
>Ultimately, I think yourself / Rubik are in the best position to decide on the final approach. We're happy to accommodate the chosen approach.
>
>Feel free to include me or Helix in any eventual PRs for review and testing.

As such, we can consider this investigation complete and close this issue. Rubik has the ball and will decide on the next steps.

We can respond with follow-up issues/PRs when needed.
