### ISSUE TITLE
WC could duplicate an order between payments when checked out with UPE

### ISSUE THREAD

**Issue by oaratovskyi** [Automattic/woocommerce-payments#3784]
### Describe the bug

Sometimes WooCommerce duplicates an order during checkout. When the successful payment webhook is processed, it incorrectly marks the initial order as completed.
In the orders mentioned in p1644259767706289/1644215203.183149-slack-C7U3Y3VMY, it looks like what caused the duplication was the coupon code not being applied on the second order, which changed the order total. But the root cause is that two orders have the same payment intent ID.

### To Reproduce

1. As a merchant, make sure you have UPE enabled and card checkbox is on.
2. As a merchant, create coupon with 1 limit usage.
3. As a shopper, buy some products, add to the cart and go to checkout.
4. Enter coupon into the input and use `4000000000009995` that should fail with insufficient funds.
5. After that, enter a valid card and do successful checkout.

### Actual behavior
As a merchant (in admin), you should see two orders with the same payment intent ID, both in status Completed.

### Expected behavior
As a merchant (in admin), you should see two orders, first (unsuccessful attepmt) is `Failed` and second one (paid-for) is `Completed`. Similar to non-UPE checkout.

### Additional context
Slack discussion where the bug was reproduced p1644341905654969/1644336878.912519-slack-C01B8KNUYSW.

**Comment by namiokuzono** [comment]
34385504-hc AT site

**Comment by aheckler** [comment]
4813245-zen

**Comment by jessepearson** [comment]
> Hi @oaratovskyi Does #3893 resolve this issue too? We have a couple of reports from merchants about what seems to be a related issue and it would be helpful to be able to follow-up with them about the 3.8.2 update.

@pauljacobson No, the fix in #3893 is unrelated to this issue.
It appears the issue is being worked on, though.
