### ISSUE TITLE
Do not show multi-currency inbox note until merchant has successfully set up WCpay

### ISSUE THREAD

**Issue by LevinMedia** [Automattic/woocommerce-payments#3806]
We're showing an inbox note when WooCommerce payments is installed, but setup is not complete. We should not show the inbox note until the merchant as successfully created a WooCommerce Payments account. If the note is clicked, you're taken to a page that says "You're not allowed to access this page"

<img width="754" alt="Screen Shot 2022-02-15 at 11 35 28 AM" src="https://user-images.githubusercontent.com/4500952/154135822-077c3ef5-aa78-4859-99b7-457c969aa493.png">
<img width="1761" alt="Screen Shot 2022-02-15 at 11 36 03 AM" src="https://user-images.githubusercontent.com/4500952/154135828-ad939f04-57eb-4b0b-a88c-f665d2cab0b1.png">

@vbelolapotkov

**Comment by vbelolapotkov** [comment]
@LevinMedia , I pinged porters on this to make sure it's triaged.
