### ISSUE TITLE
Remove platform checkout code that affects checkout block

### ISSUE THREAD

**Issue by harriswong** [Automattic/woocommerce-payments#3807]
### Description
We have `isPlatformCheckoutEnabled` feature flag wrapped around code for platform checkout functionalities. Some of these flags are integrated with the "checkout block".

Checkout block no longer needs to support platform checkout, we should remove the flag and the code inside. For example, this can be removed. 
https://github.com/Automattic/woocommerce-payments/blob/develop/client/checkout/blocks/upe.js#L60-L65

### Acceptance criteria
- Remove https://github.com/Automattic/woocommerce-payments/blob/develop/client/checkout/blocks/upe.js#L60-L65
- Find other places where `isPlatformCheckoutEnabled` is **used with checkout block**, remove those.

**Comment by harriswong** [comment]
@frosso, I want to double check with you regarding this issue. The checkout block code is functional, but we would still like to remove it because we only want to support shortcode checkout right?

cc @brettshumaker

**Comment by frosso** [comment]
@harriswong that's correct, let's remove everything related to modifications in the "checkout" block made in the WC Payments plugin 👍
