### ISSUE TITLE
Theme compatibility with platform checkout

### ISSUE THREAD

**Issue by harriswong** [Automattic/woocommerce-payments#3808]
### Description
When UPE is disabled and platform checkout is enabled, make sure the shortcode checkout is displayed properly in the following themes (in the order of highest priority to lowest):
- storefront 2 columns
- twenty-twenty 2 columns
- storefront 1 column
- twenty-twenty 1 column
- A dark theme, make sure elements are displayed properly and readable

We should timebox this no more than 1 week. If there are many things to address/fix, please create a follow-up and we will tackle it in a future sprint.

### Acceptance criteria
- Make sure shortcode checkout works with various themes described above
- Create follow-up if we can't cover all themes above.

**Comment by superdav42** [comment]
Twentty Twenty Two 1 column and appear kinda cramped
![image](https://user-images.githubusercontent.com/1534605/158831005-508dcf85-fa46-4430-b045-5129b1592908.png)
Somehow the width of the input field on this theme is not as large as on storefront theme.
Same problem on Astra theme although not as bad
![image](https://user-images.githubusercontent.com/1534605/158838455-51e98eef-c217-42ea-a27d-a985f698a957.png)


There some problem with the position of the popup if the field is near the bottom of the screen the popup will be half hidden and there's no way to scroll. Happens with any theme.
![image](https://user-images.githubusercontent.com/1534605/158831850-4730e788-1d9b-479f-98e2-46b9fdc1a5aa.png)

Twenty Twenty on mobile the modal does not cover the screen completely
![image](https://user-images.githubusercontent.com/1534605/158834984-e8279c56-bc7b-41a0-93d1-a74d81d834ad.png)

So far I've tested Twenty Nineteen, Twenty Twenty, Twenty Twenty-One, Twenty Twenty-Two, Astra, OceanWP, GeneratePress and these are the only issues I've noticed. No show stoppers really.

**Comment by superdav42** [comment]
> I'm not sure if it's meant to be covered in this issue, but the email field isn't loading the spinner in the Twenty Twenty-Two theme(and all block based themes). It's using checkout block styles that aren't being enqueued, so they might need to be copied over.

To be clear the spinner does not show but the popup appears fine and works.

**Comment by harriswong** [comment]
Thanks @superdav42! 

@frosso when we first created this issue, I remember seeing a list from you regarding some issues you found for these themes. Do you still have the list? I could be remembering a completely different list too :D

**Comment by frosso** [comment]
Those are great finds!
My list included these issues with the spinner as well, but I'm not sure if they've been addressed since:
![Screen Shot 2022-02-03 at 9 20 45 AM](https://user-images.githubusercontent.com/273592/158843427-5504b527-a085-4817-91c2-1402d660b805.png)
![Screen Shot 2022-02-03 at 9 19 37 AM](https://user-images.githubusercontent.com/273592/158843432-d30b2f17-7023-4863-8d5b-a3c1f4c2c191.png)

And the fact that the email address appears on a separate "row" when compared to the items list:
![Screen Shot 2022-03-17 at 11 12 15 AM](https://user-images.githubusercontent.com/273592/158844628-a4d80dfe-bcab-4b29-930d-57c55ffb8aad.png)
