### ISSUE TITLE
Subscription products compatibility with platform checkout 

### ISSUE THREAD

**Issue by harriswong** [Automattic/woocommerce-payments#3810]
### Description
~Investigate if subscription products are compatible with platform checkout. If not compatible, can we fix it? Should we support subscription products?~
Subscription is not compatible with platform checkout. We need a way to disable platform checkout when there are subscription products involved in checkout. These "subscription product" could come from WCPay's subscription or woocommerce-subscriptions. 

## Suggestions
- When subscription products in cart, then maybe we don't enqueue scripts for platform checkout?

### Acceptance criteria
- If platform checkout is enabled, and if subscription product is in cart, WCPay should still checkout without platform checkout, and it should not throw error.

**Comment by harriswong** [comment]
@frosso I want to double check with you on this issue. Is the description accurate?

**Comment by frosso** [comment]
@harriswong that looks good! 👍
