### ISSUE TITLE
Ensure that webhooks do not cause duplicate actions

### ISSUE THREAD

**Issue by RadoslavGeorgiev** [Automattic/woocommerce-payments#3814]
### Description

Once https://github.com/Automattic/woocommerce-payments/issues/3813 is implemented, we'll be processing webhooks even more asynchronously than we normally would. This might cause issues, so we should address it on webhook-type-basis.

### Acceptance criteria

Build on top of https://github.com/Automattic/woocommerce-payments/issues/3813, go through [event types](https://github.com/Automattic/woocommerce-payments/blob/develop/includes/admin/class-wc-rest-payments-webhook-controller.php#L118-L154) one by one, enable them for webhook polling, and make sure that they don't have any side-effects.

**Comment by htdat** [comment]
> Once https://github.com/Automattic/woocommerce-payments/issues/3813 is implemented, we'll be processing webhooks even more asynchronously than we normally would. This might cause issues, so we should address it on webhook-type-basis.

Removing block from ZenHub as the PR for this issue https://github.com/Automattic/woocommerce-payments/pull/3827 is `ready to merge`.

**Comment by htdat** [comment]
I have two following ideas to approach this issue, @RadoslavGeorgiev @deepakpathania would love to see your thoughts. Maybe @marcinbot too. 

### Idea 1 

In every Webhook_processing::process() - [src](https://github.com/Automattic/woocommerce-payments/blob/d1a65f79294d105016a39158e2de69489ac9bd95/includes/class-wc-payments-webhook-processing-service.php#L89-L89), we create a transient with 24-hour expiration to mark that we have already processed that event, something like `wcpay_process_event_evt_xxxxxxxx`. 

Before processing any other event, we check if this event exists, and only process if this transient does not exist. 

Pro: 

- We are absolutely (or at least, very close to absolutely) sure that this can prevent processing duplicate events

Cons: 

- For a huge site with a lot of transactions, aka many webhook events too, this idea can create a lot of transients. 
- Also, most of the sites are still processing these webhooks one time via Webhook_Controller. And this creates a lot of unnecessary data for most of the sites - see the stats here p1645601664622659/1645086273.563649-slack-C01BPL3ALGP


### Idea 2 

Similarly above, but we will only do the additional save and check `wcpay_process_event_evt_xxxxxxxx` when flag `has_more_failed_events` is `true` in the account data.

Pro: 

- We only check for sites with potential duplicate actions, which is more effective. 

Con: 

- Relying on `has_more_failed_events` may be a bit fragile as this can switch from `true` to `false`. 

### My opinion 

Though idea 2 is not perfect, however, I think its effectiveness outweighs the waste of unnecessary data and check of idea 1. And we can acknowledge that some duplicate webhook actions can happen, but they should account for a small portion. 

Also, for idea 2, assuming there is no force account refresh (i.e. running the `wcpay_webhook_fetch_events` job in WP Admin > Tools > Scheduled Actions, OR an `account.updated` event), the `has_more_failed_events` flag can be stable for at least two hours, which is quite enough IMO.

**Comment by deepakpathania** [comment]
I personally feel this can be solved better at the server level itself rather than introducing a verification layer at the client.

We already try to avoid duplicate events at the server by removing the stored entries from the cache table in case Stripe tries to retry sending an event before it has been polled. For the other scenario, where the entry has already been polled and we get a retry from Stripe, we could introduce this check at the server to verify that this event isn't in our records and hasn't been pulled yet and only then forward it to the client. 

With this I feel we'd be able to handle duplicate events effectively. Moving it to the client means, having to release another version in case we discover an issue with the handling later and then waiting for adoption while also taking up client cache memory for storing processed events, which is already being stored at the server.

WDYT?

**Comment by htdat** [comment]
Thanks for your feedback. Agreed that it would be better if we can offload this work to the server. However, with the assumption that Stripe can re-try sending the webhook, I am not sure if we can handle this completely on the server. I'd like to wait for feedback from Rado too, and we can have a group discussion how to move this issue forward next week.

**Comment by deepakpathania** [comment]
Not a blocker for 3.9.0 release, good to have.
