### ISSUE TITLE
KYC: Document the Explat process in WCPay

### ISSUE THREAD

**Issue by dmallory42** [Automattic/woocommerce-payments#3817]
### Description

As part of the KYC Optimization project, we'd like to document the process of running an experiment using Explat in WCPay. The outcome should be some readme or P2 post documenting our process to assist future projects.

### Acceptance criteria

* A P2 post documenting the process of running an Explat experiment.

**Comment by ismaeldcom** [comment]
paJDYF-3GJ-p2
