### ISSUE TITLE
Jetpack IDC package: include two new config options: dynamicSiteUrlText and dynamicSiteUrlSupportLink

### ISSUE THREAD

**Issue by htdat** [Automattic/woocommerce-payments#3825]
### Description

Jetpack introduces two options for Jetpack IDC https://github.com/Automattic/jetpack/pull/22805

### Acceptance criteria

* Upgrade Jetpack IDC package - [ref](https://github.com/Automattic/woocommerce-payments/blob/32714ed5eb77a0853f540bcb346b929e6b98fd14/composer.json#L28-L28). 
* Config these options.
* Update document https://woocommerce.com/document/payments/faq/safe-mode/ to explain this new feature. May simply port back the doc mentioned here https://github.com/Automattic/jetpack/pull/22805#issuecomment-1041911154

### Additional context

PR implemented Jetpack IDC: https://github.com/Automattic/woocommerce-payments/pull/3580, which is available since WCPay 3.7.0 (released on [Feb 10, 2022](https://github.com/Automattic/woocommerce-payments/releases/tag/3.7.0)).

**Comment by htdat** [comment]
Marking this issue `status: blocked` until Jetpack PR is merged https://github.com/Automattic/jetpack/issues/14143

**Comment by deepakpathania** [comment]
Since the jetpack PR is now merged, removing `status: blocked` and moving it to the prioritization queue.

**Comment by htdat** [comment]
@samiff - the latest version https://packagist.org/packages/automattic/jetpack-identity-crisis#v0.7.4 should include the two new options right?

**Comment by samiff** [comment]
v0.8.0 with required changes has been published: https://packagist.org/packages/automattic/jetpack-identity-crisis#v0.8.0

**Comment by htdat** [comment]
This issue can help for this specific merchant p1647871525140549-slack-C7U3Y3VMY
We may raise priority for it @naman03malhotra @deepakpathania
