### ISSUE TITLE
Payment method in the  'Processing Order' email  displayed as 'Popular payment methods' instead of 'Credit / Debit card'

### ISSUE THREAD

**Issue by mgascam** [Automattic/woocommerce-payments#3841]
### Describe the bug
The payment method in the 'Processing Order' email is displayed as Popular Payment methods instead of  'Credit / Debit card'.

### Actual behavior

<img width="608" alt="Screen Shot 2022-02-23 at 14 05 03" src="https://user-images.githubusercontent.com/1553182/155330411-b818f745-dcb2-4c16-a21a-bbb8a3ca8164.png">

### To Reproduce

1. Create a test site
2. Set the Store address to a Country different than US
3. Activate WC Pay and complete onboard, make sure the address is set to a country other than US
4. Under WP Admin > Payments > Settings enable UPE checkout
5. Activate Credit card / debit card + other popular payment methods (Bancontact, Giropay, iDeal...)
6. Place an order and proceed to checkout.
7. Make sure that the `Popular payment methods` widget is available as payment option and pay with credit card (note you might need to change customer address to be able to see the credit card):

<img width="1125" alt="Screen Shot 2022-02-21 at 14 05 50" src="https://user-images.githubusercontent.com/1553182/155332929-645a59c7-d8d4-4b1a-b532-503094bb2d63.png">

8. Check the error in the email that the customer receives. Hint: you might need to install a plugin to catch the emails like [WP Mail Logging](https://wordpress.org/plugins/wp-mail-logging/)

### Expected behavior
The payment method is 'Credit / Debit Card' in the email.

**Comment by dergab** [comment]
Hi there,

as I noticed this behaviour some time ago, I did some testing and want to share the results of my investigation:

- "Popular payment methods" is the radio-box summary-label for the woocommerce-paymentsoptions
- During checkout this label seems to be stored as payment-method. (`$order->get_payment_method_title()` returns "Popular payment methods" and in DB table `postmeta` the row with `meta_key` `_payment_method_title` for that order contains this string)
- After checkout (or upon payment success), this value seems to be overwritten with whatever specific payment method was used (e.g. "Visa credit card")
- With the effect, that this (proper) value is used when re-sending (customer + shop-owner) order emails and re-generating the invoice.

This behaviour is reflected in WooCommerce's order details view. Orders which are not processed fully (state = processing, although payment was successful) show "Popular payment methods" below the total import line. Order which have been processed show the proper payment method.

Kind regards
Gabriel

**Comment by raifd** [comment]
4905611-zd-woothemes

**Comment by thisissandip** [comment]
Another report: 5258560-zen

**Comment by aheckler** [comment]
5302185-zen

**Comment by rashedripon** [comment]
5704970-zen

**Comment by kaushikasomaiya** [comment]
> add_filter( 'woocommerce_defer_transactional_emails', '__return_true' );

The filter above works for me, I believe it might be taking some time to update the meta as pointed out by @dergab, deferring transactional emails show up correct method in Emails that are sent right after placing the order.

![img](https://d.pr/i/nvPZfr+)

**Comment by thuautp** [comment]
5807232-zen

**Comment by pierorocca** [comment]
@FangedParakeet is this something you could look at as a bug solve during this sprint? UPE seems to have impacted the identification of the payment method, an important piece of information for merchants.

**Comment by FangedParakeet** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Heisenberg-63586f2ec60359001310fa6a/issues/Automattic/woocommerce-payments/3841?planning-poker) with Zenhub @mdmoore @timur27

**Comment by thuautp** [comment]
Also reported in #6057388-zen

**Comment by CGA8C** [comment]
As a follow-up re: 6057388-Zen, they've demonstrated that the payment methods display either Credit/Debit Card or WooCommerce Payments completely at random, even on the same subscription. 

To demonstrate this, they created a daily subscription, and over 4 days, the Payment Method displayed either message at random, as you can see below. 
![Markup on 2023-04-19 at 1:25:02 PM](https://user-images.githubusercontent.com/17998077/233047394-6197191e-638f-4a59-a6d0-36ac270648fd.png)
![Markup on 2023-04-19 at 1:25:14 PM](https://user-images.githubusercontent.com/17998077/233047400-a40240ba-a38f-4c95-ac06-b52dc9ac6016.png)
![Markup on 2023-04-19 at 1:25:26 PM](https://user-images.githubusercontent.com/17998077/233047403-f49cee11-b68b-4b1b-a169-e32efb92780a.png)
![Markup on 2023-04-19 at 1:25:38 PM](https://user-images.githubusercontent.com/17998077/233047404-e592aa93-c621-4f83-8a5e-8006f5f05b1d.png)

**Comment by FangedParakeet** [comment]
PR that will resolve this issue may have some conflicts with #6326, which is treading on similar ground: we will be prioritising merging the latter before popping back to sort this one out shortly after.
