### ISSUE TITLE
Address various platform checkout UI issues.

### ISSUE THREAD

**Issue by brettshumaker** [Automattic/woocommerce-payments#3856]
### Description
While working on some other platform checkout features I discovered a few issues/bugs that need to be addressed.

For the "Remember your details" section:
* We need to capture the phone number from the main checkout fields and pre-fill that value into the phone number field.
* Before a user can process their checkout, if the `Save my information...` box is checked, the phone number field there must be filled out.
* Ensure that the phone number here is being validated.
* The selected country code from the phone number is not being sent with the form data.

Other items:
* I also noticed an error on the Order Received page coming from `email-input-iframe.js`
* Make the billing email validation consistent with how WordPress validates emails before checking if the user exists. This is causing 400 responses when an invalid-in-WordPress email is sent like `a@a`.

```
Uncaught TypeError: Cannot read properties of null (reading 'parentNode') at handlePlatformCheckoutEmailInput (email-input-iframe.js:13:47)
```

### Acceptance criteria

* If the checkout phone number field has a value when the `Save my information...` box is checked, pre-fill that value into the platform checkout phone number field.
* Checkout will display an error if there's an invalid phone number entered when the `Save my information...` box is checked.
* Phone numbers entered into the platform checkout phone number field are validated before checkout submission.
* The selected country code from the platform checkout phone number field is captured and sent with the rest of the form data.
* `email-input-frame.js` is properly checking for the existence of the email input field and no error occurs if it's not in the DOM.
* Email addresses are only checked after they pass validation consistent with how WordPress expects email addresses.

**Comment by deepakpathania** [comment]
@brettshumaker Do you think it makes sense to break this down into smaller issues each having their own ACs?
