### ISSUE TITLE
WCPay Admin Pages doesn't load with WooCommerce 4.8.0

### ISSUE THREAD

**Issue by achyuthajoy** [Automattic/woocommerce-payments#3862]
### Describe the bug

We've recently merged a [PR](https://github.com/Automattic/woocommerce-payments/pull/3838) that fixes picking up the correct WordPress & WooCommerce versions with setting up the WCPay E2E environment. After the merge, we noticed that WCPay merchant tests for WooCommerce 4.8.0 are failing along with the tests for WC Blocks.

### Testing Instructions

* On your test site, install WooCommerce 4.8.0 along with the latest version of WooCommerce Payments. 
* Access any WCPay pages from backend to see a blank page with the error mentioned below.

### Actual behavior

With WooCommerce 4.8.0 installed on a JN site along with the latest version of WCPay, accessing any WCPay admin page returns blank with the error:

```
Uncaught TypeError: can't access property "plugins", window.wcSettings is undefined
    297 http://localhost:8084/wp-content/plugins/woocommerce/packages/woocommerce-admin/dist/app/index.js?ver=1.7.3:2
    a http://localhost:8084/wp-content/plugins/woocommerce/packages/woocommerce-admin/dist/app/index.js?ver=1.7.3:2
    561 http://localhost:8084/wp-content/plugins/woocommerce/packages/woocommerce-admin/dist/app/index.js?ver=1.7.3:2
    561 http://localhost:8084/wp-content/plugins/woocommerce/packages/woocommerce-admin/dist/app/index.js?ver=1.7.3:2
    a http://localhost:8084/wp-content/plugins/woocommerce/packages/woocommerce-admin/dist/app/index.js?ver=1.7.3:2
    app http://localhost:8084/wp-content/plugins/woocommerce/packages/woocommerce-admin/dist/app/index.js?ver=1.7.3:2
    <anonymous> http://localhost:8084/wp-content/plugins/woocommerce/packages/woocommerce-admin/dist/app/index.js?ver=1.7.3:2
```

For failures related to WC Blocks can be ignored since WC Blocks requires a higher version of WooCommerce.

### Screenshots

Screencast - https://d.pr/v/rjgPqj

### Expected behavior

Since WooCommerce 4.8.0 is still the minimum supported version for WCPay, all WCPay pages should load as expected.

**Comment by jessepearson** [comment]
I _think_ this might be a conflict with the blocks plugin. If I run WC 4.8.0, WCPay 3.7.0, and the dev tools, I get no error. If I activate WC Blocks 7.1.0, I get the error.

Without WC Blocks active, I get this warning, but it doesn't cause issues.
```
 PHP Warning:  Use of undefined constant WOOCOMMERCE_BLOCKS_PHASE - assumed 'WOOCOMMERCE_BLOCKS_PHASE' (this will throw an Error in a future version of PHP) in /Users/j/sites/wcpaydev/wp-content/plugins/woocommerce/packages/woocommerce-blocks/src/Domain/Package.php on line 78
```

Not sure if this is something we want to look into since the newest version of WC Blocks deactivates itself when active with WC 4.8.0.

**Comment by deepakpathania** [comment]
Yes, this was a compatibility issue that we discovered because of the E2E test setup - we have fixed that by conditionally running some tests for the blocks and WCPay combination. Closing now.
