### ISSUE TITLE
Remove quick fix styling for focused textarea element

### ISSUE THREAD

**Issue by vbelolapotkov** [Automattic/woocommerce-payments#387]
Outline styling for focused form elements is defined in https://github.com/woocommerce/woocommerce-admin/ stylesheets. It's defined for input but not textarea so we have to duplicate styling to make components look similar.

Created a https://github.com/woocommerce/woocommerce-admin/pull/3655 to fix this.

Once the PR ☝️ is merged and released we should update our dependency and remove styling from `client/style.scss`.

**Comment by aprea** [comment]
@vbelolapotkov is this still needed? I don't see any focus or input related code in [`client/style.scss`](https://github.com/Automattic/woocommerce-payments/blob/develop/client/style.scss).

**Comment by htdat** [comment]
## What I found out so far. 

- Searching `textarea` among `.scss` files in the `/client` folder results in only one place. But there is no value set for CSS attribute `border-color` as well as `focus`.

https://github.com/Automattic/woocommerce-payments/blob/16c5a7c9b713fc937c46955ca33afcc27c74fda2/client/disputes/style.scss#L28-L32

- Doing the same search but for keyword `focus` results in several places none of them is related to `border-color`.

- The other PR in `woocommerce-admin` has already removed the fix by the PR https://github.com/woocommerce/woocommerce-admin/pull/3655 mentioned above: https://github.com/woocommerce/woocommerce-admin/commit/65837cfcda65c7f0f81546436f238ca91d098b2f#diff-789cf5e8c790895628f045338810427bb8e838a3224e4ce9017ebb73dbe8239cL93

- I double-check the current experience under WP Admin > Payments and WP Admin > Analytics, and they're consistent now: 

| Payments > Disputes  | Analytics > Taxes |
| ------------- | ------------- |
| ![](https://d.pr/i/aFyIzA+)  | ![](https://d.pr/i/82RkOV+)  |

## Summary 

With all of what I've found out above, I think it's fine to close this issue without doing anything further.
What do you think?

**Comment by vbelolapotkov** [comment]
Thanks for testing @htdat ! Yep, please close it.

**Comment by dechov** [comment]
👍 Looks like it was removed in https://github.com/Automattic/woocommerce-payments/commit/06569b35838648b9e8474e6c8a70d8e4472d1204#diff-a4c6117e9085ecc98b0a1c4ffdb74ac0d7479d93bd1c495ef2a2afa2cf69a241
