### ISSUE TITLE
Incorrect business URL prevents settings from saving

### ISSUE THREAD

**Issue by billrobbins** [Automattic/woocommerce-payments#3874]
### Describe the bug
If the business URL is saved without `https` then the settings page will report an error when attempting to save the settings.  

### To Reproduce

1. Setup the business URL without `https`.
2. Go to Payments > Settings and attempt to save the settings.
3. Observe the error.

### Actual behavior
This error is observed:

```
{"code":"rest_invalid_param","message":"Invalid parameter(s): account_business_url","data":{"status":400,"params":{"account_business_url":"Error: Invalid business URL: site.com"},"details":{"account_business_url":{"code":"rest_invalid_pattern","message":"Error: Invalid business URL: site.com","data":null}}}}
```

### Screenshots
<img width="809" alt="screen_shot_2022-02-25_at_19 21 07" src="https://user-images.githubusercontent.com/1138631/156202511-fe8de637-4aae-4355-85c5-2f667266d7c0.png">

### Expected behavior
I would expect either more helpful error messaging/logging or for us to check for the existence of `https` before sending the post.  

### Additional context
slack-C7U3Y3VMY/p1645802549886609
4800785-zen

**Comment by csmcneill** [comment]
Just adding here that the error is a small `Error Saving Settings` popup on the bottom-left corner of **Payments > Settings**:

![https://d.pr/i/x8xH6e](https://d.pr/i/x8xH6e+)

**Comment by csmcneill** [comment]
4831689-zen and 4836561-zen are likely affected.

**Comment by billrobbins** [comment]
I think this may be more widespread than we initially realized because merchants don't use these settings very often.  I ran into this on my test site and 4771871-zen is also affected even though they came in for an unrelated issue.

**Comment by csmcneill** [comment]
4831689-zen is affected—changing `http` to `https` resolved the issue.

It's worth noting that, when 4831689-zen changed from `http` to `https`, their Apple Pay domain verification produced an error banner on the **Payments > Settings** page:

![https://d.pr/i/Rro6zO](https://d.pr/i/Rro6zO+) 

This did not appear to change their site's ability to accept payments via Apple Pay, but I did not test a live payment:

![https://d.pr/i/lUNaFE](https://d.pr/i/lUNaFE+) 

![https://d.pr/i/VwwPiK](https://d.pr/i/VwwPiK+) 

Quickly disabling Express Payments and re-enabling them got rid of the error banner.

**Comment by csmcneill** [comment]
4823099-zen is likely affected.

**Comment by aheckler** [comment]
4852128-zen possibly

**Comment by aheckler** [comment]
4855492-zen possibly as well

**Comment by thelogicwizards** [comment]
[4867427-zd](4867427-zd-woothemes) is likely affected as well, but in this case there is no `http` or `https` - the user's domain is set to `www.votedargis.com/wordpress` when it should be `https://www.votedargis.com`

**Comment by kaushikasomaiya** [comment]
4853305-zen
(It is fixed, but just reporting this here.)
