### ISSUE TITLE
"Remember your details" should not show when UPE is enabled

### ISSUE THREAD

**Issue by harriswong** [Automattic/woocommerce-payments#3884]
### Describe the bug
When UPE is enabled and `_wcpay_feature_platform_checkout` is enabled, "Remember your details" should not show.

### To Reproduce
1. enable UPE
2. enable `_wcpay_feature_platform_checkout`
3. Go to checkout page with an item in the cart, you will see this:
![image](https://user-images.githubusercontent.com/572862/156473575-3b43835e-b2f0-4672-944a-b28832a714f5.png)

### Actual behavior
"Remember your details" shows.

### Expected behavior
"Remember your details" doesn't show.

### Desktop (please complete the following information):

* OS: macOS Monterey 12.1
* Browser chrome
* Version latest

**Comment by brettshumaker** [comment]
This is already fixed.
