### ISSUE TITLE
Error "this block has encountered an error and cannot be previewed" on media-based blocks

### ISSUE THREAD

**Issue by pauloeaquino** [Automattic/woocommerce-payments#3886]
### Describe the bug

The WooCommerce Payments plugin is causing media-based blocks (i.e. image, media & text, cover, video, etc.) to throw `this block has encountered an error and cannot be previewed` errors.

### To Reproduce

1. Install WooCommerce Payments plugin (no need to connect to a WooCommerce Payments account)
2. Add a media-based block (i.e. image, media & text, cover, video, etc.) to any page or post

### Actual behavior

The error `this block has encountered an error and cannot be previewed` is shown.

### Screenshots

<img width="1117" alt="image" src="https://user-images.githubusercontent.com/40555737/156493205-46b60236-5fd2-44f6-8bb8-5cca01c3ec2f.png">

### Expected behavior

The block should be rendered without any errors.

### Additional context

Encountered in 4827037-zen and 344659200-hc. I also tested on a fresh local install of WP with only WooCommerce Payments (and WooCommerce) plugins installed and was able to replicate the error.

----

This issue description was edited by @felipelousantos for adding more clarity.

**Comment by 1dr0** [comment]
Also encountered on:
34465920-hc
34467852-hc

And a slightly different one here:
34467672-hc (can't access Additional CSS; unconfirmed if this is related, but the last updated plugin was WooCommerce Payments in their Activity Logs)

**Comment by pauloeaquino** [comment]
User report: 4827310-zen

**Comment by nagpai** [comment]
34467077-hc 

Customizer disappears when WC Pay is enabled.

**Comment by InsomniacSabbir** [comment]
34439877-hc

Only the Widgets option is visible on the Customizer section

**Comment by pauloeaquino** [comment]
4827505-zen

**Comment by sudeepbaral** [comment]
Another user with the same issue here: 34467330-hc

Customizer appears after disabling the WooCommerce Payments plugin and disappears after enabling it again.

**Comment by sudeepbaral** [comment]
Another user with the same issue here: 4827226-zen

**Comment by edwinho89** [comment]
34468945-hc

**Comment by htdat** [comment]
FYI. https://github.com/Automattic/woocommerce-payments/pull/3888 is going to fix this issue.

**Comment by jromales** [comment]
34334410-hc
Unable to access Customizer when WooCommerce Payments is enabled

**Comment by htdat** [comment]
Hi all, WCPay 3.8.1 has been released to fix this issue. Would you please ask to customers about that?

**Comment by htdat** [comment]
I am closing this issue now. Feel free to create a new issue, and reach out to devs on #wcpay if there is still any other issue.

**Comment by jromales** [comment]
4827132-zd-woothemes - enabled WooCommerce Payments plugin again and issue is fixed now. I updated the user
