### ISSUE TITLE
Customizer options not loading after WooCommerce Payments update to version 3.8.0

### ISSUE THREAD

**Issue by sstabrizi** [Automattic/woocommerce-payments#3887]
### Describe the bug
When accessing Appearance > Customize the customizer options are not loading after the update to 3.8.0.

### To Reproduce
Navigate to Appearance > Customize.

### Actual behavior
When viewing the Customizer only the Widgets option loads. 

### Screenshots
<img width="1483" alt="Screenshot on 2022-03-02 at 21-46-38" src="https://user-images.githubusercontent.com/25855381/156497986-13695516-0b1b-45f6-bb20-a13448ad2d8b.png">

### Expected behavior
All customizer options should load like the following screenshot: 
<img width="1485" alt="Screenshot on 2022-03-02 at 21-47-41" src="https://user-images.githubusercontent.com/25855381/156498103-4f007319-cbe8-45eb-9739-60d186f5375a.png">

### Additional context
Deactivating the WooCommerce Payments plugin allows the customize options to load. Another option is to revert to any previous version of the plugin. 

### Examples
4827098-zen
4826902-zen

**Comment by sstabrizi** [comment]
https://github.com/Automattic/woocommerce-payments/issues/3886#issuecomment-1057665200

**Comment by htdat** [comment]
FYI. https://github.com/Automattic/woocommerce-payments/pull/3888 is going to fix this issue.

**Comment by htdat** [comment]
Hi all, WCPay 3.8.1 has been released to fix this issue. Would you please ask customers to update this new version?

**Comment by htdat** [comment]
I am closing this issue now. Feel free to create a new issue, and reach out to devs on Slack #wcpay if there is still any other issue.
