### ISSUE TITLE
Add flag to determine whether to track platform checkout events

### ISSUE THREAD

**Issue by brianyu28** [Automattic/woocommerce-payments#3894]
### Description

Add a new flag `wcpay_allow_tracking` to control whether Jetpack tracking events (currently used only for platform checkout) are recorded.

### Acceptance criteria

- Flag should be set on WCPay install, with messaging to merchants about what is collected
- Setting in WCPay to toggle tracking status
- Appropriately handle merchants who already have WCPay installed

### Additional context

pdpOw2-mz-p2

**Comment by malithsen** [comment]
Closing this, see pdpOw2-l8-p2#comment-478
