### ISSUE TITLE
No data displayed and payments failing after Jetpack reactivation

### ISSUE THREAD

**Issue by vbelolapotkov** [Automattic/woocommerce-payments#390]
This issue was discovered after #389 .

Reactivation of the Jetpack with initial domain name restored connection to the Stripe Connect account:

<img width="776" alt="Screenshot 2020-02-03 at 19 39 20" src="https://user-images.githubusercontent.com/3139099/73673389-9c1c0000-46bf-11ea-8f44-0c5cf1d66f98.png">

However, the following effects are discovered:

1. Transactions and disputes data are not displayed in the admin dashboard but still available in Stripe dashboard:

<img width="1076" alt="Screenshot 2020-02-03 at 19 38 10" src="https://user-images.githubusercontent.com/3139099/73673233-5c551880-46bf-11ea-86e9-87065e3e3319.png">

<img width="997" alt="Screenshot 2020-02-03 at 19 38 24" src="https://user-images.githubusercontent.com/3139099/73673441-b0f89380-46bf-11ea-90a4-a3ad8bafb6c6.png">

2. Payments with test card (4242...) are failing with the following error:

<img width="1109" alt="Screenshot 2020-02-03 at 19 43 16" src="https://user-images.githubusercontent.com/3139099/73673489-c1a90980-46bf-11ea-89a6-8b7ef770210a.png">

**Comment by vbelolapotkov** [comment]
Need to reproduce it first, maybe not an issue anymore.

**Comment by naman03malhotra** [comment]
Cannot be reproduced, feel free to reopen if you do.
