### ISSUE TITLE
Including lodash in bundle for platform checkout

### ISSUE THREAD

**Issue by ricardo** [Automattic/woocommerce-payments#3907]
More details: paJDYF-3r1-p2

When bundling lodash to fix the platform checkout, we need to bundle it in [“no conflict” mode](https://www.geeksforgeeks.org/lodash-_-noconflict-method/), to avoid any possible overwriting of global Underscore.js.

cc @superdav42 - in case this is not relevant anymore, please feel free to close the issue.

**Comment by dechov** [comment]
Looks like it was added for `debounce`, which should be bundled AFAIK – does it break without bundling?

**Comment by htdat** [comment]
@naman03malhotra @vbelolapotkov - we may need some guidance here to move this forward, or should I move it to `Ready for prioritization" queue?

**Comment by vbelolapotkov** [comment]
I don't see agreement here, neither I understand the reason and benefits of this approach. That makes me feel, engineering review is the right place for the issue. And I'd expect @Automattic/transact-architecture team would help to agree on the right approach here.

**Comment by htdat** [comment]
That makes sense. Thanks for your feedback @vbelolapotkov.

**Comment by dechov** [comment]
> Looks like it was added for `debounce`, which should be bundled AFAIK – does it break without bundling?

Not sure what I meant by "which should be bundled" here, but probably that `debounce` ought to be included in the global lodash, so there is no apparent need for bundling the library as far as I can tell.

@superdav42 @ricardo What was the outcome of unbundling the package in the patch, in terms of the relevant WooPay functionality?

**Comment by ricardo** [comment]
I assume it would break the functionality introduced in #3736, but I'm not sure exactly what. Src: p1646287792006329/1646282869.889049-slack-CGGCLBN58

@superdav42 could you confirm this and give more details?

**Comment by jessy-p** [comment]
As updated (paJDYF-8wA-p2#comment-17993) by @ismaeldcom, I am closing this

We have been releasing all versions without lodash bundled since that incident and there does not seem to be a specific need to bundle it. In fact, [we could probably end up replacing it with native methods](p1682952712399559-slack-C053VQPD74J).
