### ISSUE TITLE
Documents view: document records list

### ISSUE THREAD

**Issue by luizreis** [Automattic/woocommerce-payments#3929]
### Description

As part of the VAT invoices for processing fees project, merchants should have access to a Documents list where they can see all of their platform-generated documents.

### Acceptance criteria

* Merchants have access to a page that lists all their documents
* The Documents page should be grouped under the Settings page
* The list offers pagination controls

### Designs

Designs can be checked in paJDYF-3mi-p2 and more details around scope are available in paJDYF-3sv-p2.

**Comment by jessepearson** [comment]
Added new issue for the grouping/tabs under the settings page: #4016
