### ISSUE TITLE
Ping authors in case of E2E test failures

### ISSUE THREAD

**Issue by deepakpathania** [Automattic/woocommerce-payments#3963]
### Description

Currently, when E2E tests fail, we send a message to a Slack channel but the PR author might not get to know about it since tests run on a scheduled basis every 6 hours. Introduce a mechanism to notify the last author whose commit triggered a failing run. 

Since runs are scheduled, the failing test might not have been introduced by the latest commit but would still trigger a way for someone to look into the failing flow.

### Acceptance criteria

* The last commit author should be notified about the failing run - communication channel can be decided based on feasibility.

### Additional context

Slack channel: `#wcpay-bots`

**Comment by vbelolapotkov** [comment]
Closing this one since there is a new process in place for handling failing e2e tests: paJDYF-cCK-p2
