### ISSUE TITLE
Add option to allow splitting of card detail fields

### ISSUE THREAD

**Issue by aheckler** [Automattic/woocommerce-payments#3973]
Our Stripe gateway has this option:

![image](https://user-images.githubusercontent.com/5512652/158622682-386bfbfe-da7c-415b-8b9b-543f65b90857.png)

... which can split the card fields into number, expiry date, and security code.

However, there is no equivalent option for WooCommerce Payments! I can get the split fields by enabling UPE, but I may not want to do this for whatever reason.

**Comment by jrodger** [comment]
Just noting that the `needs design` label was applied so we can ensure adding this setting doesn't over complicate the settings page.

**Comment by pierorocca** [comment]
Closing as the current design is split and I'm conscious about proliferating options to the point that config is overlay complicated and shopper UX inconsistent.
