### ISSUE TITLE
The same intent attached to several orders

### ISSUE THREAD

**Issue by dpaun1985** [Automattic/woocommerce-payments#3980]
### Describe the bug

This addresses a bug where the intent is attached to several orders. In this case, will result in having incorrect order status for the orders that has the same intent.

### To Reproduce

1. add a product to cart
2. go to checkout and fail the payment  (eg. card declined – insufficient founds). This will result in a failed order. 
3. open a new tab(2nd) and add another product
4. go to the first tab and pay the order with an accepted credit card. This will result in creating a new order with the same intent. The intent will be updated with the new order id and amount, but on our side, both orders will have the same intent. In admin, both orders will have the same status.
5. refund the 2nd order. 

### Actual behavior

The first order will keep the "Processing" status 
The second one will reflect the real status - "Refunded"

This will not affect the client balance, but will display a wrong status to the first order. 

### Screenshots

Step 2:
<img width="1561" alt="Screenshot 2022-03-17 at 18 55 54" src="https://user-images.githubusercontent.com/82826872/158853443-12855066-c9dc-486b-a05f-f60894795cfe.png">
Step 4:
<img width="1565" alt="Screenshot 2022-03-17 at 18 57 07" src="https://user-images.githubusercontent.com/82826872/158853575-83afc2c3-5952-4679-803c-059968239995.png">
Step 5:
<img width="1561" alt="Screenshot 2022-03-17 at 18 58 10" src="https://user-images.githubusercontent.com/82826872/158853796-17ca84e9-9024-4f9d-b76c-b3024bf6e749.png">

### Expected behavior

Each order must have its own intent

### Additional context

Reference : p1647533137977779/1647464648.900989-slack-C7U3Y3VMY

**Comment by jessy-p** [comment]
Is this with UPE? In that case, could it be solved by [this](https://github.com/Automattic/woocommerce-payments/issues/3784)?
We, unfortunately, cannot prevent the same intent attaching to multiple orders when using UPE, but we try to prevent the undesirable side effects by picking the right order to update.

**Comment by dpaun1985** [comment]
indeed, this is the case. thank you @jessy-p . I will close the issue

**Comment by dpaun1985** [comment]
duplicate of #3784
