### ISSUE TITLE
Add Feature for Merchants To Update Their Support Phone Number 

### ISSUE THREAD

**Issue by darcie** [Automattic/woocommerce-payments#3981]
### Description

Stripe provides a call to update `business_profile.support_phone` in their [docs](https://stripe.com/docs/api/accounts/update#update_account-business_profile-support_phone). WooCommerce Payments doesn't include a field to change this, so merchants have no way to update this number. We update `business_profile.url` with the Customer bank statement field, and a field should be added here so merchants can update their support phone also. 

Merchants cannot change this by managing their accounts in Stripe. Changing the “Management and Ownership” phone and the main “Stripe Express account” phone does not update the Support Details phone number. 

### Acceptance criteria

* The field should be with Customer bank statement, as the two work together 
* It should update the connected account's support details, to provide a way for merchants to change what appears to their customers. 

### Designs

Should be added under the existing `Customer bank statement` field. 
<img width="960" alt="Markup 2022-03-17 at 11 28 35" src="https://user-images.githubusercontent.com/318285/158871338-1e21f04f-4780-47b1-ab4d-403de7c25fd2.png">

### Testing instructions

1. Go to Payments > Settings
2. Scroll down to Transactions and deposits
3. Enter the new phone number for the store's support 
4. Click Manage in Stripe, then Account
5. Click the store's settings under Professional Details 
6. Check that the phone has changed in Support Details.

### Dev notes

Stripe API docs for updating connected accounts: https://stripe.com/docs/api/accounts/update

### Additional context

Reported in 4868290-zen 
Support address and email may be helpful to add also, it looks like these are intended to be printed on the In Person Payments Receipt Template.

**Comment by jrodger** [comment]
Thanks for the detailed write up @darcie.

@LevinMedia, is this something we'd like adding to the settings page or are there grander plans for merchants updating their details within our UIs?

**Comment by darcie** [comment]
@jrodger, I asked about this also on Slack and learned I'd overlooked #3410. It looks like work is already being done for IPP that will address a way for merchants to add Support Contact details.

**Comment by jrodger** [comment]
Ah yes, that's where I saw some previous discussion on phone numbers! Thanks for linking the issue.

I think we can still keep this issue open so that we can consider the same feature for merchants not using in-person payments.

**Comment by darcie** [comment]
I see another recent ticket asking the same thing, 4857555-zen.

**Comment by rashedripon** [comment]
Got a similar report here: 4871954-zen. They only see this screen when trying to update that number:

![If this image fails to load, please visit:](https://d.pr/i/rWzMKv+)
Image Link: https://d.pr/i/rWzMKv

**Comment by aheckler** [comment]
4918736-zen

**Comment by darcie** [comment]
4929500-zen

**Comment by aheckler** [comment]
4869895-zen

**Comment by darcie** [comment]
Testing the addition at **Payments > Card Readers > Receipt Details** added in 4.0.0, the Support phone number field does update the Stripe account and would resolve this. I'm not sure if it will be clear to those not using In Person Payments or if the settings appear for those not yet eligible for IPP. 

One problem I found is that US numbers entered as ten digits are trimmed to the last 8 unless +1 is added before. I'll open a new issue for this later.

**Comment by aheckler** [comment]
5000090-zen

**Comment by aheckler** [comment]
4962575-zen

**Comment by rashedripon** [comment]
Reported on 5208960-zen

**Comment by rogermattic** [comment]
Hey Everyone 👋 I've just looked into this issue and wanted to ask if that's something that's already been implemented, or does it need a design input? 
cc @darcie

**Comment by EjayhanFernandes** [comment]
Reported in 5244848-Zen

**Comment by darcie** [comment]
Hey @rogermattic I missed your ping! 
For those where IPP is available, they can use **Payments > Card Readers > Receipt Details** and update the phone number to a different one. If they do not have access to IPP, there is no way to update the support phone at this time. It does need some design input.

**Comment by csmcneill** [comment]
5289957-zen

**Comment by aheckler** [comment]
> For those where IPP is available, they can use Payments > Card Readers > Receipt Details and update the phone number to a different one. If they do not have access to IPP, there is no way to update the support phone at this time.

Just noting that since 4.3.0 is released, even this workaround is unavailable now, unless you actually have a card reader connected:

https://github.com/Automattic/woocommerce-payments/pull/4346

**Comment by elizaan36** [comment]
Hey @bradyv, Could you take a look and share your recommendation on this?

**Comment by nicdwilson** [comment]
5881726-zen

**Comment by bradyv** [comment]
Design for this I think is straightforward. We can add a subheading for `Customer support` within the Transactions section and use space below the bank statement descriptor for new fields
<img width="1170" alt="Screenshot 2023-01-24 at 15 45 43" src="https://user-images.githubusercontent.com/889872/214446090-b438398f-319b-4e53-9499-423f41092819.png">

In the future it might be a good idea to allow this data to automatically populate the `Contact Info` block in site editing.
