### ISSUE TITLE
Revisit Output Escaping Exclusions

### ISSUE THREAD

**Issue by jrodger** [Automattic/woocommerce-payments#40]
PHPCS was flagging some unescaped output in the plugin. For the time being some of these have been ignored with the `PHPCS:Ignore WordPress.Security.EscapeOutput.OutputNotEscaped` annotation.

Once development has progressed a bit more, and before releasing a production version, we should revisit these exclusions.

**Comment by RadoslavGeorgiev** [comment]
Looking at the client code, there are only 8 instances of the `Security.EscapeOutput.OutputNotEscaped` annotation, and all of them seem meaningful, mostly related to echo-ing static HTML code. I'm closing this issue, as in the past 2 years most of those instances seem to have been cleared up.
