### ISSUE TITLE
Payment details page shows errors for subsription transaction with WC 4.8.0

### ISSUE THREAD

**Issue by shendy-a8c** [Automattic/woocommerce-payments#4001]
### Describe the bug

With WC 4.8.0 and subscription order, payment detail page (`/wp-admin/admin.php?page=wc-admin&path=%2Fpayments%2Ftransactions%2Fdetails&id={ch_xxx}`) shows error.

### To Reproduce

1. Purchase a subscription product.
2. Open the payment detail page of that order. You can click the link on the edit order admin page as shown below.

<img width="997" alt="Screen Shot 2022-03-22 at 02 20 24" src="https://user-images.githubusercontent.com/73803630/159369714-b6404d24-4753-4be2-844b-7ee07b134fd7.png">

### Actual behavior

Parts of the payment detail page do not render. Instead, it shows errors `TypeError: Cannot read property 'toString' of null`.

### Screenshots

![screenshot_of_failed_test](https://user-images.githubusercontent.com/73803630/159347253-016eb94a-b913-497c-a73e-7e53bb62e296.png)

### Expected behavior

No error.

### Additional context
I think this commit 02259ac19510d6d7cfc86f826fc24e22fc1092cc where the problem starts. Commit before it doesn't give the error.

Update: I understand more of the problem now.
In commit 02259ac19510d6d7cfc86f826fc24e22fc1092cc, specifically changes in `client/utils/currency/index.js`, we stop getting currency data from `@woocommerce/currency`'s `getCurrencyData()` but instead getting it from `wcpaySettings.currencyData`, which is passed from PHP `includes/admin/class-wc-payments-admin.php`.

We get the currency data from Woo's `i18n/locale-info.php`.
[WC 4.8's i18n/locale-info.php](https://github.com/woocommerce/woocommerce/blob/4.8.3/i18n/locale-info.php) doesn't have `short_symbol`.
Not sure when `short_symbol` is added but the [latest version](https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce/i18n/locale-info.php) has it.

The error is because symbol is null and [woocommerce-admin's CurrencyFactory just toString() it without checking for null](https://github.com/woocommerce/woocommerce-admin/blob/main/packages/currency/src/index.js#L27).

Also, maybe this error doesn't only happen for subscriptions order but for any kind of order.

![Screen Shot 2022-03-22 at 04 35 42](https://user-images.githubusercontent.com/73803630/159369529-a63b800a-3887-448a-94b5-34c556a018a1.png)

**Comment by csmcneill** [comment]
It looks like #4005 isn't released yet. A user in 4896575-zen is experiencing this issue currently.

**Comment by stuartduff** [comment]
It seems the same error message is displaying for other customers on all admin pages of WooCommerce Payments like Overview, Deposits, Transactions and Settings. 4896575-zen

The customer site is using the latest version of WP 5.9.2, WC 6.3.1, WC Pay v3.9.1 and the site currency is USD.
