### ISSUE TITLE
Deprecated notices with latest Woo Blocks

### ISSUE THREAD

**Issue by superdav42** [Automattic/woocommerce-payments#4004]
### Describe the bug
These deprecation notices appear when using WooCommerce  Blocks 7.2.0.
```
Automattic\WooCommerce\Blocks\StoreApi\SchemaController is deprecated since version 7.2.0! Use Automattic\WooCommerce\StoreApi\SchemaController instead.
Automattic\WooCommerce\Blocks\Domain\Services\ExtendRestApi is deprecated since version 7.2.0! Use Automattic\WooCommerce\StoreApi\Schemas\ExtendSchema instead.
```
### To Reproduce
Install Woo Blocks 7.2.0

### Actual behavior
A notice

### Expected behavior
No notices

Obviously we need to update our code to use the new class names but in a manner that is also compatible with Woo Blocks < 7.2.0

**Comment by aprea** [comment]
A PR was recently merged in `woocommerce-subscriptions-core` to address this issue https://github.com/Automattic/woocommerce-subscriptions-core/pull/124

The issue will be resolved in WCPay when we release a new version of `woocommerce-subscriptions-core` and update the `woocommerce/subscriptions-core` dependency.

**Comment by htdat** [comment]
For the next platform porter: if this issue is still open, check again if we can close it per @aprea's comment right above.
