### ISSUE TITLE
Debug and unskip failing merchant onboarding E2E tests

### ISSUE THREAD

**Issue by deepakpathania** [Automattic/woocommerce-payments#4009]
### Description

- Merchant onboarding E2E tests were skipped in [#3733](https://github.com/Automattic/woocommerce-payments/pull/3773), debug the root cause and unskip the tests.

### Acceptance criteria

* Onboarding tests should be unskipped in CI pipeline.

### Testing instructions

1. Go to Actions -> WCPay E2E tests -> Run workflow.
2. Notice that the onboarding test suite is skipped.

**Comment by RadoslavGeorgiev** [comment]
Assigning 2 SP as an average between only bumping a version or changing the E2E test ourselves.

**Comment by deepakpathania** [comment]
Blocked on `@woocomerce/admin-e2e-tests`, [reference](https://a8c.slack.com/archives/C026J0AL8NS/p1649835522089789). Created [issue](https://github.com/woocommerce/woocommerce/issues/32604) to track here.
