### ISSUE TITLE
Visually hidden text is not visually hidden

### ISSUE THREAD

**Issue by aprea** [Automattic/woocommerce-payments#4015]
### To Reproduce

1. As a merchant, navigate to **Payments → Settings**.
2. Scroll down to the "Transactions and deposits" section.
3. Observe the text:
> Manage and update your deposit account information to receive payments and payouts. [Manage in Stripe(opens in a new tab)](https://alleged-okapi.jurassic.ninja/wp-admin/admin.php?page=wc-settings&tab=checkout&section=woocommerce_payments&wcpay-login=1&_wpnonce=1a2a83408e)

The "(opens in a new tab)" text should not be visible. It's present in the DOM for screen readers but shouldn't actually be visible. I noticed the span element uses the `components-visually-hidden` class but I do not see any CSS styles attached to that class.

### Actual behavior
Visually hidden text is not visually hidden.

### Screenshots
<img width="627" alt="Screen Shot 2022-03-23 at 11 18 38 am" src="https://user-images.githubusercontent.com/1527164/159597714-224b175e-bf3b-40af-8cc0-2c8c7a4d9116.png">

### Expected behavior
Visually hidden text is visually hidden.

### Desktop (please complete the following information):

* Device: MBP
* OS: macOS 11.2.3 (20D91)
* Browser: Google Chrome Version 98.0.4758.109 (Official Build) (x86_64)

**Comment by oscarssanchez** [comment]
Hi @aprea ,

It seems the `<ExternalLink> `component uses `VisuallyHidden` as a dependency. The current version of `@wordpress/components` used by WC Payments seems to have a bug where the styles from `VisuallyHidden` are not being properly loaded.

In my opinion there's two possible solutions:

1.- Update the `@wordpress/components` dependency to the latest version (`19.7.0`) and re-build the assets. This will get rid of similar scenarios happening like these:

<img width="1356" alt="Screen Shot 2022-03-23 at 23 04 14" src="https://user-images.githubusercontent.com/31049169/159846671-2834a62b-5608-46ed-8e53-4b17b87ce981.png">

Also, this line could probably be deleted as well: https://github.com/Automattic/woocommerce-payments/blob/develop/client/components/payment-methods-checkboxes/payment-method-checkbox.scss#L77

Finally it will also ensure future compatibility.

2.- Create the css class (hacky), but it will solve the problem without needing to update the dependency.

I see the plugin has some tests in place, but am not sure how big of a lift it is to test updating the dependency. I'm happy to craft a PR based on your preference.

**Comment by aprea** [comment]
Hey @oscarssanchez, option 1 sounds good to me!

**Comment by oscarssanchez** [comment]
Thanks @aprea PR created!

**Comment by elizaan36** [comment]
hey yall, chiming in here. I agree that the best approach long term will be to update the components package and dependency to prevent this from happening again, however as an interim solution can we remove the `external-link` icon from the settings screens altogether?

I'm concerned that we've reached a stalemate with the best approach for updating the components package and this unwanted text leaves a negative brand impression on WCPay. Thoughts?

**Comment by zmaglica** [comment]
> hey yall, chiming in here. I agree that the best approach long term will be to update the components package and dependency to prevent this from happening again, however as an interim solution can we remove the `external-link` icon from the settings screens altogether?
> 
> I'm concerned that we've reached a stalemate with the best approach for updating the components package and this unwanted text leaves a negative brand impression on WCPay. Thoughts?

It would be nice to update components (or any package.json dependency) from time to time to prevent technical depth, and new code could be based on the newest components, which is nice. Maybe we could implement both solutions, bump dependency and remove the external link icon if needed.

**Comment by zmaglica** [comment]
I just tested with the latest WordPress, WooCommerce and WooCommerce Payments plugin and the issue is not presented. There is no "Opens in new tab" text. I tested it both in my local environment and on the fresh JN site. Please don't hesitate to reopen it if you still have the same issue. I am not certain how it's fixed. Maybe we fixed it in a period while this issue was not actively developed.

![image.png](https://images.zenhubusercontent.com/619211ebe2c8602efe4f243e/fc84e9aa-5e26-46d5-9dcc-76d689daa3d2)
