### ISSUE TITLE
Documents view: Settings page tabs

### ISSUE THREAD

**Issue by jessepearson** [Automattic/woocommerce-payments#4016]
### Description
The design shows the Settings page split into three tabs:

* General - current settings
* Account - account information, include tax info
* Documents - documents list

### Acceptance criteria

* The three tabs are created so that the merchant can navigate between the three.

### Designs

Designs can be checked in paJDYF-3mi-p2 and more details around scope are available in paJDYF-3sv-p2.

**Comment by luizreis** [comment]
We're closing this issue for now, as the settings page revamp will be handled in another project.
