### ISSUE TITLE
`type` parameter staying in url in address bar after viewing a transaction

### ISSUE THREAD

**Issue by jessepearson** [Automattic/woocommerce-payments#4039]
### Describe the bug
If you navigate to Payments > Transactions, then click on a transaction, a `type` parameter is added to the url in the address bar. After that, any navigation done within WCPay pages, the parameter remains. 

This parameter appears to have been added here: https://github.com/Automattic/woocommerce-payments/pull/3149/files#diff-ec9c21baeaaa8f8d287f18f4c6db1fd0fe26c1d0000ee85229d3676cff1c3cccR206

### To Reproduce

1. Navigate to Payments > Transactions.
2. Click on a transaction, and the parameter will be added in the url.
3. Navigate to Payments > Deposits, and the parameter will remain in the url.

### Screenshots
![Screen Capture on 2022-03-25 at 15-26-45](https://user-images.githubusercontent.com/4634416/160180176-c753a08b-88b2-465a-9813-9341bb39b931.gif)

**Comment by htdat** [comment]
@jessepearson - thanks for the report. I confirm your observations but I don't notice any negative effect to the Transactions screen. It's still listing all transactions of all types normally. 

![Screen Capture on 2022-03-29 at 19-25-13](https://user-images.githubusercontent.com/10045087/160610757-2443b65d-22e3-467b-a596-042f311895af.gif)

IMO, eventually, we should fix this but it's not a high priority issue. 

FYI. I am chaging/adding some labels but they can be changed after the discussion.

**Comment by jessepearson** [comment]
Thanks for taking a look 😁 

> I confirm your observations but I don't notice any negative effect to the Transactions screen. It's still listing all transactions of all types normally.

Correct, right now there are no adverse affects, however, with new development happening daily, the parameter staying in the address bar could potentially cause an issue in another section. We are adding a Documents section that has types, but so far it hasn't affected them due to the filters use `type_is` and not just `type`. 

I added `high` for the priority due to it's higher than `low`, and this isn't `critical`, but should probably be fixed sooner than later.

**Comment by htdat** [comment]
> I added `high` for the priority due to it's higher than `low`, and this isn't `critical`, but should probably be fixed sooner than later.

Thanks for the context @jessepearson! 

--- 

Hi team @Automattic/pulsar, can you have a look and may add this issue into your sprint? The cause seems to relate to the PR by the team.

**Comment by anu-rock** [comment]
The same behavior also applies to a transaction clicked from Payments → Deposits → Deposit details → Deposit transactions.

It's interesting to note that while the "type" param becomes "sticky," the stickiness doesn't apply to other params such as "id," "transaction_id", etc.

**Comment by anu-rock** [comment]
cc @dpaun1985

**Comment by kalessil** [comment]
@dpaun1985 @anu-rock : looks like a low-prio issue to me, we could address it one of the next sprints.

**Comment by kalessil** [comment]
@htdat, what's the PR you are referencing to in https://github.com/Automattic/woocommerce-payments/issues/4039#issuecomment-1082604775 ?

**Comment by htdat** [comment]
@kalessil - it's this one, which is mentioned by @jessepearson in his `Describe the bug` section.

> https://github.com/Automattic/woocommerce-payments/pull/3149/files#diff-ec9c21baeaaa8f8d287f18f4c6db1fd0fe26c1d0000ee85229d3676cff1c3cccR206
