### ISSUE TITLE
[GlobalStep] Logo image fails to display for "UPE Payment Method" on "WooCommerce Payments" page.

### ISSUE THREAD

**Issue by gglobalstep** [Automattic/woocommerce-payments#4050]
### Bug Description:
Logo image fails to display for "UPE Payment Method" on "WooCommerce Payments" page..

###  Environment:
Woocommerce Version : WooCommerce 6.3.1
WooCommerce  Payments  4.0.0-test-1
WordPress version: v5.9.2

PC:
Windows 10
Chrome(Version 99.0.4844.84) 
Firefox(Version 98.0.1)
Mac OS:
Safari: v15.4

###  Steps To Reproduce:
1. Create any test site using JN site.
1. Install and activate all the required plugins.
1. Upload and activate theWooCommerce Payments - 4.0.0-test-1 plugin.
1. Go to WooCommerce > Settings  > Payment page.
1. Observe that all Logo images fail to display for "UPE Payment Method" on "WooCommerce Payments" page.

###  Actual Result:
Logo image fails to display for "UPE Payment Method" on "WooCommerce Payments" page.

###  Expected Result:
Logo image should be properly diplayed for "UPE Payment Method" on "WooCommerce Payments" page.

###  Screenshot:

![#4050](https://user-images.githubusercontent.com/41110392/160629847-66765ddc-9391-4d1e-a644-9f5e6da460f1.jpg)

*Isolating the problem (mark completed items with an [x]):*
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront.
- [x] I can reproduce this bug consistently using the steps above.

<details>

`
### WordPress Environment ###

WC Version: 6.3.1
REST API Version: ✔ 6.3.1
WC Blocks Version: ✔ 6.9.0
Action Scheduler Version: ✔ 3.4.0
WC Admin Version: ✔ 3.2.1
Log Directory Writable: ✔
WP Version: 5.9.2
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache/2.4.53 (Unix) OpenSSL/1.0.2g
PHP Version: 7.4.28
PHP Post Max Size: 1 GB
PHP Time Limit: 30
PHP Max Input Vars: 5000
cURL Version: 7.47.0
OpenSSL/1.0.2g

SUHOSIN Installed: –
MySQL Version: 5.7.33-0ubuntu0.16.04.1-log
Max Upload Size: 512 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 6.3.1
WC Database Prefix: wp_
Total Database Size: 8.23MB
Database Data Size: 6.24MB
Database Index Size: 1.99MB
wp_woocommerce_sessions: Data: 0.03MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 0.08MB + Index: 0.09MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 0.14MB + Index: 0.14MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 0.11MB + Index: 0.09MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 0.13MB + Index: 0.09MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_options: Data: 4.45MB + Index: 0.09MB + Engine InnoDB
wp_postmeta: Data: 0.38MB + Index: 0.38MB + Engine InnoDB
wp_posts: Data: 0.13MB + Index: 0.06MB + Engine InnoDB
wp_snippets: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.05MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_attributes_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB

### Post Type Counts ###

attachment: 24
page: 10
post: 2
product: 24
product_variation: 7
revision: 3
shop_coupon: 1
shop_order: 52
shop_order_refund: 6
shop_subscription: 20
wp_global_styles: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (5) ###

Query Monitor: by John Blackbourn – 3.8.2
Code Snippets: by Code Snippets Pro – 2.14.3
Companion Plugin: by Osk – 1.24
WooCommerce Payments: by Automattic – 4.0.0-test-1
WooCommerce: by Automattic – 6.3.1

### Inactive Plugins (6) ###

Akismet Anti-Spam: by Automattic – 4.2.2
Hello Dolly: by Matt Mullenweg – 1.7.2
Jetpack: by Automattic – 10.7
WooCommerce Blocks: by Automattic – 7.3.0
WooCommerce Payments Dev Tools: by Automattic –
WooCommerce Subscriptions: by WooCommerce – 4.1.0

### Dropin Plugins (1) ###

db.php: Query Monitor Database Class

### Settings ###

API Enabled: –
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
subscription (subscription)
variable (variable)
variable subscription (variable-subscription)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –

### WC Pages ###

Shop base: #6 - /shop/
Cart: #7 - /cart/
Checkout: #8 - /checkout/
My account: #9 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Storefront
Version: 4.0.0
Author URL: https://woocommerce.com/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Subscriptions ###

WCS_DEBUG: ✔ No
Subscriptions Mode: ✔ Live
Subscriptions Live URL: https://energetic-shrimp.jurassic.ninja
Subscription Statuses: wc-cancelled: 1
wc-active: 19

WooCommerce Account Connected: ❌ No

### Store Setup ###

Country / State: United States (US) — California

### Subscriptions by Payment Gateway ###

WooCommerce Payments: wc-active: 19
wc-cancelled: 1

### Payment Gateway Support ###

WooCommerce Payments: products
refunds
multiple_subscriptions
subscription_cancellation
subscription_payment_method_change_admin
subscription_payment_method_change_customer
subscription_payment_method_change
subscription_reactivation
subscription_suspension
subscriptions
gateway_scheduled_payments
tokenization
add_payment_method

### WooCommerce Payments ###

Version: 4.0.0-test-1
Connected to WPCOM: Yes
Blog ID: 204620016
Account ID: acct_1KiZPn2HuOXtymeZ

### Action Scheduler ###

Canceled: 1
Oldest: 2022-03-29 12:02:30 +0000
Newest: 2022-03-29 12:02:30 +0000

Complete: 370
Oldest: 2022-03-29 07:28:49 +0000
Newest: 2022-03-29 11:52:11 +0000

Pending: 22
Oldest: 2022-03-29 15:02:41 +0000
Newest: 2022-05-29 11:47:02 +0000

### Status report information ###

Generated at: 2022-03-29 13:51:16 +00:00
`
</details>

**Comment by htdat** [comment]
This is a regression issue from this PR https://github.com/Automattic/woocommerce-payments/pull/4035 on [this specific file](https://github.com/Automattic/woocommerce-payments/pull/4035/files#diff-3ff0f3b11d3405e9bbb2985c409cfad67d4a5f7aad408300e78bc47deaf0a3ae). 

It changes the signature of a property from `Icon` to `icon` but a component using this object has not been updated yet. This simple fix seems to help https://gist.github.com/htdat/0eab4d860426a89a39323cce3a4558da

IMO, there are something we can improve here: 

- Improve our tests to cover this check. I did not check too deeply, but maybe a snapshot test is helpful here. 
- Be mindful when changing a property name. If we need to do that, do manual checks for its consumers too.

@naman03malhotra @vbelolapotkov - We may want to fix this issue ASAP but I am not sure which team is the best to handle this issue. It can be either @Automattic/pulsar or @Automattic/gamma

**Comment by htdat** [comment]
cc @cesarcosta99 as the current release lead too.

**Comment by vbelolapotkov** [comment]
> @naman03malhotra @vbelolapotkov - We may want to fix this issue ASAP but I am not sure which team is the best to handle this issue. It can be either https://github.com/orgs/Automattic/teams/pulsar or https://github.com/orgs/Automattic/teams/gamma

@htdat https://github.com/Automattic/woocommerce-payments/pull/4035 was merged only two days ago so shouldn't be released yet. Have you tested it with latest released version 3.9.1?

**Comment by htdat** [comment]
> @htdat https://github.com/Automattic/woocommerce-payments/pull/4035 was merged only two days ago so shouldn't be released yet. Have you tested it with latest released version 3.9.1?

It's not the issue with 3.9.x. When saying here "ASAP", I meant we may want to prioritize in fixing it.

**Comment by vbelolapotkov** [comment]
yep, definitely before the next release :) 
cc @kalessil

**Comment by kalessil** [comment]
Pulling into our Sprint @vbelolapotkov.

**Comment by kalessil** [comment]
Related: https://github.com/Automattic/woocommerce-payments/pull/4063
