### ISSUE TITLE
Shipping/Taxes not applied when switching variations while using Apple/Google Pay

### ISSUE THREAD

**Issue by achyuthajoy** [Automattic/woocommerce-payments#4064]
### Describe the bug

With Apple Pay/ Google Pay enabled on WooCommerce Payments -> Settings, choosing a different product variation on the product page & checking out with Apple/Google Pay doesn't include the configured Shipping/Tax rates. This was discovered while reviewing this [PR](https://github.com/Automattic/woocommerce-payments/pull/4030).

### To Reproduce

* Enable Apple/Google Pay on WooCommerce Payments -> Settings (you'll need a live URL with SSL to test Google/Apple Pay).
* Create a variable or variable subscription product & choose a default variation.
* Setup a Shipping & Tax rate under WooCommerce -> Settings
* Go to the product page, choose any variation from the list and click on Apple/Google Pay. Confirm that the configured shipping/tax rates are applied as expected.
* Close the Apple/Google Pay popup.
* Choose another variation from the list without refreshing the page.
* Click on Apple/Google Pay. Notice that shipping/tax rates are not applied.

### Screenshots

* Shipping/tax rates applied as expected when Apple/Google Pay is used for the first time

![Screenshot](https://d.pr/i/zR0a1N+)

* Missing shipping/tax rates on next tries

![Screenshot](https://d.pr/i/mMRcAB+)

### Expected behavior

Shipping/Taxes should be included while checking out with Apple/Google Pay even when variations are changed.

**Comment by jessy-p** [comment]
This happens because it is only on the first variation change, Stripe triggers the [shippingaddresschange](https://stripe.com/docs/js/payment_request/events/on_shipping_address_change) event. This means on the first variation change after page load , the shipping address is returned and shipping cost is calculated and updated in the preview screen.
From the next variation change, we are not able to calculate and update the shipping cost. There is a `woocommerce_variation_has_changed` event, but  unable to trigger a `shippingaddresschange` event.

**Comment by jessy-p** [comment]
This issue impacts Express checkout buttons, checkout UI, Local Payment Methods, Buy Now Pay Later (BNPL), and Additional Payment Methods (including Apple Pay / Google Pay), so assigning to Heisenberg (based on team responsibilities Pc2DNy-3z-p2) @FangedParakeet. Assigning as part of Gamma Triage process PcreKM-yM-p2.

Tagging as part of re-evaluating older issues in the backlog, please have a look and close if no longer relevant.

**Comment by mdmoore** [comment]
Having recently worked on similar issues with the payment request buttons, I thought I had seen shipping and tax working correctly for variations. Testing it out today, it does appear to be fixed. I think https://github.com/Automattic/woocommerce-payments/pull/7926 took care of it.

-----

**Shipping & Tax applied for default variation**

![image](https://github.com/Automattic/woocommerce-payments/assets/3473953/38719cce-c3ab-4c1d-a505-e56141a0fab1)

**Shipping & Tax apdated for second variation without a page refresh**

![image](https://github.com/Automattic/woocommerce-payments/assets/3473953/54e076c8-b604-48bb-80c1-05e8f070a71d)


Now that `wc_ajax_wcpay_add_to_cart` and `wc_ajax_get_shipping_options` are firing correctly, shipping, tax, and totals are updated and displayed correctly. I'll go ahead and close this, but please reopen if this happens to surface again.
