### ISSUE TITLE
Card Readers: Preview print receipt fails on Firefox

### ISSUE THREAD

**Issue by mgascam** [Automattic/woocommerce-payments#4070]
### Describe the bug

The printed receipt preview is blank in FF, works as expected in other browsers.

### To Reproduce

1. Go to WP Admin > Payments > Card Readers
2. Go to Receipt Details tab
3. Click Preview a printed receipt link
4. Check that the generated preview is blank

### Actual behavior

The generated preview is blank.

### Screenshots

<img width="1284" alt="Screen Shot 2022-04-05 at 17 58 15" src="https://user-images.githubusercontent.com/1553182/161796061-61c1bbc7-8f98-4c98-a2ec-9120f4979ec8.png">

### Expected behavior

There is a preview of the receipt.
### Desktop:

* Browser Firefox
* Version 98

### Additional context

Works fine in other browsers

**Comment by kalessil** [comment]
@mgascam, please update the description on Monday. Meanwhile, I'm pulling this into our Sprint.

**Comment by mgascam** [comment]
This seems relevant https://github.com/facebook/react/issues/22847

**Comment by kalessil** [comment]
THanks for looking into it! Looks like someone proposed a workaround there: https://github.com/facebook/react/issues/22847#issuecomment-991394558.
