### ISSUE TITLE
Text placeholders not working on In Person Payment receipt email

### ISSUE THREAD

**Issue by mgascam** [Automattic/woocommerce-payments#4071]
### Describe the bug

The placeholders `{site_title}` and `{site_url}` in the 'New Receipt' email are not being injected. They remain as `{site_title}` and  `{site_url}` in the email's text.

### To Reproduce

1. Pay for an order with a card reader
2. Check the email sent to customer

### Actual behavior

See that placeholders are not replaced
### Screenshots

![Screen Shot 2022-04-05 at 12.31.15.png](https://images.zenhubusercontent.com/6151eaf2cacd680dad2b3af4/c889fbd4-b8fa-4a5f-a282-8e29e340685f)

### Expected behavior

The placeholders are replaced by the site and url of the merchant's site.

**Comment by kalessil** [comment]
@mgascam, please update the description on Monday. Meanwhile, I'm pulling this into our Sprint.
