### ISSUE TITLE
Remove WooCommerce Payments from taking over the Settings > Payments screen.

### ISSUE THREAD

**Issue by ryanr14** [Automattic/woocommerce-payments#4073]
### Description
If I want to manage any payment methods settings, besides WooCommerce Payments, I always have to see the WooCommerce Payments settings needlessly before getting back to the main Payments screen to choose the correct payment method.

Why do we do this?

There is already a very quick way to get to the specific WooCommerce Payments settings from the main WordPress admin menu under Payments > Settings. I'd like us to leave the WooCommerce > Settings > Payments alone.

What would we do if any other developer made their payment method settings take over like WooCommerce Payments does? Would we allow it?

**Comment by aheckler** [comment]
I'll +1 this, not as WC Pay PA, but just as a reasonable WooCommerce user/expert. If we want WC Pay to succeed, we should make it good enough that it does so on it's own merits, not because we've "growth hacked" our way there.

**Comment by htdat** [comment]
@LevinMedia would you mind having a look at this issue?

**Comment by elizaan36** [comment]
+1. The **Settings > Payments** path should default to "All payment methods".
