### ISSUE TITLE
Refactor the mobile phone number input

### ISSUE THREAD

**Issue by cesarcosta99** [Automattic/woocommerce-payments#4116]
### Description

We could use some improvements to make the mobile phone number input clearer and avoid confusion with its value.

When we fill out the left section at the checkout, and then tick `Save my information for faster checkouts`, the phone number there is copied over there automatically. We see 2 country codes: one in the country select and another in the input. This might lead the user to think they'd need to remove the country code of the input.

Another situation is when we have a country code in the number and we select another country in the select, it doesn't take effect in the phone number.

Removing the country code next to the flag seems to be simple and resolve part of the issues.

<img width="340" alt="image" src="https://user-images.githubusercontent.com/10233985/162534609-fa310111-ef63-4c6c-a44e-e06d1805596c.png">

### Testing instructions

1. Enable the platform checkout.
2. Go to the shop, add any product to the cart and go to checkout.
3. Tick `Save my information for faster checkouts`
4. Play with the mobile phone input and country select. Type the phone number and later change the country select. You'll likely face some inconsistencies.

### Additional context

p1649439774429649-slack-C022WMN88KG

**Comment by alefesouza** [comment]
Fixed on #4242.
