### ISSUE TITLE
Dispute task on overview screen checks only most recent disputes

### ISSUE THREAD

**Issue by dechov** [Automattic/woocommerce-payments#4123]
The overview screen features a task that is intended to alert the merchant to the _number of disputed payments that need their response_ [[source](https://github.com/Automattic/woocommerce-payments/blob/5f07f1d1428a5cc917057c363a930ad52697ca41/client/overview/task-list/tasks.js#L131-L159)], but it is derived from an incomplete selection of disputes. The relevant hook [[source](https://github.com/Automattic/woocommerce-payments/blob/cbf2927962e26b81d8b0e245678222254cc993a7/client/overview/index.js#L38)], which originally always selected the 100 latest disputes, now works properly with pagination and defaults to 25 [[source](https://github.com/Automattic/woocommerce-payments/blob/cbf2927962e26b81d8b0e245678222254cc993a7/client/data/disputes/hooks.ts#L74)], and so the dispute task would only show the disputes needing response _out of the latest 25_. In other words, if any disputes needing response drop off the first page of the Disputes list, they will not (ever again) be included in the alert on the overview screen.

A limited improvement would be to raise the `perPage` parameter, but I suspect we'll want a more robust approach to ensuring the correctness of this alert. In my view, this should be examined in tandem with https://github.com/Automattic/woocommerce-payments/issues/354 (cc @jessy-p), and we could consider a combination of:
- calculating on the server the number of disputes needing response, perhaps including it in the new summary endpoint response
- caching the current value on the site backend, perhaps incrementing/decrementing in response to forwarded webhooks

(Also, there's a small typo / grammatical error in the alert: "disputed payments needs your response")

**Comment by james-allan** [comment]
Just to clarify, this issue is in relation to the disputes task list item on the **Payments > Overview** screen.

<img width="1045" alt="Screen Shot 2022-05-31 at 2 08 44 pm" src="https://user-images.githubusercontent.com/8490476/171091076-83becede-22d6-4fd1-986b-0bb079d16db3.png">

❗ ⚠️  **Important notes**. 

You'll need:

- to [enable the _Overview task list_ feature using WCPay Dev Tools](https://user-images.githubusercontent.com/8490476/171091315-286c276e-701a-4c55-aec7-0d4a7d348df4.png) for this to be displayed.
- disputed payments - you do that by simply using a [dispute test card](https://stripe.com/docs/testing#disputes) when making a purchase through the checkout.

**Comment by haszari** [comment]
Investigating #4341 I happened upon some of how this works so adding this comment with some breadcrumbs to pick up later 🥖 🧀 …

- The `Payments > Overview` task list is generated and managed client-side in [JavaScript code `client/overview/task-list`](https://github.com/Automattic/woocommerce-payments/tree/develop/client/overview/task-list)
- It gets its `tasks` data from [the `data/disputes` store](https://github.com/Automattic/woocommerce-payments/blob/develop/client/data/disputes/hooks.ts), see hooks `useDisputes` and `useDisputesSummary`
- Those hooks have params for pagination etc. I suspect these aren't getting used right now, unless they are in page query params for some reason - e.g. `useDisputes( getQuery() )`

https://github.com/Automattic/woocommerce-payments/blob/a661754d6def0fbcf9be9113adcbe8eb66852075/client/overview/index.js#L38


- We're manually filtering the disputes that need response on the output of the hook. We might be better pushing that logic up to store or hooks layer

https://github.com/Automattic/woocommerce-payments/blob/a661754d6def0fbcf9be9113adcbe8eb66852075/client/overview/task-list/tasks.js#L16-L26

We might be able to fix the pagination issue in a couple of ways.

1. Pass hard-coded params to force loading "all" disputes or "all needing response" to the hook.
2. Use `useDisputesSummary` or another (new custom) hook to get only disputes that need a response, or just a count, e.g. `useDisputesCount( status: [ 'needs_response', 'warning_needs_response' )` (pseudocode alert)

FYI @shendy-a8c @Jinksi  who have been looking at this too

**Comment by haszari** [comment]
WIP PR with a larger page size - https://github.com/Automattic/woocommerce-payments/pull/4380

Looks like it fixes the issue!? 🎉 
<img width="870" alt="Screen Shot 2022-06-30 at 5 03 45 PM" src="https://user-images.githubusercontent.com/4167300/176596765-67a88afc-e11a-4b75-a70c-5bdaba97227c.png">

**Comment by haszari** [comment]
> As of https://github.com/Automattic/woocommerce-payments/pull/4326 there's a dedicated endpoint for obtaining the total number of disputes needing review – and caching mechanism for it – which should be suitable on any scale without having to load individual disputes. (If we were to still load individual disputes, we could filter by status.)

Nice - so we could use a different (new) hook that targets the totals/summary view. Great plan @dechov  💯
