### ISSUE TITLE
Disputes page: Display "Needs response" items by default

### ISSUE THREAD

**Issue by htdat** [Automattic/woocommerce-payments#4124]
### Description

In the disputes page, we display "Needs response" items by default rather than all items.

@dechov mentioned this:

> It’s now possible with the “advanced filters”, but maybe we want a shortcut to a view that filters to “needs response” and sorts by due date?

@reykjalin: 

> We probably should default to showing the disputes that need a response.

### Acceptance criteria

- Add "Needs Response" filter to the disputes "Show" filter that can be selected on page load using a `filter` query param. (#4361)
- Selecting this filter option will only show disputes with one of the following statuses: `needs_response` or `warning_needs_response`. (#4361) 
- This filter should be selected by default if one or more disputes are awaiting a response.

### Designs

<img width="400" alt="image" src="https://user-images.githubusercontent.com/3147296/174949554-bab1f951-ccc1-4f1c-9928-b4da918bfce1.png">

### Additional context

p1649724071565769-slack-CGGCLBN58
pdjTHR-17I-p2#comment-1440

cc @LevinMedia

**Comment by haszari** [comment]
FYI this is at `needs design` because we likely need to consider this in the wider disputes UX before implementing a solution. Specifically showing `Needs response` filter as default may not be the best way to improve this.

cc @rogermattic (based on your thoughts in other doc)

**Comment by haszari** [comment]
> FYI this is at needs design because we likely need to consider this in the wider disputes UX before implementing a solution. Specifically showing Needs response filter as default may not be the best way to improve this.

Updating after discussion with @thenbrent . 

We've decided to go with a "smart defaults" approach here. Something like this: 

- Ensure we have appropriate filtering in the UI:
  - #282
- If there are disputes that need a response, apply the filter to display those by default. 

This allows us to start implementing. We may need a design review or input before we ship, but I'm removing `needs design` for now. FYI @rogermattic

**Comment by rogermattic** [comment]
Thanks a lot @haszari - let me know when there's a prototype that I can review!

**Comment by haszari** [comment]
One option would be to add an item to the dropdown menu: `Needs response` - hat tip @james-allan 

![screen-shot-2022-06-14-at-5 14 30-pm](https://user-images.githubusercontent.com/4167300/173958250-cc5b532e-f318-482a-a715-208252413e17.jpg)

This feels like the leanest way to allow drilling down to needs response. We could auto-select this when merchant has some outstanding disputes, as a smart default. If there are none that need response, we'd fall back to `All`.

I've started hacking on a branch to add this dropdown item, next step is to actually filter the table (if anyone wants to pick it up): https://github.com/Automattic/woocommerce-payments/tree/try/disputes-need-response-dropdown-filter-option

**Comment by Jinksi** [comment]
> One option would be to add an item to the dropdown menu: `Needs response`

To a achieve this, we need to be able to filter disputes with a `status` of either `needs_response` or `warning_needs_response`. Currently, this would require multiple requests to the WCPay `disputes` endpoint OR fetching extraneous disputes before filtering on the frontend.

I've opened an issue on WCPay-server about this: 2124-gh-Automattic/woocommerce-payments-server

**Comment by Jinksi** [comment]
I've updated the issue description with some acceptance criteria:

* Add "Needs Response" filter to the disputes "Show" filter that can be selected on page load using a filter query param.
* Selecting this filter option will only show disputes with one of the following statuses: `needs_response` or `warning_needs_response`.
* This filter should be selected by default if one or more disputes are awaiting a response.

**Comment by Jinksi** [comment]
Re-opened as #4361 is only a partial fix.
