### ISSUE TITLE
Remove the color fields on receipt settings page

### ISSUE THREAD

**Issue by anu-rock** [Automattic/woocommerce-payments#4144]
The primary and secondary color fields on the **Payments** > **Card Readers** > **Receipt Details** page were primarily meant for Stripe's [prebuilt receipts](https://stripe.com/docs/terminal/features/receipts#prebuilt). Now that we have our own email template (#4014), we don't need these fields anymore.

![image](https://user-images.githubusercontent.com/1288616/163793462-1dd6697f-036e-4b5f-b1d9-cb617a859187.png)

**Comment by mgascam** [comment]
During development we decided to augment the scope of this task to remove the icon upload controller as well, since it was used by Stripe.
I also amended the copy test to reflect the fact that the logo will not be used in emails.
