### ISSUE TITLE
Appearance parameter passed to Stripe Elements incorrectly

### ISSUE THREAD

**Issue by FangedParakeet** [Automattic/woocommerce-payments#4145]
### Describe the bug

Stripe offers us an [Elements Appearance API](https://stripe.com/docs/stripe-js/appearance-api) with which to pass custom styling to the UPE. Since [Stripe updated their API, such that we no longer need to use their beta](https://github.com/Automattic/woocommerce-payments/pull/3534) in order to have access to the UPE, the placement of some of the necessary parameters has changed. The parameter relevant to this issue--`appearance`--is no longer added to the `PaymentElement` as an option, as [we are currently adding it in the current Blocks checkout configuration](https://github.com/Automattic/woocommerce-payments/blob/develop/client/checkout/blocks/upe-fields.js#L197-L211). Instead it must be passed as an option to the parent Elements provider, as described in [this Stripe quickstart example](https://stripe.com/docs/payments/quickstart).  

Specifically, this `appearance` parameter must now be added [to the options object here in our codebase](https://github.com/Automattic/woocommerce-payments/blob/develop/client/checkout/blocks/upe-fields.js#L264-L269), rather than to the `PaymentElement` options, as is currently performed and described above. This change has been made correctly on the [regular classic checkout](https://github.com/Automattic/woocommerce-payments/blob/develop/client/checkout/classic/upe.js#L338-L342), so this issue only affects the Blocks checkout. 

I have given this issue a high priority and impact, since it affects all current users of the Blocks checkout. However, since this only degrades the appearance of the element and does not impact any checkout functionality, as far as I'm aware, I have not given it a critical status.

### To Reproduce

1. Please refer to Stripe's [documentation](https://stripe.com/docs/stripe-js/appearance-api) about styling any payment elements and refer to [this quickstart example](https://stripe.com/docs/payments/quickstart), which shows how this parameter must be used in practice.
2. Enable the UPE at checkout using the Dev Tools. Note that when using the Blocks checkout, changing the site's theme has no effect on the appearance of the payment element at checkout.
3. I think that's it really.

### Actual behavior

UPE payment element does not use cached theme-specific styling at checkout during the Blocks checkout.

### Screenshots

Sorry.

### Expected behavior

UPE payment element should pass `appearance` parameter correctly to Elements provider and should apply custom styles to payment element during both classic and Blocks checkouts. 

### Desktop (please complete the following information):

* OS: [e.g. iOS]
* Browser [e.g. chrome, safari]
* Version [e.g. 22]

### Smartphone (please complete the following information):

* Device: [e.g. iPhone6]
* OS: [e.g. iOS8.1]
* Browser [e.g. stock browser, safari]
* Version [e.g. 22]

**Comment by laurendavissmith** [comment]
@naman03malhotra Can we get this one pulled into a Gamma sprint soon?

**Comment by naman03malhotra** [comment]
@laurendavissmith we have taken this on priority, @achyuthajoy will be working on it.
