### ISSUE TITLE
UPE Survey Enhancement 

### ISSUE THREAD

**Issue by bmccotter** [Automattic/woocommerce-payments#4146]
### Description

Goal: require a more detail with UPE disablement survey submissions.

### Acceptance criteria

Stripe is requesting more details to our feedback, can we request that folks supply examples, logs, or relevant site details to help us troubleshoot and pass this back to Stripe?

* Split "slow or buggy" into two separate checkboxes - one for "It is slow" and one for "It is buggy" (these are different things we want to track separately)
* Change "Comments (Optional)" label to say "Please provide additional details to help us improve the experience"
* System status report (ideally entire report)

### Designs
Here's a quick mockup of the new form. The System Status report submission should be included below "Additional Fields" and be editable so submitters can review and remove any data they do not wish to submit.

<img width="1035" alt="Screen Shot 2022-04-21 at 16 12 32" src="https://user-images.githubusercontent.com/235523/164386075-106c9790-d358-4e49-ae1c-20ff37af3663.png">

### Testing instructions
NA

### Additional context

p6q7sZ-aiB-p2#comment-27970

**Comment by thenbrent** [comment]
There's some further discussion on the requirements for this here: p6q7sZ-aiB-p2#comment-27971

**Comment by thenbrent** [comment]
I've updated the description to include requirements and a visual mockup of the new form.

**Comment by bmccotter** [comment]
Amazing, thanks @thenbrent !
