### ISSUE TITLE
Refactor the direct DB query in Invoice Service to use `wc_get_orders()`/`WC_Order_Query`

### ISSUE THREAD

**Issue by mattallan** [Automattic/woocommerce-payments#4147]
### Description

With [Custom Order tables coming to WooCommerce Core](https://developer.woocommerce.com/2022/01/17/the-plan-for-the-woocommerce-custom-order-table/), direct DB queries that fetch orders by post meta will need to be reworked/updated to work with orders stored in custom tables.

This issue is to look at the post query in [`WC_Payments_Invoice_Service::get_order_id_by_invoice_id()`](https://github.com/Automattic/woocommerce-payments/blob/dd9d319b661427a1d22a5aeab945c23dd429f317/includes/subscriptions/class-wc-payments-invoice-service.php#L105) and replace the direct query with a DB agnostic approach i.e. using `wc_get_orders( [ '_wcpay_billing_invoice_id', 'testinvoiceID' ] )`.

### Dev notes

There's a guide on how to use `wc_get_orders()` with custom meta here: https://github.com/woocommerce/woocommerce/wiki/wc_get_orders-and-WC_Order_Query#adding-custom-parameter-support

### Additional context

**Project thread:** pdjTHR-Xp-p2
**Exploration p2:** pdjTHR-YX-p2

**Comment by naman03malhotra** [comment]
Blocked on subscriptions being compatible with COT.
