### ISSUE TITLE
Refactor the direct DB query which counts the number of multi-currency orders to use `wc_get_orders()`/`WC_Order_Query`

### ISSUE THREAD

**Issue by mattallan** [Automattic/woocommerce-payments#4148]
### Description

With [Custom Order tables coming to WooCommerce Core](https://developer.woocommerce.com/2022/01/17/the-plan-for-the-woocommerce-custom-order-table/), direct DB queries that fetch orders by post meta will need to be reworked/updated to work with orders stored in custom tables.

This issue is to look at the direct WP post query in [`Tracking::get_mc_order_count()`](https://github.com/Automattic/woocommerce-payments/blob/dd9d319b661427a1d22a5aeab945c23dd429f317/includes/multi-currency/Tracking.php#L117-L144) and replace it with `wc_get_orders()`/`WC_Order_Query`.

### Dev notes

There's a wiki on how to use `wc_get_orders()` with custom meta [here](https://github.com/woocommerce/woocommerce/wiki/wc_get_orders-and-WC_Order_Query#adding-custom-parameter-support), however I don't know how that DB query will translate to using something like `wc_get_orders()`. 

If it's not a simple task, we might have to go with some other approach where we surround this with a if/else condition and use this WP post query on stores not using custom order tables and then write a new query to fetch the orders in custom order tables. We should try to avoid having direct DB queries as they won't work for any custom data stores that stores may have implemented.

### Additional context

**Project thread:** pdjTHR-Xp-p2
**Exploration p2:** pdjTHR-YX-p2

**Comment by jessy-p** [comment]
In addition to `Tracking::get_mc_order_count()`, `Multicurrency::get_all_customer_currencies` also uses direct DB query within multicurrency feature.
