### ISSUE TITLE
Handle new line in changelog entry

### ISSUE THREAD

**Issue by shendy-a8c** [Automattic/woocommerce-payments#4150]
### Describe the bug

Today as I am to prepare for this week's testing package, I notice this error: https://github.com/Automattic/woocommerce-payments/runs/6071045933?check_suite_focus=true#step:11:81 that is caused by a new line in [one of the changelog entry](https://github.com/Automattic/woocommerce-payments/pull/4049/files#diff-fe8a0960624868cf0ed34795d9533b72fb5342e8284af9c1986acaa465e92b4bR4-R5).

To unblock me from creating the testing package, I [correct the changelog manually](https://github.com/Automattic/woocommerce-payments/pull/4149).

I think to prevent this from happening again in the future, we need some kind of validation or some sort.

Two problems I see from that changelog entry:
1. It starts with `Fix - `.
2. It has multiple lines.

I wonder if @achyuthajoy added that changelog entry by running `npm run changelog` or by adding `changelog/fix-pay-for-order-upe-checkout` file manually.

I can see that there might be no trivial way to avoid this and validation might need to happen during PR review. If so, feel free to close this issue.

### To Reproduce

1. Run `npm run changelog`
3. Add multi-lines entry.

### Actual behavior

Currently, you should be able to.

### Expected behavior

You shouldn't be able to.

**Comment by shendy-a8c** [comment]
@achyuthajoy did you add [that file](https://github.com/Automattic/woocommerce-payments/pull/4049/files#diff-fe8a0960624868cf0ed34795d9533b72fb5342e8284af9c1986acaa465e92b4b) manually or did you generate that by running `npm run changelog`?

**Comment by achyuthajoy** [comment]
@shendy-a8c I used `npm run changelog`

**Comment by shendy-a8c** [comment]
I tried it myself when running `npm run changelog`, as I hit the return key to add a newline, it submits my text. How did you end up with newline in the changelog entry @achyuthajoy?

**Comment by achyuthajoy** [comment]
@shendy-a8c I absolutely don't have any idea @shendy-a8c. I didn't notice the process then. Now it's working as you said.

**Comment by RadoslavGeorgiev** [comment]
Seems like this is not coming up anymore, as there are no further reports. Even if it happened, the release lead can manually fix the new line, so I'm closing this issue for now. If there are any new reports, we can take another look.
