### ISSUE TITLE
Update code calling `get_post_meta()` with an Order IDs and use CRUD methods instead

### ISSUE THREAD

**Issue by mattallan** [Automattic/woocommerce-payments#4152]
### Description

With Custom Order Tables being worked on by the WC Core team ([public announcement](https://developer.woocommerce.com/2022/01/17/the-plan-for-the-woocommerce-custom-order-table/)), we need to begin to think about updating the WC Payments code to remove any code that is calling WP Post API functions.

From what I found there is only one line that uses `get_post_meta()` and passes an Order ID:
 - [ ] [`WCPay\MultiCurrency\Compatibility\WooCommerceSubscriptions::override_selected_currency()`](https://github.com/Automattic/woocommerce-payments/blob/ca0aa7a9160647e3612bffc8b9e0f935bea3acd1/includes/multi-currency/Compatibility/WooCommerceSubscriptions.php#L151)

### How to update?
This line should be replaced with $object->get_meta( $property ) or $object->get_{property_name}() if the function exists.

### Additional context

**Project thread:** pdjTHR-Xp-p2
**Exploration p2:** pdjTHR-YX-p2

**Comment by haszari** [comment]
Looks like there's a unit test for this: https://github.com/Automattic/woocommerce-payments/blob/ac01055cfee91caa9ce261e4ed3333250eff0fdd/tests/unit/multi-currency/compatibility/test-class-woocommerce-subscriptions.php#L257

I'm working on tracking down how this code is called, i.e. what flow(s) are impacted. Possibly related to renewing a subscription (integration with paid extension? not WCPay Subscriptions) with WCPay multi-currency enabled.

**Comment by haszari** [comment]
Side question: @mattallan  how do you know that the other `get_post_meta` calls aren't using order ids? 

https://github.com/Automattic/woocommerce-payments/blob/ca0aa7a9160647e3612bffc8b9e0f935bea3acd1/includes/multi-currency/Compatibility/WooCommerceSubscriptions.php#L159-L168

I'm guessing that you know those two `subscription_id`s are not orders, so we're ok. I wanted to ask about this because it feels like we could miss some fixes.

**Comment by haszari** [comment]
Looks like we can use `$order->get_currency()`:

https://github.com/woocommerce/woocommerce/blob/dc095300c275311f5ae1aeea863c747ef3f435f0/plugins/woocommerce/includes/abstracts/abstract-wc-order.php#L297-L299

**Comment by mattallan** [comment]
> how do you know that the other get_post_meta calls aren't using order ids?

Yeah good question! Part of the process of creating this issue I searched every `get_post_meta()` call in WC Payments and followed the code to make sure an Order ID is passed. Most of the time it was pretty obvious, but there were some cases where I was unsure, like `get_post_meta( $switch_id )`. Is the switch ID a switch order or a subscription ID? I confirmed it's a Subscription and didn't need to be updated.

That said, it's definitely possible I missed something so feel free to ask any questions or go digging if you're unsure of a specific `get_post_meta()` call :)

**Comment by haszari** [comment]
Opened a PR with the fix: #4228

Still working on testing steps and impact, feel free to jump in with feedback any time! FYI @mattallan

**Comment by haszari** [comment]
Thanks for explaining @mattallan ! Though I am still a little confused. 

> Is the switch ID a switch order or a subscription ID?

What's a "subscription"? I thought subscription objects extend orders, i.e. all "subscriptions" are orders? How do we reliably determine when it's ok to use `get_post_meta` vs. CRUD APIs?

Looks like I'll need to revise my PR – I've changed all three, will that break?

**Comment by mattallan** [comment]
>I thought subscription objects extend orders, i.e. all "subscriptions" are orders?

That's correct :)

> How do we reliably determine when it's ok to use get_post_meta vs. CRUD APIs?
> I've changed all three, will that break?

Because Subscriptions extend Orders which implements WC Data structures, we can use CRUD APIs on both Orders and Subscriptions so no, nothing will break. Because Subscriptions are staying in the WP Posts table it's still considered "okay" to use `get_post_meta()` but it's preferred we use CRUD APIs in all cases for both orders and subscriptions.

> Opened a PR with the fix

Awesome! I'll take a look! 🎉

**Comment by haszari** [comment]
> Because Subscriptions are staying in the WP Posts table it's still considered "okay" to use get_post_meta() but it's preferred we use CRUD APIs in all cases for both orders and subscriptions.

Thanks for explaining @mattallan ! So to confirm my understanding – although orders proper are moving to a custom table, it's in our control where subscriptions are stored – and we're going to keep them as regular posts for now? Or to put it another way, the runtime data structure is `WC_Subscription > inherits WC_Order`, but the data may be persisted in a different table to regular orders? I think I read this on one of James' posts but am still getting my head around it 😁
