### ISSUE TITLE
StripeLink: Automatically start StripeLink if the email is set

### ISSUE THREAD

**Issue by elazzabi** [Automattic/woocommerce-payments#4153]
If the user is logged in/registered, during the checkout, their email is already in the form. However, you need to manually remove/add a character to trigger StripeLink. This is because StripeLink is configured to fire on `keyup` DOM events.

Fix: When loading the page, we need to check if the email field is filled and trigger StripeLink

**Comment by kalessil** [comment]
When I have the toggle off initially:
- if email is provided, when toggling on I'd expect the modal to appear

**Comment by kalessil** [comment]
@mordeth : this probably can be closed now.

**Comment by mordeth** [comment]
We have implemented a button to allow triggering StripeLink. Closing the issue.
