### ISSUE TITLE
Compatibility with WordPress 6.0

### ISSUE THREAD

**Issue by RadoslavGeorgiev** [Automattic/woocommerce-payments#4159]
### Description

WordPress 6.0 [should be released on May 24th 2022](https://make.wordpress.org/core/2022/02/16/wordpress-6-0-planning-roundup/) with [beta 2 available](https://wordpress.org/download/releases/#betas) since yesterday.

We should manually test compatibility between WCPay and the new WordPress version. We should also test the default theme, which is still TwentyTwentytTwo. Good news is that the theme [has not received major updates](https://core.trac.wordpress.org/browser/trunk/src/wp-content/themes/twentytwentytwo) since 5.9, so I'm not expecting any braking changes.

**Comment by htdat** [comment]
> We should manually test compatibility between WCPay and the new WordPress version.

My 2 cents here. We may want to set up sites having this new WP version, and ask GlobalStep to test them too?

**Comment by naman03malhotra** [comment]
>We may want to set up sites having this new WP version, and ask GlobalStep to test them too?

That is a good idea @htdat, this will also act as a 2nd set of eyes in case we missed something.

**Comment by RadoslavGeorgiev** [comment]
Manual tests did not show any issues, everything worked flawlessly 🥳 

I'll keep the issue open as a reminder for GS testing though.

**Comment by RadoslavGeorgiev** [comment]
@zmaglica this is the required plugin: https://wordpress.org/plugins/wordpress-beta-tester/. It can be also installed through the `Include WordPress Beta Tester` checkbox on JN.

**Comment by haszari** [comment]
I just noticed we don't have [`Tested up to` metadata](https://developer.wordpress.org/plugins/wordpress-org/how-your-readme-txt-works/#readme-header-information) in [`woocommerce-payments.php`](https://github.com/Automattic/woocommerce-payments/blob/a10a619f263cc86771e48326a6b773245822aa9e/woocommerce-payments.php#L1-L18):

https://github.com/Automattic/woocommerce-payments/blob/a10a619f263cc86771e48326a6b773245822aa9e/woocommerce-payments.php#L1-L18

Should we add this, or is there an explicit reason why we leave it out? If we do want it maybe we can add `Tested up to: 6.0` to close this issue in WCPay 4.2.0.

**Comment by zmaglica** [comment]
We can add those into release after GlobalStep team finished with the testing. I think that 4.2.0 version is compatible with the WordPress 6.0.

**Comment by deepakpathania** [comment]
@zmaglica to open an issue for the twenty twenty-two theme.

**Comment by naman03malhotra** [comment]
Closing as https://github.com/Automattic/woocommerce-subscriptions-core/issues/181 is under @Automattic/helix's radar.
