### ISSUE TITLE
Incompatibility with Gifting for WooCommerce Subscriptions

### ISSUE THREAD

**Issue by ismaeldcom** [Automattic/woocommerce-payments#4182]
### Describe the bug
Using the latest version of WC Pay with WooCommerce Subscriptions + Gifting for WooCommerce Subscriptions hides the recipient-specific email templates created by Gifting for WooCommerce Subscriptions. This leads to the emails being undelivered.

### To Reproduce
Use the latest versions of:

- WooCommerce Subscriptions (Version 4.1.0)
- WooCommerce Subscriptions Gifting (Version 2.2.0)
- WooCommerce Payments (Version 4.0.1)

Go to **WooCommerce > Settings > Emails** and you won’t see the following [email templates created by WooCommerce Subscriptions Gifting](https://woocommerce.com/document/subscriptions-gifting/#section-12).

You will only be able to see them if you deactivate WooCommerce Payments or use an old version of WooCommerce Payments. I tested with WooCommerce Payments Version 3.2.0 and the email templates were appearing fine but not with its latest version.

### Actual behavior
Normally this should not happen and email templates should stay regardless of the activation status of WooCommerce Payments plugin.

### Screenshots
![image](https://user-images.githubusercontent.com/7670276/164686809-b44bc060-6c0f-4f9d-812e-4b720418faae.png)

### Additional context
Ticket: 4966623-zd-woothemes

@AbhinavSakalle  have tested this on two sites and on the customer's staging site (creds in the ticket) and I was able to reproduce it.

**Comment by cesarcosta99** [comment]
@zmaglica I saw you assigned yourself to this task, and wanted to note that this has been addressed in #4198 and released in #4201. I'm going to close it, feel free to re-open if any follow-up is required 👍

**Comment by zmaglica** [comment]
Thank you for letting me know @cesarcosta99
