### ISSUE TITLE
Clarify Phone Requirements for Card Reader Settings page 

### ISSUE THREAD

**Issue by darcie** [Automattic/woocommerce-payments#4189]
### Describe the bug
Entering a phone number into Card Reader Settings meant for IPP does update the `business_profile.support_phone` for the merchant's account as mentioned in #3981. The box requires a country code to be added to Stripe correctly. 

### To Reproduce

1. Go to Payments > Card Readers > Receipt details 
2. Enter a ten digit US based phone number 
3. View the linked Stripe account and see that only 8 digits appear in support details 
4. Update the phone to use +1 and the same ten digits
5. View the Stripe account and see the phone number correctly formatted. 

### Actual behavior
Without adding +1, the phone is incorrectly formatted and not enough digits are passed to Stripe. No helper text exists to clarify that a country code is needed, and merchants may not know to include this. 

### Screenshots

**Settings without +1** 

<img width="629" alt="settings_without_country" src="https://user-images.githubusercontent.com/318285/164948766-9713358d-27bb-4f0c-a61e-c29e09fb432e.png">

<img width="450" alt="support_phone_without" src="https://user-images.githubusercontent.com/318285/164948774-be0cdbe3-9f6c-4ac1-9a9a-4c2475e83d80.png">

**Settings when using +1** 

<img width="637" alt="settings_with_country" src="https://user-images.githubusercontent.com/318285/164948781-0e9f2fbe-1e4a-4686-aeec-7bc2ee7a0c77.png">

<img width="449" alt="support_phone_with" src="https://user-images.githubusercontent.com/318285/164948782-d084e978-c9ed-4973-ac41-4425db9e3bac.png">

### Expected behavior
I expected a ten digit phone to update the Stripe support number, or for some alert or error message to display the phone number requirements. 

### Additional context
Testing with a 555 area code is not possible, Stripe seems to reject these and will not update support details. 
May be resolved by adding country drop-down suggested in #3986.

**Comment by kalessil** [comment]
We have https://github.com/Automattic/woocommerce-payments/issues/3986 on the radar, which should address this issue once we tackle it.

I'll close this one as it is pretty much duplicating https://github.com/Automattic/woocommerce-payments/issues/3986.
