### ISSUE TITLE
Running tests consecutively results in failed tests

### ISSUE THREAD

**Issue by zmaglica** [Automattic/woocommerce-payments#4192]
### Describe the bug

When you run tests using `npm run test:php` on environment where you already executed tests will result in failed test because some tables are missing

### To Reproduce

1. To have a clean environment, execute `npm run down`
2. Bring environment up by running `npm run up`
3. Execute PHP tests and confirm that they all pass (they should at this point) by running `npm run test:php`
4. Run `npm run test:php` again to rerun tests again. This is normal flow when you are coding and checking or fixing broken tests
5. You should receive an error that will look like this: `WordPress database error Table 'wcpay_tests.wptests_wc_admin_notes'`

### Actual behavior
Tests fail to pass if you run them consecutively

### Screenshots
N/A

### Expected behavior
Test should pass if you run them consecutively
### Desktop (please complete the following information):

* OS: All
* Browser All
* Version All

### Additional context
One of our test(s) deletes the table core WordPress table that was added during the installation of WordPress Test environment.

**Comment by RadoslavGeorgiev** [comment]
@zmaglica I could not reproduce this. Are you sure you have not been using a corrupted version of WCA/WC core?

**Comment by htdat** [comment]
@zmaglica can you have a look at this issue again?

**Comment by zmaglica** [comment]
It is not relevant anymore because I couldn't reproduce it. Maybe I had corrupted version of develop branch. Feel free to close it if needed.
