### ISSUE TITLE
Improve error messages for Jetpack authentication errors and HTTP request errors

### ISSUE THREAD

**Issue by jbordonado** [Automattic/woocommerce-payments#4210]
This is the first iteration following the spike #4068

### Description
We want to expose better error messages to the merchants (i.e. more descriptive, so they have an idea of what is going wrong and what they might be able to do to fix it) in case of HTTP request errors or Jetpack auth errors

Therefore, we need to be able to differentiate between a Jetpack authentication issue and other HTTP request errors.

### Acceptance criteria
- In case of Jetpack auth issue, we reused the existing error message and also mention that there is most likely an issue with the Jetpack connection (a link to the [Jetpack doc](https://jetpack.com/support/getting-started-with-jetpack/fixing-jetpack-connection-issues/) is included)
- In case of another type of HTTP request issue, we reused the existing error message and also suggest trying again

### Dev notes

Jetpack auth error can happen either on the client (https://github.com/Automattic/woocommerce-payments/blob/develop/includes/wc-payment-api/class-wc-payments-http.php#L108) or on the server (from the permission callback methods).

On the server, it's pretty straightforward, we know that an error returned to the client with code=wcpay_authorization_failure means that there was an issue with Jetpack auth.
On the client, it's more complicated. When we call Automattic\Jetpack\Connection\Client::remote_request(), there could be a number of reasons we get a WP_Error. For instance, we could get a WP_Error with code=missing_token or code=malformed_token that are both related to an auth issue, but there could also be other errors (like invalid_body, that is not related to an auth issue). 

Example of how to reproduce a Jetpack auth error:
- Make sure you are not using your local server (Jetpack auth is stubbed locally and always returns true): untick "Enable API request redirection" in WCPay Dev
- Install the [Jetpack Debug tools](https://github.com/Automattic/jetpack-debug-helper) plugin
- Enable "Broken token Utilities"
- Visit Jetpack Debug > Broken Token tab
- First, click on "Store these options" to save your valid local token options before you mess with the connection
- Then try to set an invalid blog or user token
- Visit Payments > Overview
- You should not see the Deposits section at the top (you should see the failed request in the Network tab from the Developer's tool, with code=wcpay_authorization_failure).
- You can go back to Jetpack Debug > Broken Token tab and click on "Restore from stored options" to fix your Jetpack connection

Example of how to reproduce another HTTP request error:
- In WCPay Dev, make sure "Proxy WPCOM requests" is ticked and update the value with something wrong: `socks5://host.docker.internal:8081` instead of `socks5://host.docker.internal:8080` for instance
- Visit Payments > Overview
- You should not see the Deposits section at the top (you should see the failed request in the Network tab from the Developer's tool, with code= wcpay_http_request_failed).

**Comment by vbelolapotkov** [comment]
@anu-rock routing this one to you for further prioritization since account lifecycle is the main owner of Jetpack connection.

**Comment by treibalen** [comment]
JFYI, this came up in 8271003-zen:

> Perhaps the software engineers should give a helpful error message 😊
