### ISSUE TITLE
Disable xdebug when running e2e tests

### ISSUE THREAD

**Issue by shendy-a8c** [Automattic/woocommerce-payments#4216]
Explore if disabling xdebug would speed up e2e tests.

I am thinking to disable xdebug for:
- [e2e env](https://github.com/Automattic/woocommerce-payments/blob/develop/tests/e2e/env/wordpress-xdebug/Dockerfile#L2-L7), and
- WCPay server. Maybe instead of changing it on WCPay server's repo, make the change in `tests/e2e/env/setup.sh`.

Then, time if there is time saved from those changes when e2e tests are run on GitHub Actions.

**Comment by achyuthajoy** [comment]
@jbordonado xDebug is already disabled on both the client and server. The change is specific only to GitHub actions and local enc won't be affected.

And yes, this issue can be closed.
