### ISSUE TITLE
[Observability] Explore integrating Sentry to the plugin for front-end errors

### ISSUE THREAD

**Issue by deepakpathania** [Automattic/woocommerce-payments#4223]
### Description

We explored integrating Sentry to the plugin while checking feasibility of integration with the server as a part of this issue: 565-gh-automattic/woocommerce-payments-server , opening this issue to formally write a RFC exploring this and then integrating the same if agreed upon.

### Acceptance criteria

* RFC with the integration proposal
* PR with the integration details

### Dev notes

There is a [draft PR](https://github.com/Automattic/woocommerce-payments/pull/4191) already in place with the basic integration, build on top of that if needed.

### Additional context

There is a P2 post (paJDYF-3NY-p2) with the privacy review request, refer to the comments for things to add in the RFC.

**Comment by jessy-p** [comment]
Closing as no longer relevant, as we will be shortly refactoring plugin extensively. Please create a new issue if this is still required.
