### ISSUE TITLE
Bump PHP version to 7.4 in compatibility check

### ISSUE THREAD

**Issue by shendy-a8c** [Automattic/woocommerce-payments#4230]
Bump PHP version to 7.4 in compatibility check per suggested by @achyuthajoy [here](https://github.com/Automattic/woocommerce-payments/pull/4229#pullrequestreview-963158748).

**Comment by vbelolapotkov** [comment]
No need to do so because [the latest version of WC still supports PHP 7.2](https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce/woocommerce.php#L12)
