### ISSUE TITLE
[Spike] In-Person Payments: intent description generation is not correct.

### ISSUE THREAD

**Issue by kalessil** [Automattic/woocommerce-payments#4234]
### Describe the bug

`\WC_Payments_API_Client::get_intent_description` always generates `Online payment` as prefix, what expected to be `In-person Payments` in the context of IPP.

### Developers note

- In `\WC_Payment_Gateway_WCPay::capture_charge`, calls `prepare_intention_for_capture` and `capture_intention` raising question if those 2 methods could be merged into one.
- `\WC_Payments_API_Client::create_intention` (or its' parent flows) shall inject the descriptor
- `\WC_Payments_API_Client::capture_intention` (or its' parent flows) shall inject the descriptor

### Additional context

- pdfdoF-Ks-p2

**Comment by kalessil** [comment]
Marking as blocked, will resume after we have a P2 in place with the decision on how to proceed, aligned with mobile teams.

**Comment by kalessil** [comment]
Marking as blocked, will resume after we have a P2 in place with the decision on how to proceed, aligned with mobile teams.

**Comment by kalessil** [comment]
@mordeth: IIRC, we could close this issue. Correct?

**Comment by RadoslavGeorgiev** [comment]
For Gamma Sprint 13, we should just go ahead with the spike, and see how much effort is required.

**Comment by deepakpathania** [comment]
Asked mobile team [here](https://peacockp2.wordpress.com/2022/05/05/order-description-in-stripe-dashboard-online-payment-for-order-vs-in-person-payment-for-order/#comment-7150).

**Comment by deepakpathania** [comment]
Closing based on [this comment](https://peacockp2.wordpress.com/2022/05/05/order-description-in-stripe-dashboard-online-payment-for-order-vs-in-person-payment-for-order/#comment-7151).
