### ISSUE TITLE
Error ` "message": "Invalid email address: ` for when email address field contains space

### ISSUE THREAD

**Issue by namiokuzono** [Automattic/woocommerce-payments#4239]
### Describe the bug

Error ` "message": "Invalid email address: ` for when the email address field contains space

### To Reproduce

- Place an order when space is contained in the email field

### Actual behavior

Error ` "message": "Invalid email address: ` for when email address field contains space
This results in payments not being taken, which then results in WooCommerce orders status stuck in ` Pending Payments `

### Screenshots

![https://d.pr/i/VJ91zZ](https://d.pr/i/VJ91zZ+)
Image link: https://d.pr/i/VJ91zZ

### Additional context

p1651811763955499/1651805909.385329-slack-C7U3Y3VMY

**Comment by namiokuzono** [comment]
5193851-zd-woothemes

**Comment by martynmjones** [comment]
Another user appears to be running into this: 5209418-zen

They conflict tested and realised that it was only an issue while Elementor and Elementor Pro are active. The store from the previous report also has both of them installed so that may be where the conflict is coming from.

**Comment by helenaartmann** [comment]
Played into the ticket above (5209418-zen) and they are asking if there is a workaround in this case. Please let me (or the user!) know if you know any. Thanks so much!

**Comment by htdat** [comment]
@helenaartmann and @martynmjones Regarding 5209418-zen mentioned in two last comments https://github.com/Automattic/woocommerce-payments/issues/4239#issuecomment-1126048607 and https://github.com/Automattic/woocommerce-payments/issues/4239#issuecomment-1126465099

It seems that's a conflict with one of their plugins and the merchant found a way to resolve the issue. In summary, it does not an issue with WCPay.
