### ISSUE TITLE
Update our out-of-date usages for package jetpack-connection 

### ISSUE THREAD

**Issue by htdat** [Automattic/woocommerce-payments#4256]
### Description

From p9dueE-55t-p2#comment-7911 by @leogermani 

https://github.com/Automattic/woocommerce-payments/blob/95c6c95f73bd68a0bece0baa14c2a81549856496/includes/wc-payment-api/class-wc-payments-http.php#L131

`is_plugin_enabled()` is deprecated and not needed. In fact, `is_active()` has also been deprecated a while ago. Instead you should use the following methods to verify if the site is connected:

- `is_connected()` – meaning it is connected at a site level (aka has a blog token) and
- `has_connected_owner()` – meaning at least one admin has authorized their WPCOM account.
Since WCPayments require a user connection, you could use both. (in practice, is_active has the same effect as has_connected_owner.

https://github.com/Automattic/woocommerce-payments/blob/95c6c95f73bd68a0bece0baa14c2a81549856496/includes/wc-payment-api/class-wc-payments-http.php#L181

You don’t need to call `enable_plugin()` here, this is deprecated. You can just remove it.

### Acceptance criteria

* Solve the issue above.
* Ideally to merge changes right after a major release so that this change can go thorough all testing cycles by GlobalStep for the next release.

**Comment by chrisbliss18** [comment]
I've been doing some refactoring with @sergeymitr. We have removing the call to `enable_plugin()` on our list and found that it's mentioned in this issue as well. Please let us know if we can help with removing the call. Thanks!

**Comment by htdat** [comment]
> We have removing the call to enable_plugin() on our list. 

Thanks @chrisbliss18. Can you clarify which version of Jetpack Connection package going to remove this function?

**Comment by chrisbliss18** [comment]
Hi @htdat. We don't plan on removing the function just yet. Our current goal is to get all calls removed. Once all the calls are removed, we can make a plan for when to remove the function at some point in the future.

**Comment by vbelolapotkov** [comment]
@anu-rock routing this one to you, since account lifecycle is the primary owner of Jetpack connection.

**Comment by anu-rock** [comment]
This looks like a quick win. Assigning it medium priority to pick it up in an upcoming sprint. That will help @chrisbliss18 and team to remove the deprecated functions in case they are blocked by us.
