### ISSUE TITLE
Tax rate name is not sanitized when saving to DB part of an order

### ISSUE THREAD

**Issue by elazzabi** [Automattic/woocommerce-payments#4259]
First reported by @aheckler 

### Describe the bug

Tax rate name (example `Tax for climate`) isn't sanitized when saved part of a sale/order.

### To Reproduce

1. Turn taxes on for a WC store
2. Add a new tax with a name containing spaces. For example ('Tax for climate') 
3. Apply the tax to a WC Pay subscriptions product (or leave it on all store products)
4. Purchase the product with the tax applied to it
5. Verify the `wp_options` table. There should be a new option called `_wcpay_product_id_test_tax for climate` (contains spaces)

### Actual behavior

The tax name is saved as it is to the options table

### Expected behavior

Tax name should be "sanitized" or at least spaces should be replaced with `_`.

### Desktop (please complete the following information):

* OS: macOS
* Browser Chrome
* Version 100.x

**Comment by nagpai** [comment]
I tried replicating this issue on my local test site, and it did not seem to generate the option in the `wp_options` table. 

1. I added a tax for US from `Settings > Tax > Standard rates` 
2. Completed a product purchase with the tax applied - `Tax for test` in my case.
3. Searched for the option in `wp_options` table via PhpMyAdmin search and was unable to find it 
![image](https://user-images.githubusercontent.com/4162931/180469505-83737e72-c86b-4009-866f-58302be1f142.png)

@elazzabi , Can you tell me if I am doing the steps correctly, or if I need to do something more additionally to replicate the error? Thanks.

**Comment by aheckler** [comment]
@nagpai The product has to be a WC Pay subscription product.

**Comment by nagpai** [comment]
Thanks, @aheckler . I will have this tested further on Monday 👍
