### ISSUE TITLE
Optimize E2E setup script to allow setting up a server instance on GH actions.

### ISSUE THREAD

**Issue by achyuthajoy** [Automattic/woocommerce-payments#4260]
### Describe the bug

The ability to initialize a WCPay server instance on GH actions was removed previously while optimizing the E2E setup for improving performance & security. Related PR - https://github.com/Automattic/woocommerce-payments/pull/3383

### Actual behavior
With the current setup script, a server instance cannot be created when run against GH actions.

### Expected behavior
It should be possible to create a server instance if required on GH Actions.

**Comment by htdat** [comment]
Closing this issue as the PR #4271 was merged. 

@achyuthajoy - feel free to re-open it if needed.
