### ISSUE TITLE
Update type styles to latest design standards

### ISSUE THREAD

**Issue by dechov** [Automattic/woocommerce-payments#427]
See @LevinMedia's note on type styles in https://github.com/Automattic/woocommerce-payments/pull/418#issuecomment-584939283, in the context of the dispute details screen but applicable in a general way across this app as well as upstream components:

> If you could, please align them to the type scale described in the Figma file.
> 
> The card headers use `Title S` with `$studio-gray-80` color
> 
> The card bodies use `Body` with `$studio-gray-60` as the color
> 
> The bold text that separates paragraphs in the second card are also `body` but bold, and using `$studio-gray-80` as the color
> 
> per our slack chat - hopefully type scale linked above [will soon be included with gutenberg](https://github.com/WordPress/gutenberg/pull/18244), until that time we can hard code it.
> 
> If too much time passes though, we'll probably want to include the type scale as part of @woocommerce/components - as we're using it elsewhere in new designs across WooCommerce such as onboarding and other new screens in wc-admin.

**Comment by LevinMedia** [comment]
No longer relevant - closing
