### ISSUE TITLE
Multi-Currency Analytics: Only apply join clauses on Orders queries

### ISSUE THREAD

**Issue by dmallory42** [Automattic/woocommerce-payments#4280]
### Description

When Multi-Currency is enabled, queries made to the Analytics section of WC Admin are modified to join in order to fetch the original currency of the order and the exchange rate. This is in order to display the original currency an order was placed in. However, we can only do this on the `Orders` analytics page, meaning we are doing unnecessary joins on the other analytics pages.

We can make this more efficient by checking to see which context we're in before making the joins.

### Acceptance criteria

* We should only add the extra joins in MC Analytics if in the context of the Orders page.

### Additional Context

p1653313090124909-slack-C01B8KNUYSW

**Comment by dmallory42** [comment]
This might be a little more complex than I initially thought. I made a quick spike into it and realised that we make [replacements](https://github.com/Automattic/woocommerce-payments/blob/7f58d28449bf987e884a180e71e47d63abfffcd7/includes/multi-currency/Analytics.php#L349) in the SQL using the joins in the case of calculating the `discount_amount`, `product_net_revenue`, and `product_gross_revenue` -  this is because these values are looked up using the *original* order values (stored in `wc_orders`) - rather than the stats tables.

The issue with this is that the original order values would be stored in the currency they were purchased in. For this reason, it is necessary for us to make this conversion with the SQL query.

It may be possible to optimise and work out which cases we need to apply these transformations, but it wouldn't be possible to optimise as much as I initially thought without modifying how analytics works in WC Admin.

**Comment by joshbetz** [comment]
Some questions from Slack:

How do we know if a store supports multiple currencies? Is that opt-in or enabled automatically?

Can we detect when a store has only ever received orders from a single currency and disable some of this?

**Comment by dmallory42** [comment]
> How do we know if a store supports multiple currencies? Is that opt-in or enabled automatically?

Enabled automatically currently, but it may be worth exploring whether it's safe/possible to disable this functionality in the case where a user has not onboarded with WCPay yet.

> Can we detect when a store has only ever received orders from a single currency and disable some of this?

Good question! Again, I think that's something worth exploring.

**Comment by joshbetz** [comment]
I think we can close this now?
