### ISSUE TITLE
Error changing subscription payment method via UPE more than once in a session

### ISSUE THREAD

**Issue by Jinksi** [Automattic/woocommerce-payments#4308]
### Describe the bug

An error occurs when attempting to change the payment method of a subscription more than once in a session. This occurs when UPE is enabled and affects both WCPay Subscriptions and the integration with WooCommerce Subscriptions.

This is likely due to UPE *setup intent* remaining cached from the previous payment request (added in #3782).

### To Reproduce

1. Ensure UPE is enabled ([using WCPay dev tools](https://github.com/Automattic/woocommerce-payments-dev-tools)).
2. Create a simple monthly subscription product, either using WCPay Subscriptions or the [WooCommerce Subscriptions](https://github.com/woocommerce/woocommerce-subscriptions) extension.
3. Purchase the subscription using a standard CC: `4242424242424242`.
4. Navigate to **My Account -> Subscriptions -> Change Payment**.
5. Change the subscription payment method to a new card (you can use the same number with a different expiry date) or use a card number below:
	* [SCA card](https://stripe.com/docs/development/quickstart#manual-tests) `4000002760003184`
	* [3DS2 card](https://stripe.com/docs/payments/3d-secure#three-ds-cards)  `4000000000003220`
1. Change the payment again to a new card as per step 4.
1. You will see the error message “a processing error occurred”.
1. Navigating away and attempting to change payment via step 3 will result in the same error.
1. Logging out and back in (ending the session) will allow the new card to be processed.

### Actual behavior

An error notice appears (“a processing error occurred”) and the payment method change is not processed.

### Screenshots

![785DDCF4-D750-4DD9-BCE0-F237848D2AFE](https://user-images.githubusercontent.com/3147296/171351694-1925143f-f799-4f0e-b031-35abc1927432.png)

### Expected behavior

The error does not occur and the payment method change is processed.

### Desktop (please complete the following information):

* OS: macOS 12.4
* Browser: Firefox Developer 
* Version: 101.0b9

### Additional context

Tested with a fresh JN site after completing WC 6.5.1 and WCPay 4.1.0 onboarding in test mode with **UPE enabled:**

<details>
<summary>Stripe setup intent error response</summary>

`https://api.stripe.com/v1/setup_intents/seti_xxxxxxxxxxxxx/confirm`

```json
{
	"error": {
		"code": "setup_intent_unexpected_state",
		"doc_url": "https://stripe.com/docs/error-codes/setup-intent-unexpected-state",
		"message": "You cannot update this SetupIntent because it has already succeeded.",
		"setup_intent": {
			"id": "seti_xxxxxxxxxxxxx",
			"object": "setup_intent",
			"cancellation_reason": null,
			"client_secret": "seti_xxxxxxxxxxxxxxxx",
			"created": 1653536655,
			"description": null,
			"last_setup_error": null,
			"livemode": false,
			"next_action": null,
			"payment_method": "pm_xxxxxxxxxxxxxxx",
			"payment_method_types": [
				"card"
			],
			"status": "succeeded",
			"usage": "off_session"
		},
		"type": "invalid_request_error"
	}
}
```

</details>

**Potential solution**

Remove the setup_intent from session when subscription payment method is updated – add an additional action `woocommerce_subscription_payment_method_updated` action, similar to:
https://github.com/Automattic/woocommerce-payments/blob/c0bb63a34f0014f223b875d7b6ae9394f614d959/includes/payment-methods/class-upe-payment-gateway.php#L118

**Comment by haszari** [comment]
Marking as high priority. This is relatively low impact; it's likely uncommon for shoppers to update payment method multiple times in quick succession (and this is limited to stores using UPE).

However, it reveals a flaw in our UPE / setup intent cache logic that we should tidy up IMO. 

@Jinksi what do you need to get your PR over the line? Should we tag in UPE expertise for a review or to assist?

**Comment by Jinksi** [comment]
@haszari I've just requested a review for the PR 🚀 

I was only holding back because I had [some problems](https://github.com/Automattic/woocommerce-payments/pull/4311#issuecomment-1145518411) when adding e2e tests for UPE change-payment flows. However, there are no existing e2e tests for UPE change-payment flows, therefore I don't think this should block the bugfix.
