### ISSUE TITLE
Fatal error when deactivating WC Payments on unsupported WC version

### ISSUE THREAD

**Issue by vbelolapotkov** [Automattic/woocommerce-payments#4331]
### Describe the bug

When WC Payments installed on store with WC version below min required, the fatal error triggered when trying to deactivate it.

```
Fatal error: Uncaught Error: Call to a member function delete_notes() on null in /srv/users/user3db33726/apps/user3db33726/public/wp-content/plugins/woocommerce-payments/includes/class-wc-payments.php:911 Stack trace: #0 /srv/users/user3db33726/apps/user3db33726/public/wp-content/plugins/woocommerce-payments/woocommerce-payments.php(54): WC_Payments::remove_woo_admin_notes() #1 /srv/users/user3db33726/apps/user3db33726/public/wp-includes/class-wp-hook.php(307): wcpay_deactivated(false) #2 /srv/users/user3db33726/apps/user3db33726/public/wp-includes/class-wp-hook.php(331): WP_Hook->apply_filters('', Array) #3 /srv/users/user3db33726/apps/user3db33726/public/wp-includes/plugin.php(476): WP_Hook->do_action(Array) #4 /srv/users/user3db33726/apps/user3db33726/public/wp-admin/includes/plugin.php(814): do_action('deactivate_wooc...', false) #5 /srv/users/user3db33726/apps/user3db33726/public/wp-admin/plugins.php(209): deactivate_plugins('woocommerce-pay...', false, false) #6 {main} thrown in /srv/users/user3db33726/apps/user3db33726/public/wp-content/plugins/woocommerce-payments/includes/class-wc-payments.php on line 911
There has been a critical error on this website. Please check your site admin email inbox for instructions.
```

### To Reproduce

1. Launch new site with WC version below min required (E.g. 5.5.4)
2. Install latest WC Payments version (E.g. 4.2.1) and activate it. Warning notice will be displayed about unsupported WC version.
3. Deactivate WC Payments.
4. See fatal error

### Actual behavior

Fatal is triggered.

### Expected behavior

Plugin deactivated.

### Desktop (please complete the following information):

* OS: OSX
* Browser Chrome

### Additional context

Looks like the bug is within logic for clearing plugin related inbox notes.

**Comment by vbelolapotkov** [comment]
FYI, there is a workaround available - install a previous version of the plugin (compatible with the current version of WC), and deactivate after that.

**Comment by vbelolapotkov** [comment]
There is no error in case the plugin setup was completed. So only old WC stores with freshly installed WC Payments (not onboarded) are affected.

**Comment by zmaglica** [comment]
@vbelolapotkov I think we handled this error in one of the patches where the same issue appeared. I will close this issue. Feel free to reopen in case you think it needs more attention.
