### ISSUE TITLE
Not clear how to translate strings from subscriptions-core engine / code base; e.g. `Sign up now` button text can't be translated

### ISSUE THREAD

**Issue by stuartduff** [Automattic/woocommerce-payments#4334]
### Describe the bug

When using the Subscriptions features of WooCommerce Payments it does not seem possible to translate the **Sign up now** button text which replaces **Place order** on the checkout page.

### To Reproduce

1. Install a plugin like Loco Translate.
2. Load or create a WooCommerce payments language file.
3. Search for the text **Sign up now**
4. No text referencing **Sign up now** is returned.

### Actual behaviour

When searching within language files generated for WooCommerce Payment no **Sign up now** text is found or translatable.

### Screenshots

**Checkout page with Subscription present**
![Screen Shot on 2022-06-08 at 16:49:08](https://user-images.githubusercontent.com/1190565/172661097-05665f2f-b086-41b1-8db1-34a38f4ed47b.png)

**Searching for Sign up now in a generated language file**
![Screen Shot on 2022-06-08 at 16:51:03](https://user-images.githubusercontent.com/1190565/172661521-a57b27fd-820d-40c4-89a0-dc222f2324fb.png)

### Expected behaviour

All of the customer-facing text within the plugin's subscription functionality should be fully translatable and included within any generated language files.

### Additional context

WordPress v6.0
WooCommerce v6.5.1
WooCommerce Payments v4.2.1

### Affected tickets

5767167-zen

**Comment by stuartduff** [comment]
Hey @aheckler,

Thanks for the reply and insight. After some further investigation, It seems that the imported [woocommerce subscription core]([https://github.com/Automattic/woocommerce-subscriptions-core](https://github.com/Automattic/woocommerce-subscriptions-core/blob/2.1.0/languages/woocommerce-subscriptions.pot#L284)) plugin functionality of WooCommerce Payments uses a different text domain of **woocommerce-subscriptions** to that of the main plugin which is **woocommerce-payments**.

When you enable the subscriptions features of WooCommerce payments it's not loaded as a separate plugin to WooCommerce Payments. Ideally, all files within a WordPress plugin should therefore use the same text domain so all strings are available within the plugin's main .pot file.

**Comment by haszari** [comment]
Marking as high priority – we should document guidance for merchants on how to translate text from `woocommerce-subscriptions` (subscriptions core) code-base/module. And I agree, merchants should be able to translate all UI text!

**Comment by jessy-p** [comment]
>The issue, therefore, seems to be stemming from the text domain mismatch for components within WooCommerce Payments rather than being a direct issue with Loco Translate. As Loco Translate is the translation plugin we recommend and a lot of our customers use, it's possibly something we should investigate further.

I believe the next step on this issue, is for a developer to investigate. So moving this from Engineering Review Queue to Ready for Prioritisation for further investigation.

**Comment by naman03malhotra** [comment]
Based on our Sevierty principles, this issue doesn't seem a high priority as of yet but is definitely worth looking at sometime in the near future. Please comment if you think otherwise or would like to solve it sooner.

**Comment by jessy-p** [comment]
This issue impacts WC Payments Subscriptions so assigning to Quark (based on team responsibilities Pc2DNy-3z-p2) @diego373. Assigning as part of Gamma Triage process PcreKM-yM-p2.

**Comment by james-allan** [comment]
This can be closed. Merchants who are still using WCPay Subscriptions via subscription-core should move to use the Woo Subscriptions extension.
