### ISSUE TITLE
`Accept Dispute` button does not trigger the `Lost` status

### ISSUE THREAD

**Issue by thracefulton** [Automattic/woocommerce-payments#4339]
### Describe the bug

A merchant attempted to accept a dispute of a WCPay transaction (duplicate charge) to resolve it instantly. However, several attempts at using `Accept Dispute` from the Payments > Disputes dashboard did not result in any change in the Dispute status.

### To Reproduce
Unable to reproduce elsewhere. All of our tests of dispute behavior show an immediate change to `Lost` status.

My test dispute is [here](https://dashboard.stripe.com/test/connect/accounts/acct_1JjXvS2HVLKZ9q4M/payments/pi_3L8aBW2HVLKZ9q4M1fWc7ps1).  

### Actual behavior

The logs related to the disputed transaction show at least 3 separate instances where the admin used the `Accept Dispute` button, and for each, I can see `A request to update a dispute` followed by `A request to close a dispute completed`. All of those logged events are `200 OK` in the logs, with none showing failure or error. 

Unlike my testing, however, the subsequent `charge.dispute.closed` event never occurred.

### Screenshots

![screenshot](https://d.pr/i/52T6nH+) **Image Link:** https://d.pr/i/52T6nH

### Expected behavior

When a dispute is accepted, it should move to `Lost` instantly.

### Additional context

5188158-zen 

Previous discussion in Slack: p1654290330908809-slack-C7U3Y3VMY

**Comment by deepakpathania** [comment]
Shared my findings here: p1656660395513369/1654290330.908809-slack-C7U3Y3VMY

**Comment by deepakpathania** [comment]
Closing this issue based on the findings, someone will reach out to Stripe directly for knowing more about this particular case.
