### ISSUE TITLE
Add dispute task to the "Things to do next" on the WC → Home screen for disputes which need a response

### ISSUE THREAD

**Issue by james-allan** [Automattic/woocommerce-payments#4341]
### Description

To draw store managers' attention to the disputes which need of a response, we're going to add a new task item to the **`Things to do next`** task list. Clicking this task item will direct the user to the disputes screen. This was proposed and agreed upon in this P2 proposal (pdjTHR-19j-p2) and the subsequent accepted answer (pdjTHR-19j-p2#comment-1404). 

### Acceptance criteria

* Add the Disputed payment task item to the **WooCommerce `Things to do next`** task list.
* Clicking on this task, navigates the user to the Disputes screen (filtered by disputes needing a response). 

### Designs

![image](https://user-images.githubusercontent.com/8490476/173000713-09b279a4-f28c-44de-abfb-5ea22b7648d1.png)

### Dev notes

* [WooCommerce add task example](https://github.com/woocommerce/woocommerce/blob/71456382c47eadaa4bb98501bd3c7aafbfde1a52/plugins/woocommerce-admin/docs/examples/extensions/add-task/woocommerce-admin-add-task-example.php)
* There's a WIP branch which can be found here: https://github.com/Automattic/woocommerce-payments/compare/develop...add/4341-add-disputes-task-to-thing-to-do-next

**Comment by james-allan** [comment]
> To solve this issue, we will show the WooCommerce "Things to do next" task list on the WCPay Overview screen and add the (updated) disputes task list item to it.

That is my understanding, yes. Given the **"Things to do"** component on the **Payments → Overview** screen isn't currently live, we would need to understand what tasks have been built for it and either get approval for any notice that has been added to also be released as part of this or to disable all the current ones and only enable the dispute one for now.

**Comment by james-allan** [comment]
Actually, perhaps I've also misunderstood your explanation. 

> we will show the WooCommerce "Things to do next" task list on the WCPay Overview screen

Do you mean adding the whole WooCommerce (the one on Home) to the WCPay Overview screen? Because if so, I don't know of that is correct.

**Comment by Jinksi** [comment]
@james-allan Thanks for helping me understand this 😝 

> Do you mean adding the whole WooCommerce (the one on Home) to the WCPay Overview screen

That was my initial understanding, but now I'm looking at this part of the discussion of pdjTHR-19j-p2#comment-1404:

> we have `Things to do next` (that disappears when empty), on the WooCommerce Home
> ...
> So our Disputed payments notice could possibly be a part of `Things to do next` here. We could also bring it to the Payments Overview

I take this to mean that we will add a "Disputed payments notice" to WooCommerce Home `Things to do next` **and also** display this notice in the WCPay `Things to do` component on the **Payments → Overview** screen.

**Comment by james-allan** [comment]
> I take this to mean that we will add a "Disputed payments notice" to WooCommerce Home `Things to do next` and also display this notice in the WCPay `Things to do` component on the **Payments → Overview** screen.

yep that sounds right to me. 👍

**Comment by james-allan** [comment]
### 📢  Issue scope update

I've reduced the scope of this particular issue. Essentially, I have removed the requirement for this "Things to do" list being brought to the **Payments → Overview** screen. We will handle that issue in a separate task. 

I've included the items which have been removed from this issue's scope below: 

----

### Description

~The task list will also be brought to the **Payments > Overview** screen and the items listed there will be filtered to WC Payment related items.~

### Acceptance criteria
* ~Bring the **`Things to do next`** task list to the top of the **Payments > Overview** screen and display WC Payments related tasks.~

### Dev notes
* ~There is a WCPay Payments Overview "Things to do" task list that [is currently disabled in production](https://github.com/Automattic/woocommerce-payments/blob/444e8fb10755415a43fb18b7ca2426b1ee3543be/includes/class-wc-payments-features.php#L60-L63).~
* ~There is an [existing implementation of a disputes task list item](https://github.com/Automattic/woocommerce-payments/pull/2787) that appears in the **disabled** WCPay **"Things to do"** task list.~

**Comment by haszari** [comment]
@Jinksi  has a branch open with some initial work on this branch: https://github.com/Automattic/woocommerce-payments/compare/develop...add/4341-add-disputes-task-to-thing-to-do-next

(for whoever picks this up next)
