### ISSUE TITLE
Handle zero-decimal currency in account currency and deposit currency

### ISSUE THREAD

**Issue by shendy-a8c** [Automattic/woocommerce-payments#4351]
### Describe the bug

In WooCommerce Payments, [account currency](https://woocommerce.com/document/payments/currencies/#section-5) is the currency we charge fees in. [Deposit currency](https://woocommerce.com/document/payments/currencies/#section-3) is currency used for payouts to merchants.

We are allowing merchants to have multiple banks with different currencies, read https://woocommerce.com/document/payments/currencies/multiple-deposit-currencies/.

At the time of when this issue is created, there are several places in the code where we divide or multiple by 100 without checking if the currency in context is [zero-decimal currency](https://stripe.com/docs/currencies#zero-decimal) or not. That is fine though, for now, because we are at the moment only allowing merchants from countries with *non* zero-decimal currencies. The list of allowed countries and deposit currencies can be found [here](https://woocommerce.com/document/payments/currencies/multiple-deposit-currencies/).

I searched for `100` in our WCPay repos and listed them here: paJDYF-4eJ-p2#comment-12049.
When working on this issue, those line of codes might have moved or modified, so feel free to search through the code again.

### To Reproduce

1. Make sure you have local WCPay server running using `WCPay Dev`'s API credentials because the settings for that platform account have allowed merchant from countries with zero-decimal currency, for example, Japan.
2. You will need to add base fee for Japan. Example: 2122-gh-Automattic/woocommerce-payments-server.
3. Spin up a new store using WCPay Dev Tool to connect to your local WCPay server.
4. Change WooCommerce store's currency to JPY.
5. Onboard and choose Japan as country. You might need to use real Japanese address and input Japanese characters as your name to pass the onboarding process.
6. Create a product and make a purchase.
7. Notice some amounts are not displayed correctly.

For example, this is from the order note:
![Screen Shot 2022-06-15 at 22 39 23](https://user-images.githubusercontent.com/73803630/173870100-f08fe78c-babc-4163-b147-ab006465b95c.png)

I didn't test payout / deposit, dispute, or in-person payment but looking at the code, they should be affected as we're not checking if account / deposit currency is zero-decimal.

**Comment by jessy-p** [comment]
This issue impacts Multi-Currency, so assigning to Fractal (based on team responsibilities Pc2DNy-3z-p2) @bborman. Assigning as part of Gamma Triage process PcreKM-yM-p2.

Tagging as part of re-evaluating older issues in the backlog, please have a look and close if no longer relevant.

**Comment by vbelolapotkov** [comment]
I don't think this one is relevant. We already support Japan, and I don't think any issues were reported with it. @anu-rock could you please confirm and reopen if necessary.

**Comment by anu-rock** [comment]
@vbelolapotkov Indeed - support for zero decimal currency was refined as part of the expansion to Japan last year. I recall from my testing that the order note as in the screenshot above as well as the breakup on timeline view now support zero-decimal currencies like the Yen pretty well.
