### ISSUE TITLE
Improve logging/notifications for dev accounts running without dev mode

### ISSUE THREAD

**Issue by allendav** [Automattic/woocommerce-payments#437]
The following error is displayed:

> Could not fetch data for your account: "Error: wcpay_request_failure Platform request failure."

This can happen on sites that were set up with dev mode enabled and then are switched to non-dev mode and the user attempts to use them in "live" mode. Check and see if "Enable Test Mode" is unchecked. Checking it (enabling test mode) can avoid this error.

Sites set up to use dev mode cannot be used in non-dev mode unless 1) you stick to test mode or 2) you purge the site's entries in the account database table on WordPress.com.

Action for this issue: Better logging around this situation. Will probably require a server side change too.

**Comment by vbelolapotkov** [comment]
This one is not relevant anymore. After disabling dev mode on the store, WC Payments setup is suggested.
