### ISSUE TITLE
Error passing level3 data to stripe when product ID is larger than 12 digits

### ISSUE THREAD

**Issue by thilinah** [Automattic/woocommerce-payments#4411]
### Describe the bug
During the create payment intent WCPay uses the ID of the product as the `product_code` of each line item when passing level3 metadata to stripe. 

Since stripe supported max length for product code is 12 this call fails when product ID has more than 12 digits. This is affecting WCCOM since the new product IDs are having more than 12 digits.

Currently, there is a fix in place via [this PR](https://github.com/Automattic/woocommerce.com/issues/13690) for WCCOM.

Error response:

```
A POST request to https://public-api.wordpress.com/wpcom/v2/sites/201005257/wcpay/intentions failed with:

array (
  'error' => 
  array (
    'message' => 'Invalid string: 0123456789...3456789123; must be at most 12 characters',
    'param' => 'level3[line_items][0][product_code]',
    'type' => 'invalid_request_error',
  ),
)
```

### To Reproduce

1. Update the ID of any product to a number having more than 12 digits
e.g:
```
update wp_posts set ID = 1234567891234 where ID = <original ID>;
update wp_postmeta set post_id = 1234567891234 where post_id = <original ID>;
```
3. Purchase this product
4. The error in the description should be visible in order notes.

### Actual behavior
The payment is successful but shows an error related to level3 data in order notes

### Screenshots
![Screenshot 2022-07-05 at 14 31 19](https://user-images.githubusercontent.com/1531403/177328078-ff12a57a-b54a-4dfb-a347-75c504ad263c.png)

### Expected behavior
The level3 data error should be avoided by passing a product code with less than 12 characters.

**Comment by thracefulton** [comment]
I found an instance of this with 5540551-zen. In this case, the error was triggered when an order was created by admins with only a shipping cost, and no WooCommerce products added.

One workaround I was able to test and confirm is to enter the cost using `Add Fee` rather than `Add shipping` on the order.

**Comment by nagpai** [comment]
@thracefulton - Thanks for sharing the user report. However, the issue seems to be different from the one tracked here. The error you have is related to no product price being submitted, whereas the error here relates to a product ID longer than 12 digits resulting in an invalid product ID error. 

I suggest creating a separate GH issue with the steps to replicate. Thanks.

**Comment by csmcneill** [comment]
@thracefulton’s issue is reported in #4738

**Comment by nagpai** [comment]
I am no longer able to see the level 3 data in the order notes 
<img width="337" alt="image" src="https://user-images.githubusercontent.com/4162931/189596564-b13510c6-1aea-491d-b733-2cdc273b966d.png">

However, it does appear in the transaction logs within `Status > Logs`

<details>
<summary>Error log</summary>

```
2022-09-12T07:22:34+00:00 ERROR Invalid string: 1234567891...4567891234; must be at most 12 characters (invalid_request_error)
2022-09-12T07:22:34+00:00 ERROR Level3 data error: 
Error: Invalid string: 1234567891...4567891234; must be at most 12 characters
Level 3 data sent: 
Array
(
    [merchant_reference] => 1234567891236
    [customer_reference] => 1234567891236
    [shipping_amount] => 0
    [line_items] => Array
        (
            [0] => stdClass Object
                (
                    [product_code] => 1234567891234
                    [product_description] => Long Product ID
                    [unit_cost] => 1000
                    [quantity] => 1
                    [tax_amount] => 0
                    [discount_amount] => 0
                )

        )

    [shipping_address_zip] => 11001
    [shipping_from_zip] => 94110
)
```
</details>
