### ISSUE TITLE
Stuck at WooCommerce onboarding wizard

### ISSUE THREAD

**Issue by shendy-a8c** [Automattic/woocommerce-payments#4415]
### Describe the bug

I went through WooCommerce Payments onboarding via WooCommerce onboarding wizard and got stuck at the page that has the 'Finish Setup' button. Clicking that button didn't seem to do anything. I suspect it's because my payments and deposit status were not green yet. As soon as they became green, I could proceed with WooCommerce's onboarding process.

![Screen Shot 2022-05-18 at 19 34 23](https://user-images.githubusercontent.com/73803630/177482262-5238caac-d388-4bd8-a823-2306bae605e1.png)

I could reproduce this problem several times. Here's the screen recording: p1657085713999639/1657063407.341979-slack-CGGCLBN58

### To Reproduce

1. Create a clean site. I used JN.
2. Opening the site, I saw WooCommerce's onboarding.
3. During WC's onboarding, I chose to install WooCommerce Payments.
4. After filling out Stripe's form, I was redirected back to WC's onboarding process but as if WCPay's onboarding wasn't successful, I was at a page with the 'Finish Setup' button. Clicking that button kept redirecting me back to the same page and not progressing with the rest of WC's onboarding.
5. I opened the Payments menu on a new tab and noticed my payments and deposits status were red. As soon as they became green, I could progress to the next step of WC's onboarding.

### Actual behavior

Stuck for a while at WC's onboarding.

### Screenshots

p1657085713999639/1657063407.341979-slack-CGGCLBN58

### Expected behavior

Progress along the WC's onboarding because my account was already connected even though payments and deposits status were still red.

**Comment by shendy-a8c** [comment]
This might be considered as high priority since it is one of the main entry point during the onboarding but for now I just labeled it as `needs triage`.

**Comment by jessy-p** [comment]
Created two JN sites at the same time and onboarded in parallel, one from WC onboarding, one from Payments menu

**After WC onboarding**, I land on URL https://<hostname>/wp-admin/admin.php?page=wc-admin&task=payments&method=wcpay&wcpay-connection-success=1
<img width="724" alt="image" src="https://user-images.githubusercontent.com/32092402/178414515-03bd2421-e816-45ab-99e0-26c8a1c4d5d3.png">

**After Payments menu onboarding**, I land on URL https://<hostname>/wp-admin/admin.php?page=wc-admin&path=%2Fpayments%2Foverview&wcpay-connection-success=1
<img width="719" alt="image" src="https://user-images.githubusercontent.com/32092402/178414565-235283ac-83a8-4eae-b886-54628dcc7480.png">

I guess this does not affect live accounts, as we don't have any customer reports. I agree that this should be looked into with priority, just to make them consistent and avoid something breaking silently in a future release.

**Comment by daquinons** [comment]
We will be looking at this during the next sprint, thanks for the report and the triaging! @shendy-a8c @jessy-p

**Comment by shendy-a8c** [comment]
Worth mentioning here that I posted on Slack p1652877626205709-slack-CGGCLBN58 and got some feedbacks:
- Likely it's only happening on dev mode.
- If webhook works, ie local store is reachable from WCPay server (local or live, depending on how the local dev environment is set up), the status should clear once Stripe clears it.
- Dev can use [account data that immediately validates](https://stripe.com/docs/connect/testing#test-dobs), like 1901-01-01 for DOB and address_full_match.

**Comment by oaratovskyi** [comment]
Hi @shendy-a8c and @jessy-p ! Thanks for your findings! Immediately validating lifehack (DOB, address_full_match) is awesome. 
I wonder what can we do here to improve DevEx? The only thing that is on my mind is to try setting up the return URL for WC onboarding so it's the same as for WCPay. 
Like @jessy-p mentioned above - make it consistent. 

Does this sound good to you?

**Comment by shendy-a8c** [comment]
@oaratovskyi sorry for delayed response. I am not too worried about DevEx here. Reporting the issue was to confirm if the behavior per my screen recording is expected.

**Comment by daquinons** [comment]
Closing this issue as there are no additional improvements for DevEx at the moment. This issue happens only in dev mode and it's because Stripe validation of the introduced data in the KYC gets validated async, so nothing affects our merchants.

In case we decide to make it better for Dev mode (making more obvious that the state is expected) we will be able to reopen this!

Context: p1678087669638819-slack-C03KTTK2YMA
