### ISSUE TITLE
Flaky E2E test - wcpay/shopper/shopper-myaccount-save-card-and-checkout.spec.js

### ISSUE THREAD

**Issue by achyuthajoy** [Automattic/woocommerce-payments#4421]
### Describe the bug
The test `wcpay/shopper/shopper-myaccount-save-card-and-checkout.spec.js` fails randomly with multiple errors.

* `Timeout - Async callback was not invoked within the 100000ms timeout specified by jest.setTimeout.Timeout - Async callback was not invoked within the 100000ms timeout specified by jest.setTimeout.Error:`
* `waitForFunction failed: frame got detached.`
* `TimeoutError: Element label (text: "Visa ending in 3220 (expires 04/36)") not found`
* `TypeError: expect(...).toClick is not a function`

Reference job - https://github.com/Automattic/woocommerce-payments/runs/7226350436?check_suite_focus=true

### Actual behavior
The test fails randomly.

### Expected behavior
The test should pass consistently.

**Comment by htdat** [comment]
Some research: 

> Reference job - https://github.com/Automattic/woocommerce-payments/runs/7226350436?check_suite_focus=true

Before the errors mentioned above, this is the error: 

```
       Failed to load resource: the server responded with a status of 503 ()
``` 

It's not clear which page could not be loaded but I think it's the login page, i.e. the first page is opened with this test suite.


---- 

In two other runs ([1](https://github.com/Automattic/woocommerce-payments/runs/7622276774?check_suite_focus=true#step:15:36) - [2](https://github.com/Automattic/woocommerce-payments/runs/7622277381?check_suite_focus=true#step:15:36)), it's a similar message with a different status: 

```
      Failed to load resource: the server responded with a status of 429 ()
``` 

IMO, what we need to do here is to try to config to re-run failed tests. There is an option here https://jestjs.io/docs/jest-object#jestretrytimesnumretries-options but it seems to require `jest-circus` https://www.npmjs.com/package/jest-circus

**Comment by achyuthajoy** [comment]
> IMO, what we need to do here is to try to config to re-run failed tests. There is an option here https://jestjs.io/docs/jest-object#jestretrytimesnumretries-options but it seems to require jest-circus https://www.npmjs.com/package/jest-circus

@htdat `v0.3.0` of `@woocommerce/e2e-environment` introduced the option to retry failing tests via environment variables. This also includes `jest-circus` as test runner. So we don't have to manually configure the test runner & jest config.

At the moment, we're using `v0.2.3` of `@woocommerce/e2e-environment` package and we can upgrade to `v0.3.0` to get access to the new test runner and retry feature. Here is the documentation - https://www.npmjs.com/package/@woocommerce/e2e-environment/

**Comment by htdat** [comment]
We have this configuration, which is available in our current util version: https://www.npmjs.com/package/@woocommerce/e2e-utils/v/0.1.6

https://github.com/Automattic/woocommerce-payments/blob/257464cad9462f60a16c6fb98813b9904bd34376/.github/workflows/e2e-test.yml#L25
