### ISSUE TITLE
WC Pay overwrites payment method name when using PRBs with other gateways

### ISSUE THREAD

**Issue by aheckler** [Automattic/woocommerce-payments#4428]
### Describe the bug

When a merchant is using Stripe and WooCommerce Payments at the same time, and has payment request buttons (PRBs) enabled for both gateways, WooCommerce Payments will record itself as the payment method inside the order:

![Screenshot taken on 2022-07-11 at 20 57 15 UTC@2x](https://user-images.githubusercontent.com/5512652/178356888-df96ef2d-8b76-4853-990d-b39f2c731c1b.png)

... even if Stripe actually handled the transaction.

### To Reproduce

1. WC + WC Pay test site.
2. Also install Stripe and set it up in test mode.
3. Enable Apple/Google Pay in both gateways.
4. On a product page, place a test order using the Stripe PRB.
5. Verify the test transaction shows in your Stripe account.
6. Inside the WooCommerce order, note the payment method shown is `Payment via Apple Pay (WooCommerce Payments)`

I have a WC Pay + Stripe test site available for testing if need be. Just DM me in Slack. :)

Slack discussion which led to this: p1657530419969999-slack-C3NCP7ZJ6

I'm no dev, but I think the issue lies in `add_order_meta`, where we don't seem to check if WC Pay is actually the plugin handling the payment request?

https://github.com/Automattic/woocommerce-payments/blob/4.4.0/includes/class-wc-payments-payment-request-button-handler.php#L372-L394

**Comment by achyuthajoy** [comment]
Thanks for the report @aheckler. I'm able to replicate the issue on a test site with both WooCommerce Payments & Stripe enabled.

**Comment by AashikP** [comment]
This was also noticed in 5363577-zen
