### ISSUE TITLE
Generic error message when checkout fails due to an overlength phone number

### ISSUE THREAD

**Issue by aprea** [Automattic/woocommerce-payments#4433]
### Describe the bug

Checkout fails with 1 of 2 error messages when attempting to use a phone number longer than 20 characters, e.g. `123456789012345678901` (21 characters).

The error message is either:

>We're not able to process this request. Please refresh the page and try again.

<img width="826" alt="Screen Shot 2022-07-13 at 12 53 15 pm" src="https://user-images.githubusercontent.com/1527164/178640757-818b6058-834a-4f68-bb5a-325a5fd691cd.png">

or

>Error: Invalid string: 1234567890...2345678901; must be at most 20 characters

<img width="827" alt="Screen Shot 2022-07-13 at 12 53 04 pm" src="https://user-images.githubusercontent.com/1527164/178640717-19e52e6e-7f15-4a41-a3a3-7ef6837f84ea.png">

The first error message is problematic as it doesn't provide enough information to the customer about what the error is and how to rectify it.

The second error message is better because it references the invalid phone number in the error message. As such, the customer will likely be able to identify the problem and rectify it. It could be further improved by changing the wording `Error: Invalid string` to something like `Error: Invalid phone number`.

### To Reproduce

There are a few ways to reproduce this, see below:

**UPE enabled, new payment method**

1. Add a product to your cart and navigate to checkout.
2. Fill in valid billing details.
3. Use `123456789012345678901` for the billing phone number.
4. If prompted, click the "Use a new payment method" radio button and enter valid payment details.
5. Click the "Place order" button.
6. Observe that the transaction fails and you are presented with the following error message:
>Error: Invalid string: 1234567890...2345678901; must be at most 20 characters

**UPE enabled, saved payment method**

You must have an existing saved payment method to follow these steps.

1. Add a product to your cart and navigate to checkout.
2. Fill in valid billing details.
3. Use `123456789012345678901` for the billing phone number.
4. When prompted, select an existing payment method, e.g. `Visa ending in 4242`.
5. Click the "Place order" button.
6. Observe that the transaction fails and you are presented with the following error message:
>We're not able to process this request. Please refresh the page and try again.

### Actual behavior
Checkout fails with 1 of 2 error messages when attempting to use a phone number longer than 20 characters.

### Expected behavior
Clear and actionable error messages when checkout fails when attempting to use a phone number longer than 20 characters.

### Additional context

Issue observed in - 5336099-zd-woothemes

**Comment by htdat** [comment]
Another case with a VIP client. p1669221996651949-slack-CGGCLBN58
More info: 2e4c1-pb
