### ISSUE TITLE
Error handling state management

### ISSUE THREAD

**Issue by dechov** [Automattic/woocommerce-payments#444]
We currently have query errors being stored in state, though we aren't yet displaying them: https://github.com/Automattic/woocommerce-payments/blob/d0487696e32e79a8a0331684a98b2787154e63e8/client/data/transactions/reducer.js#L22-L28

Do we need (in particular) transient errors that only warrant a notice stored in our state or should we defer to core/notices [as such](https://github.com/Automattic/woocommerce-payments/blob/0cdae2fc92faf5cb896061478262c79971d50996/client/disputes/evidence/index.js#L131-L136)?

**Comment by vbelolapotkov** [comment]
I think it's a good enhancement to plugin UX, but we'd need to discuss it with the product team first before implementing.

**Comment by jessy-p** [comment]
@dechov Could you please check if this issue is still relevant?

**Comment by dechov** [comment]
I haven't tested the error flows lately but strongly suspect we still have significant inconsistency in how they're handled, in terms of whether and how we're displaying errors from network responses.

Certainly we shouldn't just be storing them in state _instead_ of showing any indication that something's gone wrong, which does seem to me like what we're still doing in that Transactions list view.

**Comment by vbelolapotkov** [comment]
@dechov I'm closing this issues, since it's very old, has not very clear scope and wasn't prioritized for very long time. I think we can get back to this once its priority is higher.
