### ISSUE TITLE
[Deposits UI] The Account Details component should inform the merchant when KYC details are missing

### ISSUE THREAD

**Issue by aprea** [Automattic/woocommerce-payments#4454]
### Description

The **Payments → Overview** page contains an "Account Details" component. This component displays the store's payments and deposits status.

We display the following state after the merchant completes WCPay onboarding (i.e. Stripe KYC) but doesn’t provide the necessary proof of identity documents.

<img width="588" alt="screen-shot-2022-07-01-at-10 33 31-am" src="https://user-images.githubusercontent.com/1527164/179672458-6930b269-acfa-4958-9d1a-5259c148df16.png">

The same state is represented in Stripe's dashboard as per below:

<img width="444" alt="screen-shot-2022-07-01-at-10 31 38-am" src="https://user-images.githubusercontent.com/1527164/179672598-fe8d56a0-9e05-42c1-8cff-4e8d7f52aad3.png">

It was noted that this current behaviour is problematic, i.e.

> I think a point of contention tends to be this - given a merchant likely needs to supply more information, we should state the same as Stripe in that the account is restricted but more information is required.

> Agreed. And provide an obvious link (if possible) to where merchants need to go to update their info.

### Acceptance criteria

TBD

### Designs

TBD

### Testing instructions

TBD

### Dev notes

TBD

### Additional context
- WCPay proposal: deposits status UI changes - pdjTHR-1jz-p2
- Discussion in Figma - ie6jhuqFFl7l3RQeAD3mzQ-fi-0%3A1

**Comment by zmaglica** [comment]
@aprea Any updates on this issue? This is the second time we triage it, so I am not sure do we have any updates here.

**Comment by aprea** [comment]
Hi @zmaglica, apologies, I am not familiar with the triage process, what kind of update do you need here?

For context, I created this issue based on feedback from Britni and @aheckler. This came up during my exploration of the custom deposit schedules project but I purposely left it out of the project because it was out of scope.

Many of the details in this issue are marked "TBD" because I didn't have enough information at the time of creating this issue. We will need to follow up with product/design to clarify the requirements.

**Comment by zmaglica** [comment]
Thank you @aprea for feedback. Do we have open issues for product and designs and can I mark this issue as blocked?

**Comment by jessy-p** [comment]
Marking for Product Review to clarify the Requirements

**Comment by haszari** [comment]
This is directly relevant to upcoming deposits UI refresh.

**Comment by brucealdridge** [comment]
Closing as a stale issue, please reopen if this affects merchants.
