### ISSUE TITLE
Not all tasks in the Payments → Overview task list are visible

### ISSUE THREAD

**Issue by Jinksi** [Automattic/woocommerce-payments#4471]
### Describe the bug

The **Payments → Overview** `Things to do` task list should render the [following tasks](https://github.com/Automattic/woocommerce-payments/blob/37997a7e550005c1d1ca827e6ffbf8da7b15093e/client/overview/task-list/tasks.js#L65) when the [`_wcpay_feature_account_overview_task_list`](https://github.com/Automattic/woocommerce-payments/blob/2f0ffe9d3e91b4a037bc5e4636b01ad757bf2985/includes/class-wc-payments-features.php#L60-L62) feature flag is set to `'1'`.

The **Payments → Overview** `Things to do` task list is set for launch with the release of WCPay 4.5.0 #4460.

* **⚠️ Not visible:** [`update-business-details`](https://github.com/Automattic/woocommerce-payments/pull/1799): Update WooCommerce Payments business details.
* **⚠️ Not visible:** [`reconnect-wpcom-user`](https://github.com/Automattic/woocommerce-payments/pull/1912): WooCommerce Payments is missing a connected WordPress.com account. Some functionality will be limited without a connected account.
* **⚠️ Not visible:** [`force-secure-checkout`](https://github.com/Automattic/woocommerce-payments/pull/2480): Protect your customers data and increase trustworthiness of your store by forcing HTTPS on checkout pages.
* **Visible:** `dispute-resolution-task`: *x* disputed payments needs your response.

> **Warning**
> The tasks that are currently **not visible** should be reviewed from a design/product perspective before fixing this issue. See discussion: paJDYF-4EQ-p2#comment-12661

### To Reproduce

1. Meet the criteria for each task above to be visible. The simplest way is to overwrite each setting in [`class-wc-payments-admin.php`→`register_payments_scripts()`→`$wcpay_settings`](https://github.com/Automattic/woocommerce-payments/blob/55916cc468e361202601981767a81ddea9456fc9/includes/admin/class-wc-payments-admin.php#L452) to the following:
      * `update-business-details`: `'showUpdateDetailsTask' => 'yes'`
      * `reconnect-wpcom-user`: `'wpcomReconnectUrl' => WC_Payments_Account::get_wpcom_reconnect_url()`
      * `force-secure-checkout`: `'needsHttpsSetup' => 'yes'`
      * `dispute-resolution-task`: `'numDisputesNeedingResponse' => 10`
1. Visit **Payments → Overview** in wp-admin. Notice that only the `dispute-resolution-task` is visible
   * ⚠️ only in WCPay v4.5.0+ from which the `_wcpay_feature_account_overview_task_list` feature flag defaults to `'1'`.

### Actual behavior

Only the `dispute-resolution-task` is rendered.

<img width="600" alt="image" src="https://user-images.githubusercontent.com/3147296/180698908-1c2d23e4-63dc-4f0d-88a7-37d15e61c068.png">

### Expected behavior

All tasks listed above are visible.

<img width="600" alt="image" src="https://user-images.githubusercontent.com/3147296/180698771-9c1ffe30-0e84-4453-92b3-8544798e444e.png">

### Additional context

Setting the default value `isAccountOverviewTasksEnabled = true` in the [`getTasks()` function](https://github.com/Automattic/woocommerce-payments/blob/55916cc468e361202601981767a81ddea9456fc9/client/overview/task-list/tasks.js#L20) allows all list items to be displayed, so it looks like the feature flag is not being passed through to this function correctly.

Slack discussion: p1658460988099129-slack-C03LA109BKM
P2 discussion about design/product revision of task list items: paJDYF-4EQ-p2#comment-12661

**Comment by RadoslavGeorgiev** [comment]
@Jinksi is this a part of a project you are working on, or is it a part of core which Gamma should handle? Initially we thought this is a bug, but the description of #4457 made it seem like it is intentional.

**Comment by Jinksi** [comment]
@RadoslavGeorgiev this one wasn't intentional 😅  it was discovered last minute during our disputes project (pdjTHR-17C-p2) but wasn't crucial to fix for the project.

So this issue can be handled by Gamma as a normal WCPay core issue now 🙏
