### ISSUE TITLE
Enable WC Payments menu action for merchants without WC Payments installed

### ISSUE THREAD

**Issue by daquinons** [Automattic/woocommerce-payments#4483]
### Description
This is an issue to track the effort on enabling the previous experiment in WooCommerce https://github.com/woocommerce/woocommerce/issues/32219#issuecomment-1002861022 

This time is not an experiment anymore but a feature for all the merchants in countries where WC Payments is supported.

It should be rolled out to stores:
- In WCPay eligible countries.
- Without WCPay installed.
- Not selling CBD, based on WooCommerce onboarding data.
- With marketplace suggestions enabled in WooCommerce. 

For now, the flows will be the same as in the experiments, a sign-up and dismiss flows.

This is the base of the project, with #4529 as a nice-to-have feature if times allow it.

More detail in the project thread: paJDYF-4Ov-p2

**Comment by zmaglica** [comment]
@daquinons Is there an update for this issue? I noticed that linked issue in description is closed. Can we start to work on this particular issue? I mean, shall we continue with our usually processes (triaging and prioritization) or is there something more to be done before that?

**Comment by ismaeldcom** [comment]
Hey @zmaglica! It's a new project in which we will be working for the following weeks. No need to triage 🙂
