### ISSUE TITLE
[Manual deposits] Merchants can request a deposit of their available balance via the "Deposit funds" button

### ISSUE THREAD

**Issue by aprea** [Automattic/woocommerce-payments#4485]
Part of the manual deposits project - pdjTHR-1DS-p2

### Blocked by
- https://github.com/Automattic/woocommerce-payments/issues/4464
- 2265-gh-Automattic/woocommerce-payments-server

Please ensure the above issues are completed before working on this issue.

### Description

The custom deposit schedule project will let merchants change their deposit schedule to "Manual". In doing so, they can request an on-demand deposit of their available balance via the "Deposit funds" button located on the **Payments → Overview** page in WCPay Client.

<img width="698" alt="Screen Shot 2022-10-27 at 10 23 18 am" src="https://user-images.githubusercontent.com/1527164/198504176-6d479592-c6b8-4ecc-921d-5b18da58c1b4.png">

In this issue, we need to implement the "Deposit funds" button workflow.

### Acceptance criteria

- A "Deposit funds" button appears on the **Payments → Overview** page when the merchant's deposit schedule is set to "Automatic - weekly", "Automatic - monthly" or "Manual".
- The "Deposit funds" button is enabled if:
	- The merchant has deposits enabled (i.e. the `deposits_blocked` flag is not `0`)
	- **and**
	- The merchant's available balance is greater than the minimum deposit amount for the deposit currency (e.g. $5.00).
- When the "Deposit funds" button is clicked, a modal appears that asks the merchant to confirm the deposit request.
- When the deposit request is confirmed, a request is sent to WCPay Server and is processed by the endpoint handler (see 2265-gh-Automattic/woocommerce-payments-server).
- If successful:
	- A payout is initiated and the balances component is updated to reflect the new state.
	- A success notice is visible and contains the text: `Deposit for %%deposit-amount%% in transit.` The notice includes a "View details" link which links to the deposit details page for the new deposit.

**Post-release:** Add user docs for this feature to https://woocommerce.com/document/payments/

### Designs

paJDYF-6a4-p2

### Testing instructions

TBD

>To send the funds from a test transaction directly to your available balance, use the test cards in this section. Other test cards send funds from a successful payment to your pending balance.

https://stripe.com/docs/testing#available-balance

### Additional context
- Project thread: pdjTHR-1DS-p2
- PRD: pdjTHR-1DP-p2

**Comment by james-allan** [comment]
I've removed my assignment from this issue in case someone has the bandwidth to pick it up. I didn't really get very far other than exploring the relevant JS files etc.

**Comment by Jinksi** [comment]
Closing this as stale – this will be revisited in a future project.
