### ISSUE TITLE
Remove the feature flag of task list on Overview page

### ISSUE THREAD

**Issue by shendy-a8c** [Automattic/woocommerce-payments#4489]
We enabled the task list on the Overview page for all merchants in this PR: https://github.com/Automattic/woocommerce-payments/pull/4460 and will be shipped along in v4.5. Before that, the task list is behind a feature flag called `_wcpay_feature_account_overview_task_list`.

This issue is a reminder to remove the feature flag checks completely when the feature is live and stable after some time, not earlier than v4.7.

Things need to be removed:
- Any reference to `_wcpay_feature_account_overview_task_list`.
- Definition and reference to `is_account_overview_task_list_enabled()`.

Also note that as of the time when this issue is created, there is a bug with the task list issued here: https://github.com/Automattic/woocommerce-payments/issues/4471.

**Comment by daquinons** [comment]
@shendy-a8c Should we close this after #4707 is merged, or is this about a different flag?

**Comment by daquinons** [comment]
Confirmed the flag can be removed p1669623805166949/1669397142.219509-slack-C02BW3Z8SHK

**Comment by dmallory42** [comment]
Adjusting the estimate to reflect refactors and improvements included in the final PR #6696.
