### ISSUE TITLE
Add JS translation tooling

### ISSUE THREAD

**Issue by v18** [Automattic/woocommerce-payments#45]
You can use the same set up WooCommerce Admin has since they're going to get merged to WC core 👌

https://github.com/woocommerce/woocommerce-admin

**Comment by jrodger** [comment]
Does https://github.com/Automattic/woocommerce-payments/pull/1431 satisfy this issue @v18? I think it does?

**Comment by v18** [comment]
@jrodger - yes, I agree. Closing the issue since that PR was merged.
