### ISSUE TITLE
[Authorizations] Add new Authorizations tab in Transactions

### ISSUE THREAD

**Issue by mgascam** [Automattic/woocommerce-payments#4501]
### Description

As part of an effort to improve the capture payment workflow, we will add a new 'Authorizations' tab to the transactions page. This new tab will contain a table with pending authorizations.

### Acceptance criteria

* Refactor Transactions page to support tabbed navigation.
* Move Transactions page to its own tab.
* Add new Authorizations tab.
* Add Authorizations list table. N.B. We will tackle filters and pagination of the table in a different task
* Wire the Authorizations list to server endpoint.
* Click on a row will take the merchant to the payment details page

### Designs

<img width="1438" alt="Screen Shot 2022-07-29 at 11 41 58" src="https://user-images.githubusercontent.com/1553182/181748268-0a377c37-1a8f-4642-922e-a0fa00fb3bb6.png">

**Comment by elazzabi** [comment]
Given I don't have enough knowledge about the subject, do we usually have online and in-person authorizations? Asking to see if we should add a channel column (`Online|In-Person`) to the table 🤔  @kalessil @mgascam

**Comment by kalessil** [comment]
@elazzabi @mgascam : we have an updated mockups for the listing - paJDYF-4Kv-p2

**Comment by mgascam** [comment]
>do we usually have online and in-person authorizations? Asking to see if we should add a channel column (Online|In-Person) to the table

Good point @elazzabi. I'd say in-person payments are excluded from this list but asked here paJDYF-4N1-p2#comment-13060 for clarification.
