### ISSUE TITLE
[Authorizations] Add pagination to Authorizations table

### ISSUE THREAD

**Issue by mgascam** [Automattic/woocommerce-payments#4503]
### Description

As part of an effort to improve the capture payment workflow, we will add a new 'Authorizations' tab to the transactions page. This new tab will contain a table with pending authorizations.

In this task we will add pagination capability to the table of pending authorizations.

### Acceptance criteria

* Merchants can traverse the list of pending authorizations via pagination.
* Handle errors while fetching authorizations data

### Designs

<img width="1438" alt="Screen Shot 2022-07-29 at 11 41 58" src="https://user-images.githubusercontent.com/1553182/181752811-baacbb14-f480-456d-b007-de9a7f77d176.png">

**NOTE**: the current UI proposal does not include filters nor pagination.

**Comment by kalessil** [comment]
As per paJDYF-4GQ-p2#comment-12816, I updated the issue to exclude filtering.
