### ISSUE TITLE
Add Download button to the Authorizations table

### ISSUE THREAD

**Issue by mgascam** [Automattic/woocommerce-payments#4505]
### Description

Similar to what we do with Transactions, we should allow merchants to download the list of Authorizations as a CSV file.

### Acceptance criteria

* Add a Download button to the new Authorizations table.
* The file should include the whole list of pending authorizations, regardless of the pagination or filters applied.

### Designs

<img width="1438" alt="Screen Shot 2022-07-29 at 11 41 58" src="https://user-images.githubusercontent.com/1553182/181752811-baacbb14-f480-456d-b007-de9a7f77d176.png">

**NOTE**: the current UI proposal does not include filters nor pagination.

**Comment by kalessil** [comment]
As per paJDYF-4GQ-p2#comment-12816, we don't need export functionality for authorizations.
