### ISSUE TITLE
Flat rate and local pickup shipping methods for WCPay Subscriptions products can result in shipping option issues for renewals

### ISSUE THREAD

**Issue by csmcneill** [Automattic/woocommerce-payments#4509]
### Describe the bug
If a flat rate shipping method with a fee and a free local pickup option are used when purchasing a WCPay subscription product, the recurring shipping option will not be available unless a customer selects multiple radio buttons.

### To Reproduce

1. Add one flat rate shipping method (with a fee) to a shipping zone.
2. Add one local pickup shipping method (free) to a shipping zone; ensure that it is _below_ the flat rate shipping method.
3. Add a WCPay subscription product to the cart.
4. Enter in address details to pull up shipping rates for the shipping zone from step 1.
5. The displayed price will show the appropriate options for initial shipment with the flat rate shipping price, but nothing for the renewals under `Recurring totals`.
6. Change the shipping method from the flat rate option to the local pickup option.
7. No shipping options are shown for renewals.
8. Change the shipping method _back_ to the flat rate option.
10. New radio buttons will appear that offer shipping options specifically for renewals under `Recurring totals`.
11. Sometimes, when the two options match, the radio buttons under `Recurring totals` will disappear again.

### Actual behavior

Multiple shipping options are shown for the parent order, and additional shipping options are shown for renewals _only_ when changing from flat rate to local pickup and then _back_ to flat rate.

### Screenshots

When a paid flat rate and free local pickup option are used:
![Screen Capture on 2022-07-31 at 18-24-30](https://user-images.githubusercontent.com/82999806/182056260-186c5c97-1592-44f5-8b50-75521d2429fb.gif)

When two paid flat rate options are used:
![Screen Capture on 2022-07-31 at 20-13-55](https://user-images.githubusercontent.com/82999806/182056306-9feb9163-e61a-4946-9807-3cbe7dd6dcda.gif)

If a free local pickup method is listed before a paid flat rate method:

<img width="512" alt="Markup 2022-07-31 at 20 41 35" src="https://user-images.githubusercontent.com/82999806/182056585-76128383-fcbb-4516-abc0-39de4d0dfc91.png">

### Expected behavior
If the radio buttons are supposed to appear for the renewals, then they should be present consistently.

### Desktop (please complete the following information):

* OS: MacOS 12.5
* Browser Chrome
* Version 103.0.5060.134 (Official Build) (x86_64)

### Additional context

Similar to 4335-gh-woocommerce/woocommerce-subscriptions

**Comment by haszari** [comment]
Marking as low for now, since it's intermittent and requires a combination of settings. That said, would be good to tidy this behaviour up at some point.

**Comment by mattallan** [comment]
This issue was fixed in subscriptions-core PR: https://github.com/Automattic/woocommerce-subscriptions-core/pull/467 and shipped in WooPayments 6.2.0.
