### ISSUE TITLE
Cleanup old Payment method references in JS code

### ISSUE THREAD

**Issue by jessy-p** [Automattic/woocommerce-payments#4519]
### Description
After alternative payment methods like SEPA, Sofort and Giropay were switched to UPE, we have removed the redundant gateway classes via [#3394](https://github.com/Automattic/woocommerce-payments/pull/3394). There are still references to the redundant elements in the JS code. e.g. https://github.com/Automattic/woocommerce-payments/blob/8926d370a05c49382b3149300b0102f7a7d3ca75/client/checkout/classic/index.js#L190-L190 

This issue is created to clean-up the JS code.

### Acceptance criteria

Redundant code related to old payment gateways removed from JS & PHP code.

**Comment by vbelolapotkov** [comment]
Despite it's not directly checkout related but it's a leftover code from early LPMs implementation, so routing accordingly. cc @c-shultz and @pierorocca

**Comment by timur27** [comment]
Old payment methods on the front end were cleaned up as part of the deferred intent creation UPE rollout. To be more specific, in https://github.com/Automattic/woocommerce-payments/pull/7795. Having said that, I will close this issue as it's not relevant anymore.
