### ISSUE TITLE
[SPIKE] Break down outstanding platform checkout and WC Blocks incompatibilities

### ISSUE THREAD

**Issue by waclawjacek** [Automattic/woocommerce-payments#4521]
### Description

Currently when wanting to benefit from the platform checkout, you need to use the shortcode checkout. The goal of this issue is to research the work needed to add Cart and Checkout Blocks compatibility and to create the issues necessary to add this implementation.

### Acceptance criteria

Issues that need to be tackled in order for us to add Blocks checkout compatibility are created.

### Additional context

Notes on items taken in the past that might require creating issues for: pdpOw2-ls-p2

**Comment by Mayisha** [comment]
Issues created. 
- #4613 
- #4614

**Comment by frosso** [comment]
Looks like the issues have been created - closing
