### ISSUE TITLE
Pay for Order page throws error with UPE + Multi-currency

### ISSUE THREAD

**Issue by ricardo** [Automattic/woocommerce-payments#4522]
### Describe the bug

An error gets thrown on the Pay for Order page with UPE + Multi-currency:

> We're not able to process this request. Please refresh the page and try again.

And in the UPE form:

> An error was encountered when preparing the payment form. Please try again later.

I noticed no errors if the only available UPE payment method is credit card, so this seems to be related to the additional payment methods of UPE.

### To Reproduce

- Enable UPE with CC + giropay.
- Enable Multi-Currency with at least 2 currencies + currency switcher.
- Create a new order and go to the pay for order page.
- Change currency from USD to EUR on the currency switcher.
- Notice an error gets thrown.

**Comment by thelogicwizards** [comment]
User in [5559464-zen](https://woothemes.zendesk.com/agent/tickets/5559464) affected, as well:

- Site using the inbuilt multi-currency feature from WooCommerce Payments
- UPE is enabled (incl. Giropay)
- Merchant added a currency switcher widget on this page: https://reconnectiveacademy.com/events/onex-virginia/
- However, when switching the currency to USD and proceeding to checkout, these errors appear: https://d.pr/i/eteYdR
`We're not able to process this request. Please refresh the page and try again.`
`An error was encountered when preparing the payment form. Please try again later.`

Testing Completed:
- Issue only happens with USD, as it seems the site tries to place the order without any billing details entered: https://d.pr/i/QyRwWp
- Added a test product (user gave permission to do that) and see the same issue only with USD: https://d.pr/i/mSaU91
- Default CHF is fine: https://d.pr/i/cbdASy
- EUR is fine: https://d.pr/i/HOHaxi
- JPY is fine: https://d.pr/i/p3fhYv
- Seems issue might be related to this known bug (though currencies are different): [Pay for Order page throws error with UPE + Multi-currency #4522](https://github.com/Automattic/woocommerce-payments/issues/4522)

Latest fatal-errors log indicates a WCPay stack trace error:

```
2022-09-15T08:56:33+00:00 CRITICAL Uncaught TypeError: Argument 1 passed to WCPay\MultiCurrency\Currency::__construct() must be of the type string, null given, called in /home/reconne2/public_html/wp-content/plugins/woocommerce-payments/includes/multi-currency/MultiCurrency.php on line 464 and defined in /home/reconne2/public_html/wp-content/plugins/woocommerce-payments/includes/multi-currency/Currency.php:76
Stack trace:
#0 /home/reconne2/public_html/wp-content/plugins/woocommerce-payments/includes/multi-currency/MultiCurrency.php(464): WCPay\MultiCurrency\Currency->__construct(NULL, 1)
#1 /home/reconne2/public_html/wp-content/plugins/woocommerce-payments/includes/multi-currency/MultiCurrency.php(248): WCPay\MultiCurrency\MultiCurrency->initialize_available_currencies()
#2 /home/reconne2/public_html/wp-includes/class-wp-hook.php(307): WCPay\MultiCurrency\MultiCurrency->init('')
#3 /home/reconne2/public_html/wp-includes/class-wp-hook.php(331): WP_Hook->apply_filters(NULL, Array)
#4 /home/reconne2/public_html/wp-includes/plugin.php(476): WP_Hoo in /home/reconne2/public_html/wp-content/plugins/woocommerce-payments/includes/multi-currency/Currency.php on line 76
```

**Comment by tpaksu** [comment]
@thelogicwizards @ricardo is this issue still reproducible? I tested on my local but couldn't see the error. I'm trying to reproduce it on reconnectiveacademy website, but it seems they removed the currency switcher from the checkout page.

**Comment by ricardo** [comment]
@tpaksu I could not reproduce anymore, so probably was fixed somewhere. Closing.

**Comment by tpaksu** [comment]
Thanks @ricardo!
