### ISSUE TITLE
Incorrect shipping method cost displayed on cart/checkout pages

### ISSUE THREAD

**Issue by Calvin-PH** [Automattic/woocommerce-payments#4526]
### Shipping method cost coming as 1 in cart/checkout pages when WooCommerce Payments Plugin ( 4.5.0 ) is active.

When WooCommerce Payments plugin ( 4.5.0 ) is active, shipping method cost is coming as 1 in cart/checkout pages.

### To Reproduce

1. Create a sample shipping method for cart/checkout
2. Pass cost as array of costs to the WooCommerce add_rate() function
3. Go to cart/checkout page and check the rate of the created shipping method
4. Created shipping method rate will be shown as 1 in cart/checkout pages.

### Actual behavior

When WooCommerce Pyaments Plugin ( 4.5.0 ) is active, and when the cost is passed as an array to the WooCommerce add_rate() function, and the callback function from WooCommerce Payments plugin which always returns 1 for array of costs. Here the plugin is not handling the array of costs, it directly converts the cost to float, resulting in array to float conversion and the cost is returned as 1 always. 
As per the WooCommerce code reference, we can pass cost as Amount or array of costs ( for per_item shipment ) to the add_rate() function.
Also from the code reference we could see that calc_tax requires array of costs for per_item.
There is no such issue with the previous version of WooCommerce Payments plugin. Also when this plugin is deactivated the rates are returned correctly.

Please refer the below screenshots from WooCommerce code reference -

### Screenshots

![woocommerce-code-reference](https://user-images.githubusercontent.com/110521782/182552268-8ec891b8-95e0-4379-b3e6-c4435055057c.png)

![woocommerce-code-reference-2 png](https://user-images.githubusercontent.com/110521782/182553096-f2b2274f-e04e-4b1d-b32b-6de12e0b9c63.png)

### Expected behavior

WooCommerce Payments plugin should handle the array of costs and return appropriate shipping cost to the filter hook.

### Additional context

Filter hook : add_filter( 'woocommerce_shipping_method_add_rate_args', [ $this, 'convert_shipping_method_rate_cost' ], 50 );

WooCommerce Payments ( 4.5.0 )
WooCommerce ( 6.7.0 )
https://woocommerce.github.io/code-reference/files/woocommerce-includes-abstracts-abstract-wc-shipping-method.html#source-view.265

**Comment by jbordonado** [comment]
Hello! 

This issue is the same as #4609, for which I opened a Pull Request to fix it yesterday.
Hopefully, the PR will get merged soon.

Thanks for your report and detailed analysis, I'm closing this one in favor of #4609 since I started the work over there.
