### ISSUE TITLE
[Multi-Currency] Preview for Djiboutian franc (DJF) shows incorrect/misleading values

### ISSUE THREAD

**Issue by csmcneill** [Automattic/woocommerce-payments#4528]
### Describe the bug
After enabling Djiboutian franc (DJF), attempts to preview the exchange rate are miscalculated, as it seems the decimal place for the preview amount is incorrect.

### To Reproduce
1. Navigate to **WooCommerce > Settings > Multi-currency**.
2. Enable DJF as a currency.
3. Note the exchange rate (e.g. `Current rate: 1 USD = 177.90556 DJF (Last updated: August 3, 2022 9:18 am)`)
4. Change price rounding to `1`
5. Note the preview amount doesn't match the exchange rate.
6. Change the exchange rate to `Manual`.
7. Set the `Manual Rate` to `1`.
8. The preview will show that `1` in the site's default currency is `100` DJF.

### Actual behavior
The preview exchange rates for DJF appear to have a decimal error that will show the resulting rate as 100-times the expected exchange rate.

### Screenshots
![Markup on 2022-08-03 at 09:17:14](https://user-images.githubusercontent.com/82999806/182636411-a06efd73-11c8-462c-8920-92a8f4fca435.png)

![Markup on 2022-08-03 at 09:17:27](https://user-images.githubusercontent.com/82999806/182636428-39a6a969-9aff-4b5e-8699-560a3118d7c5.png)

![Markup on 2022-08-03 at 09:48:18](https://user-images.githubusercontent.com/82999806/182638638-05a277e6-97cd-4e89-9193-ee5d50d56ce9.png)

### Expected behavior
The `Preview` exchange rate should match the rates defined in the currency settings.

### Desktop (please complete the following information):

* OS: MacOS 12.5
* Browser: Google Chrome
* Version: 103.0.5060.134 (Official Build) (x86_64)

### Additional context
Ticket: 5448074-zen

**Comment by tpaksu** [comment]
Thank you @csmcneill for letting us know about that, it seems like all currencies with zero decimal places show wrong in the currency previewer. <strike>I'll prepare a fix and let you know.</strike> Prepared a fix in #6269.
