### ISSUE TITLE
[GlobalStep] [Custom Order Tables] Order status fails to update as "Refunded" for including the string "losing_evidence" in the Additional Information field on "Orders" page.

### ISSUE THREAD

**Issue by gglobalstep** [Automattic/woocommerce-payments#4553]
### Bug Description:
Order status fails to update as ["](https://envious-firefly.jurassic.ninja/cot-no-syncing/wp-admin/admin.php?page=wc-admin)Refunded" for including the string "losing_evidence" in the Additional Information field on "Orders" page.

### Environment:
Woocommerce Version: WooCommerce 6.9.0
WooCommerce  Payments 4.6.0-test-2
WordPress version: v6.0.1

PC:
Windows 10
Chrome(Version 104.0.5112.81) 

### Steps To Reproduce:
1. Open the JN site "[https://envious-firefly.jurassic.ninja/cot-syncing/wp-admin/](https://envious-firefly.jurassic.ninja/cot-no-syncing/wp-admin/)" 
1. Purchase a product using a dispute-specific test card on frontend.
1. Navigate to the order page as admin (WooCommerce > Orders)
1. Ensure the order has been set to on-hold and there is an order note indicating a dispute was created and that links to the correct dispute page.
1. Challenge the dispute, being sure to include the string losing_evidence in the Additional Information field.
1. Again, navigate to the order page
1. Observe that Order status fails to update as "Refunded" for including the string "losing_evidence" in the Additional Information field on "Orders" page.

### Note:
The order total is $171.84 USD and we’re showing Refunded --$515.52 USD (i.e. 171.84 * 3)

### Actual Result:
Order status fails to update as "Refunded" for including the string "losing_evidence" in the Additional Information field.

### Expected Result:
Order status should be updated as "Refunded" for including the string "losing_evidence" in the Additional Information field on "Orders" page.

Screenshot:

![#4553 1](https://user-images.githubusercontent.com/41110392/183675663-fa9ff6d0-1299-4116-94d8-c2696d4f9a40.jpg)

![#4553 2](https://user-images.githubusercontent.com/41110392/183675673-1ca32203-59b3-45f9-9e6e-252bc7ffdbe0.jpg)

![#4553 3](https://user-images.githubusercontent.com/41110392/183675678-6cfef2bc-7330-464b-9a1b-4b65839b42cb.jpg)

*Isolating the problem (mark completed items with an [x]):*
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

<details>

`
### WordPress Environment ###

WC Version: 6.9.0
REST API Version: ✔ 6.9.0
WC Blocks Version: ✔ 8.1.0
Action Scheduler Version: ✔ 3.4.0
Log Directory Writable: ✔
WP Version: 6.0.1
WP Multisite: ✔
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache/2.4.54 (Unix) OpenSSL/1.0.2g
PHP Version: 7.4.30
PHP Post Max Size: 1 GB
PHP Time Limit: 30
PHP Max Input Vars: 5000
cURL Version: 7.47.0
OpenSSL/1.0.2g

SUHOSIN Installed: –
MySQL Version: 5.7.33-0ubuntu0.16.04.1-log
Max Upload Size: 1 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 6.9.0
WC Database Prefix: wp_5_
Total Database Size: 31.29MB
Database Data Size: 17.75MB
Database Index Size: 13.54MB
wp_5_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_5_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_5_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_5_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_5_woocommerce_order_items: Data: 0.08MB + Index: 0.02MB + Engine InnoDB
wp_5_woocommerce_order_itemmeta: Data: 0.36MB + Index: 0.44MB + Engine InnoDB
wp_5_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_5_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_5_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_5_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_5_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_5_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_5_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_5_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_5_actionscheduler_actions: Data: 2.52MB + Index: 1.97MB + Engine InnoDB
wp_5_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_5_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_5_actionscheduler_logs: Data: 1.52MB + Index: 1.89MB + Engine InnoDB
wp_5_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_5_comments: Data: 1.52MB + Index: 0.72MB + Engine InnoDB
wp_5_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_5_options: Data: 4.08MB + Index: 0.11MB + Engine InnoDB
wp_5_postmeta: Data: 4.05MB + Index: 5.03MB + Engine InnoDB
wp_5_posts: Data: 0.31MB + Index: 0.23MB + Engine InnoDB
wp_5_snippets: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_5_termmeta: Data: 0.05MB + Index: 0.03MB + Engine InnoDB
wp_5_terms: Data: 0.05MB + Index: 0.03MB + Engine InnoDB
wp_5_term_relationships: Data: 0.05MB + Index: 0.02MB + Engine InnoDB
wp_5_term_taxonomy: Data: 0.05MB + Index: 0.03MB + Engine InnoDB
wp_5_wcs_payment_retries: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_5_wc_admin_notes: Data: 0.05MB + Index: 0.00MB + Engine InnoDB
wp_5_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_5_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_5_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_5_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_5_wc_orders: Data: 0.22MB + Index: 0.13MB + Engine InnoDB
wp_5_wc_orders_meta: Data: 1.52MB + Index: 1.52MB + Engine InnoDB
wp_5_wc_order_addresses: Data: 0.13MB + Index: 0.11MB + Engine InnoDB
wp_5_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_5_wc_order_operational_data: Data: 0.13MB + Index: 0.06MB + Engine InnoDB
wp_5_wc_order_product_lookup: Data: 0.09MB + Index: 0.06MB + Engine InnoDB
wp_5_wc_order_stats: Data: 0.09MB + Index: 0.05MB + Engine InnoDB
wp_5_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_5_wc_product_attributes_lookup: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_5_wc_product_download_directories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_5_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_5_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_5_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_5_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_5_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_blogmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_blogs: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_ms_snippets: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_registration_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_signups: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_site: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_sitemeta: Data: 0.06MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Data: 0.06MB + Index: 0.03MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB

### Post Type Counts ###

attachment: 12
page: 6
post: 2
product: 59
product_variation: 107
shop_coupon: 1
shop_order: 608
shop_order_refund: 13
shop_subscription: 132

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ❌Error messages should not be shown to visitors.

### Active Plugins (10) ###

WooCommerce Stripe Gateway: by WooCommerce – 6.5.0
WooCommerce Payments Dev Tools: by Automattic –
WooCommerce Payments: by Automattic – 4.5.1
WooCommerce Subscriptions: by WooCommerce – 4.4.0
WooCommerce: by Automattic – 6.9.0-dev
WP phpMyAdmin: by Puvox.software – 5.2.0.7
NS Cloner - Site Copier: by Never Settle – 4.1.9.3
Code Snippets: by Code Snippets Pro – 3.2.0
WP Console: by Edi Amin – 2.3.1
WooCommerce Blocks: by Automattic – 8.1.0

### Inactive Plugins (6) ###

Companion Plugin: by Osk – 1.27
WooCommerce Beta Tester: by WooCommerce – 2.0.5
WooCommerce Smooth Generator: by Automattic – 1.0.4
WooCommerce Subscriptions Core: by Automattic – 2.1.0
WooCommerce Subscriptions Core: by Automattic – 2.1.0
WooCommerce Subscriptions CSV Importer and Exporter: by Prospress Inc – 2.1.0

### Settings ###

API Enabled: –
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
subscription (subscription)
variable (variable)
variable subscription (variable-subscription)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –
Enforce Approved Product Download Directories: ✔

### WC Pages ###

Shop base: #5 - /shop/
Cart: #6 - /cart/
Checkout: #7 - /checkout/
My account: #8 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Storefront
Version: 4.1.1 (update to version 4.1.2 is available)
Author URL: https://woocommerce.com/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Subscriptions ###

WCS_DEBUG: ✔ No
Subscriptions Mode: ✔ Live
Subscriptions Live URL: https://envious-firefly.jurassic.ninja/cot-syncing
Subscription Statuses: trash: 1
auto-draft: 4
wc-active: 116
wc-expired: 1
wc-pending-cancel: 1
wc-pending: 3
wc-on-hold: 6

WooCommerce Account Connected: ❌ No
Custom Retry Rules: ✔ No
Custom Retry Rule Class: ✔ No
Custom Raw Retry Rule: ✔ No
Custom Retry Rule: ✔ No
Retries Migration Status: ✔ Completed
Report Cache Enabled: ✔ Yes
Cache Update Failures: ✔ 0 failure

### Store Setup ###

Country / State: United States (US) — California

### Subscriptions by Payment Gateway ###

Stripe: wc-active: 1
WooCommerce Payments: trash: 1
wc-active: 115
wc-expired: 1
wc-on-hold: 6
wc-pending: 3
wc-pending-cancel: 1

### Payment Gateway Support ###

WooCommerce Payments: products
refunds
multiple_subscriptions
subscription_cancellation
subscription_payment_method_change_admin
subscription_payment_method_change_customer
subscription_payment_method_change
subscription_reactivation
subscription_suspension
subscriptions
subscription_amount_changes
subscription_date_changes
tokenization
add_payment_method

Stripe: products
refunds
tokenization
add_payment_method
subscriptions
subscription_cancellation
subscription_suspension
subscription_reactivation
subscription_amount_changes
subscription_date_changes
subscription_payment_method_change
subscription_payment_method_change_customer
subscription_payment_method_change_admin
multiple_subscriptions

### Admin ###

Enabled Features: activity-panels
analytics
coupons
customer-effort-score-tracks
experimental-products-task
experimental-import-products-task
experimental-fashion-sample-products
experimental-product-tour
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
wc-pay-promotion
wc-pay-welcome-page
wc-pay-subscriptions-page

Disabled Features: minified-js
new-product-management-experience
settings

Daily Cron: ✔ Next scheduled: 2022-08-10 04:09:10 +00:00
Options: ✔
Notes: 52
Onboarding: completed

### WooCommerce Payments ###

Version: 4.5.1
Connected to WPCOM: Yes
Blog ID: 209308881
Account ID: acct_1LRpvZ2H8i9XPJFa

### Action Scheduler ###

Canceled: 110
Oldest: 2022-08-03 07:18:18 +0000
Newest: 2022-08-09 13:45:02 +0000

Complete: 6,526
Oldest: 2022-07-29 04:19:18 +0000
Newest: 2022-08-07 23:10:07 +0000

Failed: 6
Oldest: 2022-08-09 13:31:59 +0000
Newest: 2022-08-09 13:31:59 +0000

Pending: 121
Oldest: 2022-08-09 22:44:44 +0000
Newest: 2022-11-02 23:34:26 +0000

### Status report information ###

Generated at: 2022-08-09 14:27:01 +00:00
`

</details>

**Comment by ricardo** [comment]
This might be related to https://github.com/woocommerce/woocommerce/pull/34050

**Comment by jbordonado** [comment]
> The order total is $171.84 USD and we’re showing Refunded --$515.52 USD (i.e. 171.84 * 3)

This is not happening anymore with a recent zip built from `cot-main` branch: values are coherent with the order.
The original issue is still happening though: the status is stuck on "On Hold" instead of changing to "Refunded" after losing the dispute.
