### ISSUE TITLE
[GlobalStep] [Custom Order Tables] Order status fails to set as "On-hold" for purchasing a product using a dispute-specific test card on the "Woocommerce > Orders" page.

### ISSUE THREAD

**Issue by gglobalstep** [Automattic/woocommerce-payments#4554]
### Bug Description:
Order status fails to set as ["](https://envious-firefly.jurassic.ninja/cot-no-syncing/wp-admin/admin.php?page=wc-adminsite)On-hold" for purchasing a product using a dispute-specific test card on the "Woocommerce > Orders" page.

### Environment:
Woocommerce Version: WooCommerce 6.9.0
WooCommerce  Payments 4.6.0-test-2
WordPress version: v6.0.1

PC:
Windows 10
Chrome(Version 104.0.5112.81) 

### Steps To Reproduce:
1. Open the JN "[https://envious-firefly.jurassic.ninja/cot-no-syncing/wp-admin](https://envious-firefly.jurassic.ninja/cot-no-syncing/wp-admin/admin.php?page=wc-adminsite)".
1. Purchase a product using a dispute-specific test card on the front end.
1. Navigate to the order page as admin (WooCommerce > Orders)
1. Observe that the  Order status fails to set as "On-hold" for purchasing a product using a dispute-specific test card on the "Woocommerce > Orders" page.

### Actual Result:
Order status fails to set as "On-hold" for purchasing a product using a dispute-specific test card on the "Woocommerce > Orders" page.

### Expected Result:
Order status should be set as "On-hold" for purchasing a product using a dispute-specific test card on the "Woocommerce > Orders" page.

### Screenshot:

![#4554 1](https://user-images.githubusercontent.com/41110392/183677572-50a22934-29ab-4bb1-b7b6-fc777104fc09.png)

![#4554 2](https://user-images.githubusercontent.com/41110392/183677591-8a987da4-c3a9-4d27-bafb-ad2d466ba1c7.png)

*Isolating the problem (mark completed items with an [x]):*
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

<details>

`
### WordPress Environment ###

WC Version: 6.9.0
REST API Version: ✔ 6.9.0
WC Blocks Version: ✔ 8.1.0
Action Scheduler Version: ✔ 3.4.0
Log Directory Writable: ✔
WP Version: 6.0.1
WP Multisite: ✔
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache/2.4.54 (Unix) OpenSSL/1.0.2g
PHP Version: 7.4.30
PHP Post Max Size: 1 GB
PHP Time Limit: 30
PHP Max Input Vars: 5000
cURL Version: 7.47.0
OpenSSL/1.0.2g

SUHOSIN Installed: –
MySQL Version: 5.7.33-0ubuntu0.16.04.1-log
Max Upload Size: 1 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 6.9.0
WC Database Prefix: wp_6_
Total Database Size: 16.38MB
Database Data Size: 10.13MB
Database Index Size: 6.25MB
wp_6_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_6_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_6_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_6_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_6_woocommerce_order_items: Data: 0.05MB + Index: 0.02MB + Engine InnoDB
wp_6_woocommerce_order_itemmeta: Data: 0.17MB + Index: 0.19MB + Engine InnoDB
wp_6_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_6_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_6_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_6_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_6_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_6_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_6_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_6_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_6_actionscheduler_actions: Data: 1.52MB + Index: 1.17MB + Engine InnoDB
wp_6_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_6_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_6_actionscheduler_logs: Data: 1.52MB + Index: 0.58MB + Engine InnoDB
wp_6_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_6_comments: Data: 0.39MB + Index: 0.38MB + Engine InnoDB
wp_6_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_6_options: Data: 3.08MB + Index: 0.08MB + Engine InnoDB
wp_6_postmeta: Data: 1.52MB + Index: 1.98MB + Engine InnoDB
wp_6_posts: Data: 0.16MB + Index: 0.06MB + Engine InnoDB
wp_6_snippets: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_6_termmeta: Data: 0.05MB + Index: 0.03MB + Engine InnoDB
wp_6_terms: Data: 0.05MB + Index: 0.03MB + Engine InnoDB
wp_6_term_relationships: Data: 0.05MB + Index: 0.02MB + Engine InnoDB
wp_6_term_taxonomy: Data: 0.05MB + Index: 0.03MB + Engine InnoDB
wp_6_wc_admin_notes: Data: 0.05MB + Index: 0.00MB + Engine InnoDB
wp_6_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_6_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_6_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_6_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_6_wc_orders: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_6_wc_orders_meta: Data: 0.36MB + Index: 0.39MB + Engine InnoDB
wp_6_wc_order_addresses: Data: 0.08MB + Index: 0.03MB + Engine InnoDB
wp_6_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_6_wc_order_operational_data: Data: 0.08MB + Index: 0.03MB + Engine InnoDB
wp_6_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_6_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_6_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_6_wc_product_attributes_lookup: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_6_wc_product_download_directories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_6_wc_product_meta_lookup: Data: 0.05MB + Index: 0.09MB + Engine InnoDB
wp_6_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_6_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_6_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_6_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_blogmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_blogs: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_ms_snippets: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_registration_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_signups: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_site: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_sitemeta: Data: 0.06MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Data: 0.06MB + Index: 0.03MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB

### Post Type Counts ###

attachment: 12
page: 8
post: 2
product: 57
product_variation: 106
revision: 2
shop_coupon: 1
shop_order_placehold: 26
shop_subscription: 8
wp_global_styles: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ❌Error messages should not be shown to visitors.

### Active Plugins (11) ###

WooCommerce Stripe Gateway: by WooCommerce – 6.5.0
WooCommerce Payments Dev Tools: by Automattic –
WooCommerce Payments: by Automattic – 4.5.1
WooCommerce Subscriptions Core: by Automattic – 2.1.0
WooCommerce Subscriptions: by WooCommerce – 4.4.0
WooCommerce: by Automattic – 6.9.0-dev
WP phpMyAdmin: by Puvox.software – 5.2.0.7
NS Cloner - Site Copier: by Never Settle – 4.1.9.3
Code Snippets: by Code Snippets Pro – 3.2.0
WP Console: by Edi Amin – 2.3.1
WooCommerce Blocks: by Automattic – 8.1.0

### Inactive Plugins (5) ###

Companion Plugin: by Osk – 1.27
WooCommerce Beta Tester: by WooCommerce – 2.0.5
WooCommerce Smooth Generator: by Automattic – 1.0.4
WooCommerce Subscriptions Core: by Automattic – 2.1.0
WooCommerce Subscriptions CSV Importer and Exporter: by Prospress Inc – 2.1.0

### Settings ###

API Enabled: –
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
subscription (subscription)
variable (variable)
variable subscription (variable-subscription)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –
Enforce Approved Product Download Directories: ✔

### WC Pages ###

Shop base: #5 - /shop/
Cart: #6 - /cart/
Checkout: #7 - /checkout/
My account: #8 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Storefront
Version: 4.1.1 (update to version 4.1.2 is available)
Author URL: https://woocommerce.com/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Subscriptions ###

WCS_DEBUG: ✔ No
Subscriptions Mode: ✔ Live
Subscriptions Live URL: https://envious-firefly.jurassic.ninja/cot-no-syncing
Subscription Statuses: wc-active: 1
wc-on-hold: 6
wc-cancelled: 1

WooCommerce Account Connected: ❌ No
Report Cache Enabled: ✔ Yes
Cache Update Failures: ✔ 0 failure

### Store Setup ###

Country / State: United States (US) — California

### Subscriptions by Payment Gateway ###

Stripe: wc-on-hold: 1
WooCommerce Payments: wc-active: 1
wc-cancelled: 1
wc-on-hold: 5

### Payment Gateway Support ###

WooCommerce Payments: products
refunds
multiple_subscriptions
subscription_cancellation
subscription_payment_method_change_admin
subscription_payment_method_change_customer
subscription_payment_method_change
subscription_reactivation
subscription_suspension
subscriptions
subscription_amount_changes
subscription_date_changes
tokenization
add_payment_method

Stripe: products
refunds
tokenization
add_payment_method
subscriptions
subscription_cancellation
subscription_suspension
subscription_reactivation
subscription_amount_changes
subscription_date_changes
subscription_payment_method_change
subscription_payment_method_change_customer
subscription_payment_method_change_admin
multiple_subscriptions

### Admin ###

Enabled Features: activity-panels
analytics
coupons
customer-effort-score-tracks
experimental-products-task
experimental-import-products-task
experimental-fashion-sample-products
experimental-product-tour
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
wc-pay-promotion
wc-pay-welcome-page
wc-pay-subscriptions-page

Disabled Features: minified-js
new-product-management-experience
settings

Daily Cron: ✔ Next scheduled: 2022-08-10 04:09:10 +00:00
Options: ✔
Notes: 51
Onboarding: completed

### WooCommerce Payments ###

Version: 4.5.1
Connected to WPCOM: Yes
Blog ID: 209309424
Account ID: acct_1LRqQL2EmUoDpdCC

### Action Scheduler ###

Canceled: 73
Oldest: 2022-08-01 05:15:19 +0000
Newest: 2022-08-09 12:50:45 +0000

Complete: 4,052
Oldest: 2022-07-29 04:19:18 +0000
Newest: 2022-08-09 06:17:28 +0000

Failed: 3
Oldest: –
Newest: –

Pending: 2
Oldest: 2022-08-10 01:31:01 +0000
Newest: 2022-09-09 12:49:26 +0000

### Status report information ###

Generated at: 2022-08-09 14:35:12 +00:00
`

</details>

**Comment by jbordonado** [comment]
It could be related to #4151 

`order_id_from_meta_key_value` function seems to be used during the processing of `charge.dispute.created` webhook event

**Comment by jessy-p** [comment]
Closed via #4590 
Works on latest develop with COT enabled.
