### ISSUE TITLE
Non-prorated synced subscriptions don't result in synced WC Pay Subscription

### ISSUE THREAD

**Issue by james-allan** [Automattic/woocommerce-payments#4565]
### Describe the bug

When a merchant selects the **Never (charge the full recurring amount at sign-up)** synchronisation setting, synced subscription products aren't being synced to their anchor date in Stripe. 

![Screen Shot 2022-08-11 at 03 15 22](https://user-images.githubusercontent.com/8490476/184043939-b083afe4-9cf9-4ed2-9527-1f5e311f1bb1.png)

### To Reproduce

1. With WC Subscription (the extension inactive). 
2. Go to **WooCommerce > Settings > Subscriptions**
    1. Enable synchronisation
    2. Select `Never (charge the full recurring amount at sign-up)` **Prorate first payment** setting. 
4. Create a synced subscription product (See example screenshot below). 
5. Purchase that product and note the subscriptions first payment date. 
6. In the Stripe dashboard, view the subscription's billing period and note the next payment date isn't synced. 

<img width="1247" alt="Screen Shot 2022-08-11 at 11 09 02 am" src="https://user-images.githubusercontent.com/8490476/184048395-d97453ed-fb0d-410c-b82c-1a4e87775771.png">

### Actual behavior

With the **Never (charge the full recurring amount at sign-up)** setting enabled we incorrectly determine that the product "isn't" synchronised. This means we don't send the `trial_end` arg to Stripe when creating the subscription. 

From my short investigation I believe the problem stems from this [logic](https://github.com/automattic/woocommerce-payments/blob/4.5.1/includes/subscriptions/class-wc-payments-subscription-service.php#L712-L714). 

Because there is an upfront payment (non-proration), that `self::has_delayed_payment( $subscription )` returns `false` and so no trial end date is sent.

### Screenshots

<img width="1842" alt="Screen Shot 2022-08-11 at 11 03 02 am" src="https://user-images.githubusercontent.com/8490476/184047929-5bbeb015-da6f-48e3-bd15-5b084ac2623b.png">

### Expected behavior

In this situation a `trial_end` value should be sent to Stripe when creating the subscription to ensure the subscription created in Stripe is synced.

### Additional information

- Original report in Slack: p1660131760533269/1659720769.614509-slack-CGGCLBN58

**Comment by avantegarde** [comment]
@james-allan Ran into this issue today as well. 5463529-zd-woothemes

**Comment by joekercom** [comment]
Same issue here

**Comment by nicholasjeberlin** [comment]
5591504-zen

**Comment by Brianmitchtay** [comment]
Seeing this in 5824595-zen as well. 

Advising the user to set up the following workaround for new subscribers until a fix is released.

Workaround:

- Add the cost of an annual subscription to the product as a Sign-up fee  
- Set the setting for `Prorate First Renewal` to `Never (Do not Charge any Recurring Amount)` in the settings at **WP-Admin → WooCommerce → Settings → Subscriptions**
 
![LwvSaj.png](https://user-images.githubusercontent.com/45057772/210472165-1aaac2b4-1f22-42fb-b0f3-5cb67e7dba49.png)

![gaqVej.png](https://user-images.githubusercontent.com/45057772/210472166-128a39bb-5cf4-4696-a5ad-32eac8f4650d.png)

 
This will charge new sign-ups the correct amount at signup, and then synchronize their billing dates to the set date as expected.
