### ISSUE TITLE
[Authorizations] Implement Tracks metrics

### ISSUE THREAD

**Issue by mgascam** [Automattic/woocommerce-payments#4568]
### Description

Implement metrics to the improvements of the auth + capture flow that allows us to build funnels in Tracks tool.

### Acceptance criteria

Tracks metrics to implement:

* New Capture charge button click events on the Payments > Transaction details screen
* New Capture charge button click events on the authorizations list.
* Uncaptured list page views: this may be either new event or data added to existing view event

### Testing instructions

TBD

**Comment by mgascam** [comment]
> @mgascam could you please tell me, do we need more information to start working on this issue, can I move it for prioritization?

@zmaglica We have everything we need to start work so I think you can move it, thanks!

**Comment by kalessil** [comment]
@mgascam @elazzabi, do we have a PR (perhaps a draft) for this issue yet?

**Comment by elazzabi** [comment]
@kalessil the Tracks work needed to be done in 3 different places, and thus 3 different PRs. Given we didn't have the time to wait for merging and then start working on these events afterward, we decided to push the work to each PR individually. Here's a summary:

- New Capture charge button click events on the Payments > Transaction details screen ( `payments_transactions_details_capture_charge_button_click` event + payment intent id - [Commit in PR](https://github.com/Automattic/woocommerce-payments/pull/5006/commits/9a9bb5d5827e6fcafe1086b5c45d39ce00c54b57))
- New Capture charge button click events on the authorizations list. (`payments_transactions_uncaptured_list_capture_charge_button_click` event + payment intent id - [Commit in PR](https://github.com/Automattic/woocommerce-payments/pull/5006/commits/878c982f4423fd5b6639c2abe7e10bafa6fd51b4))
- Uncaptured list page views: this may be either new event or data added to existing view event (`page_view` even + path set to payments_transactions_uncaptured - [Commit in PR](https://github.com/Automattic/woocommerce-payments/pull/4982/commits/a368f50c0b89fbee16b9c9dc538948bcaed151e3))

**Comment by kalessil** [comment]
Gotcha, then I believe we can close the issue. 

Also, please actualize `https://github.com/Automattic/woocommerce-payments-server/blob/trunk/docs/Authorizations.md` to mention the tracks we introduced (in the same PR will be fine).
