### ISSUE TITLE
With COT enabled and no sync, related orders link on admin subscriptions list does not show the related orders

### ISSUE THREAD

**Issue by shendy-a8c** [Automattic/woocommerce-payments#4570]
### Describe the bug

With custom order table and without sync, on the admin subscriptions list page, the link to the related orders of certain subscription does not show the related orders.

### To Reproduce

1. Install WooCommerce with custom order table feature.
2. Enable custom order table.
3. Go to wp-admin > WooCommerce > Settings > Advanced > Custom data stores > select Use the WooCommerce orders tables and uncheck Keep the posts table and the orders tables synchronized.
4. Purchase a subscription.
5. Go to admin subscriptions list page (wp-admin > WooCommerce > Subscriptions).
6. Click on a link under the Orders column.

### Actual behavior

Related orders of the specified subscriptions do not show.

### Screenshots

![Screen Shot 2022-08-12 at 03 27 47](https://user-images.githubusercontent.com/73803630/184239127-e94af3ad-c177-4d48-a617-4cc9cbb359cb.png)

![Screen Shot 2022-08-12 at 03 28 57](https://user-images.githubusercontent.com/73803630/184239120-3e244246-3468-43a1-bc65-556f231690a4.png)

### Expected behavior

Related orders of the specified subscriptions should show.

### Additional context

This bug will be fixed in https://github.com/Automattic/woocommerce-subscriptions-core/issues/199.

**Comment by mattallan** [comment]
This issue was fixed in https://github.com/Automattic/woocommerce-subscriptions-core/pull/356 and included in `subscriptions-core` 5.2.0 which shipped in WooCommerce Payments 5.4.0. Closing
