### ISSUE TITLE
Product Variations without Prices Result in Critical Error on Product Page in PHP version 8.0

### ISSUE THREAD

**Issue by druesome** [Automattic/woocommerce-payments#4579]
### Describe the bug

When a variable product or subscription is created with no prices added to any variation, the product page results in a Critical error in PHP version 8.0.

### To Reproduce

1. On an Atomic site, go to Settings > Hosting Config and set PHP to version 8.0
2. Create a variable product or subscription and leave all prices empty
3. Publish Product
4. Visit the product page

### Actual behavior

The product page displays a critical error.  In CLI, the full error log looks like this:

```
PHP Fatal error:  Uncaught TypeError: Unsupported operand types: string + int in /srv/htdocs/wp-content/plugins/woocommerce-payments/includes/class-wc-payments-payment-request-button-handler.php:295
Stack trace:
#0 /srv/htdocs/wp-content/plugins/woocommerce-payments/includes/class-wc-payments-payment-request-button-handler.php(656): WC_Payments_Payment_Request_Button_Handler->get_product_data()
#1 /wordpress/core/6.0.1/wp-includes/class-wp-hook.php(307): WC_Payments_Payment_Request_Button_Handler->scripts('')
#2 /wordpress/core/6.0.1/wp-includes/class-wp-hook.php(331): WP_Hook->apply_filters(NULL, Array)
#3 /wordpress/core/6.0.1/wp-includes/plugin.php(476): WP_Hook->do_action(Array)
#4 /wordpress/core/6.0.1/wp-includes/script-loader.php(2156): do_action('wp_enqueue_scri...')
#5 /wordpress/core/6.0.1/wp-includes/class-wp-hook.php(307): wp_enqueue_scripts('')
#6 /wordpress/core/6.0.1/wp-includes/class-wp-hook.php(331): WP_Hook->apply_filters(NULL, Array)
#7 /wordpress/core/6.0.1/wp-includes/plugin.php(476): WP_Hook->do_action(Array)
#8 /wordpress/core/6.0.1/wp-includes/general-template.php(3042): do_action('wp_head')
#9 /wordpress/core/6.0.1/wp-includes/template-canvas.php(17): wp_head()
#10 /wordpress/core/6.0.1/wp-includes/template-loader.php(106): include('/wordpress/core...')
#11 /wordpress/core/6.0.1/wp-blog-header.php(19): require_once('/wordpress/core...')
#12 /wordpress/core/6.0.1/index.php(17): require('/wordpress/core...')
#13 {main}
  thrown in /srv/htdocs/wp-content/plugins/woocommerce-payments/includes/class-wc-payments-payment-request-button-handler.php on line 295
 
```

### Expected behavior

For the product page to load normally despite not having prices for variations set.

### Workarounds

Adding prices to all variations or downgrading to PHP version 7.4 resolves the error.  

### Relevant links

Slack: p1660540852249059-slack-C03TY6J1A

**Comment by kaushikasomaiya** [comment]
Similar error: 

> 2022-07-27T21:57:14+00:00 CRITICAL Uncaught TypeError: Unsupported operand types: string - string in /public_html/wp-content/plugins/woocommerce-payments/includes/class-wc-payments-payment-request-button-handler.php:268Stack trace:#0 /home1/hexagoo7/public_html/wp-content/plugins/woocommerce-payments/includes/class-wc-payments-payment-request-button-handler.php(656)

1. 5440801-zen
2. 5470382-zen

Unable to replicate this, but I suspect it is due to empty prices since var_dump on `wc_get_price_including_tax` returns a string on products with blank prices.

**Comment by kaushikasomaiya** [comment]
5479167-zen

**Comment by IliaDi** [comment]
5477606-zen

**Comment by kaushikasomaiya** [comment]
5486978-zen

**Comment by thelogicwizards** [comment]
> [5486978-zen](https://woothemes.zendesk.com/agent/tickets/5486978)

FYI: This user's situation is a bit different, in that their product variations already have set prices, though the exact same critical error is firing.

**Comment by thracefulton** [comment]
Another instance in 5494428-zen. As with the user mentioned above, I was unable to find any variable products missing prices, although the same `Unsupported operand types: string + int` version of the error is thrown with PHP 8.0.

**Comment by Greatdane** [comment]
5495919-zd-woothemes

**Comment by kaushikasomaiya** [comment]
In case of 5470382-zen, PHP 7.4 is outputting the following warnings when prices are not specified in products: 

> Warning: A non-numeric value encountered in /public_html/wp-content/plugins/woocommerce-payments/includes/class-wc-payments-payment-request-button-handler.php on line 274

> Warning: A non-numeric value encountered in /public_html/wp-content/plugins/woocommerce-payments/includes/class-wc-payments-payment-request-button-handler.php on line 274

> Warning: A non-numeric value encountered in /public_html/wp-content/plugins/woocommerce-payments/includes/class-wc-payments-payment-request-button-handler.php on line 301

**Comment by csmcneill** [comment]
Some discussion around this issue is occurring here: p1661023363251699-slack-C01B82V67DL

**Comment by thekingsprojects** [comment]
Another case here: 36609525-hc

They wanted a quick fix rather than having to go through their products right away, so switching to 7.4 helped them.

**Comment by helgatheviking** [comment]
Have a customer with what I think is this error.... WordPress.com hosting and PHP 8.0.22. They are using variations to suggest different prices plus one Name Your Price variation ( a common donation pattern). Is there an ETA on the patch for this?

**Comment by a-danae** [comment]
@helgatheviking This is in progress. You can find the latest updates in this thread p1661443140911449-slack-CGGCLBN58

**Comment by helgatheviking** [comment]
@a-danae I think that's a private slack thread. I only have access to the a8c marketplace vendors channel.

**Comment by vbelolapotkov** [comment]
FYI, another quick fix until patch is out could be disabling Apple/Google Pay on product pages.

**Comment by vbelolapotkov** [comment]
**Update.** 

We decided to hold a patch release for this problem to make sure we ship a proper fix. Until it's fixed, there are the following workarounds available:

1. Disable Apple Pay/Google Pay on product pages (WC Admin > Payments > Settings > Expess Checkout section > Customize). Or disable Apple Pay / Google Pay completely.
2. If applicable, set prices on products without price.
3. Downgrade PHP version from 8.0 to 7.4 if possible. In PHP 7.4 it will issue only warning.

**Comment by kaushikasomaiya** [comment]
5508417-zen

> 2022-08-26T00:04:07+00:00 CRITICAL Uncaught TypeError: Unsupported operand types: string - string in /home1/silaslac/public_html/wp-content/plugins/woocommerce-payments/includes/class-wc-payments-payment-request-button-handler.php:274

**Comment by kishor-wpm** [comment]
convert `$product_price` to float:

use `'amount'  => WC_Payments_Utils::prepare_amount( floatval($product_price) + $tax, $currency ),`

**Comment by daniyalahmadk** [comment]
Another case here: 5520516-zd 

It's not a variable product, but simple one.

**Comment by EjayhanFernandes** [comment]
Another case here: 5520112-zen. Asked the user to check their variable products to check if prices are missing. Also provided them the workaround to downgrade to PHP version 7.4.

**Comment by ariel-maidana** [comment]
Another case here: 5529501-zd-woothemes
