### ISSUE TITLE
Update documentation for custom deposits schedule changes

### ISSUE THREAD

**Issue by james-allan** [Automattic/woocommerce-payments#4591]
Part of the custom deposit schedule project - pdjTHR-1c8-p2

### Description

As part of the Custom deposit project we'll be updating various UIs and user flows around the deposits feature. This issue will act as a place to keep track of documation we will need to update once they ship.

--- 

### Documentation list

- [ ] [**_Instant Deposits with WooCommerce Payments_**](https://woocommerce.com/document/payments/instant-deposits/)
    - **PR:** https://github.com/Automattic/woocommerce-payments/pull/4588
    - **What?:** The instant deposit button has moved. The screenshots and documented steps will need updating. 
- [ ] **Remove duplication of deposit schedule**
     - I haven't got a conclusive list of impacted docs given all pages which include a screenshot of the Payments > Overview page are impacted.
     - **PR:** https://github.com/Automattic/woocommerce-payments/pull/4542
     - **What?:** The duplication of the deposit schedule on the **Payments > Overview** page has been removed. It now only includes the schedule (weekly, monthly, daily etc) in the block header, the deposit schedule in the Account details block will now only include "Automatic** if it's automatically scheduled. See PR for more details. I've included an example below.

| Before | After |
| - | - |
| <img width="400" alt="screen-shot-2022-06-16-at-9 37 08-am" src="https://user-images.githubusercontent.com/1527164/179665822-8d20219a-7914-4073-b9c3-7d54fe7e6da9.png"> | <img width="400" src="https://user-images.githubusercontent.com/1527164/179665282-086d918e-7daf-4734-b6ab-2f7e117d91c2.png" /> |

**Comment by thenbrent** [comment]
FYI @aheckler too

**Comment by aheckler** [comment]
Yep! Tracking this in my Trello board here: c/yr5qerxx-tr

Let me know if I can help in any way. :)

**Comment by aheckler** [comment]
@james-allan 

> I haven't got a conclusive list of impacted docs given all pages which include a screenshot of the Payments > Overview page are impacted.

Yeah, screenshots of that are probably sprinkled all over our docs. As best I can tell, there's no easy way find them all short of just going through the docs one by one. :( The good news is that updating screenshots of that is probably safe as a low priority item. (IMHO, the more substantive the change, the more important it is to get updated screenshots in the docs at release.)

Docs that will need updated for the new location of the instant deposit button:

- https://woocommerce.com/document/payments/instant-deposits/
- https://woocommerce.com/document/payments/faq/instant-payouts/

There might be one or two more, but those are the main ones.

**Comment by james-allan** [comment]
I've started a Google Doc to collaborate on the changes: [https://docs.google.com/document/d/1mODHkNwFJM8zZV](https://docs.google.com/document/d/1mODHkNwFJM8zZVZlCvXm2RHcQlpzki_9QNLlSHNtgxY/edit?usp=sharing). It's very much empty at this point but will be contributing to it today.

**Comment by aheckler** [comment]
Added `https://woocommerce.com/document/payments/faq/instant-payouts/` to the above Google Doc for an updated screenshot.

EDIT: Added a few more places we'll need docs updates as well.

**Comment by james-allan** [comment]
I've updated the various docs outlined in the Google doc above and hit publish on this new page: [How do I change my deposit schedule with WooCommerce Payments?
](https://woocommerce.com/document/payments/#section-11).

I can't find this [FAQ page](https://woocommerce.com/document/payments/faq/) in the WooCommerce.com docs edit list. I planned on editing it to add the new doc to the "Getting paid" section. @aheckler are you able to edit the FAQ page?

**Comment by aheckler** [comment]
DM'ed you on Slack about this. :)

**Comment by james-allan** [comment]
All the doc updates have now been made. I'm going to close this issue now. Thanks for your help @aheckler :)
