### ISSUE TITLE
Duplicated Tracks events when registering a new platform user.

### ISSUE THREAD

**Issue by malithsen** [Automattic/woocommerce-payments#4599]
### Describe the bug
`woocommerceanalytics_platform_checkout_registered` event that fires when registering a new platform user appears to be duplicated. When querying the Tracks table in db, in certain instances, there are two or more entries for the above record in the same second. These duplicates are present in both production and test events. 

### To Reproduce

This doesn't happen on all occasions. The following steps are to trigger the event being duplicated.

1. Make sure platform checkout is enabled.
2. As a customer, add a product to your cart
3. Go to the checkout page and enter an email address that doesn't already exist in platform checkout
4. Check the "Remember your details?" checkbox that says "Save my information for faster checkouts"
5. Place the order

This sometimes results in duplicated event records in the Tracks db. Check the linked slack thread for the Hue query.

### Actual behavior

`woocommerceanalytics_platform_checkout_registered` are sometimes duplicated.

### Expected behavior

`woocommerceanalytics_platform_checkout_registered` only a single event should be recorded when a user is registering to WooPay.

### Additional context

Slack Thread: p1660679217892489-slack-C02CCT3F1QA

**Comment by zmaglica** [comment]
I was unable to reproduce this issue on my end. But, we could add additional checks to prevent duplicate events you listed in the issue description @malithsen

**Comment by LCmry** [comment]
Hi @malithsen is this still an issue?

**Comment by malithsen** [comment]
@LCmry Thanks for the ping and thanks @zmaglica for having a look.

I rechecked recent `_checkout_registered` Tracks events we've received and no longer see any duplicates. Closing.
