### ISSUE TITLE
Incompatibility with Table Rate Shipping when rates are calculated `per item` or `per line item`,

### ISSUE THREAD

**Issue by Brianmitchtay** [Automattic/woocommerce-payments#4609]
### Describe the bug

With WooCommerce, WooCommerce Payments, and Table Rate Shipping active, when the table rate shipping method has its `calculation type` set to calculate rates `per item` or `per line item`, no matter the configured rates, only $1 is charged for shipping at checkout with the table rate method

### To Reproduce

1. On a test site, install the latest versions of Table Rate Shipping, WooCommerce Payments, and WooCommerce
2. Set up a shipping zone with the table rate method, create some rates and set the method to calculate `per item` or `per line item`
3. Create some products and a put together a cart that matches one of your non $1 table rates
4. Go to checkout and see that shipping costs are only $1 with the table rate method.
5. Disable WooCommerce Payments and see that the rates return correctly.

### Actual behavior

When WooCommerce Payments is active, only a $1 rate is returned.

Testing with another payment gateway, Stripe, rates return correctly.

### Screenshots

<img width="1381" alt="TRS settings-Screen Shot 2022-08-19 at 17 03 45" src="https://user-images.githubusercontent.com/45057772/185723442-b0f6b0ea-5131-46b5-bc00-3506a5d6d7e5.png">
<img width="668" alt="WCPay disabled, rates returnedScreen Shot 2022-08-19 at 17 02 30" src="https://user-images.githubusercontent.com/45057772/185723443-34df744d-d4a3-4554-9bc9-7382f8e76ccd.png">
<img width="668" alt="WCPay enabledScreen Shot 2022-08-19" src="https://user-images.githubusercontent.com/45057772/185724695-13f356a6-1ea9-421b-9f8f-c395f6238964.png">

### Expected behavior

I expected Table Rate Shipping to return the correct rates when WooCommerce Payments is active.

### Desktop (please complete the following information):

* OS: [macOS Monterrey 12.5]
* Browser [Chrome]
* Version [Version 104.0.5112.101 (Official Build)]

### Additional context

This issue was originally discovered in 5492385-zen
It's probably worth mentioning that the user in that case said the issue started with the latest update of WooCommerce.

**Comment by csmcneill** [comment]
I am fairly positive that this is a WCPay issue and not a TRS issue.

The issue persists while WCPay is activated—even if it isn't enabled as a payment method:

![Markup on 2022-08-19 at 22:52:30](https://user-images.githubusercontent.com/82999806/185727914-3e50b4eb-822b-4096-864e-9e07a47ca7d3.png)

However, once I deactivate WCPay, the issue is no longer present:

![Markup on 2022-08-19 at 22:53:37](https://user-images.githubusercontent.com/82999806/185727940-0243bfde-5806-4246-b93a-09595dad0217.png)

It is possible that [this issue](https://github.com/Automattic/woocommerce-payments/issues/4526) is related.

**Comment by thisissandip** [comment]
5526596-zen

**Comment by marissaexplores** [comment]
[5562299-zen](5562299-zd-woothemes)
The merchant disabled multi-currency in WCPay and that resolved the table rate issue for them.

**Comment by zoemyers** [comment]
5575081-zen

**Comment by jbordonado** [comment]
I forgot to mention it, but this will be released with WCpay 4.8.0 scheduled on Sep 28.
Hopefully all these cases will be solved then.
