### ISSUE TITLE
Support Platform Checkout on Checkout Blocks for existing users.

### ISSUE THREAD

**Issue by Mayisha** [Automattic/woocommerce-payments#4613]
### Description
Currently, if the checkout page is using shortcode-checkout only then Platform Checkout is supported and an existing Platform Checkout user is prompted to verify via OTP. Similar support needs to be added when the checkout page is using Checkout Blocks too.

### Acceptance criteria
- Run checks for an existing platform checkout user when a valid email is provided.
- Show OTP modal for the existing user and allow the user to checkout via Platform Checkout on successful OTP verification.

**Comment by zmaglica** [comment]
@Mayisha hi there. Could you please tell me, did you start to work on this issue?

**Comment by Mayisha** [comment]
Hi @zmaglica . I have started working on this. Here is the PR https://github.com/Automattic/woocommerce-payments/pull/4611

**Comment by zmaglica** [comment]
Thank you.
