### ISSUE TITLE
On-boarding disabled "notify" text could be misleading

### ISSUE THREAD

**Issue by jrodger** [Automattic/woocommerce-payments#462]
In #402 we notify the user if on-boarding has been disabled with this text:

"Thank you for installing and activating WooCommerce Payments! We've temporarily paused new account creation. We'll notify you when we resume!"

@dechov noted that the "We'll notify you when we resume!" could imply that we would pro-actively notify the user when we resume on-boarding. I agree that it could be misleading.

I'm creating this issue so that this discussion doesn't get lost.

The main question is likely, how much time do we want to spend refining the text for something we're hoping never to use?

**Comment by vbelolapotkov** [comment]
Closing as not relevant anymore.
