### ISSUE TITLE
[COT] Order Number not displayed on Transactions screen when COT enabled

### ISSUE THREAD

**Issue by jessy-p** [Automattic/woocommerce-payments#4631]
### Describe the bug
When COT is enabled and WooCommerce Orders tables are being used, without sync.
In Payments > Transactions, the Order Number is displayed as N/A.

If sync with Posts table, the order number is restored.

### To Reproduce
1. Use WC 6.9 and ensure COT enabled (Orders table is used)
2. Place an order
3. Check Order Number in Payments > Transactions and navigate to the order 

### Actual behavior
Order number is N/A

### Screenshots
<img width="1141" alt="image" src="https://user-images.githubusercontent.com/32092402/186345261-1dd7aff3-332f-4d33-8873-ef7708b8fc0a.png">

### Expected behavior
Order number should be displayed and link should navigate to the order page

### Additional context
Intermittently, (while switching between Orders and Posts table) observed the Order number was present but the link to Order page broken.

**Comment by deepakpathania** [comment]
Blocked on [this core issue](https://github.com/woocommerce/woocommerce/issues/34228).

**Comment by deepakpathania** [comment]
With the [latest build](https://github.com/woocommerce/woocommerce/actions/runs/3036281249) (based on `trunk`), I can no longer reproduce this issue, will wait for another confirmation before closing.

**Comment by deepakpathania** [comment]
Closing after confirmation from another member that it can no longer be reproduced.
