### ISSUE TITLE
'wc is not defined' error in the browser console on checkout when buying a free product

### ISSUE THREAD

**Issue by a-danae** [Automattic/woocommerce-payments#4635]
### Describe the bug
There's an error in the browser console on the checkout page when purchasing a free product.

### To Reproduce

1. As a merchant, create a product with a $0 price
2. As a merchant, confirm WooPay is enabled
3. As a shopper, add this free product to your cart and proceed to check out
4. On the checkout page, open the browser console
5. Notice there's an error with the message `Uncaught ReferenceError: wc is not defined`

### Actual behavior
There's an error in the console when purchasing a free product.

### Expected behavior
I wouldn't expect having errors in the console in this scenario.

**Comment by RadoslavGeorgiev** [comment]
@a-danae this is happening because there is no need for payment, and WCPay is not loaded at all in that scenario at the checkout page. In order to fix this bug, there are two options:

1. Don't load WooPay as well, because there is nothing to pay for.
2. Load WCPay anyways, even though it is not going to be used.

So the question is: Do we even want to load WooPay for orders without a positive price?

**Comment by RadoslavGeorgiev** [comment]
@a-danae could you please respond to the last question?

**Comment by a-danae** [comment]
@RadoslavGeorgiev for sure. I completely missed that, sorry. 

I'm inclined toward option 1, as I can't think of a scenario where having WooPay/WCPay would be needed for orders without a positive price. I was first thinking of free-trial subscriptions, but the `Uncaught ReferenceError: wc is not defined` doesn't show up. So it looks like that scenario is still considered to have a positive price.

**Comment by RadoslavGeorgiev** [comment]
> So it looks like that scenario is still considered to have a positive price.

I think this is handled by `$order->needs_payment()`, not the order price. That was just a side-note though.

Would you mind opening another issue for WooPay, which should prevent it from being loaded in such scenarios?

**Comment by a-danae** [comment]
> I think this is handled by $order->needs_payment(), not the order price. That was just a side-note though.

Noted, thanks for clarifying!

> Would you mind opening another issue for WooPay, which should prevent it from being loaded in such scenarios?

Sure, glad to. I was mid-way creating it but I'm not sure if I got you right. Did you mean creating a separate issue in the WooPay repo? I created it in this one because it looks like here's where we handle whether WooPay should be enabled, like in [this method](https://github.com/Automattic/woocommerce-payments/blob/develop/includes/platform-checkout/class-platform-checkout-utilities.php#L25), for example. 

But I may be getting you wrong or missing something. If so, would you please explain further what we should cover in that other issue for WooPay?

**Comment by RadoslavGeorgiev** [comment]
Actually here's good, I guess we just needed to switch from `category: core` to `category: projects`, the component label is already in place. Nothing more to do besides fixing the issue :)

**Comment by a-danae** [comment]
Gotcha. Cool 🙂

**Comment by a-danae** [comment]
Same symptom, different scenario:

- Enable [Conditional Shipping and Payments](https://woocommerce.com/products/conditional-shipping-and-payments/)
- Restrict WooCommerce Payments when Cart items count is < 2
- Add a product to the cart and proceed to checkout
- You'll see this error in the console 

This might be solved in the same PR that addresses the case from this issue or might require a separate one. Leaving it up to the author depending on the approach we'll take there.

cc @alefesouza because you have an open PR for this issue.

**Comment by alefesouza** [comment]
The problem doesn't occur anymore, apparently fixed by #4638.
