### ISSUE TITLE
CHF currency shown in ASCII in the Payments Overview screen

### ISSUE THREAD

**Issue by ralucaStan** [Automattic/woocommerce-payments#4664]
### Describe the bug
On the Payments Overview screen the CHF currency is shown in ASCII Code.
This does not happen when the WC Payments account is set up in Euro.

### To Reproduce
1. Set up a WC Payments account that has as currency the Swiss franc (CHF)

1. Go to the Payments Overview screen
2. Scroll down to Swiss francs balance box
3. Notice the weird characters before the amount

### Actual behavior
The currency appears as `&#67;&#72;&#70;`

### Screenshots

<img width="705" alt="Screenshot 2022-08-31 at 15 52 58" src="https://user-images.githubusercontent.com/1628454/187704626-f492032c-d6d7-4c56-b1f6-629e1178826a.png">

### Expected behavior

The currency should appear as CHF

**Comment by zmaglica** [comment]
Confirmed with the latest version of WooCommerce Payments plugin.

**Comment by deepakpathania** [comment]
This is coming from core directly from [this line](https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce/includes/wc-core-functions.php#L696) when we try to populate the `symbol` [here](https://github.com/Automattic/woocommerce-payments/blob/develop/includes/admin/class-wc-payments-admin.php#L444). We can either ask core folks to look at it or update the `short_symbol` for `CH` in `i18n/locale-info.php` but not sure if that is the right way to handle this. Any thoughts on this?

**Comment by amElnagdy** [comment]
5581720-zen
