### ISSUE TITLE
Add payment methods/gateways icon to checkout page

### ISSUE THREAD

**Issue by frosso** [Automattic/woocommerce-payments#4666]
### Description

There is a desire from UX to add the icons for payment methods to the checkout page.
The icon can be displayed next to the payment method's name, leveraging WooCommerce's default behavior, in order to maximize theme compatibility.

As an additional step, displaying the icon could be a preference that can be enabled on the WooCommerce Payments settings page.

### Acceptance criteria

- For each gateway displayed at checkout, its corresponding icon is displayed
- Valid for both UPE and non-UPE behavior
- "Popular payment methods" gateway (which corresponds to the UPE for _all_ payment methods) does not show an icon (there would be too many, otherwise)
- (optional) A new setting on the WC Payments settings allows to enable/disable the icon display behavior at checkout
  - The display of the icon is disabled by default for old installations, to increase compatibility
  - The display of the icon is enabled by default for new installations

### Designs

![Screen Shot 2022-08-31 at 9 05 47 AM](https://user-images.githubusercontent.com/273592/187725850-8e2be385-0912-4fbf-b632-066264c98502.png)

### Dev notes

The `WC_Payment_Gateway` has a `$icon` public member (and a `get_icon()` public method) that can be leveraged to display the gateway's icon on the checkout page.

### Additional context

paJDYF-58k-p2#comment-13580

**Comment by harriswong** [comment]
This also needs to apply to the multiple UPE project.

**Comment by rogermattic** [comment]
Hey @frosso !
Just adding this [Figma link here](https://www.figma.com/file/Yy1WqI163cKRcnANjHDb5i/WCPay%2FStripe-Assets---Shared-components-library?node-id=3%3A5433) for the reference as it contains all the payment method icons assets we have.

**Comment by bborman22** [comment]
I just wanted to clarify something on this issue in case I'm missing some additional context coming in a bit late. This request to add icons is only relevant to multiple UPE set up correct? Since the only way to add these additional payment methods through WCPay is through UPE and the default UPE would have them all grouped under the "Popular payment methods" heading, the only way WCPay adds a row for these additional payment methods is through multiple UPE. Is that train of thought and conclusion correct?

**Comment by frosso** [comment]
@bborman22 AFAIK, the icons should be added to both the UPE payment method and to the other non-UPE payment methods.

@rogermattic @elizaan36 is this accurate?
I created this ticket as a follow up from paJDYF-58k-p2#comment-13580

**Comment by elizaan36** [comment]
hey @frosso @bborman22  👋

Yes, this would be ideal. For example, if the merchant added Afterpay and PayPal as APMs they could show up in the list with the associated icon. I don't consider it a blocker for the project but I think it would look funny if some payment methods have icons and others don't.

<img width="607" alt="image" src="https://user-images.githubusercontent.com/5121465/195186042-8da55014-62eb-4aa6-9b32-720c70843006.png">

**Comment by bborman22** [comment]
@elizaan36 Thanks for that confirmation! I was able to get the following working on my PR #4860 with some screenshots if you wanted to take a look. That was with the Storefront theme and I'd say the only major difference is the icons are all right aligned. This was just using the built in WooCommerce payment method icon and so any theme should be compatible as there isn't anything custom going on.

**Comment by elizaan36** [comment]
Nice @bborman22 ! Right aligned is even better, I was under the impression we had to keep the icon to the right of the payment method.

**Comment by bborman22** [comment]
Great! The PR was merged into the multiple UPE branch for now, so will be getting rolled out with that feature when the time comes. I'll close this issue for now since that change has been merged into a larger move.
