### ISSUE TITLE
Add critical testing flows for manual testing

### ISSUE THREAD

**Issue by jessy-p** [Automattic/woocommerce-payments#4667]
### Description

Manual Critical Testing flows for the WooCommerce Payments plugins are documented [here](https://github.com/Automattic/woocommerce-payments/wiki/Testing-instructions-for-critical-flows) and tested every week. 

While analysing past incident reports (pcreKM-1bp-p2) , we identified that adding some critical testing flows can improve our ability to prevent incidents. Some such paths are conflict testing with popular plugins used alongside WooCommerce Payments, testing with popular non-USD currencies and countries, etc. Any such critical paths which cannot be automated, can be added to the [manual critical testing flows](https://github.com/Automattic/woocommerce-payments/wiki/Testing-instructions-for-critical-flows). This issue is created to find and list all such manual critical testing flows.

### Acceptance criteria
- Manual critical testing flows identified and listed.

### Additional context
pcreKM-1bp-p2

**Comment by vbelolapotkov** [comment]
Closing, since it's old and not relevant in the current context.
