### ISSUE TITLE
Stripe Link is available for non-US accounts when UPE is enabled

### ISSUE THREAD

**Issue by csmcneill** [Automattic/woocommerce-payments#4668]
### Describe the bug
Stripe Link is only available for US accounts. However, when UPE is enabled, non-US accounts can enable Stripe Link.

### To Reproduce

1. Spin up a new JN site.
2. Enable dev mode.
3. Create a new account in a country based outside the US.
4. Navigate to **Payments > Settings**.
5. Note that Stripe Link is not an option.
6. Enable UPE.
7. Note that Stripe Link is now available.
8. Disable UPE.
9. Stripe Link is still an option?
10. Try to enable Stripe Link and save the settings; an error will be displayed.
11. Reload the page—Stripe Link is no longer available.

### Actual behavior
Stripe Link can be enabled on sites that aren't based in the U.S.; some users report that this can lead to errors on checkout such as:

```
An error was encountered when preparing the payment form. Please try again later.
```

I cannot reproduce these checkout errors.

### Screenshots

US account:

![Markup on 2022-08-31 at 11:08:42](https://user-images.githubusercontent.com/82999806/187726559-7d5191d1-e466-4424-9181-d44603418482.png)

CA account:

![Markup on 2022-08-31 at 11:10:23](https://user-images.githubusercontent.com/82999806/187727060-f317146d-a804-45f5-8c8e-9671ceadc2a8.png)

![Markup on 2022-08-31 at 11:09:55](https://user-images.githubusercontent.com/82999806/187727043-88d6d10f-d224-46c6-8abf-9a6ebc26d928.png)

### Expected behavior
Stripe Link should only be an option for U.S. accounts—regardless of whether or not UPE is enabled.

### Additional context

5504970-zen

**Comment by aheckler** [comment]
I can replicate the checkout page errors.

**Comment by csmcneill** [comment]
5504970-zen also notes that Stripe Link was automatically enabled for them, which means that they had to disable Stripe Link in their settings to resolve the issue.

I flagged this in p1661963196771029-slack-CGGCLBN58 to determine if this is important enough to tackle in a 4.7.1 patch release.

**Comment by kalessil** [comment]
@csmcneill, to double check: are steps to reproduce for CA-account?

EDIT: `Create a new account in a country based outside the US.` that clarifies.

**Comment by csmcneill** [comment]
> @csmcneill, to double check: are steps to reproduce for CA-account?
> 
> EDIT: `Create a new account in a country based outside the US.` that clarifies.

While I only tested with a CA account, @darcie noticed Stripe Link was an available option if UPE was enabled for a UK account (5516674-zen).

**Comment by kalessil** [comment]
Thanks!

**Comment by csmcneill** [comment]
Encountered this in 5548463-zen. It broke checkout for the user, and we were only able to discern that this issue as at play here because of the following error on a failed payment:

>
A payment of $79.90 USD failed to complete with the following message: Error: The payment method type "link" is invalid. Please ensure the provided type is activated in your dashboard (https://dashboard.stripe.com/account/payments/settings) and your account is enabled for any preview features that you are trying to use.

On further investigation, I found the following console error:

```
IntegrationError: In order to create a payment element, you must pass a valid PaymentIntent or SetupIntent client secret when creating the Elements group.
```

**Comment by csmcneill** [comment]
Likely 5549035-zen
