### ISSUE TITLE
Identify additional automated testing flows

### ISSUE THREAD

**Issue by jessy-p** [Automattic/woocommerce-payments#4669]
While analysing past incident reports ([pcreKM-1bp-p2](pcreKM-1bp-p2)), we identified that we can expand our automated testing to prevent incidents e.g. E2E testing for additional currencies. This issue is created to identify and list all such automated testing flows that we should create. 

### Acceptance criteria
- Automated testing flows identified and issues created to work on them.

### Additional context
[pcreKM-1bp-p2](pcreKM-1bp-p2)
Some E2E test scenarios [have already been identified and available in backlog](https://github.com/Automattic/woocommerce-payments/issues?q=is%3Aissue+is%3Aopen+E2E+label%3A%22category%3A+e2e%22)

**Comment by vbelolapotkov** [comment]
Closing this one. It's very old, and that task doesn't make sense to me anymore. Individual issues created as part of the p2 discussion are ok.
