### ISSUE TITLE
Searching subscriptions is slow for merchants with a large number of subscriptions

### ISSUE THREAD

**Issue by Jinksi** [Automattic/woocommerce-payments#4695]
### Describe the bug

> **Note**
> This is a placeholder issue for https://github.com/Automattic/woocommerce-subscriptions-core/issues/183.

The Subscriptions search in **wp-admin → WooCommerce → Subscriptions** is very slow for merchants who have a large number of subscriptions. For example, searching through ~30,000 subscriptions can take as much as 30 seconds.

![image](https://user-images.githubusercontent.com/3147296/176832794-5c19b831-fde0-4a11-a049-4b795747313d.png)

## To Reproduce

1. Generate a large number of subscriptions (method TBC).
2. Navigate to the wp-admin page **WooCommerce → Subscriptions**.
3. Execute a search using the search field in the top-right of the page, e.g. "john".
4. Wait for the results and observe the duration of the query using [Query Monitor](https://wordpress.org/plugins/query-monitor/).  Look for the query called by [`WCS_Subscription_Data_Store_CPT::search_subscriptions()`](https://github.com/Automattic/woocommerce-subscriptions-core/blob/2a0654bf0385cc3e5b097943aea5589e843b05d0/includes/data-stores/class-wcs-subscription-data-store-cpt.php#L446).

### Expected behavior

The search query that is called by [`WCS_Subscription_Data_Store_CPT::search_subscriptions()`](https://github.com/Automattic/woocommerce-subscriptions-core/blob/2a0654bf0385cc3e5b097943aea5589e843b05d0/includes/data-stores/class-wcs-subscription-data-store-cpt.php#L446) should take as little time as is reasonably possible.

### Actual behavior

The search query that is called by [`WCS_Subscription_Data_Store_CPT::search_subscriptions()`](https://github.com/Automattic/woocommerce-subscriptions-core/blob/2a0654bf0385cc3e5b097943aea5589e843b05d0/includes/data-stores/class-wcs-subscription-data-store-cpt.php#L446) takes longer than is reasonably possible.

**Comment by mattallan** [comment]
This issue will be fixed in Subscriptions Core, not WooPayments.

Closing this issue as it's no longer relevant to WooPayments because of our Subscriptions Primary Offering project: peNR48-2u-p2
