### ISSUE TITLE
[Manual deposits] Deposit Scheduling: Merchants can select manual schedule.

### ISSUE THREAD

**Issue by brucealdridge** [Automattic/woocommerce-payments#4696]
### Description

#4464 added the ability for merchants to choose an automatic schedule for deposits (daily, weekly, monthly) but to meet the WCPay 4.7 release window the ability for a merchant to select a manual schedule was descoped.

Add a set of controls to the Payments → Settings page which allows the merchant to change their deposit schedule from an automatic schedule to manual.

<img width="1033" alt="Deposits section" src="https://user-images.githubusercontent.com/1527164/199891631-13dde84e-94af-4b3b-ae80-26216bb058dd.png">

### Acceptance criteria

- When `Automatic` is selected, the automatic schedule options are available (Daily, Weekly, Monthly)
- When `Manual` is selected the automatic schedule options are disabled (but still visible).
- The "Deposit schedule" controls are implemented as per the designs W8FHz6thdADIqhlPlBo4Mf-fi-1718%3A77943
- When the merchant saves their settings via the "Save changes" button, their deposit schedule is updated in Stripe via WCPay Server as requested.
- The "Learn more" links that appear in the helper text link to https://woocommerce.com/document/payments/faq/change-deposit-schedule/

**Post-release:** Add user docs for this feature to https://woocommerce.com/document/payments/

### Designs

W8FHz6thdADIqhlPlBo4Mf-fi-1718%3A77943

### Testing instructions

TBC

### Additional context

Project thread: pdjTHR-1c8-p2
PRD: pdjTHR-1bY-p2

**Comment by aprea** [comment]
I have reopened and moved this issue back to "to do" as we are reverting the original PR here → https://github.com/Automattic/woocommerce-payments/pull/5050

**Comment by Jinksi** [comment]
Closing this as stale – this will be revisited in a future project.
