### ISSUE TITLE
StripeLink: no token is saved for subscription orders

### ISSUE THREAD

**Issue by dpaun1985** [Automattic/woocommerce-payments#4703]
### Describe the bug

When ordering a subscription product, the payment token is saved in the database.

Context: p1662348099755489-slack-C7U3Y3VMY
### To Reproduce

1. Create an order with a subscription product
2. Pay it with Link payment method
3. The payment token is not saved in the database.

**Comment by nicdwilson** [comment]
In 5519127-zen this resulted in the following error

```
CRITICAL Uncaught Exception: Invalid or missing payment token fields. in [redacted]/html/wp-content/plugins/woocommerce/includes/data-stores/class-wc-payment-token-data-store.php:44
#0 /html/wp-content/plugins/woocommerce/includes/class-wc-data-store.php(169): WC_Payment_Token_Data_Store->create(Object(WC_Payment_Token_CC))
#1 /html/wp-content/plugins/woocommerce/includes/abstracts/abstract-wc-data.php(218): WC_Data_Store->create(Object(WC_Payment_Token_CC))
#2 /html/wp-content/plugins/woocommerce-payments/includes/class-wc-payments-token-service.php(77): WC_Data->save()
```

**Comment by dpaun1985** [comment]
From the docs [here](https://woocommerce.com/document/payments/subscriptions/#section-7)
> it is only available to US merchants for debit and credit card payments

Should we have Link enabled also for subscriptions ? 

cc @kalessil

**Comment by kalessil** [comment]
@dpaun1985: Link has a pre-requisite of card payments being enabled and merchants being from US, so my understanding is that Link always will be using card payment. If this is correct, then we need subscriptions integration to work properly.

PS: we'll need to update our docs for Link to mention subscriptions support.

**Comment by aheckler** [comment]
@kalessil The WC Pay doc for Stripe link ([here](https://woocommerce.com/document/payments/woocommerce-payments-stripe-link/)) does not mention subscriptions at all currently. You're saying we should update it to mention that it supports subscriptions after 4.9.0 is released?

**Comment by kalessil** [comment]
@aheckler, nope I was referencing internal dev-docs used for know-how sharing and transfer.
