### ISSUE TITLE
PHPCS errors on WooCommerce.com

### ISSUE THREAD

**Issue by thenbrent** [Automattic/woocommerce-payments#471]
Deployments to WooCommerce.com go through the Product Build Server. This applies PHPCS. The zip file is currently failing PHPCS validation, with these [errors](https://product-build.woocommerce.com/v1/?action=get-report&secret=3f9c3b6785ef5b59ea775e548ffec7aed0.53839338&queue_item_id=221546). (Screenshot in case that URL is transient: https://d.pr/i/0YhVwJ).

I've been able to deploy the beta by enabling the **PBS Queue Legacy Check** setting on the WooCommerce.com product. That will continue to work for future releases, so these fixes are not high priority item.

**Comment by vbelolapotkov** [comment]
Not relevant with current deployment process.
