### ISSUE TITLE
Remove deprecated deposits_status account key from Account Status (changed WCPay Server API response)

### ISSUE THREAD

**Issue by brucealdridge** [Automattic/woocommerce-payments#4710]
### Descrption

`deposits_status` key in has been deprecated and should no longer be used. It has been replaced by `deposits.status`.
This is alongside a change to the WCPay server response also grouping deposit-based information under a `deposits` key.

https://github.com/Automattic/woocommerce-payments/blob/6e7607586b17f255b80d0ef9f21f103501ece6fd/includes/class-wc-payments-account.php#L195-L196

**Comment by haszari** [comment]
> NB: This issue is currently blocked due to downstream dependencies

@brucealdridge is it still blocked? If so can you add details of the blocker inline so this issue is self-contained.

I'm assuming there's no blocker and we can handle this as maintenance (and we should prioritise) – let me know your thoughts 🙌

**Comment by brucealdridge** [comment]
> @brucealdridge is it still blocked? If so can you add details of the blocker inline so this issue is self-contained.

Pre-deploy checks originally caught this issue and these are somewhat hidden (private) from the normal flows and checks (unit tests, E2E.) It was just one of these tests that had hardcoded expectations around server responses. These have now been updated.

So the blocker has been removed and we should be 👍 to proceed on this.

**Comment by haszari** [comment]
> Pre-deploy checks originally caught this issue and these are somewhat hidden (private) from the normal flows and checks (unit tests, E2E.)

Gotcha, thanks for clarifying – this was blocked by a pre-deploy integration test (tumblr something?) that is not in PR checks, and that breakage has been fixed.

**Comment by shendy-a8c** [comment]
Because this issue's PR, https://github.com/Automattic/woocommerce-payments/pull/8376, broke an integration test (read context here p1710976497541019-slack-C02BW3Z8SHK), I created a revert PR https://github.com/Automattic/woocommerce-payments/pull/8432.

We need to re-apply the removal of `depositsStatus` key once the test is fixed, so I reopened this issue.
