### ISSUE TITLE
Error passing level3 data when order has only shipping fee, without product

### ISSUE THREAD

**Issue by thracefulton** [Automattic/woocommerce-payments#4738]
### Describe the bug
When a merchant creates an order containing no products, and only uses `Add shipping` to attempt to charge a shipping fee,  WooCommerce Payments is unable to process payment attempts. 

Customers report seeing JSON errors or `The string did not match the expected pattern.` error at checkout, and the following error is present in the payment intent log:

```
400 ERR A request to update a PaymentIntent pi_3LerMv2EhQJVb2mF0FpXTsq6 failed
\"error\": {

    \"message\": \"Invalid string: zero-cost-...o-cost-fee; must be at most 12 characters\",

    \"param\": \"level3[line_items][0][product_code]\",
```

### To Reproduce
1. Create a new order from the admin dashboard. 
2. Do not add any products.
3. Enter a shipping cost (any amount) using the `Add shipping` option.
4. Set the payment method to `WooCommerce Payments` and attempt to pay via the `Customer Payment Page`.

### Workaround
To bypass this issue, you can add the shipping cost using `Add fee` instead of `Add shipping`. With no products present, using only `Add fee` allows payment to process as expected without throwing any errors.

### Actual behavior
When payment is attempted, customers are shown an error message and cannot proceed past the `Place Order` button on the checkout page, even after repeated attempts. The order remains `Pending Payment` or `Failed`

### Screenshots
Example of an order that produces the error:
![93svgo.png](https://user-images.githubusercontent.com/88570946/189440010-359ef904-ba9b-4082-86d0-d433aa54d62c.png)

Workaround screencast:
![26JCFU.gif](https://user-images.githubusercontent.com/88570946/189440328-a55a5fda-412e-4479-a9ae-82eb8f861e43.gif)

### Expected behavior
The merchant who reported this has used this method of charging customers for shipping costs with prior versions of WooCommerce Payments. The expected behavior is that payment would succeed.

### Additional context
5540551-zen

**Comment by jbordonado** [comment]
I followed the steps to reproduce, and I could pay successfully for the order without seeing any issues on the site.
I could, however, notice the described error in my logs (WooCommerce > Status > Logs).

There is [a mechanism in place to retry without the level3 data](https://github.com/Automattic/woocommerce-payments/blob/1a34f24c864db04a182f7e916654c943bdb460e2/includes/wc-payment-api/class-wc-payments-api-client.php#L2149-L2151) in case the request fails, hence why I was able to pay for the order as if everything's OK.

As for the error itself, [the piece of code that adds a `zero-cost-fee` line_item in case there aren't any items](https://github.com/Automattic/woocommerce-payments/blob/1a34f24c864db04a182f7e916654c943bdb460e2/includes/wc-payment-api/class-wc-payments-api-client.php#L2116-L2128) has been around for > 1 year (see [this PR](https://github.com/Automattic/woocommerce-payments/pull/2115)), so I'm surprised that this was not seen before (unless Stripe has recently changed the character limit for the `product_code` field..).

Sending this to the "Engineering review" to decide how to cope with the 12 characters' limit.

**Comment by nagpai** [comment]
Stripe has a [character limit](https://stripe.com/docs/level3#:~:text=product_code%3A%20Up%20to%2012%20characters%20that%20uniquely%20identify%20the%20product.) of 12 for `product_code` and `zero-cost-fee` seems 13 characters long. 

~However, when I test, the logs show the `product_code` without any error. It is derived from a truncated version of the fee description.~ 

~Example:  I set the description of the fee as `Fee with a name longer than 12 digits`.  It seems to result in no errors, and a `product_code` of `fee-with-a-n` .~ (truncated product description) 

Maybe related to the [other issue ](https://github.com/Automattic/woocommerce-payments/issues/4411)where @thracefulton originally commented.  I will keep an eye on it as I work on it.

**Comment by nagpai** [comment]
Stripe has a [character limit](https://stripe.com/docs/level3#:~:text=product_code%3A%20Up%20to%2012%20characters%20that%20uniquely%20identify%20the%20product.) of 12 for `product_code` and `zero-cost-fee` seems 13 characters long. 

It looks like it is somewhat related to the [other issue ](https://github.com/Automattic/woocommerce-payments/issues/4411)where @thracefulton originally commented.  Sorry, I was unable to catch that earlier.

I was not able to see the error in the log with the [changes in the PR](https://github.com/Automattic/woocommerce-payments/pull/4741) applied. I will test this thoroughly and comment back here.

**Comment by thracefulton** [comment]
In the process of reviewing other payments in the account for 5540551-zen, I did notice at least one where the same error showed in the logs prior to the entry for the successful charge. Let me know if you need me to dig up those logs.

**Comment by nagpai** [comment]
It looks like I am able to replicate it. I may have done some wrong step earlier. Sorry about that.
