### ISSUE TITLE
Create or extend components needed for Progressive Onboarding

### ISSUE THREAD

**Issue by dmallory42** [Automattic/woocommerce-payments#4744]
### Description

This issue will cover either creating or identifying and extending any components which will be needed for Progressive Onboarding. 

Example/psuedocode of the type of components we will need (these could be extensions of existing components or brand new components):

`<OnboardingForm>`
`<OnboardingFormStep>`
`<SocialSecurityInput>`
`<DateOfBirthInput>`

#### Required components so far:
- Searchable custom select control with categories for MCC.
- International phone number field.
- Loading bar.
- Update CustomSelectControl to match other form inputs style.
- Notice component – Use the new BannerNotice component added recently.

### Acceptance criteria

* Either create or identify and then extend any components related to Progressive Onboarding, as defined in the designs paJDYF-5IU-p2.

**Comment by ismaeldcom** [comment]
Until we have the final design we cannot know for sure the required components. But for now, I see we will need a `TextControl` (input) with a formatting feature.

For example, to format date and SSN inputs value:

<img width="250" alt="Screenshot 2022-09-28 at 11 59 43" src="https://user-images.githubusercontent.com/7670276/192750631-505077c0-cdf0-49a3-86e4-2bf60bfdccb6.png">
