### ISSUE TITLE
Full Page Design for Progressive Onboarding

### ISSUE THREAD

**Issue by dmallory42** [Automattic/woocommerce-payments#4746]
### Description

This issue will cover implementing the **designs** for Progressive Onboarding. Implementation of the actual logic of the form will be covered by #5473, and implementation of the custom component elements will be covered by #4744, so this issue will mainly cover putting these two parts together.

### Acceptance Criteria

- PO flow matches the designs as shown in paJDYF-5IU-p2

**Comment by daquinons** [comment]
This issue should include the latest pending changes in design after [the latest update](paJDYF-7m7-p2#comment-17194), and any additional needed retouch
