### ISSUE TITLE
Customer can't buy products in a production site

### ISSUE THREAD

**Issue by leonardola** [Automattic/woocommerce-payments#4759]
### Describe the bug
Off by one error when customer buys product via WooPay in a production site.

discussion in the p1661796090593129-slack-C022WMN88KG
This was initially treated as a WooPay issue at 1239-gh-Automattic/woopay 
This is a tricky error because it only happens in some sites. https://woopaymerchantdemo.com/ for example

### To Reproduce
- As a non logged shopper add a product to the cart
- Go to checkout
- Create a new WooPay user by checking the option `Save my data for faster checkouts`
- Check the option to create the user in the merchant site
- Try to buy a product using WooPay
- You'll get an error that's being generated [here](https://github.com/Automattic/woocommerce-payments/blob/526960dd73a67ecd0c140e5585b18bf838938d60/includes/class-wc-payment-gateway-wcpay.php#L1340)
- The order will be marked as failed in the merchant store and there will be a note saying `We're not able to process this payment. Please try again later.`

### Expected behavior
- Customer should be able to buy products via WooPay in production sites

**Comment by vbelolapotkov** [comment]
Link to slack discussion (the original one doesn't work for me): p1661796090593129-slack-C022WMN88KG
