### ISSUE TITLE
[Authorizations] Fetch single authorization and summary data

### ISSUE THREAD

**Issue by mgascam** [Automattic/woocommerce-payments#4766]
### Description

Fetch single authorization data from WCPay server's endpoint. 

### Acceptance criteria

* Create client side data endpoint to fetch authorization data from WCPay server

### Dev notes

You can check WCPay server endpoint implementation in this [PR](2465-gh-Automattic/woocommerce-payments-server)

**Comment by elazzabi** [comment]
Couldn't find an issue to fetch a list of authorizations + summary, so I'm working on it part of this issue
