### ISSUE TITLE
Develop Further E2E Multi-Currency Tests

### ISSUE THREAD

**Issue by dmallory42** [Automattic/woocommerce-payments#4770]
### Description

In #2536 we added the basic framework of E2E tests for Multi-Currency. We can expand on this by developing further tests such as full payment flows and refunds.
 
### Acceptance criteria

* We test full Multi Currency flows in E2E.

**Comment by bborman22** [comment]
Closing this in favor of the epic: https://github.com/Automattic/woocommerce-payments/issues/6346
