### ISSUE TITLE
"Illegal offset" fatal errors during error handling with latest Jetpack

### ISSUE THREAD

**Issue by brianyu28** [Automattic/woocommerce-payments#4779]
### Describe the bug

On sites with the latest version of Jetpack, "illegal offset" fatal errors frequently happen during any situation where the WCPay client would normally gracefully handle an error from WCPay Server.

### To Reproduce

To reproduce this error, you'll need:
- PHP 8.0+ (since invalid offsets are a warning in PHP 7.4 but an [error in PHP 8.0](https://www.php.net/manual/en/migration80.incompatible.php))
- Jetpack Connection v1.44.0 (included in Jetpack v11.3, released 6 September 2022) or later installed on your site. WCPay currently comes bundled with Jetpack Connection v1.37.3 which doesn't have the issue, but if the merchant has Jetpack plugin v11.3 or later then they'll run into this problem. You can simulate the issue locally by either (a) installing Jetpack 11.3+ on your site and/or (b) Temporarily updating `composer.json` to use Jetpack Connection 1.44.0 and then `composer update`.

You can see the fatal errors by taking any action that results in an error from WCPay Server that WCPay client should gracefully handle. An easy example is to simulate declined payments:
- Go to the checkout page, complete a checkout with the test card number `4000000000000002` (generic decline)

### Actual behavior

`Internal Server Error`

Sample stacktrace:

```
PHP Fatal error:  Uncaught TypeError: Illegal offset type in /Users/brian/sites/wcpay/wp-includes/class-wp-error.php:190
Stack trace:
#0 /Users/brian/sites/wcpay/wp-includes/class-wp-error.php(65): WP_Error->add(Array, '', Array)
#1 /Users/brian/sites/wcpay/wp-content/plugins/jetpack/jetpack_vendor/automattic/jetpack-connection/src/class-error-handler.php(729): WP_Error->__construct(Array, '', Array)
#2 /Users/brian/sites/wcpay/wp-content/plugins/jetpack/jetpack_vendor/automattic/jetpack-connection/src/class-client.php(49): Automattic\Jetpack\Connection\Error_Handler->check_api_response_for_errors(Array, Array, 'https://public-...', 'POST', 'rest')
#3 /Users/brian/sites/wcpay/wp-content/plugins/woocommerce-payments/includes/wc-payment-api/class-wc-payments-http.php(108): Automattic\Jetpack\Connection\Client::remote_request(Array, '{"test_mode":tr...')
#4 /Users/brian/sites/wcpay/wp-content/plugins/woocommerce-payments/includes/wc-payment-api/class-wc-payments-http.php(74): WC_Payments_Http::make_request(Array, '{"test_mode":tr...')
#5 /Users/brian/sites/wcpay/wp-content/plugins/woocommerce-payments/includes/wc-payment-api/class-wc-payments-api-client.php(2072): WC_Payments_Http->remote_request(Array, '{"test_mode":tr...', true, false)
#6 /Users/brian/sites/wcpay/wp-content/plugins/woocommerce-payments/includes/wc-payment-api/class-wc-payments-api-client.php(2131): WC_Payments_API_Client->request(Array, 'intentions', 'POST', true)
```

### Expected behavior

Error handled gracefully.

### Additional context

The error happens as a result of https://github.com/Automattic/jetpack/pull/25694, which adds REST API error verification to Jetpack Connection. The error assumes that `$body['error']` is an error code string when constructing a `WP_Error`, but for WCPay Server requests `$body['error']` is often an array.

It may be that the fix for this should be in Jetpack rather than WCPay, but creating this issue in WCPay since it's likely to affect merchants.

cc @hsingyuc @alefesouza

**Comment by jessy-p** [comment]
@brianyu28 Is it possible to replicate on JN site?
I have installed WCPay and Jetpack 11.3, but I do get the "Card Declined" error.

**Comment by jessy-p** [comment]
Able to replicate on JN site.
- Set up site with PHP 8 using JN options
- Install Jetpack (11.3)

Tested on checkout page with test card for decline `4000000000000002`
<img width="1092" alt="image" src="https://user-images.githubusercontent.com/32092402/191216805-c500783b-9fa7-4b9f-8018-1a48b5e5dadf.png">

**Comment by namiokuzono** [comment]
Issue reported in 5571639-zen

**Comment by c-shultz** [comment]
I see the same as you with the same setup @jessy-p. 

**If I deactivate Jetpack 11.3.1**, I get the expected error:

<img width="346" alt="image" src="https://user-images.githubusercontent.com/6209518/191351963-5d0d84d7-50fc-4ab4-aac1-b71a0e6af25f.png">

**Comment by brianyu28** [comment]
Noting too that while declined payments are one example of where this error comes up, the fatal error will also come up anywhere else we catch API exceptions, including:
- Paying for a product whose price is too small
- Paying for a subscription with a free trial
- Trying to update a Stripe customer after importing it from another site
- Certain flows when capturing charges and authorizing captures
