### ISSUE TITLE
[Authorizations] Updating order status to `Processing` before Capturing - Cannot refund order.

### ISSUE THREAD

**Issue by AashikP** [Automattic/woocommerce-payments#4789]
### Describe the bug

You can capture payment after setting the order status to processing. However:

* This does not add confirmation about the amount captured in order notes. 
* This also does not let you refund the order

### To Reproduce

1. Enable authorization
2. Create order in the frontend  (don’t capture the charge)
3. Change the order status to `Processing`
4. Capture charge now
5. Notice that order notes is not updated with confirmation about the capture:

    ![Bp7nWF.png](https://user-images.githubusercontent.com/17475174/191887089-b3635621-878a-486c-8f06-b5cf2a5f05f5.png)

6. Attempt to capture the order multiple times. No update on the order itself. 
7. On Stripe, you can see that attempt to capture failed since cannot be captured since it is already captured:

    ![Baaljy.png](https://user-images.githubusercontent.com/17475174/191887173-026175a7-a8ec-4de9-8877-2186f1fb7c3c.png)
8. Access _Payments > Transactions_ to confirm that the order is indeed captured:
    ![CbEZiH.png](https://user-images.githubusercontent.com/17475174/191887203-267d460f-2c62-4566-8483-aa085614f2fb.png)
9. Notice that you cannot refund the order from the order details page even though it is successfully captured

    ![ej4oeP.png](https://user-images.githubusercontent.com/17475174/191887217-6f4896ca-3ce9-425b-bfba-8b1fd010f30e.png)

### Actual behavior

* No confirmation about the captured amount
* Unable to refund the order

### Expected behavior

If the order status is updated to processing before capturing the charge, order notes should still confirm the captured amount if it was successfully captured, and it should let merchants refund the captured amount.

### Desktop (please complete the following information):

* OS: [e.g. iOS]: N/A
* Browser [e.g. chrome, safari]: N/A
* Version [e.g. 22]: N/A

### Additional context

Reported in 5575478-zen

**Comment by jbordonado** [comment]
It looks similar to an issue that was reported in #4333, which I was unable to reproduce and figure out

**Comment by jessy-p** [comment]
Able to replicate on JN site.
@jbordonado  The key here is the third step "Change the order status to Processing" manually and then do the capture, which causes it to fail.  This was not reported in #4333. It is possible that the merchants facing issue #4333 might have manually or using some other plugin/custom code changed the order status to Capture.

As the steps to replicate this are clear, we can prioritize and fix this and it might also fix #4333

**Comment by kalessil** [comment]
@AashikP, WooCommerce core considers `processing` to indicate paid order status, and from this perspective, the behavior is correct (more details [here](https://github.com/Automattic/woocommerce-payments/pull/4805#discussion_r983541151)).

Possible mitigations (from the linked comment):

> So either this should be changed in WooCommerce core, or the merchant has to use `woocommerce_order_is_paid_statuses` hook to customize the paid statuses for their store.

cc @dpaun1985, I believe we should close the PR.

**Comment by kalessil** [comment]
@dpaun1985 explained that we can capture the order in this status and suggested fixing the root cause, by disabling capture somehow for this case.

Is that something we should look into?

**Comment by dpaun1985** [comment]
I think we have 2 options if the order has one of the paid statuses ( processing/completed ) :
1. hide the charge order option and make sure that the order will not be charged
2. let the merchant charge the buyer even if the order is considered paid, add the action in order notes and let the possibility for the merchant to refund the charge ( implemented  [here](https://github.com/Automattic/woocommerce-payments/pull/4805) ).

**Comment by paulostp** [comment]
Have another report here: 5614794-zd-woothemes

Brand-new WooCommerce Payments account. The merchant initially enabled "Issue an authorization on checkout, and capture later" due to a misunderstanding. Then, in an attempt to fix their mistake, they updated all orders from their opening day to "Processing" hoping it would take care of the "capture later" part. We then advised them to manually capture the charges, which should solve the issue.

They were left understandably confused because we told them the capture would be noted on each order, however, there was no confirmation on the order notes that the capture was successful.

We had to assure them three times that all orders were 100% paid for and that they could ship the products.

**Comment by kalessil** [comment]
@dpaun1985, how much effort would it be to implement option 1 (`hide the charge order option and make sure that the order will not be charged`).

Option 2 is risky - we don't know how many 3rd party extensions might be affected if we proceed with the first PR you have created.

**Comment by dpaun1985** [comment]
> @dpaun1985, how much effort would it be to implement option 1 (`hide the charge order option and make sure that the order will not be charged`).
> 
> Option 2 is risky - we don't know how many 3rd party extensions might be affected if we proceed with the first PR you have created.

 I don't expect to be more than 1-2 days .

**Comment by kalessil** [comment]
Sounds good. Go ahead!

Additionally:
- I remove the critical priority - the bug is misleading, but not critical IMO
- I'd say this is auth&capture related, so it worth pulling into reviews folks from the corresponding project

**Comment by raifd** [comment]
5767853-zen is experiencing this issue too.

**Comment by seanbelly** [comment]
Hi there, we seem to have another ticket with the same issue: 7012259-zd-a8c

**Comment by kgeorgee** [comment]
Similar here: 7327640-zen
