### ISSUE TITLE
Handle 429 responses with lock_timeout error

### ISSUE THREAD

**Issue by oaratovskyi** [Automattic/woocommerce-payments#4801]
### Description
Sometimes Stripe responds with the code `429` when `confirmPayment()` is called. That's related to Stripe's internal issues, which do not have a timeline (of fix) for now.
They have suggested implementing next while they're working on a solution:
> if you receive a lock timeout, when the merchant code is calling `confirmPayment()` function and it error's out (in cases of `lock_timeout`), you can manually call `retrievePaymentIntent()` from Stripe.js to re-fetch the `PaymentIntent` yourself

### Additional context
Slack threads: 
- more info about Stripe response: p1664188787481779/1663167748.635789-slack-CGGCLBN58
- history of the issue: p1663721387669259-slack-C9976E5MJ

**Comment by jbordonado** [comment]
Herafter my initial analysis.

For the classic checkout + UPE, we are going through the following code, using `confirmPayment()` (there are other places where it's used): https://github.com/Automattic/woocommerce-payments/blob/ac01d080e496f942457261435b556b34d0ccf754/client/checkout/classic/upe.js#L514-L528

As per [their doc](https://stripe.com/docs/js/payment_intents/confirm_payment):

> Upon a successful confirmation, your user will be redirected to the return_url you provide before the Promise ever resolves.

If `confirmPayment` is a success, the code on l.516 is not even resolved and we are redirected to the `return_url` we provided as a parameter (e.g., the "Order received" page: `/checkout/order-received?xxx=yyy&...`).
Only if there's an error the call is resolved and we will define the `error` object, throw an error and eventually show the error message on the checkout page.

They are suggesting that we call `retrievePaymentIntent` in case `error.code = lock_timeout`.
I guess we then need to check whether the `status` field in the PaymentIntent is set to `succeeded`. 
- If yes, we can assume that the payment was confirmed (even though we got the `lock_timeout` error). So we would need to manually redirect the customer to the "Order received" page (similarly to what the stripe.js script does for us behind the scene, at the end of `confirmPayment()`).
- If not, we do the same thing as today: throw the error received from `confirmPayment()`, and the customer will see the error message.

I'll get back to Stripe's support to confirm with them that this is what they had in mind.

**Comment by oaratovskyi** [comment]
@jbordonado let me know if you want me to reply to Stripe via the existing email thread and cc you there (I was cc'ed there as this week's janitor), that might speed things up a bit.

**Comment by jbordonado** [comment]
> @jbordonado let me know if you want me to reply to Stripe via the existing email thread and cc you there (I was cc'ed there as this week's janitor), that might speed things up a bit.

I didn't have time to follow up on that yet.
It would be great if you could confirm with them if they had in mind that we call `retrievePaymentIntent` and check the status (`succeeded`?) to confirm whether the order is OK so we can ignore the `lock_timeout` error and proceed to the confirmation page anyway.

Pinging @zmaglica as he will work on it instead of me

**Comment by oaratovskyi** [comment]
Thanks a lot @jbordonado !
I've asked Stripe via email and cc'ed @zmaglica.

**Comment by jesscga** [comment]
Noting that there's an update from David at Stripe:

>I checked with our internal team and confirming yes you can check the status of the PaymentIntent and manually redirect if it succeeded.

I put the [ticket](5574871-zd-woothemes) on a 72-hour hold in case anyone wants to follow up on Monday.
