### ISSUE TITLE
UPE disable menu shift

### ISSUE THREAD

**Issue by frosso** [Automattic/woocommerce-payments#4842]
### Describe the bug

When the "Disable UPE" menu opens, the page shifts and the menu icon changes position.
There should be no shift of content when the menu opens.

### To Reproduce

- Ensure you have the UPE enabled
- Click on the hamburger menu
- Shift happens

### Actual behavior

Content shift happens.

### Screenshots

![2022-10-04 10 07 01](https://user-images.githubusercontent.com/273592/193882562-24cd9829-6204-49fc-b743-90025d73a4c0.gif)

### Expected behavior

Content shift should not happen

### Desktop (please complete the following information):

Not device specific.

**Comment by a-danae** [comment]
@frosso, can you replicate this behavior on a fresh site? I'm on the latest develop, and things look okay over here.

![LWciWl.gif](https://user-images.githubusercontent.com/41606954/193904733-bd70d222-e9ab-4438-a6f0-262c8c0ebfdc.gif)

**Comment by frosso** [comment]
@a-danae Thanks for the ping, I noticed that this is happening with the Gutenberg plugin enabled. I am guessing that there are some updated Wordpress components that are affecting the CSS and the behavior of the site.

**Comment by a-danae** [comment]
Gotcha! I can replicate this behavior with Gutenberg since its 13.3.0 version. Thanks for clarifying!
