### ISSUE TITLE
StripeLink: Inbox notification

### ISSUE THREAD

**Issue by dpaun1985** [Automattic/woocommerce-payments#4844]
### Description

A new inbox notification has to be added in admin WC -> home

Title: Increase conversion at checkout
Copy: Reduce cart abandonment and create a frictionless checkout experience with Link by Stripe. Link autofills your customer’s payment and shipping details so they can check out in just six seconds with the Link optimized experience. That’s 9x faster than shoppers who don’t use Link. Link increases conversion rates by over 7% for logged-in Link customers.
[CTA: Set up now](https://woocommerce.com/document/payments/woocommerce-payments-stripe-link/)
→ links to the docs above.

**Comment by aheckler** [comment]
That links goes to the Stripe plugin docs, not the WC Pay docs. The link should lead here:

https://woocommerce.com/document/payments/woocommerce-payments-stripe-link/

**Comment by dpaun1985** [comment]
> That links goes to the Stripe plugin docs, not the WC Pay docs. The link should lead here:
> 
> https://woocommerce.com/document/payments/woocommerce-payments-stripe-link/

indeed, thank you @aheckler .
