### ISSUE TITLE
Update by January 1970 to avoid a disruption in deposits.

### ISSUE THREAD

**Issue by tommyshellberg** [Automattic/woocommerce-payments#4846]
### Describe the bug
It is possible that a user may have pending requirements for the account that do *not* have a deadline, which can be stored within `future_requirements` of the account object.
This sets the account's status to `restricted_soon` and [prompts a task to complete their account information](https://github.com/Automattic/woocommerce-payments/blob/8cb0e930add4d4371d6e32fd7224f3d967a8d397/client/overview/task-list/tasks.js#L30). However, the deadline will be `false` in this case (because Stripe does not provide a deadline) instead of a timestamp and we don't check if the deadline is actually a timestamp [before trying to convert it](https://github.com/Automattic/woocommerce-payments/blob/8cb0e930add4d4371d6e32fd7224f3d967a8d397/client/overview/task-list/tasks.js#L39).

Thus, we see January 1970 as the date.

![FkvJ00.png](https://user-images.githubusercontent.com/6723003/194059992-13175214-fd67-462d-90e0-1225c6e215be.png)

Slack discussion:
p1664971487465379-slack-C03KTTK2YMA

### Expected behavior
If the user has future requirements but no deadline, we could show a simpler message like `Update to avoid a disruption in deposits`.

**Comment by joashrajin** [comment]
+1 at 5624404-zd-woothemes

**Comment by rossviviano** [comment]
Another at 5630970-zen

**Comment by dreamtooloud** [comment]
another report at 5667287-zen

**Comment by daquinons** [comment]
Discussion p1668718914556339-slack-CGGCLBN58

**Comment by zoupkat** [comment]
Another report 5718733-zen

**Comment by sverleis** [comment]
Adding #5731326-zen to the list.

**Comment by csmcneill** [comment]
Saw another report of this in 5771386-zen (version 5.1.2)

Reopening (cc @Automattic/moltres)

**Comment by dmallory42** [comment]
@csmcneill I don't think that this made the cut for 5.1.x, the fix will land in 5.2.0. 🙂

Closing but feel free to reopen if more reports come in when 5.2.0 releases!
