### ISSUE TITLE
Progressive Onboarding: Collect the MCC and pre-fill it in Stripe's KYC

### ISSUE THREAD

**Issue by dmallory42** [Automattic/woocommerce-payments#4853]
### Description

After [this issue](https://github.com/Automattic/woocommerce-payments/issues/4744) that tackles the needed UI components and coupled with [this WCPay server issue](https://github.com/Automattic/woocommerce-payments-server/issues/3193), we need to introduce an MCC select control in our onboarding wizard to allow merchants to select the appropriate MCC for their business. 

After that, we can pass along this MCC and have it _prefilled_ when redirecting the merchant to Stripe KYC. [According to Stripe](https://stripe.com/docs/connect/express-accounts#create-account), any prefilled information won't be asked from the merchant in Stripe's onboarding flow. Nice!

For the PO MVP, we decided to only present in the MCC control the sub-list of MCCs that Stripe uses for its "Industry" control. For fetching the MCCs list to use in the PO wizard, we will use the WCPay API endpoint introduced in [this PR](https://github.com/Automattic/woocommerce-payments-server/pull/3180).

#### Notes

Brandon raised some thoughts on this on Slack (p1665001733545039/1664352339.162549-slack-C03KTTK2YMA) and recommended that we treat the WCPay experience as agnostic as possible.

### Acceptance criteria

* MCC is selectable on the onboarding form
* The selected MCC is passed to [Stripe's Account API](https://stripe.com/docs/api/accounts/create) and is prefilled in Stripe's KYC flow.

**Comment by darcie** [comment]
We had a request from a merchant to update MCC in 5744324-zen, adding to support the needs of this feature.

**Comment by dmallory42** [comment]
Hi @darcie, it looks like that merchant's need is slightly different - this issue would be for collecting the MCC on initial account onboarding, it looks like what they would have needed is a way to update the MCC *after* the account had been created.

cc'ing @rogermattic - it may be worth considering as part of the PO work (or in future) that it could be good to allow merchants to update details about their Stripe account in the WCPay admin section? It looks like it would be technically possible to update via API.

**Comment by rogermattic** [comment]
Thanks for pinging me @dmallory42 

> it may be worth considering as part of the PO work (or in future) that it could be good to allow merchants to update details about their Stripe account in the WCPay admin section? It looks like it would be technically possible to update via API.

Great idea, I'll definitely like to have it in Settings as one of the details that the merchant can edit! I'll add it to my wireframes.

**Comment by vladolaru** [comment]
After discussing it with my team in p1680088154481139-slack-C03KTTK2YMA, we've decided to reevaluate this issue since it is outdated and doesn't reflect what we've discovered along the way: rewrite and change estimation.
