### ISSUE TITLE
Remove `_wcpay_feature_custom_deposit_schedules` feature flag

### ISSUE THREAD

**Issue by aprea** [Automattic/woocommerce-payments#4856]
### Description
A `_wcpay_feature_custom_deposit_schedules` feature flag was added early in the development of the Custom Deposit Schedule (pdjTHR-1c8-p2) project. This feature flag is no longer needed and can be removed.

### Acceptance criteria

* Remove the feature flag and related code: https://github.com/Automattic/woocommerce-payments/blob/914f3139a2b227ce73753382d6f96fd76b43ec30/includes/class-wc-payments-features.php#L113-L120
* When removing the feature flag the left behind logic should consider that the custom deposit schedules feature is **enabled**.
* All related deposit functionality should continue to work as expected.

**Comment by haszari** [comment]
Let's get this tidied up!
