### ISSUE TITLE
Cannot dequeue wc-blocks-checkout-style-css found in footer

### ISSUE THREAD

**Issue by rlmajcom** [Automattic/woocommerce-payments#4861]
### Describe the bug

I have the following WooCommerce Payments stylesheet being loaded in my tag and have not been able to find out how to remove it:

<link rel='stylesheet' id='wc-blocks-checkout-style-css'  href='https://www.example.com/wp-content/plugins/woocommerce-payments/dist/upe-blocks-checkout.css?ver=1.0' media='all' />
(I only use WooCommerce on certain pages so therefore do not need all of the files to be loaded on most pages)

I removed the stylesheet from loading in the header successfully within the wp_enqueue_scripts action hook using:

wp_dequeue_style('wc-blocks-checkout-style');

However, wc-blocks-checkout-style-css still loads in the footer ( /wp-content/plugins/woocommerce-payments/dist/upe-blocks-checkout.css )

### To Reproduce

Have WooCommerce Payments intstalled and View source code and/or Network tab in Chrome dev tools
/wp-content/plugins/woocommerce-payments/dist/upe-blocks-checkout.css will be loaded in the footer even though 
wc-blocks-checkout-style has been dequeued

### Actual behavior

upe-blocks-checkout.css gets loaded

### Expected behavior

I should be able to use 
wp_dequeue_style('wc-blocks-checkout-style-css'); or wc-blocks-checkout-style
within the within the wp_enqueue_scripts hook to prevent this stylesheet from being loaded

### Desktop (please complete the following information):

* OS: [e.g. iOS] Windows 10
* Browser [e.g. chrome, safari] chrome 
* Version [e.g. 22] latest

### Smartphone (please complete the following information):

* Device: [e.g. iPhone6]
* OS: [e.g. iOS8.1]
* Browser [e.g. stock browser, safari]
* Version [e.g. 22]

**Comment by RadoslavGeorgiev** [comment]
Hi @rlmajcom, this is out of WCPay's control. I've recreated the issue in the WooCommerce Blocks repo, as folks there are likely much more familiar with the way scripts are enqueued.

**Comment by opr** [comment]
I left a comment on https://github.com/woocommerce/woocommerce-blocks/issues/7349 where I explain why I think this is a WooCommerce Payments issue. I'll post it here for easy access.

----

I investigated this today and I don't believe this is a WooCommerce Blocks issue. In https://github.com/Automattic/woocommerce-payments/blob/develop/includes/class-wc-payments-blocks-payment-method.php#L38-L69 it looks like you're calling wp_enqueue_style which will register the style to be output onto the page, however this method (get_payment_method_script_handles) is called several times, and probably should not have side-effects, it is supposed to return the handles of registered scripts

If you want to enqueue a style specifically for use on the Cart/Checkout blocks, I would recommend using the [IntegrationInterface](https://github.com/woocommerce/woocommerce-blocks/blob/trunk/docs/third-party-developers/extensibility/checkout-block/integration-interface.md#integrationinterface-methods) which would let you register the style and only enqueue it when rendering one of the Cart/Checkout blocks.

**Comment by jonoalderson** [comment]
Seconded, this is a pain. Really don't want/need this to be loading on all of my pages.

**Comment by rlmajcom** [comment]
Any update on this? blocks-checkout.css still cannot be dequeued or deregistered successfully and therefore unneccesarily loads across all pages.

**Comment by FangedParakeet** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Heisenberg-63586f2ec60359001310fa6a/issues/Automattic/woocommerce-payments/4861?planning-poker) with Zenhub @brettshumaker
