### ISSUE TITLE
Improve failed order notes

### ISSUE THREAD

**Issue by RadoslavGeorgiev** [Automattic/woocommerce-payments#489]
We should be more specific with the messages, which are added as notes, whenever an order fails.

h/t  @DustinHartzler for noticing this in https://github.com/Automattic/woocommerce-payments/issues/487

For example, use 4000000000009995 to check out. You will see a message like this as a customer:

> Error: card_declined Your card has insufficient funds.

However, the order note simply states the following, without any clarifications.

> Order status changed from Pending payment to Failed.

I'm not certain if we should include the particular error code, but we should _at least_ mention that there was a payment issue.

**Comment by kalessil** [comment]
Notes for myself:

- server side chages: handle 'payment_intent.payment_failed' event and bump stats as we do fir succeeded intents
- client side changes: investigating

**Comment by kalessil** [comment]
Also, ping @GeoJunkie, @zhollenbeak: with this change if a transaction fails, we'll see a corresponding order note. This should land into WCPay v1.8.0.

**Comment by DustinHartzler** [comment]
Thanks for making it more clear for WooCommerce Payment users 👍
