### ISSUE TITLE
Not possible to refund won disputed order (one-off case)

### ISSUE THREAD

**Issue by denho** [Automattic/woocommerce-payments#4931]
### Describe the bug

A customer opened a dispute for an order. Looking at order notes, it seems like the dispute was first lost, but next day the status changed and it became won. Here are the order notes which show this transition:
<img src="https://user-images.githubusercontent.com/2803994/196135350-d53e62ae-4af4-4e7d-9fd9-9b290e2a90b5.png" width="300">

After the dispute had been won, the funds placed on merchant account and order status set as Completed, it is still not possible to issue a refund - refund button is unavailable. There is a refund note, and bottom line saying order has been refunded, though no refund has been made manually:
<img width="936" alt="image" src="https://user-images.githubusercontent.com/2803994/196135904-148c8eb5-fa0d-4cd1-a557-d36cd0586688.png">

### To Reproduce
Not sure.

### Actual behavior
Not possible to issue a refund for the order.

### Screenshots
The transaction timeline, in case it helps:
![image](https://user-images.githubusercontent.com/2803994/196136715-5a23953e-fe3a-40a1-84dc-652cf655b01f.png)

### Expected behavior
Should be possible to refund the order.

**Comment by RadoslavGeorgiev** [comment]
I've asked Stripe p1666003536849509-slack-C9976E5MJ to check if this is a bug, or something typical. The issue appears to have been initially lost, only to get another webhook that it was won the next day, without providing any new evidence or something like that.

**Comment by jbordonado** [comment]
Stripe asked us to send this request to their support through support@stripe.com

Ticket created: 5716455-zd-woothemes

**Comment by jbordonado** [comment]
Stripe came back with an update on the ticket:

> It looks like the issuer first lost the dispute by rejecting the merchant's evidence but then decided to fund the dispute anyway, leading to a win for the merchant. This is somewhat unusual, but definitely not concerning.

It looks like this case is rare but can happen nevertheless.

We can look into the best way to handle this in our code.

**Comment by haszari** [comment]
After reading through the description and comments, it looks to me like this is a specific (rare) scenario – i.e. it's not common for a dispute to be lost then won. Added `(one-off case)` to the title to clarify that this has limited impact.

(I'm logging an [issue for preventing refund of disputed orders](https://github.com/Automattic/woocommerce-payments/issues/6378), so was searching for similar bugs and found this.)

**Comment by haszari** [comment]
Marking as low as this appears to be a one-off edge case. We can possibly close this – @denho @jbordonado do you have next steps in mind or is it ok to close?

**Comment by Jinksi** [comment]
Closing since this is a rare edge case (potentially a one-off) and we don't have plans to solve this.
