### ISSUE TITLE
WooPay OTP modal and redirection don't work on the block checkout

### ISSUE THREAD

**Issue by a-danae** [Automattic/woocommerce-payments#4934]
### Describe the bug
The OTP modal and redirection don't work on the block checkout.

### To Reproduce

1. Activate [WooCommerce Blocks](https://wordpress.org/plugins/woo-gutenberg-products-block/)
2. Create a new page containing the WooCommerce checkout block
3. Make sure WooPay is enabled
4. Add a product to your cart
5. Go to the page with the WC checkout block
6. Open the browser console. Notice there's an error saying `Uncaught (in promise) TypeError: Cannot read properties of null (reading 'addEventListener')` coming from the`email-input-iframe.js` file
7. Add an email that exists on WooPay. Notice the OTP modal doesn't show up.

Things work as expected on the shortcode checkout page.

### Actual behavior

There's an error in the browser console on the block checkout page. The OTP modal doesn't show up and the WooPay automatic redirection doesn't happen.

### Screenshots
<img width="1788" alt="image" src="https://user-images.githubusercontent.com/41606954/196296215-a610c0be-c151-4f04-a806-e0c375405179.png">

### Expected behavior
I'd expect the behavior on the blocks checkout to be the same as on the shortcode checkout.

### Additional context
Looks like the selector we're using for the checkout form isn't present anymore, `'form[name="checkout"]'`

**Comment by pierorocca** [comment]
@a-danae is this issue still ongoing or should be closed?

**Comment by pierorocca** [comment]
Hey @a-danae following up on this issue. Would you agree this issue is no longer relevant?

**Comment by a-danae** [comment]
Hey! Yes, I can't replicate it anymore. Closing it as it's no longer relevant.

(I completely missed the first ping. Sorry for the delay!)

**Comment by pierorocca** [comment]
No worries thank you so much for confirming! I'm going through some of the older aged issues to double check if they need to be closed. Appreciate it!
