### ISSUE TITLE
In-Person Payments: when generating receipt and fetching logo fails, still generate the receipt

### ISSUE THREAD

**Issue by kalessil** [Automattic/woocommerce-payments#4936]
In the context of https://github.com/Automattic/woocommerce-payments-server/pull/2346, we ran into some extra limitations related to the migration path, as a fetching logo in between migration steps can cause broken receipts generation.

An alternative approach would be to use a fallback logo or skip the logo at all, writing an error log and preventing crashes when generating receipts.

**Comment by anu-rock** [comment]
Note: The receipt preview functionality is not impacted since it doesn't include the logo.
