### ISSUE TITLE
Replace deprecated set-output command in code freeze workflow

### ISSUE THREAD

**Issue by jbordonado** [Automattic/woocommerce-payments#4946]
### Description
We should no longer use `set-output` in GitHub Actions because it is deprecated: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
Workflows using the command will start to fail from June 1st, 2023.

We need to update 2 instances of this command in the `release-code-freeze.yml` workflow: [here](https://github.com/Automattic/woocommerce-payments/blob/770b349ea0f287b307e154a514f56203320bd623/.github/workflows/release-code-freeze.yml#L65) and [there](https://github.com/Automattic/woocommerce-payments/blob/770b349ea0f287b307e154a514f56203320bd623/.github/workflows/release-code-freeze.yml#L68)

### Acceptance criteria
* The workflow still runs successfully after making the changes

**Comment by RadoslavGeorgiev** [comment]
@jbordonado is there a reason not to do this now? Could we add it to the release automation epic?

**Comment by jbordonado** [comment]
The reason was that I didn't find the right syntax for setting output the new way in a GitHub action within a PHP context while I was creating the code freeze workflow. I didn't want to waste more time on that and decided to merge as it is.

I'll try to squeeze it while working on the remaining items of phase 1 👍

**Comment by jbordonado** [comment]
Can be closed once #5003 is merged, as I found a way to write to `$GITHUB_OUTPUT` (and `$GITHUB_STEP_SUMMARY` by the way) variable exposed by GitHub Actions from within a PHP script.

It's a file, so we just needed to append the content to it using `file_put_contents`

**Comment by jbordonado** [comment]
Closing this, fixed by #5003
