### ISSUE TITLE
Update submitted evidence form

### ISSUE THREAD

**Issue by vbelolapotkov** [Automattic/woocommerce-payments#495]
Submitted evidence form looks weird with file upload buttons. IMO following updates woulb be nice to have:

1. Hide upload buttons.
2. Show only file name if it was uploaded during submit.
3. Show some placeholder if the file was not uploaded for the field. E.g. `Evidence file was not uploaded.`
4. Don't show any placeholder for additional details, just hide the button.

@LevinMedia what do you think?

<img width="759" alt="Screenshot 2020-03-03 at 13 44 56" src="https://user-images.githubusercontent.com/3139099/75768414-61a49200-5d55-11ea-809d-9432ce270799.png">

**Comment by dechov** [comment]
@LevinMedia Are there updated designs with the current blue button? (Just left an update [here](https://github.com/Automattic/woocommerce-payments/issues/523#issuecomment-862803200) referencing the still pink-outlined button design.)

**Comment by vbelolapotkov** [comment]
Today it looks better, but I think it would be nice to hide upload buttons.

![image](https://user-images.githubusercontent.com/3139099/147462553-9a00f132-9f19-4b01-881d-ab721699cfd2.png)

**Comment by LevinMedia** [comment]
@vbelolapotkov I miss understood the original issue - I agree - if we're looking at the form after the evidence has been submitted, we should not show the buttons, and only show the file names if they were submitted.

**Comment by kalessil** [comment]
Blocking the issue until we clarify with Brady what the locked form should look like.

**Comment by bradyv** [comment]
@kalessil I agree with David's comment above - hide the buttons if we're looking at the form after evidence has been submitted, and show the file names if they exist. Let me know if you'd like me to put together a mockup of what that would look like.

**Comment by nagpai** [comment]
@bradyv - Thanks for your reply! What about helper text like the one below?

![image](https://user-images.githubusercontent.com/4162931/196088362-b0afcf12-1840-41c1-b11e-a6a610d3dedd.png)

Does it make sense to retain them in the submitted (read only ) form, as a reminder, or is it better to keep it clean and remove them ( since the merchant has already taken the cues and submitted the form)?

 The submitted form looks like this, currently in my proposed PR. Would appreciate your review, thanks :) 
 
 
![image](https://user-images.githubusercontent.com/4162931/196089821-b3b6d612-3093-4e95-a1f4-1038bed58d1f.png)


---
![image](https://user-images.githubusercontent.com/4162931/196092530-b853d3e4-51ac-46fd-bbd6-a5c09d08d05d.png)

**Comment by kalessil** [comment]
@bradyv, thanks for following up! Super, we'd love to have a mockup.

**Comment by bradyv** [comment]
> Does it make sense to retain them in the submitted (read only ) form, as a reminder, or is it better to keep it clean and remove them ( since the merchant has already taken the cues and submitted the form)?

@nagpai I was just having a semi-related conversation about the amount of text on the page being overwhelming, and I'm not sure that the merchant _needs_ the helper text in this context, so hiding that after the form is submitted seems fine to me.

I noticed that @rogermattic was tagged on the PR so if there's any disagreements on her end we can work through a different solution.

**Comment by kalessil** [comment]
@bradyv: I pinged Magda before clarifying who'll be supporting Pulsar. Sorry for the confusion.

IIUC:
- we can skip help text
- we do hide the buttons
- we keep all remaining controls read only

Can you confirm, please?

**Comment by bradyv** [comment]
@kalessil I'm not sure what you mean by "skip" the help text, but regardless I think showing or hiding the helper text is fine. I lean towards hiding just because it's not relevant and it cleans the page up.

Otherwise, yes that's correct!

**Comment by nagpai** [comment]
My first JS related PR merged! 🎉 
https://github.com/Automattic/woocommerce-payments/pull/4840

Thanks everyone!

@bradyv  - Thanks for your guidance. I have implemented the changes based on your guidance. I have hidden the upload buttons, and helper texts for forms that are submitted and read-only.
