### ISSUE TITLE
WCPay Platform: Meta Data

### ISSUE THREAD

**Issue by RadoslavGeorgiev** [Automattic/woocommerce-payments#4951]
### Description

Prevent accessing meta data directly: paJDYF-50y-p2#woopay-meta-data.

Within this issue the focus is on `_intent_id`and `_payment_method_id`.

### Acceptance criteria

1. There is a new `Order` helper in the `WCPay\Core` namespace.
2. The helper has methods to access and change an order's intent and payment method IDs.
3. The gateway class's `attach_intent_info_to_order` functionality lives within the new class.
4. All instances where the gateway access those order meta values use the getters and setters from the new class.
5. The new class triggers an action whenever those values change, in order to let consumers consume them.

### Additional context

See the epic for links to the project thread and PRD.

**Comment by kalessil** [comment]
@Automattic/gamma , would it be possible to start documenting the order metadata under https://github.com/Automattic/woocommerce-payments-server/blob/trunk/docs/Metadata.md (as you are fresh into context)?

**Comment by RadoslavGeorgiev** [comment]
Hey Vlad, @jessy-p's working on documenting this issue, however it's just related to (post) meta data on the client, not intent meta data. I don't think we've touched that topic.

(issue was closed because of me moving it to the closed column in ZenHub, I did not know that automatically closes it)

**Comment by kalessil** [comment]
I meant to add a new chapter for Post metadata specific to WCPay, this issue is clearly not related to intents.

**Comment by RadoslavGeorgiev** [comment]
Our plan is to add a readme to the client, do you think this server file could be more suitable?

**Comment by kalessil** [comment]
I don't have a strong opinion on this, though if you make the docs public I'd really appreciate adding a link in the doc I referenced originally.
