### ISSUE TITLE
Multi-currency is incompatible with manually created orders

### ISSUE THREAD

**Issue by csmcneill** [Automattic/woocommerce-payments#4964]
### Describe the bug
If an order is manually created via **WooCommerce > Orders > Add Order**, a customer can only pay for the purchase in the store's default currency. 

Even if the currency can be selected via the breadcrumb drop-down, a customer can still only pay via the store's default currency.

### To Reproduce

1. Enable multi-currency.
2. Add the currency switcher via **WooCommerce > Settings > Multi-currency > Add a currency switcher to the Storefront theme on breadcrumb section**
3. Add a couple of additional currencies.
4. Manually create an order.
5. Navigate to the `Customer payment page ->` (or, if the order is assigned to a customer, navigate to **My Account > Orders** to pay for the order)
6. Attempt to pay for an order that is not the store's default currency, and you will be unable to.

### Actual behavior
Customers are unable to pay for manually created orders in a currency other than the store's default currency.

### Screenshots
![Screen Capture on 2022-10-19 at 16-26-52](https://user-images.githubusercontent.com/82999806/197003438-cab7f32b-6280-4c6f-a72f-51452b77793e.gif)

### Expected behavior
A customer can purchase a manually created order using a currency other than the store's default currency.

Alternatively, a merchant should be able to specify the currency for a particular order during the manual order creation process.

### Additional context
p6q6po-dnu-p2#comment-94787
5609211-zen

<details>
### WordPress Environment ###

WordPress address (URL): https://justfortestingwcpay.com
Site address (URL): https://justfortestingwcpay.com
WC Version: 7.0.0
REST API Version: ✔ 7.0.0
WC Blocks Version: ✔ 8.5.1
Action Scheduler Version: ✔ 3.4.0
Log Directory Writable: ✔
WP Version: 6.0.3
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US
External object cache: ✔

### Server Environment ###

Server Info: nginx
PHP Version: 8.0.24
PHP Post Max Size: 2 GB
PHP Time Limit: 1200
PHP Max Input Vars: 6144
cURL Version: 7.85.0
OpenSSL/1.1.1n

SUHOSIN Installed: –
MySQL Version: 10.4.26-MariaDB-log
Max Upload Size: 2 GB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 7.0.0
WC Database Prefix: wp_
Total Database Size: 5.41MB
Database Data Size: 3.36MB
Database Index Size: 2.05MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 0.08MB + Index: 0.09MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 0.19MB + Index: 0.22MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 0.14MB + Index: 0.13MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 0.09MB + Index: 0.09MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_options: Data: 1.23MB + Index: 0.06MB + Engine InnoDB
wp_postmeta: Data: 0.38MB + Index: 0.34MB + Engine InnoDB
wp_posts: Data: 0.14MB + Index: 0.06MB + Engine InnoDB
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.05MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_attributes_lookup: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_download_directories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_shipping_table_rates: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpml_mails: Data: 0.28MB + Index: 0.00MB + Engine InnoDB

### Post Type Counts ###

attachment: 24
customize_changeset: 31
custom_css: 1
jetpack_migration: 2
nav_menu_item: 6
page: 7
post: 2
product: 22
product_variation: 7
revision: 25
shop_order: 80
shop_order_refund: 2
shop_subscription: 6
wp_global_styles: 2

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (6) ###

Akismet Anti-Spam: by Automattic – 5.0.1
Jetpack: by Automattic – 11.5-a.9
WooCommerce Payments: by Automattic – 4.9.0
WooCommerce Shipping & Tax: by WooCommerce – 1.26.3
WooCommerce: by Automattic – 7.0.0
WP Mail Logging: by Wysija – 1.10.4

### Dropin Plugins (2) ###

advanced-cache.php: advanced-cache.php
object-cache.php: Memcached

### Must Use Plugins (1) ###

WP.com Site Helper: by  –

### Settings ###

API Enabled: –
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
subscription (subscription)
variable (variable)
variable subscription (variable-subscription)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –
Enforce Approved Product Download Directories: ✔

### WC Pages ###

Shop base: #8 - /
Cart: #9 - /cart/
Checkout: #10 - /checkout/
My account: #11 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Storefront
Version: 4.1.3
Author URL: https://woocommerce.com/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Subscriptions ###

WCS_DEBUG: ✔ No
Subscriptions Mode: ✔ Live
Subscriptions Live URL: https://justfortestingwcpay.com
Subscription Statuses: trash: 6
WooCommerce Account Connected: ❌ No

### Store Setup ###

Country / State: United States (US) — Mississippi

### Subscriptions by Payment Gateway ###

WooCommerce Payments: trash: 6

### Payment Gateway Support ###

WooCommerce Payments: products
refunds
multiple_subscriptions
subscription_cancellation
subscription_payment_method_change_admin
subscription_payment_method_change_customer
subscription_payment_method_change
subscription_reactivation
subscription_suspension
subscriptions
gateway_scheduled_payments
tokenization
add_payment_method

Cash on delivery: products

### Admin ###

Enabled Features: activity-panels
analytics
coupons
customer-effort-score-tracks
experimental-products-task
experimental-import-products-task
experimental-fashion-sample-products
experimental-product-tour
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
multichannel-marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: minified-js
new-product-management-experience
settings

Daily Cron: ✔ Next scheduled: 2022-10-20 22:22:37 -05:00
Options: ✔
Notes: 60
Onboarding: completed

### WooCommerce Payments ###

Version: 4.9.0
Connected to WPCOM: Yes
Blog ID: 210545187
Account ID: acct_1LhhVSFk5Ng3VVfB

### Action Scheduler ###

Canceled: 7
Oldest: 2022-09-30 01:38:37 -0500
Newest: 2022-10-03 20:30:12 -0500

Complete: 502
Oldest: 2022-09-19 13:29:07 -0500
Newest: 2022-10-02 14:53:24 -0500

Pending: 1
Oldest: 2022-10-20 12:40:29 -0500
Newest: 2022-10-20 12:40:29 -0500

### Status report information ###

Generated at: 2022-10-20 11:19:50 -05:00
</details>

**Comment by ismaeldcom** [comment]
I think this is a feature and not a bug 🤔 With our current Multi-currency implementation we don't allow orders to switch currencies. So we should choose between allowing it, adding a currency selector on manual order creation, or any other solution.

cc @Automattic/sigma

**Comment by jessepearson** [comment]
Ismael is correct, this is intentional. The currency and the exchange rate are set in the order meta at the time the order is created, and that becomes the currency for the order from that point forward. If the merchant needs to create an order for a customer in a different currency, they would need to place the order through the front end of the site.

There are a couple different ways to do this:
* A user switching plugin could be used, where they switch the the customer's user and then check out.
* A plugin that allows the admin to see other payment methods, like BACS or Check, can be used. This would allow the admin to create the order from the front under under their user, then change the user to the customer's user after the order is placed.
