### ISSUE TITLE
Feature Request: Add balance history page

### ISSUE THREAD

**Issue by senff** [Automattic/woocommerce-payments#4966]
### Description
It might be helpful to have some sort of simple account history page within the **Payments** settings that includes the _balance_ at any given point in time, much like a bank statement.

A rough concept would be something like this:

```
Jul 11 - order 123     +£18.48   - BALANCE:  £18.02
Jul 15 - order 125     +£10.09   - BALANCE:  £27.77
Jul 19 - payout        -£18.02   - BALANCE:   £9.75
Jul 22 - payout         -£9.75   - BALANCE:   £0.00
Jul 31 - order 135     +£38.89   - BALANCE:  £38.15
Aug 3  - order 138     +£11.29   - BALANCE:  £49.08
Aug 6  - order 141     +£14.89   - BALANCE:  £63.56
Aug 9  - payout        -£38.15   - BALANCE:  £25.41
Aug 10 - payout        -£10.93   - BALANCE:  £14.48
Aug 10 - order 151     +£45.74   - BALANCE:  £44.90
Aug 17 - payout of     -£44.90   - BALANCE:   £0.00
Sep 4  - dispute 135   -£38.89   - BALANCE: -£54.63
Sep 11 - order 154    +£115.20   - BALANCE:  £59.50
```

Etc.

**Comment by RadoslavGeorgiev** [comment]
Hey @senff,

thank you for the idea, but the way it is right now, this issue will probably not get much attention on GitHub. Would you mind P2-in this, so it could get wider discussion? Issues here need to either be fully defined (including design) and ready to implement, or at the worst they should require minor design input. With this being a whole separate page, it will not appear on anyone's radar.

**Comment by jbordonado** [comment]
Hi @senff,

I'm wondering if you had time to open a discussion on a P2. As explained above, this issue cannot move until we have a bit more clarity on it.

Thanks!

**Comment by senff** [comment]
@RadoslavGeorgiev @jbordonado Which P2 would be most suitable for this? I wouldn't think it's relevant for +woosupport since it doesn't really need a full-on discussion from HEs (as it is just an idea/suggestion)?

**Comment by jbordonado** [comment]
+wcpay seems like the right place for this

**Comment by csmcneill** [comment]
@senff @jbordonado Even though the links didn't direct to specific posts, I removed the P2 links from y'all's comments per PCYsg-5Xx-p2

**Comment by achyuthajoy** [comment]
Closing the issue against P2 - paJDYF-6yd-p2. Feel free to re-open if required.
