### ISSUE TITLE
[Deposits UI] Instant deposit UI is broken when balance is negative (deposit should not be available?)

### ISSUE THREAD

**Issue by anu-rock** [Automattic/woocommerce-payments#4968]
### Describe the bug

When a merchant's account has a negative available balance, clicking the "Instance deposit" button may show a confirmation dialog with figures that are not consistent with ones for "Pending balance" and "Next deposit" on the Overview and Deposits pages.

Also, it should not be possible to process an instant deposit in case of a negative balance. But that happened in 5632282-zd-woothemes. I see there's already an issue created for this at #3302.

### Expected behavior

When an account has a negative balance:

* Instant deposit should not be possible.
* Instant deposit confirmation dialog should either show correct figures ($0) or show a message saying that the deposit is not possible.

### Actual behavior

* Instant deposit was processed successfully.
* Instant deposit confirmation dialog popped up and showed unexpected values.

### Screenshots

<img width="400" alt="image" src="https://user-images.githubusercontent.com/1288616/197194430-6f45d19e-7050-4072-b157-cb737ff435b6.png">

<img width="426" alt="image" src="https://user-images.githubusercontent.com/1288616/197194552-2be763bf-3afa-4c1e-99cf-2988d5f890ef.png">

### Additional context

 See 5632282-zd-woothemes.

**Comment by nagpai** [comment]
Since the merchant with a negative balance cannot get an instant deposit, will it be simpler to hide the `Instant Deposit` button when the account has a negative balance? Maybe we should weigh in our colleagues from UI ?

The gross mismatch of the balance values is certainly a mystery.

**Comment by nagpai** [comment]
From what I see in [the documentation](p1667878267114779/1667877001.033109-slack-C02C00HCJ8J), ( and even as a commonly expected behavior ), the button should appear grayed if the balance is zero or negative.

**Comment by nagpai** [comment]
I was able to replicate the issue partially ( account showing zero Instant Deposit balance ), thanks to guidance from @shendy-a8c !  Observations: 

* The instant deposit button seems to show up, despite available deposit balance shown as zero. 
* The modal popup seems to show the amount of only the first transaction that is pending to be paid, and hence shows a smaller amount. ( check attached screenshots below) . 

<details> <summary> Screenshots and Details: </summary>
1. Modal showing incorrect balance. 

![image](https://user-images.githubusercontent.com/4162931/200486497-82ca151c-30b4-43e6-8825-b73b3f12efb2.png)

2. Props passed on to the `InstantDepositButton` component shows only the first of three transactions passed on 

```
{
  "instantBalance": {
    "amount": 17448,
    "currency": "usd",
    "fee": 262,
    "fee_percentage": 1.5,
    "net": 17186,
    "transaction_ids": [
      "txn_3M005r2HhhQOy7Ek11CBh0eo"
    ]
  }
}
```

![image](https://user-images.githubusercontent.com/4162931/200486867-a07a3ef6-a1f3-4f52-a98b-e35e2571f595.png)

</details>

**Comment by anu-rock** [comment]
@nagpai This is useful information, thanks! The issue is, at least, out of the mystical realm now.

**Comment by nagpai** [comment]
@anu-rock - Thanks! I was wanting to test this further by checking what is the output of Stripe API, via Postman, but I am unable to get my hands on the secret keys of my connected account in the test instance. :(.

**Comment by drwpcom** [comment]
The user in 5741672-zen shared some screenshots. The error message they faced is "error creating instant deposit". Their overview showed a negative balance after that error appeared.

**Comment by haszari** [comment]
We should tidy this up as maintenance or in the upcoming project.

**Comment by souravdebnath1986** [comment]
This is not a bug i.e. expected behavior. For instant deposits, the funds to deposit can come out of the available + pending balance i.e. total balance. In the example above, the total balance is $267. So the instant deposits allowed should be that amount (as it's less than the daily $1000 limit). Stripe docs aren't super clear about this but something we found out from Stripe in a call.
