### ISSUE TITLE
WooPay OTP modal and redirection taking place in WP admin customize page

### ISSUE THREAD

**Issue by a-danae** [Automattic/woocommerce-payments#4985]
### Describe the bug
The platform checkout OTP modal shows up on the WP admin customize page. Also, the WooPay redirection takes place if you're already authenticated.

### To Reproduce

1. Log in with your admin user on the merchant store
2. Make sure the email address you use for checking out with your admin user is registered in WooPay, and that WooPay is enabled in the store
3. Add a product to your cart
4. Go to your WP dashboard, then go to the customize page ( yoursite.com/wp-admin/customize.php )
5. While customizing, navigate to the checkout page
6. Wait for a bit, and notice that the OTP modal (and redirection if you're authenticated) takes place

### Actual behavior
WooPay OTP modal and redirection take place on the wp admincustomize page.

### Screenshots

https://user-images.githubusercontent.com/41606954/197535541-965cac22-9cb0-452f-b691-3167e883a428.mp4

### Expected behavior
The OTP modal and redirection shouldn't happen when on the customize page.

**Comment by pierorocca** [comment]
Thanks Danae!

**Comment by pierorocca** [comment]
@ralucaStan curious to know if this may occur with checkout blocks customization and WooPay.

**Comment by ralucaStan** [comment]
I couldn't replicate the bug on my testing site on the classic checkout. And it does not happen on the page with the Checkout Block.
