### ISSUE TITLE
Feature Request: Add setting to change payment gateway title

### ISSUE THREAD

**Issue by maxlaf** [Automattic/woocommerce-payments#5007]
### Description

Currently, when UPE is enabled and 2 or more payment methods are activated in WooCommerce Payments, the title at checkout changes from "Credit card / debit card" to "Popular Payment Methods". This was a feature added in #2530

However, some merchants have expressed their dissatisfaction with the wording of "Popular Payment Methods". This can be changed with a plugin like Loco Translate, but it would be great to have a setting to change the frontend gateway title.

### Additional Details

Mentioned in: 3407390-hc and 7363559-hc

**Comment by maxlaf** [comment]
For more context, using Loco Translate with WCPay requires some additional steps. Creating a new translation in the "Custom" location won't display any changes that are made in that translation. A second translation in the "System" location (left unchanged) also has to be created. From [Loco's troubleshooting guide](https://localise.biz/wordpress/plugin/faqs/custom-folder#jit) it appears that WCPay uses automatic text domain loading. 

This creates an additional barrier for merchants trying to translate/change text in WCPay. Since Loco Translate is often recommended for changing the text in various plugins, and WooCommerce Payments deviates from the norm, this may also warrant opening a second enhancement request if that's something we'd like to explore changing.

The proposed setting would provide merchants with an easy way to change a highly-visible piece of text displayed to customers.

**Comment by csmcneill** [comment]
6235168-zen

**Comment by francoishvz** [comment]
6465477-zen

**Comment by grig-23** [comment]
7472815-zen - we've got a merchant who was having a hard time translating the "Credit card / debit card" text. Adding a translation/language to the "System" location in Loco Translate did the trick. By the way, it doesn't have to be a second one - just one language translation in the "system" location is enough.

**Comment by grig-23** [comment]
Another merchant in 7434394-zd-a8c asked us to make sure that the translation works with Loco Translate out of the box.

**Comment by pierorocca** [comment]
Closing as this design has been sunset and replaced with an accordian style payments list.
