### ISSUE TITLE
Display information if WCPay is active alongside another Stripe-powered gateway

### ISSUE THREAD

**Issue by csmcneill** [Automattic/woocommerce-payments#5015]
### Description
When WCPay is active alongside another Stripe-powered gateway, including but not limited to [Stripe](https://woocommerce.com/products/stripe/?aff=10486&cid=1131038), it can cause some issues ([relevant doc](https://woocommerce.com/document/can-i-use-woocommerce-payments-and-the-stripe-plugin-at-the-same-time/)), but it can also lead to general confusion for merchants, especially when trying to track down deposits.

If we could find a way to inform merchants that multiple Stripe-powered gateways that are active at the same time _while also boosting WCPay_, it could:

1. Increase adoption/usage of WCPay
2. Increase conversions via WCPay
3. Reduce support inquiries
4. Create a better merchant experience
5. Create a better customer experience.

### Additional context
37652122-hc
p1666948356627279-slack-C3NCP7ZJ6

**Comment by pierorocca** [comment]
Closing as we've implement duplicate detection within WooPayments and in the future this will be implemented at the Core level.
