### ISSUE TITLE
Enhance My Account section to render and fully function payment gateways on subpages

### ISSUE THREAD

**Issue by FangedParakeet** [Automattic/woocommerce-payments#5023]
### Description
This issue ensures that payment gateways are being rendered and fully functional in different smaller pages within the _My account_ on the merchant site. Pages to cover: 

1. _Orders -> Pay_ (for order)
2. _Subscriptions_ -> _Change payment_
3. _Payment methods_ -> _Add payment method_

For the first two pages, the ultimate goal of this issue is to ensure that users can both add a new payment method or choose from the saved payment methods list. For the third page, the goal is to ensure that users can add new payment methods.

### Acceptance criteria
* Should be able to successfully complete order and transaction from Pay for Order page by using the saved payment method or a new one.
* Should be able to successfully add a new payment method 
* Should be able to successfully change the payment method for the existing subscription by choosing the saved payment method or adding a new one

### Engineering notes
[The MVC of the deferred intent UPE](https://github.com/Automattic/woocommerce-payments/pull/5869) was implemented for the shortcode in `stripe-checkout.js`. When working on this issue, creating separate scripts per subpage is highly recommended to avoid one script being responsible for multiple things and thus increase code readability. If separate scripts like `pay-for-order-handler.js`/`add-payment-method.js` or similar will be created, the `stripe-checkout.js` should be better renamed to `shortcode-checkout.js`. 

Another hint would be to look for possible common areas between `stripe-checkout.js` and newly created scripts for _My account_ subpages. If common areas will be found - try to merge them into one place.

**Comment by FangedParakeet** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Heisenberg-63586f2ec60359001310fa6a/issues/Automattic/woocommerce-payments/5023?planning-poker) with Zenhub @mdmoore @timur27

**Comment by timur27** [comment]
I gave it a `3` because of the amount of screens that need to be addressed within this issue. Also, compared to [this issue](https://app.zenhub.com/workspaces/heisenberg-63586f2ec60359001310fa6a/issues/gh/automattic/woocommerce-payments/6227) which is estimated for 2SP, _**My account**_ section related issue seems to be more complex. 


@FangedParakeet could you share your opinion on why you gave 2SP so that we could align and maybe you can convince us. Thank you!

**Comment by FangedParakeet** [comment]
>1. Orders -> Pay (for order)

This will be completed in #5808, so can be ignored here.

 >2. Subscriptions -> Change payment
>3. Payment methods -> Add payment method

These are two separate screens, but I believe they basically use the same implementation.

I estimated one point for an investigation and another for the solution, though I can readily add one more, as I'd expect the solution here would likely be a little more involved than the pleasantly petite one-liner in the issue you linked. Raising my estimate to `3` points, to settle the score. 👍

**Comment by timur27** [comment]
Thanks for the alignment! 

> Orders -> Pay (for order)
This will be completed in #5808, so can be ignored here.

I'm unsure if **_Pay for order_** page will be covered by #5808. Currently, we don't have any deferred intent creation implementation for this screen, and https://github.com/Automattic/woocommerce-payments/pull/6177 seem not to introduce it, so the working _**Pay for order**_ page with the deferred intent creation will be the result of https://github.com/Automattic/woocommerce-payments/issues/5023, I guess. It shouldn't be a complex task, but I mention it to align on the scope.

**Comment by FangedParakeet** [comment]
> I'm unsure if Pay for order page will be covered by https://github.com/Automattic/woocommerce-payments/issues/5808. Currently, we don't have any deferred intent creation implementation for this screen, and https://github.com/Automattic/woocommerce-payments/pull/6177 seem not to introduce it

Whoops, you're absolutely right: I wrote #6177 and I'm not sure why I thought it would solve this issue for the deferred UPE as well. @timur, do you think solving the Pay for Order page should be included in this issue or should we create a new one? I'm partial to the latter, because I don't see very much overlap in the implementation of saved payment methods and the pay for order checkout. Let me know your thoughts--if you agree, I'll create a new issue and drag it into the sprint.

**Comment by timur27** [comment]
Thanks, Samir, I think it's an excellent opportunity to work on all three screens (including the _Pay for order_ page) within this issue. The main reason is that the implementation could be the same in many places, allowing us to create a reusable solution for all three screens. I'll shortly update the description to include _Pay for order_ as well, but I'm happy to continue the discussion in case there are some points that still need alignment, in your opinion. 👍

**Comment by FangedParakeet** [comment]
> think it's an excellent opportunity to work on all three screens (including the Pay for order page) within this issue.

So shall it be written, so shall it be done. 👍
