### ISSUE TITLE
Streamline UPE/non-UPE code branching and eliminate UPE feature flag checks

### ISSUE THREAD

**Issue by FangedParakeet** [Automattic/woocommerce-payments#5028]
### Description
This issue is to be tackled post `6.7.0` release, once all the merchants are migrated to the split UPE with deferred intent creation. The further description is based on this assumption. 

We have four different gateway approaches in the plugin: 
* legacy card
* legacy UPE
* split UPE
* deferred intent creation UPE

The first three are not used anymore. At the same time, there are a lot of places in the code where we check which flag out of these above is enabled and execute the flow according to it. This means that we need to remove all the UPE-related code branching other than deferred UPE.

Acceptance criteria
* eliminate all branching where any of the following is a part: `is_upe_deferred_intent_enabled()`, `is_upe_split_enabled()`, `is_upe_legacy_enabled()` by keeping only the code related to the deferred intent creation UPE
* remove `is_upe_deferred_intent_enabled()`, `is_upe_split_enabled()` and `is_upe_legacy_enabled()` located in `class-wc-payments-features.php`, as well as clean up all the areas that depend on those checks
* improve test coverage wherever possible

**Comment by frosso** [comment]
Discussed internally - We're going to clean this up gradually in multiple PRs.

So we'll likely clean up each version of the UPE, one by one.
- Legacy card
- Split UPE
- Legacy UPE (likely last - it has a larger impact)
- Logic related to the Deferred Intent UPE feature flag (Deferred Intent UPE is the winner)
