### ISSUE TITLE
Pre-fill dispute evidence form fields

### ISSUE THREAD

**Issue by dechov** [Automattic/woocommerce-payments#504]
Use order details to pre-fill as many dispute evidence fields as possible, and perhaps the product type selector as well.

(See https://github.com/Automattic/woocommerce-payments/pull/500#pullrequestreview-370647844 for initial discussion.)

**Comment by vbelolapotkov** [comment]
Worth discussing the issue details with design team first.

**Comment by LevinMedia** [comment]
@vbelolapotkov generally I'm in favor of pre-filling as much as possible, although given what we know or don't about an order / shipping details, I'm not sure how much more we'll be able to pre-fill than what we're already doing. 

If an order is disputed with only a single product, we could pre-fill product information from the store's product description. Having universal shipping statuses and information in core would allow us to pre-fill additional information, but for now, that information could be coming from any number of sources, so it's going to be a challenge to get anything meaningful.

**Comment by vbelolapotkov** [comment]
@LevinMedia taking into account number of dispute reasons and lack of clarity what/how can be pre-filled this issue looks like high effort - low impact, so I'd close it for now and reopen ones there is a higher need from merchants. WDYT?

**Comment by LevinMedia** [comment]
Sounds good 👍
