### ISSUE TITLE
Warning modal when deactivating Subscriptions extension not working

### ISSUE THREAD

**Issue by aheckler** [Automattic/woocommerce-payments#5047]
### Describe the bug

In [#3061](https://github.com/Automattic/woocommerce-payments/pull/3061), @james-allan introduced a modal warning which should appear when WC Pay and the standalone Subscriptions extension are both installed, and Subscriptions is then deactivated by the merchant.

The JS that triggers the modal warning is broken though, which means it's not getting triggered now.

### To Reproduce

1. Start with a WC Pay test site. The built-in subscriptions functionality is enabled by default I believe.
2. Install the standalone Subscriptions extension.
3. Deactivate Subscriptions.
4. This should trigger the modal, but it does not.

### Additional context

I think the issue is that `plugin-page.js` is looking at the wrong ID:

https://github.com/Automattic/woocommerce-payments/pull/3061/files#diff-bbcb91becd2b5c1093d379f1224a9af0df4a7a106d6816d635a1d5fbe7d5a685

The ID for the "Deactivate" link for Subscriptions is now: `deactivate-woocommerce-com-woocommerce-subscriptions`.

We should probably check all the IDs just to be safe?

If possible, can we also update the actual modal copy to the following?

> By deactivating the **WooCommerce Subscriptions** plugin, your store will switch to using the subscriptions functionality **built into WooCommerce Payments**. Existing subscriptions will [renew manually](https://woocommerce.com/document/subscriptions/renewal-process/#section-4), meaning that subscribers will need to log in to pay for renewal. Access to the advanced features of the Subscriptions extension will be removed. [Learn more.](http://woocommerce.com/document/subscriptions/deactivation/)

**Comment by nagpai** [comment]
I am unable to replicate the bug, and see the modal correctly 

![image](https://user-images.githubusercontent.com/4162931/200477049-4baf775d-f5de-4974-9253-99d6b20c14fa.png)

>The ID for the "Deactivate" link for Subscriptions is now: deactivate-woocommerce-com-woocommerce-subscriptions.

The [ID of the `Deactivate` link](https://github.com/Automattic/woocommerce-payments/commit/b94323e9b5f5b22144db579b812fd701d9b27797#diff-bbcb91becd2b5c1093d379f1224a9af0df4a7a106d6816d635a1d5fbe7d5a685R6),  seems to be`deactivate-woocommerce-subscriptions`, and matches with what appears on the WP Admin Plugins page.

https://github.com/Automattic/woocommerce-payments/commit/b94323e9b5f5b22144db579b812fd701d9b27797#diff-bbcb91becd2b5c1093d379f1224a9af0df4a7a106d6816d635a1d5fbe7d5a685R6

(edited my earlier reply to add the correct link)

**Comment by james-allan** [comment]
> The ID for the "Deactivate" link for Subscriptions is now: deactivate-woocommerce-com-woocommerce-subscriptions.

If you're seeing that deactivate button ID then you might have a version of subscriptions where the file isn't just `woocommerce-subscriptions`. 🤔

**Comment by kalessil** [comment]
@james-allan, in your opinion, could @nagpai tackle it (you probably have to share more context) or it'd be better if Helix takes care of the issue?

**Comment by aheckler** [comment]
Interesting finding @nagpai @james-allan @kalessil: I cannot reproduce the issue on Jurassic Ninja, but I *can* repro on Pressable. The "Deactivate" link IDs are different, even though I installed Subscriptions on both sites using the same ZIP file downloaded from WooCommerce.com. 

On JN, the ID is `deactivate-woocommerce-subscriptions`, and the modal is properly triggered. On Pressable, the ID is `deactivate-woocommerce-com-woocommerce-subscriptions`, and the modal is *not* triggered.

Is it possible this is only affecting Pressable sites?

**Comment by aheckler** [comment]
Actually, shoot, after more testing I cannot reproduce on new Pressable sites, only my existing one... 🤷‍♂️ Sorry to bother y'all with this I guess. :(

Still, it would be nice to change the copy in the modal to:

> By deactivating the **WooCommerce Subscriptions** plugin, your store will switch to using the subscriptions functionality **built into WooCommerce Payments**. Existing subscriptions will [renew manually](https://woocommerce.com/document/subscriptions/renewal-process/#section-4), meaning that subscribers will need to log in to pay for renewal. Access to the advanced features of the Subscriptions extension will be removed. [Learn more.](http://woocommerce.com/document/subscriptions/deactivation/)

**Comment by nagpai** [comment]
>Actually, shoot, after more testing I cannot reproduce on new Pressable sites, only my existing one... 🤷‍♂️ Sorry to bother y'all with this I guess. :(

No bother at all, Adam! It made me more familiar with the code.  :)

@kalessil - For the copy changes suggested by Adam, from whom do we get an okay/ review  before adding the changes?

**Comment by kalessil** [comment]
@nagpai, at least from @aheckler 's team =) IMO we are good to update the copy (also for context Adam often updates WCpay public docs).

**Comment by nagpai** [comment]
>at least from @aheckler 's team =)

:blushing and facepalm simultaneous:  - Sorry @aheckler! 

Will submit a PR in a moment :)
