### ISSUE TITLE
Date picker for applicable dispute evidence fields

### ISSUE THREAD

**Issue by dechov** [Automattic/woocommerce-payments#505]
The `shipping_date` and `service_date` fields were marked as "date" inputs, but (ahead of support for this field type) are using "text" inputs.

The `@woocommerce/components` package has a `<DatePicker>` [[README](https://github.com/woocommerce/woocommerce-admin/tree/master/packages/components/src/calendar#datepicker)] that should fit.

**Comment by oaratovskyi** [comment]
@dechov I've used native date input for that, integrating `DatePicker` was difficult, as it requires additional code inside the `DatePicker`.
