### ISSUE TITLE
[Authorizations] Hide the Uncaptured tab when manual capture setting is unchecked

### ISSUE THREAD

**Issue by anu-rock** [Automattic/woocommerce-payments#5051]
### Description

The "Uncaptured" tab on the page **WP Admin** → **Payments** → **Transactions** should not be visible if manual capture is not enabled in Payments settings.

![image](https://user-images.githubusercontent.com/1288616/199909220-7b882d28-5508-4426-af92-b8fe312dcb4a.png)

### Acceptance criteria

* `manual_capture` setting controls the visibility of Uncaptured tab

#### PHP
```php
if ( $this->wcpay_gateway->get_option( 'manual_capture' ) === 'yes' ) {
    // show Uncaptured tab
}
```

#### JavaScript
https://github.com/Automattic/woocommerce-payments/blob/fdd82d4c8d120c7b7c413db446ee99f5cb664ed3/client/data/settings/hooks.js#L305-L319

**Comment by kalessil** [comment]
ping @mgascam
