### ISSUE TITLE
"Update business details" task card needs more details and context

### ISSUE THREAD

**Issue by daquinons** [Automattic/woocommerce-payments#5069]
### Describe the bug
Currently, we are showing the "Update business details" when the account is going to be restricted soon, and we redirect the users to the Stripe dashboard. This can be frustrating as we are not telling them what they need to change or why. See feedback p1666364090349799-slack-C01BPL3ALGP

We should be using:
- [requirements.errors.reason](https://stripe.com/docs/api/accounts/object#account_object-requirements-errors-reason): An informative message that indicates the error type and provides additional details about the error.
- [requirements.errors.suggestion.message](https://stripe.com/docs/api/accounts/object#account_object-requirements-errors-suggestion-message): An informative suggestion on how the user can resolve the error.

### To Reproduce

1. Go to Stripe Dashboard
2. Change the SSN on an account
3. See the "Update business details" card appear

### Actual behavior
The task card doesn't provide any information on why or what needs to be done.

### Expected behavior
Following the example, when modifying the SSN,`requirements.errors.reason` says `"The tax ID on the account has changed. Please accept the terms of service again."`. This text should be presented to the user in the card.

We need to display a descriptive message in the task as a subtitle
![image](https://user-images.githubusercontent.com/2612426/200825490-2451433a-2d99-4ad8-98bc-ebbde9ca5ff8.png)

For that, the scope of the issue also includes testing different errors and account statuses to see if we should display `requirements.errors.reason` or `requirements.errors.suggestion.message` as a subtext of the task.

**Comment by elizaan36** [comment]
Thanks @daquinons for creating the issue! 

A couple questions: 
- Do you think the message will be clear enough for the merchant to know what to do when the task directs them to the Stripe dashboard? 
- Is there logic to make sure the task will be completed for every scenario once they update the information correctly?

> It’d be worth testing some of the most common scenarios where an account has pending/overdue requirements to see what these messages return.

As Eric mentioned in Slack, it would be great to see what the error messages look like for `requirements.errors.reason` and `requirements.errors.suggestion` to see how this can be presented to merchants. 

One option is to use the descriptive text in the task like this, if the message returned is actionable and clear.
<img width="1368" alt="Screen Shot 2022-11-08 at 5 06 03 PM" src="https://user-images.githubusercontent.com/5121465/200696064-0a03238a-09f0-4e6e-a31b-4d9d1ffeb986.png">

**Comment by daquinons** [comment]
@elizaan36 
> Do you think the message will be clear enough for the merchant to know what to do when the task directs them to the Stripe dashboard?

Yes! Seems like they are very user-friendly and not the typical "Error: Info Changed" that an API would give, so I'd say they are precisely given for this use case. I'm going to add into the scope some verification and testing to decide if we use `reason` or `suggestion`, in order to display one or another in the subtext of the task following your mockup.

> Is there logic to make sure the task will be completed for every scenario once they update the information correctly?

Yes, all the verification pending info comes in the account, and we check it every time that we display the cards. So if we've ever displayed the "Update business details" task, we continue to display it but completed (see original issue https://github.com/Automattic/woocommerce-payments/pull/1799 ). The task is completed when we displayed it once and now the status of the account doesn't have `restricted_soon` or `restricted`. For reference, that happens here https://github.com/Automattic/woocommerce-payments/blob/8cb0e930add4d4371d6e32fd7224f3d967a8d397/client/overview/task-list/tasks.js#L23

EDIT: I just thought about translations 🤔 If we display them coming directly from the API response we are not going to be able to add them as labels for the translators to pick them up. That might be an issue.

**Comment by elizaan36** [comment]
Thanks all sounds good. 

Good call about the translators, is there any way to translate an API response before it gets shown in the UI?

**Comment by dmallory42** [comment]
I have been taking a look at this and wanted to add some thoughts.

I think this may be a little tricky, given how we currently show the "Update Business Details" task. As a test, I updated the SSN of an account, which triggered a few account issues which needed to be resolved. I wanted to see what messages appeared. I am able to see them in the `requirements.errors.reason` field. As far as I can see `[requirements.errors.suggestion.message](https://stripe.com/docs/api/accounts/object#account_object-requirements-errors-suggestion-message)` is not returned, nor can I find it in the API. Perhaps this is a field available in a different API version, or using a different account type?

This is what I saw returned after removing SSN:

<img width="1614" alt="Screenshot 2022-12-19 at 16 50 28" src="https://user-images.githubusercontent.com/11770181/208477712-108bbc37-fd25-492f-a305-3dd4eb8d9a6f.png">

The issue we have is that an account can have multiple errors at once, and as you can see in the screenshot, the message for some of these errors can be the same. It looks like the TOS need to be re-accepted after updating SSN, so I see the `The tax ID on the account has changed. Please accept the terms of service again.` message twice, once for the `tos.date` field, and once for the `tos.ip` field. 

It looks like with the "Update Business Task" we'd only have space for one sentence. So I guess my question is, how do we decide which error to show if there are multiple? Do we just show the first one? 

There's also the issue of translations if we just take the message directly from Stripe. We do have some Stripe documentation on the error messages, we could potentially use this to build our own error messages (which would then be translatable) - the issue here is that Stripe could add or change error messages, and we'd then be out of sync. But it's an option, if we want to at least cover the most common cases. I've listed Stripe's own descriptions of each error code below.

Could you let me know how you'd like me to proceed with this issue please, @elizaan36? 🙂 

```
invalid_address_city_state_postal_code
The combination of the city, state, and postal code in the provided address could not be validated.

invalid_street_address
The street name and/or number for the provided address could not be validated.

invalid_tos_acceptance
The existing terms of service signature has been invalidated because the account’s tax ID has changed. The account needs to accept the terms of service again. For more information, see [this documentation](https://stripe.com/docs/connect/update-verified-information).

invalid_value_other
An invalid value was provided for the related field. This is a general error code.

invalid_representative_country
The representative must have an address in the same country as the company.

verification_document_address_mismatch
The address on the document did not match the address on the account. Upload a document with a matching address or update the address on the account.

verification_document_address_missing
The company address was missing on the document. Upload a document that includes the address.

verification_document_corrupt
The uploaded file for the document was invalid or corrupt. Upload a new file of the document.

verification_document_country_not_supported
The provided document was from an unsupported country.

verification_document_dob_mismatch
The date of birth (DOB) on the document did not match the DOB on the account. Upload a document with a matching DOB or update the DOB on the account.

verification_document_duplicate_type
The same type of document was used twice. Two unique types of documents are required for verification. Upload two different documents.

verification_document_expired
The document could not be used for verification because it has expired. If it’s an identity document, its expiration date must be after the date the document was submitted. If it’s an address document, the issue date must be within the last six months.

verification_document_failed_copy
The document could not be verified because it was detected as a copy (e.g., photo or scan). Upload the original document.

verification_document_failed_greyscale
The document could not be used for verification because it was in greyscale. Upload a color copy of the document.

verification_document_failed_other
The document could not be verified for an unknown reason. Ensure that the document follows the [guidelines for document uploads](https://stripe.com/docs/connect/identity-verification-api#acceptable-verification-documents).

verification_document_failed_test_mode
A test data helper was supplied to simulate verification failure. Refer to the documentation for [test file tokens](https://stripe.com/docs/connect/testing#test-file-tokens).

verification_document_fraudulent
The document was identified as altered or falsified.

verification_document_id_number_mismatch
The company ID number on the account could not be verified. Correct any errors in the ID number field or upload a document that includes the ID number.

verification_document_id_number_missing
The company ID number was missing on the document. Upload a document that includes the ID number.

verification_document_incomplete
The document was cropped or missing important information. Upload a complete scan of the document.

verification_document_invalid
The uploaded file was not one of the valid document types. Ensure that the document follows the [guidelines for document uploads](https://stripe.com/docs/connect/identity-verification-api#acceptable-verification-documents).

verification_document_issue_or_expiry_date_missing
The issue or expiry date is missing on the document. Upload a document that includes the issue and expiry dates.

verification_document_manipulated
The document was identified as altered or falsified.

verification_document_missing_back
The uploaded file was missing the back of the document. Upload a complete scan of the document.

verification_document_missing_front
The uploaded file was missing the front of the document. Upload a complete scan of the document.

verification_document_name_mismatch
The name on the document did not match the name on the account. Upload a document with a matching name or update the name on the account.

verification_document_name_missing
The company name was missing on the document. Upload a document that includes the company name.

verification_document_nationality_mismatch
The nationality on the document did not match the person’s stated nationality. Update the person’s stated nationality, or upload a document that matches it.

verification_document_not_readable
The document could not be read. Ensure that the document follows the [guidelines for document uploads](https://stripe.com/docs/connect/identity-verification-api#acceptable-verification-documents).

verification_document_not_signed
A valid signature is missing on the document. Upload a document that includes a valid signature.

verification_document_not_uploaded
No document was uploaded. Upload the document again.

verification_document_photo_mismatch
The document was identified as altered or falsified.

verification_document_too_large
The uploaded file exceeded the 10 MB size limit. Resize the document and upload the new file.

verification_document_type_not_supported
The provided document type was not accepted. Ensure that the document follows the [guidelines for document uploads](https://stripe.com/docs/connect/identity-verification-api#acceptable-verification-documents).

verification_failed_address_match
The address on the account could not be verified. Correct any errors in the address field or upload a document that includes the address.

verification_failed_business_iec_number
The Importer Exporter Code (IEC) number could not be verified. Correct any errors in the company’s IEC number field. (India only)

verification_failed_document_match
The document could not be verified. Upload a document that includes the company name, ID number, and address fields.

verification_failed_id_number_match
The company ID number on the account could not be verified. Correct any errors in the ID number field or upload a document that includes the ID number.

verification_failed_keyed_identity
The person’s keyed-in identity information could not be verified. Correct any errors or upload a document that matches the identity fields (e.g., name and date of birth) entered.

verification_failed_keyed_match
The keyed-in information on the account could not be verified. Correct any errors in the company name, ID number, or address fields. You can also upload a document that includes those fields.

verification_failed_name_match
The company name on the account could not be verified. Correct any errors in the company name field or upload a document that includes the company name.

verification_failed_residential_address
We could not verify that the person resides at the provided address. The address must be a valid physical address where the individual resides and cannot be a P.O. Box.

verification_failed_tax_id_match
The tax ID on the account cannot be verified by the IRS. Either correct any possible errors in the company name or tax ID, or upload a document that contains those fields.

verification_failed_tax_id_not_issued
The tax ID on the account was not recognized by the IRS. Refer to the support article for [newly-issued tax ID numbers](https://support.stripe.com/questions/newly-issued-us-tax-id-number-tin-not-verifying).

verification_failed_other
Verification failed for an unknown reason. Correct any errors and resubmit the required fields.

verification_missing_owners
We have identified owners that haven’t been added on the account. Add any missing owners to the account.

verification_missing_executives
We have identified executives that haven’t been added on the account. Add any missing executives to the account.

verification_requires_additional_memorandum_of_associations
We have identified holding companies with significant percentage ownership. Upload a Memorandum of Association for each of the holding companies.

invalid_dob_age_under_18
Underage. Age must be at least 18.
```

**Comment by dmallory42** [comment]
Chatted on Slack with @elizaan36 about this, she suggested using a modal popup could be a good way to capture this information and display it to users, and will take a look at some designs. Will circle back on this issue once that's ready!

**Comment by elizaan36** [comment]
hey @dmallory42, Would it be possible to only present the modal when there's more than one error message? If we could detect that there's only one error and present the error string text in the task that would be ideal (as shown in the screenshot in the first comment on this issue.)

I think all of the error messages are useful except for this one:

> invalid_value_other
An invalid value was provided for the related field. This is a general error code.

Not sure what merchants would know what to do in that case.

When multiple notices are present, the modal could be shown from a "More details" link in the body text of the task. The task title and link wouldn't change.

<img width="737" alt="Screen Shot 2023-01-03 at 2 19 21 PM" src="https://user-images.githubusercontent.com/5121465/210426240-f4db32da-fc73-43b7-a828-fa42d65f5126.png">

<img width="1440" alt="Payments Overview - Multiple notices modal" src="https://user-images.githubusercontent.com/5121465/210426396-86ffcfe5-3ade-4d64-93c2-53ad5875932d.png">

- There are two task types - Restricted and Restricted soon
- The task appears on WooCommerce Home as well as the Payments Overview screen. 
- The modal copy reflects the state of the account (Restricted or Restricted soon) using similar copy to what appears on the task.
- The modal CTA directs to the Stripe dashboard

All use cases and designs are in Figma, will share the link in Slack.

**Comment by dmallory42** [comment]
Hey @elizaan36, thanks for working on these designs! I think this should be possible, I will make some preliminary tests to make sure, and then let you know if this workflow will be possible.
