### ISSUE TITLE
"Learn more" link for Express Checkouts is wrong

### ISSUE THREAD

**Issue by aheckler** [Automattic/woocommerce-payments#5083]
### Describe the bug

This link:

![Screenshot taken on 2022-11-09 at 12 44 13 UTC@2x](https://user-images.githubusercontent.com/5512652/200833583-828e2cb8-cb7a-4f1a-a965-ab09b9c5f612.png)

... should go here: `https://woocommerce.com/document/payments/settings-guide/#section-4`

It currently points to `https://woocommerce.com/document/payments/#section-13`, which was likely correct at the time the PR was drafted, but is no longer correct as of the Startup Guide revamp.

### To Reproduce

1. Set up WC Pay on a test site.
2. Click that link.
3. Your just taken to the Startup Guide, not anywhere specific to express checkout methods.

Destination should be: https://woocommerce.com/document/payments/settings-guide/#section-4

**Comment by kalessil** [comment]
@nagpai, this looks like an easy fix. Can you create a PR tomorrow, please to get this fixed? Thanks!
