### ISSUE TITLE
Non-admin users cannot access the dashboard

### ISSUE THREAD

**Issue by RadoslavGeorgiev** [Automattic/woocommerce-payments#5096]
### Describe the bug

Users without the `manage_woocommerce` capability are facing fatal errors when trying to access WP Admin:

```
Fatal error: Uncaught Error: Class 'WC_Payments_Admin_Settings' not found in /var/www/html/wp-content/plugins/woocommerce-payments/includes/class-wc-payments-account.php on line 572

Error: Class 'WC_Payments_Admin_Settings' not found in /var/www/html/wp-content/plugins/woocommerce-payments/includes/class-wc-payments-account.php on line 572

Call Stack:
    0.0001     402408   1. {main}() /var/www/html/wp-admin/index.php:0
    0.0001     403656   2. require_once('/var/www/html/wp-admin/admin.php') /var/www/html/wp-admin/index.php:10
    1.1864   16878384   3. do_action() /var/www/html/wp-admin/admin.php:175
    1.1864   16878760   4. WP_Hook->do_action() /var/www/html/wp-includes/plugin.php:517
    1.1864   16878760   5. WP_Hook->apply_filters() /var/www/html/wp-includes/class-wp-hook.php:332
    1.2094   17123008   6. WC_Payments_Account->maybe_redirect_to_onboarding() /var/www/html/wp-includes/class-wp-hook.php:308
```

This is caused by this line:

https://github.com/Automattic/woocommerce-payments/blob/055775044ca09aaa3e1cf85f44b183c33dc75535/includes/class-wc-payments-account.php#L572

it tries to access `WC_Payments_Admin_Settings`, but the class is not present, because of a condition, which only includes it whenever the user can `manage_woocommerce`:

https://github.com/Automattic/woocommerce-payments/blob/055775044ca09aaa3e1cf85f44b183c33dc75535/includes/class-wc-payments.php#L392-L397

### To Reproduce

1. Create a new user without the `manage_woocommerce` capability. This includes all default non-admin roles.
2. Log in with that user's credentials.
3. Navigate to any admin page, including just `/wp-admin`.

### Actual behavior

The error described above is thrown.

### Expected behavior

`wp-admin` should load without issues.

**Comment by amElnagdy** [comment]
5700343-zen

**Comment by thisissandip** [comment]
Linking more reports:


- 5699844-zen
- 5698411-zen
- https://wordpress.org/support/topic/wc_payments_admin_settings-not-found/
- https://wordpress.org/support/topic/there-was-a-problem-redirecting-you-to-the-account-connection-page-2/

**Comment by shendy-a8c** [comment]
Why isn't this issue closed as https://github.com/Automattic/woocommerce-payments/pull/5098 got merged?
Closing...
