### ISSUE TITLE
Optimize the size of the JS bundle

### ISSUE THREAD

**Issue by DanReyLop** [Automattic/woocommerce-payments#511]
Before general availability, we should aim to make our plugin as small and fast as possible. We are currently not enabling [Webpack tree-shaking](https://webpack.js.org/guides/tree-shaking/), so the JS bundle is bigger than it could be. As part of this issue, we should also take a look at other parts of the plugin ZIP that we could remove or make smaller.

**Comment by jessy-p** [comment]
Could the front end guild re-evaluate if this is still relevant. @ismaeldcom  Please close if obsolete.

**Comment by ismaeldcom** [comment]
Thanks for the ping @jessy-p, I think we can close this, I already made some bundle size optimizations. We can always do more, but it will be better to create new and specific issues for that 🙂
