### ISSUE TITLE
WooPay scripts are loaded when the WCPay gateway isn't available

### ISSUE THREAD

**Issue by a-danae** [Automattic/woocommerce-payments#5118]
### Describe the bug
When WCPay is excluded from the available payment methods, WooPay scripts are loaded on the checkout page even though they're not used.

### To Reproduce

1. Enable WooPay
2. Enable [Conditional Shipping and Payments](https://woocommerce.com/products/conditional-shipping-and-payments/)
3. Create a condition to disable WCPay on the checkout page
4. As a shopper, add a product to your cart and go to the checkout page. Make sure the condition you created to disable WCPay is met
5. On the checkout page, notice that WCPay isn't displayed in the available payment gateways
6. Open the browser developer tools -> Network -> search for checkout.js
7. Notice that WooPay scripts (platform-checkout.js) and styles (platform-checkout.css) are loaded

### Actual behavior
WooPay scripts and styles are loaded on the checkout page even though WCPay isn't available.

### Screenshots

WooPay scripts are being loaded.

<img width="1487" alt="image" src="https://user-images.githubusercontent.com/41606954/201481744-46ed5fa0-02d7-40ab-b15d-0ca7214a7e9c.png">

### Expected behavior
WooPay scripts and styles shouldn't be loaded if WCPay isn't available.

**Comment by brettshumaker** [comment]
Noting that, while working on another PR, I noticed that `platform-checkout.js` and `platform-checkout.css` are both loaded on all pages - not just checkout.

**Comment by dbrabyn** [comment]
I'm getting the express checkouts (Apple Pay for sure and Google Pay probably) buttons displaying when the WooCommerce Payments payment gateway is disabled via WC's Conditional Shipping & Payments plugin. Same issue?

I'm using the latest version of both: WooCommerce Payments (5.1.2) and WooCommerce Conditional Shipping and Payments (1.14.4).
