### ISSUE TITLE
Fraud Prevention Fatal Error on Failed Renewal Payments with Subscriptions

### ISSUE THREAD

**Issue by shevene** [Automattic/woocommerce-payments#5127]
### Describe the bug

When subscription renewal payments fail because of a fraudulent reason (blocked by customers bank), a fatal error is logged related to WooCommerce Payments Fraud Prevention:

```
1-13-2022 @ 21:06:53 - scheduled action 284132 (subscription payment retry) failed to finish processing due to the following error: Uncaught TypeError: Argument 1 passed to WCPayFraud_PreventionFraud_Prevention_Service::__construct() must be an instance of WC_Session, null given, called in .../public_html/wp-content/plugins/woocommerce-payments/includes/fraud-prevention/class-fraud-prevention-service.php on line 61 and defined in .../public_html/wp-content/plugins/woocommerce-payments/includes/fraud-prevention/class-fraud-prevention-service.php:47
Stack trace:
#0 .../public_html/wp-content/plugins/woocommerce-payments/includes/fraud-prevention/class-fraud-prevention-service.php(61): WCPayFraud_PreventionFraud_Prevention_Service->__construct()
#1 .../public_html/wp-content/plugins/woocommerce-payments/includes/wc-payment-api/class-wc-payments-api-client.php(2254): WCPayFraud_PreventionFraud_Prevention_Service::get_instance()
#2 .../public_html/wp-
```

Example declined reason given in Stripe:

<img width="321" alt="Screen Shot 2022-11-14 at 7 57 58 pm" src="https://user-images.githubusercontent.com/8490476/201775075-ff41f233-dd0e-450b-8477-f5108c0c36e5.png">

### Expected behavior
Failed renewal payments should not trigger a fatal error.

### Additional context

5709096-zen

**Comment by csmcneill** [comment]
Discussion about this can be found at p1668402895913569-slack-C7U3Y3VMY

**Comment by haszari** [comment]
Tagging in @Automattic/sigma @dwainm – since this is a fatal error in `WCPayFraud_PreventionFraud_Prevention_Service` constructor, might be a quick fix with some defensive code. Let me know if the cause is higher up in subscriptions related code!

**Comment by tpaksu** [comment]
Thanks @haszari! I'll create a quick fix for that.
