### ISSUE TITLE
Test mode cannot be enabled on payment settings in the staging environment

### ISSUE THREAD

**Issue by timur27** [Automattic/woocommerce-payments#5128]
### Describe the bug
When accessing WooCommerce Payments settings (`https://woopaytestplatform.wordpress.com/`) in the staging environment and trying to turn on/turn off the Test mode, an error notice appears on the bottom left. 

<img width="2195" alt="image" src="https://user-images.githubusercontent.com/22319444/201754170-20b90165-91c1-4f15-ba49-5166eea890b1.png">

From the console, we see CORS errors
![image](https://user-images.githubusercontent.com/22319444/201754390-6c686fbe-24c1-42c0-8a3d-0ef77e4c174b.png)

### To Reproduce

1. Go to `Payments->Settings`
2. Check the test mode checkbox
3. See the error on the bottom left and in the console/network tab

### Expected behavior

No error should be shown and a user should be able to configure their settings.

* OS: [e.g. macOS]
* Browser [e.g. Chrome]
* Version [Version 107.0.5304.110]

### Additional context
[Slack conversation](https://a8c.slack.com/archives/C022WMN88KG/p1668447363797939)
WCPay version on the WooPay staging, where the issue occurs: WCPay 4.7.2

**Comment by ricardo** [comment]
Closing with context: p1668457002912569/1668447363.797939-slack-C022WMN88KG
