### ISSUE TITLE
Purchasing a synced subscription with WCPay results in an unsynced subscription record in Stripe Billing

### ISSUE THREAD

**Issue by james-allan** [Automattic/woocommerce-payments#5131]
## Describe the bug

While testing WC Payments Subscriptions with the syncing feature enabled, I discovered an issue where the Stripe Billing subscription wasn't being synced. After investigation, this was caused by the `WC_Payments_Subscription_Service::has_delayed_payment()` function being passed and older subscription object which didn't have the synced meta saved on it (happens during the checkout create subscription process) and so calling `$subscription->get_meta( '_contains_synced_subscription' )` was returning incorrect information.

To fix this and potentially other issues, we need to make sure our `WC_Subscriptions_Checkout::create_subscription()` is fetching the latest copy of the subscription from the database after calling `$subscription->save()`.

## To Reproduce

1. Make sure WC Subscriptions plugin is disabled and WCPay Subscriptions is enabled.
2. While on `trunk` of Subscriptions Core, purchase a synced subscription with WC Payments. In my tests, I purchased a subscription that is synced to the 1st of the month.
3. Check the subscription in Stripe Billing and confirm there's no trial period and the next payment date is not set correctly.

![image](https://user-images.githubusercontent.com/2275145/201841167-82ee290d-fe60-442b-bf51-5df00cd723bb.png)

### Expected behavior

Synced WCPay Subscriptions should be created in Stripe with a trial period to account for the period between start date and first synced payment date.

### Actual behavior

WCPay Subscriptions are created with no synced payment cycle.

**Comment by shendy-a8c** [comment]
Weird that as https://github.com/Automattic/woocommerce-payments/pull/5133 got merged this issue wasn't closed. Closing...
