### ISSUE TITLE
Conflict with Max Mega Menu

### ISSUE THREAD

**Issue by megamenu** [Automattic/woocommerce-payments#5137]
Max Mega Menu needs to load scripts from widgets.php onto the nav-menus.php page, this sometimes duplicates calls depending on how other plugins are coded. In this case, register_payment_scripts() is being called twice. Usually this is not a problem, but on line 431 of class-wc-payments-admin.php 'require_once' is being used. The first time, require_once correctly loads the dependencies array, but the second time, require_once returns null. This is causing the error.

Please can I suggest this change?

Line 431

from:

$script_asset      = file_exists( $script_asset_path ) ? require_once $script_asset_path : [ 'dependencies' => [] ];

to:

$script_asset      = file_exists( $script_asset_path ) ? include $script_asset_path : [ 'dependencies' => [] ];

### Describe the bug
When WooCommerce Payments and Max Mega Menu are installed together, there is a Warning/Error on the nav-menus.php page:

`An error of type E_ERROR was caused in line 558 of the file /home/ubuntu/www.trgfineart.com/wp-content/plugins/woocommerce-payments/includes/admin/class-wc-payments-admin.php. Error message: Uncaught TypeError: array_merge(): Argument #1 must be of type array, null given in /home/ubuntu/www.trgfineart.com/wp-content/plugins/woocommerce-payments/includes/admin/class-wc-payments-admin.php:558`
### To Reproduce

Install Max Mega Menu and WooCommerce Payments and navigate to Appearance > Menus.

### Actual behavior
Error is thrown

### Expected behavior
No error

**Comment by kaushikasomaiya** [comment]
5760393-zen

**Comment by EricaKuschel** [comment]
38402373-hc
5796506-zen

Did verify that this occurs on my test site.

**Comment by mgascam** [comment]
5778526-zd-woothemes

**Comment by fevered** [comment]
37710097-hc

**Comment by csmcneill** [comment]
@Automattic/gamma Could one of y'all please prioritize this?

Details: p1670626313131429-slack-C7U3Y3VMY

**Comment by xue28** [comment]
https://wordpress.org/support/topic/php-fatal-error-333/#post-16336681

**Comment by WillBrubaker** [comment]
29051548-hc
5813736-zen

**Comment by htdat** [comment]
Ref: p1672939362291799-slack-C01BPL3ALGP

Thanks to our HEs and @megamenu for raising this issue and having a suggestion fix. 

I am having a PR to resolve this issue https://github.com/Automattic/woocommerce-payments/pull/5373 - @megamenu - it would be nice if you can give us feedback too. The build process to test this PR may be complicated but if you need to apply [this diff](https://patch-diff.githubusercontent.com/raw/Automattic/woocommerce-payments/pull/5373.diff) to the latest version of woocommerce-payments on WP.org is enough.

**Comment by htdat** [comment]
FYI. If everything goes well, i.e. no issue with our manual testing next week, the fix for this issue will be included in WCPay 5.3.0 (on Jan 11, 2023).

**Comment by csmcneill** [comment]
@megamenu Can you please check to see if the latest version of WooCommerce Payments (5.3.0) resolves the conflict you originally reported?

**Comment by megamenu** [comment]
Yes, fixed in 5.3, many thanks @htdat , @csmcneill .
