### ISSUE TITLE
Fail to checkout subscription product while logged out of the merchant store with WooPay

### ISSUE THREAD

**Issue by leonardola** [Automattic/woocommerce-payments#5140]
We do not check if the customer has an account on the merchant site before redirecting them to WooPay. When the customer is buying a subscription, clicking the place order button make the message `An account is already registered with your email address. Please log in before proceeding.` shows up.

**How to simulate:**

- Create a new WooPay account by buying a product in the merchant site
- Log in to WooPay
- Log out of the merchant site
- Buy a subscription product
- You'll be automatically redirected to WooPay
- Click place order
- You'll see the message `An account is already registered with your email address. Please log in before proceeding.`

<img width="1089" alt="Screenshot 2023-06-30 at 5 14 54 PM" src="https://github.com/Automattic/woocommerce-payments/assets/6342964/56c53feb-3480-4003-83e8-123f819da0d3">

**Comment by pierorocca** [comment]
Per @bborman22 the changes made to hide the WooPay button on sites in which guest checkout is disabled and user is not logged in, should prevent users from encountering this error. Closing for now.

**Comment by bborman22** [comment]
For additional context, this [check](https://github.com/Automattic/woocommerce-payments/blob/develop/includes/woopay/class-woopay-utilities.php#L48) makes sure that we don't offer WooPay (button or email lookup) to logged out shoppers that have a subscription in their cart
