### ISSUE TITLE
Dispute evidence: Duplicate disputes require duplicated payment charge_id which is not available 

### ISSUE THREAD

**Issue by tijosh** [Automattic/woocommerce-payments#5141]
### Describe the bug

Submitting evidence for a "Duplicate" dispute type requires [entering the charge ID](https://woocommerce.com/document/woocommerce-payments/fraud-and-disputes/managing-disputes-with-woocommerce-payments/#section-6) (ch_) for the other successful charge. However, that charge ID is not exposed in the order—rather, the pi_ is shown. 

<img width="950" alt="image" src="https://user-images.githubusercontent.com/35117248/202295846-6d8402e4-6d59-45a1-8dfe-00af16a10452.png">

### Additional context

p1668628113535099-slack-C3NCP7ZJ6

**Comment by geektzu** [comment]
The reporting merchant also suggested that make the error message more human-readable. Instead of "Failed to submit evidence. xxxx does not exist pm_xxxxxxx".

Maybe something "The charge id could be wrong. It should starts with 'ch_'. Could you double-check the order details?"

**Comment by csmcneill** [comment]
> The reporting merchant also suggested that make the error message more human-readable. Instead of "Failed to submit evidence. xxxx does not exist pm_xxxxxxx".
> 
> Maybe something "The charge id could be wrong. It should starts with 'ch_'. Could you double-check the order details?"

I'm only seeing that `Failed to submit evidence.` is a part of the WCPay code: https://github.com/Automattic/woocommerce-payments/blob/8fcfff959c851d1b1ec5b46748962e48f3cde2cb/client/disputes/evidence/index.js#L653-L657

This might indicate that the remainder of the error is something controlled by Stripe.

**Comment by jbordonado** [comment]
That's correct @csmcneill, the rest of the error comes from Stripe.

You can see what the error response looks like from Stripe in this particular case: [Stripe log](https://dashboard.stripe.com/acct_1M1Yk6FpMw8b2R71/logs?method%5B0%5D=post&method%5B1%5D=delete&direction%5B0%5D=self&direction%5B1%5D=connect_in&created%5Bpreset%5D=7D&showIP=false&success=false&starting_after=1668634278-req_yErKZzcsLJVWgu)

In addition to the error message, Stripe also tells us what field in the request is wrong (here it is `evidence[duplicate_charge_id]`), but not much else, so it seems a little hard to show something more readable for the merchant.

It looks like exposing the charge ID is a valid case for such disputes, so we'll need input from the design team before we can prioritize it.

**Comment by jbordonado** [comment]
~~On another hand, I just had a look and if you have a dispute and click on it, you have this screen:~~

![image](https://user-images.githubusercontent.com/28830738/202418958-20934932-c8f2-4c47-aea2-17e2ad31e566.png)

~~The charge ID is shown there.~~
~~In that case, I'm not sure I see the benefit of adding the charge ID to the order details screen too. The merchant only needs it when he wants to challenge a dispute for a duplicate charge, and he should see it just before challenging.~~

~~What do you think @csmcneill? Or did I understand something wrong?~~

Nevermind, I just realized my mistake: we want the other duplicate charge ID, not the one being disputed.

Sending this to product review queue.

**Comment by jessy-p** [comment]
Issue: If the merchant wants to find the charge id of a successful transaction, it is not present in the Order page or Transaction Detail Page.

**Comment by jessy-p** [comment]
@Automattic/helix As part of Prioritization, bringing this issue to your radar.

**Comment by haszari** [comment]
Thanks @jessy-p  :) This could be tackled by Helix as part of maintaining disputes functionality, or alternatively as part of general WCPay backlog, since showing the charge ID on order page is generally useful (not just for this dispute use case). 

We don't have a lot of bandwidth for maintenance as we're currently focused on High-performance order storage; we're prioritising WCPay Subscriptions maintenance issues. If this could be tackled by Gamma or another team I'd appreciate it. If not I can look at where it fits in the priorities for Helix. 

Side note – this is essentially a feature request, though a relatively simple one. (I've added `enhancement` label)

**Comment by tijosh** [comment]
> this is essentially a feature request

@haszari when the dispute is for a duplicate charge, the merchant is prompted to add the _valid_ charge's ID in the evidence form. So I don't think this could be considered a feature request until/unless that required info is changed.

<img width="915" alt="image" src="https://user-images.githubusercontent.com/35117248/207691902-d508786f-772d-4063-b612-369653cc0101.png">

**Comment by elizaan36** [comment]
@bradyv @haszari Do you think Duplicate charge ID is something that could be pre-populated into the Dispute response form for merchants so they don't need to search for it?

Seems to make sense to surface it on the Transactions detail as well though for reference.

**Comment by bradyv** [comment]
Deferring to @haszari for the technical explanation of whether or not we _can_, but if possible I think we definitely should pre-populate it.

**Comment by haszari** [comment]
> Deferring to @haszari for the technical explanation of whether or not we can, but if possible I think we definitely should pre-populate it.

I agree with "we should". Deferring technical validation until we get closer to the project, but I would expect we can do this somehow :)

**Comment by haszari** [comment]
Brainstorming at meetup – can we show the relevant order(s) and transaction(s) in the dispute detail screen? 

Next step: investigate what info we surface in dispute detail screen and what's missing 😁

**Comment by zmaglica** [comment]
Moved back to the prioritization. Context: p1693316652722699-slack-C01BPL3ALGP

**Comment by jessy-p** [comment]
Removing bug label as the problem will be tackled by an enhancement as described above. Also removing high priority label

**Comment by naman03malhotra** [comment]
>Brainstorming at meetup – can we show the relevant order(s) and transaction(s) in the dispute detail screen?

@haszari, did you get any insight from the discussion during the meetup?

**Comment by naman03malhotra** [comment]
To confirm, Helix is going to handle it as part of their backlog? @haszari

**Comment by haszari** [comment]
> did you get any insight from the discussion during the meetup?

Not that I recall, that was an idea to be followed up. 

> To confirm, Helix is going to handle it as part of their backlog?

No specific ETA but this is in our list of potential maintenance issues.

**Comment by naman03malhotra** [comment]
cc @jessy-p as the current porter.

**Comment by brucealdridge** [comment]
It's worth noting that with the release of WooPayments 6.6 dispute details are now shown on the payment details page. `charge_id` is no longer exposed to the merchant.


![image](https://github.com/Automattic/woocommerce-payments/assets/57298/82bfbefc-2a7a-4e4e-b96b-a52f77c8e076)

I can see `txn_` id's on Transaction list (need to enable column), `pi_` id's on the order and transaction details page.

Now that this information is hidden it increases the priority of this issue.

**Comment by Jinksi** [comment]
> `charge_id` is no longer exposed to the merchant.

Due to this, I've labelled this as a high-priority bug.
