### ISSUE TITLE
WooPay: Special characters are not displayed correctly in WooPay hosted checkout preview

### ISSUE THREAD

**Issue by c-shultz** [Automattic/woocommerce-payments#5143]
### Describe the bug

Special characters are not displayed correctly in WooPay hosted checkout preview:

<img width="663" alt="image" src="https://user-images.githubusercontent.com/6209518/202310216-57b82a7c-66e9-4686-a7a8-432a701a87a3.png">
The site title is `"Shwag Bag"`

### To Reproduce

1.  Enable site for WooPay
2.  Add non-alphanumeric characters to site title
3. Go to wp-admin/admin.php?page=wc-settings&tab=checkout&section=woocommerce_payments&method=platform_checkout

### Expected behavior

Site title should be correctly displayed with all printable characters

**Comment by Priyanshu-Singh-veer** [comment]
hy @c-shultz i want to work on this how can i start on this ?

**Comment by Priyanshu-Singh-veer** [comment]
I'm Working on this.....!

**Comment by pierorocca** [comment]
Closing as this was resolved when the WooPay settings screen was updated. 
![image](https://github.com/Automattic/woocommerce-payments/assets/109928953/38bc5ec1-e138-4dd3-bbbd-f6ab20c93569)
