### ISSUE TITLE
Non-decimal currency and XPF multi-currency bugs

### ISSUE THREAD

**Issue by LevinMedia** [Automattic/woocommerce-payments#5150]
The Pacific Franc (XPF, a non decimal currency) has a number of bugs in both the currency management screen, and on the front end of the store.

**Currency management screen:**

- the currency preview is producing incorrect previews given my configurations for rounding rules and price charming. 
- For the Pacific Franc (XPF) the currency symbol is incorrectly placed, and the wrong symbol. 

<img width="1122" alt="Screen Shot 2022-11-17 at 7 00 04 AM" src="https://user-images.githubusercontent.com/4500952/202455984-c885ed60-bb9a-4343-a26f-e2faf36aa9d8.png">

In the screen shot above, the preview price should be 115 and the currency symbol should be XPF, and precede the price with a space. In the example above, I would expect to see the preview displayed as **XPF 115** This preview bug seems to affect ALL non decimal currencies. Here's another screen shot of Yen - although the yen currency symbol is placed correctly. 

<img width="1111" alt="Screen Shot 2022-11-17 at 7 24 00 AM" src="https://user-images.githubusercontent.com/4500952/202459026-be76c6d5-1797-4c89-b2a3-b075631265fb.png">
 
 The preview price should be ¥140

**On the store front**

On the front end of the store, the prices appear to be calculated correctly, however for the XPF currency, they're missing the coma separator for thousands, and also using the incorrect symbol (Trailing Fr, rather than the correct XPF preceding with a space) I tested for this using Yen, and the coma was placed correctly, so it looks like it might just be limited to XPF

<img width="1666" alt="Screen Shot 2022-11-17 at 7 04 56 AM" src="https://user-images.githubusercontent.com/4500952/202459354-2c56858b-d295-49aa-95eb-d80ac2e6464f.png">

I've attached a few screen shots from business that charge customers in XPF to show how XPF is used as the currency symbol. 

<img width="342" alt="Screen Shot 2022-11-17 at 7 01 59 AM" src="https://user-images.githubusercontent.com/4500952/202457097-93a150c5-8ac0-4ae2-a3ac-67b815180eca.png">

<img width="733" alt="Screen Shot 2022-11-17 at 7 03 17 AM" src="https://user-images.githubusercontent.com/4500952/202457148-4b44bdfe-85b1-473e-b8f6-249c11cd01c8.png">

**Comment by vbelolapotkov** [comment]
Hey @LevinMedia, it feels great to keep getting your feedback, thank you ❤️

**Comment by jessy-p** [comment]
This issue impacts Multi-Currency, so assigning to Fractal (based on team responsibilities Pc2DNy-3z-p2) @bborman. Assigning as part of Gamma Triage process PcreKM-yM-p2.

Tagging as part of re-evaluating older issues in the backlog, please have a look and close if no longer relevant.

**Comment by bborman22** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Fractal-62a0f7b955648b001e1f5e1f/issues/Automattic/woocommerce-payments/5150?planning-poker) with Zenhub @cesarcosta99 @lovo-h @rafaelzaleski @reykjalin @ricardo

**Comment by cesarcosta99** [comment]
It looks like things are a bit different than the time this has been reported.

>the currency preview is producing incorrect previews given my configurations for rounding rules and price charming.
>...
>In the screen shot above, the preview price should be 115 [XPF]
>...
>The preview price should be ¥140

The values in the currency preview seem correct now and match what's expected.

| Pacific Franc | Japanese Yen |
|--------|--------|
| <img width="1051" alt="image" src="https://github.com/Automattic/woocommerce-payments/assets/10233985/45462a74-7626-4818-9c61-8ced0e9adf64"> | <img width="1059" alt="image" src="https://github.com/Automattic/woocommerce-payments/assets/10233985/78342336-c70b-4952-9e20-db950abf65be"> |

>For the Pacific Franc (XPF) the currency symbol is incorrectly placed, and the wrong symbol.

The currency codes are retrieved from WC core [here](https://github.com/Automattic/woocommerce-payments/blob/5a9a10e9257eedde30a9622bed8c3eb9a41241a2/includes/admin/class-wc-payments-admin.php#L755). And the `get_woocommerce_currency_symbols` function documents how the symbols are defined as follows:

>Currency symbols and names should follow the Unicode CLDR recommendation https://cldr.unicode.org/translation/currency-names-and-symbols

I'm not familiar with this currency and the countries that use it, but according to the `Symbols` guidelines linked above, the XPF currency would fall into item 1.3, which says:

1. If a symbol is not widely recognized around the world
    3. ...use the international currency symbol (eg ILS). This can be done just by omitting the translation

I also did some research and [Wikipedia (and a few other sites) indicate](https://en.wikipedia.org/wiki/CFP_franc) that the symbol of the CFP franc currency is `F`.

The `Fr` symbol has been [defined](https://github.com/woocommerce/woocommerce/blob/6be097ff4575ca72b7e184c0a84be7f91f664323/plugins/woocommerce/includes/wc-core-functions.php#L827) 6 years ago, but if I'm reading correctly the guidelines WC core is based on, the symbol should be changed to `XPF`, as suggested in this issue. The formatting of the value would be `XPF 100`. However, I'd like to have another pair of eyes to confirm my reasoning. Looping in @bborman22 to take a look when you have a chance.

---

Now, moving to the store frontend.

>On the front end of the store, the prices appear to be calculated correctly, however for the XPF currency, they're missing the coma separator for thousands, and also using the incorrect symbol (Trailing Fr, rather than the correct XPF preceding with a space) I tested for this using Yen, and the coma was placed correctly, so it looks like it might just be limited to XPF

The trailing `Fr` seems to have been fixed, but the comma separator is still an issue and doesn't match what's seen in the currency preview. Regarding the XPF symbol, I'll wait the outcome of the aforementioned symbol discussion.

<img width="808" alt="image" src="https://github.com/Automattic/woocommerce-payments/assets/10233985/e5be76b7-7d90-47dd-b1a3-a3789cbbd10e">

**Comment by cesarcosta99** [comment]
<img width="807" alt="image" src="https://github.com/Automattic/woocommerce-payments/assets/10233985/d1db1f27-6d8c-4741-9dcd-96dd49a7e82b">

With the new changes applied in the currency the formatting in the preview is going to be `XPF1,234` (without a space between symbol and value). That's going to happen because, in the currency preview, the value is formatted **based** on the store currency formatting [[ref](https://github.com/Automattic/woocommerce-payments/blob/6f59377afd8fb5ebe175bc565e240d69475ea899/client/utils/currency/index.js#L53-L63)].

I have conflicting perspectives about this approach because, as much as I understand this being easier for the store owner to understand the conversion, it's not representing accurately how the currency is going to be presented. @bborman22, I would appreciate a second opinion here to decide if we should keep this behavior, or change it to display the actual currency formatting.

**Comment by bborman22** [comment]
Sorry I don't have a super strong understanding of the difference between this preview and the actual display, but I would expect them to match. This conflict between using store currency formatting in the admin has been a consistent problem I'm looking to get addressed. 

Given the explicit context here that this is a preview of how it will be displayed, I would say we should use the front-end display rules if we can?
