### ISSUE TITLE
New click events on the links added to the WooCommerce > Home screen to link through the list of Uncaptured transactions

### ISSUE THREAD

**Issue by mgascam** [Automattic/woocommerce-payments#5175]
### Description

Implement Tracks metrics in the links to Uncaptured transactions under WooCommerce > Home page.
### Acceptance criteria

* Click events on the links

### Designs

<img width="976" alt="Screenshot 2022-11-24 at 18 59 01" src="https://user-images.githubusercontent.com/1553182/203844769-416ba353-dbb5-42e6-9d73-52c8c67fae48.png">

### Dev notes

Check other events already implemented [here](https://github.com/Automattic/woocommerce-payments-server/blob/trunk/docs/Authorizations.md#tracks-events)

### Additional context

P2: paJDYF-4N1-p2#comment-12901

**Comment by kalessil** [comment]
Closing: left-overs from Auth&Capture take 1. No inbox notifications are planned.
