### ISSUE TITLE
Use redesigned table component in the Uncaptured transactions page

### ISSUE THREAD

**Issue by mgascam** [Automattic/woocommerce-payments#5176]
### Description

Update Uncaptured transactions page to use redesigned table component.
### Acceptance criteria

* Use redesigned table component to implement Uncaptured transactions table
### Designs

TBD

### Dev notes

We need to double check if the redesigned component is already available before we start work on this issue.

### Additional context

P2: paJDYF-4N1-p2#comment-13117

**Comment by kalessil** [comment]
Let's close it, as updating the table component should have been coordinated and implemented across all tables in the WooPayments client.
