### ISSUE TITLE
Inform buyer wether the card will be charged immediately on checkout depending on which capture setting the merchant is using.

### ISSUE THREAD

**Issue by mgascam** [Automattic/woocommerce-payments#5177]
### Description

Inform buyer wether the card will be charged immediately on checkout depending on which capture setting the merchant is using
### Acceptance criteria

* When capture later option is disabled by the merchant, **buyer** will see `Your card will be charged immediately on checkout.` on checkout page.
* When capture later option is enabled by the merchant, **buyer** will see `Your card will be charged once we process your order.` on checkout page.

### Designs

TBD

### Additional context

P2: paJDYF-4N1-p2#comment-13645

**Comment by mgascam** [comment]
Hi @elizaan36, I wanted to follow up with you regarding this issue. I initially raised it after a conversation in the project thread: paJDYF-4N1-p2#comment-13645. As some time has passed since then, I was curious to know whether we're still interested in implementing it. If the answer is yes, we would greatly appreciate your assistance with the design. Please note that this task isn't a high priority at this moment, as we can incorporate it into the scope of phase II for the auth & capture project. Thank you in advance!

**Comment by elizaan36** [comment]
hi @mgascam This feels like an unnecessary message for the shopper and could give them some hesitation at checkout, which we should avoid. Since the payment must be captured within 7 days I think that's a reasonable enough window to not cause worry. Out of curiosity, how will it show up on the shopper's credit card statement, is there a pending charge upon placing the order?

**Comment by kalessil** [comment]
> Out of curiosity, how will it show up on the shopper's credit card statement, is there a pending charge upon placing the order?

Typically, the charge will surface in the statement when it gets captured. Until then, the amount will be secured by the bank on the card.

At least it's how this work for all my cards.

**Comment by kalessil** [comment]
> This feels like an unnecessary message for the shopper and could give them some hesitation at checkout, which we should avoid. Since the payment must be captured within 7 days I think that's a reasonable enough window to not cause worry.

+1 from me. I also have not seen any stores prompting this, so I'd rather close this issue.

**Comment by mgascam** [comment]
Thanks, @elizaan36 @kalessil, closing as not planned then
