### ISSUE TITLE
Reposition navigation tabs in Transactions page

### ISSUE THREAD

**Issue by mgascam** [Automattic/woocommerce-payments#5179]
### Description

In the first iteration, the subnav on Transactions (tabs) is detached from the page header, floating on the page with no background, and pushed right up against the table.

### Acceptance criteria

* Push the tabs in Transactions page up against the header and sidebar
* As an alternative, use new header component (being worked on at the moment of creating this issue)

### Designs

_Interim solution_

![c-gutenberg-sidebar-tabs-1](https://user-images.githubusercontent.com/1553182/203848693-cbe20b77-5412-42d1-8f31-5023a2233d39.png)

_New header component_

TBD

### Additional context

P2: 
paJDYF-4N1-p2#comment-14875 
paJDYF-4N1-p2#comment-14930

**Comment by kalessil** [comment]
Depends on https://github.com/Automattic/woocommerce-payments/issues/5180

**Comment by mgascam** [comment]
The [Tabs component](https://developer.wordpress.org/block-editor/reference-guides/components/tabs/), proposed to implement the new layout, is in experimental stage at the moment.

**Comment by mgascam** [comment]
After discussing with the team we decided to close the issue since the suggested wordpress/component is not ready for production use and this does not seem to be a high priority issue.

FYI: @bradyv since you were involved in the original discussion.
