### ISSUE TITLE
Add badge icon to the Uncaptured tab in Transactions page

### ISSUE THREAD

**Issue by mgascam** [Automattic/woocommerce-payments#5180]
### Description

The number of transactions in the Uncaptured tab should be displayed inside a badge icon
### Acceptance criteria

* The number of transactions in the Uncaptured tab should be displayed inside a badge icon, not between parenthesis

### Designs

<img width="136" alt="Screenshot 2022-11-24 at 19 42 33" src="https://user-images.githubusercontent.com/1553182/203849433-c4dac45f-f7aa-4436-ac38-3513813077d8.png">

### Dev notes

The TabPanel component that we used to implement the first iteration does not support passing an icon, only text. We need to find a way to pass the icon using the same component, or use a different component. Check additional context section.

### Additional context

P2:
paJDYF-4N1-p2#comment-14875
paJDYF-4N1-p2#comment-14930

**Comment by kalessil** [comment]
Update: The components should be evaluated to see if the recommended one is production-ready.

**Comment by mgascam** [comment]
> Update: The components should be evaluated to see if the recommended one is production-ready.

I had a look at the `Tabs` [component](https://developer.wordpress.org/block-editor/reference-guides/components/tabs/), which was the recommended component, mentioned in the linked discussions: pbIJXs-2db-p2. Unfortunately, the component is labeled as experimental at this moment. It was [first released](https://github.com/WordPress/gutenberg/pull/53960) as part of `wordpress/components` v25.9.0. For reference, the latest WordPress v6.4.3 uses `wordpress/components` v25.8.14. 

In my opinion, it's too early to start using this component and we should wait until a more stable version is consolidated. 
cc: @kalessil

**Comment by mgascam** [comment]
After discussing with the team we decided to close the issue since the suggested `wordpress/component` is not ready for production use and this does not seem to be a high priority issue.

FYI: @bradyv since you were involved in the original discussion.

**Comment by kalessil** [comment]
@elizaan36, @vbelolapotkov: you are likely the right people to ask.

In the context of updating UI/UX components, we have two factors: updating dependencies and experimental components.

Who are the right people to own and move forward with the related initiatives (example issues)?:
- https://github.com/Automattic/woocommerce-payments/issues/5180 (experimental component)
- https://github.com/Automattic/woocommerce-payments/issues/5179 (experimental component)
- https://github.com/Automattic/woocommerce-payments/issues/5176 (wider effort as per my understanding)

It feels like a waste of a good initiative, and if you have pointers to an umbrella ticket we'll link the closed ones.

**Comment by elizaan36** [comment]
hey @kalessil thanks for reaching out about these issues. We do need to focus on making these UI improvements holistically on Payments tables, and there's an initiative to redesign the UI to be more in line with the future state of the WordPress admin. @rogermattic has been taking a close look at this in relation to reporting and we should have more to share soon!

**Comment by rogermattic** [comment]
@kalessil just the heads up that those three issues are on my radar now and I will report back when I have some more context to share!

**Comment by kalessil** [comment]
Sounds good @rogermattic !
