### ISSUE TITLE
Disable Capture button in all rows while the request to capture a payment is ongoing in Uncaptured tab.

### ISSUE THREAD

**Issue by mgascam** [Automattic/woocommerce-payments#5182]
### Description

Disable Capture button in all rows while the request to capture a payment is ongoing. Currently merchants are allowed to click on more than one button. It’s seen as a bit confusing for merchants, since it can be hard to tell what payment they just captured if they click several buttons.
### Acceptance criteria

* Only allow to Capture one transaction at a time
* Clicked button transitions to loading state
* Buttons in other rows are disabled

### Designs

N/A

### Dev notes

Instead of passing a single payment intent id, we could pass an array of payment intent ids to the resolver. This way we can leverage `isResolving` to detect if there is a capture request ongoing.

### Additional context

P2:
paJDYF-4N1-p2#comment-14945

**Comment by nagpai** [comment]
The issue no longer persists in the current version. Likely resolved by #5841 . Closing it. 

Props: @mgascam  🙌
