### ISSUE TITLE
Fix Duplicate Charges: Store intent IDs whenever possible, check status

### ISSUE THREAD

**Issue by htdat** [Automattic/woocommerce-payments#5187]
### Description

We need to associate the intent ID as early as possible to the order, meaning right before/after each `(create|create_and_confirm|update)_(setup_)intention` call.

### Acceptance criteria

1. Storing the intent early will help us to check the status of the intent _and_ the order in every call, related to payment processing, including:

*   `process_payment` of the main gateway
*   `create_payment_intent`, `process_payment`, and `process_redirect_payment` of the UPE gateway.

2. Within those calls, before creating a new intent, or performing any payment-related calls, we should:

- Check if the order is marked as paid -> redirect to the order received page.
- Check if the order has an intent ID -> retrieve the intent, and if successful, redirect to the order received page. If not, try to use the same intent for the rest of the process.

### Dev notes
A couple of things to keep in mind here:

*   Orders store `cart_hash`, meaning that we can compare the contents of the order with the current cart as a confirmation step. [See this example](https://href.li/?https://github.com/Automattic/woocommerce-payments/pull/5163/files#diff-bcfd303d507c33a27671935e724ee64d0df30ff2a18bb6ef4c94f28d48190124R910)
*   While redirecting to the order received page, we need to add a (GET) parameter to the URL, and use it to show a message that we’ve used previously entered details (the customer has already committed to those details, so it should be fine). That’s because in the interim, they could have changed something in their address, their payment method, etc., but we are likely still using the old ones.

**UPE** **specifics**

Within this task, we should also make sure that the UPE gateway does not create a new intent when loading, using the one from the order instead. For this we need to do a few things:

1.  Check the order (if available) for an existing intent, and use it, instead of creating a new one. UPE has the necessary logic to update the intent within `process_payment`, so that’s fine.
2.  Consider removing calls to `remove_upe_payment_intent_from_session` in various places, especially [when handling failures](https://href.li/?https://github.com/Automattic/woocommerce-payments/blob/develop/includes/payment-methods/class-upe-payment-gateway.php#L704). Check with Pulsar (@anu-rock): did you do this as a fail-safe, or were there particular issues you were facing?
3.  The WC session object might be unreliable, as my attempts proved it to be inconsistent. We should investigate when the session it stored (wherever it is stored), and when it is cleared.

### Additional context

paJDYF-6wC-p2#comment-15189

**Comment by anu-rock** [comment]
Hey @htdat 👋 

> Consider removing calls to remove_upe_payment_intent_from_session in various places, especially [when handling failures](https://github.com/Automattic/woocommerce-payments/blob/develop/includes/payment-methods/class-upe-payment-gateway.php#L704). Check with Pulsar (@anu-rock): did you do this as a fail-safe, or were there particular issues you were facing?

Copying my response from paJDYF-6wC-p2#comment-15256:

It was to deal with a nasty issue in case of failures such as card declined, 3DS auth failure, redirection payment method failure, saved payment method failure, etc. In all those cases, a customer would not be charged but on checkout page reload would see UPE mounted with only the failed payment method. See @FangedParakeet's comment about “Failing transactions” [here](https://github.com/Automattic/woocommerce-payments/pull/3684#pullrequestreview-858935708).

If I understand correctly, removing calls to `remove_upe_payment_intent_from_session` will save us from accidentally clearing the cache in case of failed payments where customer was actually charged, hence avoiding duplicate charges. I think this is correct thinking as long as we find a way to deal with the above issue.

**Comment by htdat** [comment]
Assign this issue back to me. Ref p1672138129503049-slack-C04CH2FJ8Q0

**Comment by htdat** [comment]
> Check if the order has an intent ID -> retrieve the intent, and if successful, redirect to the order received page. If not, try to use the same intent for the rest of the process.

Thread p1672485938355429-slack-C04CH2FJ8Q0
