### ISSUE TITLE
Improve capture notification section in payment details page

### ISSUE THREAD

**Issue by mgascam** [Automattic/woocommerce-payments#5192]
### Description

Improve the capture notification section that appears in the payment details section when it is pending to be captured.

<img width="1031" alt="Screenshot 2022-11-25 at 09 17 00" src="https://user-images.githubusercontent.com/1553182/203934312-19fbc103-e730-4cab-993b-924b0324b8bf.png">

### Acceptance criteria

* Include a link to the capture section in public documentation.
* Replace ‘You need to capture before DATE’ with something like ‘You have 2 days left’ as the deadline to capture the payment gets closer.

### Designs

TBD

### Additional context

P2
paJDYF-4N1-p2#comment-14945

**Comment by bradyv** [comment]
@mgascam There's something about  `You have 2 days left` that sounds a little too threatening to my ears. Instead, what if we just append the relative value to the string when it's within a certain range - say, 48 hours until the deadline.
<img width="643" alt="Screenshot 2022-12-01 at 11 19 42" src="https://user-images.githubusercontent.com/889872/205140782-1bce5c77-85e2-4fad-9871-f3edf7ef610a.png">

It could also go a step further
- `2 days remaining`
- `tomorrow`
- `today`
- `x hours remaining`
