### ISSUE TITLE
Code freeze workflow: improve links in the Slack notification

### ISSUE THREAD

**Issue by jbordonado** [Automattic/woocommerce-payments#5206]
### Description

The Slack notification sent by the [release code freeze workflow](https://github.com/Automattic/woocommerce-payments/blob/c6154cddf73f49e486ee9316da1075c9cf982418/.github/workflows/release-code-freeze.yml#L79) looks like this:

<img width="668" alt="image" src="https://user-images.githubusercontent.com/28830738/204485976-38796e79-9415-4427-9aad-34a77f10e935.png">

The version number links to a non-existing GitHub release at the time the notification is sent, because the GitHub release is only created once the product is successfully released (2 days later theoretically).
It would be more logical/useful to instead link to the release branch or the PR targeting trunk directly.

### Acceptance criteria

* The Slack notification for the code freeze shows a version number which can be clicked to see the release PR

**Comment by deepakpathania** [comment]
Code freeze workflow has now been updated and this is no longer relevant.
