### ISSUE TITLE
Refunding Possible via Another Currency?

### ISSUE THREAD

**Issue by csmcneill** [Automattic/woocommerce-payments#5215]
### Describe the bug
We had a case where a merchant received a payment of ₹98,633 INR via WCPay. They refunded the order, but they refunded it in their store's default currency (GBP). The conversion made this ~£1,000.00 GBP. When they refunded the order, they asked:

> Do we refund in Rupee amount or GBP amount ?

We had access to the site, and they refunded the order in GBP, instead of INR.

Because they refunded £1,000.00 GBP, the value sent to the Stripe servers was `100000`, and ₹1,000 INR was refunded instead of the full ₹98,633 INR.

### To Reproduce

Cannot reproduce yet. Asked the merchant how they were able to refund in GBP when the payment was made in INR.

### Actual behavior
The merchant was able to refund an order in a currency other than the currency used to pay for the order. When refunding the order in this way, the merchant did not refund the desired amount, as the converted rate did not translate to the original currency.

### Screenshots
![Annotation on 2022-11-30 at 17-27-17](https://user-images.githubusercontent.com/82999806/204929877-ffa12fc3-56c7-48b2-9971-293e8a83720a.png)

### Expected behavior
A merchant should not be able to refund a purchase in a currency other than the currency that a customer paid in.

### Additional context
5747481-zen
p1669770363104429-slack-C7U3Y3VMY

**Comment by jbordonado** [comment]
Let's wait to hear from the merchant with more details on how he proceeded with the refund.
If we can reproduce it, that'll help with the investigation/fix.

**Comment by achyuthajoy** [comment]
@csmcneill Any updates from the merchant?

**Comment by csmcneill** [comment]
@achyuthajoy No update. The original ticket closed and the merchant has not submitted another ticket since.

**Comment by zmaglica** [comment]
@csmcneill Shall we close this issue? Have you got any updates from merchant? If not, we can close this issue and reopen it if we face with the similar problem.

**Comment by csmcneill** [comment]
Still no additional interactions from this merchant. I'll close the issue and we can re-open if needed.
