### ISSUE TITLE
Status not updated once a transaction is captured from the Transactions details page

### ISSUE THREAD

**Issue by mgascam** [Automattic/woocommerce-payments#5222]
### Describe the bug

The status of a transaction is not updated to `Paid` once a transaction is captured from the Transactions details page.

### To Reproduce

1. Using Merchant account enable Issue an authorization on checkout, and capture later on Transactions section of Payments > Settings page and save settings.
2. Follow normal card checkout flow as a Shopper to make a purchase. Take a note of order number created.
3. Using Merchant account go to Payments > Transactions.
4. In the Uncaptured transactions table, click on the row with the order you created in previous step. It will take you to the payment details page.
5. Click on 'Capture' button.

### Actual behavior

The transaction is captured, but the status chip remains as 'Payment authorized'

https://user-images.githubusercontent.com/1553182/205042917-24ea9bad-5d13-4a1e-8f24-2c3887d16967.mov

### Expected behavior

The transaction is captured and the status chip displays 'Paid' status

**Comment by jessy-p** [comment]
@Automattic/pulsar  As part of Prioritization, bringing this issue to your radar.

**Comment by kalessil** [comment]
Thanks for the ping @jessy-p! We track it under Auth&Capture (Phase 2) project, which will be kicked in in February.

**Comment by nagpai** [comment]
I am unable to replicate this bug anymore. I see the status chip successfully changing to `Paid` on my local test setup. 


https://user-images.githubusercontent.com/4162931/228200429-7f943f91-c5bc-4c21-ba34-78ac020d301f.mov

**Comment by mgascam** [comment]
Thanks @nagpai. This was a duplicate of https://github.com/Automattic/woocommerce-payments/issues/5221 and we already fixed it.
