### ISSUE TITLE
Use default appearance for file upload buttons

### ISSUE THREAD

**Issue by dechov** [Automattic/woocommerce-payments#523]
As I understand it, the file upload buttons should have <s>default</s> secondary styling, not primary.

`isPrimary={ true }` | `isPrimary={ false }`
-- | --
<img width="199" alt="hot pink" src="https://user-images.githubusercontent.com/1867547/77127823-5a070d80-6a24-11ea-8ea8-822d4350c4ed.png"> | <img width="193" alt="cold gray" src="https://user-images.githubusercontent.com/1867547/77127826-5b383a80-6a24-11ea-9756-07aef6f23ca5.png">

[_Edit:_ these screenshots are out of date, see comments below.]

However, something (that I was unable to quickly pin down) about the overrides in WooCommerce Admin make this break the busy state (and success state as well). It's possible that busy state styling just wasn't compatible with the overrides for default button. In any case, the overrides are slated for removal which might make the problem go away (https://github.com/woocommerce/woocommerce-admin/issues/3897). [_Edit:_ I believe this bit has been addressed.]

Previously: https://github.com/Automattic/woocommerce-payments/pull/503#discussion_r394320034. Didn't manage to easily fix it and it was kind of out of scope anyway.

**Comment by dechov** [comment]
A bit late on the annual update here 😄 – it currently looks like this:

https://user-images.githubusercontent.com/1867547/122307047-8d5e7380-ced7-11eb-86bb-c9c863581544.mov

Here is how it looks in the design, latest for this screen I believe (and before things turned blue):
<img width="302" src="https://user-images.githubusercontent.com/1867547/122307614-ad426700-ced8-11eb-853a-5d3753df6d91.png">

The default styling removes the border and doesn't look right – `isSecondary` seems most suitable:

https://user-images.githubusercontent.com/1867547/122307845-17f3a280-ced9-11eb-8cc5-51fda007c0e6.mov

Getting the green color for that isn't as straightforward as in the current implementation, however – the border is a `box-shadow` so we'd have to declare that whole rule just to set the color, or override the CSS variable value. The latter works, but also seems pretty brittle:

```diff
diff --git a/client/disputes/style.scss b/client/disputes/style.scss
index 9803552c..36d71819 100644
--- a/client/disputes/style.scss
+++ b/client/disputes/style.scss
@@ -61,24 +61,20 @@
                align-items: center;

                // Selector here is super specific to ensure styles are overwritten.
-               .components-button.is-primary:not( :disabled ):not( [aria-disabled='true'] ) {
+               .components-button:not( :disabled ):not( [aria-disabled='true'] ) {
                        &.is-success {
-                               background-color: $studio-green;
-                               border-color: $studio-green;
+                               --wp-admin-theme-color: #{$studio-green};

                                &:hover {
-                                       background-color: $studio-green-60;
-                                       border-color: $studio-green-60;
+                                       --wp-admin-theme-color-darker-10: #{$studio-green-60};
                                }
                        }

                        &.is-destructive {
-                               background-color: $studio-red;
-                               border-color: $studio-red;
+                               --wp-admin-theme-color: #{$studio-red};

                                &:hover {
-                                       background-color: $studio-red-60;
-                                       border-color: $studio-red-60;
+                                       --wp-admin-theme-color-darker-10: #{$studio-red-60};
                                }
                        }
                }
```

AFAICT the way the button component is currently implemented, the color isn't really meant to be changed.

**Comment by LevinMedia** [comment]
@dechov sounds good - secondary style does seem like the best fit. If it's really problematic to change the color, we can probably just change the + to the check mark.

**Comment by dechov** [comment]
Thanks @leonardola for the fix! I'm in favor of the approach, but we should be aware that it's tied to the current style implementation of the button. Besides trying to make sure that it doesn't break due to upstream changes, we may want to consider contributing a change to the component to make it more "themeable" via CSS variables. cc @ricardo
