### ISSUE TITLE
wcpayWooPayExpressParams is not defined when trying to checkout with WooPay

### ISSUE THREAD

**Issue by leonardola** [Automattic/woocommerce-payments#5233]
### Describe the bug
After #5164 was merged the error `Uncaught ReferenceError: wcpayWooPayExpressParams is not defined` started showing up in the console when trying to log in using the OTP modal in the merchant site.

### To Reproduce
- Checkout to the latest trunk version
- While logged out of WooPay add a product to your cart and try to checkout using woopay
- After you enter the OTP an error will show in the developer console and you won't be redirected to the WooPay checkout page

**Comment by leonardola** [comment]
@bborman22 adding you to the loop as it seems like a PR you worked on added this bug and you probably have more context.

**Comment by leonardola** [comment]
Same error happens when the WooPay checkout page loads

**Comment by bborman22** [comment]
So sorry about that, I have a fix locally now, running through some more testing and will push up shortly for review.

**Comment by bborman22** [comment]
I got the PR up and reviewed from someone on our team, but a second set of eyes on the PR wouldn't hurt given the fact I missed it last time 👀 .
