### ISSUE TITLE
Multiple UPE - Add icons to payment methods in Blocks checkout

### ISSUE THREAD

**Issue by FangedParakeet** [Automattic/woocommerce-payments#5259]
### Description

Specifically we want to add these payment method icons...

![Shortcode checkout payment method icons](https://cdn-std.droplr.net/files/acc_1104206/ZXgsuG)
_Behold the beautiful icons_

...to the payment methods in the Blocks checkout, where they are currently absent.

![Blocks checkout missing payment method icons](https://cdn-std.droplr.net/files/acc_1104206/bvbEmI)
_Bring me icons or bring me death_

For the shortcode checkout, we have manually added our own icons (see #4860); however, it appears that the Blocks team have managed [to pull these icons directly from Stripe](https://github.com/woocommerce/woocommerce-blocks/pull/2188/files) in order to insert them onto the appropriate label. I believe this is currently only configured for the native credit card field. It's up to us, though probably preferable, to follow this approach or not, but either way we will need to implement for all available UPE payment methods. 

### Acceptance criteria

1. Payment methods on the Blocks checkout must have pretty icons next to their labels. 

### Additional context

It has been inquired here ( -> p1670433138909099-slack-C02TS23QJ1X ) to Blocks support as to whether there is a generic, conventional way to add icons to payment gateways on the checkout block, but this has not been answered as of yet. Feel free to follow up on this thread should you desire further enlightenment.

**Comment by FangedParakeet** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Heisenberg-63586f2ec60359001310fa6a/issues/Automattic/woocommerce-payments/5259?planning-poker) with Zenhub @mdmoore @timur27

**Comment by timur27** [comment]
I imagine this issue to contain two main steps: 
1. Add the `icon` parameter with img src [here](https://github.com/Automattic/woocommerce-payments/blob/b5b85593b27f3b648cf4544389c9e1b8c188eaf7/includes/class-wc-payments-upe-checkout.php#L155-L181) for each gateway by re-using the icon url introduced [here](https://github.com/Automattic/woocommerce-payments/pull/4860)
```php
'icon' => $payment_method->get_icon()
```
2. Provide this field to the `registerPaymentMethod` [here](https://github.com/Automattic/woocommerce-payments/blob/b5b85593b27f3b648cf4544389c9e1b8c188eaf7/client/checkout/blocks/upe.js#L66-L95). It's being actively discussed how to do it (either by just adding img src to the `label` prop or create a new `icon` prop), so I don't know yet what will be the final decision here.
