### ISSUE TITLE
WC-pay disputes are disrupting WC-admin analytics

### ISSUE THREAD

**Issue by LevinMedia** [Automattic/woocommerce-payments#526]
When an order is disputed, we need to track the money that is returned to the customer via wc-admin analytics. 

At the moment, we're doing nothing, which is throwing off the analytics, and displaying incorrect data in the orders list, as well as order details screen. Behind the scenes, we need to ensure we're refunding any tax and shipping appropriately as well.  

If the disputed amount is the same as the order total (It usually is) the order status should change to refunded. 

**Example:** 

The second order was disputed. The original total should be crossed out, and the new total should be zero. The order status should read refunded. 

<img width="1545" alt="Screen Shot 2020-03-20 at 1 15 08 PM" src="https://user-images.githubusercontent.com/4500952/77204048-2624fa00-6aaf-11ea-8db5-851da6dc795c.png">

The order details screen should display the order as if it were refunded for the disputed amount. I'll open a separate issue about including new order notes in the case of a disputed order. 

For reference here are the order details for the order that was disputed - we'll need this to make sense of the analytics below.

<img width="1085" alt="Screen Shot 2020-03-20 at 1 54 37 PM" src="https://user-images.githubusercontent.com/4500952/77205570-5de17100-6ab2-11ea-9b7a-3a1ebb9fad68.png">

Now here's the result of the disputed payment in the revenue report:

<img width="1904" alt="Screen Shot 2020-03-20 at 1 45 41 PM" src="https://user-images.githubusercontent.com/4500952/77204976-20301880-6ab1-11ea-9fa1-6709b4317393.png">

- Gross sales is correct
- Returns should indicated $12.00 - the net amount of the disputed order. (The Items subtotal, minus any coupons)
- Net sales should be reduced by $12.00 (the net amount returned in the disputed order)
- Taxes should be reduced by $1.02 (the amount of tax that was collected, then returned on the disputed order)
- Shipping should be reduced by $5.00 (the amount collected for shipping then returned on the disputed order)
- Total sales should be reduced by $18.02 (the total of the returned net sales, tax and shipping amounts)

cc @Automattic/isotope

**Comment by jrodger** [comment]
There are a few things blocking progress on this issue, I'll try to break down what we need to look at first so we can start making progress again:

- We have an in progress PR which makes a first pass at implementing changes to order status based on disputes: https://github.com/Automattic/woocommerce-payments/pull/714
- As noted in the PR, ideally we would address https://github.com/Automattic/woocommerce-payments/issues/599 to avoid tipping the controller class into a bit of a mess.
- We need to do a some work on how we forward the webhook from the server (281-gh-woocommerce-payments-server).

**Comment by jrodger** [comment]
I've removed the "blocked" status from this issue, we've made sufficient progress on the points above to start looking at this again:

* The in progress PR (#714) needs some finishing up, but the approach still looks solid to me (assuming we're still comfortable with introducing these dispute order statuses). It rebased cleanly and I've also updated the associated server PR.
* Ideally we should address #599, but I don't think it should be considered a blocker.
* Our webhook forwarding on the WCPay server has matured to the point we can use it for these more critical pieces of functionality.

**Comment by LevinMedia** [comment]
>The other question is whether the $15 dispute fee should be accounted for in the analytics? And if so, should it be accounted for against the order?

>Technically, if an order has been disputed and the dispute is lost, the order cost the merchant $15, so a negative total of $15 would make sense. There is no concept or precedent in WC for this kind of negative total order amount being used to reflect a dispute fee from the payment processor (AFAIK).

@thenbrent My short answer there is yes, we should account for the 15 dollar fee. 

At the end of the day, this fee amount should be deducted from the net sales total. however, in order to disambiguate it from refunds or the amount paid for products I think it should be accounted for separately from both the net sales, discounts and returns.

Adding a new "fees" column, and integrating it on the appropriate reports would solve this issue. I assume there are other areas within WooCommerce that would likely benefit from this column as well (shipping, perhaps?) 

The new net sales calculation would look like:  _gross sales - returns - discounts - fees = net sales_

The fee summary number could be display conditionally, and only appear if the selected date range and filter combinations include an order that was assessed a fee. 

cc: @elizaan36

**Comment by LevinMedia** [comment]
>My short answer there is yes, we should account for the 15 dollar fee.

@thenbrent - I'm already having second thoughts about that statement. I'm going to do a little design exploration around this in the next week or two.

**Comment by thenbrent** [comment]
> Adding a new "fees" column, and integrating it on the appropriate reports would solve this issue.

Just to complicate matters, WooCommerce already has a concept of a "fee" line item, which is usually a fee levied to the shopper, not a fee levied on the merchant. We could reuse the same fee API, but right now, it's included in the Gross Sales of analytics (I expect) rather than being split out.

**Comment by vbelolapotkov** [comment]
Sending back for triage due to the lack of activity for the long time

**Comment by htdat** [comment]
> Sending back for triage due to the lack of activity for the long time

FYI. Per this comment by David https://github.com/Automattic/woocommerce-payments/issues/526#issuecomment-776276361, I am moving this issue to queue `Product review` for ZenHub board `WooCommerce Payments Backlog`.

**Comment by haszari** [comment]
Marking as an enhancement. Based on the discussion above, we'll need to design and consider the solution across WooPayments and WooCommerce core. 

> Perhaps WC core could/should have a new dispute custom order type, like shop_order_dispute (in the same way, they have a [shop_order_refund custom order type](https://github.com/woocommerce/woocommerce/blob/4.0.0/includes/class-wc-post-types.php#L414-L434).) This object can the be used to store and account for both the amount of the order being deducted, and the dispute fee, in analytics and elsewhere within WooCommerce by both WC Pay and other gateways.

Note we have issue open for exploring a disputed status:

- #8306

**Comment by haszari** [comment]
I think it's safe to close this – it is a problem, but we'll need to resolve it as a project across WooCommerce (core) and WooPayments. There may be future work  improving or changing Woo analytics/reporting features, or order statuses, which might touch on this. 

This issue is stale and not actionable as is, so I'm closing. FYO @warrendholmes  @souravdebnath1986  @mjdeacon – there are some good ideas/requests for future projects, feel free to log this as a project idea / enhancement / feature request.
