### ISSUE TITLE
SEPA payment method not saved in Blocks checkout

### ISSUE THREAD

**Issue by timur27** [Automattic/woocommerce-payments#5260]
### Describe the bug
In the split UPE project, SEPA payment methods are not saved from Blocks checkout. 

### To Reproduce

1. Buy a product using Blocks checkout and SEPA. Save SEPA during the process.
2. Open the Blocks checkout page again and check if you see the SEPA method saved previously. I expect it to appear, but it doesn’t. 🔴 
3. Open the Shortcode checkout page and check if you see the SEPA method saved previously. I expect it to appear, but it doesn’t. 🔴
4. Go to My account -> Payment methods and check if you see the SEPA method on the list. It’s not displayed there, and the list is empty. 🔴 
5. Add a new SEPA payment method in _My account -> Payment methods_ OR by saving the new SEPA method on the shortcode checkout page. After being added, it should appear on the list. Also, the previously added SEPA method starts to appear on the list after this action.

### Actual behavior
After the SEPA payment method is saved while checking out with Blocks, it does not appear in Blocks checkout, shortcode checkout, and _My account -> Payment methods_ page.

### Expected behavior
After the SEPA payment method is saved while checking out with Blocks, it should appear in Blocks checkout, shortcode checkout, and _My account -> Payment methods_ page.

### Additional context
[This](https://github.com/Automattic/woocommerce-payments/pull/5252#issuecomment-1342231008) comment is a good starting point, as it explains possible root causes and places to fix.

**Comment by FangedParakeet** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Heisenberg-63586f2ec60359001310fa6a/issues/Automattic/woocommerce-payments/5260?planning-poker) with Zenhub @mdmoore @timur27
