### ISSUE TITLE
The attempt to pay with a saved SEPA payment method in Blocks checkout fails

### ISSUE THREAD

**Issue by timur27** [Automattic/woocommerce-payments#5261]
### Describe the bug
In the split UPE project, the attempt to pay with a saved SEPA payment method in Blocks checkout fails. 

### To Reproduce
1. Save a new SEPA payment method in _My account -> Payment methods_
2. Add a product to the cart 
3. Open the Blocks checkout page and select the saved SEPA payment method 
4. Place an order
5. You will see `No payment method provided.` error notice on the top of the page.

The `/checkout` endpoint response is
```
{
  "code": "woocommerce_rest_checkout_missing_payment_method",
  "message": "No payment method provided.",
  "data": {
    "status": 400
  }
}
```

### Actual behavior
Users cannot pay with saved SEPA payment methods while using Blocks checkout.

### Expected behavior
Users should be able to pay with saved SEPA payment methods while using Blocks checkout.

### Additional context
This was encountered [in another PR](https://github.com/Automattic/woocommerce-payments/pull/5252#pullrequestreview-1207458645).

**Comment by FangedParakeet** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Heisenberg-63586f2ec60359001310fa6a/issues/Automattic/woocommerce-payments/5261?planning-poker) with Zenhub @mdmoore @timur27
