### ISSUE TITLE
HRK will be replaced by EUR after Jan 1, 2023

### ISSUE THREAD

**Issue by tpaksu** [Automattic/woocommerce-payments#5265]
### Description
As stated in [this P2 post](pbUcTB-1Q1-p2) Croatia will be a part of EUR using countries as stated: 

> On 1 June 2022, the Commission assessed in its 2022 [Convergence Report](https://economy-finance.ec.europa.eu/publications/convergence-report-2022_en) that Croatia fulfills all the criteria for joining the euro area and proposed to the Council that Croatia adopt the euro on 1 January 2023.

Source: https://economy-finance.ec.europa.eu/euro/eu-countries-and-euro/croatia-and-euro_en

And because of that, the HRK currency will be obsolete. We should point the record of HR from HRK to EUR on the client.

**Comment by allie500** [comment]
After testing HRK=>EUR transition scenarios with this PR branch and the `develop` branch alongside changes made to the WCPay server, we found that the changes in this Issue and PR were not needed. 

Therefore we've decided to close this issue and PR.
