### ISSUE TITLE
Multiple UPE - Fix margins on payment methods at checkout 

### ISSUE THREAD

**Issue by FangedParakeet** [Automattic/woocommerce-payments#5272]
### Describe the bug

Some unsightly inconsistencies in the spacing of payment method elements at checkout have been discovered when the split-UPE is enabled. These malicious margins must be eliminated.

#### Top padding on UPE payment gateways in shortcode checkout

The top padding on UPE payment methods is garishly enlarged. I have a sneaking suspicion that this sickness is confined to those payment methods that do not have testing instructions, where an empty `<div>` leaves a larger unused space.

![Top padding too large](https://cdn-std.droplr.net/files/acc_1104206/4LZGYT)
_Red rectangle bad, green rectangle good_

![Consistent padding on CC](https://cdn-std.droplr.net/files/acc_1104206/oXoq8N)
_See how the credit card gateway has more consistent spacing_

![Consistent padding on SEPA](https://cdn-std.droplr.net/files/acc_1104206/0Ul1Dm)
_See how the SEPA gateway also has more congruent gaps_

#### Spacing of save payment checkbox on credit card field

The checkbox to save one's payment information on the credit card gateway is too close to the input field. A little separation would be a lot more seemly.

![Checkbox too close](https://cdn-std.droplr.net/files/acc_1104206/mryUnp)
_Don't stand so close to me_

![Checkbox with correct spacing](https://cdn-std.droplr.net/files/acc_1104206/raaO0c)
_SEPA checkbox practises more appropriate social distancing_

These are the minimum obvious peeves that must be purged in order to resolve this issue, but if you happen to find any more, don't hesitate to be the change you wish to see in the world and correct those misalignments as well!

**Comment by FangedParakeet** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Heisenberg-63586f2ec60359001310fa6a/issues/Automattic/woocommerce-payments/5272?planning-poker) with Zenhub @mdmoore @timur27

**Comment by frosso** [comment]
Assigning this a 1 point, since @timur27 mentioned that it could be workable for his cooldown time :)
