### ISSUE TITLE
Multiple UPE - Improve design of non-UPE credit card fields at checkout

### ISSUE THREAD

**Issue by FangedParakeet** [Automattic/woocommerce-payments#5273]
### Description

The UPE payment fields look a lot prettier than the legacy card element inputs in the shortcode checkout. The legacy card input does not match the styling of other input fields on the checkout page and does not even match the styles of other payment fields on other payment fields on other gateways.

Since the split-UPE will initially use the legacy non-UPE gateway for the credit card gateway, while using the UPE gateways for other additional payment methods, this makes the card gateway stand out as particularly an incongruous and hideous eyesore amidst the checkout page.

![Legacy card payment fields](https://cdn-std.droplr.net/files/acc_1104206/TVujpb)
_Legacy credit card_

![UPE payment fields](https://cdn-std.droplr.net/files/acc_1104206/6exled)
_UPE credit card fields AKA the payment fields your gf says not to worry about_

The UPE payment inputs fit so seamlessly with the existing checkout elements, because we take the effort to [extract styles and fonts](https://github.com/Automattic/woocommerce-payments/blob/develop/client/checkout/upe-styles/index.js) from the inputs present on the checkout and [feed these variables back to Stripe](https://github.com/Automattic/woocommerce-payments/blob/develop/client/checkout/classic/upe.js#L265) when creating the payment element.

![UPE inputs match checkout form fields](https://cdn-std.droplr.net/files/acc_1104206/BzaITH)
_UPE inputs automatically match with existing elements_

![Non-UPE fields do no match](https://cdn-std.droplr.net/files/acc_1104206/73Ers6)
_Non-UPE fields stick out like sore thumbs_

Is there any way to improve the appearance of this input or reuse the styles actively extracted from the checkout fields, when the split-UPE is enabled? This issue will be resolved when this topic has been investigated and--if found to be possible--implemented.

### Acceptance criteria

* Investigate our options to improve appearance of legacy Stripe card element.
* Implement best solution to beautify the card element.

**Comment by FangedParakeet** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Heisenberg-63586f2ec60359001310fa6a/issues/Automattic/woocommerce-payments/5273?planning-poker) with Zenhub @mdmoore @timur27

**Comment by elizaan36** [comment]
Thanks for creating this issue, @FangedParakeet ! It was my first thought as I tested the UPE implementation and @mdmoore referred me here. Is this something we can include in the upcoming release. Just a note that the card form element should ideally match the form style on the checkout blocks as well.

**Comment by FangedParakeet** [comment]
@elizaan36 we'd definitely love to resolve this in time for the upcoming release! However, we have a few other required issues that are ahead in the current pecking order and with our limited availability due to the meetup next week, I don't want to make any promises that I might not be able to fulfill. It's definitely firmly on our radar and in our sights, but we'll have to see if we have time to squeeze this into the upcoming release. 🙏

**Comment by frosso** [comment]
Planning to fix this in 6.6.0, where we'll be migrating "Legacy UPE" merchants to the newer "Deferred Intent UPE". The "Deferred Intent UPE" doesn't use the legacy input.
