### ISSUE TITLE
Display CC fields when a 100% coupon code  that is added in cart is removed on checkout page

### ISSUE THREAD

**Issue by AashikP** [Automattic/woocommerce-payments#5277]
### Describe the bug

If a 100% coupon code that is originally added in the cart page is removed on the checkout page, no credit card fields are displayed unless you reload the page.

### To Reproduce

1. You should either try to checkout as a guest user, or try a user with no saved payment method on the store
2. Create a 100% coupon
3. Add a product to cart, and use the coupon
4. Proceed to checkout page and remove the coupon
5. Notice that the credit card fields are only displayed when you reload the page
6. Clicking on use a new payment method does not make a difference:

    ![ecDXYN.png](https://user-images.githubusercontent.com/17475174/207239582-2dcf8fd8-3a30-419d-8c6a-dacdcc01c33a.png)

### Actual behavior

**When the coupon is originally added on the checkout page, everything works fine**

![vt1g9R.gif](https://user-images.githubusercontent.com/17475174/207239822-f803da48-8afc-47de-9cb2-c5f9b514f810.gif)

**When the coupon is first added on the cart page, the CC fields don't show up**

![nTxr53.gif](https://user-images.githubusercontent.com/17475174/207240115-50b10c80-5f5a-4209-8914-8720ae7b4e55.gif)

### Expected behavior

If there are no payment method saved, CC fields should always be displayed.

### Desktop (please complete the following information):

Any

### Smartphone (please complete the following information):

Any

### Additional context

**Merchant reports**: 

5783438-zen

**Comment by jessy-p** [comment]
Might have same solution as #4764

**Comment by hamadgill** [comment]
looks like a similar issue any updates on a fix ?
