### ISSUE TITLE
Migrate WCPay codebase to use dedicated order statuses enum

### ISSUE THREAD

**Issue by dpaun1985** [Automattic/woocommerce-payments#5286]
### Description

[Here](https://github.com/Automattic/woocommerce-payments/blob/8f955cea51219f79877bffd9b553491bc7b2a940/includes/class-wc-payments-order-service.php#L20) we noticed order status values in service constants, while those should be in it's own enum.

### Acceptance criteria

Order statuses are moved into their own enum, codebase is checked to use the enum constants instead of strings.

### Testing instructions

- Tests shall pass

**Comment by kalessil** [comment]
My bad @nagpai, as per Slack - there are no constants for order statuses in WooCommerce core.
Can we still refactor and move the constants under a dedicated enum similar to https://github.com/Automattic/woocommerce-payments/blob/develop/includes/constants/class-payment-capture-type.php (in the same folder as the example enum class)?

**Comment by nagpai** [comment]
Changed my estimate to 2 since it took me a while to look and replace the hardcoded strings with the newly introduced constants. It consumed a bit of time to change, and check.
