### ISSUE TITLE
Evaluate if WC_Payment_Woo_Compat_Utils can be dropped

### ISSUE THREAD

**Issue by kalessil** [Automattic/woocommerce-payments#5291]
### Description

Some time back, the util class was introduced to cover compatibility break in WooCommerce related to changes in notes classes. As we regularly bump required versions of WordPress and WooCommerce, the util might not be needed anymore.

### Acceptance criteria

- Evaluated if WC_Payment_Woo_Compat_Utils can be dropped
- If WC_Payment_Woo_Compat_Utils dropped, changes tested on the oldest supported WooCommerce version.

**Comment by nagpai** [comment]
Writing my thoughts / steps done here. I did a top-level check and found  that the Note.php is now available in core. Further: 

1. The compatibility util class was written on [November 18, 2020](https://github.com/Automattic/woocommerce-payments/commit/bc7e5527c38582ba7f727fb7341874fdc962d469) when WC Admin classes including that of Note component, were not merged to core.

2. Many months later ( March 2022 ) , WooCommerce Admin related code/ classes including that related to the compatibility class (Note.php) , were [merged into core ](https://github.com/woocommerce/woocommerce/commits/3dd60322d5490d7d86ad33e7d732f276df73a12d/plugins/woocommerce/src/Admin/Notes/Note.php) 

This would mean that the compat util class is now redundant. I will test this and have a PR created accordingly.
