### ISSUE TITLE
[e2e test failed] Refunding orders purchased with Inquiry Dispute test card expected to fail

### ISSUE THREAD

**Issue by mattallan** [Automattic/woocommerce-payments#531]
This issue is related to the failed test that Robot Ninja reported (p1585093232076200-slack-wcpay).

---

One of our automated WC Pay checkout tests failed and I'm not sure if this is new expected behaviour or if it's a bug.

During the test, Robot Ninja purchased a product using the `Inquiry_Dispute` test card (`4000000000001976`) and a [dispute](https://verbal-trout.jurassic.ninja/wc-payments/wp-admin/admin.php?page=wc-admin&path=%2Fpayments%2Fdisputes%2Fdetails&id=dp_1GQLntJbXyPOKmDyLGWpn2iU) for this order was properly created. We then tried to process a refund for this order via the REST API and that was successful :x:

**Expected behaviour**: When I initially wrote this test case, the refund request was expected to fail, but now it's working 🤔 

Does anyone know if refunding orders that have an active/pending dispute is now allowed? Or is this a bug?

Thanks!

**Comment by vbelolapotkov** [comment]
I think this could be race conditions, but since we're not running RN tests anymore closing this issue.
