### ISSUE TITLE
Explore playwright for writing our E2E tests

### ISSUE THREAD

**Issue by deepakpathania** [Automattic/woocommerce-payments#5318]
Currently, we use puppeteer for our E2E tests and we'd like to migrate to playwright considering it makes writing and maintaining tests a lot easier.

As a part of this issue:
- Explore migrating our current tests to playwright and document the same.
- Explore writing a new E2E test with playwright and document the same.
- Explore generating a new E2E test through the [codegen](https://playwright.dev/docs/codegen-intro) and document the same.

**Comment by deepakpathania** [comment]
Started a thread with Solaris team around this [here](https://a8c.slack.com/archives/C01BWDDTGKX/p1672133938830939).

**Comment by deepakpathania** [comment]
Based on the thread started with Solaris, we can wait for the migration guide they have been working on to help us plan our migration process as per [this discussion](https://github.com/woocommerce/woocommerce-bookings/pull/3366#issuecomment-1321232529).

The `e2e-environment` package we use isn't compatible with Playwirght so we might have to use `wp-env` instead which is now being used for the [Playwright setup for core](https://github.com/woocommerce/woocommerce/tree/trunk/plugins/woocommerce/tests/e2e-pw#about-the-environment) as well. This is important since it would require us to rewrite our current testing setup accordingly.

Based on the migration guide, we can decide whether or not the effort involved with the same can be justified to the added value provided by Playwright (codegen, improved stability through reduced flakiness). The performance and syntax seems to be on the similar level as puppeteer so this should help us make an informed decision.

**Comment by deepakpathania** [comment]
The guide is supposed to be published by next week, marking this as blocked till then so it can be picked up accordingly.

**Comment by deepakpathania** [comment]
Migration guide: https://github.com/woocommerce/woocommerce/wiki/Puppeteer-to-Playwright-Migration-Guide-for-e2e-Testing

**Comment by deepakpathania** [comment]
Moving it out of the current sprint to focus on the immediate 30 day plan items for the team.

**Comment by vbelolapotkov** [comment]
Closing in favor of #8177 which is on the radar of FE guild.
