### ISSUE TITLE
Update PHP compatibility workflow

### ISSUE THREAD

**Issue by jbordonado** [Automattic/woocommerce-payments#5333]
### Describe the bug
The workflow started to fail once composer released version 2.5.1: https://github.com/Automattic/woocommerce-payments/actions/runs/3764384197

![image](https://user-images.githubusercontent.com/28830738/209312250-a3e5f2df-81c7-4a58-920b-1721dfe435dc.png)

We temporarily fixed it by pinning the version to 2.5.0 in #5332.

As mentioned in p1671788515519959/1671784565.257749-slack-C04D1QU76PK, what we really need to do is:
- bump min WP version to 5.9 in `phpcs-compat.xml.dist` file
- bump PHP version to 7.2 in `phpcs-compat.xml.dist` file
- Check if we need to update other places too?

Note: bumping min WP version in that file should be part of the [wcpay:bump-versions](https://github.com/woocommerce/woorelease-extensions/blob/trunk/class-woocommerce-payments-bump-versions.php) command, since we're already doing that for `phpcs.xml.dist` file. Ideally, we could also pass a PHP version as a parameter to bump the PHP version in every place we need to.

**Comment by htdat** [comment]
FYI. @shendy-a8c has just pinned composer to 2.5.0 to run `release-pr.yml` workflow. When working on this issue, the author might consider removing the pin.

https://github.com/Automattic/woocommerce-payments/blob/a572293ae0deaf9e279541860c8c22c63b298c83/.github/actions/setup-repo/action.yml#L28

**Comment by htdat** [comment]
@Automattic/harmony - could you prioritize this issue? It has been mentioned here: p1676902504887589/1676901156.193099-slack-C0208C3BXHP

**Comment by deepakpathania** [comment]
We do not have the bandwidth to pick it up in this sprint, noting it down for prioritising it in the next one.

**Comment by htdat** [comment]
FYI. I've noticed that we would remove this part from GlobalStep weekly posts too: 

> To perform testing with our minimum supported version of PHP, please create at least one test site using the following link: [https://jurassic.ninja/create/?nojetpack&woocommerce&php_version=php7.0](https://href.li/?https://jurassic.ninja/create/?nojetpack&woocommerce&php_version=php7.0). We just want to perform at least some testing on this minimum version. There’s no need to repeat or perform the same tests every time.

My 2 cents. May we increase these numbers manually now, and leave the [wcpay:bump-versions](https://github.com/woocommerce/woorelease-extensions/blob/trunk/class-woocommerce-payments-bump-versions.php) later? It would make developers' experience a bit better and reduce unnecessary (both manual and automated) tests.

**Comment by jbordonado** [comment]
> FYI. I've noticed that we would remove this part from GlobalStep weekly posts too

@htdat We would still keep it but target 7.2 instead, right?

Anyway, good catch, we'll have to update this after the task is closed

**Comment by htdat** [comment]
> We would still keep it but target 7.2 instead, right?

IIRC, we asked GlobalStep to test with PHP 7.0 because we had problems in dealing with this PHP version in our CI https://github.com/Automattic/woocommerce-payments/issues/2970#issuecomment-1015598461

This is worth considering again. However, IMO, it's still good to ask GlobalStep to test one of their sites with PHP 7.2 (or minimum PHP version for the future).

**Comment by jbordonado** [comment]
Now that makes sense, I was missing a bit of history here. Thanks!
