### ISSUE TITLE
Improve E2E test coverage for Stripe Link

### ISSUE THREAD

**Issue by FangedParakeet** [Automattic/woocommerce-payments#5338]
### Description

I am under the impression that our test coverage for Stripe Link may be somewhat limited. I believe that the unit test coverage may be handled adequately by tests on the UPE payment gateway; however, as far as I'm aware there is little in the way of E2E test coverage for this feature. I make this presumption after having made wholesale changes in #5282 and discovering that all the tests still passed obliviously and deliriously.

The Stripe Link integration relies authenticating the user through Stripe and then autofilling their fields at checkout once authorised. The process to login via OTP and select or edit stored payment methods and addresses is very similar to the flows performed by our Platform Checkout experience, although Stripe Link's entire functionality is completed through iframed modals that are presented on the checkout page itself. For a much more in depth description of these features, I'd invite you to consult the [description of the UPE integration PR](https://github.com/Automattic/woocommerce-payments/pull/5282#issue-1494541682) I authored in #5282.

I am not sure how feasible it is to model the Stripe Link checkout flow in the form of relevant E2E tests, since the majority of this user experience is completed inside iframes that we do not host, but if it were possible to at the minimum add some test coverage to capture the interactions between Stripe Link and other express checkout payment methods, that'd be grand.

This work is probably more relevant, but not exclusive to, our WooPay and UPE compatibility project. 

### Acceptance criteria

* Confirm adequate unit test coverage for Stripe Link.
* Add E2E test coverage for Stripe Link.
* Add E2E test coverage for Stripe Link when other Express Checkout methods are available or selected.

### Additional context

#4720 
#5282

**Comment by FangedParakeet** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Heisenberg-63586f2ec60359001310fa6a/issues/Automattic/woocommerce-payments/5338?planning-poker) with Zenhub @mdmoore @timur27

**Comment by timur27** [comment]
@mdmoore May I ask you to help us with estimating this issue? Thanks!
