### ISSUE TITLE
Intermittent TypeError: Cannot read properties of undefined (reading 'i18n') error from upe_checkout.js

### ISSUE THREAD

**Issue by shendy-a8c** [Automattic/woocommerce-payments#5347]
### Describe the bug

On checkout, I some times got this error which prevents UPE element from loading:
```
Uncaught TypeError: Cannot read properties of undefined (reading 'i18n')
    at upe_checkout.js?ver=5.2.0:1:31608
    at upe_checkout.js?ver=5.2.0:1:89786
    at upe_checkout.js?ver=5.2.0:1:89789
(anonymous) @ upe_checkout.js?ver=5.2.0:1
(anonymous) @ upe_checkout.js?ver=5.2.0:1
(anonymous) @ upe_checkout.js?ver=5.2.0:1
```

I tested with WCPay 5.2. Couldn't reproduce with 5.1 even after couple refreshes but I cannot be sure if it's not happening on 5.1 because it's an intermittent bug but based on my experience, it's likely that the bug is introduced in 5.2.

So far the affected merchants (5821264-zd-woothemes and 5823064-zd-woothemes) I am aware of use WCPay 5.2.

### To Reproduce

1. Create a clean site. I use JN site.
2. Install WCPay and WCPay Dev.
3. Check `Enable UPE checkout` and `Add UPE additional payment methods` on WCPay Dev.
4. Create a product.
5. Add to cart that product.
6. Go to checkout page.
7. Refresh the page until you see the error.

### Actual behavior

UPE is not loading. Error in Chrome dev tool console: `TypeError: Cannot read properties of undefined (reading 'i18n')`.

### Screenshots

<img width="469" alt="Screenshot 2022-12-30 at 04 40 15" src="https://user-images.githubusercontent.com/73803630/210013598-0e75024f-9755-40de-a8db-f2aae2ad29dd.png">
<img width="743" alt="Screenshot 2022-12-30 at 04 40 07" src="https://user-images.githubusercontent.com/73803630/210013602-2562c221-8a8e-4c56-885d-bed2d6b9d749.png">

### Expected behavior

No error and UPE element should load fine every time.

**Comment by shendy-a8c** [comment]
This PR might be related: https://github.com/Automattic/woocommerce-payments/pull/5257.

**Comment by csmcneill** [comment]
5823064-zen
5818033-zen
5821264-zen

All affected merchanst have been informed.

**Comment by johndcoy** [comment]
6228988-zd

Re-opening since I was able to replicate this issue in with the error message below:

`Uncaught TypeError: Cannot read properties of undefined (reading 'upeElement')`

<img width="1202" alt="Screenshot 2023-05-11 at 4 08 42 PM" src="https://github.com/Automattic/woocommerce-payments/assets/55294242/2c1e7eac-621a-4637-b7eb-0e8242c404f3">

**Comment by johndcoy** [comment]
The above issue was fixed by disabling Cred Cards and reenabling it:

![Screenshot](https://d.pr/i/ssOSn2+)
Screenshot link: https://d.pr/i/ssOSn2
