### ISSUE TITLE
Search and Filter Transactions

### ISSUE THREAD

**Issue by SiR-DanieL** [Automattic/woocommerce-payments#535]
It would be handy to be able to search transactions by order ID, customer name, customer email, transaction ID, card last 4 digits.

Also, maybe we can filter by card type, month of the transaction, transaction type.

**Comment by dechov** [comment]
It's now possible to search by order number, customer name, and email, and to filter by date and transaction type.

Not currently possible to search by card last 4 digits, or to filter by card type.

**Comment by vbelolapotkov** [comment]
Duplicate of #156 and #616
