### ISSUE TITLE
Update client workflows with deprecation notices

### ISSUE THREAD

**Issue by jbordonado** [Automattic/woocommerce-payments#5355]
### Description
There are some deprecation notices appearing on test runs indicating some of the commands we use need to be updated.

Related read: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

### Acceptance criteria
* Each workflow run should not generate any deprecation notices

### Additional context
GitHub's plan is to fully disable them on 31st May 2023 so we should take care of it before that.

**Comment by deepakpathania** [comment]
- Check for server workflows as well.

**Comment by fashuvo** [comment]
> * Check for server workflows as well.

There are no server workflows using `set-output` or `save-state`.

Update: The server uses some old actions which are generating warnings. Created [an issue](https://github.com/Automattic/woocommerce-payments-server/issues/3074) for that.

**Comment by jbordonado** [comment]
@fashuvo As discussed (my bad), the bulk of the deprecated messages comes from older versions of GitHub actions libraries such as `actions/upload-artifact`. We'll need to upgrade those actions (which should have released a new version to comply with the new way of setting output and state) to get rid of those

You'll see such warnings in the `Summary` of each workflow run, so check for each type of workflow we have, both in the server and client. It might just be E2E test workflows, but it needs to be checked.
