### ISSUE TITLE
Multi-currency incompatibility with Subscriptions renewal: Currency can be changed when cart contains renewal order

### ISSUE THREAD

**Issue by mehamasum** [Automattic/woocommerce-payments#5356]
### Describe the bug
**Expected behavior**: Currency [can not be changed](https://github.com/Automattic/woocommerce-payments/blob/develop/includes/multi-currency/Compatibility/WooCommerceSubscriptions.php#L149-L153) when renewing a subscription (example: a subscription of 85.79 USD should renew at 85.79 USD, changing currency in "Customer payment page" should not have any impact)

**Current behavior**: Currency can be changed when renewing a subscription and the renewal order can have a wrong total  (example: a subscription of 85.79 USD can renew at 85.79 EUR, changing currency in "Customer payment page" works and changes the currency but not the total)

### To Reproduce
- Set USD as default shop currency
- Enable multi currency, enable EUR and some other non-USD currencies
- Set customer currency to USD, purchase a subscription product
![image](https://user-images.githubusercontent.com/12912469/210251335-3426a1cf-f547-41aa-aa46-17129b491eed.png)
- Set the Payment Method to Manual Renewal through Admin UI of Subscription
![image](https://user-images.githubusercontent.com/12912469/210251365-09cce694-4237-4206-b490-a3db63f02e53.png)
- Renew the Subscription through Admin UI, this will create a renewal order
![image](https://user-images.githubusercontent.com/12912469/210251422-fd70ab5c-99b2-4d0c-92fa-a3dfee6cad39.png)
![image](https://user-images.githubusercontent.com/12912469/210251451-b37a74cb-ed94-4f95-b994-ff68fd3f9558.png)
- Open the "Customer payment page" as the customer, change the currency to EUR or any other non-USD one
![image](https://user-images.githubusercontent.com/12912469/210251468-2d185b8a-10a5-40e5-9b1b-e6460b4080c1.png)
  - Expectation is that the currency of the renewal order can not be changed
  - Notice that the currency can be changed, the total shown in the non-USD currency is same as the USD total. Pay for the order, notice the renewal order is completed with the wrong total  
    ![image](https://user-images.githubusercontent.com/12912469/210252005-073b2dda-b89f-4189-a3c6-8e0019799114.png)
    ![image](https://user-images.githubusercontent.com/12912469/210251680-14fee944-53eb-4713-916e-9869f4ac67df.png)

**Comment by haszari** [comment]
@mehamasum in your reproduce steps this requires a manual renewal. Do you know if this issue affects any other ways to pay? If it's manual renewal only then this is low priority as it's an edge case (manual renewal is less impact than say checkout or automatic renewal). 

If this is causing major pain for a common flow on WooCommerce.com, please add details to help us prioritise.

FYI @Automattic/sigma since this is an interaction between multi-currency and subscriptions.

**Comment by jessepearson** [comment]
@mehamasum Can you confirm what theme is being used here? Is this happening on WooCommerce.com?

There is code in place that should make it to where the currency switcher should not appear if there's a subscription renewal in the cart. I checked this out with Storefront and TwentyTwentyThree, and I couldn't get the legacy widget, nor the block switcher to show.

**Comment by mehamasum** [comment]
@haszari I haven't seen any other paths other than manual renewal flow. This is not a major issue for WooCommerce.com either as we have [applied a patch](https://github.com/Automattic/woocommerce.com/pull/14796) to prevent it from happening.

@jessepearson This is happening on WooCommerce.com with a custom theme. You should be able to reproduce this by adding the `currency` query param on the "Customer payment page" (i.e. `?currency=EUR`).

**Comment by jessepearson** [comment]
@mehamasum Thanks for the tip. It actually clicked in my head last night that there are several ways to get around the widgets and I should have tried them 🤦
