### ISSUE TITLE
Improve copy in Subscriptions deactivation modal

### ISSUE THREAD

**Issue by aheckler** [Automattic/woocommerce-payments#5365]
The modal shown when deactivating the Subscriptions plugin with WC Pay active is in this file:

https://github.com/Automattic/woocommerce-payments/blob/master/includes/subscriptions/templates/html-subscriptions-plugin-notice.php

Screenshot:

![image](https://user-images.githubusercontent.com/5512652/210641473-c9146f5c-2852-478a-8053-57330db4e4e9.png)

The copy is OK, but could use some minor improvements, which I have suggested here:

> By deactivating the WooCommerce Subscriptions plugin, your store will switch to using the subscriptions functionality built into WooCommerce Payments. [Learn more](https://woocommerce.com/document/subscriptions/deactivation/).
> 
> Existing subscribers will need to pay for their next renewal manually, after which automatic payments will resume. You will also no longer have access to the [advanced features](https://woocommerce.com/document/payments/subscriptions-basics/comparison/) of WooCommerce Subscriptions.
> 
> Are you sure you want to deactivate WooCommerce Subscriptions?

**Comment by zmaglica** [comment]
Hi @haszari . Does team Helix have this issue under its radar? We're prioritizing the WCPay backlog, and we're uncertain if you are going to handle it.

**Comment by haszari** [comment]
Thanks @zmaglica ! Yes, we have this in `Next` on our maintenance board (and it should be straightforward).
