### ISSUE TITLE
Multi-Currency Shows Currency Symbol and Abbreviation in Cart Total

### ISSUE THREAD

**Issue by csmcneill** [Automattic/woocommerce-payments#5368]
### Describe the bug
When multi-currency is enabled via [WooCommerce Payments](https://woocommerce.com/products/woocommerce-payments/?aff=10486&cid=1131038), the `Total` amount on the `/cart/` and `/checkout/` pages will show the currency symbol (e.g. `$`) and the currency abbreviation (e.g. `USD`). Deactivating multi-currency resolves the issue.

### To Reproduce

1. Enable multi-currency.
2. Add at least one other currency to the site.
3. Add a product to the cart.
4. Navigate to the `/cart/` page and note that the line items under `Cart Total` have just the currency symbol—except for the `Total` line, which has the currency symbol and the currency abbreviation.
5. Navigate to the `/checkout/` page and note the same issue as item 4 under the `Your order` section.
6. Deactivate multi-currency.
7. Navigate to the `/cart/` and/or `/checkout/` pages again.
8. Note that the `Total` line item on these pages only has the currency symbol.

### Actual behavior

When multi-currency is enabled and there is more than one currency added to the site, the currency symbol and currency abbreviation are included in the `Total` line item instead of just the currency symbol.

### Screenshots

<img width="1110" alt="Markup 2023-01-05 at 10 01 15" src="https://user-images.githubusercontent.com/82999806/210826929-bea37074-091c-4b37-b239-521e5b7d9908.png">

### Expected behavior

The currency symbol/abbreviation should follow the same format as though WCPay is not active.

### Additional context

5833601-zen
p1672886044905769-slack-C7U3Y3VMY

**Comment by zmaglica** [comment]
@dwainm Hey Dwain. Is this issue on Helix's radar? We're prioritizing the WCPay backlog, and we're not sure if you are going to handle it.

**Comment by dwainm** [comment]
@zmaglica this falls under Sigma's responsibility, so we'll add it to our backlog.

**Comment by tpaksu** [comment]
@csmcneill This is by design, called explicit formatting, check "When to use short vs explicit formats" section in paJDYF-20W-p2. TL;DR: Totals are always shown in explicit format on frontend.
