### ISSUE TITLE
Payments > Overview improvement two

### ISSUE THREAD

**Issue by aheckler** [Automattic/woocommerce-payments#5371]
Filing issues for some improvements from this post: pbUcTB-1Rx-p2

The “Pending balance” and other items shown in the account balance box could use some tooltips / (i) icons to explain the differences between the various terms. Proposed tooltips below.

![image](https://user-images.githubusercontent.com/5512652/210854639-68653e23-a253-4287-b29c-e6920435af17.png)

- Pending balance: The amount of funds still in the two-day pending period.
- Next deposit: The next upcoming deposit to be sent to your bank account.
- Last deposit: The most recent deposit sent to your bank account.
- Available balance: The amount of funds available to be deposited.

Furthermore, a link to the [negative balance doc](https://href.li/?https://woocommerce.com/document/woocommerce-payments/fees-and-debits/account-showing-negative-balance/) could be surfaced dynamically whenever the balance is negative.

**Comment by zmaglica** [comment]
Adding tooltips next to text shouldn't be a big problem. Do we agree on the proposed text? Once the text for tooltips if finalized, we can move this issue for prioritization.

**Comment by elizaan36** [comment]
@bradyv Making sure this is on your radar since it's related to Deposits work you're doing.

**Comment by zmaglica** [comment]
@aheckler Do we have any updates on this issue? Do we agree on the proposed text and designs?

**Comment by aheckler** [comment]
Let me think on it. I might want to rework our [When will I receive deposits?](https://woocommerce.com/document/woocommerce-payments/deposits/deposit-schedule/) page in the docs first, so that any links go to a known-good document.

**Comment by haszari** [comment]
@aheckler I'm thinking we should close this issue and ensure that the relevant info is included in upcoming deposits / payments overview designs. @bradyv can you comment to clarify if this is already included or if it needs consideration? 🙌

**Comment by bradyv** [comment]
@haszari @aheckler Yes this was specifically considered and included in the designs we put together. The deposits table should clear up confusion around next/last deposit, and we've added tooltips to the balances as per the recommendation here. They haven't yet been added to Figma but I'll put copy proposals in the design.

**Comment by haszari** [comment]
Great, thanks @bradyv ! Closing this issue, @aheckler feel free to review and feedback on the design (and/or check out Helix demos / work in progress when we start implementing).
