### ISSUE TITLE
Configure build steps for public facing JavaScript

### ISSUE THREAD

**Issue by jrodger** [Automattic/woocommerce-payments#54]
We're building the JavaScript for the admin pages with Webpack. The existing Stripe extension simply minifies the public facing (i.e. non-admin) JavaScript with the npm package `uglify-js`.

We're not currently doing anything with our public facing JavaScript (https://github.com/Automattic/woocommerce-payments/pull/48#issuecomment-487574917).

Options:

* Use Webpack and accept the extra 1Kb or so of bloat
* Use `uglify-js` for a smaller output but no transpiling

**Comment by vbelolapotkov** [comment]
Closing it as not relevant anymore. Webpack is used for building checkout scripts.
