### ISSUE TITLE
Tweaks to the logic to fetch customer currencies for analytics

### ISSUE THREAD

**Issue by dmallory42** [Automattic/woocommerce-payments#5420]
### Describe the bug

It was reported via Slack (p1674024754648289-slack-CGGCLBN58) that some merchants with large databases experience issues with a particular query which is made to fetch all the customer currencies used on the store. We should look into optimising this in the following ways:

1. This query is currently made regardless of the context (because it is cached anyway), but we should probably change it so that it is only made when in the context of the analytics pages.
2. We can also experiment with tweaking the cache [time](https://github.com/Automattic/woocommerce-payments/blob/f592aafc4bb27110c9718b01482146e2f9dbce4e/includes/multi-currency/MultiCurrency.php#L1373). Initially, it was chosen to have a good balance between not being made too frequently, and ensuring that when a new currency is used for the first time, the analytics would recognise this and allow filtering by that currency. Possibly we should either think about making the cache time longer, or implementing a better way to detect when a new currency is used for the first time.
 3. Potentially, we could add a filter to allow this to be tweaked on a store by store basis.

**Comment by jessy-p** [comment]
@Automattic/sigma

**Comment by tpaksu** [comment]
@dmallory42 I would like to see the results when we disable the query mods first, if it contains anything funky, but what would you think about having a toggle on the multicurrency settings page that enables/disables the multicurrency analytics as a solution for the above issue? Big players can disable it immediately as a self-service option, if it's not something they use frequently.

**Comment by dmallory42** [comment]
Thanks for the ping @tpaksu ! 

> what would you think about having a toggle on the multicurrency settings page that enables/disables the multicurrency analytics as a solution for the above issue? Big players can disable it immediately as a self-service option, if it's not something they use frequently.

Yeah - I wouldn't be against that - we have to be careful about where we use this though. We can disable some of the filters which are run (such as the [one](https://github.com/Automattic/woocommerce-payments/blob/c4ec2b80dcc7847a0e6d7d42ce3cef7ebf73da8a/includes/multi-currency/Analytics.php#L506) which is mentioned in this issue) if the user doesn't use Multi Currency, because we wouldn't need to have the current check which sees if they've had any multi-currency orders in that case.

But with regards to the analytics, we'd still need to have a query to check if they've _ever_ used Multi Currency (like querying to see if there are any orders) because otherwise the store analytics could be not converted properly! 

I think (hope) that COT will also help make these queries more efficient. 🙂

**Comment by tpaksu** [comment]
Closing this one because it's mostly handled in these new issues:

- https://github.com/Automattic/woocommerce-payments/issues/6852
- https://github.com/Automattic/woocommerce-payments/issues/6814
- https://github.com/Automattic/woocommerce-payments/issues/7000

And others will come.
