### ISSUE TITLE
IPP Interac Transactions Displayed With VISA icon

### ISSUE THREAD

**Issue by malinajirka** [Automattic/woocommerce-payments#5441]
### Describe the bug
Interac transactions on the Transactions list and transaction detail contain a small "VISA" image.

### To Reproduce

1. Collect an in-person Payment on a Canadian store using the woo mobile app using WisePad 3 and an interac card.
2. Click on Payments -> Transactions
3. Notice the row with the payment contains "VISA" icon in the "Payment method" column
The same icon is used also on transaction detail.

Example transaction:
URL https://testingwcpayincanada.wpcomstaging.com/
PI pi_3MTNL02HcN9LXx8K17PQ8oYg

### Screenshots
<img width="929" alt="Screenshot 2023-01-23 at 11 37 50" src="https://user-images.githubusercontent.com/2261188/214020184-678e96ca-61ed-47ce-aef7-d428e1c436c8.png">
<img width="922" alt="Screenshot 2023-01-23 at 11 38 08" src="https://user-images.githubusercontent.com/2261188/214020196-b5b7922f-a32a-45ea-99ff-d8815f30ca6a.png">

### Expected behavior
I'd expect an Interac icon would be used for interac transactions.

### Additional context
Relevant discussion p1674237097113869-slack-C025A8VV728

**Comment by zmaglica** [comment]
Hi @anu-rock . Do you maybe know, will team Fusion work on this issue? If you are planning to take it under your wing, perhaps you can prioritize it according to your plans and bandwidth.

**Comment by anu-rock** [comment]
Hey @zmaglica, thanks for your ping. This is indeed something @Automattic/fusion might work on. But right now it needs some design-related discussion. As we noted in the Slack thread referenced above, at the moment we intentionally display shopper's card brand logo (visa, mastercard, etc.) irrespective of payment method (card, in-person, or Interac).

cc @elizaan36 to check if Interac transactions should use a different logo.

**Comment by elizaan36** [comment]
We do have different logos for bank transfers (if a card isn't used). 
<img width="955" alt="image" src="https://user-images.githubusercontent.com/5121465/223513270-f6d89f2d-321e-490d-ab37-94a75e0cedff.png">

I'm not familiar with Interac - Is it a bank transfer service or a payment service that facilitates card payments?

**Comment by kalessil** [comment]
@elizaan36 : it's a Canada-specific payment provider. Their specific  is that you must present physically and use your card to purchase and refund payments via a terminal reader.

As In-Person Payments are de-facto card payments, we iterated here - https://wcpay.wordpress.com/2022/05/13/displaying-ipp-transactions-design-i1/ with handling them as card transactions, and added differentiation of channels - online and in-person. And we display card brands as part of that design iteration.

Hope that helps.

**Comment by kalessil** [comment]
@anu-rock , could you please look up into intent 'pi_3MTNL02HcN9LXx8K17PQ8oYg' and check which brand is presented in the charge object? If it's 'visa', we should close the issue.

**Comment by anu-rock** [comment]
Full logs aren't available as they are more than 30 days old. But as per p1674472037615349/1674237097.113869-slack-C025A8VV728, the `brand` field is indeed "visa".

Honestly, I don't have a strong opinion about whether to show the logo for Interac or the actual card's brand. FWIW, it's possible to use fields from the payment method object to know when it's an Interac payment (eg. payment method name, network).

Looping in @toupper for his thoughts.

**Comment by elizaan36** [comment]
My question would be, is there any benefit for merchants to know when it's a payment from Interac? Since I'm not sure if that's useful information it's hard to say for sure, I'd lean towards presenting the card brand (Visa/MC) since that's the same approach taken with other payment providers.

**Comment by toupper** [comment]
Thanks @anu-rock for pinging me here.

> My question would be, is there any benefit for merchants to know when it's a payment from Interac? Since I'm not sure if that's useful information it's hard to say for sure, I'd lean towards presenting the card brand (Visa/MC) since that's the same approach taken with other payment providers.

Showing the card brand in the same way as with other payment providers is ok for me, we can keep it that way and reopen this issue if users are confused about that 👍

**Comment by anu-rock** [comment]
@kalessil I'm curious if this issue was fixed elsewhere.

**Comment by kalessil** [comment]
Sorry, I re-checked the ticket from my reminder. Given that Interac is still a card and we know the brand, I re-checked the comments, and based on what Stripe holds in charge data, displaying Visa here is a valid case.

If the subject still feels relevant, someone needs to reach Stripe and request a fix for the brand identification.
If we convince Stripe to do so, we have to catch up on WooPayments side and add support for a new brand.

My understanding of the financial sector is that there is a limited amount of card providers (Visa, Mastercard and etc.)
If Interac re-brands cards serviced by Visa, it's technically Visa until we convince Stripe to recognize Interac as an independent brand in the context of charge object data.

**Comment by kalessil** [comment]
Based on that thinking, I closed the issue - feel free to re-open @anu-rock.

**Comment by anu-rock** [comment]
@kalessil Sure, thanks for the clear explanation. It makes sense to keep the issue closed.
