### ISSUE TITLE
[SPIKE] Fees: in test mode, enforce test card countries in UPE form

### ISSUE THREAD

**Issue by kalessil** [Automattic/woocommerce-payments#5463]
### Description

The test cards' country is not resolved properly when typing a new card into the UPE form (on Stripes' side).

In client/checkout/classic/upe.js we have the following handler:
```php
		upeElement.on( 'change', ( event ) => {
                        // ...
			setPaymentCountry( event.value.country );
			// ...
		} );
```

Explore opportunities to detect if we are in test mode and can access the raw card number.
If so, force mapping as per https://stripe.com/docs/testing#international-cards.

### Dev notes

In cli-code it was a special handling for test mode country dispatching, which needs to be dropped if the Spike succeeds.
The event is also triggered for, e.g., Link, so additional checks on payment method type are needed.

### Additional context

- p1674655555138179-slack-CGGCLBN58
- p1663144462776769-slack-C9976E5MJ
- pbUcTB-23B-p2
- https://github.com/Automattic/woocommerce-payments/issues/4679

**Comment by zmaglica** [comment]
Moving this issue into other queue pipeline since it is part of Pulsar’s backlog and team Pulsar will prioritize it.

**Comment by kalessil** [comment]
Update: I did evaluate if we can access the card number when injecting the country, but that's not feasible - none of the card number/prefix are available in the event. Hence we are depending on Stripe here.

Relying on billing/shipping address might be an alternative for the test mode, but this might cause even more issues.

**Comment by dmvrtx** [comment]
I've added a logging breakpoint and can confirm that Stripe always returns `US` as a payment country for test cards. Using a real card I could see an appropriate country code.

Stripe's Payment Element doesn't produce any other data that could be used to guess country code. We could try to get country from billing details when in test mode, but the test mode flag should be passed down to the point where UPE is created.

**Comment by dmvrtx** [comment]
Closing this as it is not feasible in a meaningful way.
