### ISSUE TITLE
Refactor payment method buttons and separators rendering

### ISSUE THREAD

**Issue by timur27** [Automattic/woocommerce-payments#5472]
#### Why is the refactoring needed?
There was a fix implemented [here](https://github.com/Automattic/woocommerce-payments/pull/5399) and [here](https://github.com/Automattic/woocommerce-payments/pull/5451) that resolves the issue of displaying multiple separators on the checkout, cart, product details pages. 

After the fix, the button and separator displaying implementations are separated from each other. With that, a few drawbacks are currently visible, and these should be resolved once the refactoring is completed: 
1. In a nutshell, the logic deciding whether we should render the button and the separator is duplicated (see `WC_Payments::display_express_checkout_separator_if_necessary` for the separator and `WC_Payments_*_Button_Handler::init` for `Platform_Checkout`, `Payment_Request` and `Stripe_Link` accordingly. This will lead to situations when e.g. the WooPay button logic is changed in the future, we might easily forget to update the logic in the separator rendering class, which will immediately result in displaying the separator alone when the button is disabled.
2. Separator rendering logic is located in `class-wc-payments.php`, which doesn't seem to be its direct responsibility.
3. There's limited test coverage due to static methods in the `class-wc-payments.php` class.

Ideally, we could create a new class that will merge and orchestrate all the logic from both button and separator rendering in one place and test it out properly.

#### Acceptance criteria
1. Button and separator displaying logic is merged into one place.
2. [The bug with the multiple separators](https://github.com/Automattic/woocommerce-payments/issues/5339) doesn't appear (no regression after the changes within this issue).
3. All the logic is covered with tests.

**Comment by jessy-p** [comment]
@Automattic/pulsar

**Comment by timur27** [comment]
Hey @zmaglica @jessy-p. Currently, this issue can be addressed within the split-UPE project only as [the split UPE branch](https://github.com/Automattic/woocommerce-payments/pull/3968) wasn't merged yet. After it's merged, this can be taken basically by any team to work on. Before this happened, I think adding `category:projects` label and possibly addressing this by @Automattic/heisenberg-woopay-upe-compatibility would be the best option. Sorry for not providing this information earlier.
