### ISSUE TITLE
Minimal Implementation of Progressive Onboarding Form

### ISSUE THREAD

**Issue by dmallory42** [Automattic/woocommerce-payments#5473]
### Description

This issue will cover the creation of the form for Progressive Onboarding. This will be a minimal form (not concerned with the design, just to add the fields and ensure they are getting passed to the server). It may depend on the components developed in #4744.

Validation of the form will be covered by #5474.

### Acceptance criteria

* The form contains all of the expected fields and is passed to the server.

**Comment by ismaeldcom** [comment]
Increased estimate to 4 due Stepper component implementation.
