### ISSUE TITLE
Submit and Redirect to Stripe

### ISSUE THREAD

**Issue by dmallory42** [Automattic/woocommerce-payments#5476]
### Description

We will need to adjust our existing logic, currently we pass a progressive flag from the client, but this will need to change since the intelligent router will decide whether to pass the user to PO or not. This issue handles any changes required to the Stripe redirect performed by the onboarding form.

### Acceptance Criteria

* We appropriately redirect users to either the normal Stripe KYC, or the PO KYC, with values prefilled.

**Comment by oaratovskyi** [comment]
Reasonable to take after https://github.com/Automattic/woocommerce-payments/issues/5475

**Comment by ismaeldcom** [comment]
Will be probably handled within #5779

**Comment by oaratovskyi** [comment]
@ismaeldcom I also thought so, but it does not work when `prefill` is passed. We'll need to tweak plugin PHP side or maybe even server. I'll do that in #5779 + it will be easier to review and test one by one

**Comment by ismaeldcom** [comment]
🤔 It should work, at least it was working before. If the prefilled data is invalid (according to Stripe) it will create an empty account, that can be the case.

**Comment by ismaeldcom** [comment]
Oh! I found it while reviewing your PR, we will need to update [the current prefill](https://github.com/Automattic/woocommerce-payments/blob/28e46d6ff48a2135b97eb10d68b6052c48b33305/includes/class-wc-payments-account.php#L1008-L1015) to make it work like `progressive`. Right now we're only reading country and business/company type from the URL. So yes, it will be handled in a different PR 🙁
