### ISSUE TITLE
Restore Onboarding Flow State

### ISSUE THREAD

**Issue by dmallory42** [Automattic/woocommerce-payments#5477]
### Description

We may want to allow a user to leave the new onboarding flow process and return to it later. This could be done for example by saving in the account meta, or an option cache what the user has done so far, so that they can pick up the onboarding again at a later date. This only covers the new onboarding flow form, including its context and the `Stepper` one.

### Acceptance criteria

* User can leave the onboarding and come back.
* It will remember where they were in the onboarding, and prefill what they have already filled out.

**Comment by brandonwanA8C** [comment]
This is a great feature to have, also can enable Growth/Drip marketing to deep-link the email reminder to the exact spot of the Churn.

@dmallory42 as we can't control the Stripe-hosted experience, what is our technical capability today to allow the user to go straight to the page with a deeplink (e.g. TOFU/Biz-detail) where they dropped off and have the previously entered data persisted?

**Comment by ismaeldcom** [comment]
>what is our technical capability today to allow the user to go straight to the page with a deeplink (e.g. TOFU/Biz-detail) where they dropped off and have the previously entered data persisted?

We don't have any routing system to create deep links to specific parts of the onboarding flow. But we cab just link them to the onboarding flow, and just recover the persisted state to allow them to continue where they left off.
