### ISSUE TITLE
Tracking Events for PO

### ISSUE THREAD

**Issue by dmallory42** [Automattic/woocommerce-payments#5478]
### Description

We need tracking events for each stage of the onboarding, e.g. `wcpay_onboarding_start`, `wcpay_onboarding_step1`, `wcpay_onboarding_complete`.

We may have some existing events for the start/end of the Stripe KYC, so we need to decide whether to have new events, or to also use the existing ones.

We could also decide to store the entire status of the form within the tracking event, we need to talk to product/data about their needs so the issue has a slightly higher estimate to reflect this uncertainty.

Conversation with product: p1674855453106769/1674820910.879359-slack-C03PGHYA8TG

### Acceptance criteria

* All desired tracking events are present and fired at the correct point in the onboarding.

**Comment by ismaeldcom** [comment]
As a recap from our last team call, it would be good to track the status of every onboarding step, handling drop-outs, and possibly also amount of time invested.

**Comment by elizaan36** [comment]
hey all, was just digging through to find a tracking issue :) Let me know if @brandon or I can clarify anything on what needs to be tracked for the new flow. I think the plan is to set up a tracks event for each click to learn more granular details about progress and drop offs.
