### ISSUE TITLE
Builder post-onboarding UX

### ISSUE THREAD

**Issue by dmallory42** [Automattic/woocommerce-payments#5481]
### Description

As per #5480, if a user onboard as a builder it will be possible for them to create an account in dev mode. We should consider adding some prompt to the dashboard that will allow this user to initiate a full onboarding when they are ready to do so (so that the builder can easily hand the site over to their client when ready).

### Acceptance Criteria

- When an account is created in 'builder' mode, a new onboarding can easily be initiated.
- Designs to follow based on conversations with the design team.

**Comment by daquinons** [comment]
This will (or should :D ) close #2459

**Comment by daquinons** [comment]
We should consider also handling https://github.com/Automattic/woocommerce-payments/issues/2734 in this issue and close it as well
