### ISSUE TITLE
E2E automated tests for Auth & Capture critical flows

### ISSUE THREAD

**Issue by mgascam** [Automattic/woocommerce-payments#5493]
### Description

We would like to automate the testing of the critical flows related to the auth & capture with e2e test. 
### Acceptance criteria

Implement e2e tests for the following critical flows:

* [Manual capture](https://github.com/Automattic/woocommerce-payments/wiki/Testing-instructions-for-critical-flows#manual-capture)
* [Manual capture from Uncaptured tab in Transactions page](https://github.com/Automattic/woocommerce-payments/wiki/Testing-instructions-for-critical-flows#manual-capture-from-uncaptured-tab-in-transactions-page)
* [Manual capture from payment details page](https://github.com/Automattic/woocommerce-payments/wiki/Testing-instructions-for-critical-flows#manual-capture-from-payment-details-page)
* [View Uncaptured transactions in Transactions page](https://github.com/Automattic/woocommerce-payments/wiki/Testing-instructions-for-critical-flows#view-uncaptured-transactions-in-transactions-page)

### Testing instructions

TBD

**Comment by kalessil** [comment]
Closing, as E2E automation is covered buy https://github.com/Automattic/woocommerce-payments-server/issues/4454
