### ISSUE TITLE
Multiple UPE - Improve design of UPE elements at checkout. 

### ISSUE THREAD

**Issue by FangedParakeet** [Automattic/woocommerce-payments#5502]
### Describe the bug

This issue is to resolve inconsistencies and design flaws noted in our first round of internal testing. Please refer to this comment for more details -> paJDYF-6WA-p2#comment-15823

> For Giropay, the “After submission…” text appears inside this white box, which is inconsistent with the rest of the methods.

![giropay selected](https://cdn-std.droplr.net/files/acc_1104206/s0Dm5M)
_We already know giropay is selected!_

I'm not sure that Stripe currently offers us the ability to resolve this, but it doesn't hurt to have a look and find out! I don't think I can see anything specifically mentioning that this might be possible to customise in [Stripe's documentation](https://stripe.com/docs/elements/appearance-api), so we may need to reach out to Stripe for more information on this issue.

> Between the usual checkout form and the dropdown inside some of the payment methods, we have two styles of dropdown menus.

![Two different dropdowns](https://cdn-std.droplr.net/files/acc_1104206/KvS0Vb)
_A tale of two dropdowns_

[Stripe does give us some control to customise dropdown styles](https://stripe.com/docs/elements/appearance-api?platform=web#dropdown), so it's possible that this could be achieved. Although, I assume this will be very challenging for custom WC themes, where the classes of custom dropdown elements are not consistent enough for us to scrape and parse CSS styles. 

> This might be something for legal to look at, but this paragraph under the SEPA method seems odd, since no other methods have anything like this.

![SEPA mandate](https://cdn-std.droplr.net/files/acc_1104206/skVaeU)
_Wordy SEPA mandate_

This mandate is presented by Stripe; however, I believe it was our intention to only present these terms when a user is about to save their payment information at checkout. Please can we check whether we have the ability to remove this mandate: if so, we should only reveal the mandate when it is truly appropriate. 

> The P24 logo looks a bit odd considering it’s the only one without a background color of some sort. Even a white rectangular background would help set it off against the page background, similar to the logos above it.

![p24 logo](https://cdn-std.droplr.net/files/acc_1104206/LBo3Uy)
_Unpretty P24 logo_

Please consult with design to see if we can get a more consistent logo for P24 or if this current logo is required. 

### To Reproduce

All of these issues are visible in the split UPE shortcode checkout with additional payment methods enabled and currency set to EUR.

### Actual behavior

See above.

### Screenshots

See above. 

### Expected behavior

It doesn't do bad, but look good.

### Desktop (please complete the following information):

* OS: [e.g. iOS]
* Browser [e.g. chrome, safari]
* Version [e.g. 22]

### Smartphone (please complete the following information):

* Device: [e.g. iPhone6]
* OS: [e.g. iOS8.1]
* Browser [e.g. stock browser, safari]
* Version [e.g. 22]

### Additional context

paJDYF-6WA-p2#comment-15823

**Comment by FangedParakeet** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Heisenberg-63586f2ec60359001310fa6a/issues/Automattic/woocommerce-payments/5502?planning-poker) with Zenhub @mdmoore @timur27

**Comment by timur27** [comment]
@FangedParakeet I'm curious if we want to fix the P24 logo within this issue in case it takes us a lot of effort since the split UPE design won't be used after enhanced UPE is implemented? All the other inconsistencies seem to touch the legacy UPE, so they make sense to be resolved within this issue, I just wanted to confirm with you on the P24 payment method.

**Comment by FangedParakeet** [comment]
>since the split UPE design won't be used after enhanced UPE is implemented

Just FYI, the split UPE design will live on: we will not be returning to the monolithic Popular payment methods section any time soon. To confirm, we will continue to present multiple payment gateways at checkout, each serving a single payment method. Each payment gateway will still contain a UPE payment element, but we will be using the new payment flow, without an initial payment intent and with server-side payment intent confirmation. We may not be using the `UPE_Split_Payment_Gateway` class specifically in our future implementation nor the same checkout scripts, so we should be sure that whichever solution is developed here is extendable/importable, but the gateway split will survive.

That being said, from the front-end perspective, we will be using the same payment element, the same appearances API, and it's very likely we will continue to use the same `.wcpay-upe-element` class as well. I think that should allow us to resolve these issues before the new UPE implementation is complete. Let me know if I'm missing anything though and apologies for any prior misconceptions.

**Comment by timur27** [comment]
Thanks for the clarification, Samir, and sorry for any misunderstanding. I now went through the initial P2 that compares different approaches to the split UPE project, and things are clear to me now.

**Comment by FangedParakeet** [comment]
> For Giropay, the “After submission…” text appears inside this white box, which is inconsistent with the rest of the methods.

It is not possible to alter the text inside the element, but the white box has been removed and made more consistent with other payment method elements in #8230.

> Between the usual checkout form and the dropdown inside some of the payment methods, we have two styles of dropdown menus.

Stripe does offer appearance API parameters for `.Dropdown` elements...but these do not apply to these dropdowns. These are `select` inputs that are styled by the regular `.Input` tag. Moreover it is not feasible to scrape our own dropdown styles, since the pseudo-dropdown input that users use to fill in their details in the Woo checkout (e.g. country dropdown) is only added to the page when the input is focussed and focussing on elements to trigger CSS states will cause issues with the checkout, as described in #8230.

> This might be something for legal to look at, but this paragraph under the SEPA method seems odd, since no other methods have anything like this.

It is not possible to change this text, regardless of whether terms/mandates are required or not. These terms even displayed on [Stripe's preview implementation](https://qry5s.sse.codesandbox.io/) of this element and it will not be possible for us to remove it in our checkout.

> The P24 logo looks a bit odd considering it’s the only one without a background color of some sort. Even a white rectangular background would help set it off against the page background, similar to the logos above it.

It appears that this has been resolved in another issue. All other logo display issues should be resolved in #8230.
