### ISSUE TITLE
Unify onboarding logic and experience

### ISSUE THREAD

**Issue by ismaeldcom** [Automattic/woocommerce-payments#5508]
### Description
With the new progressive onboarding flow, we're also changing how WCPay onboarding works. So it will be good to update the existing code and come with a unified solution to avoid making tricky redirections based on the flow we want to use.

For now, we have the connect page, that's skipped when the merchant comes from a task, and the new onboarding page that's injected before the Stripe redirection.

We could simplify it having just a single onboarding page, to avoid making so many conditions and redirections.

We also need to consider what to do with the current connect page in terms of UI/UX.

### Acceptance criteria
- Every merchant lands on the same WCPay page after being redirected to onboarding.
- The connect account page design is implemented.
- Jetpack connection is made at the appropriate step.

**Comment by dmallory42** [comment]
@elizaan36 we wanted to ping you about this issue - we're proposing that the Connect screen (shown in the screenshot below) be replaced by a new screen that would be the first step of the new onboarding experience. 

<img width="1007" alt="Screenshot 2023-02-02 at 13 56 05" src="https://user-images.githubusercontent.com/11770181/216343915-1d15f4bf-0174-41c1-b6a7-c00f242f93fc.png">

This may require us to add an 'intro' to the new onboarding experience, I've attached below a screen from one of Magda's designs as an example:

<img width="1450" alt="Screenshot 2023-02-02 at 13 58 36" src="https://user-images.githubusercontent.com/11770181/216344567-fd35533d-f140-4f17-9cce-91840083eb4f.png">

What do you think? Do you think it's a better experience, or is it better to stick to the current flow? The alternative would be to keep the current connect screen, and have it redirect to the new onboarding flow.

**Comment by daquinons** [comment]
> Regarding [this issue](https://github.com/Automattic/woocommerce-payments/issues/5508#issuecomment-1413793451), we should keep the Connect screen and redirect to the first step in the flow. However there’s a new design for the connect screen that we can implement. We can replace the header card with one that’s more inline with the Payments task.

<img width="687" alt="Screen Shot 2023-04-01 at 9 55 51 PM" src="https://user-images.githubusercontent.com/5121465/229328584-d6c817e0-25c8-43a6-876a-637ce6450836.png">

From [here](p1680030211937399/1680029417.340619-slack-C03KTTK2YMA)

**Comment by elizaan36** [comment]
Just a note that I updated the card to have the correct CTA. Since WCPay is installed at this point, the CTA will be "Finish setup" which will redirect to the new onboarding flow.
