### ISSUE TITLE
Credit card order payment fails with enabled UPE

### ISSUE THREAD

**Issue by timur27** [Automattic/woocommerce-payments#5512]
With the UPE enabled, when paying for an order with the CC payment method, users are not redirected to the order summary page, instead, the page is in a loading state with the error in the console: 

```
upe.js?c32f:458 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'upeElement')
    at checkUPEForm (upe.js?c32f:458:36)
    at handleUPEOrderPay (upe.js?c32f:505:32)
    at HTMLFormElement.eval (upe.js?c32f:824:4)
    at HTMLFormElement.dispatch (jquery.js?ver=3.6.1:5430:27)
    at elemData.handle (jquery.js?ver=3.6.1:5234:28)
```

The bug was encountered during the first round of split UPE testing a few days ago. More details here: paJDYF-6WA#comment-15916. 

Acceptance criteria: 
* Pay for page allows users to pay with a credit card without errors when UPE is enabled and disabled

**Comment by csmcneill** [comment]
Just to confirm: this is with Split UPE and not 5.4.0, correct?

**Comment by timur27** [comment]
> Just to confirm: this is with Split UPE and not 5.4.0, correct?

Yes, @csmcneill. Thanks for double checking.
