### ISSUE TITLE
Hook for safe mode to avoid clicking transfert or create

### ISSUE THREAD

**Issue by myalban** [Automattic/woocommerce-payments#5521]
### Description
If you use dynamic website URL 
`
define( 'WP_SITEURL', $websiteURL);
define( 'WP_HOME', $websiteURL);
`
That share the same database, you can see the safe mode but in this case, it's not user friendly as, we have to click to accept or transfert.

### Acceptance criteria
Have a hook to defined rules and avoid manuel action

**Comment by RadoslavGeorgiev** [comment]
This issue should have been fixed with [this Jetpack update](https://github.com/Automattic/jetpack/pull/22805), but it seems like the change is not included in the package, used by WooCommerce Payments.

We have prioritized this issue, but in the meantime we'd recommend installing the latest version of Jetpack in order to load the new library, and avoid warnings.

**Comment by RadoslavGeorgiev** [comment]
@myalban we checked, and the issue [was fixed](https://github.com/Automattic/woocommerce-payments/pull/4082#pullrequestreview-931312833) nearly a year ago (in version 4.0.0). Could you please verify that you are using an up-to-date version of WooCommerce Payments?

**Comment by jessy-p** [comment]
This issue impacts Onboarding, Account management, General purpose communications and communication tools, so assigning to Moltres (based on team responsibilities Pc2DNy-3z-p2) @daquinons. Assigning as part of Gamma Triage process PcreKM-yM-p2.

Tagging as part of re-evaluating older issues in the backlog, please have a look and close if no longer relevant.

**Comment by daquinons** [comment]
Seems like the issue was fixed as stated here https://github.com/Automattic/woocommerce-payments/issues/5521#issuecomment-1441332183 , feel free to ping us if is still occurring and we'll reopen the issue.
