### ISSUE TITLE
Multi-Currency Compatibility: Price conversion helper function

### ISSUE THREAD

**Issue by helgatheviking** [Automattic/woocommerce-payments#5524]
### Description

I was revisiting the [compatibility Module for Name Your Price](https://github.com/Automattic/woocommerce-payments/commit/55a751bed1ca82c92f831d359a10516b14947d9a). If you add an item to the cart in X currency. And then go to the cart and click "edit" you are taken back to the single product page. _Now_ if you switch the currency the pre-filled amount is converted from the old currency decimal separators to the new.

https://woo-helgatheviking.codeanyapp.com/product/simple-nyp/

It is not converted, but worse the commas/decimals can get borked depending on which currencies you are switching to/from. Example: 55,55EUR (55 eur and 55 cents) becomes 5555.00 USD (five thousand five hundred fifty five) dollars.

I've found a way around this by adding a "Raw" price and a currency into the edit link. And then on the single product page I can prefill the price reliably, by converting that raw price from the link currency into the current currency. 

This was working well with some of my other multi-currency integrations. However, I was going to write that for this plugin too, when I remembered that the approach to conversion is rather complicated. Is there a straight currency conversion helper yet? I think you could benefit (or at least I would benefit :) ) from a helper function that could take any price from X to Y currency. I think that would make integrations a lot easier. 

```
$converted_price = WCPay\MultiCurrency\MultiCurrency::convert_price( $amount, $from_currency, $to_currency )
```

or something like

```
$converted_price = apply_filters( $amount, $from_currency, $to_currency );
```

Or failing that... what's the best way to approximate that assuming `$x = 44.44' where it's always in the database decimal format. 

### Testing instructions

1. Create an NYP simple product
2. Add that product to the cart
3. Go to the cart and click on "Edit" to edit the price
4. Now back on the simple product page, switch the currency using a widget/switcher/whatever - Especially noteworthy if switching from say EUR to USD where the decimal separators are different

**Comment by zmaglica** [comment]
@dwainm is this issue on team Sigma's radar? I am triaging the WC Pay backlog, and I am not certain if you are going to handle it.

**Comment by dwainm** [comment]
@zmaglica , sure it's on our plate.

**Comment by jessepearson** [comment]
@helgatheviking I feel like adding a static method should be easy enough to do, but I want to make sure I understand what you're asking.

The new method, let's call it `convert_price` for now, would have 3 parameters:

* `$amount` - The amount to be converted.
* `$from_currency` - The currency the `$amount` is currently in.
* `$to_currency` - The currency the `$amount` should be converted to.

From the way you describe it, the `$amount` could be passed in `1,234.56` or `1.234,56` format, correct? If this isn't the case, then we might be able to make this straight forward and just do the math for conversions. If the format would need to be based off of the `$from_currency`, that could be pretty tricky. Formatting differs per locale, per currency, so the formatting typically relies upon the customer locale on top of the currency. These are all defined here:
https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce/i18n/currency-info.php

I am not sure if we would be able to get locale information from within a static method, but if we cannot, then we would need to make sure the `$amount` always came in as a specified format.

Can you confirm if the format of the `$amount` would always be the same, or would it already be subject to locale formatting?

**Comment by helgatheviking** [comment]
@jessepearson On my end, no matter the locale, the Name Your Price amount is always stored internally as `123.45` with a period-decimal. 

I have an issue https://github.com/kathyisawesome/woocommerce-name-your-price/issues/222 (not sure if you have access) but the gist of it is if you put a product in the cart as EURO with a custom price and then convert your site to USD the entered NYP price in the cart is not converted. 

I suspect the problem is [here](https://github.com/Automattic/woocommerce-payments/blob/develop/includes/multi-currency/Compatibility/WooCommerceNameYourPrice.php#L97-L102). In my other multi-currency compatibilities it's trivial to do the conversion and set the cart item 'nyp' data to the new amount. However, with WC Payments, I can't figure out how to do the calculation without a helper.

Though re-reading a few more times it looks like there _is_ a helper `MultiCurrency\get_price()`[https://github.com/Automattic/woocommerce-payments/blob/develop/includes/multi-currency/MultiCurrency.php#L825] so I am not sure what is not working in my integration.

**Comment by helgatheviking** [comment]
Update, My issue was that rounding to the nearest whole euro was making me think that 6USD was not getting converted to 5.89 EUR. major :facepalm: 

So looks like I don't _need_ this as much as I thought, but I still think there's value in replacing the compat module from doing the math and wrapping it all in a this currency to that currency converter.

**Comment by jessepearson** [comment]
> Update, My issue was that rounding to the nearest whole euro was making me think that 6USD was not getting converted to 5.89 EUR. major 🤦

Ya, that `get_price` method you mentioned will apply any rounding and price charm to the converted price, which isn't ideal for what you are working with.

I think what we can do is create a method to convert an amount directly from one currency to another. The only problem that I see is that if, for example, the store currency is USD and the conversion needs to be EUR to CAD, then we would need to convert CAD to USD, then USD to EUR. This is due to the rates in the store are based on the store's base currency.

**Comment by jessepearson** [comment]
@helgatheviking Could you check out what I've added in the below PR to see if that would work to solve the issue you and other developers may run into?

* https://github.com/Automattic/woocommerce-payments/pull/7202

**Comment by helgatheviking** [comment]
@jessepearson Yes, that's exactly what is needed. :muscle:

**Comment by helgatheviking** [comment]
@jessepearson Quick question... should I use this to update the entered price when the cart currency switches or should that still be charmed/rounded? For example if you enter 10USD and that's 9.31 EUR but it might get rounded to 9.40 or 10.00 or whatever the charm settings are.

**Comment by jessepearson** [comment]
> Quick question... should I use this to update the entered price when the cart currency switches or should that still be charmed/rounded? For example if you enter 10USD and that's 9.31 EUR but it might get rounded to 9.40 or 10.00 or whatever the charm settings are.

You would be able to use it to just do raw conversions, so it really matters on the use case. If you want to use the rounded and charmed versions of the prices, then you could use the `get_price` method you mentioned above, but if you wanted to have a raw conversion, you could use `get_raw_conversion`.

So, if 10 USD is converted to 9.31 EUR, you could choose to use that 9.31 EUR via `get_raw_conversion`.

This almost seems like you'd need to add some sort of toggle if WCPay Multi-Currency is active that allows the merchants to decide if they want rounding and charm to apply to NYP amounts. Like you noticed, some amounts could be low enough that the amount doesn't seem to change due to rounding.

**Comment by helgatheviking** [comment]
>This almost seems like you'd need to add some sort of toggle if WCPay Multi-Currency is active that allows the merchants to decide if they want rounding and charm to apply to NYP amounts.

Maybe, but I don't want to go adding more options when nobody has complained about it yet. In my other multicurrency integrations it's usually a more accurate conversion if the item is already in the cart. 

I was bewildered by the seeming lack of change. Granted entering a price in once currency and then changing currency in the cart is def one of those edge case things devs do more frequently than customers.

**Comment by helgatheviking** [comment]
Updating the https://github.com/Automattic/woocommerce-payments/pull/7172 NYP compat to use the helper

**Comment by jessepearson** [comment]
> Maybe, but I don't want to go adding more options when nobody has complained about it yet. In my other multicurrency integrations it's usually a more accurate conversion if the item is already in the cart.

Understandable, and the difference is likely due to everyone doing things differently.

> I was bewildered by the seeming lack of change. Granted entering a price in once currency and then changing currency in the cart is def one of those edge case things devs do more frequently than customers.

Ya, we've come across a few things recently that we haven't had any reports about, but it's likely because we're literally doing weird actions to purposely break things.

> Updating the https://github.com/Automattic/woocommerce-payments/pull/7172 NYP compat to use the helper

I had forgotten about NYP compat being built in. I see now the external function isn't needed, so I am going to remove that, then get my PR up for review.

**Comment by helgatheviking** [comment]
Not sure what you mean by external function. But as long as my changes are released at the same time as yours I think we're ok.
