### ISSUE TITLE
Can't enable CC payments

### ISSUE THREAD

**Issue by WillBrubaker** [Automattic/woocommerce-payments#5525]
### Describe the bug
As seen in 5934805-zen the user let us know that they were unable to enable credit card payments.

The checkbox was not ticked but was disabled, i.e. the appearance reflects that CC payments are not enabled, and the checkbox can not be checked to enable.

### To Reproduce

1. Disable UPE
2. Uncheck CC
3. Enable UPE but don't complete the setup. Close your browser tab when you see this: ![QGbhCe.png](https://user-images.githubusercontent.com/2127470/217126287-0fb3dbc9-4209-4686-b4e3-b2384da8f18b.png)
4. Navigate back to the WCPay settings. CC is disabled and can not enable.

### Expected behavior
To be able to enable CC payments if they're not already.

### Desktop (please complete the following information):

* OS: [e.g. iOS]
* Browser [e.g. chrome, safari]
* Version [e.g. 22]

### Smartphone (please complete the following information):

* Device: [e.g. iPhone6]
* OS: [e.g. iOS8.1]
* Browser [e.g. stock browser, safari]
* Version [e.g. 22]

**Comment by WillBrubaker** [comment]
5942573-zen

**Comment by Brianmitchtay** [comment]
Seeing this again in 6271733-zen

**Comment by zoemyers** [comment]
Again in 6320216-zen

Worth noting that disabling UPE and then checking the Credit Card option and then re-enabling UPE allowed this merchant to check the box and save the setting.
