### ISSUE TITLE
Client should render the onboarding form based on structure received from the server

### ISSUE THREAD

**Issue by dmallory42** [Automattic/woocommerce-payments#5526]
### Description

Following on from server-2989, we'll need to create a processor which accepts a JSON from the server and renders the onboarding form accordingly depending on the rules which are received.

### Acceptance criteria

* The client can render the form appropriately based on rules and fields received from the server.

**Comment by zmaglica** [comment]
@dmallory42 is this issue on team Moltres radar? I am triaging the WC Pay backlog, and I am not certain if you are going to handle it.

**Comment by dmallory42** [comment]
Hi @zmaglica, yes - this is related to the Progressive Onboarding project which we are currently working on. However, we are closing this issue as we've had some changing requirements after discussion within the team about how to handle the new onboarding forms.

Closing as no longer needed right now.
