### ISSUE TITLE
Split UPE: migrate saved SEPA tokens

### ISSUE THREAD

**Issue by frosso** [Automattic/woocommerce-payments#5531]
### Describe the bug

If a merchant switches from the "Legacy" UPE to the "Split UPE", saved SEPA tokens will not appear anymore.
We need to find a way to migrate the SEPA tokens to the new SEPA gateway.

We will also need to check if SEPA subscriptions are still working ~(but it should be working fine)~.

### Steps to reproduce
- Enable the "legacy" UPE
- Add SEPA tokens
- Disable the UPE
- Enable the "Split" UPE
- Ensure that SEPA tokens are still available

**Comment by frosso** [comment]
Team Fractal will take care of this - thanks @diegocurbelo and team!

**Comment by FangedParakeet** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Heisenberg-63586f2ec60359001310fa6a/issues/Automattic/woocommerce-payments/5531?planning-poker) with Zenhub @mdmoore @timur27

**Comment by frosso** [comment]
Looks like this never worked ( https://github.com/Automattic/woocommerce-payments/issues/3776 ) - closing.
