### ISSUE TITLE
Possible division by zero while preparing data before sending to Stripe

### ISSUE THREAD

**Issue by timur987** [Automattic/woocommerce-payments#5534]
### Describe the bug

There is no check for `$quantity` in this line https://github.com/Automattic/woocommerce-payments/blob/develop/includes/class-wc-payment-gateway-wcpay.php#L2499

As a result I saw an error.

### To Reproduce

I got that error while testing WCCOM right after experimental migration from MariaDb to MySQL8, so I can't provide you with clear instructions on how to reproduce it.

The only thing I want to convey here that we should add this check no matter how to reproduce it.

### Expected behavior

We should check against division by zero.

**Comment by leonardola** [comment]
@timur987 the link does not work anymore. Could you update it with a permalink?

**Comment by timur987** [comment]
Hey @leonardola, I need some time to figure out where was that division by zero. After some testing I either provide you with more details or close the issue. Thanks for the ping 🙌 .

**Comment by timur987** [comment]
Hey @leonardola, I looked through the code and noticed that, of course, the link I've provided is outdated but then I checked the current version and found that there are places where an error might occur.

Of course, we can assume that quantity in cart cannot be `0`, but we can't guarantee it because `$quantity` comes as and input parameter in the following places:
- in [update_product_price](https://github.com/Automattic/woocommerce-payments/blob/trunk/includes/multi-currency/Compatibility/WooCommerceProductAddOns.php#L197-L199) function, lines 197-199,
- in [get_product_calculation_price](https://github.com/Automattic/woocommerce-payments/blob/trunk/includes/multi-currency/Compatibility/WooCommerceProductAddOns.php#L276) at line 276,
- in [process_item](https://github.com/Automattic/woocommerce-payments/blob/develop/src/Internal/Service/Level3Service.php#L144-L148), lines 144 and 148.

It might be an overkill, but probably adding a "Division by zero" prevention check might be help down the road.

Since it's just a suggestion, feel free to ignore it (I assume that there should be another checks that deny processing items in cart with the quantity of `0`.

**Comment by vbelolapotkov** [comment]
Sending this one for triage. @timur987 the link in description is leading to the wrong place and I can't find where it comes from anymore, can you reproduce now or update the link?

**Comment by timur987** [comment]
Thanks for the ping, @vbelolapotkov!

As I wrote earlier, I stopped seeing a possibility of division by zero. Hopefully it was fixed before.
Due to that, I suggest to close this issue.
