### ISSUE TITLE
Implement Things To Do for Progressive Onboarding (WC Home)

### ISSUE THREAD

**Issue by oaratovskyi** [Automattic/woocommerce-payments#5547]
### Description
We need to implement Things To Do to prompt a Progressive Onboarding user to complete onboarding from WC Home. The urgency should depend on how close they are to the time/volume thresholds.

After payments are enabled: no notification
After the first sale is complete: default info notification
Balance is rising or 7 days from the first sale (1000 USD now in design):: the orange/warning color notif and slightly different message
Nearing thresholds - 21 days after the first sale or reaching 3000 USD (as it's now in design): The most urgent notification with the red color and error icon
After the limit is hit: Not sure how to handle this yet, but I think we should also have a message for when the user's payments have been disabled because they hit a limit (either 30 days or $5000 USD)
Successful onboarding: no notification

### Relevant Links
Designs for PO can be found here: s12xuy2TEGi3F91coVmxpF-fi-15788%3A257304

Unsure whether the exact wording of inbox notes has been defined, we can use this issue or the Slack channel to communicate with the Design team about this prior to working on this issue.

**Comment by ismaeldcom** [comment]
I'd like to highlight here that we **can't** easily match the proposed design due to an already mentioned blocker: p1674034659112079/1673976018.410019-slack-C03KTTK2YMA

**Comment by daquinons** [comment]
More on paJDYF-7m7-p2#comment-16544

**Comment by oaratovskyi** [comment]
Hey @elizaan36! According to the latest discussions linked above, we can't do much in the current situation regarding sorting and expanding the tasks.

I've attached the notices in their current state, please take another look 👀 at them! If the copies look good to you, I suggest closing this issue and creating another one after we have our dependencies updated, probably during the Unified Onboarding project (or Custom onboarding after recent changes).

cc @ismaeldcom @dmallory42 @vladolaru @daquinons 

| State | WC Admin | WCPay overview |
|-|-|-|
|14 days after account creation|<img width="418" src="https://user-images.githubusercontent.com/79862886/232035872-2dfc37fa-3a4e-4036-9a18-cae5b39ce171.png">|<img width="420" src="https://user-images.githubusercontent.com/79862886/232035822-933391d0-bad7-4ca8-a470-6e81fb250da9.png">|
|30 days after account creation|<img width="418" src="https://user-images.githubusercontent.com/79862886/232035722-8d34077a-b66b-4779-bb7b-c5053603dfaf.png">|<img width="420" src="https://user-images.githubusercontent.com/79862886/232035500-c00ef276-9b4d-43f3-91a2-198613e2454d.png">|
|First payment|<img width="418" src="https://user-images.githubusercontent.com/79862886/232036719-002bf8f2-715f-4720-8fc0-f75d3702f8db.png">|<img width="420" src="https://user-images.githubusercontent.com/79862886/232036613-ccb1b295-2d53-4c9a-a94a-c6a181d5e93f.png">|
|Balance raising|<img width="418" src="https://user-images.githubusercontent.com/79862886/232037963-04d21326-2110-4f14-8f37-3d49ee93f231.png">|<img width="420" src="https://user-images.githubusercontent.com/79862886/232037784-2435c657-949d-4b5d-87a4-a690715208d7.png">|
|Near threshold|<img width="418" src="https://user-images.githubusercontent.com/79862886/232038502-9bffcd84-eb70-40c1-a6d0-225a10825b39.png">|<img width="420" src="https://user-images.githubusercontent.com/79862886/232038365-2e3d10af-b09d-483b-852d-82d5bc2fb3de.png">|
|Over threshold|<img width="418" src="https://user-images.githubusercontent.com/79862886/232043682-d5c41fe7-6d68-4ec4-bdf2-090e7ab8fc2b.png">|<img width="420" src="https://user-images.githubusercontent.com/79862886/232039318-ec80f6f1-f1ee-4b7e-a83a-f4744ec05f55.png">|

**Comment by elizaan36** [comment]
Hi @oaratovskyi Thanks for sharing the tasks in this format, it's really easy to look at them as a system. I think the copy is fine for the Woo home tasks, but definitely look forward to future improvements. 

Out of curiosity, the expired task will disappear from the list when the new one appears?

**Comment by oaratovskyi** [comment]
@elizaan36 you're welcome! I did my best to show it in a convenient way.
Yes, it will! It won't be marked as finished (opposite to `Get the free WooCommerce mobile app` task that is marked). It will just disappear if completed and a new task will arrive when conditions are met.

**Comment by elizaan36** [comment]
> It will just disappear if completed and a new task will arrive when conditions are met.

Thanks, and will if still disappear if it's not actioned on/completed by the user?

**Comment by oaratovskyi** [comment]
> Thanks, and will if still disappear if it's not actioned on/completed by the user?
if completed - yes, it will disappear.

If there is no action from the user after account creation after 14 days - a notice will appear and will change to more critical after 30 days, and will not disappear until the merchant adds their details to resume payouts

After the first payment goes in, the notice will appear and change to more critical until it's 30 days from the first payment or TPV is more than $ 5000. Then the message will remain until the merchant updates their details to resume payouts.

**Comment by elizaan36** [comment]
Nice, thanks for clarifying this. Wanted to make sure merchants won't have more than 1 task at a time.
