### ISSUE TITLE
Split UPE: blocks checkout focus shifts on gateway selection

### ISSUE THREAD

**Issue by frosso** [Automattic/woocommerce-payments#5557]
### Describe the bug

When a new Split UPE gateway is selected in the blocks checkout, the page's focus is moved to the top of the checkout page, rather than within the gateway's inner content.
Please investigate whether the issue is within the checkout block or is due to the Split UPE.

Shortcode checkout is not affected by this bug.

### To Reproduce

- Create a page with the shortcode checkout
- Ensure you have multiple UPE gateways enabled for checkout
- Add some products to the cart
- Select one of the UPE gateways
- Focus is scrolling the page to the top

![2023-02-14 19 12 03](https://user-images.githubusercontent.com/273592/218917611-5b51462a-883b-4191-8d7b-582b3bf83918.gif)

### Expected behavior

The page should not scroll to the top.

**Comment by zmaglica** [comment]
@frosso is this issue on team Heisenberg's radar? I am triaging the WC Pay backlog, and I am not certain if you are going to handle it.

**Comment by frosso** [comment]
@zmaglica the issue is not planned for our current sprint, but it's something that we'll try to tackle in the next sprint. If other teams want to take a stab at it, it's also fine 👍
