### ISSUE TITLE
Apple Pay and conditionnal shipping method

### ISSUE THREAD

**Issue by MacWarrior** [Automattic/woocommerce-payments#5562]
Hello,

### Describe the bug
When using Apple Pay, conditionnal shipping method based on address isn't listed but is finally selected and payed

### To Reproduce
1. Create a default free shipping method
2. Create a second paid shipping method, based on location / postal code
3. Allow to create an order without an account
4. While disconnected, create a new cart and go to paiement page
5. Use Apple Pay and select an address compatible with second paid shipping method
6. Error 1 : Second shipping method isn't available inside Apple Pay
7. Finish your order with default free shipping method
8. Error 2 : Once order placed, the second shipping method has been selected and the shipping fee have been added to your cart total

### Actual behavior
1. In Apple Pay, conditional shipping method isn't listed, even with a compatible shipping address selected
2. Even with free shipping method selected during Apple Pay, conditional shipping method is selected and fee have been added to cart total

### Screenshots
- Shipping methods configurations : 
![shipping_conditions](https://user-images.githubusercontent.com/200590/219072897-efef77eb-f7f9-49a7-a35f-b792291e3deb.JPG)
- Apple Pay interface, address selected is compatible with second shipping method ; cart total is 19.90€ with free shipping method : 
![apple_pay-payment](https://user-images.githubusercontent.com/200590/219074547-7dbf8d73-369e-46c1-86dd-288d8c8718dd.jpg)
- In shipping method selection, with a compatible shipping address selected, only default shipping method available (free)
![image](https://user-images.githubusercontent.com/200590/219074962-a54ae65f-c530-42c7-98ef-4569ea52bceb.png)
- Once order has been placed, shipping method has switched to second conditional method and fees has ben added to total order (which differ from Apple Pay previous interface) : 
![payment_successfull](https://user-images.githubusercontent.com/200590/219075531-d845813b-970e-4c3b-8ba2-2ad87402c630.jpg)

### Expected behavior
1. In Apple Pay, conditionnal shipping method are listed when a compatible shipping address is selected
2. With Apple Pay, selected shipping method should be respected

### Smartphone (please complete the following information):
* Device: iPhone 14 Pro Max, iPhone 11 Pro Max, iPhone 11
* OS: iOS 16.3.1
* Browser: Safari (iOS 16.3.1), Brave (1.47)

### Additional context
- Wordpress : 6.1.1-fr_FR (Latest update)
- Woocommerce : 7.4.0 (Latest update)
- Woocommerce payment : 5.4.0 (Latest update)
- Stuart WooCommerce Official Plugin : 1.0.2 (https://github.com/StuartApp/stuart-woocommerce-plugin)
=> Conditionnal shipping method based on address, limited to specific postal codes

I'm a PHP developer, ask me anything technical, I'll do whatever I can !
Thanks by advance !
Best regards,
MacWarrior.

**Comment by htdat** [comment]
Hey @MacWarrior, thank you for so much for reporting this issue. We're trying to verify this issue and will update this later.

> Stuart WooCommerce Official Plugin : 1.0.2 (https://github.com/StuartApp/stuart-woocommerce-plugin)
> => Conditionnal shipping method based on address, limited to specific postal codes

Based on your description, I think that we do not need this plugin to replicate the issue. Instead, using a default flat rate shipping for the same shipping zone is enough. That would be nice to test this case. Our main purpose is to narrow down the possible cause of the issue.

**Comment by MacWarrior** [comment]
> Hey @MacWarrior, thank you for so much for reporting this issue. We're trying to verify this issue and will update this later.
> 
> > Stuart WooCommerce Official Plugin : 1.0.2 (https://github.com/StuartApp/stuart-woocommerce-plugin)
> > => Conditionnal shipping method based on address, limited to specific postal codes
> 
> Based on your description, I think that we do not need this plugin to replicate the issue. Instead, using a default flat rate shipping for the same shipping zone is enough. That would be nice to test this case. Our main purpose is to narrow down the possible cause of the issue.

Hello @htdat,
Thanks for reply, I'll try this case asap and make a return

Best regards,
MacWarrior.

**Comment by MacWarrior** [comment]
Hello @htdat, 

Issue NOT confirmed with default flat rate
How didn't I tested it before... Issue seems 100% related with custom shipping method (Stuart)

To confirm : 
- Conditional shipping method is listed correctly
- Shipping method don't change after payment

Best regards,
MacWarrior.

**Comment by htdat** [comment]
Thanks for your test and updating us @MacWarrior. You're welcome to open other issues in the future.
