### ISSUE TITLE
Update our GH workflows that are required to pass on PRs to also run on the Merge Queue

### ISSUE THREAD

**Issue by mattallan** [Automattic/woocommerce-payments#5572]
### Description

Yesterday we enabled the new GH Merge Queue feature for this repository (internal p2: paJDYF-7aL-p2), however after going through a test run, I noticed the queue was waiting for our required checks to complete but these checks weren't ever running.

![image](https://user-images.githubusercontent.com/2275145/219544329-567d4733-43f5-4677-95ad-79ece012b807.png)

Based on these [GH docs](https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/configuring-pull-request-merges/managing-a-merge-queue#triggering-merge-group-checks-with-github-actions), in order to get our workflows to run on the merge queue, we'll have to update each workflow run on `pull_requests` to also run on `merge_group`.

I believe this should just be as simple as updating the `on:` in our workflows to include `merge_group` i.e.

```
name: PHP linting and tests

on:
  pull_request:
  merge_group:
```

### Workflows to update

- [ ] `js-lint-test.yml`
- [ ] `php-lint-test.yml`

**Comment by RadoslavGeorgiev** [comment]
Tagging @Automattic/harmony as a part of the backlog prioritization call, in accordance to Pc2DNy-3z-p2
