### ISSUE TITLE
WooPay express button doesn't show on the product page when WooCommerce Bookings is activated 

### ISSUE THREAD

**Issue by hsingyuc** [Automattic/woocommerce-payments#5573]
### Describe the bug
After enabling WooPay and WooCommerce Bookings, and if the booking does not require admin approval/confirmation.  The WooPay express button is shown on the cart and checkout page but not on the product page.

Just looking at it, the book now button comes with the bookings extension, and it overwrites the WooPay button.

### To Reproduce
1. Install and activate `WooCommerce Bookings`
2. Go to `Products` and [set up a bookable product](https://woocommerce.com/document/booking-settings/)
3. Enable WooPay
4. Go to the shop, and select the bookable product
5. See, there is no WooPay express button

### Actual behavior
The wooPay button doesn't show.

### Expected behavior
Under the product page, we should see the WooPay express button.

**Comment by zmaglica** [comment]
@frosso is this issue on Heisenberg's radar? I am triaging the WCPay backlog, and I am not certain if you are going to handle it.

**Comment by brettshumaker** [comment]
Looks to be an issue with the hook used to add the button to the single product page. By default, we're using the `woocommerce_after_add_to_cart_quantity` hook but the Bookings plugin overrides this part of the single product template and that hook isn't present.

@hsingyuc did you test to see if you could get the Apple Pay or Google Pay buttons to show up on booking pages? I don't see where wcpay would be adding those buttons to bookings pages either, but I'm not currently set up to test those payment request buttons.

**Comment by hsingyuc** [comment]
>the Bookings plugin overrides this part of the single product template and that hook isn't present.

Yeah, I believe that's what happened.

>did you test to see if you could get the Apple Pay or Google Pay buttons to show up on booking pages?

I tested the Google Pay button together with the WooPay express button but not Apple Pay.  The Google Pay button also didn't show up.

**Comment by csmcneill** [comment]
Related issue: #4444

More details: pdjVC1-12Q-p2

**Comment by pierorocca** [comment]
Hey all should this be an open bug since this is part of the Pay for Order flow compatibility work? Perhaps update this from a bug to an enhancement or link it to a Pay for Order Epic?

**Comment by hsingyuc** [comment]
I'm closing this issue because the issue has been addressed.
