### ISSUE TITLE
Cloning site in Pressable creates new Stripe Express account, skipping onboarding

### ISSUE THREAD

**Issue by aheckler** [Automattic/woocommerce-payments#5582]
### Describe the bug

If I host my WC Pay site on Pressable and clone it (as shown in the image below), a new site is created for me. Oddly, WC Pay skips all the onboarding and simply creates a new Stripe Express account without any input from me.

<img width="546" alt="Screenshot taken on 2023-02-20 at 09 15 18 UTC@2x" src="https://user-images.githubusercontent.com/5512652/220063549-f6389575-daa8-4733-8881-1f1443c4763a.png">

### To Reproduce

1. Create a WP + WC site on Pressable.
2. Install WC Pay and sign up for a real live account.
3. Once that's up and running, clone the site in Pressable as shown above.

### Actual behavior

Result: you'll get a cloned site in Pressable, and upon logging into it, you'll see that you're connected to a brand new Stripe account ID despite not having gone through any onboarding.

### Expected behavior

I expected the cloned site to be in Safe Mode:

https://woocommerce.com/document/woocommerce-payments/testing-and-troubleshooting/safe-mode/

... since it's designed precisely to help avoid the "cloned site" scenario. I did NOT expected a new account to be created for me without any action on my part.

Slack thread: p1675441838806199-slack-CGGCLBN58

cc @jrodger

**Comment by htdat** [comment]
I seem not able to replicate the issue. Follow-up in the same Slack thread: p1676901877876229/1675441838.806199-slack-CGGCLBN58

**Comment by htdat** [comment]
> Follow-up in the same Slack thread: p1676901877876229/1675441838.806199-slack-CGGCLBN58

Closed this issue per the mention here.
