### ISSUE TITLE
Undismissable Notice

### ISSUE THREAD

**Issue by WillBrubaker** [Automattic/woocommerce-payments#5587]
### Describe the bug

We've got various reports of admin notices showing up that can't be dismissed (dismiss button has no effect)

5948453-zen

Which was being prompted to update WooCommerce Payments, but they were at the most recent version already
![sRkx48.png](https://user-images.githubusercontent.com/2127470/220253850-f94c07be-1534-4a29-90de-754a9aa1cf48.png)
39927407-hc

In the case of 39927407 WooCommerce Payments isn't even in use. Is this actually wc-admin adding these notices? Should an issue be opened there instead?

### To Reproduce
Unclear

### Expected behavior
To be able to dismiss notices or to not have false/incorrect notices to begin with

### Desktop (please complete the following information):

* OS: [e.g. iOS]
* Browser [e.g. chrome, safari]
* Version [e.g. 22]

### Smartphone (please complete the following information):

* Device: [e.g. iPhone6]
* OS: [e.g. iOS8.1]
* Browser [e.g. stock browser, safari]
* Version [e.g. 22]

**Comment by htdat** [comment]
Other mentions about this issue: 
- p8FGBN-1Sa-p2 
- https://wordpress.org/support/topic/action-required-please-update-woocommerce-payments-2/

This is likely a Woo core issue, but anyway, I am trying to debug it.

**Comment by htdat** [comment]
This would be a Woo core (or WCCOM issue). Some details are here: 2f2fa-pb

> In the case of 39927407 WooCommerce Payments isn't even in use. Is this actually wc-admin adding these notices? Should an issue be opened there instead?

Now wc-admin is a part of [Woo core repo](https://github.com/woocommerce/woocommerce/) so I think this issue should start in Woo core. 

And this note is actually pulled from WCCOM based on [my read here](https://github.com/woocommerce/woocommerce/blob/733bcc88cf5e9186b1ae61eb89e30d4eeac74040/plugins/woocommerce/src/Admin/RemoteInboxNotifications/DataSourcePoller.php#L17-L19).

**Comment by htdat** [comment]
@WillBrubaker - since there is an issue on Woo core repo. I am going to close this one.
