### ISSUE TITLE
UPE payment gateway payment doesn't work with the split UPE enabled

### ISSUE THREAD

**Issue by timur27** [Automattic/woocommerce-payments#5593]
When the split UPE is enabled on the merchant site, shoppers see the following error during the shortcode checkout: 

`Invalid payment method. Please input a new card number.`

#### Steps to reproduce
1. On the merchant site, enable the split UPE feature in WCPay Dev Tools
2. Add a product and proceed to the shortcode checkout
3. Try to pay with any of the available UPE payment gateways

#### Actual behavior
![image.png](https://images.zenhubusercontent.com/59de7a6cb0222d5de47b4727/b8f2e146-98f1-4404-9625-30b82cc5e15f)

#### Expected behavior
Users should be successfully redirected to the order summary page or to the third-party to proceed with the payment.

**Comment by timur27** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Heisenberg-63586f2ec60359001310fa6a/issues/Automattic/woocommerce-payments/5593?planning-poker) with Zenhub @FangedParakeet @mdmoore

**Comment by bborman22** [comment]
Just to clarify on the issue, this only happens to a shopper that has a saved credit card and then tries to checkout with a different UPE payment method, which greatly narrows down the impact of this bug.
