### ISSUE TITLE
Settings page express checkouts “Customize” button is misaligned

### ISSUE THREAD

**Issue by hsingyuc** [Automattic/woocommerce-payments#5601]
### Describe the bug
“Customize” button is misaligned for “Express checkouts” section on “Payment > Settings” page.

### To Reproduce
1. Go to WooCommerce -> Settings -> Payments -> Express checkouts
2. See error

### Screenshots

<img width="831" alt="Screen Shot 2023-02-26 at 10 03 26 PM" src="https://user-images.githubusercontent.com/56378160/221489620-8d3be865-aee9-413c-8f73-02515056decf.png">

### Desktop (please complete the following information):

Windows 10 - Browser: Chrome (Version 110.0.5481.104)
macOS 13.1 - Browser: Safari (16.2)

**Comment by htdat** [comment]
Hi @hsingyuc, I guess @Automattic/axiom would own this issue as I understand it's a regression issue from https://github.com/Automattic/woocommerce-payments/pull/5563?

**Comment by hsingyuc** [comment]
Yup, I can push a PR for this one.
