### ISSUE TITLE
Create warning modal for order status change to Cancelled

### ISSUE THREAD

**Issue by aheckler** [Automattic/woocommerce-payments#5603]
Similar to #2814, we should implement a warning modal when merchants attempt to change the order status on a successful WC Pay order to `Cancelled`. (And perhaps other statuses?)

Like with the Refunded status change, a lack of a warning modal here can sometimes lead to painful and expensive consequences for the merchant and/or us. P2 thread pbUcTB-2e0-p2

**Comment by jessy-p** [comment]
@aheckler  Could you confirm if I understand this correctly.

When the customer tries to change the Order Status of the successful order to Cancel, we want to show the same modal as implemented in #4987 
![image](https://user-images.githubusercontent.com/32092402/223023975-d0fd471e-8afb-40e6-b7a8-86537d828a78.png)
- Do we need to have any change at all in the content? (Since the user is trying to change status to "Cancel" not "Refund")
- I also see this [additional request](https://github.com/Automattic/woocommerce-payments/pull/4987#issuecomment-1315831800) for Advanced Options. I assume it will apply to both Cancel and Refund. Shall I create an additional issue to implement that for both after this one?

**Comment by aheckler** [comment]
> Do we need to have any change at all in the content?

Probably, yes. Sorry for not thinking of this before! Maybe something like this?

> Cancel order
> 
> Are you trying to issue a refund for this order? If so, please click **Do nothing** and see our documentation on <a href="#">how to issue refunds</a>. If you want to mark this order as Cancelled <em>without issuing a refund</em>, click <strong>Cancel order</strong>. 

Image:

<img width="650" alt="Screenshot taken on 2023-03-06 at 10 40 25 UTC@2x" src="https://user-images.githubusercontent.com/5512652/223087520-7e509724-2f68-416a-ab59-c04fafa15629.png">

> I also see this https://github.com/Automattic/woocommerce-payments/pull/4987#issuecomment-1315831800 for Advanced Options. I assume it will apply to both Cancel and Refund. Shall I create an additional issue to implement that for both after this one?

I don't think it will apply to the Cancelled modal, since there are only two potential outcomes:

- "Do nothing" / cancel out of the modal (and then refund the order in the correct way)
- Actually mark the order as Cancelled, which does not issue a refund.

The Refunded modal is slightly different in that there are three potential outcomes to account for:

- Do nothing / cancel out of the modal.
- Mark the order as Refunded and issue a refund.
- Mark the order as Refunded ONLY, do NOT issue a refund.

However, [during the dev process](https://github.com/Automattic/woocommerce-payments/issues/2814#issuecomment-1117605244) for that Refunded modal, it was decided to leave the third option/button out. This means it's currently **not possible** for merchants to mark a WC Pay order as Refunded without actually issuing a refund via Stripe.

So I guess my question is: @csmcneill do we get any requests from merchants asking how to mark an order as Refunded without actually issuing a refund? If so, I guess we should consider adding that "Advanced options" section to the Refunded modal. If we don't get any / many of those, maybe it's not needed at all?

**Comment by jessy-p** [comment]
Thanks @aheckler  That is much more clearer now for Cancelled status, and I also see how Advanced Options do not apply here 👍

**Comment by htdat** [comment]
FYI. This issue is also related to changing the order status and the refund process.
https://github.com/Automattic/woocommerce-payments/issues/5671

**Comment by csmcneill** [comment]
> do we get any requests from merchants asking how to mark an order as Refunded without actually issuing a refund?

Thanks for flagging @aheckler! 

If we have to issue a refund on behalf of a merchant and that purchase is associated with an order on their site, then we will ask the merchant to mark the order as refunded. However, outside of that very specific situation, I don't believe we get many merchants with this specific ask.

**Comment by jessy-p** [comment]
@aheckler  What's the link for "how to issue refunds" in the dialog?

**Comment by aheckler** [comment]
`https://woocommerce.com/document/woocommerce-payments/managing-money/#refunds`

**Comment by jessy-p** [comment]
@aheckler  One last question, the description states _"change of status on a **successful** WC Pay Order"_. This modal will be displayed only on WCPay order, I am wondering how to gauge "successful". One way is for this to be based on the order status, another way is to check if the order is eligible for a refund. We can also display it on all WCPay orders since there is no modification happening, it is just a warning. Let me know what you think.

**Comment by aheckler** [comment]
@jessy-p The objective here is to avoid merchants opening an order for which the customer has paid, changing the status to Cancelled, and then thinking that action has refunded the customer (when of course it has not).

So I would think that we could simply use the same criteria we did in #4987 to check whether the order is in a "successful" status or not. Does that work?

I don't think we should implement it for *all* status changes, since presumably it would then show up when it's not really applicable, e.g. for an On Hold order that hasn't been paid for yet.

Does that make sense? Not sure if that's enough to go on for you or not. :/

**Comment by jessy-p** [comment]
We are displaying the Refunded modal whenever the merchant is trying to change status to refunded (irrespective of previous status). Additionally we check whether the order is refundable and whether a non-zero amount is available to refund  before displaying the modal. So based on your comment, I will use the same checks (refundable && non-zero refund amount) before displaying this Cancellation modal too.
