### ISSUE TITLE
Incorrect geolocation for multi-currency

### ISSUE THREAD

**Issue by WillBrubaker** [Automattic/woocommerce-payments#5604]
### Describe the bug
A user in 5984499-zen reports that they turned off multi-currency because 

> I was getting the currency notice that said that my website visitors were in the Netherlands even though we are all in the U.S.

### To Reproduce

This is unclear

### Actual behavior

website visitors identified as being in the Netherlands

### Expected behavior

To be correctly geolocated

### Desktop (please complete the following information):

* OS: [e.g. iOS]
* Browser [e.g. chrome, safari]
* Version [e.g. 22]

### Smartphone (please complete the following information):

* Device: [e.g. iPhone6]
* OS: [e.g. iOS8.1]
* Browser [e.g. stock browser, safari]
* Version [e.g. 22]

### Additional context

There was a mention of Cloudflare here: p1677119965048489-slack-C3NCP7ZJ6 but in the case of this ticket, I don't see that's in use.

**Comment by htdat** [comment]
👋 @WillBrubaker, this issue happened with WCPay Multi-Currency. However, the original cause is from the Woo core `WC_Geolocation`, which is used by WCPay Multi-Currency. 

https://github.com/Automattic/woocommerce-payments/blob/0638affce68d58555f2bd2dd19f266895b54b2ac/includes/multi-currency/Geolocation.php#L82-L83

> There was a mention of Cloudflare here: p1677119965048489-slack-C3NCP7ZJ6 but in the case of this ticket, I don't see that's in use.

I am seeing that in the Woo core, [WC_Geolocation::get_ip_address](https://github.com/woocommerce/woocommerce/blob/733bcc88cf5e9186b1ae61eb89e30d4eeac74040/plugins/woocommerce/includes/class-wc-geolocation.php#L80-L80) has already tried to use the HTTP header `X-Forwarded-For` when it exists (in PHP, it's `$_SERVER['HTTP_X_FORWARDED_FOR']` value). CloudFlare, which acts a proxy, is actually sending the real visitor IP with this HTTP header - [ref in their doc](https://developers.cloudflare.com/fundamentals/get-started/reference/http-request-headers/#x-forwarded-for). 

In case, it does not work, I think we might try to figure out why their sites/hosts are not sending the proper HTTP headers. But anyway, this would fall into the Woo core work, IMO.

**Comment by htdat** [comment]
> But anyway, this would fall into the Woo core work, IMO.

I am closing this issue now, you may create an issue on the Woo core repo instead. Otherwise, feel free to reopen this issue.
