### ISSUE TITLE
With UPE enabled, customers are being charged multiple times for renewal order

### ISSUE THREAD

**Issue by james-allan** [Automattic/woocommerce-payments#5615]
### Describe the bug

On the latest version of WC Payments (5.5 - released last week), subscription customers are being charged multiple times for renewal orders. 

The cause of this was introduced in this PR:

- https://github.com/Automattic/woocommerce-payments/pull/3968

As part of that PR, multiple instances of the payment method classes (eg `CC_Payment_Gateway`) are instantiated in each request. Those payment method classes extend `WC_Payment_Gateway_WCPay` and call that base class constructor. That class hierarchy leads to multiple calls of [`$this->maybe_init_subscriptions()`](https://github.com/automattic/woocommerce-payments/blob/trunk/includes/class-wc-payment-gateway-wcpay.php#L386) which hooks onto the `'woocommerce_scheduled_subscription_payment_' . $this->id` hook each time ([code ref](https://github.com/automattic/woocommerce-payments/blob/5.5.0/includes/compat/subscriptions/trait-wc-payment-gateway-wcpay-subscriptions.php#L138)). 

For as many `'woocommerce_scheduled_subscription_payment_' . $this->id` functions that are hooked on, there are that many charge requests for renewal orders. For example, with legacy UPE this was 2 (CC + UPE). But with UPE SPlit enabled there were like 8 renewal order charges (CC + all the UPE ones). 

### To Reproduce

1. Enable WC Payments 5.5.0
2.Enable UPE.
3. Enable the WC Subscriptions extension.
_3. Optional. Create a subscription product if you don't have one._ 
4. Purchase the subscription.
5. Go to the edit subscription screen and from the actions drop down, process a renewal order. (see screenshot below).
6. Go to your Stripe dashboard and the transaction list. 
7. Note there are 2 or more charges for the same renewal order ID.

<img width="403" alt="Screenshot 2023-02-27 at 1 27 38 pm" src="https://user-images.githubusercontent.com/8490476/221466076-b69e833e-1965-47d7-82cf-4f9b7f045b2c.png">

Admin Process renewal action.

### Actual behavior

For every payment method class that extends the `WC_Payment_Gateway_WCPay` class, there's a `$this->maybe_init_subscriptions()` call and that leads to multiple instances WC Payments hooking onto `woocommerce_scheduled_subscription_payment_`. 

For each one of those functions hooked onto that hook, there's a renewal charge being processed.

### Screenshots

<img width="735" alt="Screenshot 2023-02-27 at 1 25 25 pm" src="https://user-images.githubusercontent.com/8490476/221466005-59b07b44-5b1d-4e87-8a97-39f83301428d.png">

Duplicate charges. 

### Expected behavior

A customer should only be charged once for each renewal order.

**Comment by csmcneill** [comment]
Affected merchants so far:
- 5997330-zen
- 5993042-zen
- 5995326-zen
- 5988005-zen

**Comment by ryanr14** [comment]
5996496-zen

**Comment by rashedripon** [comment]
41069772-hc

**Comment by shevene** [comment]
5992705-zen

**Comment by Mxchael** [comment]
5996940-zen

**Comment by thisissandip** [comment]
41098166-hc

**Comment by thisissandip** [comment]
36540221-hc
41098883-hc

**Comment by thisissandip** [comment]
6000842-zen

**Comment by francoishvz** [comment]
40957388-hc

**Comment by seanbelly** [comment]
5999165-zd-woothemes

**Comment by csmcneill** [comment]
37442085-hc

**Comment by sarbouw** [comment]
6003016-zen

**Comment by shaunkuschel** [comment]
6003901-zen
40296706-hc

**Comment by francoishvz** [comment]
40471767-hc

**Comment by francoishvz** [comment]
41142097-hc

**Comment by c-shultz** [comment]
This has been addressed by https://github.com/Automattic/woocommerce-payments/pull/5625 which released in the 5.5.1 patch.
