### ISSUE TITLE
Build up WCPay live branches: add a new workflow

### ISSUE THREAD

**Issue by htdat** [Automattic/woocommerce-payments#5624]
### Description

We'd like to have an easy way for testing any WCPay branch/PR. 

### Acceptance criteria

* Build up a new GitHub workflow, or integrate one of current GitHub workflows to send built files info from GitHub Actions to betadownload.jetpack.me ([see the same for Woo core](https://github.com/woocommerce/woocommerce/blob/a45f9c4f5544b7a2b4d116baac6800ee0317758a/.github/workflows/pr-build-live-branch.yml#L86)). This is an effort to build zip file: https://github.com/Automattic/woocommerce-payments/pull/5523

Moving two following tasks regarding integrating Jurassic Ninja to a separate meta repo issue: https://github.com/Automattic/woocommerce-payments-meta/issues/92

### Additional context

- pc2DNy-2Dm-p2#comment-4249
- pcShBQ-BZ-p2
- paJDYF-3gj-p2
- pdqwkG-eT-p2
- https://github.com/Automattic/jurassic.ninja/pull/274

**Comment by htdat** [comment]
> send built files info from GitHub Actions to betadownload.jetpack.me ([see the same for Woo core](https://github.com/woocommerce/woocommerce/blob/a45f9c4f5544b7a2b4d116baac6800ee0317758a/.github/workflows/pr-build-live-branch.yml#L86))

Secret `WCPAYBETA_SECRET` was added into this repo. p1678260535731669/1678259021.463009-slack-CBG1CP4EN

**Comment by jbordonado** [comment]
In case that helps:

- Building a zip file already exists: https://github.com/Automattic/woocommerce-payments/blob/develop/.github/workflows/build-zip-and-run-smoke-tests.yml

- Adding a [comment to a PR](https://cli.github.com/manual/gh_pr_comment) was already done somewhere, for reference: https://github.com/Automattic/woocommerce-payments/blob/165e6e2af03d08c81c88a046afbc0b99ca236e6d/.github/workflows/release-pr.yml#L139

**Comment by htdat** [comment]
Awesome, thanks @jbordonado!!!
