### ISSUE TITLE
[GlobalStep] Unable to view "Currency Switcher Widget" block at sidebar on "Appearance > Widgets" page.

### ISSUE THREAD

**Issue by gglobalstep** [Automattic/woocommerce-payments#5641]
### Bug Description:
Unable to view "Currency Switcher Widget" block at sidebar on "Appearance > Widgets" page.

### Environment:
Woocommerce Version: WooCommerce 7.4.0
WooCommerce Payments - 5.6.0 test-1
WordPress version: v6.1.1

PC:
Windows 10,
Chrome(Version 110.0.5481.178)
Firefox(Version 110.0)

### Steps To Reproduce:
1. Create any test site using the JN site.
2. Install and activate all the required plugins.
3. In WP Admin, click on Appearance > Widgets page.
4. Add a new block to the sidebar by clicking the plus icon at the bottom of the existing sidebar widgets.
5. Search Currency Switcher widget and select it. 
6. Observe that, we are unable to view "Currency Switcher Widget" block at sidebar.

### Actual Result:
Unable to view "Currency Switcher Widget" block at sidebar on "Appearance > Widgets" page.

### Expected Result:
"Currency Switcher Widget" block should be displayed properly at sidebar on "Appearance > Widgets" page.

### Screenshot:

![#5641](https://user-images.githubusercontent.com/41110392/221859612-904c4a69-cd31-4be8-8bd6-b93d3d48f7bf.gif)

*Isolating the problem (mark completed items with an [x]):*
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

<details>

`
### WordPress Environment ###

WC Version: 7.4.0
REST API Version: ✔ 7.4.0
WC Blocks Version: ✔ 9.4.3
Action Scheduler Version: ✔ 3.5.4
Log Directory Writable: ✔
WP Version: 6.1.1
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache/2.4.55 (Unix) OpenSSL/1.0.2g
PHP Version: 7.4.33
PHP Post Max Size: 1 GB
PHP Time Limit: 30
PHP Max Input Vars: 5000
cURL Version: 7.47.0
OpenSSL/1.0.2g

SUHOSIN Installed: –
MySQL Version: 5.7.33-0ubuntu0.16.04.1-log
Max Upload Size: 512 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 7.4.0
WC Database Prefix: wp_
Total Database Size: 7.54MB
Database Data Size: 5.33MB
Database Index Size: 2.21MB
wp_woocommerce_sessions: Data: 0.03MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 0.13MB + Index: 0.14MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 0.17MB + Index: 0.20MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 0.14MB + Index: 0.13MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 0.14MB + Index: 0.09MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_options: Data: 3.39MB + Index: 0.09MB + Engine InnoDB
wp_postmeta: Data: 0.41MB + Index: 0.41MB + Engine InnoDB
wp_posts: Data: 0.11MB + Index: 0.06MB + Engine InnoDB
wp_snippets: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.05MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_attributes_lookup: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_download_directories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB

### Post Type Counts ###

attachment: 25
page: 10
post: 2
product: 23
product_variation: 7
revision: 3
shop_coupon: 2
shop_order: 55
shop_order_refund: 7
shop_subscription: 18

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (5) ###

Query Monitor: by John Blackbourn – 3.11.2
Code Snippets: by Code Snippets Pro – 3.2.2
Companion Plugin: by Osk – 1.29
WooCommerce Payments: by Automattic – 5.6.0-test-1
WooCommerce: by Automattic – 7.4.0

### Inactive Plugins (4) ###

Akismet Anti-Spam: by Automattic – 5.0.2
Hello Dolly: by Matt Mullenweg – 1.7.2
WooCommerce Payments Dev Tools: by Automattic –
WooCommerce Subscriptions: by WooCommerce – 4.9.1

### Dropin Plugins (1) ###

db.php: Query Monitor Database Class (Drop-in)

### Settings ###

API Enabled: –
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
subscription (subscription)
variable (variable)
variable subscription (variable-subscription)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –
Enforce Approved Product Download Directories: ✔
Order datastore: WC_Order_Data_Store_CPT

### WC Pages ###

Shop base: #5 - /shop/
Cart: #6 - /cart/
Checkout: #7 - /checkout/
My account: #8 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Storefront
Version: 4.2.0
Author URL: https://woocommerce.com/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Subscriptions ###

WCS_DEBUG: ✔ No
Subscriptions Mode: ✔ Live
Subscriptions Live URL: https://military-plover.jurassic.ninja
Subscriptions-core Library Version: 5.3.1
Subscription Statuses: wc-pending: 1
wc-cancelled: 1
wc-active: 16

WooCommerce Account Connected: ❌ No

### Store Setup ###

Country / State: United States (US) — California

### Subscriptions by Payment Gateway ###

WooCommerce Payments: wc-active: 16
wc-cancelled: 1
wc-pending: 1

### Payment Gateway Support ###

WooCommerce Payments: products
refunds
multiple_subscriptions
subscription_cancellation
subscription_payment_method_change_admin
subscription_payment_method_change_customer
subscription_payment_method_change
subscription_reactivation
subscription_suspension
subscriptions
gateway_scheduled_payments
tokenization
add_payment_method

### Admin ###

Enabled Features: activity-panels
analytics
coupons
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
multichannel-marketing
mobile-app-banner
navigation
new-product-management-experience
onboarding
onboarding-tasks
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: minified-js
product-variation-management
settings

Daily Cron: ✔ Next scheduled: 2023-03-01 06:23:15 +00:00
Options: ✔
Notes: 38
Onboarding: completed

### WooCommerce Payments ###

Version: 5.6.0-test-1
Connected to WPCOM: Yes
Blog ID: 216103860
Account ID: acct_1MgMq8FfHSk08Tzv

### Action Scheduler ###

Canceled: 18
Oldest: 2023-02-28 07:15:06 +0000
Newest: 2023-02-28 11:37:06 +0000

Complete: 437
Oldest: 2023-02-28 06:23:27 +0000
Newest: 2023-02-28 09:30:48 +0000

Failed: 6
Oldest: 2023-02-28 06:43:30 +0000
Newest: 2023-02-28 10:00:21 +0000

Pending: 18
Oldest: 2023-03-01 06:23:27 +0000
Newest: 2023-04-30 09:31:57 +0000

### Status report information ###

Generated at: 2023-02-28 12:51:47 +00:00
`

</details>

**Comment by htdat** [comment]
When following these steps, checking the XHR requests in the browser console, I am seeing the error below. The error happened at this line: 

https://github.com/Automattic/woocommerce-payments/blob/23141d7f5d4a513d3e815366afe8d5542ca57e2e/includes/class-wc-payment-gateway-wcpay.php#L620-L620

Sounds like a regression from https://github.com/Automattic/woocommerce-payments/pull/5423 cc @jessy-p as the author of the PR.

Creds for this test site: p1677583419166969-slack-C011ENB20Q1

---- 

**Fatal error**: Uncaught Error: Call to a member function needs\_payment() on null  
in **/public/wp-content/plugins/woocommerce-payments/includes/class-wc-payment-gateway-wcpay.php** on line **620**

Call stack:

1.  `WC_Payment_Gateway_WCPay::register_scripts()`  
    wp-includes/class-wp-hook.php:308
2.  `WP_Hook::apply_filters()`  
    wp-includes/class-wp-hook.php:332
3.  `WP_Hook::do_action()`  
    wp-includes/plugin.php:517
4.  `do_action()`  
    wp-includes/script-loader.php:2180
5.  `wp_enqueue_scripts()`  
    wp-includes/class-wp-hook.php:308
6.  `WP_Hook::apply_filters()`  
    wp-includes/class-wp-hook.php:332
7.  `WP_Hook::do_action()`  
    wp-includes/plugin.php:517
8.  `do_action()`  
    wp-includes/general-template.php:3043
9.  `wp_head()`  
    wp-includes/rest-api/endpoints/class-wp-rest-widget-types-controller.php:628
10.  `WP_REST_Widget_Types_Controller::render_legacy_widget_preview_iframe()`  
    wp-includes/rest-api/endpoints/class-wp-rest-widget-types-controller.php:600
11.  `WP_REST_Widget_Types_Controller::render()`  
    wp-includes/rest-api/class-wp-rest-server.php:1171
12.  `WP_REST_Server::respond_to_request()`  
    wp-includes/rest-api/class-wp-rest-server.php:1018
13.  `WP_REST_Server::dispatch()`  
    wp-includes/rest-api/class-wp-rest-server.php:442
14.  `WP_REST_Server::serve_request()`  
    wp-includes/rest-api.php:410
15.  `rest_api_loaded()`  
    wp-includes/class-wp-hook.php:308
16.  `WP_Hook::apply_filters()`  
    wp-includes/class-wp-hook.php:332
17.  `WP_Hook::do_action()`  
    wp-includes/plugin.php:565
18.  `do_action_ref_array()`  
    wp-includes/class-wp.php:399
19.  `WP::parse_request()`  
    wp-includes/class-wp.php:780
20.  `WP::main()`  
    wp-includes/functions.php:1332
21.  `wp()`  
    wp-blog-header.php:16
22.  `require()`  
    index.php:17

**Comment by NoticeCorp** [comment]
I have this problem too
