### ISSUE TITLE
Changelog entries problems in readme.txt when using the release workflow

### ISSUE THREAD

**Issue by jbordonado** [Automattic/woocommerce-payments#5647]
### Describe the bug
During the release 5.5.0 and recently 5.5.1, I noticed that the release PR was not completely correct.
Indeed, I could notice duplicated changelog entries in `readme.txt`.

See the latest example with 5.5.1 release: https://github.com/Automattic/woocommerce-payments/commit/5fd8c713d1fbd0e049d45e93a0d4dc8a132575c3

![Screenshot 2023-02-28 at 16 58 46](https://user-images.githubusercontent.com/28830738/221909435-ef51cd75-716b-4a55-9fb6-93ae1a0ba774.png)

Here is where we insert the generated changelog into the `readme.txt` file: https://github.com/Automattic/woocommerce-payments/blob/fce081dc95ba19a6dc5efd45eb3f63d40b30e379/.github/workflows/release-pr.yml#L87-L88

**Comment by jbordonado** [comment]
Just noticed that somehow the changelog inserted in `readme.txt` during the release 5.4.0 is what is causing these issues now: https://github.com/Automattic/woocommerce-payments/pull/5485/commits/2d479e34b1d2fc233583ff8679727852e74e1c83#diff-9e6e4772050998a5c0dc3c61acf3dab0a7e594566171fa5746d6b62f9598efb6

Note the random `== Changelog ==` which should not be here (how?!) l.145: 
```
* Dev - Moved the trash, untrash == Changelog == delete related `add_actions()` in the `WC_Subscriptions_Manager` class to be added on the `woocommerce_loaded` action.
```

The correct entry is:
```
* Dev - Moved the trash, untrash & delete related `add_actions()` in the `WC_Subscriptions_Manager` class to be added on the `woocommerce_loaded` action.
```

There's also one [l.103](https://github.com/Automattic/woocommerce-payments/commit/2d479e34b1d2fc233583ff8679727852e74e1c83#diff-9e6e4772050998a5c0dc3c61acf3dab0a7e594566171fa5746d6b62f9598efb6R103)

In both cases, there was a `&` sign, which got replaced by `== Changelog == .....`

**Comment by shendy-a8c** [comment]
Some key points around changelog and readme when doing 5.6.0 release:

- I observed a bunch of deletion in `readme.txt` but I think it's corrective change to make `readme.txt` in sync with `changelog.txt` ([ref](https://github.com/Automattic/woocommerce-payments/pull/5748#discussion_r1136784158)).

- A text `WCPay\Core` in changelog becomes `WCPayCore` in readme.txt ([ref](https://github.com/Automattic/woocommerce-payments/pull/5748#discussion_r1136785703)).
