### ISSUE TITLE
Add further payment metadata for classification

### ISSUE THREAD

**Issue by dechov** [Automattic/woocommerce-payments#5669]
Add more information to payment metadata, either in a single field or multiple, about how the payment originates: initial vs. renewal, UPE vs. non-UPE, shortcode vs. block, etc.

We already have `payment_type` but its value is "recurring" for all subscription-related payments, not just renewals. (There is also `payment_context` for WCPay subscriptions – see https://github.com/Automattic/woocommerce-payments/issues/3715#issuecomment-1026416644).

**Comment by jessy-p** [comment]
To come up with the list of fields, and after checking with architects, implement it.

**Comment by souravdebnath1986** [comment]
What are the use cases (+customers i.e. merchants, internal) for enhancing the payment meta eg: enhanced reporting.

**Comment by naman03malhotra** [comment]
Moving it back to "RFP" queue to discuss it during the prioritization call.

**Comment by aheckler** [comment]
Can we also add a bit of metadata to indicate the current version of WooPayments on the merchant site? This could be helpful for support during troubleshooting.
