### ISSUE TITLE
Prevent Apple Pay domain registration for Indian merchants

### ISSUE THREAD

**Issue by ricardo** [Automattic/woocommerce-payments#5673]
Context: p1677094614234679-slack-C9976E5MJ

### Description

As Apple Pay is not supported in India, we should stop invoking domain registration requests for Indian merchants. This should be relatively straightforward and should reduce domain registration errors.

### Acceptance criteria

Stop invoking Apple Pay domain registration requests for merchants based in India.

### Dev notes

As @reykjalin suggests [here](p1677873913689259-slack-CGGCLBN58), we can probably check the store address, currency, or perhaps the Stripe account country to prevent these requests.

**Comment by htdat** [comment]
@ricardo and @reykjalin - it seems this specific issue is for https://github.com/woocommerce/woocommerce-gateway-stripe/? 

Indian merchants are not supported in WCPay yet https://woocommerce.com/document/woocommerce-payments/compatibility/countries/#supported-countries

**Comment by ricardo** [comment]
@htdat good catch!

I forgot about the unsupported countries and missed this last message p1677866623089619/1677094614.234679-slack-C9976E5MJ from Stripe. I also created an issue for the Stripe repo: https://github.com/woocommerce/woocommerce-gateway-stripe/issues/2566.

I asked one more question p1678160211523159/1677094614.234679-slack-C9976E5MJ about unsupported countries, and depending on Stripe's response, we can close this issue.

**Comment by htdat** [comment]
@ricardo and @reykjalin - any update on this issue? Thanks.

**Comment by ricardo** [comment]
@htdat We are having a call with Stripe on Wednesday. Will keep this issue updated.

**Comment by ricardo** [comment]
Closing as this issue would be only relevant for Malaysian or Indian merchants.
