### ISSUE TITLE
Duplicate Payments: Open two checkout tabs, and use 3DS cards with non-UPE flow

### ISSUE THREAD

**Issue by htdat** [Automattic/woocommerce-payments#5678]
### Describe the bug

Duplicate payments for a single order happens when shoppers open two checkout tabs, use 3DS cards, and confirm 3DS modals in both tabs in between.

### To Reproduce

- Use non-UPE flow or a saved card in UPE flows (as it eventually routes to non-UPE flow)
- Add one or some products into cart.
- Go to the checkout page (tab 1), and make a payment with a 3DS card - 4000 0027 6000 3184, which always triggers authentication (See more https://woocommerce.com/document/woocommerce-payments/testing-and-troubleshooting/testing/#3ds-test-cards)
- See the modal to confirm the payment in tab 1. **BUT STOP, do not confirm**.
- Open the checkout page on another tab (tab 2), and use the same card for the checkout.
- See the modal to confirm the payment in tab 2, and confirm it. 
- Go to tab 1, confirm the modal. 

### Actual behavior

- Check the latest order, there will be two payments (payment intents) in this order. 
- Confirm this in the Stripe Dashboard too.

### Expected behavior

Only one payment should be processed, the other one should be void. 

### Additional context

See `Order 1564354 - date: 2023-02-07` in this spike with a real merchant site - repo: woocommerce-payments-meta/issues/75#issuecomment-1455511181

**Comment by htdat** [comment]
Note: I am putting this here but I think this would be an issue for Woo core as it's more related to a locking mechanism for a in-progress payment processing order. 

Some ideas to fix it: 

- Avoid two checkout tabs at the same time. Force shoppers to use only one tab. (This is similar to WhatsApp web). 
- Quick solution: tell shoppers to not open another tab, ask them to stay in the checkout process. 
- As mentioned above, create a new locking mechanism or a new status in Woo core. 


I am pretty sure that other payment gateways have the same issue (requires more testings). 
_Update_: it turns out that Stripe gateway does not have this issue.

**Comment by RadoslavGeorgiev** [comment]
One of the reasons this is happening is that even though [we are storing the intent](https://github.com/Automattic/woocommerce-payments/blob/af9da52cc8bc9d15b4757c3d079d821ad8284f61/includes/class-wc-payment-gateway-wcpay.php#L1249-L1267) before redirecting to the confirmation modal, we do not check for the intent __before__ creating a new intent, and allowing the modal to be displayed.

Similarly to how we're [pre-loading the intent for platform checkout](https://github.com/Automattic/woocommerce-payments/blob/af9da52cc8bc9d15b4757c3d079d821ad8284f61/includes/class-wc-payment-gateway-wcpay.php#L1077-L1091), we should load the event from the order, and use it instead of creating a new one.

**Comment by htdat** [comment]
> One of the reasons this is happening is that even though [we are storing the intent](https://github.com/Automattic/woocommerce-payments/blob/af9da52cc8bc9d15b4757c3d079d821ad8284f61/includes/class-wc-payment-gateway-wcpay.php#L1249-L1267) before redirecting to the confirmation modal, we do not check for the intent before creating a new intent, and allowing the modal to be displayed.

This seems a viable option, and that's exactly what WooCommerce Stripe extension is doing, hence there is no issue in this extension.
https://github.com/woocommerce/woocommerce-gateway-stripe/blob/f862adeacf3b2d3c2e1257992111b44830c03c05/includes/class-wc-gateway-stripe.php#L417-L421

**Comment by htdat** [comment]
Per this discussion https://github.com/Automattic/woocommerce-payments/pull/7146#pullrequestreview-1679680896, we're going to move this issue to the later stage of RPP project, and add label `status: blocked`.

For PR #7146, we're going to close it. (I've moved 1SP from this issue to the PR to account for our effort in this sprint regarding all discussions we've made).

**Comment by htdat** [comment]
Closing. Context p1697617874925669/1697598833.905349-slack-C05997J5PCG
