### ISSUE TITLE
Adjust merchant-facing wording from "payouts" to "deposits" 

### ISSUE THREAD

**Issue by aheckler** [Automattic/woocommerce-payments#5689]
There are still a couple places where we refer to "payouts" when our preferred language (at least for user/merchant-facing text) is "deposits".

Example:

![image](https://user-images.githubusercontent.com/5512652/223679074-0c09bad3-2ff1-4b3d-a30b-ce3b98df3b7e.png)

We should search the codebase for `payout` / `payouts` and change those anywhere where a user/merchant could see them. So far I have found some in:

- `client/connect-account-page/strings.js`
- `client/settings/deposits/index.js`

**Comment by htdat** [comment]
According to Pc2DNy-3z-p2, this falls in Helix product area. Tagging @haszari (Helix team lead) as a part of Gamma Porter duties PcreKM-yM-p2.

**Comment by aheckler** [comment]
I searched around some more, but think the two files I pointed out about above might be the only ones that use `payout` in a merchant-facing string.

**Comment by haszari** [comment]
We can tidy this up as part of the current deposits project. FYI @shendy-a8c

**Comment by shendy-a8c** [comment]
@aheckler when working on this issue, I found other place that mentions "payouts", on the Payments page when store has not been connected to a WCPay account.

There are screenshots in the PR https://github.com/Automattic/woocommerce-payments/pull/5792.
