### ISSUE TITLE
Simplify deposits UI - Add notice on deposit card about business day delay

### ISSUE THREAD

**Issue by james-allan** [Automattic/woocommerce-payments#5697]
### Description

This issue is part of the larger Epic to add the Payments Overview Deposits card (https://github.com/Automattic/woocommerce-payments/issues/5686).

The next deposit delay may need change due to country as per the stripe docs on [payout speed by country](https://stripe.com/docs/payouts#standard-payout-timing).

As part of this issue, the card should be altered to include the following acceptance criteria: 

### Acceptance criteria 

* A notice added below the next [deposit table](https://github.com/Automattic/woocommerce-payments/issues/5696) to notify the user about potential deposit delays. 

<img width="1492" alt="Screenshot 2023-03-09 at 5 23 45 pm" src="https://user-images.githubusercontent.com/8490476/223949945-5289789f-273a-4fb3-acda-f0fad1b5e152.png">

### Designs

P2: paJDYF-7fi-p2

![image](https://user-images.githubusercontent.com/8490476/223936763-804af22f-2f9d-41f3-98e9-0017b0cf4d43.png)

### Additional context

Project: pdjTHR-2i5-p2

**Comment by haszari** [comment]
@elizaan36 does this notice (and the other similar ones) have a click out to docs via the icon? Should they have an explicit `Learn more` link as well?

**Comment by elizaan36** [comment]
hey @haszari The icons don't have any click/hover interaction and the notices won't have any learn more links. This is to reduce visual noise on the page and keep the focus on the data. Since the tooltips with Learn more links are available on the same screen (just in a different section), I think this will be sufficient in terms of education.

**Comment by james-allan** [comment]
### 28 March 2023 Update

The design for this notice has now changed. It is now placed in the deposit history table. 

<img width="664.3" alt="Screenshot 2023-03-28 at 1 07 31 pm" src="https://user-images.githubusercontent.com/8490476/228117479-07fbf515-933d-4c29-9084-1e9e54ea88f8.png">

> **Note**
> The design above also includes a change in the notice language. This is out of scope of this issue. 

There are also conditions that this notice should be shown under. 

The notice should be displayed for deposit states pending, and in-transit only. As soon as a final state is reached i.e. paid , failed or cancelled, the notice should go away.
