### ISSUE TITLE
Implement modals when changing order status for authorized orders

### ISSUE THREAD

**Issue by aheckler** [Automattic/woocommerce-payments#5712]
Similar to #5603 and #2814, we should consider implementing modal warnings when merchants change the status of authorized (but uncaptured) orders. Examples:

- Changing the status of an authed order to Cancelled should offer to cancel the authorization.
- Changing the status of an authed order to Completed should offer to capture the funds.

Potential copy for status change to Cancelled:

> **Cancel authorization**
> 
> This order has been [authorized but not captured](https://woocommerce.com/document/woocommerce-payments/settings-guide/authorize-and-capture/#authorize-vs-capture) yet. Changing the status to Cancelled will also [cancel the authorization](https://woocommerce.com/document/woocommerce-payments/settings-guide/authorize-and-capture/#cancelling-authorizations). Do you want to continue?
> 
> [ Do nothing ]     [ Cancel order and authorization ] 

Potential copy for status change to Completed:

> **Capture payment**
> 
> This order has been [authorized but not captured](https://woocommerce.com/document/woocommerce-payments/settings-guide/authorize-and-capture/#authorize-vs-capture) yet. Changing the status to Completed will also [capture the payment](https://woocommerce.com/document/woocommerce-payments/settings-guide/authorize-and-capture/#capturing-authorized-orders). Do you want to continue?
> 
> [ Do nothing ]     [ Complete order and capture payment ] 

EDIT: This idea stems from this post: paJDYF-7eg-p2

**Comment by htdat** [comment]
> Changing the status of an authed order to Completed should offer to capture the funds.

FYI. This part would fix this issue too https://github.com/Automattic/woocommerce-payments/issues/5671

**Comment by paulostp** [comment]
For reference, initially reported by 6000094-zd-woothemes.

**Comment by kalessil** [comment]
More details/desions log: pdjVC1-1vj-p2

**Comment by dmvrtx** [comment]
@aheckler , #5605 is a slightly different approach to the issue. Do you think the confirmation modal is a preferred way to go, or it is possible to cancel such authorisations automatically?

**Comment by csmcneill** [comment]
@dmvrtx Adam is away through April, so I'll chime in on his behalf :) 

I think that the confirmation modal is the way to go here, as it aligns more closely with the fix for https://github.com/Automattic/woocommerce-payments/issues/2814

**Comment by dmvrtx** [comment]
@elizaan36 , is it okay to re-use the modal that appears then cancelling an order (see below), but with the copy suggested by Adam for #7743?

![afbeelding](https://github.com/Automattic/woocommerce-payments/assets/683297/0108c30c-834f-4c94-aa52-b1ebaa11fb05)

**Comment by elizaan36** [comment]
yes, definitely. Makes perfect sense.

**Comment by dmvrtx** [comment]
Modal for transition to the "Cancelled" status has been implemented in #7743

**Comment by naman03malhotra** [comment]
@zmaglica can you please route it to pulsar, as it is related to order flow.

**Comment by zmaglica** [comment]
This issue impacts Transactions, so assigning to Pulsar (based on team responsibilities Pc2DNy-3z-p2) @kalessil .
Assigning as part of Gamma Triage process PcreKM-yM-p2.

**Comment by kalessil** [comment]
Closing as https://github.com/Automattic/woocommerce-payments/pull/8169 has been merged.
