### ISSUE TITLE
Simplify deposits UI - Add greeting header panel to balances card

### ISSUE THREAD

**Issue by james-allan** [Automattic/woocommerce-payments#5721]
### Description

This issue is part of the larger Epic to add the Payments Overview Deposits card (https://github.com/Automattic/woocommerce-payments/issues/5581).

As part of this issue, the card should altered to include the following acceptance criteria:

### Acceptance criteria 

- Greeting. 
    - "Good afternoon, {user-first-name} 👋".
    - "Good morning, {user-first-name} 👋".
- Woo Payments graphic.

![224232319-3dd3bb14-b0c8-469f-8fdc-8557fcc82199](https://user-images.githubusercontent.com/8490476/224234487-236b0aba-aa0e-4c08-a66c-88e192785fd8.png)

### Designs

P2: paJDYF-7fi-p2

![image](https://user-images.githubusercontent.com/8490476/224232319-3dd3bb14-b0c8-469f-8fdc-8557fcc82199.png)

### Additional context

Project: pdjTHR-2i5-p2

**Comment by Jinksi** [comment]
If the user's "First Name" does not exist, should the name for the greeting ever fallback to the profile's nickname or username?

<img width="584" alt="image" src="https://user-images.githubusercontent.com/3147296/225152665-80969d31-c070-4cde-85b9-02ac4871e2a6.png">
