### ISSUE TITLE
Simplify deposits UI - Add funds to balances card to include funds breakdown

### ISSUE THREAD

**Issue by james-allan** [Automattic/woocommerce-payments#5723]
### Description

This issue is part of the larger Epic to add the Payments Overview Deposits card (https://github.com/Automattic/woocommerce-payments/issues/5581).

As part of this issue, the card should altered to include the following acceptance criteria:

### Acceptance criteria 

- **Available balance** ⇒ **Available funds**
- **Pending balance** ⇒ **Pending funds**
- ❗ Removed from this issue's scope as it is not accessible. ~~**Reserve funds.** We don't currently display reserve funds in the UI. We need to confirm this reserve fund figure is included in the account balances (the balance array we already have access to) or accessible via a different API.~~
- ❗ **Note** The tooltips aren't within this issue scope. They will be added via https://github.com/Automattic/woocommerce-payments/issues/5724. 
- Add the loading state. See screenshot below.

![224232319-3dd3bb14-b0c8-469f-8fdc-8557fcc82199](https://user-images.githubusercontent.com/8490476/224241444-254c2628-62e9-4a92-a2ee-d3833df40103.png)

<img width="705" alt="Screenshot 2023-03-14 at 10 42 23 am" src="https://user-images.githubusercontent.com/8490476/224863234-10b5a304-e27f-4b67-92c8-f74c0235c2d1.png">

### Designs

P2: paJDYF-7fi-p2

![image](https://user-images.githubusercontent.com/8490476/224232319-3dd3bb14-b0c8-469f-8fdc-8557fcc82199.png)

### Additional context

Project: pdjTHR-2i5-p2

**Comment by Jinksi** [comment]
@james-allan, do you think it would help if we add data fetching to the AccountBalances foundation PR #5755?

I realise I will probably need it for #5721 as well, to fetch the accountholder's name.
