### ISSUE TITLE
Simplify deposits UI - EPIC - Deposits UX relating to store lifecycle

### ISSUE THREAD

**Issue by james-allan** [Automattic/woocommerce-payments#5726]
### Description

The goal of this project is to give merchants confidence about where there money is, how they get paid, and when their money will be available and deposited into their account.

We will achieve this by implementing an improved design for deposits related information in the payments overview screen (alongside appropriate) documentation.

As part of this epic we will improve the UX to include details and helpful links about the newly onboarded merchant holding period, negative balances handling, and capital loan implications. 

### Acceptance criteria

- [x] #5727
- [x] #5728
- [x] #5730
- [ ] Automattic/woocommerce-payments-server/issues/2869

### Designs

P2: paJDYF-7fi-p2

<img width="830" alt="Screenshot 2023-03-10 at 5 24 50 pm" src="https://user-images.githubusercontent.com/8490476/224250611-ab1acc47-a1f9-417c-ac6a-dbf87a848e97.png">

### Additional context

Project: pdjTHR-2i5-p2

**Comment by Jinksi** [comment]
Closing this since the remaining issue in the to-do list will be handled as maintenance.
