### ISSUE TITLE
Simplify deposits UI - Add notice to next deposit card indicating new account waiting period

### ISSUE THREAD

**Issue by james-allan** [Automattic/woocommerce-payments#5727]
### Description

This issue is part of the larger Epic to add details about notices to the deposits card indicating status and caveats (https://github.com/Automattic/woocommerce-payments/issues/5726).

### Acceptance criteria 

* A notice added to the next deposit section when an account is in the new account waiting period stating:
    - "Your first deposit is held for seven business days. Why?"
    - 🔗 https://woocommerce.com/document/woocommerce-payments/deposits/deposit-schedule/#section-1

### Designs

P2: paJDYF-7fi-p2

<img width="830" alt="Screenshot 2023-03-10 at 5 24 50 pm" src="https://user-images.githubusercontent.com/8490476/224250611-ab1acc47-a1f9-417c-ac6a-dbf87a848e97.png">

### Additional context

Project: pdjTHR-2i5-p2

**Comment by Jinksi** [comment]
We should keep links to public docs in a central location within the codebase to assist in updating them in the future.
