### ISSUE TITLE
Simplify deposits UI - Add notice to next deposit card indicating capital loan funds

### ISSUE THREAD

**Issue by james-allan** [Automattic/woocommerce-payments#5728]
### Description

This issue is part of the larger Epic to add details about notices to the deposits card indicating status and caveats (https://github.com/Automattic/woocommerce-payments/issues/5726).

### Acceptance criteria 

* A notice added to the next deposit section when the next deposit includes a capital loan funds:
    - "This deposit will include funds from your WooCommerce Capital loan. Learn more"
    - 🔗 https://woocommerce.com/document/woocommerce-payments/stripe-capital/overview/

<img width="1196" alt="Screenshot 2023-03-10 at 6 12 20 pm" src="https://user-images.githubusercontent.com/8490476/224260690-50836f2a-6a68-48d4-bd53-7f398acf5eeb.png">

### Designs

P2: paJDYF-7fi-p2

### Additional context

Project: pdjTHR-2i5-p2
WCPay-server issue to add a property that indicates an estimated deposit includes loan disbursement transaction in the `deposits/overview-all` endpoint: 3182-gh-Automattic/woocommerce-payments-server.

**Comment by Jinksi** [comment]
We should keep links to public docs in a central location within the codebase to assist in updating them in the future.

**Comment by Jinksi** [comment]
I have created a server issue to add a property that indicates an estimated deposit includes loan disbursement transaction in the `deposits/overview-all` endpoint here: 3182-gh-Automattic/woocommerce-payments-server.
