### ISSUE TITLE
Simplify deposits UI - Add notice to next deposit card indicating negative balance

### ISSUE THREAD

**Issue by james-allan** [Automattic/woocommerce-payments#5730]
### Description

This issue is part of the larger Epic to add details about notices to the deposits card indicating status and caveats (https://github.com/Automattic/woocommerce-payments/issues/5726).

### Acceptance criteria 

* A notice added to the next deposit section when an account has a negative balance stating:
    - "Deposits may be interrupted while your WooCommerce Payments balance remains negative. Why?"
    - 🔗 https://woocommerce.com/document/woocommerce-payments/fees-and-debits/account-showing-negative-balance/

<img width="926" alt="Screenshot 2023-03-10 at 6 05 27 pm" src="https://user-images.githubusercontent.com/8490476/224259354-ba3d72a0-de62-4d23-a09c-532233d23890.png">

### Designs

P2: paJDYF-7fi-p2

### Additional context

Project: pdjTHR-2i5-p2

**Comment by Jinksi** [comment]
We should keep links to public docs in a central location within the codebase to assist in updating them in the future.

**Comment by haszari** [comment]
I'm working on consistently using `CardBody` before starting this, so we don't have to add card padding to all our child elements, notices etc.

- #5954
