### ISSUE TITLE
Remove feature flag and old UI code for simplify deposits UI

### ISSUE THREAD

**Issue by shendy-a8c** [Automattic/woocommerce-payments#5749]
### Describe the bug

This issue is a reminder to remove the feature flag implemented here https://github.com/Automattic/woocommerce-payments/issues/5690, maybe when the feature is ready to go live 100%.
The feature flag might have been used in various places.
Make sure to remove them safely.
Remove old UI code.
Add a changelog.

### Additional context

Project: pdjTHR-2i5-p2

**Comment by Jinksi** [comment]
Do you think that removing code for the current DepositsInformation component will be part of this project?

**Comment by shendy-a8c** [comment]
Per p1681321629766639-slack-C045PC0V40G, we'll go with https://github.com/Automattic/woocommerce-payments/issues/6016 before working on this issue.

**Comment by shendy-a8c** [comment]
In https://github.com/Automattic/woocommerce-payments/pull/6004, I copied the instant deposit button component from the old UI for new UI because there is slight design change.

Part of this issue's work is to remove one of the instant deposit button component, ie:
- Move `deposits/instant-deposits/button-and-modal.js` to `deposits/instant-deposits/index.js`.
- Fix unit tests.
- Fix import in `client/components/account-balances/balances-tab-panel.tsx`.
