### ISSUE TITLE
Simplify deposits UI - Show & update the next deposit on selected currency change

### ISSUE THREAD

**Issue by james-allan** [Automattic/woocommerce-payments#5753]
Blocked until #5700 is merged.

### Description

This issue is part of the larger Epic to add support for multiple currencies in the new deposit and balances UI (https://github.com/Automattic/woocommerce-payments/issues/5750).

This issue will change the next deposit section of the deposits card to reflect changing the chosen currency on the **Payments → Overview** admin screen.

Note that we should consider if persisting the selected currency state when navigating away is appropriate.

### Acceptance criteria 

- Selecting a currency in the tab navigation should:
   - update the next deposit table to include information about the next deposit for the given currency.

### Designs

p2: paJDYF-7fi-p2

https://user-images.githubusercontent.com/8490476/224611306-583f8073-95fb-4efd-8df4-e37a4308f816.mov

### Additional context

Project: pdjTHR-2i5-p2

**Comment by Jinksi** [comment]
Should we consider persisting the selected currency state when navigating away from the overview screen?

I've added this consideration to the issue description.
