### ISSUE TITLE
Simplify deposits UI - EPIC - Tracking & health metrics

### ISSUE THREAD

**Issue by haszari** [Automattic/woocommerce-payments#5771]
As part of this project, we need to add tracks events throughout the existing and new UI so we can understand usage, and how merchants interact with deposits. 

In general, for all deposit-related UI, we need to ensure there are tracks events for:

- View the page containing the UI.
- All interactions available in the UI (e.g buttons, links). 

This covers all deposit UI, for example:

- Payments overview screen => balances card, deposits card [new!]
- Payments settings screen => deposit settings
- Payments deposits list 

With these tracks events in place we should be able to answer questions such as…

- How many merchants view payments overview screen per month?
  - What % of those merchants view `Pending` help tooltip in balances card?
     - What % of those merchants click through to documentation?
- How many merchants view payments settings screen per month?
  - What % of those merchants change their deposit schedule?

Note: The questions and UI mentioned above are examples and is not a complete list. When someone starts work on this the first step would be to review the UI & audit what events we need (and what existing events we can use).

Events can be implemented as part of work on new UI (e.g. add `balance_card_currency_selector_click` in #5750 ), or as a separate follow up task after UI is merged.

### Acceptance criteria

- [x] Ability to measure view and user interaction with deposits UI on Payments > Overview page
    - [x] #5880
    - [x] #5881
- [x] #5882
- [x] #5884
- [x] #5885

**Comment by haszari** [comment]
There is an existing `wcadmin_page_view` event with `path` parameter which we could use for `payments_overview_view`, `payments_settings_view` etc. We'll need to confirm this event fires consistently when we need it, and what the relevant `path` values are. 

Alternatively we can add our own custom `view` events if that works better.

**Comment by vbelolapotkov** [comment]
@haszari this epic seems to be completed. Closing, but feel free to reopen if still needed.
