### ISSUE TITLE
Simplify deposits UI - Insert the reserve funds figure to the balances card

### ISSUE THREAD

**Issue by james-allan** [Automattic/woocommerce-payments#5774]
> **Warning**
> 🛑 Blocked by Automattic/woocommerce-payments-server/issues/3105

### Description

This issue **was** originally part of the larger Epic to add the Payments Overview Deposits card (https://github.com/Automattic/woocommerce-payments/issues/5581)

Given this issue is blocked by API access, it was removed from project scope for now. Once reserve funds become available, we'll add it back into the balance block. 

### Acceptance criteria 

- **Reserve funds.** Inject the reserved funds amount into the balances card.
    - **Note:** We don't currently display reserve funds in the UI and the figure is only accessible via new APIs once Automattic/woocommerce-payments-server/issues/3105 is resolved. 
- Adding the tooltip. Copy: "The amount of funds being held in reserve. Learn more."
   - Learn more 🔗 https://woocommerce.com/document/woocommerce-payments/our-policies/reserves/

<img width="1935" alt="Screenshot 2023-03-15 at 11 24 27 am" src="https://user-images.githubusercontent.com/8490476/225183959-30819790-b5ad-452e-bf3a-446742ed7c94.png">

### Designs

P2: paJDYF-7fi-p2

![image](https://user-images.githubusercontent.com/8490476/224232319-3dd3bb14-b0c8-469f-8fdc-8557fcc82199.png)

### Additional context

Project: pdjTHR-2i5-p2

**Comment by brucealdridge** [comment]
Closing as duplicate #2730
