### ISSUE TITLE
Simplify deposits UI - Documentation

### ISSUE THREAD

**Issue by shendy-a8c** [Automattic/woocommerce-payments#5775]
If there is documentation that shows and explains the Payments > Overview page, that needs to be updated.

For example:
- https://woocommerce.com/document/woocommerce-payments/deposits/instant-deposits/#request-an-instant-deposit
- https://woocommerce.com/document/woocommerce-payments/deposits/change-deposit-account-info/

Note: Users with older client will keep seeing the old UI.

**Comment by james-allan** [comment]
These two docs have been updated. I understand Adam has done these updates. Closing.
