### ISSUE TITLE
Avoid multiple orders for a single payment in the UPE flow

### ISSUE THREAD

**Issue by htdat** [Automattic/woocommerce-payments#5786]
### Describe the bug

As a result of this spike 30c9c-pb/#plain, we'd like to ensure this:

- Before updating payment intent, we might check its current `metadata['order_id]` and verify its current value is the same with the current processing order_id in the gateway. Otherwise, just send a failure signal back to the front-end.

### To Reproduce

Copied from the meta link above.

1. Add this snippet into your site, which is to delay saving session data into DB. 
```php
// Delay saving session data during PHP shutdown. 
add_action(
	'shutdown',
	function() {
		if ( 'checkout' === ( $_GET['wc-ajax'] ?? null  ) ){
			sleep(10);
		}
	},
	19 // Just before priority 20 at https://github.com/woocommerce/woocommerce/blob/bec3ec18ac801875a830ddf097ba173069161c13/plugins/woocommerce/includes/class-wc-session-handler.php#L74
);
``` 
2. Use UPE, add a product, go to the checkout page.
3. Click on `Use a new payment method`, to see the input fields. (This triggers creating a new PaymentIntent and caching its ID into WC_Session)
4. Fill out this card `4000 0027 6000 3184` (that requires 3DS), but DO NOT SUBMIT. 
5. Open a new tab (tab 2), also go to the checkout page.
6. Click on `Use a new payment method`, and also fill out the 3DS card `3184`.
7. Go back to tab 1, submit with the "Place order" button
8. Wait for 4-5 seconds. This will ensure that [the intention is updated](https://github.com/Automattic/woocommerce-payments/blob/4ec527e374f2b72fc8f86b4a3fed43b2428e0193/includes/payment-methods/class-upe-payment-gateway.php#L464-L464) with this order_id. 
9. Go to tab 2, submit with the "Place order" button.
10. Close tab 2, after 4-5 seconds, which also ensures that the intention is update with another order_id.
11. Go back to tab 1, finish 3DS.  
12. Wait for a bit, check wp-admin/edit.php?post_type=shop_order. 
13. Expectation: See two new paid/processing orders with the same payment intent. 

### Expected behavior

Prevent two paid orders for the same payment intent.

### Acceptance criteria

- Prevent this issue happening.
- Check both legacy and split UPE flows.
- Consider the trade-off as mentioned by @dechov - pbUcTB-1PE-p2#comment-6110

> Checking for an existing order ID in intent metadata makes sense to me, but that’s if we can do it at a point when we’re already having to retrieve the intent – do we do that (prior to confirmation)?
> 
> I’m not sure we could justify the performance hit of an extra intent retrieval request just for this purpose, and we don’t store the intent ID on our server – at least not in a way that we could relate it to the order ID. Perhaps we could check for an existing order with that payment ID on the plugin side, though I imagine this could be a performance issue for large stores as well since even with HPOS I’d be surprised if there was an index on the column where transaction IDs are stored (though I’m not certain on that).

### TODOs before and after the merge 

- [ ] Gather data for MFF, see more in meta issue 50.

**Comment by naman03malhotra** [comment]
Estimated dev complete date: 24th May 2023
Estimated shipping date: 26th May 2023

**Comment by htdat** [comment]
@naman03malhotra - Due to my 3 AFK days this week (May 22-26), the planning dates change as the following: 

Estimated dev complete date: 30th May 2023
Estimated shipping date: 1st June 2023. 

--- 

Relevant update: with the split-UPE, it seems inconsistent to produce this error, so it's harder to find out the proper way to fix it.

**Comment by naman03malhotra** [comment]
Hey @htdat 👋, just checking in if we have a draft PR for this issue?

**Comment by htdat** [comment]
@naman03malhotra - 🤦 Not yet. It's really not what I want but I will see and may adjust the ETA again. 
This was my last Friday stand-up update for this issue:

> After multiple tries to replicate the issue again, and think about the trade-off, I am seeing if that’s possible to change the approach to make it more reasonable.
> -- Ref p1685709256465799-slack-C01BPL3ALGP

**Comment by naman03malhotra** [comment]
Dat is not happy with the current approach - Link to be added by @htdat 
Dat is looking alternate approach to solve this atm.

8th Jun Thursday - Dev ready

**Comment by naman03malhotra** [comment]
@htdat are we planning to release this with 6.1?

**Comment by htdat** [comment]
@naman03malhotra - sorry for the late response. I would delay it until the next version 6.2. I've found out that this bug https://github.com/Automattic/woocommerce-payments/issues/6575 will cause issues for setup intents in a specific case (check out a subscription product with fre trial).

**Comment by naman03malhotra** [comment]
Blocked by #6575

**Comment by naman03malhotra** [comment]
As discussed with @htdat, he will [change the approach](https://github.com/Automattic/woocommerce-payments/issues/6575#issuecomment-1614194510) to fix only payment intent and not setup intent.
