### ISSUE TITLE
Gracefully handle admin JS not being built

### ISSUE THREAD

**Issue by jrodger** [Automattic/woocommerce-payments#58]
Not a problem for end users, but as a developer, if you forget to build the JavaScript used in the admin dashboard you get a load of PHP errors.

Are there any existing conventions for prompting the developer to run a build?

**Comment by vbelolapotkov** [comment]
I think it's been fixed with dev npm scripts. So closing it for now, but please feel free to reopen if doesn't agree.

**Comment by jrodger** [comment]
I was thinking it would be nice to implement something like this notice in WooCommerce ([src](https://github.com/woocommerce/woocommerce/blob/ef015f740f89c35cebf34bc0c39a971be6723b68/plugins/woocommerce/includes/class-woocommerce.php#L935)).

For the cases where you clone the WCPay repository but don't run the appropriate npm script before opening your site.
