### ISSUE TITLE
Fatal error when editing a page that contains the Checkout block

### ISSUE THREAD

**Issue by a-danae** [Automattic/woocommerce-payments#5806]
### Describe the bug

With Blocks 9.7.0 or newer active, a fatal error is triggered when editing a page that contains the Checkout block.

WooPay specific code that should only run in the frontend is running in the editor, it tries to reach to a null class. [https://github.com/Automattic/woocommerce-payments/blob/0ff92e035d380d5a34f96d83d595eeb9d9d0cee7/includes/class-wc-payment-gateway-wcpay.php#L6[…]76](https://github.com/Automattic/woocommerce-payments/blob/0ff92e035d380d5a34f96d83d595eeb9d9d0cee7/includes/class-wc-payment-gateway-wcpay.php#L675-L676)

### To Reproduce

1. Install and activate Blocks 9.7.0 or newer
2. Edit a page where you have the checkout block (or add this block a page)
3. Notice there's a fatal error
```
PHP Fatal error:  Uncaught Error: Call to a member function is_empty() on null in /var/www/html/wp-content/plugins/woocommerce-payments/includes/class-wc-payment-gateway-wcpay.php:675
```

### Actual behavior
There's a fatal error when editing a page with the checkout block.

### Expected behavior
No error must show up when editing a page with the checkout block.

### Additional context

Reported by @senadir in p1679032024339949-slack-C022WMN88KG

**Comment by RadoslavGeorgiev** [comment]
https://github.com/Automattic/woocommerce-payments/pull/5809 should have closed this issue while being merged, but it seems like GitHub requires a dot after `Fixes #1234`. Closing it manually...
