### ISSUE TITLE
Inconsistency in transaction data

### ISSUE THREAD

**Issue by WillBrubaker** [Automattic/woocommerce-payments#5840]
### Describe the bug
Sharing what was reported in 6039045-zen

> when a "stripe credit card" payment comes in WooCommerce Payments, it shows up in the stripe app, so the rest of the payments should show up in other payment gateways eg: Gpay, Apple Pay, Credit Card & etc.

### To Reproduce
1. Be a WCPay user
2. (maybe?) Your WCPay Stripe express account is linked to your regular Stripe account
3. Use the Stripe app
4. Notice that WCPay CC payments show up in the app, Express checkouts/local payment methods do not

### Actual behavior

when a "stripe credit card" payment comes in WooCommerce Payments, it shows up in the stripe app

### Expected behavior

The rest of the payments should show up in other payment gateways eg: Gpay, Apple Pay, Credit Card & etc.

### Desktop (please complete the following information):

* OS: [e.g. iOS]
* Browser [e.g. chrome, safari]
* Version [e.g. 22]

### Smartphone (please complete the following information):

* Device: [e.g. iPhone6]
* OS: [e.g. iOS8.1]
* Browser [e.g. stock browser, safari]
* Version [e.g. 22]

**Comment by jessy-p** [comment]
We are not supporting Stripe app. Ref:  p1680594915195499-slack-C03EE4CPPK5
