### ISSUE TITLE
Refactor WC_Payments_Accounts_API

### ISSUE THREAD

**Issue by oaratovskyi** [Automattic/woocommerce-payments#5856]
### Description
There was a discussion in https://github.com/Automattic/woocommerce-payments/pull/5779#discussion_r1139022019 that the file is pretty big and adding new code to this becomes harder with time flow. 
Would be good to consider refactoring it into multiple smaller classes as suggested in the discussion.

It requires a P2 discussion prior to taking this. We should agree on how to structure new classes.

### Additional context
GH discussion: https://github.com/Automattic/woocommerce-payments/pull/5779#discussion_r1139022019

**Comment by RadoslavGeorgiev** [comment]
Good news @oaratovskyi! We extracted the first request classes from the API client during the first phase of WCPay as a Platform, and now phase two is in action. There is an issue under active development regarding this in the meta repo (issue 87, can't link it here).

Expect those APIs to exist as proper separate classes in a few weeks. I'll close this issue for now, as it seems to be a duplicate. If I got something wrong, please reopen it and ping me.

**Comment by oaratovskyi** [comment]
Thanks, @RadoslavGeorgiev ! Sounds very good to me 🙌
