### ISSUE TITLE
Prepare a payment process refactor suggestion

### ISSUE THREAD

**Issue by RadoslavGeorgiev** [Automattic/woocommerce-payments#5870]
Being handled in #5836 

The purpose of this issue is to track efforts for the attempt to understand everything, related to the PHP payment process, and spike how it could be refactored for less repetition, better readability.

Details will be added after a discussion with the architects team soon.

**Comment by RadoslavGeorgiev** [comment]
P2 is published, this issue can be assumed closed. paJDYF-7WD-p2

**Comment by naman03malhotra** [comment]
@RadoslavGeorgiev it would be nice to link the P2 post for future context.

**Comment by RadoslavGeorgiev** [comment]
@naman03malhotra shortlink added.
