### ISSUE TITLE
Ability to measure view and user interaction with the Deposits card on Payments > Overview page

### ISSUE THREAD

**Issue by shendy-a8c** [Automattic/woocommerce-payments#5881]
We need to be able to:
- Count how many times user view the card. We might be able to use Payments > Overview page view ([read](https://github.com/Automattic/woocommerce-payments/issues/5771#issuecomment-1468699248)).

- Count user's clicks on the recent history deposits.

![image](https://user-images.githubusercontent.com/8490476/223962434-3ed9e52d-f945-48f9-ae97-bfcf2e5a05cc.png)

- Count user's clicks on the "View full deposit history" button and "Change deposit schedule" link.

![image](https://user-images.githubusercontent.com/8490476/224227312-963ef96c-b13e-49f8-b909-072f61bae07f.png)

**Comment by haszari** [comment]
Here's my proposal for tracks events relating to this card. Not all are essential or urgent. I've bolded the ones I think need implementing right now, keen for feedback on which to prioritise, or if we should do all 😁 

- View card
    - **`wcadmin_page_view path=payments_overview`**
- Interactions
    - Card actions
        - **`wcadmin_wcpay_overview_deposits_view_history_click`**
        - **`wcadmin_wcpay_overview_deposits_change_schedule_click`**
    - Recent deposits table
        - `wcadmin_wcpay_overview_deposits_view_detail_click`
    - Notices
        - `wcadmin_wcpay_overview_deposits_suspended_notice_view`
            - `wcadmin_wcpay_overview_deposits_suspended_notice_docs_click`
        - `wcadmin_wcpay_overview_deposits_negative_balance_notice_view`
            - `wcadmin_wcpay_overview_deposits_negative_balance_notice_docs_click`
        - `wcadmin_wcpay_overview_deposits_new_account_notice_view`
            - `wcadmin_wcpay_overview_deposits_new_account_notice_docs_click`
        - `wcadmin_wcpay_overview_deposits_capital_loan_notice_view`
            - `wcadmin_wcpay_overview_deposits_capital_loan_notice_docs_click`

**Comment by shendy-a8c** [comment]
@haszari Are notices clickable? I don't think so.

**Comment by haszari** [comment]
> Are notices clickable? I don't think so.

Some have help links, which we might be curious to track clicks on (`*_notice_docs_click`). Also the fact that they are displayed at all could be interesting (`*_notice_view`).

However I agree these are low-priority interactions.

**Comment by haszari** [comment]
This issue is closed now that the basic events are merged in #6188 . 

I will check with @souravdebnath1986  and other stakeholders and open new issues if we need to add more events (e.g. notices).
