### ISSUE TITLE
Ability to measure view and user interaction with deposits list page

### ISSUE THREAD

**Issue by shendy-a8c** [Automattic/woocommerce-payments#5884]
We need to be able to:

- Count how many times user view the deposits list page. Make sure to take account pagination as well.

- Count user's interaction with the filter.

- Count user's click on the Download button.

- Count user's click on the column header to sort the table by.

- Count user's interaction with the column columns show / hide UI from the three dots button at the top right of the table.

<img width="1587" alt="Screenshot 2023-03-28 at 20 21 54" src="https://user-images.githubusercontent.com/73803630/228250443-ceeff9d8-8a88-4eb5-8ee3-1577c44e4195.png">

**Comment by haszari** [comment]
We have an existing view event: `wcadmin_page_view path: payments_deposits`

![Screenshot 2023-05-02 at 3 03 11 PM](https://user-images.githubusercontent.com/4167300/235571023-f2e199e3-e50e-4718-8dca-20d7ea7859f1.png)

**Comment by haszari** [comment]
Here's a proposal for all the events we could track, and the most useful events (IMO) in bold.

#### Page view

- Existing **`wcadmin_page_view path=payments_deposits`**

#### Filters / header

- `wcpay_deposits_enable_advanced_filter`
- **~~`wcpay_deposits_download_csv_click`~~** we already have `wcadmin_wcpay_deposits_download `
- `wcpay_deposits_table_options_click`
    - `wcpay_deposits_table_options_bank_column_toggle enable=bool`

#### Table

- **`wcpay_deposits_row_click`**
- `wcpay_deposits_date_order_toggle`

#### Footer

- `wcpay_deposits_table_next_page_click`
- `wcpay_deposits_table_prev_page_click`
- `wcpay_deposits_table_go_to_page page_number=int`
- `wcpay_deposits_table_rows_per_page_click rows=int`
