### ISSUE TITLE
Simplify deposits UI - Update critical flows and add release specific testing instructions

### ISSUE THREAD

**Issue by shendy-a8c** [Automattic/woocommerce-payments#5886]
Once we go [100% with the Simplify Deposits UI](https://github.com/Automattic/woocommerce-payments/issues/5749), we need to:

- Update critical flows 
    - Maybe add or update https://github.com/Automattic/woocommerce-payments/wiki/Critical-flows, and
    - Make sure to also update detailed critical flow testing instructions at https://github.com/Automattic/woocommerce-payments/wiki/Testing-instructions-for-critical-flows.
- Add to release specific testing instructions https://github.com/Automattic/woocommerce-payments/wiki/Release-testing-instructions.

**Comment by haszari** [comment]
@shendy-a8c @james-allan I'm assuming this is completed – closing (so we can claim the velocity in Sprint 4). Please reopen and comment if this still needs work!
