### ISSUE TITLE
Add Explat experiment to the new onboarding flow

### ISSUE THREAD

**Issue by daquinons** [Automattic/woocommerce-payments#5928]
### Description
As part of the new Progressive Onboarding project, we are implementing a new onboarding flow for every user, even those not eligible to use Progressive Onboarding.

We want to set up an Explat experiment to help us when releasing it.

The experiment will define two alternatives:
- Current onboarding flow (95%)
- New flow (5%)
- Duration: 90 days
- Location: US
- Primary metric: `wcadmin_wcpay_stripe_connected`
- More success metrics and guardrail metrics?
    - `wc_web_admin_product_publish`
    - `wc_web_admin_settings_payment_page_view`

There should be another experiment in the future that will increase New flow from 5% to 20% and duration from 90 to 180 days.

### Acceptance criteria
- Create and own the whole Explat experiment, adding the necessary code in our codebase
- Make sure the experiment is set up in a way that in case we interrupt the experiment, the only accessible flow will be the old one.
- Remove the different feature flags to make sure the experiment can run without any issue

### Extra
You can use this past experiment as guidance pbxNRc-1So-p2

**Comment by brandonwanA8C** [comment]
Inputs on testing goals & measurements:

Goals:
* ensure the functionalities are per specs (onboarding success full and PO, data retention, forking logic)
* ensure E2E UX is acceptable & per standard
* measure conversion rate compared to existing UX

Metrics:
* have "20%" (or per a/b testing standard) of users go through new UX
* measure the conversion count & rate for Full onboarding (KYC complete) and PO onboarding (Payment acceptance) 
* measure where the churns occur (flow, page, CTA)

Ideal success:
* conversion rate is equal to or higher than existing plug-in
* have analytics on where the most churns occur

**Comment by daquinons** [comment]
According to this discussion paJDYF-74y-p2#comment-18058 we'll be adding the first experiment with 5% target of US merchants and 90 days duration

**Comment by oaratovskyi** [comment]
Created experiment draft bxNRc-p2 and asked for review p1685016711821949-slack-C03KTTK2YMA

**Comment by oaratovskyi** [comment]
Published experiment in pbxNRc-2Cz-p2

**Comment by oaratovskyi** [comment]
PR is ready, works locally, asked for an experiment review in Slack p1685375673808949-slack-C7HH3V5AS
