### ISSUE TITLE
Prefill Stripe KYC follow-up issue (first and last name, phone for company)

### ISSUE THREAD

**Issue by oaratovskyi** [Automattic/woocommerce-payments#5929]
### Description
This is a follow-up issue from #5476.
The next fields are not prefilled yet for full KYC if you pick Company under business type
- first name & last name. Stripe responded us how it can be done p1680110407617769/1680091022.120479-slack-C9976E5MJ. Need to take a look and evaluate if it worth the effort.
- business phone for companies. I've tried it during #5476, it requires server tweaks and didn't work even after tweaking it, needs one more try. it can be sent as `support_phone` under `business_profile`.

### Additional context
p1680090653208359-slack-C03KTTK2YMA

**Comment by oaratovskyi** [comment]
Also we need to consider changing the approach of forming an array on PHP side of the client to the server one https://github.com/Automattic/woocommerce-payments/pull/5857#pullrequestreview-1366554338

**Comment by dmallory42** [comment]
Noting that I asked Strpe for access to the video they shared on how to do this and will share it here once they provide it. (p1681830162411009/1680091022.120479-slack-C9976E5MJ)

**Comment by dmallory42** [comment]
Upping the estimate because I think the proper way to do this (adding a representation of the Stripe API concept of a `Person` to the server) will take a little longer to get right.
