### ISSUE TITLE
Card fields disabled in UPE if disabled prior to 5.4.0

### ISSUE THREAD

**Issue by csmcneill** [Automattic/woocommerce-payments#5944]
### Describe the bug
In 41869298-hc, card fields were not displayed. After logging into the site, we determined that this is because the Debit / Credit card fields were disabled. They could also not be re-enabled due to #5296

Disabling and re-enabling UPE resolved the issue. 

### To Reproduce
I haven't tried to reproduce this yet, but discussion in p1679517467750309-slack-CU6SYV31A leads us to believe the following steps will reproduce the result:

1. Install and activate an older version of WCPay (5.3.0 or older).
2. Enable UPE.
3. Disable the Debit / Credit card option.
4. Update to 5.6.2+
5. The Debit / Credit card option cannot be enabled.
6. Disable and re-enable UPE, and the Debit / Credit card option will be reset.

**Comment by csmcneill** [comment]
6172493-zen

**Comment by FangedParakeet** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Heisenberg-63586f2ec60359001310fa6a/issues/Automattic/woocommerce-payments/5944?planning-poker) with Zenhub @mdmoore @timur27

**Comment by csmcneill** [comment]
6433643-zen

**Comment by csmcneill** [comment]
It seems like this might be a duplicate of https://github.com/Automattic/woocommerce-payments/issues/5525

@zmaglica When you have the chance, since you worked on https://github.com/Automattic/woocommerce-payments/pull/6504, could you see if this is a duplicate issue and can be closed?

**Comment by csmcneill** [comment]
Just noting here that I've informed the users associated with this issue about #5525 being fixed in 6.1.0. They've probably also resolved this themselves by disabling and re-enabling UPE, but this may require a bit more testing and/or discussion before closing.

**Comment by csmcneill** [comment]
With UPE being the standard, merchants cannot resolve this issue by disabling and re-enabling UPE. However, we haven't had any other reports of this issue. As a result, I'm going to close this issue, and we can re-open it if needed.
