### ISSUE TITLE
If card payments are disabled in 5.6.x+, Apple Pay and Google Pay fail

### ISSUE THREAD

**Issue by csmcneill** [Automattic/woocommerce-payments#5945]
### Describe the bug

If we follow the steps outlined in https://github.com/Automattic/woocommerce-payments/issues/5944 to disable the card payment option, Apple Pay and Google Pay payments fail with the following order note:

> A payment of $xx.xx failed to complete with the following message: `Intentions require at least one payment method`.

### To Reproduce

1. Install and activate an older version of WCPay (5.3.0 or older).
2. Enable UPE.
3. Disable the Debit / Credit card option.
4. Update to 5.6.2+
5. The Debit / Credit card option cannot be enabled.
6. Attempt to make a purchase via Google Pay or Apple Pay.
7. The order fails; check the order notes.
8. Disable and re-enable UPE, and the Debit / Credit card option will be reset.
9. Retry step 6.
10. The order will be successful.

### Actual behavior

In older versions of WCPay, merchants could disable card payments and still process payments via Google Pay and Apple Pay. This may be a side effect of the split UPE project.

### Screenshots

![Markup on 2023-04-02 at 14:59:23](https://user-images.githubusercontent.com/82999806/229376471-2c3611fa-b474-4099-9821-e87778e66411.png)

### Expected behavior

Apple Pay and Google Pay payments will not fail if a customer did not enable card payments in an older version of WCPay.

### Workaround

The CSS outlined [here](https://github.com/Automattic/woocommerce-payments/issues/3969#issuecomment-1128129498) might work for some merchants.

### Additional context

6077298-zen

**Comment by pierorocca** [comment]
@csmcneill do you know the history why that model of disabling card payments, but still allowing Apple Pay and G Pay card based payments, to be processed existed?

**Comment by csmcneill** [comment]
Thanks for asking @pierorocca! https://github.com/Automattic/woocommerce-payments/issues/3969 is the most commented open issue on this repo currently, and a part of that is probably due to the proliferation of folks who want to disable card payments via WCPay but still use WCPay to offer LPMs and/or EPMs.

I asked 6077298-zen and their response was pretty personal. I will add it to the FSOR.

**Comment by RadoslavGeorgiev** [comment]
Tagging @Automattic/fusion as a part of the backlog prioritization, in accordance with Pc2DNy-3z-p2. 

Side note: I believe this error message is not in the context of the specific payment method used, rather in the context of the [allowed payment method types](https://github.com/Automattic/woocommerce-payments/blob/f6aa0034528e56ac52b6e40a623c2ba6a0524849/includes/class-wc-payment-gateway-wcpay.php#L1068-L1074). Those were [loaded slightly differently](https://github.com/Automattic/woocommerce-payments/blame/efc897ac8ae7b6867415e298ce6385d62c23ead6/includes/class-wc-payment-gateway-wcpay.php#L1049-L1054) as a part of split-UPE, so I'm tagging @Automattic/heisenberg as well.

**Comment by senff** [comment]
Reported in 10560714-HC

**Comment by dsmithweb-a8c** [comment]
5889857-zen

**Comment by FangedParakeet** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Heisenberg-63586f2ec60359001310fa6a/issues/Automattic/woocommerce-payments/5945?planning-poker) with Zenhub @mdmoore @timur27

**Comment by anu-rock** [comment]
@FangedParakeet I was going through our backlog, so wanted to confirm if @Automattic/heisenberg will be working on this issue?

**Comment by FangedParakeet** [comment]
@anu-rock, AFAICT this isn't strictly a UPE issue, as I believe the CC method cannot be disabled for some time prior to our arrival. However, resolving this issue is still in our roadmap, though we would not expect to reach it before the beginning of the next sprint (sprint 8/May 29), due to the higher priority of other present tasks.

**Comment by anu-rock** [comment]
@FangedParakeet All right 🙌  Let me know if you need inputs from @Automattic/fusion at any point.

**Comment by senff** [comment]
6493650-zen

**Comment by pierorocca** [comment]
@anu-rock if there's extra bandwidth to take this on in ME and since it's not a UPE specific issue, I'd recommend taking this on in your backlog so that it's resolved sooner than later.

**Comment by anu-rock** [comment]
@pierorocca Thanks for the ping. We'll try and prioritize this in our next sprint (starting Jul 19).

**Comment by dsmithweb-a8c** [comment]
6374826-zen
