### ISSUE TITLE
Saved Payment Methods retain old address details, which can fail ZIP checks

### ISSUE THREAD

**Issue by csmcneill** [Automattic/woocommerce-payments#5951]
### Describe the bug

If a customer saves a payment method to their account, the ZIP code provided when that payment method is saved is seemingly tied to that saved payment method. 

If a customer...
- Proceeds through checkout using a saved payment method but adds a different ZIP/postal code.
- Updates their address for subscription products via **My Account > Addresses** flow.

...the updated address information, including ZIP/postal code is not sent to Stripe. As a result, if a customer moves and tries to use a previously saved Payment Method, this will block the payment due to ZIP Check errors.

### To Reproduce

1. Make a purchase and save the payment method. Note the ZIP/postal code used at checkout.
2. Check the Stripe dashboard for this payment.
3. Make another purchase using a different address, but use the saved payment method. 
4. Check the Stripe dashboard and note that the payment made in step 3 uses the same ZIP/postal code in step 1.
5. Install/activate [WooCommerce Subscriptions](https://woocommerce.com/products/woocommerce-subscriptions/?aff=10486&cid=1131038) and create a subscription product (if one doesn't already exist).
6. Purchase a subscription product using the saved payment method from step 1. Note the ZIP/postal code used at checkout.
7. Check the Stripe dashboard for the parent order. If using the saved payment method from step 1, the order in the Stripe dashboard will not have the updated billing address information.
8. Navigate to **My Account > Addresses** and change the billing address for the account.
9. Check `Update the Billing Address used for all future renewals of my active subscriptions (optional)` and save the settings.
10. Trigger a renewal for the subscription purchased in step 5 via scheduled actions or the early renewal flow.
11. Check the Stripe dashboard and note that the renewal order from step 9 uses the same ZIP/postal code in step 1.

### Actual behavior
If a customer moves and changes the address information at their bank, their orders will fail if the customer:
- tries to use a saved payment method for a new purchase.
- has an active subscription.

### Expected behavior
There should be an easy and accessible way for a customer to update the address associated with saved payment methods.

### Workaround
The customer can go through the checkout flow, add a new card, and save that as a payment method. They can delete the old saved payment method at **My Account > Payment Methods**, and if they have active subscriptions, they can make this new payment method the default.

**However**, this is a clunky and haphazard workaround. If a customer uses this workaround and adds the same card to their account with the correct address details, there is no way for them to know which of the cards on file is associated with the correct address.

### Additional context
See p1672937255481699-slack-CGGCLBN58 and p1680539873882779-slack-C03EE4CPPK5 for some initial digging and discussion.

Assigning `priority: high` because this has been an issue for some time and has a history of affecting HVMs.

**Comment by RadoslavGeorgiev** [comment]
Some further context: When creating a payment (intent), we are not providing a billing address. It's instead provided through either the customer or payment method objects, required for the payment:

- The payment method gets initially created on the checkout page (right before submitting the form) through JS, and then updated in PHP. As a part of the completed checkout optimizations project, this update happens asynchronously immediately after the payment: https://github.com/Automattic/woocommerce-payments/blob/f6aa0034528e56ac52b6e40a623c2ba6a0524849/includes/class-wc-payment-gateway-wcpay.php#L998-L1008. This means that the payment likely uses the not yet updated saved PM.
- The customer object is updated before the payment, but I believe the data from the payment method supersedes it, as the update happens synchronously, and would have been reflected in the payment.

**Comment by FangedParakeet** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Heisenberg-63586f2ec60359001310fa6a/issues/Automattic/woocommerce-payments/5951?planning-poker) with Zenhub @gpressutto5

**Comment by gpressutto5** [comment]
@RadoslavGeorgiev Do you think updating the saved payment method **synchronously** like we do for the customer in `manage_customer_details_for_order` would be a proper solution?

**Comment by RadoslavGeorgiev** [comment]
Hey @gpressutto5, updating (and storing in general) payment method details synchronously would solve all of our issues, but one: performance. Checkout is relatively slow, which is why this call is being scheduled for later.

The ideal solution here would be to update the payment method on the server, to avoid the client <-> server round-trip.

I know this is not a satisfactory answer to your question, but it's the reason the issue has been open for a while now.

**Comment by gpressutto5** [comment]
Reintroduced by #8689.
Check Slack thread before attempting to fix this again.
p1713894851258879/1713828072.672819-slack-C06V1EKSTC7
