### ISSUE TITLE
Epic: Add v1 filters to transaction list

### ISSUE THREAD

**Issue by luizreis** [Automattic/woocommerce-payments#596]
As part of the v1 reduced filter scope (paJDYF-qh-p2), the transaction list should be able to be filtered by the **Transaction date**, **Transaction type**, **Customer name**, and **Customer email**. 

- [x] Add transaction date and type filters to transaction list #615 
- [ ] Add customer name and email filters to transaction list #616

![image](https://user-images.githubusercontent.com/7714042/79470308-a0299f80-7fd7-11ea-9acc-12c0a7b5e13c.png)

**Comment by vbelolapotkov** [comment]
Closing this one since only #616 is left
