### ISSUE TITLE
"Restricted Soon" account status can be displayed without any call to action or additional information.

### ISSUE THREAD

**Issue by melek** [Automattic/woocommerce-payments#5966]
### Describe the bug
There appear to be circumstances where the account is going to be reviewed by Stripe and shows 'Restricted Soon', but the merchant has no way to know when they will be restricted or what to do next in either their WooCommerce dashboard nor the Stripe Express dashboard.

Presumably, Stripe will reach out the merchant in some cases like this when required, but this is an anxious situation for a business owner who wants to ensure continuity in payment operations, and often results in a support request.

### Actual behavior
'Restricted soon' can be displayed in the WooCommerce Payments dashboard without any qualifying information in the WooCommerce Payment nor Stripe Express account areas.

### Expected behavior
A 'Restricted soon' notice should always be accompanied with a timeline or call to action, even if the action is to wait.

### Additional context
This might be considered an enhancement request, but I'm starting with a bug report since this feels like missing functionality, not a nice-to-have.

p1680632713348389/1680632644.340149-slack-C3NCP7ZJ6

**Comment by jessy-p** [comment]
We do have logic to display additional information when the status is Restricted, so we should investigate and find the gaps in the logic.

**Comment by daquinons** [comment]
Additional conversation p1690517173244919-slack-C03KTTK2YMA
