### ISSUE TITLE
Typo: Capital loans displayed on the Transactions table with type "Loan Dispersement"

### ISSUE THREAD

**Issue by mattallan** [Automattic/woocommerce-payments#5979]
### Describe the bug

![image](https://user-images.githubusercontent.com/2275145/229966100-d873de1b-2f1f-4e3a-bc86-c34bc7fbc4db.png)

While testing Capital Loans I noticed a typo on the transactions table for how we display the "type" of capital loans. "Loan Dispersement" is not a valid word and instead the type should be "Loan Disbursement".

To fix this up we'll just need to update the `clients/transactions/strings/ts` file:

https://github.com/Automattic/woocommerce-payments/blob/e047d8be37217b545df29d82bd18330362e86360/client/transactions/strings.ts#L22

### To Reproduce

1. Create a capital loan on your account
   1. Visit https://dashboard.stripe.com/test/connect/capital
   2. Click on the `+ Create` button and create a loan with your account ID and with status "Delivered"
   3. Once created you should receive an email to accept the loan
   4. After accepting the loan, go back into Stripe https://dashboard.stripe.com/test/connect/capital and find your capital loan, then approve and disburse the funds:![image](https://user-images.githubusercontent.com/2275145/229968256-17128b48-f014-40d7-b1cd-e5f206da0c9b.png)
2. Now go back to your WP Admin > Payments > Transactions
3. See the new transaction with type "Loan Dispersement"

### Expected behavior

This is a typo and should be "Loan Disbursement"

### Desktop (please complete the following information):

* OS: [e.g. iOS]
* Browser [e.g. chrome, safari]
* Version [e.g. 22]

### Smartphone (please complete the following information):

* Device: [e.g. iPhone6]
* OS: [e.g. iOS8.1]
* Browser [e.g. stock browser, safari]
* Version [e.g. 22]

**Comment by haszari** [comment]
Removing `projects` and adding to backlog. Should be an easy fix!

**Comment by haszari** [comment]
Marking as high for embarrassment factor. Our UI should use the correct terms / spelling to inspire trust in the platform.
