### ISSUE TITLE
Add ability to bulk accept disputes

### ISSUE THREAD

**Issue by aheckler** [Automattic/woocommerce-payments#5982]
This issue stems from the WC Pay audit call on disputes: paJDYF-7sM-p2.

Large merchants may potentially be handling many active disputes at the same time. There may be some use cases where they want to bulk accept them. That is not possible currently, however, since merchants mush handle disputes one by one.

We should consider adding the ability for merchants to use checkboxes on the **Payments > Disputes** page to select a subset of disputes, which they can then accept all at once with a button.

cc @elizaan36 from a design POV.

**Comment by elizaan36** [comment]
@aheckler Sorry I missed this one earlier. We don't currently have the ability to select multiple in the WooCommerce table component but we'll keep in mind for future iterations. cc @souravdebnath1986

**Comment by haszari** [comment]
> We don't currently have the ability to select multiple in the WooCommerce table component

Just flagging this as an important gap that we should advocate for or help fix in core. Multi-select is pretty fundamental (and very familiar/expected for classic wp-admin users). 

FYI @beaulebens / @wcstaley – as I understand it this is not urgent for disputes as such; I'm assuming that most merchants need to deal with disputes individually, and don't accumulate large numbers of disputes. However thought it was worth raising the need about multi-select & bulk operations in wcadmin table view.

**Comment by beaulebens** [comment]
> FYI @beaulebens / @wcstaley – as I understand it this is not urgent for disputes as such; I'm assuming that most merchants need to deal with disputes individually, and don't accumulate large numbers of disputes. However thought it was worth raising the need about multi-select & bulk operations in wcadmin table view.

Multiple selection as a general feature of list tables is definitely being explored as part of the work happening in Gutenberg to standardize/introduce a new universal table design. We have folks from our design team involved there as well. Internal ref: puPv3-gpp-p2 and Gutenberg project: https://github.com/WordPress/gutenberg/issues/53233

Exactly how we leverage it in our own contexts will be up to us, but the basic functionality of selecting multiple rows looks like it'll be an established pattern that we can use.

**Comment by haszari** [comment]
Thanks for the pointers @beaulebens – watching those now so can see progress 🗂️✅🚀

**Comment by shendy-a8c** [comment]
Closing this as part of our triage process as this is not actionable by @Automattic/helix right now because blocked by a work from other team (https://github.com/Automattic/woocommerce-payments/issues/5982#issuecomment-1726035773).

We understand that this is a desired feature, so +cc-ing 
product @souravdebnath1986 so this feature request can be added to product's wish list.
