### ISSUE TITLE
PHP 8.1 version returns with PHP errors in Query Monitor

### ISSUE THREAD

**Issue by namiokuzono** [Automattic/woocommerce-payments#5985]
### Describe the bug

When the site is on PHP 8.1 version, PHP errors are returned within Query Monitor's PHP errors tab: 

>  Return type of WCPay\Core\Server\Response::offsetGet($offset) should either be compatible with ArrayAccess::offsetGet(mixed $offset): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice

It seems this issue is not going to cause any functionality issue. 

### To Reproduce

1. Install Query Monitor - https://wordpress.org/plugins/query-monitor/
2. Change PHP version to 8.1
3. Check Query Monitor's PHP errors tab
4. PHP errors are present 

### Screenshots

![7E1sckNVAApcR9Go2udDvUTs3HoAC6nracTg6QTP.jpg](https://user-images.githubusercontent.com/85893744/230168881-9afc69e3-5365-48d6-a9d4-74cdfa9bb39a.jpg)

https://user-images.githubusercontent.com/85893744/230168673-00a73d87-4074-4a81-afc8-76462ca7e922.mp4

### Expected behavior

I think these PHP errors should not be returned.

**Comment by namiokuzono** [comment]
Originally reported in 6087250-zd-woothemes

**Comment by kaushikasomaiya** [comment]
6088426-zen

Merchant here does have functionality issue. Checkout is not working.

Edit: Apologies, this doesn't affect functionality. Merchant's server settings were conflicting.

**Comment by leonardola** [comment]
6088426-zen does not seem related and was fixed by the Merchant via server settings.
