### ISSUE TITLE
Remove jQuery dependency from split-UPE

### ISSUE THREAD

**Issue by FangedParakeet** [Automattic/woocommerce-payments#5999]
### Description

Our payment gateway client code generally has a dependency on jQuery: this is particularly the case with the [UPE](https://github.com/Automattic/woocommerce-payments/blob/develop/client/checkout/classic/upe.js#L30) and [split-UPE](https://github.com/Automattic/woocommerce-payments/blob/develop/client/checkout/classic/upe-split.js#L41). There isn't really any specific cause for this, beyond simply duplicating this code from the legacy card implementation. 

However, this dependency creates complexity when constructing unit tests for this client code, since the jQuery dependency makes it difficult to mock out critical functions. We aren't really using jQuery for any purpose, other than its selectors, which can all be handled relatively comfortably with vanilla JavaScript.

**Benefits of removing jQuery dependency**
- Removes unnecessary package/dependency.
- Makes code more readable.
- Allows us to write better unit tests.
- Allows possibility of someday converting client code to React component.
- And many more.

### Acceptance criteria

* Remove jQuery dependency from client scripts for the split-UPE **only**.
	* Once this has proved to be effective, we can consider doing the same for other client scripts. 
* Replace jQuery functions with regular JS alternatives.
* Amend/improve client unit tests.

**Comment by timur27** [comment]
Both UPE and split UPE will be removed soon, hence it doesn't make much sense to refactor this area as it will be deleted. My proposal is to close this issue. @frosso @FangedParakeet

**Comment by frosso** [comment]
Let's pretend like we worked really hard to refactor this, when in reality we're just naturally removing old code 👍
