### ISSUE TITLE
Uncaught TypeError: wcpayPaymentRequestParams.product.total is undefined

### ISSUE THREAD

**Issue by DEKHTIARJonathan** [Automattic/woocommerce-payments#6000]
The following error happen on the latest version of the plugin:

```
> [payment-request.js](https://www.mystore.com/wp-content/plugins/woocommerce-payments/dist/payment-request.js?ver=5.7.0)
Uncaught TypeError: wcpayPaymentRequestParams.product.total is undefined
    init https://www.mystore.com/wp-content/plugins/woocommerce-payments/dist/payment-request.js?ver=5.7.0:1
    <anonymous> https://www.mystore.com/wp-content/plugins/woocommerce-payments/dist/payment-request.js?ver=5.7.0:1
    jQuery 13
        e
        t
        setTimeout handler*Deferred/then/l/<
        c
        fireWith
        fire
        c
        fireWith
        ready
        $
        EventListener.handleEvent*
        <anonymous>
        <anonymous>
```

**Comment by csmcneill** [comment]
Howdy @DEKHTIARJonathan! Can you provide some more details about this issue?

- This appears to be a console error. When this console error occurs, do you experience any impact on the functionality of [WooCommerce Payments](https://woocommerce.com/products/woocommerce-payments/?aff=10486&cid=1131038)?
- If you disable all plugins aside from WooCommerce Payments **and** change to a default theme, like the [Storefront Theme](https://woocommerce.com/storefront/?aff=10486&cid=1131038), does this console error persist?
- Are you using the latest versions of WordPress, WooCommerce, and WooCommerce Payments?
- Is [the new checkout experience enabled](https://woocommerce.com/document/woocommerce-payments/payment-methods/additional-payment-methods/#enabling)?

I'm removing the `type: bug` label for now until we can confirm that this is a reproducible issue.

**Comment by DEKHTIARJonathan** [comment]
@csmcneill as far I can tell, it's only in the console.
The surprising thing is that this error appear absolutely every product page of the store. Not just a cart/checkout page.

It happens whether I'm logged as an admin or not.

> If you disable all plugins aside from WooCommerce Payments and change to a default theme, like the [Storefront Theme](https://woocommerce.com/storefront/?aff=10486&cid=1131038), does this console error persist?

I don't have an environment to be able to do that. I'm sorry.

> Are you using the latest versions of WordPress, WooCommerce, and WooCommerce Payments?

Everything at the latest version.

> Is [the new checkout experience enabled](https://woocommerce.com/document/woocommerce-payments/payment-methods/additional-payment-methods/#enabling)?

Yes

![image](https://user-images.githubusercontent.com/10923599/230818004-7e9b13d9-f1b3-4a8d-8564-8384e6389608.png)

**Comment by csmcneill** [comment]
Thanks for the information!

> I don't have an environment to be able to do that. I'm sorry.

I would recommend testing this out on a staging site. Many hosts provide staging facilities, so it's worth checking in with them. It’s also possible to spin out a staging site using the free [WP Staging](https://wordpress.org/plugins/wp-staging/) plugin.

You can learn more about staging environments and how they work in [this article](https://woocommerce.com/posts/what-is-staging-site-wordpress-how-to-set-one-up/).

**Comment by leonardola** [comment]
@DEKHTIARJonathan which page does the error happen? 

[This piece of code](https://github.com/Automattic/woocommerce-payments/blob/fix%2F6010-currency-switcher-widget/client/payment-request/index.js#L500) should only run in the product page when Google Pay and or Apple Pay are enabled.

The `wcpayPaymentRequestParams` variable is being populated [here](https://github.com/Automattic/woocommerce-payments/blob/fix%2F6010-currency-switcher-widget/includes/class-wc-payments-payment-request-button-handler.php#L725-L761) with the product data.

If the error is happening in the product page. Which type of product is it? A simple product, variable product, custom product type, etc?

Do you have any custom code hooking into [the `wcpay_payment_request_product_data` filter](https://github.com/Automattic/woocommerce-payments/blob/fix%2F6010-currency-switcher-widget/includes/class-wc-payments-payment-request-button-handler.php#L331) that ends up changing the product data being returned?

I tried to simulate the error in a product page and checkout page with different types of product but the error did not show up.

I also tried with UPE, split UPE and legacy payment methods

**Comment by jessy-p** [comment]
According to Pc2DNy-3z-p2, this falls in Fusion @anu-rock. Tagging as a part of Gamma Porter duties PcreKM-yM-p2.

**Comment by anu-rock** [comment]
As @leonardola wasn't able to reproduce it and we haven't heard from @DEKHTIARJonathan, I am closing this issue for now. Feel free to re-open when we have more information.
