### ISSUE TITLE
Simplify deposits UI - Don't show deposits history heading for new accounts that have no deposits

### ISSUE THREAD

**Issue by mattallan** [Automattic/woocommerce-payments#6001]
### Describe the bug

For new merchants that have no deposits yet and haven't completed their 7-day Waiting Period, we currently show the Deposits History section heading which can have conflicting information. For instance, I see a notice saying my deposits are being held for 7 days and also that they are automatically dispatched every day.

The figma designs for new merchants don't show the Deposit History section so we should update our code to be in line with this.

Designs from Figma:

![image](https://user-images.githubusercontent.com/2275145/231054095-ce69ab40-bf33-4925-961a-276e10d6999d.png)

Deposits Overview on `trunk`:

![image](https://user-images.githubusercontent.com/2275145/231054881-397d25d3-1bba-49d2-821e-708303da33c8.png)

### To Reproduce

1. Set feature flag to view latest deposits UI: `update_option( '_wcpay_feature_simplify_deposits_ui', 1 );`
2. Onboard as a new WC Pay account
3. Visit the Payments > Overview page
4. Notice the account waiting banner and the deposits history header section.

**Comment by haszari** [comment]
I'm thinking that the deposit history section should only display if there is history to display. I don't think we need to consult the waiting period or other onboarding flags. If a merchant is onboarding, they won't have deposit history.

**Comment by mattallan** [comment]
> I'm thinking that the deposit history section should only display if there is history to display. I don't think we need to consult the waiting period or other onboarding flags.

I agree. I've updated the title of this issue and slightly tweaked the description to match
