### ISSUE TITLE
Spike: Figure out which JS dependencies to update and corresponding versions

### ISSUE THREAD

**Issue by deepakpathania** [Automattic/woocommerce-payments#6029]
AC
- List of dependencies to update along with corresponding versions.
- Split them based on whether custom types exist for them already.

Criteria:
- Mention/request of update.
- Obvious ones (components etc)
- High usage and behind the latest.
- Deprecated ones.
- Alternatives recommended.

**Comment by jbordonado** [comment]
### WordPress dependencies

We could use the [packages-update](https://developer.wordpress.org/block-editor/reference-guides/packages/packages-scripts/#packages-update) command from `@wordpress/scripts` to easily sync the `@wordpress/...` dependencies version to the same versions of a specific WP release:

`wp-scripts packages-update --dist-tag=wp-6.0`

In this case, our package.json will be updated with the same versions as the ones seen in [WP 6.0.3](https://github.com/WordPress/wordpress-develop/blob/6.0.3/package.json), i.e. the minimum supported version of our plugin.

All the versions are defined with a caret `^`, but we can manually remove them afterward to pin to the exact versions.

### WooCommerce dependencies 

There's no utility script like WordPress.
We can look at the `package.json` from the minimum supported version of WooCommerce in our plugin, i.e. [WooCommerce 7.4.1](https://github.com/woocommerce/woocommerce/blob/7.4.1/plugins/woocommerce/package.json), and manually sync each `@woocommerce/...` dependency version in our own `package.json`.

If you encounter a dependency defined like this : `"@woocommerce/api-core-tests": "workspace:*"`, it means `use the corresponding version in the target folder`, i.e. navigate to the `api-core-tests` folder, open its `package.json` file and take the `version` from here. FYI, this is a PNPM [feature](https://pnpm.io/workspaces#publishing-workspace-packages) in the context of WooCommerce monorepo, which holds many different packages (called "workspaces").

--------

We should also be aware of the [WooCommerce Dependency Extraction Webpack Plugin](https://developer.woocommerce.com/2020/11/16/woocommerce-dependency-extraction-webpack-plugin/) tool that we're using in [our webpack setup](https://github.com/Automattic/woocommerce-payments/blob/develop/webpack/shared.js#L130-L148). As it stands now, it's worth noting a few things:
- We bundle the `@wordpress/components` dependency in our application code, i.e. we are sure that we're using the version [11.1.5](https://github.com/Automattic/woocommerce-payments/blob/develop/package.json#L112) for that dependency in production environment.
- For the rest of WP/WC dependencies, we use whatever is available on the global `window`, i.e. bundled with other plugins such as WordPress, WooCommerce, Gutenberg (if installed), etc... 
- Similarly, [a few other module requests](https://github.com/WordPress/gutenberg/tree/trunk/packages/dependency-extraction-webpack-plugin#webpack) are handled by default, including `lodash`, `jquery`, `react`, `react-dom`, ... So we are also using the bundled version of these dependencies in WordPress etc...

This is why we will try to align all these WC/WP dependencies to whatever is currently defined in the `package.json` of the minimum supported versions of WP ([6.0.3](https://github.com/WordPress/wordpress-develop/blob/6.0.3/package.json)) and WC ([7.4.1](https://github.com/woocommerce/woocommerce/blob/7.4.1/plugins/woocommerce/package.json)).

--------

There already exists a doc related to dependencies, which we can follow: https://github.com/Automattic/woocommerce-payments/blob/develop/docs/dependencies.md

**Comment by jbordonado** [comment]
## Summary

Naive usage (just using "Find in Files" in the IDE most of the time):
- High (> 100 occurrences)
- Medium ( 10 to 100 occurrences)
- Low (< 10 occurrences)

The target version is defined using the principles described [above](https://github.com/Automattic/woocommerce-payments/issues/6029#issuecomment-1508360228), i.e. we sync with the version bundled with the minimum supported version of WordPress/WooCommerce.

One remark: what do we do for dependencies that we use with a more recent version than the one bundled with min WP/WC (e.g. `@wordpress/url`)?  Do we downgrade?

This doesn't cover all our dependencies, but this is a start.

### WordPress

| Dependency                        | Current version | Target version | TS types | Usage
| -------------------------- | ---------------- | -------------- | ---------| ------- |
| [@wordpress/components](https://www.npmjs.com/package/@wordpress/components/v/19.8.5) | 11.1.5 | 19.8.5 | Yes | High |
| [@wordpress/data](https://www.npmjs.com/package/@wordpress/data/v/6.6.1) | 4.23.1 | 6.6.1 | Yes | High |
| [@wordpress/i18n](https://www.npmjs.com/package/@wordpress/i18n/v/4.6.1) | 4.1.1 | 4.6.1 | Yes | High |
| [@wordpress/hooks](https://www.npmjs.com/package/@wordpress/hooks/v/3.6.1) | 3.2.0 | 3.6.1 | Yes| High |
| [@wordpress/element](https://www.npmjs.com/package/@wordpress/element/v/4.4.1) | 2.20.3 | 4.4.1 | Yes | Medium |
| [@wordpress/icons](https://www.npmjs.com/package/@wordpress/icons/v/8.2.3) | 2.10.3 | 8.2.3 | Yes | Medium |
| [@wordpress/data-controls](https://www.npmjs.com/package/@wordpress/data-controls/v/2.6.1) | 1.6.0 | 2.6.1 | Yes | Medium |
| [@wordpress/api-fetch](https://www.npmjs.com/package/@wordpress/api-fetch/v/6.3.1) | 5.1.1 | 6.3.1 | Yes | Medium |
| [@wordpress/url](https://www.npmjs.com/package/@wordpress/url/v/3.7.1) | 3.30.0 | 3.7.1 | Yes | Medium |
| [@wordpress/date](https://www.npmjs.com/package/@wordpress/date/v/4.6.1) | 3.9.0 | 4.6.1 | Yes | Medium |
| [@wordpress/scripts](https://www.npmjs.com/package/@wordpress/scripts/v/22.4.2) | 12.6.0 | 22.4.2 | N/A | Medium |
| [@wordpress/plugins](https://www.npmjs.com/package/@wordpress/plugins/v/4.4.3) | 4.0.6 | 4.4.3 | [DefinitelyTyped](https://www.npmjs.com/package/@types/wordpress__plugins) | Low |
| [@wordpress/html-entities](https://www.npmjs.com/package/@wordpress/html-entities/v/3.6.1) | 2.11.2 | 3.6.1 | Yes | Low |
| [@wordpress/blocks](https://www.npmjs.com/package/@wordpress/blocks/v/11.5.3) | 11.0.1 | 11.5.3 | [DefinitelyTyped](https://www.npmjs.com/package/@types/wordpress__blocks) | Low |
| [@wordpress/block-editor](https://www.npmjs.com/package/@wordpress/block-editor/v/8.5.10)  | 7.0.2 | 8.5.10 | [DefinitelyTyped](https://www.npmjs.com/package/@types/wordpress__block-editor) | Low |
| [@wordpress/dom-ready](https://www.npmjs.com/package/@wordpress/dom-ready/v/3.6.1) | 3.29.0 | 3.6.1 | Yes | Low |
| [@wordpress/base-styles](https://www.npmjs.com/package/@wordpress/base-styles/v/4.3.1) | 3.5.4 | 4.3.1 | N/A | Low |
| [@wordpress/babel-plugin-makepot](https://www.npmjs.com/package/@wordpress/babel-plugin-makepot/v/4.3.2) | 4.2.0 | 4.3.2 | N/A | Low |
| [@wordpress/babel-preset-default](https://www.npmjs.com/package/@wordpress/babel-preset-default/v/6.8.1) | 7.4.0 | 6.8.1 | N/A | Low |
| [@wordpress/browserslist-config](https://www.npmjs.com/package/@wordpress/browserslist-config/v/4.1.3) | 5.3.0 | 4.1.3 | N/A | Low |
| [@wordpress/jest-preset-default](https://www.npmjs.com/package/@wordpress/jest-preset-default/v/8.1.2) | 4.0.0 | 8.1.2 | N/A | Low |

### WooCommerce

| Dependency                        | Current version | Target version | TS types | Usage
| -------------------------- | ---------------- | -------------- | -------- | ------- |
| [@woocommerce/components](https://www.npmjs.com/package/@woocommerce/components/v/12.0.0) | 5.1.2 | 12.0.0 | Yes | Medium |
| [@woocommerce/experimental](https://www.npmjs.com/package/@woocommerce/experimental/v/3.2.0) | 2.1.0 | 3.2.0 | Yes | Medium |
| [@woocommerce/currency](https://www.npmjs.com/package/@woocommerce/currency/v/4.2.0) | 3.0.0 | 4.2.0 | Yes | Low |
| [@woocommerce/explat](https://www.npmjs.com/package/@woocommerce/explat/v/2.3.0) | 1.0.1 | 2.3.0 | Yes | Low |
| [@woocommerce/eslint-plugin](https://www.npmjs.com/package/@woocommerce/eslint-plugin/v/2.2.0) | 1.1.0 | 2.2.0 | N/A | Low |
| [@woocommerce/date](https://www.npmjs.com/package/@woocommerce/date/v/4.2.0) | 2.1.0 | 4.2.0 | Yes | N/A |

### Others

| Dependency                        | Current version | Target version | TS types | Usage
| -------------------------- | ---------------- | -------------- | -------- | ------- |
| [react](https://www.npmjs.com/package/react/v/17.0.2) | 16.14.0 | 17.0.2 | [DefinitelyTyped](https://www.npmjs.com/package/@types/react) | High |
| [react-dom](https://www.npmjs.com/package/react-dom/v/17.0.2) | 16.14.0 | 17.0.2 | [DefinitelyTyped](https://www.npmjs.com/package/@types/react-dom) | High |

**Comment by jrodger** [comment]
> List of dependencies to update along with corresponding versions.

I'm sure you cover this elsewhere, but it's worth being very clear that we're talking about just JavaScript dependencies here and not touching the PHP ones.

> Naive usage (just using "Find in Files" in the IDE most of the time)

I don't think there's any need to do anything more complex here, this works fine 👍 . Maybe later we could label things as more or less important based on issues / requests around them, but for now this is good.

> i.e. we sync with the version bundled with the minimum supported version of WordPress/WooCommerce.

I don't disagree, but what's the reasoning for using the minimum supported version? I'm guessing it means we don't accidentally use something not available to all versions of WordPress, and then we hope that our e2e testing on later versions of WP catches any other issues?

On this note, for non-bundled packages, changes here will only affect our JavaScript unit tests right?

> One remark: what do we do for dependencies that we use with a more recent version than the one bundled with min WP/WC (e.g. @wordpress/url)? Do we downgrade?

The first step would be to establish if there's any particular reason we're using a later version. Presumably these packages are bundled into our distribution if the version differs from WP?

**Comment by jbordonado** [comment]
> I'm sure you cover this elsewhere, but it's worth being very clear that we're talking about just JavaScript dependencies here and not touching the PHP ones.

Good point. I updated the title for this spike and the Epic to clarify it and will do the same in the Project Thread.

> I don't disagree, but what's the reasoning for using the minimum supported version? I'm guessing it means we don't accidentally use something not available to all versions of WordPress, and then we hope that our e2e testing on later versions of WP catches any other issues?

Pretty much this. I thought that if we were to sync the deps based on the latest WP/WC, we might start using new features from deps only available on those recent versions. But if we sync with what's in the minimum supported WC/WP, we are "forced" to use stuff that is still (hopefully) compatible with more recent versions of the dependencies. Not sure if I'm being clear enough...

Also, WooCommerce will start following a [L-1 policy](https://developer.woocommerce.com/2023/02/23/revisiting-wordpress-core-support-policy-for-woocommerce/) in June, so I'm assuming we'll want to do the same right after and only support latest/previous releases for WP and WC, which would leave less room for dependencies issues than there is today...

> On this note, for non-bundled packages, changes here will only affect our JavaScript unit tests right?

That's an excellent point... While writing the [first task](https://github.com/Automattic/woocommerce-payments/issues/6054) that will serve as a template to update one dependency at a time, I lost focus of this.

If no particular issue has been brought to our attention so far, we can assume there's no breaking change between the local version we defined (and its current usage in our codebase) and the version we're about to target, right?

So the only things we can check after updating is the JS unit tests (which should also alert us on issues concerning TS types, if any, since new versions are now shipping the types).

E2E tests, manual UI checks etc.. are useless because it's still using the same version from WP (or WC), no matter what we say in our `package.json` (except for the `@wordpress/components` package that we bundle in our package).

> The first step would be to establish if there's any particular reason we're using a later version. Presumably these packages are bundled into our distribution if the version differs from WP?

No, they're not. I think we just didn't choose carefully the version sometimes (example in #5813).
For dev dependencies, we could keep the latest (e.g. for e2e utils package) instead of syncing with what's in WP, but for prod dependencies like `@wordpress/url`, I think it's best to downgrade.

**Comment by jrodger** [comment]
> Also, WooCommerce will start following a [L-1 policy](https://developer.woocommerce.com/2023/02/23/revisiting-wordpress-core-support-policy-for-woocommerce/) in June, so I'm assuming we'll want to do the same right after and only support latest/previous releases for WP and WC, which would leave less room for dependencies issues than there is today...

TIL. I don't see a problem with adopting the same policy as WooCommerce core, but it might be worth a separate discussion to confirm with others.

> If no particular issue has been brought to our attention so far, we can assume there's no breaking change between the local version we defined (and its current usage in our codebase) and the version we're about to target, right?

I think we have to assume that yeah, or at least as you say, nothing is broken that anyone has reported.

**Comment by jbordonado** [comment]
> TIL. I don't see a problem with adopting the same policy as WooCommerce core, but it might be worth a separate discussion to confirm with others.

Definitely!

Thank you James for your valuable input, I will close this spike now.
