### ISSUE TITLE
Payment intent type is not updated properly after creation

### ISSUE THREAD

**Issue by timur27** [Automattic/woocommerce-payments#6030]
### Describe the bug
For the legacy UPE and the split UPE, payment intents are created on the page load, to be more specific, on the `updated_checkout` event triggering. At this stage, the payment intent type is determined based on the cart total - if a cart needs payment, `payment` intent is created; otherwise, `setup` intent is.

There is a use case when payment type can change after intents are created. When a user adds a subscription product together with a physical product to the cart, then loads the checkout page, and after loading, applies a 100% coupon which zeroes the cart total, and tries to place the order - they will face an error, and the checkout won't succeed. See [this conversation](https://github.com/Automattic/woocommerce-payments/pull/5869#discussion_r1161113907), which will help gather more details about the issue.

### To Reproduce

1. Go to the admin panel and ensure that there's a 100% discount coupon available for shoppers
2. As a shopper, add a subscription and a physical product to the cart 
3. Open the shortcode checkout and apply the 100% discount coupon
4. Place the order

### Actual behavior
Users see the error on the checkout page.

### Screenshots
![image.png](https://images.zenhubusercontent.com/59de7a6cb0222d5de47b4727/231b6ac4-676e-44f6-bacc-2391884376e7)

### Expected behavior
The payment intent type should be updated successfully after the total cart change, and users should be able to checkout without errors.

**Comment by jessy-p** [comment]
https://github.com/Automattic/woocommerce-payments/pull/5869#discussion_r1161113907

**Comment by jessy-p** [comment]
According to Pc2DNy-3z-p2, this falls in Heisenberg @bborman22. Tagging as a part of Gamma Porter duties PcreKM-yM-p2.

**Comment by jessy-p** [comment]
According to Pc2DNy-3z-p2, this falls in Heisenberg @bborman22. Tagging as a part of Gamma Porter duties PcreKM-yM-p2.

**Comment by pierorocca** [comment]
@timur27 has dUPE made this issue irrelevant?

**Comment by timur27** [comment]
Thank you for the ping @pierorocca!

> has dUPE made this issue irrelevant?

Yes. I've tested it now as well and can confirm the issue cannot be reproduced anymore. Closing.
