### ISSUE TITLE
[BNPL] Add Feature Flag for Development of BNPL providers: Affirm & Afterpay

### ISSUE THREAD

**Issue by mgascam** [Automattic/woocommerce-payments#6034]
### Description
Create a feature flag for the development of the integration of Affirm & Afterpay BNPL providers. 

### Acceptance criteria
1. The feature flag should be turned off by default, so we do not interfere with production code while the feature is under development
2. The feature flag can be turned on for development.
3. The feature flag should take into account the server flag implemented in https://github.com/Automattic/woocommerce-payments-server/pull/3344

**Comment by kalessil** [comment]
As a note: the server side is what drives the feature flag. The client shall rely on server one, and if the server is not sending it anymore, then we are considering the flag enabled.

The background here is that we can deploy the server almost any time, but client release/update by the merchant is less flexible than server deployments.

**Comment by KarlisJ** [comment]
Want to clarify the scope for this issue.

`WC_Payments_Features` exposes method to the BNPL feature flag. It's not used as part of this issue. This method will be used in future issues when we actually implement it.
Correct?

**Comment by mgascam** [comment]
> `WC_Payments_Features` exposes method to the BNPL feature flag. It's not used as part of this issue. This method will be used in future issues when we actually implement it. Correct?

Yes, correct. We are introducing the feature flag, but not using it yet
