### ISSUE TITLE
Simplify deposits UI - tooltip when pending balance is negative

### ISSUE THREAD

**Issue by shendy-a8c** [Automattic/woocommerce-payments#6051]
In https://github.com/Automattic/woocommerce-payments/issues/5724, we show special message and link when available balance is negative. Turns out, pending balance can also be negative and we do not have special explanation in the tooltip when that happens.

This issue is to address that problem.

I think when pending balance is negative, its tooltip should say the same thing as the available balance tooltip when available balance is negative, ie:
"Learn more about why your account balance may be negative." where "Learn more" links to https://woocommerce.com/document/woocommerce-payments/fees-and-debits/account-showing-negative-balance

**Comment by jessy-p** [comment]
According to Pc2DNy-3z-p2, this falls in Helix @haszari. Tagging as a part of Gamma Porter duties PcreKM-yM-p2.
