### ISSUE TITLE
Change Status chip WooCommerce pill component

### ISSUE THREAD

**Issue by dwainm** [Automattic/woocommerce-payments#6060]
We can follow the strategy that Helix are using for the status chips, this is to avoid design and tech debt within WCPay.

The status chip is currently used on the Transactions page in the Status column.

<img width="2799" alt="image" src="https://github.com/Automattic/woocommerce-payments/assets/3295/dda32cfc-305d-4277-b844-3a89fbe3d3e1">

**Comment by dwainm** [comment]
More context here: p1680453890100759-slack-C01B8KNUYSW

**Comment by nagpai** [comment]
Related - Risk Level status within Payment > Transactions has been changed to Pill in #6041
