### ISSUE TITLE
Update `@wordpress/browserslist-config` dependency to version 4.1.3

### ISSUE THREAD

**Issue by jbordonado** [Automattic/woocommerce-payments#6089]
### Description

We want to update the [@wordpress/browserslist-config](https://www.npmjs.com/package/@wordpress/browserslist-config) package to a more recent version, the one being used by our minimum supported version of WordPress:

- Current version: [5.3.0](https://www.npmjs.com/package/@wordpress/browserslist-config/v/5.3.0)
- Target version: [4.1.3](https://www.npmjs.com/package/@wordpress/browserslist-config/v/4.1.3)

### Acceptance criteria

- JS unit tests are passing
- The review process from the [dependencies doc](https://github.com/Automattic/woocommerce-payments/blob/develop/docs/dependencies.md#javascript-dev-dependencies) was followed and now has an entry for this package with all the relevant details for future iterations

### Dev notes

Run `npm install --save-exact <packageName@version>` to update a package by an exact version.

**Comment by deepakpathania** [comment]
Decided not to do based on this discussion: p1683797295043629-slack-C052F9CCVT9
