### ISSUE TITLE
Shortcode Checkout with BNPL providers

### ISSUE THREAD

**Issue by mgascam** [Automattic/woocommerce-payments#6119]
### Scenario 1: Display BNPL Providers at Checkout
**As a** buyer of a shop that has BNPL (Buy Now Pay Later) providers enabled,
**I want to** see which BNPL providers I can use on the checkout page,
**So that** I can choose one to pay for my order.

#### Acceptance Criteria

1. On the checkout page, a list of available BNPL providers should be displayed.
2. Each BNPL provider should have a clear and recognizable logo or name.
3. The buyer should be able to select one of the available BNPL providers to proceed with the payment process.
4. Each BNPL provider will appear in the list of available providers only if the purchase is compatible in terms of:
4.1. Customer location
4.2. Presentment currency
4.3. Recurring payments (a.k.a. subscriptions are not supported)
4.4. Country availability
4.5. Purchase limits
5. UPE and split UPE peculiarities should be taken into account.

Please check the following links for details:

- [Afterpay and Clearpay payments | Stripe Documentation](https://stripe.com/docs/payments/afterpay-clearpay)
- [Affirm payments | Stripe Documentation](https://stripe.com/docs/payments/affirm)

### Designs

TBD

### Dev notes
Based on our initial spikes, Split UPE and Legacy UPE work out of the box, please refer to screenshots below. Nonetheless, we should test both scenarios.

_Split UPE_
<img width="813" alt="Screenshot 2023-05-05 at 19 33 56" src="https://user-images.githubusercontent.com/1553182/236533376-6329dfc5-0908-4ef0-b444-37aefa852578.png">

_Legacy UPE_
<img width="610" alt="Screenshot 2023-05-05 at 19 24 03" src="https://user-images.githubusercontent.com/1553182/236533466-1ce7186d-7f93-472c-a23d-f75b52fb93eb.png">

### Scenario 2:  Redirect to Confirmation Page after Successful BNPL Payment

Redirect to Confirmation Page after Successful BNPL Payment

**As a** buyer,
**I want to** be redirected to a confirmation page after successfully completing the payment process with a BNPL provider,
**So that** I know that my order is completed.

#### Acceptance Criteria

1. After the buyer successfully completes the payment process with the chosen BNPL provider, they should be redirected to a confirmation page.
2. The confirmation page should display relevant order information, such as order number, items, and total cost.
3. The page should also include a message confirming that the order has been completed.

### Designs

TBD

### Scenario 3: Redirect to Error Page after BNPL Payment Error

**As a** buyer,
**I want to** be redirected to an error page when there is an error in the payment process with a BNPL provider,
**So that** I know that my order is not completed and the reason why it was not completed.

#### Acceptance Criteria

1. If an error occurs during the payment process with the chosen BNPL provider, the buyer should be redirected to an error page.
2. The error page should display a clear and informative message explaining the reason for the payment failure.
3. The buyer should be given options to either try the payment process again or choose a different payment method.

### Designs

TBD

### Assumptions
We can use integration spikes as starting points and guidance on what needs to be accomplished.

### Dev notes

* We completed integration spikes: https://github.com/Automattic/woocommerce-payments-server/pull/3183 and https://github.com/Automattic/woocommerce-payments/pull/5910
### Additional context
* We need to test all possible breaking points in the complete flow. Merchant Checkout page->BNPL site->BNPL Approval / Reject->Redirect to Merchant store.
* We should only rely on webhooks sent by Stripe to update the status of the order.

**Comment by mgascam** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Team-Pulsar-613b38b8326cdc001438b38f/issues/Automattic/woocommerce-payments/6119?planning-poker) with Zenhub @dmvrtx @kalessil @KarlisJ @nagpai

**Comment by KarlisJ** [comment]
@mgascam To confirm - we need to test all the scenarios from UPE, Legacy UPE, and SPLIT UPE?

**Comment by KarlisJ** [comment]
**Changing billing country doesn't trigger hiding the Affirm PM from UPE element.** 

As a result, I managed to put my billing address in EU and perform payment. Getting failed payment.
> We were unable to process your order, please try again. 


Moved to [issue](https://github.com/Automattic/woocommerce-payments/issues/6515)

**Comment by KarlisJ** [comment]
**Visiting checkout page with less than 50 USD in cart immediately display error message "We're not able to process this request. Please refresh the page and try again.
"**

In the logs:
> ERROR Amount must be no less than $50.00 USD for the Affirm payment method. (amount_too_small)


Moved to [issue](https://github.com/Automattic/woocommerce-payments/issues/6516)

**Comment by KarlisJ** [comment]
**Affirm is not hidden from UPE for incorrect presentment currency**

Affirm support both USD and CAD but limits the currency for the payment to the currency of Stripe account. In this case my local setup is as follows
- Stripe account based in US
- Multicurrency available
- Buyer select CAD as currency 
- Failed payment
Visible error message:
>We're not able to process this request. Please refresh the page and try again.

Error logs:
> ERROR The currency provided (cad) is invalid. Payments with affirm support the following currencies: usd. (invalid_request_error)

Note: Any other currency than USD/CAD does properly hide Affirm from UPE. 



Moved to [issue](https://github.com/Automattic/woocommerce-payments/issues/6517)
