### ISSUE TITLE
Review the repository access rights for collaborators and teams

### ISSUE THREAD

**Issue by jbordonado** [Automattic/woocommerce-payments#6120]
### Description

The goal is to review the access for each collaborator and team working on this repository.
Ideally, the number of administrators is limited.

Why? We've seen multiple instances of people mistakenly pushing to `develop` or `trunk` without a PR. It can happen because administrators can always bypass the branch protection settings in place, and several teams have the "admin" role.

### Acceptance criteria

* Every team and collaborator has the least level of access required to function
* The branch protection settings are still relevant. If not, they were updated accordingly.
* Release workflows (`botwoo`) are not impacted by the changes

**Comment by jbordonado** [comment]
@vbelolapotkov Maybe something for you to take on, by the way?

**Comment by vbelolapotkov** [comment]
Closing as not relevant at this point.
