### ISSUE TITLE
[Spike]: Confirmation Modal while canceling un-captured orders

### ISSUE THREAD

**Issue by nagpai** [Automattic/woocommerce-payments#6126]
### Background

Whenever the status of an Authorization is changed, it is desired to have a confirmation modal that gives further information / warning to the merchant with the following scenarios:

* When the status of the order is manually changed to Cancelled, the modal can show a message warning that the authorization would be cancelled too. Sample text:  

>Cancel authorization
>
>This order has been [authorized but not captured](https://woocommerce.com/document/woocommerce-payments/settings-guide/authorize-and-capture/#authorize-vs-capture) yet. Changing the status to Cancelled will also [cancel the authorization](https://woocommerce.com/document/woocommerce-payments/settings-guide/authorize-and-capture/#cancelling-authorizations). Do you want to continue?
>
>[ Do nothing ]     [ Cancel order and authorization ] 

* When the order status is manually changed to `Complete`, the modal will need to show a warning mentioning that the payment will be captured if we proceed. Sample message:

>
>Capture payment
>
>This order has been [authorized but not captured](https://woocommerce.com/document/woocommerce-payments/settings-guide/authorize-and-capture/#authorize-vs-capture) yet. Changing the status to Completed will also [capture the payment](https://woocommerce.com/document/woocommerce-payments/settings-guide/authorize-and-capture/#capturing-authorized-orders). Do you want to continue?
>
>[ Do nothing ]     [ Complete order and capture payment ]
>

### Acceptance criteria
* Document how the scenarios above are currently handled
* Estimate the effort needed to bring about these modals

### Designs
Similar to the modals we have currently 
![image](https://user-images.githubusercontent.com/4162931/233620809-87182b34-526c-41fb-a707-6724c04d204e.png)

### Dev notes

* Code of [existing cancellation modal](https://github.com/Automattic/woocommerce-payments//blob/29292b783f31af50741b65e21322ee25f5f818b5/client/order/cancel-confirm-modal/index.js) 

### Additional context
* Related P2 Discussion - pdjVC1-1vj-p2
* Related issue - #5712  
* Related Spike on server GH on fixing the actual handling of Auth expiration on orders. - https://github.com/Automattic/woocommerce-payments-server/issues/3254

**Comment by nagpai** [comment]
Currently,  we have a jQuery based code that listens to changes in the order status dropdown on the order detail page, and modals are triggered whenever `Cancelled` or `Refunded` status is chosen in the dropdown. 

If further action is confirmed on the modal, then an API call is sent to update the order status / issue refund ( if applicable). 

We could use a similar structure 

1. On the `Cancelled` event handler, we will need to add a conditional for uncaptured ( Auth and capture ) orders, and to show a different modal if that is true. This modal will show contents similar to what is specified in the main issue above, and then cancel the authorization if confirmed. 

2. For the `Completed` condition a new modal and event handler will need to be written that would update the order status , and also send a request to cancel the pending authorization.

**Comment by kalessil** [comment]
@mgascam: please re-check this and connected issues to see what's yet to be covered.

**Comment by mgascam** [comment]
We could prioritize implementing confirmation modals when the order transitions from `On Hold`, as this status occurs after the order has been successfully authorized. I have compiled a table listing the possible transitions with the corresponding actions to take for each:

| Current State | Next State | Action                    | Implemented |
|---------------|------------|---------------------------|-------------|
| On Hold       | Pending    | Cancel the authorization | No          |
| On Hold       | Processing | Capture the authorization| No          |
| On Hold       | Failed     | Cancel the authorization | No          |
| On Hold       | Completed  | Capture the authorization| No          |
| On Hold       | Cancelled  | Cancel the authorization | https://github.com/Automattic/woocommerce-payments/pull/7743         |

I propose that the available actions should involve either capturing or canceling the authorization, depending on the subsequent state.
