### ISSUE TITLE
Check compatibility between WooPay and WCPay Fraud Service

### ISSUE THREAD

**Issue by ricardo** [Automattic/woocommerce-payments#6132]
### Description

There was [a bug](https://github.com/Automattic/woocommerce-payments-private/pull/34#discussion_r1172160667) in `WC_Payments_Fraud_Service` affecting WooPay where the fraud service class didn't expect a different object returned from `WC()->session` and was calling an undefined method `get_session_cookie`.

As WooPay uses the Store API Session Handler, it doesn't provide that method. So an error was thrown.

We fixed that bug by returning early in `check_if_user_just_logged_in` and `get_cookie_session_id` in case the `get_session_cookie` method didn't exist, but the support for the fraud service in WooPay might be broken as a cookie is never attached to `session_id`. 

To be clear, this bug was already present before we merged https://github.com/Automattic/woocommerce-payments-private/pull/34. On that PR we're just re-implementing the same Store API Session Handler with a different fix.

### Acceptance criteria

* Check and fix the compatibility between the implementation in `WC_Payments_Fraud_Service` and WooPay.

### Additional context

p1681914603020739/1681852372.665879-slack-C022WMN88KG

**Comment by jessy-p** [comment]
According to Pc2DNy-3z-p2, this falls in Sigma @dwainm. Tagging as a part of Gamma Porter duties PcreKM-yM-p2.

**Comment by c-shultz** [comment]
I'm changing this to a (potential) bug and flagging it in the WooPay queue to confirm/follow-up.

**Comment by ricardo** [comment]
> do we understand what the potential consequences are here?

I'm not very familiar with the Sift integration, but I'm guessing it might not work properly for WooPay checkouts.

Maybe someone from @Automattic/sigma would be best to answer this – If the [`get_cookie_session_id`](https://github.com/Automattic/woocommerce-payments/blob/9797501248d45fa165465cfabd3ec7f5386fce3d/includes/class-wc-payments-fraud-service.php#L185) method always returns `null` for https://pay.woo.com checkout sessions, how does it affect the fraud prevention on that website?

**Comment by dwainm** [comment]
I am closing this issue for now. Will message you directly.
