### ISSUE TITLE
Evaluate static type checkers

### ISSUE THREAD

**Issue by jrodger** [Automattic/woocommerce-payments#614]
Strong typing could help our development, but there are some blockers to going all out with it:

* There's a potential runtime penalty of type checking everything (in some cases, and not sure how much)
* We target a relatively low version of PHP so don't have access to all the features we might want

On the plus side it can help us understand what we're working with and avoid simple mistakes. It could help with some of the exception handling discussions we've had.

Some options:

* https://github.com/phan/phan
* https://github.com/phpstan/phpstan
* https://github.com/vimeo/psalm (Explored in https://github.com/Automattic/woocommerce-payments/pull/486).

We should evaluate some of the proposed tools, and see if we can hook some reporting into our CI builds. Once we have that we can discuss if we think it's useful.

**Comment by RadoslavGeorgiev** [comment]
https://github.com/Automattic/woocommerce-payments/pull/3484 introduced Psalm to the client, so I'm closing this issue. @kalessil or @jrodger correct me if I'm wrong.
