### ISSUE TITLE
Address progressive onboarding feedback

### ISSUE THREAD

**Issue by ismaeldcom** [Automattic/woocommerce-payments#6158]
After finishing the implementation of the main project issues, we will have multiple reviews to refine the end result, and fix any unnoticed bug.

List of known feedback to address:
- **Builder mode**
  - `<SetupRealPayments/>` card should be placed above the account card.
  - `<SetupRealPayments/>` should be dismissable `isDismissible={true}` as by default.
  - `Continue setup` on `Setup live payments on your store` should redirect to the new onboarding flow directly, skipping payments connect screen.
- **Eligibility modal**
  - Check padding on the bottom buttons 
![image](https://user-images.githubusercontent.com/79862886/236177626-e4fd0dd8-f969-4148-9968-2a52f5fbf4c1.png)
- **Loading page**
  - fix styling on the page https://github.com/Automattic/woocommerce-payments/issues/6158#issuecomment-1535917400

Most recent design feedback: p1682541754731339-slack-C03KTTK2YMA

**Comment by dmallory42** [comment]
Just noting that I saw a possible issue when testing the tracking PR, not sure if it was just a local issue or some change introduced by the recent dependencies update, but we should confirm. 

![Screenshot 2023-05-05 at 09 18 59](https://user-images.githubusercontent.com/11770181/236412031-0d47ad69-d893-4c0b-b36a-9bcaf904aa39.png)

**Comment by oaratovskyi** [comment]
@dmallory42 I also reproduced that, I will add it to the description, thanks!
