### ISSUE TITLE
Some add payment method tasks unit tests failing due to jest.runAllTimers() issue

### ISSUE THREAD

**Issue by allie500** [Automattic/woocommerce-payments#6173]
While reviewing an unrelated PR, I ran unit tests and saw that a couple of tests in `client/additional-methods-setup/upe-preview-methods-selector/test/add-payment-methods-task.test.js` failed with the following error:

```
Ran 100000 timers, and there are still more! Assuming we've hit an infinite recursion and bailing out...
```

I reinstalled dependencies and rebuilt the client code but the issue persisted. I flagged the issue in Slack with the rest of Sigma and other team members were able to reproduce it. 

[Research](https://jestjs.io/docs/25.x/timer-mocks#run-pending-timers) and my local testing shows that replacing `jest.runAllTimers();` with `jest.runOnlyPendingTimers();` resolves the issue.

**Comment by jessy-p** [comment]
According to Pc2DNy-3z-p2, this falls in Harmony @deepakpathania. Tagging as a part of Gamma Porter duties PcreKM-yM-p2.
