### ISSUE TITLE
WooPay express checkout button not displaying on Cart blocks page

### ISSUE THREAD

**Issue by bborman22** [Automattic/woocommerce-payments#6181]
### Describe the bug

While testing some of the WooPay checkout flows it was discovered that the WooPay express checkout button was not displaying on the Cart blocks page even when the button was set to display on the cart.

In digging into the problem I found that there is an additional check being performed that is limiting the one flag to only be true on the checkout page.
[Conditional that should include the cart as well as checkout page.](https://github.com/Automattic/woocommerce-payments/blob/develop/includes/platform-checkout/class-platform-checkout-utilities.php#L48-L51)
[Flag that gets set to false due to the previous check on the cart page.](https://github.com/Automattic/woocommerce-payments/blob/develop/includes/class-wc-payments-checkout.php#L120)
[The front-end check that prevents rendering the express checkout button due to the flag being false.](https://github.com/Automattic/woocommerce-payments/blob/develop/client/checkout/blocks/index.js#L70)

I can see two solutions, either removing this check that limits it to just the checkout page or extending this check to include the cart page as well. I also think a lot of [these checks are already performed](https://github.com/Automattic/woocommerce-payments/blob/develop/includes/class-wc-payments-platform-checkout-button-handler.php#L531-L551) for the express checkout button in the handler, so the original issue of subscriptions + no guest checkout should still be handled properly.

### To Reproduce

1. With a merchant store set up with WooPay enabled and eligible.
2. Make sure that WooPay is enabled on product, cart, checkout page.
3. If not already created, [create a blocks Cart page](https://woocommerce.com/document/using-the-new-block-based-checkout/).
4. As a shopper visit the merchant store.
5. Visit the product cart and confirm button IS displayed.
6. Add product to cart and visit the blocks cart page.
7. Confirm express checkout button is NOT displayed.
8. Click on checkout and confirm express checkout button IS displayed.

### Actual behavior

WooPay express checkout button is not displayed on the blocks cart.

### Expected behavior

The WooPay express checkout button should be displayed on the blocks cart page.

### Additional context

This is likely a side effect from #6150

**Comment by pierorocca** [comment]
@bborman22 I'm testing out a Looker model for pulling in Github issue data and noticed this issue is open and should be closed?

**Comment by pierorocca** [comment]
@bborman22 following up again as this is marked 'critical' and open for 22 days. Should be closed?

**Comment by bborman22** [comment]
Oo sorry, yes this closed by #6184 and was part of a patch release in 5.8.1.
