### ISSUE TITLE
WP core time settings can mess up exchange rate times

### ISSUE THREAD

**Issue by aheckler** [Automattic/woocommerce-payments#6183]
### Describe the bug

If the WP core time format is like so:

![Screenshot taken on 2023-05-01 at 19 26 30 UTC@2x](https://user-images.githubusercontent.com/5512652/235515687-2d3122e5-6a4a-457f-a048-bc6f40c27ff3.png)

... the WC Pay exchange rate "Last updated" time is not displayed correctly:

![Screenshot taken on 2023-05-01 at 19 27 16 UTC@2x](https://user-images.githubusercontent.com/5512652/235515775-fa95cf89-e038-4a38-9846-21dad4291d28.png)

### To Reproduce

1. WC Pay test site with multi-currency enabled.
2. Go to core's Settings page and set time format to Custom using `g:ia`.
3. Save Changes.
4. Go WooCommerce > Settings > Multicurrency tab.
5. Add a currency.
6. Click the "manage" link for that currency.
7. Notice the timestamp displayed with `i` for the minutes.

**Comment by jessy-p** [comment]
According to Pc2DNy-3z-p2, this falls in Sigma @dwainm. Tagging as a part of Gamma Porter duties PcreKM-yM-p2.

**Comment by dwainm** [comment]
Nice catch! Interesting bug.
