### ISSUE TITLE
Rename "Add currencies" button

### ISSUE THREAD

**Issue by aheckler** [Automattic/woocommerce-payments#6185]
Minor issue, but the Add Currencies button could use a name improvement since, after all, it's possible to also _remove_ currencies using it.

![Screenshot taken on 2023-05-01 at 19 52 45 UTC@2x](https://user-images.githubusercontent.com/5512652/235519847-29cd641f-ad7b-42c8-9322-4dff3c435e87.png)

Maybe one of these?

- Add/remove currencies
- Edit currencies list
- Manage currencies

... or similar.

**Comment by jessy-p** [comment]
According to Pc2DNy-3z-p2, this falls in Sigma @dwainm. Tagging as a part of Gamma Porter duties PcreKM-yM-p2.

**Comment by dwainm** [comment]
This makes sense @aheckler . Myself and @jessepearson spoke about this when the feature was being developed.
