### ISSUE TITLE
Update links in multi-currency settings

### ISSUE THREAD

**Issue by aheckler** [Automattic/woocommerce-payments#6186]
Several links in the multi-currency settings are no longer linking to the correct places.

![Screenshot taken on 2023-05-01 at 20 00 40 UTC@2x](https://user-images.githubusercontent.com/5512652/235521048-6e79f902-39d6-4c52-b395-c7361794da77.png)

Link 1 should go here: `https://woocommerce.com/document/woocommerce-payments/currencies/multi-currency-setup/#enabled-currencies`

Link 2 should be: `https://woocommerce.com/document/woocommerce-payments/currencies/multi-currency-setup/#store-settings`

![Screenshot taken on 2023-05-01 at 20 01 35 UTC@2x](https://user-images.githubusercontent.com/5512652/235521221-0230a024-1a23-4709-95ea-23b8f02be123.png)

Link 3: `https://woocommerce.com/document/woocommerce-payments/currencies/multi-currency-setup/#price-rounding` 

Link 4: `https://woocommerce.com/document/woocommerce-payments/currencies/multi-currency-setup/#charm-pricing`

**Comment by jessy-p** [comment]
According to Pc2DNy-3z-p2, this falls in Sigma @dwainm. Tagging as a part of Gamma Porter duties PcreKM-yM-p2.

**Comment by eduardoumpierre** [comment]
Hi @aheckler!

I checked the code and links 3 and 4 were already updated. Links 1 and 2 are linking to https://woocommerce.com/document/woocommerce-payments/currencies/multi-currency-setup/ and are missing the URI fragment part `#enabled-currencies` and `#store-settings`.

Should we still update the links?

**Comment by aheckler** [comment]
@eduardoumpierre Yes please. :) Thanks!

**Comment by aheckler** [comment]
Actually, with the rebranding, the correct links for 1 and 2 would be:

1. `https://woocommerce.com/document/woopayments/currencies/multi-currency-setup/#enabled-currencies`
2. `https://woocommerce.com/document/woopayments/currencies/multi-currency-setup/#store-settings`
