### ISSUE TITLE
Make alignment of text columns in tables to the left.

### ISSUE THREAD

**Issue by vbelolapotkov** [Automattic/woocommerce-payments#620]
Discussed with @LevinMedia in slack: p1587455735265600-slack-wcpay
See screenshots in server#228

Discussed with isotope: p1587540899281400-slack-team-isotope.
A related issue is created in WC admin: woocommerce/woocommerce-admin#4175

**Comment by naman03malhotra** [comment]
Closing in favor of https://github.com/Automattic/woocommerce-payments/issues/2351
