### ISSUE TITLE
Missing checks for order status before capturing terminal payment

### ISSUE THREAD

**Issue by anu-rock** [Automattic/woocommerce-payments#6203]
### Description

We currently have checks in place to prevent a terminal payment from being captured when the given payment intent's status is not one that we expect.

https://github.com/Automattic/woocommerce-payments/blob/9797501248d45fa165465cfabd3ec7f5386fce3d/includes/admin/class-wc-rest-payments-orders-controller.php#L169-L171

We should add a similar check for the order status to ensure that processed or completed orders are not double-charged when provided with a fresh payment intent.

### Additional context
* Discussion and related incident - pdfdoF-2HE-p2

**Comment by toupper** [comment]
@anu-rock Any news about this one? Do you have a rough estimation of when could it be tackled? Thanks a lot :)

**Comment by anu-rock** [comment]
@toupper We discussed this at the start of our maintenance sprint a couple of weeks back but prioritized #6239 over this. To me, this looks like an edge case and we can revisit it during our next maintenance sprint or cooldown week. But let me know if you think it should be prioritized soon.

**Comment by toupper** [comment]
@anu-rock Thanks for the answer :) Yeah, #6239 has more priority also from my point of view. I will keep an eye in case this happens again, so we can prioritize it sooner 👍

**Comment by anu-rock** [comment]
@toupper Awesome, thank you 🙌
