### ISSUE TITLE
Analytic & Tracking for Merchant BNPL Enablement Journey

### ISSUE THREAD

**Issue by mgascam** [Automattic/woocommerce-payments#6204]
### Description

As a Woo system user, I want to track and analyze each step and interaction of the merchant's BNPL enablement journey so that I can understand the conversion rate, churn rate, and identify potential areas of improvement.
### Acceptance criteria

1. The Woo system must track each step and interaction of the merchant's BNPL enablement journey.
2. The Woo system should have Tracks events for each main interaction (main CTA) and supporting interactions (page-level UX).
3. The Woo system must allow users to construct a Tracks "funnel view" along the merchant BNPL enablement journey.
4. The funnel view should provide insights into the following metrics:
    a. Percentage of merchants who completed BNPL enablement (Conversion Rate)
    b. Percentage of merchants who dropped off during the journey (Churn Rate)
    c. Analysis of where merchants mostly dropped off during the journey (Churn Analysis)

### Additional context

- Tracks FG: https://fieldguide.automattic.com/analytics-development-documentation/data-tools/tracks/tracks-for-developers-product-teams/tracks-in-woocommerce/
- Tracks JS module: https://github.com/Automattic/woocommerce-payments/blob/develop/client/tracks/index.js

Adding examples of how we implemented tracks for the auth&capture project in case are useful:

- https://github.com/Automattic/woocommerce-payments/pull/5006/commits/9a9bb5d5827e6fcafe1086b5c45d39ce00c54b57
- https://github.com/Automattic/woocommerce-payments/pull/5006/commits/878c982f4423fd5b6639c2abe7e10bafa6fd51b4
- https://github.com/Automattic/woocommerce-payments/pull/4982/commits/a368f50c0b89fbee16b9c9dc538948bcaed151e3

Another example: https://github.com/Automattic/woocommerce-payments/pull/5564

**Comment by dmvrtx** [comment]
From my understanding we want to have tracks at these places in `client/payment-methods/index.js`:

 - `handleEnableUpeClick`, start of the funnel, enables access to BNPL methods. I'd use feature flag check to send a BNPL-specific event.
 - `handleCheckClick` and `handleUncheckClick` in `PaymentMethods` will tell us if merchant enables one of the payment methods or disables it later.

We might be also interested in the first BNPL payment, which I'll explore further.

Does this sound reasonable, @mgascam?

**Comment by mgascam** [comment]
> From my understanding we want to have tracks at these places in `client/payment-methods/constants.ts`:
> 
>     * `handleEnableUpeClick`, start of the funnel, enables access to BNPL methods. I'd use feature flag check to send a BNPL-specific event.
> 
>     * `handleCheckClick` and `handleUncheckClick` in `PaymentMethods` will tell us if merchant enables one of the payment methods or disables it later.
> 
> 
> We might be also interested in the first BNPL payment, which I'll explore further.
> 
> Does this sound reasonable, @mgascam?

Thanks @dmvrtx this makes sense to me 👍
