### ISSUE TITLE
SEPA support with deferred intent UPE

### ISSUE THREAD

**Issue by FangedParakeet** [Automattic/woocommerce-payments#6205]
### Description

The goal of this issue is to ensure that the main checkout flow for the SEPA Direct Debit payment method is supported and implemented within the deferred intent UPE feature, developed in #5869. In theory, SEPA should be no different than any other UPE payment method; however, SEPA will become the only non-card payment method available for use with recurring payments. 

SEPA will consequently require compatibility with existing WC Payment Tokens and WC Subscriptions. This scope of this issue does **not** include completing the implementation for these features, but will include scoping their current compatibility once the main checkout flow has been completed. Resolving subscriptions can be handled by #5517, while managing payment tokens can be handled by #5531. If further functionality for this feature is needed, we will need to create new issues to handle these requirements.

#### Features that should be expected within this issue
- Merchant can enable SEPA Direct Debit from settings.
- Customer can complete checkout using SEPA Direct Debit.
- Success/failed status updates are reflected on WC Order.
- Correct WCPay Transaction details are reflected and visible for merchant.

#### Things that should not be expected within this issue
- SEPA Direct Debit checkouts for subscription items.
- Manual capture, refunds, disputes, etc. Essentially any [merchant flows](https://github.com/Automattic/woocommerce-payments/wiki/Testing-instructions-for-critical-flows#merchant) beyond the basic transaction details.
- Saving/reusing SEPA Direct Debit payment methods. (disabled because we don't want to enable it for subscriptions and currently they share the same flag; see #7094)

Once this feature has been implemented, it would be great if the reviewer (or assignee, if must be) could complete all relevant [critical test flows](https://github.com/Automattic/woocommerce-payments/wiki/Testing-instructions-for-critical-flows) while using SEPA and report which additional functionality still requires implementation, so that we can create new issues to handle this future work. 

### Testing instructions

To enable SEPA Direct Debit, you will need to enable the SEPA Direct Debit capability from your store's Stripe account dashboard and then refresh your local cache to recheck for this renewed capability; the simplest way that I'm aware of to achieve the latter is to restart the containers for your local Payments Server.

### Additional context

Dependent on implementation from #5770 
Sibling to #5517 and #5531

**Comment by FangedParakeet** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Heisenberg-63586f2ec60359001310fa6a/issues/Automattic/woocommerce-payments/6205?planning-poker) with Zenhub @mdmoore @timur27

**Comment by csmcneill** [comment]
Currently, we see that SEPA via WCPay isn't compatible with recurring payments. The parent order is fine, but renewals don't work correctly (and maybe never have). See https://github.com/Automattic/woocommerce-payments/issues/3776 for more details.

**Comment by frosso** [comment]
SEPA support for subscription payments will come to a later date, the solution will be revisited once SEPA becomes widely available.

It can take up to 14 business days to receive notification on the success or failure of a payment with SEPA. Woo Subscriptions' [renewal process](https://href.li/?https://woocommerce.com/document/subscriptions/renewal-process/#the-renewal-process) is designed with the assumption that payment notification is near immediate (or at least within 24 hours).

For context on this decision: paJDYF-9Ud-p2#comment-20540
