### ISSUE TITLE
Update critical testing flows documentation

### ISSUE THREAD

**Issue by FangedParakeet** [Automattic/woocommerce-payments#6206]
### Description

We need to update our documentation [here](https://github.com/Automattic/woocommerce-payments/wiki/Testing-instructions-for-critical-flows) to reflect the deferred intent implementation. Initially we will need to include instructions on how to enable the deferred intent UPE: eventually, we will need to replace the UPE instructions entirely, but this will only happen once #5028 is completed.

### Acceptance criteria

- Add critical test flow instructions to enable the deferred intent UPE.
- Add critical test flow instructions for split/deferred intent UPE.
- Add critical test flow instructions for recurring payments with SEPA Direct Debit payment method.

**Comment by FangedParakeet** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Heisenberg-63586f2ec60359001310fa6a/issues/Automattic/woocommerce-payments/6206?planning-poker) with Zenhub @mdmoore @timur27

**Comment by FangedParakeet** [comment]
I just added a few implemented checkout flows to this document [here](https://github.com/Automattic/woocommerce-payments/wiki/Testing-instructions-for-critical-flows#test-new-deferred-intent-upe), since #5770 has been completed. For now these "New UPE deferred intent" flows will have to live alongside the existing UPE flows, but as stated in the issue description, we will eventually replace the latter entirely.

**Comment by frosso** [comment]
Critical flows have been updated.
