### ISSUE TITLE
Create E2E tests for progressive onboarding

### ISSUE THREAD

**Issue by dmallory42** [Automattic/woocommerce-payments#6214]
### Description

We would like to develop a set of E2E tests covering the behaviour of the new onboarding flow. For more context and some examples based on the existing E2E tests, please see: p1683182248112819-slack-C03KTTK2YMA

### Acceptance criteria

* E2E tests covering the new onboarding flow (both normal and progressive)

**Comment by brandonwanA8C** [comment]
@dmallory42  
Love this initiative. Is the goal to run a periodical "smoke test" to monitor the E2E flow?
If so, I'd recommend that let's define a frequency & alert system to run this and generate notifications.
For example:
1) Run weekly, two major use-cases
   a) Non-PO user goes through E2E onboarding (fake data)
   b) PO eligible user goes through E2E onboarding till Payment Acceptance, then **Delete Acct** (fake data)
2) generate alerts for success & error scenarios for either

Lmk what you have in mind.

**Comment by oaratovskyi** [comment]
Progressive onboarding is covered in https://github.com/Automattic/woocommerce-payments/pull/7309
Normal one is just Stripe onboarding, we don't have tools to cover it yet, I've described it in the PR. 
Duplicating here:
> Disclaimer: End-to-end tests currently have a major limitation. They are designed to run with specific linked Stripe account ID. 
All the specs run with the pre-requirement that we already have the Stripe account set up. In these conditions it is hard to fully test the onboarding because it would require:
> - unlinking the account before tests / not linking it at all, then running onboarding tests at first specs
> - being able to unlink account (created with tests) from the website = having self-serve deletion tool
> - being able to link account (that has everything set up) from the website to continue tests

> Considering all these steps, I decided to start with something simpler, such as checking whether new flow is shown to the merchant when Progressive Onboarding and Force the WCPay plugin to act as disconnected flags are checked in Dev tools. With these flags enabled **all redirects to Stripe lead us back to** `payments/connect`.

> That's why the Stripe part of Progressive Onboarding (and normal one) **must** be covered by critical flows that are manually run by GlobalStep. They cover normal part now. Even more, PO part should be run in Dev mode because we have a limit of 800 accounts per month in a live Stripe account.
