### ISSUE TITLE
Migrate Simple and Straightforward Requests to a Generic Request Class

### ISSUE THREAD

**Issue by zmaglica** [Automattic/woocommerce-payments#6217]
### Description
 As part of the request classes migration, we need to migrate a set of requests that are relatively simple and straightforward to a generic request class to reduce code duplication and improve code organization.

Here is the breakdown of the tasks:

- Analyze the simple and straightforward requests and determine the best approach for migrating them to a generic request class.
- Implement a generic request class that can handle the identified requests.
- Update the relevant code to use the new generic request class.
- Test the functionality of the requests after the migration.
### Acceptance criteria

- All simple and straightforward requests are successfully migrated to the new generic request class.
- The code is properly refactored to use the new generic request class, with no code duplication.

### Testing instructions

- Use manual testing to verify that all simple and straightforward requests are working as expected after the migration.
- Make sure that all unit tests are passing.

**Comment by naman03malhotra** [comment]
@zmaglica are we planning to merge this for 6.1?
