### ISSUE TITLE
EPIC – Simplify deposits: critical flows refresh & add/improve e2e tests as needed

### ISSUE THREAD

**Issue by haszari** [Automattic/woocommerce-payments#6222]
## Overview
We've changed the UI and flows for deposits recently. Also, the [critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Critical-flows) relating to deposits might need a refresh.

The goals of this epic are:

- Holistically review the deposits UI and document the flows (as bullet points). Note this should cover all deposits UI, not just changes from recent project.
- Determine which flows are critical and update critical flows & testing instructions accordingly.
- Review e2e test coverage and ensure we have up-to-date, robust tests for critical flows (as a minimum).

**Comment by haszari** [comment]
> Holistically review the deposits UI and document the flows (as bullet points). Note this should cover all deposits UI, not just changes from recent project.

Assigning to @brucealdridge who is in progress on first step (above) – reviewing current deposits flows and making a list.

**Comment by haszari** [comment]
Marking this as 0 SP as it's an epic. After the audit we can log issues for the follow up work and estimate.

**Comment by brucealdridge** [comment]
Marking as closed. This Epic is no longer part of any active project and we are considering the best course of action to handle moving this relevant issues forward.
