### ISSUE TITLE
Clean up old (?) experiment code in deposits list 

### ISSUE THREAD

**Issue by haszari** [Automattic/woocommerce-payments#6224]
### Describe the bug
In 2021 there was an empty state AB experiment in the deposits list.

- #1963

There is still code to show a control & treatment view, I suspect this code is no longer needed.

Experiment name is `wcpay_empty_state_preview_mode`.

If not needed would be good to tidy this up.

**Comment by vbelolapotkov** [comment]
@haszari is it a bug? I agree it's tech debt though, so removing bug label.

**Comment by nagpai** [comment]
* I checked the files within the PR 
https://github.com/Automattic/woocommerce-payments/pull/1963
and found that all the changees added in that PR were no longer in the `develop` branch
* Other than the PR above there was one more PR that brought in changes related to the test
[https://github.com/Automattic/woocommerce-payments/pull/2557](https://github.com/Automattic/woocommerce-payments/pull/2557/)
* I found a PR where most things were cleaned up 
https://github.com/Automattic/woocommerce-payments/pull/7045/files#diff-3863b4f88d0515e080fadc56af3c5e38e942afb96e569cb000ae6a594e8bea4a

* On searching for the experiment name - `wcpay_empty_state_preview_mode` , I did come across a [function ](https://github.com/Automattic/woocommerce-payments/blob/ba1678e9d4850cf9cf4b3150363dc485acd484c0/includes/admin/class-wc-payments-admin.php#L291) in `WC_Payments_Admin`, that was related to the experiment and needs to be removed. 

* On the earlier PR where the function was introduced there were some CSS changes added for the test. I have removed them as well. 

I hope I am not missing anything @haszari ?

**Comment by haszari** [comment]
Nice work @nagpai  – sounds good to me! And glad to hear that this was mostly already handled :)
