### ISSUE TITLE
Test Compatibility with Stripe Extension and Subs

### ISSUE THREAD

**Issue by allendav** [Automattic/woocommerce-payments#623]
Some merchants will want to use WooCommerce Payments at the same time as the Stripe extension - for subscriptions. We should make sure this combo works (WCPay, Stripe and Subs) for recurring and non-recurring payments.

**Comment by vbelolapotkov** [comment]
@Automattic/helix could you please check if this one is still relevant today? My gut feeling says it could be closed but would be nice to double-check.

**Comment by james-allan** [comment]
I believe the two work together just fine. I'll double check and report back.

**Comment by james-allan** [comment]
The scenarios I tested just related to Brent's comment above. 

- [x] WC Pay, Stripe, Subscriptions plugins active. **Stripe gateway enabled.**
    - [x] _WC Pay subscription purchase and renewal_
    - [x] _Stripe subscription purchase and renewal_
- [x] WC Pay, Stripe, Subscriptions active. **Stripe gateway disabled - existing subscriptions only.**
    - [x] _WC Pay subscription purchase and renewal_
    - [x] _Stripe subscription renewal only_

With that in mind and @vbelolapotkov's instinct above, I'll close this now.
