### ISSUE TITLE
Error message shows up on checkout page when merchant uses Icelandic Króna with decimals

### ISSUE THREAD

**Issue by hsingyuc** [Automattic/woocommerce-payments#6232]
### Describe the bug
Stripe doesn’t allow decimals with Icelandic Króna.  The error handling shows `We’re not able to process this request. Please refresh the page and try again.` on the checkout page, which doesn't help shoppers check out and Merchant isn't aware of the error.

I suggest we show an error notice in the settings when the merchant uses Icelandic Króna with decimals.

### To Reproduce
1. Go to WC settings -> General
2. Set currency to Icelandic Króna and Number of decimals to 2
3. Checkout as a shopper
4. See error `We’re not able to process this request. Please refresh the page and try again.` on the checkout page

### Actual behavior
The above error message shows up on the checkout page when the merchant uses Icelandic Króna with decimals.

### Expected behavior
Don't show the error message on the checkout page but show on the setting's page.

**Comment by jessy-p** [comment]
According to Pc2DNy-3z-p2, this falls in Sigma @dwainm. Tagging as a part of Gamma Porter duties PcreKM-yM-p2.
