### ISSUE TITLE
Spike: Speed up capture terminal payment endpoint

### ISSUE THREAD

**Issue by anu-rock** [Automattic/woocommerce-payments#6239]
### Description

The `capture_terminal_payment` endpoint may take a few seconds to complete. Above 5-second response times have been observed in mobile app performance testing. There may be a few optimization opportunities. This spike is to explore them.

### Dev notes

See pdfdoF-2Kh-p2#comment-4059 for a list of potentially expensive operations.

### Additional context

Original thread - pdfdoF-2Kh-p2

**Comment by anu-rock** [comment]
Initial results of this spike posted at pdfdoF-2Kh-p2#comment-4118, thanks to @elazzabi

**Comment by elazzabi** [comment]
The results of this spike were already shared and we started acting upon it. Closing this issue.
