### ISSUE TITLE
Customizing the transactions list : Acoweb's Deposits & partial payments

### ISSUE THREAD

**Issue by d-damien** [Automattic/woocommerce-payments#6266]
### Description
Hello. [Acoweb's Deposits & partial payments](https://fr.wordpress.org/plugins/deposits-partial-payments-for-woocommerce) is an extension that enables shop owners to split payments. For this purpose, it creates "sub-orders" that inherit Woocommerce orders, each having their transaction : a `WC_Order` may have several `AWCDP_Order`.

Our issue appears in the list of transactions : the ones that belong to a `AWCDP_Order` don't show the original order ID, name nor email of the customer.

Hence our request : how does one customize the transactions list ?

### Acceptance criteria
Give a way in PHP to :

* Show parent order ID (the `post_parent` column of `wp_posts` table)
* Show the client's name and email

### Designs
Is it feasible to add a hook without having an "n+1 queries" problem ? Or maybe a hook that just replaces the full query ?

### Testing instructions
Install Woocommerce, Woocommerce Payments & Acoweb's Depoits. Configure it with eg. two 50% payments.  Order something and pay the first half. Check that, in `Payments > Transactions`, these 3 columns are missing.

Regards

**Comment by nxmndr** [comment]
In the meantime, here's the query I've used to export data from partial payments (I'm still not quite sure this is the same data that transactions use). Most of it is here, it's only missing about 20 early fees and some names (on 140 records so far), and about 30€ on 12k€, but overall it seems correct. Use `select sum(total)-sum(fee) ...` on the whole query to check.

```
global $wpdb;
$data = $wpdb->get_results("
    SELECT ID, post_date, post_parent as order_id,
        m1.meta_value as email,
        m2.meta_value as first_name,
        m3.meta_value as last_name,
        m4.meta_value as total,
        m5.meta_value as fee
    FROM $wpdb->posts
    LEFT JOIN $wpdb->postmeta as m1 on m1.post_id = ID and m1.meta_key = '_billing_email'
    LEFT JOIN $wpdb->postmeta as m2 on m2.post_id = ID and m2.meta_key = '_billing_first_name'
    LEFT JOIN $wpdb->postmeta as m3 on m3.post_id = ID and m3.meta_key = '_billing_last_name'
    LEFT JOIN $wpdb->postmeta as m4 on m4.post_id = ID and m4.meta_key = '_order_total'
    LEFT JOIN $wpdb->postmeta as m5 on m5.post_id = ID and m5.meta_key = '_wcpay_transaction_fee'

    WHERE post_type in ('awcdp_payment', 'shop_order_refund') AND post_status = 'wc-completed'
    HAVING total != 0.00
    ORDER BY order_id DESC
", ARRAY_A);
```

**Comment by jessy-p** [comment]
This issue impacts Transactions (Auth and Capture), so assigning to Pulsar (based on team responsibilities Pc2DNy-3z-p2) @kalessil. Assigning as part of Gamma Triage process PcreKM-yM-p2.

Tagging as part of re-evaluating older issues in the backlog, please have a look and close if no longer relevant.

**Comment by kalessil** [comment]
Adding this request to the review queue of our product folks: I have no clue how fast this will be investigated, hence closing the issue, and we'll reopen it once we have feedback. But keeping fingers crossed as the extension you reference has a great rating!
