### ISSUE TITLE
Extract duplicate payments prevention functionality into a new service

### ISSUE THREAD

**Issue by RadoslavGeorgiev** [Automattic/woocommerce-payments#6285]
During the duplicate payment prevention project, we added some code straight to main the gateway class in the following PRs: 
https://github.com/Automattic/woocommerce-payments/pull/5247 and https://github.com/Automattic/woocommerce-payments/pull/5346.

This code should be extracted into a separate and independent service instead of residing within the gateway.

Here is an example service that was created during one of the spikes for the new payment process:
💡  [includes/payment/class-duplicate-payment-prevention-service.php](https://github.com/Automattic/woocommerce-payments/blob/61544ea96850a56abc7f428c769a338a32f840bf/includes/payment/class-duplicate-payment-prevention-service.php)

The service should be coded in a way, which performs all necessary functionality without actually being dependent/specific to the payment process. Here are some examples how the service could be used:

1. [Store the currently processing order in session.](https://github.com/Automattic/woocommerce-payments/blob/61544ea96850a56abc7f428c769a338a32f840bf/includes/payment/state/class-prepared-state.php#L109)
2. [Check for an existing similar order.](https://github.com/Automattic/woocommerce-payments/blob/61544ea96850a56abc7f428c769a338a32f840bf/includes/payment/state/class-prepared-state.php#L121C45-L124)
3. [Prepare an existing intent.](https://github.com/Automattic/woocommerce-payments/blob/61544ea96850a56abc7f428c769a338a32f840bf/includes/payment/state/class-prepared-state.php#L137-L143C11)

**Comment by naman03malhotra** [comment]
Estimated dev complete date: 29th
Estimated completion date: June 2nd (Given quick reviews)

**Comment by RadoslavGeorgiev** [comment]
Sorry, project planning took longer than expected today. https://github.com/Automattic/woocommerce-payments/pull/6421 now contains extracted functionality, and working tests, but some further testing might be needed. I'll add details in https://github.com/Automattic/woocommerce-payments-meta/issues/158.
