### ISSUE TITLE
Update to remove all mentions of Prototype from PO code

### ISSUE THREAD

**Issue by dmallory42** [Automattic/woocommerce-payments#6298]
### Description

We currently use the word `Prototype` in a few places relating to Progressive Onboarding, a hangover from the Prototype code. We should do a sweep of the code to ensure we're using the correct terminology in all places.

### Acceptance criteria

* Titles and references to PO are up to date and don't mention the prototype.

**Comment by daquinons** [comment]
In this issue, we are going to be covering the user-facing aspects, such as the title and the URL.

We'll be making a deeper refactor, of this prototype reference and also the expired onboarding experiment in this follow-up https://github.com/Automattic/woocommerce-payments/issues/6333
