### ISSUE TITLE
Misleading statement descriptor for profile page business URLs

### ISSUE THREAD

**Issue by dechov** [Automattic/woocommerce-payments#630]
If the business URL submitted in the KYC flow has a generic domain name, such as a social media profile page – which (with or without e-commerce features) some set of businesses could start with as a primary web destination – the domain will be used as the default statement descriptor.

This is unhelpful and/or misleading, so we should possibly set a different default in this case, or at least allow the merchant to change it (see https://github.com/Automattic/woocommerce-payments/issues/407).

**Comment by jessy-p** [comment]
This is now addressed as merchant can edit this from Payments -> Settings -> Transactions and Deposits

![image.png](https://images.zenhubusercontent.com/607f1d1a52a3081b859b1066/df974347-d042-48ef-bae3-a2ee96739b55)

**Comment by jessy-p** [comment]
Closed by https://github.com/Automattic/woocommerce-payments/pull/788
