### ISSUE TITLE
Subscription status changes and other features on staging sites impact the live site

### ISSUE THREAD

**Issue by james-allan** [Automattic/woocommerce-payments#6316]
### Describe the bug

When a store is in [staging mode](https://woocommerce.com/document/subscriptions-handles-staging-sites/), subscription status changes are sent to WC Pay servers. This typically results in:

- the subscription being put on-hold during the renewal process on the staging site. 
    - this is because the subscription is manual on the staging site so a renewal order is created and the subscription goes on-hold during the renewal process.
- as a result the Stripe billing subscription is put on hold (paused).
- the live site still thinks the subscription is active and so awaits renewal order webhooks, but they never get sent. 

> **Warning**
> **This is the most likely cause of inexplicably paused subscriptions**

What's more, other Stripe billing related requests are also sent from staging sites which may have some impact the live site. For example, Stripe billing product related requests. Product updates and deletes on a staging site propagate to the WC Pay live Stripe account and so could impact the live site.

> **Note**
> Product price changes don't have any impact because subscription prices are taken from the order and subscription at the time of purchase.

### To Reproduce

1. Purchase a subscription using WC Pay subscriptions (Stripe billing)
2. Mimic your site being in staging mode: 
   - alter your `wc_subscriptions_siteurl` option. eg add an extra character so it no longer matches your site URL.
3. Go to **Tools > Scheduled Actions**
4. Search for the subscription ID. 
5. Run the scheduled payment action for the subscription
6. Go to the edit subscription screen for the subscription you purchased note that the subscription is on-hold and there's a pending renewal order.
7. Find the subscription in your Stripe dashboard and notice the it is paused. 

![image](https://github.com/Automattic/woocommerce-payments/assets/8490476/77235a13-0142-499e-be8a-79917693a0c7)

### Actual behavior

Stripe billing requests related to WCPay 

### Expected behavior

Staging sites shouldn't impact live data like this. It's common for agencies, or developers to set up duplicate sites for their customers to enable them to test things on. For a staging site to be communicating with the live WCPay account and for it to impact the live account is not intended. 

We need to work out what the experience is for staging sites. Is stripe billing functionality completely disabled, do we just act as if these stripe billing subscriptions are tokenised wc pay subscriptions?

In the end, staging sites shouldn't be communicating with the live site in any way.

**Comment by thenbrent** [comment]
Noting this is closely related, and potentially the cause, of #4547.

**Comment by zmaglica** [comment]
According to Pc2DNy-3z-p2, this falls in Helix @haszari . Tagging as a part of Gamma Porter duties PcreKM-yM-p2.

**Comment by csmcneill** [comment]
Adding the `priority: high` label given the impact this may have on #6316 _and_ how it might impact other issues.
