### ISSUE TITLE
Remove review references from Fraud & Risk tour

### ISSUE THREAD

**Issue by eduardoumpierre** [Automattic/woocommerce-payments#6324]
### Description

The Fraud & Risk tour copies need to be updated to remove the references from "review any flagged transactions".

### Additional context

- p1683905170267169/1683880868.493449-slack-C04109UAJH5

**Comment by zmaglica** [comment]
According to Pc2DNy-3z-p2, this falls in Sigma @dwainm . Tagging as a part of Gamma Porter duties PcreKM-yM-p2.

**Comment by eduardoumpierre** [comment]
Hi @zmaglica! This issue is related to the Fraud & Risk project worked on by Sigma which is one of the team's responsibilities. It's described as "Risk & Fraud" on the page that you shared.

**Comment by zmaglica** [comment]
Oh. Thank you for your comment. I will update the comment.

**Comment by dwainm** [comment]
@eduardoumpierre we missed an opportunity to do this for 6.0.0.

**Comment by dwainm** [comment]
I'll add it to the backlog for Sprint 5.

**Comment by eduardoumpierre** [comment]
@dwainm This was resolved on https://github.com/Automattic/woocommerce-payments/pull/6328. I added a comment to our release tracker post but forgot to add it to the 6.0.0 release post. I think we can close this one.

**Comment by dwainm** [comment]
Perfect, thanks for the update, closing this one.
