### ISSUE TITLE
Incorrect text in Multi-Currency onboarding wizard related to currency switcher in cart widget

### ISSUE THREAD

**Issue by jessepearson** [Automattic/woocommerce-payments#6335]
### Describe the bug
The text in the screenshot is wrong. Initially the currency switcher was supposed to be added to the cart widget, however, this never worked. We decided to add it to the Storefront breadcrumb bar, this is what is on the MC settings page:

> Add a currency switcher to the Storefront theme on breadcrumb section.

![Screenshot 2023-05-19 at 9 49 13 AM](https://github.com/Automattic/woocommerce-payments/assets/4634416/134b224f-aa62-4e4f-8d7f-132718c9e1fa)

### To Reproduce

1. You need to update the option `wcpay_multi_currency_setup_completed` in the database to `no`: `wp option update wcpay_multi_currency_setup_completed no`
2. Go to Payments > Overview, scroll down and look for the note with the title "Sell worldwide in multiple currencies"
3. Click the "Set up now" button.
4. On the next page choose a currency and add it to get to step 2.
5. You will now see what is in the above screenshot.

**Comment by zmaglica** [comment]
This issue impacts Multi-Currency, so assigning to Sigma team (based on team responsibilities) @dwainm . Assigning as part of the Gamma Triage process.
