### ISSUE TITLE
Develop the schema for deposits API endpoint

### ISSUE THREAD

**Issue by zmaglica** [Automattic/woocommerce-payments#6337]
### Description

In order to enhance the data reporting, we need to create a new endpoint or modify the existing "deposit" endpoint, and define the corresponding schema. Before we start with the endpoints, we need to define the schema first.

The "deposit" endpoint schema should have the following properties:

- Timestamp (`datetime`): The date and time when the deposit is estimated or created.
- Deposit ID (`string`): A unique identifier for the deposit. This field may be absent if the deposit status is "estimated".
- Deposit status (`string`): The status of the deposit, which can be "estimated," "pending," "in-transit," "paid," "failed," or "cancelled".
- Deposit arrival date (`datetime`): The date and time when the deposit is expected to reach the merchant's bank account.
- Deposit type (`string`): The type of deposit, which can be "Deposit" or "Withdrawal" from the merchant's bank account.
- Deposit schedule:
  - Type (`string`): Specifies whether the deposit schedule is "automatic" or "manual". (To be implemented in Q4 CY23)
  - Schedule (`string`): This field is blank for "manual" deposits. For "automatic" deposits, it can be set to "daily," "weekly," or "monthly".
  - Anchor (`string`): This field is blank for "manual" deposits and for "automatic" deposits with a "daily" schedule. For "automatic" deposits with a "weekly" schedule, it represents a day of the week (e.g., Wed). For "automatic" deposits with a "monthly" schedule, it represents a day number of the month (e.g., 15).
- Deposit speed (`string`): Indicates the speed of the deposit, which can be "standard" (typically takes a few business days) or "instant" (the deposit can reach the bank account in under 30 minutes).
- Amount (`number`): The amount in the merchant's deposit currency. This currency is also used for the merchant's bank account. The amount is negative for "Withdrawal" deposits.
- Deposit account:
  - Type (`string`): Specifies whether the deposit account is a "bank account" or a "card".
  - ID (`string`): A unique identifier for the bank account or card.

Please note that the provided property types are based on the current requirements. However, they can be adjusted if necessary to better suit the implementation needs.

### Acceptance Criteria

- Ensure a clear understanding of the existing endpoints for getting the deposits.
- Implement the "deposit" schema.
- Thoroughly document the "deposit" schema once it is completed.

### Designs

Not needed.

### Testing Instructions

Ensure that the implemented schema matches the defined properties for the "deposit" endpoint.

### Additional Information

pcreKM-1Hp-p2

For more information on WordPress REST API schema documents, please refer to the [Schema Documents](https://developer.wordpress.org/rest-api/extending-the-rest-api/schema/#schema-documents) in the WordPress Developer Handbook.

**Comment by haszari** [comment]
Closing as stale task from previous project, see https://github.com/Automattic/woocommerce-payments/issues/6341#issuecomment-2111523453
