### ISSUE TITLE
Develop the schema for disputes API endpoint

### ISSUE THREAD

**Issue by zmaglica** [Automattic/woocommerce-payments#6338]
### Description

The purpose of this issue is to create a schema for the "disputes" endpoint, which will be used to manage dispute-related information for data reporting. The schema should be designed to accommodate the following properties:

- Timestamp (`datetime`): The date and time when the dispute is created.
- Dispute ID (`string`): A unique identifier for the dispute.
- Dispute status (`string`): The status of the dispute, which can be one of the following:
  - `inquiry:needs response`
  - `inquiry:under review`
  - `inquiry:closed`
  - `needs response`
  - `under review`
  - `charge refunded`
  - `won`
  - `lost`
- Dispute action (`string`): The action taken for the dispute, which can be one of the following:
  - `challenge`
  - `accept`
  - `no response`
- Transaction ID (`string`): A unique identifier for the charge that is being disputed.
- Evidence due by (`datetime`): The date and time by which the dispute needs to be responded to.
- Dispute type (`string`): The type of dispute, such as "Fraudulent," "Product not received," "Product not as described," etc.
- Payment method:
  - Type (`string`): Specifies whether the payment method used was a card (Visa, Mastercard, etc.) or an Alternative Payment Method (APM) or Local Payment Method (LPM) (iDEAL, Apple Pay, Google Pay, etc.).
  - ID (`string`): The payment method ID used to create the transaction type.
- Evidence sent on (`datetime`): The date and time when the dispute was responded to, either by challenging with evidence or accepting.
- Finalized on (`datetime`): The date and time when the outcome of the dispute is finalized. This field is `null` if the dispute is still in progress.
- Risk level (`string`): The transaction risk level, usually received from the underlying processor (e.g., Stripe).
- Order ID (`string`): The identifier of the WooCommerce order associated with this transaction.
- Email (`string`): The customer's email ID.
- Country (`string`): The country of the customer's address.

Please note that the provided property types are based on the current requirements. However, they can be adjusted if necessary to better suit the implementation needs.

### Acceptance Criteria

- Understand the purpose and requirements of the "disputes" endpoint.
- Design a schema that encompasses the defined properties for the endpoint.
- Implement the schema with the appropriate type hints for schema validation.
- Thoroughly document the "disputes" schema once it is completed.

### Designs

Not needed.

### Testing Instructions

Ensure that the implemented schema aligns with the defined properties for the "disputes" endpoint.

### Additional Information

pcreKM-1Hp-p2

For more information on creating schemas for WordPress REST API endpoints, please refer to the relevant documentation in the [WordPress Developer Handbook](https://developer.wordpress.org/rest-api/extending-the-rest-api/schema/#schema-documents).

**Comment by haszari** [comment]
Closing as stale task from previous project, see https://github.com/Automattic/woocommerce-payments/issues/6341#issuecomment-2111523453
