### ISSUE TITLE
Incorrect branding of "Woo Payments" and "WooPayments" in use

### ISSUE THREAD

**Issue by jessepearson** [Automattic/woocommerce-payments#6339]
### Describe the bug
Incorrect branding of "Woo Payments" and "WooPayments" in use, found this while testing other things. I noticed "WooPayments" in use, so I did a search across the code for both "Woo Payments" and "WooPayments" and found both in several places, both in text and images.

According to P2 and Slack conversations, this change is upcoming and should not happen for another month:
p1684500901771419-slack-CGGCLBN58
paqDfi-5TY-p2#comment-15838

### To Reproduce

1. Do a text search of both "Woo Payments" and "WooPayments" via your code editor.

**Comment by jessepearson** [comment]
Noting that I did not directly reference where I found these instances due to their location may change, others may be added, etc.

**Comment by zmaglica** [comment]
This issue impacts WooPay, so assigning to Heisenberg team (based on team responsibilities) @bborman22. Assigning as part of the Gamma Triage process.

**Comment by zmaglica** [comment]
paJDYF-7Sw-p2#comment-18316

**Comment by oaratovskyi** [comment]
Fixed in #6766
