### ISSUE TITLE
Create/update API endpoint for retrieving a filtered list of deposits

### ISSUE THREAD

**Issue by zmaglica** [Automattic/woocommerce-payments#6340]
### Description
Review the existing API endpoint for retrieving deposits to determine if it meets the schema requirements for data reporting while maintaining backward compatibility. If the existing endpoint is sufficient, modify it to include the ability to retrieve a filtered list of deposits based on the provided parameters. If the existing endpoint does not meet the schema requirements, create a new API endpoint to fulfill the data reporting needs.

### Parameters
- `timestamp` (datetime): Filter deposits based on timestamp. Acceptable values are "on", "before", "after", or "between".
- `deposit_status`: Filter deposits based on their status.
- `deposit_schedule`: Filter deposits based on their schedule. This parameter will be blank for manual deposits. For automatic deposits, acceptable values are "daily", "weekly", or "monthly".
- `type`: Filter deposits based on their type. Acceptable values are "automatic" or "manual". Please note that the "manual" type will be available in Q4 of CY23.
- `deposit_id`: Filter deposits based on their unique deposit ID.
- `pagination`: Standard pagination.

### Schema
The request schema for the API endpoint should follow the specifications outlined in the following GitHub issue: [#6337](https://github.com/Automattic/woocommerce-payments/issues/6337). Please refer to the schema provided in the issue and incorporate it into the API endpoint implementation. Make sure that the schema is defined before you start to work on the issue.

### Response
The API endpoint should return a list of deposits that match the specified filters. Each deposit should include relevant information such as deposit ID, timestamp, status, schedule, and type.

### Note
Please ensure that the API endpoint implementation adheres to RESTful design principles and follows proper error handling practices. If the existing endpoint is sufficient, modify it to accommodate the new requirements. If it is not sufficient, create a new API endpoint to fulfill the data reporting needs.

**Comment by haszari** [comment]
Closing as stale task from previous project, see https://github.com/Automattic/woocommerce-payments/issues/6341#issuecomment-2111523453
