### ISSUE TITLE
Create/update API endpoint for retrieving disputes

### ISSUE THREAD

**Issue by zmaglica** [Automattic/woocommerce-payments#6341]
### Description
Please review the existing API endpoint for retrieving disputes to determine if it meets the schema requirements for data reporting while maintaining backward compatibility. If the existing endpoint is sufficient, modify it to include the ability to retrieve disputes based on the provided parameters. If the existing endpoint does not meet the schema requirements, create a new API endpoint to fulfill the data reporting needs.

### Parameters
- `timestamp` (datetime): Filter disputes based on timestamp. Acceptable values are "on", "before", "after", or "between".
- `dispute_status`: Filter disputes based on their status.
- `dispute_action`: Filter disputes based on the action taken.
- `dispute_type`: Filter disputes based on the type of dispute.
- `single_dispute`: Retrieve a single dispute based on its unique dispute ID.
- `dispute_id`: Filter disputes based on their unique dispute ID.
- `pagination`: Standard pagination.

### Request Schema
The request schema for the API endpoint should follow the specifications outlined in the following GitHub issue: [#6338](https://github.com/Automattic/woocommerce-payments/issues/6338). Please refer to the schema provided in the issue and incorporate it into the API endpoint implementation.

### Response
The API endpoint should return a list of disputes that match the specified filters. Each dispute should include relevant information such as dispute ID, timestamp, status, action, transaction ID, evidence due date, dispute type, payment method details, evidence response date, finalization date, risk level, order ID, customer email, and country.

### Note
Please ensure that the API endpoint implementation adheres to RESTful design principles and follows proper error handling practices. If the existing endpoint is sufficient, modify it to accommodate the new requirements. If it is not sufficient, create a new API endpoint to fulfill the dispute retrieval needs.

**Comment by haszari** [comment]
@zmaglica – this looks like a stale task issue from a previous reporting project. I'm going to close, as there's no specific actionable bug. 

Please comment with details if we should keep open as bug or add to product roadmap as an idea/enhancement. Also closing these other related task issues:

- #6338
- #6337
- #6340
