### ISSUE TITLE
Create API endpoint for retrieving filtered list of transactions

### ISSUE THREAD

**Issue by zmaglica** [Automattic/woocommerce-payments#6342]
### Description
Review the existing API endpoint for retrieving transactions to determine if it meets the schema requirements for data reporting while maintaining backward compatibility. If the existing endpoint is sufficient, modify it to include the ability to retrieve a filtered list of transactions based on the provided parameters. If the existing endpoint does not meet the requirements, create a new API endpoint to fulfill the transaction retrieval needs.

The following endpoint need to be checked/added:

[Captures](https://href.li/?https://github.com/Automattic/woocommerce-payments/commit/a3fabba4aff238cb4a0752fb5dd60432db3727dd#diff-f5ce5009262d1356eb28b2a0e36b3473d8bb278e2b61534579520ca7c4918ee3) – includes/core/server/request/class-list-transactions.md

## Filtering Parameters
- `date_before` (string, optional): Filters transactions that took place before this specified date. The date format should be in 'date-time'.
- `date_after` (string, optional): Filters transactions that happened after this particular date. The date format should be in 'date-time'.
- `date_between` (array): Allows you to filter transactions that occurred between specific dates.
- `order_id` (integer, optional): Filters transactions by their associated order ID.
- `deposit_id` (string, optional): Enables transaction filtering based on the linked deposit ID.
- `email` (string, optional): Filters transactions according to the customer's email.
- `payment_method_id` (string, optional): This parameter is for filtering transactions based on the payment method used.
- `type` (string, optional): Filters transactions where the type matches a specified value.
- `transaction_id` (string, optional): Filters transactions based on their unique transaction ID.
- `source_id` (string, optional): Filters transactions using their unique source ID.
- `match` (string, optional): A match filter for transactions.
- `search` (array, optional): A search parameter for transactions.
- `user_timezone` (string, optional): Incorporates the timezone into date filtering.
- `orderby` (string, optional): Sorts transactions based on the specified field. By default, it's sorted by 'date'.
- `order` (string, optional): Orders transactions based on the given field. By default, it's in descending ('desc') order. It can be either 'asc' (ascending) or 'desc' (descending).
- `page` (integer, optional): Indicates the page number. By default, it's set to 1, with a minimum limit of 1.
- `per_page` (integer, optional): Specifies the page size. By default, it's set to 25, with a minimum limit of 1 and a maximum limit of 100.

## Request Schema
The request schema for the API endpoint should follow the specifications outlined in the following GitHub issue: [#6336](https://github.com/Automattic/woocommerce-payments/issues/6336). Please refer to the schema provided in the issue and incorporate it into the API endpoint implementation.

## Response
The API endpoint should return a list of transactions that match the specified filters. Each transaction should include relevant information such as transaction ID, timestamp, type, order ID, deposit ID, customer email, payment method details, and transaction details.

## Note
Please ensure that the API endpoint implementation adheres to RESTful design principles and follows proper error handling practices. If the existing endpoint is sufficient, modify it to accommodate the new requirements. If it is not sufficient, create a new API endpoint to fulfill the transaction retrieval needs.

**Comment by jessy-p** [comment]
Add tests
