### ISSUE TITLE
Epic: WCPay Disputes – Optimise disputes list view

### ISSUE THREAD

**Issue by haszari** [Automattic/woocommerce-payments#6355]
### Description
The goal of this epic is to make it easier to manage and respond to disputes from the disputes list view. 

<img width="977" alt="Screenshot 2023-05-23 at 1 08 59 PM" src="https://github.com/Automattic/woocommerce-payments/assets/4167300/adecaa47-8f46-42d0-92d6-b0e23996ebb1">

![dispute-list-1](https://github.com/Automattic/woocommerce-payments/assets/3147296/98ed7541-c8d3-44f4-b598-61cee8bd212b)

Note – the above screenshot shows some other future improvements not scoped to this project. 

### Steps
- [x] #6661
- [x] #6667
- [x] #6702
- [x] #6722
- [x] #6692
- [x] Add Changelog entry for this epic's changes https://github.com/Automattic/woocommerce-payments/pull/6754
    - Remove/replace changelog entry for #6723 – `changelog/fix-6722-dispute-list-status-chip-colours`
- [x] Tracks / tracking
  - [x] #6747
- [x] Add testing instructions to this description for impacted flows

The above is a high-level summary of the changes in the design. These can be split off as separate issues. Can add / adapt if details change.

### Additional context (internal links)
- Discussion about 72h urgency criteria: p1688655548302669-slack-C03LA109BKM

## Testing flows

* Visit the Disputes listing page, Payments > Disputes
* Hide `Disputed on` column
	* Ensure that the `Disputed on` column is not visible.
	* Download the csv and see that the results are unchanged.
	* Ensure the `Disputed On` column can be enabled by using the options menu.
* `Action` column
	* See active disputes with `Respond` button.
	* Change filter from `Needs Response` to `All Disputes`.
	* See historical disputes with `See details` link in action column.
* `Response date` column
	* When due date is <= 72 hours from now, value is highlighted red with an icon and the text `N days left`
	* When due date is <= 24 hours from now, value is highlighted red with an icon and with the text `Last day today`
	* When due date is > 72 hours from now, value is a formatted date without highlighting.
* Status chip colours.
	* Ensure the status chip colours match the following criteria
		* red = needs response within 72h
		* yellow = needs response > 72h
		* green = won
		* blue = in progress / under review
		* grey = lost

**Comment by haszari** [comment]
Need to confirm the sorting of the table – assuming sorting by `respond by` i.e. most urgent at top.

**Comment by Jinksi** [comment]
Reopening to ensure last 2 tasks are completed before closing.

**Comment by Jinksi** [comment]
All tasks complete.
