### ISSUE TITLE
IPP: Speed up capture terminal payment endpoint

### ISSUE THREAD

**Issue by elazzabi** [Automattic/woocommerce-payments#6358]
This is a follow-up to the spike #6239

After running a few tests on the `capture_terminal_payment` function, we've seen that it can be improved by passing information to the `capture_charge` function instead of resending a new HTTP function to Stripe.

This issue is to keep track of this useful change and to implement it in the future.

**Comment by zmaglica** [comment]
This issue impacts In-Person Payments, so assigning to Fusion (based on team responsibilities) @anu-rock  . Assigning as part of Gamma Triage process.

**Comment by anu-rock** [comment]
Thanks, @zmaglica. Moved it to Fusion's product backlog to keep track of it.

**Comment by anu-rock** [comment]
We did some initial work on this recently at #6408, which reduces one redundant call to Stripe.
