### ISSUE TITLE
Adjust payments overview after recent Stripe changes

### ISSUE THREAD

**Issue by oaratovskyi** [Automattic/woocommerce-payments#6375]
### Description
The overview screen for the PO account was looking like this before recent Stripe changes p1684873002176489-slack-C051WFFE961
![image](https://github.com/Automattic/woocommerce-payments/assets/79862886/2dac9a8e-b1d4-41fe-a8e7-a3db497ace42)

But now it looks like this for progressive accounts (the same as for pending full KYC accounts)
![image](https://github.com/Automattic/woocommerce-payments/assets/79862886/2d31e0ae-397c-42e2-8d24-4a991805fb85)

We need to combine two things: use _Pending_ status chip instead of _Restricted_.

**Comment by daquinons** [comment]
Adding [this feedback](paJDYF-8Ra-p2#comment-18476)

> 6. After refresh, the Payment Overview card reverted to Restricted badge and Disabled deposits (from the lovely new Pending status.) Do you know why it would have reverted? Screenshots show immediately after completing PO KYC, and after refreshing the Payments Overview screen.
