### ISSUE TITLE
Merchants should not be able to refund disputed orders

### ISSUE THREAD

**Issue by haszari** [Automattic/woocommerce-payments#6378]
### Description
When a shopper raises a dispute, the order can be manually refunded using the refund button. 

![Screenshot 2023-05-26 at 9 10 16 AM](https://github.com/Automattic/woocommerce-payments/assets/4167300/30cbad04-2cd0-43b1-9eb9-ff55d6feab2a)

The goal of this issue is to either disable or hide the `Refund` button so the merchant can't refund orders that are in dispute (which would complicate dispute handling, as I understand it). 

> @souravdebnath1986 can you summarise the scenario in a comment (or edit description) to make the pain point clear? I realised while writing this that I don't know why it's bad to refund when disputed; assuming the merchant is only allowed to do things via dispute process (i.e. accept or challenge) – is this correct?

When a dispute is raised on an order, the funds are already taken away from the merchant and refunded to the buyer. If the merchant initiates a refund on top, it results in a second refund where the merchant is out of additional funds. Hence refund or any type of order edits should be prevented for a disputed order. The only action that the merchant can perform on the disputed order is to either accept or challenge the dispute.

### Additional context
We noticed this was a potential problem during a project to highlight and improve dispute handling. Internal project thread ref: pdjTHR-2Hv-p2

Slack discussion: p1690426678829459-slack-C03LA109BKM

Pulsar is exploring a project that allows merchants to refund from the Transaction Details screen: pdjVC1-1CM-p2

**Comment by zmaglica** [comment]
This issue impacts Disputes, so assigning to team Helix (based on team responsibilities) @haszari . Assigning as part of Gamma Triage process PcreKM-yM-p2

**Comment by zmaglica** [comment]
This issue impacts Disputes, so assigning to team Helix (based on team responsibilities) @haszari . Assigning as part of Gamma Triage process PcreKM-yM-p2

**Comment by souravdebnath1986** [comment]
> @souravdebnath1986 can you summarise the scenario in a comment (or edit description) to make the pain point clear? I realised while writing this that I don't know why it's bad to refund when disputed; assuming the merchant is only allowed to do things via dispute process (i.e. accept or challenge) – is this correct?

When a dispute is raised on an order, the funds are already taken away from the merchant and refunded to the buyer. If the merchant initiates a refund on top, it results in a second refund where the merchant is out of additional funds. Hence refund or any type of order edits should be prevented for a disputed order. The only action that the merchant can perform on the disputed order is to either accept or challenge the dispute.

**Comment by Jinksi** [comment]
I've added this slack discussion to additional context: p1690426678829459-slack-C03LA109BKM

**Comment by kalessil** [comment]
Folks, can you please keep Pulsar in the loop for the solution you are working on? We have a project starting soon (pdjVC1-1CM-p2) related to refunds.

**Comment by Jinksi** [comment]
@kalessil good to know, thanks for the ping! I'll review the project you're working on and provide an update to Pulsar 👍
