### ISSUE TITLE
Enrich "order has dispute" order note with amount, reason, and deadline

### ISSUE THREAD

**Issue by haszari** [Automattic/woocommerce-payments#6379]
### Describe the bug

WCPay adds an order note when a dispute is raised. This note doesn't have much detail.

> (old wording) Payment has been disputed as fraudulent. See <link>dispute overview</link> for more details.

![Screenshot 2023-05-26 at 1 55 42 PM](https://github.com/Automattic/woocommerce-payments/assets/4167300/a9717304-7d37-465d-8945-a4d460de37d2)

The goal of this issue is to update this note so it has relevant details, and ultimately help merchants to quickly respond to disputes.

New wording: 

> Payment has been <link>disputed for {AMOUNT} with {REASON}. Response due by {DEADLINE}</link>. (link to dispute detail)

### To Reproduce

1. Go to '…'
2. Click on '…'
3. Scroll down to …'

### Desktop (please complete the following information):

* OS: [e.g. iOS]
* Browser [e.g. chrome, safari]
* Version [e.g. 22]

### Smartphone (please complete the following information):

* Device: [e.g. iPhone6]
* OS: [e.g. iOS8.1]
* Browser [e.g. stock browser, safari]
* Version [e.g. 22]

**Comment by haszari** [comment]
Here's the code that generates the note:

https://github.com/Automattic/woocommerce-payments/blob/99de2876c4bd5335d87136ddc4673db847235857/includes/class-wc-payments-order-service.php#L283-L296

Some notes for testers/engineers…

- This note is added in a webhook handler. So your test site will need to have working webhooks (e.g. available at hostname on internet, ngrok).
- The current code doesn't convert the reason into human readable. We are doing this in a few places, this code needs to do that mapping too.
- The current code doesn't supply date or amount, so we'll need to get that info (ideally from dispute not order).

**Comment by Jinksi** [comment]
@haszari is this issue part of a project epic or maintenance? I'm wondering whether this could be story-pointed.

**Comment by haszari** [comment]
> is this issue part of a project epic or maintenance? I'm wondering whether this could be story-pointed.

I have this as part of the order screen epic, so was story pointed as part of that: 

- #6354
