### ISSUE TITLE
Express Payment Method settings copy overlaps with buttons

### ISSUE THREAD

**Issue by pierorocca** [Automattic/woocommerce-payments#6384]
### Describe the bug
The express payment methods copy and the Customize/Learn More buttons overlap

### To Reproduce

Varying the browser zoom level, decreasing the viewport width, or switching to a mobile view will result in overlap on the EPM text and the Button to the right. 90% zoom is the worst on my display and browser combo.

### Actual behavior
Overlapping copy and button

### Screenshots
![image](https://github.com/Automattic/woocommerce-payments/assets/109928953/aaec952c-726e-472a-9e09-82a75040733a)

### Expected behavior
A clear delineation between the express payment method copy and the button to the right of it

### Desktop (please complete the following information):
* OS: Mac OS
* Browser Chrome

### Additional context
Through a bit of experimentation I've found that changing the button margin-left:auto to a fixed value and adding nowrap to the button class does the trick in both mobile and desktop modes. If only a margin is added the button will wrap in mobile and will make it look even worse.

**Comment by zmaglica** [comment]
I tried to replicate the issue @pierorocca with multiple zoom levels and different mobile screens both in portrait and landscape mode, and I wasn't able to reproduce the issue. Could you please tell me what resolution you are using?

**Comment by pierorocca** [comment]
Hi @zmaglica thanks for looking at this. Apologies for the delayed response, been dealing with my first COVID infection.

I'm using an Apple Studio Display at 5K. Here's a video of my view on desktop and mobile.
https://d.pr/v/y2SFaw

**Comment by pierorocca** [comment]
Adding new Figma's provided by @elizaan36 that updates the styling on desktop and that updates the responsive designs for mobile and tablet. Huge improvement!

https://www.figma.com/file/C1r0Vzxh1mhbDJJnbjHp5q/Payments-Settings?type=design&node-id=2127-78464&t=s47rWiJd7zvNotgf-0

@zmaglica I assume you'll need a separate enhancement issue for mobile/tablet?

**Comment by zmaglica** [comment]
Thank you for the video. I will move it to the prioritization column

**Comment by naman03malhotra** [comment]
@pierorocca I belive this has been fixed along with https://github.com/Automattic/woocommerce-payments/pull/6986. Please feel free to open it again. Closing for now :))
