### ISSUE TITLE
[BNPL][MVP] Post-Delivery Cleanup Task

### ISSUE THREAD

**Issue by mgascam** [Automattic/woocommerce-payments#6387]
### Description

This issue is created as a collection point for all the cleanup tasks that we need to perform once the project is delivered. The objective is to ensure that we maintain clean, efficient, and sustainable code base and environment after the project's implementation phase.

### Acceptance criteria

- [x] Remove the feature flags

Please feel free to add more tasks to this issue as they arise.

**Comment by kalessil** [comment]
@mgascam : can this issue be closed (or anything is till pending on server/client)?
