### ISSUE TITLE
Spike on effort required to integrate with WooCommerce Gutenberg Cart and Checkout Blocks

### ISSUE THREAD

**Issue by allendav** [Automattic/woocommerce-payments#639]
pbIy4N-7Y-p2

Key questions to answer
- high level description of what changes would need to be made to WCPay to support cart and checkout blocks
- rough estimate for each
- things that would need to change in the current impl of blocks to support this, if any
- any other risks to the integration

cc @thenbrent @bmccotter

**Comment by reykjalin** [comment]
Blocks support has been enabled so we can close this issue
