### ISSUE TITLE
Create self-hosted API endpoint: Balance (Transactions)

### ISSUE THREAD

**Issue by coderkevin** [Automattic/woocommerce-payments#64]
Create a new API endpoint in the self-hosted site plugin for transactions.

- [x] Create base endpoint
- [x] Create pass-through fetch request to WordPress.com endpoint
- [ ] Support pagination
- [ ] Support searching
- [ ] Ensure adequate unit testing

**Comment by vbelolapotkov** [comment]
I think it's been fully solved, so closing it, but please reopen if I'm wrong.
