### ISSUE TITLE
Epic: Integrate with WooCommerce Gutenberg Cart and Checkout Blocks

### ISSUE THREAD

**Issue by allendav** [Automattic/woocommerce-payments#640]
See #639

**Comment by haszari** [comment]
We've changed the API for registering a payment method in WooCommerce Blocks - now pass an options object (previously was a callback). 

Check this PR for more info: https://github.com/woocommerce/woocommerce-gutenberg-products-block/pull/3404

I recommend that you update the blocks integration in WCPay as soon as practical - thanks!

**Comment by thenbrent** [comment]
@haszari from the description on https://github.com/woocommerce/woocommerce-gutenberg-products-block/pull/3404, it sounds like the existing calback API is being deprecated. Is that correct? Or is it being broken?

**Comment by haszari** [comment]
> @haszari from the description on woocommerce/woocommerce-gutenberg-products-block#3404, it sounds like the existing calback API is being deprecated. Is that correct? Or is it being broken?

@thenbrent Correct, the plan is to deprecate the existing callback API. It will be backward-compatible for the time being, so not urgent to change (though should be a quick fix!). 

Note that I don't have specifics for exactly what "deprecated" means for WooCommerce Blocks JS APIs (e.g. when and how it might actually be a breaking change). These are mostly still experimental and subject to change anyway - not stable yet.

**Comment by thenbrent** [comment]
@haszari understood. Thanks for flagging it. I've opened https://github.com/Automattic/woocommerce-payments/issues/1109 to keep track of it now.

**Comment by reykjalin** [comment]
I think we can close this epic since blocks support has been live for some time
