### ISSUE TITLE
Error while buying a subscription product with multi currency enabled

### ISSUE THREAD

**Issue by naman03malhotra** [Automattic/woocommerce-payments#6401]
### Describe the bug

An error is observed while buying a subscription product with multi-currency enabled.
### To Reproduce

1. Make sure you have a subscription product listed
2. Make sure to have multi-currency enabled
3. Now, as a guest user, add that product to your cart
4. Before checkout, switch currency using the currency switcher to a different currency than store's
5. Checkout normally and you should see an error.
6. Try switching to different currencies to see different error messages

### Actual behavior
Different error messages are seen while checking out with different currencies. For instance, it returns empty for EUR, and for INR it shows "Received unknown parameters". For AUD it shows "There was a problem creating your subscription".

### Screenshots

Error 1:
![image](https://github.com/Automattic/woocommerce-payments/assets/15019298/868ecf46-ba80-4d8a-b22b-c3d0c09bea7a)
Error 2:
![image](https://github.com/Automattic/woocommerce-payments/assets/15019298/7349a0b7-5e57-410c-a48f-9298eda0d561)

Error 3:
![image](https://github.com/Automattic/woocommerce-payments/assets/15019298/57641d20-c7a4-47d3-9c11-4254a691648a)
API response for Error 3:
![image](https://github.com/Automattic/woocommerce-payments/assets/15019298/dc5cf06d-6a48-4485-84f8-554ddeff0498)

### Expected behavior
I am not sure what is the intended behavior here but it should be either smooth checkout or a meaningful error message should be displayed according to product UX.
### Desktop (please complete the following information):

* Browser: Chrome
* Version: WC Pay 5.9.0

**Comment by james-allan** [comment]
There is a known Stripe limitation with multiple currencies and wcpay subscriptions. Customers cannot mix currencies. So for example you cannot have a subscription in USD and EUR. 

I couldn't recall what the error message shown to customers says in this instance but testing locally suggests its this generic one. 

<img width="740" alt="Screenshot 2023-05-31 at 12 39 38 pm" src="https://github.com/Automattic/woocommerce-payments/assets/8490476/ff96d226-9017-47e3-81b0-15179a5d516d">

When I view the WC Payment logs, I see these corresponding entries:


```
 ERROR You cannot combine currencies on a single customer. This customer has an active subscription, subscription schedule, discount, quote, or invoice item with currency usd. (invalid_request_error)
 INFO There was a problem creating the WCPay subscription. Error: You cannot combine currencies on a single customer. This customer has an active subscription, subscription schedule, discount, quote, or invoice item with currency usd.
```

As noted in the issue description, this could be improved to be more helpful to the shopper, enabling them self serve and resolve the issue. 

Given you got 3 different error conditions, there's also likely to be other issues here.

**Comment by zmaglica** [comment]
This issue impacts Multi-Currency, so assigning to team Sigma (based on team responsibilities) @dwainm . Assigning as part of Gamma Triage process PcreKM-yM-p2

**Comment by jessepearson** [comment]
@naman03malhotra Can you confirm that this is with Subscriptions that is included with WooCommerce Payments? If so, can you enable logging under Payments > Settings > Advanced, then perform the transactions again. From there, go to WooCommerce > Status > Logs and look for the most recent WooCommerce Payments log, and copy the relevant errors here?

As James noted above, errors should only be received if the current logged in customer already has a subscription in a different currency. For instance, if your user has a subscription in USD, you cannot add new subscriptions in EUR, which is a Stripe limitation.

Additionally, are these purchases with credit cards or another payment method?

**Comment by jessepearson** [comment]
I have a feeling that the errors that occurred were due to some sort of legacy UPE issue. We have had no other reports of the issue and I am not able to replicate by following the steps above. I tried with split and legacy UPE enabled without any issues, those methods do not appear for subscriptions. I disabled the stand alone WooCommerce Subscriptions plugin to just test with WCPay Subs to confirm, and still was not able to replicate.

@naman03malhotra I am going to close this issue, but if you are still able to replicate, please reopen it with additional steps and/or logs with how to replicate.
