### ISSUE TITLE
Delay FRT popup banner to show X days after account

### ISSUE THREAD

**Issue by dwainm** [Automattic/woocommerce-payments#6405]
Only show the welcome banner X days after account creation.

The details will be confirmed.

p1685497455014429-slack-C01B8KNUYSW

**Comment by zmaglica** [comment]
This issue impacts Fraud and Risk, so assigning to team Sigma (based on team responsibilities) @dwainm . Assigning as part of Gamma Triage process PcreKM-yM-p2

**Comment by dwainm** [comment]
Closing this issue as there were no further requests for this.
