### ISSUE TITLE
New country selector in onboarding flow should only allow choose between supported countries

### ISSUE THREAD

**Issue by daquinons** [Automattic/woocommerce-payments#6406]
### Describe the bug
The new country selector should not display non-supported WCPay countries, see feedback paJDYF-8Ra-p2#comment-18477

![image](https://github.com/Automattic/woocommerce-payments/assets/2612426/de5cb204-4354-4075-8cdd-4b5c9c597134)

**Comment by vladolaru** [comment]
The list of supported countries is here: https://woocommerce.com/document/woocommerce-payments/compatibility/countries/#supported-countries

**Comment by vladolaru** [comment]
Fixed via https://github.com/Automattic/woocommerce-payments-server/pull/3457
