### ISSUE TITLE
Additional Payment Methods should not be available on Progressive Onboarding without the full KYC finished

### ISSUE THREAD

**Issue by daquinons** [Automattic/woocommerce-payments#6413]
### Describe the bug
On this feedback paJDYF-8Ra-p2, we've been asked to hide the APMs on the Settings screen when the account is not fully verified (only payments are enabled but not payouts).

**Comment by daquinons** [comment]
I've noticed that in the documentation we speak about this, so we should actually confirm if we want this to happen before working on this issue https://woocommerce.com/document/woocommerce-payments/startup-guide/gradual-signup/#additional-payment-methods

**Comment by brandonwanA8C** [comment]
@daquinons the "feedback" link didn't seem to work.
was this from the same [P2 post](https://hostedwoo.wordpress.com/2023/05/26/my-awesome-store-woo-express-experience/) that was dated on May-26?  If so, it may not be related to PO, possibly an existing/legacy issue.

**Comment by daquinons** [comment]
> @daquinons the "feedback" link didn't seem to work. was this from the same [P2 post](https://hostedwoo.wordpress.com/2023/05/26/my-awesome-store-woo-express-experience/) that was dated on May-26? If so, it may not be related to PO, possibly an existing/legacy issue.

No! It was in the Call for testing. I've fixed the link

**Comment by brandonwanA8C** [comment]
@daquinons got it, with Tempermonkey I can see the P2 now.

>I've noticed that in the documentation we speak about this, so we should actually confirm if we want this to happen before working on this issue https://woocommerce.com/document/woocommerce-payments/startup-guide/gradual-signup/#additional-payment-methods

The example in the doc: LPM (e.g. Sofort) requiring additional info is a valid case for **post-KYC** accounts.
Even with default/full KYC, Stripe may require additional data to enable certain LPMs (as a requirement from the LPM provider). 
For PO, let's:
1) either Gray out APM / LPM during PO period
2) or, if user chose to enable APM / LPM, we will send them to Full Onboarding path first (same path as "unlock deposit")

**Comment by dmallory42** [comment]
Hey @elizaan36 / @brandonwanA8C, I'd be keen to get your thoughts and also possibly would need a design for this one. 

I agree with Brandon's thought here that we need to adjust this flow for PO users.

For context, the current flow for a normal (non-PO) onboarding is as follows:

1. User finishes KYC
2. User goes to settings when they want to add an APM (e.g. Sofort)
3. If any additional requirements are needed, the user gets informed by a modal they will be sent an email by Stripe to get the details
4. The APM is set to a `pending_verification` state until the user submits any necessary additional requirements, and then it becomes active.

A PO user would need to complete the full KYC as these are minimum requirements for all APMs.

My suggestion for a PO user would be similar to Brandon's proposition above:

1. User finishes initial KYC to enter PO state.
2. User goes to settings to add an APM
3. When user tries to select an APM, they see a new modal telling them they need to provide more information before they can add APMs. This modal should have an action which takes the user to the full KYC to complete account verification.
4. After KYC the merchant would become a normal user so the workflow would be the same as above ^ 

We have a modal (screenshot below) which we show to the user after partial KYC is completed, perhaps we could either reuse or slightly adjust the wording on it for this use case?

<img width="892" alt="Screenshot 2023-07-25 at 15 07 09" src="https://github.com/Automattic/woocommerce-payments/assets/11770181/1efa020f-5bca-4f0e-98b3-88a167c9429d">

Thanks!

**Comment by elizaan36** [comment]
Could you give examples of APMs where this would be necessary, or is it all payment methods listed in WCPay settings?

**Comment by dmallory42** [comment]
For a PO account, AFAIK it would be for all APMs, because they all have a minimum subset of requirements which includes details that a PO user would not have provided yet (such as business address).

**Comment by brandonwanA8C** [comment]
@dmallory42 is correct.
With Stripe integration today, any & all APMs (including BNPL) would require Full KYC to enable them as "capabilities". 
Nudging the "PO-tagged" merchants to enable additional APM/LPM (if they need to) is also a great way to pull them out of the PO zone to full account activation.

**Comment by elizaan36** [comment]
Would this existing pattern work? In Payments Settings we're currently using an error icon to indicate that the PM is not available, which brings up a tooltip stating the reason + link to learn more. I'm having a conversation at this very moment about updating this popover to a white background for better legibility but let me know if I'm on the right track with this pattern first. :)

<img width="952" alt="image" src="https://github.com/Automattic/woocommerce-payments/assets/5121465/ef68075c-2e59-4549-93cc-10edbb35e344">

**Comment by dmallory42** [comment]
I wasn't previously aware of that pattern, but it looks good to me. 🙂 I think the main thing is that the user is informed/knows that they are not able to add those APMs until they finish full KYC.

**Comment by dmallory42** [comment]
Hey @elizaan36, I just started looking at this and had a question:

If an APM is not available because the user is PO enabled but hasn't completed full account verification yet, would you like the message to be the same as the current one (the one you screenshotted above, "We need more information from you to enable this method.", or would you like a bespoke message for this case? Personally, I think the message is suitable because the action advised in `Learn more` should help a PO user complete onboarding (It links to [this page](https://woocommerce.com/document/woopayments/payment-methods/additional-payment-methods/#method-cant-be-enabled)), but just wanted to check since we may want to provide more specific guidance.

Thanks! :)

**Comment by elizaan36** [comment]
I actually think this message works well for the PO use case!
