### ISSUE TITLE
Update `Settings > Deposits` notices to current inline notice style (e.g. `Your first deposit will be held for 7 days. Deposit scheduling will be available after this period.`

### ISSUE THREAD

**Issue by haszari** [Automattic/woocommerce-payments#6424]
### Describe the bug
In `WooCommerce > Settings > Deposits`, the new account waiting period notice uses an old variation of the component. It should use ~`inline notice`~ `BannerNotice` component, notice no bar on left, and explicit `Learn more` instead of help icon. The goal of this issue is to update all similar notices in `Deposits` section of the settings.

Thanks to @elizaan36 for spotting this. 

Ideally we can just switch in a new component from Woo admin / gutenberg, maybe we're using custom styles or an old version of the component?

#### Should look like this
![image-31](https://github.com/Automattic/woocommerce-payments/assets/4167300/13c75c45-c987-4cfc-906d-c8da0b88632f)

##### Currently looks like this
<img width="742" alt="Screenshot 2023-06-02 at 10 58 13 AM" src="https://github.com/Automattic/woocommerce-payments/assets/4167300/c41ff1ae-2ff7-40e6-9132-92942f48eb95">

<img width="1185" alt="275905817-9e207a78-be66-4a0a-81e5-64c870d28a8e" src="https://github.com/Automattic/woocommerce-payments/assets/4167300/dfabb89e-33f8-410d-aa70-df67cccbcb0a">

### To Reproduce

1. `WooCommerce > Settings > Deposits`
2. Do whatever you need to do to show the new account notice – e.g. in test mode, or onboard a new WCPay account.

**Comment by zmaglica** [comment]
This issue impacts Disputes, so assigning to team Helix (based on team responsibilities) @haszari . Assigning as part of Gamma Triage process PcreKM-yM-p2

**Comment by bradyv** [comment]
Just continuing from the duplicate issue I filed

> Good spotting! This is already logged in our maintenance queue. @bradyv if you have any thoughts or details why we should prioritise this sooner (e.g. next sprint / release) please add info to https://github.com/Automattic/woocommerce-payments/issues/6424 🙌

I would only suggest prioritizing this sooner as it seems like it would be a fairly simple fix, and little inconsistencies like this contribute to the Woo experience feeling fragmented from screen to screen.

**Comment by souravdebnath1986** [comment]
@haszari is it possible to combine with https://github.com/Automattic/woocommerce-payments/issues/7970. Though the notice locations are different between the issues i.e. this issue is deposit settings while 7970 is payments overview, the notice is the same. Ok to keep it as seperate issues as you deem fit.

**Comment by haszari** [comment]
> @haszari is it possible to combine with https://github.com/Automattic/woocommerce-payments/issues/7970. Though the notice locations are different between the issues i.e. this issue is deposit settings while 7970 is payments overview, the notice is the same. Ok to keep it as seperate issues as you deem fit

Better to keep both issues, so we can tackle incrementally. Small self-contained issues => more momentum.

It's likely someone could do both in quick succession :)
