### ISSUE TITLE
BNPL: Change Afterpay / Clearpay branding dynamically based on country

### ISSUE THREAD

**Issue by nagpai** [Automattic/woocommerce-payments#6425]
### Description

Afterpay is branded as Clearpay in the United Kingdom and EU. The branding should dynamically change for merchants in these countries. 

United States, Canada, United Kingdom, Australia, New Zealand, France, Spain

### Acceptance criteria

* The PM should show as `Afterpay` in the United States, Canada, Australia and New Zealand.
* It should show as `Clearpay` for merchants in the United Kingdom, France and Spain.

### Designs
List of screens where this change is applicable:
* Additional Payment Methods enablement screen ( when merchant enables it for the first time ) 
* `Payments --> Settings` ( list of Additional Payment Methods )
* Checkout screen ( user frontend )
* Banners shown to eligible merchants before APM enablement within `Payments --> Settings`

### Testing instructions
* Each of the screens above should show Afterpay or Clearpay branding depending on the country.

**Comment by mgascam** [comment]
We will implement this feature in phase II of the project

**Comment by Babylon1999** [comment]
Same story in zd-7157237, the merchant is reporting a discrepancy between the radio button and logo displayed.

<img src="https://d.pr/i/hwAu6J+" alt="">

Link to image: https://d.pr/i/hwAu6J


https://wordpress.org/support/topic/clearpay-labelling/#post-17122014

**Comment by haszari** [comment]
Reopening – the fix in #7995 unintentionally broke refreshing the account cache (via dev tools), so was reverted in #8034.
