### ISSUE TITLE
Payment Settings - Cramped Spacing in the Express checkout section

### ISSUE THREAD

**Issue by stephendharmadi** [Automattic/woocommerce-payments#6426]
### Describe the bug
The spacing in the payment settings, specifically in the express checkouts section was pretty cramped on the smaller screen.

### To Reproduce
1. Go to 'Settings'
2. Click on 'Payments'
3. Scroll down to 'Express checkouts'
4. Change the browser to a smaller size
5. See the cramped spacing between the description and the CTA button

### Actual behavior
The spacing between elements of the express checkout description and the CTA button was getting smaller as the container size gets reduced.

### Screenshots
<img width="1019" alt="screenshot-2023-05-24-at-3 45 32-pm" src="https://github.com/Automattic/woocommerce-payments/assets/110893979/aaaf1a56-3e77-4eb6-a309-7b8fd5c9525a">

### Expected behavior
Please refer to [this design specification in Figma](https://www.figma.com/file/C1r0Vzxh1mhbDJJnbjHp5q/Payments-Settings?type=design&node-id=2135-81957&t=l4MB6qkUoe9KeY8Y-4)
The spacing between elements should remain the same (16 px) as the container gets smaller.
![iPad Pro 12 9_ - 1](https://github.com/Automattic/woocommerce-payments/assets/110893979/96a3d4b4-94c5-4419-8571-3422aa83c5e3)
![iPad mini 8 3 - 1](https://github.com/Automattic/woocommerce-payments/assets/110893979/e7546f90-dfb8-4dd4-a9c0-6519505f38f6)

### Desktop (please complete the following information):

* OS: [Ventura 13.4]
* Browser [Chrome]
* Version [Version 113.0.5672.126 (Official Build) (arm64)]

### Additional context
This ticket issue is created based on [@beau](https://a8c.slack.com/team/U029C2SCD)’s [post here](https://wcpay.wordpress.com/2023/05/25/small-observations-from-wcpay).

**Comment by stephendharmadi** [comment]
I just realized it's already opened in another ticket #6384 by @pierorocca, please refer to the design provided

**Comment by zmaglica** [comment]
Closed as duplicate #6384
