### ISSUE TITLE
Add interface for storing and retrieving metadata; change metadata name from _intention_status to _intent_status

### ISSUE THREAD

**Issue by v18** [Automattic/woocommerce-payments#644]
We want abstract functions like `$order->update_meta_data( `_charge_id` )`  so that we can change the name of the metadata we use, and add any other logic we need.

For example, we'd like to change one metadata name from _intention_status to _intent_status.
From @marcinbot:

> Then, in the getter we could add a simple check: if _intent_status does exist, return it, otherwise check for _intention_status and then return that. We’d have to keep this code in the client for a long time, but it’s better than breaking the sites or writing a migration script.

**Comment by jessy-p** [comment]
Context here: paJDYF-Gk-p2

**Comment by vbelolapotkov** [comment]
I'm closing this one as it's probably not relevant anymore. Happy to reopen or create a new issue if this is the case.
