### ISSUE TITLE
Avoid sending inbox notifications if KYC haven't been completed

### ISSUE THREAD

**Issue by daquinons** [Automattic/woocommerce-payments#6441]
### Describe the bug
Seems like we are sending notifications without having completed the full onboarding. From [this feedback](https://hostedwoo.wordpress.com/2023/05/26/my-awesome-store-woo-express-experience/):

> I received an inbox notification to “Boost your sales by accepting new payment methods” which I clicked enable on and I get redirected to a screen that says “Sorry, you are not allowed to access this page.” – Likely because I hadn’t completed WC Pay onboarding?
> 
> Same thing with an inbox notification that says “Sell worldwide in multiple currencies”

We'll need to also take into consideration accounts progressively onboarded. For example, for those, the notifications related to Multicurrency make sense, but not those related to additional payment methods.

**Comment by daquinons** [comment]
❕ Pay attention to #6413 before working on this, might partially close this one (the part of the PO accounts for additional payment methods). If that was taken care of in that issue, you can skip that part in this one.

If you finish this one before #6413, give an update about the inbox notification work in it.

**Comment by brandonwanA8C** [comment]
Looking at the [feedback](https://hostedwoo.wordpress.com/2023/05/26/my-awesome-store-woo-express-experience/) it was dated back in May 26 2023 - PO wasn't live yet. Hence, I don't think this was related to PO. 

Likely this is a legal issue, do we know where the URL in the email was supposed to redirect the user to?

**Comment by daquinons** [comment]
> Looking at the [feedback](https://hostedwoo.wordpress.com/2023/05/26/my-awesome-store-woo-express-experience/) it was dated back in May 26 2023 - PO wasn't live yet. Hence, I don't think this was related to PO.
> 
> Likely this is a legal issue, do we know where the URL in the email was supposed to redirect the user to?

Yes, it's definitely present from before PO, but it's also going to potentially affect PO onboarded accounts because they don't have all the features as normal accounts do at some point, like the multiple payment methods that I mention!

**Comment by daquinons** [comment]
Related to #6779 too
