### ISSUE TITLE
Investigate adding customer ID to payment intent on WCPay server

### ISSUE THREAD

**Issue by jrodger** [Automattic/woocommerce-payments#646]
https://github.com/Automattic/woocommerce-payments/pull/608 added customer IDs to payment intents. A WCPay customer is created the first time we see a WP user make a purchase. The ID of the customer is stored against that WP user and used for subsequent payments.

This works well, however, it adds a server round-trip into the payment processing function. We could investigate managing customers on the server instead and seeing if we can remove this round-trip. This may involve adding all the customer details (email, name etc) to each payment request and then handling the creation or update of the customer from that.

We would need to see how the mapping between WP user and WCPay customer would be maintained (currently on the local site, would that still be appropriate?)

**Comment by zmaglica** [comment]
This is the old issue and I think it's stuck in the Engineering review queue for quite some time. Based on the description, the investigation could be performed and feedback from the Architects or Engineers can be asked anytime during the investigation.

This is the part of the Gamma backlog porter duty to reduce the number of the issues in the Engineering review column.

**Comment by jessy-p** [comment]
Closing as  obsolete, will be part of the Payment Processing Domain @htdat
