### ISSUE TITLE
Make sure all strings can be translated

### ISSUE THREAD

**Issue by elazzabi** [Automattic/woocommerce-payments#6464]
### Describe the bug
While working on https://github.com/Automattic/woocommerce-payments/pull/6388, we discovered there are many other strings that we need to wrap in `__(` `)` to make these strings ready for translations.

The work has already started in https://github.com/Automattic/woocommerce-payments/pull/6385 but we'll need to continue and make this a team effort.

**Comment by zmaglica** [comment]
This issue impacts i8n, so assigning to team Fusion (based on team responsibilities) @anu-rock . Assigning as part of Gamma Triage process PcreKM-yM-p2.

**Comment by anu-rock** [comment]
Hey @zmaglica 👋 Thanks for the ping. I'll add it to Fusion's backlog noting that this is apparently a much bigger effort for one team to handle. @elazzabi can probably share a rough estimate of untranslated string, but from initial discussions it seems there are too many spread across the codebase. Fusion will be happy to coordinate this initiative, but I think it's best done based on team focus areas.
