### ISSUE TITLE
Multi-Currency Errors with Woo Express onboarding

### ISSUE THREAD

**Issue by dwainm** [Automattic/woocommerce-payments#6466]
On a newly onboarded site, the multi-currency tab shows a few errors.

More details here:
peapX7-2wb-p2#comment-3237

**Comment by zmaglica** [comment]
This issue impacts multi-currency, so assigning to team Sigma (based on team responsibilities) @dwainm . Assigning as part of Gamma Triage process PcreKM-yM-p2

**Comment by eduardoumpierre** [comment]
I had to switch focus during the week and will resume the work today.

**Comment by eduardoumpierre** [comment]
There are two main issues happening:
- The debug data showing
- A notice and an error

The next step is to try to understand the error by uploading a development version of the plugin.

![Image](https://github.com/Automattic/woocommerce-payments/assets/16882226/5df1954d-c97a-4897-a7da-1f2b1b238955)
