### ISSUE TITLE
Improve design of express checkout button settings

### ISSUE THREAD

**Issue by c-shultz** [Automattic/woocommerce-payments#6470]
### Description
In a user flow review, the group called out the lack of hierarchy in the express checkout button settings:
<img width="631" alt="image" src="https://github.com/Automattic/woocommerce-payments/assets/6209518/048a5c32-cb6b-487b-b530-1a46cb3aefec">

The above screenshot was taken on `wp-admin/admin.php?page=wc-settings&tab=checkout&section=woocommerce_payments&method=woopay`

We would like to see more hierarchy and visual separation between sections.

cc @elizaan36  @kellychoffman  @pierorocca

**Comment by pierorocca** [comment]
@c-shultz the other callout I believe was the too narrow store logo settings shown below. It should match the width of the other areas.

![image](https://github.com/Automattic/woocommerce-payments/assets/109928953/e079985d-9f08-4f4f-aabf-d8261dc7aaef)

**Comment by pierorocca** [comment]
Also noting that these are targeted, small quick improvements and that payments settings in general require a more extensive overhaul and the addition of front-end editing support.

**Comment by pierorocca** [comment]
cc @shaunandrews

**Comment by zmaglica** [comment]
This issue impacts express checkout, so assigning to team Heisenberg (based on team responsibilities) @bborman22 . Assigning as part of Gamma Triage process PcreKM-yM-p2

**Comment by elizaan36** [comment]
Hi friends, Here's a proposed layout to solve for the lack of hierarchy in the Payments settings screens. This applies to Google Pay/Apple Pay, WooPay settings in the WCPay plugin.

<img width="608" alt="image" src="https://github.com/Automattic/woocommerce-payments/assets/5121465/9f6d589e-4506-494a-a435-4d7120939f5b">

Rather than a wall of radio buttons, we can try converting the "Call to action" section into a dropdown selection. Reach out with any questions!

**Comment by pierorocca** [comment]
Let's implement the new design for the PRBs and WooPay in lieu of fixing the regression in #8087 @FangedParakeet @c-shultz. Given this impacts multiple areas including WooPayments checkout this would be a good issue to tackle soon if not now if someone has a small window to tackle this layout update.

**Comment by frosso** [comment]
@elizaan36 to confirm - do we want the "Call to action" dropdown to be width-constrained? Or should it go full width, like the other elements on the page?

![Screenshot 2024-02-08 at 2 34 08 PM](https://github.com/Automattic/woocommerce-payments/assets/273592/13067b95-fc61-4e8a-81bd-1e419f0cd3b4)
![Screenshot 2024-02-08 at 2 35 38 PM](https://github.com/Automattic/woocommerce-payments/assets/273592/443d85f9-4b91-48e0-8bf1-2ab96a6d80be)

**Comment by pierorocca** [comment]
The former would be more consistent with the rest of the WooPay settings page and full width would be best for mobile imo. Good callout @frosso.
