### ISSUE TITLE
Right margin issue in WooPay checkout appearance settings

### ISSUE THREAD

**Issue by c-shultz** [Automattic/woocommerce-payments#6471]
### Description
In a user flow review, the group called out the way the store logo and custom message settings have an unnecessary right margin instead of filling out the width:

<img width="461" alt="image" src="https://github.com/Automattic/woocommerce-payments/assets/6209518/98d73b81-b4c2-4d47-9b56-80ee8ec05248">

The above screenshot was taken on `wp-admin/admin.php?page=wc-settings&tab=checkout&section=woocommerce_payments&method=woopay`

cc @elizaan36  @kellychoffman

**Comment by zmaglica** [comment]
This issue impacts WooPay UI, so assigning to team Heisenberg (based on team responsibilities) @bborman22 . Assigning as part of Gamma Triage process PcreKM-yM-p2

**Comment by pierorocca** [comment]
Closing in favor of #6993.
