### ISSUE TITLE
Add Telephone Input with validation to the PO Form

### ISSUE THREAD

**Issue by dmallory42** [Automattic/woocommerce-payments#6478]
### Description

We previously discussed creating a custom element to represent a Telephone Input. This should validate the number based on the format for the selected region. There are some useful looking libraries we could explore to help us with this. 

One thing to consider is that we may not want to be too strict with our validation. Perhaps we should allow the user to leave the field blank (and enter it in the Stripe KYC) or confirm the number they entered is correct in case there are cases where a user has a valid number that doesn't match our criteria.

### Acceptance criteria

* A custom telephone field input is available to use on the PO form.
* We try and validate the number based on the format of the selected region.

**Comment by brandonwanA8C** [comment]
**Goal**: improve UX, reduce data entry & validation redundancy 
**Desired outcome:** 
use-case-1: IF the particular phone# field is used solely for Stripe (2FA), THEN just let Stripe collect it. 
use-case-2: WCPay wants to retain "phone number, email, etc" as part of the User Contact info, regardless Stripe (or not) needs it. in this case, we should specify "Business (or Owner) Contact Phone Number" 
use-case-3: Merchant would have "Customer Support Phone Number" listed as part of their biz profile, this is used for KYC/Risk/Profiling purposes, such phone # may/may-not receive SMS

**Comment by vladolaru** [comment]
I think we can safely close this one as we've recently removed phone number collection from our MOX (https://github.com/Automattic/woocommerce-payments/issues/8311).
