### ISSUE TITLE
WooPay "Learn more" link in tooltip sometimes hard to click

### ISSUE THREAD

**Issue by c-shultz** [Automattic/woocommerce-payments#6484]
### Describe the bug
In a user-flow review for WooPay, @pierorocca noted that sometimes the "Learn more" link cannot be clicked because the tooltip occasionally disappears before the cursor overlaps the tooltip and "Learn more" link. When it works right, the user can click the link:
<img width="301" alt="image" src="https://github.com/Automattic/woocommerce-payments/assets/6209518/2725eb4c-866a-46d3-aacc-47f49838260d">

But when it does not work right, the whole tooltip disappears before the cursor overlaps the link.

This was reproduced on the shortcode checkout with WooPay enabled.

**Comment by zmaglica** [comment]
This issue impacts WooPay UI, so assigning to team Heisenberg (based on team responsibilities) @bborman22  . Assigning as part of Gamma Triage process PcreKM-yM-p2

**Comment by elizaan36** [comment]
This can be solved by using click/tap to open the popover rather than hover. This will provide better accessibility in general.
