### ISSUE TITLE
Dismissed dispute task shouldn't stay hidden even though there is new dispute

### ISSUE THREAD

**Issue by shendy-a8c** [Automattic/woocommerce-payments#6485]
### Describe the bug

When there is a dispute, it will appear as task on the overview page about the dispute. When merchant dismiss that task (despite whether they have resolved the dispute or not), the task will stay dismissed. Even though after that there is a new dispute, the task will stay hidden and it's a big risk because merchant might not get alerted about the new dispute from the task list.

As @Jinksi [mentioned](https://github.com/Automattic/woocommerce-payments/pull/6397#issuecomment-1576013516), the solution might be to come up with a new key for the dispute task. Part of the work for this issue is to make sure changing that key does not have negative impact, or find another solution if possible. Is the state of the task, whether dismissed or not, stored somewhere? Can we make it reset the state when there is new dispute?

### To Reproduce

1. Purchase a product using one of the [test cards](https://stripe.com/docs/testing#disputes) to result in a dispute.
2. Notice there is a dispute task on the Payments > Overview page.
3. Dismiss the task by clicking the three dots menu on the right of the task.
4. Make another dispute.

### Actual behavior

Dispute task will stay hidden.

### Expected behavior

Dispute task should appear.

### Additional context

Related to:
- https://github.com/Automattic/woocommerce-payments/pull/6397 which moves the task list to the greeting card at the top, and
- https://github.com/Automattic/woocommerce-payments/pull/6371 which makes task item not dismissible.

**Comment by Jinksi** [comment]
> Can we make it reset the state when there is new dispute?

Since the "dismissed" state is associated to the task key (`dispute_resolution_task`), perhaps we could create a dynamic key: e.g. `dispute_resolution_task_{...dispute_ids}`.

Tracks events would still use the static `dispute_resolution_task` key to remain discoverable.

**Comment by haszari** [comment]
Thanks for catching this @shendy-a8c !
