### ISSUE TITLE
Prefill the Business Website for PO

### ISSUE THREAD

**Issue by dmallory42** [Automattic/woocommerce-payments#6488]
### Description

Raising a feature that was asked about in the recent call for testing on Progressive Onboarding. (sharing screenshot from the post):

<img width="626" alt="Screenshot 2023-06-08 at 14 33 58" src="https://github.com/Automattic/woocommerce-payments/assets/11770181/a0f980f0-cb1b-4fc1-a6e5-3ca1d9de490d">

Can/should we try and prefill the business website field with the store URL? This issue is to bring the topic forward, and then possibly work on it if we think it should be done.

**Comment by brandonwanA8C** [comment]
Preliminary input:

**Goal**: Improved UX for faster onboarding 
**Desired outcome**: IF the SAME question was asked (e.g. in profiler) AND the data is available with the required format, THEN we should pre-populate the already collect data across onboarding UX, WHILE allowing the user to Edit the data wherever necessary.
**Need to validate**: 
1) what was the "Question" asked prior to Payment onboarding for the "same" Data field? need to make sure the same query to the data stays consistent.
2) did the original data collector validate the inputs/format/etc (e.g. htttp:/\ninja.comm), as this URL would be used by Risk team to manually/automate Site Audit, etc.
