### ISSUE TITLE
Show admin notices in WC-Admin pages

### ISSUE THREAD

**Issue by DanReyLop** [Automattic/woocommerce-payments#649]
See https://github.com/woocommerce/woocommerce-admin/pull/3827 for more context.

In newer versions of WC-Admin, it's impossible to show an `admin_notice` in "real" WC-Admin pages, like `Analytics` or the onboarding task list. So, some error messages will never be displayed. That affects, for example, the Jetpack connection process, which uses [the `add_notice_to_settings_page` function](https://github.com/Automattic/woocommerce-payments/blob/86f81b946527c2622c3e3b3dc22143280136730c/includes/class-wc-payments-account.php#L558) to display errors.

Also, we can remove [this code](https://github.com/woocommerce/woocommerce-admin/blob/ec36a00b77b5c0e313985a5a64c88aaec9eb154e/docs/examples/extensions/important-admin-notice/js/index.js#L10-L21), since the filter no longer exists in WC-Admin.

**Comment by jessy-p** [comment]
Closing as obsolete. Please create a new issue if this feature is still required.
