### ISSUE TITLE
Add a way to allow us to define if WooPay should be enabled or disabled by default for new merchants

### ISSUE THREAD

**Issue by leonardola** [Automattic/woocommerce-payments#6494]
### Description
We need a way to be able to control if WooPay gets enabled or disabled by default for new merchants.

### Acceptance criteria
- This needs to be done in a way that we can change it without having to create a new release for WC Payments

### Additional context
P2: pdpOw2-2TC-p2

**Comment by zmaglica** [comment]
This issue impacts WooPay, so assigning to team Axiom (based on team responsibilities) @LCmry  . Assigning as part of Gamma Triage process PcreKM-yM-p2
