### ISSUE TITLE
Spike: Concerns with Stripe's 3DS implementation

### ISSUE THREAD

**Issue by FangedParakeet** [Automattic/woocommerce-payments#6498]
### Description

The UPE, in its original incarnation, creates openings for vulnerabilities by relying on client-side confirmation. This is because payment intents and client secrets must be shared on the client, where they can be scraped and reused in attacks to create inauthentic transactions. With our [new deferred intent implementation](paJDYF-7za-p2), Stripe his allowed us to move all of this confirmation deep into the server-side, where it belongs. However, [3DS authentication](https://stripe.com/docs/payments/3d-secure) still evades us as a payment flow that requires client-side confirmation and forces us to share privileged client information in potentially insecure ways. 

#### How is 3DS authentication currently implemented?

3DS authentication is handled via a modal that Stripe automatically presents when fire either the `confirmCardSetup` or `confirmCardPayment` function via Stripe's JS API. In the shortcode checkout, when attempting to confirm the intent, if the intent status transitions to `requires_action`, [we keep the user on the checkout page](https://github.com/Automattic/woocommerce-payments/blob/develop/includes/class-wc-payment-gateway-wcpay.php#L1285-L1298)--inserting the payment intent and client secret into the current page URL--and eventually we will parse these parameters and use them to [confirm the intent on the client](https://github.com/Automattic/woocommerce-payments/blob/develop/client/checkout/api/index.js#L242-L276) and present the 3DS modal.

Similarly, in the add payment method flow, [we attempt to create and confirm a setup intent](https://github.com/Automattic/woocommerce-payments/blob/develop/client/checkout/classic/index.js#L270) and if the status is `requires_action` (i.e. [not `succeeded`](https://github.com/Automattic/woocommerce-payments/blob/develop/client/checkout/api/index.js#L372)), [we attempt to confirm the intent on the client](https://github.com/Automattic/woocommerce-payments/blob/develop/client/checkout/api/index.js#L378) using `confirmCardSetup` instead, which will consequently spawn the 3DS modal.

#### Why it's bad

We must expose intent ID and client secret on the client, where it can be read by malicious parties.

#### Why it's not so bad

3DS cards always require additional authentication before they can be confirmed, so even if a malicious party acquires this information, they cannot use this immediately to their advantage to create false transactions. They can, however, get the card (justifiably) flagged for fraud, by attempting to create transactions using these details. 

#### What else can we do?

Well, we're not really sure and that's what this issue is for really. We would like to find out (most likely by asking Stripe) whether they are aware/concerned of this vulnerability and whether there is any other way to implement our 3DS flow.

#### Useful questions to ask Stripe

- Does Stripe have any concerns about client side confirmation?
   - I'd imagine that they don't have too many concerns, since the UPE is designed this way, but are they aware of the possibility of carding attacks, for example?
   - Is the client secret supposed to be kept secret or is it acceptable to share this with our front-end?
- Is there any other way to implement 3DS authentication?
   - Can the 3DS modal only be triggered by firing `confirmCardPayment` or `confirmCardSetup`?
   - Is there any manual way to trigger the 3DS modal?
   - Is authenticating 3DS cards via iframe modal more secure or preferred to doing so via redirection?
- And many more!
   - These are just a few ideas I had to get your critical juices flowing.

The results of this investigation can be confined to this issue, but a P2 post would probably benefit Transact as a whole, to share this knowledge of a somewhat niche yet critical payment flow.

**Comment by timur27** [comment]
After some research and discussions (p1696586191094739-slack-C0208C3BXHP), below is the summary. 

Since 3DS authentication is essentially a confirmation done by customer, it's natural that the action should occur on the client and be handled by Stripe JS. There are at least two options to carry out 3DS authentication: by using `confirmCardPayment/confirmCardSetup` or `handleNextActions`. Both require [`client_secret`](https://stripe.com/docs/api/payment_intents/object#payment_intent_object-client_secret) to be passed to the front-end, which means we're following the requirements here.

We use `confirmCardPayment/confirmCardSetup` because this implementation from the past didn't require any new changes and at the same time, works well in our use-case. It won't confirm an intent with `requires_action` status, but instead, will handle the 3DS flow.
