### ISSUE TITLE
Testing Instructions for 4.2

### ISSUE THREAD

**Issue by tammullen** [Automattic/woocommerce-payments#650]
During upcoming Woo 4.2 testing we were going to have our external testers (who we started using in 4.1) have a look at some things they didn’t get to in 4.1.

In 4.1 they did some testing around the setup and connection for payments (https://github.com/woocommerce/woocommerce/wiki/Release-Testing-Instructions-WooCommerce-4.1#woocommerce-payments)

We would like to get some additional Testing Instructions for them to test a bit more around payments. 

We have a guide on adding instructions here p7bje6-21l-p2

If there are already suitable instructions elsewhere such as the docs (e.g https://docs.woocommerce.com/document/payments/testing/) we can just link to them or copy from them.

The current plan is for them to test the 4.2 beta on May 13th-14th and the 4.2 RC May 20th-21st so ideally any instructions would need to be ready by then.

**Comment by vbelolapotkov** [comment]
This seem to be not relevant anymore. @allendav feel free to reopen if I'm wrong.
