### ISSUE TITLE
Support the checkout block

### ISSUE THREAD

**Issue by allendav** [Automattic/woocommerce-payments#652]
Related to adding WCPay to https://github.com/woocommerce/woocommerce-gutenberg-products-block and #639

cc @thenbrent  @bmccotter

**Comment by thenbrent** [comment]
Renaming this issue to reflect the work in #723. :)

**Comment by DustinHartzler** [comment]
Yay! I just came to report this :)

**Comment by thenbrent** [comment]
@DustinHartzler we have an open PR for this now. If you have someone interesting in using WC Pay with the blocks, it would be great to work with them as a beta tester for it.

**Comment by DustinHartzler** [comment]
I'd be happy to test. I ran into in when I was trying to add a bookable product to my wife's site with the block checkout enabled.

**Comment by DustinHartzler** [comment]
Excuse my noviceness. How's the best way to check the PR? Should I just grab the master? Or is their a fancy terminal command that I can use to just test the PR? 

I've got a site that's currently taking bookings and I'll be happy to try it out.
