### ISSUE TITLE
Add meta to Stripe Billing subscription requests noting the store's Stripe billing opt-in status

### ISSUE THREAD

**Issue by james-allan** [Automattic/woocommerce-payments#6529]
#### 🛑 This issue is blocked by: 

- [ ] https://github.com/Automattic/woocommerce-payments/issues/6508

We're moving towards sunsetting the subscription features that are currently bundled within WC Pay, referred to as WC Pay Subscriptions. However, we will continue offer Stripe Billing as an optional billing engine for merchants who choose to use it.

Because of this opt-in mode there is a need to distinguish between subscriptions processed via Stripe Billing that are part of WC Pay Subscriptions and those processed with WC Subscriptions. This distinction will enable us to identify active WC Pay Subscriptions user accounts.

To achieve this, we need to add metadata sent to Stripe during Stripe Billing subscription requests. The metadata should contain relevant information that allows us to differentiate between WC Pay Subscriptions and WC Subscriptions. By analyzing this metadata, we can determine the subscription type and identify active WC Pay Subscriptions users.

Furthermore, having the ability to identify when there are no active WC Pay Subscriptions users will be valuable for maintenance and analysis purposes. It will help us streamline our processes and make informed decisions based on the usage and popularity of WC Pay Subscriptions.

### Acceptance criteria

- Metadata is successfully included in transactions sent to Stripe Billing.
- The metadata field is populated correctly with the appropriate subscription information.
- WC Pay Subscriptions can be identified and distinguished from WC Subscriptions using the metadata.

### Testing instructions

1. Install WC Payments.
2. Purchase a Subscription. You will get a WC Pay Stripe billing enabled subscription. 
3. Enable the WC Subscriptions plugin. 
4. Enable Stripe Billing via the setting. See [#6508](https://github.com/Automattic/woocommerce-payments/issues/6508).
5. Purchase a subscription. You will still get a WC Pay Stripe billing subscription. However this subscription should be distinguishable from the other subscription purchased while using the built in WC Pay subscription feature. 

### Additional context

peNR48-2u-p2 project.

**Comment by james-allan** [comment]
Hey @thenbrent I just wanted to get some clarification around this issue. It's a reference to this point from the [PRD](https://wcsubscriptions.wordpress.com/2023/06/07/prd-subscriptions-primary-offering-problem-solution/)

> Distinguish between subscriptions processed via Stripe Billing that is part of WC Pay Subscriptions and Stripe Billing with WC Subscriptions (likely in meta data sent to Stripe on transactions) to make it possible to identify active WC Pay Subscriptions user accounts and also eventually identify when there are no longer any active WC Pay Subscriptions users.

There it mentions that this meta would likely be added to transactions. I'm wondering if that's because auditing transactions is what we're interested in (eg volume). The approach mentioned in the issue description above indicates it would be meta data stored on the Stripe billing subscription object on creation and therefore the data would only count number of active WCPay vs WooSubscription Stripe billing subscriptions. Would that work or would you prefer it to be in transaction meta? 

If if it's in transaction meta, I'm then trying to understand if it needs to represent the environment of the subscription at the time of signup, or at the time of renewal. Or maybe even both? eg transactions for subscription created via WCPay Subscriptions, but using WooSubscriptions now. 🤷‍♂️

I guess the question is what kind of data are we wanting? Just a count active Stripe billing subscriptions and whether they were created with WCPayments or WooSubscriptions with the Stripe billing engine setting enabled. Or number Stripe billing subscription transactions processed with every possible environment type.

**Comment by thenbrent** [comment]
@james-allan sorry I missed this. The key requirement initially was to make sure we could see if anyone was still using WC Pay Subscriptions. 

Having the meta against each transaction processed via Stripe Billing will help us figure out if it was initiated via the bundled subscription functionality (i.e. WC Pay Subscriptions) or via the WooPayments + Woo Subscriptions combination (with the Stripe Billing option enabled). 

However, having the same data against the subscriptions themselves will also give us a better way to track how _new_ subscriptions are being created (and given there may be a large lag between subscriptions being created and renewals processing, that's valuable.)

I'll go through each comment now to elaborate a bit more:

> There it mentions that this meta would likely be added to transactions. I'm wondering if that's because auditing transactions is what we're interested in (eg volume). 

Yeah, volume will be part of what we are interested in even if it's not the primary driver here.

> The approach mentioned in the issue description above indicates it would be meta data stored on the Stripe billing subscription object on creation and therefore the data would only count number of active WCPay vs WooSubscription Stripe billing subscriptions. Would that work or would you prefer it to be in transaction meta?

We will need transaction meta to be more confident in our assessment.

> If if it's in transaction meta, I'm then trying to understand if it needs to represent the environment of the subscription at the time of signup, or at the time of renewal.

Just at the time of renewal is fine. I assume can track time of signup by looking at meta on previous transactions for the subscription I assume. If we are able to get both, that might make querying the data easier / faster though.

> I guess the question is what kind of data are we wanting? Just a count active Stripe billing subscriptions and whether they were created with WCPayments or WooSubscriptions with the Stripe billing engine setting enabled. Or number Stripe billing subscription transactions processed with every possible environment type.

The primary goal of this data is to identify active WC Pay Subscriptions user accounts. Tracking both new subscriptions and renewals is the most accurate way to do that. Given we will almost certainly also want to look at the volume of the different options, especially over time, to track migration progress, having the meta data on transactions is also valuable.

**Comment by james-allan** [comment]
Thanks @thenbrent! 

So I've been playing around on this for the last couple of hours and this is currently what I have running locally. 

If the store has opted into Stripe Billing (ie they have installed Woo Subscriptions and actively chosen to use Stripe Billing) the metadata on the transaction will look like this: 

<img width="431" alt="Screenshot 2023-09-12 at 4 52 52 pm" src="https://github.com/Automattic/woocommerce-payments/assets/8490476/83b31917-586e-461b-a120-e4f110e8952d">

Note the `wcpay_subscription` meta is pre-existing to indicate transactions linked to Stripe Billing subscriptions. 

If the user hasn't installed Woo Subscriptions or hasn't switched on Stripe Billing, then the subscription is considered a legacy wcpay subscription and the meta would look like this:

<img width="385" alt="Screenshot 2023-09-12 at 4 54 26 pm" src="https://github.com/Automattic/woocommerce-payments/assets/8490476/deaca0f1-7663-4762-a5c8-678389807f71">


Just to give some example scenarios: 

1. If a merchant continues using WCPay Subscriptions after updating to next version of WooPayments, each time a Stripe Billing subscription renewal is paid or fails, it will be recorded as a `legacy_wcpay_subscription` payment. 
2. If a merchant was using WCPay subscriptions, installs Woo Subscriptions but doesn't migrate. Each time a Stripe Billing subscription renewal is paid or fails, it will be recorded as a `legacy_wcpay_subscription` payment. 
3. If a merchant installs Woo Subscriptions and turns on Stripe Billing. All of their Stripe Billing subscription renewals will be recorded `stripe_billing` payments. 
4. If an existing wcpay subscription merchant installs Woo Subscriptions and chooses to opt into Stripe Billing, all of their Stripe Billing subscription renewals (including ones created prior to Woo Subscriptions being installed), will be recorded `stripe_billing` payments. 

Does that work for these purposes and inline with your thinking? Also are these terms and meta keys appropriate in your opinion?

**Comment by james-allan** [comment]
I've also added the meta to the Stripe Billing Subscription object. In this case I went with the meta key name `source`.

If a Stripe Billing subscription is created without the Woo Subscription plugin active, or if no source is provided in the create request (eg the store hasn't updated WooPayments yet), the subscription source will be `wcpay_subscriptions`:  

<img width="500" alt="Screenshot 2023-09-12 at 8 04 45 pm" src="https://github.com/Automattic/woocommerce-payments/assets/8490476/9553818e-9a59-4cdd-9e4d-84a1ce699278">

---

If the subscription is created with the Woo Subscriptions plugin active, then we know the store has enabled Stripe Billing and it's source will be `woo_subscriptions`. 

<img width="500" alt="Screenshot 2023-09-12 at 8 04 57 pm" src="https://github.com/Automattic/woocommerce-payments/assets/8490476/3e42a57e-b0ca-4786-9da3-9097adcd19c0">

Are these terms and meta keys appropriate in your opinion?

**Comment by thenbrent** [comment]
> Are these terms and meta keys appropriate in your opinion?

Yep, `wcpay_subscriptions` and `woo_subscriptions` work well.

> In this case I went with the meta key name source.

Just having `source` might be a bit too general. Something like `subscription_source` has tighter scope, making it more self-descriptive and future proof. Not a big deal to just go with `source` though if necessary for some reason.

> Does that work for these purposes and inline with your thinking? Also are these terms and meta keys appropriate in your opinion?

That works and those meta keys and meta values look appropriate.

> Just to give some example scenarios

What happens in this example: a merchant was using WCPay subscriptions, installs Woo Subscriptions but doesn't opt into Stripe Billing or migrate. Is nothing recorded in `subscription_context` on future transactions? Or will `subscription_context` be recorded as `woo_subscriptions` or something else?

**Comment by james-allan** [comment]
Thanks Brent. 

> Just having source might be a bit too general. Something like subscription_source has tighter scope, making it more self-descriptive and future proof. Not a big deal to just go with source though if necessary for some reason.

That should be fine. I had excluded `subscription_` as a prefix because it is meta stored on a subscription but happy to be very specific and use `subscription_source`. 

> What happens in this example: a merchant was using WCPay subscriptions, installs Woo Subscriptions but doesn't opt into Stripe Billing or migrate. Is nothing recorded in subscription_context on future transactions?

Nah, the subscription context on their pre-existing Stripe Billing subscription payments will be `legacy_wcpay_subscription`. It's the 2nd example in the scenarios above.

**Comment by james-allan** [comment]
> Nah, the subscription context on their pre-existing Stripe Billing subscription payments will be `legacy_wcpay_subscription`. It's the 2nd example in the scenarios above.

If we want to be able to separate transactions made with Woo Subscriptions by un-migrated Stripe Billing subscriptions from those users that are still using WCPay Subscriptions (don't have the plugin), then we'll need a new value to capture those. eg `unmigrated_wcpay_subscription`?

**Comment by thenbrent** [comment]
> Nah, the subscription context on their pre-existing Stripe Billing subscription payments will be legacy_wcpay_subscription. It's the 2nd example in the scenarios above.

@james-allan sorry I meant _does_ migrate (but didn't enable Stripe Billing). I'm wondering what the meta will be when Woo Subscriptions is the billing engine with WooPayments.

> If we want to be able to separate transactions made with Woo Subscriptions by un-migrated Stripe Billing subscriptions from those users that are still using WCPay Subscriptions (don't have the plugin), then we'll need a new value to capture those. eg unmigrated_wcpay_subscription?

I think it's fine not to use that, and just use the same `legacy_wcpay_subscription` meta value for both.

**Comment by james-allan** [comment]
> I'm wondering what the meta will be when Woo Subscriptions is the billing engine with WooPayments.

Ohh. I haven't changed that meta so it's the current meta data which in my recent test looks like this: 

<img width="1048" alt="Screenshot 2023-09-13 at 3 09 01 pm" src="https://github.com/Automattic/woocommerce-payments/assets/8490476/105fc0b2-ffd1-44fb-bd02-3cd97de43174">

Note I just stumbled across a bug in that code. That `subscription_payment` shouldn't be `'no'`. It should be `renewal` and have a `payment_context` of `regular_subscription`.

**Comment by thenbrent** [comment]
> `payment_context` of `regular_subscription`

OK that works for me.
