### ISSUE TITLE
Currency Search input width is collapsed when viewing multi-currency settings modal on Woo Express

### ISSUE THREAD

**Issue by Jinksi** [Automattic/woocommerce-payments#6534]
### Describe the bug

On a Woo Express site, the Multi-currency settings modal search input only renders as 58px wide on Woo Express, not enough to view the text being input.

### To Reproduce

1. Create a Woo Express site
	* Follow the link (https://wordpress.com/setup/wooexpress) to create a Woo Express site on the Woo Express trial with the default plugins. Upgrading to the Performance plan (Upgrades -> Plans) _may_ be necessary to replicate, due to the additional plugins installed.
3. Navigate to Settings → WooCommerce → Multi-currency
4. Click the **Add currencies** button to view the modal
5. The search input only renders as 58px wide, not enough to view the text being input

### Actual behavior

The Multi-currency settings modal search input only renders as 58px wide on Woo Express, not enough to view the text being input.

### Screenshots

<img width="908" alt="image" src="https://github.com/Automattic/woocommerce-payments/assets/3147296/89e207b2-6e54-41d5-944a-18e9208b7306">

### Expected behavior

The Multi-currency settings modal search should fill the width of the parent element (minus padding) on Woo Express, allowing a user to view the text being input.

### Desktop (please complete the following information):

* OS: macOS
* Browser: Tested with Arc (chromium) & Safari
* Version: Arc 0.107.1 (chromium 114.0.5735.133) & Safari 16.5
* WCPay: 6.0.0

**Comment by zmaglica** [comment]
This issue impacts Multi-Currency, so assigning to Sigma (based on team responsibilities) @dwainm . Assigning as part of Gamma Triage process PcreKM-yM-p2

**Comment by bborman22** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Fractal-62a0f7b955648b001e1f5e1f/issues/Automattic/woocommerce-payments/6534?planning-poker) with Zenhub @cesarcosta99 @lovo-h @rafaelzaleski @ricardo
