### ISSUE TITLE
Attach new `wcpay_overview_task_click` tracks event to existing tasks

### ISSUE THREAD

**Issue by Jinksi** [Automattic/woocommerce-payments#6542]
### Describe the bug

In #6371, the tracks event `wcpay_overview_task_click` was introduced for monitoring click events on the new dispute resolution task. This event should be attached to other tasks in the Payments → Overview task list for completeness.

**Comment by haszari** [comment]
Makes sense, would be good to consistently fire this `wcpay_overview_task_click` event.

Next steps:

- Audit the other tasks – i.e. what tasks, confirm event is useful.
- Fire event from all relevant tasks.
- Check props and add any missing useful props (e.g. what task triggered event, task-specific data).
- Update registration for the event.

**Comment by haszari** [comment]
This is not a project issue, so removed that label (this was logged during a project, but that project is long complete, and this issue is unrelated to project goals). Removed from Helix board and sent for re-triage – this might be better handled by another team.

**Comment by zmaglica** [comment]
This issue impacts account Overview, so assigning to Moltres (based on team responsibilities Pc2DNy-3z-p2) @daquinons .
Assigning as part of Gamma Triage process PcreKM-yM-p2.
