### ISSUE TITLE
Resolve usage of "cancelation" vs "cancellation"

### ISSUE THREAD

**Issue by brucealdridge** [Automattic/woocommerce-payments#6550]
### Describe the bug

`cancelation` and `cancellation` are both used within WCPay. We should be consistent in our spelling.

Using one `l` is preferred for `cancel`, `canceling`, and `canceled`. While `cancelation` isn't necessarily incorrect, `cancellation` is more commonly used.

### Examples

https://github.com/Automattic/woocommerce-payments/blob/9dc0b955669368916fd1d847266b71a4618b1133/client/disputes/strings.ts#L273

https://github.com/Automattic/woocommerce-payments/blob/9dc0b955669368916fd1d847266b71a4618b1133/client/disputes/strings.ts#L300

### See also
- https://www.dictionary.com/e/canceled-vs-cancelled/
- https://en.wiktionary.org/wiki/cancelation#:~:text=the%20word%20cancellation%20is%20still%20much%20more%20widely
- https://www.merriam-webster.com/dictionary/cancellation

**Comment by SamantaTarun** [comment]
Let me do it.

**Comment by karthickbharathi1** [comment]
Hey @brucealdridge , could you assign this to me?

**Comment by SamantaTarun** [comment]
> 

Should I just only make a change to it to strings.ts?
