### ISSUE TITLE
User set Date and Time formatting aren't respected in react components

### ISSUE THREAD

**Issue by brucealdridge** [Automattic/woocommerce-payments#6567]
### Describe the bug

Date and time formats are user settable in WordPress. WCPay components do not use these settings instead opting to hardcode formats.

### To Reproduce

1. Go to 'Settings' > 'General'
2. Change a date time format that is not the default.
3. Visit a page with react components such as Transactions
4. See dates and time format is not used.

**NB:** This also applies to Deposits, Disputes, Loans, and more.

### Actual behavior

Date and time formats are hardcoded inside react components across WCPay. User settings are not respected.

### Screenshots

![Screenshot 2023-06-22 at 2 52 03 PM](https://github.com/Automattic/woocommerce-payments/assets/57298/a4279565-1ab8-4822-8be6-9afe2f8f0bc6)
![Screenshot 2023-06-22 at 2 51 40 PM](https://github.com/Automattic/woocommerce-payments/assets/57298/8c825382-18b9-4505-9425-172651586bba)

### Expected behavior

User set date/time formats should be used wherever possible

### Sample Snippets:

https://github.com/Automattic/woocommerce-payments/blob/23b58e9ea093f9fd001c761abfda30bc13234a81/client/disputes/index.tsx#L204-L207

https://github.com/Automattic/woocommerce-payments/blob/23b58e9ea093f9fd001c761abfda30bc13234a81/client/disputes/index.tsx#L213-L216

**Comment by rossviviano** [comment]
7293502-zen

**Comment by brucealdridge** [comment]
@mgascam, I'm not sure you meant to close this issue with #9640. It looks like that PR just alters some tests, whereas I believe this issue will require code changes in addition to test changes.

**Comment by mgascam** [comment]
Thanks @brucealdridge, you are right, this was closed by mistake. Reopening.

**Comment by mgascam** [comment]
We’re pausing work on this issue until the design proposal discussed in this [thread](https://github.com/Automattic/woocommerce-payments/pull/9635#issuecomment-2459193325) is available for review.
