### ISSUE TITLE
The authenticity of woocommerce-payments.0.9.2.zip could not be verified as no signature was found.

### ISSUE THREAD

**Issue by allendav** [Automattic/woocommerce-payments#657]
Observed when updating WooCommerce Payments on my site. Doesn't seem to prevent update.

<img width="936" alt="Screen Shot 2020-05-15 at 10 45 06 AM" src="https://user-images.githubusercontent.com/1595739/82080307-2994c600-9699-11ea-9364-0c947edf434e.png">

**Comment by RadoslavGeorgiev** [comment]
As indicated in the Trac ticket above, as well as most search results, this was an issue with WP 5.2, and the feature got rolled back. Since we don't have any further reports, I'm closing this issue, it doesn't seem to be relevant anymore.
