### ISSUE TITLE
Invalid Setup Intent links in the edit page for zero orders 

### ISSUE THREAD

**Issue by htdat** [Automattic/woocommerce-payments#6577]
### Describe the bug

Invalid Setup Intent links in the order page for zero orders such as free trial subscription product). 

### To Reproduce

1. Use WCPay Subscription and create a subscription product with free trial.
2. Purchase this product, and check out with a new card.
3. Check the setup intent (starting with prefix `seti_`) attached to the edit page of this order.
4. Click the link for the setup intent ID, which is similar to this http://localhost:8082/wp-admin/admin.php?page=wc-admin&path=%2Fpayments%2Ftransactions%2Fdetails&id=seti_1NM5QOR67tFB8u4VSbAIJoyW
6. Get the error!  

#### Edit order page:

![Markup on 2023-06-23 at 16:24:49](https://github.com/Automattic/woocommerce-payments/assets/10045087/d33aea59-c3bd-4608-bce9-aff8b6f55fc7)

#### Error translation detail page: 

![Markup on 2023-06-23 at 16:23:33](https://github.com/Automattic/woocommerce-payments/assets/10045087/ad069844-bed7-4b0b-860b-d5dbef0ea791)

### Expected behavior
May not have a link to the transaction page for setup intents.

### Desktop (please complete the following information):

* OS: [e.g. iOS]
* Browser [e.g. chrome, safari]
* Version [e.g. 22]

### Smartphone (please complete the following information):

* Device: [e.g. iPhone6]
* OS: [e.g. iOS8.1]
* Browser [e.g. stock browser, safari]
* Version [e.g. 22]

**Comment by zmaglica** [comment]
This issue impacts subscriptions to team Helix (based on team responsibilities) @haszari . Assigning as part of Gamma Triage process PcreKM-yM-p2.
