### ISSUE TITLE
[Deposits UI] Display notice for expected deposit delay due to upcoming holiday

### ISSUE THREAD

**Issue by thenbrent** [Automattic/woocommerce-payments#658]
I just noticed Stripe display a notice in the dashboard when a holiday is coming up and a payout / deposit will be delayed: 

![Image upload on 2020-05-18 at 10-18-14](https://user-images.githubusercontent.com/235523/82163948-61964600-98f1-11ea-9ff1-b1936b6e4590.png)

Our deposit estimation will eventually account for holidays (see: server issue 230). Once that's done, displaying a similar notice on the **Payment / Deposits** screen could help prevent confusion, and support tickets, around delays.

@LevinMedia do you agree or have other ideas how to address this?

**Comment by LevinMedia** [comment]
@thenbrent can you investigate whether or not we're able to get these messages through Stripe's API? If we can, I'll attach a needs design label to this issue.

**Comment by thenbrent** [comment]
@LevinMedia I had a brief look, but couldn't see anything that would make it explicitly available. I was originally thinking we'd use our own data source for that info, but aligning with the payout data is definitely the better approach.

@dechov do you know of any way with Stripe's API we could uncover it? e.g. maybe it could be inferred from the `arrival_date`?

**Comment by haszari** [comment]
Let's consider what we can do about this as part of upcoming refresh of deposits UI.

It might be simpler and more robust to add some wiggle room to the estimated deposit date, rather than try to refine our estimate to be more accurate.

**Comment by brucealdridge** [comment]
Closing as a stale issue. If there is any merchant requests for this please reopen.
