### ISSUE TITLE
Add Affirm & Afterpay Explat experiment

### ISSUE THREAD

**Issue by mgascam** [Automattic/woocommerce-payments#6592]
### Acceptance criteria

* First requirement
* Second requirement
* Third requirement
* etc.

### Testing instructions

1. Go to '…'
2. Click on '…'
3. Scroll down to '…'
4. Observe expected behaviour

**Comment by kalessil** [comment]
Closing: it was [decided](p1688078880415799/1687914398.433419-slack-C04VCT34PCP) to go beta with a regular feature flag (as estimated originally)
