### ISSUE TITLE
Progressive Onboarding: "Setup Payments" persists in task-list after PO completion

### ISSUE THREAD

**Issue by brandonwanA8C** [Automattic/woocommerce-payments#6601]
### Describe the bug
After the user is successfully onboarded with Progressive Onboarding (Payment Acceptance == true, KYC == false), the user still sees "Setup Payments" as the 3rd task un-checked in store task-list.

### To Reproduce
1. Merchant goes through Woo & WCPay onboarding with PO eligible data
2. Merchant sees PO completion screen: "you are eligible to start selling now"
3. Merchant wants to finish setup Store, by clicking on "WooCommerce" sidebar button
4. Merchant sees usual task-list, with "Setup Payments" untouched

### Actual behavior
Merchant sees usual task-list, with "Setup Payments" untouched

### Screenshots
See [Video](https://us02web.zoom.us/rec/share/yGyJMoLsc8f6J_JBfci88eZ8TEpnxNNIXbEILpRQMLEBkrWWdDCz-eUCcB5RZI7K.hj4BC1gHNRi0XT3b)  Passcode: *04acSf!
4:00~4:20

### Expected behavior
"Setup Payments" option should be checked. "Finishing setting up the deposit" should be the next step and it will be in the Payments "things to do" view.

**Comment by daquinons** [comment]
Thanks for the report, Brandon! Seems like it's the same as #5769, so closing in favor of that one where Design already confirmed desirable behavior! 👍
