### ISSUE TITLE
WCPay Sub with free trial has renewal charged immediately

### ISSUE THREAD

**Issue by csmcneill** [Automattic/woocommerce-payments#6610]
### Describe the bug

When using the built-in subscription functionality of WCPay, if a subscription uses a free trial, the first renewal payment (which should be charged when the trial finishes) is charged immediately.

### To Reproduce

1. Create a simple subscription.
2. Add a free trial to said subscription.
3. Purchase said subscription.
4. Navigate to **WooCommerce > Subscriptions**.
5. Note that there is a parent order of `0.00` and a renewal order.

### Actual behavior

The free trial logic added via WCPay Subs is not respected, and a renewal order is triggered even though the free trial has not elapsed.

### Screenshots

![Markup on 2023-06-28 at 19:13:22](https://github.com/Automattic/woocommerce-payments/assets/82999806/db8ee1ab-3cb5-4e0f-9286-bb0b3588cfbf)

![Markup on 2023-06-28 at 19:14:16](https://github.com/Automattic/woocommerce-payments/assets/82999806/5966acfa-eace-40f4-9eaa-e5a427432d75)

![Markup on 2023-06-28 at 19:13:40](https://github.com/Automattic/woocommerce-payments/assets/82999806/c9f97a57-24c3-4b6b-aee6-31c03f2cc8ad)

![Markup on 2023-06-28 at 19:12:50](https://github.com/Automattic/woocommerce-payments/assets/82999806/5edaf2ca-85c6-4c1c-a8ad-12165e5f78a9)

### Expected behavior

The free trial period is respected, and a renewal will not be charged until that expires.

### Additional context

p1687990729350239-slack-C03EE4CPPK5
6477696-zen

This might be related to https://github.com/Automattic/woocommerce-payments-server/pull/3548 (cc @james-allan)

**Comment by james-allan** [comment]
Thanks @csmcneill. @mattallan and I are on it.

This is indeed caused by the changes we recently deployed to server. This is caused by Stripe creating a $0 invoice for the free trial and it communicating with the site. We'll have to revert the changes to server to prevent further issues and find either a different way to resolve it or find a way to block this invoice webhook from firing to the site.

**Comment by james-allan** [comment]
> This is caused by Stripe creating a $0 invoice for the free trial and it communicating with the site.

I should clarify that the invoice is $0 on the Stripe dashboard and no actual charge has been made to the customer. It shows in WC as a full invoice because it is assumed to be a full renewal order.
