### ISSUE TITLE
Update references to Fraudulent Disputes

### ISSUE THREAD

**Issue by brucealdridge** [Automattic/woocommerce-payments#6611]
### Description

We recently retitled "fraudulent" disputes to "unauthorized transactions" in #6372. There are some additional references to fraudulent disputes which need to be updated.

### Additional context

p1687853312775169/1687801778.118189-slack-C02BW3Z8SHK

**Comment by Jinksi** [comment]
I've added this to the Highlighting Disputes Phase 1 project.

![image](https://github.com/Automattic/woocommerce-payments/assets/3147296/3d4131c8-152a-4af3-a6f1-14989711b6f5)
