### ISSUE TITLE
Advanced filters on transactions tables are broken

### ISSUE THREAD

**Issue by elizaan36** [Automattic/woocommerce-payments#6612]
### Describe the bug
The advanced filters on the transactions tables appear to be broken.

### To Reproduce

1. Go to WooCommerce > Payments > Transactions
2. Click on Advanced Filters
3. Choose "Add a filter"

### Actual behavior
I'm unable to configure any advanced filters on the Transactions table.

### Screenshots
<img width="653" alt="Screen Shot 2023-06-28 at 9 38 11 PM" src="https://github.com/Automattic/woocommerce-payments/assets/5121465/8ac274c5-a355-4edd-bf0c-8bfbe55de7d5">

### Expected behavior
User should be able to add an advanced filter to filter the Transactions tables.

cc @vbelolapotkov as I'm not sure who would take this one. I was able to reproduce on two sites and seems critical.

**Comment by daquinons** [comment]
Additional conversation p1688006903600379-slack-CGGCLBN58

**Comment by daquinons** [comment]
Duplicated of #6533
