### ISSUE TITLE
Unify payment method logos accross settings pages

### ISSUE THREAD

**Issue by KarlisJ** [Automattic/woocommerce-payments#6620]
### Describe the bug
We have a list of payment method icons in the `assets/images/payment-methods/` directory widely used across multiple pages. 

We have several inconsistencies in how we re-use these assets.

Icons for CC is significantly different from others as it have a "built-in outline" that other PMs don't. For this reason, the `PaymentMethodIcon` component has this line
```
{ 'has-icon-border': 'card' !== name }
```

which will add the `has-icon-border` class to all icons except the CC. 

1. We don't always target this class in our CSS because of the use of BEM. There is not global CSS definition for adding border to the icon when there's the additional `has-icon-border` class. In some cases, we have added it, but it's isolated by BEM conventions. 
2. When we do add the border, it creates several problems
- CC icon appears smaller then remaining
- Sofort icon has background color and rounded corners. Border doesn't have the border radius which stands out when zoomed in
- Affirm and Afterpay Icons has boarders in the asset which overlap with CSS border making the border looks thicker

### To Reproduce
The issue can be perfectly observe in Payments -> settings "Payment methods" block.

### Actual behavior
- CC icon is aligned off from rest icons
- Outlines are not consistent in design

### Screenshots
![Screenshot 2023-06-28 at 15 38 41](https://github.com/Automattic/woocommerce-payments/assets/24650518/28f0b8d3-b9b9-4c7b-886f-bf412bdf4120)

![image](https://github.com/Automattic/woocommerce-payments/assets/24650518/8d0541f9-9fa7-44b7-9887-2058d20dcdaf)

### Expected behavior
We should:
- Ask designers to prepare CC icon that is aligned with other icons
- Ask designers for Affirm and Afterpay icons without border
- Add global CSS for `has-icon-border` class that would add border that is consistent with all icons. 

### Additional context
p1687862667003019-slack-C04VCT34PCP

Currently `client/settings/payment-method-icon/style.scss` is trying to globally apply the rules but for some reason they are not picked up. Most likely due to different BEM accessors.

We're using `box-shadow: 0 0 0 1px #ddd;` which might have be related to issues with [Figma borders being applied differently than the browser does](https://threads.com/blog/34432545238/why-we-use-the-css-property-boxshadow-instead-of-border-in-our-app).

**Comment by KarlisJ** [comment]
Please see the slack thread in the "Additional context" to find logos for Affirm and Afterpay without borders.

**Comment by KarlisJ** [comment]
https://github.com/Automattic/woocommerce-payments/pull/6892 Has addressed the icons. Still need to unify the border rules in CSS.

**Comment by kalessil** [comment]
@KarlisJ: I was probably too fast to merge =) What's the level of effort to unify the border rules?

**Comment by KarlisJ** [comment]
@kalessil No it's fine. It was meant to be tackled in separate PRs. 

The border rule is a bit tricky CSS thing. So there's some uncertainty. I'm currently reaching out for assistance.

**Comment by KarlisJ** [comment]
Closed in https://github.com/Automattic/woocommerce-payments/pull/6892
