### ISSUE TITLE
Incorrect format for Saudi Riyal (SAR) and United Arab Emirates Dirham (AED) currencies

### ISSUE THREAD

**Issue by allie500** [Automattic/woocommerce-payments#6633]
### Describe the bug

We were recently informed by a merchant that WCPay displays an incorrect format for Saudi Riyal (SAR) and Dubai Dirham (AED) currencies (see ticket 6461033). We are currently setting the thousand separator to a comma and the decimal separator to a period for both currencies. It should be the inverse.

UAE related localization and currency data:
https://github.com/Automattic/woocommerce-payments/blob/develop/i18n/locale-info.php#L30-L45
https://github.com/Automattic/woocommerce-payments/blob/develop/i18n/currency-info.php#L129-L132

KSA related localization and currency data:
https://github.com/Automattic/woocommerce-payments/blob/develop/i18n/locale-info.php#L3070-L3085
https://github.com/Automattic/woocommerce-payments/blob/develop/i18n/currency-info.php#L725-L728

As part of my investigation, I checked with our team that handles i18n. They shared their sources that showed it should be a comma as the thousands separator and a period as the decimal separator. One of the sources was [CLDR](https://www.unicode.org/cldr/cldr-aux/charts/24/summary/ar.html) which is what we used when Multi-Currency was being developed and the two above linked files were being built. Apparently it was just an error during development.

[CLDR - Arabic - Number Formatting Patterns - Standard Patterns when using Western Digits (latn) - standard-currency](https://www.unicode.org/cldr/cldr-aux/charts/24/summary/ar.html#3471)

`¤#,##0.00`

### To Reproduce

1. Go to WooCommerce > Settings > Multi-currency
2. Add SAR and AED as currencies.
3. Add the multi-currency widget to your site's sidebar if not already there.
4. Go to a single product page and select SAR and then AED to see the incorrect format. See screenshots below.

### Actual behavior

The price is displayed with the incorrect currency format: `1.234,56`

### Screenshots

SAR format incorrect:
![Screenshot on 2023-06-29 at 15_40_06](https://github.com/Automattic/woocommerce-payments/assets/60988591/23d9b616-f1c8-46df-a152-96f8d2d33d61)

AED format incorrect:
![Screenshot on 2023-06-29 at 15_41_21](https://github.com/Automattic/woocommerce-payments/assets/60988591/56f2e9ef-6ff1-4703-aabd-af99ec2fc52d)

### Expected behavior

The price is displayed with the correct currency format: `1,234.56`

### Additional context

Slack links:
- p1687923858267909-slack-C7U3Y3VMY
- p1687957037838519-slack-C01B8KNUYSW
- p1687967942985629-slack-C02AED43D

**Comment by htdat** [comment]
This issue impacts `Multi-Currency`, so assigning to Sigma (@dwainm as team lead) (based on team responsibilities Pc2DNy-3z-p2). Assigning as part of Gamma Triage process PcreKM-yM-p2.
