### ISSUE TITLE
WooPay shoppers blocked from order success page by a security wall 

### ISSUE THREAD

**Issue by pierorocca** [Automattic/woocommerce-payments#6638]
Actual: An authenticated WooPay shopper, on a shortcode checkout site, when successfully placing an order is frequently presented with a security screen and must either login to the site or verify their email address to access the order thank you page.

Expectation: Under no circumstance should a WooPay user who places an order be presented with a security screen in order to access the thank you page on an order they just placed.

![image](https://github.com/Automattic/woocommerce-payments/assets/109928953/0538c419-95f4-41d5-a3ba-49adc2f787b8)

Cross posted to https://github.com/Automattic/woopay/issues/1951, the primary ticket for this issue. Duplicated here for extra visibility and urgency.

**Comment by pierorocca** [comment]
https://d.pr/v/z194ji

**Comment by pierorocca** [comment]
Renewal orders (not WooPay related) may possibly be impacted too by whatever security changes were put in place.

https://d.pr/v/PddHiv

cc @thenbrent

**Comment by thenbrent** [comment]
> Under no circumstance should a WooPay user who places an order be presented with a security screen in order to access the thank you page on an order they just placed.

Yeah for sure. For backstory on why this was introduced, see p3btAN-2hQ-p2; however, it appears the WooPay redirect use case wasn't considered as being impacted by those (and I agree, the verification shouldn't be required immediately after payment.)

> Renewal orders (not WooPay related) may possibly be impacted too by whatever security changes were put in place.

They will be for sure in certain situations, like coming on site to pay for a failed renewal order; however, the login and/or email verification requirement on those is more reasonable.

**Comment by pierorocca** [comment]
Thanks @thenbrent. 

Here are screen captures for the renewal orders that fail for me when attempting to view the order.

![image](https://github.com/Automattic/woocommerce-payments/assets/109928953/7f9055dd-563e-4a28-89a3-4172d52bb7f6)

![image](https://github.com/Automattic/woocommerce-payments/assets/109928953/a984786f-2263-4099-9253-f91af27410dc)

**Comment by pierorocca** [comment]
Checking to see if I'm actually missing the page on my test site.

**Comment by pierorocca** [comment]
OK my site had a few issues which I've resolved. @thenbrent clicking on the renewal order on my site, which may still have issues, takes me to the My Account dashboard not the order details. Could you double check please?

**Comment by pierorocca** [comment]
Closing as https://github.com/Automattic/woocommerce-payments/pull/6559 was merged yesterday.
