### ISSUE TITLE
Product service-related exceptions during checkout

### ISSUE THREAD

**Issue by RadoslavGeorgiev** [Automattic/woocommerce-payments#6645]
### Describe the bug

During checkout, there is a consistent `Exception: Invalid product.`.

The exception is being handled, and it does not affect customers, but during debugging I'm typically monitoring for all sorts of errors, and every time I get at least a couple of those (worse with subscriptions).

### To Reproduce

1. Enable Xdebug and start listening for exceptions.
2. Attempt checkout. Any payment method, any product works.
3. Observe the error.

### Actual behavior

`WC_Payments_Product_Service`'s `maybe_schedule_product_create_or_update` and `limit_subscription_product_intervals` methods are linked to the `save_post` hook, and try to retrieve a product based on the received post ID.

Whenever the post ID is not associated with a product, `wc_get_product()` throws an exception.

### Screenshots

https://github.com/Automattic/woocommerce-payments/assets/5311119/6cdc84a5-0ed0-4750-91a6-fa45f6f9caf4

### Expected behavior

Checkout should not trigger any exceptions.

### Desktop (please complete the following information):

Any

**Comment by jessy-p** [comment]
Moved to next Sprint - waiting for review from Quark.

**Comment by RadoslavGeorgiev** [comment]
Closed by https://github.com/Automattic/woocommerce-payments/pull/6644
