### ISSUE TITLE
QuickPay buttons don't fire on Pay For Order page (manual order payment page)

### ISSUE THREAD

**Issue by lynnjat7** [Automattic/woocommerce-payments#6650]
### Describe the bug
When a shop's customer has to pay for an order manually, they receive an email that directs them through to their My Account area on the website, to the Pay For Order page, to pay. This is a different page than the typical Checkout page.

You can also access this page if you are logged into your account and go to the My Account area, under Orders --> find an order in Payment Pending status and click the "Pay" button.

On the Pay For Order page, quick pay buttons (Google Pay and Apple Pay) are no longer visible.

You *can* see them in version 5.9.1 of WCPay
You *cannot* see them in version 6.1.1 of WCPay

Will test further to see if I can pinpoint when the bug was introduced.

### To Reproduce
1. Install and configure WooCommerce Payments and check the option to enable Quickpay buttons in the settings. (Double check: they should show up on the product/cart/checkout page, Google Pay in Chrome and Apple Pay in Safari.)

2. Create a manual order - can be for an existing customer on the site or a guest. It should be in Payment Pending status.
3. Use the Order Actions on the order to send an invoice email to the customer, like this:

![eYFIaK.png](https://github.com/Automattic/woocommerce-payments/assets/109691691/4e31e061-9365-4c76-a56e-b9617669c9fe)

4. Alternately --> if it is for an existing customer, you can log into their account and go under My Account > Orders, and click the "Pay" button next to the pending order, like this:

![gitNlv.png](https://github.com/Automattic/woocommerce-payments/assets/109691691/da98fc45-05a6-4f0c-bc66-89df05dad6b2)

5. Either way, this loads the Pay For Order page --> the QuickPay buttons are missing (when testing with version 6.1.1 of WCPay).

6. Testing this with version 5.9.1 shows that the quick pay buttons do show up on this page, as shown here:

![trr8no.png](https://github.com/Automattic/woocommerce-payments/assets/109691691/ac61568e-8dee-42d5-99a4-f4be7fe07077)

### Expected behavior
The quick pay buttons show show here as shown in the last screenshot above. Not sure exactly when this stopped working, somewhere between 5.9.1 and 6.1.1.

### Desktop (please complete the following information):

* Browser: tested in both Chrome for Google Pay, and Safari for Apple Pay

### Additional context
Wordpress version 6.2.2
WooCommerce version 7.8.1

**Comment by lynnjat7** [comment]
6480797-zen

**Comment by htdat** [comment]
This issue impacts `Additional Payment Methods (including Apple Pay / Google Pay)`, so assigning to team Fusion (@anu-rock as team lead) (based on team responsibilities Pc2DNy-3z-p2). Assigning as part of Gamma Triage process PcreKM-yM-p2.

**Comment by anu-rock** [comment]
Moved this to Fusion's backlog. Thanks, @htdat.

**Comment by aheckler** [comment]
This came up yesterday in the WC community Slack:

https://woocommercecommunity.slack.com/archives/C1KAZ91E3/p1691008800568199

**Comment by pierorocca** [comment]
@hsingyuc do you happen to observe this issue in your testing?

**Comment by elazzabi** [comment]
I can replicate this issue and I'm working on a fix. This was indeed introduced by [a commit](https://github.com/Automattic/woocommerce-payments/commit/8c3b4ffc0edb43b5b93b20ae278fee2d1f6c27ec) ~4 months ago.

**Comment by hsingyuc** [comment]
@pierorocca  I didn't test quick pay buttons (Google Pay and Apple Pay) since it's a slightly different flow and the logic is separate.  I tested [this PR](https://github.com/Automattic/woocommerce-payments/pull/7535) and it doesn't affect the pay-for-order flow I did.
