### ISSUE TITLE
"Set up payments" step in setup wizard crossed out when WooCommerce Payments is enabled

### ISSUE THREAD

**Issue by francoishvz** [Automattic/woocommerce-payments#6658]
### Describe the bug
The "Set up payments" step (#3) in the setup wizard for a new WooCommerce site is not being completed/crossed out when WooCommerce Payments is enabled as a payment gateway.

![OHppgs.png](https://github.com/Automattic/woocommerce-payments/assets/104560284/ceff9b93-e7cb-456b-9a77-b129b1452c30)

### To Reproduce

1. Create a brand new store.
2. Follow the setup wizard's **Set up payments** step and enable WooCommerce Payments.
3. Once enabled, continue with the Setup Wizard process and notice that the **Set up payments** step is not completed.

### Actual behavior

With WooCommerce Payments activated, the **Set up payments** step is not completed. If you add "direct bank transfer" it will work.

### Expected behavior
When enabling WooCommerce Payments, this should mark the **Set up payments** step as complete.

### Additional context

6479027-zen

**Comment by zmaglica** [comment]
I wasn't able to reproduce the issue. Usually cleaning the cache would do the trick, but that's not an ideal solution. I will move it to the prioritization column, so it can be looked into in more detail.

**Comment by RadoslavGeorgiev** [comment]
Tagging @Automattic/moltres as a part of the backlog prioritization call, in accordance with Pc2DNy-3z-p2. Is it relevant to your focus area/backlog?

**Comment by daquinons** [comment]
Closing as duplicated of #5769
