### ISSUE TITLE
If a zone region is specified in the shipping zone settings - Apple and Google Pay disregard that shipping zone and move on to the next one

### ISSUE THREAD

**Issue by grig-23** [Automattic/woocommerce-payments#6659]
### Describe the bug
If a zone region is specified in the shipping zone settings - Apple and Google Pay disregard that shipping zone and move on to the next one.

### To Reproduce

1. We will need two shipping zones - one with a specific region in a country specified (E.G. Bavaria, Germany, or Attica, Greece), and one could be a catch-all for all other geographic areas around the world.
2. Add different shipping methods to the zones so you could clearly see methods from which shipping zone are returned. I had a flat rate shipping method with the price of 900$ in the second catch-all zone.
3. On the product page, click the Apple Pay button and edit your address to match the first zone. I used Sankt-Jakobs-Platz 1, 80331 München or Antoniou Travlantoni 1, Zografou 157 73, Greece.
4. Shipping methods from the second shipping zone are shown, despite the address being a match for the first shipping zone.
5. (optional) if we enter the same address at the checkout page - we will see the correct shipping methods from the first shipping zone.

### Actual behavior

Shipping methods from the second shipping zone are shown, despite the address being a match for the first shipping zone.

### Screenshots

<img width="1535" alt="Screenshot 2023-07-03 at 19 19 32" src="https://github.com/Automattic/woocommerce-payments/assets/13084901/85a98cc6-840c-4b5a-b883-a6e9f69fbca4">

<img width="386" alt="Screenshot 2023-07-03 at 19 20 11" src="https://github.com/Automattic/woocommerce-payments/assets/13084901/e35ae7c7-5530-45bd-b38d-9e3a40159212">

### Expected behavior
Shipping methods from the first shipping zone should be shown, since the address is a match for the first shipping zone.

### Desktop (please complete the following information):

* OS: Mac OS Ventura 13.4.1
* Browser Safari
* Version 16.5.1 (18615.2.9.11.7)

### Additional context
6491771-zen

**Comment by grig-23** [comment]
ZIP code ranges can be used as a workaround - so instead of Bavaria, Germany we would use Germany as a zone region and a range of zip codes in `Limit to specific ZIP/postcodes` field.

**Comment by csmcneill** [comment]
@grig-23 Is this specific to WCPay, or can we also reproduce this with [Stripe](https://woocommerce.com/products/stripe/?aff=10486&cid=1131038) and [WooCommerce Square](https://woocommerce.com/products/square/?aff=10486&cid=1131038)?

**Comment by htdat** [comment]
This issue impacts `Additional Payment Methods (including Apple Pay / Google Pay)`, so assigning to team Fusion (@anu-rock as team lead) (based on team responsibilities Pc2DNy-3z-p2). Assigning as part of Gamma Triage process PcreKM-yM-p2.

**Comment by anu-rock** [comment]
Moved this to Fusion's backlog. Thanks, @htdat.

**Comment by gpressutto5** [comment]
Hi @grig-23! Is this issue still reproducible? I've tried using Brazil, Brazil's specific state, and Rest of the world and it worked as expected as long as the State specific zone is above the country zone.

![image](https://github.com/Automattic/woocommerce-payments/assets/12385501/56ae22d9-e598-49a0-81f3-d34f528758d5)

![Feb-13-2024 14-36-21](https://github.com/Automattic/woocommerce-payments/assets/12385501/64da2dfe-13dd-4e1e-bacf-b538e2fdb46f)

**Comment by gpressutto5** [comment]
I'm closing this issue for now. Feel free to reopen it if the problem still exists.

**Comment by grig-23** [comment]
@gpressutto5 apologies for the delay! Indeed, I can no longer replicate this issue, thank you for closing!
