### ISSUE TITLE
WC_Payments_Action_Scheduler_Service::schedule_job() is causing slow downs

### ISSUE THREAD

**Issue by prettyboymp** [Automattic/woocommerce-payments#6662]
The `WC_Payments_Action_Scheduler_Service::schedule_job()` can get called dozens of times during the process of creating an order.  Each time the callback is hit, calling `as_unschedule_action()` is adding quite a bit of overhead.  This handling was added in #1295.  

https://github.com/Automattic/woocommerce-payments/blob/db6e4446b9f246897c116c56fee90475fb2e29d0/includes/class-wc-payments-action-scheduler-service.php#L147-L153

Do we need to unschedule and reschedule the job, or can we simply call `as_has_scheduled_action()` instead?

`as_has_scheduled_action()` doesn't require that the query for the scheduled action be ordered by the date, so it doesn't have the same query issues with requiring a filesort that the normal query to get the next action does.

cc @dmallory42

**Comment by htdat** [comment]
Thanks for the report. We have prioritized it. In case, you need to fix this soon, let us know. 

It seems related to this issue https://github.com/Automattic/woocommerce-payments/issues/5279 by @marcinbot

**Comment by zmaglica** [comment]
I will close this issue in favor of this issue:  #5279
