### ISSUE TITLE
Branding rollout: Change WordPress.org logo for WCPay

### ISSUE THREAD

**Issue by oaratovskyi** [Automattic/woocommerce-payments#6669]
### Description
As part of the WooPayments branding rollout, we need to change the following assets of the plugin:
- icons
- banners
- images
- readme.txt (text in the plugin page https://wordpress.org/plugins/woocommerce-payments/)
- adjust logo padding
- change Woo Payments to WooPayments as described in https://github.com/Automattic/woocommerce-payments/issues/6339

### Designs
- paJDYF-7Sw-p2#comment-19439
- 6VfBF8B9vw15Y7897Y6V0b-fi-28_30

### Dev notes
They all are located at https://github.com/Automattic/woocommerce-payments/tree/develop/wordpress-org-assets.
How to release - PaJDYF-933-p2

### Additional context
paJDYF-7Sw-p2#comment-19082

**Comment by dlcallaway** [comment]
@oaratovskyi Is it also possible to tackle updating the plugin title and copy to change all instances of "WooCommerce Payments" to "WoPayments? as part of this issue? if it's helpful, I can pull the current content into a Google Doc and highlight all the instances that need to change. 

I'm also not familiar with how URLs work on .org — do you know what the level of effort is to request a change and a redirect? It's not something that's critical to include on rollout but a nice to have.

**Comment by oaratovskyi** [comment]
> Is it also possible to tackle updating the plugin title and copy to change all instances of "WooCommerce Payments" to "WoPayments? as part of this issue?

Sure thing! I'll just change occurrences in this file https://github.com/Automattic/woocommerce-payments/blob/33a3b1188fc96fe69176bdda75f21a203588acb1/readme.txt
No need to put in the G-Doc, but thanks!

> I'm also not familiar with how URLs work on .org — do you know what the level of effort is to request a change and a redirect? It's not something that's critical to include on rollout but a nice to have.

Good question! I'll ask the team because I'm not familiar too.

**Comment by oaratovskyi** [comment]
Asked here p1689019702591339-slack-CGGCLBN58

**Comment by dlcallaway** [comment]
@oaratovskyi Awesome, thank you!

**Comment by oaratovskyi** [comment]
> I am 99% sure the url is built off of the slug, which I don’t think can ever be changed due to it is part of the whole naming structure, including the folder name.
The WooCommerce Shipping & Tax extension still has the woocommerce-services slug and url: https://wordpress.org/plugins/woocommerce-services/

@dlcallaway here's the best answer I got so far, big thanks to @jessepearson!

I guess we can explore URL one in a separate issue (I'll create one) because it might take some time. Since we have a code freeze on Friday, we may not have time to include URL redirect / URL change.  What do you think?

**Comment by jessepearson** [comment]
Another example would be _WooCommerce Blocks_ this is the url to the plugin at .org: https://wordpress.org/plugins/woo-gutenberg-products-block/

I don't think it's possible to change a plugin's slug once it is created at all, then it would be defined as a new plugin.
