### ISSUE TITLE
Order dispute list view by `respond by` column

### ISSUE THREAD

**Issue by brucealdridge** [Automattic/woocommerce-payments#6692]
### Description

In #6666 the `Disputed on` column was hidden on the disputes listing page. Currently, the list view is still ordered by this column.

The sort order should be updated to use a visible column instead. `Respond by` is the obvious choice.

Sorting by `DESC` will show the dispute furthest from the current date first. Using `ASC` will show the oldest dispute first as values are shown in this column for old and responded to disputes. Responded to and older disputes should have this column empty which will likely also affect the CSV report generated in WCPay and on Server.

An outstanding task in #6355 is to make the `Respond by` column more dynamic.

**Comment by shendy-a8c** [comment]
> make the Respond by column more dynamic

Won't sorting `ASC` enough as with filter `awaiting_response`, we'll show the most urgent disputes at the top?

**Comment by brucealdridge** [comment]
> Won't sorting `ASC` enough as with filter `awaiting_response`, we'll show the most urgent disputes at the top?

Good thinking, that would work for the awaiting response. I'm unsure if this would be desirable or not when using the all disputes filter.

**Comment by brucealdridge** [comment]
After much discussion and passing this issue around it is being closed.

Setting the default sort to the `respond by` column using `ASC` would work correctly for the default pageview with `Needs Response` filter. However, changing the filter to `All disputes` would show the oldest disputes first. 

Ideally, the desired sort of the `respond by` column would be to sort by future dates `ASC` and past dates `DESC`. This is not something we can do with the current table component easily.

Data shows that most merchants have less than 2 active disputes. Leaving the current default sort by `created_on` `desc`, while not ideal is a middle ground between the complications to work around in changing this.
