### ISSUE TITLE
Update WooPay express button setting to default enabled for product/cart/checkout pages

### ISSUE THREAD

**Issue by malithsen** [Automattic/woocommerce-payments#6699]
### Describe the bug

When enabling WooPay for the first time, the WooPay button should be enabled on all pages by default.
Currently, the button is disabled on all pages when enabling WooPay for the first time.

Express button location preference should persist when a merchant disables and re-enables WooPay after the first time.
 
### To Reproduce

1. On a fresh site, go to Payments -> Settings
2. Enable WooPay in the "Express checkouts" section
3. Go to "Customize"
4. Note that none of the pages are preselected.

### Actual behavior

None of the express buttons are preselected

### Screenshots

![SCR-20230706-jh6](https://github.com/Automattic/woocommerce-payments/assets/6216000/c2f8dc6d-2379-4f33-b956-ca3fa87054c6)

### Expected behavior

WooPay express button should be preselected on all available pages when enabling WooPay for the first time.

**Comment by zmaglica** [comment]
This issue impacts WooPay Checkout button, so assigning to Heisenberg (based on team responsibilities) @bborman22 . Assigning as part of Gamma Triage process PcreKM-yM-p2

**Comment by bborman22** [comment]
cc @frosso Just as an update @zmaglica, @frosso has returned as team lead of Heisenberg for the triage pings.
