### ISSUE TITLE
Disputes Listing: Highlight urgent (< 72h) dates with smart date column, ❗️ tooltip & red colouring

### ISSUE THREAD

**Issue by brucealdridge** [Automattic/woocommerce-payments#6702]
### Description

In the disputes listing page Payments > Disputes. The `Respond by` column needs to be changed into a smart date column. When a dispute is due within 72hours, the text must be red with a ❗️ showing the time left in days.
When the due date is greater than 72hours, the date will continue to be shown as it currently is.

The column should also be retitled `Response date`. CSV exports must not be changed (headers or content).

![image](https://github.com/Automattic/woocommerce-payments/assets/57298/5f6831c8-a47e-49c7-a210-d6243cac4ad2)

**Comment by Jinksi** [comment]
> The column should also be retitled `Response by` as in the design mockup.

I've seen different versions of this column header title (e.g. `Response date`) in the Figma design – asked in Figma to confirm: RiEQmaKRI7u9USAI3lyZz0VX-fi-2957_296960

**Comment by Jinksi** [comment]
Confirmed: the column header title should be `Response date` since it represents future and past dates.
(RiEQmaKRI7u9USAI3lyZz0VX-fi-2957_296960)
