### ISSUE TITLE
Fees show they're applied to the Authorize amount instead of Capture amount

### ISSUE THREAD

**Issue by jtobiesen** [Automattic/woocommerce-payments#6721]
### Describe the bug
When the authorize and capture payments feature is enabled, merchants see that the fee is based off the authorized amount. The fee is correctly calculated based on the captured amount, but this is not reflected in the order notes. 

### To Reproduce

1. Go to WooCommerce Payments settings and the Issue an authorization on checkout, and capture later setting.
2. Complete a transaction that authorizes the payment. 

### Actual behavior

- In the order notes and when inspecting the payment ID, the fee shows that it is based off the authorized amount. 

- The fee is correctly calculated based on the capture amount. 

### Screenshots

- The initial authorization is for $108.21, but the capture is for $50. 
- The fee shown ($1.75) is for the captured amount of $50, not the authorized amount, which would have a fee of $3.44 like - in the second photo. 
- The third photo shows that the transaction fee under the order details is correctly reflected both when the payment is authorized and changes when the payment is captured. 

![Markup on 2023-07-10 at 10_06_03](https://github.com/Automattic/woocommerce-payments/assets/101466957/50c0a4ff-8e2d-4805-a9e1-d557f9365a44)
![Markup 2023-07-10 at 09 58 55](https://github.com/Automattic/woocommerce-payments/assets/101466957/f71f1ce0-631c-4917-ae0e-d4087bfe47e1)
![Annotation on 2023-07-10 at 19-25-08](https://github.com/Automattic/woocommerce-payments/assets/101466957/c71a360d-98b7-4f5c-9ae2-93697b90cf9b)

### Expected behavior

- The fee should reflect the correct amount it's applied to. 
- The initial authorized amount should show the fee that is associated with that amount. 
- When the payment is captured later for a different amount, a new note should reflect the new fee, and final fee, that is applied to the captured amount.

### Desktop (please complete the following information):

* OS: 13.4.1 
* Browser Chrome
* Version: WooCommerce Payments v 6.1.1

**Comment by jtobiesen** [comment]
6453324-zen

**Comment by htdat** [comment]
This issue impacts `Fees, Transactions (Auth and Capture), Refunds`, so assigning to Pulsar (@kalessil as team lead) (based on team responsibilities Pc2DNy-3z-p2). Assigning as part of Gamma Triage process PcreKM-yM-p2.

I found out this is reported based on this convo between HEs: p1688992722491269-slack-C3NCP7ZJ6

**Comment by kalessil** [comment]
The issues in Pulsar's Sprint backlog, but we have to re-check how the refunding process is expected to act on the charge fees from a product perspective.

**Comment by kalessil** [comment]
Dev notes: There is [a flag](https://stripe.com/docs/api/refunds/create#create_refund-refund_application_fee) for Stripe's API to handle the refunding of fees as well, but it seems we are not using it.

TBD: a bit of manual testing before and a kickoff conversation on product expectation.

**Comment by kalessil** [comment]
Started a wider conversation on product-side expectations: pdjVC1-1Lb-p2

**Comment by kalessil** [comment]
Confirming: both green rectangles on the screenshots are subject to fixing.

**Comment by kalessil** [comment]
To summarize a bit constraints:
- fees are not subject to refunds (a historical constraint), so on refund the fee amount is not changing
- when captured amount is less than authorize, fee shall be reduced accordingly

**Comment by kalessil** [comment]
Flagging the need to collect/align on requirements:
- the way it is handled now is the partial refund under the hood, and we don't refund the fees
- but it's quasi-refund, and we better to align with stakeholders representing business side of things

**Comment by kalessil** [comment]
On-hold: we are re-evaluating functional requirements in pdjVC1-22n-p2

**Comment by kalessil** [comment]
The path forward is cleared out, and the following adjustments are needed:
- rely on the captured amount for timeline entry rendering
- actualize the fee on capture (we don't support multi-capture yet, so it should be good)
- actualize order meta which holds the fee value on capture

**Comment by kalessil** [comment]
@mgascam: can you please resume working on this and update the remaining estimate?
