### ISSUE TITLE
Excessive amount of redundant attempts to fetch payment method during payment processing

### ISSUE THREAD

**Issue by timur27** [Automattic/woocommerce-payments#6731]
### Describe the bug
The scope of this issue is UPE - the split UPE and the UPE with the deferred intent creation. As a precautionary measure, other settings should be tested as part of this issue. 

### To Reproduce
1. Enable deferred intent creation UPE 
2. Go to the checkout and place an order
3. Note that the checkout lasts longer than expected (first screenshot), and during this time, you are not redirected
4. Open the server's `access.log` (second screenshot) and find the significant number of requests to get the payment method

![image](https://github.com/Automattic/woocommerce-payments/assets/22319444/ddd63b55-8efb-4cca-a985-5bc55b988b30)

![image](https://github.com/Automattic/woocommerce-payments/assets/22319444/1038577c-6648-46d2-a37b-5571a5eddcac)

The same symptoms are to be observed for the split UPE, but there's no visual regression from the user perspective happening, most probably because the redirect occurs before the hook's callback is executed. Still, the payment method is fetched more times than expected. This is also why the issue remained invisible/hidden for some time.

### Expected behavior
As part of setting the email title, only one payment method should be fetched equal to the one used during the checkout.

### Additional context
Per my research, this is happening because of the hook that sets the method title for the email during order processing. The [payment method is fetched multiple times in this place](https://github.com/Automattic/woocommerce-payments/blob/develop/includes/payment-methods/class-upe-payment-gateway.php#L1073), as result of this callback being attached to a hook multiple times [here](https://github.com/Automattic/woocommerce-payments/blob/develop/includes/payment-methods/class-upe-payment-gateway.php#L120).

**Comment by csmcneill** [comment]
Related discussion: p9F6qB-cLx-p2

6530522-zen is likely affected.

**Comment by pierorocca** [comment]
Could we get an update on this @timur27 @frosso even if it's a "still working on it" kind of update?

**Comment by frosso** [comment]
@pierorocca there's a PR being reviewed with a fix to ensure we're not making as many requests: https://github.com/Automattic/woocommerce-payments/pull/6826

**Comment by timur27** [comment]
The fix has been merged. @frosso @pierorocca
