### ISSUE TITLE
PO UX & copies feedback from "LT/DRI weekly meeting"

### ISSUE THREAD

**Issue by brandonwanA8C** [Automattic/woocommerce-payments#6741]
July-11-2023 "New WCPay Active Merchants: DRIs <> LT Weekly Sync"
The team reviewed the new TOFU & PO UX, and had the following UX and Copy suggestions:

1) "Inconsistent punctuation (periods) usage on this screen"
<img width="1078" alt="Screenshot 2023-07-11 at 9 16 58 AM" src="https://github.com/Automattic/woocommerce-payments/assets/113071364/4869de70-c32d-4487-b9e7-7b81c1965029">

2) "Consider using another word 'stakeholder' rather than 'shareholder' in this instruction"
<img width="786" alt="Screenshot 2023-07-11 at 9 19 04 AM" src="https://github.com/Automattic/woocommerce-payments/assets/113071364/88136e26-9268-433f-bf3c-b5331c7e47a5">

should be fairly simple updates.

cc @daquinons  @elizaan36

**Comment by elizaan36** [comment]
We can remove the period on the task titles for consistency. The period on the subtext is expected.

"Stakeholder" sounds a bit corporate for the new merchant perspective. Maybe "Authorized team member" rather than shareholder.

**Comment by dmallory42** [comment]
Hi! Thanks for opening this issue. I opened a PR [here](https://github.com/Automattic/woocommerce-payments/pull/6793) which removes the period and uses @elizaan36's suggested copy. Let me know if it looks okay, if any further tweaks to the form copy are required I can use this issue to handle them. Thanks!
