### ISSUE TITLE
New Tracking Events for Onboarding

### ISSUE THREAD

**Issue by dmallory42** [Automattic/woocommerce-payments#6750]
### Description

In order to help us better understand our onboarding flow, there are some new events we would like to add.

- We need to add a tracking event in PHP in the client when the jetpack connection is done, right before the Stripe redirection. 
- Have a single tracking event for every entry point to the onboarding (currently we have events like `wcpay_account_clicked`, etc. depending on the entry point).

This may end up being one event, or 2, or more, depending on looking at the code and seeing where the events would fit. 

The desired outcome is that we can see exactly how many people entered the onboarding, along with where they eventually ended up (depending on which onboarding flow was being used).

**Comment by daquinons** [comment]
After additional discoveries in our current Tracks we've decided to close this issue for now p1689236413968729/1689227159.550309-slack-C03KTTK2YMA

We'll reopen it if it's finally needed
