### ISSUE TITLE
E2E Test: Checkout with Google Pay

### ISSUE THREAD

**Issue by anu-rock** [Automattic/woocommerce-payments#6758]
### Description

Create an E2E test to validate the flow for checking out with Google Pay.

### Acceptance criteria

An E2E test that checks whether a shopper can successfully use Google Pay to purchase an item. See the related [critical flow](https://github.com/Automattic/woocommerce-payments/wiki/Testing-instructions-for-critical-flows#checkout-with-payment-request) instructions.

### Additional context
* paJDYF-7q7-p2
* p1686744024688229-slack-C04DN7Q51KK
* Possible roadblock - paJDYF-76e-p2

**Comment by vbelolapotkov** [comment]
I don't think it's possible, so closing this one. However, pinging @c-shultz in case you know the ways to automate that and want to reopen.
