### ISSUE TITLE
Consider adding a query prop to Transactions filters and list

### ISSUE THREAD

**Issue by luizreis** [Automattic/woocommerce-payments#676]
@vbelolapotkov suggested [here](https://github.com/Automattic/woocommerce-payments/pull/618#discussion_r418067144) that we pass query as a prop to `TransactionsFilters` and `TransactionsList` to give us better testability by breaking dependency on navigation package.

**Comment by reykjalin** [comment]
I just want to advise that if we decide to use our own query prop we need to manually implement the `onQueryChanged` function we now get for free using the `@woocommerce/navigation` package.

We get a lot of things for free that "Just Work™" by using the `@woocommerce/navigation` package so I think we should consider carefully whether we want to roll our own logic here or whether we should use the navigation package.

What specifically would be easier to test without the navigation dependency? Are there any tests in the navigation package that would make those tests we're thinking of redundant?

**Comment by deepakpathania** [comment]
@luizreis @reykjalin Triaging this right now and wondering whether we arrived at a conclusion for implementing this or not based on the discussion, could either of you please update the same?

**Comment by luizreis** [comment]
Hi @deepakpathania - This was a small refactor suggestion to move the `@woocommerce/navigation` dependency higher up the chain, to allow easier mocking of some components. Especially because we currently use real methods from the navigation package, like `updateQueryString`, to simulate testing scenarios.

IMO this is a very-low priority issue, given that it's possible to set up specific scenarios in tests using `updateQueryString`, and it might make sense to close this issue since it hasn't popped up since it's been created.

@vbelolapotkov - What do you think? Is this still relevant?

**Comment by deepakpathania** [comment]
Thanks for clarifying @luizreis. Closing this, for now, we can reopen if still needed.
