### ISSUE TITLE
Refactor: Change Payment_Intent_Status to Intent_Status

### ISSUE THREAD

**Issue by htdat** [Automattic/woocommerce-payments#6773]
### Description

From https://github.com/Automattic/woocommerce-payments/pull/6586#discussion_r1250367313, change the name of current class name `Payment_Intent_Status` to `Intent_Status` so that it can be agnostic for either payment and setup intents.

https://github.com/Automattic/woocommerce-payments/blob/e3f1820ac05b9932a94ce1900d070363078c7eff/includes/constants/class-payment-intent-status.php#L20-L20

### Acceptance criteria

* Find all occurrences of `Payment_Intent_Status` and makes changes.
* May change the filename too.
* PHP tests should be run fine.

**Comment by naman03malhotra** [comment]
@htdat do you plan to pick this up in upcoming sprint?

**Comment by htdat** [comment]
yeah, let me pick up this one.
