### ISSUE TITLE
Show clear info in UI when there will be no payout because merchant balance is below deposit minimums (e.g. AUD$5)

### ISSUE THREAD

**Issue by EjayhanFernandes** [Automattic/woocommerce-payments#6774]
### Description

The estimated deposit date displayed for users in WooCommerce Payments may draw confusion when the minimum deposit amount is not yet met. 

![https://d.pr/i/r3y5wm+](https://d.pr/i/r3y5wm+)
For example: The minimum deposit amount for AUD currency is $5, as stated in the [doceumentation](https://woocommerce.com/document/woocommerce-payments/deposits/deposit-schedule/#minimum-deposit-amounts). However, it is worth noting that the dashboard does not provide a clear indication of this requirement. As a result, users may be left wondering why their deposit did not go through on the estimated date.

To improve the user experience, we can incorporate a tooltip or a similar prompt when the deposit amount is below the minimum requirement. This would explain that the deposit will be processed once the minimum balance is exceeded. Additionally, we can include a note about minimum balances in a prominent location in the user interface

### Additional context

- [Slack conversation](https://a8c.slack.com/archives/C7U3Y3VMY/p1689309505749639)
- 6535410-zen

**Update**
A proposed solution for this issue is a banner on the **Payments → Overview** screen, as per @bradyv's [design](https://www.figma.com/file/aDFNTeogq2cXSr4Nqeni8g/%5BWCPay%5D-Instant-Deposits?type=design&node-id=294-83778&mode=design&t=exSeHwn5tRxr33zg-4).

When the available balance is below the minimum deposit threshold:
* Remove the schedule string as it causes confusion when deposits aren't happening
* Show the banner below
      <img width="500" alt="image" src="https://user-images.githubusercontent.com/889872/282548013-cdba6fc9-faa5-4b0f-8695-844fe3ee6d9e.png">

**Comment by csmcneill** [comment]
Please note that the previously documented $5 minimum deposit amount for AUD amount has since been removed from [our documentation](https://woocommerce.com/document/woocommerce-payments/deposits/deposit-schedule/#minimum-deposit-amounts). 

Discussion in p1689353300538449-slack-C03EE4CPPK5

**Comment by haszari** [comment]
I've clarified the title of the issue to `Show clear info in UI when there will be no payout because merchant balance is below deposit minimums (e.g. AUD$5)` – that seems to be the main problem here! @EjayhanFernandes @csmcneill let me know if I've misunderstood, feel free to tweak the title.

I've added projects label, I think we should consider this as part of current deposits focus – e.g. as part of tidying up estimated deposits / linked transactions. FYI @brucealdridge @bradyv - something to consider. We could handle as maintenance but better to consider the messaging/notice wording holistically.

**Comment by bradyv** [comment]
@haszari Thanks for the ping! I agree we should improve the messaging for this case, and if we can get it into the scope of work for deposits that would be even better. I'll make a note for us to discuss the details

**Comment by haszari** [comment]
Note we are (possibly) planning to not show a deposit detail page for estimated (future) deposits, so this exact issue would get fixed by that. Though we might want to show a notice or messaging in deposits list and/or payments overview.

**Comment by bradyv** [comment]
That's precisely the detail I noted for discussion heh 🙂

**Comment by Jinksi** [comment]
A proposed solution for this issue is a banner on the **Payments → Overview** screen, as per @bradyv's [design](https://www.figma.com/file/aDFNTeogq2cXSr4Nqeni8g/%5BWCPay%5D-Instant-Deposits?type=design&node-id=294-83778&mode=design&t=exSeHwn5tRxr33zg-4).

<img width="400" alt="image" src="https://github.com/Automattic/woocommerce-payments/assets/3147296/bcf86cc0-7fbb-454a-9b88-81120debd6ea">

**Comment by bradyv** [comment]
This will probably see more iteration but two changes I've made in Figma
- Removed the schedule string as it causes confusion when deposits aren't happening
- Changed `Deposits are unavailable` to `Deposits are paused` as it's more clear to the merchant what is actually happening

<img width="717" alt="Screenshot 2023-11-13 at 10 00 51" src="https://github.com/Automattic/woocommerce-payments/assets/889872/cdba6fc9-faa5-4b0f-8695-844fe3ee6d9e">

**Comment by Jinksi** [comment]
Adding `blocked` label until we determine the correct source of the minimum deposit thresholds for scheduled/automated deposits.

**Comment by csmcneill** [comment]
> Adding blocked label until we determine the correct source of the minimum deposit thresholds for scheduled/automated deposits.

My understanding following the conversation in p1700692443698049-slack-C045PC0V40G is that:
1. Stripe themselves have deposit minimum thresholds in place that affect standard, scheduled deposits that we cannot control per p1700693040505149/1700692443.698049-slack-C045PC0V40G.
2. We have our own minimum deposit thresholds in place on the server that would affect non-scheduled deposits* per p1700693021285799/1700692443.698049-slack-C045PC0V40G.  

*Note: The minimum on the server may or may not affect instant deposits per p1700696058923899/1700692443.698049-slack-C045PC0V40G

Here are the values for minimum deposits based on this information:

Currency | [Stripe's Minimum Amount](https://stripe.com/docs/payouts#minimum-payout-amounts) | [WooPayments Server Minimum Amount](https://github.com/Automattic/woocommerce-payments-server/blob/8501cc0335e272fd26b1aa3ff12d33e873f97a99/server/wp-content/rest-api-plugins/endpoints/wcpay/utils/class-currency.php)
-- | -- | --
AED | 2.00 | 2.00
AUD | 0.00 | 5.00
BGN | 1.00 | 1.00
CAD | 0.00 | 5.00
CHF | 5.00 | 5.00
CZK | 30.00 | 30.00
DKK | 20.00 | 50.00
EUR | 1.00 | 5.00
GBP | 1.00 | 5.00
HKD | 0.00 | 50.00
HUF | 360.00 | 360.00
JPY | 1 | 50
NOK | 20.00 | 50.00
NZD | 0.00 | 5.00
PLN | 5.00 | 5.00
RON | 5.00 | 5.00
SEK | 20.00 | 50.00
SGD | 1.00 | 5.00
USD | 0.00 | 5.00

**Comment by haszari** [comment]
@Jinksi is this still blocked?

I see a list of minimums in comment above. However there may be risks with how to encode/store these minimums (i.e. if we can't get them from an API) – that might be a blocker or risk with a potential fix. Looks like you're in progress on enriching the minimum limits data in WooPayments server, so maybe there's a clear path to resolving this 🚀

**Comment by Jinksi** [comment]
I'm using the blocked label to show that progress on the client solution is blocked until we can access the minimum deposit data (potentially server PR 4302 if suitable).

I think the `blocked` label is suitable to communicate this situation, as per the label description:

> `blocked`: The issue is blocked from progressing, waiting for another piece of work to be done.

But I'm happy to remove it if it's confusing the status of the issue's progress.

**Comment by haszari** [comment]
Ah I see! That description is not a match for my understanding of blocked, feels misleading in this case – we are blocked on ourselves/waiting on ourselves. 

The key thing for me is when things are `blocked` it usually means one of two things:

- We can't implement this, not practical.
- We can implement, but we need another team or another company to do something first. 

Often these are good points for team lead to step in – close or coordinate.

`blocked` on a subtask is more like a dependency or work-sequencing thing. (which I can ignore as lead)

Do you have the ball for all of this currently? So from a team point of view, it's not blocked, @Jinksi  is on it?

**Comment by Jinksi** [comment]
> Do you have the ball for all of this currently?

Yes

> So from a team point of view, it's not blocked, @Jinksi is on it?

Indeed – not blocked because I/we have the ball. I am aligned with your understanding of `blocked`, therefore, I am removing the `blocked` label.

**Comment by haszari** [comment]
Medium priority, this is in progress 🚀
