### ISSUE TITLE
Payments Connect Illustration color bar is partly cut off

### ISSUE THREAD

**Issue by elizaan36** [Automattic/woocommerce-payments#6780]
### Describe the bug
Small visual bug on the Payments Connect (before setup is complete), the color bar is getting cut off on the illustration. I think this was due to a design oversight and we've since fixed the illustration.
<img width="1943" alt="Screen Shot 2023-07-14 at 11 11 08 AM" src="https://github.com/Automattic/woocommerce-payments/assets/5121465/ba487dcd-bc7d-476c-95fa-ef21ae187177">

I'll share a link to the correct illustration file in Slack.
cc @vladolaru since I think this was last updated as part of the incentive project.

**Comment by daquinons** [comment]
The illustration is shared here p1689357131075329-slack-C03KTTK2YMA

**Comment by vladolaru** [comment]
Thank you, @elizaan36, for reporting this issue. I will pick it up as part of the Incentives projects.
