### ISSUE TITLE
Unable to capture authorized funds from manually created orders

### ISSUE THREAD

**Issue by billrobbins** [Automattic/woocommerce-payments#6781]
### Describe the bug
Say we have a manually created order for a new customer.  WooCommerce Payments is set to authorize instead of capture.  When the customer goes to pay for the order, they will see an error message.  In the Transactions screen in the admin, the transaction will be listed along with a capture button.  Clicking on capture does not have any effect.  Also, the customer name field shows `null` next to the order number.

Customers who purchased successfully in the past do not appear to be affected.

Also, this worked as expected previously.  I can reproduce this with only WooCommerce, WooCommerce Payments, and Storefront active.

### To Reproduce
1.  Create a new WooCommerce customer/WP user.
2. Go to WooCommerce > Orders and click "Add new" to create a new order.
3. Manually add products to the order and save it with the "pending payment" status.
4. In a private browser window, log in as the new customer and go to the orders section of the user facing WooCommerce dashboard.
5. Click on the pay button next to the order and attempt to check out.
6. You should see an error message at the top saying, `We're not able to process this payment. Please try again later.`.
7. Back in the WooCommerce admin, go to Payments > Transactions and click on the "Uncaptured" tab.
8. Attempt to capture the authorization.
9. Observe the error.

### Actual behavior
Customers are able to create multiple authorizations however, they cannot be captured by the merchant.

The network response for the affected payment intent returns `null` for the `customer_name` and `customer_email`.

```json
{
    "wcpay_charges_cache_id": 34738,
    "stripe_account_id": "acct_1G9axHGAccZ7MjSw",
    "charge_id": "ch_3NTqUGGAccZ7MjSw0HgDNTuF",
    "transaction_id": null,
    "amount": 2095,
    "net": 1983,
    "amount_captured": 0,
    "amount_refunded": 0,
    "is_captured": false,
    "created": "2023-07-14 18:13:25",
    "modified": "2023-07-14 18:13:26",
    "channel": "online",
    "source": "visa",
    "source_identifier": "4242",
    "customer_name": null,
    "customer_email": null,
    "customer_country": "US",
    "fees": 112,
    "currency": "usd",
    "risk_level": 0,
    "payment_intent_id": "pi_3NTqUGGAccZ7MjSw0Yh6RfpO",
    "refunded": false,
    "order_id": 1326,
    "outcome_type": "authorized",
    "status": "succeeded"
}
```

### Screenshots
![error](https://github.com/Automattic/woocommerce-payments/assets/1138631/08e7dd90-6bc0-4059-9a0c-0148dd304ada)

![null](https://github.com/Automattic/woocommerce-payments/assets/1138631/44047537-6f97-44b1-98d3-640b3b5ad003)

### Expected behavior
I expect it to be possible for new customers to pay for pending payment orders and the store owner to be able to capture the funds.

### Desktop (please complete the following information):

* OS: MacOs
* Browser Chrome
* Version 114.0.5735.198

### Smartphone (please complete the following information):

* Device: [e.g. iPhone6]
* OS: [e.g. iOS8.1]
* Browser [e.g. stock browser, safari]
* Version [e.g. 22]

### Additional context
My wife's business ran into this (3sonscabinets.com) and I was able to replicate it on a test site.

**Comment by csmcneill** [comment]
Noting that this affects [a critical flow](https://github.com/Automattic/woocommerce-payments/wiki/Testing-instructions-for-critical-flows#manual-capture).

**Comment by htdat** [comment]
@billrobbins - thanks for detailed report. However, I could not replicate this issue with the latest dev version (i.e. the `develop` branch of this repo). 

I'd like to grab more details to troubleshoot this issue p1689577357334009-slack-C7U3Y3VMY

**Comment by billrobbins** [comment]
This ended up being an issue with UPE.  When I disabled it, checkout worked as expected for these orders.

It does appear to be fixed now as I can pay for manually created orders with UPE when transactions are set to authorize only.  I'm going to close this now but feel free to reopen it if this comes up again.
