### ISSUE TITLE
BNPL - Fix the PM conditional in Afterpay shipping address sending check

### ISSUE THREAD

**Issue by nagpai** [Automattic/woocommerce-payments#6792]
### Describe the bug

For Afterpay, we have a requirement of sending Shipping Address, in the request. We had introduced [this code](https://github.com/Automattic/woocommerce-payments/pull/6492/files#diff-bcfd303d507c33a27671935e724ee64d0df30ff2a18bb6ef4c94f28d48190124R1119) in an earlier PR to to do that. ( [Link in the develop branch ](https://github.com/Automattic/woocommerce-payments/blob/develop/includes/class-wc-payment-gateway-wcpay.php#L1119)) 

Props to @FangedParakeet who reminded that `$payment_information->get_payment_method()` would not return the name of the payment method  (i.e. `afterpay_clearpay` ). Instead it returns the payment method id similar to `pm_xxxxxyyyy...` . Because of this the code in the if statement will never execute. 

### Additional context
Discussion on slack with hints to resolve this 
p1689060282807879-slack-C02C00HCJ8J
```[tasklist]
### Tasks
- [ ] https://github.com/Automattic/woocommerce-payments/pull/6800
- [ ] https://github.com/Automattic/woocommerce-payments/pull/6838
```

**Comment by nagpai** [comment]
I have removed the PHP snippet under discussion to see if it affects Afterpay checkout. 

The transaction completed successfully after removing the PHP snippet for classic as well as block checkout, and within each - for Legacy as well as Split UPE. However, for checkout cases where there was a separate shipping address specified, the address submitted to Afterpay was the billing address. 

I will be creating two PR's to fix this issue in Classic as well as Block checkout. (check tasklist in the main message of the issue )

**Comment by nagpai** [comment]
2. Legacy UPE - Classic checkout - I tested with separate Shipping and billing address.  Checkout completes successfully, however, the billing address is submitted as shipping address. The payment completes successfully and the billing and shipping address appear correctly on the order.

**Comment by KarlisJ** [comment]
@nagpai @mgascam I see that both associated PRs are merged. Can we close this issue?

**Comment by kalessil** [comment]
Yes, we can =)
