### ISSUE TITLE
Adjust wording of dispute notice on WC core order page

### ISSUE THREAD

**Issue by aheckler** [Automattic/woocommerce-payments#6801]
Starting in 6.2.0, we now [alert merchants on the WC core order page](https://github.com/Automattic/woocommerce-payments/blob/6.2.0-test-3-bis/client/order/index.js#L162) when an order's transaction has been disputed. An example alert:

> This order has a chargeback dispute of $50.00 labeled as "Transaction unauthorized". Please respond to this dispute before Jul 26, 2023.

However, we do not refer to disputes as "chargebacks", and a "chargeback dispute" is an awkward phrasing anyway. Can we change this to the following?

> This order has been disputed in the amount of `$amount`. The customer provided the following reason: `$reason`. Please respond to this dispute before `$deadline`.

cc @souravdebnath1986 @Jinksi

**Comment by Jinksi** [comment]
This is on Helix's radar.

**Comment by Jinksi** [comment]
Noting this could be resolved alongside #6802
