### ISSUE TITLE
Change dispute alert wording for transactions with an inquiry

### ISSUE THREAD

**Issue by aheckler** [Automattic/woocommerce-payments#6802]
Starting in 6.2.0, we now [alert merchants on the WC core order page](https://github.com/Automattic/woocommerce-payments/blob/6.2.0-test-3-bis/client/order/index.js#L162) when an order's transaction has been disputed. An example alert:

> This order has a chargeback dispute of $50.00 labeled as "Transaction unauthorized". Please respond to this dispute before Jul 26, 2023.

However, we also show this same wording for payments against which [an inquiry](https://stripe.com/docs/disputes/how-disputes-work#inquiries) has been filed. As Stripe says, an inquiry is "a preliminary phase before creating a formal dispute", so we should avoid calling them disputes if possible.

Can we change the alert wording for inquiries to the following?

> The card network involved in this order has opened an inquiry into the transaction with the following reason: $reason. Please respond to this inquiry before $deadline, just like you would for a formal dispute.

**Comment by htdat** [comment]
cc @Jinksi as it belongs to Disputes.

**Comment by Jinksi** [comment]
Thanks, this is on Helix's radar.

**Comment by brucealdridge** [comment]
Wording of this alert also needs changing detailed #6801

**Comment by brucealdridge** [comment]
@aheckler when the dispute/inquiry is due within the next 7 days the wording changes to 
```
Please resolve the dispute on this order for [amount] labeled "[reason]" by [date].
```
 there are screenshots of this on the [original pull-request](https://github.com/Automattic/woocommerce-payments/pull/6373#:~:text=Screenshots%20of%20this%20PR%27s%20implementation)

![image](https://github.com/Automattic/woocommerce-payments/assets/57298/682bcf21-50f3-4984-9ccb-3ed60490c7ca)

This could be updated to match the dispute wording to 
```
Please resolve the inquiry on this order for [amount] by [date].
``` 
Alternatively, it could be left as you suggested in this issue despite the looming deadline. 
```
The card network involved in this order has opened an inquiry into the transaction with the following reason: [reason]. Please respond to this inquiry before [date], just like you would for a formal dispute.
```

**Comment by aheckler** [comment]
Yeah, I think we can make it a bit more forceful when the deadline is approaching. Maybe:

> Please respond to this inquiry by $date. You have X days remaining!

**Comment by brucealdridge** [comment]
@aheckler I've opted to keep the wording similar to disputes.

```
Please resolve the inquiry on this order for [amount] by [date].
```

When less than 7 days remain, the number of days left is also included. I've included all the appropriate screenshots in there. Did you want to review the text changes on the PR?  #6970
