### ISSUE TITLE
Avoid using the word "chargeback" in settings explainer text

### ISSUE THREAD

**Issue by aheckler** [Automattic/woocommerce-payments#6803]
On the Settings page, we use [this sentence](https://github.com/Automattic/woocommerce-payments/blob/develop/client/settings/settings-manager/index.js#L123) to explain the fraud and risk tools settings:

> Help avoid chargebacks by setting your security and fraud protection risk level.

However, we should avoid using the word "chargeback" if possible, since we've more or less settled on calling them "disputes".

Can we please change this to something like the following?

> Help avoid unauthorized transactions and disputes by setting your fraud protection level.

**Comment by htdat** [comment]
cc @Jinksi as it belongs to Disputes.

**Comment by Jinksi** [comment]
Thanks, this is on Helix's radar.
