### ISSUE TITLE
Add a notice for JCB capability request on the Settings page

### ISSUE THREAD

**Issue by anu-rock** [Automattic/woocommerce-payments#6804]
### Description
JCB is a card payment method that needs a separate capability. To activate JCB in their stores, Japanese merchants must provide additional information to get the capability approved. To be able to request the capability, a notice above the payment methods list needs to be provided to the merchants.

<img width="1488" alt="enable-jcb-1" src="https://github.com/Automattic/woocommerce-payments/assets/8667118/84d4e434-0329-43e3-b427-cd94328dfb5c">

### Acceptance criteria
- A notice must be displayed when JCB capability is `unrequested` and the account country is Japan.
- The notice must guide the merchants through all capability statuses: `unrequested`, `pending`, `active`, `inactive`
- The notice must be dismissable with a confirmation popup.

### Designs
https://www.figma.com/file/C1r0Vzxh1mhbDJJnbjHp5q/Payments-Settings?type=design&node-id=2622%3A33711&mode=design&t=L4MM6rrMQwyS8Txl-1

**Comment by anu-rock** [comment]
Waiting for inputs from design, which may drastically change the shape of this task.

**Comment by dpaun1985** [comment]
There are 3 things to add here: 
- Replace “coming soon” with “request access”
- Check with Design if we should move JCB to Cards?
- Indicate status changes for requested JCB access - pending, successful, rejected, etc.
 
@mordeth could you update the issue description including these 3 points mentioned above?
