### ISSUE TITLE
Display BNPLs order consistently across settings page and enable LPMs page

### ISSUE THREAD

**Issue by mgascam** [Automattic/woocommerce-payments#6810]
### Description

BNPLs are below LPMs when enabling, but they are above LPMs on the Settings page:

![markup-on-2023-06-19-at-211455](https://github.com/Automattic/woocommerce-payments/assets/1553182/6fb3d4a2-2463-4ee6-a162-7e70aa6a4702)

![markup-on-2023-06-19-at-211616](https://github.com/Automattic/woocommerce-payments/assets/1553182/9aaa8b98-1f0e-4935-b65f-652566d4211d)

### Acceptance criteria

For consistency, we should have BNPLs either on the top or on the bottom in both sections.

### Designs

TBD.

### Additional context

paJDYF-7XP-p2#comment-18922

**Comment by elizaan36** [comment]
hey @rikmantel, Could you take a look at this issue as part of the Klarna work?
