### ISSUE TITLE
Improve has_multi_currency_orders function response time

### ISSUE THREAD

**Issue by ovidiul** [Automattic/woocommerce-payments#6814]
### Description

On sites with a large number of orders, the current count query used to compute results for the `has_multi_currency_orders` [function](https://github.com/Automattic/woocommerce-payments/blob/445d80f651c10137839d7b8ca4161bfea312b670/includes/multi-currency/Analytics.php#L502-L524) leads to increased response times, which scale proportionally with the number of records matching the WHERE clause. The query employs the COUNT(ID) function, which requires scanning all matching table rows to obtain the result.

Right now, I am seeing this query affecting the `/wp-json/wc/store/v1/cart/` endpoint, which, when it gets busy, might show increased response times, averaging 1-2 seconds increased execution time due to that query.

To improve the performance of this query, I propose optimizing the query by modifying its logic. Instead of scanning all matching rows, the query could search for the first match and then proceed with the remaining operations. This approach would decrease the load on the MySQL server and improve overall execution time.

It's important to note that this modification would not affect the return value of the function, ensuring that all existing tests will continue to pass. The primary benefit of this optimization is a significant reduction in execution time, leading to improved response times for count queries on sites with a high volume of orders.

My test:

```
#> explain analyze SELECT COUNT(post_id) FROM wp_postmeta WHERE meta_key = '_wcpay_multi_currency_order_exchange_rate';

-> Aggregate: count(wp_postmeta.post_id)  (cost=160055.35 rows=148020) (actual time=251.008..251.008 rows=1 loops=1)
    -> Filter: (wp_postmeta.meta_key = '_wcpay_multi_currency_order_exchange_rate')  (cost=145253.35 rows=148020) (actual time=0.272..247.841 rows=85683 loops=1)
        -> Index lookup on wp_postmeta using meta_key (meta_key='_wcpay_multi_currency_order_exchange_rate')  (cost=145253.35 rows=148020) (actual time=0.271..214.589 rows=85683 loops=1)
```

and the new suggested query

```
#> explain analyze SELECT EXISTS(SELECT 1 FROM wp_postmeta WHERE meta_key = '_wcpay_multi_currency_order_exchange_rate' limit 1) as count ;

-> Rows fetched before execution  (cost=0.00..0.00 rows=1) (actual time=0.000..0.000 rows=1 loops=1)
-> Select #2 (subquery in projection; run only once)
    -> Limit: 1 row(s)  (cost=146023.84 rows=1) (actual time=0.426..0.426 rows=1 loops=1)
        -> Filter: (wp_postmeta.meta_key = '_wcpay_multi_currency_order_exchange_rate')  (cost=146023.84 rows=148800) (actual time=0.425..0.425 rows=1 loops=1)
            -> Index lookup on wp_postmeta using meta_key (meta_key='_wcpay_multi_currency_order_exchange_rate')  (cost=146023.84 rows=148800) (actual time=0.423..0.423 rows=1 loops=1)
```

notice now the first query needs 251.008 miliseconds to aggregate the count and has to process 148020 rows while the proposed query only needs to process 1 row and executes much faster.

Time measurement

```
#> select exists(SELECT 1 FROM wp_postmeta WHERE meta_key = '_wcpay_multi_currency_order_exchange_rate' limit 1 ) as count;
+-------+
| count |
+-------+
|     1 |

#>  SELECT COUNT(post_id) FROM wp_postmeta WHERE meta_key = '_wcpay_multi_currency_order_exchange_rate';
+----------------+
| COUNT(post_id) |
+----------------+
|          85685 |
+----------------+
1 row in set (0.256 sec)
```

The validation of that function 85685 > 0 === 1 > 0 

Happy to submit a PR if this is acceptable.

**Comment by htdat** [comment]
Thanks the report @ovidiul 
Yes, it would be super helpful if you could open a PR. It would be great if HPOS (with other COT - Custom Order Tables) is taken into account https://woocommerce.com/document/high-performance-order-storage/

**Comment by htdat** [comment]
This issue impacts `Multi-currency`, so assigning to Sigma (based on team responsibilities Pc2DNy-3z-p2) - cc @dwainm as team lead. 
Assigning as part of Gamma Triage process PcreKM-yM-p2.
