### ISSUE TITLE
Subscriptions appearing in My Accounts tab when Woo Payments is disabled from Woo → Payment Methods settings page

### ISSUE THREAD

**Issue by danielk-am** [Automattic/woocommerce-payments#6821]
### Describe the bug
The Subscriptions tab shows up in My Accounts tab when Woo Payments is disabled from Woo → Payment Methods settings page.

### To Reproduce
Conditions:
Woo Payments plugin is active.
Woo Payment is disabled in Woo → Payment Methods

1. Go to My Accounts
2. Subscriptions tab is active

### Actual behavior
The subscription tab is active in My Accounts when Woo Payments is disabled.

Also, you can't disable the subscriptions option from the settings page when these conditions are met. It will show the option as enabled, even after disabling and saving the Woo Payments settings.

It looks like the current workarounds are:
- Enable Woo Payments and complete setting it up, then disable the Subscriptions feature before disabling Woo Payments.
- Or, deactivate Woo Payments plugin.

### Screenshots
NA

### Expected behavior
I want to disable the built-in Subscription feature even when Woo Payments is disabled.

### Desktop (please complete the following information):
N/A

### Smartphone (please complete the following information):
N/A

### Additional context
N/A

**Comment by htdat** [comment]
This issue impacts `WCPay Subscription`, so assigning to Quark (based on team responsibilities Pc2DNy-3z-p2) cc @diegocurbelo as lead. 
Assigning as part of Gamma Triage process PcreKM-yM-p2.

**Comment by csmcneill** [comment]
I think that this may be expected. When WooPayments is disabled as a payment method, it still functions from the administrative side of the house (e.g., processing refunds) as though it is enabled.

Disabling the payment method will allow an admin to still manage existing subscriptions while not accepting new payments.

**Comment by mattallan** [comment]
> I think that this may be expected.

@csmcneill comment above is 100% correct. Disabling the gateway should still allow customers and merchants to manage existing subscriptions on the store. Closing this without a fix.
