### ISSUE TITLE
Evaluate Additional Merchant Details for BNPLs per Supported Country

### ISSUE THREAD

**Issue by mgascam** [Automattic/woocommerce-payments#6839]
### Description

We need to evaluate additional merchant details requirements for Buy Now, Pay Later (BNPL) payment methods for each country we support. This evaluation is necessary to better understand regional requirements and implement appropriate features.

### Acceptance criteria

* Identify any additional merchant details we need to collect for each country and payment method
* Collaborate with Adam on creating documentation to highlight why new PMs might be disabled

### Additional context

Check this Slack thread: p1689364005427329-slack-C04VCT34PCP

**Comment by kalessil** [comment]
@aheckler: I did a quick exploration using Stripe API:

- Affirm: no additional requirements
- Aferpay: `business_profile.support_email` and `business_profile.support_phone` are required as per my exploration

I hope that helps a bit in your testing, as I'm not sure that all five countries include the fields into onboarding steps.

**Comment by brandonwanA8C** [comment]
@kalessil  
Aferpay: business_profile.support_email and business_profile.support_phone are required as per my exploration

to your knowledge, was this required for merchants on ALL supported markets, or just the US?

**Comment by kalessil** [comment]
@brandonwanA8C: for merchants on ALL markets (I didn't check FR/ES as there were not aimed in Phase 1)

**Comment by mgascam** [comment]
Sharing my findings after exploratory testing. I created Express accounts in test mode in the WCPay Dev account for US, CA, UK, AU, NZ. I synched each with my local dev environment, to check the behavior in the Settings page:

1. Similar to @kalessil's findings, I only noticed additional requirements needed for Afterpay:
   - `business_profile.support_email`
   - `business_profile.support_phone`
   - `person_1NXN17QrkHlMbRqqDH5Ae1ou.verification.document` (only in AU based account)
2. I got the `Contact WooCommerce Support` badge when the status of the capability was `inactive` in the `capabilities` section of the account settings.
3. I found this [PR](https://github.com/Automattic/woocommerce-payments/pull/3093) related to inactive status handling.
4. We add a task in Payments > Overview to inform the user that there's missing business information. Clicking the link takes the merchant to the connected account dashboard in Stripe.
<img width="704" alt="Screenshot 2023-07-24 at 18 08 31" src="https://github.com/Automattic/woocommerce-payments/assets/1553182/8357c729-4eb9-4379-802a-bf3b85158cb6">

**Comment by aheckler** [comment]
Ah, you beat me to the testing. :) Thanks for doing that!

**Comment by kalessil** [comment]
Thanks for checking this @mgascam @aheckler. What'll be our next steps here?

**Comment by mgascam** [comment]
> Thanks for checking this @mgascam @aheckler. What'll be our next steps here?

@kalessil I opened a thread to discuss them paJDYF-7XP-p2#comment-19747
