### ISSUE TITLE
Align critical testing flows for all the UPE types

### ISSUE THREAD

**Issue by timur27** [Automattic/woocommerce-payments#6840]
There’s some unclarity if it goes to the critical testing flows for the UPE settings. First, when GlobalStep gets their testing site, split UPE is enabled by default. Going forward, [the first instruction](https://href.li/?https://github.com/Automattic/woocommerce-payments/wiki/Testing-instructions-for-critical-flows#testing-instructions) suggests that they can test either with the legacy UPE or with the split UPE, but we can’t say for sure which one.

Following the Stripe Link tests, there are [test UPE](https://href.li/?https://github.com/Automattic/woocommerce-payments/wiki/Testing-instructions-for-critical-flows#test-upe) instructions that don’t suggest choosing/changing any of the UPE settings (they probably were initially created for the legacy UPE), and thus we’re still unsure which version is being tested.

Finally, [the deferred intent section](https://href.li/?https://github.com/Automattic/woocommerce-payments/wiki/Testing-instructions-for-critical-flows#test-new-deferred-intent-upe) emphasizes checking the proper checkbox.

#### Things to accomplish within this issue
1. Decide if we will ask GlobalStep to test all three UPEs, for the time being.
2. Regardless of the decision on the first step, merge all three groups of tests into a single group that will stay UPE-agnostic (e.g., no mention of which feature flag to choose).
3. Based on the decision from the first step, add a specific mention of which flags must be enabled and in which sequence. Put this instruction before the second step.
4. Introduce any other improvements to the UPE testing instructions which you feel will make them more readable

**Comment by htdat** [comment]
@timur27 or @Automattic/heisenberg are going to work on this issue? 
Otherwise, I think it falls into Harmony's product area cc @deepakpathania?

**Comment by timur27** [comment]
> @timur27 or https://github.com/orgs/Automattic/teams/heisenberg are going to work on this issue?

I think so. cc @frosso @FangedParakeet

**Comment by timur27** [comment]
Closing this issue in favor of https://app.zenhub.com/workspaces/heisenberg-63586f2ec60359001310fa6a/issues/zh/3
