### ISSUE TITLE
Develop the schema for authorizations API endpoint

### ISSUE THREAD

**Issue by zmaglica** [Automattic/woocommerce-payments#6846]
### Description

In an effort to expand the functionality of the WooCommerce Payments plugin, we are planning to add a set of APIs for detailed reporting. As part of this initiative, we need to create a schema for the Authorizations endpoints. The purpose of this issue is to develop a schema based on the WordPress REST API Schema Documents, which will be utilized to create additional endpoints for retrieving transaction information.

The updated Authorization schema includes the following properties:

- ID (`string`): This is a unique identifier for each record based on its details.
- Date (`string` in `date-time` format): This signifies when the transaction was initiated.
- Transaction ID (`string`): A unique identifier for each transaction, characterized by its type.
- Source ID (`string`): A unique identifier (payment intent) for each transaction.
- Channel (`string`): Indicates if the transaction was processed online or offline.
- Payment method (`object` with `type` and `id` properties):
  - Type (`string`): Specifies if the payment method used was a card (like Visa, Mastercard, etc.) or an Alternative Payment Method (APM) or Local Payment Method (LPM), such as iDEAL, Apple Pay, Google Pay, etc.
  - ID (`string`): The ID of the payment method used to initiate the transaction type.
- Type (`string`): Defines the nature of the transaction.
- Transaction currency (`string`): This is the currency used for the transaction.
- Amount (`number`): Denotes the total transaction value.
- Fees (`number`): This pertains to the transaction fees.
- Customer (`object` with `name`, `email`, and `country` properties):
  - Name (`string`): The customer's name.
  - Email (`string`): The customer's email address.
  - Country (`string`): The country where the customer resides.
- Net amount (`number`): This represents the net amount after deducting fees.
- Order ID (`number`): The identifier of the WooCommerce order associated with this transaction.
- Risk level (`number`): This represents the risk level associated with potential fraud in the transaction.

Please note that the property types mentioned above are based on the current understanding of the requirements. However, they are subject to change if necessary to accommodate future considerations or specific implementation needs.

### Acceptance Criteria

- Ensure familiarity with the topic of WordPress REST API schemas.
- Implement the schema based on the provided set of properties.
- Set the correct type hints on both the client and server sides to enable schema validation.
- Document the schema thoroughly once it is completed.

### Designs

Not needed.

### Testing Instructions

Verify that the schema aligns with the object defined in this issue.

### Additional Information

pcreKM-1Hp-p2
https://developer.wordpress.org/rest-api/extending-the-rest-api/schema/#schema-documents

**Comment by jessy-p** [comment]
This is addressed in PR #6652 and will be reviewed there. Closing this issue.
