### ISSUE TITLE
Create API endpoint for retrieving a filtered list of authorizations

### ISSUE THREAD

**Issue by zmaglica** [Automattic/woocommerce-payments#6847]
### Description
Review the existing API endpoint for retrieving transactions to determine if it meets the schema requirements for data reporting while maintaining backward compatibility. If the existing endpoint is sufficient, modify it to include the ability to retrieve a filtered list of transactions based on the provided parameters. If the existing endpoint does not meet the requirements, create a new API endpoint to fulfill the transaction retrieval needs.

The following endpoint needs to be checked/added:

[Authorizations](https://github.com/Automattic/woocommerce-payments/blob/develop/includes/core/server/request/class-list-authorizations.md) – includes/core/server/request/class-list-authorizations.md

## Filtering Parameters

- Date Before (`string` in `date-time` format, not required): This filters authorizations that happened before a certain date.
- Date After (`string` in `date-time` format, not required): This filters authorizations that happened after a certain date.
- Date Between (`array`): This filters authorizations that happened between two dates.
- Order ID (`integer`, not required): This filters authorizations associated with a specific order ID.
- Email (`string`, not required): This filters authorizations associated with a specific customer email.
- Payment Method ID (`string`, not required): This filters authorizations that used a specific payment method.
- Type (`string`, not required): This filters authorizations of a specific type. Acceptable values include 'failed', 'cancelled', 'expired', 'uncaptured'.
- Transaction ID (`string`, not required): This filters authorizations based on a unique transaction ID.
- Source ID (`string`, not required): This filters authorizations based on a unique source ID.
- Match (`string`, not required): This is used to match a filter for the authorizations.
- Search (`array`, not required): This parameter is used to search within the authorizations.
- User Timezone (`string`, not required): This includes the timezone in date filtering.
- Order By (`string`, not required, defaults to 'created'): This sorts the authorizations based on a specific field.
- Order (`string`, not required, defaults to 'desc'): This orders the authorizations based on a specific field. Acceptable values include 'asc' and 'desc'.
- Page (`integer`, not required, defaults to 1, minimum 1): This specifies the page number.
- Per Page (`integer`, not required, defaults to 25, minimum 1, maximum 100): This specifies the number of items per page.

## Request Schema
The request schema for the API endpoint should follow the specifications outlined in the following GitHub issue: [#6846](https://github.com/Automattic/woocommerce-payments/issues/6846). Please refer to the schema provided in the issue and incorporate it into the API endpoint implementation.

## Response
The API endpoint should return a list of transactions that match the specified filters. Each transaction should include relevant information such as transaction ID, timestamp, type, order ID, deposit ID, customer email, payment method details, and transaction details.

## Note
Please ensure that the API endpoint implementation adheres to RESTful design principles and follows proper error handling practices. If the existing endpoint is sufficient, modify it to accommodate the new requirements. If it is not sufficient, create a new API endpoint to fulfill the transaction retrieval needs.

**Comment by jessy-p** [comment]
Seperate PR, tests, documentation

**Comment by RadoslavGeorgiev** [comment]
Awaiting feedback from @souravdebnath1986
