### ISSUE TITLE
The `Automattic\WooCommerce\Admin\API\Options::get_options` function is deprecated since version 6.3.

### ISSUE THREAD

**Issue by jimjasson** [Automattic/woocommerce-payments#6849]
### Describe the bug

When the QIT tests run for Product Bundles, the following error is caught: 

```
The Automattic\WooCommerce\Admin\API\Options::get_options function is deprecated since version 6.3.
Stack trace:
#0 /var/www/html/wp-content/plugins/woocommerce/includes/class-wc-data-store.php(159): WC_Shipping_Zone_Data_Store->read(Object(WC_Shipping_Zone))
#1 /var/www/html/wp-content/plugins/woocommerce/includes/class-wc-shipping-zone.php(62): WC_Data_Store->read(Object(WC_Shipping_Zone))
#2 /var/www/html/wp-content/plugins/woocommerce/includes/class-wc-shipping-zones.php(32): WC_Shipping_Zone->__construct(Object(stdClass))
#3 /var/www/html/wp-content/plugins/woocommerce-payments/includes/multi-currency/FrontendPrices.php(207): WC_Shipping_Zones::get_zones()
#4 /var/www/html/wp-includes/class-wp-hook.php(308): WCPay\MultiCurrency\FrontendPrices->register_free_shipping_filters('')
#5 /var/www/html/wp-includes/class-wp-hook.php(332): WP_Hook->apply_filters(NULL, Array)
#6 /var/www/html/wp-includes/plugin.php(517): WP_Hook->do_action(Array)
```

which seems to be coming from a WC Pay function, not related to Product Bundles.

Report: https://compatibilitydashboard.wpcomstaging.com/?qit_results=4512885.3tBRHTEKMoTjkMrKQOCvGQKP51DeIHbkDcc8lWrHRSyPHWUIFpGRyLstQGgFa3VF

**Comment by htdat** [comment]
Thanks for the report @jimjasson 

This issue impacts `Multi-currency`, so assigning to Sigma (based on team responsibilities Pc2DNy-3z-p2) cc @dwainm as team lead. Assigning as part of Gamma Triage process PcreKM-yM-p2.

**Comment by tpaksu** [comment]
@htdat I think this is more related with the authors of `WC_Shipping_Zones::get_zones()` method. As MC is only touching that method which eventually triggers the error. We don't use `Automattic\WooCommmerce\Admin\API\Options::get_options` in our code. What do you think? Do you want us to pursue the fix on the shipping zone part?

**Comment by tpaksu** [comment]
I dug deep and couldn't find where Shipping Zone data object calls `get_options`. Maybe it's an issue for an old version of WC Core?

**Comment by jessepearson** [comment]
I looked into this, as well. I think we're good to close it for now. It looks like the version of WC core being used was 8.0.0-beta.1, I wonder if it was something fixed within that version that never made it to the actual release.

@jimjasson If you are still seeing issues related to this, can you open the issue back up?
