### ISSUE TITLE
Improvement: slow get_all_customer_currencies response on stores with large amount of orders

### ISSUE THREAD

**Issue by ovidiul** [Automattic/woocommerce-payments#6852]
### Description

On sites with a large amount of orders(+1M), there is a slow query generated by the function [get_all_customer_currencies](https://github.com/Automattic/woocommerce-payments/blob/688daab64bb6c5ef027de187c1d5c05976fee290/includes/multi-currency/Analytics.php#L118C50-L118C77) which seems to take, in our case, over 60s to execute, affecting all wp-admin pages. 

Executed query:
```
SELECT DISTINCT(meta_value)
FROM wp_postmeta
WHERE meta_key = '_order_currency'
```

<img width="1450" alt="Screenshot 2023-07-25 at 09 53 47" src="https://github.com/Automattic/woocommerce-payments/assets/537751/8883b845-bc8f-4dec-9163-017725af9881">

While caching is being used, the problem is that the query, due to the setup of our MySQL server, is getting stopped if it runs over 60s, so the cache doesn't get properly populated.

Is there a solution that could be put in place, like a filter, which we can use to intercept that function execution and replace it with something more efficient that can be defined at the customer app level? 

Replacing it with

```
$currencies = array_keys($available_currencies);
```

seems to work in our case, however this requires us to modify the core plugin file.

Right now, the slow load of that query makes accessing the WordPress admin backend painful.

### Acceptance criteria

* the `register_customer_currencies` is being able to replace the `get_all_customer_currencies` execution
* response time of `get_all_customer_currencies` is optimised and decreased on sites with large amount of orders

### Testing instructions

1. Load the site with over 1M orders
2. try and access the wp-admin/ backend
3. notice the slow query displayed in Query Monitor on any admin page
4. go to the Transactions page `/wp-admin/admin.php?page=wc-admin&path=%2Fpayments%2Ftransactions&filter=advanced` and check the Customer Currency filter

<img width="787" alt="Screenshot 2023-07-25 at 09 59 37" src="https://github.com/Automattic/woocommerce-payments/assets/537751/df83d967-b297-44d6-9e4e-5985a6b5e2d6">

### Dev notes

Suggesting this code as drop in replacement which should not modify existing functionality, but allowing the user of the defined filter to hook into the returned value.

```
add_filter('woocommerce_analytics_customer_currencies', function ( $currencies, $multi_currency ) {
     return is_null($currencies) ? $multi_currency->get_all_customer_currencies() : $currencies;
}, 10, 2);

$currencies = apply_filters('woocommerce_analytics_customer_currencies', $currencies, $this->multi_currency );
```

A second solution is to optimise the executed query of the `get_all_customer_currencies` function so UNION ALL is being used against all existing known currencies taken from `$available_currencies = $this->multi_currency->get_available_currencies()`, like:

```
SELECT 'USD' AS currency_code, EXISTS(SELECT meta_value FROM wp_postmeta WHERE meta_key='_order_currency' AND meta_value='USD' LIMIT 1) AS exists_in_wp_postmeta
UNION ALL
SELECT 'EUR' AS currency_code, EXISTS(SELECT meta_value FROM wp_postmeta WHERE meta_key='_order_currency' AND meta_value='EUR' LIMIT 1) AS exists_in_wp_postmeta
UNION ALL
SELECT 'NEW' AS currency_code, EXISTS(SELECT meta_value FROM wp_postmeta WHERE meta_key='_order_currency' AND meta_value='NEW' LIMIT 1) AS exists_in_wp_postmeta;
...
```

which proves to run much faster than the initial query

Happy to submit a PR once a suitable solution is accepted.

**Comment by htdat** [comment]
Thanks for the report @ovidiul. 

This issue impacts `Multi-currency`, so assigning to @Automattic/sigma (based on team responsibilities Pc2DNy-3z-p2) cc @dwainm as team lead. Assigning as part of Gamma Triage process PcreKM-yM-p2.
