### ISSUE TITLE
Workflows on older plugin versions won't run due to operating system

### ISSUE THREAD

**Issue by jbordonado** [Automattic/woocommerce-payments#6854]
### Description
For older versions of the plugin (e.g. 4.6.x), most of the PR checks won't run, indefinitely waiting for a runner to pick up the jobs.

I guess that the operating system we run on is not available anymore. In this example, that would be `ubuntu-18.04`.

One way to circumvent this is to always use `ubuntu-latest` as the operating system.

### Additional context
p1690257533532099/1690257321.554219-slack-C05AW31EKFF

**Comment by deepakpathania** [comment]
Also look at: https://github.com/Automattic/woocommerce-payments/issues/6815 and https://github.com/Automattic/woocommerce-payments/issues/6855
