### ISSUE TITLE
Workflows on older versions of the plugin won't succeed due to incoherent beta and latest versions of WP/WC

### ISSUE THREAD

**Issue by jbordonado** [Automattic/woocommerce-payments#6855]
### Description
For older versions of the plugin (e.g. 4.6.x), some of the PR checks won't run successfully.
That's probably because we target `beta` or `latest` for WP/WC and, while it made sense at the time we were developing that old version (e.g. 4.6.x), the `beta` and `latest` values are different if we were to run the PR checks for that old version now.

Idea:
- As part of the release lead duties, once the release branch is created and the PR is up, we could add a step to "hardcode" those versions fetched by a tag (i.e. `latest` or `beta`), so that the final tagged version (e.g. 4.6.x) and zip deployed contain the true WC/WP versions targeted at the time. If we ever work again from this version (e.g. 4.6.x), the workflows will run with the correct versions from the time it was initially developed.

There might be a way to automate this step. If not, we can go with a manual step for now, and leave the automation as an improvement task.

Idea: parse the Woo and WP supported versions from woocommerce-payments.php , and then do the calculations from there? I.e. Each of them would plus 0.2 for latest versions to support?

### Additional context
p1690273644892579/1690257321.554219-slack-C05AW31EKFF

**Comment by vbelolapotkov** [comment]
Closing this one. It's still relevant but the case is so rare, so doesn't make sense implementing it right now. We may reopen or create new issue in the future if it's causing any troubles.
