### ISSUE TITLE
Multi-Currency: Manual Exchange Rate is not saved - Error: wcpay_multi_currency_invalid_currency_rate

### ISSUE THREAD

**Issue by AashikP** [Automattic/woocommerce-payments#6857]
### Describe the bug

The manual exchange rate changes are not saved. Reloading the page shows that the exchange rate is set to Manual, but still takes the value pulled via API and sets that as the exchange rate.

### To Reproduce

1. Set store currency to `Pound sterling (£)`
2. Go to WooCommerce > Settings > Multi-Currency > And add USD as an option
3. Set the exchange rate to Manual, and save changes:

    ![Q8QUrw.png](https://github.com/Automattic/woocommerce-payments/assets/17475174/70ae71c7-bc12-492f-993e-1e2c43a7a6b3)

4. Find the `Currency Settings updated` notice.
5. Test the updated exchange rate in cart/checkout page to find that no changes are applied to the exchange rates.
6. Reload the page (WooCommerce > Settings > Multi-Currency) to find that the exchange rate is still set to Manual, but the rate itself is the default exchange rate pulled by API:

    ![jCxtu4.png](https://github.com/Automattic/woocommerce-payments/assets/17475174/6690e231-5bba-4970-89fd-a4fa7ddc8f44)
7. Try to modify the exchange rate and save it again
8. Do not reload the page. Save it once again to find this error in browser console:

    ![8UTe6Q.png](https://github.com/Automattic/woocommerce-payments/assets/17475174/b38cc768-c6de-4579-b66b-fd99131060e2)

```
{
    "code": "wcpay_multi_currency_invalid_currency_rate",
    "message": "Invalid manual currency rate passed to update_single_currency_settings: 0",
    "data": null
}
```

This was the Payload sent in original request (Step 6):

![q4aXlk.png](https://github.com/Automattic/woocommerce-payments/assets/17475174/c38f4401-65ce-40d1-8552-a8907f2f514a)

This was the Payload sent for the second request (Step 7 - without reloading the page):

![WVOb4j.png](https://github.com/Automattic/woocommerce-payments/assets/17475174/63738bb9-edc6-4045-b694-cef48f7263c1)

### Actual behavior

Manual exchange rate request should be respected, and saved correctly.

### Expected behavior

Manual exchange rates are not saved, and are lost on page reload.

### Desktop (please complete the following information):

* OS: MacOS Ventura 13.5
* Browser: Chrome
* Version: 114.0.5735.198 (Official Build) (arm64)

### Additional context

Related ticket: 6451299-zd-woothemes
Slack discussion: p1690277547352709-slack-C3NCP7ZJ6

**Comment by htdat** [comment]
Thanks for the report @AashikP. 

This issue impacts `Multi-currency`, so assigning to @Automattic/sigma (based on team responsibilities Pc2DNy-3z-p2) cc @dwainm as team lead. Assigning as part of Gamma Triage process PcreKM-yM-p2.

**Comment by CGA8C** [comment]
We've had another report of this (6812313-zen), which led to a [Duplicate Issue](https://github.com/Automattic/woocommerce-payments/issues/7207) being created. 

@dwainm do we have any idea on how deep in the backlog this is? :)

**Comment by dwainm** [comment]
@CGA8C thanks for the ping; this goes out with 6.5.0.
