### ISSUE TITLE
Spike: Tap to Pay payments enabling for all supported countries

### ISSUE THREAD

**Issue by mordeth** [Automattic/woocommerce-payments#6864]
### Description
With the current implementation, the Tap to Pay is available only in the US. This Spike should determine what changes are required in order to enable Tap to Pay in all supported countries for both iOS and Android platforms.

### Additional context
pdfdoF-3ni-p2

**Comment by kalessil** [comment]
@mordeth: is this issue still relevant?

**Comment by RadoslavGeorgiev** [comment]
@mordeth seems like the linked project should have been completed by the end of Nov last year. I assume this issue is not relevant anymore, could you please comment?

**Comment by mordeth** [comment]
I believe this spike is no longer relevant and can be closed.
