### ISSUE TITLE
Extra WooPay init request every time express checkout button is clicked

### ISSUE THREAD

**Issue by alefesouza** [Automattic/woocommerce-payments#6866]
### Describe the bug

Currently when we click the WooPay express checkout button it makes a request to `/?wc-ajax=wcpay_init_woopay`, but when we close the modal and click the button again, it makes two requests to `/?wc-ajax=wcpay_init_woopay`, doing the same steps again it will be three, one more every time we repeat it.

### To Reproduce

1. Enable express checkout button on WooPay settings.
2. Add a product to the cart.
3. Go to a page with the WooPay express checkout.
4. Open the DevTools network tab.
5. Click the WooPay express checkout button.
6. Wait one request to `/?wc-ajax=wcpay_init_woopay`.
7. It will make two requests to this endpoints.
8. Close the modal.
9. Click the WooPay express checkout button again.
10. It will make two requests to `/?wc-ajax=wcpay_init_woopay`.
11. Repeat the last three steps, it will make one more request every time.

### Screenshots

<img width="578" alt="Screenshot 2023-07-26 at 20 06 12" src="https://github.com/Automattic/woocommerce-payments/assets/1693223/93ebfefb-610b-4f42-baa5-dd28e210d444">

### Expected behavior

Just one request to `/?wc-ajax=wcpay_init_woopay`.

**Comment by bummytime** [comment]
@alefesouza are you still working on this issue?

**Comment by alefesouza** [comment]
@bummytime it's in review on #6867
