### ISSUE TITLE
The new onboarding flow should use the new Jetpack connection screen integrated as part of the flow

### ISSUE THREAD

**Issue by daquinons** [Automattic/woocommerce-payments#6872]
**Status**: 🔴 Until we decide if we will finally move the onboarding to a hosted solution.

### Description
Similar to what was done with Core profiler https://github.com/Automattic/wp-calypso/pull/77826, we need a custom Jetpack screen similar to that one, but with some major differences:
- Our Jetpack connection screen comes at the beginning of the flow, so it'll need a different copy (not "One last thing").
- It will need to show the progress bar as a first step, instead of the last one
- It will need to be triggered with a custom `from` parameter, as the example PR. Something like `from=wcpay_onboarding` to trigger our own look.

### Acceptance criteria
- The new Jetpack connection looks like part of the WC Pay new onboarding, with the progress bar simulating it. This will make us modify also the first screen of the onboarding to show as the "second step" of it.
- We are approaching the colors from the consistency point of view. We need to share as many components as possible from WooCommerce parent components, and in doubt, we'll choose their style selections modifying WCPay to go towards them and not the other way around.

### Designs
Figma 3GMoaU7mat68VraYE9jadA-fi-2000%3A16522

Conversation: p1690387137349699-slack-C03KTTK2YMA

**Comment by ismaeldcom** [comment]
After an initial exploration and internal conversations, we've decided to put the issue on hold until we determine if we will finally move the onboarding to a hosted solution.

Key findings:
- WC solution relies on a query param to load the new UI, in a way that's not easy to reuse for us. We will need to do something similar using our own param and duplicating some code.
- WCPay currently uses `wooDNA` solution for UI and email customization, something we need to keep unless we decide to revamp the actual implementation. Keeping it will require us to put our conditions earlier than WC.
- With the new onboarding flow behind an experiment, we need to keep our current implementation for control users and the new UI for the treatment ones. Using a conditional param to differentiate them.
- The proposed Jetpack flow includes login and signup (authorize), while we only use the signup one right now. We will need to customize login, signup, password reset, and 2FA pages.

**Comment by daquinons** [comment]
There is a new version of the design here paJDYF-bax-p2#comment-21515

**Comment by daquinons** [comment]
New design being iterated here https://a8c.slack.com/archives/C03KTTK2YMA/p1701919915139739

**Comment by vladolaru** [comment]
We are closing this as a lot has changed in the meantime regarding our approach to onboarding and the Jetpack connection.

Related: paJDYF-c1U-p2
