### ISSUE TITLE
Support kanji and kana statement descriptors for Japanese merchants

### ISSUE THREAD

**Issue by mordeth** [Automattic/woocommerce-payments#6874]
### Description
Additional kanji and kana statement descriptors are supported for Japanese merchants. It is recommended to support Latin, kanji, and kana descriptors to reduce chargeback for Japanese merchants.
For JP Stripe accounts, add statement descriptors for kana and kanji. 
Under the latin statement descriptor, if it's a JP stripe account, we need to show another 2 inputs for kana and kanji statement descriptors.
Max length for kanji - 17 chars
Max length for kana - 22 chars
<img src="https://user-images.githubusercontent.com/5121465/261484253-671d5407-fc3f-4001-91c0-d232936e9865.png" />

**Comment by mordeth** [comment]
Waiting for inputs from design, which may drastically change the shape of this issue. The description will be updated accordingly.

**Comment by htdat** [comment]
> Waiting for inputs from design. 

@mordeth - do you have internal reference links for this? 

--- 

This issue impacts `Account management`, so assigning to Moltres (based on team responsibilities Pc2DNy-3z-p2) cc @daquinons as team lead. 

Assigning as part of Gamma Triage process PcreKM-yM-p2.

**Comment by dpaun1985** [comment]
@elizaan36 could you please share your inputs on how to display the two extra inputs conditionally for Japan merchants only?

**Comment by elizaan36** [comment]
Hi @dpaun1985 @mordeth I had a look at the requirements from paJDYF-9bt#comment-19925 and also the [Stripe documentation](https://stripe.com/docs/payments/account/statement-descriptors#set-japanese-statement-descriptors).

Would an additional dropdown selector work for this use case? The merchant can choose whether they'd prefer the statement descriptor in kanji, kana, or Latin.

<img width="849" alt="Screen Shot 2023-08-14 at 8 46 09 PM" src="https://github.com/Automattic/woocommerce-payments/assets/5121465/8cefbfdc-8f3e-4bf9-800d-b9b1e96c15c5">

<img width="699" alt="image" src="https://github.com/Automattic/woocommerce-payments/assets/5121465/cfe6919b-c8b5-4af5-9e5a-d440887a8d74">

I'll try additional explorations if anything is missing, let me know.

**Comment by dpaun1985** [comment]
> Hi @dpaun1985 @mordeth I had a look at the requirements from paJDYF-9bt#comment-19925 and also the [Stripe documentation](https://stripe.com/docs/payments/account/statement-descriptors#set-japanese-statement-descriptors).
> 
> Would an additional dropdown selector work for this use case? The merchant can choose whether they'd prefer the statement descriptor in kanji, kana, or Latin.
> 
> <img alt="Screen Shot 2023-08-14 at 8 46 09 PM" width="849" src="https://user-images.githubusercontent.com/5121465/260607821-8cefbfdc-8f3e-4bf9-800d-b9b1e96c15c5.png"> <img alt="image" width="699" src="https://user-images.githubusercontent.com/5121465/260607880-cfe6919b-c8b5-4af5-9e5a-d440887a8d74.png">
> I'll try additional explorations if anything is missing, let me know.

Based on what Stripe describe [here](https://stripe.com/docs/payments/account/statement-descriptors#issuer-behavior), 

> While most issuers use a Japanese statement descriptor rather than a Latin one, it is ultimately up to the issuer to decide which statement descriptor (kanji, kana, or Latin) to show on the cardholder’s statement.
The [calculated_statement_descriptor](https://stripe.com/docs/api/charges/object#charge_object-calculated_statement_descriptor) in API responses is always the Latin statement descriptor, but it doesn’t mean the issuer needs to select the Latin statement descriptor rather than the Japanese one.

the issuer chose what statement descriptor will be shown, and not the merchant. Also, in API responses, only the Latin statement descriptor is shown. 
That means that at least the Latin statement descriptor should be mandatory. If we add a dropdown, the merchant will think that they can select what statement descriptor is shown and could not complete the Latin statement descriptor.

In my opinion, this dropdown will create confusion to the merchant. What do you think @elizaan36  ?

**Comment by elizaan36** [comment]
Got it, ok. What's your suggestion as an alternative solution? Where should the statement descriptor appear?

**Comment by dpaun1985** [comment]
> Got it, ok. What's your suggestion as an alternative solution? Where should the statement descriptor appear?

I would keep the Latin statement descriptor input as it is, and add another 2 inputs for kanji and kana. Not a great solution, but I don't have other ideas.

**Comment by dpaun1985** [comment]
@elizaan36 could you please share your opinion on how should we proceed with this ?

**Comment by elizaan36** [comment]
Do you mean something like this? I'm afraid I don't know a better solution for this either, but let me know if there's anything missing.

<img width="679" alt="image" src="https://github.com/Automattic/woocommerce-payments/assets/5121465/671d5407-fc3f-4001-91c0-d232936e9865">

**Comment by anu-rock** [comment]
My two cents: I like @elizaan36's latest design as they seem to address @dpaun1985's concern. Other than that, having separate, always-visible text inputs will help reinforce Stripe's recommendation:

> We recommend setting statement descriptors in all three supported scripts (kanji, kana, and Latin characters).

The only thing I would change here is the language used with each text field. I think the description and hint texts for kanji and kana fields should be written in the Japanese language. But that's beyond the scope of this issue.

@dpaun1985 We may also want to use the appropriate max character length [requirements](https://stripe.com/docs/payments/account/statement-descriptors#japanese-requirements) - 17 for kanji and 22 for kana. I hope we currently show any validation error messages that we receive from Stripe. If this is not the case, we should open a new issue for dealing with it later.
