### ISSUE TITLE
Stripe Link autofill does not update fields in blocks checkout

### ISSUE THREAD

**Issue by FangedParakeet** [Automattic/woocommerce-payments#6881]
### Describe the bug

The Link express checkout method functions by identifying a user from their email, authenticating them via OTP, and then manually autofilling the billing and shipping input fields at checkout. To autofill these fields, Stripe returns an `autofill` event to the Stripe Link autofill instance containing the user's address details and we provide the location of the inputs that need to be completed.

In the blocks checkout, this event is captured successfully and the fields visually appear to be filled. However, the state does not seem to update and if we submit the form--without any further interaction with the checkout--we will be told that the fields are empty. Updating any of the fields manually at checkout will update the state and enable the form to be submitted. 

### To Reproduce

1. Enable Stripe Link payment and disable WooPay. This can be achieved by either enabling the legacy, split, or deferred intent UPE.
2. Go to blocks checkout. Ensure all inputs are empty.
3. Enter email address registered with Stripe Link. Authenticate via OTP and select autofill button.
4. Notice that input fields are satisfyingly completed.
5. Select "Place order". Notice that an unsatisfying error will appear stating that billing fields cannot be empty.
6. Edit any billing field manually and then select "Place order" again. Notice that checkout will now satisfactorily complete.

### Actual behavior

I cannot complete checkout after autofilling billing fields with Stripe Link.

### Expected behavior

I would like autofilled fields to be correctly completed, so that I can complete the checkout.

### Desktop (please complete the following information):

* OS: Any
* Browser [e.g. chrome, safari]: Any
* Version [e.g. 22]: `develop`

### Smartphone (please complete the following information):

* Device: Any
* OS: Any
* Browser: Any
* Version [e.g. 22]: `develop`

### Additional context

#6391

**Comment by FangedParakeet** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Heisenberg-63586f2ec60359001310fa6a/issues/Automattic/woocommerce-payments/6881?planning-poker) with Zenhub @timur27

**Comment by frosso** [comment]
FWIW, I tried modifying [this line](https://github.com/Automattic/woocommerce-payments/blob/71bac7396318389b973525cc9ab9e9cf0e47b7d8/client/checkout/stripe-link/index.js#L57-L57) and [this line](https://github.com/Automattic/woocommerce-payments/blob/71bac7396318389b973525cc9ab9e9cf0e47b7d8/client/checkout/stripe-link/index.js#L91-L91) into `'#billing_country, #billing_state, #shipping_country, #shipping_state, #billing-country input, #billing-state input, #shipping-country input, #shipping-state input'` - no luck.
I think we might need to call `updateCustomerData({...})` or something similar.

**Comment by frosso** [comment]
I also suspected it was due to us referencing "old" versions of store data that was passed to the `useEffect()` hook. While I'm not excluding that, it doesn't seem to be the culprit ( p1692785060944829-slack-C02TS23QJ1X )

**Comment by frosso** [comment]
Follow-up on the WC blocks repo: https://github.com/woocommerce/woocommerce-blocks/issues/10748
