### ISSUE TITLE
Improve integration tests for deferred intent UPE

### ISSUE THREAD

**Issue by FangedParakeet** [Automattic/woocommerce-payments#6882]
### Description

Currently, in our deferred intent UPE integration work, we have relied greatly on extending existing functionality. Our checkout code inherits the original UPE payment gateway class and relies on the legacy gateway's `process_payment` function to complete a checkout. Similarly our unit test coverage mostly consists of extending existing UPE unit tests. Consequently our unit test coverage is somewhat lacking in that we neglect to comprehensively the new deferred intent flows of logic from the UPE gateway to the legacy gateway, testing all components in concord concurrently. 

It would be nice if we could create some new unit tests that effectively test the deferred intent UPE checkout by ensuring that relevant functions are only fired when necessary, metadata is always added when relevant, and that redundant UPE function calls are no longer made.

### Acceptance criteria

Here are a few things of the top of my head that would be nice to have specific integration test coverage for.
- Complete deferred intent checkout flow.
- Assert/count calls to payments API (e.g. calls to retrieve payment method, calls to update intent, etc.).
- Assert intent metadata added to WC order.
- Assert WC order metadata added to intent.
- Assert calls to hooks.
- Platform checkout flow.
- Assert additional request fields for Stripe Link (e.g. `payment_method_types`, `mandate_data`).

### Designs

N/A

### Testing instructions

Exactly.

### Additional context

#6391

**Comment by FangedParakeet** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Heisenberg-63586f2ec60359001310fa6a/issues/Automattic/woocommerce-payments/6882?planning-poker) with Zenhub @timur27

**Comment by timur27** [comment]
Use cases for saving payment methods to check and try to integrate into the testing coverage
https://github.com/Automattic/woocommerce-payments/issues/5022#issuecomment-1663973487

**Comment by timur27** [comment]
* This issue can also include checking and possibly improving E2E & unit test coverage for deferred intent creation UPE. 
* While working on this issue, we should consider what is the status of https://app.zenhub.com/workspaces/heisenberg-63586f2ec60359001310fa6a/issues/gh/automattic/woocommerce-payments/5028, because both issues can have some common areas
