### ISSUE TITLE
Epic: Improve Disputes Challenge Form

### ISSUE THREAD

**Issue by shendy-a8c** [Automattic/woocommerce-payments#6884]
Project: pdjTHR-2PC-p2

Because it's a pretty major change, it's hard to improve iteratively from the current dispute challenge page, so we're going to create a new page.

#### Current dispute challenge form

![Untitled](https://github.com/Automattic/woocommerce-payments/assets/73803630/87fffdad-8d20-4ed7-9b94-878821158091)

#### New dispute challenge form

<img width="703" alt="Screenshot 2023-08-01 at 05 31 17" src="https://github.com/Automattic/woocommerce-payments/assets/73803630/01bd1043-d703-4550-9517-a30267e77f9b">

### TODOs
- [ ] Header.
- [ ] General evidence.
- [ ] Supporting evidence.
- [ ] Footer.

**Comment by haszari** [comment]
Closing - improving the dispute challenge/evidence form is an upcoming project in our roadmap.
