### ISSUE TITLE
Redirect legacy dispute details URL(s) to transaction details screen

### ISSUE THREAD

**Issue by shendy-a8c** [Automattic/woocommerce-payments#6891]
We're moving all the relevant UI and actions for disputes from a dedicated screen (aka legacy dispute details) to the transaction details screen.

As part of that we'll need to ensure any links, bookmarks, navigations to legacy dispute details land on the relevant transaction details.

The URL(s) we need to redirect are:

- example URL: `http://{domain}/wp-admin/admin.php?page=wc-admin&path=%2Fpayments%2Fdisputes%2Fdetails&id={dispute_id}`
  - route: `wp-admin/admin.php?page=wc-admin`
  - path: `/payments/disputes/details`
  - params: `id`

Any navigation to that url needs to land on the relevant transaction details screen.

#### implementation tips from @Jinksi 
I think we can rename the [‘legacy’ dispute details page](https://github.com/Automattic/woocommerce-payments/blob/feda536268e6254fd63167b23e842d3e2e336ca0/client/disputes/details/index.tsx) and change its behavior to do a Javascript redirect to the transaction details page. 

All the information we need to get the transaction details link is available in the dispute object:

- Payment intent id (pi_abc)
- Transaction id (txn_abc)

The rename needs to be applied [here](https://github.com/Automattic/woocommerce-payments/blob/feda536268e6254fd63167b23e842d3e2e336ca0/client/index.js#L154) as well.

**Comment by haszari** [comment]
> I think we can rename the [‘legacy’ dispute details page](https://github.com/Automattic/woocommerce-payments/blob/feda536268e6254fd63167b23e842d3e2e336ca0/client/disputes/details/index.tsx) and change its behavior to do a Javascript redirect to the transaction details page.

If there's a way to redirect this server-side that might speed it up (especially for external links e.g. other parts of Woo dashboard or in emails).

**Comment by haszari** [comment]
I'm in the middle of this but I have no objections to anyone taking over at any time 😁

- #7310

> If there's a way to redirect this server-side that might speed it up (especially for external links e.g. other parts of Woo dashboard or in emails).

🤦🏻 aha – we are a single page app, there's no server side entity so will need to be a client side solution 👍🏻
