### ISSUE TITLE
Remove Daily from deposits schedule

### ISSUE THREAD

**Issue by elazzabi** [Automattic/woocommerce-payments#6895]
For merchants in Japan, it's not possible to have daily deposits. Remove that from the dropdown if the merchant is in Japan

**Comment by htdat** [comment]
cc @Jinksi as Helix is owning Deposits (based on team responsibilities Pc2DNy-3z-p2).

**Comment by Jinksi** [comment]
Thanks for the ping! On our radar.

Noting that we should check if there are any other countries that do not support daily deposits as part of this issue.

**Comment by Jinksi** [comment]
Actually, I notice Japan is not yet supported and is part of the International Expansion Phase 3 project: paJDYF-9bt-p2.

@elazzabi is this issue being handled by team Fusion?

**Comment by shendy-a8c** [comment]
Maybe make sense to handle this problem generally for all countries in this table: [Payout speed by country](https://stripe.com/docs/payouts#standard-payout-timing).

**Comment by elazzabi** [comment]
Thank you for your input!
@Jinksi indeed, this is handled by Fusion as part of the International Expansion project.
@shendy-a8c I like the long-term solution proposed, and I think it makes sense. Given the tight deadline, I'll see if we can remove the Daily from the dropdown for now.

Out of curiosity, and given @shendy-a8c 's comment, do I understand that this is not an issue with Japan only? ie, multiple countries are seeing "Daily" even if it's not possible? For ex, Australia is 2 business days.

**Comment by shendy-a8c** [comment]
As far as I remember, we do not enforce country-specific exception when displaying the Daily deposit option.

**Comment by aheckler** [comment]
To be clear, the [payout speed table](https://stripe.com/docs/payouts#standard-payout-timing) is not relevant here. That table merely shows the minimum delay between money entering a merchant account (via a new order) and that money leaving the account (as part of a deposit).

However, that is different from the payout schedule/frequency merchants can choose, e.g. daily, weekly, or monthly. The only restrictions on payout schedule/frequency are [here](https://stripe.com/docs/payouts#payout-schedule):

> - In Brazil and India, payouts are always automatic and daily.
> - In Japan, daily payouts are not available.

Up to now, that has not affected us, but now that Japan support is about to be released, we need to prevent Japanese merchants from being able to choose the daily deposit schedule/frequency.

If it's still not clear how the deposit pending period and the deposit schedule/frequency are different, or it's unclear how they interact, please see our doc [here](https://woocommerce.com/document/woopayments/deposits/deposit-schedule/).
