### ISSUE TITLE
Fraud protection menu item inside of Payments should not be accessible if no account is onboarded

### ISSUE THREAD

**Issue by daquinons** [Automattic/woocommerce-payments#6907]
### Describe the bug
The new item "Fraud protection" inside of the "Payments" parent item is displayed and accessible even without an onboarded account. This should not be the case and should only be displayed if an account is connected.

### To Reproduce

1. Delete your local account
3. Click on Payments
4. Click the 'Finish setup' button to start the onboarding process.
5. Go back to the store without finishing the onboarding process.
6. See "Fraud protection" under payments.
7. Click on it

### Screenshots
<img width="1440" alt="image" src="https://github.com/Automattic/woocommerce-payments/assets/2612426/c01b0868-3622-4c94-954e-b27362371b1d">

<img width="1440" alt="image" src="https://github.com/Automattic/woocommerce-payments/assets/2612426/dffb9da5-62c2-4750-9fc7-298cd0a618ff">

cc @Automattic/sigma

**Comment by daquinons** [comment]
[False alarm](p1691037048835029-slack-C01B8KNUYSW), closing the issue

**Comment by shendy-a8c** [comment]
I can reproduce this issue. Updated the reproduce steps in the issue body.
