### ISSUE TITLE
Update the Balances/Deposits clickable tooltips in Overview to the correct component

### ISSUE THREAD

**Issue by nikivias** [Automattic/woocommerce-payments#6917]
### Describe the bug
We need to update the black tooltips that is currently implemented in WooCommerce Payments Overview (and possibly elsewhere within WCPay?) to the correct clickable white tooltips for better accessibility/readability and align with the new Woo design direction. 

We have 2 tooltip components available for Woo:
1. black tooltip, activated on hover, ideal for shorter notices
2. white clickable tooltips (popovers), activated on click, ideal for longer form messages

### To Reproduce

1. Go to Woo Commerce Payments
2. Click on a "clickable" icon or pill

### Actual behavior
Clicking a help icon, or any clickable element that triggers a tooltip shows the black tooltip.

### Screenshots
![image (3)](https://github.com/Automattic/woocommerce-payments/assets/99638528/9c85a89b-584b-49fa-b17d-4731c653ef2c)
![image (1)](https://github.com/Automattic/woocommerce-payments/assets/99638528/cc00c8f3-638b-4b99-9dee-3c106b77546c)

### Expected behavior
We need to use the clickable white tooltip component instead, found [in the design system Figma](https://www.figma.com/file/Kofpo8jj4zDWXDsVdlSz0f/WooCommerce-Admin-Design-Library?type=design&node-id=6795%3A10109&mode=design&t=JMWLeP4FlzoDURdH-1). If it's clickable, it should trigger the white popover, not the black tooltip. We can keep the same positioning of the popover that is configured 
The component doesn't seem to be in Storybook, but this was first used for the new Woo product form

<img width="466" alt="image" src="https://github.com/Automattic/woocommerce-payments/assets/99638528/4d6b483c-c4c4-46da-a600-935ad161d36b">

**Comment by Jinksi** [comment]
Helix can implement this change as part of the Improving Disputes Part 2 project: pdjTHR-2PC-p2

Note that the `ClickTooltip` component in question is currently only used for the Account Balances Tooltip Panel (https://github.com/Automattic/woocommerce-payments/blob/98c291141b41f87213f480a4ce271260fef29fb8/client/components/account-balances/index.tsx), but will be used as part of the new Transaction/Dispute details screen being introduced in #6883.

**Comment by elizaan36** [comment]
I linked another issue where we can deal with the accessibility issue on the black tooltips (on hover) overall, so this issue can be focused on only updating the component in the account balances panel to trigger the white popover on click.
