### ISSUE TITLE
Allow transactions list to be filtered by APM types

### ISSUE THREAD

**Issue by luizreis** [Automattic/woocommerce-payments#692]
As of https://github.com/Automattic/woocommerce-payments/pull/691, we're hiding all transaction types that start with `payment`, as we do not support APMs yet. Once we start supporting them, we need to let them be used as filters.

**Comment by deepakpathania** [comment]
Closing this since it has been handled in [this PR](https://github.com/Automattic/woocommerce-payments/pull/3025).
