### ISSUE TITLE
Transaction Details > Dispute Details > Steps to resolve for disputes

### ISSUE THREAD

**Issue by shendy-a8c** [Automattic/woocommerce-payments#6925]
![Screenshot 2023-08-04 at 09 20 12 copy 2](https://github.com/Automattic/woocommerce-payments/assets/73803630/29f979b2-570b-4ebd-bd7b-04d8971fd243)

> **Note**
> **Review the claim** is not part of this issue – now handled in issue #7156.

> **Note**
> Steps to resolve for **Inquiries** is not part of this issue – now handled in issue #7245.

**Link targets**
* `Email the customer` – a mailto link with the following prefilled detail:
	* Recipient: customer email
	* Subject: `Problem with your purchase from {store name} on {order date: YYYY-MM-DD}?
	* Body:
		```
		Hello {customer name}

		We noticed that on {dispute date: YYYY-MM-DD}, you disputed a {disputed amount with explicit formatting ($123 USD)} from {order date: YYYY-MM-DD}. We wanted to contact you to make sure everything was all right with your purchase and see if there's anything else we can do to resolve any problems you might have had.

		Alternatively, if the dispute was a mistake, you could easily withdraw it by calling the number on the back of your card. Thank you so much – we appreciate your business and look forward to working with you.
		```
	* `guidance on dispute withdrawal` – TBD (marked as "Doc in progress" in Figma – see pbUcTB-3oM-p2)

**Tooltips**
* Tooltips should use the `ClickTooltip` component.
* Challenge – `Challenge the dispute if you consider the claim invalid. You'll need to provide evidence to back your claim. Keep in mind that challenging doesn't ensure a resolution in your favor.`
* Accept – `Accepting this dispute will automatically close it. Your account will be charged a {fee amount, formatted explicitly: $15 USD} fee, and the disputed amount will be refunded to the cardholder.`]

#### Additional details
* See related issue for inquiries: #7245
* See figma: RiEQmaKRI7u9USAI3lyZz0VX-fi-6978_70329

**Comment by Jinksi** [comment]
For `Review the claim`, I've asked Stripe about testing issuer evidence here: p1692835906482299-slack-C9976E5MJ

**Comment by Jinksi** [comment]
The `IssuerEvidence` interface added in #7047 will be useful for this issue when you need to access this `dispute.issuer_evidence` data.

https://github.com/Automattic/woocommerce-payments/pull/7047/files#diff-3281997a33f70ad0c3013fdb32857f43264b59ddf3b76dd1f3aef2d0b8b435edR22

**Comment by Jinksi** [comment]
> For `Review the claim`, I've asked Stripe about testing issuer evidence here: p1692835906482299-slack-C9976E5MJ

**Update**: testing [`issuer_evidence` (PDF of issuer claim](https://stripe.com/docs/api/disputes/object#dispute_object-issuer_evidence)) is not possible with test mode transactions. (p1693520733612839/1692835906.482299-slack-C9976E5MJ)

**Comment by Jinksi** [comment]
**Update**: **Review the claim** is no longer part of this issue – now handled in issue #7156.

I've updated the description with this.

**Comment by Jinksi** [comment]
Update: Steps to resolve for **Inquiries** is not part of this issue – now handled in issue #7245.
