### ISSUE TITLE
Transaction Details > Dispute Details > Dispute CTA buttons and Accept dispute modal

### ISSUE THREAD

**Issue by shendy-a8c** [Automattic/woocommerce-payments#6926]
Part of #6883

To the Transaction Details screen we're adding buttons to the dispute details that the merchant can click to challenge or accept their dispute (`needs_response` status).

![image](https://github.com/Automattic/woocommerce-payments/assets/3147296/753a79d4-3b24-4387-b140-ace98aa7fda6)

The `Challenge dispute` button changes to `Continue with challenge` if the merchant has staged evidence (pressed "Save for later" on the challenge form).

Accept dispute modal:

![image](https://github.com/Automattic/woocommerce-payments/assets/3147296/80771e2a-03e7-42a0-9661-6dba5a71a643)

A snackbar should appear, the same like when Payments > Settings page is saved.

![Screenshot 2023-08-07 at 16 00 11](https://github.com/Automattic/woocommerce-payments/assets/73803630/eaf0e2ba-8b5f-4438-ac21-8cf293b36f37)

#### Additional Details
* Related issue for inquiry actions: #7193

**Comment by Jinksi** [comment]
The Accept dispute button opens a confirmation modal – this should be implemented as part of this issue.

**Comment by shendy-a8c** [comment]
Also, a snackbar should appear, the same like when Payments > Settings page is saved.

![Screenshot 2023-08-07 at 16 00 11](https://github.com/Automattic/woocommerce-payments/assets/73803630/eaf0e2ba-8b5f-4438-ac21-8cf293b36f37)
