### ISSUE TITLE
Remove View dispute link in Transaction Details page timeline.

### ISSUE THREAD

**Issue by shendy-a8c** [Automattic/woocommerce-payments#6928]
![Screenshot 2023-08-04 at 09 27 23](https://github.com/Automattic/woocommerce-payments/assets/73803630/d28ee056-ac01-4809-b0cc-0ed43127d084)

Remove `View dispute` link at timeline.

While in there, please also change all timeline text's font size to 13px. Context: p1692552508057969-slack-C03LA109BKM

**Comment by Jinksi** [comment]
I haven't progressed on this issue for a while, so I'll unassign myself from this issue to allow others to pick it up.
