### ISSUE TITLE
Change any link to dispute details link to transaction details link – client.

### ISSUE THREAD

**Issue by shendy-a8c** [Automattic/woocommerce-payments#6929]
Since we are showing the dispute details on the transaction details page, any links to the Dispute details page (i.e. this URL`/wp-admin/admin.php?page=wc-admin&path=%2Fpayments%2Fdisputes%2Fdetails&id={dispute_id}`) now need to link to the relevant changed to Transaction details screen (e.g. `/wp-admin/admin.php?page=wc-admin&path=%2Fpayments%2Ftransactions%2Fdetails&id={id}`).

The goal of this issue is to update any links to dispute details anywhere in WooPayments admin and ensure they work correctly (i.e. link to relevant transaction).

**Comment by Jinksi** [comment]
I haven't progressed on this issue for a while, so I'll unassign myself from this issue to allow others to pick it up.
