### ISSUE TITLE
Multi-Currency Doesn't Work on Pay for Order Page

### ISSUE THREAD

**Issue by zoemyers** [Automattic/woocommerce-payments#6937]
Describe the bug: 

When a manual order is created, the pay for order page doesn't work with the multi-currency switching widget. The currency formatting changes but the currency displayed is still the store currency and no conversion takes place to the correct amount in the chosen currency. 

<img width="1121" alt="Markup 2023-08-04 at 14 04 42" src="https://github.com/Automattic/woocommerce-payments/assets/101880208/9364f914-dd7f-4a30-812e-5adfc74357f7">
<img width="1170" alt="Markup 2023-08-04 at 13 59 23" src="https://github.com/Automattic/woocommerce-payments/assets/101880208/b95bcd34-227f-4fcb-b5d4-20505bd9d99b">

In this case, the merchant reported and I was able to replicate the issue on my test site (which is featured in the screenshots above) 

This is WooPayments 6.2.2 

System Status Report: 

`
### WordPress Environment ###

WordPress address (URL): https://zoewootest.mystagingwebsite.com
Site address (URL): https://zoewootest.mystagingwebsite.com
WC Version: 7.8.1
REST API Version: ✔ 7.8.1
WC Blocks Version: ✔ 10.2.4
Action Scheduler Version: ✔ 3.5.4
Log Directory Writable: ✔
WP Version: 6.2.2
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: ✔

### Server Environment ###

Server Info: nginx
PHP Version: 7.4.33
PHP Post Max Size: 2 GB
PHP Time Limit: 1200
PHP Max Input Vars: 6144
cURL Version: 8.0.1
OpenSSL/1.1.1n

SUHOSIN Installed: –
MySQL Version: 5.5.5-10.4.25-MariaDB-log
Max Upload Size: 2 GB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 7.8.1
WC Database Prefix: wp_
Total Database Size: 24.81MB
Database Data Size: 17.24MB
Database Index Size: 7.57MB
wp_woocommerce_sessions: Data: 0.11MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 0.17MB + Index: 0.17MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 1.52MB + Index: 1.14MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 1.52MB + Index: 0.84MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 1.02MB + Index: 0.14MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 1.02MB + Index: 0.09MB + Engine InnoDB
wp_automatewoo_abandoned_carts: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_automatewoo_customers: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_automatewoo_customer_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_automatewoo_events: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_automatewoo_guests: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_automatewoo_guest_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_automatewoo_logs: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_automatewoo_log_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_automatewoo_queue: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_automatewoo_queue_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_automatewoo_referrals: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_automatewoo_referral_advocate_keys: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_automatewoo_referral_invites: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 0.08MB + Index: 0.09MB + Engine InnoDB
wp_followup_coupons: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_followup_coupon_logs: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_followup_customers: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_followup_customer_carts: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_followup_customer_notes: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_followup_customer_orders: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_followup_email_excludes: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_followup_email_logs: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_followup_email_orders: Data: 0.14MB + Index: 0.09MB + Engine InnoDB
wp_followup_email_tracking: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_followup_followup_history: Data: 0.05MB + Index: 0.05MB + Engine InnoDB
wp_followup_order_categories: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_followup_order_items: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_followup_subscribers: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_followup_subscribers_to_lists: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_followup_subscriber_lists: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_gla_attribute_mapping_rules: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_gla_budget_recommendations: Data: 0.22MB + Index: 0.14MB + Engine InnoDB
wp_gla_merchant_issues: Data: 0.09MB + Index: 0.00MB + Engine InnoDB
wp_gla_shipping_rates: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_gla_shipping_times: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_jckwds: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_custom_fields: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_dynamic_segment_filters: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_feature_flags: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_forms: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_mailpoet_log: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_mailpoet_mapping_to_external_entities: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_newsletters: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_mailpoet_newsletter_links: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_mailpoet_newsletter_option: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_newsletter_option_fields: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_newsletter_posts: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_newsletter_segment: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_newsletter_templates: Data: 2.52MB + Index: 0.00MB + Engine InnoDB
wp_mailpoet_scheduled_tasks: Data: 0.06MB + Index: 0.03MB + Engine InnoDB
wp_mailpoet_scheduled_task_subscribers: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_segments: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_mailpoet_sending_queues: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_mailpoet_settings: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_statistics_bounces: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_mailpoet_statistics_clicks: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_mailpoet_statistics_forms: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_statistics_newsletters: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_mailpoet_statistics_opens: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_mailpoet_statistics_unsubscribes: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_mailpoet_statistics_woocommerce_purchases: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_mailpoet_stats_notifications: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_mailpoet_subscribers: Data: 0.02MB + Index: 0.13MB + Engine InnoDB
wp_mailpoet_subscriber_custom_field: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_subscriber_ips: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_subscriber_segment: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_mailpoet_subscriber_tag: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_mailpoet_tags: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_user_agents: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_user_flags: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_options: Data: 2.05MB + Index: 0.14MB + Engine InnoDB
wp_postmeta: Data: 1.52MB + Index: 0.84MB + Engine InnoDB
wp_posts: Data: 0.14MB + Index: 0.06MB + Engine InnoDB
wp_snippets: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_term_relationships: Data: 0.05MB + Index: 0.02MB + Engine InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Data: 0.06MB + Index: 0.03MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.08MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.08MB + Index: 0.02MB + Engine InnoDB
wp_wc_bookings_availability: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_bookings_availabilitymeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_booking_relationships: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_deposits_payment_plans: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_deposits_payment_plans_schedule: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_bundle_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_order_composite_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_attributes_lookup: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_download_directories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_bundled_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_bundled_items: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_gc_activity: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_gc_cards: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_gc_cardsmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_table_rates: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_square_customers: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpml_mails: Data: 2.52MB + Index: 0.00MB + Engine InnoDB
wp_wp_phpmyadmin_extension__errors_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB

### Post Type Counts ###

addf_prc_pt: 1
attachment: 41
aw_workflow: 5
bookable_resource: 5
custom_css: 3
follow_up_email: 2
global_product_addon: 1
mailpoet_page: 1
nav_menu_item: 14
page: 17
post: 2
product: 74
product_variation: 74
revision: 32
shop_coupon: 5
shop_order: 79
shop_order_refund: 1
shop_subscription: 15
wc_booking: 5
wc_membership_plan: 1
wc_user_membership: 3
wc_voucher_template: 1
wp_global_styles: 2

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (2) ###

WooCommerce Payments: by Automattic – 6.2.2
WooCommerce: by Automattic – 7.8.1 (update to version 7.9.0 is available)

### Inactive Plugins (58) ###

Akismet Anti-Spam: Spam Protection: by Automattic - Anti Spam Team – 5.2
AutomateWoo: by WooCommerce – 5.7.3
AutomateWoo - Refer A Friend Add-on: by WooCommerce – 2.6.8
Check Conflicts: by ioannup – 1.1.4
Database Access with Adminer: by Roy Orbison – 2.0.0
Facebook for WooCommerce: by Facebook – 3.0.23
Filter Featured for WooCommerce: by Backpack.Studio – 1.0.1
Follow-Up Emails: by WooCommerce – 4.9.24
Google Listings and Ads: by WooCommerce – 2.4.10
Homepage Control: by WooThemes – 2.0.3
Jetpack: by Automattic – 12.5-a.1
Loco Translate: by Tim Whitlock – 2.6.4
Lottery for WooCommerce: by Flintop – 8.4.0
Prepaid for WooCommerce Subscriptions: by Meow Crew – 3.2.1 (update to version 4.1.1 is available)
Price Calculator for WooCommerce: by Addify – 1.0.3
Query Monitor: by John Blackbourn – 3.13.0
Sticky Cart For WooCommerce: by SkroTron – 1.1.6
Storefront Powerpack: by WooCommerce – 1.6.2
Teams for WooCommerce Memberships: by SkyVerge – 1.6.3 (update to version 1.7.0 is available)
Tiered Price Table for WooCommerce: by U2Code – 4.5.2
User Roles Editor for WooCommerce: by FME ADDONS – 1.0.4
Variations as single products for WooCommerce: by Procom – 1.0.3
WCS staging: by mb – 1.0
WooCommerce All Products For Subscriptions: by WooCommerce – 3.3.1 (update to version 4.1.2 is available)
WooCommerce Anti Fraud: by OPMC Australia Pty Ltd – 4.9 (update to version 5.5.1 is available)
WooCommerce Blocks: by Automattic – 10.5.0
WooCommerce Bookings: by WooCommerce – 1.15.74 (update to version 2.0.0 is available)
WooCommerce Bookings Availability: by WooCommerce – 1.1.20
WooCommerce Brands: by WooCommerce – 1.6.38 (update to version 1.6.55 is available)
WooCommerce Chained Products: by StoreApps – 2.11.0 (update to version 3.0.0 is available)
WooCommerce Checkout Field Editor: by WooCommerce – 1.7.3 (update to version 1.7.10 is available)
WooCommerce Composite Products: by WooCommerce – 8.5.0 (update to version 8.10.1 is available)
WooCommerce Conditional Shipping and Payments: by WooCommerce – 1.14.0 (update to version 1.15.2 is available)
WooCommerce Delivery Slots by Iconic: by Iconic – 1.18.0
WooCommerce Deposits: by WooCommerce – 2.1.5 (update to version 2.1.7 is available)
WooCommerce Eway Payment Gateway: by WooCommerce – 3.5.2 (update to version 3.7.0 is available)
WooCommerce FedEx Shipping: by WooCommerce – 3.7.2 (update to version 3.8.2 is available)
WooCommerce Force Sells: by WooCommerce – 1.1.30 (update to version 1.2.0 is available)
WooCommerce Gift Cards: by WooCommerce – 1.15.1 (update to version 1.16.3 is available)
WooCommerce Memberships: by SkyVerge – 1.23.0 (update to version 1.25.0 is available)
WooCommerce Min/Max Quantities: by WooCommerce – 4.0.4 (update to version 4.1.0 is available)
WooCommerce Mix and Match Products: by Kathy Darling – 1.12.0 (update to version 2.4.10 is available)
WooCommerce One Page Checkout: by Automattic – 1.9.9 (update to version 2.6.0 is available)
WooCommerce PDF Product Vouchers: by SkyVerge – 3.9.17 (update to version 3.12.2 is available)
WooCommerce Product Add-ons: by WooCommerce – 4.9.0 (update to version 6.4.4 is available)
WooCommerce Product Bundles: by WooCommerce – 6.17.3 (update to version 6.22.2 is available)
WooCommerce Product CSV Import Suite: by WooCommerce – 1.10.46 (update to version 1.10.60 is available)
WooCommerce Shipment Tracking: by WooCommerce – 2.0.0 (update to version 2.3.3 is available)
WooCommerce Shipping & Tax: by WooCommerce – 2.2.5 (update to version 2.3.1 is available)
WooCommerce Stripe Gateway: by WooCommerce – 7.4.2
WooCommerce Subscriptions: by WooCommerce – 5.1.2 (update to version 5.3.1 is available)
WooCommerce Subscriptions Gifting: by WooCommerce – 2.5.1 (update to version 2.7.0 is available)
WooCommerce Table Rate Shipping: by WooCommerce – 3.0.38 (update to version 3.1.1 is available)
WooCommerce UPS Shipping: by WooCommerce – 3.4.3 (update to version 3.5.1 is available)
WooCommerce USPS Shipping: by WooCommerce – 4.4.73 (update to version 4.7.1 is available)
WordPress Importer: by wordpressdotorg – 0.7
WP Mail Logging: by Wysija – 1.10.4
YayMail Addon for AutomateWoo: by YayCommerce – 1.6

### Dropin Plugins (2) ###

advanced-cache.php: advanced-cache.php
object-cache.php: Memcached

### Settings ###

API Enabled: –
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: booking (booking)
bundle (bundle)
composite (composite)
external (external)
grouped (grouped)
mix and match (mix-and-match)
simple (simple)
subscription (subscription)
variable (variable)
variable subscription (variable-subscription)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: ✔
Enforce Approved Product Download Directories: –
HPOS feature screen enabled: –
HPOS feature enabled: –
Order datastore: WC_Order_Data_Store_CPT
HPOS data sync enabled: –

### WC Pages ###

Shop base: #5 - /shop/
Cart: #6 - /cart/
Checkout: #11912 - /checkout3/
My account: #8 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Storefront
Version: 4.2.0 (update to version 4.4.1 is available)
Author URL: https://woocommerce.com/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: /srv/htdocs/wp-content/plugins/woocommerce/packages/woocommerce-blocks/templates/notices/error.php
/srv/htdocs/wp-content/plugins/woocommerce/packages/woocommerce-blocks/templates/notices/notice.php
/srv/htdocs/wp-content/plugins/woocommerce/packages/woocommerce-blocks/templates/notices/success.php

### Subscriptions ###

WCS_DEBUG: ✔ No
Subscriptions Mode: ✔ Live
Subscriptions Live URL: https://zoewootest.mystagingwebsite.com
Subscriptions-core Library Version: 6.0.0
Subscription Statuses: wc-pending: 2
wc-on-hold: 9
wc-cancelled: 2
wc-pending-cancel: 1
wc-scheduled: 1

WooCommerce Account Connected: ✔ Yes
Active Product Key: ❌ No

### Store Setup ###

Country / State: United States (US) — North Carolina

### Subscriptions by Payment Gateway ###

other: wc-on-hold: 1
wc-pending: 1

WooPayments: wc-cancelled: 2
wc-on-hold: 7

### Payment Gateway Support ###

WooPayments: products
refunds
multiple_subscriptions
subscription_cancellation
subscription_payment_method_change_admin
subscription_payment_method_change_customer
subscription_payment_method_change
subscription_reactivation
subscription_suspension
subscriptions
gateway_scheduled_payments
tokenization
add_payment_method

Cash on delivery: products

### Admin ###

Enabled Features: activity-panels
analytics
product-block-editor
coupons
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: core-profiler
minified-js
new-product-management-experience
product-variation-management
settings
async-product-editor-category-field

Daily Cron: ✔ Next scheduled: 2023-08-05 15:04:53 -04:00
Options: ✔
Notes: 120
Onboarding: completed

### WooCommerce Payments ###

Version: 6.2.2
Connected to WPCOM: Yes
Blog ID: 206048937
Account ID: acct_1LxFuI2EAq4xD78i

### Action Scheduler ###

Complete: 188
Oldest: 2023-07-05 11:53:39 -0400
Newest: 2023-08-04 13:58:01 -0400

Pending: 6
Oldest: 2023-08-04 14:26:04 -0400
Newest: 2024-01-31 23:00:00 -0500

Failed: 171
Oldest: 2022-06-25 16:16:06 -0400
Newest: 2023-08-03 17:37:42 -0400

### Status report information ###

Generated at: 2023-08-04 14:26:15 -04:00
`

This is similar to but behavior is different from https://github.com/Automattic/woocommerce-payments/issues/5031

This definitely seems to be a bug, but let me know if I can provide any additional information.

**Comment by benhager** [comment]
Is there any estimate on when this issue might be able to be resolved? Or when would that type of estimate be available?

Best Regards,
-Ben

**Comment by jessepearson** [comment]
I am closing this in favor of #5031 since the issue there was broadly stated that currency switching doesn't work, both from the widget(s) and the automatic location based switching.

Currency switching is disabled on the Pay for Order page due to the currency is already set in the order, and the prices are already set on the order items. This includes taxes, shipping, etc. Since all of those values can be controlled by other plugins/extensions before the order is created, we cannot guarantee we would be converting the values correctly.

There is a PR created to remove the currency switcher widgets and to disable the automatic switching on the currency page: #7152 

If a different currency is needed for an order being placed by a store admin, the store admin can create the order on the front end by using another gateway like the Check/Cheque method, then switch the user on the order in the admin after the fact. They can also use a plugin like User Switching to place the order as a user.
