### ISSUE TITLE
"Paid" status chip in Transaction details should map to same green used in "Paid" status in Deposits

### ISSUE THREAD

**Issue by elizaan36** [Automattic/woocommerce-payments#6938]
### Description
As mentioned in #6794 there's a discrepancy where the `Paid` status chip is mapped to different colors between the Deposits and Transactions areas.

Transactions Details
<img width="1092" alt="image" src="https://github.com/Automattic/woocommerce-payments/assets/5121465/521768f3-db9d-440e-be9a-8230fd50b2a4">

Deposits
<img width="1221" alt="image" src="https://github.com/Automattic/woocommerce-payments/assets/5121465/cd286e1e-8d22-460f-9cf5-05adb000bf31">

Even though the meaning of "Paid" is different in each of these contexts, we feel the status label should reflect the same color to align the visual meaning of "Paid" for merchants.

### Solution

<img width="770" alt="image" src="https://github.com/Automattic/woocommerce-payments/assets/5121465/1e0738f5-6b61-4998-9199-b198b0109ed9">

Since green offers a moment of celebration and success, we think the `Paid` status chip should be mapped to the green color throughout. So the gray color in the transaction details should be replaced with green.

@Jinksi I'll ping you on this one, but feel free to recommend others for input.

**Comment by RadoslavGeorgiev** [comment]
This issue impacts transactions, so assigning to @Automattic/pulsar  (based on team responsibilities Pc2DNy-3z-p2), tagging @kalessil. Assigning as part of Gamma Triage process PcreKM-yM-p2.

**Comment by Jinksi** [comment]
Helix can take this issue as we are currently working on updating both the `Chip` component (#6794) and the Transactions/Disputes screen (#6883) as part of the Improving Dispute Response Part 2A project: pdjTHR-2PC-p2.

Thanks for the ping @elizaan36.
