### ISSUE TITLE
Limit WCPay to merchants in supported countries only

### ISSUE THREAD

**Issue by allendav** [Automattic/woocommerce-payments#694]
@thenbrent @bmccotter - looks like we check the currency but overlooked checking the country for the store - we should fix this, right?

If so, what we do about Puerto Rico? It would appear we are supporting it already as a result of this oversight.

3005814-zd

https://github.com/Automattic/woocommerce-payments/blob/5926ec62a950409015ef2264dfbac3cec2fe67d3/includes/class-wc-payment-gateway-wcpay.php#L216

props @DanReyLop

**Comment by timmyc** [comment]
Dropping in with a ➕ on this - I'd really like for us to be able to call out to a method in WCPay from wc-admin to determine easily if we should be featuring WCPay based upon country support. As I mentioned in Slack - we are just now getting things rolling to have WooCommerce Payments installed on all new ecom plan sites on WordPress.com. The way the Atomic "plumbing" works for this is to just add the plugin to an array for either Install/Activate - which works great, but then can lead to some interesting logic in wc-admin to determine if we should still be actively promoting WCPay for a given store.

We are already starting to sprinkle in some country code specific checks into wc-admin for this, and I fear that will create more work/things to check and update as WCPay expands to other locales.

**Comment by thenbrent** [comment]
Related: we saw a number of issues recently in the Stripe extension when it was changed to use the store's country to determine the store's ability to use a payment method. Some businesses have a legal entity in the US, while their store operates in a different jurisdiction.

**Comment by vbelolapotkov** [comment]
Related discussion: p1614781403172900-slack-CGGCLBN58

**Comment by kalessil** [comment]
@thenbrent, since we have enabled more countries, can we close this ticket?

**Comment by jrodger** [comment]
I don't think we can close it, but a new issue description and title would be a good idea. This one confuses me every time I open it.

The launch in more countries doesn't change the issue we're trying to fix here, there are still cases where we want to detect whether a store is in a supported country or not (it's just that this isn't limited to the US now). To be honest, I'm not sure we've completely figured out how we want to do that yet either.

**Comment by kalessil** [comment]
@jrodger : I see, updated the title.

Leaving more considerations:
- while onboarding new merchants, the available countries are configured in the platform account
- merchants from other countries, will run into the issue that they are not able to register a Stripe account for their country
- if the check is introduced, and we are able to reliably identify the shop country, ensure the enabled countries are fetched from the server (not client, as we can not control the client updates, but we can deploy server changes frequently)

**Comment by LevinMedia** [comment]
This is going to function as a double-check to keep people from getting frustrated when they get into the KYC and wonder why their country isn't supported.

If we notice they're in an unsupported country - we'd display this modal:

<img width="532" alt="Screen Shot 2021-06-14 at 11 05 10 AM" src="https://user-images.githubusercontent.com/4500952/121953579-97834500-cd12-11eb-8475-94e833e058c2.png">

The primary action is cancel, however the merchant can still continue because there's the edge case where they're simply using a computer from an unsupported location, but they're still based in one of the available countries.

**Comment by kalessil** [comment]
We also might want to pick up #2105 as it sounds related to this one.
