### ISSUE TITLE
Webpack config to transpile CSS files used in PHP

### ISSUE THREAD

**Issue by elazzabi** [Automattic/woocommerce-payments#6943]
The current [webpack config](https://github.com/Automattic/woocommerce-payments/blob/develop/webpack/shared.js) transpiles CSS files used in JS files only. But a few others are used in PHP files (Currently 2 files in `/assets/*.css`).

While that has been working for now, with the new RTL support, we need a way to transpile those files to generate their RTL equivalent.

Currently, we removed enqueuing RTL for these files, but we would like to be able to generate RTL for those too 4da1a3aec

**Comment by elazzabi** [comment]
@ismaeldcom as discussed, here is the issue for the new webpack config :)

**Comment by ismaeldcom** [comment]
Thanks for taking care of it @elazzabi!

Among other solutions, we can handle this by adding an additional Webpack configuration to manage those CSS files in the `assets/` folder. In this way we don't need to use any other tool, and build time increase should be unnoticeable.

Some documentation about it can be found on [Exporting multiple configurations.](https://webpack.js.org/configuration/configuration-types/#exporting-multiple-configurations)

**Comment by zmaglica** [comment]
During our prioritization call, we addressed this issue and realized it may not have been fully triaged. We did not thoroughly elaborated the context regarding the issue's impact, its complexity, and the overall benefit to the customer.

@elazzabi, could you provide insights into the specifics of this issue, its level of impact, and the anticipated benefits?

**Comment by elazzabi** [comment]
Hello @zmaglica, thank you for looking into this! I'm sorry for not getting back to you sooner, I was in a long AFK.

Here's a more specific presentation of this issue, let me know if you have any further questions:

### Specifics
During the building process of our plugin, we create and export two versions of our CSS files: The normal LTR (Left-to-Right languages), and another RTL (Right-to-Left languages) version.

When a customer switches their WordPress installation to an RTL language (like Arabic), we load the RTL-specific CSS files instead of the default ones. This ensures that most of our screens' padding, margin, and spacing are RTL-ready.

Currently, we have two types of CSS files: Those generated and enqueued from PHP to style the administration/WP-pages/etc, and those to style the React application.

The problem: Given the RTL CSS files are generated from the LTR counterparts, this is done as part of the project building step via webpack. But given PHP doesn't need building, and the current webpack config can't access CSS files outside of the JS repository, those CSS files (used in PHP) aren't converted to their RTL equivalent.

### Level of impact
Realistically, this impacts *one* country (UAE) out of all the countries we support. So I believe it's a low impact for now.

### Anticipated benefits
This will make our product completely ready for RTL support.

So far, we're not preparing the whole CSS files. The core React application is ready for RTL, but pages that are controlled by PHP only are not. Also, realistically, this is a small set only.

With what we currently have, we are taking care of 80-90%, this issue is for the remaining 10% only.

**Comment by souravdebnath1986** [comment]
Thank you @elazzabi. If the impact is low, can we mark this issue as `won't fix` and close the issue ?

**Comment by anu-rock** [comment]
@souravdebnath1986 I see there's already a PR for this issue at #8264 with one approving review. I think it won't be long before it's closed by merging the PR.
