### ISSUE TITLE
UGX generates zero decimal currency errors because should not be zero based

### ISSUE THREAD

**Issue by nicdwilson** [Automattic/woocommerce-payments#6946]
### Describe the bug

UGX is now a zero decimal currency, and placing orders in UGX generates errors. 

### To Reproduce

1. Go to shop base settings and set UGX as base currency
2. Set up a product using UGX and checkout
3. Checkout

### Actual behavior

![3MopCA.png](https://github.com/Automattic/woocommerce-payments/assets/3624025/82a71bdf-e747-49e6-a812-3b0854d64ac8)

With UPE disabled a general error occurs `We cannot process at this time`

### Expected behavior

UGX is supported, as it shows as available as a base currency

### Additional context
6626828-zd-a8c

**Comment by RadoslavGeorgiev** [comment]
Triage note: There is no priority specified within the issue, but the inability to process a currency, which should be supported, seems significant. At the same time, it looks like we never had transactions with it.

**Comment by nicdwilson** [comment]
https://github.com/woocommerce/woocommerce-gateway-stripe/issues/2674 explains the problem fully

**Comment by nicdwilson** [comment]
The merchant in 6626828-zd-a8c is currently unable to transact because of this error. Any chance of a prioritization to allow feedback to them on this?

It's also worth adding that if you are running multi-currency, pricing gets two zeroes knocked off it if the site has UGX enabled.

**Comment by zoupkat** [comment]
Hello @RadoslavGeorgiev (or anyone else that can offer input)!
Can someone please take a look at Nic's comment above and let us know?
The user is waiting for an update.
Thank you!

**Comment by ncsramona** [comment]
Hi folks! I was played into the ticket (6626828-zd) and wondering if there's any update on this?

**Comment by thisissandip** [comment]
6626849-zen

**Comment by thisissandip** [comment]
7220457-zen

**Comment by pierorocca** [comment]
@frosso @diegocurbelo welcome to my rotation week! This ticket came up in my triaging :) Similar to other zero decimal currency issues, given the 100x over or under change potential, we need to put a critical level type of priority on these when they come up. Merchant is reporting they're using Stripe, and considering WooPayments.

**Comment by naman03malhotra** [comment]
We have released a temporary fix for this, however it warrants a proper fix: https://github.com/Automattic/woocommerce-payments/pull/7575

**Comment by naman03malhotra** [comment]
Closing in favor of issues defined here: p1700151428703539/1699610429.755939-slack-C01B8KNUYSW
