### ISSUE TITLE
Link payment method occasionally stored with incorrect meta_key

### ISSUE THREAD

**Issue by csmcneill** [Automattic/woocommerce-payments#6963]
### Describe the bug
We've had two reports of merchants who are unable to make any refunds for payments that are processed via Stripe Link.

Somehow, when the payments are made, the `_payment_method` meta_key is stored as `woocommerce_payments_link` in the postmeta table instead of `woocommerce_payments`.

An HE was able to resolve this on one site by manually changing the meta_key from woocommerce_payments_link to woocommerce_payments, but we don't know how the orders got this way.

### To Reproduce
So far, we've been unable to reproduce this issue, and I've tried lots of testing as outlined in p1691011054410049/1691006693.911279-slack-C03EE4CPPK5

### Actual behavior
Orders affected by this issue will act as though WooPayments isn't active. There is only a manual refund option, and the `pi_` string is not a hyperlink.

### Screenshots
Normal order:
<img width="1441" alt="Markup 2023-08-02 at 16 33 05" src="https://github.com/Automattic/woocommerce-payments/assets/82999806/9f4678fd-bb61-4ba6-b2d4-d7f1821e4b8c">

The same order with WooPayments disabled:
<img width="1441" alt="Markup 2023-08-02 at 16 35 52" src="https://github.com/Automattic/woocommerce-payments/assets/82999806/7fad993f-85d4-4e57-b0d8-e353919dc642">

An affected order looks similar to the second screenshot, except it reads `Payment via woocommerce_payments_link`.

### Expected behavior
The `_payment_method` meta_key is stored as `woocommerce_payments` in the postmeta table.

### Additional context

6577325-zen
6614815-zen
p1691006693911279-slack-C03EE4CPPK5
p1691460770351259-slack-C7U3Y3VMY

**Comment by dpaun1985** [comment]
This issue was fixed in #6784 by setting `woocommerce_payments` as payment method for Link in UPE split context.

We can reopen the issue if the problem persists.
