### ISSUE TITLE
Subscriptions Step 1: Process sub sign ups

### ISSUE THREAD

**Issue by allendav** [Automattic/woocommerce-payments#697]
Epic: #117

There is a [doc for this](https://docs.woocommerce.com/document/subscriptions/develop/payment-gateway-integration/#section-2), but much of it won’t apply here because tokens can be used with WC Pay. Because WC Pay can use tokens, we’ll get almost all of Subscriptions features for free once we have a token connected to the subscription.

**Comment by DanReyLop** [comment]
I have a branch for this issue almost ready for review. I'm having a few problems with Customer objects and Payment Methods, I don't think it's working correctly in `master` either.

I'll finish this after my AFK.

**Comment by allendav** [comment]
@DanReyLop 

> I have a branch for this issue almost ready for review.

Please push the WIP branch and we'll move it forward for you while you're gone.

cc @RadoslavGeorgiev
