### ISSUE TITLE
Unclear description when enabling Auth & Capture

### ISSUE THREAD

**Issue by KarlisJ** [Automattic/woocommerce-payments#6972]
### Describe the bug
In the Payments -> settings we have "Issue an authorization on checkout, and capture later" checkbox and it has description 
> Charge must be captured on the order details screen within 7 days of authorization, otherwise the authorization and order will be canceled. The setting is not applied to In-Person Payments (please note that In-Person Payments should be captured within 2 days of authorization).

Given that my account doesn't have in-Person Payments enabled it seems confusing that it's mentioned. If I'm not aware of what in-Person payments are, I might be tempted to bail out of Auth & Capture.

### Screenshots

![image](https://github.com/Automattic/woocommerce-payments/assets/24650518/8f3e5efc-a97a-4ed1-84b9-bf74a07bf3bf)

**Comment by RadoslavGeorgiev** [comment]
This issue impacts Auth and Capture, so assigning to @Automattic/pulsar (based on team responsibilities Pc2DNy-3z-p2). Assigning as part of Gamma Triage process PcreKM-yM-p2.
