### ISSUE TITLE
Missing fields data on progressive onboarding

### ISSUE THREAD

**Issue by ismaeldcom** [Automattic/woocommerce-payments#6981]
### Describe the bug
A merchant reported not being able to select the country on the progressive onboarding flow.

### To Reproduce
We need to try to find the reason to the issue and reproduce it.

### Actual behavior
After reaching the business step on the progressive onboarding flow, the country input is empty.

### Expected behavior
The country input should have options.

### Screenshots
<img width="480" alt="image" src="https://github.com/Automattic/woocommerce-payments/assets/7670276/46b51900-0cab-4b9e-bd47-c350960138d8">

### Additional context
Country and business structures comes from the server. Our logs (p1691751413029599/1691741924.088819-slack-C03KTTK2YMA) show that the request for those details have a 401 status. That means that the Jetpack connection is not working as expected.

Before reaching that step in the onboarding process, we check for the Jetpack connection and request it before proceeding. We need to investigate if it's possible to successfully pass that check with a flaky connection, causing the issue. In this case, the site has an old connection.

Slack conversation: p1691741924088819-slack-C03KTTK2YMA
Ticket: 6610367-zd-a8c

**Comment by ismaeldcom** [comment]
Tried to check the mentioned case of Jetpack connection being flaky, but after using a JN site I noticed that an invalid `Blog Token` doesn't cause any issue here, and an invalid `User Token` will throw an error before redirecting to the onboarding flow, and will prevent being able to see the empty field.

**Comment by daquinons** [comment]
Additional debugging p1694511664067099-slack-C03KTTK2YMA
