### ISSUE TITLE
Adjust WooPay "custom message" to be reused for T&C and privacy policy

### ISSUE THREAD

**Issue by frosso** [Automattic/woocommerce-payments#6993]
## Description

<img width="1440" alt="Preview - WooPay Customizations" src="https://github.com/Automattic/woocommerce-payments/assets/110893979/68d54036-2326-49de-a19c-02af8f3534bc">

WooPay sites need to include the merchant site's T&C & Privacy Policy. We need to make some adjustments to ensure we can link those merchant pages from WooPay.

## Acceptance criteria
- "Custom message" label/title is renamed to "Policies and custom text" (just rename the label in the UI, no need to modify the field name - since it's also used on WooPay, we don't want to also make changes on the WooPay server)
- "Custom message" textbox is converted to a text area, without a character limit
- "Policies and custom text" will need to have the following text presented by default (until the merchant overrides it): 
	- Option 1: 'By placing this order, you agree to our [Terms of Service] and understand our [Privacy Policy].'
		- Where `[Terms of Service]` is shown in the UI as `<a href="https://merchant-site.com/TOS-page-link" target="_blank" rel="noopener noreferrer">Terms of Service</a>` when the page exists, otherwise it is shown in the UI as `Terms of Service`
		- Where `[Privacy Policy]` is shown in the UI as `<a href="https://merchant-site.com/Privacy-Policy-page-link" target="_blank" rel="noopener noreferrer">Privacy Policy</a>` when the page exists, otherwise it is shown in the UI as `Privacy Policy`
	- Option 2: 'By placing this order, you agree to our [terms_of_service_link] and understand our [privacy_policy_link].'
		- Where `[terms_of_service_link]` and `[privacy_policy_link]` are respectively replaced by the correct links and sent to WooPay on session initialization to `<a href="https://merchant-site.com/TOS-page-link" target="_blank" rel="noopener noreferrer">Terms of Service</a>` (or by the plaintext `Terms of Service` if the page doesn't exist) and `<a href="https://merchant-site.com/Privacy-Policy-page-link" target="_blank" rel="noopener noreferrer">Privacy Policy</a>` (or by the plaintext `Privacy Policy` if the page doesn't exist)
- "Policies and custom text" help text is replaced by "Override the default [privacy policy](https://proccaatomic.wpcomstaging.com/wp-admin/admin.php?page=wc-settings&tab=account) and terms of service, or add custom text to WooPay checkout." (update the "privacy policy" link to the sites' privacy policy page)

**Comment by frosso** [comment]
Thanks for the fast turnaround @gpressutto5 ! 💪

**Comment by pierorocca** [comment]
@frosso @gpressutto5 awesome work getting this gap closed. Lets please ensure these are being demoed to product and design before merging the PRs. Note the attached mock is outdated relative to the latest design Stephen provided. Looks like the acceptance criteria is in line with the design though. https://github.com/Automattic/woocommerce-payments/issues/6639#issuecomment-1678403303

**Comment by pierorocca** [comment]
@frosso @stephendharmadi on 6.4.1 the help text links to the policy pages rather than the policy acceptance copy. The custom message is supposed to replace the shopper terms acceptance copy, not the policy pages themselves. That makes the merchant instructions misleading

If I clear the custom text, then there's nothing displayed on hosted checkout. With 1500+ merchants already live, let's look at how we can get them to a good baseline. 

I'm thinking a matrix like what Kris put together for the https://github.com/Automattic/woocommerce-payments/issues/6994#issuecomment-1701665168 would be useful for this use case.

https://github.com/Automattic/woocommerce-payments/assets/109928953/f462974f-ec6c-44d4-9538-986a2575fa6f

**Comment by pierorocca** [comment]
Got up to speed on the implementation and I did a bit of testing and we're better off than I had thought.

1. For newly created sites, the default text and embedded shortcode links is great. Awesome job.
2. For existing sites, of which there are 1500, do those sites get the default text if there's no existing custom text? 
3. If no to 2, is there a way to either update their custom text and then honor their choice if they then delete it? Alternative option is to send a RIN to the existing 1500 merchants to get them to set their policies in the settings.
4. The helper text is confusing due in part to my poor choice of wording and the change in the link from the acceptance criteria which pointed to the policy settings not the policy page as implemented. I can interpret the existing copy different ways and the links to the policy pages that may or may not display depending if the pages are set is unpredictable and likely confusing to a merchant. My recommendation is to update the helper text to that attached below and include a [Learn more](https://woocommerce.com/document/woopay-merchant-documentation/#checkout-appearance) link to the relevant documentation.

Thanks for your patience on this @frosso and @bummytime. Bummy if 4 is the only change, is a patch like this considered low risk and doable? Or added to the expected 6.4.2 release?

![image](https://github.com/Automattic/woocommerce-payments/assets/109928953/a8cc359b-4189-4e7a-a7e0-5c7a46117fd8)

**Comment by frosso** [comment]
> For existing sites, of which there are 1500, do those sites get the default text if there's no existing custom text?

I just tested this by upgrading an onboarded site from 6.3.2 to 6.4.1. The text was kept blank.
Only newly onboarded merchants would get the default text.

> If no to 2, is there a way to either update their custom text and then honor their choice if they then delete it? Alternative option is to send a RIN to the existing 1500 merchants to get them to set their policies in the settings.

One thing we _could_ do is overwrite the textarea's content every time that the merchant erases its contents. But I don't think that's desirable; it would just become confusing to clear the text, save, and see the text reappear.

What do you think about adding a button that resets the textarea's content to the "default" text? Once clicked, the textarean's content would be overwritten by our default text, and the merchant would be able to save the settings again.

> My recommendation is to update the helper text to that attached below and include a [Learn more](https://woocommerce.com/document/woopay-merchant-documentation/#checkout-appearance) link to the relevant documentation.

We can add a help text and update the help text. To confirm, besides the help text update, would you also like to update the "privacy policy" and "terms of service" links on the help text to something else? Or not have links at all (besides the "Learn more" link)?

> Thanks for your patience on this @frosso and @bummytime. Bummy if 4 is the only change, is a patch like this considered low risk and doable? Or added to the expected 6.4.2 release?

Next week/today we can proceed with implementing the updates, once we confirm the scope above ☝️ 

The decision process on whether a patch release is desirable is outlined here: PaJDYF-95v-p2#is-patch-necessary
WooPayments 6.5.0 is scheduled to be released on Sep 20 ( PaJDYF-1gY-p2 )

**Comment by pierorocca** [comment]
Thanks for having a look @frosso on short notice.

> One thing we could do is overwrite the textarea's content every time that the merchant erases its contents. But I don't think that's desirable; it would just become confusing to clear the text, save, and see the text reappear.

I agree that's not desirable.

> What do you think about adding a button that resets the textarea's content to the "default" text? Once clicked, the textarean's content would be overwritten by our default text, and the merchant would be able to save the settings again.

I like this idea. Looking at Shopify for inspiration, they use a "Create from template" and "Replace from template" approach for policy generation. See attached. For terms acceptance, they have the luxury that we do not, of placing policy links in the footer that are visible on all pages including all checkout pages.

So how about a button, only a single state, labeled "Insert default text" or "Create from template"?

https://d.pr/v/MiAbUH

> We can add a help text and update the help text. To confirm, besides the help text update, would you also like to update the "privacy policy" and "terms of service" links on the help text to something else? Or not have links at all (besides the "Learn more" link)?

No. I found it weird that on a new site without the pages created and set, there were no links yet I was instructed to overwrite the pages. Then if I set one or more pages, one or more links appeared. It won't be obvious to a new merchant why this is happening, especially since the whole policy setup for a site is complicated and fragmented. Note Blocks currently does not persist terms of service and I don't see anything in the FSE that allows the terms of service page to be set. So Blocks sites may never have the link visible. So I'm recommending a simpler approach where we state what is required, provide a link to the instructions if needed, and provide two ways to pre-populate the text - added by default for new sites OR by the new button above.

Sept 20th can work if 6.4.2 isn't an option. As Bummy pointed out at least new sites will all have the new default text.

cc @stephendharmadi for visibility and comment.

**Comment by pierorocca** [comment]
Until WooCommerce core re-vamps the entire policy approach, populating default text rather than trying to pull in the copy from the account and privacy settings is the only viable option.

**Comment by frosso** [comment]
> > What do you think about adding a button that resets the textarea's content to the "default" text? Once clicked, the textarean's content would be overwritten by our default text, and the merchant would be able to save the settings again.

> I like this idea. Looking at Shopify for inspiration, they use a "Create from template" and "Replace from template" approach for policy generation. See attached. For terms acceptance, they have the luxury that we do not, of placing policy links in the footer that are visible on all pages including all checkout pages.

> So how about a button, only a single state, labeled "Insert default text" or "Create from template"?

@pierorocca Another option to allow merchants to use the custom message: I was looking for similar patterns in the WC admin. I couldn't find examples that allowed merchants to "restore to default" with the click of a button.
Instead, what I found, is that we use checkboxes to show/hide settings. 

I was wondering if you had strong preferences on using the button to "restore" the text to the default value, or if we should instead conform to the "default" WC settings, where we could have a checkbox (checked by default) that controls what the custom text would need to be. When unchecked, the merchant would be allowed to set some custom text.

A few existing examples in WC admin:
![2023-09-12 15 04 50](https://github.com/Automattic/woocommerce-payments/assets/273592/1d918380-f6c4-4e10-8869-28dcf836c0de)
![2023-09-12 15 09 09](https://github.com/Automattic/woocommerce-payments/assets/273592/8deebf00-6db3-4ca9-9b15-d3a11b35258b)

Do you have any preference on whether we should be using a checkbox or a button to reset the value?

Example:
![2023-09-12 15 21 30](https://github.com/Automattic/woocommerce-payments/assets/273592/1203ab18-30b6-408d-945b-d6865c3fb0bf)

**Comment by pierorocca** [comment]
@frosso thanks for exploring existing patterns and for your scrutiny and looking for alternatives. I'll defer to @elizaan36 and @stephendharmadi. If we follow this approach I'd like to see a shorter checkbox label/title (e.g. Display default checkout policies) and to eliminate the "override the default.." copy as it's unnecessary.

**Comment by stephendharmadi** [comment]
Hey @frosso, thanks for exploring the pattern. I see the checkbox works fine and we can use it. Just to confirm, do we recommend merchant link their privacy policy and terms of service page at checkout? If yes then we can make it checked by default.

**Comment by pierorocca** [comment]
> Just to confirm, do we recommend merchant link their privacy policy and terms of service page at checkout?

@stephendharmadi yes that's correct. We recommend it because normally the policies are either in the store footer or on the standard checkout page. With hosted checkout, it's possible the shopper never sees the policy links depending on how the store is configured.

**Comment by frosso** [comment]
I created a new ticket to outline this work ( https://github.com/Automattic/woocommerce-payments/issues/7196 ). @stephendharmadi @pierorocca if you have any preferences on the checkbox copy and/or the textarea copy, please feel free to edit the ticket's description!
