### ISSUE TITLE
WooPay checkout appearance preview UI refactor

### ISSUE THREAD

**Issue by frosso** [Automattic/woocommerce-payments#6995]
## Description

Update the appearance of the "WooPay > Checkout Appearance" section to the new preview

![Checkout privacy policy - Default](https://github.com/Automattic/woocommerce-payments/assets/110893979/4b956188-3570-4a31-90c1-91b15db0301c)

https://github.com/Automattic/woocommerce-payments/issues/6639#issuecomment-1674143256
Figma link: nngbiDUWyJa7fYcpiE9Jdu-fi-5649_4058

## Acceptance criteria
- See https://github.com/Automattic/woocommerce-payments/issues/6639#issuecomment-1674143256
- "Store logo on checkout" heading is renamed to "Checkout logo"
- "Store logo on checkout" help text is renamed to "Upload a custom logo. For best results, upload a horizontal image with white or transparent background. HEIC, WEBP, SVG, PNG, or JPG. Recommended width: 512 pixels minimum." (no need to enforce the 512 pixels)
- Update the WooPay checkout preview as displayed in the screenshot above

**Comment by pierorocca** [comment]
@frosso do you foresee this being picked up in the upcoming sprint? It fell off my radar during the last planning session.

**Comment by frosso** [comment]
@pierorocca  I didn't add it to the sprint's scope, but we _might_ be able to tackle it maybe during maintenance. Would you consider this a higher priority to maintenance?

**Comment by bborman22** [comment]
@pierorocca Just curious, do we have a design or asset for the new page preview visual? In the current implementation it's an SVG that allows us to drop our content on it dynamically and would likely be looking for the same sort of treatment.

**Comment by pierorocca** [comment]
@bborman22 should be able to grab the svg from the Sigma here https://github.com/Automattic/woocommerce-payments/issues/6639#issuecomment-1678403303

**Comment by bborman22** [comment]
Perfect, thanks I had missed the link on that comment!
