### ISSUE TITLE
Issue in Extending requests class during runtime 

### ISSUE THREAD

**Issue by manzurahammed** [Automattic/woocommerce-payments#7007]
### Describe the bug

I wanted to extend request during runtime following the [official guideline](https://github.com/Automattic/woocommerce-payments/blob/develop/includes/core/server/CONTRIBUTING.md#extending-requests-during-runtime).

I created a new class named `My_Namespace\Prefix_Create_And_Confirm_Intention` to extend the `Create_And_Confirm_Intention class`. My purpose was to include additional information in the request during the checkout process. To achieve this, I utilized a callback function bound to the `wcpay_create_and_confirm_intent_request` hook with a priority of 20, to run it after a [similar callback is run by WooPay](https://github.com/Automattic/woocommerce-payments/blob/develop/includes/woopay/services/class-checkout-service.php).

Sample code:
```
namespace My_Namespace;

use WCPay\Core\Server\Request\Create_And_Confirm_Intention;

class Prefix_Create_And_Confirm_Intention extends Create_And_Confirm_Intention {
  // some custom function
}
```

```
add_filter( 'wcpay_create_and_confirm_intent_request', [ __CLASS__, 'add_dynamic_statement_descriptor' ], 20, 2 );
...
public static function add_dynamic_statement_descriptor( Request $base_request, Payment_Information $payment_information ) {
		$request = Prefix_Create_And_Confirm_Intention::extend( $base_request );
		// some customization
		return $request;
}
```

However, when attempting to complete the checkout, an error emerged: 
```
"Failed to extend request. My_Namespace\Prefix_Create_And_Confirm_Intention is not a subclass of WCPay\Core\Server\Request\WooPay_Create_And_Confirm_Intention."
```

Afterwards, I tried adjusting the priority from 20 to 5 (to run it before WooPay), which led to a similar error: 
```
"Failed to extend request. `WCPay\Core\Server\Request\WooPay_Create_And_Confirm_Intention` is not a subclass of `My_Namespace\Prefix_Create_And_Confirm_Intention`."
```

Upon examining the codebase, I discovered the root cause: as the `wcpay_create_and_confirm_intent_request` is applied, if another callback extends the base request and send the new request down the chain, the next callback can not extend the base request anymore. Because the base request of the second filter is the one filtered by the first filter and no parent-child relationship exists between the two.

In this context, when I attempted to extend the base class with `Prefix_Create_And_Confirm_Intention`, it appears that the base class had already been altered and no longer corresponded to `Create_And_Confirm_Intention`.
 
Could you kindly review this situation and provide some guidance?

**Comment by zmaglica** [comment]
Hi there. I think we have a bug with the validating extended class. I am not entirely sure, since I will have to do some testing.

For a temporary workaround, could you try to extend `Prefix_Create_And_Confirm_Intention` class with `WooPay_Create_And_Confirm_Intention ` class and set the filter priority to execute after `WooPay_Create_And_Confirm_Intention` ?

**Comment by manzurahammed** [comment]
>Hi there. I think we have a bug with the validating extended class. I am not entirely sure, since I will have to do some testing.
For a temporary workaround, could you try to extend Prefix_Create_And_Confirm_Intention class with WooPay_Create_And_Confirm_Intention  class and set the filter priority to execute after WooPay_Create_And_Confirm_Intention ?


Thank you, @zmaglica, for your prompt response. However, after testing the method you suggested, we encountered another error.

```
namespace My_Namespace;

use WCPay\Core\Server\Request\WooPay_Create_And_Confirm_Intention;

class Prefix_Create_And_Confirm_Intention extends WooPay_Create_And_Confirm_Intention {
  // some custom function
}
```

```
WCPay\Core\Server\Request\WooPay_Create_And_Confirm_Intention can only be extended within its ->apply_filters() method.
```

**Comment by mehamasum** [comment]
@zmaglica, as a temporary workaround, is it worth disabling `self::$woopay_checkout_service->init();` ([ref](https://github.com/Automattic/woocommerce-payments/blob/29db59e57e6a964e10cfe6e2023fe49cdd9ee203/includes/class-wc-payments.php#L457-L458)) since the site doesn't use WooPay? (cc: @RadoslavGeorgiev)

Curious to know why this is not run by checking `should_enable_woopay` as it is done in `init_woopay`.

**Comment by zmaglica** [comment]
I have crafted PR that will resolve the issue. @mehamasum perhaps that will do the trick, but it will only solve the issue for this specific request class. The PR will be reviewed shortly, and we will merge it once it is ready. Meanwhile, can you create a filter and use `set_param` to make the changes you might need? By default, the protection mode is set to false, so you can use this function to set request param according to your need.

**Comment by naman03malhotra** [comment]
@zmaglica can you please share the PR link, even it is in draft mode that is fine.

**Comment by naman03malhotra** [comment]
Got it https://github.com/Automattic/woocommerce-payments/pull/7061

**Comment by htdat** [comment]
Fixed by https://github.com/Automattic/woocommerce-payments/pull/7099
