### ISSUE TITLE
Improve error message when amount is below minimum

### ISSUE THREAD

**Issue by dechov** [Automattic/woocommerce-payments#701]
If the payment amount is below the minimum [[Stripe doc](https://stripe.com/docs/currencies#minimum-and-maximum-charge-amounts)], this is the message we currently show:

<img width="686" src="https://user-images.githubusercontent.com/1867547/83460311-14a78900-a434-11ea-9b6c-f4115c923f3f.png">

…which is adequate but we _might_ want to revise it to something friendlier since it doesn't seem like a terribly exceptional case. The Stripe extension includes a function [[code](https://github.com/woocommerce/woocommerce-gateway-stripe/blob/19e5f4a47d4ad94d4d367a588b3cd4b227c9f80d/includes/abstracts/abstract-wc-stripe-payment-gateway.php#L235-L248)] for validating the amount, and throws an exception if it's not high enough, with this message:

<img width="647" src="https://user-images.githubusercontent.com/1867547/83460250-f2157000-a433-11ea-9291-648c4a62f2d2.png">

However, according to that [Stripe currency doc](https://stripe.com/docs/currencies#minimum-and-maximum-charge-amounts), the minimum depends on the _settlement_ (payout) currency, which isn't available before the payment is processed, at least not with the current implementation, so we should consider this before proceeding to mimic the approach there.

**Comment by dmvrtx** [comment]
I am closing related PRs because base branches have gone too far away and changes do not make a lot of sense anymore, partially due to ABP updates.
539-gh-Automattic/woocommerce-payments-server is a good point to start for anyone up to a challenge with this story.

**Comment by RadoslavGeorgiev** [comment]
Closing this issue, because it was fixed in https://github.com/Automattic/woocommerce-payments/pull/3319 both for UPE and standard Stripe Elements, as well as the classic checkout and the checkout block.
