### ISSUE TITLE
Download column not labeled in columns list under Payments > Documents

### ISSUE THREAD

**Issue by aheckler** [Automattic/woocommerce-payments#7014]
If you have a WooPayments site which receives VAT invoices, you can see under Payments > Documents that the column containing the download links does not have a header. This causes there to be an unlabelled column in the three dots menu.

![Screenshot taken on 2023-08-16 at 16 41 06 UTC@2x](https://github.com/Automattic/woocommerce-payments/assets/5512652/74370293-82db-42de-9800-29135547f677)

![Screenshot taken on 2023-08-16 at 16 41 25 UTC@2x](https://github.com/Automattic/woocommerce-payments/assets/5512652/08d2f47f-6b2c-4a12-bd4f-a956b5808f84)

**Comment by jessy-p** [comment]
This issue impacts Reporting so assigning to Fusion (based on team responsibilities Pc2DNy-3z-p2) @anu-rock. Assigning as part of Gamma Triage process PcreKM-yM-p2.

Tagging as part of re-evaluating older issues in the backlog, please have a look and close if no longer relevant.

**Comment by anu-rock** [comment]
@jessy-p Thanks for the ping. I've added it to Fusion's board. We'll prioritize it soon.

**Comment by anu-rock** [comment]
I'm not sure if we need a column heading in the table, but we definitely need a label in the three-dots menu 😄

**Comment by vbelolapotkov** [comment]
This one has nothing to do with currencies and localization. Changing labels to reporting.
