### ISSUE TITLE
Spike: Improve the UX of downloading CSV report larger than page size

### ISSUE THREAD

**Issue by Jinksi** [Automattic/woocommerce-payments#7017]
### Description

When a merchant clicks **Download** on a Transaction/Dispute/Deposits list, and there are more rows than are visible on the current page, the CSV is [generated via WCPay-server](https://github.com/Automattic/woocommerce-payments-server/blob/9df68311dfb4ce915526238aa4107abdb7eaa6b6/server/wp-content/rest-api-plugins/endpoints/wcpay/service/class-transaction-service.php#L560) and [emailed](https://github.com/Automattic/woocommerce-payments-server/blob/9df68311dfb4ce915526238aa4107abdb7eaa6b6/server/wp-content/rest-api-plugins/endpoints/wcpay/service/class-transaction-service.php#L614) to the merchant.

This is not a conventional UX and makes it inconvenient for the merchant to access the CSV.

We should improve this experience by either:
* Allowing the merchant to download immediately via their browser, as occurs for CSV exports of smaller datasets (< 100 rows). This may not be possible for large datasets.
* Providing this generated CSV as a file within wp-admin that can be downloaded once ready. This could be **Payments → Documents**.

![download-transactions](https://github.com/Automattic/woocommerce-payments/assets/3147296/2b0fa483-fa06-4976-8875-be18cdf290eb)

### Acceptance criteria

* Exported CSV files are available to download immediately or via WP-admin rather than delivered via email.

### Testing instructions

1. Ensure your store has 26+ transactions. Make additional purchases to increase this number.
2. Navigate to **Payments → Transactions**
3. Limit the rows per page to 25. This will ensure the CSV export will be generated via server.
4. You will be notified that the CSV will be emailed to you. Here we would like more immediate access to the CSV, as mentioned above.

### Dev notes

* Relevant PRs for the current implementation
	* #2939
	* 1178-gh-Automattic/woocommerce-payments-server

### Additional context

Slack discussion: p1692032263586399-slack-C7U3Y3VMY
ZD ticket: 6651946-zd-a8c

**Comment by vbelolapotkov** [comment]
> This could be a new screen (e.g. Payments → Files).

I think there is already a screen called "Documents"

**Comment by Jinksi** [comment]
Thanks @vbelolapotkov. I've updated the description to suggest this.

**Comment by shendy-a8c** [comment]
Part of our meetup workshop, we @Automattic/helix looked at this issue and decided:
- Improve the issue title to state the problem and not a possible solution to the problem.
- There are several possible solutions and the best one needs to be decided involving product and design team.
- As this is a 'core' feature touching not just dispute, deposit, and transaction, we feel @Automattic/gamma can take this on.

**Comment by anu-rock** [comment]
As reporting is now a focus area for @Automattic/fusion, we'll be prioritizing it soon.

**Comment by anu-rock** [comment]
I agree that delivering exported CSV reports solely via email can be sometimes inconvenient especially when a merchant doesn't have ready access to their inbox. This also increases the number of steps to view a CSV report. Lastly, it makes it hard to download older reports.

@mordeth Could you please work with @souravdebnath1986 to flesh out the requirements? In my opinion, we could take up this enhancement as part of the transaction reporting improvement project. We'll likely need to revise our estimation after that.

**Comment by mordeth** [comment]
While investigating the reason behind emailing the downloaded CSV when the results exceed the page limit, we discovered that the same method is employed for WooCommerce Analytics CSV exports. Regardless of the approach we choose, it's essential to maintain consistency between WooPayments and WooCommerce Analytics.

Given the current system's limitations, we discussed potential strategies with @souravdebnath1986  to enhance the CSV download. One notable limitation is that emails are consistently sent to the store owner, posing challenges for other users attempting to export.

After deliberation, we decided against displaying a loading bar and waiting for server-side processing during the download. The concern is that the processing time for substantial reports with tens of thousands of records is uncertain, making this approach less practical.

Initially, we determined that the most suitable option was to add a new tab under the Documents page within the Payments section to showcase all generated CSV exports. However, if we aim to encompass both WooPayments and WooCommerce Analytics, this page would not fulfill its intended purpose. In that case, we would need to create a new page under the WooCommerce section.

Before we settle on the best approach, we'd like to hear from everyone on the best option to enhance the CSV exports and possible limitations.

cc. @beaulebens @vbelolapotkov @anu-rock @elizaan36 @naman03malhotra

**Comment by htdat** [comment]
> Regardless of the approach we choose, it's essential to maintain consistency between WooPayments and WooCommerce Analytics.

Just my 2 cents here. I don't think we must stick ourselves to this kind of principle. They can look the same, but they're essentially different under the hood. WooPayments fetches data from the server API while WooCommerce Analytics has data in house (i.e. merchant site) without any external request.

**Comment by beaulebens** [comment]
What I was suggesting was that rather than thinking about this as a purely WCPay problem/gap, think about it as a "WooCommerce" issue. There are other parts of Woo that generate reports, and allow them to be downloaded. Is there a more holistic approach we should take that can solve all needs, or at least approach them similarly? As a couple of quick example thoughts;
- if we generate reports and allow them to be downloaded, does it make sense to always store them in the same place (with the same retention policies) and offer them for download from the same screens/in the same ways?
- if users want to be able to email them to somewhere other than the admin email, then should we always provide a similar interface to let them enter a different address when generating them?

I don't actually know the answer to these, I just want to make sure they're being considered, before a WCPay-only solution is created, and that makes for a more fragmented overall experience.

The backend/place/way the data is generated may need to be completely different in different cases, and that's fine. But if the mental model of the user is "I just want to generate a report from x or y different place, and get it in my email" then the overall experience probably makes sense to be pretty similar.

**Comment by haszari** [comment]
> As reporting is now a focus area for Fusion, we'll be prioritizing it soon.

Removing `Deposits` and `Disputes` label for now, as Fusion are looking at improving this for transactions report (higher priority than deposits and disputes). 

@Automattic/fusion / @anu-rock When ya'll start work on this, please keep @Automattic/helix informed. We can add follow up issues if needed to make deposits and disputes consistent. As a first step, request a review from Helix on any PRs related to this issue. Thanks! 🙌

**Comment by elizaan36** [comment]
I agree this solution would be a big improvement to the Woo experience overall, not just payments. There's been design exploration on this in the past year related to payments that would be useful to share, is there a P2 related to this issue?

Also, considering the complexity of the flows it feels like potentially larger scope UX issue and want to make sure the design phase is incorporated into the timeline.

**Comment by mordeth** [comment]
I am closing this spike in favor of engaging in a P2 discussion to ascertain the optimal solution.

**Comment by mordeth** [comment]
I am closing this spike in favor of engaging in a P2 discussion to ascertain the optimal solution.

**Comment by brucealdridge** [comment]
@mordeth was a discussion on this started? I'm going to reopen this to make sure it doesn't get lost

**Comment by anu-rock** [comment]
@brucealdridge We continued to discuss this at paJDYF-bxH-p2. A good deal of design exploration also happened. I think it's a great enhancement to see through, so thanks for re-opening this :)

**Comment by haszari** [comment]
Closing. There are some good ideas for a potential enhancement here, but no actionable bug. We would need to prioritise this as a roadmap project to improve or change how we generate and make available large CSVs.
