### ISSUE TITLE
Avoid returning Stripe error message when capturing more than order amount

### ISSUE THREAD

**Issue by aheckler** [Automattic/woocommerce-payments#7029]
If I try to capture an order after editing it to total to more than the original authorized amount, I get an error in the order notes that tells me to contact Stripe. This is not ideal.

![Screenshot taken on 2023-08-18 at 08 02 48 UTC@2x](https://github.com/Automattic/woocommerce-payments/assets/5512652/6f87fd67-9afa-462b-a7fa-1a693c0b2339)

To reproduce:

1. WooPayments test site with an example product.
2. Under Payments > Settings, enable the authorize and capture later setting.
3. On the frontend, place an order for the example product.
4. Under WooCommerce > Orders, edit the order to add a fee, or any other way of making the order total more than it was originally.
5. Using order actions box, try to capture the order.
6. You'll get the above error telling you to contact Stripe.

This shouldn't happen. Merchants should always be directed to our support channels, but IMHO contacting support isn't really needed here. Simply displaying the error is enough:

> Error: The payment could not be captured because the requested capture amount is greater than the amount you can capture for this charge.

**Comment by kalessil** [comment]
Fells under @Automattic/pulsar responsibility areas, adding to our Sprints backlog.
