### ISSUE TITLE
[Woo Express] WooPayments action incentive should also be displayed in Woo Express "Get paid with WooPayments" task

### ISSUE THREAD

**Issue by brandonwanA8C** [Automattic/woocommerce-payments#7036]
### Describe the bug
During Woo Express demo, WCPayments incentives (10% discount for new sign-ups) are not showing in Woo Express UI. 
see 31'50" beyond: https://fathom.video/share/faXSSxp7MHHavqkPeAxmUKMT64zmJsk2

@daquinons extra context: The issue is about displaying the WooPayments incentive also in the Woo Express task, as shown in design https://github.com/Automattic/woocommerce-payments/issues/7036#issuecomment-1688458296.

### To Reproduce
see 31'50" beyond: https://fathom.video/share/faXSSxp7MHHavqkPeAxmUKMT64zmJsk2

### Expected behavior
WCPayments incentive offerings should be available across any Woo-supported onboarding channels and UX

### Additional context
Design: https://github.com/Automattic/woocommerce-payments/issues/7036#issuecomment-1688458296

**Comment by warrendholmes** [comment]
@verofasulo Do you have the design ready? Sorry I can't find it now 😅

**Comment by daquinons** [comment]
<img width="107" alt="Screenshot 2023-08-22 at 10 05 45" src="https://github.com/Automattic/woocommerce-payments/assets/2612426/967df98a-f791-4d5f-bcb3-7cc7812d48a1">

Hello there! I can see the Payments tab in 32:08, is that what you were missing?

**Comment by verofasulo** [comment]
> Do you have the design ready? Sorry I can't find it now

@warrendholmes, are you referring to the WooPayments task in the task list? 

![image](https://github.com/Automattic/woocommerce-payments/assets/98944206/e11174ff-cc68-4a4e-81a1-88ba6fc80e9e)

![image](https://github.com/Automattic/woocommerce-payments/assets/98944206/ab420d74-2fc0-4f4a-81a5-225c381d26f9)

[Figma](https://www.figma.com/file/Y5pUYSJPsGEud1vknUZhi8/Core-onboarding---Profiler?type=design&node-id=2738-40528&mode=design&t=eHLTx3oBBi1N73Jy-4) | [Airtable](https://airtable.com/appwjbwlTdyPwuZJY/tbl12okQedrWfwbXw/viwMHqEl7hz7MxJ8Y/recDNHJcuxGdAqsIG?blocks=hide)

**Comment by warrendholmes** [comment]
@verofasulo Yes, that's the one FYI @daquinons and @brandonwanA8C

**Comment by daquinons** [comment]
@warrendholmes Aha! Ok, so the issue is about making the incentive appear also in the Woo Express task, is that correct?

From the first read, I thought that it was about the current existing incentive not showing as it should :) Which is true at the beginning, because of the async request that we make to the incentives endpoint (as you can see, the badge shows up later).

**Comment by warrendholmes** [comment]
> @warrendholmes Aha! Ok, so the issue is about making the incentive appear also in the Woo Express task, is that correct?

Yep! Let me know if you need any more info. Essentially we need your team to implement @verofasulo's design.

**Comment by ismaeldcom** [comment]
Hey @warrendholmes! I just pushed https://github.com/Automattic/woocommerce-payments-server/pull/3890 and https://github.com/woocommerce/woocommerce/pull/40034 to implement the requested changes in WC. I still need to write the bridge part for Woo Express. But I need to ask a couple of things first 🙂 

- This enhancement requires a new release of WC to work, and as WC 8.1 code freeze was a while ago, we will need to wait for 8.2 release on 20 Oct. Does it work for you or do you want to ask for a code freeze exception?
- It isn't mentioned on the Figma notes, but I've noticed that the task title is still `Set up WooPayments` in Woo Express, do you want me to update it to match the design? Renaming it to `Get paid with WooPayments`.

**Comment by brandonwanA8C** [comment]
per discussion with @warrendholmes, we will keep the copies consistent, hence using "`Set up WooPayments`" in the task list (FYI @verofasulo).

@warrendholmes will confirm the timeline required: to make a Core release exception or not.

**Comment by warrendholmes** [comment]
@wcstaley Are we able to release this earlier on Woo Express in one of the weekly releases?

**Comment by wcstaley** [comment]
@warrendholmes If you are referring to [this PR](https://github.com/woocommerce/woocommerce/pull/40034), then yes.

**Comment by ismaeldcom** [comment]
Hey @wcstaley! The WC PR (https://github.com/woocommerce/woocommerce/pull/40034), WooPayments (https://github.com/Automattic/woocommerce-payments/pull/7132) and bridge one (https://github.com/Automattic/wc-calypso-bridge/pull/1294) are now merged. Do we need to request a WC code freeze exception, or we have another way for Woo Express releases?
