### ISSUE TITLE
Visual Issue when Disabling UPE in Firefox

### ISSUE THREAD

**Issue by dmallory42** [Automattic/woocommerce-payments#7039]
### Describe the bug

When using Firefox, I noticed a visual bug where spacing wasn't getting applied properly when trying to disable UPE.

<img width="605" alt="Screenshot 2023-08-22 at 10 53 03" src="https://github.com/Automattic/woocommerce-payments-server/assets/11770181/8d7d4658-1e32-4423-ae7c-3c60dbaa81d9">

### To Reproduce

1. Use Firefox
2. Go to `Payments > Settings`
3. Click the `...` next to `Payment Methods` then click `Disable`
4. Verify the spacing doesn't display correctly.

**Comment by frosso** [comment]
This will be gradually fixed by https://github.com/Automattic/woocommerce-payments/issues/5019 as we convert more and more merchants to the dUPE and clean up the codebase

**Comment by frosso** [comment]
Merchants will no longer disable the new payment experience manually - closing for now.
