### ISSUE TITLE
Fix Edge Case around PO onboarding being continued later

### ISSUE THREAD

**Issue by dmallory42** [Automattic/woocommerce-payments#7065]
### Describe the bug

#7009 added a new task to prevent users from getting stuck if they exit the Stripe onboarding at a very early stage.

There's an edge case when a PO user leaves the onboarding at a very early stage (before entering a phone number) where the task takes them to the full onboarding (rather than the PO onboarding).

This issue covers a fix for this so that they are directed back to the PO onboarding.

### To Reproduce

1. Complete the Woo onboarding to onboard a PO account.
2. When redirected to Stripe, immediately click `Back`.
3. Click on the `Complete set up` task.
4. You will be redirected to the Stripe KYC, but it will be the full KYC (not PO).

**Comment by oaratovskyi** [comment]
I was testing Ismael's PR and reproduced the issue, here's how Stripe KYC looks like:
![image](https://github.com/Automattic/woocommerce-payments/assets/79862886/42ebae66-19b7-4c82-ad41-1f6f1e189060)
Should be PO, but it's full
