### ISSUE TITLE
Unable to change color of text on payment portal

### ISSUE THREAD

**Issue by eoinsav** [Automattic/woocommerce-payments#7071]
We have a site with a dark blue background, which makes the grey text hard to read (card number, expiration, cvc). The payment window is added through an iFrame so we can't change the color of that specific text to make it more readable.

It would be great if we had more control over the color of that text or if it could autodetect when there is darker text on a dark background.

<img width="667" alt="262442125-33147f0a-4665-40cf-af30-3d9cbab9de36" src="https://github.com/Automattic/woocommerce-payments/assets/35590156/e1beaf24-730d-4918-9c27-4feab83fd19b">

**Comment by csmcneill** [comment]
Howdy @eoinsav!

This is already covered a bit in #3604

Given that this is a duplicate issue, I will close it. I recommend that you subscribe to #3604 for updates :)
