### ISSUE TITLE
`isInquiry()` utility func `client/disputes/utils.ts` takes `Dispute` param but only needs string `dispute.status`

### ISSUE THREAD

**Issue by shendy-a8c** [Automattic/woocommerce-payments#7085]
Make [isInquiry()](https://github.com/Automattic/woocommerce-payments/blob/e9baed092efb354e0280a9a34fc4dc0e7566cd07/client/disputes/utils.ts#L61-L64) accept dispute status instead of dispute object to be consistent with other similar helper functions.

https://github.com/Automattic/woocommerce-payments/blob/e9baed092efb354e0280a9a34fc4dc0e7566cd07/client/disputes/utils.ts#L61-L64

Context: https://github.com/Automattic/woocommerce-payments/pull/7043#discussion_r1308134383

@Jinksi says: 

> IMO we should change isInquiry to accept DisputeStatus to be consistent with the other util functions since the function doesn't need any other dispute details.

**Comment by haszari** [comment]
A nice little code fix. Functions should only have params they need/use 🚀
