### ISSUE TITLE
"Set up WooPayments" task should only be marked as completed after onboarding is completed

### ISSUE THREAD

**Issue by daquinons** [Automattic/woocommerce-payments#7119]
### Describe the bug
We rely on [`is_connected()`](https://github.com/woocommerce/woocommerce/blob/f493e921d5730543344485af8edfeb9749b4d9f3/plugins/woocommerce/src/Admin/Features/OnboardingTasks/Tasks/WooCommercePayments.php#L96) for marking the task as completed. We should rely on `details_submitted` in addition to `is_connected`, similar to what is done [here](https://github.com/Automattic/woocommerce-payments/blob/f9d55c6b9ccafc74f3dd39d8033771b3370c8a6e/includes/class-wc-payments-account.php#L208) to see if an account is half way onboarded.

Right now, if onboarding is begun and abandoned, because the account is created the task is marked as complete even if the user can't process payments yet.

Example here p1693415438856559/1693411091.881309-slack-C03KTTK2YMA

![image](https://github.com/Automattic/woocommerce-payments/assets/2612426/9695861e-defe-4177-aac3-b14d9b821afd)

**Comment by ismaeldcom** [comment]
I wonder whether we should rely on [`needs_setup`](https://github.com/woocommerce/woocommerce/blob/a0f427364b539e7e449d3d54fb3886c033b62bef/plugins/woocommerce-admin/docs/features/payment-gateway-suggestions.md?plain=1#L54) instead. It's designed for payment gateway suggestions configuration. It might need to use a new condition in `get_connection_url` to redirect to the appropriate step based on the account status (EG finish onboarding, or provide new due details). But sounds like the more consistent approach here.

**Slack thread**: p1696575007152069-slack-C03KTTK2YMA

**Comment by ismaeldcom** [comment]
Will be available with WooCommerce 8.3.0 release.
