### ISSUE TITLE
Old WCPay Subscription renewals marked as failed during Woo Subscriptions scheduled payment flow

### ISSUE THREAD

**Issue by james-allan** [Automattic/woocommerce-payments#7123]
### Describe the bug

When a store has WCPay Subscriptions and has installed Woo Subscriptions (plugin), the scheduled action for WCPay Subscription payments still runs, however it should exit payment attempts because of this logic [here](https://github.com/Automattic/woocommerce-payments/blob/issue/6508/includes/compat/subscriptions/trait-wc-payment-gateway-wcpay-subscriptions.php#L320). 

However, above that check is another check that looks if the renewal has a token saved. A renewal order usually does have the token stored so this _"shouldn't"_ cause issues, however it can.

If the renewal order doesn't have the token stored, it marks the last renewal order<sup>*</sup> as failed. 

<sup>* in this case, because the subscription is a WCPay subscription the last order happens to be last months renewal order</sup>  

### To Reproduce

1. Purchase a subscription using Stripe Billing.
2. Process a renewal order using the billing clock 
3. Install the WooCommerce Subscriptions plugin. 
4. Go in and delete the token meta from the renewal order. (idk why this site has the token missing). 
5. Run the scheduled subscription payment action.
6. Note the last renewal order is set to "failed". 

### Actual behavior

The last WCPay subscription renewal order is marked as failed. 

### Expected behavior

The scheduled action payment flow should be skipped altogether for WCPay/Stripe Billing subscriptions. 

### Additional context

Discussion in Slack: p1693475520832749-slack-C055WHLA98D
Ticket: 6677730-zd-a8c

**Comment by htdat** [comment]
@james-allan and @mattallan @Automattic/helix - should this issue be closed as it has already had fix, i.e. PR https://github.com/Automattic/woocommerce-payments/pull/7125?

**Comment by shendy-a8c** [comment]
Linked this issue with https://github.com/Automattic/woocommerce-payments/pull/7125 and closing this issue as the PR has been merged.
