### ISSUE TITLE
Transaction details → use store currency as headline transaction amount

### ISSUE THREAD

**Issue by Jinksi** [Automattic/woocommerce-payments#7124]
Part of #6883

On the **Transaction → Details** screen, we want to change the headline transaction amount to display in the merchant's default/primary currency, leaving the transaction currency as a detail within the breakdown.

This applies to stores that have
1. enabled multi-currency
1. a single deposit currency

![transaction headline currency](https://github.com/Automattic/woocommerce-payments/assets/3147296/ae876776-71ff-4148-9977-f0eeb4ff3f4e)

Relevant discussion about closing this issue here: p1695933636976819-slack-C02BW3Z8SHK

**PRs**
- [ ] #7159 
- [x] #7287

**Comment by Jinksi** [comment]
Reopening until #7159 is merged.

**Comment by haszari** [comment]
Closing – we're backing away from making this change as it could potentially be more confusing for merchants.

Key points from discussion in PR and offline: 

- Headline currency is in the store currency but the sub-line (below the headline) has one part in buyer/transaction currency and the rest in store currency. _This could be confusing for the merchant._
- Looking at 2 close competitors - Shopify and Stripe - I don't see a similar representation of the payment amount called out in the store currency. It's always called out in the buyer/transaction currency and additional context is provided on the rate used to convert to the store currency and the amount in store currency.

Thanks @souravdebnath1986 @brucealdridge @csmcneill for working through this!

**Comment by haszari** [comment]
Note discussions are ongoing. @souravdebnath1986 @nikkivias if we decide to revisit this, please open a new issue.

**Comment by Jinksi** [comment]
Thanks for the update! I was 🤏 this close to merging.

**Comment by Jinksi** [comment]
@haszari should we revert #7287 which shows the dispute amount in the store currency rather than buyer/transaction currency?

**Comment by haszari** [comment]
> should we revert https://github.com/Automattic/woocommerce-payments/pull/7287 which shows the dispute amount in the store currency rather than buyer/transaction currency?

Not sure, @Jinksi can you investigate (check in with slack threads etc) and make a call?

**Comment by Jinksi** [comment]
Relevant slack discussion here: p1695933636976819-slack-C02BW3Z8SHK

**Comment by haszari** [comment]
@Jinksi what's the outcome of that discussion? Do we need to link to slack on this issue?

**Comment by Jinksi** [comment]
I posted the link here once I found it so I didn't have to look for it again.

No outcome yet – I've proposed keeping the current behaviour of showing the disputed amount in the merchant's currency. Alternatively, I've proposed showing in both currencies: e.g. `¥10,000 → kr725.81 NOK`.

**Comment by Jinksi** [comment]
The outcome is: We should revert #7287 and show the "dispute amount" in the shopper/transaction currency.

I've created issue #7373 to resolve this.
