### ISSUE TITLE
More welcoming new merchant experience

### ISSUE THREAD

**Issue by dechov** [Automattic/woocommerce-payments#715]
After a merchant completes onboarding, the dashboard UI is a little cold: a smattering of zeroes, with featured text "No data to display". Here's the top-level "Payments" view:

![Initial Payments screen after connection](https://user-images.githubusercontent.com/1867547/84195934-63c16f80-aa6d-11ea-9878-0f1f28a6fa8e.png)

(Regression from Deposits list PR https://github.com/Automattic/woocommerce-payments/commit/66be994f68117b55188f6bffe09aee7edf11140f#diff-895656aeaccff5d7c0f56a113ede9662L22)

We might want to customize the initial views with some useful and/or encouraging information, along the lines of "After your first payments come in, deposits to your •••• [account] will be listed here" and possibly linking to more introductory [documentation](https://docs.woocommerce.com/document/payments/)? We can also take the opportunity for some general orientation, spelling out that this is the place for _WooCommerce Payments_, and not other WooCommerce payments. cc @LevinMedia

As for the "No data to display" text, this was an improvement at the time (https://github.com/woocommerce/woocommerce-admin/pull/2801), but we could further enhance the Table component to accept a custom message, such as "Your transactions will show up here" – see https://github.com/woocommerce/woocommerce-admin/commit/11324c0e87197db9eec539b7c6aa205dd0dc2c9e [needs PR] and see also https://github.com/Automattic/woocommerce-payments/issues/97#issuecomment-527180802.

**Comment by LevinMedia** [comment]
The new merchant experience has evolved significantly since this issue was created, so I'm closing it.
