### ISSUE TITLE
Multi-Currency onboarding is broken

### ISSUE THREAD

**Issue by jessepearson** [Automattic/woocommerce-payments#7151]
### Describe the bug
There is a note that a merchant receives in the dashboard directing them to onboard Multi-Currency, but the onboarding wizard currently does not work. When accessing the wizard you get two errors and cannot use the wizard:

* Error retrieving currencies.
* Error retrieving store settings.

### To Reproduce

1. Go to Payments > Settings > Advanced and confirm Multi-Currency is disabled.
2. Go to `yourstoreurl/wp-admin/admin.php?page=wc-admin&path=%2Fpayments%2Fmulti-currency-setup`
3. Receive errors.

### Additional context
This was found by Taha in https://github.com/Automattic/woocommerce-payments/pull/7141

**Comment by jessepearson** [comment]
As far as I can tell, this doesn't work due to if Multi-Currency is disabled, then the files for MC, including the RestController, are not included. Due to this the `currencies` and `get-settings` endpoints fail. Below is the response for both:

```
{
    "code": "rest_no_route",
    "message": "No route was found matching the URL and request method.",
    "data": {
        "status": 404
    }
}
```

This likely hasn't come up before due to Multi-Currency is enabled by default and would need to be manually disabled in order for this to happen.

It's possible we could fix this by checking if the onboarding wizard is being viewed and we could load the MC files at that point.

**Comment by zmaglica** [comment]
This issue impacts Multi-Currency, so assigning to Sigma (based on team responsibilities Pc2DNy-3z-p2) @dwainm . Assigning as part of Gamma Triage process PcreKM-yM-p2.
