### ISSUE TITLE
Onboarding LPM's which require additional currencies while MC is disabled

### ISSUE THREAD

**Issue by tpaksu** [Automattic/woocommerce-payments#7154]
When someone is enabling a LPM that requires another currency that isn't the store currency, we should do one of two things:

* Enable MC by default and state it in that message.
* Inform them that they need to enable MC manually so that the additional currency can be added. 

If we don't do either one of these then they will not be able to take payments with the LPM.

_Originally posted by @jessepearson in https://github.com/Automattic/woocommerce-payments/issues/7141#issuecomment-1710261667_

#### Reproduce with:

- Set your store currency to USD on WooCommerce > Settings
- Disable MC from Payments > Settings > Advanced.
- Navigate to: http://localhost:8082/wp-admin/admin.php?page=wc-admin&path=%2Fpayments%2Fadditional-payment-methods
- Enable iDeal, or any payment method that operates with EUR
- MC should be activated, EUR should get enabled, and EUR is missing warning needs to be shown, but none of these happen.

#### Acceptance criteria

- You should see the "will enable EUR on your store" warning, but it doesn't display
- You should have MC enabled back
- You should have EUR enabled as a payment currency

**Comment by zmaglica** [comment]
This issue impacts Multi-Currency, so assigning to Sigma (based on team responsibilities Pc2DNy-3z-p2) @dwainm . Assigning as part of Gamma Triage process PcreKM-yM-p2.

**Comment by tpaksu** [comment]
There's an ongoing discussion on the PR itself, so the UI will change a bit. The notice won't appear, instead the checkboxes will be grayed out and there will be a tooltip on each, indicating the LPM is in need of a currency being active to operate. You can find the details on the PR itself.
