### ISSUE TITLE
Transaction Details > Dispute Details: issuer evidence UI (Review the claim & View dispute details)

### ISSUE THREAD

**Issue by Jinksi** [Automattic/woocommerce-payments#7156]
Part of #6883

This issue handles the features of Transaction Details → Dispute Details that require linking to a [dispute's `issuer_evidence`](https://stripe.com/docs/api/disputes/object#dispute_object-issuer_evidence) if it exists:

1. The **Steps to resolve** → **Review the claim** row should be rendered with a link that opens the issuer evidence PDF in a new window.

<img width="600" alt="257356531-731dc70a-36f5-43ac-9e84-fb8078649733" src="https://github.com/Automattic/woocommerce-payments/assets/3147296/d26d4572-40ea-4119-a0b1-8f5e9806f4c3">

2. The **View dispute/inquiry details** button should be rendered. When clicked, it will open the issuer evidence PDF in a new window – only for `lost` disputes that were:
	* **Accepted** (`disputes.metadata.__closed_by_merchant`)
	* **Lost due to non-response** (no `dispute.metadata.__evidence_submitted_at`)
	* **Inquiry: Closed** (`dispute.status === 'warning_closed'`)

<img width="600" alt="view-dispute-details" src="https://github.com/Automattic/woocommerce-payments/assets/3147296/ef84f869-1fb1-4d46-9a8b-0a6d783b41a1">

#### Note on testing `issuer_evidence`

**Update**: testing [`issuer_evidence` (PDF of issuer claim](https://stripe.com/docs/api/disputes/object#dispute_object-issuer_evidence)) is not possible with test mode transactions. `dispute.issuer_evidence` will return `null` unless the dispute occurs on a live account with a real disputed transaction.

See discussion on Slack: p1693792635213789-slack-C03LA109BKM.

**Comment by Jinksi** [comment]
I've added an `Issuer_Evidence` TS interface to `client/types/disputes.d.ts` in PR https://github.com/Automattic/woocommerce-payments/pull/7047/files#diff-3281997a33f70ad0c3013fdb32857f43264b59ddf3b76dd1f3aef2d0b8b435edR35 – if it is useful when working on this issue.

**Comment by brucealdridge** [comment]
This issue is on hold and may or may not be picked up later. A different iteration of this issue is being worked on in #7173.

**Comment by haszari** [comment]
This is a task from a previous project, which we didn't pursue (design iteration & testing challenges). 

We have a future project to improve the UI for accessing & viewing dispute issuer evidence. Closing this issue, as we are not planning to handle as maintenance. If there is relevant info in this issue then we can review when we start work on the project.
