### ISSUE TITLE
WooPay empty cart page when adding a bundle with express checkout button on product page

### ISSUE THREAD

**Issue by alefesouza** [Automattic/woocommerce-payments#7157]
### Describe the bug

When we click the WooPay express checkout button on product page, we are redirected to WooPay with a "Your cart is currently empty!" message.

### To Reproduce

1. Install Product Bundles
2. Create a bundle
3. Access bundle page
4. Click WooPay checkout page
5. You'll be redirected but the cart will be empty

### Screenshots

![Screenshot 2023-09-07 at 11 40 15 PM](https://github.com/Automattic/woocommerce-payments/assets/1693223/ab28ada7-5675-4237-ba88-beec2b8915f2)

**Comment by hsingyuc** [comment]
@alefesouza I can't reproduce this issue.  I got redirected to the WooPay checkout page with the correct cart items.  

<img width="917" alt="Screen Shot 2023-09-11 at 6 43 59 PM" src="https://github.com/Automattic/woocommerce-payments/assets/56378160/3a5b4daa-d3fa-4014-8491-f4b2e2bf0ce9">

**My product bundle**
<img width="690" alt="Screen Shot 2023-09-11 at 6 45 24 PM" src="https://github.com/Automattic/woocommerce-payments/assets/56378160/8111eeef-5f46-4446-b8aa-46f40f6272f1">
