### ISSUE TITLE
Unify the add payment method tasks

### ISSUE THREAD

**Issue by dmallory42** [Automattic/woocommerce-payments#7166]
### Description

There was a discussion in #7129 around unifying the "Add new APMs" and "enable more payment gateways" tasks as both relate to adding additional payment methods from a merchant POV.

Relevant comment from @elizaan36:

> 
> I think we'll need to combine them because hiding the "Set up additional..." task would conflict with some of our contractual commitments that state certain payment gateways/methods "need to be part of onboarding".
> 
> I know this has been discussed (somewhere :D ) before, but from the core perspective we can add a section to enable the WooPayments APMs to the "Set up additional..." task. I had a look and I have two possible directions for this. Both options would direct the merchant through the vertical stepper guided flow to set up APMs, then when setup is complete they would be directed back either to Woo Home or Payments overview.
> 
> Option 1 - New section in "Set up additional..." task

![Payments _ WooCommerce Payments-1](https://github.com/Automattic/woocommerce-payments/assets/5121465/369189c2-9342-45e9-83a2-fc5810d811e8)
 
> Option 2 - One-time directed flow from "Set up additional..." task. Announcement would dismiss once setup is complete.

![Payments _ WooCommerce Payments](https://github.com/Automattic/woocommerce-payments/assets/5121465/b15698f5-99f8-4f03-87f3-ce01b73409fc)
 
> Let me know your thoughts on these options. This needs more work from a design perspective, so I'll likely share with Rik next week and he can hit the ground running on this.

Opening this issue because we shipped a partial fix in #7129 but we will also need to address rebuilding these tasks in a unified way.

### Acceptance criteria

* First requirement
* Second requirement
* Third requirement
* etc.

### Testing instructions

1. Go to '…'
2. Click on '…'
3. Scroll down to '…'
4. Observe expected behaviour

**Comment by elizaan36** [comment]
cc @rikmantel 👋

**Comment by elizaan36** [comment]
Hi all, Wanted to comment on here that this issue won't be relevant anymore with the recent changes. Since the set up payments task leads directly to the payments connect page, there's no need to iterate on that screen. cc @vladolaru

**Comment by dmallory42** [comment]
Makes sense, thanks for letting us know! Closing this issue.
