### ISSUE TITLE
Deprecated string interpolation ${var} with {$var} in /woocommerce-payments/includes/multi-currency/Analytics.php

### ISSUE THREAD

**Issue by ridonibishi** [Automattic/woocommerce-payments#7169]
### Describe the bug
When using the WooCommerce Payments plugin, we've encountered a deprecation issue related to string interpolation.

### To Reproduce
1. Install and activate the WooCommerce Payments plugin.
2. Visit WordPress Dashboard

### Actual behavior
Upon inspecting the server logs, we observe the following deprecation warnings:

Deprecated: Using ${var} in strings is deprecated, use {$var} instead in /plugins/woocommerce-payments/includes/multi-currency/Analytics.php on line 330
Deprecated: Using ${var} in strings is deprecated, use {$var} instead in /plugins/woocommerce-payments/includes/multi-currency/Analytics.php on line 331
Deprecated: Using ${var} in strings is deprecated, use {$var} instead in /plugins/woocommerce-payments/includes/multi-currency/Analytics.php on line 332

### Desktop (please complete the following information):

* OS: macOS 13.3 (22E252)
* Browser: chrome
* Version: 116.0.5845.140

### Smartphone (deemed not neccessary):

* Device: [e.g. iPhone6]
* OS: [e.g. iOS8.1]
* Browser [e.g. stock browser, safari]
* Version [e.g. 22]

### Additional context
* PHP Version: 8.2 - as of this version using ${var} in strings is deprecated
* Woocommerce Version: 8.0.3
* Woocommerce Payments Version: 6.4.1

**Comment by zmaglica** [comment]
This issue impacts Multi-Currency, so assigning to Sigma (based on team responsibilities Pc2DNy-3z-p2) @dwainm . Assigning as part of Gamma Triage process PcreKM-yM-p2.
