### ISSUE TITLE
Update version of @wordpress/components

### ISSUE THREAD

**Issue by dechov** [Automattic/woocommerce-payments#717]
In https://github.com/Automattic/woocommerce-payments/pull/571, a severe styling regression from a WP update was dealt with by pinning our version of `@wordpress/components` to what WooCommerce Admin was using at the time (8.5.0). Now the latter version has been updated as well (see https://github.com/woocommerce/woocommerce-admin/pull/4427).

We should follow suit and update our version (or possibly consider using the external dependency again, despite being demonstrably riskier), which should no longer cause the issue solved in https://github.com/Automattic/woocommerce-payments/pull/571, though we'll need to consider newer WCPay releases' compatibility with older WooCommerce Admin versions.

(See also https://github.com/woocommerce/woocommerce-admin/issues/4538.)

**Comment by dechov** [comment]
The dependency version in `woocommerce-admin` was now most recently bumped in https://github.com/woocommerce/woocommerce-admin/pull/5293, causing some styling regressions (https://github.com/woocommerce/woocommerce-admin/issues/5345) currently being addressed.

**Comment by dechov** [comment]
The bundling of `@wordpress/components` in WC Admin was removed altogether in https://github.com/woocommerce/woocommerce-admin/pull/5753.

**Comment by LevinMedia** [comment]
@dechov @vbelolapotkov While working on https://github.com/Automattic/woocommerce-payments/pull/1378 I noted that the outdated version of @wordpress/components as well as the base components are preventing us from being able to use the correct `isSecondary` button type in the disputes section. 

I believe @jessepearson may have also encountered this issue while he was working on styling for instant deposits. We should consider re-prioritizing this issue ASAP.

**Comment by waclawjacek** [comment]
> While working on #1378 I noted that the outdated version of @wordpress/components as well as the base components are preventing us from being able to use the correct `isSecondary` [button styles](https://wordpress.github.io/gutenberg/?path=/docs/components-button--secondary#secondary) in the disputes section.

I have just encountered this as well while working on #1501.

**Comment by vbelolapotkov** [comment]
There is a [draft PR](https://github.com/Automattic/woocommerce-payments/pull/1536) created but some UI is failing atm due to various deprecations in components props.

**Comment by waclawjacek** [comment]
@vbelolapotkov Thank you! In the meantime, what is the best course of action to get the current component styles without updating the version numbers? Should I wait for the PR to be merged or backport the button styles?

**Comment by vbelolapotkov** [comment]
@waclawjacek it depends on the timeline and importance for your PR/feature. If you want it to go live with next release (2.3.0), it's better to copy components/styles you need and create a follow up issue to address once the components package is updated. If it can wait and can be blocked until package is updated, you can build on top of #1536 (I plan to update it soon to make more usable).
