### ISSUE TITLE
Missing borders for icon in additional payment methods screen

### ISSUE THREAD

**Issue by KarlisJ** [Automattic/woocommerce-payments#7182]
### Describe the bug

When enabling additional payment method we don't apply border for icons which stands out as uneven allignment.

Once any PM is enabled the list in the `payments->settings` have proper border and looks much better. 

### To Reproduce

1. Make sure you disable additional payment methods in `payments->enable`
2. Under "Payments accepted on checkout" click "enable in store"
3. Observe the list of icons

### Screenshots
![image](https://github.com/Automattic/woocommerce-payments/assets/24650518/eabbc761-d914-42e2-836b-b4b95392d703)
### Expected behavior
We should apply the border, ideally, it should be a global CSS rule (the Icon component has prop for border and applies the class but for this screen we don't target it)

### Desktop (please complete the following information):

* OS: [e.g. iOS]
* Browser [e.g. chrome, safari]
* Version [e.g. 22]

### Smartphone (please complete the following information):

* Device: [e.g. iPhone6]
* OS: [e.g. iOS8.1]
* Browser [e.g. stock browser, safari]
* Version [e.g. 22]

**Comment by kalessil** [comment]
@KarlisJ : is it still relevant?

**Comment by KarlisJ** [comment]
@kalessil Nop, closing
