### ISSUE TITLE
Error in checkout with Afterpay payment method due to missing shipping information

### ISSUE THREAD

**Issue by mgascam** [Automattic/woocommerce-payments#7187]
### Describe the bug

There's an `We're not able to process this request. Please refresh the page and try again.` error in the checkout with Afterpay payment method selected.

### To Reproduce

_You need to test in a store where Afterpay is enabled_

1. As a shopper, add a product to the cart and proceed to the checkout. 
2. Fill the form and select Afterpay from Payment options
3. Place order

### Actual behavior

An error appears after the checkout form is submitted:
`We're not able to process this request. Please refresh the page and try again.`

### Screenshots

<img width="876" alt="Screenshot 2023-09-12 at 16 57 32" src="https://github.com/Automattic/woocommerce-payments/assets/1553182/894d2c0f-3b07-4afd-b45b-f38e9e750c9a">

### Expected behavior

Order is placed without errors when Afterpay method is selected
### Additional context

- We can see this error in the Stripe dashboard, when we POST to `payment_intents` endpoint:
```
{
  "error": {
    "code": "parameter_missing",
    "doc_url": "https://stripe.com/docs/error-codes/parameter-missing",
    "message": "Missing required param: shipping[address][line1].",
    "param": "shipping[address][line1]",
    "request_log_url": "https://dashboard.stripe.com/acct_xxxxxx/test/logs/req_xxxxxx?t=1694520304",
    "type": "invalid_request_error"
  }
}
```
- According to my tests it affects Split and Defferred UPE implementations, the Legacy one is not affected.
- Can be reproduced in both block and shorcode based checkouts
- I can only reproduce the issue locally in v6.4.x, previous versions don't seem to be affected

**Comment by brandonwanA8C** [comment]
@mgascam 
any context you can provide about "Split and Defferred UPE implementations"?
