### ISSUE TITLE
Transaction Details > Dispute Details > Inquiry CTA buttons

### ISSUE THREAD

**Issue by Jinksi** [Automattic/woocommerce-payments#7193]
Part of #6883

To the Transaction Details screen, we're adding buttons to the dispute details that the merchant can click to take action to resolve an inquiry (disputes with status `warning_needs_response`).

#### Additional Details
* Related issue for dispute actions: #6926
* Related issue for inquiry steps to resolve: #7245

**Comment by haszari** [comment]
Clarification – is this issue just action buttons, or does it cover all changes to transactions screen for open, unresponded inquiries?

**Comment by Jinksi** [comment]
This issue is only for action buttons.

There is one additional project issue for inquiries awaiting a response:
* #7245

I've grouped the issues for Inquiries on epic #6883 if this helps:

<img width="820" alt="image" src="https://github.com/Automattic/woocommerce-payments/assets/3147296/da568cc0-3809-4b4e-afae-a08c202db410">

**Comment by haszari** [comment]
> > ~~**Warning**~~
> ~~This issue is `blocked` until we determine the actions available for inquiries.~~
> ~~See slack discussion: p1693496507185109-slack-C03LA109BKM~~

Removed `blocked` label (and from description) as @brucealdridge is working on this – Bruce feel free to re-add blocked label (with a comment) if you hit a blocker 🙌
