### ISSUE TITLE
WooPay Checkout overrides all webhook payloads, not just WooPay webhook payloads

### ISSUE THREAD

**Issue by thejamescollins** [Automattic/woocommerce-payments#7219]
### Describe the bug

WooCommerce Payments includes functionality to send order status changes to WooPay URLs, however this functionality incorrectly interferes with  **all** other webhook payloads, not just WooPay webhook payloads.

This causes any other users of WooCommerce's webhook mechanism to have unexpected behaviour.

We are the creators of WooCommerce Zapier, and we rely heavily on WooCommerce's built in webhook delivery mechanism.

We have received reports from several of our users, whose Zaps are not working because they have recently activated WooCommerce Payments and it has caused their existing WooCommerce Zapier webhook payloads to break.

### To Reproduce

1. Go to WooCommerce Payments Settings and enable WooPay Checkout.
2. Go to `/wp-admin/admin.php?page=wc-settings&tab=advanced&section=webhooks` and ensure a `WCPay` `order.status_changed` webhook has been created.
3. Use http://requestbin.com (or similar) to create a webhook delivery URL destination. Use that URL when creating a new Product Updated webhook. Save the webhook and ensure it is active.
4. Edit an existing product in your store and save.
5. Wait 1-2 minutes for the webhook delivery to occur.
6. In requestbin, note the product webhook payload is something like:
  ```{"blog_id":220660587,"order_id":54080,"order_status":"draft"}```
  When it should be a usual product webhook payload with 60+ data fields in it.
7. Return to your store and turn off WooPay Checkout
8. Confirm that the WooPay webhook is removed.
9. Re-edit a product, and confirm that the webhook payload delivered is now correct as expected.

### Actual behavior
With WooPay checkout enabled, **all** WooCommerce webhooks will deliver an incorrect payload containing only `blog_id`, `order_id`, and `order_status`.

### Expected behavior

WooPay should only override/customise the webhook payload for its own webhooks.
It should **not** change or break payloads for other webhooks.

### Desktop (please complete the following information):

* OS: Mac
* Browser Safari
* Version 16.6

(this issue occurs regardless of os/browser/version though)

### Additional context

This webhook functionality was introduced in https://github.com/Automattic/woocommerce-payments/pull/4324.

The likely solution would be to update the [`WooPay_Order_Status_Sync:: create_payload()`  function](https://github.com/Automattic/woocommerce-payments/blob/ca7929f37ebaea13126c87904e71b22a38f47855/includes/woopay/class-woopay-order-status-sync.php#L137) so that it returns `$payload` unmodified if the `$webhook_id` is *not* for a WooPay webhook. For example, you could do something like:

 ```php
        $webhook = wc_get_webhook( $id );
        if ( 0 !== strpos( $webhook->get_delivery_url(), \WCPay\WooPay\WooPay_Utilities::get_woopay_url() ) ) {
            // Not a WooPay webhook.
            return $payload;
        }
		return [
			'blog_id'      => \Jetpack_Options::get_option( 'id' ),
			'order_id'     => $resource_id,
			'order_status' => $payload['status'],
		];
```

WooCommerce Payments should not override or interfere with any other WooCommerce webhooks apart from it's own webhook(s).

**Comment by namiokuzono** [comment]
6785516-zd-a8c

**Comment by thejamescollins** [comment]
Hi @rafaelzaleski,

I'm thinking that you might be the most familiar with this syncing via webhooks feature, so would you be willing to chime in here?

Thank you in advance 🙏

**Comment by achyuthajoy** [comment]
@om4james Thanks for reporting the issue and sharing the testing instructions. I can confirm that the webhook payloads are modified when WooPay is active on the site. 

We're looking into this and will keep you posted. Thanks again
