### ISSUE TITLE
[BNPL] Increase Afterpay/Clearpay UK transaction upper limit to 1,200 GBP

### ISSUE THREAD

**Issue by brandonwanA8C** [Automattic/woocommerce-payments#7222]
### Description
There is a recent Doc discrepancy on the BNPL/Afterpay txn upper limit.
Stripe Doc said "1000 GBP" whereas in the contract it **should be "$1200 GBP"**
<img width="1038" alt="Screenshot 2023-09-15 at 10 59 51 AM" src="https://github.com/Automattic/woocommerce-payments/assets/113071364/0b88fa8e-229a-4a11-96eb-5494d77b8074">

This ticket is to make any change & testing necessary to ensure BNPL/Afterpay's upper txn limit is 1200 GBP in the UK market.

### Acceptance criteria
* Afterpay/Clearpay BNPL txn upper limit in UK is 1200 GBP (instead of 1000 GBP)
* Any BNPL txn in the UK with total amount in Payment Intent that is larger than 1200 GBP should not have Afterpay as an option
* Docs content is reflecting this limit (already reflects the truth): https://woocommerce.com/document/woopayments/payment-methods/buy-now-pay-later/

### Dev notes

Limits defined in: https://github.com/Automattic/woocommerce-payments/blob/c8190e0efd693faa8b948279b26d0148badcf72d/includes/payment-methods/class-afterpay-payment-method.php#L48

### Additional context
Stripe Doc: https://stripe.com/docs/payments/afterpay-clearpay#collection-schedule
Woo Doc: https://woocommerce.com/document/woopayments/payment-methods/buy-now-pay-later/

**Comment by kalessil** [comment]
Confirmed: the [actual limit](https://github.com/Automattic/woocommerce-payments/blob/develop/includes/payment-methods/class-afterpay-payment-method.php#L48) is 1000 GBP. @mgascam: can you update the limit as per Brandon's request, please?

**Comment by kalessil** [comment]
@dmvrtx @KarlisJ: there is a linked issue about supplying server-side configurations and using it for BNPL PMs configuration. That's a reasonable proposal IMO, given we went live and can streamline/optimize related operations.

Assuming this is feasible:
- is there anything in place that supplies PMs-focused configurations to clients yet?
- how does that look in terms of reliability for the client?
- any other hints?

**Comment by KarlisJ** [comment]
@kalessil 
> is there anything in place that supplies PMs-focused configurations to clients yet?

No, we have a static hardcoded values in `payment-methods-map.tsx` file.

> how does that look in terms of reliability for the client?

About a month ago I was exploring this and the biggest problem was the number of changes required in client JS files. Currently, the paymentMethodsMap is available on the initial load and we use direct access for the properties. As soon as we load it through hooks (easy to achieve, we have many examples of that in the codebase) the syntax is broken because the values are not accessible on initial load.

**Comment by kalessil** [comment]
Thanks for the feedback @KarlisJ !
