### ISSUE TITLE
[BNPL] Externalize BNPL txn limits in MC, and make them configurable 

### ISSUE THREAD

**Issue by brandonwanA8C** [Automattic/woocommerce-payments#7223]
**this is an idea concept for now, still requires impact & needs analysis. 
do not need to implement until we have clear requirements in place.**

### Description
BNPL transactions have certain lower & upper limits per market: https://stripe.com/docs/payments/afterpay-clearpay
These limits can (and may) change to accommodate local markets' risk threshold, as well as driving higher AoV for each provider or market.

Instead of implementing & testing a code change for each limit update (e.g. https://github.com/Automattic/woocommerce-payments/issues/7222), we can consider making these txn limits configurable in Mission Control that:
* enables MC admin to see what the existing BNPL limits are across each provider and market
* enables MC admin to update the limits (per contract) to accommodate the BNPL limits change
* enables MC admin to see the logs of the "changes, timestamp, by-whom" to ensure tracability   

More Details TBD---------------
### Acceptance criteria
tbd

### Designs
tbd

### Testing instructions
tdb

**Comment by pierorocca** [comment]
Closing in favor of addressing this in the domain driven architecture.
