### ISSUE TITLE
Mobile layout & styling fixes and improvements for `Payment details` when payment is disputed

### ISSUE THREAD

**Issue by brucealdridge** [Automattic/woocommerce-payments#7230]
### Describe the bug

On the payments summary page with a dispute the mobile view needs some styling changes.

- When the pill for the payment - `Disputed: Needs response` - the label can sit outside the Card element.
- Padding consistency 

**Current View**
![image](https://github.com/Automattic/woocommerce-payments/assets/57298/9e1b0f65-d570-4f5d-b632-5de99a39af26)

### Changes Required

- Make sure padding/margin is consistent to be 16PX in all boxes. 
- Move the status pill to the very top positioned at the very top. 
- ~Stack the buttons~ handled in #7093

![image](https://github.com/Automattic/woocommerce-payments/assets/57298/5bba9dda-b0fa-45bc-9a25-a073b62a0f9b)

RiEQmaKRI7u9USAI3lyZz0VX-fi-7430%3A30973

### To Reproduce

1. On WooPayments 6.5 set the feature flag on `update_option( '_wcpay_feature_dispute_on_transaction_page', '1' );`
2. Create a disputed transaction using the card `4000000000000259` at checkout.
3. Find the dispute in Payments → Disputes and click it to view the dispute details screen on mobile.

### Additional context

p1695089677913989-slack-C03LA109BKM

**Comment by zmaglica** [comment]
This issue impacts disputes, so assigning to team Helix. (based on team responsibilities Pc2DNy-3z-p2) @haszari Assigning as part of Gamma Triage process PcreKM-yM-p2.

**Comment by haszari** [comment]
As discussed with @nikkivias and team in slack, there's a bigger issue here which we might want to look at in future. This issue is to fix specific pain points with current design. 

The "you have a dispute" notice illustrates the problem. It's nested three levels deep:

- Transaction detail box
  - Dispute detail box
    - Dispute needs response notice

And on mobile, that nesting makes for a very small box, and lots of margins!

<img width="586" alt="Screenshot 2023-09-26 at 2 07 49 PM" src="https://github.com/Automattic/woocommerce-payments/assets/4167300/9e91633d-a9f1-4fb9-a751-c06034baeb19">

**Comment by nikivias** [comment]
Hi team, I've previously mentioned that there is not much room to compromise here as the dispute notice HAS to be contained and made separate from the rest of the details. The idea here is that the dispute details are akin to a yellow notice slapped onto a transaction. I think the bigger issue here is that the dispute details is so far down on mobile, but that is another problem, for maybe another team lol.

However I definitely recognize the marg-inception 🤓 situation here, I was wondering if the banner itself could be made to fill the entire container. Please see mockup

<img width="998" alt="image" src="https://github.com/Automattic/woocommerce-payments/assets/99638528/1e13a5dd-b6b6-4b73-916c-2d14c290d763">

**Comment by haszari** [comment]
Removing `projects`, this is a bug that we can add to maintenance backlog.

**Comment by haszari** [comment]
Next steps:

- Review description, comments and UI and list essential styling tweaks/fixes.
- Implement the fixes!
