### ISSUE TITLE
Accept dispute modal text implies that the fee will only be deducted if the dispute is accepted

### ISSUE THREAD

**Issue by Jinksi** [Automattic/woocommerce-payments#7254]
Reported in https://github.com/Automattic/woocommerce-payments/pull/7093#discussion_r1329564268

The text in the Accept dispute modal below implies that the fee will be deducted only once they've accepted, yet the deduction has already occurred ([Stripe docs ref](https://support.stripe.com/questions/dispute-fees-faq)).

I've suggested a replacement below as inspiration:

```diff
-The disputed amount will be returned to the cardholder, with a %s dispute fee deducted from your account.
+The disputed amount and the %s dispute fee will not be returned to you.
```

This also affects the "Steps to resolve" accept tooltip text.

```diff
-Accepting this dispute will automatically close it. The account will be charged a %s fee, and the disputed amount will be refunded to the cardholder.
+Accepting this dispute will automatically close it. The disputed amount and the %s dispute fee will not be returned to you.
```

**Comment by haszari** [comment]
@nikkivias can you review @Jinksi 's suggested tweaks to wording and make sure there's no issues? 

If anyone (Helix) picks this up, **please prototype and show the changes in context (screenshots/vids) so it's easy for design & product to review**.

**Comment by nikivias** [comment]
@Jinksi @haszari text for both places looks good, thank you
