### ISSUE TITLE
Transaction Details → Dispute Details: the steps to resolve date should show "Past due" if it is awaiting response and past the `due_by` date.

### ISSUE THREAD

**Issue by Jinksi** [Automattic/woocommerce-payments#7255]
Reported in https://github.com/Automattic/woocommerce-payments/pull/7231#issuecomment-1730375167

On the Transaction Details → Dispute Summary Row, we show "Past due" when a dispute is awaiting a response but the `due_by` date is in the past.

We should match this behaviour within the "Steps to resolve" section.

![Image](https://github.com/Automattic/woocommerce-payments/assets/3147296/1bc847f4-7764-4c43-9244-c077a2119a83)

**Comment by brucealdridge** [comment]
Is there a way a Merchant can get into this state? 

I'm not sure it's helpful to show the Steps to Resolve if the dispute is past due. Can we show the won/lost footer instead?

**Comment by Jinksi** [comment]
> Is there a way a Merchant can get into this state?

It is not clear whether this is possible for live accounts – one would assume that as soon as the `due_by` time has been reached, the dispute will enter `under_review`, but the exact timing is not clear. Because of this uncertainty, it is best to gracefully render UI for this case IMO.

> Can we show the won/lost footer instead?

I think there is a greater risk in removing these steps or challenge/accept buttons while the dispute has a `needs_response` status.
