### ISSUE TITLE
Block checkout error with subscription product while WooPayments gateway is disabled

### ISSUE THREAD

**Issue by aheckler** [Automattic/woocommerce-payments#7271]
### Describe the bug

This is pretty edge case, but the combination of factors below causes an indecipherable error on the block checkout page:

![image](https://github.com/Automattic/woocommerce-payments/assets/5512652/fa29f950-1a62-4874-9e2d-4bda24f4c4ce)

### To Reproduce

1. Have a WooPayments test site. WooPayments account must be U.S.-based.
2. Enable the subscriptions feature under Payments > Settings.
3. Disable WooPayments as a gateway at the top of the settings page.

<img width="309" alt="Screenshot taken on 2023-09-22 at 21 38 20 UTC@2x" src="https://github.com/Automattic/woocommerce-payments/assets/5512652/6b1dab51-f197-4622-8641-5fae3a0679c7">

4. Enable another gateway for payments, e.g. Stripe.
5. Create a subscription product.
6. Create a page using the checkout block.
7. Set that page as the checkout page in the core WooCommerce settings.
8. On the frontend, add the subscription product to the cart and go to the checkout page (which should be using the block).
9. See the screenshot above.

If you then disable the Stripe plugin, you will see the error that you probably should see even when Stripe is enabled:

<img width="909" alt="Screenshot taken on 2023-09-22 at 21 34 12 UTC@2x" src="https://github.com/Automattic/woocommerce-payments/assets/5512652/642014d8-6c5e-4016-acad-f15204534137">

The scenario produces this error for the shortcode checkout (with Stripe enabled or disabled):

<img width="626" alt="Screenshot taken on 2023-09-22 at 21 35 06 UTC@2x" src="https://github.com/Automattic/woocommerce-payments/assets/5512652/9ea80f40-f531-4344-b867-887b3dfcf067">

I'm not sure how much we care about this given that it's gotta be pretty rare and the built-in subscriptions functionality is going away (ish) anyway. 🤷‍♂️

**Comment by frosso** [comment]
@aheckler do you have any additional details on how to reproduce?
I tried to reproduce this locally, with WooPayments 6.5.1 and `develop`.
Following your instructions, I ensured that WC Stripe CC was enabled and WooPayments disabled, with a subscription product in the cart.
![Screenshot 2023-09-27 at 9 23 10 AM](https://github.com/Automattic/woocommerce-payments/assets/273592/87662da7-1b3b-4634-8fb0-702ca69a1866)

This is the error I see on the blocks checkout when WC Stripe is enabled.
![Screenshot 2023-09-27 at 9 22 54 AM](https://github.com/Automattic/woocommerce-payments/assets/273592/adcf219b-ea92-4a58-96e0-3ab4775b4f8a)

**Comment by aheckler** [comment]
Hmm, I can't repro on a fresh JN site either. :( Must be something specific to my long-running test site then, so I'll go ahead and close this.

JS errors from my test site, for reference:

![Screenshot taken on 2023-09-27 at 13 18 24 UTC@2x](https://github.com/Automattic/woocommerce-payments/assets/5512652/081a075a-2496-4b66-a28e-273f6aa68a9c)
