### ISSUE TITLE
6.5.0 broke payment_method_title in API, value always ignored

### ISSUE THREAD

**Issue by alexhaas** [Automattic/woocommerce-payments#7273]
### Describe the bug

When creating an order using the WooCommerce API, if either `status=processing` or `set_paid=true` is included in the request, any value of `payment_method_title` is ignored and will default to "Credit card / debit card".

This seem to be a regression in a recent update because I have some automation that relies on this and it recently broke.

**Request**
```
curl --location --request POST '<site-root>/wp-json/wc/v3/orders?payment_method=bacs&payment_method_title=Direct%20bank%20transfer&status=processing' \
```

**Result**
```
...
    "payment_method": "bacs",
    "payment_method_title": "Credit card / debit card",
...
```

### Expected behavior

The value of `payment_method_title` should always be respected and persisted.

### Actual behavior

The value of `payment_method_title` is lost.

### Steps to reproduce

1. Run the cURL command below

```
curl --location --request POST '<site-root>/wp-json/wc/v3/orders?payment_method=bacs&payment_method_title=Direct%20bank%20transfer&status=processing' \
```

Worked on 6.4.2, broken on 6.5.0

**Comment by frosso** [comment]
Fixed by https://github.com/Automattic/woocommerce-payments/pull/7285 , will be part of the 6.5.1 release today.
