### ISSUE TITLE
[6.5.0] Issues enabling UPE with Page Optimize active

### ISSUE THREAD

**Issue by csmcneill** [Automattic/woocommerce-payments#7274]
### Describe the bug
If [Page Optimize](https://wordpress.org/plugins/page-optimize/) is active while version 6.5.0 of WCPay is active, a merchant may not be able to enable UPE.

### To Reproduce

So far, I've been unable to reproduce the issue, but I suspect:

1. Install Page Optimize.
2. Install a version of WCPay where UPE isn't enabled by default.
3. Update WCPay to 6.5.0.
4. Onboard WCPay.
5. Try to enable UPE.
6. The elements at `wp-admin/admin.php?page=wc-admin&path=/payments/additional-payment-methods` to select payment methods and continue enablement do not render.
7. Deactivate Page Optimize.
8. Repeat step 5.
9. The elements from step 6 load properly, even if re-enabling Page Optimize.

### Actual behavior
Under certain conditions, WooPayments merchants cannot enable UPE while the Page Optimize plugin is active. Page Optimize is an Automattic plugin and comes installed/active by default for all sites hosted on WordPress.com and Woo Express.

### Screenshots
![GP8dzc.png](https://github.com/Automattic/woocommerce-payments/assets/82999806/01f846b5-6c4c-4e85-adf5-640421a61a6f)

### Expected behavior
WooPayments options are rendered properly while Page Optimize is active.

### Additional context

p1695559405915419-slack-C3NCP7ZJ6
7077777-zen

**Comment by jessy-p** [comment]
Assigning low priority as it will occur only on very old versions 
> Install a version of WCPay where UPE isn't enabled by default.

@csmcneill please confirm ?

**Comment by csmcneill** [comment]
> please confirm ?

@jessy-p I tested this on a fresh AT site by...

2. Breaking symlink.
3. Reverting to version 5.0.0.
4. Updating to 6.5.0.
5. Enabling UPE.

...and I couldn't reproduce the issue. Page Optimize hasn't been updated for ~2 months now, so it's unlikely there was an update there that resolved the issue. It's possible that this could be isolated to the site in 7077777-zen or that there was something amiss with Woo core or something specific to the AT environment that caused this issue temporarily.

Since I cannot reproduce and we're moving to remove legacy card elements, I'll close this for now.
