### ISSUE TITLE
Add loading state to WooPay button

### ISSUE THREAD

**Issue by bborman22** [Automattic/woocommerce-payments#7295]
### Description

The goal of this issue is to add a loading state to the WooPay button to indicate when it is requesting a new checkout session. This discussion (pdpOw2-3Di-p2#comment-3590) will need some input from design on the right implementation of the loading state but would likely include a spinner icon and particularly anything we can pull from existing button loading states.

### Acceptance criteria

* Clicking the WooPay button will display a visual loading indicator while the session request is processing.
* The shopper will be unable to trigger the session request while the button is in the loading state.
* Upon success or failure of the session request, the loading state will be removed and the button can be clicked again.
* The button loading state is approved by design with a demo video in the PR for review.

### Designs

TBD

### Additional context

This issue is related to the larger WooPay First Party Authentication project.

**Comment by zmaglica** [comment]
This issue impacts WooPay, so assigning to team Heisenberg (based on team responsibilities Pc2DNy-3z-p2) @frosso . Assigning as part of Gamma Triage process PcreKM-yM-p2.
