### ISSUE TITLE
(Minor) WooPayments `General` settings help text emphasises test mode

### ISSUE THREAD

**Issue by haszari** [Automattic/woocommerce-payments#7299]
### Describe the bug
In the settings screen for WooPayments, there's help text to explain each category of settings. 

The top category is `General` and the main setting is to enable / disable WooPayments. There's also a much less important `Test mode` setting (mostly used by developers, or stores trialling WooPayments). 

The help text says: `Enable or disable WooPayments on your store and turn on test mode to simulate transactions.`. As I see it, this places a lot of emphasis on `Test mode` as a setting the merchant might want to toggle.

<img width="910" alt="Screenshot 2023-09-27 at 2 24 27 PM" src="https://github.com/Automattic/woocommerce-payments/assets/4167300/cf678dd7-b975-4c20-9bfc-88625fb355c5">

### Expected behavior
My suggested change is to either:

- Remove the help text – I think the label `General` and the copy in the settings box do a good job of explaining the settings. Less is more. Declutter. (I prefer this)
- OR
- Simplify the help text to focus on the fact that these are high-level settings that affect things globally: `Enable WooPayments on your store` or `Global settings`.

**Comment by vbelolapotkov** [comment]
@anu-rock routing to you since it relates to settings. cc @vladolaru @timmy5685

**Comment by anu-rock** [comment]
I agree with Rua's observation. Added to our backlog.

**Comment by anu-rock** [comment]
@haszari Opened a PR to fix this. I tried both options, then went with the second one as the first one was looking a bit inconsistent.
