### ISSUE TITLE
Epic: Update styles to G2 styles

### ISSUE THREAD

**Issue by allendav** [Automattic/woocommerce-payments#732]
aka Gutenberg 2. No more pink, purple, etc. cc @LevinMedia 

- [ ] Settings
- [ ] Deposits (List)
- [ ] Deposit (Detail)
- [ ] Transactions (List)
- [ ] Transaction (Detail)
- [ ] Disputes (List)
- [ ] Dispute (Detail)

**Comment by deepakpathania** [comment]
@allendav  @LevinMedia Is this still relevant and if yes, do we need designs before proceeding with the same?

**Comment by LevinMedia** [comment]
No longer relevant, closing
