### ISSUE TITLE
Express checkout buttons are not rendered on "Pay for Order" page if cart is empty

### ISSUE THREAD

**Issue by mehamasum** [Automattic/woocommerce-payments#7346]
### Describe the bug
Express checkout buttons are not rendered on the Pay for Order page if the cart is empty.

### To Reproduce
1. Make sure your cart is empty
2. Create an order from wp-admin for a customer, add line tems
3. Open the "Customer payment page" as customer
4. Notice GPay/APay is not rendered
5. Add something to cart on a different browser tab
6. Refresh the "Customer payment page" as customer
7. Notice GPay/APay is rendered now

### Additional context
Plugin version: 6.5.1

I did some digging and found that `display_pay_for_order_page_html` calls `display_payment_request_button_html` which checks `should_show_payment_request_button`.

This function checks if cart total is zero for "non-product" pages. Pay for Order is a non-product page, thus it returns false.
But for Pay for Order page, the cart total shouldn't matter.

https://github.com/Automattic/woocommerce-payments/blob/cdd14ca3eebf62857b1a7d0e823c70f55c0f7d58/includes/class-wc-payments-payment-request-button-handler.php#L536

**Comment by jessy-p** [comment]
This issue impacts Additional Payment Methods (including Apple Pay / Google Pay), so assigning to Fusion (based on team responsibilities Pc2DNy-3z-p2) @anu-rock. Assigning as part of Gamma Triage process PcreKM-yM-p2.

**Comment by elazzabi** [comment]
Noting that this is a duplicate issue of https://github.com/Automattic/woocommerce-payments/issues/6650 but this one has more details on how to fix it :). Thanks for the discovery/hints @mehamasum ! I'm working on a fix and will close this issue in favor of the other one ^
