### ISSUE TITLE
Merchant facing: On-boarding

### ISSUE THREAD

**Issue by dwainm** [Automattic/woocommerce-payments#7347]
As described and assigned in paJDYF-7q7-p2, Sigma needs to improve the E2E test coverage of the multi currency feature. 

The fix for this issue will cover the multi-currency onboarding screen tests that resides in `/wp-admin/admin.php?page=wc-admin&path=%2Fpayments%2Fmulti-currency-setup`.

**Possible scenarios:**

- Button is not clickable when no currencies are selected.
- Currencies are selectable.
- Already enabled currencies do not list in the currency screen.
- There are some suggested currencies on the beginning on the list.
- Selected currencies are enabled after submitting the form.
- Currency switch by geolocation is offered
- Currency switch by geolocation is previewed correctly with USD and GBP currencies.
- Currency switcher widget is offered while Storefront theme is active.
- Currency switcher widget is not offered when active theme is not Storefront.

The dev can decide which ones are good enough to be tested, and dismiss others.

**Comment by bborman22** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Fractal-62a0f7b955648b001e1f5e1f/issues/Automattic/woocommerce-payments/7347?planning-poker) with Zenhub @cesarcosta99 @lovo-h @rafaelzaleski @ricardo
