### ISSUE TITLE
Shopper Facing: Switch currency via the widget.

### ISSUE THREAD

**Issue by dwainm** [Automattic/woocommerce-payments#7349]
As described and assigned in paJDYF-7q7-p2, Sigma needs to improve the E2E test coverage of the multi currency feature. 

The fix for this issue will cover the tests for the currency switcher widget.

**Possible scenarios:**
- Merchant doesn't see the currency switcher when multi-currency is disabled
- Merchant can add the currency switcher to the sidebar
- Merchant can add the currency switcher to a post/page
- Merchant can switch the currency on:
    - the homepage
    - the product page
    - cart page
    - checkout page
via the currency switcher on the sidebar.
- Currency switching doesn't affect:
    - Prices on the shopper order pages
    - Prices on the pay for order pages
    - Prices on the order received page

The dev can decide which ones are good enough to be tested, and dismiss others, and they can add their own tests which may be missing in this list.

**Comment by bborman22** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Fractal-62a0f7b955648b001e1f5e1f/issues/Automattic/woocommerce-payments/7349?planning-poker) with Zenhub @cesarcosta99 @lovo-h @rafaelzaleski @ricardo
