### ISSUE TITLE
Shopper Facing: Multi-currency checkout.

### ISSUE THREAD

**Issue by dwainm** [Automattic/woocommerce-payments#7350]
As described and assigned in paJDYF-7q7-p2, Sigma needs to improve the E2E test coverage of the multi currency feature. 

The fix for this issue will cover the multi-currency checkout tests.

**Possible scenarios:**

- Can checkout with different currency than the store currency
- Order received page shows correct currency
- Shopper order page shows correct currency
- Previous order in different currency still shows correct currency

The dev can decide which ones are good enough to be tested, and dismiss others.

**Comment by bborman22** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Fractal-62a0f7b955648b001e1f5e1f/issues/Automattic/woocommerce-payments/7350?planning-poker) with Zenhub @cesarcosta99 @lovo-h @rafaelzaleski @ricardo
