### ISSUE TITLE
Rename master branch to trunk

### ISSUE THREAD

**Issue by allendav** [Automattic/woocommerce-payments#736]
May require an update to woorelease first

**Comment by allendav** [comment]
@m has requested we standardize on trunk instead

**Comment by reykjalin** [comment]
There is no dependency on branches in `woorelease` so I think we can safely rename the branch without any hassle 🙂. The only work we _might_ have to do is to go through all the open PRs and change the base branch 🤷‍♂️

**Comment by reykjalin** [comment]
I'm setting the priority on this to `High` so we can align with the rest of A8c asap.

**Comment by allendav** [comment]
Added to janitorial trello

**Comment by kalessil** [comment]
Checklist for the migration:
- [ ] - Travis configuration updated
- [ ] - The trunk branch is marked as main in GH repository settings
- [ ] - bin/*, .tasks/*, github/* are not referencing 'master'
- [ ] - All open PRs are updated (target branch is trunk)

**Comment by kalessil** [comment]
For the next janitors: it was a discussion about a good time for this (p1603961576057000-slack-wcpay + next messages in the channel) and it was proposed to do it during cooldown week or Christmas time.

FYI: GitHub might rollout migration tooling later this year: https://github.com/github/renaming#later-this-year-seamless-move-for-existing-repositories-
