### ISSUE TITLE
Clean up legacy dispute screen code

### ISSUE THREAD

**Issue by Jinksi** [Automattic/woocommerce-payments#7363]
Part of #6883

Now that we've added all dispute details to the Transaction Details screen, we can remove code related to the now unused `/payments/disputes/details` screen.

- [x] Update/rename the accept dispute action function to become the default hook, removing the legacy one. Addressed by https://github.com/Automattic/woocommerce-payments/pull/7456.
	 - Legacy `acceptDispute` action function can be removed
		 - https://github.com/Automattic/woocommerce-payments/blob/8c1558bd3fe67596eb32803357380194d23d0b2c/client/data/disputes/actions.js#L42
	 - New action function added in #7093 can be renamed `acceptDispute`
		 - https://github.com/Automattic/woocommerce-payments/blob/8c1558bd3fe67596eb32803357380194d23d0b2c/client/data/disputes/actions.js#L101
- [x] Remove [openDisputeDetails()](https://github.com/Automattic/woocommerce-payments/blob/a8069441a4be0c5e21a0eb7ba6b579fc76de18aa/tests/e2e/utils/flows.js#L517) used by e2e tests. Addressed in https://github.com/Automattic/woocommerce-payments/pull/7448.
- [x] Remove the [legacy dispute details page](https://github.com/Automattic/woocommerce-payments/blob/2eb4de5d4bca3573339e15197987a3943ffeddf4/client/disputes/details/index.tsx). Addressed in https://github.com/Automattic/woocommerce-payments/pull/7456.
- [x] Remove 'disputes' from the [`details-link` `ParentSegment` type](https://github.com/Automattic/woocommerce-payments/blob/efd9c5a5a0068972eab6827967eac6c8be4ccf6e/client/components/details-link/index.tsx#L18). Addressed in https://github.com/Automattic/woocommerce-payments/pull/7460.
- [x] Delete any other unused code used solely by the `/payments/disputes/details` screen. Addressed in https://github.com/Automattic/woocommerce-payments/pull/7456.

**Comment by haszari** [comment]
Setting this zero SP as the work is estimated in #6883
