### ISSUE TITLE
Missing mappings for the Payment Status Chip in Transaction Details

### ISSUE THREAD

**Issue by reykjalin** [Automattic/woocommerce-payments#737]
[The mappings](https://github.com/Automattic/woocommerce-payments/blob/241d218b853b5628412908a033c0ad4d128a0015/client/utils/charge/index.js#L31-L46) for the Payment Status Chip in the Transaction Details page are missing mappings for `warning_closed` and `charge_refunded`. This results in the chip using its own [default mapping](https://github.com/Automattic/woocommerce-payments/blob/241d218b853b5628412908a033c0ad4d128a0015/client/components/payment-status-chip/index.js#L15-L66) which results in an empty chip.

![image](https://user-images.githubusercontent.com/13835680/84934919-9244e780-b10a-11ea-9054-fc0073c4b5d3.png)

**Expected behavior**

A status chip that isn't empty:

![image](https://user-images.githubusercontent.com/13835680/84934880-83f6cb80-b10a-11ea-88b1-4f92d94bbed3.png)

# Suggested fix

* Map `charge_refunded` to `Refunded`, similar to what we're already doing for refunded transactions.
* Map `warning_closed` to `Disputed: Inquiry closed`, similar to how the dispute table [maps that to `Inquiry: Closed`](https://github.com/Automattic/woocommerce-payments/blob/241d218b853b5628412908a033c0ad4d128a0015/client/components/dispute-status-chip/mappings.js#L18-L21).

Note that these mappings will probably have to be implemented in the [charge `util.js` file](https://github.com/Automattic/woocommerce-payments/blob/241d218b853b5628412908a033c0ad4d128a0015/client/utils/charge/index.js#L49-L69).

@LevinMedia what do you say to these suggested chip texts?

# Reproducing the issue

1. Make a payment using Stripe's `inquiry` type [dispute testing number](https://stripe.com/docs/testing#disputes) to make a payment: `4000 0000 0000 1976`.
1. Challange the dispute with either `winning_evidence` or `losing_evidence`. Both should result in `warning_closed`.
1. Notice that the transaction details page now has an empty chip.

`charge_refunded` hasn't been reproduced yet (and might actually not strictly have to be handled) but we should cover our bases there anyway.

cc @luizreis

**Comment by luizreis** [comment]
After some discussions in #738, we've decided to:

* Update payment statuses to match the [disputes list](https://github.com/Automattic/woocommerce-payments/blob/master/client/components/dispute-status-chip/mappings.js). Meaning that we're going to differentiate between disputes and inquiries in the status chip and we're going to display the same text, adding a Disputed: label for non-inquiry cases.
* Dispute and inquiry statuses should take precedence over refunds. In case a merchant refunds an inquiry and it gets to the `warning_closed` state, `Inquiry: Closed` should be the payment status.
