### ISSUE TITLE
Update WooPay express checkout button to appear as default

### ISSUE THREAD

**Issue by mdmoore** [Automattic/woocommerce-payments#7370]
### Describe the bug

When enabling WooPay for the first time, the express checkout buttons do not appear even though the Checkout, Cart, and Product pages are enabled by default. The buttons only appear after the settings have been saved.

### To Reproduce

1. On a fresh site, go to Payments -> Settings
2. Check that WooPay is enabled in the "Express checkouts" section
3. Go to "Customize"
4. Note that all pages are checked **don't save the settings**
5. Add a product to the cart and visit the Checkout page
6. Notice that the express button doesn't appear

### Actual behavior

All express button locaatoins are selected by default, but buttons do not appear on any page until the settings have been saved.

### Screenshots
<img src="https://github.com/Automattic/woocommerce-payments/assets/3473953/5f1c5bf2-e292-4694-bc33-23fbd65cfe64" />

<img src="https://github.com/Automattic/woocommerce-payments/assets/3473953/f1501455-8332-4a2d-a6a6-aca94152275c" />

### Expected behavior

WooPay express checkout buttons should be rendered on pages by default.

**Comment by mdmoore** [comment]
This is likely happening because the `platform_checkout_button_locations` option doesn't exist until it's [updated here](https://github.com/Automattic/woocommerce-payments/blob/e7915bb989d6f369ead31ef5f3e68d297399d081/includes/admin/class-wc-rest-payments-settings-controller.php#L908) upon saving the WooPay express checkout settings.

**Comment by pierorocca** [comment]
I think there's a similar issue with the default policies. The shortcode link wouldn't appear until I saved the settings. #7302

**Comment by mdmoore** [comment]
@pierorocca Nice find. I don't think this has the same cause. The `platform_checkout_custom_message` option [does already exist](https://github.com/Automattic/woocommerce-payments/blob/287990726914e93078e5af4207498136206d59a4/includes/class-wc-payment-gateway-wcpay.php#L405) whereas the `platform_checkout_button_location` option did not. I just tested this out on a new site before saving any settings and the custom message appears as expected with shortcodes converted to links. Unfortunately, that doesn't shed any light on this mystery.
