### ISSUE TITLE
Disputes: Remove Issuer Evidence

### ISSUE THREAD

**Issue by brucealdridge** [Automattic/woocommerce-payments#7372]
### Description

Issuer evidence from linked disputes has been added to the transactions screen behind a feature flag. This feature flag will be removed shortly #7365 

Issuer evidence is not yet ready for general availability. It must be either removed or gated behind a feature flag.

![image](https://github.com/Automattic/woocommerce-payments/assets/57298/188a3b2c-9de4-45bd-ac8a-599369751942)

**Comment by shendy-a8c** [comment]
Just to note that issuer evidence was added in https://github.com/Automattic/woocommerce-payments/pull/7192.

**Comment by haszari** [comment]
> gated behind a feature flag

@brucealdridge are you thinking feature flag or rip it out? Might be useful to keep the code in case we want to test something in production. Your call.

**Comment by shendy-a8c** [comment]
I'm adding a feature flag. https://github.com/Automattic/woocommerce-payments/pull/7192 is a lot of code to remove / re-add in the future.

Just wondering if having new [end-points](https://github.com/Automattic/woocommerce-payments/pull/7192/files#diff-f3ef21d4e1e17f691a673c58026614f3abdef78ee99a1d3a5cc1dde404a55745) here has a risk @brucealdridge.
