### ISSUE TITLE
Transactions list shows `estimated` for deposits (payouts) in the past

### ISSUE THREAD

**Issue by haszari** [Automattic/woocommerce-payments#7375]
### Describe the bug

The transactions list has a `Deposit date` column. 

- ✅ For transactions that will get paid out in the future, it says `Estimated Oct 11, 2023`
- 🧐 For transactions that have already been paid out, it says `Estimated Oct 1, 2023` aka `Estimated [in the past]`

<img width="1782" alt="Screenshot 2023-10-05 at 2 05 18 PM" src="https://github.com/Automattic/woocommerce-payments/assets/4167300/a70e81d6-66ae-4ff1-95cd-a69df7243075">

### To Reproduce
1. Set up WooPayments and ensure you have purchases and payouts in the past (this might take time to set up, can see on any store that's been live for a few payouts).
2. Go to `Dashboard > Payments > Transactions`.
3. Ensure `Deposit date` column is visible.
4. View transactions from before the most recent deposit.

### Actual behavior
`Estimated 20 June 2021`

### Expected behavior
`Paid 20 June 2021` or similar. Wording might need care when deposit is in transit, or other situations close to payout date.

**Comment by jessy-p** [comment]
This issue impacts Deposits so assigning to Helix (based on team responsibilities Pc2DNy-3z-p2) @haszari  Assigning as part of Gamma Triage process PcreKM-yM-p2.

**Comment by haszari** [comment]
This issue could be handled by Helix or a team that looks after transaction list. IMO this is a core issue, it's not really about Disputes.

**Comment by zmaglica** [comment]
@haszari We have discussed about this issue in Gamma prioritization call, and we decided that the issue is not within the core. This is the perfect example of the issue that affects multiple team responsibilities. Since it affects reports, I am also looping @anu-rock too, so we can decide could Fusion put this issue under its wing.

@anu-rock Do you think that the team Fusion can work on this issue?

For now, I will move this issue to the Other Teams Queue, as a part of the Gamma Triage process.

**Comment by anu-rock** [comment]
@zmaglica Yes, it does make sense to tackle this issue as part of the reporting maintenance backlog. I'll put it there.

**Comment by haszari** [comment]
Thanks @anu-rock ! The behaviour is likely different now that we've stopped estimating future deposits, the bug might not be happening anymore - worth retesting before starting work!

**Comment by haszari** [comment]
Closing – we fixed this when we removed estimated future payouts (and linking of transactions to future payouts). See relevant issue: 

- #7876
