### ISSUE TITLE
Transaction Details → Improve dispute steps to resolve wording to better guide merchants with resolution

### ISSUE THREAD

**Issue by Jinksi** [Automattic/woocommerce-payments#7380]
Without the "Review the claim" step to resolve on the Transaction Details screen, there is a gap in the steps we provide to merchants to help them resolve disputes.

This issue expands on the language of the first two steps to better communicate the recommended path to resolution.

Proposed new text:
```diff
-1. Email the customer to address their concerns.
+1. Email the customer to identify the issue and work towards a resolution where possible.
-2. Provide guidance on dispute withdrawal if the customer agrees.
+2. Assist the customer in withdrawing their dispute if they agree to do so.
```

![Image](https://github.com/Automattic/woocommerce-payments/assets/3147296/5bccccd1-151b-4a05-bb7c-8c34cec6070b)

Note: we plan to add the "Review the claim" step in a future release: see #7156.

See design: https://www.figma.com/file/RiEQmaKRI7u9USAI3lyZz0VX/Dispute-Flows?node-id=7580%3A73421&mode=dev.

**Comment by shendy-a8c** [comment]
> Note: we plan to add the "Review the claim" step in a future release: see https://github.com/Automattic/woocommerce-payments/issues/7156.

When https://github.com/Automattic/woocommerce-payments/issues/7156 is implemented, would we want to revert this wording change?

**Comment by shendy-a8c** [comment]
@Jinksi can I get a confirmation on the numbering?

Sounds like what you mean:

```diff
-1. Email the customer to address their concerns.
+1. Email the customer to identify the issue and work towards a resolution where possible.
-2. Provide guidance on dispute withdrawal if the customer agrees.
+2. Assist the customer in withdrawing their dispute if they agree to do so.
```

Step 3 remains unchanged.

**Comment by Jinksi** [comment]
Yes! Apologies for the type. Design is the source of truth here.
