### ISSUE TITLE
Merchant facing: Multi-currency setup

### ISSUE THREAD

**Issue by tpaksu** [Automattic/woocommerce-payments#7382]
As described and assigned in paJDYF-7q7-p2, Sigma needs to improve the E2E test coverage of the multi currency feature. 

The fix for this issue will cover the tests for admin screens that are used to set up multi-currency.

**Possible scenarios:**
- Merchant can enable/disable the multi currency feature.
- Merchant can enable/disable currencies.
- Merchant can enter single currency settings, and:
    - Can change the currency rate manually.
    - Can change the charm price manually.
    - Can change the rounding precision manually.
    - Sees the correct decimal points for these currencies:
       - JPY: 0
       - JOD: 3
       - EUR: 2
- Merchant can see those modifications are applied on the product page.

The dev can decide which ones are good enough to be tested, and dismiss others, and they can add their own tests which may be missing in this list.

**Comment by bborman22** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Fractal-62a0f7b955648b001e1f5e1f/issues/Automattic/woocommerce-payments/7382?planning-poker) with Zenhub @rafaelzaleski
