### ISSUE TITLE
Add missing unit tests for restricting PM to location in client

### ISSUE THREAD

**Issue by KarlisJ** [Automattic/woocommerce-payments#7387]
### Describe the bug
in #7315 we introduced 2 new JS methods that can be unit tested but we needed to land the changes in code freeze so PR was approved without the unit tests. 

### Expected behavior
The two new methods in `client/checkout/utils/upe.js` should be covered by unit tests.

**Comment by timur27** [comment]
For visibility: this issue aims to address tests for two methods: `isPaymentMethodRestrictedToLocation` and `togglePaymentMethodForCountry`. The test suite for the latter was added in #8909, potentially requiring this issue to focus only on `isPaymentMethodRestrictedToLocation`.
