### ISSUE TITLE
Test matrix failing with WooCommerce 8.2+ and PHP 7.3

### ISSUE THREAD

**Issue by c-shultz** [Automattic/woocommerce-payments#7392]
### Describe the bug
The GitHub Actions test matrix has 7.3 as the minimum version of PHP. This is causing test failures with WooCommerce beta, since WooCommerce 8.2 is about to be released on October 10th with the minimum PHP version bumped to 7.4.

This PR is temporary workaround: https://github.com/Automattic/woocommerce-payments/pull/7391 But the failures will start again after October 10th.

**Comment by jessy-p** [comment]
This issue impacts Release Process, Monitoring (including On-call process ownership), MC Tools, Dev Tools, CI/CD Pipeline, and Dependencies Management, so assigning to Harmony (based on team responsibilities Pc2DNy-3z-p2) @deepakpathania. Assigning as part of Gamma Triage process PcreKM-yM-p2.

**Comment by jbordonado** [comment]
Rest of the dependencies issues can be followed in #7451
