### ISSUE TITLE
Disputes: Add integration or e2e tests for disputed order notice

### ISSUE THREAD

**Issue by Jinksi** [Automattic/woocommerce-payments#7397]
We should increase our test coverage of the _disputed order notice → view dispute_ merchant flow via e2e or integration tests.

This is a critical flow for dispute resolution.

![Image](https://github.com/Automattic/woocommerce-payments/assets/3147296/afb45025-d6ae-4063-8622-6caa0b1695aa)

> [!note]
> A previous solution has been removed in #7493 since it broke e2e tests for WC 7.7.

**Comment by Jinksi** [comment]
Re-opening, since the previous solution has been removed in #7493 since it broke e2e tests for WC 7.7.

To resolve this, we need to determine a way to run certain tests on certain WC versions. We can then author a disputed order notice flow that will run only for WC 7.9+.

**Comment by haszari** [comment]
I'm curious if this is the only high-priority gap in our e2e coverage, or if this is a good example. 

If there are other important gaps in e2e coverage, we could track that separately (coverage tooling or a manual flow-based sheet). Or we could audit and add issues for each missing test (e.g. if it's < 5 instances).

**Comment by haszari** [comment]
Labelled as high priority as this flow is important: inform merchant that an order is disputed. We should have an automated test to confirm this flow is functioning correctly each release.
