### ISSUE TITLE
Add Jetpack DNA connection e2e test

### ISSUE THREAD

**Issue by allendav** [Automattic/woocommerce-payments#740]
Or propose a better way to ensure this critical happy path keeps working.

Related #539 

cc @DanReyLop  @vbelolapotkov

**Comment by deepakpathania** [comment]
Is this still relevant? If yes, could we add more details to the same for it to be picked up - ideally the expected flow to be tested. @vbelolapotkov @DanReyLop

**Comment by DanReyLop** [comment]
It *is* still relevant, but I don't think it's possible to write an e2e test for it.

The goal would be to test the WP.com connection flow, and then check that it's working correctly. For that, the test would need to:
- Start with a clean site, without WCPay configured.
- Go to the `Payments -> Connect` splash page and click on `Finish setup`.
- That would redirect the user to a page hosted on `wordpress.com`.
- For the WP.com connection flow to work, the site will need to be reached from the Internet (like using jurassic.tube, ngrok.io, etc).
- Once the connection flow is done, test that the communication between the WCPay client and the WCPay server works correctly (for example, by making a purchase or going to the `Payments -> Transactions` list).

**Comment by vbelolapotkov** [comment]
I think this is covered by manual testing with GlobalStep. So I'm fine with closing the issue.

**Comment by DanReyLop** [comment]
I agree, this is a flow that will be tested manually constantly. Closing.
