### ISSUE TITLE
[PO] Occasionally cannot select country

### ISSUE THREAD

**Issue by csmcneill** [Automattic/woocommerce-payments#7436]
### Describe the bug

Sometimes, when merchants luck into gradual signup / progressive onboarding, they are unable to select a country. The dropdown options do not appear; instead, a thin line appears in its place.

### To Reproduce

We have been unable to reproduce this so far.

### Actual behavior

When a merchant is affected by this issue, they are unable to onboard. They also cannot bypass the PO flow, which puts them into a state of limbo.

### Screenshots

![GgiQHy.png](https://github.com/Automattic/woocommerce-payments/assets/82999806/4faba05b-ea9c-4cb1-871a-28446f459015)

### Expected behavior

1. Countries are rendered without issue, allowing a merchant to onboard properly.
2. If a merchant faces an issue with the Woo portion of the PO flow, there is a definitive way to exit this flow and revert to the fully Stripe-owned flow (e.g., adding a filter, using a specific wp-admin URL).

### Additional context

6610367-zen
p1692653371292309-slack-C023E3QBKST
p1691738612910509-slack-C3NCP7ZJ6
p1691741924088819-slack-C03KTTK2YMA
7113333-zen

In my tests, I can set `_wcpay_feature_progressive_onboarding` to `0` and it will allow me to bypass PO and go through the standard, Stripe-owned onboarding flow. However, 6610367-zen was unable to find this in their options.php so it might not be a reliable workaround.

**Comment by csmcneill** [comment]
I forgot that https://github.com/Automattic/woocommerce-payments/issues/6981 was already created to tackle this. However, since that issue is closed and 7113333-zen is experiencing this issue with 6.5.1, I'm leaving this one open.

**Comment by ismaeldcom** [comment]
Hi @csmcneill! We've recently found an issue that could be causing this one. It was fixed in #7386 and will land in v6.6.

**Comment by csmcneill** [comment]
Thanks @ismaeldcom!

7129579-zen is the latest report of this issue—I've asked them and 7113333-zen to update to determine if this resolves the issue.

**Comment by daquinons** [comment]
The users haven't confirmed if the issue was addressed in the new version or not, but it should be addressed by #7386 

Closing it, please feel free to reopen if the issue persists.
