### ISSUE TITLE
Introduce product based filter to `WC_Payments_Payment_Request_Button_Handler::has_allowed_items_in_cart()`

### ISSUE THREAD

**Issue by peterwilsoncc** [Automattic/woocommerce-payments#7438]
### Description

Introduce a filter to allow developers to modify whether a product allows the express pay options (Google and Apple Pay) in the cart.

```php
/**
 * Filter whether product supports Payment Request Button on cart page.
 *
 * @param boolean $is_supported Whether product supports Payment Request Button on cart page.
 * @param object  $_product     Product object.
 */
apply_filters( 'wcpay_payment_request_is_cart_supported', true, $_product )
```

This is intended as a sibling filter to the existing `wcpay_payment_request_is_product_supported` filter.

The purpose of the new filter is to allow developers to specify whether a product supports the express payment options based on attributes other than type.

An example is bookings products generally support the express pay options in the cart and at checkout, but for bookings requiring confirmation the express pay options are not supported as payment is not processed at the time.

Introducing a filter allows extenders to apply more complex rules without requiring compatibility shims in Payments.

**Possible alternative approaches:**

* Use the existing `woocommerce_cart_item_product` by allowing developers to return a non-object to indicate the product is not supported (ideally the developer would return false) -- this would require changes to the has_subscriptions method
* pass the product as a parameter to the filter `wcpay_payment_request_supported_types`

### Acceptance criteria

* [Supported product types](https://github.com/peterwilsoncc/woocommerce-payments/blob/efd9c5a5a0068972eab6827967eac6c8be4ccf6e/includes/class-wc-payments-payment-request-button-handler.php#L552-L568) takes priority over the new filter.
* Filter only runs for supported product types

### Testing instructions

1. Enable express payment options (Google and Apple Pay)
   * testing Apple Pay requires you use the Safari browser
   * testing Google Pay requires you use the Chrome browser
2. Install WooCommerce Bookings
3. Create a bookable product that requires confirmation
4. Order the item by clicking "check availability" to place it in your cart
5. Click through to the cart
6. The express pay option should not be displayed
7. Click through to checkout
8. The express pay option should not be displayed
9. Empty the cart
10. Create a bookable product that does not require confirmation
11. Add the item to your cart
12. Click through to the cart
13. The express pay option should be displayed
14. Click through to checkout
15. The express pay option should be displayed

### Additional context

https://github.com/woocommerce/woocommerce-bookings/issues/3619

**Comment by jessy-p** [comment]
This issue impacts International Expansion, In-Person Payments, Local Payment Methods, and Additional Payment Methods (including Apple Pay / Google Pay), so assigning to Fusion (based on team responsibilities Pc2DNy-3z-p2) @anu-rock. Assigning as part of Gamma Triage process PcreKM-yM-p2.
