### ISSUE TITLE
Date filters for Authorization Reporting API

### ISSUE THREAD

**Issue by jessy-p** [Automattic/woocommerce-payments#7445]
### Describe the bug
Date filters in the Authorization API need to be re-looked at to come up with an appropriate solution
Currently, we have `date_before`, `date_after` and `date_between`. After the issue with date filters is resolved, make sure to update documentation on `docs/rest-api/source/includes/wp-api-v3/reports.md` to include missing date filters for authorizations API endpoint.

- Based on https://github.com/Automattic/woocommerce-payments/pull/7066#issuecomment-1730831577
- Related to #7066 

### To Reproduce
https://github.com/Automattic/woocommerce-payments/pull/7066#issuecomment-1713727346

### Actual behavior
Unexpected & inconsistent behavior of date filters across the Authorizations reports API

### Expected behavior

- The date filters should behave consistently and be useful to merchants.
- Make sure to update the documentation for reports API and include missing date filters (`docs/rest-api/source/includes/wp-api-v3/reports.md`)

**Comment by jessy-p** [comment]
cc: @souravdebnath1986 Created a new issue to relook at the filters.

**Comment by jessy-p** [comment]
Assigning to @dpaun1985 as it is related to extensibility

**Comment by zmaglica** [comment]
EDIT: The date filters for transactions API work fine. I just tested them. I will update the issue.
