### ISSUE TITLE
If Afterpay/Clearpay rejects the merchant, "More information needed" still shows in Payments > Settings

### ISSUE THREAD

**Issue by csmcneill** [Automattic/woocommerce-payments#7449]
### Describe the bug
When a WCPay merchant is unable to offer Afterpay/Clearpay due to a rejected status like `rejected.unsupported_business`, the chip will read `More information needed`. 

If they follow the instructions outlined in our docs [here](https://woocommerce.com/document/woopayments/payment-methods/buy-now-pay-later/#contact-support), they will not be able to provide any additional information.

### To Reproduce

I have no idea how to reproduce. I suspect that we can...

1. Create a WCPay account.
2. Ask Stripe to reject _just_ Afterpay/Clearpay.
3. Navigate to Payments > Settings.
4. See the `More information needed` chip.

### Actual behavior

If a merchant cannot use Afterpay/Clearpay due to rejection, they are still asked to provide more information—but they cannot provide that information as expected.

### Screenshots

![Markup on 2023-10-10 at 19:13:23](https://github.com/Automattic/woocommerce-payments/assets/82999806/6ae89041-bd92-4559-ad73-7e32bcc85d46)

![Markup on 2023-10-10 at 19:15:54](https://github.com/Automattic/woocommerce-payments/assets/82999806/37ce478d-5a73-41ef-89b8-ca46afa32236)

Event log for `evt_1NsCi4Fsnquk42sRqjqklfUX`:

```
{
  "object": {
    "id": ["afterpay_clearpay_payments"]([REDACTED]),
    "object": "capability",
    "account": "[REDACTED]",
    "future_requirements": {
      "alternatives": [
      ],
      "current_deadline": null,
      "currently_due": [
      ],
      "disabled_reason": null,
      "errors": [
      ],
      "eventually_due": [
      ],
      "past_due": [
      ],
      "pending_verification": [
      ]
    },
    "requested": true,
    "requested_at": 1695054795,
    "requirements": {
      "alternatives": [
      ],
      "current_deadline": null,
      "currently_due": [
      ],
      "disabled_reason": "rejected.unsupported_business",
      "errors": [
      ],
      "eventually_due": [
      ],
      "past_due": [
      ],
      "pending_verification": [
      ]
    },
    "status": "inactive"
  },
  "previous_attributes": {
    "requirements": {
      "disabled_reason": null
    },
    "status": "active"
  }
}
```

### Expected behavior

We should likely treat this like rejections for other APMs, like P24, and render a chip that directs the merchant to contact support.

### Additional context

7123991-zen

**Comment by jessy-p** [comment]
@kalessil I believe Pulsar would be looking into this?

**Comment by csmcneill** [comment]
I was able to reproduce this with one of my "live" test accounts that regularly gets caught by Stripe's risk workflows. 

`acct_1LhhVSFk5Ng3VVfB` is rejected by Affirm (`rejected.unsupported_business`) and I am unable to provide more information, even though I'm prompted to via wp-admin.

I think a shortcut to rejection here is to onboard an account with an MCC that is not supported by Affirm.

**Comment by mgascam** [comment]
The issue seems related to the fact that the status of the capability will be `inactive` for both a rejected account and
an account that requires more information. We need to look further into the reason why the capability is inactive to determine if we show the 'More Information Needed' or 'Contact Support' chip. Currently, we [rely only on the `status` of the capability.](https://github.com/Automattic/woocommerce-payments/blob/4ea6a98e0872560a10bdadf85fe7cdb2702f6e26/client/payment-methods/index.js#L289)

To achieve that, we could look into the `disabled_reason` key that is part of the capability hash that comes from Stripe:
```javascript
"requirements": {
        "alternatives": [],
        "current_deadline": null,
        "currently_due": [
          "business_profile.support_email",
          "business_profile.support_phone"
        ],
        "disabled_reason": "requirements.fields_needed",
        "errors": [],
        "eventually_due": [
          "business_profile.support_email",
          "business_profile.support_phone"
        ],
        "past_due": [
          "business_profile.support_email",
          "business_profile.support_phone"
        ],
        "pending_verification": []
      },

``` 

Using the content of the `disabled_reason` key we can tell why the account is inactive and react accordingly.

**Comment by kalessil** [comment]
Thanks @mgascam ! It looks like we need to start passing requirements into components and enhancing notices logic. Is this issue something @KarlisJ could tackle (design references can be found in https://github.com/Automattic/woocommerce-payments/pull/7406)?

**Comment by KarlisJ** [comment]
I'll look into this today

**Comment by KarlisJ** [comment]
@csmcneill 
>  treat this like rejections for other APMs, like P24

Could you please provide an example of such a treatment? Looking at the code, I can't find any references to us treating any PM as "rejected"

**Comment by csmcneill** [comment]
Hey @KarlisJ! There may not be a specific handling for rejected accounts, but this is what a merchant sees if they are unable to enable P24:

![image](https://github.com/Automattic/woocommerce-payments/assets/82999806/2e456454-bbf2-4bc4-acd1-621e888dcb56)

Some more details on how we handle this in Happiness can be found in PbTz5e-20i-p2#disabled-p24

**Comment by KarlisJ** [comment]
@csmcneill This behavior seems weird to me. Merchant can still try to enable the checkbox. Shouldn't it be disabled?

**Comment by KarlisJ** [comment]
@csmcneill You can ignore my previous comment. 

That screenshot is outdated. Here's how that case looks now (using Klarna but would be the same for P24)
![image](https://github.com/Automattic/woocommerce-payments/assets/24650518/d7248933-7747-4599-b33f-85ec8f4342eb)
Note that I've hovered the `!` to see the tooltip content. The link in tooltip points to https://woo.com/document/woopayments/payment-methods/buy-now-pay-later/#contact-support for BNPLs and https://woocommerce.com/document/woopayments/payment-methods/additional-payment-methods/#method-cant-be-enabled for other PMs.

I'll copy some DM text from @mgascam 
> When working on Affirm and Afterpay we changed the content of the badge to More Information Needed but there was an error there because we were not accounting the rejected status. With your PR we will have a new rejected status, so we handle all the cases:
> - More information needed-> Stripe status is inactive and we check for disabled reason requirements.fields_missing- 
> - Rejected-> Stripe status is inactive and we check for disabled reason rejected.*

In the linked PR, we've implemented the `rejected` status like this
![image](https://github.com/Automattic/woocommerce-payments/assets/24650518/79d2b00f-e957-4c86-83ac-c1b5fb83861c)

But I'm not entirely sure where exactly should the link in tooltip point to in the docs?

**Comment by csmcneill** [comment]
> I'm not entirely sure where exactly should the link in tooltip point to in the docs?

If we just want to link to the support contact page, we can link to https://woo.com/my-account/contact-support/

However, if we want to link to the prohibited products/businesses section of the BNPL docs, that can be found at https://woo.com/document/woopayments/payment-methods/buy-now-pay-later/#prohibited
