### ISSUE TITLE
Deleting a Payment method turns Subscriptions into manual renewal

### ISSUE THREAD

**Issue by leonardola** [Automattic/woocommerce-payments#7457]
### Describe the bug
This bug was found when trying to reproduce #3235. 

### To Reproduce
- Place a subscription order using card `5555555555554444`
- Place another subscription using card `4242424242424242`
- Go to My Account > Payment Methods
- Delete the card `4242424242424242`
- Notice the message says the subscriptions got updated to use the deleted card instead of using the other one
- Go to My Account > Subscriptions
- Notice the subscription using `4242424242424242` has no card attatched anymore

### Screenshots
<img width="1131" alt="Screenshot 2023-10-11 at 11 39 33 AM" src="https://github.com/Automattic/woocommerce-payments/assets/6342964/32c621bb-286d-415d-a8cc-74bc15af1cb0">

**Comment by jessy-p** [comment]
This issue impacts WC Payments Subscriptions, so assigning to Quark (based on team responsibilities Pc2DNy-3z-p2) @diego373. Assigning as part of Gamma Triage process PcreKM-yM-p2.
