### ISSUE TITLE
Can't load the Documents screen

### ISSUE THREAD

**Issue by WillBrubaker** [Automattic/woocommerce-payments#7461]
### Describe the bug

I'm starting to see some users reporting that they are unable to access the Documents screen. They get an error that says "wpApiSettings is not defined."

I haven't been able to reproduce this, but maybe that's because I don't actually have any documents to view. 

### To Reproduce

1. Attempt to open the Documents screen

### Actual behavior

Can't open the documents screen.

### Screenshots

![NTs82Y.jpg](https://github.com/Automattic/woocommerce-payments/assets/2127470/ae1026b9-f1e9-46c6-80e0-a4be9695883f)
### Expected behavior

The Documents screen loads

### Desktop (please complete the following information):

* OS: [e.g. iOS]
* Browser [e.g. chrome, safari]
* Version [e.g. 22]

### Smartphone (please complete the following information):

* Device: [e.g. iPhone6]
* OS: [e.g. iOS8.1]
* Browser [e.g. stock browser, safari]
* Version [e.g. 22]

### Additional context

https://wordpress.org/support/topic/cant-view-on-documents-because-of-this-error/
7151120-zen
7152173-zen

**Comment by thuautp** [comment]
Just to add to this report, in 7152173-zen, there's a browser console error on the Documents page: 
<img width="1697" alt="Screenshot on 2023-10-12 at 11-26-50" src="https://github.com/Automattic/woocommerce-payments/assets/13119409/0653b3c3-7fc8-4bdc-b8fe-1753a1d13f78">

**Comment by thuautp** [comment]
also reported in 7163146-zen

**Comment by jessepearson** [comment]
It looks like WooCommerce core 8.2.0 removed some JS dependencies that we relied on to build the urls for the documents, which is what is causing the error. There might be a simple fix at this time, but I am not sure if it is the right fix. If a merchant needs to have access to their documents immediately, they can roll back to WooCommerce 8.1.1.

p1697206889345649-slack-CGGCLBN58

**Comment by francoishvz** [comment]
7163949-zen

**Comment by francoishvz** [comment]
7174438-zen

**Comment by Prin-S** [comment]
Reported in 7182895-zd-a8c

**Comment by Prin-S** [comment]
One more 7183279-zd-a8c

**Comment by jessepearson** [comment]
#7484 with the fix has been added to the merge queue. The next release that will include this will be on November 1.

**Comment by jessepearson** [comment]
There is actually going to be a patch release today for some other fixes, and I was able to include this fix in there. It's going to be in 6.6.1.

**Comment by jtobiesen** [comment]
7171228-zd-a8c
