### ISSUE TITLE
Transaction Dispute Details tracks events: remove redundant `on_page` and `dispute_status` event props

### ISSUE THREAD

**Issue by Jinksi** [Automattic/woocommerce-payments#7474]
There are some redundant tracks event props related to the dispute details on the transaction details screen.

If we confirm they are redundant, we should remove them to clarify our event definitions.

Discovered while registering tracks events: https://github.com/Automattic/tracks-events-registration/issues/1883.

* `wcadmin_wcpay_dispute_accept_click` and `wcadmin_wcpay_dispute_accept_modal_view`
  * `dispute_status` is redundant – these can only fire for disputes with `needs_response` status
  * `on_page` is redundant – these are new events that only render on the Transaction Details screen.
* `wcpay_dispute_inquiry_refund_click` and `wcpay_dispute_inquiry_refund_modal_view`
  * `dispute_status` is redundant – these can only fire for disputes with `warning_needs_response` status
  * `on_page` is redundant – these are new events that only render on the Transaction Details

**Comment by brucealdridge** [comment]
There is little benefit to tidying these up. 🎣
