### ISSUE TITLE
Transaction Dispute Details tracks events: rename `_clicked` events to use present tense `_click`

### ISSUE THREAD

**Issue by Jinksi** [Automattic/woocommerce-payments#7475]
We have two tracks events related to the Transaction Dispute Details UI that aren't named consistent with the naming conventions. They use the past-tense `clicked` rather than present-tense `click`.

We should correct these to keep our event naming consistent with the event naming guidelines. (See internal doc PCYsg-4S2-p2)

1. `wcpay_dispute_challenge_clicked` is an existing/historical event, so we should consider any negative impacts of changing it, or ensure this rename is documented.
2. `wcpay_view_submitted_evidence_clicked` is a new event, so we can safely correct it now.

Notes from related slack discussion: p1697160049734799-slack-C03LA109BKM
* if these events aren’t being used in a funnel right now then feel free to change.
* historical data is probably not a particular concern (secondary use case for tracks).
* if you do rename, it’s a good idea to P2 what changed, and then if somebody is impacted (now or in future) they can figure it out (and or ask us not to rename stuff)
* Helix owns these events.
* registration metadata can give hints too – e.g. `this event is deprecated, we renamed, see _click`

Discovered while registering tracks events in https://github.com/Automattic/tracks-events-registration/issues/1883.

**Comment by haszari** [comment]
I think this is unlikely to get actioned any time soon, as we have other priorities and it would take effort to rename existing events.

However, when we next work on a disputes-related project, that might be a good opportunity to make these events consistent and best-practice. Added `projects` label.

**Comment by haszari** [comment]
Closing, I don't see this happening any time soon and there's zero cost/impact (so no problem not doing this).
