### ISSUE TITLE
Pre-filling business URL on staging sites leads to staging site URL as statement descriptor

### ISSUE THREAD

**Issue by thenbrent** [Automattic/woocommerce-payments#749]
PR #605 began pre-filling the business URL on an account based on the site's home URL.

### Expected behaviour

By pre-filling the business URL, we hoped to guide merchants away from accidentally ending up with the platform's default statement descriptor server/issues/220; as well as make their onboarding experience faster.

### Actual behaviour

Since #605 shipped, I've noticed a number of accounts and payments with odd URLs being used for their statement descriptor, even when the account has a valid business URL.

Based on 3075532-zen and other accounts, I believe some merchants are on-boarding while on their staging site, then going live, which leads to the staging site's URL being used as a the statement descriptor.

This issue is compounded by the fact that:

* there is no indication that the business URL set during onboarding is used as the statement descriptor.
* the statement descriptor can not currently be changed by the merchant (which will change once #407 is implemented).

### Proposed solution

I'm not sure how we resolve this issue. #407 will give merchants a way to update the statement descriptor, but given the important role the statement descriptor plays in avoiding chargebacks, we may also want to proactively notify the merchant of the issue if we see their site URL change, perhaps as part of a safe mode or staging mode (see paJDYF-IP-p2).

**Comment by vbelolapotkov** [comment]
> the statement descriptor can not currently be changed by the merchant

This is not the case anymore. 

> there is no indication that the business URL set during onboarding is used as the statement descriptor.

That's an interesting question, though. I'll talk to product team to see if we can do anything here. Maybe we can alert a merchant once if their descriptor doesn't match site URL, but I doubt this is an urgent problem.

**Comment by vladolaru** [comment]
Closing this as things have changed considerably, and merchants have clear ways to configure their statement descriptor. 

Overall guidance on setting up payment methods and settings (including statement descriptor) should be part of larger product initiatives.
