### ISSUE TITLE
Small UI fixes for Transaction details: Add separator on balance breakdown line at top & remove redundant deadline urgency string

### ISSUE THREAD

**Issue by nikivias** [Automattic/woocommerce-payments#7504]
### Description
A couple of follow-ups to ensure the Dispute modal follows the Figma design

### Acceptance criteria

1. Add a small separator line between converted currency and the next line item.

Currently the converted currency is right next to the balance breakdown items, and it is confusing trying to make out their relation to one another. We are adding this separation line after the converted currency so it doesn't appear as part of an equation, and visually becomes more connected to the main currency

![Screenshot 2023-10-16 at 10 16 38 PM](https://github.com/Automattic/woocommerce-payments/assets/99638528/1307293c-b059-4900-a8ef-aa00be738646)

2. For the 'Needs response' stage for Inquiries and disputes, please remove the 2nd appearance of the [X days left] string, which is in the last step of 'Steps to resolve'.

We have sufficient urgent signals in the modal such as the colored pill and banner, as well the 1st appearance of the string. So 2nd appearance has become redundant.

<img width="1088" alt="272725609-eed3158e-a1ad-458b-80a0-f3d29172c484" src="https://github.com/Automattic/woocommerce-payments/assets/99638528/8d6c6f2f-47ef-4ec9-86bb-957331a7ed50">

![Screenshot 2023-10-16 at 10 20 36 PM](https://github.com/Automattic/woocommerce-payments/assets/99638528/58d7c6e2-b206-4f5e-8bd2-04a3564698f1)

### Designs
[See on Figma](https://www.figma.com/file/RiEQmaKRI7u9USAI3lyZz0VX/Dispute-Flows?type=design&node-id=7733%3A81755&mode=dev&t=Gg0FaIJBj38ntmlx-1)

**Comment by jessy-p** [comment]
This issue impacts Deposits, Disputes, Reporting, so assigning to Helix (based on team responsibilities Pc2DNy-3z-p2) @haszari. Assigning as part of Gamma Triage process PcreKM-yM-p2.

**Comment by haszari** [comment]
Thanks @nikkivias and @jessy-p ! We'll triage and handle as maintenance.

**Comment by haszari** [comment]
@nikkivias could you add some more info to the description about each problem (there are two)? Focusing on the problem(s) helps us to better understand and prioritise appropriately. Thank you 🤩

**Comment by nikivias** [comment]
Thank you, just updated the description to include more information about each problem

**Comment by souravdebnath1986** [comment]
I think there is opportunity to make this headline clearer. 

This is the headline of a real dispute - 

![Image](https://github.com/Automattic/woocommerce-payments/assets/112917711/5207c216-ceb2-4ec0-82c6-80bbf1dce441)

- it calls out the merchant currency i.e. USD multiple times. As per @nikkivias design, this only needs to be mentioned once in the converted currency amount. 
- for this transaction, when the dispute arrived in presentment currency i.e. buyer currency or 95 EUR, the fx rate had moved. So a different fx rate was applied to convert to the amount that was deducted **Note:** that the converted currency amount and deducted amount are different. How can we make it clearer eg: like through a tooltip that deducted amount can be different from converted transaction amount in merchant currency ? 
- `NET` signifies the net income of the merchant from the transaction so far. Income is sales minus fees. How do we make this clearer ? 

@rogermattic fyi for your inputs.

**Comment by naman03malhotra** [comment]
>I think there is opportunity to make this headline clearer.

@souravdebnath1986 I agree here, I think we can definitely improve that, do you mind opening a different issue for it? Since now this has been closed.

**Comment by rogermattic** [comment]
Hey @souravdebnath1986  and @naman03malhotra 
This is a good one to improve, I agree! Since I've been working on some improvements to the payment details heading within the improving fees display scope of work, I can include this issue in the scope as well :) 
 
 Please, would you mind pinging me on the new issue when it's created? And I'll provide some designs! Thanks!
