### ISSUE TITLE
Afterpay checkout fails when shipping information is missing.

### ISSUE THREAD

**Issue by mgascam** [Automattic/woocommerce-payments#7509]
### Describe the bug

Afterpay checkout fails when shipping information is missing in the order.

### To Reproduce

1. You'll need to remove the shipping fields from the checkout form. One way to accomplish it is by disabling shipping in `WooCommerce > Settings > General > Shipping location(s)`
2. As a shopper add product(s) for a value greater than 50 USD and proceed to checkout
3. Fill the form, select Afterpay as payment method and place the order

### Actual behavior

The checkout fails and there's an error shown to the shopper:

<img width="833" alt="Screenshot 2023-10-18 at 20 56 05" src="https://github.com/Automattic/woocommerce-payments/assets/1553182/7a9447cf-b545-4be4-ada6-24f5db98745a">

### Expected behavior

Checkout does not fail with Afterpay

### Additional context

The error seems to originate in this line, when there's missing shipping information in the order.

https://github.com/Automattic/woocommerce-payments/blob/359ea902ca5b5c88952ade7d2310345d620d9854/includes/payment-methods/class-upe-split-payment-gateway.php#L565

We could fallback to the address in the billing details in this case.

**Comment by raifd** [comment]
7113829-zen
