### ISSUE TITLE
Jetpack Connection: Even if the site is already fully connected to Jetpack, go through the authorization flow

### ISSUE THREAD

**Issue by DanReyLop** [Automattic/woocommerce-payments#752]
See this comment for the updated design: paJDYF-Ei-p2#comment-2819

To make sure that the user is connecting to WCPay/Jetpack with the intended WP.com account, we'll show the Jetpack "Authorize" screen even if the site is already fully connected.

Note: We should check what happens if the user is currently logged-in with a different WP.com account, and/or with another Admin account in the local site.

https://github.com/Automattic/woocommerce-payments/pull/711 has been already opened to address this, but it's pending review and a new version of `jetpack-connection` to be released.

**Comment by htdat** [comment]
Moving this issue to `Ready for priotization`. I think we will need to double check it again and see if this is still an issue before moving forward.

**Comment by naman03malhotra** [comment]
@zmaglica can you please test it as part of porter duties, not urgent but whenever you get some bandwidth.

**Comment by RadoslavGeorgiev** [comment]
Moving back to _Triage in progress_ because it needs to be tested before we can prioritize it.

**Comment by dwainm** [comment]
FYI, I've closed the PR as it will probably need a complete rework due to all the changes that have gone into the plugin since then.

**Comment by dwainm** [comment]
Closing out this issue as per the p2 link, the discussions are no longer a valid reflection of the direction we're currently taking.
