### ISSUE TITLE
WooPay button erroneously renders on external product pages

### ISSUE THREAD

**Issue by csmcneill** [Automattic/woocommerce-payments#7521]
### Describe the bug
If a site has an `External/Affiliate product` available, the WooPay button will render on that product page—even though that item cannot be purchased on the site itself.

Selecting the WooPay button yields a console error...

```
react-dom.min.js?ver=18:1 Uncaught TypeError: Cannot read properties of null (reading 'value')
    at Object.getProductData [as current] (woopay-express-button.js?ver=6.6.0:2:149611)
    at M.current (woopay-express-button.js?ver=6.6.0:2:152104)
    at onClick (woopay-express-button.js?ver=6.6.0:2:153845)
    at Object.Ga (react-dom.min.js?ver=18:1:105731)
    at B (react-dom.min.js?ver=18:1:10495)
    at W (react-dom.min.js?ver=18:1:10550)
    at qe (react-dom.min.js?ver=18:1:23312)
    at Ke (react-dom.min.js?ver=18:1:23727)
    at react-dom.min.js?ver=18:1:29088
    at pl (react-dom.min.js?ver=18:1:85869)
```

...and the customer is never directed to the hosted checkout flow on `pay.woo.com`.

Other EPMs do not render on the product pages for external products because these purchases by their very nature happen on a different site (e.g., the external product included in the [sample_products.csv](https://github.com/Automattic/woocommerce-payments/files/13047721/sample_products.csv) included in Woo core directs customers to `https://mercantile.wordpress.org/product/wordpress-pennant/`).

### To Reproduce

1. Enable WooPay on an eligible account.
2. Ensure that WooPay is enabled for product pages.
3. Create [an external/affiliate product](https://woocommerce.com/document/managing-products/#:~:text=External%C2%A0or%C2%A0Affiliate%C2%A0%E2%80%93%20one%20that%20you%20list%20and%20describe%20on%20your%20website%20but%20is%20sold%20elsewhere.), assign a price, and publish it.
4. Navigate to the product page for the product created in step 3.
5. Note that the WooPay button renders.
6. Select the WooPay button.
7. Note that you are not redirected to `pay.woo.com`.
8. Check the console for the error.

### Actual behavior
The WooPay button renders on external product pages. When a customer selects it, they get a spinning animation as though they are trying to be redirected to `pay.woo.com`, but that never happens.

### Screenshots

![Markup on 2023-10-19 at 15:48:58](https://github.com/Automattic/woocommerce-payments/assets/82999806/fe398fa7-d1d9-4ddb-ad45-6949744293f4)

![Markup on 2023-10-19 at 15:49:12](https://github.com/Automattic/woocommerce-payments/assets/82999806/2d06b68a-b828-49be-8d90-e504206a586c)

### Expected behavior

The WooPay button doesn't render on external/affiliate products.

### Additional context

p1697747745623979-slack-C055H555X37

**Comment by francoishvz** [comment]
7203133-zd-a8c

**Comment by jessy-p** [comment]
This issue impacts WooPay - Express checkout buttons, checkout UI, so assigning to Heisenberg (based on team responsibilities Pc2DNy-3z-p2) @frosso. Assigning as part of Gamma Triage process PcreKM-yM-p2.
