### ISSUE TITLE
Fraud & risk radio selectors aren't matching the wp-admin theme

### ISSUE THREAD

**Issue by bradyv** [Automattic/woocommerce-payments#7539]
### Describe the bug
The radio selectors for fraud & risk tools are using a hard coded hex `#3582c4` for their selected state instead of matching the user selected wp-admin theme.

### To Reproduce
1. Go to Payments -> Settings
2. Scroll down to `Fraud protection`

Here's a screenshot from two different test sites using different wp-admin themes.
<img width="2430" alt="Screenshot 2023-10-23 at 19 11 11" src="https://github.com/Automattic/woocommerce-payments/assets/889872/77847c07-ed48-42ff-beec-98f5735d9d7b">

### Expected behavior
The radio fill colour should match the wp-admin theme. We can do this by changing the hard coded hex value to `var(--wp-admin-theme-color)`

**Comment by jessy-p** [comment]
This issue impacts Risk & Fraud, Client Facing Risk Tools, Multi-Currency, Taxes, General purpose communications and communication tools., so assigning to Sigma (based on team responsibilities Pc2DNy-3z-p2) @tpaksu. Assigning as part of Gamma Triage process PcreKM-yM-p2.

**Comment by jessy-p** [comment]
This issue impacts Risk & Fraud, Client Facing Risk Tools, Multi-Currency, Taxes, General purpose communications and communication tools., so assigning to Sigma (based on team responsibilities Pc2DNy-3z-p2) @tpaksu. Assigning as part of Gamma Triage process PcreKM-yM-p2.
