### ISSUE TITLE
Incorporate guided setup for Progressive Onboarding

### ISSUE THREAD

**Issue by csmcneill** [Automattic/woocommerce-payments#7543]
### Description
During the Progressive Onboarding audit call, it was mentioned by Keala that it would be important to introduce a guided process for newly onboarded merchants.

This could look similar to the guided process that is currently used with the FRT:

![image](https://github.com/Automattic/woocommerce-payments/assets/82999806/c12ba060-a46d-4678-8cc4-e340ab20533f)

It was also noted that we'd want to direct the merchants to **Payments > Settings** after onboarding is complete. This will provide them with more information about what is possible with WooPayments, like enabling APMs, enabling test mode, configuring EPMs, etc.

### Acceptance criteria

* First requirement
* Second requirement
* Third requirement
* etc.

### Testing instructions

1. Go to '…'
2. Click on '…'
3. Scroll down to '…'
4. Observe expected behaviour

### Additional context

See pbUcTB-3yp-p2 for full details of the audit call.

**Comment by dmallory42** [comment]
@daquinons I think this would be a good issue for us to tackle when we can as is it addresses a few gaps between onboarding and helping the merchant know what to do next. We'd likely need design and to estimate based on the size of the work. :)

**Comment by daquinons** [comment]
Thank you! I think this is very interesting.

@elizaan36 I've added a needs design label, could you take a look when you have availability? 🙏

Apart from the guided setup similar to what we did in the fraud tools, also for how to incorporate in Settings the ability to complete KYC in PO accounts.

**Comment by elizaan36** [comment]
This is a cool idea, and would bridge the gap between the store setup, payments onboarding, and other required payments setup. Do we have data on usage of the fraud tools guide to determine potential success of this one?

**Comment by daquinons** [comment]
Not sure about that :) @dwainm @tpaksu do we have any data on that? ^

**Comment by tpaksu** [comment]
Yes we do @daquinons, the tour component has two tracks available, the count of people who walked through all, and the count of who abandoned it in an early step. You can find the track links in pcqRLn-1Gh-p2.

**Comment by elizaan36** [comment]
Looks like from the data shared in that p2 taking a random day in July there's a ~24% clickthrough rate on the fraud tools guide until after August when all the numbers drop off. (It looks like the tour may have been removed then)

I think there are ways we can explore the problem space to improve the "guided-ness" of onboarding without jumping directly to a solution of creating a popup tooltip guide immediately. It may be a matter of providing clearer copy and guidance before and after KYC but will think more about this.

**Comment by anu-rock** [comment]
@timmy5685 @vladolaru @elizaan36 Nooby question - based on recent improvements in MOX, is the idea for a guided progressive onboarding still relevant? If yes, I'm curious how we should prioritize it.

**Comment by elizaan36** [comment]
Great question. Looking into the problem to solve here, I'd be curious if we're seeing an issue with merchant discovery,  understanding, and usage of Progressive onboarding. Or if the request is more for awareness/promotion of the feature?

I still feel strongly that guided tours are a band aid to mask UI deficiencies. If it's a real problem that merchants are facing I still think it's worth an exploration "How to provide more guidance for Progressive Onboarding after connection". Currently we have the system of task lists so I'd be curious what engagement those are seeing as well.

**Comment by timmy5685** [comment]
@anu-rock - I agree with @elizaan36 here and I don't believe this is a specific issue we are dealing with. Also - I don't see how this would be specific to Progressive onboarding vs overall onboarding. @csmcneill - do you have any insight on that or is it just because it came up during a call about PO?

That aside - we will be kicking off our next round of onboarding improvements this quarter and I think we should tackle exploring this as part of the overall review. I'm good to close this if everyone is in agreement and open a new one if we need it coming out of that work.

**Comment by anu-rock** [comment]
@timmy5685 Yep, closing this does make sense based on your and Elizabeth's comments. No objection from my end.

We'll perhaps wait a bit more to hear what @csmcneill thinks?

**Comment by csmcneill** [comment]
Sorry friends! I was out for a week and I am still going through my email backlog 😅 

This enhancement spun up from discussion during an audit call focused on progressive onboarding (pbUcTB-3yp-p2), but I'll close it — especially in light of Elizabeth's comments :)

**Comment by csmcneill** [comment]
Sorry friends! I was out for a week and I am still going through my email backlog 😅

This enhancement spun up from discussion during an audit call focused on progressive onboarding (pbUcTB-3yp-p2), but I'll close it — especially in light of Elizabeth's comments 😄
