### ISSUE TITLE
Progressive Onboarding overlay appears if an account has added deposit details but isn't fully verified

### ISSUE THREAD

**Issue by csmcneill** [Automattic/woocommerce-payments#7544]
### Describe the bug

When a merchant onboards via PO and add their payment details to receive deposits, if there are other pending requirements (e.g., verifying identification documentation), this can still make the PO overlay appear (that has the `Enable payments only` option) as though the merchant has not added any deposit details.

### To Reproduce

1. Enable PO on a test site.
2. Onboard with a US account and do not add deposit details immediately.
3. Once directed back to wp-admin, add deposit details via the prompts in wp-admin.
4. Add a deposit account, but do not complete a requirement (e.g., identity documentation).
5. When you're directed back to wp-admin, you will see the Progressive Onboarding overlay.

### Actual behavior
A merchant who onboards via PO and later adds a deposit account can run into an experience in wp-admin that appears as though they _haven't_ added a deposit account.

Other pending requirements (e.g., identity documentation) can still prompt the merchant to add a deposit account, even if one is already added.

### Expected behavior
Non-bank-related pending requirements shouldn't prompt a merchant who onboarded via PO to add a bank account.

### Additional context

See pbUcTB-3yp-p2 for full details of the PO audit.

**Comment by jessy-p** [comment]
This issue impacts Onboarding, Account management, so assigning to Moltres (based on team responsibilities Pc2DNy-3z-p2) @daquinons. Assigning as part of Gamma Triage process PcreKM-yM-p2.

**Comment by daquinons** [comment]
Thank you.

Note on the issue: we need to discern better if the pending requirements are for PO payout enablement (then we need to ask for setting up a deposits account) or a different requirement (then the generic message for pending requirements in Non-PO accounts would work).

**Comment by dmallory42** [comment]
Noting that this will also be closed by the fix described in #7683.
