### ISSUE TITLE
Generic error message is thrown while checking out

### ISSUE THREAD

**Issue by naman03malhotra** [Automattic/woocommerce-payments#7574]
### Describe the bug
I came across this error while testing https://github.com/Automattic/woocommerce-payments/issues/6946

A generic error message is thrown during checkout instead of amount too small error.

<img width="830" alt="image" src="https://github.com/Automattic/woocommerce-payments/assets/15019298/b981336e-72d8-4a7d-80c5-94776f8338c9">

### To Reproduce

1. Set your store currency as `ugx`.
2. Try checking out with a small amount, say 10 `ugx`.
3. Trying checking out.

### Expected behavior

A clear error message should be shown describing the behavior.

**Comment by htdat** [comment]
May double check after this issue #6946 is fixed.

**Comment by zmaglica** [comment]
I have tested this, and the correct error is shown (that amount is too small). This error is fixed with the issue that was liked by @htdat
