### ISSUE TITLE
PO success modal needs a new iteration

### ISSUE THREAD

**Issue by daquinons** [Automattic/woocommerce-payments#7579]
### Describe the bug
> The CTAs aren’t clear enough to the new user. They may be asking, what does it mean to Enable Payments only? Update the CTAs for better clarity.

> The modal feels too salesy for the user who’s already invested. Why do they need to be sold on this step? For something that’s meant to be quick and easy, there’s too much reading required. Simplify the copy to be more straightforward.

More details paJDYF-bax-p2

**Comment by daquinons** [comment]
@elizaan36 Created the issues coming from the Design Leads review, please help us with the specific suggestions for improvements! 🙏

**Comment by daquinons** [comment]
Some additional comments to take into consideration:

> - It isn’t as clear as it could be what “set up payments and deposits” leads to (add your bank to enable deposits is likely more clear).
> - Setting up payments actually makes logical sense, but this isn’t where the user is navigated and configuring payment options isn’t possible till the step to add a bank account is completed.
> - The “enable payments only” closes the window and doesn’t really guide the user in what to do next… this seems like (a) a bit of a false choice, and (b) perhaps a missed opportunity to progress the user to more meaningful and intuitive actions in their activation journey.
>

**Comment by vladolaru** [comment]
The initial design proposal for the PO modal is here: paJDYF-bGl-p2
