### ISSUE TITLE
WooPay flow for Pay for Order page isn't working properly

### ISSUE THREAD

**Issue by elazzabi** [Automattic/woocommerce-payments#7584]
### Describe the bug

On a Pay for Order page, the total of the order isn't passed to WooPay. Instead, WooPay reads from the current cart.

### To Reproduce

Please see this video for a reproduction of the issue:

https://github.com/Automattic/woocommerce-payments/assets/12542046/b9c3b4c0-49f8-4224-a810-3efc1dc7357f

If there is no cart, this error is displayed:

<img width="1209" alt="Screenshot 2023-10-31 at 12 08 48" src="https://github.com/Automattic/woocommerce-payments/assets/12542046/04ed60d8-280a-492f-ae81-ebf7a35bec74">

### Expected behavior

WooPay should capture the order total instead of the cart total.

**Comment by hsingyuc** [comment]
I'm going to close this issue since we have a duplicate issue open [here](2250-gh-Automattic/woopay).
