### ISSUE TITLE
Google/Apple pay buttons: Conflict between WooPay and payment button handlers.

### ISSUE THREAD

**Issue by ecairol** [Automattic/woocommerce-payments#7588]
### Describe the bug
The implementation of `wc_ajax_wcpay_add_to_cart` is done twice on two different files. If the product is `subscription_variation` and the user clicks the ApplePay or GooglePay button, the logic from WooPay will still trigger. This WooPay logic doesn't recognize a `subscription_variation` product so after removing all Products from the cart, these products won't be added back causing a `$0` amount in the GooglePay/ApplePay modal.

The files implementing the same AJAX function are:
 - `/includes/class-wc-payments-payment-request-button-handler.php`
 - `/includes/class-wc-payments-woopay-button-handler.php`

The second one, `woopay-button-handler`, has this condition to add the products back:
```
if ( in_array( $product_type, [ 'simple', 'subscription', 'bundle', 'mix-and-match' ], true ) ) {
    ...
}
```

The above should probably include support for `subscription_variation`, just like it's done in `class-wc-payments-payment-request-button-handler.php`:

```
$subscription_types = [
    'subscription',
    'subscription_variation',
];


if ( 'simple' === $product_type || in_array( $product_type, $subscription_types, true ) ) {
  ...
}
```

If there's no way WooPay can support `subscription_variation`, then some condition needs to be added so that WooPay implementation doesn't interfere with Google Pay and Apple Pay experience in case both are enabled.

A nice solution would be to have a third file from where this logic can be pulled by both files, to avoid future similar problems.

Reference of how this was fixed for the standard button handler: https://github.com/Automattic/woocommerce-payments/pull/5964

### To Reproduce

1. Enable the Express checkout buttons for Google Pay and Apple Pay
2. Create or look for a product of type`subscription_variation`
3. Go to the product and click the Google Pay or Apple Pay button
4. A modal opens with the correct price information
5. Go back to the WordPress Admin and enable WooPay
6. Repeat steps 2 and 3

### Actual behavior
The Google Pay modal shows a $0 amount

### Expected behavior
The Google Pay modal should show the actual product price.

### Desktop (please complete the following information):

* OS: [e.g. iOS]
* Browser [e.g. chrome, safari]
* Version [e.g. 22]

### Smartphone (please complete the following information):

* Device: [e.g. iPhone6]
* OS: [e.g. iOS8.1]
* Browser [e.g. stock browser, safari]
* Version [e.g. 22]

**Comment by htdat** [comment]
This issue impacts "Additional Payment Methods (including Apple Pay / Google Pay)", so assigning to Heisenberg (based on team responsibilities Pc2DNy-3z-p2) cc team lead @frosso.  Assigning as part of Gamma Triage process PcreKM-yM-p2.

**Comment by frosso** [comment]
Whoever takes this should also validate the fix on #7801

**Comment by mdmoore** [comment]
I haven't yet been able to reproduce the $0 total in Google Pay using a variable subscription. 

<img src="https://github.com/Automattic/woocommerce-payments/assets/3473953/954c77ca-89a4-4c3c-9dca-697a6fb72da3" width='400' />

The product type for my variable subscription product is `variable-subscription` rather than `subscription_variation` and is being added back to the cart in [the conditional here](https://github.com/Automattic/woocommerce-payments/blob/6914572c0ad8e51e798250e1c34973dd5c7e0d9d/includes/class-wc-payments-woopay-button-handler.php#L272). After a lot of research, I can't find what a `subscription_variation` product type is, only that both product types exist. @ecairol Do you know how a product of type `subscription_variation` can be created?

I have verified that, if WooPay is enabled, `WC_Payments_WooPay_Button_Handler::ajax_add_to_cart()` is indeed called even when clicking Google Pay as mentioned in #7801.

**Comment by ecairol** [comment]
>  @ecairol Do you know how a product of type subscription_variation can be created?

This conversation took place via DM in Slack, however, to recapitulate our convo:
 - I don't know at the moment how this type of product can be created. A few subscription products were already configured like that on one of our partner's sites when the problem was presented
 - I gave access to @mdmoore to both the WP Admin and the repo of a dev site where the problem can be reproduced.
 - I agree with @mdmoore  that it would be a good idea to get to the bottom of this re: how this product type can exist, to be 100% certain that WooPay should support it. There's very little mention of it on MGS, although @james-allan mentions it [in this P2](https://globalstepp2.wordpress.com/2021/03/25/wc-subscriptions-integration-with-wc-blocks-globalstep-call-for-testing-to-be-done-on-march-26-2021/#comment-237) outside the context of this particular website.
 - I offered to take a few hours next week to help clarify where this product type comes from, if necessary.

**Comment by james-allan** [comment]
> Do you know how a product of type subscription_variation can be created?

To create a `subscription_variation` you just need to create a variable subscription product with variations. The parent product will have a `variable-subscription` type, the variation (child) products with have a `subscription_variation` type.

**Comment by mdmoore** [comment]
Thanks @ecairol and @james-allan. That's what I discovered as well. When purchasing a subscription variation from a normal variable subscription product, the posted product ID is that of the parent. It seems there's some scenario where a subscription variation can be purchased outside of its parent product and the product ID will be that of the variation. I wasn't able to find a way to create this scenario but we have enough info to simulate it.
