### ISSUE TITLE
How to block certain card type, like for example Amex or others

### ISSUE THREAD

**Issue by SomeDevWeb** [Automattic/woocommerce-payments#7593]
### Description
I can't believe this option is not already present and nobody asked for it, but I guess I'll be the first. 
I got a request from my bloody financial department to block Amex cards and whatever I did and searched there's no obvious option. 
So I need to ask if anyone has any idea if there is an option in the settings or otherwise if there is any implementation plan in the future or some custom code that can be added with Woo hooks or something like that. 

Thank you very much and sorry for the frustration, but it's been days of extremely annoying searches and nobody knows or can give any clear solution. Thanks a lot!

**Comment by csmcneill** [comment]
Howdy @SomeDevWeb! Thanks for sharing this and communicating your clients' needs!

Generally, adding a feature like this is best handled via [the feature request portal](https://woo.com/feature-requests/woopayments/), which is where developers go to look for future plugin features and improvements. However, I am not going to close this issue in case you, one of the WooPayments developers, or a member of the community may have some ideas about how you can accomplish this.

**Comment by htdat** [comment]
Maybe a good candidate for iterating the current Fraud tool. 

This issue impacts "Risk and Fraud", so assigning to Sigma (based on team responsibilities Pc2DNy-3z-p2) cc team lead @tpaksu. Assigning as part of Gamma Triage process PcreKM-yM-p2.

**Comment by tpaksu** [comment]
Thanks for the ping @htdat, yes it makes sense to include this in the Fraud tool. I'll discuss it with my team.

**Comment by tpaksu** [comment]
@htdat we discussed this on our refinement call, and we decided that this issue is more like a merchant payment method configuration issue than a fraud issue. Can we re-assign this? Removing it from our backlog. Thanks!

**Comment by htdat** [comment]
Thanks @tpaksu for your feedback. I am checking with Gamma team: p1699494613568689-slack-C02L752DS0G

**Comment by SomeDevWeb** [comment]
Thanks for all the attention to this. This is indeed a quite necessary feature I think. 
@tpaksu - yes I think this is not a fraud feature, it should maybe be as an option right at the top in the "Select card payment" tick box, maybe as an "Advanced card options". 
As a thought, I had to give up on woopayments for now, not only because of this feature, but partially. 
But thanks for looking int it. Good luck with the coding!

**Comment by tpaksu** [comment]
Thanks @SomeDevWeb, then I'm closing this issue according to the comment above. Sorry to hear that you had to give up on WooPayments. Good luck!

**Comment by naman03malhotra** [comment]
>As a thought, I had to give up on woopayments for now, not only because of this feature, but partially.

Hey @SomeDevWeb, thanks for raising this issue. If it is possible, we would love to know what else we could have improved to let you stay.
