### ISSUE TITLE
Transactions Report - Add filters for other useful columns in UI

### ISSUE THREAD

**Issue by anu-rock** [Automattic/woocommerce-payments#7596]
### Description

The **Channel** column on the Transactions page indicates whether a transaction was made online or in person. Currently, there's no way of filtering out transactions of a particular type (channel).

Similarly, we can add filters for **Country** and **Risk Level**.

### Acceptance criteria

* Add a new filter called Channel in the advanced filters UI that will let a merchant show only online or only in-person orders.
* Add a new filter for Country.
* Add a new filter for Risk Level.

### Screenshot

<img width="631" alt="image" src="https://github.com/Automattic/woocommerce-payments/assets/1288616/5f209384-4727-46a6-b8c7-c6dbcce03dba">

**Comment by souravdebnath1986** [comment]
We could have filters for 2 other columns - `Country` (Customer country) and `Risk Level`

**Comment by anu-rock** [comment]
@mordeth I've updated the title and description based on @souravdebnath1986's comment.

**Comment by anu-rock** [comment]
Closed by #7754.

**Comment by anu-rock** [comment]
Closed by https://github.com/Automattic/woocommerce-payments/pull/7754.
