### ISSUE TITLE
Transactions Report - Add a button to download a detailed fees report

### ISSUE THREAD

**Issue by anu-rock** [Automattic/woocommerce-payments#7597]
### Description

The present CSV report contains only the total fee for a transaction. A merchant may want a detailed fee breakup for each transaction as part of their accounting reconciliation workflow.

### Acceptance criteria

* Add a new button to download the fees report as a CSV file.
* The CSV should contain a breakup similar to the one seen on the transaction details page, eg. base fee, international feel, FX fee, etc.

**Comment by souravdebnath1986** [comment]
This could become a seperate fee report in itself. We might want to park this in backlog for now until we have determined what specific fields we want in this report.

**Comment by anu-rock** [comment]
Closing this for now until we start working on separate fee reports.
