### ISSUE TITLE
Remove unused updateOptions in setup-complete-task.js

### ISSUE THREAD

**Issue by allie500** [Automattic/woocommerce-payments#7603]
### Description

While working on another issue with `updateOptions` usage in the client I found [this instance](https://github.com/Automattic/woocommerce-payments/blob/develop/client/additional-methods-setup/upe-preview-methods-selector/setup-complete-task.js#L78-L86) that didn't appear to be used any more. I checked with the team that made the most recent changes to the code and confirmed that the function is not used any longer and could be removed. 

Slack thread:
p1697656434448939-slack-CKNC7KACA

### Acceptance criteria

- The unused `updateOptions` function is removed from the `setup-complete-task.js` file.
- The additional payment methods setup complete task functionality continues to work as expected.
- Unit tests continue to pass.

**Comment by htdat** [comment]
This issue impacts "Additional Payment Methods", so assigning to Heisenberg cc team lead @frosso. Assigning as part of Gamma Triage process PcreKM-yM-p2.

**Comment by frosso** [comment]
I created a PR here: https://github.com/Automattic/woocommerce-payments/pull/7609

@allie500 do you feel comfortable giving it a quick review?

Thanks!
