### ISSUE TITLE
Only show actual (historic) deposits on deposits list page (no "estimated" deposits)

### ISSUE THREAD

**Issue by haszari** [Automattic/woocommerce-payments#7604]
The deposit list page shows historical deposits, and currently, also shows estimated future (or past?) deposits too:

<img width="1352" alt="Screenshot 2023-11-02 at 1 30 47 PM" src="https://github.com/Automattic/woocommerce-payments/assets/4167300/0bcfcf0b-c583-42e9-bb3c-c38989ba2bd2">

The estimated deposits are confusing, and not accurate, as we are manually estimating by summing transactions from orders. This is not 100% perfect as there may be other $ line items that affect future payouts, e.g. loan repayments, corrections for previous instant deposits, etc.

The goal of this issue is to remove all the estimated deposits from the deposit list screen.

**Comment by Jinksi** [comment]
Re-opening this issue as the resolving PR was reverted in #7668.
