### ISSUE TITLE
SPIKE: UPE integration with global styles

### ISSUE THREAD

**Issue by frosso** [Automattic/woocommerce-payments#7610]
### Description

The UPE payment methods are currently rendered by "guessing" the styles on a hidden field.
This computation can sometimes be sub-optimal: additional rendering time is needed, and the outcome can _sometimes_ be very approximate (but accurate, most times).

Let's investigate the possibility of using Global Styles for styling the UPE elements, when possible, instead of the "guesstimation" we're making at rendering time.

Obviously, the theme should be supporting global styles - not all themes do.

### Acceptance criteria

- Investigation of global styles integration
- P2 to highlight outcomes/pros/cons
- Next steps are logged as tickets

### Additional context

paJDYF-b5M-p2#comment-21555

**Comment by FangedParakeet** [comment]
Marking this as completed in #5502 and #8094. 🚀
