### ISSUE TITLE
Fatal error in 6.7.0 if WC_Logger is overridden via woocommerce_logging_class filter

### ISSUE THREAD

**Issue by jessepearson** [Automattic/woocommerce-payments#7612]
### Describe the bug
If the `WC_Logger` class is overridden via the `woocommerce_logging_class` filter, then a fatal error is thrown due to we are expecting the `WC_Logger` class in the [`WCPay\Internal\Logger` class](https://github.com/Automattic/woocommerce-payments/blob/develop/src/Internal/Logger.php).

> Fatal error: Uncaught TypeError: Argument 1 passed to WCPay\Internal\Logger::__construct() must be an instance of WC_Logger, instance of WooCommerce_Bogus_Logger given in /wp-content/plugins/woocommerce-payments/src/Internal/Logger.php:51

### To Reproduce

[woocommerce-bogus-logger.zip](https://github.com/Automattic/woocommerce-payments/files/13241249/woocommerce-bogus-logger.zip)

1. Install the above plugin.
2. Activate plugin.
3. Receive fatal error.

### Additional context
The plugin is just the `WC_Logger` class copied and renamed, and then it is called via the `woocommerce_logging_class` filter.

**Comment by jessepearson** [comment]
If merchants experience this bug, they can roll back to 6.6.2 as a work around. That is available in the drop down here: https://wordpress.org/plugins/woocommerce-payments/advanced/

**Comment by csmcneill** [comment]
Reported in the community Slack: https://woocommercecommunity.slack.com/archives/C1K9J1ED9/p1698962555203669

**Comment by htdat** [comment]
FYI. Reported in p1698934493232699-slack-C7U3Y3VMY but originally reported for multiple Atomic sites: p1698930663970289-slack-C03TY6J1A

Use this information to decide whether we need a patch release.

**Comment by jessepearson** [comment]
Fix was released with 6.7.1
