### ISSUE TITLE
Add order note for orders placed while WooPayments is in test mode

### ISSUE THREAD

**Issue by csmcneill** [Automattic/woocommerce-payments#7615]
### Description
This is similar to #334 in that it would be great to have test purchases clearly indicate that they were made in test mode. In pchH0V-1le-p2#test-transactions I posited adding an order note when a purchase is made in test mode. This would allow the notice to persist even when WooPayments no longer has test mode enabled, and it will provide additional clarity to merchants who may use **WooCommerce > Orders** during their fulfillment process.

### Acceptance criteria

* First requirement
* Second requirement
* Third requirement
* etc.

### Testing instructions

1. Go to '…'
2. Click on '…'
3. Scroll down to '…'
4. Observe expected behaviour

### Additional context

p1698948832695539-slack-C05QSQ0GT0U

**Comment by darcie** [comment]
7265333-zen While there are notes in the payment screens, not seeing a note in the order was confusing to the merchant.

**Comment by darcie** [comment]
7296174-zen

**Comment by htdat** [comment]
FYI. Relevant project: paJDYF-bnR-p2

**Comment by vladolaru** [comment]
@csmcneill In light of having an order notice that is persistent when test mode is deactivated (implemented https://github.com/Automattic/woocommerce-payments/pull/7898), is this issue still relevant? What are the use cases where having details in the order notes would help? I can only think about having WooPayments deactivated completely.

Besides, I don't know if having a dedicated order note is the best way. Maybe we can go more general and augment related order notes like this:

For example from this:
> A payment of $18.00 USD was successfully charged using WooPayments (pi_TERTEWERTET).
to this:
> A payment of $18.00 USD was successfully charged using WooPayments in TEST MODE (pi_TERTEWERTET).

My proposal is that wherever we have order notes like these (that include "using WooPayments") we add "in TEST MODE" when the order was handled in test mode.

WDYT?

**Comment by csmcneill** [comment]
Thanks for flagging this @vladolaru! With the changes implemented via #7898, I don't think that this issue is necessary.

I'll close this one out, but we can re-open it if we find that it may be worth exploring again :)
