### ISSUE TITLE
Improve redirects logic in payments

### ISSUE THREAD

**Issue by oaratovskyi** [Automattic/woocommerce-payments#7654]
### Description
At the moment, we have quite complex redirects logic in `WC_Payments_Account`. First, we have a lot of hooks around the topic:
```
add_action( 'admin_init', [ $this, 'maybe_redirect_to_onboarding' ], 11 ); // Run this after the WC setup wizard and onboarding redirection logic.
add_action( 'admin_init', [ $this, 'maybe_redirect_to_wcpay_connect' ], 12 ); // Run this after the redirect to onboarding logic.
add_action( 'admin_init', [ $this, 'maybe_redirect_to_capital_offer' ] );
add_action( 'admin_init', [ $this, 'maybe_redirect_to_server_link' ] );
add_action( 'admin_init', [ $this, 'maybe_redirect_settings_to_connect' ] );
``` 
Second, there is a big function `maybe_handle_onboarding` that also contains logic around redirects, see a couple of examples (not all):
```
if ( ( $from_wc_admin_task || $from_wc_pay_connect_page ) ) {
	// Redirect complete accounts to payments overview page, otherwise to the onboarding flow.
	if ( $this->is_account_complete() ) {
		$this->redirect_to( static::get_overview_page_url() );
	} else {
		$this->redirect_to_onboarding_flow_page();
	}
}
...
if ( isset( $_GET['wcpay-disable-onboarding-test-mode'] ) ) {
    ...
    $this->redirect_to_onboarding_flow_page();
}
```

After conversation in https://github.com/Automattic/woocommerce-payments/pull/7652#issuecomment-1798425685, we decided to normalize and reduce the redirect logic, so we don't get to pile on more conditional branches to the logic. 
We should strive to have a stable, catch-all logic that would prevent any other such issues in the future (no more ending up on pages with "Sorry you are not allowed").

### Dev ideas
- Centralize logic around redirects in a class
- Reduce the amount of hooks to one or two that are responsible for all kinds of redirects
- Have extensive tests covering all possible scenarios

**Comment by daquinons** [comment]
Open to increase it to 5 estimation points if necessary to nail this

**Comment by oaratovskyi** [comment]
I started thinking about the best solution but got a bit stuck and then PRD of Tracking v2 appeared which is due in April and I'm the DRI of one. I'm putting this on pause until the next cooldown.

**Comment by anu-rock** [comment]
Moving it to our on-hold pipeline to keep track.
