### ISSUE TITLE
PHP error on local sites when clicking "Verify details" on WooCommerce setup pages when running on local

### ISSUE THREAD

**Issue by ncsramona** [Automattic/woocommerce-payments#7677]
### Describe the bug
I created a new site using Local app and after installing WooPayments, I clicked on the "Verify details" button here:
<img width="400" alt="image" src="https://github.com/Automattic/woocommerce-payments/assets/133644769/574ef19a-cc00-4662-ae3d-1454d9dee6e1">
A PHP error was displayed:
```
Fatal error: Uncaught WCPay\Exceptions\API_Exception: Your site host "shipping.local" is on a private network. Jetpack can only connect to public sites. in /Users/[..]/Local Sites/shipping/app/public/wp-content/plugins/woocommerce-payments/includes/wc-payment-api/class-wc-payments-http.php on line 194
--

1 | 0.0015 | 373400 | {main}( ) | .../index.php:0
2 | 0.0015 | 374680 | require_once( '/Users/[...]/Local Sites/shipping/app/public/wp-admin/admin.php ) | .../index.php:10
3 | 0.1777 | 11813848 | do_action( $hook_name = 'admin_init' ) | .../admin.php:175
4 | 0.1777 | 11814224 | WP_Hook->do_action( $args = [0 => ''] ) | .../plugin.php:517
5 | 0.1777 | 11814224 | WP_Hook->apply_filters( $value = '', $args = [0 => ''] ) | .../class-wp-hook.php:348
6 | 0.1843 | 11943304 | WC_Payments_Account->maybe_handle_onboarding( '' ) | .../class-wp-hook.php:324
7 | 0.1850 | 11950256 | WC_Payments_Account->redirect_to_onboarding_flow_page( ) | .../class-wc-payments-account.php:937
8 | 0.1852 | 11950368 | WC_Payments_API_Client->start_server_connection( $redirect = 'https://shipping.local/wp-admin/admin.php?page=wc-admin&path=/payments/onboarding' ) | .../class-wc-payments-account.php:1836
9 | 0.1852 | 11950368 | WC_Payments_Http->start_connection( $redirect = 'https://shipping.local/wp-admin/admin.php?page=wc-admin&path=/payments/onboarding' ) | .../class-wc-payments-api-client.php:213
```

### To Reproduce
1. Create a new site in a local environment. I just used Local
2. Install Woo and WooPayments (I don't have Jetpack at all)
3. When Woo displays the "It's time to get paid" message, click on the Verify Details button
You'll see the error.

### Actual behavior
While I don't think this would affect many people, it would be nice to avoid displaying such an error.

### Screenshots
<img width="400" alt="image" src="https://github.com/Automattic/woocommerce-payments/assets/133644769/574e0335-d102-4d42-8c94-a1ae207aa3cf">

### Expected behavior
Instead of a PHP error, we could display a notice stating that the site was not able to connect to Jetpack .

### Desktop (please complete the following information):

* OS:  MacOS 14.1 (23B74)
* Browser: Chrome 119.0.6045.123
* Version: 119.0.6045.123
* Host: Local

### Additional context
SSR:
<details>
`
### WordPress Environment ###

WordPress address (URL): http://videos.local
Site address (URL): http://videos.local
WC Version: 8.2.2
REST API Version: ✔ 8.2.2
WC Blocks Version: ✔ 11.1.3
Action Scheduler Version: ✔ 3.6.3
Log Directory Writable: ✔
WP Version: 6.4.1
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache/2.4.43 (Unix)
PHP Version: 8.2.10
PHP Post Max Size: 1,000 MB
PHP Time Limit: 1200
PHP Max Input Vars: 4000
cURL Version: 8.1.2
(SecureTransport) LibreSSL/3.3.6

SUHOSIN Installed: –
MySQL Version: 8.0.16
Max Upload Size: 300 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 8.2.2
WC Database Prefix: wp_
Total Database Size: 5.03MB
Database Data Size: 3.31MB
Database Index Size: 1.72MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 0.05MB + Index: 0.11MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_options: Data: 2.08MB + Index: 0.06MB + Engine InnoDB
wp_postmeta: Data: 0.13MB + Index: 0.06MB + Engine InnoDB
wp_posts: Data: 0.06MB + Index: 0.06MB + Engine InnoDB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.05MB + Index: 0.02MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.06MB + Index: 0.00MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_addresses: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_operational_data: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_orders: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
wp_wc_orders_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_attributes_lookup: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_download_directories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB

### Post Type Counts ###

attachment: 34
page: 7
post: 2
product: 18
product_variation: 7
wp_navigation: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (2) ###

WooCommerce Payments: by Automattic – 6.7.1
WooCommerce: by Automattic – 8.2.2

### Settings ###

API Enabled: –
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –
Enforce Approved Product Download Directories: ✔
HPOS feature screen enabled: ✔
HPOS feature enabled: ✔
Order datastore: Automattic\WooCommerce\Internal\DataStores\Orders\OrdersTableDataStore
HPOS data sync enabled: –

### WC Pages ###

Shop base: #7 - /shop/
Cart: #8 - /cart/
Checkout: #9 - /checkout/
My account: #10 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Storefront
Version: 4.5.3
Author URL: https://woocommerce.com/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### WooPayments ###

Version: 6.7.1
Connected to WPCOM: ❌ No
Logging: Disabled

### Admin ###

Enabled Features: activity-panels
analytics
product-block-editor
coupons
core-profiler
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
product-variation-management
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: customize-store
minified-js
new-product-management-experience
settings
async-product-editor-category-field

Daily Cron: ✔ Next scheduled: 2023-11-09 12:54:58 +00:00
Options: ✔
Notes: 69
Onboarding: completed

### Action Scheduler ###

Complete: 70
Oldest: 2023-11-07 12:56:00 +0000
Newest: 2023-11-09 12:26:12 +0000

Failed: 1
Oldest: 2023-11-07 12:57:11 +0000
Newest: 2023-11-07 12:57:11 +0000

Pending: 1
Oldest: 2023-11-10 12:23:28 +0000
Newest: 2023-11-10 12:23:28 +0000

### Status report information ###

Generated at: 2023-11-09 12:49:02 +00:00
`
</details>

**Comment by htdat** [comment]
This issue impacts "Onboarding", so assigning to Moltres (based on team responsibilities Pc2DNy-3z-p2) cc @daquinons as team lead. 
Assigning as part of Gamma Triage process PcreKM-yM-p2.

**Comment by oaratovskyi** [comment]
it's not happening anymore on this page, the link leads to the payments connect page.
The issue with the payment connect page will be closed by #8532

**Comment by anu-rock** [comment]
This issue was not closed when https://github.com/Automattic/woocommerce-payments/pull/8532 was merged, likely because the issue number was not linked to the PR (GH requires each linked issue to be specified in a new line as "fixes #123abc".

@oaratovskyi - FYI. I am closing this issue.

**Comment by oaratovskyi** [comment]
Thanks @anu-rock ! You're right, I'll add fixes next time 👍
