### ISSUE TITLE
[PO] Dev mode account is restricted to the US and cannot be changed

### ISSUE THREAD

**Issue by csmcneill** [Automattic/woocommerce-payments#7678]
### Describe the bug

A merchant can land into the new Woo-owned progressive onboarding flow even if they do not qualify for progressive onboarding.

If they are presented with the Woo-owned PO flow and they are not based in the United States, selecting the dev mode option will autofill information, such as::

```
Name: John Woolliams
DOB: 01/01/1980
Address: 1040 Grand Ave, South San Francisco, California, USA 94080
Phone: +10000000000
```

However, because the address is provided already, this means that the country cannot be changed. This forces someone who...
1. Is presented with the Woo-owned PO flow.
2. Is based outside of the United States.
3. Wants to create a dev mode account.

...to create a dev mode account based in the US.

### To Reproduce

1. Onboard with progressive onboarding enabled.
2. Select dev mode.
3. Try to onboard in a non-US country.

### Actual behavior

A merchant who is presented with PO can only create a dev mode account based in the United States due to prefilled information. This:
1. Allows the merchant to test functionalities that may not be available for other goes, like WooPay and Link by Stripe. 
2. Means that some BNPL offerings, like Klarna, will also offer different options to customers that may not be available in the merchant's real geo.

### Expected behavior

Choosing dev mode via the PO flow only prefills enough data (or none at all) so that a merchant can still choose their country.

Optionally: provide a way for a merchant to bypass the PO flow completely, either via a PHP filter or something in the UI.

### Additional context

p1699546619185449-slack-C3NCP7ZJ6
7277600-zen

**Comment by htdat** [comment]
This issue impacts "Onboarding", so assigning to Moltres (based on team responsibilities Pc2DNy-3z-p2) cc @daquinons as team lead. 
Assigning as part of Gamma Triage process PcreKM-yM-p2.

**Comment by francoishvz** [comment]
7277600-zd-a8c

**Comment by dmallory42** [comment]
@daquinons - do you think we could squeeze this one into the sprint? I think ideally we should just adjust the builder flow so it doesn't pre-fill the country (since this prevents merchants from being able to test region-specific functionality and seems to cause confusion).

**Comment by daquinons** [comment]
@dmallory42 Agree, added it for now with a low priority, thank you for jumping in first!
