### ISSUE TITLE
Date pickers not functioning 

### ISSUE THREAD

**Issue by rossviviano** [Automattic/woocommerce-payments#7679]
### Describe the bug

When filtering through transactions and deposits, the date picker (under advanced filters) Isn't functioning. 

### To Reproduce

1. Head to Payments> Transactions
2. Show advanced filters, and add a date filter
3. Try to select any date

### Actual behavior

No dates or months are able to be selected

### Screenshots

gif of issue: 
https://github.com/Automattic/woocommerce-payments/assets/10045087/1a2553c5-0177-4507-ae7a-f0f378b0b594

### Desktop (please complete the following information):

* OS: Mac 14.1
* Browser  Chrome
* Version 119.0.6045.123

### Additional context

7293502-zen

**Comment by csmcneill** [comment]
I can reproduce this; the calendar is basically non-responsive.

Reverting to 6.6.0 and 6.5.0 of WCPay does not resolve the issue. Additionally, reverting to versions 8.2.0, 8.1.0, and 8.0.0 of Woo core does not resolve the issue.

This issue is also present in WordPress 6.3.2 and 6.4.1 — could this be a server issue?

**Comment by htdat** [comment]
It seems an issue with Woo core. As I check the code, the advanced filters in WooPayments use `AdvancedFilters` component from Woo core. 

I am checking a similar DatePicker with only WooCommerce active, and the same issue happens. E.g. Go to wp-admin > Analytics > Select a date range > Custom. 
![Markup on 2023-11-10 at 14:14:10](https://github.com/Automattic/woocommerce-payments/assets/10045087/d8d8e2d1-fb29-4574-859a-2193992a2a25)

**Comment by htdat** [comment]
Asking in p1699601009652009-slack-C01CMSA1VHS

**Comment by AnnaMag** [comment]
[Opened an issue in the Core repository](https://github.com/woocommerce/woocommerce/issues/41362) and assigned it to Mothra.

**Comment by htdat** [comment]
@AnnaMag @octaedro as I also mentioned on p1699853000416149/1699601009.652009-slack-C01CMSA1VHS :

> Thanks for the quick fix on this issue. However, WooPayments issue (I tested with WooCommerce Bleeding Edge with Jetpack Beta) is still there.
> It turns out that WooPayments config for `AdvancedFilters` is `input.component: 'Date'`  ([ref](https://github.com/Automattic/woocommerce-payments/blob/0ecb8e100f3134e3c4fed47abfea3996cb63b155/client/transactions/filters/config.ts#L188-L189)), which is actually `DatePicker` in [WooCommerce core](https://github.com/woocommerce/woocommerce/blob/70154d5476254a061734c0bf47259d9a71156aca/packages/js/components/src/advanced-filters/item.js#L34-L35).
> Could you check and apply the similar fix for DatePicker too?

**Comment by htdat** [comment]
@octaedro fixed the issue in Woo core https://github.com/woocommerce/woocommerce/pull/41404 . AFAIK, this fix will be released in Woo 8.3.0.

I confirm that date pickers in WooPayments advanced filters are working now.
