### ISSUE TITLE
WP 5.6 - Test with core JQuery update

### ISSUE THREAD

**Issue by allendav** [Automattic/woocommerce-payments#768]
WordPress is rolling the version of jQuery bundled with it. Let's test compatibility. https://make.wordpress.org/core/2020/06/29/updating-jquery-version-shipped-with-wordpress/
Thankfully, WCPay barely uses jQuery, so this should be quick.

**Comment by dwainm** [comment]
Closing as we didn't have any issue with this and are on WP 5.7 already.
