### ISSUE TITLE
Update order amount requirements for Klarna PM

### ISSUE THREAD

**Issue by dmvrtx** [Automattic/woocommerce-payments#7680]
Related to #7530 

Limits are given per-country as the widest possible range. When shopper is redirected to Klarna they might have limited choice of options depending on the order amount. E.g. term loan for Austria requires a minimum amount of € 25, while other options are available from € 0,01.

| Country | Currency | Min    | Max     |
| :-----: | :------: | -----: | ------: |
|    AT   |   EUR    | 0,1    | 10.000  |
|    BE   |   EUR    | 0,1    | 10.000  |
|    DE   |   EUR    | 0,1    | 10.000  |
|    NL   |   EUR    | 0,1    | 15.000  |
|    DK   |   DKK    | 1      | 100.000 |
|    FI   |   EUR    | 0      | 10.000  |
|    NO   |   NOK    | 0      | 100.000 |
|    SE   |   SEK    | 0      | 150.000 |
|    ES   |   EUR    | 0      | 10.000  |
|    IE   |   EUR    | 0      | 4.000   |
|    IT   |   EUR    | 0      | 10.000  |
|    UK   |   GBP    | 0      | 11.500  |
|    US   |   USD    | 0      | 10.000  |

Per-currenyc limits, derived from the table above:

| Currency | Min     | Max      | Comment |
| :------: | ------: | -------: | ------- |
| EUR      |  0,1    | 4.000    | Max based on IE |
| DKK      |  1      | 100.000  | |
| NOK      |  0      | 100.000  | |
| GBP      |  0      | 11.500   | |
| USD      |  0      | 10.000   | |

**Comment by KarlisJ** [comment]
AFAIU, we're losing some valuable ranges with this approach. 

Couldn't we update `is_enabled_at_checkout` method to account for currency/country limits? We currently have limits only for BNPL PMs which would make it rather simple refactor. 

I'm thinking something like 
```php
$this->limits_per_currency          = [
	'EUR' => [
		'IE' => [
			'min' => 0,
			'max' => 400000,
		],
		//..
		'default' => [
			//..
		],
	],
```

**Comment by kalessil** [comment]
Like the idea.

Code-wise, we would need to supply the method with account data, which is available in gateways. It has a `country` property, which we can use to pick the range.

**Comment by dmvrtx** [comment]
Approach suggested by @KarlisJ makes sense to me. Who is willing to make it happen?

**Comment by kalessil** [comment]
@KarlisJ: it should be a good fit for you.

Karlis: the code freeze is `Monday Nov 13th, 2023 @ 12:00 UTC`, can you please prioritize this issue over other activities?

**Comment by KarlisJ** [comment]
@kalessil Will provide PR EoD

**Comment by KarlisJ** [comment]
@dmvrtx Could you point to the source for the values provided in the description? They differ from what we have in the codebase right now for all currencies
