### ISSUE TITLE
Should not redirect to WooPay checkout page when WC Bookings require confirmation

### ISSUE THREAD

**Issue by hsingyuc** [Automattic/woocommerce-payments#7684]
### Describe the bug
On the Blocks checkout page, we should not redirect to the WooPay checkout page when WC Bookings require confirmation.

### To Reproduce
1. Install and activate WC Bookings plugin
2. Check the "Requires confirmation?" box
3. As a logged-in customer, go through the purchasing process and go to the Blocks checkout page
4. See, we redirect to WooPay and skip the merchant confirmation process.

### Actual behavior
When the WC Bookings product requires confirmation, on the Blocks checkout page, we redirect to the WooPay checkout page and skip the merchant confirmation process.

### Screenshots

https://github.com/Automattic/woocommerce-payments/assets/56378160/e3ee160a-f0ea-4420-ba80-56960b1d96fb

### Expected behavior
When the WC Bookings product requires confirmation, on the Blocks checkout page, we should not redirect to the WooPay checkout page.

**Comment by hsingyuc** [comment]
Note: WC Pre-orders have the same issue.  If click the place order button, will get 'Merchant store order creation failed with the following error:' and the pay-for-order order still got created.

**Comment by pierorocca** [comment]
For prioritization, noting that Bookings is marked as incompatible and merchants will get an inline warning noting such. @c-shultz this seems more like a dev bug related to the pay for order compatibility work rather than a bug related to a production supported feature?

**Comment by c-shultz** [comment]
>@c-shultz this seems more like a dev bug related to the pay for order compatibility work rather than a bug related to a production supported feature?

@LCmry @hsingyuc, do you all have plan for prioritizing this to close out the pay for order work or should we just keep it in the maintenance queue to be solved once it reaches the top of the queue?

**Comment by hsingyuc** [comment]
This is not a pay-for-order issue but I can prioritize it since pay-for-order flow issues are all addressed and waiting on review.
