### ISSUE TITLE
Move track calls into a utils function to make a clearer separation from external function

### ISSUE THREAD

**Issue by dwainm** [Automattic/woocommerce-payments#769]
Our code contains calls to:

```
window.wcTracks.recordEvent
```

These calls should be replaced by a utils function that wraps the function in order for us to ensure better separation between our code and external dependencies. 

Is it makes sense we should also add tests.

**Comment by vbelolapotkov** [comment]
Partly implemented in #855 https://github.com/Automattic/woocommerce-payments/pull/855/commits/d3afc8258a78e6a4cb00692bc9a2857a2dd50fb2

**Comment by ilyasfoo** [comment]
I think we can close this, addressed in https://github.com/Automattic/woocommerce-payments/pull/1520

**Comment by vbelolapotkov** [comment]
Yep @ilyasfoo , you're right. Closing it. Thanks again for fixing this!
