### ISSUE TITLE
Product quantity not taken into account when using the Payment Request Button

### ISSUE THREAD

**Issue by ecairol** [Automattic/woocommerce-payments#7694]
### Describe the bug
When using the Payment Request Button (both Apple Pay and Google Pay), the product quantity is not taken into account to calcualte the `total_amount`.

### To Reproduce

1. Go to a site that has WooPayments and Apple/Google Pay enabled. I'm using [this test site](https://esteban-sandbox.mystagingwebsite.com/product/simple-product/) to isolate the problem.
2. Increment the product quantity > 1
3. Click on the Google Pay or Apple Pay button, depending on your browser config.
4. A modal should open, indicating the total amount to pay.

### Actual behavior
Google/Apple Pay modal shows the product price x1

### Expected behavior
The modal should show the product price multiplied by the product quantity. 
Note: this value is corrected once a third request is made to `?wc-ajax=get_shipping_options`, however, if the user doesn't have a pre-selected shipping address the incorrect value will be displayed until the user selects the shipping address. I suspect that for virtual products this would never happen, since there's no shipping method to select.

This error probably comes from the function `/?wc-ajax=wcpay_get_selected_product_data` that's invoked when the quantity is updated. See screenshot below.

Request to `wcpay_get_selected_product_data`
<img width="720" alt="Screenshot 2023-11-10 at 11 19 34" src="https://github.com/Automattic/woocommerce-payments/assets/1821060/cd215d47-95f9-4305-97d8-9a9ba43b6d9a">

Request to `wcpay_add_to_cart`: amount is correct on the JSON response, but not updated on the Google Pay screen
<img width="904" alt="Screenshot 2023-11-10 at 11 18 26" src="https://github.com/Automattic/woocommerce-payments/assets/1821060/decf2d3d-d90f-40f2-9c32-adc6567b43f0">

If a third request was made to `get_shipping_options`, then the modal would flicker and correct the value after a couple of seconds. This behavior can be reproduced on this other [test site](https://novoslabs-dev-optimization.mystagingwebsite.com/product/novos-core/) (to reproduce, click on "Individual", then increment the quantity and click the Google Pay button: it will flicker and update the total amount accordingly, as long as you have a shipping address preselected).

### Desktop (please complete the following information):

* OS: macOS
* Browser Chrome
* Version 118.0

### Smartphone (please complete the following information):

* Device: Samsung
* OS: Android
* Browser Chrome

**Comment by htdat** [comment]
This issue impacts "Additional Payment Methods (including Apple Pay / Google Pay)", so assigning to Heisenberg (based on team responsibilities Pc2DNy-3z-p2) cc team lead @frosso.

Assigning as part of Gamma Triage process PcreKM-yM-p2.
