### ISSUE TITLE
Google/Apple Pay total is $0 if product type is variation

### ISSUE THREAD

**Issue by ecairol** [Automattic/woocommerce-payments#7695]
### Describe the bug
If a Product type is `variation`, the totals is reset to $0. The same behavior happens on Apple Pay.

### To Reproduce
1. Go to this site: https://novoslabs-dev-optimization.mystagingwebsite.com/product/novos-core/
2. Click on `Individual`
3. Click on `Google Pay` or `Apple Pay` button
5. If there is not selected a shipping method, enter or select one
6. The total price is changed to $0

### Actual behavior
Total amount on the Google/Apple Pay modal is $0

### Screenshots
<img width="898" alt="Screenshot 2023-11-10 at 14 10 08" src="https://github.com/Automattic/woocommerce-payments/assets/1821060/50f2b93f-302a-4269-b8dd-5d819cc38fc3">

### Expected behavior
The total amount calculation should take into account products with the type `variation`. This will ensure that the product is re-added to the cart during the `ajax_add_to_cart()` implementation.

### Desktop (please complete the following information):

* OS: MacOS
* Browser Chrome
* Version 118.0

### Smartphone (please complete the following information):

* Device: [e.g. iPhone6]
* OS: [e.g. iOS8.1]
* Browser [e.g. stock browser, safari]
* Version [e.g. 22]

### Additional context

- This is pretty much the same issue as https://github.com/Automattic/woocommerce-payments/issues/5963, just a different product type to give support. 

- This is also related to https://github.com/Automattic/woocommerce-payments/issues/7588

**Comment by htdat** [comment]
This issue impacts "Additional Payment Methods (including Apple Pay / Google Pay)", so assigning to Heisenberg (based on team responsibilities Pc2DNy-3z-p2) cc team lead @frosso.

Assigning as part of Gamma Triage process PcreKM-yM-p2.

**Comment by ecairol** [comment]
@frosso I have submitted this PR with a fix for this issue: https://github.com/Automattic/woocommerce-payments/pull/7702/ – I did add https://github.com/Automattic/woocommerce-payments/pull/7702/files#r1391249464 with a potential broader fix for other scenarios.

**Comment by ecairol** [comment]
Re-opening because the patch was overwritten.

This issue had been fixed with PR: https://github.com/Automattic/woocommerce-payments/pull/7702/files#r1391249464, however, there has been a rollback and the problem is now happening again.

All this logic was moved to the new helper file here:
https://github.com/Automattic/woocommerce-payments/blob/trunk/includes/express-checkout/class-wc-payments-express-checkout-button-helper.php#L88

and while `'bundle', 'mix-and-match' ` were added, the value `variation` was removed, accidentally I supposed.

cc @mdmoore

**Comment by mdmoore** [comment]
Closed via #8101
