### ISSUE TITLE
Informational banner that informs a merchant with a WC store set in a country not supported by WooPayments

### ISSUE THREAD

**Issue by daquinons** [Automattic/woocommerce-payments#7699]
### Description
We should add a notice banner on the Connect page, before onboarding takes place, if a WooCommerce store is set in a country not supported at the moment by WooPayments.

This makes sense because the extension can be installed in multiple ways and we need to give notice to a merchant as soon as possible in the flow of the supported countries. Also, at the end of the day, we can't really restrict a user to install an extension even if they are in unsupported countries.

Ultimately, what Payments is interested in is the entity/legal country, which might, or might not, be the same as the WooCommerce store setting. Because of this, the approach should be informational and not restrictive.

More in this thread peapX7-3uM-p2#comment-5127

### Acceptance criteria
- Informational banner in the Connect page if the WC store is set in a location that is not supported by WooPayments
- The informational banner should link to our supported countries https://woo.com/document/woopayments/compatibility/countries/ saying that they'll need a business address in one of those countries to use WooPayments - copy to be finalised by design

**Comment by elizaan36** [comment]
We could use the WP or WC error notice component for this, to align with the notice components being used in WC core.

<img width="1440" alt="image" src="https://github.com/Automattic/woocommerce-payments/assets/5121465/85c84145-9d39-42e3-8987-3510acd6f3b8">

Here's the proposed copy with link to the docs.

> WooPayments is not currently available in your location. To be eligible for WooPayments, your business address must be in one of the following [supported countries](https://href.li/?https://woo.com/document/woopayments/compatibility/countries/).

**Comment by daquinons** [comment]
Thanks a lot!

There is [this part of the codebase](https://github.com/Automattic/woocommerce-payments/blob/f0d1ae05973b9e26e0dae4e8652357b3db8cd470/client/connect-account-page/modal/index.js#L49) that addresses exactly this issue, which was added https://github.com/Automattic/woocommerce-payments/pull/2181. Somehow seems like the feature is broken because the modal is not being displayed, it probably got overridden in some of the additional updates and we didn't realise the feature was lost (as it was reported from ZA peapX7-3uM-p2 )

I'm increasing the estimation to 2 to revisit that area, clean up the unused code of the modal, reuse the logic for the location check as much as possible and add the new informative banner

**Comment by elizaan36** [comment]
Interesting! I think the banner + link to the docs is a more user friendly solution, since the user will have a warning prior to any attempt to click "Finish setup". But it might be worth also reiterating the message in a modal popup if the click attempt is made.

**Comment by ismaeldcom** [comment]
Agreed on Slack to add the banner and keep the existing modal – p1701344646655589/1700563878.596979-slack-C03KTTK2YMA
