### ISSUE TITLE
Listen for payment success webhook events and complete payment on order

### ISSUE THREAD

**Issue by jrodger** [Automattic/woocommerce-payments#770]
We currently rely on a customer's browser redirecting back to the store after completing SCA authentication. We should also listen for a webhook telling us the payment was successful as a backup method of completing the payment on the order.

The handling will be largely similar to the Stripe gateway

**Comment by dechov** [comment]
Is this closed by https://github.com/Automattic/woocommerce-payments/pull/1623? cc @harriswong

**Comment by harriswong** [comment]
Hi @dechov! https://github.com/Automattic/woocommerce-payments/pull/1623 listens to `payment_intent.succeeded` from the webhook. Then it updates the order status by calling [woo core's payment_comlpete](https://github.com/Automattic/woocommerce-payments/blob/d10ceb6ab11c58324c32c7806ef3a3c4fa6288e5/includes/admin/class-wc-rest-payments-webhook-controller.php#L268) method. The result of the order should be either "processing" or "completed". 

I think it should resolve this issue.

**Comment by jrodger** [comment]
Thanks both, agreed, this can be closed.
