### ISSUE TITLE
Merchants get redirected to Sorry, not allowed page after trying to access settings

### ISSUE THREAD

**Issue by oaratovskyi** [Automattic/woocommerce-payments#7705]
### To Reproduce

1. Spin up new JN site
2. Does not matter if PO flag is enabled or not, you can choose any option
3. Leave the KYC on address input (Return back to WooPayments)
4. You'll be redirected to payments/overview page. You can check that link Finish setting up WooPayments works perfectly.
5. But if you try accessing Settings page, you'll be redirected to payments/connect page and see Sorry, you are not allowed to access this page.

### Actual behavior
Merchant gets redirected to `payments/connect` and sees the error

### Expected behavior
Story:

- As a WooPayments merchant onboarding, when I exit the KYC halfway, I shouldn't be able to see the Settings page, which is already restricted for them, in the payments menu.
- As a WooPayments merchant onboarding, I shouldn't be able to see any other subitem in the Payments menu, except for Overview, which is the only place where the user can continue with their onboarding.

Important:

- This should only affect to standard users without details_submitted, but not to progressively onboarded users that can collect payments already
- It should also not affect other account lifecycle statuses, such as restricted accounts
- Remove link to settings from info banner

### Additional context
p1699891469296849-slack-C03KTTK2YMA

**Comment by daquinons** [comment]
Thanks, Oleks!

I've tested the flow and I can confirm it results in the user getting stuck in that screen unless they reload the whole page, which is a negative experience for merchants. Taking that into account, I'm giving it a high priority.

Story:
- As a WooPayments merchant onboarding, when I exit the KYC halfway, I shouldn't be able to see the Settings page, which is already restricted for them, in the payments menu.
- As a WooPayments merchant onboarding, I shouldn't be able to see any other subitem in the Payments menu, except for Overview, which is the only place where the user can continue with their onboarding.

Important:
- This should only affect to standard users without details_submitted, but not to progressively onboarded users that can collect payments already
- It should also not affect other account lifecycle statuses, such as restricted accounts

**Comment by daquinons** [comment]
We need to remove the link from this info banner as well

<img width="670" alt="image" src="https://github.com/Automattic/woocommerce-payments/assets/2612426/81c9e825-9f49-49c1-8b20-958cb95bbd50">
