### ISSUE TITLE
Nondescript error with Stripe Billing if customers attempt to have multiple active subscriptions with different currencies

### ISSUE THREAD

**Issue by csmcneill** [Automattic/woocommerce-payments#7732]
### Describe the bug
If a site uses Stripe Billing with WooPayments + Woo Subscriptions and a customer has an active subscription in one currency (e.g., EUR), they cannot purchase another subscription in a different currency (e.g., USD).

This is expected, but it produces a nondescript error on checkout:

```
There was a problem creating your subscription. Please try again or contact us for assistance.
```

Additionally, there are no subscription notes for the `Pending` subscription or the `Draft` Parent Order that are created. As a result, no one will know what happened unless:

1. Logging is enabled.
2. A merchant assesses the logs

The logs indicate the following:

```
You cannot combine currencies on a single customer. This customer has an active subscription, subscription schedule, discount, quote, or invoice item with currency eur. (invalid_request_error)
```

### To Reproduce

1. Enable Stripe Billing.
2. Enable logging.
3. Enable multi-currency.
4. Add at least one additional currency.
5. Access the store while logged into an account (e.g., your admin account).
6. Complete a purchase for a subscription product in one currency.
7. Reproduce step 5 while logged into the same account as step 4, but change the currency.
8. Note the `There was a problem` error.
9. Check the order and subscription notes.
10. Check the logs.

### Actual behavior
The error provided to the customer has zero indication as to why the payment failed, and there is no information surfaced to the merchant unless logging is enabled _and_ they access the logs.

### Screenshots
![blocks invalid request error](https://github.com/Automattic/woocommerce-payments/assets/82999806/a41db646-0396-4b08-8ef9-cc6fd2243ed0)

![order notes](https://github.com/Automattic/woocommerce-payments/assets/82999806/ccdec800-1dda-4a5b-b778-80c3214524c9)

![sub notes](https://github.com/Automattic/woocommerce-payments/assets/82999806/acb5853d-6298-44a2-8f2b-9109650c711d)

### Expected behavior
The `invalid_request_error` is surfaced to either the customer or the merchant in a way that is actionable.

**Comment by htdat** [comment]
This issue impacts "Multi-Currency" and " WC Payments Subscriptions", so assigning to team Fractal and Quark (based on team responsibilities Pc2DNy-3z-p2) cc team leads @bborman22 and @diegocurbelo,

Assigning as part of Gamma Triage process PcreKM-yM-p2.

**Comment by bborman22** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Fractal-62a0f7b955648b001e1f5e1f/issues/Automattic/woocommerce-payments/7732?planning-poker) with Zenhub @cesarcosta99 @lovo-h @rafaelzaleski @reykjalin @ricardo
