### ISSUE TITLE
Update banner notice to use the new modern component

### ISSUE THREAD

**Issue by bradyv** [Automattic/woocommerce-payments#7733]
Per my conversation with @daquinons, attached is a collection of places across WooPayments where we currently display the older low contrast banner notification, specifically when a store is in test mode. We should update these to use our modern notice components.
- Payments Overview
- WooPayments Settings
- Deposits list
- Deposit details
- Transactions list
- Transaction details

### Designs
Existing on the left, new on the right.

**Payments Overview**
![Payments Overview](https://github.com/Automattic/woocommerce-payments/assets/889872/ad29cffb-23f3-40f3-9b32-e8ad8c9179f2)
- `Ready to go live?` link should click through to WooPayments Settings

**Deposits list**
![Deposits](https://github.com/Automattic/woocommerce-payments/assets/889872/6656238a-b394-4bfe-824c-e830a1376241)

**Deposit details**
![Deposit details](https://github.com/Automattic/woocommerce-payments/assets/889872/9b2fa0b1-a4d9-4b39-a1d2-a9fd15d479b5)
- Replace the banner notice with an inline notice and place it in the deposit details card.

**Transactions list**
![Transactions](https://github.com/Automattic/woocommerce-payments/assets/889872/e43ada32-3f87-4463-84c6-4a7944c11063)

**Transaction details**
![Transaction details](https://github.com/Automattic/woocommerce-payments/assets/889872/b004426d-efe3-4aef-b900-1a3837720e7f)
- Replace the banner notice with an inline notice and place it in the payment details card.

**Comment by vladolaru** [comment]
The notices have already been updated to use the new components. I've created a small PR https://github.com/Automattic/woocommerce-payments/pull/8430 to tackle some inconsistencies for the transactions page.
