### ISSUE TITLE
In-Person Payment: transaction details are not rendering customer details corerctly

### ISSUE THREAD

**Issue by kalessil** [Automattic/woocommerce-payments#7740]
### Describe the bug

`PaymentDetailsSummary` component when renders `CustomerLink` supplying customer data from `charge.billing_details`. When billing details are not provided (In-Person Payments), the customer shall be rendered based on `charge.order` as fallback. Client shall also inject `customer_email` and `customer_name` into `charge.order` as well (currently, we have only `customer_url` what's not enough for the fallback) based on order meta-data (`customer_email`, `customer_name`, which In-Person Payments do provide).

**Comment by kalessil** [comment]
@malinajirka, can you please add a screenshot here? Thanks!

**Comment by malinajirka** [comment]
<img width="939" alt="Screenshot 2023-11-20 at 12 47 52" src="https://github.com/Automattic/woocommerce-payments/assets/2261188/2d0e729c-4563-4607-9f54-a38aeba4d646">

**Comment by kalessil** [comment]
@malinajirka: the fix, which should address the issue, is merged. In case you can try it out (do you need a snapshot of WooPayments, or perhaps you know how to create it locally?) Let me know if it works as expected for you, thanks!

**Comment by malinajirka** [comment]
Thanks @kalessil for the quick fix!

I can see the customer so the fix works as expected. 🙇 

I noticed a potential UI glitch though. When there is no customer assigned, before these changes there was `-` and the `Customer` title was aligned to the top. However, now the `-` is missing and the `Customer` title is centered vertically.

<img width="944" alt="Screenshot 2023-11-23 at 9 06 32" src="https://github.com/Automattic/woocommerce-payments/assets/2261188/407da217-9219-4790-bd89-1ecbb6ea5e2f">

**Comment by malinajirka** [comment]
O̶h̶h̶, I̶ j̶u̶s̶t̶ n̶o̶t̶i̶c̶e̶d̶ a̶n̶o̶t̶h̶e̶r̶ b̶u̶g̶ -̶ i̶t̶ s̶e̶e̶m̶s̶ t̶o̶ b̶e̶ r̶e̶c̶o̶r̶d̶e̶d̶ a̶s̶ `̶T̶a̶p̶ t̶o̶ P̶a̶y̶ o̶n̶ A̶n̶d̶r̶o̶i̶d̶`̶ e̶v̶e̶n̶ t̶h̶o̶u̶g̶h̶ i̶t̶ w̶a̶s̶ a̶ p̶a̶y̶m̶e̶n̶t̶ m̶a̶d̶e̶ w̶i̶t̶h̶ a̶ h̶a̶r̶d̶w̶a̶r̶e̶ c̶a̶r̶d̶ r̶e̶a̶d̶e̶r̶. L̶o̶o̶k̶i̶n̶g̶ a̶t̶ t̶h̶e̶ s̶c̶r̶e̶e̶n̶s̶h̶o̶t̶ 3̶ d̶a̶y̶s̶ a̶g̶o̶, i̶t̶ w̶a̶s̶ r̶e̶c̶o̶r̶d̶e̶d̶ c̶o̶r̶r̶e̶c̶t̶l̶y̶ t̶h̶e̶r̶e̶ =̶> c̶o̶u̶l̶d̶ t̶h̶e̶s̶e̶ c̶h̶a̶n̶g̶e̶s̶ a̶f̶f̶e̶c̶t̶ t̶h̶i̶s̶ b̶e̶h̶a̶v̶i̶o̶r̶ a̶s̶ w̶e̶l̶l̶ o̶r̶ p̶e̶r̶h̶a̶p̶s̶ I̶ w̶a̶s̶ u̶s̶i̶n̶g̶ a̶n̶ o̶u̶t̶d̶a̶t̶e̶d̶ v̶e̶r̶s̶i̶o̶n̶ w̶h̶e̶n̶ I̶ t̶o̶o̶k̶ t̶h̶e̶ s̶c̶r̶e̶e̶n̶s̶h̶o̶t̶ 3̶ d̶a̶y̶s̶ a̶g̶o̶ (̶I̶ c̶a̶n̶ s̶u̶b̶m̶i̶t̶ a̶ n̶e̶w̶ i̶s̶s̶u̶e̶ i̶f̶ i̶t̶'s̶ u̶n̶r̶e̶l̶a̶t̶e̶d̶ t̶o̶ t̶h̶i̶s̶ P̶R̶/I̶s̶s̶u̶e̶)̶?̶
False alarm - I clicked on a transaction made by someone else so it was indeed a TTP transaction.

**Comment by kalessil** [comment]
> I noticed a potential UI glitch though. When there is no customer assigned

Good catch. I'll create a new fix, no testing will be needed. Thanks for verifying.
