### ISSUE TITLE
Discounted fee details in tooltip do not match the discount shown in pill

### ISSUE THREAD

**Issue by csmcneill** [Automattic/woocommerce-payments#7750]
### Describe the bug

When onboarding with a discounted fee associated with an incentive, the discount is displayed properly in the pill, but the tooltip details that appear on mousehover do not show the discount.

This is similar to #5255 but this could be an issue that specifically affects discounted rates that are enabled due to an incentive. Flagging this to @nagpai since he's done a lot of work on fees, discounts, and how these pills display that information.

### To Reproduce

1. Onboard a WCPay account with discounted card fees associated with an incentive.
2. Navigate to **Payments > Settings.**
3. Mouseover the `Credit Debit card` pill with the discounted rate: `From x.xx% + $x.xx — see Terms and Conditions`
4. The additional details listed in the tooltip do not include the non-discounted `Base fee`; the normal, non-discounted base fee is listed instead.

### Actual behavior
The details of the discounted rate are not accurately displayed in the fee detail element, 

### Screenshots

My site qualifies for a 10% discount (2.61% + $0.27)...

![wcpay 10 discount](https://github.com/Automattic/woocommerce-payments/assets/82999806/92acabc2-58c4-4bf2-8000-937eeac258fc)

...but the base US fee of 2.9% + $0.30 displays in the tooltip:

![custom rate discrepancy](https://github.com/Automattic/woocommerce-payments/assets/82999806/3b9e1842-e75f-458f-8f4d-57fc66add2f9)

### Expected behavior
Custom rates are a part of the `Base fee` when viewing the fee details tooltip.

**Comment by htdat** [comment]
This issue impacts "Fees", so assigning to Pulsar (based on team responsibilities Pc2DNy-3z-p2) cc team lead @kalessil.

Assigning as part of Gamma Triage process PcreKM-yM-p2.

**Comment by kalessil** [comment]
Note: we need to use corrected values in the right side of breakdown, no chnages in UI, only values correction asp er discount.
