### ISSUE TITLE
WooPay save my info box contents misaligned on some sites

### ISSUE THREAD

**Issue by pierorocca** [Automattic/woocommerce-payments#7756]
Also reported for Yumi, which is on Blocks. 

Note the vertical misalignment and the tooltip misalignment. If the tooltip is removed, it renders correcly.
![image](https://github.com/Automattic/woocommerce-payments/assets/109928953/2422f324-d27b-4fc1-9b9d-d4f9a6f09d27)

**Comment by pierorocca** [comment]
cc @LCmry as you recently worked on the tooltip. Might need another iteration :)

**Comment by pierorocca** [comment]
cc @elizaan36

**Comment by LCmry** [comment]
What themes would be best to test for this? I have a probable fix, which I tested with the Chrome dev tools on Olivia Mark and seemed to work.

Add this `min-height: fit-content;` after this line
https://github.com/Automattic/woocommerce-payments/blob/7849b433722f0b6922cad32b158ba1cefec00af1/client/components/woopay/save-user/style.scss#L62

**Comment by pierorocca** [comment]
https://github.com/Automattic/woopay/issues/1854 @bborman22 had a good selection of themes that was used for button testing. I'd add in Tsubaki for Blocks as well at a minimum.

**Comment by LCmry** [comment]
Thanks for the reference, here's a list I am working on testing:
- Storefront
- Astra
- Botiga
- Minimalist eCommerce
- Neve
- Tsubaki

**Comment by LCmry** [comment]
Here's the info icon on trunk:
**Storefront**
<img width="476" alt="Screen Shot 2023-12-15 at 9 25 35 AM" src="https://github.com/Automattic/woocommerce-payments/assets/7651258/53497e98-83ca-4f89-a4b8-4b7893e88ddc">

**Astra**
<img width="505" alt="Screen Shot 2023-12-15 at 9 19 14 AM" src="https://github.com/Automattic/woocommerce-payments/assets/7651258/ad2aa814-1caf-4c14-9468-c6302eae5d75">

**Botiga**
<img width="513" alt="Screen Shot 2023-12-15 at 9 19 38 AM" src="https://github.com/Automattic/woocommerce-payments/assets/7651258/3dd9b63c-e316-4475-a5d2-99871c7bb3f1">

**Minimalist eCommerce**
<img width="1163" alt="Screen Shot 2023-12-15 at 9 20 15 AM" src="https://github.com/Automattic/woocommerce-payments/assets/7651258/8d1ea146-9e79-47e6-91b3-e74733105902">

**Neve**
<img width="475" alt="Screen Shot 2023-12-15 at 9 20 55 AM" src="https://github.com/Automattic/woocommerce-payments/assets/7651258/d3702031-cbd4-4c7d-9ff0-24f85f77fb84">

**Tsubaki**
<img width="340" alt="Screen Shot 2023-12-15 at 9 21 33 AM" src="https://github.com/Automattic/woocommerce-payments/assets/7651258/28a6b1d1-0f2a-49fb-8a00-c0e76adc5109">

It looks like Neve is the only one with some issues, though perhaps not quite what is described here. I can investigate that one, but also need to find a theme that displays this issue.

**Comment by pierorocca** [comment]
@LCmry why is Tsubaki so narrow? Could you paste in the full page for Tsubaki for extra clarity please?

**Comment by LCmry** [comment]
@pierorocca that was just the default after I activated it.
<img width="1340" alt="Screen Shot 2023-12-18 at 12 13 07 PM" src="https://github.com/Automattic/woocommerce-payments/assets/7651258/2b15c7e4-6cce-4ad1-98f0-25ce845a2029">

**Comment by pierorocca** [comment]
@LCmry that doesn't look right to me on Tsubaki. While it is two column the place order button, payments fields and save my info are supposed to be in the first column. Can you recheck your site and if necessary reset the theme?

![image](https://github.com/Automattic/woocommerce-payments/assets/109928953/b9003fbc-30af-427f-b07f-fddb06c8b20c)

**Comment by LCmry** [comment]
@pierorocca, I see, I was on the shortcode checkout and this must be the blocks checkout.
<img width="646" alt="Screen Shot 2024-01-05 at 5 35 26 AM" src="https://github.com/Automattic/woocommerce-payments/assets/7651258/4b0d0398-82cc-4361-b288-4c90f32a6402">

**Comment by pierorocca** [comment]
Cool thanks! Last request, what does it look like when checked?

**Comment by LCmry** [comment]
<img width="765" alt="Screen Shot 2024-01-05 at 10 19 04 AM" src="https://github.com/Automattic/woocommerce-payments/assets/7651258/d360b802-9d84-450e-9e67-9917a907aa62">

**Comment by LCmry** [comment]
@pierorocca I haven't seen themes yet that have this issue, so it's hard to make sure a possible fix works. Have you come across any others?

**Comment by pierorocca** [comment]
@LCmry I have not though I haven't been looking either.

**Comment by alefesouza** [comment]
@pierorocca since https://github.com/Automattic/woocommerce-payments/pull/8608 we do not have the border, WooPay logo and tooltip anymore, is it ok to close this issue?

![Screenshot 2024-06-10 at 9 30 27 PM](https://github.com/Automattic/woocommerce-payments/assets/1693223/115ef39e-c100-4945-97c3-e46a0eea02dd)

![Screenshot 2024-06-10 at 9 31 07 PM](https://github.com/Automattic/woocommerce-payments/assets/1693223/d64e3cb6-dd37-4ce8-a600-867b62d967c0)
