### ISSUE TITLE
Add Instant Deposits Support

### ISSUE THREAD

**Issue by DanReyLop** [Automattic/woocommerce-payments#776]
More context: paJDYF-6e-p2

**Comment by allendav** [comment]
And even more including things we need to consider paJDYF-Pl-p2

**Comment by dechov** [comment]
_Manual_ deposits would be a self-contained prerequisite issue here – do we plan to support those independently of instant deposits, or only for that case? cc @thenbrent

**Comment by thenbrent** [comment]
Good question @dechov. Not at this stage - I haven't seen any requests to make the deposit schedule manual.

Long term, I expect we will want to offer it for the small number of merchants who expect/require it. Instant Deposits will ship well before that day though.

/cc @LevinMedia

**Comment by DanReyLop** [comment]
Closing in favor of more focused issues. All of them are tagged using the `[Feature] Instant Deposits` label.
