### ISSUE TITLE
Align deposit status colour coding across pages

### ISSUE THREAD

**Issue by bradyv** [Automattic/woocommerce-payments#7761]
### Description
Presently we apply colour coding to deposit status differently depending on where they're displayed. It would be great to bring consistency to the visual cues and reduce some of the cognitive load of understanding deposits.

<img width="594" alt="Screenshot 2023-11-21 at 11 17 07" src="https://github.com/Automattic/woocommerce-payments/assets/889872/f7fb089a-9ac3-4cbd-add8-625207c328bb">

### Acceptance criteria
Consistent colours are used throughout WooPayments to represent disputes at each stage.

![Statuses](https://github.com/Automattic/woocommerce-payments/assets/889872/c181c018-2c0e-47b3-8a78-83368bcd14d5)
- Pending -> yellow
- In transit -> blue
- Paid -> green
- Failed -> red
- Canceled -> gray

**Comment by haszari** [comment]
Nice quick-fix. Not urgent but a great thing to tidy up so medium priority.

**Comment by naman03malhotra** [comment]
@bradyv can you please share the color codes you'd like us use for consistent visual behavior?

**Comment by haszari** [comment]
> can you please share the color codes you'd like us use for consistent visual behavior?

FYI @naman03malhotra @bradyv isn't working with us any longer (though maybe he'll reply as a civilian!)

I'd recommend using the existing colours – we already have colours in place, but we're just using them inconsistently. If there are gaps, feel free to find colours from elsewhere in the UI and/or colour schemes/libraries. 

@rogermattic  or @elizaan36 can advise and review, though there's no need to wait on design to start implementing! Possibly no need for design on this if we're using existing colours to make dispute status consistent across all UI/screens.

**Comment by naman03malhotra** [comment]
>I'd recommend using the existing colours – we already have colours in place, but we're just using them inconsistently

@haszari  My question largely is, if we have two variations of the same color which one to standardize. My step would be to find inconsistency in colors and ask design which one to pick.

**Comment by rogermattic** [comment]
> I'd recommend using the existing colours – we already have colours in place, but we're just using them inconsistently. If there are gaps, feel free to find colours from elsewhere in the UI and/or colour schemes/libraries.
> 
> @rogermattic or @elizaan36 can advise and review, though there's no need to wait on design to start implementing! Possibly no need for design on this if we're using existing colours to make dispute status consistent across all UI/screens.

1000% agree! Please use the existing colours.

> My question largely is, if we have two variations of the same color which one to standardize. My step would be to find inconsistency in colors and ask design which one to pick.

Would you be able to check the colours and the [style here in this Figma](https://www.figma.com/file/Kofpo8jj4zDWXDsVdlSz0f/WooCommerce-Admin-Design-Library?type=design&node-id=6538%3A47107&mode=dev)
