### ISSUE TITLE
Padding issue when Woo Core "Things to do next" banner is displayed

### ISSUE THREAD

**Issue by dmallory42** [Automattic/woocommerce-payments#7777]
### Description

There's a blue banner that gets added to every page when the user is in the middle of completing the Woo initial setup tasks. This has the effect of pushing the page content down, and means that the first component on the Payments page isn't getting a proper margin applied and is overlapping slightly.

<img width="1282" alt="Screenshot 2023-11-24 at 10 56 58" src="https://github.com/Automattic/woocommerce-payments/assets/11770181/6fea4dcb-b161-431c-aa54-ac98e23f70e1">

We should adjust our styling for the payments related pages to have a clear separation between the top bar and the first component in this case.

### Acceptance criteria

* Clear separation between the top bar and the rest of the content across Payments pages.

### Additional context

- This was discovered as a side effect of #7498.

**Comment by vbelolapotkov** [comment]
@anu-rock routing to you since it relates to onboarding. cc @vladolaru @timmy5685

**Comment by anu-rock** [comment]
@vbelolapotkov I see this is already in our backlog, but thanks for your ping.

**Comment by timmy5685** [comment]
@anu-rock guessing this one is an easy fix. Any chance we could get this knocked out in an upcoming sprint?

**Comment by vladolaru** [comment]
This is no longer an issue because it was fixed in the WooCommerce core 8.6.0 version via [this PR](https://github.com/woocommerce/woocommerce/pull/43020).

**Comment by timmy5685** [comment]
amazing - thanks for confirming @vladolaru!
