### ISSUE TITLE
Deposit details screen for a non-existing deposit renders a buggy UI with an unhelpful error message

### ISSUE THREAD

**Issue by Jinksi** [Automattic/woocommerce-payments#7785]
### Describe the bug

When viewing the deposit details screen for a non-existing deposit the UI shows an unhelpful error message, rather than a helpful and more accurate "deposit not found" message.

```
There was an error rendering this view. Please contact support for assistance if the problem persists.
TypeError: Cannot read properties of undefined (reading 'automatic')
```

### To Reproduce

1. Go to the deposit details screen for any previous deposit.
2. Remove a character from the deposit ID in the URL.
3. Observe the page.

### Actual behavior

When viewing the deposit details screen for a non-existing deposit, the page renders empty UI elements and `undefined` strings.

### Screenshots

<img width="1008" alt="Screenshot 2024-01-10 at 16 46 38" src="https://github.com/Automattic/woocommerce-payments/assets/3147296/2ca3959e-52ac-4225-a30b-4403b1e5cc8b">

### Expected behavior

When viewing the deposit details screen for a non-existing deposit, the page should render a helpful "not found" message and should not render the deposit transactions table.

**Comment by haszari** [comment]
> When viewing the deposit details screen for a non-existing deposit

How likely is this scenario @Jinksi ? I'm guessing that the chances of a merchant hitting this are low, but we should fix as a code tidy/tech debt/robust system thing.

**Comment by haszari** [comment]
Even though this is likely rare, it's not ideal that the error message asks merchant to contact support.
