### ISSUE TITLE
Provide billing name and email on Pay-for-Order and Add Payment Method pages

### ISSUE THREAD

**Issue by timur27** [Automattic/woocommerce-payments#7788]
### Describe the bug
Compared to the legacy card, legacy UPE & deferred intent creation UPE are not adding `name` and `email` to the `billing_address`. This leads to the customer name being empty in the transactions list.

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK29LQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--4a1296fc6a76e22bd9acb70f7f729d9d72b13bed/image.png)

### To Reproduce
1. Place order with a declined `4000000000000002` card
2. Navigate to `My account` -> `Orders` -> `Pay` and pay for the previously paid order
3. Open `Transactions` in the admin panel under `Payments -> Transactions` and confirm that `Customer` field is empty for this transaction's row

### Additional context
* [This implementation](https://github.com/Automattic/woocommerce-payments/blob/develop/client/checkout/classic/upe-deferred-intent-creation/payment-processing.js#L110-L138) should not check if the script is being run on the checkout page, but let script run on the pay-for-order and add-payment-method pages as well. Since billing fields can't be taken from the form on these pages, we should [fetch the fields from `wcpayCustomerData`](https://github.com/Automattic/woocommerce-payments/blob/6.8.0/client/checkout/classic/index.js#L50-L51) which comes from the back-end
* Check how it works [in the legacy card implementation](https://github.com/Automattic/woocommerce-payments/blob/6.8.0/client/checkout/classic/index.js#L356-L367), where [`generatePaymentMethodRequest`](https://github.com/Automattic/woocommerce-payments/blob/6.8.0/client/checkout/api/index.js#L140) sets [billing and address details](https://github.com/Automattic/woocommerce-payments/blob/6.8.0/client/checkout/api/index.js#L161-L196) by taking the name & email data from the `preparedCustomerData` which comes from the back-end for pay-for-order and add-payment-method pages
* This issue is assigned to the `low` priority since it's present in the legacy UPE and there haven't been any bug reports related to it.

**Comment by frosso** [comment]
Might have also been the case for Split UPE
