### ISSUE TITLE
Update Onboarding critical flows

### ISSUE THREAD

**Issue by oaratovskyi** [Automattic/woocommerce-payments#7794]
### Description
To improve coverage of the onboarding functionality by GlobalStep, we need to add/modify the following flows:
- Builder flow as a builder (not covered)
- Leave early as a merchant when starting the KYC (merchant happy path covered but not this edge case, this may be done as a part of the happy path)

### Additional context
p1701093017610729-slack-C03KTTK2YMA

**Comment by oaratovskyi** [comment]
Added new critical flow _Onboard as a builder_ https://github.com/Automattic/woocommerce-payments/wiki/Testing-instructions-for-critical-flows#onboard-via-payments-connect-as-a-builder
Updated current critical flow _Onboard via Payments Connect_ https://github.com/Automattic/woocommerce-payments/wiki/Testing-instructions-for-critical-flows#onboard-via-payments-connect

**Comment by vladolaru** [comment]
The updated CF and the new builder flow look good to me, Oleks. I would say ship it but it is already shipped 😅 Good work!
