### ISSUE TITLE
Pay-for-order flow and the first-party auth flow are incompatible

### ISSUE THREAD

**Issue by hsingyuc** [Automattic/woocommerce-payments#7796]
### Describe the bug
When we are on the pay-for-order page and hit the WooPay button, we are not using the first-party auth flow but the OTP iframe.

### To Reproduce
1. Create a Pre-Orders pay-for-order order
2. Go to the pay-for-order page and click on the WooPay button
3. See the OTP iframe

### Actual behavior
When we are on the pay-for-order page and hit the WooPay button, we are not using the first-party auth flow but the OTP iframe.

### Expected behavior
When we are on the pay-for-order page and hit the WooPay button, we should use the first-party auth flow, not the OTP iframe.

**Comment by RadoslavGeorgiev** [comment]
This issue impacts WooPay's express checkout buttons, so assigning to @Automattic/heisenberg  (based on team responsibilities Pc2DNy-3z-p2).

Assigning as part of Gamma Triage process PcreKM-yM-p2.

**Comment by frosso** [comment]
It looks like @hsingyuc 's got it, since it affects the pay-for-order flow on WooPay 👍
