### ISSUE TITLE
Duplicate wc_ajax_wcpay_add_to_cart endpoint is being overriden by WooPay

### ISSUE THREAD

**Issue by gpressutto5** [Automattic/woocommerce-payments#7801]
### Describe the bug
[WooPay button's wc_ajax_wcpay_add_to_cart](https://github.com/Automattic/woocommerce-payments/blob/69e52443a95eef5f9812d447992c7597dae42526/includes/class-wc-payments-woopay-button-handler.php#L128) endpoint is taking precedence and overriding [the endpoint that was meant to be used by Apple Pay](https://github.com/Automattic/woocommerce-payments/blob/69e52443a95eef5f9812d447992c7597dae42526/includes/class-wc-payments-payment-request-button-handler.php#L81). Currently this is not causing any bugs because both methods are identical, but it is confusing. These endpoints should be merged or one of them should be renamed to avoid conflicts.

### To Reproduce

1. Enable WooPay in your store.
2. Add `throw new \Exception('test');` as the first line of `WC_Payments_Payment_Request_Button_Handler::ajax_add_to_cart()`.
3. Check the network tab of your browser's devtools, use the Apple Pay button and notice the call to `wc_ajax_wcpay_add_to_cart` was succesfull.
4. Add the same exception to `WC_Payments_WooPay_Button_Handler::ajax_add_to_cart()`.
5. Repeat step 3 and notice the request fails.

**Comment by RadoslavGeorgiev** [comment]
Might be related to https://github.com/Automattic/woocommerce-payments/issues/7588.

This issue impacts "Additional Payment Methods (including Apple Pay / Google Pay)", so assigning to Heisenberg (based on team responsibilities Pc2DNy-3z-p2) cc team lead @frosso, similar to the related issue.

Assigning as part of Gamma Triage process PcreKM-yM-p2.
