### ISSUE TITLE
Misleading dev mode message when onboarding as a live account

### ISSUE THREAD

**Issue by dmallory42** [Automattic/woocommerce-payments#7803]
### Describe the bug

Follow on from #7768

As mentioned by @daquinons https://github.com/Automattic/woocommerce-payments/pull/7768#issuecomment-1831163066, there is a misleading prompt if the user is in dev mode but onboards a "live" account. We should update the logic to catch this corner case and either hide this message or show a different message, because in this case, the account is being treated by the system as if it is a live account, NOT a dev account, and therefore nothing happens when the button is clicked.

This is only affecting dev mode accounts (using dev tools plugin), so it wouldn't be a problem for merchants, it's just a bit confusing for devs.

### Expected behaviour

As mentioned on Slack:

> If Dev mode is enabled and I click on “live account”, a dev mode account is created
> If I click on Set up payments, the account is deleted and I’m redirected to the onboarding again
> If I click on live mode, a new dev mode account will be created, and that’s expected (we have an info banner for it)

**Comment by RadoslavGeorgiev** [comment]
@dmallory42 / @daquinons is this something that Sigma or Moltres is planning to or already working on? cc @Automattic/harmony as this is regarding Dev Tools.

**Comment by dmallory42** [comment]
@RadoslavGeorgiev - yes, this is low priority but we'll look to address it when we have time because it relates to the onboarding flow under our area of responsibility. 🙂

**Comment by zmaglica** [comment]
Based on the previous comments, will Molters work on this issue @daquinons ? If not, I can put it in Gamma backlog or ping another team?

**Comment by daquinons** [comment]
@zmaglica Thanks for the ping. This is an edge case happening only with the dev tools enabled. It's definitely related to onboarding, and it's in our backlog :) The priority is extremely low, though.

**Comment by zmaglica** [comment]
Thank you for commenting @daquinons . I will move this issue to Other Team Queue as a porter

**Comment by oaratovskyi** [comment]
I think it's not relevant anymore
since we show this popup
> Sandbox mode is enabled, only test accounts will be created. If you want to process live transactions, please [disable it](https://woocommerce.com/document/woopayments/testing-and-troubleshooting/sandbox-mode/).

**Comment by vladolaru** [comment]
I have tackled it in [this PR](https://github.com/Automattic/woocommerce-payments/pull/9105) to make sure the expected behavior is met.
