### ISSUE TITLE
The styling of the advanced filters dropdown is not displaying correctly

### ISSUE THREAD

**Issue by mordeth** [Automattic/woocommerce-payments#7808]
### Describe the bug
Lately, we've observed issues with the dropdown styling in advanced filters. There haven't been any recent UI changes that could have caused these issues. We suspect it may be a result of a recent update to a component.

### To Reproduce
- Go to Payments -> Transactions.
- Apply any Advanced filter.
- Confirm that the filter dropdown width is incorrect when the "Add a filter" button is clicked.

### Actual behavior
![image](https://github.com/Automattic/woocommerce-payments/assets/8667118/98ad692d-88e3-4355-b245-ac5512985cad)

### Expected behavior
![image](https://github.com/Automattic/woocommerce-payments/assets/8667118/74e90cba-968a-46c8-9c55-f93dade187b9)

**Comment by mordeth** [comment]
After conducting an investigation, I found that the problem stems from WordPress 6.4.1. This issue affects both WooPayments and WooCommerce. It would be logical to address the styling issues in the WooCommerce core.

**Comment by anu-rock** [comment]
@mordeth What's the recommended course of action? Based on your comment above, is it to open an issue in WC and close this one?

**Comment by mordeth** [comment]
I have raised an [issue in the WooCommerce repository](https://github.com/woocommerce/woocommerce/issues/41863) since the resolution needs to be addressed there.
