### ISSUE TITLE
Incorrect test mode notice when left KYC early after going live from builder

### ISSUE THREAD

**Issue by oaratovskyi** [Automattic/woocommerce-payments#7819]
### Describe the bug
In a specific scenario, there is a bug with test mode notice when it shows account is in test mode but it's not.

### To Reproduce

1. Disable dev tools locally
2. Onboard a builder account
3. Go live from builder account (you can use dev mode notice), leave at the address and dob step
4. Visit payments overview page

### Actual behavior
There is a test mode notice

### Screenshots
<img width="602" alt="image" src="https://github.com/Automattic/woocommerce-payments/assets/79862886/5b86caee-5f15-4b60-a040-7a9344fa2b6a">

### Expected behavior
There shouldn't be test mode notice

### Dev notes
it returns gateway test mode = true here
https://github.com/Automattic/woocommerce-payments/blob/4b395bc5c70de6974d8c36e56a30c1ddee1c1627/includes/core/class-mode.php#L72-L72
so this var is set to true [https://github.com/Automattic/woocommerce-payments/blob/4b395bc5c70de6974d8c36e56a30c1ddee1c1627/includes/admin/class-wc-payments-admin.php#L8[…]802](https://github.com/Automattic/woocommerce-payments/blob/4b395bc5c70de6974d8c36e56a30c1ddee1c1627/includes/admin/class-wc-payments-admin.php#L802-L802)
and returned true in [https://github.com/Automattic/woocommerce-payments/blob/4b395bc5c70de6974d8c36e56a30c1ddee1c1627/includes/admin/class-wc-payments-admin.php#L8[…]830](https://github.com/Automattic/woocommerce-payments/blob/4b395bc5c70de6974d8c36e56a30c1ddee1c1627/includes/admin/class-wc-payments-admin.php#L830-L830)

in terms of gateway test_mode value is changed to false - it's done in the finalize_connection [method](https://github.com/Automattic/woocommerce-payments/blob/4b395bc5c70de6974d8c36e56a30c1ddee1c1627/includes/class-wc-payments-account.php#L1446-L1446) that is run in the end
we may want to do this when going from builder to live

p1701438490357639/1701430936.263369-slack-C03KTTK2YMA

**Comment by daquinons** [comment]
Needing the dev tools and the movement from flows in order to reproduce it makes the impact of the issue as low impact and priority
