### ISSUE TITLE
Compatibility with Woo Stripe Gateway - "Your payment information is incomplete." error on /order-pay/ checkout flow

### ISSUE THREAD

**Issue by Brianmitchtay** [Automattic/woocommerce-payments#7824]
### Describe the bug

When the WooCommerce Stripe payment gateway is enabled and 

### To Reproduce

1. On a test site with a WooPayments account attached, install and configure the Woo Stripe Payment plugin. Leave the Stripe gateway disabled, the plugin active.
2. Create a manual order for a guest - with no customer attached nor billing information in the order
3. Check in **WP Admin → WooCommerce → Settings → Accounts & Privacy** that "Allow customers to place orders without an account: is **checked**
4. Visit the customer payment link from the manually created order, enter test card payment information in the WooPayments checkout form and try to submit.
5. See error
6. Disable the Stripe plugin then try again
7. Error no longer occurs and payment processes successfully

### Actual behavior

While the Stripe payment gateway plugin is active on the site, the `/order-pay/` flow does not function and throws an error.

### Screenshots

![Screenshot 2023-12-03 at 7 17 28 PM](https://github.com/Automattic/woocommerce-payments/assets/45057772/56d36dbc-14ad-482d-8af6-b5f2d233a727)

### Expected behavior

Ideally, payment processes should function whether or not a merchant has the Stripe gateway installed and active on the site as well

### Desktop (please complete the following information):

* OS: MacOS 14.0 (23A344)
* Browser Chrome
* Version 119.0.6045.199 (Official Build) (arm64)

### Additional context

This was brought to our attention in 7399911-zd-a8c

**Comment by c-shultz** [comment]
While addressing the bug here may be necessary, I would recommend we take a bigger picture look at this to consider if we could better educate the merchant about potentially conflicting payment gateways being enabled alongside each other.

**Comment by jessy-p** [comment]
This issue impacts Checkout UI, so assigning to Heisenberg (based on team responsibilities Pc2DNy-3z-p2) @FangedParakeet. Assigning as part of Gamma Triage process PcreKM-yM-p2.

**Comment by mdmoore** [comment]
Hey @Brianmitchtay! Thanks for including detailed reproduction steps in your report. Do you recall the WooPayments and Woo Stripe versions used in your tests? I haven't been able to reproduce the on the latest versions of both plugins. It's possible that it's been fixed with some recent changes to either plugin, but I'd like to try reproducing with versions matching your tests.

**Comment by mdmoore** [comment]
Trying further to reproduce the problem here, I tested using Woo Stripe 7.7.0 and WooPayments 6.8.0, WooCommerce 8.3.1, while using a block based theme(Twenty Twenty-Three). First I've ensured that Woo Stripe is active but disabled. I've then created a guest order with no address details then proceeded to the customer payment page, both logged in and logged out. So far, all test payments have processed successfully and the error described here hasn't shown up.

I'll close this for now, but if you're still able to reproduce it, please re-open and we can pin down the exact conditions.

**Comment by Brianmitchtay** [comment]
Hi @mdmoore thanks for following up. I can still replicate. 

The user was running:

- WooCommerce Stripe Gateway: by WooCommerce – 7.7.0
- WooPayments: by Automattic – 6.8.0
- WooCommerce: by Automattic – 8.3.1

Like you had in your tests.

However I just tested again and can still replicate with the following (latest) versions on my testing site.

WooCommerce Stripe Gateway: by WooCommerce – 7.9.0
WooPayments: by Automattic – 7.1.0
WooCommerce: by Automattic – 8.5.2

I fully acknowledge that this testing site has been used for a lot. So I'll also set up a clean Jurassic Ninja site to confirm.

<img width="819" alt="Screenshot 2024-01-28 at 4 26 09 PM" src="https://github.com/Automattic/woocommerce-payments/assets/45057772/d97f56f5-3182-4135-9a67-7b8e717fb67a">

SSR enclosed
<details> `
### WordPress Environment ###

WordPress address (URL): https://woolivetesttesttest.mystagingwebsite.com
Site address (URL): https://woolivetesttesttest.mystagingwebsite.com
WC Version: 8.5.2
REST API Version: ✔ 8.5.2
WC Blocks Version: ✔ 11.8.0-dev
Action Scheduler Version: ✔ 3.7.1
Log Directory Writable: ✔
WP Version: 6.4.2
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US
External object cache: ✔

### Server Environment ###

Server Info: nginx
PHP Version: 8.1.27
PHP Post Max Size: 2 GB
PHP Time Limit: 1200
PHP Max Input Vars: 6144
cURL Version: 8.4.0
OpenSSL/1.1.1n

SUHOSIN Installed: –
MySQL Version: 10.4.26-MariaDB-log
Max Upload Size: 2 GB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 8.5.2
WC Database Prefix: wp_
Total Database Size: 26241.84MB
Database Data Size: 17121.07MB
Database Index Size: 9120.77MB
wp_woocommerce_sessions: Data: 0.05MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.14MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 1.52MB + Index: 1.91MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 4999.00MB + Index: 15.55MB + Engine InnoDB
wp_actionscheduler_actions: Data: 7667.05MB + Index: 6213.88MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 4410.27MB + Index: 2847.92MB + Engine InnoDB
wp_advanced_notifications: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_advanced_notification_triggers: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_afwc_campaigns: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_afwc_commission_plans: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_afwc_hits: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_afwc_payout_orders: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_afwc_referrals: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_automatewoo_abandoned_carts: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_automatewoo_customers: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_automatewoo_customer_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_automatewoo_guests: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_automatewoo_guest_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_automatewoo_logs: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_automatewoo_log_meta: Data: 0.06MB + Index: 0.03MB + Engine InnoDB
wp_automatewoo_queue: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_automatewoo_queue_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_automatewoo_referrals: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_automatewoo_referral_advocate_keys: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_automatewoo_referral_invites: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 1.52MB + Index: 0.58MB + Engine InnoDB
wp_followup_coupons: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_followup_coupon_logs: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_followup_customers: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_followup_customer_carts: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_followup_customer_orders: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_followup_email_logs: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_followup_email_orders: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_followup_subscribers: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_followup_subscribers_to_lists: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_gla_attribute_mapping_rules: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_gla_budget_recommendations: Data: 0.22MB + Index: 0.14MB + Engine InnoDB
wp_gla_merchant_issues: Data: 0.13MB + Index: 0.00MB + Engine InnoDB
wp_gla_shipping_rates: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_gla_shipping_times: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_jetpack_sync_queue: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailchimp_jobs: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_mailpoet_automations: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_mailpoet_automation_runs: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_mailpoet_automation_run_logs: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_mailpoet_automation_run_subjects: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_mailpoet_automation_triggers: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_mailpoet_automation_versions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_custom_fields: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_dynamic_segment_filters: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_feature_flags: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_forms: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_mailpoet_log: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_mailpoet_mapping_to_external_entities: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_migrations: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_newsletters: Data: 0.09MB + Index: 0.05MB + Engine InnoDB
wp_mailpoet_newsletter_links: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_mailpoet_newsletter_option: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_newsletter_option_fields: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_newsletter_posts: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_newsletter_segment: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_newsletter_templates: Data: 2.52MB + Index: 0.00MB + Engine InnoDB
wp_mailpoet_scheduled_tasks: Data: 0.14MB + Index: 0.11MB + Engine InnoDB
wp_mailpoet_scheduled_task_subscribers: Data: 0.05MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_segments: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_mailpoet_sending_queues: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_mailpoet_settings: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_statistics_bounces: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_mailpoet_statistics_clicks: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_mailpoet_statistics_forms: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_statistics_newsletters: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_mailpoet_statistics_opens: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_mailpoet_statistics_unsubscribes: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_mailpoet_statistics_woocommerce_purchases: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_mailpoet_stats_notifications: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_mailpoet_subscribers: Data: 0.02MB + Index: 0.23MB + Engine InnoDB
wp_mailpoet_subscriber_custom_field: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_subscriber_ips: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_subscriber_segment: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_mailpoet_subscriber_tag: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_mailpoet_tags: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_user_agents: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_user_flags: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_options: Data: 3.16MB + Index: 0.17MB + Engine InnoDB
wp_pmxe_exports: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_pmxe_google_cats: Data: 0.39MB + Index: 0.00MB + Engine InnoDB
wp_pmxe_posts: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_pmxe_templates: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_postmeta: Data: 21.34MB + Index: 29.25MB + Engine InnoDB
wp_posts: Data: 1.38MB + Index: 0.44MB + Engine InnoDB
wp_premmerce_bundles: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_premmerce_bundles_products: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_rank_math_analytics_gsc: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_rank_math_internal_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_rank_math_internal_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_snippets: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_termmeta: Data: 0.05MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_term_relationships: Data: 0.13MB + Index: 0.11MB + Engine InnoDB
wp_term_taxonomy: Data: 0.05MB + Index: 0.03MB + Engine InnoDB
wp_trp_gettext_en_us: Data: 1.52MB + Index: 0.80MB + Engine InnoDB
wp_trp_gettext_original_meta: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_trp_gettext_original_strings: Data: 1.52MB + Index: 0.47MB + Engine InnoDB
wp_usermeta: Data: 0.17MB + Index: 0.11MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wcpv_commissions: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wcpv_per_product_shipping_rules: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wcs_payment_retries: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.08MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.08MB + Index: 0.02MB + Engine InnoDB
wp_wc_bookings_availability: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_bookings_availabilitymeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_booking_relationships: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_deposits_payment_plans: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_deposits_payment_plans_schedule: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_orders: Data: 0.34MB + Index: 0.39MB + Engine InnoDB
wp_wc_orders_meta: Data: 1.52MB + Index: 3.03MB + Engine InnoDB
wp_wc_order_addresses: Data: 0.20MB + Index: 0.31MB + Engine InnoDB
wp_wc_order_bundle_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_order_composite_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_operational_data: Data: 0.14MB + Index: 0.09MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.13MB + Index: 0.16MB + Engine InnoDB
wp_wc_order_stats: Data: 0.09MB + Index: 0.08MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.08MB + Index: 0.03MB + Engine InnoDB
wp_wc_points_rewards_user_points: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_points_rewards_user_points_log: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_product_attributes_lookup: Data: 0.23MB + Index: 0.22MB + Engine InnoDB
wp_wc_product_download_directories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.17MB + Index: 0.33MB + Engine InnoDB
wp_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_bis_activity: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_woocommerce_bis_notifications: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_woocommerce_bis_notificationsmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_bundled_itemmeta: Data: 0.08MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_bundled_items: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_exported_csv_items: Data: 1.52MB + Index: 0.05MB + Engine InnoDB
wp_woocommerce_gc_activity: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_gc_cards: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_gc_cardsmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_per_product_shipping_rules: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_prl_deploymentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_prl_deployments: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_prl_frequencies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_prl_generator_queue: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_prl_tracking_conversions: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_woocommerce_shipping_table_rates: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_square_customers: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpml_mails: Data: 1.02MB + Index: 0.00MB + Engine InnoDB
wp_wpstg_queue: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wp_phpmyadmin_extension__errors_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wt_iew_action_history: Data: 0.05MB + Index: 0.00MB + Engine InnoDB
wp_wt_iew_cron: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wt_iew_ftp: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wt_iew_mapping_template: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_yoast_indexable: Data: 0.11MB + Index: 0.09MB + Engine InnoDB
wp_yoast_indexable_hierarchy: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_yoast_seo_links: Data: 0.02MB + Index: 0.03MB + Engine InnoDB

### Post Type Counts ###

addify_whp: 1
af_disc_p_rules: 1
attachment: 260
aw_workflow: 43
bookable_person: 4
bookable_resource: 13
csp_rules: 1
custom_css: 1
efw_fees: 5
enr_subsc_plan: 2
event_ticket: 23
follow_up_email: 6
global_product_addon: 1
mailpoet_page: 1
nav_menu_item: 13
oembed_cache: 1
page: 24
post: 1
prl_engine: 1
product: 196
product_variation: 392
revision: 84
shipping_package: 1
shop_coupon: 41
shop_order: 880
shop_order_refund: 16
shop_subscription: 121
wcpf_item: 4
wcpf_project: 1
wc_booking: 27
wc_membership_plan: 7
wc_order_status: 12
wc_stamps_label: 1
wc_user_membership: 4
wp_global_styles: 4
wp_navigation: 3
wp_template: 2

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (3) ###

WooCommerce Stripe Gateway: by WooCommerce – 7.9.0
WooPayments: by Automattic – 7.1.0
WooCommerce: by Automattic – 8.5.2

### Inactive Plugins (79) ###

Akismet Anti-spam: Spam Protection: by Automattic - Anti-spam Team – 5.3.1
Allow Editing of 'vendor' path in plugin editor: by Hiro – 0.1b
AutomateWoo: by WooCommerce – 6.0.13
AutomateWoo - Refer A Friend Add-on: by WooCommerce – 2.6.7 (update to version 2.7.14 is available)
Bookings Helper: by WooCommerce – 1.0.3
Braintree for WooCommerce Payment Gateway: by WooCommerce – 3.0.8 (update to version 3.1.2 is available)
Classic Editor: by WordPress Contributors – 1.6.3
Classic Widgets: by WordPress Contributors – 0.3
Code Snippets: by Code Snippets Pro – 3.6.2
Facebook for WooCommerce: by Facebook – 3.1.3
Frequently Bought Together: by Premmerce – 1.0.2
Google Listings and Ads: by WooCommerce – 2.5.12
Health Check & Troubleshooting: by The WordPress.org community – 1.7.0
Jetpack: by Automattic – 13.1-a.7
Loco Translate: by Tim Whitlock – 2.6.6
MailPoet: by MailPoet – 4.41.2
MailPoet Premium: by MailPoet – 4.35.0
Order Export & Order Import for WooCommerce: by WebToffee – 2.4.7
Order Export for WooCommerce: by JEM Plugins – 3.21
Post Meta Viewer: by Yongki Agustinus – 2.0
Product Bundles - Bulk Discounts: by SomewhereWarm – 1.4.0
Product Bundles - Variation Bundles: by franticpsyx – 1.1.4
Product Filters for WooCommerce: by WooCommerce – 1.3.2 (update to version 1.4.20 is available)
Query Monitor: by John Blackbourn – 3.15.0
String Locator: by InstaWP – 2.6.3
WCS staging: by mb – 1.0
WooCommerce - ShipStation Integration: by WooCommerce – 4.3.9
WooCommerce Accommodation Bookings: by WooCommerce – 1.2.1 (update to version 1.2.3 is available)
WooCommerce Additional Variation Images: by WooCommerce – 2.3.0 (update to version 2.3.2 is available)
WooCommerce Advanced Notifications: by WooCommerce – 1.3.1 (update to version 1.4.3 is available)
WooCommerce Affirm Gateway: by WooCommerce – 2.0.0 (update to version 2.3.0 is available)
WooCommerce All Products For Subscriptions: by WooCommerce – 4.1.3 (update to version 4.1.5 is available)
WooCommerce Back In Stock Notifications: by WooCommerce – 1.4.0 (update to version 1.6.7 is available)
WooCommerce Blocks: by Automattic – 11.5.1
WooCommerce Bookings: by WooCommerce – 2.0.3 (update to version 2.0.8 is available)
WooCommerce Bookings Availability: by WooCommerce – 1.1.20
WooCommerce Box Office: by WooCommerce – 1.1.50 (update to version 1.2.4 is available)
WooCommerce Brands: by WooCommerce – 1.6.46 (update to version 1.6.63 is available)
WooCommerce Bulk Stock Management: by WooCommerce – 2.2.34 (update to version 2.2.35 is available)
WooCommerce Checkout Field Editor: by WooCommerce – 1.7.8 (update to version 1.7.12 is available)
WooCommerce Composite Products: by WooCommerce – 8.10.4 (update to version 8.10.5 is available)
WooCommerce Conditional Shipping and Payments: by WooCommerce – 1.15.4 (update to version 1.15.5 is available)
WooCommerce Customer/Order/Coupon Export: by SkyVerge – 5.5.0
WooCommerce Distance Rate Shipping: by WooCommerce – 1.3.3 (update to version 1.3.5 is available)
WooCommerce Eway Payment Gateway: by WooCommerce – 3.7.1 (update to version 3.7.2 is available)
WooCommerce FedEx Shipping: by WooCommerce – 3.7.3 (update to version 3.8.7 is available)
WooCommerce Force Sells: by WooCommerce – 1.1.30 (update to version 1.4.0 is available)
WooCommerce Gift Cards: by WooCommerce – 1.16.3 (update to version 1.16.9 is available)
WooCommerce GoCardless Gateway: by WooCommerce – 2.5.3 (update to version 2.6.2 is available)
WooCommerce Min/Max Quantities: by WooCommerce – 4.1.0 (update to version 4.1.4 is available)
WooCommerce One Page Checkout: by Automattic – 1.9.7 (update to version 2.8.1 is available)
WooCommerce Order Barcodes: by WooCommerce – 1.6.0 (update to version 1.7.3 is available)
WooCommerce Order Status Logger: by @billrobbins – 0.1
WooCommerce Payfast Gateway: by WooCommerce – 1.5.9 (update to version 1.6.1 is available)
WooCommerce PayPal Payments: by WooCommerce – 2.4.0 (update to version 2.5.1 is available)
WooCommerce PDF Watermark: by WooCommerce – 1.4 (update to version 1.6.3 is available)
WooCommerce Points and Rewards: by WooCommerce – 1.7.8 (update to version 1.7.47 is available)
WooCommerce Pre-Orders: by WooCommerce – 2.0.8
WooCommerce Product Add-ons: by WooCommerce – 6.5.0 (update to version 6.6.0 is available)
WooCommerce Product Bundles: by WooCommerce – 6.22.3 (update to version 6.22.6 is available)
WooCommerce Product CSV Import Suite: by WooCommerce – 1.10.59 (update to version 1.10.67 is available)
WooCommerce Product Recommendations: by WooCommerce – 3.0.3 (update to version 3.0.5 is available)
WooCommerce Product Vendors: by WooCommerce – 2.1.71 (update to version 2.2.5 is available)
WooCommerce Purchase Order Payment Gateway: by WooCommerce – 1.4.2 (update to version 1.4.6 is available)
WooCommerce Shipment Tracking: by WooCommerce – 2.4.3
WooCommerce Shipping Per Product v2: by WooCommerce – 2.5.0 (update to version 2.5.5 is available)
WooCommerce Ship to Multiple Addresses: by WooCommerce – 3.8.0 (update to version 4.0.0 is available)
WooCommerce Square: by WooCommerce – 4.3.1 (update to version 4.4.1 is available)
WooCommerce Square Helper: by WooCommerce – 1.1
WooCommerce Stamps.com API integration: by WooCommerce – 1.9.0 (update to version 1.9.7 is available)
WooCommerce Subscriptions - Preserve Billing Schedule: by Prospress Inc. – 1.0.0
WooCommerce Subscriptions Gifting: by WooCommerce – 2.5.1 (update to version 2.7.0 is available)
WooCommerce Table Rate Shipping: by WooCommerce – 3.1.3 (update to version 3.1.6 is available)
WooCommerce UPS Shipping: by WooCommerce – 3.5.7
WooCommerce USPS Shipping: by WooCommerce – 4.7.5 (update to version 4.7.6 is available)
WooCommerce Xero Integration: by WooCommerce – 1.7.58 (update to version 1.8.4 is available)
Woo Subscriptions: by WooCommerce – 5.7.0 (update to version 5.9.1 is available)
WP Crontrol: by John Blackbourn & crontributors – 1.16.0
WP Mail Logging: by WP Mail Logging Team – 1.12.0

### Dropin Plugins (2) ###

advanced-cache.php: advanced-cache.php
object-cache.php: Memcached

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: USD ($)
Currency Position: right
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: accommodation-booking (accommodation-booking)
booking (booking)
bundle (bundle)
composite (composite)
external (external)
grouped (grouped)
mix and match (mix-and-match)
simple (simple)
subscription (subscription)
variable (variable)
variable subscription (variable-subscription)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to Woo.com: ✔
Enforce Approved Product Download Directories: –
HPOS feature screen enabled: –
HPOS feature enabled: –
Order datastore: WC_Order_Data_Store_CPT
HPOS data sync enabled: ✔

### WC Pages ###

Shop base: #5 - /shop/
Cart: #6 - /cart/
Checkout: #7 - /checkout-block/
My account: #8 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Storefront
Version: 4.5.4
Author URL: https://woo.com/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### WooPayments ###

Version: 7.1.0
Connected to WPCOM: Yes
WPCOM Blog ID: 206058563
Account ID: acct_1Kv91A2Hvd3W6TTd
Payment Gateway: Enabled
Test Mode: Enabled
Enabled APMs: card
WooPay: Enabled (checkout,product,cart)
WooPay Incompatible Extensions: No
Apple Pay / Google Pay: Disabled
Fraud Protection Level: basic
Multi-currency: Disabled
Public Key Encryption: Enabled
Auth and Capture: Enabled
Documents: Disabled
Logging: Enabled

### Admin ###

Enabled Features: activity-panels
analytics
product-block-editor
coupons
core-profiler
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
product-variation-management
product-virtual-downloadable
product-external-affiliate
product-grouped
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: customize-store
minified-js
new-product-management-experience
product-linked
settings
async-product-editor-category-field

Daily Cron: ✔ Next scheduled: 2024-01-29 18:57:50 -09:00
Options: ✔
Notes: 171
Onboarding: completed

### Action Scheduler ###

Complete: 24,180,603
Oldest: 2023-10-02 23:20:44 -0800
Newest: 2024-01-28 14:28:35 -0900

Pending: 16
Oldest: 2024-01-28 14:29:01 -0900
Newest: 2028-03-06 14:16:06 -0900

In-progress: 1
Oldest: –
Newest: –

Failed: 14,423
Oldest: 2022-05-23 11:43:49 -0800
Newest: 2024-01-28 09:18:37 -0900


### Status report information ###

Generated at: 2024-01-28 14:28:35 -09:00
`</details>

**Comment by Brianmitchtay** [comment]
A few updates here. This must be some kind of deeper conflict on the site I was using to test.

- I can replicate using just the Direct Bank transfer payment method on my testing site
-  I can't replicate at all on a clean Jurassic Ninja site.

I'll close this issue back up now. If anything it seems it likely would need to be re-opened in the Stripe repo if we're able to determine the deeper cause of the conflict

**Comment by mdmoore** [comment]
Thanks for taking the time to test so thoroughly @Brianmitchtay! Feel free to re-open here as well if WooPayments is involved.
