### ISSUE TITLE
Document deposits REST API endpoints

### ISSUE THREAD

**Issue by Jinksi** [Automattic/woocommerce-payments#7839]
Documentation for deposits should be added to the existing docs in [`/docs/rest-api/source/includes/wp-api-v3/`](https://github.com/Automattic/woocommerce-payments/blob/bb63e3c163b076d568ec3319f899943158a35032/docs/rest-api/source/includes/wp-api-v3/).

See existing public-facing documentation [here](https://automattic.github.io/woocommerce-payments/#introduction).

- A followup issue #7847 will update docs with params and endpoints related to coupled deposits that are to be deprecated

**Comment by haszari** [comment]
Thanks @Jinksi ! This will be very handy to get us all on the same page about the baseline "before" state of the deposits APIs. Then we can be explicit about what we want to change, deprecate etc.

**Comment by Jinksi** [comment]
> Then we can be explicit about what we want to change, deprecate etc.

See #7848 for these API docs updated with proposed changes.

**Comment by Jinksi** [comment]
Removed from 7.1 milestone since this was released in 7.0
