### ISSUE TITLE
Instant deposit button does not disappear after an instant deposit is created

### ISSUE THREAD

**Issue by shendy-a8c** [Automattic/woocommerce-payments#7841]
### Describe the bug

Currently, the daily limit for instant deposit is USD 1k. After creating an instant deposit, the button does not go away, so it's clickable again which will gives a generic error without explanation.

### To Reproduce

1. [Be eligible for instant deposit](https://woo.com/document/woopayments/deposits/instant-deposits/#eligibility-requirements).
2. Purchase a product so balance is USD 2k.
3. Open Payments > Overview page.
4. Confirm 'Deposit available funds' button shows up.
5. Click that button will bring up a modal.
6. Click the main CTA, the 'Deposit $xx now' button. Notice that the amount must be USD ~1k as that's the instant deposit's daily limit.
7. A success message will show at the bottom left. An instant deposit has been created.

### Actual behavior

The 'Deposit available funds' button still shows up. After a refresh, it will be gone.

### Expected behavior

The 'Deposit available funds' should disappear if merchant can no longer create an instant deposit.

ps: it's not always the case that the button should disappear after being clicked. We need to check with server if merchant is still eligible and has instant balance to be deposited.

**Comment by Jinksi** [comment]
Related to #7829 and may be fixed by #7830, since `deposits/overview-all` `balances.instant.available` will be refreshed and the **deposit funds** button will no longer render unless it is eligible to.
