### ISSUE TITLE
CSVs are not localized if sent via email

### ISSUE THREAD

**Issue by csmcneill** [Automattic/woocommerce-payments#7843]
### Describe the bug

When CSVs for deposits, transactions, and disputes are small enough to be downloaded directly from wp-admin, the language in the CSV will match the site's language if it is set to something that is not English. 

However, if a site's language is set to something other than English and a CSV is large enough that it is sent to the user via email, the resulting CSV is in English regardless of the site's language.

### To Reproduce

1. Ensure the site language is set to a non-English language (e.g., Español).
2. Isolate a small dataset of deposits, transactions, or disputes.
3. Download a CSV of the information.
4. Note that the details are localized (e.g., headings and statuses are in the site language as expected).
5. Expand the dataset from step 2 (or find a new dataset) so that it is too large for downloading from wp-admin.
6. Repeat step 3.
7. Check your email.
8. Download the CSV.
9. Note that the CSV is not localized (e.g., headings and statuses are **not** in the site language).

### Actual behavior

When downloading larger datasets as a CSV, the information is not localized. This creates a lack of parity in the experience when downloading smaller datasets directly from wp-admin. This also negatively affects merchants who primarily use non-English languages when generating or managing reports.

### Screenshots

Localized, small CSV downloaded directly from wp-admin with a site language of `Español`:

![localized csv](https://github.com/Automattic/woocommerce-payments/assets/82999806/20434ab3-84fb-4391-9fc4-2eb52a5fcd2a)

Larger CSV from the same `Español` site that is emailed and is not localized:

![non-localized csv](https://github.com/Automattic/woocommerce-payments/assets/82999806/c471e97d-de38-4d92-a871-5f9351365f20)

### Expected behavior

Localization behavior that affects CSV files persists regardless of how the CSV is delivered.

**Comment by csmcneill** [comment]
This doesn't appear to be (completely) affecting CSVs that are emailed from Analytics; the column headers are translated, but statuses are not:

![localized csv analytics](https://github.com/Automattic/woocommerce-payments/assets/82999806/42eb734a-4cd7-43b8-a97d-96160834a8fb)

Flagging this to @mordeth and @anu-rock as they are currently going through reporting improvements as a part of paJDYF-bhm-p2

**Comment by RadoslavGeorgiev** [comment]
This issue impacts Reporting, so assigning to Fusion (based on team responsibilities Pc2DNy-3z-p2) @Automattic/fusion.

Assigning as part of Gamma Triage process PcreKM-yM-p2.
