### ISSUE TITLE
Clearpay is not offered on UK sites in 6.8.0+

### ISSUE THREAD

**Issue by csmcneill** [Automattic/woocommerce-payments#7849]
### Describe the bug

UK merchants who are approved to offer Afterpay / Clearpay are unable to offer this payment method to customers if they are using version 6.8.0 or later of WooPayments.

### To Reproduce

1. Configure a site with WooCommerce and WooPayments 6.8.0 or 6.9.0.
2. Onboard a UK account.
3. Ensure that the account's default currency is set to GBP (e.g., use a GBP deposit account when onboarding).
**Note:** I tested with a live UK account; you can find the login credentials at p1701915053732739/1701906047.285749-slack-C3NCP7ZJ6
4. Enable Afterpay / Clearpay in the WooPayments settings.
5. Create a test product that is between 1 and 1,200 GBP per [this doc](https://woo.com/document/woopayments/payment-methods/buy-now-pay-later/#afterpay-minimums-and-maximums).
6. Navigate to the product page for the product created in step 4.
7. Notice that Clearpay messaging is included on the product page (though it may be in a weird spot if you're using Twenty Twenty-Four or its predecessors).
8. Add the product to the cart and go to checkout.
9. Note that there is no payment method for Afterpay / Clearpay.
10. Revert to WooPayments 6.7.1.
11. Refresh the checkout page.
12. Afterpay is now offered as expected*.
*Caveat: **Afterpay** is offered — but not **Clearpay** as expected.

### Actual behavior
UK merchants who update beyond 6.7.1 are unable to offer Afterpay / Clearpay as a BNPL method on checkout because it does not display as expected.

### Screenshots
![clearpay](https://github.com/Automattic/woocommerce-payments/assets/82999806/73a9696b-407c-416d-afc3-2f54a3e40038)

### Expected behavior
Merchants who are able to offer Afterpay / Clearpay on checkout can do so without issue.

### Additional context

7345386-zen

**Comment by RadoslavGeorgiev** [comment]
After checking in with the product area owner, it falls under @Automattic/heisenberg's responsibilities. @frosso is looking into it.

**Comment by frosso** [comment]
Following up the discussion here: p1701918520387539-slack-C04VCT34PCP

Updating priority to "critical".
