### ISSUE TITLE
Adding WooPayments transaction id (txn_xxxx) into order meta

### ISSUE THREAD

**Issue by geektzu** [Automattic/woocommerce-payments#7856]
### Description

Currently, the WooPayment intent id is added to the order meta. When a merchant is integrated to NetSuite the payment intend id could be synchronized with the orders to NetSuite. However, the transaction id is not included as part of the order meta. It posts a challenge for a merchant who uses NetSuite for transaction reconciliation. They can get transaction ids (txn_xxxx) from the "Payments" -> "Transactions", however, txn_xxx were not synchronized over to NetSuite.

### Acceptance criteria

Add a new meta field to register WooPayments transaction id. So a NetSuite connector such as In8Sync can pick and synchronize to NetSuite.

### Designs

No UI required

### Testing instructions

1. A new meta field must be present in Woo order after a payment is charged via WooPayments. 
2. Use the Store Toolkit plug to inspect the order meta for transaction id (txn_xxxxxx). Go to WooCommerce -> Orders.

### Additional context
P2: https://wp.me/pcJe93-3R9

**Comment by geektzu** [comment]
@souravdebnath1986

**Comment by RadoslavGeorgiev** [comment]
Asked for a responsible team in Slack: p1702301046121889-slack-C04DN7Q51KK

**Comment by geektzu** [comment]
The transaction id here in the meta should be of the "charge" transaction for WooPayments.  As there is already a "_transaction_id" in the order meta to store the payment intent id that pays the order. Suggest to have another meta field such as "_charge_transaction_id"  for transaction id (txn_XXXX) of charge transactions. @RadoslavGeorgiev @anu-rock 

Also, when _charge_transaction_id will be added to order meta? Upon the order transited to "Processing"? We need to re-configure the in8Sync rule for Woo->NetSuite synchronization accordingly.

**Comment by geektzu** [comment]
@RadoslavGeorgiev @souravdebnath1986 @anu-rock let me know if there is more clarification needed. Wonder if it will be included in the next version of WooPayments? Any ETA we can anticipate?

**Comment by anu-rock** [comment]
@geektzu 

Just to be sure: the [attach_intent_info_to_order](https://github.com/Automattic/woocommerce-payments/blob/a2f53a355d72e9367f97194d08653b46c88c27eb/includes/class-wc-payments-order-service.php#L741) method currently saves the charge id (ch_xxx) to order meta. Seems like this is not sufficient and we'd like to also save the transaction id (txn_xxx), correct?

> Wonder if it will be included in the next version of WooPayments? Any ETA we can anticipate?

Fusion will prioritize this issue in the current sprint. If all goes well, the change will be included in v7.0.0.

**Comment by geektzu** [comment]
@anu-rock yes. As the transaction ids (txn_xxxx) are the ones in WooPayments -> Transactions report.

**Comment by anu-rock** [comment]
@geektzu You can keep an eye on the implementation progress at https://github.com/Automattic/woocommerce-payments/pull/7945. Feel free to leave your comments there.

**Comment by dechov** [comment]
The charge ID mentioned by @anu-rock (ch_xxx) is also in the WooPayments -> Transactions report, and would potentially be more useful since a charge (and likewise, an order) can potentially have multiple "transactions" (charge, refund, dispute…) – at least in theory, not sure how this particular accounting integration is supposed to work. @geektzu Might the charge_id in the Transactions report be enough to associate with the _charge_id in order meta?

**Comment by geektzu** [comment]
@dechov the charge_id is currently not in the transaction report. Unless there is a column to display charge id. Currently, there is only transaction ids. Also, for partial refunded transactions, believe we cannot use charge_id for reconciliation but only txn id (txn_xxxx).

![image](https://github.com/Automattic/woocommerce-payments/assets/7579242/53a381a0-ae34-48c1-a202-0b454b736574)

**Comment by geektzu** [comment]
@dechov @souravdebnath1986 

charge_id is not exposed by the API /wp-json/wc/v3/payments/reports/transactions
There is no way to use the charge id for reconciliation. It isn't very clear what the best ID for reconciliation is.

    {
        "transaction_id": "txn_3OPKjzC80Ttix7JI0DfOT167",
        "date": "2023-12-20 08:02:55",
        "payment_id": "pi_3OPKjzC80Ttix7JI0x3WvDzW",
        "channel": null,
        "payment_method": {
            "type": "visa"
        },
        "type": "charge",
        "transaction_currency": "usd",
        "amount": 990,
        "exchange_rate": 1,
        "deposit_currency": "usd",
        "fees": 59,
        "customer": {
            "name": "Alan Zhu",
            "email": "alan.zhu@automattic.com",
            "country": "US"
        },
        "net_amount": 931,
        "order_id": 72,
        "risk_level": 0,
        "deposit_date": "2023-12-27",
        "deposit_id": "wcpay_estimated_daily_usd_1703635200",
        "deposit_status": "estimated"
    },

**Comment by dechov** [comment]
Ah, I see – can we use the `payment_id`, which should match the `_transaction_id` in order meta (mentioned above)?

**Comment by geektzu** [comment]
Technically, believe we can use "payment_id": "pi_xxxxx" but it is not in the WooPayments transactions screen. It makes it hard for manual reconciliation and educate the Finance people what are the ids for. Shall we add a column of "pi_xxxxx" into the WooPayments ->"Transactions" screen?

**Comment by dechov** [comment]
Understood – if you click the row, it shows that Payment ID at the top right, but it sounds like it might make sense to add that as a column in the Transactions list as well.

_Edit:_ I may have missed it but is there a reason order ID couldn't alternatively be used to fulfill this requirement?

**Comment by anu-rock** [comment]
@geektzu So, would it address the underlying issue if we added the payment intent ID to the transactions table? We maintain a 1:1 mapping between order ID and payment intent ID, which from @dechov's comments does not seem to be the case for transaction IDs.

**Comment by anu-rock** [comment]
I will go ahead with my existing implementation #7945 as it also introduces an improvement to the `attach_intent_info_to_order` method.

I've created https://github.com/Automattic/woocommerce-payments/issues/8027 to separately track the addition of the payment id column on the Transactions page.
