### ISSUE TITLE
Expose WooPayments transaction id (txn_xxxxx) via current refund API end

### ISSUE THREAD

**Issue by geektzu** [Automattic/woocommerce-payments#7857]
### Description

The current WooComemrce REST API only returns an internal id after a refund is created.
https://woocommerce.github.io/woocommerce-rest-api-docs/#create-a-refund

It posts a challenge for reconciliation for refunds created by NetSuite via the REST API. 
The internal id in the “Create a refund" API point cannot be reconciled with the WooPayments transaction report (Payments -> Transactions).

### Acceptance criteria

The response of the current refund API should include a new field if the payment gateway is WooPayments. https://woocommerce.github.io/woocommerce-rest-api-docs/#create-a-refund

For example, a new field should be woopayments_transaction_id: "txn_xxxxxxx" should be returned by the API endpoint.

### Testing instructions

1. Create a refund via https://woocommerce.github.io/woocommerce-rest-api-docs/#create-a-refund
2. Look for the WooPayment transactions id in the API response. 
3. Reconcile with the report in "Payments -> Transactions"

### Additional context
P2: https://woocustomersuccess.wordpress.com/2023/12/06/journey-to-launch-woopayments-for-joola-usa/

**Comment by geektzu** [comment]
@souravdebnath1986

**Comment by RadoslavGeorgiev** [comment]
Asked for a responsible team in Slack: p1702301046121889-slack-C04DN7Q51KK

**Comment by anu-rock** [comment]
@geektzu If the WooPayments transaction id is stored in order meta (#7856), will it not be returned in the metadata property of [create refund API](https://woocommerce.github.io/woocommerce-rest-api-docs/#create-a-refund)'s response?

**Comment by geektzu** [comment]
@anu-rock WooPayment transaction id is not currently stored in order meta.  That transaction id should be the id of the WooPayment "charge" transaction id.
The transaction id of the refund API is a different WooPayments transaction id. 

A  Woo order could have multiple transaction ids.
1. transaction id for capturing the payment
2. transaction id for refunds (could be multiple transaction ids due to partial refunds)

If you go to Payments ->Transactions, you could find multiple transaction ids can be linked to the same Woo order.

**Comment by anu-rock** [comment]
@geektzu I see, thanks for clarifying.

> For example, a new field should be woopayments_transaction_id: "txn_xxxxxxx" should be returned by the API endpoint.

Is this expected to be the transaction id for the captured payment or refund? In the case of the former, when we implement https://github.com/Automattic/woocommerce-payments/issues/7856 my guess is that it will be available in the refund API's response as metadata. In the case of the latter, I wonder how it will work. I have not worked with our refund APIs before, so someone else could provide a better answer. But we might want to consider whether we would like to store the refund transaction id as a top-level field in the response or as another field in order meta, say `_refund_transaction_id`.

**Comment by geektzu** [comment]
For the refund API, it should be the transaction id of the "refund" transaction.

**Comment by anu-rock** [comment]
@geektzu We have a PR ready at #7932. For your convenience, this is how the refund transaction id will look like in the create refund API response. Feel free to leave your feedback directly in the PR.

![291598361-7ec9798c-6149-4dae-92be-f9e1039abd62](https://github.com/Automattic/woocommerce-payments/assets/1288616/667a6709-b59e-444b-a554-aedb50fd6c68)
