### ISSUE TITLE
Payment asset outlines are being drawn incorrectly on the transactions screen(s)

### ISSUE THREAD

**Issue by bradyv** [Automattic/woocommerce-payments#7865]
### Describe the bug
On the transactions table, and the transaction details page, we're not applying an offset to the outline drawn around payment method assets.

### To Reproduce

1. Go to 'Payments -> Transactions'
2. Click on a row to view transaction details

### Actual behavior

The outline is drawn outside the asset

### Screenshots

<img width="1049" alt="Screenshot 2023-12-08 at 12 51 25" src="https://github.com/Automattic/woocommerce-payments/assets/889872/65798e2b-bb13-4825-8403-c480d9658dec">
<img width="1411" alt="Screenshot 2023-12-08 at 12 51 18" src="https://github.com/Automattic/woocommerce-payments/assets/889872/295d5924-684c-452a-8de7-9fa1b331edcb">

### Expected behavior

The outline should be drawn with an asset so it appears _on top_ of the asset. The fix for this should be simple, we just need to update the `.payment-method__brand` css class to include
```outline-offset: -1px;```

**Comment by csmcneill** [comment]
I was having a hard time determining what is the expected vs. actual here, so I added the `outline-offset: -1px;` via my browser's dev tools:

![CleanShot 2023-12-08 at 16 22 44](https://github.com/Automattic/woocommerce-payments/assets/82999806/a9948400-f597-4071-9245-ec96e939d6c9)
