### ISSUE TITLE
[cosmetic] Accepting TOS (terms of service) shows both `Accept` and `Decline` buttons with spinner, confusing

### ISSUE THREAD

**Issue by haszari** [Automattic/woocommerce-payments#7866]
### Describe the bug
When onboarding WooPayments, merchant needs to accept ToS. 

The modal has an  `Accept` and `Decline` buttons.

If merchant `Accept`s, both buttons show a spinner, which is a tiny bit weird – only the button that the user actioned should show a spinner. 

Very minor! 

<img width="425" alt="WooPayments TOS accept shows spinner on Accept AND Decline" src="https://github.com/Automattic/woocommerce-payments/assets/4167300/b024880f-80be-4fa7-b9ff-836859e8d09b">

**Comment by zmaglica** [comment]
@anu-rock I will move this issue to the team Moltres since it affects onboarding as a part of the Gamma issue triage process

**Comment by anu-rock** [comment]
@haszari I am not entirely sure why this is the case, but my gut says we wanted to prevent users from clicking Decline while accepting was in process 🤷 Maybe a better UX would be to just disable the Decline button and not show a loading animation on it.

cc @elizaan36

**Comment by elizaan36** [comment]
Thanks for the ping, @anu-rock 

I must admit, I'm not familiar with the model to accept TOS. @haszari Could you share the steps to bring this up? I don't think it's the primary onboarding path.

**Comment by haszari** [comment]
> I must admit, I'm not familiar with the model to accept TOS. @haszari Could you share the steps to bring this up? I don't think it's the primary onboarding path.

I forget how I triggered this, was re-onboarding months ago. Might be a rare edge case.

> @haszari I am not entirely sure why this is the case, but my gut says we wanted to prevent users from clicking Decline while accepting was in process 🤷 Maybe a better UX would be to just disable the Decline button and not show a loading animation on it.

Yeah that was my thinking, disable components you can't click, and show progress/activity only on components that are really in progress.

**Comment by elizaan36** [comment]
> Yeah that was my thinking, disable components you can't click, and show progress/activity only on components that are really in progress.

This makes sense to me. I'm still perplexed where this is though!
