### ISSUE TITLE
Enhance handling of setup intents on the "Add Payment Method" page.

### ISSUE THREAD

**Issue by timur27** [Automattic/woocommerce-payments#7868]
### Description
This issue is the follow-up to the thread we had earlier paJDYF-aOH-p2. We have a chance to slightly improve the performance on the add-payment-method page as well as unify 3DS handling across the screens.

https://github.com/Automattic/woocommerce-payments/pull/7440 was where this initiative has started, so it can be used as the inspiration for further development in the separate PR.

### Acceptance criteria

* 3DS payment handling is unified across screens
* non-3DS cards setup intents are not confirmed on the client
* https://github.com/Automattic/woocommerce-payments/pull/7440 is closed in case other PR is created to complete this issue

**Comment by frosso** [comment]
Added a reflection of the internal discussion here: paJDYF-aOH-p2#comment-22987

We won't be moving forward with the removal of the AJAX call, but we'll be looking at other ways of optimizing the code reuse without affecting the customer's experience.

CC: @FangedParakeet
