### ISSUE TITLE
Console error on pay for order page

### ISSUE THREAD

**Issue by frosso** [Automattic/woocommerce-payments#7871]
### Describe the bug

On the "Pay for order" page, I noticed this console error:
![Screenshot 2023-12-11 at 9 39 57 PM](https://github.com/Automattic/woocommerce-payments/assets/273592/a95faf89-1452-43f3-8570-80fa7f39922c)

I also noticed that the page refreshes when clicking the "Pay for order" button with a 3DS card - which might be related:
![2023-12-11 21 40 43](https://github.com/Automattic/woocommerce-payments/assets/273592/b5a165d5-9551-4ec8-8b3b-f81a27a7662c)

### To Reproduce

- Ensure you have multi-currency enabled
- In `wp-admin`, create a new order via the **WC > Orders > Add order** CTA
- Add a few items
- Save the order
- Click the "Customer payment page" link
![Screenshot 2023-12-11 at 9 45 14 PM](https://github.com/Automattic/woocommerce-payments/assets/273592/a1cc9bc6-0f4c-49fd-bc4f-4445fdc2a128)
- Use a 3DS card (might be optional)

### Actual behavior

Error appears in the console.
On "Pay for order" CTA click, page refreshes (but still allows for the payment)

### Screenshots

![2023-12-11 21 40 43](https://github.com/Automattic/woocommerce-payments/assets/273592/680d7446-d6a9-46f8-b756-8ad13a5825f4)

### Expected behavior

No console error.
Ideally, also no page refresh.

**Comment by timur27** [comment]
I'm not 100% sure, but for whoever takes this, please check if some areas are not overlapping with the https://github.com/Automattic/woocommerce-payments/issues/7799's scope.
