### ISSUE TITLE
Deposits - Overview: When available balance is at or below zero, no schedule is shown.

### ISSUE THREAD

**Issue by brucealdridge** [Automattic/woocommerce-payments#7874]
### Describe the bug

When a merchants available balance is at or below $0, no schedule is shown. This leads merchants to incorrectly assume that deposits are blocked or paused.

The deposit schedule should always show when deposits are not blocked or restricted.

![image](https://github.com/Automattic/woocommerce-payments/assets/57298/1f3404cb-4cf0-4251-ab5b-239476cc7d8c)

**Comment by Jinksi** [comment]
Closing as resolved in 6.9.2 #7894
