### ISSUE TITLE
Deposits / Transaction list: Deposit date is missing.

### ISSUE THREAD

**Issue by brucealdridge** [Automattic/woocommerce-payments#7876]
### Describe the bug

With the removal of estimated deposits, merchants aren't sure when a deposit is going to arrive and can incorrectly assume that deposits are paused.

To help resolve this, we can show `Future deposit` or `Processing` in the deposit date column to show that these aren't lost or stuck.

![image](https://github.com/Automattic/woocommerce-payments/assets/57298/8b332741-4de6-422d-9dc4-08d8da792552)

**Comment by Jinksi** [comment]
Closing as resolved in 6.9.2 #7894
