### ISSUE TITLE
Deposits listing page no longer shows next deposit date.

### ISSUE THREAD

**Issue by brucealdridge** [Automattic/woocommerce-payments#7877]
### Describe the bug

With the removal of estimated deposits, merchants do not have a clear understanding of when their next deposit is due from the deposit listing page.

To help resolve this, we should add the deposit schedule to the page as either a notice or as a row in the table. This can be a duplication of the information on the payments overview screen.

**Sample Mockup**

![image](https://github.com/Automattic/woocommerce-payments/assets/57298/5824c05d-846f-4eb8-b4a2-3cde45b40e7a)

**Comment by Jinksi** [comment]
Closing as resolved in 6.9.2 #7894
