### ISSUE TITLE
Strict return type on `get_edit_post_link` filter callback leading to fatal errors in some circumstances

### ISSUE THREAD

**Issue by james-allan** [Automattic/woocommerce-payments#7881]
### Describe the bug

This was originally reported as causing errors when processing subscription renewal payments using the Stripe gateway, however after debugging the cause, its reach is more broad and general than that. 
 
The `OrderMetaHelper::maybe_update_edit_post_link()` function, which is hooked onto the `get_edit_post_link` filter, has a strict/defined return type of a `string`. Given this function is a callback and could receive any type from other callbacks further up the chain it should either remove this defined return type or transform unacceptable inputs into an acceptable return type (eg null -> empty string) to avoid fatal errors pointing to this function as the cause due to third-party code doing the wrong thing. 

Example stack trace: 

```
CRITICAL Uncaught TypeError: Return value of WCPay\MultiCurrency\Helpers\OrderMetaHelper::maybe_update_edit_post_link() must be of the type string, null returned in /plugins/woocommerce-payments/includes/multi-currency/Helpers/OrderMetaHelper.php:336
Stack trace:
#0 /wp-includes/class-wp-hook.php(326): WCPay\MultiCurrency\Helpers\OrderMetaHelper->maybe_update_edit_post_link(NULL)
#1 /wp-includes/plugin.php(205): WP_Hook->apply_filters(NULL, Array)
#2 /plugins/woocommerce-subscriptions/vendor/woocommerce/subscriptions-core/includes/wcs-helper-functions.php(71): apply_filters('get_edit_post_l...', 'https://www.wpb...', 7873, '')
#3 /plugins/woocommerce-subscriptions/vendor/woocommerce/subscriptions-core/templates/emails/subscription-info.php(35): wcs_get_edit_post_link(7873)
#4 /plugins/woocommerce/includes/wc-core-functions.php( dans /plugins/woocommerce-payments/includes/multi-currency/Helpers/OrderMetaHelper.php à la ligne 336
```

Looking at this example stack trace the flow appears to be:

1. Woo Subscriptions is generating an edit post link for a subscription in an email sent to admin users. 
2. You can see in line `#2` the `apply_filters()` did receive a url (starting with `https://www.wpb`). 
3. `maybe_update_edit_post_link()` receives null so something in between the `apply_filters()` and it being called is transforming the url into null (likely a callback mistakingly not returning). 

### To Reproduce

I don't know what the custom/third-party code actually looks like so these steps just showcase the issue rather than list a legitimate use case.  

1. To reproduce you'd need to add custom code like this (see below) to your site to simulate bad third-party code. 
2. Enable WP post order storage in **WooCommerce > Settings > Advanced > Features**
3. Go to **WooCommerce > Orders**
4. You should see the following fatal. 

```php
add_filter( 'get_edit_post_link', function( $url ) {
} );
```

```
PHP Fatal error:  Uncaught TypeError: WCPay\MultiCurrency\Helpers\OrderMetaHelper::maybe_update_edit_post_link(): Return value must be of type string, null returned in public/wp-content/plugins/woocommerce-payments/includes/multi-currency/Helpers/OrderMetaHelper.php:336
Stack trace:
#0 public/wp-includes/class-wp-hook.php(326): WCPay\MultiCurrency\Helpers\OrderMetaHelper->maybe_update_edit_post_link(NULL)
#1 public/wp-includes/plugin.php(205): WP_Hook->apply_filters(NULL, Array)
#2 public/wp-includes/link-template.php(1499): apply_filters('get_edit_post_l...', 'https://wcdev.l...', 5599, 'display')
#3 public/wp-admin/includes/class-wp-posts-list-table.php(1477): get_edit_post_link(Object(WP_Post))
#4 public/wp-admin/includes/class-wp-list-table.php(1800): WP_Posts_List_Table->handle_row_actions(Object(WP_Post), 'order_number', 'order_number')
#5 public/wp-admin/includes/class-wp-posts-list-table.php(1432): WP_List_Table->single_row_columns(Object(WP_Post))
#6 public/wp-admin/includes/class-wp-posts-list-table.php(834): WP_Posts_List_Table->single_row(Object(WP_Post), 0)
#7 public/wp-admin/includes/class-wp-posts-list-table.php(810): WP_Posts_List_Table->_display_rows(Array, 0)
#8 public/wp-admin/includes/class-wp-list-table.php(1709): WP_Posts_List_Table->display_rows()
#9 public/wp-admin/includes/class-wp-list-table.php(1636): WP_List_Table->display_rows_or_placeholder()
#10 public/wp-admin/edit.php(503): WP_List_Table->display()
#11 {main}
```

### Actual behavior

If a bad third-party plugin code hooks onto `get_edit_post_link` returns null, WooPayments will fatal. 

### Expected behavior

There shouldn't be a fatal.

`OrderMetaHelper::maybe_update_edit_post_link()` should either not have a strict return type given we cannot guarantee the input type. 

Alternatively, if `maybe_update_edit_post_link()` doesn't receive a string, it could transform it into a string to align the return type with it's defined return type. Eg `null ⇒ ''` 

### Additional context

Ticket: 7390013-zd-a8c
Slack thread: p1702245873542259-slack-C7U3Y3VMY

**Comment by RadoslavGeorgiev** [comment]
This issue impacts Multi-Currency, so assigning to Fractal (based on team responsibilities Pc2DNy-3z-p2) @Automattic/fractal.

Assigning as part of Gamma Triage process PcreKM-yM-p2.

**Comment by bborman22** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Fractal-62a0f7b955648b001e1f5e1f/issues/Automattic/woocommerce-payments/7881?planning-poker) with Zenhub @cesarcosta99 @lovo-h @rafaelzaleski @ricardo
