### ISSUE TITLE
Fix E2E tests failing for WC 7.7

### ISSUE THREAD

**Issue by ricardo** [Automattic/woocommerce-payments#7892]
### Description

As noted in https://github.com/Automattic/woocommerce-payments/pull/7844#pullrequestreview-1777894531, `shopper-myaccount-payment-methods-add-delete-success.spec.js` tests are failing – [Sample run](https://github.com/Automattic/woocommerce-payments/actions/runs/7184590554/job/19569276470).

The issue has probably to do with test 3DS cards, as fixed in #7844.

**Comment by cesarcosta99** [comment]
This issue has been repurposed to account for the `shopper-multi-currency-widget.spec.js` as well. Both tests are failing on WC 7.7.0 as indicated in [this run](https://github.com/Automattic/woocommerce-payments/actions/runs/7185934402/attempts/1).
