### ISSUE TITLE
Deposits: Too many notices are shown when account is in new account waiting period.

### ISSUE THREAD

**Issue by brucealdridge** [Automattic/woocommerce-payments#7901]
### Describe the bug

The in-progress patch release of 6.9.2 shows two notices, that may overload the merchant with information.

![image](https://github.com/Automattic/woocommerce-payments/assets/57298/72b714ab-4a56-4f8f-a90e-6d218c137a77)

**Comment by Jinksi** [comment]
Closing as resolved in 6.9.2 #7894
