### ISSUE TITLE
dismissable `Available funds are automatically dispatched every _` is different height to other notices

### ISSUE THREAD

**Issue by brucealdridge** [Automattic/woocommerce-payments#7903]
### Describe the bug

When the `BannerNotice` component is used with and without an icon the height and vertical alignment of the text appears different. 

![image](https://github.com/Automattic/woocommerce-payments/assets/57298/6a339ec4-0068-46d9-9c40-c3d954161587)

The size and vertical alignment of the text should be consistent regardless of the icon being displayed.

Fix ideas:

- The class used in the component `wcpay-banner-notice__content` doesn't have a minimum height or line-height set. In my testing, without an icon the height of this `<div>` is `18.19px` and `24px` with the icon. This is due to the icon having a `height` of `24px`
- Make the small notice bigger (to match "with icon" sizing) - i.e. minimum size & ensure the text is appropriately centered. 
- Making the icon not take up space ([`position: absolute` or similar](https://www.w3schools.com/css/css_positioning.asp)).

**Comment by RadoslavGeorgiev** [comment]
This issue impacts Deposits, so assigning to Helix (based on team responsibilities Pc2DNy-3z-p2) @Automattic/helix. Correct me if I'm wrong, and we need the FE guild to handle it.

Assigning as part of Gamma Triage process PcreKM-yM-p2.

**Comment by haszari** [comment]
> This issue impacts Deposits, so assigning to Helix (based on team responsibilities Pc2DNy-3z-p2) @Automattic/helix. Correct me if I'm wrong, and we need the FE guild to handle it.

On the one hand: it's an issue with a component, so would be a good fit for either gamma/core or a components team (if we had one).

On the other hand, the first instance of this bug impacts the deposits experience, so Helix want it fixed :) 

I'll tweak the title to clarify. Happy for this to be assigned to Helix :)

**Comment by haszari** [comment]
Marking as low priority as this is a minor, cosmetic issue.

**Comment by Jinksi** [comment]
> On the other hand, the first instance of this bug impacts the deposits experience, so Helix want it fixed :)

This will no longer be an issue for the deposits experience when the UI for this deposits list notice/message is updated in #8026.

**Comment by brucealdridge** [comment]
Closing as this looks to be resolved in https://github.com/Automattic/woocommerce-payments/pull/8263
