### ISSUE TITLE
Express Pay buttons expect extension field names to be prefix with `addon-` which isn't always the case.

### ISSUE THREAD

**Issue by peterwilsoncc** [Automattic/woocommerce-payments#7907]
### Describe the bug

The JavaScript for the Express Pay button puchases on the product page expects fields added by other extensions to use the prefix `addon-`

https://github.com/Automattic/woocommerce-payments/blob/e5bca8df8ccbb61b1707cbd947f413b1bacb9f27/client/payment-request/index.js#L176-L194

This isn't always the case, as many extensions (possibly most) use the prefix `wc_extensionname` for custom fields on the front end. This is certainly the case with deposits and bookings.

Deposits uses the field `wc_deposit_option` for selecting whether to pay a deposit or the full amount. Bookings uses a number of fields: `wc_bookings_field_start_date_month`, `wc_bookings_field_start_date_day`, `wc_bookings_field_start_date_year`, `min_date`, `max_date` and `timezone_offset` for daily blocks, others exist for part day blocks.

As a default, I think it would be good to include fields that begin with `wc_` in the form values submitted to the express pay buttons. A JavaScript filter could also be made available to allow extensions to add other fields to be included when the express pay buttons add items to carts.

This issue came out of testing deposits compatibility with this extension, see woocommerce-deposits#569.

The result of this assumption for Deposits is that the user always gets charged the full amount when using express pay buttons on the product page. This is regardless of their selection.

### To Reproduce

1. Activate Payments and Deposits
2. Create a product with a deposit: make the deposit optional, ie allow purchesers to chose whether to pay in full or pay a deposit
3. Enable Express Pay buttons
4. Visit the product create above
5. Select "Pay deposit"
6. Click an express pay button (eg, Google Pay)
7. The full amount will be charged to the user.

### Actual behavior

Incomplete form data is used on the product page.

### Screenshots

![Screen Shot 2023-12-14 at 10 50 40 am](https://github.com/Automattic/woocommerce-payments/assets/519727/d119e9a9-6157-4d13-bb78-4ce0c896829e)

![Screen Shot 2023-12-14 at 10 51 14 am](https://github.com/Automattic/woocommerce-payments/assets/519727/1c59774c-2816-4d12-9387-7eee9b5043c0)

### Expected behavior

Full form data be used when adding items to cart for express pay buttons

(In case of Deposits, that selecting deposit results in charging the deposit only)

### Desktop (please complete the following information):

* OS: macOS
* Browser Chrome
* Version 120

### Smartphone (please complete the following information):

* Device: [e.g. iPhone6]
* OS: [e.g. iOS8.1]
* Browser [e.g. stock browser, safari]
* Version [e.g. 22]

### Additional context

woocommerce-deposits#569.

**Comment by peterwilsoncc** [comment]
I've created a draft pull request for this but need some assistance to get it wrapped up, see https://github.com/Automattic/woocommerce-payments/pull/7910.

I've set it up as the PR so I can give y'all edit rights on the branch.

**Comment by RadoslavGeorgiev** [comment]
This issue impacts WooPay's express checkout buttons, so assigning to Heisenberg (based on team responsibilities Pc2DNy-3z-p2) @Automattic/heisenberg 

Assigning as part of Gamma Triage process PcreKM-yM-p2.
