### ISSUE TITLE
Legacy front-end UPE scripts enqueued on checkout resulting in 404 File Not Found.

### ISSUE THREAD

**Issue by peterwilsoncc** [Automattic/woocommerce-payments#7909]
### Describe the bug

In #7795 a number of UPE legacy scripts were removed. 

However, the develop branch still attempts to enqueue `dist/upe-split-blocks-checkout.js?ver=6.9.1` on the front-end checkout and triggers a 404 File Not Found error.

The file is registered via PHP in the `WC_Payments_UPE_Split_Blocks_Payment_Method` class.

https://github.com/Automattic/woocommerce-payments/blob/9f6ee85feacf516b401511fa43e28ad172330039/includes/class-wc-payments-upe-split-blocks-payment-method.php#L17-L25

### To Reproduce

1. Checkout the develop branch
2. Run `npm i; npm run build:client`
3. Add an item to the cart
4. Proceed to the checkout (using blocks in the screen shot below)
5. A 404 File Not Found error is thrown for the items removed

### Actual behavior

Enqueuing of removed assets

### Screenshots

![Screen Shot 2023-12-14 at 11 48 30 am](https://github.com/Automattic/woocommerce-payments/assets/519727/39979a92-96a1-4254-b21e-7edd7197bf76)

### Expected behavior

Enqueued files all be available.

### Desktop (please complete the following information):

* OS: macOS
* Browser: Chrome, Firefox, all

* Node: 16.17.1
* NPM: 8.15.0
* Checkout out commit: Develop e5bca8df8ccbb61b1707cbd947f413b1bacb9f27

### Smartphone (please complete the following information):

* Device: [e.g. iPhone6]
* OS: [e.g. iOS8.1]
* Browser [e.g. stock browser, safari]
* Version [e.g. 22]

**Comment by RadoslavGeorgiev** [comment]
This issue impacts UPE, so assigning to Heisenberg (based on team responsibilities Pc2DNy-3z-p2) @Automattic/heisenberg 

Assigning as part of Gamma Triage process PcreKM-yM-p2.
