### ISSUE TITLE
BNPL currency display issue on Payments > Settings page

### ISSUE THREAD

**Issue by wpniall** [Automattic/woocommerce-payments#7940]
### Describe the bug
The **Payments > Settings** page no longer displays the currency for buy now, pay later (BNPL) options correctly, as only the first ISO currency code letter displays. This issue happens with both Dev Mode and Live Mode accounts:

#### Dev Mode issue
We confirmed the same issue happens with different currencies, where `USD` displays as `U` and `EUR` as `E` in Dev Mode:

![image](https://github.com/Automattic/woocommerce-payments/assets/773782/ea575c05-71d7-48bd-9013-2b8560f9ad71)

![image](https://github.com/Automattic/woocommerce-payments/assets/773782/c7e80de6-6273-43e2-9031-bf508052cc1f)

#### Live Mode issue
The same issue happens in Live Mode too, though I only tested a UK account that shows `G` instead of `GBP`:

![image](https://github.com/Automattic/woocommerce-payments/assets/773782/c77f7bb1-90e6-450d-9b22-1c7c51993c8e)

### To Reproduce

1. Go to **Payments > Settings** for a WooPayments account in a country that [supports BNPL methods](https://woo.com/document/woopayments/payment-methods/buy-now-pay-later/#supported-providers)
2. Look for Affirm, Afterpay, and/or Klarna depending on the account country
3. See the only the first currency code letter and not the full ISO code: e.g., for USD, that shows as `Available to all customers paying in U.` instead of `Available to all customers paying in USD.`

### Expected behavior

I'd expect the full three letter ISO currency code to display.

### Desktop (please complete the following information):

* OS: OSX
* Browser Chrome
* Version 120.0.6099.129

### Additional context
Happens with the latest WooPayments v6.9.2. Not sure if it happened before that, but per the [Buy now, pay later with WooPayments](https://woo.com/document/woopayments/payment-methods/buy-now-pay-later/#enabling) doc, the currencies used to display correctly:

![image](https://github.com/Automattic/woocommerce-payments/assets/773782/b522297a-92bd-472b-bdae-8ba59886c6c2)

Slack thread discussion: p1703231396192399-slack-C014E5VH9HC

**Comment by kalessil** [comment]
Fixed in https://github.com/Automattic/woocommerce-payments/pull/7872
