### ISSUE TITLE
Add check for existence of Woo session before calling it in WooPay_Utilities::should_save_platform_customer

### ISSUE THREAD

**Issue by billrobbins** [Automattic/woocommerce-payments#7957]
### Describe the bug
On TumblrPay, successful, subscription payment retries were not finishing completely.  The payment is successful, the order and subscription statuses are updated, and the next renewal is scheduled but the payment retry is not updated, and the successfully charged order note is not saved.

The issue was traced to calling `get()` on `null` in `WooPay_Utilities::should_save_platform_customer`.  The session is not set when this method is called which results in an error.  

### To Reproduce
I have been unable to reproduce this in my own testing.  Stripe has a test card that can be attached to a customer but will fail once charged but they do not have one that will fail and then be successful.  We only saw this error on payment retries where the card was declined and then the same card number was later successful.  

Modifying the `should_save_platform_customer()` method to check for the existence of the session before processing prevented the error for us.

```php
$session_data = [];

if ( isset( WC()->session ) && WC()->session->has_session() ) {
	$session_data = WC()->session->get( WooPay_Extension::WOOPAY_SESSION_KEY );
}

$availability = ! empty( $session_data ) ? 'available' : 'not available';
\wc_get_logger()->debug(
	"WooPay: Session $availability when checking if we should save platform customer.",
	[
		'extra' => [
			'session_data' => $session_data,
		],
	]
);
```

We also added logging to see how often this was called.  Over the past three days, we had this logged 270 times however only one of those was for a successful payment retry.

### Screenshots
_Order notes from an affected order:_
![order-notes](https://github.com/Automattic/woocommerce-payments/assets/1138631/70edcecb-202d-4b56-84f7-21c252951fe8)

_Retry data from the related subscription_
![retry-data](https://github.com/Automattic/woocommerce-payments/assets/1138631/c8b4ecb0-1e38-411c-916c-8d871620d32b)

### Additional context
Log entry with stack trace available: https://logstash.a8c.com/logstash/app/discover#/doc/log2logstash-*/log2logstash-1m-index-2023.12.29-001558?id=N_Ewt4wBizqA4NEXpH8f

**Comment by jessy-p** [comment]
This issue impacts WooPay, so assigning to Heisenberg (based on team responsibilities Pc2DNy-3z-p2) @frosso. Assigning as part of Gamma Triage process PcreKM-yM-p2.

**Comment by bborman22** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Fractal-62a0f7b955648b001e1f5e1f/issues/Automattic/woocommerce-payments/7957?planning-poker) with Zenhub @cesarcosta99 @lovo-h @rafaelzaleski @reykjalin @ricardo

**Comment by bborman22** [comment]
Hey @billrobbins! I saw you have a PR already for this update as we were going to pull this into the next sprint. Just want to confirm that the best next step here is for us to give that PR a review to close this issue?

**Comment by billrobbins** [comment]
Hi @bborman22 that would be fantastic.  We've been running this change on WordPress.com, but if that's not a good solution we definitely want to change that.  If you have any questions, just let me know.
