### ISSUE TITLE
Disputed transactions should not show refund actions if they are not refundable

### ISSUE THREAD

**Issue by Jinksi** [Automattic/woocommerce-payments#7960]
### Describe the bug

Transactions disputed with the status `needs_response`, `under_review` or `lost` are not refundable. Therefore, the refund dropdown should not be visible for transactions with these dispute statuses.

<img width="1075" alt="image" src="https://github.com/Automattic/woocommerce-payments/assets/3147296/eb4221fa-10b9-4437-a935-42135b247b19">

Dispute statuses that are refundable and should show the refund dropdown: `won`, `warning_needs_response`, `warning_under_review`, `warning_closed`.

### To Reproduce

* As a shopper, create a disputed order by purchasing a test product using the card `4000000000000259` at checkout.
* As a merchant, navigate to Payments -> Disputes and click the row for the dispute you just created. You will be taken to the "Transaction Details" screen.
* Notice that the refund dropdown is rendered.
* Clicking "Refund in full" will result in an API response error, since refunds are not possible.

### Actual behavior

The transaction details refund dropdown is visible for transactions with dispute statuses that are not eligible for refunds.

### Expected behavior

The transaction details refund dropdown is not rendered for transactions with dispute statuses that are not eligible for refunds.

### Additional context

* See PdjTHR-2T4-p2 for more information about dispute statuses.
* [See order screen logic for determining if a dispute is eligible for a refund.](https://github.com/Automattic/woocommerce-payments/blob/b5d1da3e16264a1b3936814dcbfba568d2cdab39/client/components/disputed-order-notice/index.js#L45-L46)

**Comment by kalessil** [comment]
@mgascam @KarlisJ: can we look into fixing this next week, please?
