### ISSUE TITLE
Ability to measure reporting-related interactions on the Transactions page

### ISSUE THREAD

**Issue by anu-rock** [Automattic/woocommerce-payments#7961]
To measure the impact of our improvements to transaction reporting, we'd like to track the following user interactions:

#### View the **Transactions page**

(contains the transactions list view, a basic report)

![image](https://github.com/Automattic/woocommerce-payments/assets/1288616/e468c5cd-7a4a-4e55-8891-27637f574790)

####  Click the **Filter** button

<img width="540" alt="Screenshot 2024-01-04 at 11 20 22 AM" src="https://github.com/Automattic/woocommerce-payments/assets/1288616/430f19bb-dc33-4271-aa90-e5f5db0b61ad">

#### Click the **Download** button

<img width="159" alt="image" src="https://github.com/Automattic/woocommerce-payments/assets/1288616/a26ba39e-3ae0-4c00-beec-61f7d0534065">

We already have a Tracks event `wcadmin_wcpay_transactions_download_csv_click` to record download button clicks. We'd like to add events for the other two interactions.

### Dev notes

* An example PR where a new event was introduced - #6281
* Registering an event in Tracks - PCYsg-mUj-p2

### Additional context

* Related project - paJDYF-bhm-p2

**Comment by jessy-p** [comment]
Moving to Other Teams as it looks like Fusion will work on it.

**Comment by anu-rock** [comment]
@souravdebnath1986 brought up a good point today about using the `wcadmin_page_view` event along with its "path" property set to "payments_transactions". So we might not need a dedicated event for tracking page views.
