### ISSUE TITLE
Full Refunds from Transaction page do not restock inventory and make restocking difficult.

### ISSUE THREAD

**Issue by melek** [Automattic/woocommerce-payments#7969]
### Describe the bug
When refunding a transaction in full from the Transaction Page in WooPayments 7.0.0, inventory is not restored. This is a departure from the recommended, quantity-based refund procedure when refunding on the Order page.  

### To Reproduce

1. Place any order for a product with tracked inventory. The inventory should be reduced, evidenced in the order notes.
2. Refund the order via the Transaction screen.
3. Review the Order page post-refund. Note that 'Refund' is still an option, and they inventory hasn't been restocked.
4. Try to manually restock with the 'Refund' button. See error.
5. Place an identical order and refund fully via the Order screen by incrementing the quantity and refunding. Stock is restored, and the 'Refund' button is no longer available.

### Actual behavior
When fully refunding via the new Transaction page refund option, dollar amount is refunded fully, but the inventory is not restored, and the 'Refund' button remains available on the order page.

To manually correct this issue so the accounting on the order page is totally correct, I tried to perform the refund from the Orders page again, then zero out the calculated debit (which is annoying) - but that produced an error (`The refund amount is invalid`). 
Ultimately a merchant refunding an order this way would have to manually update the stock in the Product page, and leave a private note on the refunded order if they want to correctly audit the inventory.

This could be really inconvenient for businesses which have tight inventory auditing requirements.

### Screenshots
<img width="3560" alt="image" src="https://github.com/Automattic/woocommerce-payments/assets/220149/c6266dbe-fcdd-445e-ba48-98edaee349ef">

### Expected behavior
If there is a linked order for a transaction, the merchant should be given some UI to indicate whether or not to restock the item(s). I suggest the following options appear when 'Refund in full' is selected on a transaction with a linked order:

1. Restock all items. // Recommended refund procedure from orders page
2. Do not restock items. // Current behavior
3. Restock some items (will open Order page). // Only show if order has more than 1 item. Same functionality as 'Partial refund', which is to redirect to the Order page.

Alternatively, when that linked order is present a notice should appear to the merchant that the procedure doesn't restore inventory automatically - that must be done with a second, $0 refund on the Orders page (which must be fixed in order to work - see discussion below). We could also direct them to update the product inventory, though I don't favor that approach since it can desync inventory if a sale occurs between while editing a product.

None of these should appear if there is no linked order (such as an orphaned transaction due to card testing, etc.)

### Desktop (please complete the following information):

* OS: MacOS
* Browser: Firefox
* Version: Latest

### Discussion
Any WooPayments order which has already been fully refunded shows the annoying behavior when trying to restock the order via a $0 refund - that should probably be filed as a separate issue, but for now making it less likely to get put in that situation feels sufficient.

**Comment by jessy-p** [comment]
This issue impacts Deposits, Disputes, Reporting, so assigning to Helix (based on team responsibilities Pc2DNy-3z-p2) @haszari. Assigning as part of Gamma Triage process PcreKM-yM-p2.

**Comment by kalessil** [comment]
That's related to refunds, which are maintained by @Automattic/pulsar.

**Comment by kalessil** [comment]
For context: WooCommerce core has 'Restock items' options on refund, but in the early stages of the project, we decided that `Streamline refunds` would not cover it (as we didn't plan to cover full refunds of transactions with properly connected orders). 

@elizaan36: do you have the capacity to do a bit of graphics update of the full refund dialog and add a check box 'Restock inventory' (I need to lookup the exact text used in WooCommerce Core)?

**Comment by melek** [comment]
> For context: WooCommerce core has 'Restock items' options on refund, but in the early stages of the project, we decided that `Streamline refunds` would not cover it (as we didn't plan to cover full refunds of transactions with properly connected orders).

If the new functionality was only intended for transactions with properly connected order, I think that redirecting to the order for refunding would be preferable to the current 'Refund in full' behavior. 

I also am noticing that the 'Partial refund' option doesn't work on an orphaned transactions if that order existed and was then trashed, or if it was never linked in the first place. In that case, I'd expect a modal to come up to let me issue a partial refund - I've created a new issue for this here: #7983

I'd consider replacing three dot menu with a 'Refund' button like in Stripe, and handling the choice between full or partial in the modal for unlinked transactions. Until this restocking issue is fixed, I'd redirect to the order page; I really like the idea of handling refunds fulling from the Txn page, but duplicating the UI seems laborious when linking to the order gives all the refund options without having to worry about restocking or any other hooks / parts of the refund process that might be getting skipped. It could look like this:

- Orphaned TXNs: ![image](https://github.com/Automattic/woocommerce-payments/assets/220149/23c89fe0-7e34-4d0b-a3ad-79bdb4fbf28d)
- Linked TXNs: ![image](https://github.com/Automattic/woocommerce-payments/assets/220149/186e7694-1cc0-46a0-a3dd-809db883df65)

Edit: I'd also be transparent in the modal that the modal option is to help refund orphaned / unlinked transactions, and perhaps link to the related doc: https://woo.com/document/woopayments/managing-money/#refund-via-transaction-details

**Comment by elizaan36** [comment]
@kalessil In the designs shared here (paJDYF-9sf), it states that the items would be restocked. It seems that these requirements were missed somehow.

> This solution presents a popover menu from the transaction details, indicated by an ellipses (three dots) icon. The two options in the dropdown are the following:

> - “Refund in full”, which would refund the transaction. This would update the core order to indicate the new Refunded status, order details would indicate the amount refunded, and items will be restocked to inventory counts.
> - “Partial refund”, which would direct the user to the order details where merchant can have control of the number of items, amount, shipping, and whether to restock refunded items.
> When choosing the option to refund in full, the merchant is presented with a modal indicating that the full amount will be refunded to the customer. They also have the option of selecting a reason for the refund.

> Upon refunding in full, the order status of the associated order is updated to Refunded and all order notes and timeline content is consistent between payments and orders. The item should be restocked to the store inventory.

> Partial refund
In order to complete a partial refund, the merchant will be directed to the order details screen. Here there’s the ability to choose the number of items to refund, or to refund by a particular amount including shipping costs.

**Comment by kalessil** [comment]
Right, thank you, @elizaan36! We fixed the re-stocking issue.
