### ISSUE TITLE
On a fresh clone, composer install and then npm run build:release creates a 22 MB ZIP

### ISSUE THREAD

**Issue by allendav** [Automattic/woocommerce-payments#797]
Probably including more from vendor than needed?

Fresh clone of this repo
- npm install
- composer install
- npm run build:release

**Comment by DanReyLop** [comment]
> composer install

You're supposed to use [`composer install --no-dev`](https://github.com/Automattic/woocommerce-payments/blob/65032f16754985f6c73f6fd95987b3959a246ca7/package.json#L18) on a production build. Running [`npm run build`](https://github.com/Automattic/woocommerce-payments/blob/65032f16754985f6c73f6fd95987b3959a246ca7/package.json#L16) should take care of it. I'm getting a 304KB ZIP.

**Comment by jrodger** [comment]
Just to confirm, the release tooling uses `npm run build`. The last version uploaded to the plugin repository is the same size as @DanReyLop observed here.
