### ISSUE TITLE
New account waiting period says `business days` but the code uses calendar days – inconsistent

### ISSUE THREAD

**Issue by csmcneill** [Automattic/woocommerce-payments#7970]
### Describe the bug

When a WooPayments merchant captures their first payment, they enter the new account waiting period. This period is seven calendar days per [this](https://github.com/Automattic/woocommerce-payments-server/blob/322e9826eca751bfb9b82a8b384a089c2aca35c6/server/wp-content/rest-api-plugins/endpoints/wcpay/stripe/class-stripe-account.php#L798).

However, we currently indicate in [a couple of places](https://github.com/search?q=repo:Automattic/woocommerce-payments+%22seven+business+days%22&type=code) that this is business days.

### To Reproduce

1. Trigger the new account waiting period.
2. Note that there is a notice on the **Payments > Overview** page that reads:

```
Your first deposit is held for seven business days.
```

### Actual behavior

The merchant is notified that the new account waiting period is seven business days — even though it's seven calendar days.

### Screenshots

![seven business days](https://github.com/Automattic/woocommerce-payments/assets/82999806/ef9f7d9a-9f80-4b0c-9183-48cd1da1a19e)

### Expected behavior

The new account waiting period includes weekends and holidays. Even though deposits will not be initiated on non-business days, for the sake of clarity and accuracy, we should specify that the new account waiting period is seven calendar days (or just seven days) instead of seven business days.

### Additional context

p1703938260739969/1703936807.503649-slack-C3NCP7ZJ6
p1704123858585669-slack-C02BW3Z8SHK
7514473-zen

**Comment by jessy-p** [comment]
This issue impacts Deposits, Disputes, so assigning to Helix (based on team responsibilities Pc2DNy-3z-p2) @haszari. Assigning as part of Gamma Triage process PcreKM-yM-p2.

**Comment by haszari** [comment]
Adding to helix maintenance board as medium priority. The 7-day new account period is there for risk/fraud reasons, and is part of the onboarding process, so this issue could be handled by those teams also. I've added these labels.

We should at least make the messaging consistent with the code here, though it might be worth checking if this is intended to be business vs. calendar days (i.e. the code might be wrong & UI correct).

**Comment by csmcneill** [comment]
I checked in with support and they indicated the following:

> I can confirm that it is 7-14 calendar days.

**Comment by haszari** [comment]
> > I checked in with support and they indicated the following:

> I can confirm that it is 7-14 calendar days.

Thank you @csmcneill ! That's good info. It's likely the existing message is causing frustration after ~7 days, so a great idea to update it (and likely quick fix too). Raising priority to high.

Suggested wording: 

> `Your first deposit is held for 7-14 days.`

@rogermattic @souravdebnath1986 please comment if you have feedback or ideas for how to refine this message to set clearer expectations for first deposit.

**Comment by souravdebnath1986** [comment]
I am going to mark this down as `medium`. True that our messaging is incorrect, it still delivers on the promise of first deposit dispatched before 7 business days. This would be a bigger concern if it was the other way round i.e. coded as 7 business days and messaged as 7 calendar days. 

> Your first deposit is held for 7-14 days.

That's fair. This is in-line with the new account waiting period as per [Stripe docs](https://support.stripe.com/express/questions/waiting-period-for-first-payout-on-stripe#:~:text=Your%20first%20payout%20is%20typically%20available%20seven%20days%20after%20you%27ve%20added%20your%20bank%20account%20and%20taken%20your%20first%20successful%20payment%20on%20Stripe.%20This%20waiting%20period%20can%20be%20up%20to%2014%20days%20for%20businesses%20in%20certain%20industries)
We will probably have to change the wording in [our docs](https://woo.com/document/woopayments/deposits/deposit-schedule/#new-accounts) as well when the change goes out.

**Comment by rogermattic** [comment]
> True that our messaging is incorrect, it still delivers on the promise of first deposit dispatched before 7 business days. This would be a bigger concern if it was the other way round i.e. coded as 7 business days and messaged as 7 calendar days.

Agreed with @souravdebnath1986
