### ISSUE TITLE
Make "Sandbox mode" term used everywhere where "Dev mode" is used 

### ISSUE THREAD

**Issue by daquinons** [Automattic/woocommerce-payments#7974]
### Description
Following up on a decision driven here paJDYF-bGl-p2 we want to use "sandbox mode" instead of "dev mode" in order to avoid confusion for our users

This is an additional issue to https://github.com/Automattic/woocommerce-payments/issues/7731 which is only taking care of the "selection mode", when this issue takes care of settings, banners and everywhere else to have the "dev mode" renamed to "sandbox mode" everywhere (including the dev tool).

**Comment by dmallory42** [comment]
Placing this on hold pending the outcome of https://github.com/Automattic/woocommerce-payments/issues/7731.
