### ISSUE TITLE
Failing shopper E2E tests

### ISSUE THREAD

**Issue by timur27** [Automattic/woocommerce-payments#7980]
### Describe the issue
[E2E tests started to fail](https://github.com/Automattic/woocommerce-payments/actions/workflows/e2e-test.yml)

`WC - latest | wcpay - shopper` has two failing test suites:
* `shopper-checkout-free-cart.spec.js`
* `shopper-myaccount-payment-methods-add-delete-success.spec.js` which most probably depends on the failure from the previous test suite

As per my investigation, this might be related to [this code](https://github.com/Automattic/woocommerce-payments/blob/develop/client/checkout/classic/event-handlers.js#L62-L72).

**Comment by jessy-p** [comment]
This issue impacts Release Process, Monitoring (including On-call process ownership), MC Tools, Dev Tools, CI/CD Pipeline, and Dependencies Management, so assigning to Harmony (based on team responsibilities Pc2DNy-3z-p2) @deepakpathania. Assigning as part of Gamma Triage process PcreKM-yM-p2.

**Comment by deepakpathania** [comment]
There is a PR for the issue already.
