### ISSUE TITLE
 Partial Refunds for orphaned tsransactions result in 404 / "That page can’t be found"

### ISSUE THREAD

**Issue by melek** [Automattic/woocommerce-payments#7983]
### Describe the bug
When partially refunding an orphaned transaction from the Transaction Page in WooPayments 7.0.0, the merchant is redirected to a 404 / Page can't be found page. Instead I'd expect a UI flow similar to the one in the Stripe dashboard for refunds.

### To Reproduce
1. Create an orphaned transaction, either deleting an order placed with WooPayments, or by manually adding a payment in the Stripe dashboard on the connected account.
2. View the transaction in Payments → Transactions. The 'Order' field will be blank.
3. Click on the three dots and click 'Partial refund'.
4. See error - "Oops! Thank page can't be found.". Observe the URL as well: `https://example.com/wp-admin/undefined`

### Actual behavior
The merchant is redirected to a 404 / undefined endpoint. 

### Screenshots
![image](https://github.com/Automattic/woocommerce-payments/assets/220149/7cea5752-705e-4dd6-921a-254a62d8dbf5)
![image](https://github.com/Automattic/woocommerce-payments/assets/220149/75fe8dd3-af4b-458f-9aa9-90c829bc90b1)

### Expected behavior
Transactions can be orphaned for multiple reasons, and sometimes a partial refund might be needed for an unlinked transaction. For example, if a customer had to restore to a backup, some number of transactions may have lost linkage with their respective orders, and some of these customers may need a partial refund.

I'd expect the 'Partial refund' functionality to work in these cases, probably with a modal like in Stripe:
![image](https://github.com/Automattic/woocommerce-payments/assets/220149/3cec7d72-208b-4f8f-91bc-cddbab44604e)

### Desktop (please complete the following information):

* OS: MacOS
* Browser: Firefox
* Version: Latest

### Additional context
- For orphaned transactions, the three dot menu could just be replaced with a single 'Refund' button like in Stripe.
- Linked transactions could always point to the order page until #7969 is resolved.

**Comment by jessy-p** [comment]
This issue impacts Fees, Transactions (Auth and Capture), Refunds, Amazon Pay, In-Person Payments so assigning to Pulsar (based on team responsibilities Pc2DNy-3z-p2) @kalessil. Assigning as part of Gamma Triage process PcreKM-yM-p2.

**Comment by dmvrtx** [comment]
@melek, partial refunds for orphaned transactions are out of scope of work at the moment. Thus, only full refunds are supported for orphaned transactions.

Regarding this issue, I'm working on a fix to prevent menu item from appearing if order is not known to WooCommerce.
