### ISSUE TITLE
Spike: Detect multiple plugins providing the same payment methods

### ISSUE THREAD

**Issue by bborman22** [Automattic/woocommerce-payments#7993]
### Description

A problem that merchants can face when using multiple payment gateways on their shop is having the same payment method provided twice (or more), once from each gateway. This shows up most obviously with payment buttons like Apple Pay and Google Pay, but can also show up by providing the same methods like Afterpay or P24, etc. 

This problem can create a confusing UI for the shopper and could impact conversion. Overall it could negatively impact the shopper's perspective of the store.

The goal of this issue is to determine the technical feasibility of determining when multiple payment methods are being provided by different plugins. This could be technically challenging given the wide range of possible plugins and their naming, etc. At a bare minimum we should be able to address this issue with all of our internal payment gateways, but ideally be able to address this more broadly.

The end result of this detection would likely be a notification to the merchant about the duplicated payment methods.

### Acceptance criteria

- A GH comment explaining the findings of the research and if applicable an RFC for the suggested approach.
- A draft PR showing how this detection process could work in practice.

### Additional context

pc2DNy-3ru-p2

**Comment by pierorocca** [comment]
Looks great Brian. Thanks for capturing this. One way to combat naming challenges, if that is indeed something that's determinable, is maintaining a mapping for the most common gateways.

**Comment by jessy-p** [comment]
@bborman22  Would your team be working on this?

**Comment by pierorocca** [comment]
@jessy-p yes correct as BE now owns the merchant settings that line up with shopper ui/ux.

**Comment by bborman22** [comment]
@jessy-p Yes, this will be handled by @Automattic/fractal, thanks!

**Comment by bborman22** [comment]
Sorry for the confusion, but based on this conversation p1706829373735599-slack-C043JN7AJHY this will be handled by @Automattic/heisenberg.

**Comment by timur27** [comment]
Hey @pierorocca @FangedParakeet! After analyzing the solutions and considering the details involved, I've decided to share my findings in a P2 post at paJDYF-ck0-p2.

There's also a draft https://github.com/woocommerce/woocommerce/pull/44617 created in WooCommerce Core, which covers the main pieces for two proposed solutions.

I will keep an eye on the P2 post if there's any feedback from Woo Core Engineering. Other than that, I'll discuss the next steps for this feature with you all within the next few days. We can also decide on the status for this issue (if it should be closed given the ACs are met and a separate issue should be created). Of course, I'm always happy to align further whenever you need me! :)

**Comment by timur27** [comment]
Below is the summary of the work that has been done as part of this issue
1. Technical analysis: paJDYF-ck0-p2
2. Two solutions' drafts implemented in https://github.com/woocommerce/woocommerce/pull/44617
3. Feedback on the solutions which confirms that they can be considered (especially the second one): paJDYF-ck0-p2#comment-23314
4. Discussion on solutions with one of the Woo Core teams p1707475837221869-slack-C0E1AV8T0
5. Analysis of potential implementation amendments based on data gathered paJDYF-cwe-p2#comment-23280. 

The conclusion for me at the moment is that the initially proposed solutions won't be changed after refining the false positive occurrences and gathering feedback. If the decision is taken to develop the implementation in Woo Core, I can help create separate issues. I'm planning to close this issue by the end of the week, and before doing so, I'm happy to hear if there is anything I can help with here! 👍

**Comment by pierorocca** [comment]
Wanted to add @timur27 this is thorough and impressive work. I appreciate your attention to detail and collaboration. You rock.
