### ISSUE TITLE
Pending payment order issue: Can't find variable: wcpayPaymentRequestPayForOrderParams on login page

### ISSUE THREAD

**Issue by wpniall** [Automattic/woocommerce-payments#7996]
### Describe the bug
The "Can't find variable: wcpayPaymentRequestPayForOrderParams" error appears in specific circumstances on the Customer payment log in page after manually creating a pending order.

### To Reproduce

1. Create a pending payment order for an existing user.
2. Copy the link for the Customer payment page into a new incognito/private browser window in Chrome or Safari (or a browser when not logged in to the site).
3. The wcpayPaymentRequestPayForOrderParams localization wcpayPaymentRequestPayForOrderParams param will not be defined.

Note: This issue does not happen on a guest order given there is no login required. No error appears after logging in to the site.

#### Error on Chrome:
![image](https://github.com/Automattic/woocommerce-payments/assets/773782/6cae180d-49bd-472d-ae78-b0cce639676a)

#### Error on Safari:
![image](https://github.com/Automattic/woocommerce-payments/assets/773782/e100db7f-7ace-44c1-b649-3b5fa827c50e)

### Expected behavior
No error should happen when opening a pending payment order when not logged in.

### Desktop (please complete the following information):
N/A

### Smartphone (please complete the following information):
N/A

### Merchant's suggestion for a fix
A merchant suggested the following to fix this issue:

In the file where this is hooked in `woocommerce-payments\includes\class-wc-payments-payment-request-button-handler.php` with the method `display_pay_for_order_page_html`, this can be moved from:

```
add_action( 'before_woocommerce_pay_form', [ $this, 'display_pay_for_order_page_html' ], 1 );
```
to:

```
add_action( 'before_woocommerce_pay', [ $this, 'display_pay_for_order_page_html' ], 1 ); 
```

Then update the method to get the order from the query vars:

```
/**
 * Displays the necessary HTML for the Pay for Order page.
 *
 * @param WC_Order $order The order that needs payment.
 */
public function display_pay_for_order_page_html() {
    global $wp;
    $order_id = !empty( $wp->query_vars['order-pay'] ) ? $wp->query_vars['order-pay'] : false;
    if ( !$order_id ) {
        return;
    }

    $order = wc_get_order($order_id);
    if ( !$order ) {
        return;
    }

    $currency = get_woocommerce_currency();
```

### Additional context
7556917-zd-a8c

**Comment by jessy-p** [comment]
This issue impacts Checkout UI so assigning to Heisenberg (based on team responsibilities Pc2DNy-3z-p2) @FangedParakeet. Assigning as part of Gamma Triage process PcreKM-yM-p2.

**Comment by sandgreenOU** [comment]
Have the same issue, when customer try to pay pending order. 
- Breakdance Builder.

the change of the code doesn't fix the problem!

**Comment by gpressutto5** [comment]
Hi @wpniall, can you test if https://github.com/Automattic/woocommerce-payments/pull/8014#issuecomment-1889615605 fixes the issue, please?

**Comment by sandgreenOU** [comment]
I added the code to the payment-request.js:	if ( ! window.wcpayPaymentRequestPayForOrderParams ) {
					return;
				}

Sorry, nothing happens. still empty checkout page with the JS-errror:
Uncaught ReferenceError: wcpayPaymentRequestPayForOrderParams is not defined
    at Object.init (payment-request.js?ver=7.0.0:1:40009)
    at HTMLDocument.<anonymous> (payment-request.js?ver=7.0.0:1:40616)
    at e (jquery.min.js?ver=3.7.1:2:27028)
    at t (jquery.min.js?ver=3.7.1:2:27330)

**Comment by gpressutto5** [comment]
Adding the code to the js file won't have any effect because that's not the js file used by the browser. You have to build it for it to have effect. Could you try again using the build [from the PR](https://github.com/Automattic/woocommerce-payments/pull/8014#issuecomment-1889615605)?

**Comment by sandgreenOU** [comment]
uhh.. i am Web developer, not at coder. What is a PR?  i thought the plugins are still just source code...?   need help ... or i wait for the update of the woopayment plugin.  what should i do?

**Comment by gpressutto5** [comment]
Oh, I understand. Let's wait for @wpniall to test it, and if it fixes the issue, you can get the fix in the new version.

I noticed you mentioned an _empty checkout page with the JS error_. I'm not sure these errors are related. I tested this without the fix, and even with the JS error in the console, the checkout form is still displayed, and it is possible to place the order. @wpniall, how does it work for you?
