### ISSUE TITLE
Incorrect Warning Notice About Location Availability - Puerto Rico

### ISSUE THREAD

**Issue by nicholasjeberlin** [Automattic/woocommerce-payments#8001]
When Puerto Rico is selected as the country under <strong>WooCommerce > Settings > General > General options > Default customer location > Shop base address</strong>:
<img width="1512" alt="Screenshot 2024-01-09 at 5 33 12 PM" src="https://github.com/Automattic/woocommerce-payments/assets/18408583/d81d5f7e-f89e-432e-b2a1-d418b5c00494">

WooCommerce Payments generates a warning notice letting you know that WooPayments is not available in the selected location:
<img width="1512" alt="Screenshot 2024-01-09 at 5 32 06 PM" src="https://github.com/Automattic/woocommerce-payments/assets/18408583/b711dbd7-34fd-4c57-85a3-50c68e1ab935">

However, Puerto Rico is a US Territory, and is supported:
https://woo.com/document/woopayments/compatibility/countries/#outlying-territories-of-the-us

**Comment by csmcneill** [comment]
From an onboarding perspective, a PR merchant is considered a US merchant. Onboarding as a PR merchant requires selecting `United States` as the country and then choosing `Puerto Rico` as the state:

![puerto rico us](https://github.com/Automattic/woocommerce-payments/assets/82999806/32ea5f65-8e5d-42ec-8e42-e72b60c177de)

**Comment by jessy-p** [comment]
This issue impacts Onboarding, Account management, General purpose communications and communication tools, so assigning to Moltres (based on team responsibilities Pc2DNy-3z-p2) @daquinons. Assigning as part of Gamma Triage process PcreKM-yM-p2.

**Comment by ismaeldcom** [comment]
We're evaluaiting the best way to solve this issue going forward, more details in this Slack thread(p1707129988050199-slack-CGGCLBN58).

As a temporary solution, Purto Rico merchants can onboard by setting their country to US in WooCommerce settings.

**Comment by daquinons** [comment]
Product decision is to consider from a Payments perspective Puerto Rico as a US state p1707232315180359/1707129988.050199-slack-CGGCLBN58

In this issue we need to make sure that the location banner availability is not shown when Core has "Puerto Rico" selected.

In our current MOX, PR doesn't appear at all, but we need to make sure that if "Puerto Rico" is selected in Core, we pre-select US in the onboarding form.
