### ISSUE TITLE
Export transactions fails for a large number of transactions

### ISSUE THREAD

**Issue by dpaun1985** [Automattic/woocommerce-payments#8008]
We received reports about exporting the transactions. It seems that for a large number of transactions, the export fails. 
We need to identify the root cause that makes merchants to not receive the email containing the export link.

Context: p1704823898940709-slack-C7U3Y3VMY

**Comment by jessy-p** [comment]
This issue impacts Reporting, Extensibility & Integrations, International Expansion (formerly), and Answering to Customer Success Team so assigning to Fusion (based on team responsibilities Pc2DNy-3z-p2) @anu-rock. Assigning as part of Gamma Triage process PcreKM-yM-p2.

**Comment by sverleis** [comment]
## Linked interaction(s)
- 7559555-zen → 7726672-zen
