### ISSUE TITLE
Safe Mode Message Showing Origin Name in Reverse.

### ISSUE THREAD

**Issue by AmeliaBriscoe** [Automattic/woocommerce-payments#8025]
### Describe the bug
When the 'Safe Mode' appears for merchants that are changing the domain, the origin domain is appearing in reverse in the message

### Screenshots

![woocomerce bug](https://github.com/Automattic/woocommerce-payments/assets/2174223/fc6592ef-5608-4256-a4bf-3d6e94f9006f)

![Screen Shot 2024-01-15 at 2 19 25 PM](https://github.com/Automattic/woocommerce-payments/assets/2174223/59bd3a09-650f-4860-b916-9eb383739296)

### Expected behavior

The origin domain name should appear correctly in the message

### Additional context

Tickets:
 - 7589094-zd
- 7589228-zd

**Comment by WillBrubaker** [comment]
Also spotted in 7589094-zen adding backward and backwards for search terms.

**Comment by jessy-p** [comment]
This issue impacts Onboarding, Account management, General purpose communications and communication tools, so assigning to Moltres (based on team responsibilities Pc2DNy-3z-p2) @daquinons. Assigning as part of Gamma Triage process PcreKM-yM-p2.

**Comment by daquinons** [comment]
After reviewing it with Product we are decreasing its priority to medium:
- The core functionality works
- The visual regression occurs only in a section of the screen, being still present correctly on the main cards 

Also some discoveries:
Might be related to pf5801-3R-p2 and https://github.com/Automattic/jetpack-identity-crisis/blob/trunk/src/class-identity-crisis.php#L465

**Comment by AbhinavSakalle** [comment]
Also reported in 7607389-zen
