### ISSUE TITLE
Invalid Recurring Shipping Method with Apple / Google Pay When Paying for Multiple Subscriptions

### ISSUE THREAD

**Issue by mattallan** [Automattic/woocommerce-payments#8029]
Originally reported in 4606-gh-woocommerce/woocommerce-subscriptions

---

### Describe the bug

When attempting to purchase multiple subscriptions of varying periods with Apple/Google Pay, you will get an "Invalid recurring shipping method." error:

![image](https://github.com/Automattic/woocommerce-payments/assets/2275145/5e474977-08da-4c86-b070-cc0c27023430)

After some initial investigation I believe this issue is caused by WooPayments wiping the recurring shipping methods from the `chosen_shipping_methods` session when it calls [`WC()->shipping->reset_shipping()`](https://github.com/Automattic/woocommerce-payments/blob/f63d75f2c2a83e8dce804fa0b248e86eefbeeeac/includes/class-wc-payments-payment-request-button-handler.php#L1412), which is called when calculating the shipping options to display in the Apple/Google Pay pop-ups.

Before we wipe/clear the chosen shipping methods, we store them in a [variable here](https://github.com/Automattic/woocommerce-payments/blob/f63d75f2c2a83e8dce804fa0b248e86eefbeeeac/includes/class-wc-payments-payment-request-button-handler.php#L937) so I think to fix this we'll need to restore any other chosen shipping methods that were wiped.

#### Additional details
Example of shipping_method data from payment button $_POST:

```
Array
(
    [0] => free_shipping:2
)
```

Example from a default checkout process:

```
Array
(
    [0] => free_shipping:2
    [2024_04_12_every_3rd_month_0] => free_shipping:2
    [2024_03_12_every_2nd_month_0] => free_shipping:2
)
```

### To Reproduce

1. Install and activate the latest Woo Subscriptions plugin
2. Enable/activate Apple Pay and Google Pay payment request buttons
3. Create two subscription products with different billing periods (monthly and weekly)
4. Add both subscription products to your cart and navigate to the checkout page
5. Purchase the checkout with Google Pay
6. Notice the error seen in the screenshot above

### Desktop (please complete the following information):

* OS: [e.g. iOS]
* Browser [e.g. chrome, safari]
* Version [e.g. 22]

### Smartphone (please complete the following information):

* Device: [e.g. iPhone6]
* OS: [e.g. iOS8.1]
* Browser [e.g. stock browser, safari]
* Version [e.g. 22]

**Comment by zmaglica** [comment]
This issue impacts WC Payments Subscriptions so assigning to Quark (based on team responsibilities Pc2DNy-3z-p2) [@diego373](https://github.com/diego373). Assigning as part of Gamma Triage process PcreKM-yM-p2.

**Comment by glagonikas** [comment]
Hi @mattallan can you check if #8602 indeed resolves the issue and complies with the coding requirements? We could do with having this merged soon as it's affecting a reasonable number of customers.

I suspect a similar PR would also resolve https://github.com/woocommerce/woocommerce-gateway-stripe/issues/2837

**Comment by mattallan** [comment]
Hey @glagonikas I've just left a comment on https://github.com/Automattic/woocommerce-payments/pull/8602 but I'll also message here to let you know there was an issue with the approach taken, so I've pushed up a PR which fixes this in a different way: https://github.com/Automattic/woocommerce-payments/pull/8618
