### ISSUE TITLE
Create automated tests for critical flow: View Uncaptured transactions in Transactions page

### ISSUE THREAD

**Issue by mgascam** [Automattic/woocommerce-payments#8036]
### Description

We want to create e2e tests to automate the testing of the [View Uncaptured transactions in Transactions page](https://github.com/Automattic/woocommerce-payments/wiki/Testing-instructions-for-critical-flows#view-uncaptured-transactions-in-transactions-page)] critical flows that are currently manually tested.

### Acceptance criteria

* Implement the steps to test the `View Uncaptured transactions in Transactions page` critical flow as automated E2E test(s).

### Additional context

Related spike: https://github.com/Automattic/woocommerce-payments-server/issues/4454

**Comment by kalessil** [comment]
Closing, we need to re-iterate how to reliably actualize transactions cache in E2E (tests flackiness).
