### ISSUE TITLE
New account waiting period notice is not displayed for new accounts (regression)

### ISSUE THREAD

**Issue by haszari** [Automattic/woocommerce-payments#8040]
### Describe the bug
After onboarding to WooPayments, the first payouts are held for 7-14 days to mitigate risk for new accounts. We have a notice to explain this to merchants:

![seven business days](https://github.com/Automattic/woocommerce-payments/assets/82999806/ef9f7d9a-9f80-4b0c-9183-48cd1da1a19e)

However, it's not currently displaying, because the notice is not rendered unless … the store has at least one deposit (! 🤨): 

https://github.com/Automattic/woocommerce-payments/blob/81f4be369a8571fa708316dcccbb2290a4732f0e/client/components/deposits-overview/index.tsx#L91-L94

Thanks @Jinksi for discovering this

### To Reproduce
1. Onboard a new WooPayments account.
2. Make a test purchase.
3. Go to `Dashboard > Payments` overview screen.

Should have a message here explaining that deposits will start 7-14 days after first payment.

### Actual behavior
No notice on overview.

There is one in settings:

<img width="1113" alt="Screenshot 2024-01-18 at 10 45 07 AM" src="https://github.com/Automattic/woocommerce-payments/assets/4167300/747ac641-281f-4010-8d3f-c97114377b38">

**Comment by haszari** [comment]
Marking this as `priority: high` and adding to current sprint because:

- This notice is important for setting expectations during onboarding and appears to be not showing at all.
- Should be a low-risk fix.
- Is blocking work-in-progress to fix the wording of this notice:
  - #8030

**Comment by haszari** [comment]
I suspect this regressed as part of removing estimated deposit from that deposits overview card 💭

**Comment by haszari** [comment]
FYI Gamma this is already assigned and on Helix board, no need to tag us in triage.

**Comment by Jinksi** [comment]
> Marking this as priority: high and adding to current sprint

I'll add to the 7.1 milestone as we should attempt to get this in with 7.1
