### ISSUE TITLE
WC Pre-Orders pay later should not redirect to WooPay for existing users

### ISSUE THREAD

**Issue by hsingyuc** [Automattic/woocommerce-payments#8053]
### Describe the bug

When testing the pay later Pre-Orders product with an existing user email, on the blocks checkout page, the WooPay iframe would pop up but doesn't redirect shopper to the WooPay checkout page.

### To Reproduce

1. Install and activate WC Pre-Orders plugin
2. Create a pre-order product and pick `upon release` for `When to charge`
3. As an existing shopper, add the product to the cart and go to the checkout page
4. See the WooPay iframe pop up, use test code and doesn't redirect to the WooPay checkout page

### Actual behavior
The WooPay iframe would pop up but doesn't redirect shoppers to the WooPay checkout page.

### Screenshots / Video

https://github.com/Automattic/woocommerce-payments/assets/56378160/a510dc71-08cd-4c95-8176-8472d72416d4

### Expected behavior
If the product set to upon release(pay later) then the WooPay iframe should not pop up

**Comment by zmaglica** [comment]
This issue impacts WooPay, so assigning to team Fractal (based on team responsibilities Pc2DNy-3z-p2) @bborman22 .
Assigning as part of Gamma Triage process PcreKM-yM-p2.

**Comment by hsingyuc** [comment]
I'm fixing [this issue](https://github.com/Automattic/woocommerce-payments/issues/7684) for WC Bookings, and this Pre-Orders issue will be fixed as well.
