### ISSUE TITLE
Merchants Receive monthly VAT Emails without VAT Information Entered

### ISSUE THREAD

**Issue by CGA8C** [Automattic/woocommerce-payments#8054]
### Describe the bug
If a Merchant is in a VAT country, they receive the monthly, "Your VAT Invoice report is ready" email, despite not having documents available. Example: 7439195-zen

### To Reproduce

1. Do not enter VAT Information during Onboarding
2. Wait until the 10th of the next month
3. Receive "Your VAT Invoice report is ready" email
4. The link won't work, because there are no documents available. 

### Expected behavior
If no VAT Information is added by a Merchant, they shouldn't receive this email.

**Comment by zmaglica** [comment]
This issue impacts VAT reports, so assigning to Team Fusion (based on team responsibilities Pc2DNy-3z-p2) @anu-rock .
Assigning as part of Gamma Triage process PcreKM-yM-p2.

**Comment by anu-rock** [comment]
@zmaglica Thanks for the ping. I've added it to Fusion's board. We'll prioritize it soon.

**Comment by anu-rock** [comment]
@coreymckrill It sounds like a glaring issue. Has it always been like this or a recent occurrence?

@jessepearson Do you happen to have a clue about this?

**Comment by jessepearson** [comment]
Without reviewing the code, there does seem to be an issue. If a merchant is in a VAT country, the documents should be created for them whether they have entered VAT info or not. The creation happens so that the invoices are available for when they do enter the information, as there's nothing that backfills once the information is entered. They will only have access to the documents/invoices once they enter VAT information, though.

IIRC, the email isn't sent to the merchant until the document is created in the database. 

> If no VAT Information is added by a Merchant, they shouldn't receive this email.

I don't think this is correct. We can create the document, but if they do not have VAT information entered, we can skip the email. This goes back to what I mentioned about there's nothing to automatically backfill once they enter their information.

**Comment by coreymckrill** [comment]
I think the above ping was meant for @CGA8C

**Comment by anu-rock** [comment]
> I think the above ping was meant for @CGA8C

Whoops, sorry about that and thanks for correcting 🙌

**Comment by CGA8C** [comment]
I'm not sure why I didn't get a ping for this: I just happened upon this reply by chance. 🙃 

> It sounds like a glaring issue. Has it always been like this or a recent occurrence?

I'm not sure it's always been like this, but it has been like this for the past 6 months or so. I've used it as a chance to add their VAT Number for them, but it's definitely something we should fix. 

> Without reviewing the code, there does seem to be an issue. If a merchant is in a VAT country, the documents should be created for them whether they have entered VAT info or not. The creation happens so that the invoices are available for when they do enter the information, as there's nothing that backfills once the information is entered. They will only have access to the documents/invoices once they enter VAT information, though.

Ooo, so this does suggest a different issue, because this isn't accurate as it stands right now. 

What happens right now is that if the Merchant doesn't have a VAT number entered, we get an Error when we try to access their Invoices. Example: acct_1LkT13FdsdkAislW

![Markup on 2024-02-12 at 1:40:08 PM](https://github.com/Automattic/woocommerce-payments/assets/17998077/6ec7c50a-37f0-4546-9571-1491bc72f9cf)

They also don't see the "Documents" tab when they don't have a VAT Number, yet they get the email. 

HOWEVER, when we do enter their VAT Number, it is backfilled: all of their Invoices since they created the account are displayed, with the new information. 

So it sounds like the issue may be more related to that error in the screenshot above, instead of the emails themselves. 🤔 

CC: @jessepearson

**Comment by CGA8C** [comment]
Also, one tiny little additional note that may be useful: the Merchant's Documents Tab _won't _appear_ right away when we add their VAT number, but instead shows up on the 10th of the next month, when the next Document is generated.

**Comment by CGA8C** [comment]
7865163-Zen

**Comment by haszari** [comment]
Added to Helix board (assuming we are handling VAT invoices, related to reporting focus). 

@CGA8C – do you know steps for how we could reproduce this locally? What store setup do we need to keep in mind to set up VAT support in test store?

**Comment by CGA8C** [comment]
@haszari I would only know how to reproduce this from a Merchant standpoint, which will be time consuming: 
- Onboard an Account, selecting a VAT Country (EEA and UK)
- Do not add VAT Information
- Complete at least one transaction
- Wait until the 10th of the next month for a VAT Invoice to be issued. 

I'm sure there's a way to trigger this process without waiting a month, but that's above my technical knowledge. 

I do want to note again that it seems like what's happening is that VAT Documents are being generated whether they enter VAT Information or not (which is good), but either they shouldn't be getting this email if they haven't added a VAT Doc, OR they should get access to their VAT Doc, without any VAT Information added to the Doc.

**Comment by haszari** [comment]
Thanks @CGA8C that's really helpful. This gives us a (slow) way to reproduce, relevant settings/config, and we can find out a way to trigger that async job. 🙌

**Comment by CGA8C** [comment]
It's the 11th of the month, so we have a fresh batch of Merchants dealing with this, so looking at these accounts may be able to provide some insight:
- ZD-8027719 (acct_1OltBpFptJ8jCuwV)
- ZD-8026992 (acct_1OrGPLCRhBz1PjwA)
