### ISSUE TITLE
tracks events names are easier to manage inline (constants file is not helpful)

### ISSUE THREAD

**Issue by haszari** [Automattic/woocommerce-payments#8066]
### Describe the bug
[Many of our tracks events names are stored as constants in `/tracks/index.js`](https://github.com/Automattic/woocommerce-payments/blob/f1a2d7c81570fc1c4eeb09abeb05cc710a226fc8/client/tracks/index.js).

This is unnecessary, and makes it more painful to iterate on tracks:

- If you want to find where an event is triggered, you can't search for the event name (you need to search for the constant instead).
- If you need to iterate on the name of an event, you also need to update the constant (or … if you don't, the variation will add to confusion).
- If you want to find all events sent in a file/subfolder, searching for `recordEvent` doesn't show the actual event name.
- Event names are decoupled from their props.

I recommend the following approach:

- Pass event name direct as a literal string to `recordEvent`, alongside the props.
- Remove constants for event names (over time - we don't have to do this immediately).
- (Note that the event name in code will be unprefixed, as Woo core adds `wcadmin_` prefixed.)

The example code in field guide `Recording Events in Tracks` page (PCYsg-4KT-p2) has event names inline, for example:

> ```
> window._tkq = window._tkq || [];
> window._tkq.push( [
>   'recordEvent',
>   'wpadmin_domain_search',
>   { status: 'available' }
> ] );
> ```

Note also other Automattic code bases have event names inline as raw strings. I'd argue we should aim for broad consistency unless we have good reason to take a different approach.

- Calypso (WPCOM): https://github.com/search?q=repo%3AAutomattic%2Fwp-calypso+recordTracksEvent&type=code&p=2
- Jetpack: https://github.com/search?q=repo%3AAutomattic%2Fjetpack%20recordEvent&type=code
- WooCommerce: https://github.com/search?q=repo%3Awoocommerce%2Fwoocommerce%20recordEvent&type=code

--- 

I don't know the history and rationale for these constants, so if anyone is aware of benefits to these constants, please comment! One potential reason would be to ensure the event name is consistent everywhere (i.e. avoid typos). Any event typos should show up in PR reviews, testing, and tracks data, and can easily be rectified. If there is a typo in the constant value … see above about iterating on names! Looks like `events` was introduced early (#855), though that PR doesn't have specifics on why move constants out of line.

**Comment by haszari** [comment]
This has been bugging me for a while 😄 .  I'm working on Helix-owned events in this PR at a background priority: #8069

**Comment by zmaglica** [comment]
@haszari do you maybe know, will team Helix work on this issue, or shall I move it to the Gamma backlog?

**Comment by haszari** [comment]
> will team Helix work on this issue, or shall I move it to the Gamma backlog?

Thanks for checking @zmaglica . I had planned to work on _part_ of this (move Helix event names out of constants) though at a low priority (#8069). If there's agreement that this is worthwhile, yes please shift it to Gamma backlog – I appreciate y'all taking on my idea :)

**Comment by haszari** [comment]
Fixed by @dmallory42 in #8166 🎉 

- #8166

Closing.
