### ISSUE TITLE
Show `total` balance instead of `pending` to reduce confusion when pending is negative

### ISSUE THREAD

**Issue by haszari** [Automattic/woocommerce-payments#8070]
### Describe the bug
We currently show account balances as two numbers:

- `Available funds` - the amount of $ that is available to payout in a deposit, i.e. has cleared pending period
- `Pending funds` - the amount of $ from recent transactions that is still pending, and not available to pay out (yet)

At times these numbers can be confusing, especially when `Pending` is negative (usually temporarily). Here are some situations where this might apply:

- A deposit is in transit
- An instant deposit has been triggered recently
- Other situations due to refunds or dispute fees

When the pending balance is negative, this is concerning and can lead to support requests and confusion about the health of the account balance. 

To mitigate this, we could present account balance in a different way, that doesn't emphasise temporary negative pending balance:

- `Available funds` - as before
- `Total balance` - pending + available, roughly equivalent to TPV cashflow, the $ value in the account right now

In future projects we may revisit some UI relating to this, e.g. the overview screen in general, or showing risk reserve amounts (which can affect available funds for some accounts). This issue is tightly scoped to addressing the immediate pain point.

The goal of this bug is to change the UI element currently showing `Pending funds` to show `Total balance`.

### To Reproduce
TBC – I don't know reproduce steps off hand, feel free to update this section, thank you 🙇

### Screenshots
![woo2](https://github.com/Automattic/woocommerce-payments/assets/4167300/6cf3777e-d319-4665-a6ed-8cffb8740595)

and this is the new design – in line with the new Payments Overview widget that team Fusion is working on:
<img width="1500" alt="Overview - Finance Overview – Balance" src="https://github.com/Automattic/woocommerce-payments/assets/94967682/ca1a7365-0abd-473e-ac0d-856ed1677dfe">

### Expected behavior
Show merchant account balance in a way that does not cause concern.

##### Additional context
This issue has been hotly discussed internally, and comes up in support regularly. 

pdjTHR-2Sz-p2 paJDYF-bY2-p2#comment-22689

**Comment by haszari** [comment]
Marking as high priority as this has been noted as a high-impact bug recently (paJDYF-bY2-p2#comment-22689) and also reported consistently by merchants to support (pdjTHR-2Sz-p2).

**Comment by Jinksi** [comment]
> To mitigate this, we could present account balance in a different way, that doesn't emphasise temporary negative pending balance:

> `Available funds` - as before
> `Total balance` - pending + available, roughly equivalent to TPV cashflow, the $ value in the account right now

Should this say "`Pending funds` - as before" @haszari ?

**Comment by haszari** [comment]
> Should this say "Pending funds - as before"

No – we don't want to show pending $ in the UI, and we don't want to confuse things by labelling a value with `Pending` when it is pending+available … unless I'm confused?

**Comment by Jinksi** [comment]
> unless I'm confused?

It is me that was confused! Thanks for clarifying.

**Comment by zmaglica** [comment]
@haszari I moved this issue to the Other Teams queue since I noticed the conversion between you and @Jinksi . Do you think that Helix can work on this issue, or shall I move it to the different team or within the Gamma backlog?

**Comment by haszari** [comment]
Thanks @zmaglica – Helix plans to fix this, it's prioritised in our backlog.

**Comment by rogermattic** [comment]
Hey, I updated the issue above with the new designs screenshot, since I'm finally sure that the design is ok!

**Comment by grig-23** [comment]
In 7726276-zen we have a confusing situation:

Two payments were processed, let's just say US$420.89 and US$889.05, and disregard fees and currency conversion to make things simpler.

For some reason though on this screen at one point it was showing "available funds" as $420.89 but "pending funds" was not $889.05 but 889.05 minus 420.89 = 468.16:

<img width="641" alt="Screenshot 2024-02-14 at 11 32 07" src="https://github.com/Automattic/woocommerce-payments/assets/13084901/55a2ac9b-281c-4415-96f3-f21c9f0936e7">

I'm not sure at all why this happened, maybe the first deposit of 420.89 was already initiated, but then why all the amount of 889.05 was divided between "pending" and "available"? The merchant is confused and frustrated.

Let me know if this belongs in some other bug report.

**Comment by csmcneill** [comment]
@grig-23 This issue is intended to address discrepancies like this.

The pending and available balance is pulled directly from Stripe. As a result, this information can sometimes reflect how the funds move through Stripe's systems. Our hope here is that by removing the `Pending funds` option and replacing it with a `Total balance` section, it can help reduce these kinds of interactions.

**Comment by namiokuzono** [comment]
7781892-zd-a8c

**Comment by Brianmitchtay** [comment]
7792858-zd-a8c would also be helped by this
