### ISSUE TITLE
Spike: Break down the work for Payments widget on Overview page

### ISSUE THREAD

**Issue by anu-rock** [Automattic/woocommerce-payments#8076]
### Description

The proposed **Payments Widget** on the Payments Overview page will enhance the discoverability of various reporting features in WooPayments. The designs are detailed in P2 and Figma (linked below). See the P2 before going deeper in Figma.

Since the widget is a considerable piece of UX with several moving parts, we would like to analyze the designs and identify opportunities to break the widget down into smaller, manageable tasks (if necessary).

### Acceptance criteria

*  Identify all front-end components required to realize the design. This list of identified components should include both existing (WordPress/WooCommerce) and missing components.
* Propose/create separate issues for the missing components.
* Propose/create separate issues for composable parts of the widget.

### Designs

p6riRB-9LX-p2
bIfbBgyBPRzvXEl7dEg3cv-fi-294%3A42839

**Comment by mordeth** [comment]
More context on the break down: pepjwh-Jw-p2
