### ISSUE TITLE
When WCPay is Installed during the OBW, users are redirected to WCPay Settings

### ISSUE THREAD

**Issue by timmyc** [Automattic/woocommerce-payments#808]
While testing out 4.4 beta 1 today - I saw that if a user elects to install the recommended plugins ( which now includes WCPay ), they are redirected to the WC Pay setup screen after selecting a theme in the onboarding wizard:

https://cloudup.com/c8f7mBL21eD

__Steps to Reproduce__
- On a fresh JN site
- Install the woocommerce beta tester plugin, and switch to 4.4.0-beta.1
- Launch the OBW, use a US-based address, and elect to install all recommended biz extensions.
- Note that after you select a theme, you are then redirected to the WC Pay setup screen.

__What I Expected__
I expected to be redirected to the WooCommerce Home Screen, and to see the setup checklist ( which does have a specific task for WCPay when installed )

![image](https://user-images.githubusercontent.com/22080/88726401-832a5f80-d0e2-11ea-9400-f61b66ee59fe.png)

cc @allendav @pmcpinto

**Comment by allendav** [comment]
@LevinMedia  @thenbrent  - what would you like to see happen here? We can prioritize this for the next sprint.

**Comment by timmyc** [comment]
I mentioned this in Slack too, but we had a similar _bug_ with MailChimp for WooCommerce which was causing a redirect in the same spot. It makes for kind of an abrupt UX, and also side-steps the intent of the Setup Checklist on the home screen.

Here is the solution that MailChimp implemented: https://github.com/mailchimp/mc-woocommerce/blob/e8c539390b40fc028660e2829f1c3ae2d684bd41/includes/class-mailchimp-woocommerce-options.php#L37-L45

Essentially they are looking to see if the plugin was installed during the OBW flow, and if so, don't do the redirect. This still allows them to redirect for users that install manually via the .org repo, but just not when the install is sourced from the OBW.

**Comment by thenbrent** [comment]
> they are looking to see if the plugin was installed during the OBW flow, and if so, don't do the redirect.

That sounds like a good approach to fix this issue.

@LevinMedia should we direct the merchant to start/complete WC Pay onboarding in some other way if they've already installed the plugin at this stage?

The Payments step will still direct the merchant to WC Pay onboarding, but they'll need to choose it again later, they just won't have to install the plugin. The new _Payments_ menu will also be added to direct them there, but should we do more?

**Comment by thenbrent** [comment]
> We can prioritize this for the next sprint.

@allendav as much as I hate to add to the already loaded Sprint 16, given this is hijacking the entire WC OBW, I think we need to add it to the current sprint so it's released alongside the August 18 W 4.4. release. I'll look for an Issue we an cut in lieu of adding this one.

**Comment by thenbrent** [comment]
I've requested it be added to Sprint 16 in paJDYF-Mh-p2#comment-3151
