### ISSUE TITLE
Refunds: revisit events handling (externally-sourced refunds are not changing order state not rtacked in order notes)

### ISSUE THREAD

**Issue by kalessil** [Automattic/woocommerce-payments#8085]
### Description

In earlier iterations of WooPayments, we partially implemented related hooks handling (#426) but didn't look into the bigger picture.

That surfaced in the following conversations:
- paJDYF-bVn-p2
- https://github.com/Automattic/woocommerce-payments-server/issues/1865

### Acceptance criteria

- Both in-store and externally initiated refunds (incl. fees refunds) are reflected in order status and order notes.

### Dev-notes

- Please reference to https://github.com/Automattic/woocommerce-payments-server/issues/1865
- Worth case scenario: order refunded from store, transaction fees refunded externally - both actions expected to appear in order notes.

**Comment by zmaglica** [comment]
This issue impacts Refunds, so assigning to Pulsar (based on team responsibilities Pc2DNy-3z-p2) @kalessil . Assigning as part of Gamma Triage process PcreKM-yM-p2.

**Comment by KarlisJ** [comment]
I'd like to clarify if I've understood correctly. 

Regular refund:
- no application fee is refunded
- Merchant doesn't get anything refunded
- customer gets back everything he paid
- merchant loses the application fee amount
- WCpay gains application fee amount

Refund with application fee; everything the same, except:
- Merchant get's back his fee and doesn't lose any money overall
- Wcpay losses money as Stripe still charges us

Correct?

**Comment by kalessil** [comment]
@KarlisJ: I'm not sure why we need to dive into the big picture here (but we are okay to ask for details in the team channel).

There are events that the WooPayment client is not processing - examples are mentioned in the description.
What we need here is:
- check which events we need to process (with awareness of disputes)
- implement writing order notes and updating order status and refunds/fee-related metadata

The use-case is Dashboard-initiated full/partial refund, fee-refund: the details you are referencing are part of the events data we'll receive.

**Comment by KarlisJ** [comment]
https://github.com/Automattic/woocommerce-payments-server/issues/1865 should not have been closed in favor of this issue as it requires changes in the server, whereas this issue is client-only changes.

**Comment by mgascam** [comment]
Just adding a couple of notes as I dig into the issue.

The server [forwards](https://github.dev/Automattic/woocommerce-payments-server/blob/5243eb1d62e7461440d917915fe02df5bc3dd3d0/server/wp-content/rest-api-plugins/endpoints/wcpay/event-handler/class-charge-event-handler.php#L273) the `charge.refunded` event from Stripe to the client, once it is processed.

The `charge.refunded` event is not currently handled, [only 'charge.refund.updated'](https://vscode.dev/github/Automattic/woocommerce-payments/blob/update/8085-refunds-revisit-events-handling-externally-sourced-refunds-are-not-changing-order-state-not-rtacked-in-order-notes/includes/class-wc-payments-webhook-processing-service.php#L134). 

I'll look into implementing the actions to handle this event, namely update order status and order notes.
