### ISSUE TITLE
Move off deprecated formatCurrency function to new formatAmount

### ISSUE THREAD

**Issue by jrodger** [Automattic/woocommerce-payments#809]
The `formatCurrency` function in the WooCommerce Admin currency module has been deprecated ([issue](https://github.com/woocommerce/woocommerce-admin/issues/4860) and [PR](https://github.com/woocommerce/woocommerce-admin/pull/4891/files)). We should figure out a way of moving onto the new function `formatAmount`.

Is it sufficient to wait until WooCommerce 4.3 falls outside out support policy and then switch over at that point, bumping the minimum version of WooCommerce?

**Comment by dechov** [comment]
In the interim, we could use `formatAmount` if it exists, and fall back to `formatCurrency` otherwise – would that work?

Might be able to encapsulate that in a helper util so it can be managed in one place.

**Comment by vbelolapotkov** [comment]
Raising this to high as WC 5.0 is already in beta and deprecation warning references 5.0 as last version supporting `formatCurrency`.

Probably will be able address it as part of solution for #1054
