### ISSUE TITLE
WooPayments header collides with Woo Express survey banner.

### ISSUE THREAD

**Issue by zmaglica** [Automattic/woocommerce-payments#8093]
### Describe the bug
When a site is hosted on Woo Express, store owners typically see the Woo Express survey header at the top of the page. However, an issue arises when a user clicks an action that redirects to the WooPayments setup wizard. In this scenario, the WooPayments header appears, leading to a collision where the Woo Express Survey header is obscured by the WooPayments header.

### To Reproduce

1. Start Woo Express trial
2. Make sure that you don't finish Woo Express survey. It should be on the top of the page.
3. Once the initial setup is finished, click on the action item to start with setting up WooPayments
4. On the wizard page you will notice Woo Express survey header behind WooPayments header (check screenshot below)

### Actual behavior
Woo Express survey appearing behind the Woo Payments header

### Screenshots
![image](https://github.com/Automattic/woocommerce-payments/assets/15913573/e3b518e9-ee06-4b63-bfd0-c37603e648c5)

### Expected behavior
Woo Express survey and Woo Payments header should not collide.

### Desktop (please complete the following information):

* OS: [e.g. iOS]
* Browser [e.g. chrome, safari]
* Version [e.g. 22]

### Smartphone (please complete the following information):
N/A

### Additional context
More info can be found here: peapX7-45b-p2

**Comment by vladolaru** [comment]
IMHO, this fix should be on the Woo Express side as they introduce that banner and control its logic.

As long as WooPayments provides the context data points to inform the banner's display logic (in this case, I think it is the `path` GET param), we can't/shouldn't worry about hiding something not under our control.

**Comment by PanosSynetos** [comment]
These are JetPack's JITM (just in time messages). It's not only Woo Express, any Jetpack enabled site is potentially affected. 

Should we transfer the issue, and edit it to reflect that it's JITM related?

**Comment by vladolaru** [comment]
Oh! That changes the game, @PanosSynetos, and makes it something that we should at least try to see if we can get under our control.

**Comment by zmaglica** [comment]
This issue impacts Onboarding, so assigning to Moltres (based on team responsibilities Pc2DNy-3z-p2) @daquinons .
Assigning as part of Gamma Triage process PcreKM-yM-p2.
