### ISSUE TITLE
Shipping is removed if quanity increased after Payment Request has been initialized

### ISSUE THREAD

**Issue by mdmoore** [Automattic/woocommerce-payments#8097]
### Describe the bug

On simple products, when clicking the Google Pay button the first time, shipping costs are added and appear in the itemized costs inside the popup. When closing the popup and increasing the quantity, then click the Google Pay button again, shipping isn't re-added and doesn't appear in the list. 

### To Reproduce

1. Enabled Payment Requests
2. Add a shipping method
3. Navigate to a product and attempt to checkout via Google Pay, confirming that shipping appears in the order details inside the popup
4. Close the popup
5. Increase the product quantity
6. Click the Google Pay button once more and notice that shipping no longer appears in the order details

### Screenshots

First time, with shipping

![image](https://github.com/Automattic/woocommerce-payments/assets/3473953/dbff2ecc-cd90-4c10-945e-2b39a8ede9a9)

Next, without shipping

![image](https://github.com/Automattic/woocommerce-payments/assets/3473953/8e1b77bf-9bad-4495-9d43-9317cf7b76cc)

### Expected behavior

Shipping should be recalculated and added when increasing product quantity after opening and closing the Google Pay popup.

### Additional context

The Payment Request API emits a `onshippingaddresschange` event that is fired when the shipping address changes inside the popup. The event is emitted on initialization as well but no when closing the popup and changing product quantity, since the Google Pay shipping address has not changed. Variable products get around this by re-initializing the Payment Request which is likely what needs to happen here.

**Comment by zmaglica** [comment]
I noticed that there is an active development on this issue. For ticket triage, I am moving this issue to team Heisenberg @FangedParakeet .
