### ISSUE TITLE
Change plugin's WPORG title for better plugin search rankings

### ISSUE THREAD

**Issue by vladolaru** [Automattic/woocommerce-payments#8099]
### Description

As we stand right now (v7.1), if one searches for `woocommerce payments` on WPORG's [plugin search](https://wordpress.org/plugins/search/woocommerce+payments/), WooPayments is near the bottom of the first page or on the second page, depending on the day you search. Definitely not the top result, as it should be.

We do know that the plugin title weighs disproportionately in the search (both the proximity of terms and its length - the shorter the better as each individual term gets more weight).

From @dlcallaway:

"Given that title length is factored in, I think we should change it to "WooPayments: WooCommerce Integrated Payments" for now. It's shorter than my original proposal and also gets "WooCommerce" closer to the start (which, at least on Google, is a factor)."

After https://github.com/Automattic/woocommerce-payments/issues/8099#issuecomment-1921378075 **we will change it** to "WooPayments: Integrated WooCommerce Payments"

### Additional context
paJDYF-c6x-p2

**Comment by vladolaru** [comment]
@dlcallaway What do you think about "WooPayments: Native WooCommerce Payments"? It has "WooCommerce" and "Payments" grouped. But I don't know if "native" is appropriate for our audience.

**Comment by dlcallaway** [comment]
@vladolaru I think "WooPayments: Integrated WooCommerce Payments" works just as well and "integrated" is something we use pretty frequently. And it's only four more characters.
