### ISSUE TITLE
Opt-in to WC Tracker when onboarding

### ISSUE THREAD

**Issue by thenbrent** [Automattic/woocommerce-payments#810]
When a merchant agrees to [our ToS](https://wordpress.com/tos/) by clicking _Set up_ to start the onboarding process, we should opt the site into WC Tracker. This data helps improve product metrics, like churn, as well as risk mitigation.

The data collected should be covered by that ToS already, as this is done by WC Services already. We will need to confirm this with legal and also review the [Usage Tracking doc](https://woocommerce.com/usage-tracking/) to ensure we are transparent about all usage tracking.

**Comment by allendav** [comment]
Why shouldn't this be in WooCommerce core?

**Comment by thenbrent** [comment]
@allendav the triggering event can be unknown to WC core because it is introduced by WC Pay. Specifically, WC core doesn't, and probably shouldn't, have to know anything about the _Set up_ button on this screen: https://d.pr/i/TIMUcf (, including that ToS are being agreed to when clicking it). Core only knows about the button on the Task List.

That said, given this same behavior is present in WC Services, there might be a more generalised way to this upstream into core. The

**Comment by vbelolapotkov** [comment]
Fixed by https://github.com/woocommerce/woocommerce-admin/pull/5248
