### ISSUE TITLE
Bump qit-cli dependency to 0.4.0.

### ISSUE THREAD

**Issue by allie500** [Automattic/woocommerce-payments#8113]
### Description 

There have been some recent updates to the Quality Insights Tool and related infrastructure as announced in this recent P2:
pcShBQ-1qu-p2

As a result, the current version of `qit-cli` on WooPayments no longer works correctly. 

```
Request failed... Retrying.
Request failed... Retrying.

[Synchronization with the Quality Insights Toolkit servers failed. Only limited commands are available]
There are no commands defined in the "partner" namespace.  
```

I was able to successfully run the QIT security report when I updated `qit-cli` to version `0.4.0` locally.

### Acceptance criteria

- `npm run test:qit` successfully completes.

**Comment by zmaglica** [comment]
Moving this to Other Teams queue @allie500 since I noticed that you assigned this issue to yourself. Please let me know if you think that some other team needs to handle this issue.

**Comment by allie500** [comment]
> Moving this to Other Teams queue @allie500 since I noticed that you assigned this issue to yourself. Please let me know if you think that some other team needs to handle this issue.

Hi @zmaglica! I just took care of it b/c I was working on running the QIT scan as part of the release lead duties and ran into errors and saw that it needed to be updated. I have the PR open and ready for review. I've requested review from Harmony team since they handle dependencies management.
