### ISSUE TITLE
Adjust payment method display on order received page for Stripe Link with setup intents

### ISSUE THREAD

**Issue by timur27** [Automattic/woocommerce-payments#8122]
### Describe the issue
The following explanation assumes that the payment method used is a payment method registered with a Stripe Link account.

When updating an order with the payment method, we take payment method details from payment intent or setup intent. In case of payment intents, the `payment_method_details` parameter provides the expected payment method, which is `link` or `card` depending on which is used. Our system receives already prepared data from Stripe and forwards it to order details.

For setup intents, there's no `payment_method_details` object in the response from Stripe, and here we're trying to get the data from the `payment_method_options` Stripe object. It returns card only, and our system doesn't attempt to understand further if it was a `card` or `link` payment and forwards a `card` into the order details.

### Acceptance criteria
1. The most efficient way of identifying the payment method used for setup intents is found and implemented
2. The area covered by implementation should contain
    * Link payments with non-3DS cards
    * Link payments with 3DS cards
    * shortcode & blocks checkout
3. In case the logic for getting the payment method type is not a one-liner, the logic for normal cards and 3DS cards is merged into one place and re-used

### Additional context
The implementation for setting the payment method for order is located in
* `WC_Payment_Gateway_WCPay::process_payment_for_order` for non-3DS cards
* `WC_Payment_Gateway_WCPay::update_order_status` for 3DS payments

**Comment by zmaglica** [comment]
This issue impacts Stripe Link and other payment methods, so assigning to Heisenberg (based on team responsibilities Pc2DNy-3z-p2) @FangedParakeet .
Assigning as part of Gamma Triage process PcreKM-yM-p2.
