### ISSUE TITLE
SPIKE: Explore moving the BNPL payments method messaging element from below the payments wrapper to below the product price

### ISSUE THREAD

**Issue by pierorocca** [Automattic/woocommerce-payments#8128]
### Description
BNPL is an important payment method that allows shoppers to spread payments over a longer time period. As a new category of online payment, consumer adoption and awareness continues to be in a growth phase. Thus, how this category of payment method is presented to shoppers is important to adoption and perception.

In the initial deployment of BNPL, the Stripe [payments method messaging component
](https://stripe.com/docs/payments/payment-method-messaging) was placed below the payment request buttons on the Product Page. Additionally, if another gateway such as PayPal is activated and is ordered below WooPayments, it pushes the BNPL messaging below that gateway's buttons.

Combined there are several issues with this placement:
1. The "4 payments of $20.00" message is visually far removed from the product price, impacting discoverability and lessens the impact of the perceived price reduction.
2. In single gateway stores, the close proximity to the PRB buttons can create an association that the financing option is offered by the express checkout provider. Additionally, we have found that it is difficult to inject elements near the PRB wrapper and have it styled properly without merchant intervention.
3. In multi-gateway stores, the BNPL messaging can be pushed far down, completely disassociated with the important details on the page.
4. Product details such as the SKU, category tags, etc. get pushed down even further to the point they are no longer visually associated with the product details, and impacting the theme's design goals.

**Shortcode Examples:**
![image](https://github.com/Automattic/woocommerce-payments/assets/109928953/68890d43-5cb4-4276-a56a-b7086c712b3c)

![image](https://github.com/Automattic/woocommerce-payments/assets/109928953/d9366462-fdfc-4442-a5f5-381312fa90d5)

**Blocks:**
Blocks presents with a better placement, though I'm unsure if this placement was intentional. The spacing between the price and the messaging is better if reduced.
![image](https://github.com/Automattic/woocommerce-payments/assets/109928953/fd7ba9c3-f170-4121-8757-d3f400c72dcf)

**Inspirational Examples:**
Looking at how retailers position BNPL options, there's a clear pattern. The BNPL messaging is in close proximity to the price either on the same line or on the next line.

![image](https://github.com/Automattic/woocommerce-payments/assets/109928953/5af8437d-4901-4c76-ae3a-ff89ffc91e94)

![image](https://github.com/Automattic/woocommerce-payments/assets/109928953/48396999-8c34-4680-8ed6-1548c5082516)

![image](https://github.com/Automattic/woocommerce-payments/assets/109928953/ea1369a5-b35d-4895-9a2c-b123c09732bb)

![image](https://github.com/Automattic/woocommerce-payments/assets/109928953/924ffc51-25f7-4677-93a4-10d4fedb9a74)

### Acceptance criteria

- The existing BNPL payments method messaging component is placed immediately below the price

Open questions: 

1. Can this be done reliably across a selection of Shortcode templates? Is there a filter located after price on most themes that we can utilize consistently and without impact other elements such as the quantity picker, add to cart button and the payments button wrapper?

2.In the current Blocks implementation, where was the messaging intended to be placed vs. where it's rendering?

cc @FangedParakeet @csmcneill @elizaan36

**Comment by pierorocca** [comment]
Love what Purple is doing in the cart to increase discoverability and usage.

![image](https://github.com/Automattic/woocommerce-payments/assets/109928953/c576ba67-de94-4663-b6d1-798c1c075b51)

**Comment by pierorocca** [comment]
Thanks @brettshumaker!

**Comment by zmaglica** [comment]
This issue impacts BNPL, so assigning to Heisenberg (based on team responsibilities Pc2DNy-3z-p2) @FangedParakeet .
Assigning as part of Gamma Triage process PcreKM-yM-p2.

**Comment by pierorocca** [comment]
FYI as long as the right component is labeled, the issue will automatically get added to Heisenberg's project board, triaged, prioritized, and then picked up by an engineer. Is the assigning process still needed @zmaglica ?

**Comment by zmaglica** [comment]
It will be in the WooPayment Backlog and as a Gamma porter I have to triage it, assign it to the right team and ping the right people to avoid losing context.

**Comment by brettshumaker** [comment]
@pierorocca 

> Can this be done reliably across a selection of Shortcode templates? Is there a filter located after price on most themes that we can utilize consistently and without impacting other elements such as the quantity picker, add to cart button and the payments button wrapper?

Yes, we should be able to utilize the `woocommerce_single_product_summary` hook with a priority of `10`. The priority doesn’t matter so much on block-based single product pages (reason noted below), but will ensure that it gets placed in the correct spot on non-block themes as well as when other plugins (or the theme) are also trying to place information in that same location based on the core WooCommerce hook priorities.

The trickiest thing will be getting the base styling correct. The core Woo product price block (and non-block version) will likely have a custom margin set for the top and bottom. We would likely have to try and get the bottom margin from the price element, remove or adjust it, and then apply it to our element so the theme’s spacing remains consistent. That method may not be foolproof as there are multiple html elements inside the `.price` element that a margin could be applied to by the theme.

<img width="400" alt="before-margin-adjustment" src="https://github.com/Automattic/woocommerce-payments/assets/1558827/d3428626-f0b7-47d7-960d-9c4ff4914e1e">

<img width="400" alt="after-margin-adjustment" src="https://github.com/Automattic/woocommerce-payments/assets/1558827/deddba92-7aeb-45b6-a227-2ab8254c624d">

___

> In the current Blocks implementation, where was the messaging intended to be placed vs. where it's rendering?

I think this is accidental. I’m not 100% confident on this, but it looks like the blocks single product template essentially removes all of the core filters that add the various bits of product info to the product summary section. This means that whenever we hook into that section to add the BNPL text, nothing else is there and we get placed just *above* the post excerpt block in the product template. That just so happens to be directly underneath the product price block.

**Comment by FangedParakeet** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Heisenberg-63586f2ec60359001310fa6a/issues/Automattic/woocommerce-payments/8128?planning-poker) with Zenhub @brettshumaker

**Comment by pierorocca** [comment]
Thanks for the deep detail @brettshumaker. Much appreciated.

Noting here that on a few other sites, I've seen 5 star product reviews located below the PRBs which is yet another potential for a collision with the existing implementation.

**Comment by pierorocca** [comment]
Nice work.
