### ISSUE TITLE
Allow Sandbox accounts to be deleted at any moment of the account lifecycle

### ISSUE THREAD

**Issue by Brianmitchtay** [Automattic/woocommerce-payments#8132]
### Description

in #7914 we added the ability for self service account deletion of partially onboarded accounts. This is awesome, full stop.

We can extend this functionality to another use case where users would see great benefit by enabling self service account deletions for all accounts created in sandbox mode given that they will never have live transactions, and users that are testing the platform may want to check many aspects of the account creation process, or creating accounts in various jurisdictions.

Presently, even for accounts created in test mode, if the user wants to clear the fully onboarded account connected to their site, they must contact support. 

### Acceptance criteria

* Accounts created in test mode are able to be self service deleted "reset" from a UI option exposed to the end user.
* This functionality would be limited to testing/sandbox/dev-mode accounts.

### Designs

We could very easily re-use the existing design work from the already implemented feature

### Testing instructions

1. Create a new site and add WooPayments
2. Onboard a new account following the setup directions for sandbox accounts
3. Return to the Payments > Overview page. You should be able to see the Account Tools section and reset account option, including warning modal, customized for testing accounts
4. Account is reset so merchant can re-onboard with a live or sandbox account.

### Additional context

This request was born from 7690740-zd-a8c where a new-to-woo site builder was surprised this wasn't an option already.

**Comment by zmaglica** [comment]
This issue impacts Onboarding, so assigning to Molters (based on team responsibilities Pc2DNy-3z-p2) @daquinons 
Assigning as part of Gamma Triage process PcreKM-yM-p2.

**Comment by daquinons** [comment]
Hi there @Brianmitchtay! Thank you so much for the proposal :) 

Just want to share with you that this is already possible. When. you create a "sandbox account", there is a banner appearing in the "Payments" screen, and also in the settings, that urge you to "set up a live account". 
<img width="1502" alt="Screenshot 2024-02-06 at 14 03 30" src="https://github.com/Automattic/woocommerce-payments/assets/2612426/fe4ce28c-a3f5-4351-b556-a754b7482884">
<img width="1502" alt="Screenshot 2024-02-06 at 14 03 43" src="https://github.com/Automattic/woocommerce-payments/assets/2612426/89df4c44-a984-4d49-b4bb-b4114f9cff6f">


When that "Set up payments" button is pressed, a confirmation modal appears and if confirmed, the sandbox account is deleted and you are redirected back to the first screen of the onboarding (so you can either create a live account or a new sandbox account, as you prefer).


It's true that what I'm referring to is heavily directed to final users and not developers, but the final result is the same here. We've been actively tried to clean up the experience for non-developers, as they were getting confused in some situations (see for example https://github.com/automattic/woocommerce-payments/issues/7974 )

Do you think that after this explanation is there still a need for a new way of accomplishing this?

Again, thank you so much!

**Comment by Brianmitchtay** [comment]
Thanks for the explanation! @daquinons 

I see now that what the merchant wanted to do is possible, but understand why they and I didn’t find it. I think my enhancement request still stands to improve the product by creating a clearer user flow that’s more intuitive for deleting test accounts.

That said, given that we already have a mechanism for this in place, we might be able to address the need with some simple copy changes instead of adding new UI components. Or we could add a "Reset test Account" button/link separately in the same areas with a different modal and text, but have it go to the exact same place.

I'm open to other ideas, but do think that the current flows being very directed at users wanting to set up live accounts is a bit confusing.

**Comment by daquinons** [comment]
New requirements for the issue:
- We need to display the account tool added here https://github.com/Automattic/woocommerce-payments/pull/7914 to sandbox accounts as well
- We need to modify the copy in both the account tool and the confirmation modal: it needs to be explicit about deleting the sandbox mode account (as you can see in the previous shared PR, currently it's very oriented to the specific use case of live accounts who have not finished onboarding yet)
- Sandbox accounts can be deleted at any state of the account lifecycle, with our without processed test transactions
