### ISSUE TITLE
Sandbox mode: cursor for debug logging hover state indicates debug logging can be disabled

### ISSUE THREAD

**Issue by csmcneill** [Automattic/woocommerce-payments#8138]
### Describe the bug

When a merchant tries to disable the `Credit / Debit card` payment method, the mouse cursor changes to one with a [no symbol](https://en.wikipedia.org/wiki/No_symbol), which indicates that they are unable to modify this setting.

When WooPayments is in sandbox mode, there is an additional item that cannot be disabled: debug logging. However, the cursor does not change to reflect that this is an option that cannot be disabled.

### To Reproduce

1. Onboard in sandbox mode.
2. Navigate to Payments > Settings.
3. Hover over the checkbox for `Credit / Debit card (Required)`.
4. Note the cursor used.
5. Scroll down and hover over the checkbox for `Sandbox mode is active so logging is on by default.`.
6. Note that the cursor is different than step 4.
7. Hover over another option that can be enabled/disabled (e.g., `Enable Multi-Currency`)
8. Note that the cursor is the same as when hovering over `Sandbox mode is active so logging is on by default.`.

### Actual behavior

When in sandbox mode, the cursor does not change when hovering over the debug logging option, which is inconsistent with other options that are enabled but cannot be disabled.

### Screenshots

![CleanShot 2024-02-05 at 17 58 33](https://github.com/Automattic/woocommerce-payments/assets/82999806/c84d915b-efae-4c36-8e2e-0ebf68b51058)

### Expected behavior

Hovering over the debug logging option while in sandbox mode displays a mouse cursor that mirrors other options that cannot be enabled.

**Comment by zmaglica** [comment]
This issue impacts <team responsibility WooPayments Settings page, so assigning to Moltres (based on team responsibilities Pc2DNy-3z-p2) @daquinons .
Assigning as part of Gamma Triage process PcreKM-yM-p2.
