### ISSUE TITLE
With Woo Subscriptions, setting a payment method as the default does not update any pending payment orders awaiting retry

### ISSUE THREAD

**Issue by billrobbins** [Automattic/woocommerce-payments#8139]
### Describe the bug
Say a subscriber has a credit card that is no longer valid for whatever reason and payment fails during a renewal attempt.  They go to the payment methods section of the account page, add a new credit card, and set it to be the default.  When prompted, they select to update existing subscriptions to use this card.  However, when the retry is attempted again, payment will fail because the card hasn't been updated on the order.  Only the subscription is updated.

### To Reproduce
1.  Purchase a subscription product using WooPayments.
2. After checking out, go to the payment methods endpoint on the account page.  Add a new payment method using the "Decline after attaching" test card, `4000000000000341`.
3. Edit the subscription inside the admin.  Use the actions menu to process a renewal.  There should be a failed payment note on the subscription.
4. Back on the payment methods endpoint, add a valid test card number such as `5555555555554444`.
5. Once it has been saved, set it to be the default.  Then once prompted, select the option to update existing subscriptions to use the new card.
6. Copy the renewal order's ID and go to WooCommerce > Status > Scheduled Actions and search for the ID.  Hover over the pending `woocommerce_scheduled_subscription_payment_retry` action and click run.  

That should trigger the payment retry which will fail since the payment method for this order, wasn't updated.

### Screenshots
Here is a failed renewal order after updating the subscription's payment method via the add payment method screen.  We can see the order meta's `_payment_method_id` is still using the old method while the customer only has one method set and it has a different token.

<img width="1928" alt="Markup 2024-02-05 at 14 45 38" src="https://github.com/Automattic/woocommerce-payments/assets/1138631/cebafadf-8cfa-4253-a4fd-a2a4d54d03ea">

### Expected behavior
I expect that setting the option to update existing subscriptions will update the pending payment renewal that's in the retry cycle.

### Desktop (please complete the following information):

* OS: MacOs
* Browser: Chrome 
* Version: 121.0.6167.85 

### Additional context
https://github.com/Automattic/multiwoo/issues/1112

**Comment by mattallan** [comment]
Hey @billrobbins thanks for reporting this issue.

I'm having trouble reproducing this one! Here's a screencast of how I'm testing this, do you mind confirming that I'm going through the proper steps to replicate this? Sorry for the long video!

https://github.com/Automattic/woocommerce-payments/assets/2275145/cc25b54f-82fe-41ab-9e4c-973456cf2f60

---

During the Retry Failed Payment process, Woo Subscriptions calls `wcs_copy_payment_method_to_order()` to make sure the latest renewal order has the updated payment token data from the subscription before it retries the failed payment. From sifting through the WooPayments code, it looks like it's hooking onto all the proper subscription hooks to make sure it updates the payment method ID and tokens, but based on your issue description it sounds like that might not be happening in all cases 🤔

**Comment by billrobbins** [comment]
Thanks for checking @mattallan.  I also can't reproduce this today outside of TumblrPay.  Yesterday I was attempting to confirm this on a regular WooPayments site and I believe I forgot to actually click the "Set as default" button.  Sorry for the wild goose chase.  We do have this issue on TumblrPay but I believe we have a different root cause there.  I'll close this out now.
