### ISSUE TITLE
Update how the fraud prevention token is added to the checkout page

### ISSUE THREAD

**Issue by eduardoumpierre** [Automattic/woocommerce-payments#8141]
### Description

There are occurrences where the Fraud Prevention Token is not added to the checkout page due to restrictions in the `the_content` filter, making the checkout form fail.

p1706826656327619-slack-C03EE4CPPK5 was one of those occurrences, which took a considerable time to understand and debug the real issue.

Suggestions to fix this issue:
- p1707221154160759/1706826656.327619-slack-C03EE4CPPK5 suggests that `wp_footer` would be a better filter to hook into instead of `the_content`.
- p1707221337069669/1706826656.327619-slack-C03EE4CPPK5 suggests that the token can be added as a global JS variable.

### How to reproduce it

* Enable `fraud_prevention_service` on your site
* Go to your checkout page, inspect the form, and search for `wcpay-fraud-prevention-token`
  * It should be present on the page
* Change your theme to any that has Site Editor support – such as "Twenty Twenty Four"
* Go to **Appearance > Editor**
* On the Site Editor, go to **Templates > Page: Checkout > Customize**
* On the List View, delete all the blocks that aren't the header or footer
* Add a new checkout block between them
* Save the changes
* Go back to your checkout page, inspect the form, and search for `wcpay-fraud-prevention-token`
  * It should **not** be present on the page

### Acceptance criteria

* The checkout form works even to pages without "the content" block

### Additional context

- Related Slack thread (p1706826656327619-slack-C03EE4CPPK5)

**Comment by zmaglica** [comment]
This issue impacts Risk & Fraud, so assigning to Sigma (based on team responsibilities Pc2DNy-3z-p2) @dwainm .
Assigning as part of Gamma Triage process PcreKM-yM-p2.
