### ISSUE TITLE
Add BNPL Payment Method Messaging below the Cart summary total

### ISSUE THREAD

**Issue by pierorocca** [Automattic/woocommerce-payments#8144]
### Description
BNPL is an important payment method that allows shoppers to spread payments over a longer time period. As a new category of online payment, consumer adoption and awareness continues to be in a growth phase. Thus, how this category of payment method is presented to shoppers is important to adoption and perception.

In the initial implementation of BNPL, [payment method messaging](https://stripe.com/docs/payments/payment-method-messaging) was added to the product page. This messaging e.g. As low as $14/month or 0% APR is critical to driving shopper awareness, usage, and conversion.

The problem is that not all shoppers will click into the product page to see that messaging. Even if they do see the messaging, it may be forgotten by the time the shopper completes filling up their basket/cart. 

WooPayments lacks that messaging at other important touch points such as the cart and checkout pages.

This feature adds the Stripe payment method messaging element below the cart summary total.

### Acceptance criteria
1. The payment method messaging copy is displayed below the cart summary total per the design.
2. The copy is based on providing the appropriate `paymentMethodTypes` values that correspond to those enabled on the store.
3. The messaging language matches the browser locale language.
4. The styling closely matches the site theme
 
**Out of scope:** Mini-cart

**Unknowns**: 

1. What does Stripe return if the messaging/values don't match between brands? Are multiples returned? https://stripe.com/docs/payments/payment-method-messaging#supported-plans

2. Styling - does the Appearance API provide enough customizability to be able to closely match the site theme?

### Designs
Design needed - @nikkivias I'll connect with you directly with a few options for consideration

### Testing instructions
1. Enable Affirm on your test store
2. Shop and add a simple $50+ product to the cart
3. View the cart
5. Observe that the payment method messaging displays below the cart summary total per the design
6. Repeat for Afterpay/Clearpay and Klarna
7. Repeat testing on mobile
8. Enable both Affirm and Afterpay and repeat 2-4.
9. Enable Affirm, Afterpay, and Klarna and repeat 2-4.
10. Change the browser locale to a supported non en-US language and observe that the copy language matches the new locale. 

### Additional context
Inspirational examples

![image](https://github.com/Automattic/woocommerce-payments/assets/109928953/0f19ab04-fe74-4f6a-94ef-5a963858b276)

![image](https://github.com/Automattic/woocommerce-payments/assets/109928953/c1cb9476-90d3-40b9-b491-b678e2cb579c)

![image](https://github.com/Automattic/woocommerce-payments/assets/109928953/69f67dae-6bb3-43c0-893f-da91f272903a)

![image](https://github.com/Automattic/woocommerce-payments/assets/109928953/b7b6230f-892c-416e-baf0-7390612768d6)

cc @FangedParakeet

**Comment by mdmoore** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Heisenberg-63586f2ec60359001310fa6a/issues/Automattic/woocommerce-payments/8144?planning-poker) with Zenhub @FangedParakeet

**Comment by pierorocca** [comment]
Looking at the example above and how our cart is laid out, the Pandora example seems closest to what we have and looks excellent...in case development outpaces design capacity.

**Comment by mdmoore** [comment]
@pierorocca @nikkivias Apologies for closing this without posting some demos. Here are a few:

### Shortcode Cart
![Screen Capture on 2024-03-29 at 12-25-26](https://github.com/Automattic/woocommerce-payments/assets/3473953/176e5e8c-43be-461a-95d0-1db396888bfd)

### Shortcode Cart Appearance API
![image](https://github.com/Automattic/woocommerce-payments/assets/3473953/3701917d-9bab-481d-ada4-9fed3287dc1e)

### Cart Block
![Screen Capture on 2024-03-29 at 12-41-24](https://github.com/Automattic/woocommerce-payments/assets/3473953/237bd345-d0f2-40bf-924e-7e2d6f943476)

## Cart Block Appearance API
![image](https://github.com/Automattic/woocommerce-payments/assets/3473953/bab112be-c3bf-4789-9823-abe26c9e15f6)

This has been merged to `develop`, but we have a fair amount of time before the 7.5.0 RC freeze on April 14 if any changes are needed.

**Comment by pierorocca** [comment]
Looks good @mdmoore. I'm confused about the 1st gif. It looks like the messaging only appears after scrolling and shifts the buttons down?

**Comment by pierorocca** [comment]
Or is that a recording artifact?

**Comment by mdmoore** [comment]
>I'm confused about the 1st gif. It looks like the messaging only appears after scrolling and shifts the buttons down?

The messaging appears on page load, but when cart totals are updated, the cart totals section HTML is stripped and replaced with new HTML from a request to the backend. So similar to the PRB, the messaging element is remounted with the new data. It's not a limitation of the PMME, but more an unfortunate side effect affecting elements living in that section. 

The remounting isn't tied to any scroll event. The timing in the gif just happens to line up with my scrolling back down a bit after WC scrolls to the cart update notification. Also worth noting that these gifs are created on local via Jurassic Tube which can be quite slow.

**Comment by pierorocca** [comment]
Gotcha thanks @mdmoore. In cases where the update is slow and beyond our control, would a skeleton loading component be warranted @mdmoore @nikkivias to prevent the shifting components and to mitigate any negative shopper perceptions?

**Comment by pierorocca** [comment]
I see a spinner loading component already in place so why does it resolve before the BNPL messaging is available to display?

**Comment by mdmoore** [comment]
>I see a spinner loading component already in place so why does it resolve before the BNPL messaging is available to display?

The spinner is from core and resolves when the cart update completes. It just happens to center perfectly on the he BNPL messaging element in that gif. The BNPL messaging element needs the new cart total from that resolved request to re-render. A skeleton component could be a viable option as a place holder while the element re-renders though we might end up with layered loading components.

**Comment by pierorocca** [comment]
> The spinner is from core and resolves when the cart update completes. It just happens to center perfectly on the he BNPL messaging element in that gif.

:) Makes sense. That creates a challenging scenario where core total has to update first, which has its own loading component and then is followed by a call to Stripe to update the BNPL amounts. 

I'm noticing that the core loading component is applied to the Buttons and the BNPL messaging? I had expected the cart summary to be independent of the buttons. Obviously we want to avoid a choppy UX and that seems like an impediment. Do we have a way to alter the core behavior?

Shopify here must be delaying the refresh because both the total and BNPL amounts change at the exact same time. The button is unaffected by the refresh.
https://github.com/Automattic/woocommerce-payments/assets/109928953/f520f6aa-6f45-4814-bf64-bb4758e64666

Pandora Jewelry uses a subtle blurring effect that begins when the qty change is triggered and resolves once the updated value is known. The blur effect occurred less frequently once I cycled through the quantities. Curious if there's some caching happening to prevent unneeded API calls. Also buttons are not impacted by the refresh.
https://github.com/Automattic/woocommerce-payments/assets/109928953/cbb01f59-9779-4456-8cf1-9ab95b01224c

**Comment by mdmoore** [comment]
>I'm noticing that the core loading component is applied to the Buttons and the BNPL messaging? I had expected the cart summary to be independent of the buttons. Obviously we want to avoid a choppy UX and that seems like an impediment. Do we have a way to alter the core behavior?

@pierorocca 

I expected the same regarding the buttons and it's related before/after hooks. It turns out that WC re-renders this entire container(`.cart_totals`) when the request resolves. So anything added here after the page has initially rendered, like the PMME, is removed.

<img width="533" alt="image" src="https://github.com/Automattic/woocommerce-payments/assets/3473953/278009c3-f43d-419a-ad39-a422a64d782b">


>Do we have a way to alter the core behavior?

At the extension level, we do not. Core doesn't offer any method to exclude elements from the cart totals refresh. Adding a hook to core that allows elements to be excluded would be a really nice to have.

But all is not lost yet. After some tinkering I've been able to reach a solution that allows the PMME to refresh without affecting the flow of the elements. Basically, reserving the PMME location, allowing it to re-render when it has the new cart totals:

### No Layout Shift
https://github.com/Automattic/woocommerce-payments/assets/3473953/618048c8-08df-4440-b357-f4a3d77ec17b

Let me know what you think. Since we're getting into this release cycle, it would good to understand if this is something we can go with and iterate on, or if this is a blocker for the feature.

**Comment by pierorocca** [comment]
Great improvement @mdmoore. Is the behavior the same on Blocks? The buttons and anything after the total should not be part of the total component so it would be great to give the feedback on our use case to the Core team.

The attached demo, the delay is because of the local environment? Is there a way to apply a skeleton loading component to the PMME at the point where it refreshes and disappears in the video?

**Comment by mdmoore** [comment]
>Is the behavior the same on Blocks?

It isn't. Much less friction there. The PMME remains on the page and just updates the amount.

### Cart Block PMME Update
https://github.com/Automattic/woocommerce-payments/assets/3473953/f04ff406-98eb-4475-9f4c-372f8f630d56

>The attached demo, the delay is because of the local environment? Is there a way to apply a skeleton loading component to the PMME at the point where it refreshes and disappears in the video?

Yes, the delay is mostly due to the local environment. A skeleton component is possible and the best solution within our limitations IMO. Here's a demo with a basic skeleton:

https://github.com/Automattic/woocommerce-payments/assets/3473953/c34fa9c9-20d6-4896-8821-32b46f184107

**Comment by pierorocca** [comment]
Beautiful on both counts @mdmoore. LGTM!

**Comment by pierorocca** [comment]
@mdmoore just noticed that with either Gift Card or Points and Rewards extensions enabled, the placement gets pushed down. Do we have any control in these scenarios?

![image](https://github.com/Automattic/woocommerce-payments/assets/109928953/7a18d81c-16c4-4f2c-8a4f-7548ccb48abe)

**Comment by pierorocca** [comment]
@brettshumaker I'm noticing that there's no longer a skeleton in production. Do you see the same?
