### ISSUE TITLE
Use WooPayments Server to determine next scheduled deposit date (vs. calculating manually)

### ISSUE THREAD

**Issue by haszari** [Automattic/woocommerce-payments#8146]
### Description
In `Payments > Overview`, we show an approximate date for the next scheduled payout:

<img width="838" alt="Screenshot 2024-02-07 at 2 32 43 PM" src="https://github.com/Automattic/woocommerce-payments/assets/4167300/37bdb76c-4353-4721-854f-b4cbaa319b9a">

Currently this is [calculated in the plugin](https://github.com/Automattic/woocommerce-payments/blob/15e611714c4b94a8772f8ba82dc20cd0b7c44be6/client/deposits/utils/index.ts#L57-L100), based on the deposit schedule. 

Ideally we would delegate this logic to WooPayments Server, as the authority. And the parallel logic in plugin should be removed.

### Additional context

We're looking at adding next expected deposit date to a `deposits/overview-all` API response:

- Automattic/woocommerce-payments-server#4435
- https://github.com/Automattic/woocommerce-payments/pull/8145

**Comment by zmaglica** [comment]
This issue impacts Deposits, so assigning to Helix (based on team responsibilities Pc2DNy-3z-p2) @haszari  .
Assigning as part of Gamma Triage process PcreKM-yM-p2.

**Comment by haszari** [comment]
Note the server issue is blocked on internal discussions of risk/benefit, so marking this as blocked until that discussion resolves.

**Comment by haszari** [comment]
Closing – we've decided that we shouldn't estimate the next deposit date as we can't guarantee accuracy and it's not in our control. See follow up issue to remove the estimate from the UI and provide merchant with info / guidance on when they can expect funds in their account.

- https://github.com/Automattic/woocommerce-payments/issues/8175

**Comment by haszari** [comment]
Setting estimate to 0 as this is closed / not planned.
