### ISSUE TITLE
Update deposits export to allow a high number of results 

### ISSUE THREAD

**Issue by dpaun1985** [Automattic/woocommerce-payments#8156]
### Description

Change the export approach to allow a high number of results similar to transactions : 8008-gh-Automattic/woocommerce-payments-server

**Comment by zmaglica** [comment]
This issue impacts Reporting, so assigning to Fusion (based on team responsibilities Pc2DNy-3z-p2) @anu-rock.
Assigning as part of Gamma Triage process PcreKM-yM-p2.

**Comment by anu-rock** [comment]
@dpaun1985 Could you please elaborate a bit for clarity and context? Also, the linked server issue points to a 404 page.

**Comment by haszari** [comment]
Potentially we can close this, if there's a specific need it will resurface via feedback and we can prioritise appropriately. Looks like a technical task / idea that is not a priority.

**Comment by haszari** [comment]
Closing, please open a new issue with merchant problem/impact if needed :)
