### ISSUE TITLE
Make Tracks cookie cache compatible

### ISSUE THREAD

**Issue by malithsen** [Automattic/woocommerce-payments#8162]
### Describe the bug

`tk_ai` is set by WooPay Tracks integration on page load [here](https://github.com/Automattic/woocommerce-payments/blob/develop/includes/class-wc-payments-checkout.php#L203) (#6904). Typically, the cookie is set via an Ajax requests or as a result of a hook. In this case, the cookie is set, and its value is immediately printed onto the page to make it available if/when a user navigates to WooPay. 
As pointed out in p6q8Tx-4j4-p2#comment-8955, setting the cookie in PHP during a page load bypasses the page cache in certain environments. One proposed solution is to set the cookie in frontend. We should review the cookie usage to make sure whether it needs to be set in the initial page load or whether it can be moved elsewhere.

### Additional context
p2: p6q8Tx-4j4-p2#comment-8955
Slack: p1707306910715269-slack-CGGCLBN58

**Comment by zmaglica** [comment]
This issue impacts WooPay, so assigning to Axiom (based on team responsibilities Pc2DNy-3z-p2) @LCmry .
Assigning as part of Gamma Triage process PcreKM-yM-p2.
