### ISSUE TITLE
Create E2E tests for card testing prevention mitigations

### ISSUE THREAD

**Issue by tpaksu** [Automattic/woocommerce-payments#8163]
### Description
We need some tests to ensure our card testing mitigation doesn't prevent legit customers don't get their payments blocked because of some error in the mitigation code. 

Activating of the meta possibly will be achieved via mocking the account data.

### Acceptance criteria

The code will test that when the preventions are enabled:

- Regular payments are still working as expected
- Saved card payments are still working as expected
- Payments with LPM's are still working as expected
- Payments with ApplePay/GooglePay is still working as expected
- Payments with WooPay is still working as expected
### Testing instructions

See [tests\e2e\README.md](https://github.com/Automattic/woocommerce-payments/blob/develop/tests/e2e/README.md) for running E2E tests on your local. Also GH E2E actions shall complete without errors.

### Dev notes
Something like this was required since the mitigations were implemented, but didn't have an issue defined. After developing https://github.com/Automattic/woocommerce-payments/issues/8141 and fixing paJDYF-c8j-p2 showed that it is needed.

**Comment by zmaglica** [comment]
I have noticed that you are working on this issue @tpaksu . I will move it to the Other Teams queue as a part of the Gamma triage process.
