### ISSUE TITLE
WCPay sending Stripe VAT Invoices email

### ISSUE THREAD

**Issue by rossanafmenezes** [Automattic/woocommerce-payments#8173]
### Describe the bug

ZD Ticket: 7709344-zd-a8c
Slack Convo: p1707500390243519-slack-C3NCP7ZJ6

### To Reproduce

N.A

### Actual behavior

The user in the Ticket above received a WooPayments email about a VAT invoice that is not ours. It's Stripe's.
If you check the UPDATE VAT INFO in their WCPAY dashboard, it's empty. 

### Screenshots

Please check the ticket added above

### Expected behavior

Users should not be getting emails from WCPay regarding Stripe VAT invoices.

**Comment by csmcneill** [comment]
Is this any different from #8054 by chance?

The merchant responded to a VAT invoice email that has a WooPayments logo...

![vat woopayments logo](https://github.com/Automattic/woocommerce-payments/assets/82999806/31d3deb0-3acb-4b34-a538-ed9fa11bba3e)

...but there is no indication that this email contains a Standard Stripe invoice that I can find.

**Comment by rossanafmenezes** [comment]
Hi @csmcneill 

I don't think the issues are the same. Regarding this one, the invoice is not in the email exactly. The user attached it to the email. But if you check the link provided in the email it takes you to the WCPay Payments Dashboard.

`(...)admin.php?page=wc-admin&path=%2Fpayments(...)`

**Comment by csmcneill** [comment]
@rossanafmenezes The links in that email should direct users to the **Payments > Documents** section of their dashboard...

![documents list](https://github.com/Automattic/woocommerce-payments/assets/82999806/ff2441ed-953f-40b2-a708-9be92fa27c64)

...or to download the invoice PDF directly:

![vat invoice download](https://github.com/Automattic/woocommerce-payments/assets/82999806/838a72ab-75fa-4239-a741-8ea4d593aae3)

However, this is dependent on which of the links they select. Regardless, having some aspect of `wp-admin.php` in the URL is expected.

What that link will _not_ do is direct merchants to download a PDF similar to the one attached to that ticket: 

![stripe vat invoice](https://github.com/Automattic/woocommerce-payments/assets/82999806/b2daff2e-3751-443c-a5ab-f8cd3d0ece87)

Instead, the template used is generated from the WooPayments server in [document-template-vat-invoice.php](https://github.com/Automattic/woocommerce-payments-server/blob/a3a04aec311c802710e064ecdf1a73ce9935e989/server/wp-content/rest-api-plugins/endpoints/wcpay/documents/templates/document-template-vat-invoice.php).

According to the issue behavior that you've described...

> If you check the UPDATE VAT INFO in their WCPAY dashboard, it's empty.

...this merchant is experiencing #8054. It appears as though they shared a VAT invoice that is not generated by WooPayments or the WooPayments server.
