### ISSUE TITLE
Don't show an estimated deposit (payout) date in WooPayments UI

### ISSUE THREAD

**Issue by haszari** [Automattic/woocommerce-payments#8175]
### Describe the bug
Currently we show an estimate for when the next deposit will be initiated on the `Payments > Overview` screen:

<img width="1311" alt="Screenshot 2024-02-12 at 12 59 21 PM" src="https://github.com/Automattic/woocommerce-payments/assets/4167300/7970f87f-228b-42be-839f-0ff94720cb31">

This date is an estimate for when the deposit will be initiated, based on the merchant's deposit schedule, and our understanding of how payouts are handled in the platform backend (e.g. Stripe).  

There are some limitations and challenges with this estimate:

- The $ will land in the merchant's account some time after the deposit is _initiated_, 1-3 days or maybe more.
- Deposits are initiated in UTC, so our estimate is based on UTC, but merchants (and their banks) are operating in other timezones.
- There are edge cases such as bank holidays that might mean our estimate is incorrect or misleading.

The goal of this issue is to remove the estimated deposit date from the UI (and remove associated code to estimate the date). Instead of showing the date we'll show a help icon or `Learn more` link, empowering new merchants with information so they understand when they will get paid.

### To Reproduce
View `Payments > Overview`.

### Actual behavior
- Estimated payout date shown, which may not be 100% accurate at all times, and doesn't provide any context on how payouts work.

### Expected behavior
- Show the merchant a summary of their deposit schedule. 
- Provide info (in docs or a tooltip) about how deposits work so merchants can understand how & when they will receive funds.

### Additional context
See also related issues:

- https://github.com/Automattic/woocommerce-payments/issues/8026
- Automattic/woocommerce-payments-server#4435

**Comment by Jinksi** [comment]
What are your thoughts on priority of this one, @haszari?

I'll move it to `backlog` as I see it as medium/low-priority, but feel free to change as you see fit.

**Comment by haszari** [comment]
> What are your thoughts on priority of this one, @haszari?

I want to get this wrapped up, we have a decision on this and should be quick to wrap up. Also I think it's important to remove the estimated date from the UI soon.

**Comment by csmcneill** [comment]
Regarding tooltips, I'm not sure the best way to go about providing information succinctly as deposit timing is complex.

A rough draft is something like: 

> Deposits are initiated based on a country's [pending period](https://woo.com/document/woopayments/deposits/deposit-schedule/#pending-period-chart), an account's [available funds](https://woo.com/document/woopayments/deposits/deposit-schedule/#available-funds), and an account's [deposit schedule](https://woo.com/document/woopayments/deposits/change-deposit-schedule/).

I don't think that we would need to make any new documentation _specifically_ to reference in a tooltip here, but if that seems to be an option worth exploring, let me know and I can see what's what :)

**Comment by zmaglica** [comment]
This issue impacts Deposits, so assigning to Helix (based on team responsibilities Pc2DNy-3z-p2) @haszari .
Assigning as part of Gamma Triage process PcreKM-yM-p2.

**Comment by elizaan36** [comment]
Just riffing off @csmcneill 's copy and thinking about how it could appear in the tooltip. Maybe bullet points would help organize the information and make it more scannable.

> Deposits are initiated based on the following criteria:
> - A country's [pending period](https://woo.com/document/woopayments/deposits/deposit-schedule/#pending-period-chart)
> - An account's [available funds](https://woo.com/document/woopayments/deposits/deposit-schedule/#available-funds) 
> - An account's [deposit schedule](https://woo.com/document/woopayments/deposits/change-deposit-schedule/)

**Comment by haszari** [comment]
Looks good @elizaan36 ! Perhaps we can humanise/personalise it e.g.

> Deposits are initiated based on the following criteria:
> - The [pending period](https://woo.com/document/woopayments/deposits/deposit-schedule/#pending-period-chart) in your country
> - Your account's [available funds](https://woo.com/document/woopayments/deposits/deposit-schedule/#available-funds)
> - Your [deposit schedule](https://woo.com/document/woopayments/deposits/change-deposit-schedule/) settings
