### ISSUE TITLE
Update the GitHub actions we use for tests to support NodeJS 20

### ISSUE THREAD

**Issue by achyuthajoy** [Automattic/woocommerce-payments#8176]
### Describe the bug

GitHub is upgrading actions to support NodeJS 20. Right now the actions we're using are currently on NodeJS 16. Hence with every action run, GitHub adds the following notice to Action Summary.

```
Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: actions/checkout@v3, actions/setup-node@v3, actions/cache@v3. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.
```

We should look into upgrading the actions to latest versions using NodeJS 20

### Expected behavior

The NodeJS 16 deprecation warnings shouldn't show.

**Comment by zmaglica** [comment]
This issue impacts CI/CD, so assigning to Harmony (based on team responsibilities Pc2DNy-3z-p2) @deepakpathania . 
Assigning as part of Gamma Triage process PcreKM-yM-p2.
