### ISSUE TITLE
The `deposits/overview` client REST API endpoint is no longer used and should be removed

### ISSUE THREAD

**Issue by Jinksi** [Automattic/woocommerce-payments#8179]
### Describe the bug

The `/deposits/overview` is no longer used by the WooPayments client (since WooPayments [2.5](https://github.com/Automattic/woocommerce-payments/releases/tag/2.5.0)). We should remove this endpoint from the client to ensure we're not unnecessarily maintaining redundant code/endpoints.

https://github.com/Automattic/woocommerce-payments/blob/59a85492d0372964127a17f5230b2eb2237fb034/includes/admin/class-wc-rest-payments-deposits-controller.php#L47-L55

REST API documentation must also be updated to reflect these changes.

https://github.com/Automattic/woocommerce-payments/blob/8512583463697730cb901ff318e17b9ffb089494/docs/rest-api/source/includes/wp-api-v3/deposits.md#L176-L188

### Additional information

* Related to server issue for removal of this endpoint https://github.com/Automattic/woocommerce-payments-server/issues/4489
* Related to client issue for removal of data-fetching code related to `/deposits/overview/` #8047

**Comment by zmaglica** [comment]
This issue impacts Deposits, so assigning to Helix (based on team responsibilities Pc2DNy-3z-p2) @haszari  .
Assigning as part of Gamma Triage process PcreKM-yM-p2.

**Comment by Jinksi** [comment]
Prioritised as `Next` as this issue should be resolved in tandem with server issue https://github.com/Automattic/woocommerce-payments-server/issues/4489 (in `Next`) which removes this endpoint from the server.
