### ISSUE TITLE
If logged in user associated with invalid customer ID then payment form does not render

### ISSUE THREAD

**Issue by jrodger** [Automattic/woocommerce-payments#818]
Not something we should see very often, but I occasionally change the WCPay server that my store is looking at (WPCOM or local dev). This means it uses a different Stripe account, which then means that some IDs aren't valid. In this case my logged in user has a customer ID associated to it that doesn't exist in the Stripe account the store is now connected to.

When attempting to checkout:
<img width=250 src="https://user-images.githubusercontent.com/686419/89555631-35130b80-d808-11ea-87c9-a8ac489ab7a6.png"/>

In the logs:
```
2020-08-06T16:07:26+00:00 INFO REQUEST GET https://public-api.wordpress.com/wpcom/v2/sites/%s/wcpay/payment_methods?test_mode=1&customer=cus_Hk59pJQKctg4Jj&type=card&limit=100
2020-08-06T16:07:26+00:00 ERROR Error: No such customer: 'cus_Hk59pJQKctg4Jj' (resource_missing)
```

We do ensure that the customer ID isn't null, but I don't think we're handling the error response for this use case. Presumably this might also happen in the event of a timeout or similar.

Ideally we would handle this and carry on rendering the payment fields. The log message makes sense though and should alert a merchant to the configuration issue.

**Comment by reykjalin** [comment]
I'm seeing this same issue after removing Jetpack from my test site to use the built-in jetpack connection. Do we have a way to get around this now besides either creating a new account or just nuking the site and setting up a new one?

**Comment by luizreis** [comment]
> I'm seeing this same issue after removing Jetpack from my test site to use the built-in jetpack connection. Do we have a way to get around this now besides either creating a new account or just nuking the site and setting up a new one?

@reykjalin - you may also delete the user metadata entry that has the customer ID saved from `wp_usermeta`. Its `meta_key` is `wp__wcpay_customer_id`. Once you do that, a new customer should be created for that user.

**Comment by aheckler** [comment]
We have a forum post with this same error here:

https://wordpress.org/support/topic/credit-card-payments-failing/?view=all

I'm assuming the same tactic applies: find the customer ID in `wp_usermeta`, delete that row, and try again?

**Comment by reykjalin** [comment]
>I'm assuming the same tactic applies: find the customer ID in wp_usermeta, delete that row, and try again?

Yes.

It's concerning that this issue happened in production, especially since it shouldn't happen unless you're somehow reconnecting to WPCOM and your store gets assigned a new ID there.

We probably need to look into handling this type of reconnection more gracefully.

**Comment by thenbrent** [comment]
> especially since it shouldn't happen unless you're somehow reconnecting to WPCOM and your store gets assigned a new ID there.

Likely related ticket in 3240516-zd-woothemes as that site has 5 separate WC Pay accounts.

**Comment by AmeliaBriscoe** [comment]
Have had a few tickets come through about this in the last couple of days. I hope it's ok to note them here.

* https://woothemes.zendesk.com/agent/tickets/3275694 (AT website)
* https://woothemes.zendesk.com/agent/tickets/3276166
* https://woothemes.zendesk.com/agent/tickets/3280603
