### ISSUE TITLE
Shortcode checkout displays Stripe error when payment information is entered but billing fields are empty

### ISSUE THREAD

**Issue by FangedParakeet** [Automattic/woocommerce-payments#8192]
### Describe the bug

When in the shortcode checkout, if payment information is entered but required billing fields are empty, [the call to `createPaymentMethod`](https://github.com/Automattic/woocommerce-payments/blob/develop/client/checkout/classic/payment-processing.js#L178) will throw a user-unfriendly error that will be displayed to the user. This occurs because [we instruct the payment element not to collect any billing fields](https://github.com/Automattic/woocommerce-payments/blob/develop/client/checkout/utils/upe.js#L84-L118), since we will collect this information from the checkout fields instead. If these fields are missing when we create the payment method, Stripe's API will throw an error that we will display immediately to the user. 

![Any payment method, name missing](https://cdn-std.droplr.net/files/acc_1104206/yS1oLW)
_Place order with any payment method, but name fields are empty_

![Afterpay, email missing](https://cdn-std.droplr.net/files/acc_1104206/aJHkEk)
_Place order with Afterpay with name present, but email address field is empty_

![Affirm, address missing](https://cdn-std.droplr.net/files/acc_1104206/EgGib2)
_Place order with Affirm with name present, but address field is empty_

Instead of showing this incomprehensible error to the shopper, we should display the usual WooCommerce form field validation errors instead.

![Usual WC validation errors](https://cdn-std.droplr.net/files/acc_1104206/JVszwu)
_Expected WC validation errors_

#### First error message (any PM)

1. Add an item to cart, proceed to shortcode checkout.
2. Ensure all billing fields are empty, select any payment method, and fill out payment method fields, if any are present/required.
3. Select Place order.
4. Notice error stating, `You specified "never" for fields.billing_details.name when creating the payment Element, but did not pass params.payment_method_data.billing_details.name when calling stripe.createPaymentMethod(). If you opt out of collecting data via the payment Element using the fields option, the data must be passed in when calling stripe.createPaymentMethod().`

#### More error messages (Affirm/Afterpay)

1. Ensure Affirm & Afterpay are enabled at checkout and enable a currency that is compatible with both payment methods (e.g. USD).
2. Add an item or items to cart that satisfy amount limits for both payment methods (e.g. total amount greater than $50, less than $4,000).
3. Select either Affirm or Afterpay, leaving all billing fields empty.
4. Select Place order.
5. Notice first error mentioned above.
6. Select Afterpay, fill name fields, but leave email and address fields empty.
7. Select Place order.
8. Notice error message stating, `Missing required param: billing_details[email].`
9. Select Affirm, with name fields filled, and address fields empty.
10. Select Place order.
11. Notice error message stating, `Missing required param: billing_details[address][line1].`

### Actual behavior

An ugly and confusing error message is displayed to shoppers when billing fields are empty.

### Screenshots

See above.

### Expected behavior

Expected and formatted WooCommerce validation errors should be shown to shoppers instead.

### Desktop (please complete the following information):

* OS: [e.g. iOS] Any
* Browser [e.g. chrome, safari]: Any
* Version [e.g. 22]: Latest

### Smartphone (please complete the following information):

* Device: [e.g. iPhone6] Any
* OS: [e.g. iOS8.1] Any
* Browser [e.g. stock browser, safari]: Any
* Version [e.g. 22]: Latest

### Additional context

CC @pierorocca

**Comment by FangedParakeet** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Heisenberg-63586f2ec60359001310fa6a/issues/Automattic/woocommerce-payments/8192?planning-poker) with Zenhub @mdmoore

**Comment by cs9k** [comment]
experiencing the same issue, opened #8270 before I found yours
