### ISSUE TITLE
Remove currency tooltip layout is broken

### ISSUE THREAD

**Issue by FangedParakeet** [Automattic/woocommerce-payments#8206]
### Describe the bug

When removing a currency from one's store, a tooltip appears warning store owners that doing so will disable certain payment methods that require this currency to be present. The layout of this tooltip looks very messy and is inconsistent with other tooltips presented in WooPayments settings.

![Broken layout on remove currency tooltip](https://cdn-std.droplr.net/files/acc_1104206/B7Xgcv)
_Uh oh, what happened here_

Note that in the above image the padding on the header is missing, padding on the body looks inadequate, and the padding between payment method names and their icons is also missing. For comparison, here is another tooltip that appears when removing payment methods from WooPayment settings: notice how much nicer it looks. 

![Nicer tooltip when removing payment methods](https://cdn-std.droplr.net/files/acc_1104206/CxaKJc)
_That's more like it_

Here is a comparison of the inconsistent padding between these tooltips.

![Padding on acceptable tooltip](https://cdn-std.droplr.net/files/acc_1104206/mXGAlz)
_Padding on header and body is 24px_

![Padding on inacceptable tooltip](https://cdn-std.droplr.net/files/acc_1104206/NEfcoT)
_Padding on header is 0px, padding on body is 16px_

It would be great if we could make the padding and layout on the latter tooltip neater and more consistent with its former relative. Here are a few incongruencies that I noticed.

- Header/body padding is different.
- Header and content font-size is different.
- Payment method name is not weighted bold.
- Currency name is not weighted bold in the footer, whereas it is weighted bold near the head of the content.
- Main currency icon is smaller (this might be fine as is, since there is more content in the body in the currency tooltip).

Here is a quick knock-up I made, which I think would already be a great improvement.

![Fixing the currency tooltip](https://cdn-std.droplr.net/files/acc_1104206/zQnqSt)
_A small step in the right direction_

CC @pierorocca & @nikkivias for feedback on the above suggested improvements. Note that I also removed the outline around the payment method icons, which I think looks a little neater and is more consistent with how these icons are displayed at checkout where the icon is also paired with its title-text label. 

### To Reproduce

1. Ensure you have multiple currencies enabled, as well as payment methods that depend on them.
2. Navigate to the Multi-currency tab (**WooCommerce > Settings > Multi-currency**).
3. Remove a currency upon which an enabled payment method depends.
4. Notice the aforementioned hideous tooltip.
5. Cringe internally.

### Actual behavior

A wild and wonky tooltip appears.

### Screenshots

See above

### Expected behavior

A nice and neat tooltip should appear with consistent styling to other related tooltips that we present to users.

### Desktop (please complete the following information):

* OS: [e.g. iOS] Any
* Browser [e.g. chrome, safari]: Any
* Version [e.g. 22]: Latest

### Smartphone (please complete the following information):

* Device: [e.g. iPhone6] Any
* OS: [e.g. iOS8.1] Any
* Browser [e.g. stock browser, safari]: Any
* Version [e.g. 22]: Latest

### Additional context

N/A

**Comment by zmaglica** [comment]
@FangedParakeet I wanted to move this issue to the team Fractal since it fails under their category of responsibilities. Do the Heisenberg plans to work on this issue? 

As a Gamma triage process, I will move this issue into the Other Team Queue. @bborman22 pinging you as well. Feel free to move this issue to the Fractal backlog if you think that Fractal is a better fit.

**Comment by pierorocca** [comment]
cc @elizaan36 as input into the ongoing settings design refresh work.

**Comment by nikivias** [comment]
Thank you. Aligning with the other modal looks good to me.

I just wonder what this red icon is for and if we can do without it?

![image](https://github.com/Automattic/woocommerce-payments/assets/99638528/73abe574-0ecd-4d86-abda-eabda88380d3)

Another thing that I wonder is whether it would look better if the payment icon came first before it's label.

**Comment by elizaan36** [comment]
Thanks for bringing this up, @FangedParakeet and for the ping @pierorocca. The modal needs some love!

+1 on removing the red error icon as @nikkivias suggests. It doesn't add anything to the message.

Here's an example of the old design for this modal to illustrate the intended scale and layout. (This could also certainly use an update in the future.)
<img width="1440" alt="Settings _ Payments _ WooCommerce Payments _ Payment methods _ None" src="https://github.com/Automattic/woocommerce-payments/assets/5121465/cd3bd7d5-f945-4f98-bebf-88cf7641b121">

There are a few issues with the existing currency modal:
- The scale is off. The header illustration is too small and the payment icons are too big.
- The payment icons should be placed to the left of the payment method name.
- The aspect ratio is off. It should be mobile friendly but ideally would have a max width (I'm seeing 670px) and adapt based on screen size.

FYI the Figma where I grabbed this is in the Production file under Payments Settings.
