### ISSUE TITLE
Internet Explorer 11 incompatibility: Unable to enter in credit card details

### ISSUE THREAD

**Issue by damiannep** [Automattic/woocommerce-payments#821]
I had a user in 23278560-hc (follow up in 3221933-zen who reported that the fields to enter in credit card details are missing in Internet Explorer 11. I tested this with Browserstack and was able to confirm it:

![checkout](https://d.pr/i/qq0dfc+)
*Full link: https://d.pr/i/qq0dfc*

**Comment by vbelolapotkov** [comment]
I confirm the bug. There is an array destructuring syntax used [here](https://github.com/Automattic/woocommerce-payments/blob/master/assets/js/wcpay-checkout.js#L354) which is not supported by IE11 [[MDN link](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Destructuring_assignment#Browser_compatibility)]. 

Note: worth checking other places as well.

**Comment by luizreis** [comment]
There's also a default parameter [here](https://github.com/Automattic/woocommerce-payments/blob/master/assets/js/wcpay-checkout.js#L270), and a `newURL` usage for a `hashevent` [here](https://github.com/Automattic/woocommerce-payments/blob/master/assets/js/wcpay-checkout.js#L504). Both are not supported by IE11 [[default parameters](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/Default_parameters#Browser_compatibility), [newURL](https://developer.mozilla.org/en-US/docs/Web/API/HashChangeEvent#Browser_compatibility)].

On a cursory look, those are the incompatibilities I found. Based on a quick test, it also seems like fixing them would allow users to checkout using IE11 (basic and 3DS cards; saved cards or not).

Given that is file is not changed much, would it be enough to fix those issues for now, or should we adopt a better strategy of supporting IE11 in the future to avoid regressions like this?

**Comment by james917** [comment]
for newUrl you can use a small library to fake it http://blog.stevenlevithan.com/archives/parseuri
