### ISSUE TITLE
Instant Deposits: `Deposit available funds` is unclear

### ISSUE THREAD

**Issue by brucealdridge** [Automattic/woocommerce-payments#8220]
### Describe the bug

When a merchant who has access to Instant Deposits has a pending balance but not available funds, the messaging is unclear. 

The merchant is told they can `Deposit available funds`, when `Available funds` are `$0.00` while also being told `You have no funds available to deposit.`

![Screenshot 2024-02-19 at 2 50 55 PM](https://github.com/Automattic/woocommerce-payments/assets/57298/e9f83451-2af3-4fe3-bcb1-4596cd4283aa)

We should update the Instant deposit button with a clearer message.

### designs
We now have designs for this from @rogermattic 🙌🏻  (see comment below https://github.com/Automattic/woocommerce-payments/issues/8220#issuecomment-2006501704)

![Image](https://github.com/Automattic/woocommerce-payments/assets/94967682/95d7fc3e-009d-4519-872e-4a7336108fec)

`Learn more` link directs the user to: https://woo.com/document/woopayments/deposits/instant-deposits/

#### older info

Ideas:
 - `Deposit pending funds`
 - `Deposit $162.83 instantly!`
 - `Deposit $162.83 within 30 minutes`

**Comment by haszari** [comment]
> When a merchant who has access to Instant Deposits has a pending balance but not available funds, the messaging is unclear.

Good point! This is somewhat an edge case (0 available + nonzero pending), so the inconsistent UI between the notice & the button is maybe of secondary importance to the word `available` on the button, which makes things more confusing (since instant deposits pay out `pending` balance as well as any cleared funds).

> `Deposit pending funds`

~~This wording tweak seems a no-brainer, no risk and clearer than the current UI. Possibly we could ship this change as an easy win.~~ no, because it's not just pending funds!

> `Deposit $162.83 instantly!`
> `Deposit $162.83 within 30 minutes`

I like the idea of using the button to promote instant deposits, and highlight the amount. Curious to hear thoughts from design & product. Possibly could log a separate follow up enhancement (i.e. `available` is a straight bug, showing the amount or promoting instant is an enhancement).

**Comment by haszari** [comment]
> Deposit pending funds
> This wording tweak seems a no-brainer, no risk and clearer than the current UI. Possibly we could ship this change as an easy win.

Actually, scratch that, I think this does need some design thinking. Because in the typical case, the instant deposit will pay out the `total` balance – `pending` + `available`. Related issue:

- #8070

**Comment by haszari** [comment]
`Deposit [total balance] now` is another option.

**Comment by shendy-a8c** [comment]
I like to respond @rogermattic's comment from p1707308907789589/1707273640.914329-slack-C045PC0V40G:

> or the CTA could just be displayed next to the relevant amount

Because the amount that can be instantly deposited isn't necessary always the same as ones displayed at the above balance 'boxes', displaying the CTA next to one of the amount might lead to confusion.

I like the proposed text copy ideas mentioned in the issue's body which basically removes the word 'available' and replaces it with an amount with some time reference.

**Comment by rogermattic** [comment]
> Because the amount that can be instantly deposited isn't necessary always the same as ones displayed at the above balance 'boxes', displaying the CTA next to one of the amount might lead to confusion.

Thanks for bringing it up @shendy-a8c it's true...

I like the simplicity of this approach with the CTA saying:
> `Deposit [total balance] now` is another option.

But it will need some connection (or rather the explanation of the lack of connection :D ) to the balances displayed above. 

Just wanted to clarify those last bits...In the new implementation, when we only have the `Total` and `Available` columns, and if
1)  `Available` is `0` the button will display the same amount as `Total balance` right? 
2) in fact it will always be the `total balance` that is available for the instant deposit, won't it?

**Comment by shendy-a8c** [comment]
> in fact it will always be the total balance that is available for the instant deposit, won't it?

Not always. There are many factors, for example, depending on merchant's risk tier, Stripe might apply a max amount that can be instant deposited. On top of that, we apply our own [limits](https://woo.com/document/woopayments/deposits/instant-deposits/#deposit-limits), so if total balance is $100k, only $1k can be instant deposited, for example.

**Comment by rogermattic** [comment]
@shendy-a8c @haszari @brucealdridge I'm not sure if it's better to present this option here or in slack (let me know) but I made a mockup for this!

Still not sure about the message... it's a tiny issue but so hard to come up with something that will be clear for the user and within our design language 😅

What do you think about this? 

**VERSION A**
<img width="970" alt="Screenshot 2024-03-13 at 15 49 07" src="https://github.com/Automattic/woocommerce-payments/assets/94967682/0de77eef-580d-46fd-8b41-64e910157db2">


I also considered this wording:
<img width="927" alt="Screenshot 2024-03-13 at 15 53 03" src="https://github.com/Automattic/woocommerce-payments/assets/94967682/cd14d6c7-e927-476c-bace-38bf976c7354">

and alternatively I'm considering this too...
**VERSION B**
<img width="573" alt="Screenshot 2024-03-13 at 16 38 46" src="https://github.com/Automattic/woocommerce-payments/assets/94967682/3c9a7c91-da1f-48b7-8407-ff620ba1af55">

Any preference on your side?

**Comment by haszari** [comment]
@rogermattic those all look like reasonable, workable options. I don't think I have a strong preference, maybe version B, or A2.

Your iterations sparked ideas…

- Should we try to consistently use exact phrase `instant deposit` – in copy and on button too? This would be super clear, like a brand name, and should localise well too. e.g. `Instant deposit $3143`
- The extra notice/copy explaining instant deposits could become clutter when merchant understands the feature. How can we balance educating the user about the feature and keeping the UI lean and focused? Maybe we can use the blue/notice version, and make it dismissable. When dismissed, we could add a help icon tooltip next to the button so the education /explanation is still available. 

Side note, I was a bit confused by the amounts in the mockups. I think in this case the instant available amount would be Total balance (`3143`), or the merchant's max instant payout (say, `1000`).

**Comment by rogermattic** [comment]
Thanks for your comment @haszari :)

>Should we try to consistently use exact phrase instant deposit – in copy and on button too? This would be super clear, like a brand name, and should localise well too. e.g. Instant deposit $3143

It's a great idea! The only thing that I'd say is that the button should call-to-action...so perhaps we could use `Instantly deposit €1,000`? So that `deposit` is that action..

>The extra notice/copy explaining instant deposits could become clutter when merchant understands the feature. How can we balance educating the user about the feature and keeping the UI lean and focused? Maybe we can use the blue/notice version, and make it dismissable. When dismissed, we could add a help icon tooltip next to the button so the education /explanation is still available.

Great suggestion!
What do you think about this? I like having the notice dismissable, definitely! But I wonder if the tooltip works better next to a heading?


![Image](https://github.com/Automattic/woocommerce-payments/assets/94967682/38e02480-9cea-47f1-9bc9-cdd489c2840f)


On the other hand I do like the version without the heading, but not sure if the tooltip works well just next to the button...(I'm still thinking about  it)..how do you feel about it? Maybe it's okay...



![Image](https://github.com/Automattic/woocommerce-payments/assets/94967682/f656f1a9-f3ae-43f7-8fe4-541509ab3064)

Let me know how you feel about it and I'll post the final final:)

CC: @brucealdridge @shendy-a8c

**Comment by haszari** [comment]
> On the other hand I do like the version without the heading, but not sure if the tooltip works well just next to the button...(I'm still thinking about it)..how do you feel about it? Maybe it's okay...

I prefer the button + tooltip. I agree the tooltip looks a little lonely, but we can't justify an extra heading (clutter, hierarchy; this text is not more important than e.g. `Total balance`). The button + tooltip pattern is useful, maybe we just need to get used to it – i.e. I can imagine other places where there's a button that might benefit from a help bubble.

**Comment by rogermattic** [comment]
@haszari thanks for this mini-review :)

On a second thought I think it works well with the tooltip next to the button, I don't mind it.
I made this final mockup:


![Image](https://github.com/Automattic/woocommerce-payments/assets/94967682/95d7fc3e-009d-4519-872e-4a7336108fec)


Learn more link directs the user to: https://woo.com/document/woopayments/deposits/instant-deposits/

[Figma designs](https://www.figma.com/file/aDFNTeogq2cXSr4Nqeni8g/Instant-Deposits?type=design&node-id=768%3A76519&mode=design&t=yAAHREAhhAvDKbh5-1)

**Comment by haszari** [comment]
Thanks @rogermattic ! This issue is super actionable now for an engineer maintaining :) – I'll remove the `needs design` label.

**Comment by haszari** [comment]
I added designs to the description and also deleted the private slack link. If there's important info in slack, someone can add it here inline.

**Comment by haszari** [comment]
Marking as high since it's confusing and there is a design we can implement. Anyone should feel free to bump this down to medium if not actioned soon (~2 weeks) e.g. due to capacity/other priorities.

**Comment by nagpai** [comment]
This may be me, but there is a chance merchants may misunderstand `Instantly deposit $xxx` as them needing to deposit, instead of receiving a deposit ( payout is a better word! ).  @aheckler - what do you think? If this needs improvement, can you please help with some alternative text? Thanks!

**Comment by aheckler** [comment]
> This may be me, but there is a chance merchants may misunderstand Instantly deposit $xxx as them needing to deposit, instead of receiving a deposit

Yeah, it's a bit unclear. :/ 

> payout is a better word!

Perhaps. Historically though, we have used "deposit" over "payout" for WooPayments, and I don't think we should break with that here.

> what do you think? If this needs improvement, can you please help with some alternative text?

Maybe simpler is better? `Get $XXX.XX now` or something similar could work, provided we can accurately calculate the max amount the merchant is eligible to receive via Instant Deposit at that moment?

Alternatively, we could use `Get $XXX.XX via instant deposit` to maintain the branding, but that text may be too long for a button/CTA?

**Comment by rogermattic** [comment]
I'd agree with the simpler is better approach and go for  `Get $XXX.XX now` but I remember we wanted to raise awareness to Instant deposits as a feature. Not a big fan of `Get $XXX.XX via instant deposit` tho..


What do you think about this info box tho?
<img width="637" alt="Screenshot 2024-06-18 at 13 21 57" src="https://github.com/Automattic/woocommerce-payments/assets/94967682/6850ac3e-3554-49ba-b5fd-3820a7a65d2e">

Does it make it any clearer than just the button in isolation?

**Comment by aheckler** [comment]
> but I remember we wanted to raise awareness to Instant deposits as a feature.

This is true, but if a merchant is seeing this button, then by definition they are already eligible for instant deposits. They've already arrived, in other words, and the only thing left to do is get them to use it, hence the direct CTA of `Get $AMOUNT now`.

> What do you think about this info box tho?

The word "and" makes it seem like the two actions ("Instantly deposit" and "get funds in your bank account") are separate things, so if anything IMHO it would _increase_ the potential for confusion. It almost sounds like I need to send $1000 to WooPayments in order to "unlock" faster deposits or something.

**Comment by rogermattic** [comment]
>This is true, but if a merchant is seeing this button, then by definition they are already eligible for instant deposits. They've already arrived, in other words, and the only thing left to do is get them to use it, hence the direct CTA of Get $AMOUNT now.
I don't mind that shorter label at all :)

>The word "and" makes it seem like the two actions ("Instantly deposit" and "get funds in your bank account") are separate things, so if anything IMHO it would increase the potential for confusion. It almost sounds like I need to send $1000 to WooPayments in order to "unlock" faster deposits or something.

Would it be better as:

Instantly deposit €1,000. Funds will be available in your bank account within 30 minutes. Fee: 1.5%.

or


Instantly deposit €1,000 and receive funds in your bank account within 30 minutes for a 1.5% fee.

??

**Comment by aheckler** [comment]
IMHO neither sounds good. "Deposit" as a verb usually means money flowing away from me and to some third party, which is the opposite of what's actually happening here. 

To clarify that, I still think we have to say "Get $AMOUNT via instant deposit" or something like that. Phrasing it that way makes it clear that the money is flowing to the merchant, not away from them.

**Comment by rogermattic** [comment]
"Get €1,000 via instant deposit. Funds will be available in your bank account within 30 minutes. Fee: 1.5%." ? :)

**Comment by aheckler** [comment]
Sounds good. The final thing I'd be wary of is "Funds will be available in your bank account within 30 minutes." Stripe says "funds typically settle in the associated bank account within 30 minutes", so maybe ours should be a tad more vague?

> Get €1,000 via instant deposit. Funds are typically in your bank account within 30 minutes. Fee: 1.5%.

**Comment by haszari** [comment]
> IMHO neither sounds good. "Deposit" as a verb usually means money flowing away from me and to some third party, which is the opposite of what's actually happening here.

This is a really good example of why switching to `Payouts` would be helpful 😁

**Comment by aheckler** [comment]
> This is a really good example of why switching to Payouts would be helpful 😁

Perhaps. It'd be helpful for _us_ no doubt, but past research shows it confuses merchants. See paJDYF-6u-p2 and paJDYF-6G-p2.
