### ISSUE TITLE
Loop when trying to setup a production account in a dev mode site

### ISSUE THREAD

**Issue by leonardola** [Automattic/woocommerce-payments#8229]
### Describe the bug
[WooPayments will stick to dev mode](https://github.com/Automattic/woocommerce-payments/blob/8f6b267928fb12bee30cb0ba6d1773e9c24b4ff2/includes/core/class-mode.php#L44-L47) when `WP_ENVIRONMENT_TYPE` is set to `development` or `staging` so when a user clicks the onboarding button it tries to go into production mode but then fails and goes back to the same page without a warning message.

### To Reproduce
- Set the `WP_ENVIRONMENT_TYPE` const to `staging` or `development`
- Go to /wp-admin > Payments > Settings
- Click the Setup Payments button

### Actual behavior
The page reloads but no error message is shown
 
### Screenshots
[](https://github.com/Automattic/woocommerce-payments/assets/6342964/70b1662c-18c3-407e-b659-169f153cbab9)

### Expected behavior
Either an error should show up telling the merchant that the site needs to be in production mode before setting up a production WooPayments account or not show the button to create the account at all.

**Comment by htdat** [comment]
This issue impacts "Onboarding", so assigning to @Automattic/moltres (based on team responsibilities Pc2DNy-3z-p2) cc team lead @daquinons. 
Assigning as part of Gamma Triage process PcreKM-yM-p2.

**Comment by daquinons** [comment]
This is the same as https://github.com/Automattic/woocommerce-payments/issues/7803 :) Closing
