### ISSUE TITLE
Multi-Currency charm pricing not applied to shipping cost

### ISSUE THREAD

**Issue by emilhov** [Automattic/woocommerce-payments#8237]
### Describe the bug
When switching between currencies the configured charm pricing is applied to all prices, however not to the shipping cost.

### To Reproduce
1. Enable Multi-Currency under WooCommerce -> Payments -> WooPayments -> Advanced settings -> Multi-Currency
2. Enable any other currency than default USD (e.g. EUR)
3. Manage newly enabled currency (Price rounding to 1.00, Charm pricing to -0.01)
4. Add Shipping Zone with fixed rate shipping method ($2.99)
5. Add any item to cart
6. Go to checkout and switch to any different currency (e.g. EUR)
7. See error

### Actual behavior
Shipping costs receive the configured price rounding correctly ($2.99 becomes 3.00€ instead of 2.76€), however the configured charm pricing (-0.01) is not applied.

### Screenshots

| **USD (default)** | **EUR (with price rounding 1.00 and charm pricing -0.01)** |
|--------|--------|
| ![image](https://github.com/Automattic/woocommerce-payments/assets/50546876/90cf1547-ba62-47f4-a51d-3e3f8bcc1075) | ![image](https://github.com/Automattic/woocommerce-payments/assets/50546876/4b090429-5f30-4087-bd47-91bbc2f3697b) | 

### Expected behavior
Charm pricing should be correctly applied according to configuration for each currency.
For USD to EUR: $2.99 should become 2.99€

### Desktop:

* OS: Windows 10
* Browser Microsoft Edge
* Version 121.0.2277.128

### Smartphone:

* Device: Samsung Galaxy S10
* OS: Android 12 / OneUI 4.1
* Browser Samsung Browser
* Version 23.0.1.1

### Additional context
WooCommerce 8.6.0
WooPayments 7.2.0

Even when deactivating every other plugin the error remains.

**Comment by htdat** [comment]
Thanks for reporting this issue, @Hovhannibang! 

This issue impacts " Multi-Currency", so assigning to @Automattic/fractal (based on team responsibilities Pc2DNy-3z-p2) cc team lead @bborman22 
Assigning as part of Gamma Triage process PcreKM-yM-p2.

**Comment by pierorocca** [comment]
According to the documentation, Charm pricing does not apply to taxes and shipping thus this seems to be working as expected. If you feel this is incorrect, please reopen the issue. Thanks.



![Image](https://github.com/Automattic/woocommerce-payments/assets/109928953/b6d53891-1d9f-4a0e-b0ad-e6775d6b83c3)
