### ISSUE TITLE
Update to React 17

### ISSUE THREAD

**Issue by allendav** [Automattic/woocommerce-payments#825]
Needs coordination with https://github.com/woocommerce/woocommerce-admin

Timeframe unspecified

cc @timmyc @nerrad

**Comment by nerrad** [comment]
Do you folks load a different version of React than what ships with WordPress? Currently react should be loaded as an external within the WP environment? From my perspective we should monitor what happens in [the Gutenberg project](https://github.com/WordPress/gutenberg/issues/24485) (which will be the signal for when it will potentially land in WordPress core too). 

Some suggested steps:

- Watch [the Gutenberg issue](https://github.com/WordPress/gutenberg/issues/24485) for when GB has updated it's packages to run React 17 (likely won't happen completely until React 17 stable drops).
- When those updates land in the GB feature plugin, test with the feature plugin active against our projects (which should start using the new version of React with GB active) - address any issues the pop up.

The interesting thing from my perspective is that when React 17 drops in WordPress core, there likely will be this awkward period where supporting multiple versions of WordPress means also supporting multiple versions of React. Hopefully that won't be problematic (from what I've seen it shouldn't be).

Specific to WooCommerce payments, you might have a different approach than the above if you use React directly in some contexts, but thought I'd share anyways for relevance to the larger coordination between teams using React.

**Comment by timmyc** [comment]
We do not load another version of React in wc-admin iirc - we instead inherit from WP core.

**Comment by deepakpathania** [comment]
There is an open [PR](https://github.com/woocommerce/woocommerce-admin/pull/8305) for this in the `woocomerce-admin` repo now. We can pick this up once that gets merged.

**Comment by vbelolapotkov** [comment]
WCA PR has been merged, unblocking this one.

**Comment by zmaglica** [comment]
We are already on react [17](https://github.com/Automattic/woocommerce-payments/blob/develop/package.json#L162). Closing this issue as resolved. Please don't hesitate to reopen it if you think that we have more work to do.
