### ISSUE TITLE
Payment messaging element should use computed styles for the Appearances API

### ISSUE THREAD

**Issue by FangedParakeet** [Automattic/woocommerce-payments#8253]
### Description

Stripe allows us to customise the appearance of our payment method payment elements at checkout by submitting our preferences to the [Appearances API](https://docs.stripe.com/elements/appearance-api) by offering these parameters to the Elements object used to create a payment element. We produce these parameters by computing styles from temporary clones of checkout DOM elements and these values are stored to a site-wide transient. 

The payment method messaging element can also accept these parameters, but we are not yet providing them to the element. Consequently, this element is often at odds with the theme of the site, particularly on darker themes. 

![Payment messaging text is illegible](https://cdn-std.droplr.net/files/acc_1104206/3V2k1l)
_Invisible information_

### Acceptance criteria

Please ensure that we are submitting custom computed styles to the Appearances API when creating the payment method messaging element, so that it is as legible and consistent as possible with any store theme. 

The simplest option would be to reuse the styles computed at checkout and stored in a site-wide transient. If this is not sufficient, we may need to add new rules for the Appearances API to match suitable elements contained within the payment messaging element or--worse yet--we may need to compute new styles from the product details page, but this latter operation will be much more challenging, so should be treated as a last resort. 

### Designs

N//A

### Testing instructions

1. Enable Klarna/Afterpay/Affirm, ensure payment methods are enabled and will be supported, then activate a dark theme for your store.
2. Proceed to product detail page for a suitable product, when these payment methods are applicable, and notice that the payment method messaging element that should appear below the price of the product is illegible.

### Additional context

#8094 
#8128

**Comment by gpressutto5** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Heisenberg-63586f2ec60359001310fa6a/issues/Automattic/woocommerce-payments/8253?planning-poker) with Zenhub @FangedParakeet
