### ISSUE TITLE
BNPL payment method issue in the "Customer payment page" flow

### ISSUE THREAD

**Issue by hesahesa** [Automattic/woocommerce-payments#8254]
### Describe the bug

The Affirm / Afterpay / Klarna payment methods cannot be paid using the "Customer payment page" flow

### To Reproduce

1. In the wp-admin Order page, create an Order with the "pending payment" status, assign it to a customer
2. Copy the "Customer payment page" URL and open it as the assigned customer
3. The Pay for Order page is opened. Open the Chrome browser's console log, and see that there is a `Uncaught (in promise) TypeError: Cannot read properties of null (reading 'value')` error.
4. Try choosing Klarna, click the "Pay for Order" button. Observe that there is a `Cannot read properties of null (reading 'submit')` error and the page is stuck

### Screenshots

<img width="532" alt="image" src="https://github.com/Automattic/woocommerce-payments/assets/1663428/e8e71816-5052-4ac8-9eb0-18e6b7fcf217">

<img width="587" alt="image" src="https://github.com/Automattic/woocommerce-payments/assets/1663428/2388957a-da7a-4aa9-9cab-8c902f13e2ef">

<img width="1127" alt="image" src="https://github.com/Automattic/woocommerce-payments/assets/1663428/215edc02-d70a-4618-8550-fbff5dca0220">

### Expected behavior

BNPL payment methods should be usable on that page, or they need to be hidden if the flow is not supported

**Comment by danielmx-dev** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Heisenberg-63586f2ec60359001310fa6a/issues/Automattic/woocommerce-payments/8254?planning-poker) with Zenhub @FangedParakeet

**Comment by danielmx-dev** [comment]
@FangedParakeet Although the initial estimate was 2, I bumped this to 3 given the complexity that the final solution involved.
