### ISSUE TITLE
Remove duplicate/redundant "Ready to start Selling" text

### ISSUE THREAD

**Issue by dmallory42** [Automattic/woocommerce-payments#8278]
### Describe the bug

When a user is onboarded progressively, we show modal with confetti confirming that this was successful.

However, we also have a similar message which appears on the dashboard which we can now remove because it is duplicating the modal and therefore redundant.

### To Reproduce

1. Onboard a progressive account.
2. Verify you see the success modal.
3. Once this is closed, there is a further "You're ready to start selling" card which can be removed since it's duplicating the modal.

### Screenshots

<img width="970" alt="Screenshot 2024-02-27 at 16 16 42" src="https://github.com/Automattic/woocommerce-payments/assets/11770181/7facfdb3-e86a-4c32-b4c7-2b3565cbb481">

**Comment by htdat** [comment]
@dmallory42 - I think this issue will go to Team Moltres backlog, right? 

I am doing triage so asking that to know where I can put it in the proper triage queue.

**Comment by dmallory42** [comment]
Hi @htdat ! Yes, I think this is one for Moltres.

**Comment by vladolaru** [comment]
We should make sure that the PO modal and this success notice are mutually exclusive.

**Comment by anu-rock** [comment]
@dpaun1985 As you have self-assigned this issue, could you also add an estimate for it?
