### ISSUE TITLE
Hide Fraud Tools Banner until account process a first order with WooPayments

### ISSUE THREAD

**Issue by dmallory42** [Automattic/woocommerce-payments#8279]
### Describe the bug

As mentioned on Slack (p1709049534474959/1709049161.731439-slack-C03KTTK2YMA) - we should hide the `Enhanced Fraud Protection` banner while an account is in progressive/store setup. We should only show this banner once the account setup is fully complete.
 

### To Reproduce

1. Onboard a new progressive account.
2. You will see the Fraud Protection banner on the Overview page.

### Screenshots

<img width="615" alt="Screenshot 2024-02-27 at 16 41 29" src="https://github.com/Automattic/woocommerce-payments/assets/11770181/712b2b53-ffdd-4787-9d0c-b274bb35f72d">

### Expected behavior

* For a progressive account, the FRT banner should only show after PO setup is complete.

### Desktop (please complete the following information):

* OS: [e.g. iOS]
* Browser [e.g. chrome, safari]
* Version [e.g. 22]

### Smartphone (please complete the following information):

* Device: [e.g. iPhone6]
* OS: [e.g. iOS8.1]
* Browser [e.g. stock browser, safari]
* Version [e.g. 22]

**Comment by htdat** [comment]
This issue impacts `Merchant facing Risk Tools`, so assigning to @Automattic/sigma (based on team responsibilities Pc2DNy-3z-p2) cc team lead @dwainm

Assigning as part of Gamma Triage process PcreKM-yM-p2.

**Comment by daquinons** [comment]
There has been a rethink in the issue [here](https://a8c.slack.com/archives/C01B8KNUYSW/p1712917339984119?thread_ts=1712860760.259209&cid=C01B8KNUYSW).

We are going to hide the banner for all type of accounts until the store collects the first payment.
