### ISSUE TITLE
Feature: Provide more details to resolve Restricted and Pending verification account states

### ISSUE THREAD

**Issue by csmcneill** [Automattic/woocommerce-payments#8283]
### Description

If an account is in a non-Enabled state (e.g., `Restricted` or `Pending verification`), in addition to providing them them with email comms about the issue, we will provide the status of the account at **Payments > Overview > Account details**. However, there are no clear steps for the user to take in-plugin to move their account from a non-Enabled state to `Enabled`.

_We_ know that there are additional details needed to verify the account, and _we_ know that those details can be provided via the **Edit details** option on the **Payments > Overview** page...

![image](https://github.com/Automattic/woocommerce-payments/assets/82999806/4fdbf739-0de6-41db-9897-a081dfb216dc)

...but a merchant may not know this. Some specific guidance would be super helpful here so that merchants can self-serve more easily without referring to an outside source for information.

### Acceptance criteria

* First requirement
* Second requirement
* Third requirement
* etc.

### Testing instructions

1. Go to '…'
2. Click on '…'
3. Scroll down to '…'
4. Observe expected behaviour

### Additional context

pbUcTB-447-p2#no-direction-if-an-account-is-pending-verification

**Comment by htdat** [comment]
This issue impacts `Account`, so assigning to @Automattic/moltres (based on team responsibilities Pc2DNy-3z-p2) cc team lead @anu-rock. 

Assigning as part of Gamma Triage process PcreKM-yM-p2.

**Comment by anu-rock** [comment]
Added it to the team backlog.

**Comment by rogermattic** [comment]
@csmcneill Thanks for creating this issue! 
What are the details that the merchant will need to provide? Do we have a list of requirements that every merchant needs to submit? Do they need to Edit the details in Stripe or send them to us by email? I'm asking cause it can help me understand how we can surface the details in the UI.

**Comment by csmcneill** [comment]
@rogermattic The details required vary wildly depending on the geo and the business structure. One option to consider would to _not_ provide specifics in-product and use a general notice providing _some_ information.

My understanding about resolving Restricted states is that it usually requires providing additional information in the Express Dashboard, which is similar to [updating tax information](https://woo.com/document/woopayments/account-management/tax-id-changes/). If an account is Pending verification, there's nothing that a merchant can do, as the information needs to be verified by Stripe.

A rudimentary solution could be, if an account is in a Restricted state, providing a general notice suggesting something like:

> More information is needed to enable your account. Please [edit the account details](#insert-magic-link-here) and provide the requested information to start using WooPayments! [Learn more](https://woo.com/document/woopayments/account-management/tax-id-changes/).

Before Adam went on leave, we had discussed consolidating some of the "Update account" pages (e.g., updating tax ID, contact information, etc.) because they all require the same initial steps.

**Comment by anu-rock** [comment]
Thanks for the tip, @csmcneill 🙌

@rogermattic I'm circling back for your expert thoughts here. Adding a notice does sound like a good idea to me to avoid leaving the merchant in the lurch. Hypothetically, this may even reduce a few support tickets from merchants curious about their account status.

**Comment by vladolaru** [comment]
Please note that we have this one-pager (paJDYF-cyI-p2) specifically for handling situations like these.

**Comment by rogermattic** [comment]
@anu-rock @vladolaru 
Thanks for bringing me back here! I didn't forget about this project, just wanted to explore this a bit better as this seems to be a part of a bigger project. I didn't want to just start exploring the designs in Figma before some competitive analysis etc.   Just a quick question – what is the timeline of this project? When are we looking to improve this?

**Comment by anu-rock** [comment]
@rogermattic I think we would like to take up this project a bit later in Q2 depending on when we are ready with the designs. We do not have set dates yet. Pulling in @timmy5685 for visibility and thoughts.

**Comment by anu-rock** [comment]
The original issue reported by @csmcneill will be fixed by https://github.com/Automattic/woocommerce-payments/issues/9128, which we plan to pick up in Q1 of 2025. Closing this one.
