### ISSUE TITLE
WooPayments checkout payment method radio buttons are not WCAG compliant

### ISSUE THREAD

**Issue by pierorocca** [Automattic/woocommerce-payments#8289]
### Description
The radio button group in the attached example, when selected using a screen reader such as Talkback, voices "Checked. In option group 1 of 6.“ 

**Problem**: The shopper does not know what payment method they've selected just by navigating onto the radio button. They are forced to navigate into the option, in order to have the payment method label voiced. Note that on desktop, a screen reader user will use the up and down arrow keys to quickly navigate through an option group. Forcing the user to navigate into the option disrupts that quick navigation.

![image](https://github.com/Automattic/woocommerce-payments/assets/109928953/271910af-cac7-46ec-a9d4-1fe707330776)

### Acceptance criteria
The screen reader voices "Checked. In option group 1 of 6. Credit card / debit card.“ when the checked radio button is selected in the attached example.

The screen reader voices "Unchecked. In option group 2 of 6. Check payments.“ when the next (unchecked) radio button is navigated to in the attached example.

And so on for the remaining payment methods.

### Designs
N/A

### Testing instructions
1. Add items to a cart
2. Proceed to checkout
3. Enable Talkback or Voiceover
4. Select the Credit card / debit card option
5. Observe that "Checked. In option group 1 of 6. Credit card / debit card.“ or equivalent is voiced.
6. Select the next unchecked radio button. Do not yet check it.
7. Observe that "Unchecked. In option group 2 of 6. [payment method name]“ or equivalent is voiced.

### Additional context
https://www.w3.org/WAI/ARIA/apg/patterns/radio/examples/radio/

**Comment by htdat** [comment]
This issue impacts `Checkout UI`, so assigning to @Automattic/heisenberg (based on team responsibilities Pc2DNy-3z-p2) cc team lead @FangedParakeet

Assigning as part of Gamma Triage process PcreKM-yM-p2.

**Comment by brettshumaker** [comment]
@pierorocca I've looked into this a little bit today and haven't been able to reproduce this issue on your test site. Once I'm tabbed into that radio group, I can use my L/R arrow keys to navigate through the options and hear VoiceOver speak the payment method titles. They're read out multiple times for some reason but they're being said.

Could you upload a screencast of how you're navigating through the page or confirm if this is still an issue?

Thanks!

**Comment by pierorocca** [comment]
>  I can use my L/R arrow keys to navigate through the options and hear VoiceOver speak the payment method titles. 

This may have been resolved through another issue or refactor elsewhere. I am now hearing "Checked. In option group 1 of 6. Credit card / debit card.“ whereas when I opened the ticked I'd only hear "Checked. In option group 1 of 6.“ using Talkback on Android.

I think we can close this one out.
