### ISSUE TITLE
[Spike] Implementing Stripe's new Express Checkout Element

### ISSUE THREAD

**Issue by FangedParakeet** [Automattic/woocommerce-payments#8297]
### Description

Currently we implement express checkout methods, like Apple and Google Pay, using Stripe's [Payment Request Button](https://docs.stripe.com/stripe-js/elements/payment-request-button) (PRB) implementation. This is not yet immediately deprecated, but soon to be replaced by Stripe's newer [Express Checkout Element](https://docs.stripe.com/elements/express-checkout-element) (ECE). The ECE offers improved browser support and enhanced functionality for existing payment methods, as well as support for additional wallet payment methods (e.g. PayPal). 

Additionally, Stripe has an October mandate to update the domain registration flow for wallet-type payment methods (pbUcTB-40l-p2); it would likely be beneficial to couple this update with their newer ECE as a future-proofed solution for our checkouts.

This spike issue is to validate the benefits of the ECE integration, explore the [migration path from our current PRB implementation](https://docs.stripe.com/elements/express-checkout-element/migration), and to explore how this new implementation may aid us to alleviate many of our ongoing ailments with PRBs at checkout (e.g. #3372, #3417, #1573, #5657).

### Acceptance criteria

Here are some questions that it would be helpful to answer in this spike.

1. What problems can the ECE implementation solve for us?
2. What does migration to the ECE look like?
3. How will our new domain registration flow work with the ECE integration?
4. Can this implementation support deferred payment intent creation via [client-side payment method creation](https://docs.stripe.com/elements/express-checkout-element/accept-a-payment#create-pm)?
5. Would it be possible to separate the ECE into its constituent payment methods and would it be possible to include these as payment gateway options alongside our regular payment methods, as opposed to displaying them in the express checkout widget at checkout?
6. And many more...

A positive output from this spike would probably include a P2 explaining and comparing the implementation, from which we can create new issues to proceed with the actual implementation.

### Designs

N/A

### Testing instructions

N/A

### Dev notes

N/A

### Additional context

paJDYF-ckK-p2

**Comment by gpressutto5** [comment]
7841665-zd-a8c

**Comment by FangedParakeet** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Heisenberg-63586f2ec60359001310fa6a/issues/Automattic/woocommerce-payments/8297?planning-poker) with Zenhub @mdmoore

**Comment by mdmoore** [comment]
Findings posted here - pbIwZe-1QB-p2
