### ISSUE TITLE
Disputes should have custom order statuses rather than using `on-hold`

### ISSUE THREAD

**Issue by brucealdridge** [Automattic/woocommerce-payments#8306]
### Description

When a dispute is received, WooPayments updates the status of the order to `on-hold`.

This has created a few issues (#526, #7928) and isn't ideal. Specific dispute-related status should be added.

### Dev notes

Work on this occurred in #714 and was never merged and closed as stale. This could be a good starting point.

**Comment by haszari** [comment]
See also next steps from abandoned PR #714 :


- Find any prior art & discussion (P2/internal/product/design) relating to disputed order status.
- Ideate what bugs and pain points this could fix/mitigate.
- P2 this as a proposal, with the status values and how order can transition between. (could be design-led)
- Then we can decide whether to proceed, and where (WooPayments vs. WooCommerce core). If we proceed we will need to start afresh in a new PR as the relevant code has changed significantly.

FYI @souravdebnath1986 - we could consider adding explicit order statuses for disputes as a roadmap project.

Could potentially also log this issue in WooCommerce core to get input from core side.

**Comment by haszari** [comment]
This is a project/enhancement idea, we can't action as-is. In future there may be projects to provide more detailed order status (in WooCommerce core). FYI @warrendholmes - I am pretty sure this is on product radar as there are discussions about order status.

Closing the issue to keep our issue backlog focused on actionable bugs. Feel free to reopen or ping me if it's useful to keep this enhancement idea open.
