### ISSUE TITLE
Update the Payments Connect page design and logic

### ISSUE THREAD

**Issue by vladolaru** [Automattic/woocommerce-payments#8310]
### Description
To streamline our onboarding flow, we are doing a series of enhancements to our Payments Connect page and our MOX (onboarding wizard) with the goal of providing extra context and and setting clearer expectations before each step, while reducing the number of steps/clicks involved. 

The Payments Connect page will function as **a catch-all entry point** in our onboarding. The design for it is brand new with added focus and simplicity, while also better aligning with the Woo overall design language.

We are moving the live or sandbox decision to the Connect page, out of the first MOX step (removing that step completely). The CTA of the Connect page will become dynamic, depending on if there is a working store WPCOM/Jetpack connection or not:

Already working Jetpack connection:
![Screenshot 2024-03-04 at 12 09 45](https://github.com/Automattic/woocommerce-payments/assets/8830539/c92c05f9-2f18-4094-adc1-aa691f281bb7)

No Jetpack connection:
![Screenshot 2024-03-04 at 12 10 06](https://github.com/Automattic/woocommerce-payments/assets/8830539/ab9f4f54-2fc2-44ac-b1f3-5f7de24061a1)

To further provide context, for each scenario, there will be a notice (see the above screenshots) informing the merchant about what the next step implies.

There is not ToS copy on the Connect page as that will be included in the MOX (see https://github.com/Automattic/woocommerce-payments/issues/8311).

The expanded sandbox mode section:
![Screenshot 2024-03-04 at 12 17 56](https://github.com/Automattic/woocommerce-payments/assets/8830539/775acf2f-134c-4ad2-bfdb-39a28cc8b312)

Note: As a general principle (and in alignment with @elizaan36), we want to make the Connect page dynamic and context-aware about where the merchant is coming from (directly through the main menu item, WooCommerce task list, Payments > Settings page, etc.) For this, we should have a system similar to marketing UTMs that would allow (but not force) the page logic to know how to "speak" with the merchant in a manner aligned with how he's been primed by the lead surfaces. For this dynamism, we will probably create separate issues to tackle the various scenarios, but it may be worthwhile to be knowledgeable of this aim when designing the page rendering logic.

### Acceptance criteria

* The new design for the Connect page is implemented (both for desktop and mobile)
* Existing Jetpack connections are properly detected and skipped. The Connect page CTA and notice are dependent on the prior existence of a working Jetpack connection
* If the merchant returns from the Jetpack connection flow without setting up a connection we maintain the current logic that provides a notice about the fact that a working Jetpack connection is required (the same way it is working today).
* Ineligible country detection remains in place with notice and modal, like it is currently working. @elizaan36 to provide designs for this scenario if changes need to be made.
* The Sandbox mode will skip our MOX and go straight to Stripe KYC, but will require a Jetpack connection (as it does today). We should probably inform the user about the need for a Jetpack connection, the same way we are doing for live mode.
* WooPayments Incentives (Action and Switch) surfaces still show up.

For final copy consult this doc: https://docs.google.com/document/d/1CGDCmOyGSkHj5kJhdWXoAkXXaHN_cnjkGJ0WVvl_o30/edit

### Designs
Figma connected to WPCOM: VLWDmeuIXQ7XAK4flyqTFO-fi-714_95806
Figma not-connected to WPCOM: VLWDmeuIXQ7XAK4flyqTFO-fi-714_95807
Figma Sandbox-mode: VLWDmeuIXQ7XAK4flyqTFO-fi-714_90878

### Additional context
P2 post: paJDYF-ci2-p2

**Comment by elizaan36** [comment]
> Ineligible country detection remains in place with notice and modal, like it is currently working. @elizaan36 to provide designs for this scenario if changes need to be made.

@vladolaru I think the existing notice can appear in the same placement at the top of the redesigned Payments Connect screen. I don't see any reason this needs to change at this time. 🤔

<img width="1437" alt="image" src="https://github.com/Automattic/woocommerce-payments/assets/5121465/76f73f12-8b84-4007-9ab3-05c82ac4f3ef">

**Comment by vladolaru** [comment]
Agree @elizaan36. It is good to get clarity about these things as it will make implementation that much quicker.

About the Incentives dedicated surface, I know you did some explorations, but in the meantime, could you provide some guidance on where and how to surface them?

**Comment by elizaan36** [comment]
As far as I know the action incentive will remain in place for now. I did some explorations but the new design hasn't been reviewed, so we can hold that for a future update and use the existing incentive component placed just below the CTA.

<img width="1276" alt="image" src="https://github.com/Automattic/woocommerce-payments/assets/5121465/0163ae12-b5a7-4fd5-946c-726247fd4c08">

The only thing I'd tweak to help integrate into the new design is the border color to match the grey border of the other card components.

I think it still works it doesn't push the builder mode option too far down the page. What do you think?

**Comment by vladolaru** [comment]
@elizaan36 I am struggling a little bit with the overall Information Architecture of this page when an incentive is available. 

Since the incentive is directly tied to your signing up for WooPayments via the page CTA (it is not a separate signup flow like the sandbox mode), it seems more natural to me to have the incentive section integrated into the main section, just above the CTA. Maybe with less of a box feel and more like the notice about the need for a WPCOM account to make it more integrated.

I think it would reduce cognitive load around making it feel like a third option (which it isn't) and also convey the overall WooPayments value proposition in a top-to-bottom way (merchants would scan our payments options, deposits, payments capture and recurring payments, then a limited time offer, and then decide if to start signing up).

WDYT?

**Comment by elizaan36** [comment]
I agree! Iteration on the incentive could be a separate scope of work since I'm not super clear on the need to make adjustments based on metrics.

Here's an approach we could use that would be more integrated into the main section. The badge contains the incentive prompt, and clicking the toggletip will present more details on the offer.

I'm updating the prompt to mention "transaction fees" rather than processing costs in line with Magda's recent fees UX review. cc @rogermattic for your thoughts on the design and copy.

<img width="1292" alt="Payments Connect - WP Installed, WPCOM connection required" src="https://github.com/Automattic/woocommerce-payments/assets/5121465/7f77bbad-b366-4deb-812e-575ede1c5b81">

<img width="1292" alt="Payments Connect - WP Installed, WPCOM connection required popover" src="https://github.com/Automattic/woocommerce-payments/assets/5121465/359dcdfc-fc53-4beb-9293-43fd8e009e90">

**Comment by vladolaru** [comment]
Interesting take @elizaan36! Thank you for the fast turnaround. I think this less prominent placement could work for the Connect page (maybe less so for the core Payments page). Do we still want to emphasize that an incentive is a limited-time offer?

**Comment by elizaan36** [comment]
Yes, makes sense. Here's the same popover concept with additional text for the Limited time offer.

<img width="794" alt="Payments Connect - WP Installed, WPCOM connection required popover" src="https://github.com/Automattic/woocommerce-payments/assets/5121465/47eeb1ed-6563-42b4-8c88-cec5ceef145f">

I think this approach may actually work for the payments in core page, if we're moving more in the direction of WooPayments feeling default/included. I'll have a close look at that next.

**Comment by rogermattic** [comment]
Hey @elizaan36  for the ping! 

> I'm updating the prompt to mention "transaction fees" rather than processing costs in line with Magda's recent fees UX review. cc @rogermattic for your thoughts on the design and copy.

I really like the copy, don't have any comments on that. The only thing that worries me is that the badge might be a little hard to spot and perhaps a bit disconnected. My first thought was to add it closer to `Payments` column. Would you be okay with me trying this (making a mockup)?

**Comment by elizaan36** [comment]
Yes! Thank you so much Magda, it's a huge help.

**Comment by timmy5685** [comment]
@elizaan36 @rogermattic - do we have the bandwidth to experiment with the incentive design a bit more here? Based on our chat this morning, I totally understand the move from a separate tile to combining it into the main box (and totally agree!). But my concern with the current tooltip design is that the incentive gets lost and is hard to spot as @rogermattic mentions in her comment - but I'm not sure that placement of the tooltip will solve that problem.

My understanding is that the goal of the incentive is to drive higher acquisition. If so - then I feel like we should be exploring designs that make the incentive more prominent so we capture the merchant's attention.

**Comment by elizaan36** [comment]
@timmy5685 Let me know if you're having trouble accessing the Figma or sharing comments on there where I've pinged you. It would be most helpful for the design team if you could provide feedback in context of the explorations. There are four different possibilities currently. 
<img width="798" alt="image" src="https://github.com/Automattic/woocommerce-payments/assets/5121465/41276361-c0f4-4187-ba09-025aa297c9f1">

**Comment by timmy5685** [comment]
@elizaan36 Sorry - trying to follow all the conversations in different places. Will drop my comments there instead.

**Comment by timmy5685** [comment]
@oaratovskyi Just wanted to close the loop here after some additional conversation with design. We have decided to proceed with leaving the incentive tile in it's current placement below the main tile. Here is the final design:

Figma: https://www.figma.com/file/VLWDmeuIXQ7XAK4flyqTFO/Payments-Adoption-%26-Activation?type=design&node-id=685%3A109475&mode=design&t=EuO0JBZXaov8Ava9-1

<img width="1452" alt="Payments Connect - WP Installed, WPCOM connection required" src="https://github.com/Automattic/woocommerce-payments/assets/32650633/ef113702-31b1-4f34-8388-655e481392f9">

Let me know if you have any questions.

cc: @rogermattic @vladolaru @elizaan36

**Comment by oaratovskyi** [comment]
Thanks @timmy5685 and the design team! Looks good to me, I like it 🙂

**Comment by oaratovskyi** [comment]
@elizaan36 I also noticed that we need to move somewhere the developer/builder sandbox notice 

I came up with three options, I am curious what you think and whether copy of the notice makes sense!
| One - InlineNotice | Two - BannerNotice |
|---|---|
| ![image](https://github.com/Automattic/woocommerce-payments/assets/79862886/f0ca4638-9250-46d9-abe2-f5bfe7d8849d) | ![image](https://github.com/Automattic/woocommerce-payments/assets/79862886/818934b2-2988-4123-b4ad-3238eca7228d) |

cc @vladolaru @timmy5685

**Comment by timmy5685** [comment]
@elizaan36 - after chatting with @vladolaru, we are both of the opinion that it should be Option 2 as it's only a notice that our internal developers see. This will not be visible externally.

If you are in agreement with that - my only remaining question would be is that the correct styling? While we aren't leveraging a shared component - would still be great to have this follow the correct pattern whether it be the one shown in option 1, option 2, or some other pattern.

Thanks!

**Comment by elizaan36** [comment]
> we are both of the opinion that it should be Option 2 as it's only a notice that our internal developers see. This will not be visible externally.

+1. Makes sense. 

This is the correct styling and consistent with the other updated notices we've been using in WooPayments.

**Comment by vladolaru** [comment]
The details about these changes have been shared here: pc2DNy-3Sh-p2
