### ISSUE TITLE
Reduce our MOX (onboarding wizard) for added focus

### ISSUE THREAD

**Issue by vladolaru** [Automattic/woocommerce-payments#8311]
### Description
To streamline our onboarding flow, we are doing a series of enhancements to our Payments Connect page and our MOX (onboarding wizard) with the goal of providing extra context and and setting clearer expectations before each step, while reducing the number of steps/clicks involved.

For our MOX, we need to remove the first step for deciding between live or sandbox mode, remove the individual details second step, improve our business details step, and provide better context and expectations before redirecting to Stripe.

### Acceptance criteria

* There is no live or sandbox step in the MOX as that is moved to the Payments Connect page (https://github.com/Automattic/woocommerce-payments/issues/8310)
* There is no individual details step in our MOX
* The first step of the MOX is the business details collection step (see Figma VLWDmeuIXQ7XAK4flyqTFO-fi-723_118919 ) that includes:
  * Business registration country - prefilled with the country collected through the WooCommerce profiler, in a state that is not a select with the possibility to change it (see Figma VLWDmeuIXQ7XAK4flyqTFO-fi-723_118919)
  * Legal entity type (with options depending on the business registration country)
  * Business structure (shown after the legal entity type selection with options depending on it)
  * Types of goods or services (MCC) (shown after the business structure is selected); the MCC field will be prefilled depending on the industry vertical provided in the WooCommerce profiler; this mapping should be provided by our platform via the `onboarding/fields_data` API as a separate entry in the response (see https://github.com/Automattic/woocommerce-payments-server/issues/4854).
* When the MCC field is filled (prefilled or selected) the ToS copy will appear above the step CTA
* The second step of the MOX will be for store self-assessment as it is today (estimated revenue and go-to-live timeframe) for Progressive Onboarding eligibility purposes.
  * We should do a pre-step eligibility assessment based on the collected business details, and if the merchant is already ineligible (mostly due to country and business type), we should skip this second step of the MOX; see this server issue (https://github.com/Automattic/woocommerce-payments-server/issues/4853) for this
* The third step of the MOX is the loading screen while the Stripe account is initialized (PO or no) after which the user is redirected to the Stripe KYC.
* The MOX maintains its current local storage save and restore functionality 

For final copy consult this doc: https://docs.google.com/document/d/1CGDCmOyGSkHj5kJhdWXoAkXXaHN_cnjkGJ0WVvl_o30/edit

### Designs
Figma for first MOX step VLWDmeuIXQ7XAK4flyqTFO-fi-566_43521
The states the first MOX step is going through:
![image](https://github.com/Automattic/woocommerce-payments/assets/8830539/37a49b3a-0d4a-42c6-b206-ab9372536cf1)
![image](https://github.com/Automattic/woocommerce-payments/assets/8830539/38bcab27-1faf-4f2d-b950-0275c7044ae0)
![image](https://github.com/Automattic/woocommerce-payments/assets/8830539/40430b73-1dd5-48ea-825b-a8c2d1c3c45f)
![image](https://github.com/Automattic/woocommerce-payments/assets/8830539/5f5b3119-e6d4-4e73-8752-aeb88c29a707)
![image](https://github.com/Automattic/woocommerce-payments/assets/8830539/417a8eae-3fa9-4194-899e-97d25d43d910)

Figma for second MOX step VLWDmeuIXQ7XAK4flyqTFO-fi-595_60987
The states the second MOX step is going through:
![image](https://github.com/Automattic/woocommerce-payments/assets/8830539/fce73ba4-fdca-4828-aba3-724967826767)
![image](https://github.com/Automattic/woocommerce-payments/assets/8830539/496998ea-8c7c-486a-b52b-17eb539c7290)
![image](https://github.com/Automattic/woocommerce-payments/assets/8830539/cd08184c-ca78-4457-9449-752f0c4e7b71)
![image](https://github.com/Automattic/woocommerce-payments/assets/8830539/d59c0e45-7b5b-432c-b680-64ea21c19d1b)

Third step:
<img width="1488" alt="309935308-90cb5928-768b-4531-9831-17ab07762c02" src="https://github.com/Automattic/woocommerce-payments/assets/8830539/94ad7b2d-f92e-4cfc-ad3a-240883f35dca">

### Additional context
P2 post: paJDYF-ci2-p2
Related issues:
https://github.com/Automattic/woocommerce-payments-server/issues/4853
https://github.com/Automattic/woocommerce-payments-server/issues/4854

**Comment by vladolaru** [comment]
cc @elizaan36

**Comment by elizaan36** [comment]
All looks good except I think we agreed to remove the CTA from the loading screen. Per discussion:  paJDYF-ci2#comment-23055

With no CTA this screen would look like this. 

<img width="1488" alt="Payments – Loader screen" src="https://github.com/Automattic/woocommerce-payments/assets/5121465/90cb5928-768b-4531-9831-17ab07762c02">

**Comment by vladolaru** [comment]
Thank you for double-checking things, @elizaan36! I've updated the issue with regards to the loading step and removed the CTA.
