### ISSUE TITLE
Create payments activity widget survey definition in WPCOM

### ISSUE THREAD

**Issue by dpaun1985** [Automattic/woocommerce-payments#8314]
Part of #8485

### Description

In order to have the survey data ( created in #8506 ) available in MC tools, we need to define the survey in WPCom. 

> [!IMPORTANT]  
> Code changes can be reviewed at [D140691-code](https://href.li/?https://code.a8c.com/D140691)

### Acceptance criteria

* New survey definition is added WP/mc/marketing/survey/ 

### Testing instructions
- change your host file to point `public-api.wordpress.com` and `dev-mc.a8c.com` to your sandbox's IP address if you didn't already
- log-in to your sandbox
- apply this patch created to your dev server
	```
	cd /home/missioncontrol/public_html && git clean -df && git reset --hard && arc patch D140691
	```
- in your client repo, run `wp option update _wcpay_feature_payment_overview_widget 1` in CLI (`npm run cli` if docker)
- in the client admin panel, go to `Payments -> Overview`
- by clicking the first 3 emoji, a textarea for comments should appear
- for the highest rates ( last 2 emojis ) the survey will be sent without comments
- after submitting the results, go to https://dev-mc.a8c.com/marketing/survey/index.php?survey=wcpay-payment-activity and check the answers.
- download the resutls of the survey as a CSV file to check the responses.
- to re-submit, run `wp option delete wcpay_survey_payment_overview_submitted` to clear your local submission state

> [!NOTE]  
> There will be lots of PHP warnings rendered when visiting the `dev-mc` pages and/or downloading the CSV file. This is an issue with all marketing survey response views in MC and these warnings do not render for production MC.

**Comment by dpaun1985** [comment]
Code changes can be reviewed at D140691-code

**Comment by shendy-a8c** [comment]
@Jinksi I left some feedback at D140691-code.

**Comment by Jinksi** [comment]
Thanks @shendy-a8c ! I've made changes and am requesting a re-review 🔄

**Comment by shendy-a8c** [comment]
Nice! Approved D140691-code.

**Comment by Jinksi** [comment]
Deployed D140691-code
