### ISSUE TITLE
[QIT] Warning in`class-wc-payments-express-checkout-button-display-handler.php`

### ISSUE THREAD

**Issue by cesarcosta99** [Automattic/woocommerce-payments#8316]
### Context

This warning was caught during the release cycle after running the QIT tests against the 7.3.0 release branch.

### Message

> filter_input() used w/o filter or with default/unsafe ones

### Source

> audit.php.lang.misc.filter-input-no-filter

### File

[includes/express-checkout/class-wc-payments-express-checkout-button-display-handler.php:173](https://github.com/Automattic/woocommerce-payments/blob/25eb75f2c777c5f8e33917591d98ec72ed9d6984/includes/express-checkout/class-wc-payments-express-checkout-button-display-handler.php#L173)

**Comment by vbelolapotkov** [comment]
@c-shultz sending this one to you since it comes from express checkout button.

**Comment by ricardo** [comment]
This issue is still present for 7.7.0.

@hsingyuc – since you worked on this line, can we add `FILTER_SANITIZE_EMAIL` to `filter_input` to fix this warning?

**Comment by dmvrtx** [comment]
Still present in 7.8.0
