### ISSUE TITLE
Epic: Add support for SCA recurring transactions (subscriptions)

### ISSUE THREAD

**Issue by thenbrent** [Automattic/woocommerce-payments#833]
A follow-on to #117. Once we support non-SCA charges, we will need to also suppose SCA charges.

Needs of scoping and breakdown.

From @DanReyLop via Slack: p1597832108399100-slack-CGGCLBN58

> We’ll need several email templates, a way for the user to click on an email link and get to the SCA modal, special handling for user-initiated early renewals (those are on-session payments), etc.

**Comment by thenbrent** [comment]
I went over the Stripe plugin's handling of SCA renewal payments with @LevinMedia including content of the emails and approach of marking orders as failed to leverage WC Subscriptions' failed payment retry system.

He confirmed, implementing the same behavior as Stripe is suitable for WC Pay.

**Comment by dwainm** [comment]
See this note for when we start working on this: https://github.com/Automattic/woocommerce-payments/pull/832#discussion_r476925733

**Comment by thenbrent** [comment]
Closing this as a duplicate of https://github.com/Automattic/woocommerce-payments/issues/2002.
