### ISSUE TITLE
[7.3.0] Non-card payment methods noted as incompatible with the Checkout Block

### ISSUE THREAD

**Issue by csmcneill** [Automattic/woocommerce-payments#8349]
### Describe the bug

If a site admin edits a page that has the checkout block, there will be a warning that all APMs (even those that are not enabled) are incompatible with the checkout block.

The notice is resolved when reverting to 7.2.0.

### To Reproduce

1. Ensure the site is running 7.3.0.
2. Edit a page using the Checkout block.
3. Attempt to modify one of the blocks.
4. See a "Some active extensions do not yet support this block" notice in the block settings.
5. Revert to 7.2.0.
6. Repeat steps 2 and 3.
7. The notice from step 4 is no longer visible.

### Actual behavior

The checkout block suggests that it is incompatible with non-card payment methods, which is not true AFAICT.

### Screenshots

![CleanShot 2024-03-07 at 11 32 32@2x](https://github.com/Automattic/woocommerce-payments/assets/82999806/6afe433a-19e6-4c67-9466-be82c7a1573a)

### Expected behavior

This notice should only appear if these payment methods are incompatible.

### Additional context

From what I can tell, APMs and BNPLs may be considered individual payment gateways/extensions in 7.3.0. When spinning up a new site, I get spammed with emails about multiple payment gateways being activated — one for each APM/BNPL method available:

![Screenshot 2024-03-07 at 11 31 30 AM](https://github.com/Automattic/woocommerce-payments/assets/82999806/656f8f5e-ffec-4284-932c-5fb40adeb3f7)

**Comment by FangedParakeet** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Heisenberg-63586f2ec60359001310fa6a/issues/Automattic/woocommerce-payments/8349?planning-poker) with Zenhub @FangedParakeet @timur27
