### ISSUE TITLE
E2E test suite `shopper-bnpls-checkout` fails due to missing selector when changing currency.

### ISSUE THREAD

**Issue by Jinksi** [Automattic/woocommerce-payments#8354]
### Describe the bug

The e2e test suite in file `shopper-bnpls-checkout.spec.js` is failing due to a missing selector when attempting to change the shopper account currency.

https://github.com/Automattic/woocommerce-payments/blob/bb876e12d97b1bc07fa10f1e51b1ffd42f5f5c09/tests/e2e/specs/wcpay/shopper/shopper-bnpls-checkout.spec.js#L36-L39

Which calls the function `changeAccountCurrencyTo`:
https://github.com/Automattic/woocommerce-payments/blob/bb876e12d97b1bc07fa10f1e51b1ffd42f5f5c09/tests/e2e/utils/flows.js#L167

### To Reproduce

1. Observe PR GH checks targeting `develop` `E2E Tests - Pull Request / WC - latest | wcpay - shopper`, [example](https://github.com/Automattic/woocommerce-payments/actions/runs/8186840074/job/22386061490?pr=7671#step:5:82).
	- Alternatively, run locally with the command
	`npm run test:e2e -- tests/e2e/specs/wcpay/shopper/shopper-bnpls-checkout.spec.js`. 	
	- Also failing for server e2e tests ([example](https://github.com/Automattic/woocommerce-payments-server/actions/runs/8194869092/job/22411872166?pr=4889#step:16:42))
3. Notice the above test failing due to `No node found for selector: #wcpay_selected_currency`

**Comment by FangedParakeet** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Heisenberg-63586f2ec60359001310fa6a/issues/Automattic/woocommerce-payments/8354?planning-poker) with Zenhub @timur27
