### ISSUE TITLE
Admin multi-currency e2e tests are failing

### ISSUE THREAD

**Issue by cesarcosta99** [Automattic/woocommerce-payments#8357]
### Description

The admin multi-currency e2e tests are failing and affecting checks of other PRs.

**Spec**: [tests/e2e/specs/wcpay/merchant/merchant-admin-multi-currency.spec.js](https://github.com/Automattic/woocommerce-payments/blob/develop/tests/e2e/specs/wcpay/merchant/merchant-admin-multi-currency.spec.js)
**Error**: `TimeoutError: Navigation timeout of 100000 ms exceeded`
**Relevant line**:

```
> 889 | 		await page.goto( `${ WP_ADMIN_DASHBOARD }widgets.php`, {
```

**GitHub checks that this spec is failing**:
- WP - nightly | WC - latest | wcpay - merchant

### Acceptance criteria

All tests on that spec pass.

**Comment by bborman22** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Fractal-62a0f7b955648b001e1f5e1f/issues/Automattic/woocommerce-payments/8357?planning-poker) with Zenhub @cesarcosta99

**Comment by vbelolapotkov** [comment]
@c-shultz sending this one to you since it's related to multi-currency widget tests.
