### ISSUE TITLE
Entering a new card number should deselect any saved card

### ISSUE THREAD

**Issue by allendav** [Automattic/woocommerce-payments#836]
i.e. after I started typing in 4242... the "Use a new payment method" radio should have automatically selected

<img width="364" alt="Screen Shot 2020-08-24 at 4 36 22 PM" src="https://user-images.githubusercontent.com/1595739/91106736-404ba100-e628-11ea-872e-73d973c03aa1.png">

**Comment by dechov** [comment]
Fixed by adjusting the markup so that the form is hidden altogether when a saved card is selected, which is the standard/intended behavior in WC core.
