### ISSUE TITLE
Husky pre-push script prevents `git push` via VSCode command

### ISSUE THREAD

**Issue by Jinksi** [Automattic/woocommerce-payments#8360]
### Describe the bug

The husky pre-push script added in #8287 prevents the VSCode command `Git: push` from working.

The following command output is shown:
```
> git push origin e2e/fix-shopper-bnpls-checkout:e2e/fix-shopper-bnpls-checkout
.husky/pre-push: line 5: /dev/tty: Device not configured
error: failed to push some refs to 'github.com:Automattic/woocommerce-payments.git'
```

https://github.com/Automattic/woocommerce-payments/blob/bb876e12d97b1bc07fa10f1e51b1ffd42f5f5c09/.husky/pre-push#L4-L5

> [!TIP]
> **Workaround**: use terminal to run `git push` 🫢

### To Reproduce

1. Use VSCode and open this repo.
2. Choose a branch, any branch.
3. Open the command palette and run the command `Git: push`
4. Notice the dialog `Can't push refs to remote.`.
5. Click `Show command output` to see the error message above.

**Comment by timur27** [comment]
@Jinksi thanks for the issue! I was passing by and implemented a quick fix for this scenario. I hope it's fine that I added you as the reviewer.
