### ISSUE TITLE
Update Link by Stripe branding

### ISSUE THREAD

**Issue by csmcneill** [Automattic/woocommerce-payments#8366]
### Description

On 8 March, we received the following communication from Stripe:

> The week of April 15th we plan to update the logos/icons used to the attached assets across:
> 
> - Logo and color swap on all Link product surfaces, including payment surfaces, Link app, Stripe dashboard, Stripe docs, support, Financial Connections, Identity, Crypto, and Stripe outbound emails
> - [link.com](http://link.com/) and [stripe.com/link](http://stripe.com/link) updates

### Acceptance criteria

Replacing the Link logo at `/assets/images/payment-methods/link.svg` (and any other Link-related branding) with updated assets.

### Designs
pbUcTB-4pX-p2

### Additional context

We have 7.5.0 launching during the week of 15th April, so it may be a good opportunity to update the branding in that release.

**Comment by gpressutto5** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Heisenberg-63586f2ec60359001310fa6a/issues/Automattic/woocommerce-payments/8366?planning-poker) with Zenhub @FangedParakeet

**Comment by gpressutto5** [comment]
I pinged @elizaan36 on Slack to find out if we already have the icons to be used in the admin. I tried updating the svg we have in pbUcTB-4pX-p2, but it didn't go well 😅 

![image](https://github.com/Automattic/woocommerce-payments/assets/12385501/eace4ce3-7f6a-44d8-b106-e13e47c65e44)

![image](https://github.com/Automattic/woocommerce-payments/assets/12385501/68e2d88b-cf22-4a59-9189-ad295c57d30b)

Currently we use the same icon for the checkout page. We might want to change that.

![image](https://github.com/Automattic/woocommerce-payments/assets/12385501/63efe5af-e226-48d6-aaad-7f931acdd16c)

![image](https://github.com/Automattic/woocommerce-payments/assets/12385501/ce03ecc9-a826-4d1a-9d3c-7390be807951)

**Comment by FangedParakeet** [comment]
@gpressutto5, all the assets are included in the `link-branded-assets-selected-assets` in this P2 post ->  pbUcTB-4pX-p2

We reached out to Stripe here to confirm which assets we should be using specifically, but are still awaiting a response -> p1710878901039989-slack-C9976E5MJ

Perhaps for now we can use "Link logo green light RGB" on the settings page...

![Link_logo_primary_green_light_RGB](https://github.com/Automattic/woocommerce-payments/assets/1694446/addc71ec-1e8a-4cf0-ada0-25789473c1de)
_A bit difficult to see here, but should be clearer on a light background in settings_

...and the smaller logo on the email field perhaps?

![Link_symbol_circle_green_RGB](https://github.com/Automattic/woocommerce-payments/assets/1694446/eeed3dec-8b4c-49f2-b426-47154f3de72a)
_Mini logo to add to email address field_

CC @pierorocca for blessings: also, not sure if you have any preferences between using the circular, rounded, or square icons that Stripe has provided. 🙏

**Comment by pierorocca** [comment]
Is the email field logo provided through an iframe or are we populating it @FangedParakeet? If we are, could you add that question to the Stripe Slack thread please?

Let's wait for Stripe to confirm which logo is correct given they do not have an accompanying brand guideline to share and would like to do this only once. :)

**Comment by FangedParakeet** [comment]
> Is the email field logo provided through an iframe or are we populating it @FangedParakeet?

It's an icon that we manually add to the email input that triggers Stripe's iframe on click.

> If we are, could you add that question to the Stripe Slack thread please?

Done and just dumped all the icon options into the thread. Will await Stripe's enlightenment. 🙏

**Comment by FangedParakeet** [comment]
Just updating this thread with the result of our Slack conversation with Stripe: we have indeed decided to go with the icons described in [this comment](https://github.com/Automattic/woocommerce-payments/issues/8366#issuecomment-2013086560) (`Link_logo_primary_green_light_RGB` & `Link_symbol_circle_green_RGB`). And let my mind-reading abilities never be called into question again. 😁

**Comment by pierorocca** [comment]
Ha I called `Link_logo_primary_green_light_RGB` so we must both be savants.

**Comment by gpressutto5** [comment]
p1711387457836599-slack-CU6SYV31A
Can we get a 16:10 (64x40) version of `Link_logo_primary_green_light_RGB`? I tried using an online editor but it went from 1.46kB to 4.62kB and looks bad:

![image](https://github.com/Automattic/woocommerce-payments/assets/12385501/7a6fa310-2104-4891-96dc-b8c48118bd37)

**Comment by elizaan36** [comment]
hey @gpressutto5 I've updated the link logos in our design assets. I'll share the Figma and exports with you in Slack!
