### ISSUE TITLE
Postcode / zip code is required not optional

### ISSUE THREAD

**Issue by docmartin** [Automattic/woocommerce-payments#8368]
### Describe the bug

Attempting to make a payment with the postcode/ zip code field blank leads to payment failed message, saying some info is lacking.

### To Reproduce

1. Go to '…'  Try making payment
2. Click on '…'  Payment button, after filling in everything except this field.
3. Scroll down to …'   

- see Failed payment

### Actual behavior

That's it really: no postcode/ zip code, the payment fails.

Realised this for store I have targeting Hong Kong, which does not have postcode. [Elsewhere, postcodes / zip codes are commonplace, so users may tend to fill in this field].

A prospective customer had a payment failed, tried with 2 credit cards.
I switched to test mode; and found the error occurring.

Then, although the field says "optional", I tried adding "000000" which can work for Hong Kong when postcode is required. And payment worked. The actual payment by customer then worked too, also with "000000" in the postcode field.

### Screenshots

This works; field left blank does not.

<img width="517" alt="Screenshot 2024-03-11 at 11 19 26 PM" src="https://github.com/Automattic/woocommerce-payments/assets/161782/c941ba6a-42b8-4cab-91bb-924c49f2b5e7">

### Expected behavior

Well, expected payment to proceed... ... 

### Desktop (please complete the following information):

* OS: [e.g. iOS] 
* Browser [e.g. chrome, safari]
* Version [e.g. 22]

Don't believe this matters; didn't ask what customer uses.
For me, with latest Mac 14.2.1, Safari. I didn't try with others, as found the "00000" pseudo code entry worked.

### Smartphone (please complete the following information):

* Device: [e.g. iPhone6]
* OS: [e.g. iOS8.1]
* Browser [e.g. stock browser, safari]
* Version [e.g. 22]

### Additional context

Hopefully this is enough info, and straightforward enough to resolve.
Googling for info, I noticed various people with payment failures, sometimes mysterious. It might be that this is at times the culprit, rather than anything "deeper"?

I think either make this postcode / zip code field actually optional - though of course, if places have postcodes, they can be very helpful.

Or note that should use correct postcode if there is one; and if none, please enter "000000".   [as temporary workaround effort, I have added text to this effect to the checkout page, rather than dig into the plugin code, which will change at times anyway\

**Comment by csmcneill** [comment]
I can reproduce this consistently using the shortcode checkout.

To expand on @docmartin's reproduction steps:

1. Ensure WooPayments 7.3.0 is active.
2. Add a product to your cart.
3. Proceed to the shortcode checkout.
4. Ship to any address in HK.
5. Leave the postcode empty (as it is optional).
6. Attempt to pay for the order with a new card (saved card details will succeed).
7. Placing the order will produce the following error:

```
Invalid or missing payment details. Please ensure the provided payment method is correctly entered.
```

I suspect that this is related to https://github.com/Automattic/woocommerce-payments/issues/8352

Similar reports:
- p1709887537591149-slack-C3NCP7ZJ6 / 7855655-zen
- p1710124942897699-slack-C3NCP7ZJ6 / 7866692-zen

**Comment by devvnawaz** [comment]
By default, WooCommerce hides the **Postcode / ZIP** field on the checkout form when a merchant is [selling to specific countries](https://d.pr/i/cXhCvq) that do not require Postcode / ZIP. I was able to replicate the error in such scenario on my test website with WooPayments version `7.3.0` and the `[woocommerce_checkout]` shortcode. Reverting to version `7.2.0` or using **checkout block** instead of the **checkout shortcode** solved the issue for me. 

Another example here: 7880220-zen

**Comment by Prin-S** [comment]
7878822-zd-a8c

**Comment by zmaglica** [comment]
@pierorocca it appears that this issue is put on the Shopper Experience maintenance queue. Are you folks looking into this issue? Do you need help from the Gamma team? The reason why I am asking is that I had to triage this issue as a porter and noticed that you folks have some activity on this issue.

**Comment by pierorocca** [comment]
@zmaglica if the focus label is applied, it will be pulled into our project board automatically and will be triaged by Wednesday eod or earlier. I'd say no need to triage issues already in our board as we're very active.

**Comment by daniyalahmadk** [comment]
Another report 7904615-zen

**Comment by gpressutto5** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Heisenberg-63586f2ec60359001310fa6a/issues/Automattic/woocommerce-payments/8368?planning-poker) with Zenhub @FangedParakeet

**Comment by EjayhanFernandes** [comment]
8054526-zd-a8c - The user in this ticket experienced this issue on `7.4.0`. I can also replicate the issue on `7.4.0` of WooPayments. Having them roll back to `7.2.0`.

**Comment by gpressutto5** [comment]
@EjayhanFernandes This fix was released with version `7.5.0` a few hours ago.

**Comment by pierorocca** [comment]
Fabulous @gpressutto5. Does this have any side benefit for express checkouts (Google and Apple Pay)?

**Comment by gpressutto5** [comment]
No, this does not affect express checkouts.

**Comment by csmcneill** [comment]
@francoishvz Can you please follow up with affected merchants and let them know to update to version 7.5.0?
