### ISSUE TITLE
Update the WP.org plugin author to WooCommerce

### ISSUE THREAD

**Issue by vladolaru** [Automattic/woocommerce-payments#8385]
### Description
We need to change the plugin author displayed in WordPress.org from `Automattic` to `WooCommerce` and make sure it is linked to `https://woocommerce.com`.

### Acceptance criteria

* On [the WP.org plugin page](https://wordpress.org/plugins/woocommerce-payments/), we see `by WooCommerce` with `WooCommerce` linked to `https://woocommerce.com`
* In the WP admin dashboard, when searching for WooPayments (`/wp-admin/plugin-install.php?s=woopayments&tab=search&type=term`), for the WooPayments result tile, we see `by WooCommerce` with `WooCommerce` linked to `https://woocommerce.com`
* In the WP admin dashboard installed plugins page (`/wp-admin/plugins.php`), for WooPayments, we see `by WooCommerce` with `WooCommerce` linked to `https://woocommerce.com`

### Additional context
p1710352835484739-slack-C3ECCGUVC

**Comment by beaulebens** [comment]
Please make sure when this changes that the `automattic` wp.org user is still a contributor/has access to the plugin code in WP.org's SVN repo.

**Comment by vladolaru** [comment]
@beaulebens contributors will remain [as they are today](https://github.com/Automattic/woocommerce-payments/blob/9e98720f82da1ef96994567c71ed521efcdfa857/readme.txt#L2-L2): `woocommerce, automattic`
