### ISSUE TITLE
Transaction listing pages show times in UTC.

### ISSUE THREAD

**Issue by brucealdridge** [Automattic/woocommerce-payments#8386]
### Describe the bug

Transactions, Disputes, and Deposits listing pages show Date / Time in `UTC` rather than in the Merchant's timezone.

This was changed in https://github.com/Automattic/woocommerce-payments/issues/7591 to align with server exports which are in UTC. While the label says `UTC` it appears to be in the Merchant's timezone. This may require a new issue to resolve.

![image](https://github.com/Automattic/woocommerce-payments/assets/57298/dcd61795-e1e7-4d01-9428-23127d77b691)

### To Reproduce

1. Go to Payments > Transactions
2. See `Date / Time (UTC)`

**Comment by haszari** [comment]
I see there are a few issues open about dates, times, reports and timezones. We need to consider this as a whole – maybe worth a project. FYI @souravdebnath1986  

Related issues:

- #4845
- #2847
- #8386 (this issue)

**Comment by haszari** [comment]
> While the label says UTC it appears to be in the Merchant's timezone.

@brucealdridge are you confident on this? Assuming correct, marking this as `high` priority because the UI is inaccurate/misleading for all merchants.

**Comment by brucealdridge** [comment]
> are you confident on this? 

The PR #7813 updated the labels, but didn't update the formatting or the tests.

https://github.com/Automattic/woocommerce-payments/blob/85079f54ab9dc8454da8d36c7c7cd38ea385046b/client/transactions/list/index.tsx#L449-L457
The code to render the date calls `.local()` which [converts into the users timezone](https://momentjscom.readthedocs.io/en/latest/moment/03-manipulating/07-local/)

**Comment by haszari** [comment]
Thanks for clarifying! We have a high priority issue to fix :)
