### ISSUE TITLE
Create Payment Activity Parent Component | Simplify UX Phase 1 | Iteration 1

### ISSUE THREAD

**Issue by jessy-p** [Automattic/woocommerce-payments#8389]
### Description

- Develop a parent wrapper component which will be visible on Payment Overview page when the feature flag `_wcpay_feature_payment_overview_widget` is enabled.
- This component will serve as a simple wrapper component, allowing other developers to include their components when ready.
- Could include the title (if appropriate)
- Out of scope for this issue: Implementation of TPV check and empty state logic.

### Acceptance criteria
- Parent Wrapper Component exists, within which other components for Payment Activity can be added

### Designs
Phase 1 Design: p6riRB-9OY-p2
Simplified Iteration 1 Design: bIfbBgyBPRzvXEl7dEg3cv-fi-1373_37800

### Additional context
https://github.com/Automattic/woocommerce-payments/pull/8234

**Comment by jessy-p** [comment]
Closing in favor of new set of stories for this project.

**Comment by Jinksi** [comment]
Should we re-open this as part of #8484 (Show payment activity widget on overview screen)?

We still require this step and #8412 (@nagpai) has made progress on this.

**Update**: I've re-opened this and added it as part of #8484.
