### ISSUE TITLE
WooPay Button Preview Styles not Loading on Settings Page

### ISSUE THREAD

**Issue by LCmry** [Automattic/woocommerce-payments#8401]
### Describe the bug

When on the WooPay settings page the preview of the WooPay button is greyed out and misaligned. Similar to #8328 

<img width="689" alt="Screenshot 2024-03-15 at 8 05 39 AM" src="https://github.com/Automattic/woocommerce-payments/assets/7651258/0893c576-9cf1-4a03-b640-4868126370de">

**Comment by pierorocca** [comment]
Team concerned that this could have an adverse impact on merchants keeping WooPay enabled during a new store setup. Please treat as a top high priority issue.
