### ISSUE TITLE
Payments using the legacy Card object can fail if there are changes to billing details

### ISSUE THREAD

**Issue by csmcneill** [Automattic/woocommerce-payments#8405]
### Describe the bug

If a customer has a subscription where the tokenized payment method uses the legacy Card object, these payments can fail with the following error:

```
This PaymentMethod was converted from a legacy Card object. You may not update the email or phone number of these PaymentMethods.
```

Based on the error message, this is a result of changes to the customer's email or phone number. However, this only occurs with 7.3.0 active — reverting to 7.2.0 resolves the issue.

#### Note: I have not reproduced this yet.

1. Purchase a subscription product with a `card_` payment method.
2. Force a renewal by running the `woocommerce_scheduled_subscription_payment` scheduled action.
3. If that is successful, try adjusting either the email address or phone number associated with the customer and repeating step 2.

### Actual behavior

Payments fail when using a tokenized payment method, but only with 7.3.0 active. I suspect it is related to #8226 but I'm not positive.

Additionally, it's TBD if this only affects subscription renewals.

### Expected behavior

Renewals do not fail if they use the `card_` object while running 7.3.0

### Additional context

p1710532466431139-slack-C03EE4CPPK5
p1710531291134079/1704393766.219159-slack-C03EE4CPPK5

**Comment by zmaglica** [comment]
@bummytime for this issue, I set the focus label to subscription, but the ownership could also be shared with other teams. If you think that other teams could be a better fit for this issue, feel free to replay here or/and change the focus label.

**Comment by EjayhanFernandes** [comment]
8031701-zd-a8c 

Some additional findings:

- When reverting to `7.2.0` and retrying payment for the renewal order it looks like this error occurs:
```
Error: The PaymentMethod card_**************** does not belong to the Customer you supplied 
cus_****************. Please use this PaymentMethod with the Customer that it belongs to instead.
```

- My findings indicate that users don't have the `_wcpay_customer_id_live` key set, so Stripe creates a new one for the renewal order. Same findings from Katie here: p1710962674706519/1710527408.209409-slack-C026V8PUALS
- The merchant updated the user's `_wcpay_customer_id_live` to match the corresponding `customer_id_new` provided in the CSV file (p1711136718217879/1710539210.905229-slack-C03EE4CPPK5) via the database. This update resulted in a successful renewal.
- Additionally, the merchant updated the `_wcpay_customer_id_live` for other users, aligning them with the matching `customer_id_new` through the database, which also led to successful renewals.
- One thing to note, even after adding the ` _wcpay_customer_id_live` key to all the users, subscriptions will still fail if they renew on version `7.4.0`, so staying on version `7.2.0` for now is the best option until a fix is deployed.

**Comment by csmcneill** [comment]
@Automattic/quark Could y'all help determine if `focus: subscriptions` is the right focus label here? If it isn't, I'd like to get this triaged to the right team.

I also want to loop in @geektzu since he's spent a good amount of time working on subscription migrations with regard to WooPayments.

**Comment by csmcneill** [comment]
Noting here that this issue is likely currently affecting WCCOM: p1713402398368049-slack-C07418EA0

The impact is 120+ failed renewals.

**Comment by Jinksi** [comment]
Added `priority: critical` based on evidence of failing sub renewals.

**Comment by Mayisha** [comment]
> @Automattic/quark Could y'all help determine if `focus: subscriptions` is the right focus label here? If it isn't, I'd like to get this triaged to the right team.

@csmcneill from the error message in the description https://github.com/Automattic/woocommerce-payments/issues/8405#issue-2189424357 and this comment https://github.com/Automattic/woocommerce-payments/issues/8405#issuecomment-2050981468, the issue is related to the `paymentMethod` and `customer`. The payment gateway sets these data and the subscription plugin does not handle them. Considering this, the issue should not be labeled as `focus: subscriptions` as it it more like an WooPayments issue.
