### ISSUE TITLE
WooPay button on express checkout merchant settings preview is broken

### ISSUE THREAD

**Issue by pierorocca** [Automattic/woocommerce-payments#8408]
### Describe the bug
 This bugs makes express checkout look broken and doesn't inspire confidence in new merchants in keeping it enabled.

![image](https://github.com/Automattic/woocommerce-payments/assets/109928953/c96d6497-586f-4d15-8519-4d7204ac84d4)

![image](https://github.com/Automattic/woocommerce-payments/assets/109928953/3a80fe69-be56-4afc-aa6f-30af126ea879)

Would be great to bundle this and https://github.com/Automattic/woopay/issues/2559 together as a combo.

**Comment by zmaglica** [comment]
Hi @pierorocca, I have noticed that you put the focus label, and I think that you made the right choice. Do you think that Shopper experience team could pick this issue?

**Comment by pierorocca** [comment]
> Hi @pierorocca, I have noticed that you put the focus label, and I think that you made the right choice. Do you think that Shopper experience team could pick this issue?

Yes @zmaglica as it's my team and all `focus: WooPay` issues will always be handled by Shopper Experience.

These labels will auto place the issue into the Shopper Experience project board for weekly triaging:

focus: checkout payment
focus: woopay
focus: multi-currency 

I'll add you to the board for visibility?

**Comment by c-shultz** [comment]
@LCmry looks like this is a duplicate of the issue you created last week: https://github.com/Automattic/woocommerce-payments/issues/8401

I assigned you here since you're assigned to the other. This one has some additional screenshots, so do you mind reconciling these two issue? I wasn't sure which you would prefer to close since you were already looking at the issue.

**Comment by pierorocca** [comment]
Closing in favor of #8401. Good catch @LCmry.
