### ISSUE TITLE
Placing an order with Klarna e2e test keeps failing

### ISSUE THREAD

**Issue by shendy-a8c** [Automattic/woocommerce-payments#8416]
### Describe the bug

[Placing an order with Klarna e2e test](https://github.com/Automattic/woocommerce-payments/blob/67e989e1eaec3066cb0589e114c75727838cfa59/tests/e2e/specs/wcpay/shopper/shopper-klarna-checkout.spec.js#L80) keeps failing.

Example run: https://github.com/Automattic/woocommerce-payments/actions/runs/8335400815

**Comment by bborman22** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Fractal-62a0f7b955648b001e1f5e1f/issues/Automattic/woocommerce-payments/8416?planning-poker) with Zenhub @ricardo
