### ISSUE TITLE
Only payment methods active in the plugin's settings screen to be available when creating a new order manually

### ISSUE THREAD

**Issue by anastas10s-afk** [Automattic/woocommerce-payments#8418]
### Description

Currently, there is the option to selectively enable additional [payment methods](https://woo.com/document/woopayments/payment-methods/), subject to availability in each country/region.

Yet, all of them appear to be displayed in the related drop-down, when creating a new order manually — not just the enabled ones.

That said, the plugin's primary purpose is to accept payments on the front-end, therefore, not sure how/if possible for this to be implemented in the back-end.

### Designs

Screenshots showcasing the current situation.

![l7Iyzw](https://github.com/Automattic/woocommerce-payments/assets/73900974/d7ba7ba2-eb1a-4439-8a66-cb0ec159878d)

![rqHADC](https://github.com/Automattic/woocommerce-payments/assets/73900974/9cb38d61-eac4-4212-81ab-eab43e8efe2a)

### Additional context

7910084-zen
https://wordpress.org/support/topic/all-payment-methods-showing-in-admin-drop-down/

#hc

**Comment by pierorocca** [comment]
Great catch. This is likely an oversight.

**Comment by gpressutto5** [comment]
This is not reproducible anymore:

![Image](https://github.com/user-attachments/assets/ff731565-93e1-4e49-81cb-10d404c83ba9)

![Image](https://github.com/user-attachments/assets/716a171b-0f7d-4237-9e9d-553e44f29f16)
