### ISSUE TITLE
Authenticate by `blog_id` instead of by user

### ISSUE THREAD

**Issue by allendav** [Automattic/woocommerce-payments#842]
- May? also need to stop using JETPACK_MASTER_USER as user_id here https://github.com/Automattic/woocommerce-payments/blob/ea0b251301bceadf3cced38b7e8fca97d478c5c6/includes/wc-payment-api/class-wc-payments-http.php#L59

p9dueE-1Gw-p2

Edit: 9/24/2020 p9dueE-1PK-p2

**Comment by allendav** [comment]
Assigning my best guess at size. Feel free to counter with a different size.

**Comment by v18** [comment]
Related: https://github.com/Automattic/woocommerce-payments/issues/111

A starting point on blog tokens: paJDYF-tL-p2

**Comment by DanReyLop** [comment]
Some more context about the Jetpack Userless Connection project: p1HpG7-a4a-p2

I don't think we necessarily need to wait for Jetpack to implement their changes though.

The big decision here is to select which requests will use the blog token (more robust but not associated with a person), and which ones will use the user token (more brittle, but associated with a person). A good first step would be to make all customer-facing requests (checkout) use the blog token. A good second step (IMHO) would be to use the blog token everywhere except for "critical" stuff like onboarding or getting to the Express Dashboard. In that case, we should make sure that the user performing the action is in fact the `JETPACK_MASTER_USER`, or else it would defeat the purpose of using user tokens at all.
