### ISSUE TITLE
Remove Incentive TOS link from APM task and settings

### ISSUE THREAD

**Issue by elizaan36** [Automattic/woocommerce-payments#8448]
### Describe the bug
Currently when the user onboards to WooPayments with the incentive applied, a link to 'Terms of service' appears within the fees pill. This is a bug considering that the Terms of service are accepted upon choosing "Finish setup" at the previous step on the connect page. The Terms links aren't required after that.

More context in @vladolaru 's comment, pbUcTB-447#comment-9272
> we need to show the specific T&C before a merchant takes us up on that offer and then provide a way to reference those terms for further consultation. We include this link clearly, before onboarding starts, on the Connect page – we are legally covered.

We also include the link in the Account details after the user has onboarded, so we're covered there.

### To Reproduce

1. Create a new site with WooPayments installed and go to 'Payments'
2. Click on 'Finish setup'
3. Complete WooPayments onboarding and verification
4. On the Payments Overview, see the "Set up additional payment methods" task and click on it.
5. In the setup wizard, see the "Terms" link in the fees pill for card payments.
6. Navigate to WooPayments Settings and see the "Terms" link also listed in the fees pill for Card payments.

### Actual behavior
The user accepts the terms on the Payments Connect screen, so additional links are not needed.
<img width="812" alt="Screenshot 2024-03-22 at 9 50 16 AM" src="https://github.com/Automattic/woocommerce-payments/assets/5121465/96130d4b-6795-48be-8996-06ebb48ac59d">

### Expected behavior
Terms links can be removed from these two places.

Set up additional payment methods task
<img width="3450" alt="Frame 1000005934" src="https://github.com/Automattic/woocommerce-payments/assets/5121465/4746701d-5fdd-4eec-8c93-348ce97c127f">

Settings > Payments > WooPayments
<img width="3444" alt="Frame 1000005935" src="https://github.com/Automattic/woocommerce-payments/assets/5121465/8768f000-24f8-44fb-87aa-52df3b6b331e">

cc @timmy5685

**Comment by vladolaru** [comment]
@elizaan36 As a future step, we could consider including discount information in the tooltip also, like so:

![Screenshot 2024-03-25 at 15 03 11](https://github.com/Automattic/woocommerce-payments/assets/8830539/2ca26e90-e946-4b8d-ba59-d3a46e3f3deb)

cc @rogermattic

**Comment by rogermattic** [comment]
Hey @vladolaru !
As I've mentioned  in my post on displaying the fees in the tooltips section: p6riRB-9T6 
This is the design proposal I shared:
![Help text popover](https://github.com/Automattic/woocommerce-payments/assets/94967682/6b3b9b82-befd-4f3a-b694-8f513b3f588f)
WDYT?

**Comment by vladolaru** [comment]
@rogermattic I like it. My ask was around what to do in the interim, before we have the new design for fees shipped.

Also, you should be aware that I stirred up this (https://github.com/Automattic/woocommerce-payments-server/issues/5000) around how discounts work (to what fees they should apply). That is one of the reasons I used an asterisk in https://github.com/Automattic/woocommerce-payments/issues/8448#issuecomment-2017965519.

**Comment by elizaan36** [comment]
@vladolaru What's blocking the team from implementing the new design that @rogermattic proposed?

**Comment by vladolaru** [comment]
@elizaan36 Do you mean implementing the fees details tooltip design shared above? As far as I am aware, that is part of a wider initiative around fees (p6riRB-9T6-p2), I don't know the product domain owning that, and it is not something currently on our roadmap. I'll let you and @timmy5685 align and open an issue for it.

**Comment by elizaan36** [comment]
Since it falls under the WooPayments settings I believe @pierorocca 's team is working on that area at the moment. Might be worth opening the separate issue and prioritizing it since it would make such a positive impact on the user experience. I don't think the tooltip update is dependent on the other improvements listed in the design post. @rogermattic What do you think?

**Comment by elizaan36** [comment]
Also, the Settings and APM task tooltips should align so might require cross team collaboration.

**Comment by pierorocca** [comment]
@rogermattic's new tooltip design is an awesome upgrade! Thanks for the ping Elizabeth. 

Priority - 100% focused on supporting anything related to the WooPayments merchant settings refresh and any pertinent effort on the top level, Payments Settings refresh. We will immediately begin working on those once they're ready to go as I expect those will have an order of magnitude more impact on funnel conversion and activation. Unless there's strong evidence the tooltip is impacting conversion and activation, there are high impact activities in the queue that would take precedence.

Related to the current state and any of it that carries over to the refreshed design, the discussion above triggered a few questions and insights:

1. The visible pricing in the pill doesn't quite communicate the promotional benefits like the fine print in the new tooltip. It's not as evident it's promo pricing, a positive benefit, imo. The discounted green badge found in the tooltip, would that be helpful to have in the pill?

2. Does the pricing revert after the promotional period ends and how does that manifest in the UI? Any notice to the merchant that the period is ending? Asking in case the merchant forgets about the promotion or timing and somehow thinks we're secretly increasing the pricing. How would a merchant react if one day the price was 2.61% and the next 2.9% and they didn't see or remember about the promo?

3. Question about mobile and touch screen laptop/tablet users, how might we improve the affordance of the tooltip for mobile users on the settings page? Same question for desktop users. We know we can hover or tap, does a user?
