### ISSUE TITLE
WooPayments post-onboarding enhancements to improve activation

### ISSUE THREAD

**Issue by elizaan36** [Automattic/woocommerce-payments#8449]
### Description
The current Payments Overview experience is overwhelming for the new user upon completing onboarding. There are three competing CTAs and announcements that aren't relevant to the user at this critical stage. We have a larger scope of work ongoing to provide better education for the new user post-onboarding (cc @pierorocca) 

These two small wins will improve the onboarding and activation experience for users immediately. It will facilitate merchant focus on the most important task of completing their store and payments setup.

### Acceptance criteria

* Change sandbox mode notice CTA to a text link.
* ~~Delay the appearance of the Fraud tools announcement for 3 days after connection.~~ There is another issue about this: https://github.com/Automattic/woocommerce-payments/issues/8279 

### Designs
<img width="2793" alt="Frame 1000005936" src="https://github.com/Automattic/woocommerce-payments/assets/5121465/9cf8fbf0-7d68-4ef2-aa90-b8d3c74b1e0e">

### Testing instructions

1. Create a new store and complete WooPayments onboarding and verification
2. See Payments Overview experience

cc @timmy5685

**Comment by vladolaru** [comment]
@elizaan36 I've removed the fraud banner requirements since those will be tackled by this issue (https://github.com/Automattic/woocommerce-payments/issues/8279) and in accordance with the conclusions of this discussion: p1712860760259209-slack-C01B8KNUYSW

**Comment by vladolaru** [comment]
@elizaan36 About the sandbox notice banner, I went one step further (https://github.com/Automattic/woocommerce-payments/pull/8631) and **included a help tooltip** with some information about sandbox mode and its benefits. I also moved the learn more documentation link in the tooltip:
![Screenshot 2024-04-12 at 13 27 47](https://github.com/Automattic/woocommerce-payments/assets/8830539/630b65c0-4c61-42dc-a4f7-9cf71cf23ec0)

Do let me know if something is off with this approach.

**Comment by elizaan36** [comment]
hey @vladolaru, I think the tooltip could work for additional information, but I wonder why this copy couldn't be included in the notice itself? A couple notes

- What is the experience on smaller screen sizes? Want to make sure the tooltip doesn't wrap in a strange way. 
- I'm not sure if the tooltip copy is clear. What does it mean that "Personal/business verifications are simulated"? "Find out what works best for you" is vague - are you referring to testing out different payment methods or other features? It's not clear what the goal/central message of the tooltip is.

Let me know and I can try to workshop the copy a bit.

**Comment by vladolaru** [comment]
@elizaan36 About including the copy in the notice itself, I was under the impression you were going for a one-liner notice to keep the visual surface reduced.

> I'm not sure if the tooltip copy is clear. What does it mean that "Personal/business verifications are simulated"? "Find out what works best for you" is vague - are you referring to testing out different payment methods or other features? It's not clear what the goal/central message of the tooltip is.

With the verifications copy, I am trying to be clear about _the current_ behavior: there are verifications, but they will all pass (aka simulated, not skipped). With the rest of the copy, I am trying to encourage folks to use sandbox mode to play with all the features and explore all the payment flows (checkout, processing orders, refunds, disputes, etc.) This is the goal of sandbox mode: gain access to all the features and test the store-wide integration of WooPayments.

> What is the experience on smaller screen sizes? Want to make sure the tooltip doesn't wrap in a strange way.

Here is how it looks on smaller screens:
![AJUAw7.png](https://github.com/Automattic/woocommerce-payments/assets/8830539/e71b2d6f-6451-4e29-b901-ef0a176df32b)
![O3nxX9.png](https://github.com/Automattic/woocommerce-payments/assets/8830539/bec1140e-e8ae-46ae-8bfb-f7acc8b260a0)

**Comment by elizaan36** [comment]
hey @vladolaru Here's an alternative for the copy. I think it communicates the same message in a more digestible format. We try to keep tooltips to 2-3 lines max for easier scanning. Do you need me to create a new issue for this?

<img width="587" alt="image" src="https://github.com/Automattic/woocommerce-payments/assets/5121465/acf64f94-0d8c-46a0-81fb-97e1c18e01ad">

**Comment by vladolaru** [comment]
No need for a separate issue @elizaan36. I've created this PR (https://github.com/Automattic/woocommerce-payments/pull/8848) to implement the new copy.

**Comment by elizaan36** [comment]
Great! Thank you, @vladolaru !
