### ISSUE TITLE
DevOps: fix WordPress.Security phpcs reports

### ISSUE THREAD

**Issue by vbelolapotkov** [Automattic/woocommerce-payments#8464]
Part of https://github.com/Automattic/woocommerce-payments/issues/8434

Check and fix reports in the following files:

* `bin/class-wcpay-changelog-formatter.php`
* `tests/unit/helpers/class-wc-helper-subscription.php`

**Comment by reykjalin** [comment]
@marcinbot @vbelolapotkov I think we can close this issue, yes?

**Comment by vbelolapotkov** [comment]
I'd expect so, but wondering why it didn't auto-close? I see that #8472 was merged into non-develop branch. @reykjalin do you know if the changes from this PR were finally shipped? I see that there was a revert, but got lost in the timeline.

**Comment by reykjalin** [comment]
The changes were shipped as part of #8460 , so I'll close this issue.
