### ISSUE TITLE
Payments: fix WordPress.Security phpcs reports

### ISSUE THREAD

**Issue by vbelolapotkov** [Automattic/woocommerce-payments#8465]
Part of https://github.com/Automattic/woocommerce-payments/issues/8434

Check and fix reports in the following files:

* `src/Container.php`
* `src/Internal/Payment/State/InitialState.php`
* `src/Internal/DependencyManagement/DelegateContainer/LegacyContainer.php`
* `includes/in-person-payments/class-wc-payments-in-person-payments-receipts-service.php`
* `src/Internal/Payment/State/StateFactory.php`
* `src/Internal/DependencyManagement/ExtendedContainer.php`
* `src/Internal/Proxy/LegacyProxy.php`
* `src/Internal/Service/MinimumAmountService.php`
* `src/Internal/Service/OrderService.php`
* `src/Internal/Payment/PaymentRequest.php`
* `src/Internal/Payment/State/AbstractPaymentState.php`
* `includes/core/server/class-request.php`
* `includes/class-payment-information.php`
* `includes/core/server/request/class-create-and-confirm-setup-intention.php`
* `includes/class-wc-payments-order-service.php`
* `includes/class-wc-payments-status.php`

**Comment by nagpai** [comment]
Sorry about the noisy references above. I tagged the wrong issue number in my PR. 🙏

**Comment by zmaglica** [comment]
This issue is addressed in https://github.com/Automattic/woocommerce-payments/pull/8509
