### ISSUE TITLE
Multi-currency: fix WordPress.Security phpcs reports

### ISSUE THREAD

**Issue by vbelolapotkov** [Automattic/woocommerce-payments#8468]
Part of https://github.com/Automattic/woocommerce-payments/issues/8434

Check and fix reports in the following files:

* `includes/multi-currency/MultiCurrency.php`

**Comment by dwainm** [comment]
Confirmed that there are no issues here. Some items are run through our own customer escape function, and the others are for string literals used with the error_code when throwing an exception.
