### ISSUE TITLE
Epic: Show payment activity widget  with payment volumes for Custom period selected by the user using Calendar input.

### ISSUE THREAD

**Issue by haszari** [Automattic/woocommerce-payments#8483]
- All tiles should update when the time selection is changed.
- Calendar input should update with time selection presets.

This may require a new component for selecting the time period. 

![Image](https://github.com/Automattic/woocommerce-payments/assets/4167300/79993978-9e42-4e2b-a998-4f83eef6984e)

**Comment by haszari** [comment]
Removing estimate of 4 SP, I suspect we need to revisit this to account for the new date picker component. FYI @jessy-p

**Comment by jessy-p** [comment]
Closing this issue as it is descoped from this phase of the project p1717572623138709/1717556630.331739-slack-C06BBFTF6EM
