### ISSUE TITLE
Epic: Show the Refunds tile on the Payment Activity widget for the store’s primary currency and last 7 days

### ISSUE THREAD

**Issue by jessy-p** [Automattic/woocommerce-payments#8487]
On click of the tile, redirects to Transactions page filtered by date for type Refunds. This click is recorded by track - track event name TBD

Refunds amount should be shown as a positive value as per discussion: pdjTHR-3DQ-p2#comment-4966

```[tasklist]
### Tasks
- [ ] https://github.com/Automattic/woocommerce-payments/issues/8748
```

**Comment by nagpai** [comment]
Task #8595 - Includes adding UI for the Refunds tile . This task is already included in Epic #8484 , hence not added as a task here.

**Comment by nagpai** [comment]
Task #8511 - Added tooltips to all tiles including `Refunds`

#8519 - Fetched actual data to each tile including `Refunds`

These tasks are tracked under Epic - #8484

**Comment by Jinksi** [comment]
Added note: Refunds amount should be shown as a positive value as per discussion: pdjTHR-3DQ-p2#comment-4966

**Comment by jessy-p** [comment]
Removed #8702 to #8740

**Comment by jessy-p** [comment]
Pending on #8687 (Tracks)

**Comment by Jinksi** [comment]
I've added #8748 as a sub-task, since it was a missed requirement of this epic.
