### ISSUE TITLE
Epic: Show the Disputes tile on the Payment Activity widget for the store’s primary currency and last 7 days

### ISSUE THREAD

**Issue by jessy-p** [Automattic/woocommerce-payments#8488]
On click of the tile, redirects to Disputes page filtered by date (last 7 days). This click is recorded by track - track event name TBD

Disputes amount should be shown as a positive value as per discussion: pdjTHR-3DQ-p2#comment-4966

```[tasklist]
### Tasks
- [ ] https://github.com/Automattic/woocommerce-payments/issues/8748
```

**Comment by nagpai** [comment]
Task #8595 - Includes adding UI for the Disputes tile . This task is already included in Epic #8484 , hence not added as a task here.

**Comment by nagpai** [comment]
Task #8511 - Added tooltips to all tiles, including `Disputes`

#8519 - Fetched actual data to each tile, including `Disputes`

These tasks are tracked under Epic - #8484

**Comment by Jinksi** [comment]
Added note: Disputes amount should be shown as a positive value as per discussion: pdjTHR-3DQ-p2#comment-4966

**Comment by jessy-p** [comment]
Removed #8704  to #8740

**Comment by jessy-p** [comment]
This issue is pending on #8687  (Tracks)

**Comment by Jinksi** [comment]
I've added #8748 as a sub-task, since it was a missed requirement of this epic.
