### ISSUE TITLE
Epic: Show the Fees tile on the Payment Activity widget for the store’s primary currency and last 7 days

### ISSUE THREAD

**Issue by jessy-p** [Automattic/woocommerce-payments#8489]
Fees amount should be shown as a positive value as per discussion: pdjTHR-3DQ-p2#comment-4966

**Comment by nagpai** [comment]
Task #8595 - Includes adding UI for the Fees tile . This task is already included in Epic #8484 , hence not added as a task here.

**Comment by nagpai** [comment]
Task https://github.com/Automattic/woocommerce-payments/issues/8511 - Added tooltips to all tiles, including `Fees`

https://github.com/Automattic/woocommerce-payments/issues/8519 - Fetched actual data to each tile, including `Fees`

These tasks are tracked under Epic - https://github.com/Automattic/woocommerce-payments/issues/8484

**Comment by Jinksi** [comment]
Added note: Fees amount should be shown as a positive value as per discussion: pdjTHR-3DQ-p2#comment-4966
