### ISSUE TITLE
Epic: Empty state screen if no payments in this time period or currency

### ISSUE THREAD

**Issue by jessy-p** [Automattic/woocommerce-payments#8492]

**Comment by shendy-a8c** [comment]
Since per p6riRB-9OY-p2#comment-10564, empty state should just display zeroes, as of now, it's already doing that:

![Screenshot 2024-04-18 at 15 15 54](https://github.com/Automattic/woocommerce-payments/assets/73803630/6c8467b5-0e63-40f9-819d-6895a179b3cb)

So, closing.
