### ISSUE TITLE
E2E test for Bancontact failing

### ISSUE THREAD

**Issue by jessy-p** [Automattic/woocommerce-payments#8495]
### Description
E2E test related to Bancontact is failing

**Output from the test failure**:
```
  console.warn
      [Stripe.js] The following payment method types are not activated:
      
      - bancontact
      
      They will be displayed in test mode, but hidden in live mode. Please activate the payment method types in your dashboard (https://dashboard.stripe.com/settings/payment_methods) and ensure your account is enabled for any preview features that you are trying to use.
```
### Additional context
Runs during release 7.4.0:
- https://github.com/Automattic/woocommerce-payments/actions/runs/8447754862/job/23138683068
- https://github.com/Automattic/woocommerce-payments/actions/runs/8447754862/job/23139092934

> [!Important]
> Please, ensure when closing this issue (PR fix) that only one `e2e: broken` label is added and it is accurate.
> - [x] I confirmed there's only one `e2e: broken` label in this issue and it is accurate.

**Comment by cesarcosta99** [comment]
I think this isn't related to Bancontact at all, even though we see these warnings. It's likely the run stopped abruptly for other reason as we don't see any `FAIL` message.

[In the latest run](https://github.com/Automattic/woocommerce-payments/actions/runs/8472540256/job/23214858441), for instance, we see the same warnings, but what actually failed were a couple tests related to Klarna and the shopper's payment methods in the My Account page. I'm going to open separate issues for them.

My suggestion would be closing this issue, or repurposing it, unless we have evidence this behavior is consistent.

---

Update: the issue in the Klarna checkout tests is reported in #8416.

**Comment by vbelolapotkov** [comment]
Ok, closing this one.
