### ISSUE TITLE
Admin merchant progressive onboarding tests fails

### ISSUE THREAD

**Issue by oaratovskyi** [Automattic/woocommerce-payments#8496]
### Description
Progressive onboarding flow `should pass merchant flow without any errors` fails due to outdated test 

**Output from the test failure**:
```
FAIL tests/e2e/specs/wcpay/merchant/merchant-progressive-onboarding.spec.js (17.705 s)
  Admin merchant progressive onboarding
    ✕ should pass merchant flow without any errors (7931 ms)

  ● Admin merchant progressive onboarding › should pass merchant flow without any errors

    TimeoutError: Element h1.stepper__heading (text: "First, you’ll need to create an account") not found
```

### Additional context
None

### Priority
Low. Since the PO/MOX flow is much thinner than it was.

### Reason why this e2e test is broken
The test is broken because it's failure wasn't tracked before 7.4 release. Since executing e2e tests is not a part of the PR anymore, it become harder to track the errors.

> [!Important]
> Please, ensure when closing this issue (PR fix) that only one `e2e: broken` label is added and it is accurate.
> - [ ] I confirmed there's only one `e2e: broken` label in this issue and it is accurate.

**Comment by oaratovskyi** [comment]
was fixed in https://github.com/Automattic/woocommerce-payments/pull/8508
thanks @vladolaru !

**Comment by vladolaru** [comment]
Oh! Didn't know there was an issue for it. Linking in the PR.
