### ISSUE TITLE
Error on JN site when using Google Pay with subscription

### ISSUE THREAD

**Issue by timur27** [Automattic/woocommerce-payments#8499]
### Describe the bug
The below behavior happens when attempting to pay for a subscription on Blocks checkout and in a JN store. We weren't able to reproduce the same behavior on a local setup.

<img width="1371" alt="image" src="https://github.com/Automattic/woocommerce-payments/assets/22319444/fb766926-d36f-4e8a-a9ce-bba47a35a782">

### To Reproduce
* Create a subscription with a sign-up fee
* Log out from the store
* Add subscription to the cart, navigate to Blocks checkout
* Click GPay button and observe the error

### Additional context
From a very quick scan, the error seems to be coming from https://github.com/Automattic/woocommerce-payments/blob/develop/client/payment-request/blocks/use-initialization.js#L88.

**Comment by zmaglica** [comment]
@timur27 Could this be regarding the 402 status code? Do you maybe know does payment fails?

**Comment by timur27** [comment]
@zmaglica sorry for not being clear enough: the error happens before the Google Pay modal window, so there is no payment attempt at this stage.
