### ISSUE TITLE
Fetch data for TotalPaymentsActivity component

### ISSUE THREAD

**Issue by naman03malhotra** [Automattic/woocommerce-payments#8518]

**Comment by zmaglica** [comment]
@naman03malhotra Could you please fill issue description and apply labels if you can, so we can triage it? Thank you in advance.

**Comment by naman03malhotra** [comment]
Hey Zvonimir, thanks for the ping, sorry I missed adding the labels. I've added it now.

**Comment by shendy-a8c** [comment]
Looks like this is a duplicate of https://github.com/Automattic/woocommerce-payments/issues/8519. Closing. Let me know if that's not the case, @naman03malhotra .

**Comment by naman03malhotra** [comment]
You are right shendy, I missed closing it when I meged the PR.
