### ISSUE TITLE
CSV exports have date/time in UTC, not clear to merchant (vs. localised timezone) (all – e.g. Transactions, Disputes, Deposits)

### ISSUE THREAD

**Issue by brucealdridge** [Automattic/woocommerce-payments#8522]
### Describe the bug

When exporting a CSV of Transactions, Disputes, or Deposits, the date time columns are shown in UTC but this is not communicated.

Times are shown in local time when viewing the transactions, disputes, or deposits pages. For both the plugin and server-generated CSV exports, UTC is used.

A simple fix would be to label the column in the CSV exports as UTC.

### To Reproduce

1. Go to Payments > Transactions
2. See dates/times in local time.
3. Download as a CSV
4. See dates/times in UTC.

**Comment by haszari** [comment]
Labelling as high since it's misleading.

**Comment by haszari** [comment]
> When exporting a CSV of Transactions, Disputes, or Deposits, the date time columns are shown in UTC but this is not communicated.

> Times are shown in local time when viewing the transactions, disputes, or deposits pages. _For both the plugin and server-generated CSV exports, UTC is used_.

@brucealdridge can you clarify something for me – are **all CSV exports using UTC now**? There are other issues open for specific CSVs with inconsistent timezone (UTC or localised, depending on where the CSV was generated). 

If we **are** consistently UTC then these issues might not be relevant: ✨ 

- https://github.com/Automattic/woocommerce-payments-server/issues/2847
- https://github.com/Automattic/woocommerce-payments-server/issues/4845

**Comment by haszari** [comment]
We will need to change this label (UTC) on both server and plugin client, so will likely require a client issue + PR also (that scope is included in this issue + estimate).

**Comment by brucealdridge** [comment]
> can you clarify something for me – are all CSV exports using UTC now

Based on a cursory look, it appears so. 

TBH it looks like we need a spike to confirm the current state of the three list pages, the exports (client and server-generated.) Then confirm what should be shown in each case, including date formating as this is also inconsistent.

**Comment by nagpai** [comment]
I am assigning this to myself since @shendy-a8c  is AFK and Maintenance is my sprint focus.
