### ISSUE TITLE
Store currency inherits all default currency options except decimal separator when multi-currency is enabled

### ISSUE THREAD

**Issue by csmcneill** [Automattic/woocommerce-payments#8559]
### Describe the bug

When WooPayments multi-currency is enabled, the store's default currency will inherit the (1) default thousands separator, (2) currency position, and (3) number of decimals from the WooCommerce currency settings at WooCommerce > Settings > General — but not the decimal separator.

Using PLN as an example, it uses the following standards by default:
- A space (` `) for the thousands separator
- A comma (`,`) for the decimal separator
- A currency position of `Right with space` 
- Two decimal places

As a result, something that is one thousand PLN will display as `1 000,00 zł`.

#### 1. Thousands separator

If a site’s default currency is set to PLN and both separators are set to ` `, the currency will appear as `1 000,00 zł`. However, if both are set to `'`, then it will appear as `1’000,00 zł`.

In turn, if the store’s default currency is set to PLN with the thousands separator as `,` and the decimal separator set to `.`, the currency will appear as `1,000,00 zł`, which can inadvertently trigger https://github.com/woocommerce/woocommerce/issues/46045

If the default currency is **not** PLN, but a customer pays in PLN via the WooPayments multi-currency functionality, prices will display in the standard format (e.g., `1 000,00 zł`) and not interface with any of the Core currency options.

#### 2. Currency position

If a site's default currency is set to PLN and the currency position is set to `Left`, the currency position will follow that setting (e.g., `zł1 000,00`). However, the standard for PLN is to have a `Right with space` currency position.

If the default currency is **not** PLN, but a customer pays in PLN via the WooPayments multi-currency functionality, prices will display in the standard format (e.g., `1 000,00 zł`) and not interface with any of the Core currency options.

#### 3. Number of decimals

If a site's default currency is set to PLN and the number of decimals is set to something other than `2`, this option will show for customers paying in PLN (e.g., six decimal places will show as `1 000,000000 zł`)

If the default currency is **not** PLN, but a customer pays in PLN via the WooPayments multi-currency functionality, prices will display in the standard format (e.g., `1 000,00 zł`) and not interface with any of the Core currency options.

### To Reproduce

1. Enable multi-currency
2. Change the store's currency to one whose format you are familiar with 
3. Modify the other currency options so that they are non-standard, such as:
- Change the currency position to `Left`
- Change the thousands separator to `'`
- Change the decimal separator to `'`
- Change the number of decimals to `6`
4. Save your settings.
5. Change your presentment currency to match the site's default
6. Add enough product to your cart to increase the value so that a thousands separator is displayed
7. Note that the currency position, thousands separator, and number of decimals match the settings configured in step 3 — but not the decimal separator.
8. Change the presentment currency
9. Note that the currency position, thousands separator, number of decimals, and decimal separator do not inherit any of the settings configured in step 3
10. Disable multi-currency
11. Refresh the cart page
12. The presentment currency now matches all of the settings configured in step 3

### Actual behavior

When multi-currency is enabled, it creates inconsistent formatting for the site's default currency.

### Screenshots

---
![CleanShot 2024-04-02 at 10 33 56](https://github.com/Automattic/woocommerce-payments/assets/82999806/6ae83e85-bf26-4392-aedd-b909a71f9c55)
---
![CleanShot 2024-04-02 at 10 34 25](https://github.com/Automattic/woocommerce-payments/assets/82999806/31e9b7bc-a4fa-4f1c-b8d6-7b04e3dc8ac3)
---
![CleanShot 2024-04-02 at 10 35 27](https://github.com/Automattic/woocommerce-payments/assets/82999806/803d4318-796c-4ab1-83c4-1f29356d01a1)
---
![CleanShot 2024-04-02 at 10 36 08](https://github.com/Automattic/woocommerce-payments/assets/82999806/470644c8-39bd-431f-8b16-9e61894ae950)
---
### Expected behavior

Either:
1. Multi-currency overwrites _all_ of the currency options for the site's default currency.
2. Multi-currency doesn't overwrite the decimal separator currency option for the site's default currency.

### Additional context

p1711621558983609-slack-C02TS23QJ1X

**Comment by cat-og** [comment]
Ran into this issue today in 7980072-zd-a8c. As indicated above, this did also trigger the related issue; https://github.com/woocommerce/woocommerce/issues/46045 because their thousands separator was set to use a comma in their settings. 

To get around this on their site, they have updated the thousands separator to use another symbol, but they would like to be updated when this is resolved so they can set that back to use a comma again.

**Comment by spraveenitpro** [comment]
another 7995098-zen

**Comment by bborman22** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Fractal-62a0f7b955648b001e1f5e1f/issues/Automattic/woocommerce-payments/8559?planning-poker) with Zenhub @cesarcosta99 @lovo-h @rafaelzaleski @reykjalin @ricardo

**Comment by simranvijwani** [comment]
Another report: 8002243-zd-a8c

User is getting error on the shop page. I tried disabling the multicurrency, but it didn't help resolve the issue. 

<img width="730" alt="image" src="https://github.com/Automattic/woocommerce-payments/assets/34896144/46ca4604-4a17-48ab-8b69-ac45b3133c97">

![image](https://github.com/Automattic/woocommerce-payments/assets/34896144/9ddfc13d-e0f3-41f6-95a0-d04f30bdac62)
