### ISSUE TITLE
Updates to payment icons on Payments Connect screen

### ISSUE THREAD

**Issue by elizaan36** [Automattic/woocommerce-payments#8567]
### Describe the bug

Two updates to the payment icons on the Payments Connect screen.
✅ Remove duplicate WooPay logo [Will be fixed in another issue]
- Replace Sofort with Klarna icon [per this thread](https://github.com/Automattic/woocommerce-payments/pull/8378#issuecomment-2027588380)
- Replace Afterpay icon with green version per brand guidelines

Small note - Can we remove the period after "& more"? It's not necessary as it's not a complete sentence.

### To Reproduce

1. Create a new store with WooPayments installed and activated
2. Go to the Payments Connect screen
3. See payment icons

### Expected behavior
Here's a mockup of the correct icon layout.

<img width="638" alt="image" src="https://github.com/Automattic/woocommerce-payments/assets/5121465/623b2d35-ee20-4176-8f95-fffae698ebe9">

cc @anu-rock

**Comment by csmcneill** [comment]
The duplicate WooPay icon was reported in #8505 and may be resolved by #8521

**Comment by elizaan36** [comment]
I updated the original comment to mention that the WooPay icon is being fixed and added the replacement for the Afterpay icon. I'm noting here that there are two additional placements of the payment icons that will need to be updated in WooCommerce core, the Set up payments task, and the Payments Settings banner. 

<img width="1365" alt="Screenshot 2024-04-03 at 8 53 11 PM" src="https://github.com/Automattic/woocommerce-payments/assets/5121465/7b063ce8-edec-441c-aca5-38f5f10feae8">
<img width="1828" alt="Screenshot 2024-04-03 at 12 26 53 PM" src="https://github.com/Automattic/woocommerce-payments/assets/5121465/a0ca83f6-7441-4a22-939a-f6f758e4750e">

@nikkivias and I are discussing a shared component for the payment icons that can stay consistent throughout all placements, mobile/ desktop versions, and only needs to be updated in one place. @pierorocca Would that work land with your teams or with Moltres, so we know who to collaborate with on this.

**Comment by pierorocca** [comment]
A couple more callouts. The Discover and Diners logos are outdated. Attached are samples from [Discover's brand guidelines](https://www.discoversignage.com/uploads/09-12-21_03:59_DGN_BG_10052021_AccMk.pdf).

Downloadable assets - https://discover.widen.net/s/rtwc682nvd/discover-global-network-acceptance-mark-2
https://www.discoversignage.com/free-signage-logos/

Preview- 
![image](https://github.com/Automattic/woocommerce-payments/assets/109928953/beeb71eb-0332-4368-b268-b3a259867c49)

**Comment by csmcneill** [comment]
@pierorocca @elizaan36 Since this PR is closed, I opened #8580 to tackle the Discover/Diners changes :)
