### ISSUE TITLE
Switch URLs from woo.com to woocommerce.com

### ISSUE THREAD

**Issue by vladolaru** [Automattic/woocommerce-payments#8573]
### Description

We are switching back to using the `woocommerce.com` domain instead of the current `woo.com` one. All URLs should reflect this change, even if there will be redirects in place.

### Acceptance criteria

* All URLs using `woo.com `should be using `woocommerce.com`

### Dev context
The PR that handled the previous domain switch: https://github.com/Automattic/woocommerce-payments/pull/7643

### Additional context
p6q6po-fKm-p2
paqDfi-9z5-p2

**Comment by vbelolapotkov** [comment]
@anu-rock could you please take care of that, asking because your team handled the switch to woo.com.

**Comment by vladolaru** [comment]
Already took care of it @vbelolapotkov through https://github.com/Automattic/woocommerce-payments/pull/8574
