### ISSUE TITLE
Remove BNPL options from payments in core to prevent duplication

### ISSUE THREAD

**Issue by elizaan36** [Automattic/woocommerce-payments#8578]
### Describe the bug
As part of the initiative to solve the persistence of duplicate payment methods on WooCommerce stores, we need to remove the prompt to install separate extensions that could contribute to the duplication from the payments in core screen.

### To Reproduce

1. Create a new JN site with WooCommerce
2. Go to the Payments item in the navigation
3. See prompt to install BNPL options in the list

### Actual behavior
Prompts to install the BNPL option Klarna appears in the list below the switcher incentive. This is misleading to merchants as it implies that a separate extension is required to enable BNPL options, while the functionality is available within WooPayments.

<img width="1784" alt="Screenshot 2024-04-04 at 10 54 28 AM" src="https://github.com/Automattic/woocommerce-payments/assets/5121465/c74bbd20-df02-4263-b306-f90e598be8a0">

### Expected behavior
In addition to removal of the Klarna option from this screen, we can update the payment icon row to the indicate the correct offerings in line with brand guidelines.

<img width="1440" alt="Payments Welcome" src="https://github.com/Automattic/woocommerce-payments/assets/5121465/5418a02a-e911-47dc-a478-29a97ae3a207">

cc @pierorocca @timmy5685 @anu-rock Note that this is an interim update to this screen. There are longer term explorations to improve the design and messaging overall.

**Comment by anu-rock** [comment]
> Prompts to install the BNPL option Klarna appears in the list below the switcher incentive. This is misleading to merchants as it implies that a separate extension is required to enable BNPL options, while the functionality is available within WooPayments.

@elizaan36 Wow, I had the exact thought just a few days ago while testing a freshly baked JN site. Thanks for reporting this and offering your suggestion.

> In addition to removal of the Klarna option from this screen, we can update the payment icon row to the indicate the correct offerings in line with brand guidelines.

Could you clarify what "correct offerings" means here? The only difference I see in the second screenshot is the blue box that says "Installing WooCommerce Payments..."

**Comment by vladolaru** [comment]
> Could you clarify what "correct offerings" means here? The only difference I see in the second screenshot is the blue box that says "Installing WooCommerce Payments..."

@anu-rock They should be the same as the ones on the new Payments Connect page (https://github.com/Automattic/woocommerce-payments/issues/8567)

**Comment by vladolaru** [comment]
@elizaan36 FYI, I've pinged Payments Partnerships here: p1712749196233489-slack-CSPAQH38F

**Comment by elizaan36** [comment]
> Could you clarify what "correct offerings" means here?

@anu-rock, Yes I meant the update to the payment icons here! There were recent additions plus some tweaks to comply with brand guidelines.

Thanks @vladolaru
