### ISSUE TITLE
Update Discover and Diners logos on connect page and elsewhere

### ISSUE THREAD

**Issue by csmcneill** [Automattic/woocommerce-payments#8580]
### Describe the bug

The Discover and Diners logos are outdated. 

- [Discover's brand guidelines](https://www.discoversignage.com/uploads/09-12-21_03:59_DGN_BG_10052021_AccMk.pdf).
- [Downloadable assets](https://discover.widen.net/s/rtwc682nvd/discover-global-network-acceptance-mark-2
https://www.discoversignage.com/free-signage-logos/)

### To Reproduce

1. Onboard with WooPayments
2. Note that the Discover and Diners logos are out of date.

### Screenshots

Preview- 
![image](https://github.com/Automattic/woocommerce-payments/assets/109928953/beeb71eb-0332-4368-b268-b3a259867c49)

### Expected behavior

Discover and Diners logos are updated to adhere to updated brand guidelines.

### Additional context

Pulled from https://github.com/Automattic/woocommerce-payments/issues/8567#issuecomment-2037696756

**Comment by pierorocca** [comment]
One suggestion sparked by your comment @csmcneill - Diners Club is super niche and limited to corporate travellers. As an online acceptance mark it's irrelevant imo. We're only seeing a few thousand TPV per month on Diners. I'd recommend swapping it out with iDeal or Bancontact which are seeing much more charge volume.

**Comment by mordeth** [comment]
After discussing the replacement of the Diners Club logo with @pierorocca and @csmcneill, we have decided to replace it with the more popular iDeal logo.
