### ISSUE TITLE
[Task] Add a basic UI for data tiles - Total payment volume, charges, refunds, disputes and fees

### ISSUE THREAD

**Issue by nagpai** [Automattic/woocommerce-payments#8595]
Replicate the visual design of the Payment activity widget MVP. 

![image](https://github.com/Automattic/woocommerce-payments/assets/4162931/e3476bb7-dfb7-42e4-9934-487758b60641)

### In the scope:
* Reusable component for each of the data tiles
* Payment widget layout using these tiles with correct proportions for desktop and mobile view
* Links on each tile leading to the respective report page
* Placeholders only for currency and amounts
* Basic tooltip placeholders

### Outside scope for the issue
* Detailed contents of the tooltips
* Adding of track events 
* Getting the actual data for each of the tiles. 
* Date filters on the linked report page.

**Comment by Jinksi** [comment]
Is this issue part of an Epic? I'm wondering if we should zero-out the story-point value.

Perhaps it is related to all of these.

![Image](https://github.com/Automattic/woocommerce-payments/assets/3147296/6036e0e6-0887-4f60-bf63-ac0b333c39d2)

**Comment by haszari** [comment]
> Is this issue part of an Epic?

I was wondering the same thing, @nagpai please ensure this issue is linked to one of the project epics. 

If it's appropriate to implement all those epics with one issue then I have no objections – maybe we broke down the epics too small. Unless this PR/issue is "greedy" and should broken up into smaller PRs. (Musing, I have no opinions either way.)

**Comment by nagpai** [comment]
@haszari , @Jinksi , I think this issue relates as one of the two major tasks for each of these Epics. That is to add a UI. The second part which it does not include is to show the actual data for  last 7 days.  I think @naman03malhotra is close to getting that done. 

For the UI, i found the components too similar and hence added it via same issue + PR.  For fetching the data things maybe different. 

Is it possible to add this issue as the first task for each of the epics?  and then have the data part as the next task? 

My apologies for not thinking through this clearly earlier.

**Comment by haszari** [comment]
@nagpai let's discuss this as a team, this would ideally be discussed as part of story pointing and aligning on epics. In future I'd suggest trying to align more closely with the epics, or work with the team to change the epics if needed.

**Comment by nagpai** [comment]
Based on the discussion we had today at our sync hangout:

1. The task here has been linked to the first larger Epic - #8484 
2. Comments have been added on the other epics related to `Charges`, `Refunds`, `Disputes` and `Fees` , shared by @Jinksi earlier. 
3. The SP on this task is marked as 0 correctly, since it is accounted within the Epic.
