### ISSUE TITLE
Overview > Balances card should show balances in stacked layout on mobile

### ISSUE THREAD

**Issue by nagpai** [Automattic/woocommerce-payments#8599]
The `Balance` widget in the overview page, currently shows `Total balance` and  `Available funds` side-by-side on desktop as well as mobile view. 

<img src='https://github.com/Automattic/woocommerce-payments/assets/4162931/03b253da-e5d8-4887-b156-feb24765a019' width='550' />

 On mobile screen, we would want this one below the other. 

### To Reproduce

1. Browse to `Payments` section in admin
2. Check how the `Balance` widget currently appears

### Additional context

The responsive behavior improvement for the Balances tiles was recommended by design - @rogermattic , to make it consistent with the mobile view of the payment activity widget tiles. 

p1712249591796559/1712130711.969139-slack-C06BBFTF6EM

Props - @rogermattic 
### Design mockups

<img width="1798" alt="Mobile views" src="https://github.com/Automattic/woocommerce-payments/assets/94967682/447ef755-e927-42f0-b906-717fe722825b">

**Comment by haszari** [comment]
Upgrading this to `medium` and adding to current sprint. This will make WooPayments better on mobile and should be relatively straightforward – quick win!

> p1712249591796559/1712130711.969139-slack-C06BBFTF6EM

@nagpai could you add anything relevant from that slack link inline? E.g. where did this enhancement originate, is it follow up to a project/issue, general design feedback or reported by a merchant/support?

**Comment by brucealdridge** [comment]
FYI: In the mobile app these are side-by-side. Not sure if we want consistency here.


![Image](https://github.com/user-attachments/assets/69907fc8-47bf-47e1-a22e-b911157148ee)

Sidenote: Mobile app shows Pending/Available funds and there is an issue open for this https://github.com/woocommerce/woocommerce-ios/issues/13206

**Comment by nagpai** [comment]
The design has changed slightly from the screenshots in the main message. We have moved the currency selector outside the account balances box . Hence the final outcome of the PR would be slightly different visually.
