### ISSUE TITLE
Distinguish between "unit" and "integration" tests

### ISSUE THREAD

**Issue by jrodger** [Automattic/woocommerce-payments#86]
Currently, all our unit tests require a WordPress DB to execute. There are unit tests that don't actually need it, but one is setup anyway thanks to the test bootstrapping.

So that our tests run fast, and to promote good coding practices, it would be nice to be able to run those unit tests that don't need it without this bootstrapping.

Any tests that still require it can still be run with PHPUnit, but we might consider moving them to an "integration" tests folder.

**Comment by jessy-p** [comment]
Moving to the Ready for Prioritisation queue because the problem statement is clear.

**Comment by jessy-p** [comment]
As discussed in Prioritization call with MattD, closing for now as this will be addressed in WooPayments client refactoring.
