### ISSUE TITLE
Remove BNPL options in WooCommerce core > Additional payments options

### ISSUE THREAD

**Issue by vladolaru** [Automattic/woocommerce-payments#8603]
### Description
In line with this issue (https://github.com/Automattic/woocommerce-payments/issues/8578) related to the WooPayments Connect-in-core page, we should not show options that WooPayments already provides when merchants click on the `Set up additional payment options` task list.

![Screenshot 2024-04-09 at 16 47 34](https://github.com/Automattic/woocommerce-payments/assets/8830539/05c6d633-5585-4c59-8000-7e68fda5b05b)

### Acceptance criteria

* If WooPayments is set up (an account is connected), don't show on the Set up additional payment options page (`/wp-admin/admin.php?page=wc-admin&task=payments`) BNPL options that are already provided by WooPayments.

### Designs
cc @elizaan36 if more design work is needed

### Testing instructions

1. Make sure you have WooPayments set up with a connected account
2. Click on the `Set up additional payment options` task item in the `Things to do next` list of the WooCommerce home page
3. There should not be BNPL options provided by WooPayments (in the Payments > Settings page), regardless if they are enabled or not.

### Dev notes
We should be informed by the actual capabilities of the connected merchant account, the same way the Payments > Settings page is. This would make our logic resilient to various per-country payment options. This would also require us to dynamically parse the list of recommended additional payments options shown in the WC core page.

### Additional context
https://github.com/Automattic/woocommerce-payments/issues/8578

cc @pierorocca @timmy5685 @anu-rock

**Comment by pierorocca** [comment]
To double check, has anyone reached out to Partnerships in case those placements are tied to commercial agreements? Would be good due diligence to conduct.

**Comment by vladolaru** [comment]
@pierorocca I've pinged Payments Partnerships here: p1712749196233489-slack-CSPAQH38F

**Comment by pierorocca** [comment]
Nice @vladolaru. Looks like a healthy discussion got triggered. :)

**Comment by anu-rock** [comment]
@vladolaru Is this something we are still pursuing? Looks like the discussion on Slack has stalled.

**Comment by vladolaru** [comment]
I don't have any update about it. Maybe @timmy5685 has an update about it.

**Comment by timmy5685** [comment]
@anu-rock - catching up on this thread. Just followed up on slack to summarize what I think I understand to get final confirmation from the team. Standby.

**Comment by elizaan36** [comment]
> as long as it is overtly clear to the merchant that one or all of the additional payment methods (BNPLs) are available (but not enabled) or  already enabled within WooPayments, then you can remove the duplication. 

Building off Web's comment in Slack, we could potentially direct people through the WooPayments APM setup from this core task as well.

Here are a couple options. Copy TBD, just to illustrate the concept. Let me know what you think.

1.
<img width="1440" alt="Payments _ WooCommerce Payments 1" src="https://github.com/Automattic/woocommerce-payments/assets/5121465/1c21a7ce-3394-44b6-978e-a494d84c1912">

2. 
<img width="1440" alt="Payments _ WooCommerce Payments 2" src="https://github.com/Automattic/woocommerce-payments/assets/5121465/ddeb6ab3-7838-4bdf-93d0-2b012a660e17">

**Comment by anu-rock** [comment]
I like how @elizaan36's Option 1 above hits two targets with one rock - remove confusion related to BNPLs and make WooPayments the very obvious pick (I have to say that banner is quite attractive 😄).

**Comment by pierorocca** [comment]
In both options, I'm not clear why any WooPayments payment methods would be in this flow. I'd expect WooPayments payment methods to only be within an amazing WooPayments flow.

**Comment by timmy5685** [comment]
@elizaan36 - similar to unsupported countries - let's include this in our overall onboarding review!

**Comment by vladolaru** [comment]
Great ideas, @elizaan36! For clarity, those WooPayments tiles will appear when WooPayments is already activated and properly onboarded, linking to the WooPayments Payments > Settings page, right?

**Comment by elizaan36** [comment]
> those WooPayments tiles will appear when WooPayments is already activated and properly onboarded

Thanks @vladolaru. Correct, these tiles only appear once WooPayments is connected and enabled and the user makes their way back to the "Set up additional payments" task on _Woo Home_.

> linking to the WooPayments Payments > Settings page, right?

The thinking is that the tiles would replicate the behavior of the "Set up additional payments" task that appears only on the _Payments Overview_. It currently leads to the guided payment method setup.

<img width="1440" alt="New merchants - Enable local payment methods" src="https://github.com/Automattic/woocommerce-payments/assets/5121465/2e9a6a15-f5ab-4d85-8f7b-cb5082b59969">

If we decide in the future to remove the guided setup the tasks would lead to settings.

@timmy5685, Orcun and I are taking a look at the overall onboarding review and will include this path.

**Comment by anu-rock** [comment]
@elizaan36 I saw in pe69sR-1ot-p2#comment-1095 that this issue is ready for engineering. Confirming it is no longer blocked and we can pull it in an upcoming sprint?

**Comment by elizaan36** [comment]
I'd confirm with @timmy5685 but I think this should be done relatively soon because it solves a usability issue with confusion on duplicate payment methods. 

The only thing I'd like to do is align the visual design and messaging with @orcunomattic 's latest work in pfHfG4-cO. Will reach out on the latest in Figma to align on this.

**Comment by vladolaru** [comment]
@elizaan36 @timmy5685 Could we get an update on the latest state of things here?

**Comment by timmy5685** [comment]
@anu-rock @vladolaru - thanks for the patience. @orcunomattic and I caught up on this today and we are good to move forward with this.

Here is the final version of the page from @orcunomattic:
<img width="1440" alt="Set up payments task B" src="https://github.com/Automattic/woocommerce-payments/assets/32650633/22743daf-4a1e-47f2-9ae7-11c7772b127f">
Figma: VLWDmeuIXQ7XAK4flyqTFO-fi-2566_58764

**Criteria:**
WooPayments is installed and enabled.

**Expected behavior:**
1. Clicking "Set up additional payment options" from the WooCommerce "Things to do next" list brings you to the page above.
2. Clicking get started brings you to the same page as when you click "Set up additional payments" on the payments overview page: 
![image](https://github.com/Automattic/woocommerce-payments/assets/32650633/18ed1be4-6764-4ff0-ba51-1f70933ce7cd)

Let me know if you have any questions. cc: @elizaan36

**Comment by vladolaru** [comment]
Thank you for sharing these details @timmy5685. A couple of questions:

> Criteria:
> WooPayments is installed and enabled.

Isn't the criteria also that WooPayments has a connected Stripe account (aka is fully setup)? Because without a working account there will be no way to enable BNPLs. Or maybe `enabled` means our current understanding of `connected`.

I see there is a "Get started" CTA and a "Dismiss" button. I assume the "Dismiss" button will permanently hide the section and BNPL payment gateways recommendations _will remain hidden._ **Could we NOT make this dismissable?** The same way all the other payment gateways recommendations are NOT dismissable?

**Comment by timmy5685** [comment]
> Isn't the criteria also that WooPayments has a connected Stripe account (aka is fully setup)? Because without a working account there will be no way to enable BNPLs. Or maybe enabled means our current understanding of connected.

@vladolaru - yes. sorry for the confusion. When I said enabled - I meant fully connected.

> Could we NOT make this dismissable? The same way all the other payment gateways recommendations are NOT dismissable?

Great callout and I agree. @orcunomattic can we remove the dismiss?

**Comment by vladolaru** [comment]
Excellent, @timmy5685! This makes the logic simpler and clearer.

**Comment by orcungogus** [comment]
I updated it, you can view it here on Figma: VLWDmeuIXQ7XAK4flyqTFO-fi-2566_58764

@vladolaru, do you need me to export any assets? Let me know.

**Comment by vladolaru** [comment]
Due to unforeseen complexities, I am bumping the estimate from 2️⃣ to 3️⃣

**Comment by vladolaru** [comment]
@orcunomattic I've pinged you in [the WooCommerce core PR](https://github.com/woocommerce/woocommerce/pull/49234) for design review.
