### ISSUE TITLE
Add skeleton to cart BNPL messaging

### ISSUE THREAD

**Issue by mdmoore** [Automattic/woocommerce-payments#8606]
### Description

The BNPL Payment Method Messaging element on the shortcode cart page should display a skeleton component when cart totals are refreshing.

### Additional context

https://github.com/Automattic/woocommerce-payments/issues/8144#issuecomment-2040688316

**Comment by pierorocca** [comment]
@brettshumaker I'm noticing that there's no longer a skeleton in production. Do you see the same?
