### ISSUE TITLE
Add 'seller_message' alongside the generic "Your card was declined." response to the Order Notes.

### ISSUE THREAD

**Issue by danielk-am** [Automattic/woocommerce-payments#8642]
### Description

I request a more descriptive response alongside the current "Your card was declined." message. This could be added as a private note in the Order Note, which can help the seller better understand what was causing their customers' cards to be declined.

Adding the 'seller_message' and 'type' will give merchants a clearer picture so they can better advise their customers on their next steps.

### Acceptance criteria

Get the 'seller_message' and 'type' in the JSON response and print to Order Notes

### Additional context

Ticket: 8005926-zen

**Comment by htdat** [comment]
Related: #9156 #9810 #8638
