### ISSUE TITLE
Sofort can be re-enabled after it is disabled

### ISSUE THREAD

**Issue by csmcneill** [Automattic/woocommerce-payments#8646]
### Describe the bug

Following https://github.com/Automattic/woocommerce-payments/pull/7480, if an account already had Sofort enabled later removes Sofort from the available APMs, it shouldn't be available to re-enable:

![CleanShot 2024-04-16 at 00 02 46@2x](https://github.com/Automattic/woocommerce-payments/assets/82999806/d0a95281-c9f9-4f9f-912a-444756d62841)

However, this is not happening. Disabling Sofort keeps it as an option to be re-enabled at a later time.

### To Reproduce

1. Open a site with a WooPayments account that has Sofort enabled as an APM.
2. Navigate to **Payments > Settings**.
3. Disable Sofort.
4. Note the message (emphasis added):

> As of October 20th 2023, Sofort is no longer supported for merchants who are not already using it. This means that if you disable Sofort, **you will not be able to re-enable it later**. [Learn more](https://woo.com/document/woopayments/payment-methods/additional-payment-methods/#sofort-migration)

6. Confirm you'd like to disable Sofort.
7. Save your settings.
8. Clear the account cache.
9. Check the `capabilities` from the server.
10. Note that `sofort_payments` still has a status of `active`.
11. Note that there is still a fee structure for `sofort`.
12. Navigate back to **Payments > Settings**.
13. Enable Sofort.
14. Save your settings.

### Actual behavior

Once Sofort is disabled, it can be reactivated without issue.

### Expected behavior

Once Sofort is disabled, it's expected that it will no longer be available from the APM list in **Payments > Settings**.

**Comment by oaratovskyi** [comment]
Closed in https://github.com/Automattic/transact-platform-server/pull/6916
