### ISSUE TITLE
Subscriptions Step 2.1 — Cleaning up the last bits

### ISSUE THREAD

**Issue by reykjalin** [Automattic/woocommerce-payments#865]
As per discussions during team chat we're going to move some clean-up out of #826 and #832. The PRs are both complete functionality-wise, but there are some things we should improve, e.g. getting rid of generic exceptions.

**Comment by allendav** [comment]
@reykjalin - in the next day or two, would you add more detail here? Would like to cover this in Sprint 18 if possible

**Comment by reykjalin** [comment]
@allendav There are issues linked to this epic in ZenHub, each of which contains details about what specifically needs to be done 🙂 

I guess it would've been better to mention that in the issue from the start 😅

**Comment by vbelolapotkov** [comment]
Closing this as all sub issues are closed now.
