### ISSUE TITLE
BNPL announcement "Get started" button doesn't direct to the Settings page

### ISSUE THREAD

**Issue by csmcneill** [Automattic/woocommerce-payments#8660]
### Describe the bug

The BNPL announcement modal has three options:
1. Close the modal via the `x` in the top-right.
2. Learn more which links out to https://woo.com/document/woopayments/payment-methods/buy-now-pay-later/ but doesn't close the modal.
3. Get started, which closes out the modal and should direct to the **Payments > Settings** page at the `/wp-admin/admin.php?page=wc-settings&tab=checkout&section=woocommerce_payments` endpoint.

Option 3 closes the modal but does not direct to the payments settings.

### To Reproduce

1. Onboard a live WooPayments account.
2. Do not enable any BNPL options.
3. Process three live transactions.
4. Clear the `wcpay_bnpl_april15_successful_purchases_count` transient (just in case).
5. Navigate to the **Payments > Overview** page.
6. Inspect the `Get started` button using your browser tools.
7. Note that there is a `<button>` tag but it is not wrapped in an `<a>` tag to direct merchants to the `/wp-admin/admin.php?page=wc-settings&tab=checkout&section=woocommerce_payments` endpoint.
8. Select the `Get started` button.
9. Note that the modal closes.
10. Note that you are still on the **Payments > Overview** page.

### Actual behavior

Selecting the `Get started` button doesn't direct folks to the Settings page.

### Screenshots

![CleanShot 2024-04-17 at 16 50 26](https://github.com/Automattic/woocommerce-payments/assets/82999806/aff96bf8-9492-4a0c-9081-b76c36255ab2)

### Expected behavior

Selecting the `Get started` button _does_ direct folks to the Settings page.

### Additional context

p1713388069625709-slack-CU6SYV31A

**Comment by pierorocca** [comment]
Thanks @csmcneill. Tagging @c-shultz @FangedParakeet if there's anything we can do here to get this resolved, maybe patched? Timing obviously critical as the modal is displayed only for a short moment.

**Comment by csmcneill** [comment]
I have next to zero experience with JS, but it seems like we just need to add a `href` to the `<Button>` here: 

https://github.com/Automattic/woocommerce-payments/blob/2cef5b65db19049374c8a3db747ac1c87254fa9a/client/bnpl-announcement/index.js#L50-L60

However, I don't know what we'd use to dynamically link to the site's settings page. It looks like `href={ getPaymentSettingsUrl() }` _might_ work based on the following:

https://github.com/Automattic/woocommerce-payments/blob/166c0383432d88cdabd2e72b86c0837e011f628b/client/utils/index.js#L65-L71
