### ISSUE TITLE
GH checks fails since WC 8.9 release – `WC compatibility (latest, latest, latest, 7.4)` and `Code coverage`

### ISSUE THREAD

**Issue by Jinksi** [Automattic/woocommerce-payments#8662]
### Description

The following GitHub checks fail due to a deprecated `AssetDataRegistry` arg – deprecated since WC 8.9:

* `WC compatibility (latest, latest, latest, 7.4)`
* `Code coverage (latest, latest, 7.4, includes)` 

[See example run](https://github.com/Automattic/woocommerce-payments/actions/runs/8731648682/job/23957392556#step:5:743).

**Output from the test failure**:

```
Function Automattic\WooCommerce\Blocks\Assets\AssetDataRegistry::add() was called with an argument that is deprecated since version 8.9! The $check_key_exists parameter is no longer used: all duplicate data will be ignored if the key exists by default
```

### Additional context

The deprecation notice introduced to WC in https://github.com/woocommerce/woocommerce/pull/46139.

### Priority

Low priority – deprecation notice only and does not impact functionality.

**Comment by thuautp** [comment]
also reported in 8062374-zen

**Comment by shameemreza** [comment]
Another report here: 8073185-zen
Forum thread with a solution: https://wordpress.org/support/topic/error-on-line-6078/
