### ISSUE TITLE
Add date filter to Disputes page

### ISSUE THREAD

**Issue by jessy-p** [Automattic/woocommerce-payments#8669]
### Description
Add date filter to disputes page so that disputes report between start and end date can be fetched. This is required for the link from Payment Activity widget - https://github.com/Automattic/woocommerce-payments/pull/8667#pullrequestreview-2008950747

### Acceptance criteria
Should be able to load the Disputes page with disputes between certain dates.

### Additional context
p1713363418702459-slack-C06BBFTF6EM

**Comment by nagpai** [comment]
My apologies, during our discussion I mentioned about not seeing a date filter on the disputes page. I saw now that we do have it. 

The filters dropdown though, appear squished and I will create a separate issue for that.  I think we can close this issue for now
