### ISSUE TITLE
Subscription renewals can fail due to "meta_exists() on null" action scheduler error

### ISSUE THREAD

**Issue by csmcneill** [Automattic/woocommerce-payments#8678]
### Describe the bug

Some merchants are unable to process renewals after updating to the latest version of WooPayments due to the following action scheduler error:

```
scheduled action [ID_HERE] (subscription payment) failed to finish processing due to the following exception: Call to a member function meta_exists() on null  
Additional context
{
    "_legacy": true
}
```

This may also appear for subscription payment retries. In that case, the error will be slightly different:

```
scheduled action [ID_HERE] (subscription payment retry) failed to finish processing due to the following exception: Call to a member function meta_exists() on null  
Additional context
{
    "_legacy": true
}
```

This error appears in the `failed-scheduled-actions` log.

Based on extensive testing, this is affecting merchants who are eligible to receive the BNPL announcement implemented in #8605 — which launched in version 7.5.0 of WooPayments.

### To Reproduce

We have not been able to reproduce this issue yet. Please update this section once we can identify reproduction steps.

The current theory is that this is related to a change in the 7.5.0 release.

**Edit**: I've been able to successfully reproduce this issue with the following steps. Some of them may be superfluous, but this is what worked for me.

1. Create a new site.
2. Install and activate WooCommerce.
3. Install and activate WooPayments 7.5.x.
4. Install and activate Woo Subscriptions.
5. Onboard WooPayments in sandbox mode using a country that is eligible for BNPL (e.g., `GB`).
6. Create a virtual simple subscription product with any billing interval.
7. Purchase the product created in step 6.
8. Make your site eligible for the BNPL notice introduced in #8605.

You can either:
a. Follow steps 10–19 twice to force the site to have three total orders (the third order will be affected by this issue and have a `Pending payment` status).
b. Modify `class-wc-payments-bnpl-announcement.php` and comment out the following lines:
https://github.com/Automattic/woocommerce-payments/blob/0025182fe766c5ca17511b6b92c934526770d169/includes/admin/class-wc-payments-bnpl-announcement.php#L135-L138

9. Navigate to **Payments > Overview** and dismiss the BNPL announcement.
**Note**: Dismissing the announcement is not required but can help you determine if your site is eligible to receive the notice.
10. Navigate to **WooCommerce > Subscriptions**.
11. Visit the subscription details page for the subscription purchased in step 7.
12. Open your browser's Network tools and locate `meta-boxes-subscription.js?ver=7.0.0`.
**Note**: a browser refresh may be necessary.
13. [Override](https://developer.chrome.com/docs/devtools/overrides) the `meta-boxes-subscription.js?ver=7.0.0` file.
14. Change line 66 so that `one_hour_from_now` is equal to `moment().add( 2, 'minutes' ),` to bypass the one-hour minimum.
15. Press `CMD + S` or `CTRL + S` to save the override.
16. Press `CMD + R` or `CTRL + R` to refresh the page.
17. Change the `Next Payment` date and time in the **Schedule** meta box to two minutes in the future.
**Note**: If you change the date to today's date, you'll get a JS popup, and the scheduled renewal time defaults to two minutes in the future.
18. Update the subscription.
19. Wait two minutes.
**Note**: You might need to wait just a bit longer if the scheduled action isn't firing right on time.
20. Refresh the subscription details page.
21. Note that the subscription is now `On hold`.
22. Note that there is a notice about a failed scheduled action for the subscription that was renewed in steps 10–19.
23. Navigate to **WooCommerce > Orders**.
24. Note that there is a new order with the `Pending payment` status.
25. Check the `failed-scheduled-actions` log and confirm that the error is present.

### Actual behavior

Subscriptions are not renewing. A renewal order is created, but no attempts at payment are made. There are no order notes, and there is no PaymentIntent created in the Stripe dashboard for affected orders. The renewal order is in a `Pending payment` state.

**Edit**: My tests indicate that affected orders are in a `Pending payment` state. However, selecting the `Retry Renewal Payment` order action while 7.5.x is active, will successfully charge for the renewal, change the status to `Processing`, and re-activate the subscription.

### Screenshots

![image](https://github.com/Automattic/woocommerce-payments/assets/82999806/10f89579-ff69-45bd-956d-a6e0151cca46)

### Expected behavior

Subscriptions renew as expected without action scheduler issues.

### Additional context

8067919-zen was able to resolve the issue by moving from WP Cron to an alternate cron.

Discussed a bit pre-release in p1713299466129449-slack-CGGCLBN58

Originally identified by GlobalStep in p1713287854020229-slack-C011ENB20Q1

Affected interactions so far are:
8067919-zen (also noted above)
8066989-zen
8059197-zen
8061745-zen
8062133-zen
8068744-zen

8080040-zen
8080004-zen
8080155-zen

**Comment by csmcneill** [comment]
I am not adding the `focus: subscriptions` label here since early signs indicate that reverting to 7.4.0 resolves the issue.

**Comment by csmcneill** [comment]
8069156-zen

**Comment by csmcneill** [comment]
Another report of this affecting a T51 site: p1713548962933279/1713548939.245859-slack-C02C4GXMY

**Comment by hayley-king** [comment]
Possibly 8070067-zen

Note that the user was able to process manual renewal before rolling back to 7.4

**Comment by hayley-king** [comment]
8069098-zen

**Comment by battouly** [comment]
8063449-zen

**Comment by fernmed** [comment]
> 8063449-zd-a8c

New details added in thread.

**Comment by fernmed** [comment]
8072670-zen

**Comment by marzianixie** [comment]
8068406-zd-a8c
8069294-zd-a8c

**Comment by yukikatayama** [comment]
8073365-zd-a8c

**Comment by battouly** [comment]
8073437-zen

**Comment by EjayhanFernandes** [comment]
8060140-zd-a8c

**Comment by EjayhanFernandes** [comment]
8069199-zd-a8c

**Comment by thisissandip** [comment]
8078290-zen

**Comment by thisissandip** [comment]
8059197-zen

**Comment by sukafia** [comment]
8078699-zen

**Comment by imodouglas** [comment]
8079069-zen

**Comment by imodouglas** [comment]
8079442-zen

**Comment by kingsleyinfo** [comment]
Another one here 8080040-zd-a8c

**Comment by rbgly** [comment]
8080004-zen

**Comment by sverleis** [comment]
8080155-zen

**Comment by rossviviano** [comment]
8080690-zen

**Comment by rossviviano** [comment]
8080878-zen

**Comment by csmcneill** [comment]
8077182-zd-a8c

**Comment by csmcneill** [comment]
8081746-zen

**Comment by csmcneill** [comment]
8074040-zen

**Comment by csmcneill** [comment]
8070123-zen

**Comment by maxlaf** [comment]
8082109-zen

**Comment by kdingsa8c** [comment]
8074033-zen

**Comment by maxlaf** [comment]
8082224-zen

**Comment by csmcneill** [comment]
8071880-zen

**Comment by csmcneill** [comment]
8076930-zen

**Comment by csmcneill** [comment]
Resolved in 7.5.3. Closing this issue.

**Comment by csmcneill** [comment]
8086827-zen
8093317-zen
8086609-zen

**Comment by csmcneill** [comment]
8087917-zen

**Comment by csmcneill** [comment]
8067066-zen

**Comment by shohanhossainnab** [comment]
8096692-zen
