### ISSUE TITLE
Site Health Reports Performance errors related to wcpay_currency cookie

### ISSUE THREAD

**Issue by darcie** [Automattic/woocommerce-payments#8679]
### Describe the bug

Related to #8534

After updating to WooPayments 7.5.1, Site Health sometimes reports a critical performance issue. 

```
Page cache is not detected and the server response time is slow

Page cache enhances the speed and performance of your site by saving and serving static pages instead of calling for a page every time a user visits.

Page cache is detected by looking for an active page cache plugin as well as making three requests to the homepage and looking for one or more of the following HTTP client caching response headers:

cache-control, expires, age, last-modified, etag, x-cache-enabled, x-cache-disabled, x-srcache-store-status, x-srcache-fetch-status.
 Median server response time was 1,419 milliseconds. It should be less than the recommended 600 milliseconds threshold.
 No client caching response headers were detected.
 A page cache plugin was not detected.
[Learn more about page cache(opens in a new tab)](https://wordpress.org/documentation/article/optimization/#Caching)
```

Upon checking in hosting, it appeared to be related to this string:
```
set-cookie: wcpay_currency=GBP_1; expires=Fri, 19-Apr-2024 11:05:09 GMT; Max-Age=3600; path=/
```

### To Reproduce

1. Have WooPayments 7.5.1 installed with multicurrency enabled
2. Go to Tools > Site Health
3. See the error once Site Health completes loading 

### Actual behavior

The error seems to be temporary in some cases, I reproduced it with Multi-currency enabled but no additional currencies as well as multiple added currencies.  
The merchant did not notice any change in site behavior yet, but was concerned about the critical warning. 

### Screenshots

<img width="900" alt="Screenshot 2024-04-19 at 5 01 03 PM" src="https://github.com/Automattic/woocommerce-payments/assets/318285/bf4cbc46-ec96-4c9e-a2e3-717d5b9b466d">

### Expected behavior

No performance change with the additions of  #8645

### Additional context

8070554-zd-a8c

**Comment by bborman22** [comment]
I've updated the focus label and linked PR. This is an issue with the wcpay_currency cookie and how it is being set. We'll be exploring ways to address this in the next release.

**Comment by bborman22** [comment]
@rafaelzaleski Given the note about the set cookie header preventing caching, is there a different approach we could take here? My thoughts are not setting it when the same or setting through another mechanism (I'm less clear on this as I know there was some effort around HTTP only cookies or not).

**Comment by bborman22** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Fractal-62a0f7b955648b001e1f5e1f/issues/Automattic/woocommerce-payments/8679?planning-poker) with Zenhub @rafaelzaleski

**Comment by bborman22** [comment]
We'll be reverting the cookie change that causes this caching issue in WooPayments 7.6.0 releasing on May 8 and will reopen the https://github.com/Automattic/woocommerce-payments/issues/8130 as we look for a better solution.
