### ISSUE TITLE
[Task] - Add Track events to each tile

### ISSUE THREAD

**Issue by nagpai** [Automattic/woocommerce-payments#8685]

**Comment by vbelolapotkov** [comment]
@nagpai please add description or context for the issue, or add appropriate labels. Without it, it's hard to triage.

**Comment by FangedParakeet** [comment]
@nagpai or @Automattic/helix, is this issue still relevant, created for some higher purpose, or created in error? 🤔 Not sure if this needs to be triaged or if we might be able to close it instead.

**Comment by haszari** [comment]
Thanks @FangedParakeet  - still relevant, we need to add labels and description – part of a project. Apologies for the noise! @nagpai  can you add relevant labels & brief description so this issue is clear to others? Thanks 🙌

**Comment by nagpai** [comment]
@FangedParakeet , @vbelolapotkov  and @haszari . My apologies about this and a couple of other issues that got created by me without descriptions. They may have been created via some task list entries I did and later renamed . 

For now, I have done a check of all issues opened by me, and I am closing duplicates including this one. Very sorry about this landing on the triage list, when it shouldn't have been created. I will be careful henceforth in regularly checking issues created by me appearing in open.

**Comment by nagpai** [comment]
Closing this issue, since it is a duplicate of #8686

**Comment by nagpai** [comment]
Duplicate issue
