### ISSUE TITLE
[Task] Fix the `View report` link on the Disputes tile

### ISSUE THREAD

**Issue by nagpai** [Automattic/woocommerce-payments#8703]

**Comment by vbelolapotkov** [comment]
@nagpai it would be great if add description with more context. For now, routing it to Disputes based on title.

**Comment by nagpai** [comment]
@vbelolapotkov I am sorry. This is a duplicate of #8704 . I am not sure how it got created. Closing this now, and doing a check on other open issues from me as well. Sorry about this.
