### ISSUE TITLE
[Task] - Fix the `View report` link on the Total payment volume tile

### ISSUE THREAD

**Issue by nagpai** [Automattic/woocommerce-payments#8706]
The `View report` link on the Total payment volume tile should lead to the `Transactions` page showing all types created over the last 7 days (or selected time filter) except for `Loan disbursement` and `Loan repayment`

It is currently showing all types created over the last 7 days (or selected time filter) . We need to make sure `Loan disbursement` and `Loan repayment` are excluded. 

This may require creating an additional advanced filter on the Transactions page, to accommodate the above rule 

#### Context
P2 - pdjTHR-3DQ-p2#comment-4954

```[tasklist]
### Subtasks
- [ ] #8726
- [ ] https://github.com/Automattic/woocommerce-payments-server/issues/5247
```

**Comment by haszari** [comment]
Thanks for logging this @nagpai . We need to take a step back and understand the inconsistency between the payment widget/tile and the default transactions list view. 

This is effectively new scope, as we all assumed that the tiles would link through to existing views. i.e. no changes needed, or trivial adjustments to default filtering, or possibly link through to a specific filtered view (using existing filters). FYI @jessy-p

I think it's worth taking a moment to check-in with design and product before we implement a solution. @rogermattic @souravdebnath1986 keen for your thoughts here – we missed this issue in initial exploration

**Comment by haszari** [comment]
Suggestion: use new epic(s) for the changes needed to list screens. I think we can decouple the work safely, and use our original estimates/SP for the tile epics.

**Comment by souravdebnath1986** [comment]
Mentioned on [P2 comment here](https://helixp2.wordpress.com/2024/04/18/first-demo-payment-activity-project/#comment-4993). tl;dr we should keep report defaults separate from the `view report` dataset displays on the same report which will be dependent on time-filter and tile selected on the payment activity card.
