### ISSUE TITLE
Epic: Payment Activity widget - MVP: Hide the payment activity widget when the merchant switches to a non-default currency.

### ISSUE THREAD

**Issue by jessy-p** [Automattic/woocommerce-payments#8707]
For the MVP of Payment Activity Widget, display the widget in the store primary currency. When the merchant switches to a non-default currency using the (existing) tabs on the balance box, hide the payment activity widget.

This is devised as a temporary solution to make a fully functional MVP. Decision based on the discussion: p1713836526287659-slack-C06BBFTF6EM

**Comment by haszari** [comment]
Now we have a currency selector design, we could potentially skip this temporary workaround. Alternatively, if we think it's useful to ship an MVP iteration, we could roll this epic into another MVP epic since it's a temporary, relatively small change.

**Comment by jessy-p** [comment]
Closing in favor of implementing the final design of currency switcher
