### ISSUE TITLE
Payment activity card survey throws an error when submitting as a different WooPayments account-holder

### ISSUE THREAD

**Issue by Jinksi** [Automattic/woocommerce-payments#8709]

**Comment by vbelolapotkov** [comment]
@Jinksi I suppose it's related to ongoing reporting project. Anyway, it would be great to add some description to make it less cryptic 🙂

**Comment by Jinksi** [comment]
Thanks @vbelolapotkov and my apologies, this was not intentional. It seems that some kind user error occurred when creating this issue, and it was created twice.

Closing as a duplicate of the correctly submitted issue #8710
