### ISSUE TITLE
Query with wrong parameter being executed repeatedly in the checkout page

### ISSUE THREAD

**Issue by leonardola** [Automattic/woocommerce-payments#8716]
### Describe the bug
`SELECT id, type FROM wp_wc_orders WHERE id IN ( <cart_id> )` is being called when visiting the shortcode chekcout page.
Note it's cart_id where it should be order_id. 

This happens because [this function](https://github.com/Automattic/woocommerce-payments/blob/e0e62ff755a979aa4b0a5a6e972c0905354f564a/includes/class-wc-payments-payment-request-button-handler.php#L461) uses the `global $post;` instead of `global $theorder;` which is set to the page being visited.

I believe [this function](https://github.com/Automattic/woocommerce-payments/blob/e0e62ff755a979aa4b0a5a6e972c0905354f564a/includes/class-wc-payments-payment-request-button-handler.php#L435) should only return a gateway title for admin pages. So just adding a check to return if not an admin page should be enough to reduce those queries for the customer facing pages. 

Also moving the `'woocommerce_payments' === $id` check to the first line of the function will also prevent executing that query when the data is not going to be used.

In the end the first line should probably look like this:

```
if ( 'woocommerce_payments' !== $id || ! is_admin() ) {
	return $title;
}
```

Also apparently [this core cache](https://github.com/woocommerce/woocommerce/blob/d8486e579cabec16f0be70c1894a4418e88e2e9b/plugins/woocommerce/includes/class-wc-order-factory.php#L34-L41) is not working correctly so the query repeats everytime `wc_get_order()` is called. We should investigate more to make sure it's not something WooPayments is doing wrong and if it's not then open an issue on Woo Core monorepo.

### To Reproduce
- Place a breakpoint [here](https://github.com/woocommerce/woocommerce/blob/d8486e579cabec16f0be70c1894a4418e88e2e9b/plugins/woocommerce/src/Internal/DataStores/Orders/OrdersTableDataStore.php#L1122)
- Add a product to the cart
- Visit the shortcode checkout
- Notice that the query is executed multiple times instead of using the cache available [here](https://github.com/woocommerce/woocommerce/blob/d8486e579cabec16f0be70c1894a4418e88e2e9b/plugins/woocommerce/includes/class-wc-order-factory.php#L34-L41))

### Expected behavior
Not execute the same query multiple times unnecessarily.

### Additional context
Slack thread: p1712565091800569-slack-C7U3Y3VMY
Ticket: 8008825-zd-a8c

**Comment by vbelolapotkov** [comment]
@pierorocca @c-shultz I've checked the links and it seems to be coming from Payment Request Buttons flows, so routing to you for further investigation and prioritization.
