### ISSUE TITLE
[Klarna] Error on non-domestic transactions for shoppers from supported countries

### ISSUE THREAD

**Issue by a-danae** [Automattic/woocommerce-payments#8718]
### Describe the bug

When the shopper is from a country supported by Klarna and the transaction isn't a domestic one, the following error gets displayed:

| Checkout error | Stripe error |
|--------|--------|
| <img width=400 src="https://github.com/Automattic/woocommerce-payments/assets/41606954/2a7a7c75-d217-475c-b3fe-d4aaeceaed2c"> | <img width=400 src="https://github.com/Automattic/woocommerce-payments/assets/41606954/76d10f54-d9ac-48aa-ba8d-e89bbe1be36f"> acct_1NsqFlFlHoxiQPiO / req_fKLp2r0WYVzA1A?t=1714078733 | 

This error seems to be related to Klarna only accepting domestic transactions, with the [exception of the EEA, UK, and Switzerland](https://docs.stripe.com/payments/klarna#:~:text=If%20you%E2%80%99re%20based%20in%20the%20EEA%2C%20UK%2C%20or%20Switzerland).

We already hide Klarna for unsupported customer countries, but we're not handling the domestic transaction restriction.

### To Reproduce

1. Connect your store to a Stripe account from a Klarna-supported country, like the US
2. Enable Klarna
3. As a shopper, add a product to your cart and proceed to checkout
4. As the billing country, select one different from the one your Stripe account is from, like UK
5. Place the order
6. Notice error mentioned above is displayed and that the payment can't be completed

### Actual behavior

The order can't be placed when using Klarna, even though it's displayed as an available payment method.

### Expected behavior

As a shopper, I'd expect Klarna not to be displayed if it's not available. Or maybe to have a less generic error message.

### Additional context

For reference, we're also seeing this behavior in the Stripe extension. https://github.com/woocommerce/woocommerce-gateway-stripe/issues/3096

**Comment by pierorocca** [comment]
Good point. Klarna does accept cross-border in the EU but it was launched without this support for MVP from my understanding.

**Comment by pierorocca** [comment]
For now, first preference would be to hide the payment method since the shopper is ineligible based on our current lack of support for this use case. Second preference, and less ideal but an improvement is to improve the error message. If hiding isn't possible, reach out and I'll provide a suggested error message.

**Comment by danielmx-dev** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Heisenberg-63586f2ec60359001310fa6a/issues/Automattic/woocommerce-payments/8718?planning-poker) with Zenhub @FangedParakeet

**Comment by danielmx-dev** [comment]
While working on https://github.com/Automattic/woocommerce-payments/pull/8980 I found that the current logic that determines which payments methods are available is too restrictive when it comes to using different currencies. This prevents the customer from using Klarna in some valid scenarios.

Take this example from the [Stripe docs](https://docs.stripe.com/payments/klarna):

> For example, a Swedish business can present in EUR to accept Klarna from a buyer in Germany.

However, Sweden's domestic currency is the Swedish Krona (SEK), and currently there checks in the code that prevent Klarna from showing up unless the Store Currency is set to SEK. This means that currently there's no way to accept Klarna payments in other valid currencies (e.g. GBP from customers in the UK, EUR from customers in Spain), even if they are valid transactions.

I'll create a follow-up issue to document this limitation. Also, please note that this limitation already exists in the develop branch, and it's not a regression from the work performed in #8980

**Comment by pierorocca** [comment]
That's correct. The previous team that launched BNPL did so without support for these intra-Europe multicurrency use cases.
