### ISSUE TITLE
[QIT] Warning in `class-wc-rest-woopay-session-controller.php`

### ISSUE THREAD

**Issue by gpressutto5** [Automattic/woocommerce-payments#8732]
### Context

This warning was caught during the release cycle after running the QIT tests against the `develop` branch. This was introduced by #8645.

### Message

> The use of function wp_set_current_user() is discouraged

### Source

> Generic.PHP.ForbiddenFunctions.Discouraged

### File

[includes/admin/class-wc-rest-woopay-session-controller.php:63](https://github.com/Automattic/woocommerce-payments/blob/3c6bba13c5340c5ea0927fb621c76cba32554a1c/includes/admin/class-wc-rest-woopay-session-controller.php#L63)

**Comment by c-shultz** [comment]
Discussed here p1714597754101339-slack-C01BZUL57SQ with @bborman22 . The team will likely take a different approach here prior to release.
