### ISSUE TITLE
Track clicks on the date range preset dropdown

### ISSUE THREAD

**Issue by shendy-a8c** [Automattic/woocommerce-payments#8736]
Send track events when user clicks and send another track events when user chooses a value from the date range presets dropdown (done in https://github.com/Automattic/woocommerce-payments/issues/8734).

**Comment by haszari** [comment]
> Send track events when user clicks and send another track events when user chooses a value from the date range presets dropdown

IMO we don't need a `click` event, I think the main event we need is when the merchant chooses a date preset: e.g. `wcadmin_wcpay_payments_overview_payment_activity_date_range_preset_changed` or similar.

Probably easiest to implement this in PR for the date range selector:

- #8734

I'll add a comment to that issue.

If anyone has a funnel/flow that needs to the `date_range_selector_click` event please comment with details.

**Comment by nagpai** [comment]
[Added track events code](https://github.com/Automattic/woocommerce-payments/commit/32d9d98ff14c554d9a10c32f01607a106259252a) for the date selector in the [same PR ](https://github.com/Automattic/woocommerce-payments/pull/8927)for adding the selector

**Comment by haszari** [comment]
@nagpai probably a good idea to close this issue then, keep things simple :)

**Comment by nagpai** [comment]
Thanks @haszari 🙌 

Closing this issue since it is covered within #8927
