### ISSUE TITLE
Calling woocommerce_checkout_fields on settings pages resulting in conflicts with other plugins

### ISSUE THREAD

**Issue by IanMisnerThough** [Automattic/woocommerce-payments#8752]
### Describe the bug
The `woocommerce_checkout_fields` filter is called on the WooPayments settings page, which can lead to conflicts with plugins that modify the checkout. The outcome is a failure of the WooPayments settings page. 

This has resulted in a conflict with one of our plugins, which we are fixing on our side, but it may benefit the broader Woo community to review this handling in WooPayments as well as the failure is triggered by the checkout fields being filtered for unrelated reasons. 

### To Reproduce

To replicate:

- Activate WooPayments (current version 7.5.3), test credentials are fine
- Activate Aweber, connect it to Aweber (current version 4.0.3) - note: plugin will resolve this in 4.0.4 or later
- Go to the WooPayments settings page [and see this error](https://share.kwp.to/v/iGWpJvZs2FpxOClSmvad)
- For an additional error, attempt to save settings and [see this](https://share.kwp.to/v/ktlModdJ7XO5A2YVrGps)

Note: the frontend experience appears to continue to work just fine, and the issue appears to be specific to the settings page.

### Actual behavior
The settings page fails to load any data, which appears to be a pre-setup state

### Expected behavior
The settings page loads normally 

### Desktop (please complete the following information):
* OS: MacOS 13.6.6 (22G630)
* Browser Chrome
* Version 124.0.6367.93

### Additional context

Backtrace: 
```
 require(‘wp-blog-header.php’), wp, WP->main, WP->parse_request, do_action_ref_array(‘parse_request’), WP_Hook->do_action, WP_Hook->apply_filters, rest_api_loaded, WP_REST_Server->serve_request, WP_REST_Server->dispatch, WP_REST_Server->respond_to_request, WC_REST_Payments_Settings_Controller->get_settings, WC_REST_Payments_Settings_Controller->should_show_express_checkout_incompatibility_notice, apply_filters(‘woocommerce_checkout_fields’), WP_Hook->apply_filters, WC_Aweber_Checkout->checkout_fields
```

**Comment by csmcneill** [comment]
This is related to #8299 / #8339 (cc @FangedParakeet @gpressutto5)
