### ISSUE TITLE
Implement PHPStan tests with QIT and address errors

### ISSUE THREAD

**Issue by FangedParakeet** [Automattic/woocommerce-payments#8754]
### Description

An integration with the [QIT test suite](https://qit.woo.com/docs/) was added in #6486, adding a script to the repo that runs [QIT security tests](https://qit.woo.com/docs/managed-tests/security/). This issue is to build off this integration to add support for [PHPStan tests](https://qit.woo.com/docs/managed-tests/phpstan/) as well.

PHPStan performs static analysis tests on the codebase: [currently the PHPStan test will fail](https://qit.woo.com/?qit_results=4588774.Q9VaiOxEucFOMPFRKZrqK77ilPuyaQyJD9KaiF2Bm4cLdt9RGIbIlTTaEp0sIQQ1), revealing 27 errors at current count within the codebase. Many of these failures can be ignored, but several appear as if they should be addressed. Utilising this existing static code analysis tool will help to harden our codebase and once this feature is added, we can explore whether these tests can be included in any of our existing code workflows.

### Acceptance criteria

* Add working script and `npm` command to run QIT PHPStan tests on the WooPayments codebase.

Once this is completed in this issue, we can create a separate issue or multiple new issues to address the errors that require immediate attention. We can also begin discussing the advantages and disadvantages of including these PHPStan checks in our CI/CD workflows and, if in agreement, create another new issue to include this in our existing Git workflows and/or release process.

### Designs

N/A

### Testing instructions

N/A

### Dev notes

[QIT docs](https://qit.woo.com/docs/)

### Additional context

#6486

**Comment by timur27** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Heisenberg-63586f2ec60359001310fa6a/issues/Automattic/woocommerce-payments/8754?planning-poker) with Zenhub @FangedParakeet
