### ISSUE TITLE
Reporting: Transactions - can't set a date range filter on mobile, `To` date picker is clipped/offscreen

### ISSUE THREAD

**Issue by nagpai** [Automattic/woocommerce-payments#8782]
### Describe the bug

The mobile view of the date range filter ( `Between`  two dates ) , is broken for the Transactions page. It should be made similar to that of `Deposits` and `Disputes` 

### To Reproduce
* Switch to mobile view or a very narrow viewport
* Browse to `Payments` > `Transactions`
* Click on `Advanced filter` and choose `Date`
* Further, select `Between` to be able to specify a date range
* You will see the date selectors appearing squished like in the screenshot below

<img src="https://github.com/Automattic/woocommerce-payments/assets/4162931/43efd731-d447-47de-8730-33ffd4f297c1" width="400px" />

### Expected behavior

The date selector should appear the way it does for `Disputes` or `Deposits` section. 

<img src="https://github.com/Automattic/woocommerce-payments/assets/4162931/61a84332-44a2-498b-b104-41b88d24fcc0" width="400px" />

**Comment by haszari** [comment]
FYI @nagpai I updated the title to make it clear what the merchant can't do – exactly how the UI is broken.

Raising to `high` since this breaks functionality and should be a quick ish fix.

**Comment by Jinksi** [comment]
This is being caused the the following css override that isn't applied to disputes / deposits:

https://github.com/Automattic/woocommerce-payments/blob/65b9b3a850a462b8c3f16c094c3b0a64828ba2b2/client/transactions/filters/style.scss#L1-L7

The same css is being applied to the documents list screen:

https://github.com/Automattic/woocommerce-payments/blob/65b9b3a850a462b8c3f16c094c3b0a64828ba2b2/client/documents/filters/style.scss#L1-L8

IMO we should apply the same custom CSS to all list screen advanced filters if possible.
