### ISSUE TITLE
Epic: Create new shared select component – for payments overview currency select initially

### ISSUE THREAD

**Issue by Jinksi** [Automattic/woocommerce-payments#8788]
We are creating new UI for selecting currency on the Payment Overview page (#8765). This currency select UI requires a new component as per the design (bIfbBgyBPRzvXEl7dEg3cv-fi-2286_67401).

![Image](https://github.com/Automattic/woocommerce-payments/assets/3147296/78b612c2-aa2c-4358-81a8-525e58aab79a)

**Differences from existing WooPayments `CustomSelectControl` component**
* Label positioned inline, aligned left, when inactive.
* Selected option appears inline next to label, but hidden when select dropdown is open/active
* When the dropdown is open/active, the selected option marked with a checkmark ✔️, outset to the left of the option label

Future requirements (e.g. for date range select) to be aware of when implementing 
* Hints (descriptions for each select option)
* The ability to add a second input in a second column with shared state (e.g. calendar input)
* Apply & reset buttons to confirm selection
* Search field to filter options

Note a similar component is used for onboarding screens – the [`CustomSelectControl`](https://github.com/Automattic/woocommerce-payments/blob/0f4abcf8fa8e1eaf1d8d845f17ab729f9bfafcf6/client/components/custom-select-control/index.tsx#L84) component for [`OnboardingSelectField`](https://github.com/Automattic/woocommerce-payments/blob/0f4abcf8fa8e1eaf1d8d845f17ab729f9bfafcf6/client/onboarding/steps/business-details.tsx#L86) country selector:

<img width="300" alt="image 4" src="https://github.com/Automattic/woocommerce-payments/assets/3147296/55894d86-dbab-4cda-ad2d-0b547b12795f">

## Future

This component will also share use-case with:
* Comparison period select #8734 (inl
* Date range select with calendar input #8483 
* Onboarding country select (paJDYF-dgT-p2#comment-24489)

These will have extended features, e.g. multiple columns, apply button and a search field. These do **not** have to be supported by this issue, but should be kept in mind while implementing the currency select.

<img width="1168" alt="image 2" src="https://github.com/Automattic/woocommerce-payments/assets/3147296/2b2f13df-3904-4db7-b8b1-8659295bd92c">

![image](https://github.com/Automattic/woocommerce-payments/assets/3147296/7ae61c27-ffeb-4dd2-8ef4-a4bcd40418ca)

**Comment by haszari** [comment]
@Jinksi  suggests strategy:

- Fork (copy) Woo CustomSelectComponent
- Adapt to our needs and give it a good name
- (later) Work with Woo core to merge our improvements upstream
