### ISSUE TITLE
Release 1.5.0

### ISSUE THREAD

**Issue by DanReyLop** [Automattic/woocommerce-payments#879]
At the end of Sprint 18, release WCPay 1.5.0.

WooRelease should take tare of everything, but remember to check that:
- [ ] Changelog entries are correct both in `readme.txt` and `changelog.txt`, and changelog header for this version (version and date) are correct.
- [ ] Version is bumped in the `woocommerce-payments.php` header, `package.json`, and `readme.txt` `Stable tag` field.
- [ ] GitHub tag and release is created.
- [ ] The correct tag is created in wp.org's SVN.

**Comment by vbelolapotkov** [comment]
Implemented with this commit: https://github.com/Automattic/woocommerce-payments/commit/0046c5af8a6718554b767a165f1443fe09ed7900
