### ISSUE TITLE
Reorganise payments overview currency switcher, welcome message and balances card

### ISSUE THREAD

**Issue by Jinksi** [Automattic/woocommerce-payments#8790]
Part of #8765 

As part of the Payment Activity Card project, we are adding a new currency selector dropdown to the Payment Overview screen. This replaced the existing Balances currency selector.

This currency selector will be a page setting, at top of page and in a sticky header on scroll. It will only be available for merchants with multiple deposit currencies.

This will affect all relevant cards (e.g. Balances, Deposits, Payment activity). Note also the WooPayments logo is removed in the design, and this epic includes that work (removing the logo).

Changes to occur:
- Welcome message now appears outside the Card
- Remove the WooPayments logo on top of the page
- Replace with the Currency switcher dropdown (appears only for merchants with multi-currency setup)
  - The sticky currency switcher on scroll will be handled in #8913
- Remove the currency-switcher tabs from the Balance card
- Ensure that all cards **except Payments Activity Card** on the Payments Overview page reflect the currency switcher dropdown changes
	- A subsequent issue #8490 will handle the Payments Activity Card currency-switching

> [!IMPORTANT]  
> This change is not behind the Payment Activity Widget feature flag and will be launched directly.

> [!NOTE]  
> A subsequent issue #8490 will handle the Payments Activity Card currency-switching, which is not part of this issue

![Image](https://github.com/Automattic/woocommerce-payments/assets/4167300/d36dbf5c-9ad0-4192-aaa4-b5d7f2807999)

**Comment by haszari** [comment]
> Ensure that all cards except Payments Activity Card on the Payments Overview page reflect the currency switcher dropdown changes

Clarifying that `Payments Activity Card` will need to work with this, it's just getting implemented in a separate issue. @Jinksi can you link the issue in the description so it's clear why this is excluded?

**Comment by Jinksi** [comment]
Done, thanks @haszari
