### ISSUE TITLE
Transactions: Add space before Giropay and P24 logo and source_identifier

### ISSUE THREAD

**Issue by mdmoore** [Automattic/woocommerce-payments#8804]
### Describe the bug

On the transactions page, the logo and source_identifier are crowded. I think it just needs a `&nbsp;` or 2 [here](https://github.com/Automattic/woocommerce-payments/blob/d272e6ae0b4a8102a0ded6aad89d87d730585523/client/transactions/list/index.tsx#L106) and [here](https://github.com/Automattic/woocommerce-payments/blob/d272e6ae0b4a8102a0ded6aad89d87d730585523/client/transactions/list/index.tsx#L110).

### To Reproduce

1. Place an order using Giropay as the payment method
2. View the transaction at Payments > Transactions

### Actual behavior

Giropay and P24 transactions have no space between the logo and source_identifier

### Screenshots
<img width="973" alt="image" src="https://github.com/Automattic/woocommerce-payments/assets/3473953/9b37e02d-6f1d-455b-b21b-6a8fec8d7204">

<img width="972" alt="image" src="https://github.com/Automattic/woocommerce-payments/assets/3473953/e5e7b0c9-02ed-4fb3-b561-b2911b7812b3">

**Comment by haszari** [comment]
@mdmoore  feel free to fix this if you're in there and can easily reproduce!

**Comment by haszari** [comment]
Thanks for fixing this @mdmoore !

Note for helix – marking as zero SP as we didn't need any effort here 🙌🏻
