### ISSUE TITLE
Combine cart contents of guest cart and user cart when logging in

### ISSUE THREAD

**Issue by christopher-bio** [Automattic/woocommerce-payments#8806]
### Description

- When a logged-in user adds a product to cart, logs out and leaves the site
- Returns after some time and adds further products to cart (as a guest)
- Logs in during checkout
- The cart contents from the logged-in session are lost
- It would be ideal to still save them, because it is frustrating for the user otherwise

### Research done by @pierorocca
The key concern I have is that a very high amount of shoppers use the cart as a way to save items for consideration for days, weeks, or months. https://baymard.com/premium/guideline-collections/wvcimm/2157. Here's a summary of the approaches I've observed:

Walmart & Target: Combined cart contents
Best Buy: Overwrote cart contents
Home Depot: Overwrote cart content AND placed my existing contents into 'saved for later'. This was especially appreciated as I had searched for pressure treated wood and calculated what lengths and quantities I need for a repair project. Had that cleared my contents, I would have been super annoyed at losing that work.
Shopify Sites: Signed out and signed in carts are shared when possible. State doesn't matter. If cart can't be shared, overwrites cart contents. Does a really good job of continuing a shopper's shopping journey regardless of state.
Aliexpress: Combined cart contents (bug observed - contents correct but qty badge incorrect)
Ikea: Overwrote cart contents. Only after navigating to cart does it display a modal to add cart contents from a previous logged in session. If I choose to remove, those items are gone forever. If I keep them, I can then individually choose to save them as a favorite...but I don't know that in advance. If I don't click on the cart right away and add the same product that's in the invisible saved cart, Ikea doesn't add the product to the existing cart, it increases the quantity in the invisible cart. Good intentions but their flow is complicated and has issues.
Of these patterns Home Depot was my favorite as it strikes a good balance between respecting the cart as a bookmarking tool and a shopper's current purchase intentions. Next is Shopify's approach but it falls apart if the cart can't be cookied/stored. It took effort to circumvent their efforts so they've done a pretty good job.

### Testing instructions

1. Login / Create an account
2. Add product X to cart
3. Logout
4. Add product Y to cart
5. Login again
6. Currently: Product Y is in cart
7. Should be: Have products X and Y in cart

If guest cart and user cart contain the same item, just take the quantity of the guest cart and ignore the user cart item's quantity.

### Additional context
Similar to this issue: https://github.com/Automattic/woocommerce-payments/issues/5491

**Comment by aheckler** [comment]
@christopher-bio Since the issue you describe is not particular to WooPayments, I'm going to close this out. If you like, you can request this feature as a part of WooCommerce itself [here](https://woocommerce.com/feature-requests/woocommerce/).
