### ISSUE TITLE
Session variable 'chosen_shipping_methods' not updating

### ISSUE THREAD

**Issue by coycash** [Automattic/woocommerce-payments#8807]
### Describe the bug
I have my own plugin which checks for the currently chosen shipping method on ajax update by way of the following code:

```
function wtld_checkout_addons_process() {
   $chosen_shipping_method_id = WC()->session->get( 'chosen_shipping_methods' )[0];
   // ...
}
add_action('woocommerce_checkout_process', 'wtld_checkout_addons_process');
```

This works on WooPayments 7.4.0 and earlier but after 7.5.0 $chosen_shipping_method_id is never updated/changed from the initial selection.

### To Reproduce
1. Go to 'Checkout' under WooPayments 7.5.0 or 7.6.0
2. Change from 'flat_rate' to 'local_pickup' shipping method
3. woocommerce_checkout_process hook still says 'flat_rate' is selected
4.  Rollback to WooPayments 7.4.0
5.  Works fine
6. 
### Desktop (please complete the following information):

* OS: Windows 10
* Browser: Firefox
* Version: 125.0.3

### Additional context
Originally posted woocommerce/woocommerce#47295

**Comment by gpressutto5** [comment]
Hi @coycash! I'm using WooPayments 7.6.0, but I still can't reproduce the issue following the steps you provided. Should I do anything differently?

![local_pickup](https://github.com/Automattic/woocommerce-payments/assets/12385501/ca23511b-9f79-41dc-a355-39bddd99219d)

**Comment by coycash** [comment]
I can't quite see the bottom or your screen but it looks like you are submitting the order.  I am not submitting the order and checking the ajax response but rather checking the value of 'chosen_shipping_methods' server side after an ajax call.  Does that make sense?

**Comment by gpressutto5** [comment]
Hi @coycash. Yes, I'm submitting the order because that's the only way I found to make the `woocommerce_checkout_process` hook run. Have you found another way?
Could you update the "To Reproduce" steps with everything we need to reproduce the issue or provide a repository that reproduces it?

**Comment by coycash** [comment]
Sorry, I mispoke.  Yes the order is submitted.  After extensive testing I have found that the following custom code cause my issue:

```
add_filter('woocommerce_package_rates', 'wtld_filter_woocommerce_package_rates', 10, 2);
function wtld_filter_woocommerce_package_rates( $package_rates, $package) {
   ...
   WC()->session->set( 'chosen_shipping_methods', array($first_rate));
   ...
}
```

This definitely didn't break anything until 7.5.0 but I'm probably not supposed to be setting that session variable anyway.
