### ISSUE TITLE
Double Scrollbars Displayed in the Woopay Survey Modal

### ISSUE THREAD

**Issue by lovo-h** [Automattic/woocommerce-payments#8810]
### Describe the bug

Unexpected double scrollbars are displayed in the modal with the WooPay survey, on the "WCPay settings" page. 

### To Reproduce

* As a merchant, ensure WooPay is enabled.
* Navigate to **Payments > Settings**.
* Scroll down to **Express checkouts** section.
* Disable **WooPay** by unchecking the checkbox.
* Scroll down and click the **Save changes** button.
* Notice that a model with WooPay Survey appears.
* Resize the window to something like 590px x 730px (see screenshots).
* Confirm double scrollbars are displayed.

### Actual behavior

When the window is resized, two scrollbars appear in the modal.

### Screenshots

![image](https://github.com/Automattic/woocommerce-payments/assets/6844516/44e6407a-db89-4e24-a20d-8e8a5e6804b9)

### Expected behavior

When the window is resized, only one scrollbar should appear in the modal.

### Additional context

For more details, see the following:
* p1715338926030429-slack-C011ENB20Q1

**Comment by malithsen** [comment]
https://github.com/Automattic/woocommerce-payments/assets/6216000/e24be25c-b7c8-4519-917c-47576c62f15c

I cannot replicate this issue on either Chrome or Firefox anymore.

@lovo-h Can you confirm whether this is still reproducible on your end?

**Comment by malithsen** [comment]
I was not able to replicate this on the staging env either. Closing this but feel free to reopen if reproducible.

**Comment by lovo-h** [comment]
Thanks for the ping, @malithsen. 

I am also not able to replicate this issue as originally reported.
