### ISSUE TITLE
Fix QIT PHPStan errors

### ISSUE THREAD

**Issue by timur27** [Automattic/woocommerce-payments#8817]
### Description
Static code analysis by QIT performs PHPStan checks, which are currently available for execution through the `npm run test:qit-phpstan` command. The outcome of the scan is the report with 27 errors, some of them seem to be more critical than others and those more critical should be fixed within this issue.

### Acceptance criteria

* critical errors are fixed
* `npm run test:qit-phpstan` ends up with only non-critical errors/warnings

**Comment by timur27** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Heisenberg-63586f2ec60359001310fa6a/issues/Automattic/woocommerce-payments/8817?planning-poker) with Zenhub @FangedParakeet

**Comment by vbelolapotkov** [comment]
@timur27 I see you've added devops label, but I see little in common with devops here. What's your plan or expectations here? What does your planning poker comment mean? I'm removing devops labels for now and returning this for triage.

**Comment by timur27** [comment]
Hi @vbelolapotkov thanks for the question, this issue is similar to https://github.com/Automattic/woocommerce-payments/issues/8754, and I used the same labels as https://github.com/Automattic/woocommerce-payments/issues/8754 here. I'm fine with removing the devops labels.

I'm working on this issue at the moment which is part of the Heisenberg Sprint Backlog.

**Comment by vbelolapotkov** [comment]
Ok, thanks for working on it! I'll mark it as triaged then, since you and the team are working on it.
