### ISSUE TITLE
Implement an Idempotency Key for Payment Requests

### ISSUE THREAD

**Issue by jrodger** [Automattic/woocommerce-payments#882]
Adding an idempotency key to requests will give us better control over handling re-tries and other types of errors. Initially we can look at requests that create payments, but the technique can be expanding to other requests if found to be appopriate.

**Comment by deepakpathania** [comment]
Closing this based on [this PR](https://github.com/Automattic/woocommerce-payments/pull/3303) after a discussion with @jrodger.
> I don’t think that PR completely resolves the issue, but I’d suggest going ahead and closing it anyway. It’s 18 months old and I’m not aware of any plans to handle it. If we do start to get issues with multiple requests / payments going through we can reopen it. The idempotency key is quite prominent in Stripe’s documentation, so I’m not worried we’ll lose it.
