### ISSUE TITLE
Google Pay button lacks outline when set to Outline theme

### ISSUE THREAD

**Issue by pierorocca** [Automattic/woocommerce-payments#8828]
### Describe the enhancement
As shown in this [recent PRB test](https://github.com/Automattic/woocommerce-payments/pull/8827#issue-2298855884), the Google Pay button lacks an outline despite being set to the Outline theme.

### To Reproduce

1. Enable Google Pay
2. Set button theme to Outline
3. Observe the preview on Chrome, Google Pay button lacks an outline
4. On a product, cart, or checkout page with a light background observe that the button lacks an outline

### Expected behavior
Google Pay button has an outline in the merchant settings preview and on product, cart, and checkout pages.

**Comment by pierorocca** [comment]
@bborman22 would you recommend we resolve this in the ECE implementation rather than fixing it in the PRB implementation?

**Comment by bborman22** [comment]
Yeah given the timings, this would make more sense as a fix in ECE rollout.

**Comment by pierorocca** [comment]
@bborman22 also appears that there's no support for Outline for Google Pay on Apple Pay. Is there a way to "fake" an outline?

**Comment by bborman22** [comment]
Yeah I can see that it's not an [option for Google Pay](https://developers.google.com/pay/api/web/guides/brand-guidelines) (wondering if this recently changed?). Given how the button is rendered in an iframe, I don't know of a good way we could fake it. We are doing [this exploration around individual ECE renders](https://github.com/Automattic/woocommerce-payments/issues/8872) per button and there might be some ability to add a border around just the Google Pay button if outline is chosen, but I wouldn't consider it very promising as I doubt we'd get a clean look that way.

**Comment by pierorocca** [comment]
Switching to an enhancement since this is not technically a bug.

**Comment by pierorocca** [comment]
Closing this in favor of a potential enhancement to allow buttons to be themed independently from one another. Rationale - buttons can have _n_ number of themes, different definitions of what "white" or "light" means, and there's no guarantee of overlap. Therefore, trying to normalize this is futile.
