### ISSUE TITLE
Pressing the Enter key while interfacing with checkout fields will start the WooPay checkout flow instead of placing the order

### ISSUE THREAD

**Issue by csmcneill** [Automattic/woocommerce-payments#8862]
### Describe the bug

If WooPay is enabled on the checkout page and a customer presses the `Enter`/`Return` key while any field on the checkout page is focused, it will start the WooPay checkout flow (`?wc-ajax=wcpay_get_woopay_session`). The WooPay button will change to a spinner, and the customer will be redirected to the WooPay hosted onboarding experience.

This issue is not present on the cart page when the shipping calculator is enabled; pressing the `Enter`/`Return` key saves the address settings.

### To Reproduce

1. Ensure WooPay is not enabled.
2. Add a product to your cart.
3. Navigate to the checkout page (shortcode or blocks).
4. Select any editable field (e.g., email, shipping address, billing address, card fields, etc.)
5. Press the `Enter/Return` key.
6. Note the error that suggests the `Place order` flow was started.
7. Enable WooPay.
8. Repeat steps 2–5.
9. Note the WooPay button changes to a spinner icon.
10. Note that you are redirected to the platform checkout.

### Actual behavior

Pressing `Enter` while interfacing with any editable field on the checkout page directs a customer to `pay.woo.com`.

### Screenshots
![CleanShot 2024-05-22 at 13 33 02](https://github.com/Automattic/woocommerce-payments/assets/82999806/368b8823-e1f8-4b66-9e8d-cf751c57297f)

### Expected behavior
Pressing `Enter` while interfacing with any editable field on the checkout page does not direct a customer to `pay.woo.com` and instead tries to place the order.

### Additional context

p1716368611870019-slack-C022WMN88KG

**Comment by pierorocca** [comment]
Noting that @asumaran confirmed this on his site as has @aheckler.

> "The problem I was mentioning is related to point 3. Simply entering an existing WooPay email on the checkout page (i.e. for a returning WooPay customer) doesn't seem to trigger anything.
> That happens when Klarna is enabled on the site as the site"

Chris has confirmed the same issue when Afterpay is enabled.

**Comment by bborman22** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Fractal-62a0f7b955648b001e1f5e1f/issues/Automattic/woocommerce-payments/8862?planning-poker) with Zenhub @asumaran @cesarcosta99 @lovo-h @rafaelzaleski @reykjalin @ricardo
