### ISSUE TITLE
Integrate ECE for Payment Processing in the Blocks Cart Page

### ISSUE THREAD

**Issue by rafaelzaleski** [Automattic/woocommerce-payments#8867]
Implement the Stripe Express Checkout Element (ECE) to process payments on the WooCommerce Blocks cart page. 

### Acceptance criteria:

- The ECE implementation must successfully process payments on the WooCommerce Blocks cart page without disrupting the existing checkout flow.
- The ECE implementation is not expected to function in any other flows or within the shortcode checkout.
- Ensure there are no regressions in Payment Request Buttons (PRB) when ECE is disabled.
- There are no regressions when no express checkout payment methods are active.

**Comment by bborman22** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Fractal-62a0f7b955648b001e1f5e1f/issues/Automattic/woocommerce-payments/8867?planning-poker) with Zenhub @asumaran @cesarcosta99 @lovo-h @rafaelzaleski @reykjalin @ricardo
