### ISSUE TITLE
Integrate ECE Payment Processing for the Pay for Order Endpoint

### ISSUE THREAD

**Issue by rafaelzaleski** [Automattic/woocommerce-payments#8869]
Implement the Stripe Express Checkout Element (ECE) to process payments on the pay for order endpoint (pending payment orders). 

### Acceptance criteria:

- The ECE implementation must successfully process payments for orders in the pending payment status via the pay for order page.
- Ensure there are no regressions in Payment Request Buttons (PRB) when ECE is disabled.
- There are no regressions when no express checkout payment methods are active.

**Comment by bborman22** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Fractal-62a0f7b955648b001e1f5e1f/issues/Automattic/woocommerce-payments/8869?planning-poker) with Zenhub @asumaran @cesarcosta99 @lovo-h @rafaelzaleski @reykjalin @ricardo

**Comment by bborman22** [comment]
Just noting that there is a blocks and legacy version of Pay for Order that would need to be implemented.
