### ISSUE TITLE
Spike: investigate compatibility between Link and WooPay when Link is offered in ECE

### ISSUE THREAD

**Issue by rafaelzaleski** [Automattic/woocommerce-payments#8874]
We need to investigate the compatibility of WooPay and Link when Link is offered as an ECE (Express Checkout Element) payment method. Currently, they are mutually exclusive options because the [Link Authentication Element](https://docs.stripe.com/payments/link/link-authentication-element) attempts to control the email field, which is also utilized by WooPay. The key question we need to answer is: **Can Link function as an Express Checkout button option when WooPay has control over the email field?**

Context: paJDYF-dBB-p2#comment-24692

### Acceptance criteria:

- Document the conditions required to display Link as a payment option in ECE.
- Determine and document if Link can work as an ECE option while WooPay controls the email field.
- Document any other incompatibilities discovered.

**Comment by bborman22** [comment]
Timeboxing this spike to 2 points based on our usual process for spikes.

**Comment by ricardo** [comment]
@bborman22 as a result of this spike, I have created these two follow up issues: #9035, #9034 and added them to Milestone 3 in #8768. Can you please review the prioritization of both and determine where they fit best?

Closing #9034 first will invalidate #9035, but we can also close #9035 and then #9034 after the migration, depending on prioritization.

Documenting the Spike:

---

✅ WooPay and Link as an ECE button are perfectly compatible together:

<img width="400" alt="product-page" src="https://github.com/Automattic/woocommerce-payments/assets/5509901/5e6f5676-8017-4156-ae84-a6467df0e993">

I was able to checkout with both WooPay and Link enabled at the same time.

As for controlling the email field and "Save payment information" checkbox, both are still mutually exclusive.

## Conditions required to display Link as a payment option in ECE

Link must be enabled via Stripe's payment method settings for connected accounts. To test this, I temporarily enabled it for the WCPay Dev (Express) account (it's back to disabled now).

For live merchant accounts Link is currently disabled in the ECE. Also there's a custom rule to enable Link for Stripe Checkout for [U.S. accounts only](https://woocommerce.com/document/woopayments/payment-methods/link-by-stripe/).

<img width="400" alt="live-stripe-link-settings" src="https://github.com/Automattic/woocommerce-payments/assets/5509901/661ef537-74c3-48dd-9cd2-83b666f90597">

In addition to that, in order for the Link ECE checkout to work, we need to add it as an option in the [payment methods array for new Payment Intents](https://github.com/Automattic/woocommerce-payments/blob/98a9863a66d5aefc6696a5e617740e713b71574d/includes/core/server/request/class-create-and-confirm-intention.php#L91).

## Link and WooPay as Express Checkout buttons

As mentioned above, they can both work well together, but the WooPayments settings currently doesn't allow for that.

Right now, if WooPay is enabled, Link must be disabled and vice-versa. There needs to be a separate option to determine who controls the email input and the "Save payment information" checkbox, so they don't conflict at checkout.

<img width="400" alt="WooPayments settings" src="https://github.com/Automattic/woocommerce-payments/assets/5509901/149ca6cb-7b7f-433c-a253-6dfc5d01acb7">

I opened #9034 as a result of this spike. In case we want to allow both WooPay and Link at the same time, we need to redesign their settings to separate the control of billing email + cc form checkbox and the button availability.

In case we want to keep them mutually exclusive, no action is necessary on the settings, but we still need to fix the Link checkout.

## Other issues discovered

- In the current PRB implementation Link is disabled (pbIwZe-1so-p2), so there's no mechanism to control the button availability when Link is disabled from WooPayments settings. When the PRB migration is complete, we will have a problem unless we implement a way to hide Link, similar to this: 2714-gh-woocommerce/woocommerce-gateway-stripe (Also documented in #9034).
- Another issue is that we currently don't support `link` checkouts as we don't offer it as a payment method when creating new Payment Intents for express checkouts ([src](https://github.com/Automattic/woocommerce-payments/blob/98a9863a66d5aefc6696a5e617740e713b71574d/includes/core/server/request/class-create-and-confirm-intention.php#L91)) – We need to either disable Link by default in the ECE, or support Link payments BEFORE the PRB migration is complete (#9035 and/or #9034).

**Comment by rafaelzaleski** [comment]
For now, I’ll keep #9035 in the project epic for milestone 2 and remove #9034, since our focus is on achieving feature parity with PRBs. 
We can look into integrating Link or adding new features after we’ve successfully switched from PRBs to ECE, possibly in a new milestone, depending on our priorities. 
Thanks for your detailed investigation and documentation, @ricardo!

**Comment by pierorocca** [comment]
Awesome work! Pinging @nikkivias for awareness from a design perspective. We are considering supporting the Link button (express checkout) alongside WooPay. This is only a "what if" analysis at this time

The challenge: Link autofill and WooPay both vie for control of the email address field on checkout. In order to avoid that conflict, today we force either WooPay or Link to be disabled. The addition of the Link button, which doesn't require the email, changes the scenario a bit. We don't need to fully disable Link if WooPay is enabled, only partially disable the autofill portion of it. 

OR

We keep them mutually exclusive, ensuring that each is the best experience they can be.
