### ISSUE TITLE
Update Product Add-Ons integration

### ISSUE THREAD

**Issue by rbgly** [Automattic/woocommerce-payments#8911]
### Background Info / Debug

SomewhereWarm adopted Product Add-ons and brought several improvements to the extension.
One of them was to **Change the way prices are presented in the cart** -  see  pdqkbG-2E8-p2

SomewhereWarm was not aware that Woo Payments integrated with Product Add-ons and didn't inform Woo Payments for these changes.

- Woo Payments Integration `get_item_data` - [See Github](https://github.com/Automattic/woocommerce-payments/blob/8aa455c724e3eeaa7a31bbe536b6266296b0592a/includes/multi-currency/Compatibility/WooCommerceProductAddOns.php#L111-L146)
- Product Add-ons `get_item_data` - [See Github](https://github.com/woocommerce/woocommerce-product-addons/blob/195901c6732aeac5e24b4011671f7aafc8ae22fb/includes/class-wc-product-addons-cart.php#L721-L802)

For this bug to be fixed, the Woo Payments integration `includes/multi-currency/Compatibility/WooCommerceProductAddOns.php` has to be updated.

See p1717513051447799-slack-C7U3Y3VMY

The issue is not only related to addons with 0 prices, as Product Add-ons has changed how all prices are presented in cart.

_This section was added by @PanosSynetos_

### Describe the bug
Product Add-Ons with no price are showing as 0.00 in the cart when WooPayments is enabled.

### To Reproduce

1. With only WooCommerce, WooPayments and Product Add-Ons active on the site, create a new product with multiple choices. One should have a flat rate of 0.00.

<img width="2030" alt="add-on-configuration" src="https://github.com/Automattic/woocommerce-payments/assets/107065508/e9fc05d8-79f6-400f-bb8a-55d7f162ab38">

2. On the front-end of the site, select the "free" add-on.

<img width="1425" alt="product-page" src="https://github.com/Automattic/woocommerce-payments/assets/107065508/62a839bb-f0dc-4e7b-8101-0d8c23f1cbbd">

3. Add this to the cart.
4. Next, repeat the steps above but with WooPayments deactivated.

### Actual behavior

When WooPayments is active, the product is added to the cart with the add-on details below the main product information. The price is displayed as 0.00 instead of not appearing at all. Repeating the process with WooPayments deactivated causes the price to be hidden as expected.

<img width="823" alt="cart-zero" src="https://github.com/Automattic/woocommerce-payments/assets/107065508/26ce4e51-9eb1-4e70-ada9-421370e13789">

### Expected behavior

The price should **not** show 0.00 at the cart for "free" product add-ons.

<img width="1032" alt="cart-no-price" src="https://github.com/Automattic/woocommerce-payments/assets/107065508/457169b9-6c8b-4658-b2f5-f986d140f704">

### Desktop (please complete the following information):

* OS: MacOS
* Browser: Chrome
* Version: 125.0.6422.114

### Additional context
- 8198244-zen
- p1717513051447799-slack-C7U3Y3VMY

**Comment by PanosSynetos** [comment]
Hey team - @nagpai 

We (SomewhereWarm) will evaluate whether we can absorb it in an upcoming sprint and let you know later in the day.

Tagging @jimjasson @xristos3490 @peterfabian @dakota for awareness

**Comment by haszari** [comment]
> For this bug to be fixed, the Woo Payments integration includes/multi-currency/Compatibility/WooCommerceProductAddOns.php has to be updated.

Based on the affected code, and discussion in slack, I've switched the focus label to `multicurrency`. (FYI `integration` is specifically about external APIs as a product, not compatibility issues within Woo ecosystem.)
