### ISSUE TITLE
Use generic language for VAT/GST in VAT details form to reduce confusion in non-VAT regions (e.g. Japan)

### ISSUE THREAD

**Issue by brucealdridge** [Automattic/woocommerce-payments#8926]
### Describe the bug

Support for Japan Consumption Tax (JCT) is enabled on the server allowing merchants to submit a corporate number and access tax invoices.

While JCT is fully supported, updating the following would help make the process clearer to merchants.
 - Remove references to VAT. 
 - Update hints to support JCT and [Corporate Numbers](https://www.houjin-bangou.nta.go.jp/en/setsumei/).

The current hint text when entering a Tax ID is `This is 8 to 12 digits with your country code prefix, for example DE 123456789.` Corporate numbers must be 13 digits.

References to `VAT` are unclear for countries that don't have a VAT tax. The tax name should be localised (e.g. JCT, GST) or changed to something that would work for all countries e.g. `Tax ID`, `Tax Documents`, and `Tax Invoice`

![image](https://github.com/Automattic/woocommerce-payments/assets/57298/24d18df5-36e2-4f51-9f15-248d29bc884b)

Noting also there is an encoding issue with this error message:

> `Error: Your account&#039;s country is not supported for VAT validation.`

And possibly any other error messages that are displayed inline. If convenient, fix in this issue, otherwise please log a follow up issue.

**Comment by haszari** [comment]
Adding to `Next` so we can estimate SP. We may push back to backlog after that depending on capacity x need.

**Comment by haszari** [comment]
@brucealdridge can we retitle this bug so the desired outcome is crystal clear?

Something like:

> Use generic language for VAT/GST in `VAT details` form to reduce confusion in non-VAT regions (e.g. Japan)

Is that accurate?

**Comment by haszari** [comment]
Noting also there is an encoding issue with this error message:

> `Error: Your account&#039;s country is not supported for VAT validation.`

And possibly any other error messages that are displayed inline. Adding this to the description so we can fix in this bug or log a follow up issue.

**Comment by haszari** [comment]
<img width="1236" alt="Screenshot 2024-06-17 at 3 36 30 PM" src="https://github.com/Automattic/woocommerce-payments/assets/4167300/ac41f8b8-d373-426c-baee-ce8fb9c085bc">

#### What fields need changing?
Here's a summary of all the strings / fields that need updating:

- Title: `VAT details`
- Step 1: `Update your VAT information`
	- Copy: `VAT information saved on this page will be applied to all of your account’s receipts.`
	- Checkbox: `I’m registered for a VAT number`
	- Legal requirement note: `If your sales exceed the VAT threshold for your country, you’re required to register for a VAT number.`
	- Field label: `VAT Number`
	- Field hint: `This is 8 to 12 digits with your country code prefix, for example DE 123456789.`

There are a lot of mentions of `VAT` in this modal. 

Here are two options for making this modal work across different tax regimes/countries:

1. Use generic `tax` language, avoid specifics, link to user docs for more info. 
2. Dynamically show country-specific info where needed.

### Option 1 - generic language & docs link

- Title: `Tax details` or, can we make this an action, e.g. `Add your tax information`
- Step 1: `Enter your tax ID`
	- Copy: `The information you provide here will be used for all of your account's tax documents.`
	- Checkbox: `I’m registered for a tax number (e.g. VAT, GST, JCT)`
	- Legal requirement note: `If your sales exceed the relevant threshold for your country, you’re required to provide a tax ID.`
	- Field label: `Tax ID`
	- Field hint: `The format of the ID depends on your store country. [Learn more](https://woocommerce.com/document/woopayments/taxes/documents/)` 

Here's a mockup: 

<img width="1062" alt="Screenshot 2024-06-17 at 3 53 53 PM" src="https://github.com/Automattic/woocommerce-payments/assets/4167300/f10d3050-71f6-4104-96d5-1f39af8a927f">


@sheenalee4 @bmccotter @souravdebnath1986 @rogermattic  – would this generic approach work? I figure we can add lots more details about format, requirements etc in the docs page and keep that up to date more easily than the plugin UI.

### Option 2 - dynamic, country specific

We'd potentially need country-specific wording for all of the above elements, here's an example for Japan.


- Title: `Tax details` or, can we make this an action, e.g. `Add your tax details`
- Step 1: `Enter your corporate number (JCT)`
	- Copy: `Your JCT will be used for all of your account’s tax documents.`
	- Checkbox: `I’m registered for a JCT`
	- Legal requirement note: `If your sales exceed the threshold for your country, then you’re required to provide your JCT.`
	- Field label: `JCT`
	- Field hint: `Your corporate number (JCT) should be 13 digits. [Learn more](https://woocommerce.com/document/woopayments/taxes/documents/)`

**Comment by haszari** [comment]
Marking as `needs design` until we get confirmation that generic wording is ok and confirm copy. I have the ball for confirming this.

**Comment by souravdebnath1986** [comment]
If I understand the issue correct, this calls for a generic language to the Indirect tax info collection page ? I 'm assuming this is functional for all countries, however could be misleading by region where Indirect tax is not know as VAT. 

I like the approach, though I 'll defer to @sheenalee4 @wojtekn from tax to guide the design. Based on the language we use, it would also require updates to the support page, emails and VAT documents as well I suppose.

**Comment by wojtekn** [comment]
@souravdebnath1986 I believe you wanted to ping @WKA8C 😄

**Comment by souravdebnath1986** [comment]
Yes thank you, sorry for the wrong ping. This is for @WKA8C.

**Comment by aheckler** [comment]
FYI, I have updated [our support doc](https://woocommerce.com/document/woopayments/taxes/documents/) to use more generic language (e.g. "tax ID number" instead of "VAT number" and so on). I have left the screenshots as-is, since "VAT" will be the language that the majority of merchants will see.

Once this issue is closed and JP merchants can see "JCT" language, or some kind of generic language, I'll use the Pay Ops email tool to notify all JP merchants of this new-to-them feature.

**Comment by bmccotter** [comment]
My preference would be to enable country specific messaging here. I think it provides a better experience, is clear, concise and will avoid confusion. What we don't want to happen is folks not entering in their tax information and cause a support burden for our team.

**Comment by haszari** [comment]
> My preference would be to enable country specific messaging here. I think it provides a better experience, is clear, concise and will avoid confusion. What we don't want to happen is folks not entering in their tax information and cause a support burden for our team.

Thanks @bmccotter  – tailoring the UI and copy would certainly be clearer.

I'll work through a proposal for that. I might take the opportunity to simplify and reduce the places where `VAT` (or similar) is mentioned, so the modal is consistent across different countries, but also has specific guidance where needed.

Working on a prototype in linked PR.

**Comment by bmccotter** [comment]
Sounds great @haszari; however we can optimize I'm here for it!

**Comment by rogermattic** [comment]
Agreed with @bmccotter !
>My preference would be to enable country specific messaging here. I think it provides a better experience, is clear, concise and will avoid confusion. 

@aheckler :
>I'll work through a proposal for that. I might take the opportunity to simplify and reduce the places where VAT (or similar) is mentioned, so the modal is consistent across different countries, but also has specific guidance where needed.

Do you think a mockup for each country / area variant would be useful?
When we have the content for it, I'm happy to see if there's anything we can optimise UI-wise and produce the variant mockups!

**Comment by aheckler** [comment]
> Do you think a mockup for each country / area variant would be useful?

I don't think so, since IIRC all countries except Japan will see "VAT", and only Japan will see anything different, right?

**Comment by haszari** [comment]
> > Do you think a mockup for each country / area variant would be useful?

> I don't think so, since IIRC all countries except Japan will see "VAT", and only Japan will see anything different, right?

Correct – ish. This is essentially a localisation bug, the current modal assumes "VAT", and maybe a specific kind of VAT (EU/UK?). I will post examples of the modal for Japan, EU, and UK when I have it working (in the pull request), so we can use that to discuss and refine wording.

- Mockup is not needed to discuss – I am mocking up live in code.
- Discussion of mockup(s) is worthwhile – to get the details right for what language we make generic (e.g. `Tax information`) vs specific (`e.g. you need to provide your Corporate Number for JCT (consumption tax)`). 

I think we should consult an expert (tax expert or local expert) for each variation and get feedback on if the modal is clear & helpful. E.g. a happiness engineer with experience in Japan, or a friendly Japan merchant. And maybe similar for EU and UK.

In future this modal might need to support `GST` (e.g for AU, NZ, IN). Ideally we could implement that quickly – so I'm keeping that in mind too.

Side note – we also need to consider how this modal gets translated into other languages, which could complicate things (e.g. search-replace `VAT` for `JCT` might not work).

**Comment by bmccotter** [comment]
> Side note – we also need to consider how this modal gets translated into other languages, which could complicate things (e.g. search-replace VAT for JCT might not work).

This can be feature state though.

**Comment by haszari** [comment]
> This can be feature state though.

Side note (I have what I need for this issue, but curious) – @bmccotter what do you mean by "feature state" here?

**Comment by bmccotter** [comment]
> Side note – we also need to consider how this modal gets translated into other languages, which could complicate things (e.g. search-replace VAT for JCT might not work).

That we don't need this today, but would be a nice to have in the future / feature state :)
