### ISSUE TITLE
Ensure the Telemetry events for PRBs are Implemented into ECE

### ISSUE THREAD

**Issue by rafaelzaleski** [Automattic/woocommerce-payments#8948]
Ensure that all telemetry events currently triggered by Payment Request Buttons (PRBs) are also implemented and triggered in the Express Checkout Element (ECE). This task involves reviewing the telemetry setup for PRBs and replicating it appropriately within the ECE implementation to maintain consistency in data collection and monitoring.

From a quick search, I could only find the following events:

```
gpay_button_click
applepay_button_click
gpay_button_load
applepay_button_load
```

### Acceptance criteria:

- All PRB telemetry events are correctly implemented and triggered in the ECE.

**Comment by bborman22** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Fractal-62a0f7b955648b001e1f5e1f/issues/Automattic/woocommerce-payments/8948?planning-poker) with Zenhub @asumaran @cesarcosta99 @lovo-h @rafaelzaleski @reykjalin @ricardo
