### ISSUE TITLE
Set ECE as Default for Express Checkout Buttons

### ISSUE THREAD

**Issue by rafaelzaleski** [Automattic/woocommerce-payments#8949]
Modify the integration of the Express Checkout Element (ECE) in WooPayments to make it the default method for express checkout buttons, irrespective of the feature flag. 

### Acceptance Criteria:
- ECE is the default experience for express checkout buttons and PRBs are not loaded.

**Comment by bborman22** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Fractal-62a0f7b955648b001e1f5e1f/issues/Automattic/woocommerce-payments/8949?planning-poker) with Zenhub @asumaran @cesarcosta99 @lovo-h @rafaelzaleski @reykjalin @ricardo
