### ISSUE TITLE
The Payment Activity Card throws error `wcpay_invalid_currency` for live accounts in test mode

### ISSUE THREAD

**Issue by Jinksi** [Automattic/woocommerce-payments#8960]
### Describe the bug

When a live account in test mode attempt to view the Payment Activity card, it will not render and a network error `wcpay_invalid_currency` will be returned from `/payment_activity`.

Disabling test mode will not result in the same error and the Payment Activity card will render (and show values if the account has non-zero live transaction history).

> [!TIP]
> This issue affects the Payments Overview Card which is behind feature flag `_wcpay_feature_payment_overview_widget`

**Request params** via browser devtools (identical for test/live)
```
currency: aud
date_start: 2024-06-06700:00:00
date_end: 2024-06-1223:59:59
timezone: +10:00
_locale: user
```

**Response**

```
{
"code": "wepay_invalid_currency",
"message": "Error: Invalid currency.",
"data": null
}
```

### To Reproduce

1. Use an account onboarded in live mode, with at least one live transaction
	* You can use the live account `ej-wcpay-aus`, credentials on secret store
3. Enable WooPayments test mode
4. Make some test purchases
5. Enable feature flag `_wcpay_feature_payment_overview_widget`
6. Visit Payments → Overview, with "Network" browser dev tools tab open
8. Notice the Payment Activity Card will not render and an Error notification will appear.
9. In the Network browser dev tools, notice the request to `/payments/reporting/payment_activity` returns the error `wcpay_invalid_currency`

### Additional context

First discussed in Slack p1718257356593509-slack-C06BBFTF6EM

**Comment by jessy-p** [comment]
@csmcneill Unable to replicate, could you please recheck?

**Comment by jessy-p** [comment]
Able to replicate on site shared by @aheckler.  p1718893319085829/1718870846.767419-slack-C06BBFTF6EM
A bug was introduced in `validate_currency` code when we made currency parameter mandatory. It is triggered when external payout accounts are not set.
