### ISSUE TITLE
Investigate need for creating payment intent with fallback of all enabled payment methods

### ISSUE THREAD

**Issue by frosso** [Automattic/woocommerce-payments#8969]
### Describe the bug

As part of https://github.com/Automattic/woocommerce-payments/pull/8966 it was noted that the Payment Intent was created with all the enabled payment methods.

This is happening because this line isn't detecting the correct payment method being used:
https://github.com/Automattic/woocommerce-payments/blob/13ea0cffabe45301b6f2850036784e389142559b/includes/class-wc-payment-gateway-wcpay.php#L2059-L2059

As part of the PR review process, we discussed the possibility of removing such fallback, and just using `card` instead: https://github.com/Automattic/woocommerce-payments/pull/8966#pullrequestreview-2122582752

The purpose of this ticket is to investigate the need for such fallback, to determine if it's needed in any of the supported scenarios.
If it's not needed, let's fallback to using `card`, instead.

**Comment by mdmoore** [comment]
Adjusting the estimate on this one as it required quite a bit more investigation and testing that originally planned.
