### ISSUE TITLE
Add modal to capture terms of service agreement

### ISSUE THREAD

**Issue by thenbrent** [Automattic/woocommerce-payments#897]
Create a lightboxed modal that covers the transactions, disputes and deposits views (and prevents interaction with them) with:

> We’ve updated our <a href="https://wordpress.com/tos/">Terms of Service</a> – to continue using WooCommerce Payments please acknowledge that you’ve read them and agree.
>
> [Agree]      [Disable WooCommerce Payments]

More details: paJDYF-OD-p2#comment-3342

**Comment by thenbrent** [comment]
@LevinMedia can we get some design work for this one?

**Comment by thenbrent** [comment]
Alternative button text recommended in paJDYF-OD-p2#comment-3452:

> By clicking [Button Text], you agree to our Terms of Service.

**Comment by vbelolapotkov** [comment]
Design work by @LevinMedia in this post: paJDYF-R2-p2.
