### ISSUE TITLE
`Payment activity` card – user-selected date range selected is not remembered, reverts to default on navigate away

### ISSUE THREAD

**Issue by souravdebnath1986** [Automattic/woocommerce-payments#8972]
### Describe the bug
Testing the Payment Activity Card (PAC) on the Helix demo site. The default date range is `Last 7 days`. On selecting a different date range eg: `Last 12 months`, when we navigate away from the page by clicking `view report` for example, and then come back to the PAC on the overview page, the date range flips back to default. 

### To Reproduce

1. Grab a WooPayments site that has a history of transactions (I can provide access as needed to a personal test site with a history of live and test transactions).
2. Navigate to Payments > Overview.
3. Select the date range to an option other than the default option of `Last 7 days`
4. Navigate away from the Payments > Overview page. You can also refresh the page. 
5. Come back to the Payments > Overview page. 
6. Note that the date range (and associated data) has flipped back to default i.e. `Last 7 days`

### Actual behavior
The PAC always defaults to `Last 7 days` instead of the date range (and data) selected which shouldn't be the case. 

### Screenshots
https://github.com/Automattic/woocommerce-payments/assets/112917711/354631ec-3590-4912-b298-f1c5443b0953

### Expected behavior
The PAC should persist the state selected based on the date range for the same user session
It can go back to default state for any new user session

### Additional context
Discussed in this [comment](https://github.com/Automattic/woocommerce-payments/issues/8737#issuecomment-2171361503)

**Comment by jessy-p** [comment]
@souravdebnath1986  clarified that this state should be preserved within a session

**Comment by jessy-p** [comment]
> state should be preserved within a session

@souravdebnath1986  While implementing, had a question - Isn't this a merchant preference, and do you think we should persist it between sessions? i.e if a merchant likes to see his Payment Activity in MTD, should we always set it so. What is the rationale behind resetting it every session?

**Comment by haszari** [comment]
> While implementing, had a question - Isn't this a merchant preference, and do you think we should persist it between sessions? i.e if a merchant likes to see his Payment Activity in MTD, should we always set it so. What is the rationale behind resetting it every session?

I agree, I think it would be simpler to treat this as a user preference. Any time merchant change the card settings they are saved and used for next view of the overview screen. Each user has their own preferences.

I don't have any objections to making this persist for session only, but I don't see any particular advantage to that.

**Comment by souravdebnath1986** [comment]
Setting reporting or analytics preferences is a separate purpose and hence a separate feature at an account or user level.  

For this date selection filter, we want to allow flexibility within the user session for the merchant user to flip between multiple date/state selections for their analysis exercise without reseting to the default selection always. 
We however don't want to persist the last selection at a user or merchant level. Why? - 
- Relevance: We always want to show the most relevant selection/state i.e. the merchant's recent payment activity over the `Last 7 days`. 
- Consistency: Persisting the last selection at a user or account level would be super confusing for the user the next time they login in specially if it is something like `All time` or `Last 12 months` or `Custom` (when we introduce it). We want merchant users to have a consistent experience every time they login. 
- Competitor analysis: Competitors like Stripe or Shopify follow same practices.
