### ISSUE TITLE
Improve help text in `Payments > Overview > Payment activity` card

### ISSUE THREAD

**Issue by souravdebnath1986** [Automattic/woocommerce-payments#8973]
### Description
The help texts associated with the tooltips in the `Payment activity` card can be simplified. 

### Acceptance criteria
* Simplify the TPV help icon text to: "Total payment volume is the sum of all transactions in a given time period, minus refunds and disputes."
* The help icon text for Fees can be changed to "Fees includes all types of fees charged by WooPayments. [Learn more](https://woocommerce.com/document/woopayments/fees-and-debits/fees/)."
* Clarify the help text icon in the disputes section: "Disputes includes the amount of any disputed charges. Dispute fees are included in the Fees section."

### Testing instructions
1. Go to Payments > Overview
2. Click on tool tips of TPV (Total Payment Volume), Fees and Disputes
3. Observe that the texts are as per the requirements

### Additional context
Mentioned in this [comment](https://github.com/Automattic/woocommerce-payments/issues/8737#issuecomment-2171361503)

**Comment by jessy-p** [comment]
<img width="343" alt="image" src="https://github.com/Automattic/woocommerce-payments/assets/32092402/b6f3d9d5-99d7-4f93-9c04-f352b901a2f4">
<hr/>
<img width="370" alt="image" src="https://github.com/Automattic/woocommerce-payments/assets/32092402/8d2362cb-072a-4eea-b66f-e4b66a698ab4">
<hr/>
<img width="668" alt="image" src="https://github.com/Automattic/woocommerce-payments/assets/32092402/8a4ce57b-99b9-4023-8918-650efada0314">

**Comment by haszari** [comment]
Updated the title to remove acronym so title is self-explanatory / clear :)
