### ISSUE TITLE
Possible issue with sandbox onboarding

### ISSUE THREAD

**Issue by dmallory42** [Automattic/woocommerce-payments#8990]
### Describe the bug

As mentioned in this Slack thread: p1718875622258119-slack-C03KTTK2YMA

There seems to be a possible issue with onboarding in sandbox mode in some cases

### To Reproduce

1. Use Jurassic Ninja to create a new site (this is necessary because it's not possible to test this flow with the Dev Tools plugin installed)
2. Install WooCommerce, go through the onboarding, and install WooPayments as part of this.
3. Click on the `Get Paid` task on the WooCommerce Home page.
4. On the WooPayments onboarding page, click "Setting up store for a client" and then `Enable sandbox`. 

### Expected behavior

When sandbox mode is enabled, via the onboarding wizard, the Stripe KYC should always be in test mode, meaning it is possible to enter fake test data to pass the onboarding.

### Actual behavior

There are some reports (see Slack link above) that sandbox mode isn't properly initialised, and the user is taken to a _live_ Stripe KYC.

I haven't been able to reproduce, but it may be worth testing with different store countries to see if that leads to reproducing the issue. In the Slack thread, it was onboarded as a merchant from the Netherlands.

**Comment by dmvrtx** [comment]
Steps that reproduced the issue for me, using Safari browser:

 - Create a JN site, without Jetpack, but with WooCommerce and WooPayments pre-installed.
 - Go to the site, it should start WooCommerce onboarding flow choosing, "I'm setting up a store for a client".
 - Start customisation step, click on "Start designing", then "Save" without changes.
 - Use "Back home" to get to the WooCommerce dashboard.
 - Click on the "Add products" CTA in the top panel.
 - Click on "More options" and then "Import sample product"
 - Go back to the dashboard. Top panel now has "Get paid" CTA. Click on it.
 - On the WooPayments page scroll to the bottom, open the "I'm building for the client" section and click on "Enable sandbox mode".
 - This should take to the WPCOM login page. Authorize and go through.
 - After a redirect a Stripe KYC flow appears, in the live mode (no "test mode" badges).

**Comment by anu-rock** [comment]
Setting a priority of low for now since it's not always reproducable as per the linked Slack thread.

**Comment by anu-rock** [comment]
Thanks for the report, @dmvrtx and @dmallory42 🙌

**Comment by dmallory42** [comment]
My suspicion here is the cause may be when we redirect to the Jetpack auth flow. When I tested, I did Jetpack auth as part of the WooCommerce Core profiler, so I redirected directly from WooPayments -> Stripe without going through Jetpack as an intermediate step.

**Comment by vladolaru** [comment]
Confirming that the bug happens when one onboards in sandbox mode _without_ having a Jetpack connection.
