### ISSUE TITLE
Tokenized PRB shortcode cart total update is delayed

### ISSUE THREAD

**Issue by mdmoore** [Automattic/woocommerce-payments#9000]
### Describe the bug

On the shortcode cart, after updating cart totals(quantity change, coupon, etc.) then subsequently clicking the PRB to open the payment interface, there is a delay before the total updates to the correct total. The old total is briefly displayed.

The delay occurs due to the [`updateCustomer` call](https://github.com/Automattic/woocommerce-payments/blob/a63d3b90c66df54f1b0395f478e206a9f36bca44/client/tokenized-payment-request/payment-request.js#L246) that happens when the payment interface opens for the first time after initialization. Because we have to re-initialize the PRB when cart totals update, that event will fire on the first button click after totals have updated. `cartData` needs to be updated also, when [cart totals update](https://github.com/Automattic/woocommerce-payments/blob/aac2f270fa282260326e5dc0677c80fed23353b3/client/tokenized-payment-request/index.js#L76), most likely via the  `wcpay.payment-request.update-button-data` hook. Something like this: 

```
$( document.body ).on( 'updated_cart_totals', async () => {
	doAction( 'wcpay.payment-request.update-button-data' );
	await waitForAction( 'wcpay.payment-request.update-button-data' );
	wooPaymentsPaymentRequest.init();
} );
```

### To Reproduce

1. Enable the "Enable Cart-Token implementation for PRBs" flag in your dev tools
2. Add a product to the cart
3. Visit the cart page
4. Update the item quantity and click update cart
5. Click the PRB and notice the pre-update total is briefly displayed before the correct total is displayed

### Actual behavior

The payment interface briefly displays an incorrect total before updating to the correct total.

### Screenshots

See the video [here](https://github.com/Automattic/woocommerce-payments/pull/8891#pullrequestreview-2124397374).

### Expected behavior

After clicking the PRB, the total displayed in the payment interface should be correct.

### Additional context

https://github.com/Automattic/woocommerce-payments/pull/8891#pullrequestreview-2124397374

**Comment by danielmx-dev** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Heisenberg-63586f2ec60359001310fa6a/issues/Automattic/woocommerce-payments/9000?planning-poker) with Zenhub @FangedParakeet
