### ISSUE TITLE
Replace payment method component with the one in core

### ISSUE THREAD

**Issue by dpaun1985** [Automattic/woocommerce-payments#9002]
After the node version will be updated from V16 to 20, we can remove the component created in #8977 as we can use the one from woocommerce core implemented [here](https://github.com/woocommerce/woocommerce/pull/48598). 
The one created here is a duplicate of the one in woocomerce core.

Context: p1718354100601209/1718353521.468869-slack-C03KTTK2YMA

**Comment by c-shultz** [comment]
I'm routing this to account lifecycle to go with https://github.com/Automattic/woocommerce-payments/issues/8808

**Comment by anu-rock** [comment]
Superseded by native onboarding work.
