### ISSUE TITLE
[ECE] Fix incorrect button widths

### ISSUE THREAD

**Issue by reykjalin** [Automattic/woocommerce-payments#9005]
## Description

> I think the width issue is a problem in Storefront. Stripe is doing some weird magic with their `iframe` that sets `margin: -4px` and then "makes up" the difference by setting `width: calc( 100% + 8px )` (where the 8px make up for the negative margin on either side).
>
> However, storefront sets `max-width: 100%` on `iframe`s which means those 8px never get made up, causing the issue. If I remove the `max-width` style the button is fine:
>
>
> https://github.com/Automattic/woocommerce-payments/assets/13835680/fd105a3b-546a-450a-bfe8-7d0b822e801c
>
> We could fix this by adding our own `max-width: calc( 100% + 8px ) !important` on the button, but I wonder if that wouldn't make things difficult for other themes. I'm honestly not sure where to fix this problem 😕 . It might even be on Stripe to make sure the width isn't more than 100%. I'll admit they way they're going about the width of the button is _odd_ and I have no idea why they do it this way.
>
> _Originally posted by @reykjalin in https://github.com/Automattic/woocommerce-payments/issues/8951#issuecomment-2183378659_

## Expected behavior

Buttons fill the container width.

## Actual behavior

Buttons are missing 16px from their width due to how Stripe calculates the width of the button.

## Suggested solution

Probably talk to Stripe? Setting the max-width of the button to be greater than the container is a weird approach, but maybe there's a good reason for it.

**Comment by bborman22** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Fractal-62a0f7b955648b001e1f5e1f/issues/Automattic/woocommerce-payments/9005?planning-poker) with Zenhub @asumaran @cesarcosta99 @lovo-h @rafaelzaleski @reykjalin @ricardo

**Comment by ricardo** [comment]
I contacted Stripe about this p1720833500937719-slack-C9976E5MJ, but also opened a PR with a simple fix.

**Comment by ricardo** [comment]
Stripe provided us with an update on this issue:

> @ricardo I was able to get an update from our elements team on this.
The negative margin is needed to prevent focus rings or borders being cut off, and it might be risky for us to change the way we are calculating it without a thorough investigation of underlying complexity.
We recommend moving forward with your workaround but we will add this to our backlog to investigate if we want to add the max-width:unset in the future.

p1720833500937719-slack-C9976E5MJ

As we have already merged the fix, no further actions needed from our end.
