### ISSUE TITLE
[ECE] Button max-height is 55px due to constraints in Stripe's API

### ISSUE THREAD

**Issue by reykjalin** [Automattic/woocommerce-payments#9006]
## Description

> I reacted too quickly to the 55px and didn't think of the repercussions to other gateway's buttons sizes which have slowly been adhering to our design guidelines. Let me spin up a conversation with @nikkivias and Stripe.
>
> _Originally posted by @pierorocca in https://github.com/Automattic/woocommerce-payments/issues/8951#issuecomment-2183177946_

This issue is mostly for tracking a resolution here. Either Stripe fix the maximum allowed height (we need it to be 56px to be consistent with previous designs), or we need to adjust the max height for all payment gateways.

**Comment by pierorocca** [comment]
As noted elsewhere, we'll need to move to 55px and the external design guideline are being updated to note the change.

**Comment by bborman22** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Fractal-62a0f7b955648b001e1f5e1f/issues/Automattic/woocommerce-payments/9006?planning-poker) with Zenhub @asumaran @cesarcosta99 @lovo-h @rafaelzaleski @reykjalin @ricardo
