### ISSUE TITLE
Try challenging a dispute will result in "Dispute not loaded" error

### ISSUE THREAD

**Issue by shendy-a8c** [Automattic/woocommerce-payments#9008]
### Describe the bug

Try challenging a dispute will result in "Dispute not loaded" error.
Request to `/wp-json/wc/v3/payments/disputes/du_abc` comes back as 404.

### To Reproduce

This is not easily to reproduce since the problem seems to be specific to certain format of dispute id.

### Actual behavior

Challenging a dispute whose id starts with `du_` result in "Dispute not loaded" error.

### Expected behavior

Dispute should be loaded fine.

### Additional context

Discovered from p1719255900379659-slack-C7U3Y3VMY.

Likely caused by https://github.com/Automattic/woocommerce-payments/pull/8901.
The problem might not be limited to only dispute that starts with `du_`, if dispute id does not start with `dp_` or `dispute_`, it might get the same error.
Also, problems might not only limited to dispute.

**Comment by shendy-a8c** [comment]
I can see possible solutions:
- Revert https://github.com/Automattic/woocommerce-payments/pull/8901 entirely.
- Allow dispute id to have `du_` prefix.
- Ease the validation for dispute id, maybe `(d.|dispute)_[A-Za-z0-9]+`.

Do we know all possible prefix Stripe might use for dispute (and other objects as well) id?

What do you think @deepakpathania @Automattic/helix?

**Comment by haszari** [comment]
> Option 1: Revert https://github.com/Automattic/woocommerce-payments/pull/8901 entirely.

Great default option – that's the quickest and pretty low risk (we can revisit the validation in next release). But maybe risk since there are lots of other route validators.

> Option 1a: Revert dispute id validation only (from https://github.com/Automattic/woocommerce-payments/pull/8901 )

Benefits of 1 with less risk/disruption.

> Option 2: Allow dispute id to have du_ prefix AND/OR Ease the validation for dispute id, maybe (d.|dispute)_[A-Za-z0-9]+.

This might be enough but it will be very frustrating if we find a different pattern after we ship the patch. 

I'm happy with either of the above approaches. 

Some considerations:

- Can we quickly determine if all the affect tickets see `du_` prefix? If so option 2 probably fine.
- Can we ask Stripe what prefixes are available? If so, option 2 probably fine.
- Is there any risk that other route validation might be too strict? If so, option 1 is best.

I have a slight preference for option 1a since it's quick, targeted to the specific pain point, we can get back to project focus quicker, and revisit the validation later and with more care/research.

**Comment by brucealdridge** [comment]
A quick search doesn't reveal any resource from Stripe that lists valid in-use object prefixes. 

https://gist.github.com/fnky/76f533366f75cf75802c8052b577e2a5 notes many of the prefixes that stripe uses but misses `dispute_` `du_` (which is mentioned in the comments)

Without clear direction from Stripe or the docs, restricting based on prefixes will likely cause future issues as these could change at any time.

I'll prep a PR for Option 1a and would recommend removing all prefix checks at a later date.

**Comment by haszari** [comment]
> I'll prep a PR for Option 1a and would recommend removing all prefix checks at a later date.

Thank you @brucealdridge ! If all these checks are dubious, maybe it's cleaner and safer to do a straight revert (and follow up issue to possibly reinstate regex checks carefully). Your call (and of course will be discussed on PR).

**Comment by Jinksi** [comment]
> Without clear direction from Stripe or the docs, restricting based on prefixes will likely cause future issues as these could change at any time.

As per [Stripe docs](https://docs.stripe.com/upgrades#what-changes-does-stripe-consider-to-be-backwards-compatible), changing ID prefixes is considered backwards compatible:

> Stripe considers the following changes to be backwards-compatible:
> 
> Changing the length or format of opaque strings, such as object IDs, error messages, and other human-readable strings.
> **This includes adding or removing fixed prefixes (such as `ch_` on charge IDs).** ⚠️

**Comment by Jinksi** [comment]
> maybe it's cleaner and safer to do a straight revert 

➕ Therefore I suggest we straight revert and consider a different approach for all IDs in a followup issue.

**Comment by shendy-a8c** [comment]
Fixed by https://github.com/Automattic/woocommerce-payments/pull/9009.
