### ISSUE TITLE
[Spike] Implement new component to render SVGs

### ISSUE THREAD

**Issue by dpaun1985** [Automattic/woocommerce-payments#9029]
When implementing #8808 , we noticed that the bundle size increased  when SVGs are rendered as React components.
One of the solutions suggested in pe4Hk0-1d6-p2#comment-1459 is to implement a new component to render the SVGs  through an SVG map.

We need to identify if we can and how to implement the component in order to be used for #8808  in:
1. woocommerce payments
2. woocommerce core 

The purpose of #8808 is to implement a component for the payment method icons, that can be re-used in different places, having consistency across all places.

The PRs implementing the component are: #8977 and [#48598 ](https://github.com/woocommerce/woocommerce/pull/48598)

A SVG component similar to what we need is already implemented in wcpay: https://github.com/Automattic/woopay/blob/4f16439719d375cea68ec54120edd38cac471bf9/svgs/README.md

Details about the SVG component : https://github.com/Automattic/woocommerce-payments/issues/8808#issuecomment-2194171272 and pe4Hk0-1d6-p2#comment-1459

**Comment by mordeth** [comment]
This spike can be closed since we’ve found a way to exclude the SVG-in-JS from the bundle.
