### ISSUE TITLE
Migrate dispute evidence form to use wp.data

### ISSUE THREAD

**Issue by dechov** [Automattic/woocommerce-payments#903]
The evidence form should be updated from component-local state to the client-side persistence layer that uses wp.data.

A couple of considerations, from https://github.com/Automattic/woocommerce-payments/issues/331#issuecomment-642368244:

> The evidence screen may be somewhat more complicated due to having more state and interaction to deal with. (We could consider continuing with `useState` for some of the lower-level stuff.)

> Ultimately we'll probably want a separate selector (and resolver) for the evidence, even if it reads and writes to the same bit of the state tree, because we plan to cache dispute info on the server but without evidence (see 273-gh-woocommerce-payments-server). In most cases, the dispute (info-only) data will already be available when navigating to the evidence screen, so ideally we'd use both selectors on the "Challenge dispute" screen. This means it would fire off two requests when loading the evidence screen initially, but I think we should be able to avert that by selecting the evidence first, having the resolver `startResolution` on the info-only selector, and just `finishResolution` on it after the fetch.

**Comment by vbelolapotkov** [comment]
Note: the work on the issues was [started by Kris](https://github.com/Automattic/woocommerce-payments/pull/2757) but deprioritized, so moving issue into core backlog for prioritization purposes.

It could be a good idea to continue work based on existing PR: https://github.com/Automattic/woocommerce-payments/pull/2757

**Comment by Jinksi** [comment]
Closing with the assumption that this will be refactored as part of a project to redesign the challenge form UX which is on the Helix roadmap.
