### ISSUE TITLE
Implement error logging in ECE

### ISSUE THREAD

**Issue by cesarcosta99** [Automattic/woocommerce-payments#9049]
Currently, the Express Checkout Element (ECE) implementation lacks error logging in some critical parts (e.g. [here](https://github.com/Automattic/woocommerce-payments/blob/05e7d8629eefb351b15a57e9af609781e5fa21e9/includes/express-checkout/class-wc-payments-express-checkout-ajax-handler.php#L66) and [here](https://github.com/Automattic/woocommerce-payments/blob/05e7d8629eefb351b15a57e9af609781e5fa21e9/includes/express-checkout/class-wc-payments-express-checkout-ajax-handler.php#L128-L131), and in the frontend in general). We plan to add error logging to monitor ECE and improve our debugging capabilities.

### Acceptance criteria

Implement error logging across all critical parts of the ECE implementation, including backend and frontend, ensuring that all errors and exceptions are properly captured and logged.

**Comment by bborman22** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Fractal-62a0f7b955648b001e1f5e1f/issues/Automattic/woocommerce-payments/9049?planning-poker) with Zenhub @asumaran @cesarcosta99 @lovo-h @rafaelzaleski @reykjalin @ricardo
