### ISSUE TITLE
A bullet appears in the WooPay button on Safari

### ISSUE THREAD

**Issue by reykjalin** [Automattic/woocommerce-payments#9068]
## Describe the bug

Originally discovered in https://github.com/Automattic/woocommerce-payments/issues/8951#issuecomment-2179646209.

## To Reproduce

> [!IMPORTANT]
> This may only be happening with the ECE elements enabled, in which case you have to enable them via `npm run wp option set _wcpay_feature_stripe_ece 1`.

1. Enable WooPay.
2. Go to any page the WooPay button appears on.
3. Notice there is a bullet in the WooPay button:

## Actual behavior

There is a bullet in the WooPay button.

## Screenshots

<img width="452" alt="image" src="https://github.com/Automattic/woocommerce-payments/assets/13835680/faa226fa-c981-416c-8b5d-ddf9047739ae">

## Expected behavior

There should be no bullet in the WooPay button.

## Desktop (please complete the following information):

* OS: macOS Sonoma Version 14.5 (23F79)
* Browser Safari
* Version 17.5 (19618.2.12.11.6)

## Additional context

I tried to fix this but couldn't. The bullet behaves in a very weird way too, where it'll disappear when you disable a setting in the devtools, but it won't reappear when you reenable that same setting. See https://github.com/Automattic/woocommerce-payments/issues/8951#issuecomment-2183475932 for details.

**Comment by reykjalin** [comment]
FYI @pierorocca also opened an issue to track the bullet appearing in the WooPay button on Safari.

**Comment by ricardo** [comment]
Also, there's a bigger space between buttons in Safari, which appears to be fixed with `list-style: none`, so hopefully we can fix the bullet and the spacing with the same CSS.

p1721071385574529/1721042476.523939-slack-C01BZUL57SQ
