### ISSUE TITLE
VAT Invoice reports cannot be downloaded: "There was an error accessing the document..."

### ISSUE THREAD

**Issue by francoishvz** [Automattic/woocommerce-payments#9083]
### Describe the bug

Merchants are unable to access VAT Invoice reports via emails or through **Payments > Documents**.

They see the following error instead:

`There was an error accessing the document vat_invoice_fde7mtwo7qoqt5-hmHmf2g. Validation of the route parameter failed.`

### Expected behavior

Merchants should be able to access VAT invoices via email and documents tab.

### Additional context

8468603-zd-a8c
p1720704694309099-slack-C01BPL3ALGP

**Comment by francoishvz** [comment]
8468022-zd-a8c
8468641-zd-a8c
8467633-zd-a8c

**Comment by zoupkat** [comment]
Another case 8468334-zd-a8c

**Comment by jessepearson** [comment]
Version 7.9.1 has been released, which should fix this issue.
