### ISSUE TITLE
Saved cards: Copy customer ID and card ID on click

### ISSUE THREAD

**Issue by luizreis** [Automattic/woocommerce-payments#910]
Child of #908

Depends on #909 

See paJDYF-Kq-p2 for more details.

Merchants should be able to copy the Customer and Card IDs by clicking on them. A tooltip should be displayed indicating that clicking on the item copies its value.

![image](https://user-images.githubusercontent.com/7714042/93265747-7095e380-f77f-11ea-9a81-f7c5e447d67d.png)

**Comment by zmaglica** [comment]
Closing for now. More info can be found [here](https://a8c.slack.com/archives/C02L752DS0G/p1643975980351219).
