### ISSUE TITLE
[ECE] Disable the "Proceed to checkout" button in the Cart block while payment sheet is open and while the payment is being processed

### ISSUE THREAD

**Issue by reykjalin** [Automattic/woocommerce-payments#9100]
## Describe the bug

When ECE is enabled clicking the Google Pay and Apple Pay buttons doesn't disable the **Proceed to checkout** button in the Cart Block. This allows a customer to click the **Proceed to checkout** button before they're redirected to the order confirmation page when paying with Google Pay or Apple Pay from the Cart Block.

## To Reproduce

1. Add a product to your cart.
2. Go to a page with the Cart block present.
3. Click the Google Pay or Apple Pay button.
4. Authorize a payment in the payment sheet.
5. Notice that the **Proceed to checkout** button isn't disabled. You can even click it before being redirected to the order received page.

## Actual behavior

The **Proceed to checkout** button isn't disabled.

## Screenshots

https://github.com/user-attachments/assets/27ada72c-697d-43d7-a335-e02a61d41d5f

## Expected behavior

The **Proceed to checkout** button is disabled.

## Desktop (please complete the following information):

* OS: macOS Sonoma 14.5
* Browser Arc (Chromium based)
* Version 1.51.0 (51691) - [Chromium Engine Version 126.0.6478.127]

**Comment by bborman22** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Fractal-62a0f7b955648b001e1f5e1f/issues/Automattic/woocommerce-payments/9100?planning-poker) with Zenhub @cesarcosta99
