### ISSUE TITLE
Fix WooPay opt-in layout

### ISSUE THREAD

**Issue by leonardola** [Automattic/woocommerce-payments#9102]
### Describe the bug
WooPay opt-in check box is too close to the add a note to order checkbox in the latest WooCommerce. Also the design does not fully match the figma ones 2JyXNimI4oGeJZhgQNZE9V-fi-1143%3A9115

### To Reproduce
- Install WooCommerce 9.1.2
- Add products to your cart
- Visit the blocks checkout page
- The WooPa opt-in checkbox will look like this:
<img width="530" alt="Screenshot 2024-07-16 at 11 12 11" src="https://github.com/user-attachments/assets/05805209-fc91-4e6c-9231-8028dc8aa5b6">

While it should look like this:
<img width="473" alt="Screenshot 2024-07-16 at 11 16 09" src="https://github.com/user-attachments/assets/b631baae-1e59-4dfe-bf50-277cd822667a">

### Additional context
Design Figma file:
2JyXNimI4oGeJZhgQNZE9V-fi-1143%3A9115

**Comment by pierorocca** [comment]
@leonardola there's also a formatting issue when the phone number is autofilled. It's fine when key entered.

![image](https://github.com/user-attachments/assets/e0de8621-3f81-4620-b400-ed5de1349222)
