### ISSUE TITLE
[ECE] Checkout fails for physical subscription product if no shipping methods are configured

### ISSUE THREAD

**Issue by ricardo** [Automattic/woocommerce-payments#9106]
### Describe the bug

For simple or variable non-virtual subscription products, the checkout fails with the following error if no shipping methods are configured:

> The following problems were found: The payment request button is not supported in United States (US) because some required fields couldn't be verified. Please proceed to the checkout page and try again. Shipping First name is a required field. Shipping Last name is a required field. Shipping Country / Region is a required field...

It looks like the core checkout expects a shipping address, but ECE is not providing it.

This works when testing the PRB implementation, so this is a regression in the ECE implementation.

### To Reproduce

1. Enable the ECE flag.
2. As a merchant, remove all shipping zones and shipping methods for "Rest of the world".
3. Create a simple physical subscription product.
4. As a shopper, navigate to the product page.
5. Try to checkout using Google Pay or Apple Pay.
6. Notice the error "The following problems were found: The payment request button is not supported..."
7. Disabling the ECE flag and testing with PRB should work.

### Expected behavior

Checkout with ECE should work for physical subscription products as it does with PRB.

**Comment by asumaran** [comment]
@ricardo I couldn't re produce this. The store won't allow me to buy a physical product if there's no shipping options defined. I've tested with simple products and subscriptions.

I wonder if we should disable ECE for all products that require shipping if there's no shipping options defined.

**Comment by ricardo** [comment]
> The store won't allow me to boy a physical product

@asumaran What happens when you try?

I tested with [this product](https://ece-test-1.mystagingwebsite.com/product/monthly-gourmet-coffee-subscription/). No shipping zones or shipping methods. No tax enabled.

https://github.com/user-attachments/assets/bf56e8f2-7351-45e8-92ea-7e5abbc6cb60

**Comment by asumaran** [comment]
> @asumaran What happens when you try?

@ricardo I can't using ECE. If I try via the regular checkout form I get this error:
<img width="436" alt="image" src="https://github.com/user-attachments/assets/f7dabc5a-06a6-4593-bd3f-b97fac6e63d4">
