### ISSUE TITLE
Upgrade node support to version 20

### ISSUE THREAD

**Issue by danielmx-dev** [Automattic/woocommerce-payments#9116]
### Description
Currently, the supported node version is set to `v16` in both `.nvmrc` and `package.json`. According to the current release schedule https://nodejs.org/en/about/previous-releases, v16 is out of maintenance mode, with v20 being the active LTS version.

Since WooCommerce Core already performed the upgrade to v20 a few months ago https://github.com/woocommerce/woocommerce/pull/45148 we should do the same for WooPayments.

### Acceptance criteria

* All the functionality must remain the same.
* All tests must pass.
* All scripts defined in `package.json` should still work as expected.

### Testing instructions

- All tests, checks, and scripts should pass after the upgrade
- Functionality should be unchanged.

### Additional context
* This issue currently blocks #8581 
* The GH actions will be upgraded as part of a separate issue: #8129

**Comment by FangedParakeet** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Heisenberg-63586f2ec60359001310fa6a/issues/Automattic/woocommerce-payments/9116?planning-poker) with Zenhub @danielmx-dev
