### ISSUE TITLE
Address 2px height difference between WooPay and Google Pay

### ISSUE THREAD

**Issue by bborman22** [Automattic/woocommerce-payments#9137]
### Describe the bug

The bug description is pulled from this [comment](https://github.com/Automattic/woocommerce-payments/pull/9117#pullrequestreview-2184383267).

For some reason the WooPay button at 55px is smaller than the Google Pay ECE button at 55px???

![Screenshot 2024-07-19 at 10 41 02 AM](https://github.com/user-attachments/assets/195da577-1b2e-4d9c-994c-3f633678eab5)

Both are 55px according to the dev tools. Maybe the ECE buttons don't take the border into account so a 1px border means the end result is a height of 57px? That seems to be right:

![Screenshot 2024-07-19 at 10 41 07 AM](https://github.com/user-attachments/assets/e0c3922e-bfb9-4e3e-9da8-d3a5d6978b6d)

Setting the max-height of the container to 55px results in an obvious cut-off:

![Screenshot 2024-07-19 at 10 41 12 AM](https://github.com/user-attachments/assets/3eb52171-117f-43ac-9e5e-b1402d377a52)

It's only just barely noticable when they're side-by-side.

This issue only applies when the Light or Outline theme is chosen for the express checkout settings. The easiest solution is to adjust the WooPay button height to 57px when Light or Outline theme is selected, but it might be worth following up with Stripe to confirm this is the intended behavior.

### To Reproduce

1. Enable both WooPay and Google Pay / Apple Pay.
2. From the express checkout settings choose the Large (55px) option for button size.
3. From the express checkout settings choose the Light or Outline theme for buttons.
4. Load the checkout blocks page in Chrome (so there is only two buttons).
5. Confirm that there is a 2px height difference between the buttons.

### Actual behavior

The button heights are different by 2px with Google Pay being larger than WooPay.

### Expected behavior

The button heights should be the same in all themes and button sizes.

**Comment by bborman22** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Fractal-62a0f7b955648b001e1f5e1f/issues/Automattic/woocommerce-payments/9137?planning-poker) with Zenhub @asumaran @cesarcosta99 @lovo-h @rafaelzaleski @reykjalin @ricardo

**Comment by reykjalin** [comment]
Hmmm, maybe we can fix this _somehow_ with the `box-sizing` CSS rule?

**Comment by asumaran** [comment]
<img width="492" alt="Screenshot 2024-08-12 at 2 50 33 PM" src="https://github.com/user-attachments/assets/616f9187-e7e7-4e24-a9e6-0f5a34273a92">

It's seems Stripe is hardcoding the element height to `48px` for Google Pay only.

Edit: This seems correct as the button size I'm using is `48px`

**Comment by asumaran** [comment]
I'm going to pick this one and fix it as part of https://github.com/Automattic/woocommerce-payments/issues/9169

**Comment by jaclync** [comment]
This still seems like an issue in 10.9.0, and Stripe extension just fixed the same issue in https://github.com/woocommerce/woocommerce-gateway-stripe/pull/5708. Is it worth re-opening this?

<img width="805" height="198" alt="Image" src="https://github.com/user-attachments/assets/bd7a3aa9-5c98-49ca-90c8-843f3abe8281" />

The 2px offset still exists in [code](https://github.com/Automattic/woocommerce-payments/blob/6d85940948da/client/express-checkout/utils/payment-method-overrides.ts#L67-L73).
