### ISSUE TITLE
Saved cards: Delete a payment method

### ISSUE THREAD

**Issue by luizreis** [Automattic/woocommerce-payments#914]
Child of #908

See paJDYF-Kq-p2 for more details.

Merchants should be able to remove a payment method by clicking the trash can icon:
- They should be prompted with a simple JS alert confirming the deletion.
- If a default card is removed, the next card in the list will become the new default.

**Comment by zmaglica** [comment]
Closing for now. More info can be found [here](https://a8c.slack.com/archives/C02L752DS0G/p1643975980351219).
