### ISSUE TITLE
Clearly communicate card declines as such

### ISSUE THREAD

**Issue by dechov** [Automattic/woocommerce-payments#9156]
When a card is declined, the error response from the API contains an `error` code of "card_declined", a `decline_code`, and a `message` describing the decline reason. We appear to just present the latter, without an explicit acknowledgement of the initial fact that the card was declined. It might be acceptable to keep it implicit in most cases, since certain common scenarios would be understood to describe declines:

Front-end (shopper-facing):
<img width="321" alt="card-declined-shopper-message" src="https://github.com/user-attachments/assets/8551ed1a-4878-42d7-ae03-567a7e33c5be">

Admin (merchant-facing):
<img width="299" alt="card-declined-merchant-message" src="https://github.com/user-attachments/assets/e452ab47-56d5-4e07-94d4-ba4ea8f0944d">

However, some messages (codes listed [here](https://docs.stripe.com/declines/codes)) are more ambiguous, such as "Invalid account" – without the context of it being a decline, it could be (and has been, anecdotally) interpreted as something more to do with the merchant account, and it could be helpful to prefix the message to suit this particular "card_declined" error case.

**Comment by dechov** [comment]
https://github.com/Automattic/woocommerce-payments/issues/8642 is related – it don't think we currently show a generic decline message, except perhaps in the case of the "generic_decline" `decline_code`, but that `seller_message` from the charge outcome might be helpful to display.

**Comment by htdat** [comment]
Closed by #9934
