### ISSUE TITLE
Checkout: Handle errors from endpoint POST /v1/payment_methods

### ISSUE THREAD

**Issue by htdat** [Automattic/woocommerce-payments#9177]
### Describe the bug

Currently, after shoppers fill out card details and submit the "Pay now" button, a `POST /payment_methods` request is sent. 

This can create an error (decline) right away and shoppers are aware about that in the checkout page. However, merchants do not have any visibility about this failure.

### To Reproduce

Currently, this is not possible to reproduce in the test/dev mode. However, that's possible if using a test card for the test mode in a live mode. 

### Actual behavior

Merchants have no idea about this attempt, and no order is created in WP Admin. 

### Expected behavior

Merchants are aware about this error. They expect to see an order created in WP Admin, or at least an entry in the WooPayments log. 

### Dev notes 

Here is the current flow: 

1. Customer adds products, and goes to the checkout page.
2. Customer submits card details, then WooPayment uses Stripe JS to submit these raw card details to `POST /v1/payment_methods`
3. Stripe returns a payment method ID `pm_random_string`.
4. WooPayents use this payment method to submit this order thorugh the Woo core checkout process i.e. to `/?wc-ajax=checkout `for the classic checkout.
5. On the PHP side of the merchant side: a new order is created, a payment intent creation request is sent to the WooPayments server.

However, in these failed cases, the process above is terminated at step 2, as Stripe did not return any payment method ID. Therefore, the checkout page also relays the same/similar error message, i.e. `Your card has been declined` and no order is created/udpated.

### Additional context

- Originally reported in p1721152035596249-slack-C7U3Y3VMY
- More details 3533d-pb

**Comment by pierorocca** [comment]
@FangedParakeet @c-shultz for extra awareness.

**Comment by FangedParakeet** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Heisenberg-63586f2ec60359001310fa6a/issues/Automattic/woocommerce-payments/9177?planning-poker) with Zenhub @danielmx-dev
