### ISSUE TITLE
Possible bug with Store API requests and MultiCurrency

### ISSUE THREAD

**Issue by dmallory42** [Automattic/woocommerce-payments#9181]
### Describe the bug

Relates to this slack thread: p1722254839910269-slack-C7U3Y3VMY

In short: when Multi Currency is enabled in WooPayments, requests made to the Store API, e.g. `https://<store-url>/wp-json/wc/v2/products/<product_id>` return the amount based on the _customer session_, rather than returning in base store currency.

### To Reproduce

1. Enable Multi Currency in WooPayments, and add at least one extra currency. In my case, GBP was my store default currency and I added EUR as an extra currency.
2. Create a product and make a note of the price in your default currency.
3. Edit the site using the Blocks Editor to add a "Currency Switcher" block somewhere on the page.
4. Go to the store as if you are a customer and use the currency switcher block to change the display currency to EUR.
5. Make an API request to ``https://<store-url>/wp-json/wc/v2/products/<product_id>`
6. The price of the product will display in EUR.

### Expected behaviour

I believe the product price should display in the store default currency when using the REST API. Display currencies should only be for frontend requests.

### Screenshots

In this case, the product should be £10 in my store, but it's displaying as 12 EUR

<img width="809" alt="Screenshot 2024-07-29 at 16 34 41" src="https://github.com/user-attachments/assets/a40acd5a-9880-4733-a97b-a3b3a5695663">

### Additional context

We use this logic to disable conversions on Admin API requests: https://github.com/Automattic/woocommerce-payments/blob/2101d7620b84699e0dd816f4a886be42e5261d91/includes/multi-currency/Utils.php#L59

We should consider adding similar logic for Store API requests.

**Comment by bborman22** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Fractal-62a0f7b955648b001e1f5e1f/issues/Automattic/woocommerce-payments/9181?planning-poker) with Zenhub @asumaran @cesarcosta99 @lovo-h @rafaelzaleski @reykjalin @ricardo

**Comment by ricardo** [comment]
This appears to be related to https://github.com/Automattic/woocommerce-payments/pull/8816 – in that case, it may not be a bug as they made it so that the Store API also implements MCCY – but it's up to the person assigned to the issue to determine in detail.
