### ISSUE TITLE
Multiple payment method saving checkboxes

### ISSUE THREAD

**Issue by c-shultz** [Automattic/woocommerce-payments#9186]
### Describe the bug
<img width="646" alt="image" src="https://github.com/user-attachments/assets/975c866a-fa9b-4437-a62b-6e5b0bdc1db7">

Two payment method saving checkboxes are displayed at the same time.

### To Reproduce

1. Sign into a merchant's store with a shopper account
2. Go to checkout
3. Enter email that does NOT have a WooPay account
4. See both checkboxes present on checkout

### Expected behavior
Only WooPay's checkbox should be visible in this case.

Expected behavior from @pierorocca:
Store - signed out, WooPay - not known user -> Show WooPay checkbox.
Store - signed out, WooPay - signed in -> Show no checkboxes
**Store - signed-in, WooPay - not known user -> Show WooPay checkbox (currently showing both)**
Store - signed-in, WooPay - signed in-> Show no checkboxes or show store checkbox? (currently showing store checkbox)

**Comment by pierorocca** [comment]
Updated state list and requirements:

### **Shopper State List**

**Signed-out of store**
1. WooPay - not a user                 -> Show WooPay checkbox
2. WooPay - user, not signed-in  -> Show WooPay checkbox
3. WooPay - user, signed in         -> Show no checkboxes

**Signed-in to store**

1. WooPay - not a user                  -> Show WooPay checkbox (currently showing both)
2. WooPay - user, not signed-in   -> Show no checkboxes (currently showing both)
3. WooPay - user, signed-in          -> Show no checkboxes (currently showing store checkbox)

**WooPay not enabled**
- Show store save info checkbox when signed in to store (current behavior)

**Notes:**
- Sign-out of store - these are all current behavior. Leave as is.
- Signed in to store - The proposed matches Shopify behavior. One difference is they will trigger OTP flow if email is pre-populated. We’ve disabled this, however, we’ll test this in the future once we’ve enabled A/B testing to see which performs better.

User determination is based on cookie identification and email identification.

**Comment by pierorocca** [comment]
Hopefully this is more clear @alefesouza. 

![image](https://github.com/user-attachments/assets/7465d7bc-5755-4c7f-a5a2-c001dcfb2f50)

You're correct, the only time they'll see a save card to store option is if WooPay is disabled. 

**Special case 1**: If a shopper is on checkout, is not signed into WooPay, and the email field is blank, show the WooPay checkbox. If the shoppers adds an email that is a WooPay email, and the OTP is triggered and they close it, remove the WooPay checkbox. 

**Special case 2**: If a shopper is on the WooPay checkout and clicks "alternative payment methods" and is returned to the store checkout, do not show any checkboxes.
