### ISSUE TITLE
Update inline notification component in the Express Checkout settings

### ISSUE THREAD

**Issue by pierorocca** [Automattic/woocommerce-payments#9193]
### Description
Back in 2023 we updated the notifications and snackbar components related to WooPay shopper and merchant UI/UX. Shortly after design updated the wp-admin inline notification component design. This specific notification remains on the old design and needs to be updated.

Old component
![image](https://github.com/user-attachments/assets/6b42479c-b213-431c-be43-6b38d4112d29)

New Component
![image](https://github.com/user-attachments/assets/6493f88d-3bf3-496f-b18e-9f5f9581ce83)

### Acceptance criteria
Inline notification on the WooPay and Google/Apple Pay settings screen is updated to the new component design

**Comment by bborman22** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Fractal-62a0f7b955648b001e1f5e1f/issues/Automattic/woocommerce-payments/9193?planning-poker) with Zenhub @asumaran @cesarcosta99 @lovo-h @rafaelzaleski @reykjalin @ricardo
