### ISSUE TITLE
Updating to 8.0 causes the website to crash if you have PayPal payments active

### ISSUE THREAD

**Issue by carolframen** [Automattic/woocommerce-payments#9197]
### Describe the bug
After updating to 8.0 several users reported there was a critical error on their website. I was able to replicate this on my website if I have PayPal payments active.

Tried with only Woo active and the issue did not happen. 

### To Reproduce
Update to 8.0 while having WooCommerce PayPal Payments active
Or activate PayPal Payments after updating to 8.0

### Actual behavior
The website crashed

### Screenshots
![image](https://github.com/user-attachments/assets/ff74fcae-d3ca-4257-86c8-3a7295178796)

### Expected behavior
For the website to not crash.

### Desktop (please complete the following information):

* OS: Windows 11
* Browser Chrome
* Version 127

WooCommerce 9.1.4
WooCommerce PayPal Payments: 2.8.2
Theme: Storefront

### Additional context
https://wordpress.org/support/topic/site-crashes-after-update-4/#post-17924925 → several reports here

**Comment by carolframen** [comment]
Another report [here ](https://wordpress.org/support/topic/site-crashes-after-8-0-0-update-incompatibility-to-yaymail-and-germanized/) mentions issues with other plugins.

[YayMail – WooCommerce Email Customizer](https://yaycommerce.com/yaymail-woocommerce-email-customizer/)
[Germanized](https://vendidero.de/woocommerce-germanized)

**Comment by carolframen** [comment]
Another report: https://wordpress.org/support/topic/woopayments-8-0-kills-3rd-party-payment-methods/

**Comment by c-shultz** [comment]
This is the same report as #9195, so I'll close this issue. The team has created a fix and is actively deploying a patch to address this.
