### ISSUE TITLE
[ECE] Google Pay missing on Cart and Checkout pages in Safari.

### ISSUE THREAD

**Issue by pierorocca** [Automattic/woocommerce-payments#9202]
### Describe the bug
On Blocks, Google Pay is not displayed on the Cart and Checkout but is on the PDP.

![image](https://github.com/user-attachments/assets/9d0d9ae7-8324-4760-8445-4f0e3d0f83ee)

### To Reproduce
Safari on desktop, signed into Google Pay with an active account.

### Expected behavior
1. Google Pay is visible on Cart and Checkout when eligible.

**Comment by bborman22** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Fractal-62a0f7b955648b001e1f5e1f/issues/Automattic/woocommerce-payments/9202?planning-poker) with Zenhub @asumaran @cesarcosta99 @lovo-h @reykjalin

**Comment by pierorocca** [comment]
Adding a note that `paymentMethods.googlePay` and `paymentMethods.applePay` are to be set to `always` instead of `auto`. While Stripe's rationale for hiding the buttons to optimize conversion is a good one from a shopper perspective, without a merchant setting to enable/disable it, merchants have no way to know the button hiding is occurring. And I suspect is hard to test as well.
