### ISSUE TITLE
E2E GH actions fail when using Ubuntu 22.04 image (20240730) during env setup: `docker-compose: command not found`

### ISSUE THREAD

**Issue by Jinksi** [Automattic/woocommerce-payments#9205]
### Description

The E2E Playwright tests GH action _sometimes_ fails during env setup: `docker-compose: command not found`. 

```
https://github.com/Automattic/woocommerce-payments/actions/runs/10215251265/job/28264296577#step:1:8

Runner Image
  Image: ubuntu-22.04
  Version: 20240730.2.0
  Included Software: https://github.com/actions/runner-images/blob/ubuntu22/20240730.2/images/ubuntu/Ubuntu2204-Readme.md
  Image Release: https://github.com/actions/runner-images/releases/tag/ubuntu22%2F20240730.2

> woocommerce-payments@8.0.1 test:e2e-setup
  > ./tests/e2e/env/setup.sh
  
  ===> Fetching dev tools
  Cloning into '/home/runner/work/woocommerce-payments/woocommerce-payments/tests/e2e/deps/wcp-dev-tools'...
  
  ===> Starting CLIENT containers
  ./tests/e2e/env/shared.sh: line 24: docker-compose: command not found
```

This is occurring during the execution of this file: https://github.com/Automattic/woocommerce-payments/blob/80e6144ca9d40ff72629f945bf6c71b8ff286805/tests/e2e/env/setup.sh#L106-L107

As @danielmx-dev mentioned below, the GH actions that are run on a more recent image (in this case `Version: 20240730.2.0`) will always fail. We should migrate to Docker Compose v2: [docs.docker.com/compose/migrate](https://docs.docker.com/compose/migrate/).

The GH actions image we use [Ubuntu 22.04 20240730 release](https://github.com/actions/runner-images/releases/tag/ubuntu22%2F20240730.2) links to the following issue:

[**[Ubuntu, Windows] Docker Compose v1 will be removed from images on July, 29**](https://github.com/actions/runner-images/issues/9692)

### Additional context

See a list of The E2E Playwright test GH action runs: 

https://github.com/Automattic/woocommerce-payments/actions/workflows/e2e-pw-pull-request.yml.

Examples of recently failed runs due to this issue:

https://github.com/Automattic/woocommerce-payments/actions/runs/10205112195/job/28235151754?pr=9175#step:4:483 
https://github.com/Automattic/woocommerce-payments/actions/runs/10201953778/job/28225014486?pr=9203#step:4:478

### Priority

Low priority: optional e2e test, workaround is to re-run.

> [!Important]
> Please, ensure when closing this issue (PR fix) that only one `e2e: broken` label is added and it is accurate.
> - [x] I confirmed there's only one `e2e: broken` label in this issue and it is accurate.

**Comment by danielmx-dev** [comment]
Please note that this is also affecting E2E tests. See this failed run: https://github.com/Automattic/woocommerce-payments/actions/runs/10215251265/job/28264296577

From what I see, the difference between a failed and a successful run is the runner image version. The ones running on a more recent image (in this case `Version: 20240730.2.0`) will always fail.

I think it should be safe to assume that eventually Github Actions will stop supporting Compose V1 completely, so we should consider migrating sooner rather than later https://docs.docker.com/compose/migrate/

**Comment by Jinksi** [comment]
Thanks @danielmx-dev

The GH actions image we use [Ubuntu 22.04 20240730 release](https://github.com/actions/runner-images/releases/tag/ubuntu22%2F20240730.2) links to the following issue:

[**[Ubuntu, Windows] Docker Compose v1 will be removed from images on July, 29**](https://github.com/actions/runner-images/issues/9692)
