### ISSUE TITLE
User event is tracked even though WooPayments is disabled as a payment method

### ISSUE THREAD

**Issue by ricardo** [Automattic/woocommerce-payments#9208]
### Describe the bug

Initially reported in https://github.com/Automattic/woocommerce-payments/pull/9203#issuecomment-2264887577.

If WooPayments is enabled, but the gateway is disabled as a payment method, we have at least [one active listener](https://github.com/Automattic/woocommerce-payments/blob/daf84cd20041bb4c67462455c49ab230cca87f1c/client/cart/index.js#L9-L15) trying to record tracks events. It fails to do so as the gateway does not provide other variables.

As part of this issue, we may want to check if there aren't other instances of this happening.

### To Reproduce

1. As a merchant, navigate to **Payments > Settings** and uncheck "Enable WooPayments".
2. As a shopper, add a product to the cart.
3. Navigate to the cart page and open the Network tab.
4. Click the "Proceed to checkout" button.
5. Notice a 404 request to `cart/null` with `tracksEventName: wcpay_proceed_to_checkout_button_click`.

### Screenshots

https://github.com/user-attachments/assets/d6b6f797-2464-4f94-bc5e-a3d6edafea34

### Expected behavior

The plugin should not attach event listeners of this type if WooPayments is disabled as a payment method.

**Comment by bborman22** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Fractal-62a0f7b955648b001e1f5e1f/issues/Automattic/woocommerce-payments/9208?planning-poker) with Zenhub @lovo-h @ricardo

**Comment by anu-rock** [comment]
This issue is related to checkout / store front-end. Sending it to @Automattic/fractal (cc @bborman22) as per our product responsibilities Pc2DNy-3z-p2. I see the team has already picked it up.
