### ISSUE TITLE
rtrim(): Passing null to parameter #1 ($string) of type string is deprecated in WC_Payments_Utils

### ISSUE THREAD

**Issue by jsikkes** [Automattic/woocommerce-payments#9214]
### Describe the bug

Method is_store_api_request() in WC_Payments_Utils throws the following warning when an url is requested with additional slashes prepended to the path. This occurs when the rest api is called with a malformed url. In most cases these are bots trying to work around .htaccess rules blocking specific api endpoints.

### To Reproduce

Call the wordpress rest api with an url prepending additional slashes to the path: https://{hostname}**//**/wp-json/wp/v2/users
or a non-existing rest api endpoint like https://{hostname}**//**/wp-json/this/endpoint/does/not/exists

### Actual behavior

This will cause ```$url_parts    = wp_parse_url( esc_url_raw( $_SERVER['REQUEST_URI'] ?? '' ) );``` to  be null

and ```$request_path = rtrim( $url_parts['path'], '/' ); ``` to fail with the following error:

```

Warning:  Trying to access array offset on value of type bool in **wordpress/plugins/woocommerce-payments/includes/class-wc-payments-utils.php** on line **1085**

**Deprecated**:  rtrim(): Passing null to parameter #1 ($string) of type string is deprecated in <b>wordpress/wp-content/plugins/woocommerce-payments/includes/class-wc-payments-utils.php</b> on line **1085**

```

### Expected behavior
No PHP warnings or deprecation messages are thrown for invalid rest-api urls.

### Additional context

A quick fix would be to change line 1085 in woocommerce-payments/includes/class-wc-payments-utils.php

from:
```
$request_path = rtrim( $url_parts['path'], '/' );
```

to:
```
$request_path = $url_parts ? rtrim( $url_parts['path'], '/' ) : "";
```

**Comment by anu-rock** [comment]
@jsikkes Many thanks for reporting the bug and suggesting a fix! Would you like to have a shot at creating a pull request? I can help you find the right people to review.
