### ISSUE TITLE
ECE w/ applied coupon error at checkout

### ISSUE THREAD

**Issue by frosso** [Automattic/woocommerce-payments#9233]
### Describe the bug

When the ECE is being used and a coupon is applied and the customer clicks the ECE button (GPay/ApplePay), an error is thrown in the console and the customer cannot checkout with GPay/ApplePay.
The customer needs to refresh the page to make the UI unblock and checkout with another payment method.

### To Reproduce

- Create a coupon (e.g. 90% off)
- Add a product to the cart
- Go to the cart page
- Apply the coupon
- Attempt to use GooglePay/ApplePay

https://github.com/user-attachments/assets/20091830-f323-4c0b-a4cb-2f08b44e9aca

https://github.com/user-attachments/assets/0ad77cee-887e-4153-8f8e-e2a4a7e477d3

### Actual behavior

An error is thrown:

```
IntegrationError: The amount xxx is less than the total amount of the line items provided.
    at F (v3/?ver=3.0:1:36711)
    at v3/?ver=3.0:1:338245
    at v3/?ver=3.0:1:331691
F @ v3/?ver=3.0:1
(anonymous) @ v3/?ver=3.0:1
(anonymous) @ v3/?ver=3.0:1
Promise.then
N @ v3/?ver=3.0:1
resolve @ v3/?ver=3.0:1
resolve @ v3/?ver=3.0:1
eval @ index.js:268
(anonymous) @ v3/?ver=3.0:1
c._emit @ v3/?ver=3.0:1
c._emitEvent @ v3/?ver=3.0:1
(anonymous) @ v3/?ver=3.0:1
(anonymous) @ v3/?ver=3.0:1
c._emit @ v3/?ver=3.0:1
_handleMessage @ v3/?ver=3.0:1
(anonymous) @ v3/?ver=3.0:1
(anonymous) @ v3/?ver=3.0:1
```

### Expected behavior

Customer should be able to checkout with the applied coupon with GPay/ApplePay

### Additional context

p1723041481419939-slack-C7U3Y3VMY

**Comment by bborman22** [comment]
Closed by #9234
