### ISSUE TITLE
WooPay opt-in changes to wrong country when clicking in then out after autocomplete

### ISSUE THREAD

**Issue by leonardola** [Automattic/woocommerce-payments#9235]
### Describe the bug
The WooPay opt-in changes the country code to 1 after clicking in then out of the phone field after it was auto completed by copying the billing phone. **The phone is correctly saved** but the wrong flag shows up during checkout.

https://github.com/user-attachments/assets/146e9656-105d-45dd-a579-cd5160694cae

### To Reproduce
- As a new unlogged customer add a product to your cart
- Go to the blocks checkout page
- Fill in the billing details
- Use a billing phone from another country like `+5541991788166`
- Click the WooPay opt-in checkbox (Securely save my information for 1-click checkout)
- It should copy the billing phone
- Click the phone field then click out
- The country flag will change to US but it should stay as Brazil
- The WooPay phone number was saved correctly in the database but the flag shows the wrong country during checkout

**Comment by alefesouza** [comment]
This looks to be fixed by https://github.com/Automattic/woocommerce-payments/pull/9464 too.
