### ISSUE TITLE
BNPL - Respect minimum order amounts when adding the PMME to the page

### ISSUE THREAD

**Issue by mdmoore** [Automattic/woocommerce-payments#9244]
### Describe the bug

BNPL has [minimum order amounts](https://github.com/search?q=repo%3AAutomattic%2Fwoocommerce-payments%20limits_per_currency&type=code). Stripe uses the total when determining which BNPL methods are applicable. If no payment methods are applicable, say due to the total not hitting the minimum, no payment methods are displayed. Until recently, this wasn't a problem because nothing would be displayed on the page. However, the container with id `payment-method-message` is still added to the page and contains an empty Stripe iframe. Since https://github.com/Automattic/woocommerce-payments/pull/9166, a skeleton loader is added. When minimum order amounts aren't hit, the skeleton loader still appears, but no PMME is displayed when loading is finished. The result is a loader that appears to load nothing.

### To Reproduce

1. Enable all BNPL payment methods
2. Set your currency to USD
3. Create a product that is less than $1. 
4. Navigate to the product and see the skeleton loader appear

### Screenshots

https://github.com/user-attachments/assets/680ace22-648f-4849-bf80-1d691b33de22

### Expected behavior

The loader shouldn't appear if minimum order amounts aren't met for the selected currency.

**Comment by bborman22** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Fractal-62a0f7b955648b001e1f5e1f/issues/Automattic/woocommerce-payments/9244?planning-poker) with Zenhub @asumaran @cesarcosta99 @lovo-h @reykjalin @rafaelzaleski @ricardo

**Comment by rafaelzaleski** [comment]
@cesarcosta99 @bborman22 While testing another issue, I noticed that this bug can also occur with the maximum amount, but I believe the fix only addressed the minimum amount. Notice the blank space in the image below.

![Screen Shot 2024-09-10 at 11 15 21 AM](https://github.com/user-attachments/assets/082b85f2-600a-477e-9f7c-f7f5c1ffa275)

**Comment by cesarcosta99** [comment]
> While testing another issue, I noticed that this bug can also occur with the maximum amount, but I believe the fix only addressed the minimum amount. Notice the blank space in the image below.

Thanks for reporting this, Rafael. I created #9459 to track it 👍
