### ISSUE TITLE
[ECE] Provide a locale to the ECE element instead of relying on Stripe to detect it for us

### ISSUE THREAD

**Issue by reykjalin** [Automattic/woocommerce-payments#9245]
## Description

- To match the PRB implementation let's pass the customer's locale to the ECE express checkout buttons like we do for the PRBs.

## Acceptance criteria

* Customer's locale is passed to the ECE express checkout buttons.

## Dev notes

See Stripe's doc on how to provide the locale option [here](https://docs.stripe.com/js/elements_object/create#stripe_elements-options-locale).

The locale is loaded to the front-end here for the PRBs:

https://github.com/Automattic/woocommerce-payments/blob/106db15e504912b1561da4139d900d8fba47d284/includes/express-checkout/class-wc-payments-express-checkout-button-handler.php#L229

## Additional context

- p1723161411280019-slack-C01BZUL57SQ

**Comment by anu-rock** [comment]
This issue is related to the PRB (payment request button) to ECE (express checkout element) migration. Sending it to @Automattic/fractal (cc @bborman22) as per our product responsibilities Pc2DNy-3z-p2.

**Comment by bborman22** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Fractal-62a0f7b955648b001e1f5e1f/issues/Automattic/woocommerce-payments/9245?planning-poker) with Zenhub @asumaran @cesarcosta99 @lovo-h @rafaelzaleski @reykjalin @ricardo
