### ISSUE TITLE
Remove UPE reference from Link payment method copy 

### ISSUE THREAD

**Issue by csmcneill** [Automattic/woocommerce-payments#9253]
### Description
The description for the Link payment method currently reads:

> Link autofills your customers’ payment and shipping details to deliver an easy and seamless checkout experience. New payment experience (UPE) needs to be enabled for Link. By enabling this feature, you agree to the [Link by Stripe terms](https://link.co/terms), and [Privacy Policy](https://link.co/privacy).

However, following PRs like https://github.com/Automattic/woocommerce-payments/pull/7821, there are no checks for UPE enablement, and users cannot enable/disable UPE.

### Acceptance criteria

* References to UPE requirements are removed from in-app copy for the Link payment method.
* Bonus: Links are updated from `link.co` to `link.com`
* Bonus: Other references to `UPE` or the `new checkout experience` are also removed from in-app copy.

### Testing instructions

1. Navigate to Payments > Settings
2. Check the copy for the Link payment method description
3. Determine if there is mention of UPE or the new checkout experience

**Comment by vbelolapotkov** [comment]
@pierorocca I don't think "new payment experience" is relevant anymore as well. So forwarding it to you for deciding on the right copy here and prioritizing this small enhancement.

**Comment by pierorocca** [comment]
I agree. Good catch Vlada and Chris.

**Comment by pierorocca** [comment]
@FangedParakeet @frosso perhaps one of you could fully remove the sentence containing UPE and update the links from .co to .com for 8.1?
