### ISSUE TITLE
Update bin/docker.setup for the latest WP CLI Docker image 

### ISSUE THREAD

**Issue by vladolaru** [Automattic/woocommerce-payments#9254]
### Describe the bug

The `cli:latest` Docker image doesn't have the `xfs` user anymore ([we use this user](https://github.com/Automattic/woocommerce-payments/blob/064d10e45f1cde32636682755d3a95b55f81c6ac/bin/docker-setup.sh#L17-L17) in our `docker.setup` script).

Because of this missing user, we get errors when running `./bin/docker-setup.sh`:

```
docker: Error response from daemon: unable to find user xfs: no matching entries in passwd file.
Waiting until the service is ready...
docker: Error response from daemon: unable to find user xfs: no matching entries in passwd file.
Waiting until the service is ready...

```

**Comment by vbelolapotkov** [comment]
@vladolaru, thank you for reporting and creating PR with the fix! I'll ask DevOps squad to help with reviews.
