### ISSUE TITLE
Disputes > Merchant can save and resume draft dispute challenge E2E test failure

### ISSUE THREAD

**Issue by jessy-p** [Automattic/woocommerce-payments#9281]
### Description

**Before reporting an issue, are you sure this e2e test is failing consistently?**
Yes, this e2e test failed 4 times consistently with the same error while creating the 8.1.0 release branch

**Issue**
`Disputes > Merchant can save and resume draft dispute challenge` fails with the error `Element [data-testid="dispute-challenge-product-type-selector"] (text: "Offline service") not found`

**Output from the test failure**:
```
FAIL tests/e2e/specs/wcpay/merchant/merchant-disputes-save-draft-challenge.spec.js (43.931 s)
  Disputes > Merchant can save and resume draft dispute challenge
    ✕ should be able to save a draft dispute challenge and resume (13525 ms)

  ● Disputes > Merchant can save and resume draft dispute challenge › should be able to save a draft dispute challenge and resume

    TimeoutError: Element [data-testid="dispute-challenge-product-type-selector"] (text: "Offline service") not found
    Waiting failed: 3000ms exceeded

      114 |
      115 | 		// Verify the previously selected Product type was saved
    > 116 | 		await expect( page ).toMatchElement(
          | 		^
      117 | 			'[data-testid="dispute-challenge-product-type-selector"]',
      118 | 			{
      119 | 				text: 'Offline service',

      at tests/e2e/specs/wcpay/merchant/merchant-disputes-save-draft-challenge.spec.js:116:3
```

### Additional context
https://github.com/Automattic/woocommerce-payments/actions/runs/10440457389/job/28938598192

### Priority
low
Looks like E2E test are flaky on all previous release

### Reason why this e2e test is broken
e2e: broken test

> [!Important]
> Please, ensure when closing this issue (PR fix) that only one `e2e: broken` label is added and it is accurate.
> - [x] I confirmed there's only one `e2e: broken` label in this issue and it is accurate.

**Comment by Jinksi** [comment]
Testing locally with `npm run test:e2e -- tests/e2e/specs/wcpay/merchant/merchant-disputes-save-draft-challenge.spec.js`:

* Passes on `trunk`
* Fails with this error on `develop`

**Comment by Jinksi** [comment]
I think this might be caused by an _improvement_ in admin page loading speed in the e2e env.

The test has been acting as follows:
1. Go to dispute challenge screen
2. Change some details in the form
3. Press save for later
	- The page will redirect to disputes list here :warning:
4. Before the redirect occurs, reload the page to view the saved dispute challenge details

Now that perf has improved, the time between 3 → 4 is not enough to reload before the redirect occurs.

🔧 The fix will be to allow the redirect to complete before navigating to the challenge dispute screen again.
