### ISSUE TITLE
Test mode can be disabled after sandbox mode onboarding

### ISSUE THREAD

**Issue by aheckler** [Automattic/woocommerce-payments#9296]
### Describe the bug

After "onboarding" in the new one-click sandbox mode in 8.1.0, I can disable test mode in the **Payments > Settings** page. This causes errors if I change other settings.

### To Reproduce

1. Spin up a JN site.
2. Install WooPayments 8.1.0.
3. Go to **Payments** page.
4. Click **Enable sandbox mode** at bottom.
5. Connect to WordPress.com 
6. Wait for the test account to finish creating.
7. You'll land back in wp-admin.
8. Go to **Payments > Settings**.
9. Add a real phone number to get around [this recently reopened bug](https://github.com/Automattic/woocommerce-payments/issues/6782).
10. **Save Changes**.
11. Still on **Payments > Settings**, disable test mode.
12. **Save Changes** again.
13. Now check some boxes next to some payment methods to "enable" them.
14. **Save Changes** again.
15. Observe:

![Screenshot taken on 2024-08-21 at 14 34 33 UTC@2x](https://github.com/user-attachments/assets/f51dd72a-9251-4a68-99aa-2fe379a32460)

### Expected behavior

Since sandbox mode is of course unable to process real transactions, it was surprising to me that I could even uncheck the test mode setting and save it. We should disable that / gray it out, so it's clear the site is only in test mode and that it cannot go live.

**Comment by pierorocca** [comment]
@vladolaru want to get your eyes on this as well since I wouldn't have expected changes in onboarding to impact existing functionality and to get through GS and e2e testing.

**Comment by pierorocca** [comment]
@aheckler can you confirm you are actually not in Live mode to rule out that Sandbox mode checkbox functionality is working as expected?

**Comment by pierorocca** [comment]
What’s actually shown now in new sites according to Adam's testing is that the Live mode UI is shown in settings.

When working properly, this is shown in Sandbox mode:
![Image](https://github.com/user-attachments/assets/846ea882-ac88-49f7-9fa3-a069d2c41956)

Does anyone think this might be a Critical issue? Does this impede a store from getting to Live mode? Or at least make it harder to understand they need to enable live mode? That could impact activation rates.

Another thing to check is, is the site actually in Sandbox mode or is it in Live mode hence why the Live UI is being shown?

@vladolaru @FangedParakeet @c-shultz could we dive into this please?

@timmy5685 for awareness.

**Comment by pierorocca** [comment]
@anu-rock adding you in to this thread. There were changes made to the Sandbox mode in 8.1 bypassing KYC. We're now seeing on new stores going through that flow that we're displaying the Live payments setting UI rather than the Sandbox payment settings UI.

**Comment by aheckler** [comment]
> can you confirm you are actually not in Live mode to rule out that Sandbox mode checkbox functionality is working as expected?

Following the steps in my original report above does yield a site in sandbox mode and NOT in live mode. There's the sandbox mode warning present on **Payments > Overview**, and the database indicates the same:

```shell
$ wp option get wcpay_account_data | grep 'acct\|is_live\|test_drive'
    'account_id' => 'acct_1PqVhsFj6lsvoLY5',
    'is_live' => false,
    'is_test_drive' => true,
```

Anyone can try it out on Jurassic Ninja and get the same result.

**Comment by anu-rock** [comment]
Thanks for your inputs, @aheckler and @pierorocca. Moltres are looking into it.

Heads up for others following this issue. It's also being discussed in this Slack thread - p1724281242025799-slack-CGGCLBN58

**Comment by vladolaru** [comment]
@pierorocca, thanks for the ping. I am the one who messed this up. I [have a PR](https://github.com/Automattic/woocommerce-payments/pull/9306) with the fix (@mordeth will take it from there since I am AFK).

The issue doesn't affect how the account is created or the ability of merchants to switch to a live account (from the Payments Overview since we don't have the notice on the Settings page due to the bug). It just a display/JS bug, not something in our platform or onboarding logic.

**Comment by pierorocca** [comment]
Closing as the patch went out today.
