### ISSUE TITLE
In sandbox mode, settings page only warns about test mode

### ISSUE THREAD

**Issue by aheckler** [Automattic/woocommerce-payments#9297]
### Describe the bug

After "onboarding" in the new one-click sandbox mode in 8.1.0, I see a warning about test mode on **Payments > Settings** page, but that's irrelevant: I'm in sandbox mode, which is test only anyway. We should warn about sandbox mode, not test mode.

### To Reproduce

1. Spin up a JN site.
2. Install WooPayments 8.1.0.
3. Go to **Payments** page.
4. Click **Enable sandbox mode** at bottom.
5. Connect to WordPress.com 
6. Wait for the test account to finish creating.
7. You'll land back in wp-admin.
8. Go to **Payments > Settings**.
9. See this warning:

![Screenshot taken on 2024-08-21 at 14 38 54 UTC@2x](https://github.com/user-attachments/assets/a055d1c4-a09d-4062-ad3c-7891de1b86db)

We should replace this with a similar warning about sandbox mode, since that's the mode we care about here. Maybe something like:

[Sandbox mode](https://woocommerce.com/document/woopayments/testing-and-troubleshooting/sandbox-mode/) active: All settings and transactions are simulated. Customers can't make real purchases through WooPayments.

**Comment by pierorocca** [comment]
@aheckler my existing site, now updated to 8.1.0 shows a more appropriate set of settings and messages. Is this issue limited to new sites?

![Image](https://github.com/user-attachments/assets/76c684b1-5e10-430e-a99c-09eaa20b52ec)

**Comment by aheckler** [comment]
@pierorocca 

> Is this issue limited to new sites?

Perhaps. I don't have a pre-8.1.0 sandbox mode site to test on myself.

**Comment by pierorocca** [comment]
OK well when working correctly the UI/UX accounts for this scenario by removing the Test mode checkbox and replacing it with this Sandbox mode message. Something else is going on where we can no longer recognize the site is in Sandbox mode or the site isn't actually in Sandbox mode when we think it is.

**Comment by mordeth** [comment]
@aheckler [This PR](https://github.com/Automattic/woocommerce-payments/pull/9306) will replace the `Enable test mode` checkbox with the sandbox notice that Piero mentioned. However, the `Test mode active:` notice will remain, since Sandbox mode is still considered a test mode.

**Comment by pierorocca** [comment]
Closing.
