### ISSUE TITLE
Setup page copy not ideal after coming out of sandbox mode

### ISSUE THREAD

**Issue by aheckler** [Automattic/woocommerce-payments#9298]
### Describe the bug

After "onboarding" in the new one-click sandbox mode in 8.1.0 and then disabling it using the **Set up a live WooPayments account** link, the initial WooPayments setup page is not ideal.

### To Reproduce

1. Spin up a JN site.
2. Install WooPayments 8.1.0.
3. Go to **Payments** page.
4. Click **Enable sandbox mode** at bottom.
5. Connect to WordPress.com 
6. Wait for the test account to finish creating.
7. You'll land back in wp-admin.
8. In the Sandbox mode notice at the top of the **Payments > Settings** page, click the **Set up a live WooPayments account** link.
9. Click **Continue setup** in the modal.
10. Land back on the setup page, see this:

![Screenshot taken on 2024-08-21 at 14 43 30 UTC@2x](https://github.com/user-attachments/assets/77999d60-2040-4126-a0fd-722efab797d1)

This is not ideal, because it makes it look like I've partially set up my live account, and only need to verify a few things to get going. In reality, I haven't even started, I'm still at "square one", since I have entered absolutely zero real details.

**Comment by anu-rock** [comment]
> Click Continue setup in the modal.
> Land back on the setup page, see this:

@aheckler On clicking the "Continue setup" button in the modal, were you directly taken to the connect page in the screenshot? Weren't you redirected to the MOX screens first (MOX eventually leads to Stripe KYC)?

cc @timmy5685 for visibility

**Comment by anu-rock** [comment]
@mordeth Pinging you too since you had this issue self-assigned. Just in case you have a clue for my above question.

**Comment by aheckler** [comment]
> On clicking the "Continue setup" button in the modal, were you directly taken to the connect page in the screenshot? Weren't you redirected to the MOX screens first (MOX eventually leads to Stripe KYC)?

I just tested this again and now I *AM* being guided through onboarding after clicking the "Continue setup" button in the modal. Back when I filed this issue, that didn't happen though, I just got plopped back into wp-admin and shown the image in the original report.

Maybe a fix for a different issue solved this one too?

**Comment by mordeth** [comment]
I believe this issue was resolved due to the fixes implemented in #9358. I think we can safely close this issue.
