### ISSUE TITLE
Using WCPAY_DEV_MODE doesn't enter one-click sandbox mode onboarding

### ISSUE THREAD

**Issue by aheckler** [Automattic/woocommerce-payments#9300]
If you have WooPayments in sandbox mode using `define( 'WCPAY_DEV_MODE', true );` in your `wp-config.php` file, the **Connect your store** button on the initial WooPayments setup page should enter the one-click sandbox mode process, but it does not.

1. Spin up a JN site.
2. Install WooPayments 8.1.0 and activate it.
3. Via SSH, set `define( 'WCPAY_DEV_MODE', true );` in `wp-config.php`.
4. Go to **Payments** page.
5. See this:

![Screenshot taken on 2024-08-21 at 14 58 19 UTC@2x](https://github.com/user-attachments/assets/f432ac13-8899-47c9-b6a5-cdb93a606ba4)

6. This should mean that using EITHER the **Connect your store** button or the **Enable sandbox mode button** at the bottom should engage the one-click sandbox mode process.
  - As a side note, if I've already enabled sandbox mode via `WCPAY_DEV_MODE`, why does the button at the bottom even say "Enable sandbox mode"? I've already enabled it! 
7. Click **Connect your store** button.
8. Connect to WordPress.com.
9. You get thrown into progressive onboarding instead of just having a sandbox mode account made for you automatically.

**Comment by mordeth** [comment]
Closing the issue as the behavior described in the description is the expected one.

**Comment by vladolaru** [comment]
See this Slack discussion for more context: p1726575054196589/1726493754.757129-slack-CGGCLBN58
