### ISSUE TITLE
Unpolished mobile layout when onboarding additional payment methods

### ISSUE THREAD

**Issue by frosso** [Automattic/woocommerce-payments#9301]
### Describe the bug

The layout of the "Add payment methods" task looks unpolished on mobile.
The changes seem likely due to the loadable checkboxes and their labels, it looks like a not-so-recent refactoring didn't account for the mobile layout.

### To Reproduce

Method 1 (slow):
- As an admin, onboard with a new WooPayments account
- Go to the WooPayments page
- Click on the "Add payment methods" task

Method 2:
- As an admin, access https://wcpay.test/wp-admin/admin.php?page=wc-admin&path=%2Fpayments%2Fadditional-payment-methods directly (change `wcpay.test` with your site's URL

### Actual behavior

The layout shifts inconsistently on mobile

### Screenshots

https://github.com/user-attachments/assets/31bc97c2-8018-415b-86a7-3680c5c99268

### Expected behavior

I would expect a more responsive behavior of the individual payment methods and their labels.

### Smartphone (please complete the following information):

The layout shift happens at 660px

**Comment by pierorocca** [comment]
Noting that this screen will soon be EOL as the new onboarding flow will thankfully replace this. I wouldn't spend time on updating this screen.

**Comment by pierorocca** [comment]
Closing as won't do in favor of the ongoing onboarding updates.
