### ISSUE TITLE
Link icon now skews right instead of left in 8.1.0

### ISSUE THREAD

**Issue by pierorocca** [Automattic/woocommerce-payments#9304]
FYI the icon now skews right instead of left in 8.1.0 @frosso.
![image](https://github.com/user-attachments/assets/5e347989-3b2f-4021-94bc-680c13a335c8)

_Originally posted by @pierorocca in https://github.com/Automattic/woocommerce-payments/issues/9255#issuecomment-2303070316_

**Comment by pierorocca** [comment]
Actually everything is skewed right including the title and descriptive copy.

**Comment by pierorocca** [comment]
WooPay icon similarly shifts left and right

![image](https://github.com/user-attachments/assets/f22342a0-1895-496d-95bc-98a0ccf6d190)

**Comment by frosso** [comment]
@pierorocca I'm not able to reproduce this shift - I just tested it locally and on a brand new JN site with WooPayments 8.1.
![2024-08-22 09 34 07](https://github.com/user-attachments/assets/87b114ba-1d33-4459-b116-e956bc50b225)

Could you please verify again?

**Comment by timur27** [comment]
FWIW I tried to reproduce it with Chrome, Firefox, and Safari, but I haven't been able to replicate it so far.

**Comment by pierorocca** [comment]
Thanks guys. Do you have an existing site you can try on or have a look at proccaatomic.wpcomstaging.com?

I have the Sandbox banner, Sofort deprecation inline notice, and the Apple/Google conflict warning which I thought was supposed to be disabled this release.

Perhaps those additional notices are causing styling issues or it's only happening to existing sites.

**Comment by frosso** [comment]
@pierorocca I just DM'd you with the JN site I tested this on: https://salamander-of-monkeys.jurassic.ninja/wp-admin/admin.php?page=wc-settings&tab=checkout&section=woocommerce_payments

**Comment by frosso** [comment]
Chatted over DM - it looks like it's a difference in styling between the WPcom back-end and a non-WPcom back-end. Likely due to Gutenberg styling.
The size of the checkboxes and their margins are slightly different on a WPcom site.
![2024-08-22 17 56 11](https://github.com/user-attachments/assets/4672e32b-6c94-47ec-ad9b-9ff8a386ba80)
