### ISSUE TITLE
Save changes button on WooPayments pages are always active

### ISSUE THREAD

**Issue by pierorocca** [Automattic/woocommerce-payments#9305]
### Describe the bug

WooPayments and Multicurrency pages seem to be the only pages where the "save settings" button is always enabled. Settings can be saved even if no changes were made to any setting. On occasion, the browser will throw a warning typical of unsaved changes.

![image](https://github.com/user-attachments/assets/ad32aba3-24af-4f7a-acc8-0fe1a62d4bac)

### Expected
Save settings is disabled until a settings change is made
When a change is made, the button is enabled

@FangedParakeet do you know if there's a historical reason or technical limitation for this behavior?

**Comment by pierorocca** [comment]
![image](https://github.com/user-attachments/assets/3e049a38-1a39-43ee-855a-21a4b49fdaea)

**Comment by FangedParakeet** [comment]
> do you know if there's a historical reason or technical limitation for this behavior?

@pierorocca, I wanted to confirm with the team before I offered a definitive answer here, but AFAICT there shouldn't be any technical limitations preventing us from implementing this enhancement and moreover there should be some existing functionality in the current code that might assist us in providing this feature, so might be a lightweight improvement from a development perspective as well.

**Comment by FangedParakeet** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Heisenberg-63586f2ec60359001310fa6a/issues/Automattic/woocommerce-payments/9305?planning-poker) with Zenhub @mdmoore

**Comment by mdmoore** [comment]
This turned out to be more complex than a 2 because of the multiple settings screens accessible through modals and sub-pages. Upgrading the estimate to a 3.

**Comment by pierorocca** [comment]
@mdmoore which subpages don't have their own save button?

**Comment by mdmoore** [comment]
@pierorocca It's that more that they all **do** have their own save buttons. It's just that I kept realizing there were more settings to consider than just a main settings page and the multi-currency page, such as the Advanced Fraud settings, Single Currency settings via the "manage" link within each currency, and Express Checkout customization settings. Then there is the Add/Remove Currencies modal which requires updating the disabled state based on changes made via the modal.

**Comment by pierorocca** [comment]
Ah I see, it's the quantity of pages with save buttons as opposed to tracking changes multiple levels deep. Gotcha.
