### ISSUE TITLE
[ECE] Remove Apple Pay test warning notification

### ISSUE THREAD

**Issue by pierorocca** [Automattic/woocommerce-payments#9323]
### Describe the bug
The recent updates to the Domain Registration implementation for express checkout has removed a previous testing limitation where Apple Pay could not be tested with Sandbox accounts. That's no longer a limitation thus this notification should be removed.

![image](https://github.com/user-attachments/assets/6329f0f9-758b-46fd-9ae1-9b0a5684a21e)

CC @bborman22

**Comment by bborman22** [comment]
Thanks @pierorocca! This should be fixed in #9307

**Comment by pierorocca** [comment]
Dang I looked for this but only looked in the Open issues. Thanks for letting me know.
