### ISSUE TITLE
Default express checkout button label to "Only icon" instead of "Buy with"

### ISSUE THREAD

**Issue by pierorocca** [Automattic/woocommerce-payments#9332]
### Description
For new stores, set the default express checkout button label to "Only icon". The reasoning, based on good user flow feedback, is that GPay, WooPay, Apple Pay are verb like and can stand on their own without the additional text. 

While there are use cases where the additional text is warranted, e.g. donations, we don't currently have a way to decouple the setting on a per page basis. Therefore we'll optimize for the base cart and checkout use cases, and we'll revisit product page settings after PRB Tokenization has been implemented (fyi @frosso) and in 2025 as we look at embedded commerce use cases where button labels have more importance.

![image](https://github.com/user-attachments/assets/de37788d-051e-4849-b7ec-52b4037be46d)

### Acceptance criteria
1. "Only icon" is the default express checkout button label for WooPay, Apple Pay, Google Pay. 
2. Link continue to have no related setting
3. Existing sites are not impacted

**Comment by pierorocca** [comment]
cc @bborman22

**Comment by bborman22** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Fractal-62a0f7b955648b001e1f5e1f/issues/Automattic/woocommerce-payments/9332?planning-poker) with Zenhub @asumaran @cesarcosta99 @lovo-h @rafaelzaleski @reykjalin @ricardo
