### ISSUE TITLE
Payment methods do not declare support for Cart and Checkout blocks if they cannot be enabled in the Payments settings

### ISSUE THREAD

**Issue by csmcneill** [Automattic/woocommerce-payments#9363]
### Describe the bug

If any payment methods cannot be enabled because...
1. Auth + capture is enabled
2. That method has been rejected
3. That method requires more information to enable

...the Cart and Checkout block will show those particular payment methods do not support those blocks.

### To Reproduce

1. Create a page that uses the Cart or Checkout block.
(if such a page already exists, edit that page) 
2. Select one of the blocks on the page.
3. Open the sidebar.
4. Select the `Block` tab.
5. Note there are no listed incompatibilities with any of the WooPayments payment methods listed in the sidebar.
6. Navigate to **Payments > Settings**.
7. Enable any BNPL payment method or LPM.
8. Enable `Issue an authorization on checkout, and capture later`.
9. Save your settings.
10. Edit the Cart or Checkout block page.
11. Repeat steps 2–4.
12. Note that the payment method(s) enabled in step 7 are highlighted as not supporting the selected block.

### Actual behavior

When enabling auth + capture, any non-card payment methods enabled beforehand will be identified as not supporting the Card or Checkout blocks.

### Screenshots

![CleanShot 2024-08-29 at 20 13 29@2x](https://github.com/user-attachments/assets/d29ca83e-d2d2-44d8-b01f-2f0c652c8931)

Video recording here: U01TTK2RXJB/F07K6NZMPM1-slack-file

### Expected behavior

All payment methods show as compatible with the Cart and Checkout blocks regardless of their state in the WooPayments settings.

**Comment by mdmoore** [comment]
I looked into this briefly today. I'm not sure where the compatibility notices get the data. In this scenario, with `Issue an authorization on checkout, and capture later` being enabled while LPMs are enabled, the correct payment methods are passed to `registerPaymentMethod`. The Payment Options block displays the correct payment method as well, `card`. As well, `get_payment_method_ids_enabled_at_checkout()` returns only card. We'll need to find why this part of the Checkout Block thinks these payment methods are still enabled.

**Comment by senadir** [comment]
Hey @mdmoore! The logic we use to decide if payments are compatible or not is the following:

1. First, we fetch all enabled payment methods PHP side:
```php
$payment_gateways = WC()->payment_gateways->payment_gateways();
return array_filter(
	$payment_gateways,
	function ( $payment_gateway ) {
		return 'yes' === $payment_gateway->enabled;
	}
);
```
2.  We get all JS payment methods that are available, and enabled. As long as the payment calls `registerPaymentMethod` with the correct name that matches what's in `WC_Payment_Gateway`, it should show up.

calling `registerPaymentMethod` conditionally is advised against, I suggest you put your conditions in the `canMakePayment` function. That function will always be true in the editor, and load up correctly in frontend.

**Comment by mdmoore** [comment]
@csmcneill I've been able to verify the issue with LPMs enabled before auth + capture is enabled 👍 

Do you have any quick tips on getting LPMs into the rejected and needs more information states?

**Comment by csmcneill** [comment]
Hey @mdmoore! I don't have any tips for that, but it seems like Affirm will often be rejected depending on the MCC.

Per p1711458771878539-slack-CGGCLBN58 onboarding with `Software` as the industry would result in a rejected account at one point in time — but that may no longer be the case. 

An alternative would be to [select a business type explicitly prohibited from using Affirm](https://docs.stripe.com/payments/affirm#prohibited-and-restricted-business-categories).

**Comment by mdmoore** [comment]
Thanks @csmcneill! The business type tip did the trick.
