### ISSUE TITLE
Express Checkout box is always visible, even if there are no Express Payment Methods

### ISSUE THREAD

**Issue by pierorocca** [Automattic/woocommerce-payments#9365]
Original issue 
https://github.com/woocommerce/woocommerce/issues/50353

**Comment by asumaran** [comment]
I’m running out of ideas on how to reliably validate whether a payment method is available using ECE. In Firefox, the onReady event triggers twice(!). I was hoping to use this event to detect if the Stripe iframe has increased its height (indicating that a button was rendered), but it’s not reliable. In both Firefox and Chrome, the iframe height is 8px when the onReady event is first fired. However, Firefox fires the event twice, while Chrome only fires it once.

**Comment by asumaran** [comment]
We’re left with only hacky and unreliable methods to fix this bug.

**Comment by pierorocca** [comment]
We discussed this today in the sprint planning meeting and this may require working with Team Rubik to figure out how to unregister payment methods. There are plenty of use cases when payment method eligibility changes like a discount code or gift card being applied where the total no longer allows a shopper to qualify. Or a currency change. Or a country change. Tons of ways where eligibility could change and the registered payment methods needs to be dynamic. Guessing based on height changing is not a reliable enough method for the criticality of payments imo.

**Comment by asumaran** [comment]
>Tons of ways where eligibility could change and the registered payment methods needs to be dynamic.

@pierorocca I completely agree. 

Regarding this issue. I might have found a reliable way to fix it. I didn't realized we have an `event` argument on the `ready` event https://docs.stripe.com/js/element/events/on_ready#element_on_ready-handler-availablePaymentMethods
>This field is only present on the expressCheckout Element. Describes which buttons render in the Element. Returns undefined if no buttons will render.

This object shows us exactly which payment methods are available. I’ve confirmed it works on Chrome, Safari, and Firefox. I’m just wrapping up a few details, and then I’ll submit the PR for review.

**Comment by pierorocca** [comment]
That's great. What happens if eligibility changes after an event like changing the currency or applying a gift card/discount code that drops the total to $0?

**Comment by asumaran** [comment]
@pierorocca Thanks for bringing that up. Based on my testing, the behavior remains consistent: applying a 100% coupon causes the button to disappear, while applying a 50% coupon keeps the buttons visible, and the amounts are applied correctly. The checkout process via Express Checkout also works as expected.
