### ISSUE TITLE
BNPL payment methods and PMME are still enabled when WooPayments gateway is disabled

### ISSUE THREAD

**Issue by pierorocca** [Automattic/woocommerce-payments#9390]
### To Reproduce
On shortcode, disable WooPayments gateway in WooPayments Settings
Shop and observe that BNPL payment methods and PMME are enabled throughout the store

### Expected behavior
No payment methods are enabled on the front-end if the gateway is disabled (plugin still activated)

![image](https://github.com/user-attachments/assets/ca57adbb-1aee-4b16-9a39-a130efe360c9)

![image](https://github.com/user-attachments/assets/2121f78f-93f3-41c2-af45-2a93fab535d8)

![image](https://github.com/user-attachments/assets/3ff1e0eb-a55a-48ce-bfdf-5b47b40c0419)

**Comment by c-shultz** [comment]
@FangedParakeet @bborman22  Are there any lessons learned here that we can apply to v2? We had some messy enablement logic with WooPay as well. Looks like there's a lot of complexity in this area that could potentially be better solved at an architecture level.

**Comment by danielmx-dev** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Heisenberg-63586f2ec60359001310fa6a/issues/Automattic/woocommerce-payments/9390?planning-poker) with Zenhub @FangedParakeet
