### ISSUE TITLE
RGBA to RGB conversion does not work correctly for colorful backgrounds

### ISSUE THREAD

**Issue by leonardola** [Automattic/woocommerce-payments#9415]
### Describe the bug
#8404 changed the way we handle conversion from RGBA to RGB for Stripe theming. Currently the code will always use a white background to mix the color. This ends up converting colors on sites with a non white background buggy.

### To Reproduce
- Install and activate the [Blockbase theme](https://wordpress.org/themes/blockbase/)
- Go to /wp-admin > Appearance > Editor > Templates > WooCommerce > Checkout
- Click on the background > Styles > Background > Black 

<img width="995" alt="Screenshot 2024-09-10 at 11 47 08" src="https://github.com/user-attachments/assets/5bcf3894-1ff6-48f5-bfe5-4caaa63b9daa">

- Click on the Checkout element > Blocks
- Enable Dark mode inputs

<img width="1201" alt="Screenshot 2024-09-10 at 11 51 15" src="https://github.com/user-attachments/assets/800fa239-2f28-4341-895b-ceb44a3b2a7f">

- Save the page
- As a customer add a product to your cart
- Visit the checkout page
- Notice that the Stripe fields look different from the checkout field

<img width="661" alt="Screenshot 2024-09-10 at 13 51 31" src="https://github.com/user-attachments/assets/e03ca6bf-b1f0-46f5-b6e8-3bd5c107112f">

### Solutions

Currently the code looks like this:
https://github.com/Automattic/woocommerce-payments/blob/3ab1e66eeec8e3f4674b4919a3b98a472fdcd519/client/checkout/upe-styles/utils.js#L118

For black background themes the formula could be changed to:
```
Math.round( part * ( 0 + alpha ) );
```

The problem is that it will not work well on all other cases. [So another approach would be to take into account the background color and mix with the color we're converting](https://stackoverflow.com/a/11615135).

```
alpha = 1 - RGBA.alpha;
RGB.red = Math.round((RGBA.alpha * (RGBA.red / 255) + (alpha * (bg.red / 255))) * 255);
RGB.green = Math.round((RGBA.alpha * (RGBA.green / 255) + (alpha * (bg.green / 255))) * 255);
RGB.blue = Math.round((RGBA.alpha * (RGBA.blue / 255) + (alpha * (bg.blue / 255))) * 255);
```

But then what if there is another element with a different color between the page background and the element we're converting the color?

**Comment by leonardola** [comment]
Including @brettshumaker to the discussion as he worked on the last fix for this code #8404

**Comment by pierorocca** [comment]
Is this related?

https://github.com/user-attachments/assets/82ec4455-d3a3-4a7d-b497-6a71e34b2f63

@c-shultz want to point this out as critical as mentioned on Slack. I'm seeing white on white and black input fields on white backgrounds. Generally this functionality is not reliable. Sometimes it works, other times it's quite broken.

**Comment by leonardola** [comment]
Seems related. But the black fields in a white theme should have been fixed in #8404 right now it only shows white fields on a dark theme

**Comment by c-shultz** [comment]
This report on .org looks related: https://wordpress.org/support/topic/stripe-field-color-changing-all-the-time-2/

Any thoughts on why this would be coming up now after this code has been live for most of the year?

**Comment by gpressutto5** [comment]
@leonardola Is it possible to reproduce this issue without using the [Blockbase theme](https://wordpress.org/themes/blockbase/)? It is breaking my store. When I install it I can't see any products and the checkout page won't load.
Also, I can't see the background color option as in the first image.

**Comment by gpressutto5** [comment]
Can you confirm I'm reproducing the same issue in Storefront using custom css?

<img width="526" alt="image" src="https://github.com/user-attachments/assets/6284c7c8-4a9c-4951-8737-860fb6136af2">

```css
* {
	background-color: black;
}

input {
	background-color: rgba(255, 255, 255, .5) !important;
}
```

**Comment by gpressutto5** [comment]
It looks like Stripe supports RGBA. @FangedParakeet Why have we decided to convert it to RGB? Does it break anything?

<img width="697" alt="image" src="https://github.com/user-attachments/assets/d109e980-f0c0-4f48-b3b9-c412321c5235">

**Comment by leonardola** [comment]
> @leonardola Is it possible to reproduce this issue without using the [Blockbase theme](https://wordpress.org/themes/blockbase/)?

@gpressutto5 Yep. You can use Storefront too. Just set the page background to black and enable dark node inputs

- Change the theme to Storefront
- Go to /wp-admin > Appearance > Customize > Background
- Set the background as black
- Go to /wp-admin > Pages > edit the blocks checkout page
- Click on the Checkout element
- Click block
- Enable dark mode inputs
- Save
- As a customer add a product to your cart
- Go to the checkout page
- Notice the white credit card inputs

Steps to reproduce the bug:
https://github.com/user-attachments/assets/a7f7bdf7-dc45-4448-871a-256ff7be07c3

How the checkout page looks with a dark background + dark inputs:
https://github.com/user-attachments/assets/aab31c1c-1ac0-482b-90f0-7e8c8dc66525

How the checkout page looks with a white background + dark inputs:
https://github.com/user-attachments/assets/e5d1f4a5-d5f4-4bf4-9cd5-eaf379df175a

> It looks like Stripe supports RGBA

Perfect let's use that. 
But I think we should also remove the alpha from the inputs so they don't keep mixing with the background and generating weird combinations like the white background with dark inputs. Or give merchants full control over the color of the inputs instead.

**Comment by FangedParakeet** [comment]
> Why have we decided to convert it to RGB? Does it break anything?

I left a comment here in my previous PR -> https://github.com/Automattic/woocommerce-payments/pull/8230#discussion_r1501043601

> AFAICT, Stripe only allows rgba colours with transparency for border outlines; otherwise the appearances API will ignore them and present a warning in the console.

Note that RGBA colours did not produce errors, but rather warnings in the console. It's possible that Stripe has updated this since and now supports RGBA, so if there are no warnings in the browser console, we may be in the clear here.
