### ISSUE TITLE
Transaction Fee shows when payment is authorized but not captured

### ISSUE THREAD

**Issue by rossviviano** [Automattic/woocommerce-payments#9418]
### Describe the bug

No fee should be taken when authorizing a charge. However, when authorizing a transaction in WooPayments, the "Transaction Fee" line item is populated with a fee, even if the charge isn't captured. 

### To Reproduce

1. Set WooPayments to "Issue an authorization on checkout, and capture later"
2. Place an order (but do not capture the charge)
3. Look at the order, and see the Transaction Fee

The correct fee amount ($0.00) shows in Stripe for authorized charges. 

### Screenshots

Here, we can see an uncaptured charge showing a transaction fee:

![Screenshot](https://d.pr/i/a2TwOj+)
Image Link: https://d.pr/i/a2TwOj

In Stripe, however, we can see the correct fee of $0.00:

![Screenshot](https://d.pr/i/KYvimg+)
Image Link: https://d.pr/i/KYvimg

### Expected behavior

I'd expect that no fees would show until the transaction is captured. 

### Desktop (please complete the following information):

* OS: Sonoma 14.6.1
* Browser Chrome/ Firefox

Reported in 8711849-zen

**Comment by AashikP** [comment]
Just adding some more details.

When the payment is authorized, fee details are not included in order notes:

The tooltip also says:

<img width="507" alt="image" src="https://github.com/user-attachments/assets/5df2d82c-9e2a-44c7-bdaf-ac96661ba528">

Under **Payments → Transactions**, we do not see fee info until the payment is captured:

<img width="1129" alt="image" src="https://github.com/user-attachments/assets/566a78e0-f02b-4b05-a0e5-da15cbcca4fc">


After capture:

<img width="1133" alt="image" src="https://github.com/user-attachments/assets/f5bc2087-02b4-4604-96c5-c86ffa23bb5f">

In comparison, the Stripe extension does not show the transaction fee at all on the Order details page (even after payment is captured) if the extension is set to authorize payment: (cc @imodouglas as PA to further investigate and report as bug if required)

<img width="912" alt="image" src="https://github.com/user-attachments/assets/a75aaaa9-7c87-4635-a146-2f13fc2511f0">

<img width="758" alt="image" src="https://github.com/user-attachments/assets/c469d921-3c3a-4bde-8efe-d1a18e48ccc5">

**Comment by csmcneill** [comment]
> In comparison, the Stripe extension does not show the transaction fee at all on the Order details page [...]

@AashikP @imodouglas There is a related issue on the Stripe for WooCommerce repo at https://github.com/woocommerce/woocommerce-gateway-stripe/issues/2478
