### ISSUE TITLE
WooPay is not automatically enabled in sandbox test-drive flow

### ISSUE THREAD

**Issue by csmcneill** [Automattic/woocommerce-payments#9421]
### Describe the bug

When onboarding in sandbox mode via the test-drive flow (see https://github.com/Automattic/woocommerce-payments/pull/9109), WooPay is not automatically enabled.

Originally reported in https://github.com/Automattic/woopay/issues/2922

### To Reproduce

1. Spin up a new JN site

> [!WARNING]
> Do not use the dev tools option when creating the site. See p1726100013463429/1726097935.447679-slack-C022WMN88KG for more details.

2. Install and activate WooCommerce
3. Configure the store location as a US state (e.g., California)
4. Install and activate WooPayments
5. Onboard in sandbox mode
6. Navigate to **Payments > Settings**
7. Note that WooPay is not automatically enabled

### Actual behavior

WooPay is not automatically enabled when in sandbox mode. It is automatically enabled on a live account.

We've been able to reproduce in 8.1.1 and 8.2.0.

### Expected behavior

WooPay is automatically enabled in sandbox mode, which creates parity with the live mode experience.

**Comment by senadir** [comment]
Even when I force enable it via the dev tools plugin, I still need to manually enable it.

**Comment by csmcneill** [comment]
Thanks for confirming that @senadir! Another a11n ran into an issue with this, so I wasn't sure how the dev tools affected the flow.

@FangedParakeet I see you're triaging this week. Is `focus: woopay` appropriate here, or would something else be a better fit since this is primarily a sandbox mode issue and not a WooPay issue?

**Comment by FangedParakeet** [comment]
> I see you're triaging this week. Is focus: woopay appropriate here

`focus: woopay` sounds about right to me--at the least, this will put it in the right queue for now, where if we decide this isn't the right fit after all, we can assess and redirect. 👍

**Comment by bborman22** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Fractal-62a0f7b955648b001e1f5e1f/issues/Automattic/woocommerce-payments/9421?planning-poker) with Zenhub @asumaran @lovo-h @rafaelzaleski @ricardo
