### ISSUE TITLE
WooPay T&Cs copy is illegible on sites with certain background colors

### ISSUE THREAD

**Issue by pierorocca** [Automattic/woocommerce-payments#9430]
### Describe the bug
On my shortcode site with a blue background, the WooPay T&Cs are illegible against the background. 

![image](https://github.com/user-attachments/assets/39a922df-637e-4d6d-8801-e6624d1ed6dd)

### Acceptance criteria
Instead of using fixed WooPay colors for the component, use the site's text and link colors so the copy is legible and so the component looks integrated.

@nikkivias should we use any of the site's styling?

**Comment by alefesouza** [comment]
This is fixed on https://github.com/Automattic/woocommerce-payments/pull/9497, it was forced to be black and grey so I just removed it to inherit the site text color, @nikkivias is this okay for you?

<img width="810" alt="Screenshot 2024-09-26 at 1 47 30 PM" src="https://github.com/user-attachments/assets/6d790e62-8ebd-4574-acd1-6127377417c8">
<img width="810" alt="Screenshot 2024-09-26 at 2 56 51 PM" src="https://github.com/user-attachments/assets/b7479d2e-0411-4da6-abbc-472534d5bd68">
