### ISSUE TITLE
Checkout Block doesn't submit the form when WooPay is enabled.

### ISSUE THREAD

**Issue by asumaran** [Automattic/woocommerce-payments#9437]
### To Reproduce

- Create a Jurassic Ninja site with WooCommerce, WooPayments, and WC Dev tools
- Go through the onboarding.
- **Make sure WooPay is enabled.**
- Install the WooCommerce Subscriptions plugin.
- Create a page, add the classic checkout (shortcode checkout) to it.
- Go to WooCommerce > Settings > Advanced
  - Set the checkout page to the page you just created in the previous step.
- Create a simple subscription.
- **Checkout using the page that has the Checkout block**.

### Actual behavior

Form doesn't submit

### Expected behavior

Form should submit and the order to be processed successfully.

**Comment by asumaran** [comment]
It seems it's not necessary to set the Shortcode Checkout as the Checkout page to observe the error.

**Comment by frosso** [comment]
Can this be closed now that https://github.com/Automattic/woocommerce-payments/issues/9449 is fixed?

**Comment by a-danae** [comment]
Closing this as a duplicate of https://github.com/Automattic/woocommerce-payments/issues/9449
