### ISSUE TITLE
Google & Apple Pay buttons are displayed in editor even when the payment method is disabled

### ISSUE THREAD

**Issue by alexflorisca** [Automattic/woocommerce-payments#9444]
### Describe the bug

The Google & Apple Pay buttons are displayed in editor even when the payment method is disabled in WooPayments settings.

### To Reproduce

1. In wp-admin, go to WooCommerce > Settings > Payments > WooPayments page
2. Disable Apple / Google Pay
3. Open the checkout page in the editor
4. See that the Apple & Google pay buttons are still rendered in the editor

### Actual behavior

The Apple and Google Pay buttons are visible in the editor when they are disabled in settings.

### Expected behavior

The Apple and Google Pay buttons should not be visible in the editor when they are disabled in settings.

### Potential solution
We should only call `registerExpressPaymentMethod` if it is enabled from the WooPayments settings page

**Comment by Shravanth007** [comment]
hey can you give more clarification on this i am unable to find a settings page on the main website

**Comment by alexflorisca** [comment]
> hey can you give more clarification on this i am unable to find a settings page on the main website

I've edited the steps to reproduce above to be a bit clearer. Let me know if you still have an issue to reproduce. Perhaps the following video is also useful

https://github.com/user-attachments/assets/a9203513-8e6f-4e45-8618-713d7d383f0e

**Comment by Shravanth007** [comment]
Assign this to me I will try to work on this.

**Comment by gpressutto5** [comment]
Hi @CodingWithError, thanks for your interest in helping. Do you still plan on working on this issue? If not, I'll assign it to myself.

**Comment by gpressutto5** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Heisenberg-63586f2ec60359001310fa6a/issues/Automattic/woocommerce-payments/9444?planning-poker) with Zenhub @FangedParakeet
