### ISSUE TITLE
Google/Apple Pay buttons wrong size

### ISSUE THREAD

**Issue by pawkat** [Automattic/woocommerce-payments#9446]
### Describe the bug
Hi, I have an issue with the google/apple buttons’ width. The article https://developer.woocommerce.com/docs/user-experience-guidelines-payment-button-size-and-anatomy/ shows that these buttons can be small, but when I set the small width to have 3 buttons in a row, the Google Pay button is not shown.

How it works screenshot: https://prnt.sc/TGPe33kwltly.
And the bug screenshot: https://prnt.sc/2VuZ4EW-g4N6.

We want to use PLAIN button https://prnt.sc/YpWZ4GtKDVuH.

Here is the settings https://prnt.sc/3_4Y9LU2X9qK. In the settings choosed only icon, but it still displaying icon and credit card ending. Our theme doesn’t containing hooks for modifying this button, only modifying markup to have 2 cols checkout

If I set the storefront theme and just use woocommerce_checkout shortcode – still the minimum width for button is 232px https://prnt.sc/pl9ZrNQGnigM, https://prnt.sc/l22H_A8xh9IU. Doesn’t matter what size I choose in the settings small/medium/light.

### To Reproduce
1. Enable google/apple pay buttons in WooPayments
2. Visit checkout page 
3. Set for the button 100px width

### Actual behavior
The button is not shown

### Screenshots
https://prnt.sc/2VuZ4EW-g4N6

### Expected behavior
Shown small button(only google/apply pay icon, without card ending etc.)

### Desktop (please complete the following information):

* OS: Mac OS
* Browser chrome
* Version 128.0.6613.138

**Comment by pierorocca** [comment]
Hi @pawkat thanks for reaching out. [The minimum width that Stripe allows, who power our buttons, is 150px.](https://docs.stripe.com/elements/express-checkout-element#create-an-express-checkout-element) 

I suspect this is to accommodate the various buttons and Google Pay's display of the card brand logo and last 4 card digits. I would encourage you to support the last 4 digits. It has doubled Google Pay usage over the version without it.  The last 4 feature is part of Google's implementation with Stripe and we don't have control of that behaviour.

**Comment by pawkat** [comment]
Hi @pierorocca, as you can see, for me, the minimum width is 232px. 
<img width="1439" alt="image" src="https://github.com/user-attachments/assets/07972c9c-4247-47ac-839c-c0712a625709">
<img width="1439" alt="image" src="https://github.com/user-attachments/assets/7cfae80e-1210-4cc4-ac9f-0b7dccda2057">
I can have 3 buttons in a row it google pay button will be 150, but it doesn't work

**Comment by pawkat** [comment]
@pierorocca Why you marked this task as closed?

**Comment by pierorocca** [comment]
Hey @pawkat I was under the impression you need 100px width and no card ending in text, both of which we have no control over. 

I can look into why the min width is 232 instead of 150 if that's helpful?

**Comment by pawkat** [comment]
@pierorocca yes, 150px will be helpful, take a look on it, please

**Comment by pawkat** [comment]
@pierorocca Ideally we want to have the next design 
<img width="259" alt="image" src="https://github.com/user-attachments/assets/f60597bd-c7ba-46bc-b14b-8448cee4242b">

**Comment by pawkat** [comment]
apple/google pay without card number

**Comment by pierorocca** [comment]
> apple/google pay without card number

This is not technically possible for Google Pay.

**Comment by pierorocca** [comment]
@pawkat I received info back from Stripe on the minimum widths. The 150px minimum they said applies when GPay is not present. As mentioned, we're unable to alter the last4 or the logo at all as it's controlled by Google. We've seen awesome results with GPay usage doubling since the change. GPay has a higher checkout conversion rate than card form based payments so there's a tradeoff of form over function that we're ok with. I know that doesn't meet your design requirements as we're bound by these constraints. For that reason, I'll be closing this issue as a can't do.

Stripe Response
> Thank you for flagging this! Turns out, GPay displaying last4 is a recent change, and the minimum width for GPay specifically is 240px (per Google's requirement). I have made a request to update our docs. What we currently note as 150px is a general guideline since it holds good for most PMs (GPay being an exception).

**Comment by pierorocca** [comment]
Some good news @pawkat Stripe followed up and let us know they're working on an upgrade that would allow the button sizes to go as low as 90px including GPay. I don't have an exact date but they've indicated likely by the end of the year.
