### ISSUE TITLE
Classic checkout js broken with custom templates

### ISSUE THREAD

**Issue by miguelpeixe** [Automattic/woocommerce-payments#9447]
### Describe the bug

#8502 introduced a change in the handling of the classic checkout that might break the form for custom templates.

In Newspack, we have a 2-step modal checkout experience that doesn't render the billing fields in the standard way when in the payment section. Instead, it renders them in hidden inputs because they have been previously edited.

Because the inputs are not inside a `.form-row`, the `$formRow.classList.contains()` call will cause a js crash and break the form submission. We're tweaking our strategy in https://github.com/Automattic/newspack-blocks/pull/1883, but it would probably be a good idea to check if that node exists before the validation.

**Comment by danielmx-dev** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Heisenberg-63586f2ec60359001310fa6a/issues/Automattic/woocommerce-payments/9447?planning-poker) with Zenhub @FangedParakeet
