### ISSUE TITLE
[WC Payments NOX] Spike: Analyse existing React components and identify gaps

### ISSUE THREAD

**Issue by vladolaru** [Automattic/woocommerce-payments#9451]
### Description

Before starting the implementation of the new React-based WooCommerce Native Onboarding eXperience (NOX) via the Payments settings page we need to get a grip on what React components we will use to:
- avoid reinventing the wheel
- reuse existing work
- align with upstream developments and initiatives (especially around the overall WC settings pages but also overall WP admin efforts with Gutenberg)

### Acceptance criteria

Publish a P2 post that will:
* Identify React components (from WC or WP) to be used directly
* Identify React components (from WC or WP) to be used but customized/forked
* Identify the areas where we will need new components
* Identify the areas where we will provide custom solutions since the UI is specific to the Payments settings page

### Designs
Design post: pfHfG4-q7-p2
Figma: xO8YdpKfaVoP2d8NvweZ5I-fi-1428_21437

### Dev notes
Reactifying the Payments settings page: pe4Hk0-1ly-p2
Populate react-powered main payments settings screen PR: https://github.com/woocommerce/woocommerce/pull/50825

### Additional context
PRD: 1wMfX8CAjDnOp24tcU-PADB0pOt3cz7mGdyZYeRBxx2Y-gdoc

**Comment by vladolaru** [comment]
A couple of resources and discussions:
- Fork DataViews component or build custom component: p6riRB-b05-p2
- WC Launch Your Store: pfwcF5-3N-p2

**Comment by oaratovskyi** [comment]
The spike is done, the results are published in pe4Hk0-1zc-p2

**Comment by anu-rock** [comment]
Note to myself - the effective closing date is Sep 26 when Oleks posted the final remark.
