### ISSUE TITLE
Update PMME implementation on the PDP to eliminate dead space

### ISSUE THREAD

**Issue by pierorocca** [Automattic/woocommerce-payments#9456]
p1726566945164299-slack-CGGCLBN58
Following up on the conversation above, the PMME and skeleton are being loaded on PDPs even when there's no offer available. This leads to a loader that, when removed, leaves dead space on the page. This was brought up as a problem with minimum order amount not being met and solved [here](https://github.com/Automattic/woocommerce-payments/pull/9355). The same type of solution needs to be applied to all BNPL payment method requirements so that no skeleton or dead space appear on the page, and no elements are shifted.

_Originally posted by @mdmoore in https://github.com/Automattic/woocommerce-payments/issues/9126#issuecomment-2356583837_

**Comment by mdmoore** [comment]
Hey @pierorocca @FangedParakeet  👋. Just want to run some demos by you before merging #9626. To recap, when no BNPL offer is available on PDPs, the skeleton loader still appears only to reveal a dead space. We want to avoid showing a loader or dead space when no offer is available. 

| Before - skeleton and dead space                                                                                   | After                                                                                   |
|------------------------------------------------------------------------------------------------------------------------|---------------------------------------------------------------------------------------------|
| ![Image](https://github.com/user-attachments/assets/a16add15-c984-4242-a95e-47ba2472dfe6)                              | ![Image](https://github.com/user-attachments/assets/384673e5-995f-4093-b5c7-62558c1998f9)   |

I noticed similar issues when transaction limits are hit upon quantity updates. I've fixed this by slide toggling the PMME as offers become available/unavailable.
| Before - dead space when transaction limit is hit                                                                  | After                                                                                   |
|------------------------------------------------------------------------------------------------------------------------|---------------------------------------------------------------------------------------------|
| ![Image](https://github.com/user-attachments/assets/498cbbb9-753b-4b89-8359-9463b57d3219)                              | ![Image](https://github.com/user-attachments/assets/e9aca8b6-e04b-4b92-b5e8-fc790b7aced4)   |

I also noticed that payment methods were not responding to transaction limit changes. For example, increasing the quantity of a $5 product to 10 did not display Affirm, even though it's lower transaction limit is $50. This isn't specific to Affirm. Payment methods will now filter in and out as expected based on product price.
| Before - No Affirm when minimum is met                                                                             | After                                                                                   |
|------------------------------------------------------------------------------------------------------------------------|---------------------------------------------------------------------------------------------|
| ![Image](https://github.com/user-attachments/assets/a2419085-7723-4e3b-b84e-233d6721e83a)                              | ![Image](https://github.com/user-attachments/assets/63c36638-443a-44f3-bf36-9cdb91116075)   |

Another bug I encountered was, if there's a product in the cart, the PMME uses that total when determining which payment methods to display:
| Before - $5 in cart $60 product                                                                                   | After - $5 in cart $60 product price is used                                            |
|------------------------------------------------------------------------------------------------------------------------|---------------------------------------------------------------------------------------------|
| ![Image](https://github.com/user-attachments/assets/95958a06-d043-4273-a9c9-bbb89745351f)                              | ![Image](https://github.com/user-attachments/assets/93604f4d-eb1e-4acb-bad1-0f3967a58d14)   |

A bigger issue discovered is that we're not actually using the BNPL minimums. Instead we're applying Stripe transaction minimums as BNPL minimums. For example, a 50 cent minimum is applied leading to the skeleton loader appearing when it shouldn't as the actual BNPL minimum is $1. BNPL min/max limits per currency are now applied correctly.

| Before                                                                                                             | After                                                                                   |
|------------------------------------------------------------------------------------------------------------------------|---------------------------------------------------------------------------------------------|
| ![Image](https://github.com/user-attachments/assets/6440c41e-74f4-4f5a-9351-bd8f2c28cdb2)                              | ![Image](https://github.com/user-attachments/assets/82b751b9-2f3b-4c25-91a7-536e5957815e)   |

**Comment by pierorocca** [comment]
@mdmoore truly awesome work here paying attention to detail and quality of the experience. The bug finds and fixes are the icing on top. Well done.

**Comment by pierorocca** [comment]
@elizaan36 FYI only to help ease you back into things.

**Comment by pierorocca** [comment]
@mdmoore one thing @FangedParakeet and I noticed prior is that the express checkout buttons could paint at different times than the PMME making the overall experience feel piecemeal.

If you zoom out, what's the before and after when also looking at the express checkout buttons?

**Comment by mdmoore** [comment]
>If you zoom out, what's the before and after when also looking at the express checkout buttons?

I wouldn't say that experience has been affected by these changes much. WooPay always loads with the page content. ECEs seem to finish faster than the PMME, though in some cases they load at the same time. The PMME is generally slower to finish. It does all seem a bit chaotic. Each element, the PMME and ECE, requires a separate request to Stripe. I'm not sure what we could do to make the loading smoother beyond waiting until all requests are finished before displaying the elements. That would mean slower perceived page load though. 

| Before                                                                                                             | After                                                                                   |
|------------------------------------------------------------------------------------------------------------------------|---------------------------------------------------------------------------------------------|
| ![Image](https://github.com/user-attachments/assets/3a3e6d96-2202-4641-857a-b7ffe93c58a8)                              | ![Image](https://github.com/user-attachments/assets/f91aa719-99ab-4fde-8e3c-87b3d685b256)   |

**Comment by pierorocca** [comment]
Thanks @mdmoore. Do you see any performance opportunities for ECE so that it loads with the page? When I benchmark other experiences, the express checkout buttons load with the page and then the BNPL offer renders as needed. That 1-2 is acceptable. The 1-2-3 sequence is a bit choppy and degrades the feeling of smoothness.
