### ISSUE TITLE
Respect maximum order amount when adding the PMME to the page

### ISSUE THREAD

**Issue by cesarcosta99** [Automattic/woocommerce-payments#9459]
### Describe the bug

Originally reported [here](https://github.com/Automattic/woocommerce-payments/issues/9244#issuecomment-2340956569). Similar to #9244, the container with ID `payment-method-message` is still added to the page and contains an empty Stripe iframe when a maximum order amount is hit. The skeleton loader appears too, but no PMME is displayed when loading is finished. The result is a loader that appears to load nothing and finally a dead space.

### To Reproduce

1. As a merchant, enable all BNPL payment methods.
2. Set your currency to USD.
3. Create a product that is more than $1,000,000.00.
4. As a shopper, navigate to the product and see the dead space created by the PMME component.

### Actual behavior

Dead space in the product page when all BNPL payment methods are active, currency is USD and the product is more than $1,000,000.

### Screenshots

![Screen Shot 2024-09-10 at 11 15 21 AM](https://github.com/user-attachments/assets/082b85f2-600a-477e-9f7c-f7f5c1ffa275)

### Expected behavior

No skeleton loading or dead space is observed when the aforementioned criteria match.

### Additional context

p1726566945164299-slack-CGGCLBN58

**Comment by pierorocca** [comment]
Noting here that BNPL payment methods have a max limit that are well below the $1M mark. e.g. Affirm is $30K USD and CAD.

**Comment by bborman22** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Fractal-62a0f7b955648b001e1f5e1f/issues/Automattic/woocommerce-payments/9459?planning-poker) with Zenhub @asumaran @cesarcosta99 @lovo-h @rafaelzaleski @reykjalin @ricardo

**Comment by cesarcosta99** [comment]
To whoever picks this up, the thread in the additional context points out to an interesting discussion where I can see a potential refactor based on Mike's message there. That refactor would benefit minimum and maximum limit implementations and make things tighter:

> If the billing country falls outside of the list of supported countries, the PMME isn’t rendered and all is well. But I wonder if we could just use the  `limits_per_currency`  for everything. It contains all supported countries. So if the billing country is found in that list and the amount is within it’s min/max range, render the PMME. Otherwise, don’t.

**Comment by mdmoore** [comment]
This was solved by #9626. Closing.
