### ISSUE TITLE
Applying V2 card styles to V1 element: Card brand icons on radio button

### ISSUE THREAD

**Issue by FangedParakeet** [Automattic/woocommerce-payments#9475]
### Description

Part of #9331

This is an incremental issue is to add card brand icons from V2 to the payment gateway radio button at checkout in V1. We should also remove existing brand icons from the card number input field. This applies to ~both shortcode and blocks~ _just the blocks_ checkouts. 

![Card brand icons](https://github.com/user-attachments/assets/1dab2aea-77da-4340-bd5f-ad4f6a9df1f3)
_Card brand icons placement_

Please find designs linked below in relevant P2. Card brand icons component should already exist in V2: if possible, we would like to reuse it here. 

### Designs

pfHfG4-gT-p2#comment-211

### Additional context

pfHfG4-gT-p2#comment-211

**Comment by FangedParakeet** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Heisenberg-63586f2ec60359001310fa6a/issues/Automattic/woocommerce-payments/9475?planning-poker) with Zenhub @gpressutto5

**Comment by gpressutto5** [comment]
@FangedParakeet @pierorocca The brand icons on the input are updated dynamically to show which card brand is being used. Should we remove that?

| <img width="533" alt="image" src="https://github.com/user-attachments/assets/095e549b-7c82-40b4-9758-ad71cc8424eb"> | <img width="504" alt="image" src="https://github.com/user-attachments/assets/27bebc00-551b-4332-bcc6-210ef1165e85"> | <img width="488" alt="image" src="https://github.com/user-attachments/assets/27b172da-8733-4521-acd8-f81502f6c58d"> |
| ----- | ----- | ----- |

This is also used to select the preferred brand when a cobadged card is used.
Stripe does not provide an option to hide that, and the Appearance API can't affect those. If we decide to go ahead with the change I'll ask if that's possible in the [Stripe Discord server](https://stripe.com/go/developer-chat).

**Comment by pierorocca** [comment]
Hey guys, Stripe hasn't enabled us yet to remove the animated logos from the card number field. They're supposed to provide an update on timing but the backup plan for now is https://github.com/Automattic/woocommerce-payments/issues/9331#issuecomment-2346495793. They will have an option for us by end of year I just don't know when exactly and there's a chance it could be part of a larger Stripe redesign effort that they have going on.

**Comment by gpressutto5** [comment]
Oh, I missed that, thanks @pierorocca!
