### ISSUE TITLE
Applying V2 card styles to V1 element: Test mode flag (shortcode)

### ISSUE THREAD

**Issue by FangedParakeet** [Automattic/woocommerce-payments#9487]
### Description

This is a follow-up issue to #9474. 

### Acceptance criteria

We would like to extend our V2 payment element designs to the V1 payment element. In #9474, we added the test mode flag to the blocks checkout. This should apply the same change to the shortcode checkout as well. 

> In Sandbox or in Test mode, the test copy is displayed.

### Designs

Please see #9474 and #9483 where this has been implemented on the blocks checkout for a visual comparison. 

### Dev notes

See #9483 

### Additional context

pfHfG4-gT-p2#comment-211

**Comment by danielmx-dev** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Heisenberg-63586f2ec60359001310fa6a/issues/Automattic/woocommerce-payments/9487?planning-poker) with Zenhub @FangedParakeet
