### ISSUE TITLE
Test mode badge should be rendered only for Credit Card

### ISSUE THREAD

**Issue by gpressutto5** [Automattic/woocommerce-payments#9513]
### Description
In #9483 we added the Test mode badge to all Payment Method labels, but the the design was to add it only to the Credit Card payment method.

![Image](https://github.com/user-attachments/assets/603badfd-5d2c-4e1b-a835-35fa89906c36)

### Acceptance criteria

- The Test mode badge is rendered only for credit card

### Designs

![Image](https://github.com/user-attachments/assets/11d7d0ad-006c-453f-b164-beeaa1f2085e)

### Additional context

paJDYF-foh-p2#comment-26617

**Comment by anu-rock** [comment]
**Triaging alert:** This issue concerns the checkout form and there is already a PR attached. Sending it to Heisenberg as per Pc2DNy-3z-p2 by adding the relevant focus label. cc @FangedParakeet
