### ISSUE TITLE
Apple Pay button not displayed on Checkout

### ISSUE THREAD

**Issue by pierorocca** [Automattic/woocommerce-payments#9518]
### Describe the bug
On procaatomic.wpcomstaging.com, the Apple Pay button is visible on PDP and Cart pages but not on Checkout. Running WooPayments 8.3.0.

![Image](https://github.com/user-attachments/assets/ae003340-a04e-41d7-88ca-a15fe138e127)

### Expected
Apple Pay button is visible on checkout on supported browsers.

**Comment by pierorocca** [comment]
@c-shultz could we get some eyes on this please? I'm seeing Apple Pay numbers really drop and this could be the cause. Please treat as urgent.

**Comment by aheckler** [comment]
Looks like this is only affecting the checkout block when WooPay is enabled. If WooPay is disabled or you're using checkout shortcode, Apple Pay shows up.

Lots of JS issues on the checkout page. It seems to think the domain isn't verified.

![Image](https://github.com/user-attachments/assets/8e8e335c-a9b8-462b-bf8f-7e17079d0f0e)

**Comment by aheckler** [comment]
CC @cesarcosta99 as this seems very similar to the issue you uncovered during testing:

p1726770977888069-slack-C01BZUL57SQ

**Comment by pierorocca** [comment]
Thanks for jumping in @aheckler. Much appreciated!

**Comment by asumaran** [comment]
It seems to fail when WooPay + Pre check is enabled on the site. Last fix we did about it was in https://github.com/Automattic/woocommerce-payments/pull/9450 cc @alefesouza

**Comment by cesarcosta99** [comment]
It looks like it's not related to pre-check, but it's confirmed to be WooPay-related. We're still investigating.
