### ISSUE TITLE
Advanced fraud protection page does not render the settings correctly

### ISSUE THREAD

**Issue by eduardoumpierre** [Automattic/woocommerce-payments#9520]
### Describe the bug

The settings on the Advanced Fraud Protection page are not being rendered/populated as expected. The data is stored correctly when the changes are saved, but it fails to display it in the UI.

### To Reproduce

1. Go to **Payments > Settings** and scroll to the **Fraud protection** section
2. Check the **Advanced** option and click on its action button
3. Scroll to the **Purchase Price Threshold** section and enable filtering
4. Save the changes
5. Refresh the page
6. The **Purchase Price Threshold** section will be empty/unchecked

### Expected behavior

1. The fraud protection changes should be reflected in the UI after saving them and refreshing the page

**Comment by csmcneill** [comment]
8861147-zen

My tests indicate that this is just a _visual_ bug. If I...
1. Configure WooCommerce to only accept payments in the US
2. Enable filtering for international IP addresses
3. Enable filtering for IP address mismatch
4. Use a VPN to change my IP address to another country (e.g., `DK`)
5. Make a payment using a non-US card (e.g., `4000002080000001` is a `DK` test card)

...the payment is blocked as expected:

![Image](https://github.com/user-attachments/assets/edfebff1-e07d-4921-a71f-e777e96e987e)
