### ISSUE TITLE
Express checkout button size for WooPay does not change in the preview

### ISSUE THREAD

**Issue by pierorocca** [Automattic/woocommerce-payments#9537]
### Describe the bug
Changing the express checkout button size does not result in the WooPay button size changing in the preview. This could give the impression that WooPay functionality on checkout is broken when if fact only the settings preview is broken.

[Recording](https://d.pr/v/MyoG09)

**Comment by bborman22** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Fractal-62a0f7b955648b001e1f5e1f/issues/Automattic/woocommerce-payments/9537?planning-poker) with Zenhub @asumaran @cesarcosta99 @lovo-h @rafaelzaleski @reykjalin @ricardo
