### ISSUE TITLE
Display transaction fee structure in timeline

### ISSUE THREAD

**Issue by thenbrent** [Automattic/woocommerce-payments#954]
As part of Automattic/woocommerce-payments-server#347, the transaction fee structure (e.g. 2.9% + $0.30) should be displayed against the fee amount in the timeline.

Example from Figma (link to the file in p1601350495093000-slack-CGGCLBN58):

<img width="961" alt="Screen Shot 2020-09-29 at 13 30 34" src="https://user-images.githubusercontent.com/235523/94509654-12293480-0258-11eb-9537-57dae7962c1b.png">

Additional related design work: paJDYF-T8-p2

**Comment by jrodger** [comment]
It might be tricky to derive a meaningful description for any given type of fee. We might want to consider simply adding a description against any fee structure we create.

Either way, that can all be handled on the server and this issue can likely just focus on the mechanics of fetching the text and displaying it.

**Comment by thenbrent** [comment]
I've added a link to the additional design work relating to this in the description now: paJDYF-T8-p2

**Comment by allendav** [comment]
@RadoslavGeorgiev - please add an update today or tomorrow - thx!
