### ISSUE TITLE
Rename "Deposits" to "Payouts" in Transactions list

### ISSUE THREAD

**Issue by nagpai** [Automattic/woocommerce-payments#9543]
We currently use "Deposits" to denote funds being sent from payment provider to the merchant. Merchants associate "Payouts" rather than "deposits" for this, and it can be confusing.

**Comment by Jinksi** [comment]
@nagpai This can probably be moved to `Done` once the PR has been merged to the feature branch – the automation won't close it until its merged to `develop`, I believe.

**Comment by nagpai** [comment]
The PR #9546 that fixes this issue has been merged with the feature branch - [feature/deposits-payouts-rename](https://github.com/Automattic/woocommerce-payments/tree/feature/deposits-payouts-rename) . Closing this issue and marking it as `done`. 

Thanks for the heads-up, @Jinksi  🙌🏼
