### ISSUE TITLE
WooPay no longer auto-enabled for new accounts

### ISSUE THREAD

**Issue by vladolaru** [Automattic/woocommerce-payments#9548]
### Describe the bug

Starting with the 8.3.0 release, WooPay is no longer auto-enabled for new US accounts.

### To Reproduce

1. Onboard a new WooPayments account with the `US` as the business location
2. Go to Payments > Settings and notice that WooPay is not enabled.

### Actual behavior

WooPay is not enabled.

### Expected behavior

WooPay should be enabled for all new US accounts.

cc @pierorocca @timmy5685

**Comment by pierorocca** [comment]
Cc @hsingyuc
