### ISSUE TITLE
System Status Report always shows Auth and Capture as enabled

### ISSUE THREAD

**Issue by AashikP** [Automattic/woocommerce-payments#9551]
### Describe the bug
System Status Report says Auth and Capture is enabled even though it is not enabled.

### To Reproduce

1. Make sure that authorization is not enabled

    ![Image](https://github.com/user-attachments/assets/23faa1c7-aeef-4cd2-839a-7f3508d07bee)
2. Check System Status Report:

    ![Image](https://github.com/user-attachments/assets/52fdf0aa-d0a9-4e42-907e-4b6b3ca4dbf2)

### Actual behavior
System Status Report always says `Enabled` irrespective of the status of Auth and Capture.

### Expected behavior
System Status Report should only say enabled when Auth and Capture is enabled.

### Additional context
Slack: p1728462757565959-slack-C7U3Y3VMY

**Comment by timur27** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Heisenberg-63586f2ec60359001310fa6a/issues/Automattic/woocommerce-payments/9551?planning-poker) with Zenhub @FangedParakeet
