### ISSUE TITLE
BNPL - Tax exclusive amounts are being used to display the PMME monthly calculations.

### ISSUE THREAD

**Issue by danielmx-dev** [Automattic/woocommerce-payments#9553]
### To Reproduce

1. Enable taxes and set a standard tax rate in your store (e.g. 20%)
2. In the Tax settings select  "No, I will enter prices exclusive of tax"
3. Enable Klarna, Afterpay, and/or Affirm.
4. Go to a product page.

### Actual behavior
The PMME calculation uses the price exclusive tax instead of the price with taxes. For example, a product that costs 40.83 with a 20% tax rate will cost 49; however, if you multiply the amount shown in the image (13.61) by the number of payments (3), the total will equal the tax exclusive price.
![Image](https://github.com/user-attachments/assets/96c9a662-87ab-47ae-8625-d69277c0da33)
![Image](https://github.com/user-attachments/assets/6762ad3c-cbf7-4bd8-ba91-89c61cddb997)

### Expected behavior
The amount displayed should be displayed using tax inclusive amounts, even if the product price is defined without them.

### Additional context
Originally reported in p1728626227629339-slack-C7U3Y3VMY

**Comment by danielmx-dev** [comment]
I have a WIP branch with a potential solution, but we'll need to discuss further with the team once we receive more details about the issue and after it has been triaged. https://github.com/Automattic/woocommerce-payments/compare/fix/9553-use-tax-inclusive-prices-pmme?expand=1

**Comment by AashikP** [comment]
To add a few things:

I could not initially replicate this in my US-based store. However, I can now, irrespective of the tax settings:

![Image](https://github.com/user-attachments/assets/206ce79d-2352-42f8-be62-b628781b7fed)
![Image](https://github.com/user-attachments/assets/8255abd1-7618-4e36-8a2d-46cf0f814fd9)
![Image](https://github.com/user-attachments/assets/2ee551f2-2e20-4279-b997-7472ee77fe71)

**Results on Single product page:**

![Image](https://github.com/user-attachments/assets/8256a28c-e0fa-45f3-95cd-27e7a2fc6979)
![Image](https://github.com/user-attachments/assets/111fd07b-5413-4211-81d2-ba7de8752e68)

**Works without issues on the Cart/Checkout page:**

![Image](https://github.com/user-attachments/assets/f0fa0758-2a6a-4eb3-a3c9-bdda7f64df1a)

**Comment by AashikP** [comment]
Merchant report 8848647-zen

**Comment by bborman22** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Fractal-62a0f7b955648b001e1f5e1f/issues/Automattic/woocommerce-payments/9553?planning-poker) with Zenhub @asumaran @cesarcosta99 @lovo-h @rafaelzaleski @reykjalin @ricardo

**Comment by pierorocca** [comment]
@AashikP we're targeting a fix in the 8.4.0 release.

**Comment by danielmx-dev** [comment]
@pierorocca Regarding on how this should be resolved. If the product page displays tax exclusive pricing, should the PMME use the tax inclusive amount anyway? Even if the amounts between the PMME and the product don't match? Or should we also use tax exclusive amounts to keep the numbers consistent ?

**Comment by danielmx-dev** [comment]
Per @pierorocca , we'll proceed with the following:

> Ideally whatever price is shown on the product page, is the price provided to the PMME component. That price, inclusive or exclusive of taxes, is configurable in Settings > Tax when WooCommerce Tax is installed.

So the PMME amounts should always match the display price of the product.
