### ISSUE TITLE
Set support phone number's initial value from onboarding phone number

### ISSUE THREAD

**Issue by anu-rock** [Automattic/woocommerce-payments#9556]
### Description

The support phone number field on the Payment settings page defaults to empty for newly onboarded accounts. When the merchant does not provide its value, support requests are routed to the platform's support phone number which leads to issues described at pbUcTB-5ch-p2

![Image](https://github.com/user-attachments/assets/2c5ecd70-813d-4afc-aded-4a1cd3e838d2)

### Acceptance criteria

Set this field using the phone number entered on the onboarding form.

![Image](https://github.com/user-attachments/assets/37aeb7c7-aecd-4c6b-9361-914a015db149)

### Dev notes

See my comment at pbUcTB-5ch-p2#comment-11620.

**Comment by dpaun1985** [comment]
After checking it,it appears that we cannot use [individual phone](https://docs.stripe.com/api/accounts/object#account_object-individual-phone). 
When fetching the account, the `individual` field is available in very specific situations - when `business_type` is `individual` and `controller.requirement_collection` is `application`.  In our case, requirement_collection is `stripe`

> Information about the person represented by the account. This property is null unless business_type is set to individual. After you create an [Account Link](https://docs.stripe.com/api/account_links) or [Account Session](https://docs.stripe.com/api/account_sessions), this property is only returned for accounts where [controller.requirement_collection](https://docs.stripe.com/api/accounts/object#account_object-controller-requirement_collection) is application, which includes Custom accounts.

More details are available [here](https://docs.stripe.com/api/accounts/object#account_object-individual)

I think we can close this issue.
cc @anu-rock

**Comment by aheckler** [comment]
> I think we can close this issue.

IMHO we shouldn't do this without some sort of solution, or else the issues in pbUcTB-5ch-p2 will persist. :( We need to find a way to make it mandatory to add a support phone, even if we can't use the phone number new merchants are entering during onboarding.

**Comment by dpaun1985** [comment]
as @timmy5685 mentioned in pbUcTB-5ch-p2#comment-11615 , an easy way to prevent merchants from saving changes to their settings until they provide that number. 
wdyt ?
cc @timmy5685 @anu-rock

**Comment by anu-rock** [comment]
@dpaun1985 Are you proposing to make the support phone field on the Settings page mandatory? It would seem that was @timmy5685's suggestion in case his preferred solution didn't work out.

**Comment by dpaun1985** [comment]
> [@dpaun1985](https://github.com/dpaun1985) Are you proposing to make the support phone field on the Settings page mandatory? It would seem that was [@timmy5685](https://github.com/timmy5685)'s suggestion in case his preferred solution didn't work out.

Indeed. I would go with @timmy5685's suggestion, to make the support phone field mandatory.

**Comment by timmy5685** [comment]
@dpaun1985 - looking at the docs - it appears that each business type object has a phone number. Can we detect the type and pull the phone number from the relevant object? i.e. if individual - use `individual.phone`, if company - use `company.phone`

I would still suggest making the phone number mandatory in settings so they can't remove it (or if for some reason they are missing a phone number on their respective object) but would be great if we could implement conditional logic based on business type.

**Comment by dpaun1985** [comment]
> [@dpaun1985](https://github.com/dpaun1985) - looking at the docs - it appears that each business type object has a phone number. Can we detect the type and pull the phone number from the relevant object? i.e. if individual - use `individual.phone`, if company - use `company.phone`

According to the [docs](https://docs.stripe.com/api/accounts/object#account_object-company), `company` or `individual` fields are returned only if [controller.requirement_collection](https://docs.stripe.com/api/accounts/object#account_object-controller-requirement_collection) is set to `application` .
In our case, `requirement_collection` is set to `stripe`. 
`controller.requirement_collection` - indicates responsibility for collecting requirements on this account.

**Comment by aheckler** [comment]
@dpaun1985 @timmy5685 If we can't set the support phone to the number provided during onboarding, I guess the next best solution is to make it mandatory on the settings page? My worry is that this isn't mandatory _enough_ though. Merchants can always just click out of the page, and since we're leaning more and more toward configuring the suggest payment methods for them, the chances that they need to alter anything on the settings page becomes lower and lower. :/

**Comment by anu-rock** [comment]
Based on @dpaun1985's findings, it sounds like we are technically limited in terms of fetching the phone number provided during onboarding. The alternative (pbUcTB-5ch-p2#comment-11615) is to either introduce a phone number field in MOX (non-trivial change, needs to be thought-through) or make the support phone field on the Settings page mandatory.

My suggestion is to take the latter approach while we keep looking for a longer-term solution (possibly as part of the second wave of Native Onboarding changes). That will reduce some if not all instances of this issue.

cc @aheckler @timmy5685

**Comment by aheckler** [comment]
WFM for now. I can draft some email comms to send to merchants who do not have a support number currently, kindly asking them to add one.
