### ISSUE TITLE
Rename 'deposit' to 'payout' in account status string

### ISSUE THREAD

**Issue by shendy-a8c** [Automattic/woocommerce-payments#9574]
Rename 'deposit' to 'payout' in account status string ([ref](https://github.com/Automattic/woocommerce-payments/blob/49103232e9aeaa1800d987032d652a216e087a80/client/components/account-status/account-tools/strings.tsx#L20)).

**Comment by nagpai** [comment]
PR #9611 that resolves this issue has  been merged with the feature branch. Marking this issue as done.
