### ISSUE TITLE
Rename 'deposit' to 'payout' in account status chip

### ISSUE THREAD

**Issue by shendy-a8c** [Automattic/woocommerce-payments#9575]
Rename 'deposit' to 'payout' in account status chip ([ref](https://github.com/Automattic/woocommerce-payments/blob/49103232e9aeaa1800d987032d652a216e087a80/client/components/account-status/status-chip.js#L37)).

**Comment by nagpai** [comment]
This will be resolved by #9529

**Comment by nagpai** [comment]
This has been fixed by #9529
