### ISSUE TITLE
Rename 'deposit' to 'payout' in SetupLivePaymentsModal

### ISSUE THREAD

**Issue by shendy-a8c** [Automattic/woocommerce-payments#9576]
Rename 'deposit' to 'payout' in SetupLivePaymentsModal ([ref](https://github.com/Automattic/woocommerce-payments/blob/49103232e9aeaa1800d987032d652a216e087a80/client/components/sandbox-mode-switch-to-live-notice/modal/index.tsx#L85)).

**Comment by nagpai** [comment]
Fixed by #9529
