### ISSUE TITLE
Rename 'deposit' to 'payout' in progressive onboarding modal

### ISSUE THREAD

**Issue by shendy-a8c** [Automattic/woocommerce-payments#9578]
Rename 'deposit' to 'payout' in progressive onboarding modal ([ref](https://github.com/Automattic/woocommerce-payments/blob/49103232e9aeaa1800d987032d652a216e087a80/client/overview/modal/progressive-onboarding-eligibility/index.tsx#L85-L86)).

**Comment by nagpai** [comment]
PR merged with feature branch . Closing this issue.
