### ISSUE TITLE
Rename 'deposit' to 'payout' in reset account modal

### ISSUE THREAD

**Issue by shendy-a8c** [Automattic/woocommerce-payments#9579]
Rename 'deposit' to 'payout' in reset account modal ([ref](https://github.com/Automattic/woocommerce-payments/blob/49103232e9aeaa1800d987032d652a216e087a80/client/overview/modal/reset-account/strings.tsx#L16-L17)).

**Comment by nagpai** [comment]
PR merged with feature branch. Marking the issue as closed.
