### ISSUE TITLE
Rename 'deposit' to 'payout' in update business details modal

### ISSUE THREAD

**Issue by shendy-a8c** [Automattic/woocommerce-payments#9580]
Rename 'deposit' to 'payout' in update business details modal ([ref](https://github.com/Automattic/woocommerce-payments/blob/49103232e9aeaa1800d987032d652a216e087a80/client/overview/modal/update-business-details/strings.tsx#L17)).

**Comment by nagpai** [comment]
Closing this issue as `Done` since the PR has been merged with the feature branch cc @jessy-p
