### ISSUE TITLE
Rename 'deposit' to 'payout' in account balance tooltip

### ISSUE THREAD

**Issue by shendy-a8c** [Automattic/woocommerce-payments#9586]
Rename 'deposit' to 'payout' in account balance tooltip ([ref](https://github.com/Automattic/woocommerce-payments/blob/49103232e9aeaa1800d987032d652a216e087a80/client/components/account-balances/balance-tooltip.tsx#L39)).

**Comment by nagpai** [comment]
This issue will be resolved by #9529 . Assigning this to @Jinksi who worked on the PR.
