### ISSUE TITLE
Blocks: Support the "create account" option

### ISSUE THREAD

**Issue by RadoslavGeorgiev** [Automattic/woocommerce-payments#959]
As described in [this comment](https://github.com/Automattic/woocommerce-payments/pull/723#discussion_r494208543), WooCommerce Blocks will have support for account creation through the checkout block once [the #2851 PR](https://github.com/woocommerce/woocommerce-gutenberg-products-block/pull/2851) gets merged.

Once the PR is merged, test whether the option works with WCPay. Make sure that the `updateOrderStatusNonce` gets updated here: https://github.com/Automattic/woocommerce-payments/blob/spike/stripe-react-elements/client/checkout/api/index.js#L149

---

## Testing instructions

![image](https://user-images.githubusercontent.com/5311119/152530156-b4a0a370-38ab-4263-9000-2d4f1d99b895.png)

1. Install [WooCommerce Blocks](https://github.com/woocommerce/woocommerce-gutenberg-products-block/).
2. Create a page, which contains the checkout block.
3. Modify the block by clicking the _Contact Information_ sub-block, and enabling the `Allow shoppers to sign up for a user account during checkout` setting (gif above).
4. Open the store in an private window where you are not logged in.
5. Add a product to the cart
6. Navigate to the page with the checkout block
7. Attempt checkout with an SCA-enabled card (ex. ***3184) and make sure to check the account creation checkbox.

You will see this:

![image](https://user-images.githubusercontent.com/5311119/152530313-c502ef60-bb3f-4896-ba6a-c5a96033921b.png)

Those errors are probably caused by the changed (or initial lack of) user data.

**Comment by naman03malhotra** [comment]
@achyuthajoy can you please test this as well, during your rotation.

**Comment by naman03malhotra** [comment]
@RadoslavGeorgiev to test this and see the relevancy

**Comment by RadoslavGeorgiev** [comment]
Tested, the flow does not change nonces, and everything works well. Nothing futher needed :)
