### ISSUE TITLE
Add npm script to update Playwright e2e snapshots

### ISSUE THREAD

**Issue by shendy-a8c** [Automattic/woocommerce-payments#9596]
There is already an npm script to update snapshot for unit tests: `npm run test:update-snapshots`.
However, I couldn't find one for Playwright e2e tests.

The readme [mentions](https://github.com/Automattic/woocommerce-payments/tree/develop/tests/e2e-pw#running-playwright-e2e-tests) the command to update the snapshots but it will be nice an "symmetrical" to unit test's if it's available as npm script as well.

**Comment by haszari** [comment]
> There is already an npm script to update snapshot for unit tests: npm run test:update-snapshots.
However, I couldn't find one for Playwright e2e tests.

I have no objection to us adding more npm scripts.

However I'd lean the other way:

- Keep the npm scripts to the bare minimum.
- Lean on documentation to encourage deeper understanding of our toolchain. 

If we have less scripts / aliases in our `package.json` it encourages everyone to learn the tooling directly. Scripts can act like a "buffer", a crutch on top of the tooling.
