### ISSUE TITLE
Rename 'deposit' to 'payout' in dev docs

### ISSUE THREAD

**Issue by shendy-a8c** [Automattic/woocommerce-payments#9601]
- Audit everything under https://github.com/Automattic/woocommerce-payments/blob/develop/docs.

~- https://github.com/Automattic/woocommerce-payments/wiki (critical flows etc).~

Wiki related changes have been moved to #9672 to prevent blocking changes to docs. Wiki changes will need to be merged after UI changes are merged, to prevent confusion for Global Step / Release testers.

**Comment by nagpai** [comment]
The linked PR covers changes to the dev docs. 

Changes to the Wiki will need to be done immediate after merge of the feature branch. ( to avoid confusion to Global step during the release process )

**Comment by nagpai** [comment]
Changes in PR #9669 merged to feature branch. Closing this issue.

**Comment by nagpai** [comment]
Changes to wiki covered by  https://github.com/Automattic/woocommerce-payments/issues/9672
