### ISSUE TITLE
Order notes says "payment has been disputed" for inquiries

### ISSUE THREAD

**Issue by raifd** [Automattic/woocommerce-payments#9612]
### Describe the bug

When a payment inquiry occurs, an order note shows _"Payment has been disputed for `amount` with reason `reason`. Response due by `date`."_

### To Reproduce

1. Purchase an order with the test card `4000000000001976`
2. View the order in WooCommerce Admin.
3. See order note mentions "dispute"

### Actual behavior

A note with the following text is added to the **Order notes**: _"Payment has been disputed for `amount` with reason `reason`. Response due by `date`."_

### Screenshots

![Image](https://github.com/user-attachments/assets/66718d52-0bf8-4fda-a5fe-2701dfd9a4ad)

### Expected behavior

The note should not indicate a dispute, instead a payment inquiry should be noted. 

### Desktop (please complete the following information):

* OS: macOS 15.0.1
* Browser: Google Chrome
* Version: 129.0.6668.101

### Additional context

Discussed in detail in Slack [here](https://a8c.slack.com/archives/C7U3Y3VMY/p1729257283105179). 

**Note: There might be additional enhancements needed to the UX and the way we display inquiries.**

**Comment by francoishvz** [comment]
Merchants affected by this:

8658095-zd-a8c
8903383-zd-a8c

**Comment by haszari** [comment]
See also related previous issue:

- https://github.com/Automattic/woocommerce-payments/issues/7885

Marking this as medium priority for now. It's painful when it occurs, but it's lower impact (not all merchants use Klarna). If we hear more reports of this we could raise priority. 

Also we need to confirm what we can do here, i.e. if there is a bug in our handling, or if the Klarna process itself is different (i.e. could the issue be fixed at Klarna end).

**Comment by haszari** [comment]
> Click on Report return

Note – this doesn't look to me like it should raise an inquiry. I.e. normally if you return a product, that's not an inquiry or a dispute (those are escalation paths if merchant doesn't accept return). So a related question is why are returns generating disputes at all?

Here are some relevant docs on return process in Klarna: 

- https://www.klarna.com/nz/return-instructions/
- https://www.klarna.com/nz/customer-service/how-do-i-return-my-order/
- https://www.klarna.com/us/customer-service/what-happens-when-i-report-a-return/

**Comment by brucealdridge** [comment]
I've updated the title to reflect that this issue is specifically about the order note and inquiries and unrelated to klarna.

I've also added simpler reproduction steps
