### ISSUE TITLE
Dynamically suggest default test card based on merchant country

### ISSUE THREAD

**Issue by aheckler** [Automattic/woocommerce-payments#9619]
Right now, with WooPayments in test mode, we always suggest using the Stripe `4242` card to test with:

![Image](https://github.com/user-attachments/assets/e89c32c7-3a5c-416e-a57e-0b4de809837e)

However, because this test card is a U.S.-issued card, merchants outside the U.S. will be faced with [additional (test) fees](https://woocommerce.com/document/woopayments/fees-and-debits/fees/#definitions) when they use it. To avoid that, we should dynamically suggest a test card (from [this list](https://docs.stripe.com/testing?testing-method=card-numbers#international-cards)) that matches the merchant's WooPayments account country.

Originally came up in 8658095-zd-a8c and this Slack thread: p1729673384290339-slack-C05QSQ0GT0U

**Comment by timur27** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Heisenberg-63586f2ec60359001310fa6a/issues/Automattic/woocommerce-payments/9619?planning-poker) with Zenhub @FangedParakeet

**Comment by timur27** [comment]
Hey @aheckler! We implemented this, [here's the package.](https://github.com/Automattic/woocommerce-payments/actions/runs/11740618193) if you want to try it out on you test site.

I also prepared a couple of JN sites for different countries 

UK account - https://perfectly-musical.jurassic.ninja/
PL account - https://reef-of-capybaras.jurassic.ninja/
US account - https://peaceful-okapi-ray.jurassic.ninja/


A couple of things worth noting: 
* If account country is not found on [the list](https://docs.stripe.com/testing?testing-method=card-numbers#international-cards), we fallback to the default `4242`
* If there are multiple test cards for a country provided on [the list](https://docs.stripe.com/testing?testing-method=card-numbers#international-cards), we use the first card provided
