### ISSUE TITLE
Dates not displaying in Deposits overview

### ISSUE THREAD

**Issue by dechov** [Automattic/woocommerce-payments#962]
The Deposits overview is no longer showing the next and last deposit dates. There are some (presumably unintentional) visual design changes as well but the main issue is that dates were intended to show up in the first two boxes (as seen in #560's screenshots) and they are now hidden:

<img width="1143" src="https://user-images.githubusercontent.com/1867547/94662926-1183b300-02d7-11eb-9c43-20701d7c7980.png">

The regression is due to [this update](https://github.com/woocommerce/woocommerce-admin/commit/7264fb188ee972c688a7d38a397342929085b6f0#diff-90fcf229de552082a1814a5368c62f11L130-R112) to the `<SummaryNumber>` component: the prop we are passing would now appear as a tooltip for a % delta, which isn't applicable for this usage. We should likely replace it with a different component – probably a new one unless there's still an existing one prescribed by the design.

**Comment by dechov** [comment]
Maybe replacing it isn't the best idea, since I guess we'd likely wind up rewriting the `<SummaryList>` component as well.

Essentially, the updated implementation of the `<SummaryNumber>` component doesn't fit our usage (of showing a date instead of a percentage below the value). Is there an upstream change we should consider here before just creating our own component? cc @LevinMedia @psealock

**Comment by DanReyLop** [comment]
After updating the `@woocommerce/components` dependency, this bug surfaces in the tests. I've added a comment [here](https://github.com/Automattic/woocommerce-payments/pull/1077/files#diff-7d088880b2a0c5deb1ffc8e927a12a135a6970189fc857987a3825b61919dc84R142) to fix/rewrite the failing test cases when this issue is solved.

**Comment by LevinMedia** [comment]
@dechov @psealock I think it would be idea to create an upstream change that would help us solve this use case rather than creating our own new summary numbers. Perhaps making the missing label an optional prop?

**Comment by psealock** [comment]
>Is there an upstream change we should consider here before just creating our own component?

Absolutely, changing the component to also handle a date instead of just a percentage seems like a very nice improvement. Happy to help with code review
