### ISSUE TITLE
Request recommended Payment Methods from NOX

### ISSUE THREAD

**Issue by mordeth** [Automattic/woocommerce-payments#9631]
### Description
This issue focuses on requesting and configuring the selected recommended payment methods from Native Onboarding Experience (NOX) located in WooCommerce core after successful account creation.

### Acceptance criteria
- LPMs and BNPLs selected during onboarding are requested and configured.

### Designs
- Figma: xO8YdpKfaVoP2d8NvweZ5I-fi-1428_21437

### Additional context
- One-pager: paJDYF-e7R-p2
- PRD: 1wMfX8CAjDnOp24tcU-PADB0pOt3cz7mGdyZYeRBxx2Y-gdoc

**Comment by oaratovskyi** [comment]
was closed in https://github.com/woocommerce/woocommerce/pull/53688
