### ISSUE TITLE
[WordPress 6.7] UI issues with `CustomSelectControl`

### ISSUE THREAD

**Issue by ilyasfoo** [Automattic/woocommerce-payments#9636]
### Describe the bug

UI issues with `CustomSelectControl` is observable with WordPress 6.7-RC1:

- The modal rendered disrupts the flow of the screen (elements pushed downwards when it's opened)
- Border seems missing
- Cursor shows text select when hovering over texts in dropdown items
- Checkmark icon to show selected item is rendered outside of intended area

This seems to be exclusively visual bug, no issue found with the dropdown's functionality.

### To Reproduce

1. Use [WordPress Beta Tester](https://wordpress.org/plugins/wordpress-beta-tester/) plugin and update to WordPress 6.7-RC1
2. Go to KYC screen
3. Click on any dropdown
4. Observe the issues

### Actual behavior

<img src="https://github.com/user-attachments/assets/48e4a5d1-848f-422b-ad86-8753f9149442" width="600"/>

### Expected behavior

<img src="https://github.com/user-attachments/assets/e5fef729-f298-43d8-8084-6a0f62687a37" width="600"/>

### Desktop (please complete the following information):

* OS: MacOS 14.4.1 (23E224)
* Browser Brave browser
* Version v1.71.118

**Comment by ilyasfoo** [comment]
Hey, @ismaeldcom 👋 

Tagging you because I saw your name in `CustomSelectControl` commit history, found this bug while doing testing for WordPress 6.7 readiness. pcShBQ-2qf-p2

**Comment by ismaeldcom** [comment]
Hi @ilyasfoo! I pretty much work with the server and MC since I switched to Sigma and I don't currently have the client set up to quickly look at this issue, so it will probably be better to ping @Automattic/moltres 🙂

**Comment by mordeth** [comment]
@ilyasfoo Thank you for creating the issue! I’ve assigned it to myself and will also review all instances where `CustomSelectControl` is used during onboarding.
