### ISSUE TITLE
Associate saved payment methods with the mode they were created in

### ISSUE THREAD

**Issue by reykjalin** [Automattic/woocommerce-payments#965]
Discussion in p1601537410119900-slack-wcpay.

Since payment methods saved in test mode can only been used in test mode, and payment methods saved in live mode can only be used in live mode, we should associate these saved methods with the mode they were made in.

This will prevent issues that come up when customers (accidentally or otherwise) save a card in test mode, and then try to use that card in live mode (and vice versa).

## Some things to keep in mind

- How does this affect subscriptions?

**Comment by allendav** [comment]
Assigning my best guess at size. Feel free to counter with a different size.

**Comment by dwainm** [comment]
@v18  @vbelolapotkov I'd like us to cloe this issue. I don't think it's important enough to warrant any further time on it.

**Comment by vbelolapotkov** [comment]
@dwainm I agree. We can reopen if needed.

**Comment by dwainm** [comment]
Thank you @vbelolapotkov, closing it.
