### ISSUE TITLE
Rename 'deposit' to 'payout' in Wiki section

### ISSUE THREAD

**Issue by nagpai** [Automattic/woocommerce-payments#9672]
All instances of 'deposit' within the wiki needs to be renamed to 'payout'. 

https://github.com/Automattic/woocommerce-payments/wiki (critical flows etc).

The wiki mainly consists of release related documentation referred to by Global Step and hence should be pushed only after the UI related renaming changes are merged. 

The issue is a part of a larger project to rename 'deposit' to 'payout' across the codebase.

**Comment by Jinksi** [comment]
I've proposed the required changes to [`Testing-instructions-for-critical-flows.md`](https://github.com/Automattic/woocommerce-payments/wiki/Testing-instructions-for-critical-flows) critical flows in this gist:

https://gist.github.com/Jinksi/56c54e75f25f6a118bfd365d8fe69743

Please review the [code diff](https://gist.github.com/Jinksi/56c54e75f25f6a118bfd365d8fe69743/revisions?source=1#diff-db4b5e1f1d52890f719dad6aed8b16a3a9a42a9e60686c6ced6e07a618ecfa20) or [rich/visual diff](https://gist.github.com/Jinksi/56c54e75f25f6a118bfd365d8fe69743/revisions?short_path=db4b5e1#diff-db4b5e1f1d52890f719dad6aed8b16a3a9a42a9e60686c6ced6e07a618ecfa20).

**Comment by Jinksi** [comment]
Note: back to `in-progress` – need to update screenshots.

**Comment by Jinksi** [comment]
Rather than regenerate all of the impacted screenshots (a siginificant portion of the 109 images), I've added the following notice to the critical flows:

![Image](https://github.com/user-attachments/assets/dffbbc5c-8d11-4fea-a0d6-877129ed4b59)

**Comment by Jinksi** [comment]
_Ready for review._

I've proposed the required changes to [`Testing-instructions-for-critical-flows.md`](https://github.com/Automattic/woocommerce-payments/wiki/Testing-instructions-for-critical-flows) critical flows in this gist:

https://gist.github.com/Jinksi/56c54e75f25f6a118bfd365d8fe69743

Please review the [code diff](https://gist.github.com/Jinksi/56c54e75f25f6a118bfd365d8fe69743/revisions?source=1#diff-db4b5e1f1d52890f719dad6aed8b16a3a9a42a9e60686c6ced6e07a618ecfa20) or [rich/visual diff](https://gist.github.com/Jinksi/56c54e75f25f6a118bfd365d8fe69743/revisions?short_path=db4b5e1#diff-db4b5e1f1d52890f719dad6aed8b16a3a9a42a9e60686c6ced6e07a618ecfa20).

**Comment by shendy-a8c** [comment]
@Jinksi it looks good to me. My biggest concern is to make sure anchor links are clickable and go to the correct section. To really test it, the change needs to be implemented live.

**Comment by Jinksi** [comment]
> My biggest concern is to make sure anchor links are clickable and go to the correct section. To really test it, the change needs to be implemented live.

Yeh I agree, thanks @shendy-a8c. I'll publish the wiki and ensure the anchor links work – easy to iterate.

**Comment by Jinksi** [comment]
I've updated the wiki with the changes proposed in the gist above: [see this revision](https://github.com/Automattic/woocommerce-payments/wiki/Testing-instructions-for-critical-flows/_compare/b178f507a153d6bcd8518bc6da3db8a9b556195e...0c9df5448c429f7c32730b2dfa3a2bf38133c0e5)

**Comment by Jinksi** [comment]
Anchor links work as expected. I've also changed deposit → payout within the flow names listed on the [**WooPayments critical flows** wiki page](https://github.com/Automattic/woocommerce-payments/wiki/Critical-flows).

Closing as complete.
