### ISSUE TITLE
Payouts: Add a spotlight notice to announce rename from 'deposit' to 'payout'

### ISSUE THREAD

**Issue by nagpai** [Automattic/woocommerce-payments#9673]
Add a dismissible spotlight notice to highlight the rename of 'deposit' to 'payout' for merchants. 

@rogermattic  shared a mockup of this: 

<img src="https://github.com/user-attachments/assets/82ec89cd-4a7f-4859-b248-79ee48725dcc" width="500px" /> 

There is a sweet component in WooCommerce core we can use

### Reference
* paJDYF-e8c-p2#comment-26855

**Comment by aheckler** [comment]
Dropped some feedback on the copy in Slack: p1730802947821119/1729049775.777369-slack-C02BW3Z8SHK

**Comment by rogermattic** [comment]
Thanks @nagpai for creating the issue, I'll update the screenshot with an updated copy and the updated illustration asap.

I also wondered if this component could be reused as mentioned here: p1730803519217269-slack-C074153PC (is this a correct way to point out to stuff in Slack?). Apparently team Ghidorah developed the spotlight as a part of some previous work and it would be good to link to the component directly, if that's OK @adrianduffell ?

**Comment by rogermattic** [comment]
@adrianduffell kindly shared that it is a reusable component in the WooCommerce packages [here](https://github.com/woocommerce/woocommerce/tree/trunk/packages/js/components/src/tour-kit)! So I hope it will save us some work @nagpai ?

**Comment by jessy-p** [comment]
Just to confirm, this will be shown once for the merchant, and once dismissed, will not be shown again ?

**Comment by rogermattic** [comment]
Hey @jessy-p ! That's right!

Also, just a note here, I'll finalise the copy of the spotlight and the illustration till the end of this week – will that give you enough time to swap the contents by the release, please?

**Comment by jessy-p** [comment]
>  I'll finalise the copy of the spotlight and the illustration till the end of this week – will that give you enough time to swap the contents by the release, please?

👋  @rogermattic Created a draft PR [here](https://github.com/Automattic/woocommerce-payments/pull/9680) though there is some pending work including tests, final copy and review etc. Our code freeze is this Friday, and we also have some AFK and additional hats on the team so it might be a challenge. Talked to @haszari  and it is fine to target 8.6, if we cannot make it in 8.5

**Comment by rogermattic** [comment]
> 👋 @rogermattic Created a draft PR https://github.com/Automattic/woocommerce-payments/pull/9680 though there is some pending work including tests, final copy and review etc. Our code freeze is this Friday, and we also have some AFK and additional hats on the team so it might be a challenge. Talked to @haszari and it is fine to target 8.6, if we cannot make it in 8.5

Thanks a lot – I've requested an illustration and a copy review and will confirm tomorrow what's the progress on that!

**Comment by shendy-a8c** [comment]
@rogermattic just to confirm when this spotlight ui should popup. It should popup when user goes to the deposits list page, right?
How about deposit details page? When user open the deposit details page, the 'Payouts' menu will be highlighted just like when they open the deposits list page, so maybe make sense to open the spotlight UI there too?

**Comment by rogermattic** [comment]
> just to confirm when this spotlight ui should popup. It should popup when user goes to the deposits list page, right?

Good question! I was thinking that it could popup when the user opens the dashboard in general for the first time after the name swap is released, WDYT? Otherwise if they somehow directly go to the Deposits list / Deposit page or a payment overview..

**Comment by rogermattic** [comment]
Update on assets: 

We have a revised copy now:
> **Deposits are now known as Payouts!** 
> Same reliable system for giving you access to your earnings quickly — a new, clearer name. In our quest to provide you with the best possible experience, we're making some changes to our terminology. "Deposits" will now be known as "Payouts"

[And the illustration in Figma](https://www.figma.com/design/q2b4LTEUhyw0y1vKmfEVpx/Deposits?node-id=3078-18080&t=o3qXpJTK2Inrjyfq-1):
![Image](https://github.com/user-attachments/assets/f18ad145-387d-41d3-8a50-80cfa1d031d2)
