### ISSUE TITLE
Include more payment method icons on the Order Received page for LPMs

### ISSUE THREAD

**Issue by FangedParakeet** [Automattic/woocommerce-payments#9682]
### Description

We would like to continue the work completed in #8897 by adding more payment method icons for LPMs to the Order Received page. This includes icons for the following payment methods.

- Bancontact
- BECS Direct Debit
- EPS
- iDEAL
- P24
- SEPA Direct Debit

Note that giropay and Sofort are no longer available for use. 

There should be icons available for all these payment methods already within the plugin, so these can be reused, and dark mode compatible icons should be used where appropriate and available. 

### Acceptance criteria

Icons for the payment methods linked above should appear on the following pages...
- Order Received page.
- Transactions page.
- Transaction details page.

### Designs

CC @elizaan36, but please refer to existing designs in #8897 and #8650 for guidance. 

### Testing instructions

1. Complete checkout for product using any of aforementioned payment methods.
2. Notice payment method is described in text on Order Received page rather than by icon.
3. No.

### Dev notes

N/A

### Additional context

#8897

**Comment by frosso** [comment]
Adjusting the original estimate to `1`. Because I was right during planning. And I picked the ticket. lol

**Comment by frosso** [comment]
@pierorocca FYI, here are some screenshots for proof:

### New

<img width="817" alt="Screenshot 2024-11-07 at 12 55 43 PM" src="https://github.com/user-attachments/assets/48e0fca8-7aa6-4d74-88a7-7ae6a620ec76">
<img width="838" alt="Screenshot 2024-11-07 at 12 55 30 PM" src="https://github.com/user-attachments/assets/b7f0dbd0-6b8b-44cc-b280-a756f33387c2">
<img width="822" alt="Screenshot 2024-11-07 at 12 55 23 PM" src="https://github.com/user-attachments/assets/f0907e5a-16e7-453c-a116-c252609d7f66">


### Unaltered
<img width="824" alt="Screenshot 2024-11-07 at 12 55 58 PM" src="https://github.com/user-attachments/assets/e363de4f-f0d0-4d6a-a18a-a500d46fa62d">
<img width="833" alt="Screenshot 2024-11-07 at 12 55 49 PM" src="https://github.com/user-attachments/assets/1b36e435-a858-4312-bcdc-62fb9784864f">
![Image](https://github.com/user-attachments/assets/452eb0e2-cb7a-4ac1-8fd6-18c89c346b75)
<img width="813" alt="Screenshot 2024-11-07 at 12 55 36 PM" src="https://github.com/user-attachments/assets/b07cf6ff-65a2-4ad8-bd27-d3e5947825a6">
<img width="828" alt="Screenshot 2024-11-07 at 12 55 11 PM" src="https://github.com/user-attachments/assets/16a5cc1c-7812-4935-8981-739fcad49d73">


With another theme:
<details><summary>Details</summary>
<p>

![Image](https://github.com/user-attachments/assets/3e301879-ef24-413c-8d3b-919fbcf1d279)
![Image](https://github.com/user-attachments/assets/d98c4e5a-abde-452b-88d8-1bbeb4493aef)
![Image](https://github.com/user-attachments/assets/ac7e83bd-d63e-403f-90b0-018ac6b6a38a)
![Image](https://github.com/user-attachments/assets/95bb0b5e-9c94-45ae-9285-44fc22d7fbe5)
![Image](https://github.com/user-attachments/assets/020fae98-22ee-4207-9e5c-69cc5a0b2171)
![Image](https://github.com/user-attachments/assets/cae74f9f-806f-43df-bd05-5257355fc811)
![Image](https://github.com/user-attachments/assets/0fd3d74c-98a0-47d5-b100-b4b421632138)


</p>
</details> 

Please note that icon sizes have not changed compared to the current state on `develop`.

**Comment by pierorocca** [comment]
Ignoring Nikki's spacing observation, looks good.
