### ISSUE TITLE
Spike: Scoping Tokenised Cart Integration with ECE

### ISSUE THREAD

**Issue by FangedParakeet** [Automattic/woocommerce-payments#9686]
# Description
The PRBs refactor to utilise tokenised carts project has been on-hold pending woocommerce/woocommerce#48540. We would like to revisit the remaining effort required to complete this project by integrating the tokenised cart implementation with the ECE. 

The purpose of this issue is to fully explore how the ECE is currently integrated with the existing PRB implementation and to plot out a path towards replacing it with the tokenised cart solution. Tokenised carts will need to replace the PRB on all pages where they are present, so a valuable outcome of this spike would be a set of issues to continue the tokenised cart project and complete the integration.

# Notes
pbIwZe-1Q4-p2

**Comment by frosso** [comment]
Closing this - plan outlined here: pbIwZe-2ur-p2
Tickets have been created, see post for reference.
