### ISSUE TITLE
Evidence submitted for Klarna Inquiries is ignored by Stripe

### ISSUE THREAD

**Issue by brucealdridge** [Automattic/woocommerce-payments#9703]
### Describe the bug

In WooPayments, we allow evidence submission for Klarna inquires, but this evidence is not considered by Stripe/Klarna. Evidence submission should be disabled for Klarna inquiries and copy should be added to help the merchants respond appropriately.

Available options for responding to Klarna Inquires
- Refund the payment
- Communicate with the customer to resolve the issue
- Wait for the inquiry to become a dispute to submit evidence.

### Changes required

![Image](https://github.com/user-attachments/assets/43dd5536-bc89-4979-90eb-0fc1e72547c5)

- [Email body copy](https://github.com/Automattic/woocommerce-payments/blob/bc057e7fc13716a1a26022f2c1e675b81994af0b/client/payment-details/dispute-details/dispute-steps.tsx#L196-L201) could be refined (Email the customer link)
  - `you disputed a $<amount> charge`. The customer likely has no knowledge of "dispute" may have initiated a "return"
  - Suggests `calling the number on the back of your card`
- [Remove](https://github.com/Automattic/woocommerce-payments/blob/bc057e7fc13716a1a26022f2c1e675b81994af0b/client/payment-details/dispute-details/dispute-steps.tsx#L243-L246) `Submit evidence <submitEvidenceIcon/> or ` 

It would be helpful to add some additional copy about the Klarna dispute process. @aheckler is it worth adding something to the docs that we can link to?

### Additional context

pdjTHR-3qO-p2#comment-6397

**Comment by haszari** [comment]
Marking as `high`, this is a broken experience, and hopefully can resolve without major effort. We've had a few of reports of this and we know that Klarna inquiries are relatively common, so worth prioritising.

**Comment by aheckler** [comment]
We have [some existing info in the docs already](https://woocommerce.com/document/woopayments/payment-methods/buy-now-pay-later/#klarna-inquiries-returns). Feel free to use and adjust that copy as needed. :)

Worth noting too that fraudulent transaction filings go right to being a dispute, and do not go through the inquiry phase. I pulled a lot of the relevant info from [this Stripe doc](https://docs.stripe.com/payments/klarna/disputes).
