### ISSUE TITLE
Fix translation notice during WooPayments plugin initialization

### ISSUE THREAD

**Issue by Aljnk** [Automattic/woocommerce-payments#9727]
Update: PHP Notices are triggered during plugin initialization. This issue should focus on fixing notice coming from plulgin init flow.

### Describe the bug

```
Function _load_textdomain_just_in_time was called incorrectly. Translation loading for the <code>woocommerce</code> domain was triggered too early. This is usually an indicator for some code in the plugin or theme running too early. Translations should be loaded at the <code>init</code> action or later. Please see <a href="https://developer.wordpress.org/advanced-administration/debug/debug-wordpress/">Debugging in WordPress</a> for more information. (This message was added in version 6.7.0.) in .../wp-includes/functions.php on line 6114
```

### To Reproduce
- WP 6.7.0.
- Other language the EN
wp-config.php -> define('WP_DEBUG',true);define('WP_DEBUG_DISPLAY',true);@ini_set('display_errors',0);define('SCRIPT_DEBUG',true);

### Actual behavior
Open any page

### Desktop (please complete the following information):

* OS: W11
* Browser chrome (last)

### Additional context
[debug.log](https://github.com/user-attachments/files/17774978/debug.log)

Internal investigation results by @mordeth (paJDYF-fWD):

> The second instance arises during the initialization of the WooPayments plugin, where all classes and gateways are initialized. The main source of the notices was identified as the gateway initialization process.

**Comment by vbelolapotkov** [comment]
For the context, stack trace points to Jetpack-sync package, rather than WooPayments src code, and translation domain is from core rather than WooPayments. So probably the problem has to be solved outside WooPayments repo.

**Comment by tsetend** [comment]
Hi @vbelolapotkov,

I have a [customer](https://a8c.zendesk.com/agent/tickets/9054470) who reported the error:


`Notice: Function _load_textdomain_just_in_time was called incorrectly. Translation loading for the woocommerce-payments domain was triggered too early. This is usually an indicator for some code in the plugin or theme running too early. Translations should be loaded at the init action or later. Please see Debugging in WordPress for more information. (This message was added in version 6.7.0.) in /home/eueu3893/public_html/wp-includes/functions.php on line 6114`


This error message specifically says `woocommerce-payments` does this still fall under WooCommerce core problem? If yes, is this: https://github.com/woocommerce/woocommerce/issues/53006 the related issue? Can you please help confirm as I want to ensure I'm not looking at the wrong issue?

Thanks!

**Comment by vbelolapotkov** [comment]
This is the main issue in Core: https://github.com/woocommerce/woocommerce/issues/52646
I'm yet to figure out if there is anything we could do in the plugin in order to avoid causing early translations before init.

For the context, here is the link to the source of changes in WP and the context behind it: https://core.trac.wordpress.org/ticket/44937

**Comment by vbelolapotkov** [comment]
I'm cutting this issue into two based on the investigation results. Updated this issue description and title to narrow down its focus.
Since this issue comes from "breaking" changes in WP 6.7, I'd treat it as a compatibility enhancement rather than a bug.

@deepakpathania sending this part to your team for further prioritization and fixing. Note, some collaboration with core team might be necessary for figuring out the best way forward. See @mordeth's post for more details.

**Comment by deepakpathania** [comment]
Will #9884 fix this as well? @zinigor

**Comment by zinigor** [comment]
It should, but I don't know if we have any other notices generated by the plugin during its use. The linked PR fixes the use case where the plugin loads i18n strings for Jetpack Connection.

**Comment by vbelolapotkov** [comment]
@deepakpathania I doubt it will. The error is the same, but it comes from multiple places as described in @mordeth's post. This issue is focused on fixing notice coming from payment gateway registration during WooPayments init.

**Comment by mordeth** [comment]
I confirm Vasily’s statement. PR #9884 would address only the error triggered by Jetpack.

**Comment by vbelolapotkov** [comment]
I don't think this issue was fixed, so reopening.

**Comment by pingram3541** [comment]
Please see https://github.com/Automattic/woocommerce-payments/issues/10676#issuecomment-2891601679
