### ISSUE TITLE
Update WooPay global theme settings copy

### ISSUE THREAD

**Issue by pierorocca** [Automattic/woocommerce-payments#9738]
### Description
We will update the new global theme support label and copy to better express the value to the merchant, to include a link to documentation, and to be consistent with case, spacing, and font used in settings.

![Image](https://github.com/user-attachments/assets/f19f9314-937f-4c01-9f54-09f3e9741e98)

### Acceptance criteria

1. The title is changed to "Checkout theme"
2. The checkbox label is changed to "Enable global theme support"
3. Add secondary text, on the next row: "When enabled, WooPay checkout will be themed with your store’s brand colors and fonts. Learn more [opens in new tab icon]."
4. Font family, size, and relative placement matches this pattern:
![Image](https://github.com/user-attachments/assets/cc0be7c3-0357-4963-b5f0-8007b60e40a2)

cc @hsingyuc

**Comment by pierorocca** [comment]
@aheckler could we get a placeholder url for this documentation that you could attach here please?

**Comment by aheckler** [comment]
It'll almost certainly go in the checkout appearance section:

`https://woocommerce.com/document/woopay-merchant-documentation/#checkout-appearance`

**Comment by a-danae** [comment]
☑  Issue added to the related WooPay epic. 

Just a heads up that the development for WooPay theming is currently on hold as the team focuses on individual issues while we define the project's next steps. We're planning to resume development late next week or the week after. We'll address this issue then, but happy to work on it earlier if needed.

**Comment by pierorocca** [comment]
@a-danae this is one issue that's well defined that we could work on while we sort out the style inheritance scoping, and since it's only a copy change.

**Comment by pierorocca** [comment]
What do you all think about adding a Beta badge to the feature title? If yes the Blocks FSE  has a Beta badge for Express Checkout styling overrides that we could use.
