### ISSUE TITLE
Usability: when payment server is n/a do not hide "Payment" menu entry silently

### ISSUE THREAD

**Issue by kalessil** [Automattic/woocommerce-payments#975]
Instead, it would be great to:
- Keep the menu entry, but display it as "disabled"
- Emit a notice/warning about server availability issues (perhaps with some troubleshooting or pointing to technical issue)

**Comment by dechov** [comment]
Thanks for raising this 👍 – related to https://github.com/Automattic/woocommerce-payments/issues/551

**Comment by vbelolapotkov** [comment]
Sort of fixed with #1133
