### ISSUE TITLE
Take advantage of GitHub Security tools

### ISSUE THREAD

**Issue by kalessil** [Automattic/woocommerce-payments#977]
GitHub offers basic built-in Security monitoring features here: https://github.com/Automattic/woocommerce-payments/security

- Security policy (Define how users should report security vulnerabilities for this repository), perhaps complimentary with #974.
- Security Advisories (Privately discuss, fix, and publish information about security vulnerabilities in your repository's code.)
- Dependabot alerts (similar to renovate bot, but with primary focus to deps security)
- Code scanning alerts (not sure though how good the available tools are)

**Comment by DanReyLop** [comment]
> Dependabot alerts

Let's not add this, `renovate bot` already has that same functionality (security updates).

**Comment by kalessil** [comment]
Closing as irrelevant - we added relevant tooling earlier last year.
