### ISSUE TITLE
ECE does not render on PDP when subscription product has a free trial but has a non-zero signup fee

### ISSUE THREAD

**Issue by pierorocca** [Automattic/woocommerce-payments#9776]
### Describe the bug
ECE does not render on PDP when subscription product has a free trial but has a non-zero signup fee

### To Reproduce
1. Create a simple or variable subscription product. Set to virtual.
2. Add a $20 signup fee
3. Shop the product
4. Observe that the ECE buttons are not rendered even though the cart total will be a non-zero value because of the signup fee.

### Actual behavior
- ECE buttons render if the total price + signup fee is > $0.

### Screenshots
![Image](https://github.com/user-attachments/assets/0f3cf9a9-939e-48d4-bf6f-257d0a5bdce0)

![Image](https://github.com/user-attachments/assets/ffb472b4-b50e-4498-a4de-20b9f92485cc)

**Comment by bborman22** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Fractal-62a0f7b955648b001e1f5e1f/issues/Automattic/woocommerce-payments/9776?planning-poker) with Zenhub @asumaran @cesarcosta99 @lovo-h @rafaelzaleski @reykjalin @ricardo

**Comment by rafaelzaleski** [comment]
I'll close this issue as it's no longer reproducible with the following versions:

- WooCommerce 9.5.1
- WooCommerce Subscriptions 7.0.0
- WooPayments 8.6.1
