### ISSUE TITLE
Free trial subscriptions can no longer be processed using WooPay

### ISSUE THREAD

**Issue by alefesouza** [Automattic/woocommerce-payments#9777]
### Describe the bug

(copied from the WooPay repo, text by @malithsen)

When placing a free-trial subscription, WooPay shows the following error
![Image](https://github.com/user-attachments/assets/df476fc2-8d05-488a-a5bc-31bbc839ad7d)

These orders seems to be failing due to an order ID mismatch in
![Image](https://github.com/user-attachments/assets/83578188-ab18-4e4b-b41b-9844519092f3)

### To Reproduce

1. As a merchant, create a free trial subscription
2. As a logged in shopper, purchase the above subscription using WooPay
3. See error when clicking on the "Place order" button in WooPay.

### Actual behavior

Shoppers are unable to purchase free trial subscriptions using WooPay

### Expected behavior

Shoppers should be able to purchase free trial subscriptions using WooPay.

**Comment by pierorocca** [comment]
Friendly reminder to use Focus labels instead of Component labels or it won't get pulled into triaging. Thanks @alefesouza.
