### ISSUE TITLE
Completed order email has incorrect payment method title

### ISSUE THREAD

**Issue by morepurplemorebetter** [Automattic/woocommerce-payments#9779]
### Describe the bug
Since #9647 was merged, the order confirmation emails include added content for the payment method title, which shouldn't be there.

### To Reproduce
1. Create a one-page checkout. I'm using shortcode `[woocommerce_checkout]`.
2. Make a test payment and have the email sent to yourself.
3. Note that the payment method listed in the email has a bunch of unnecessary text added to it.
4. Important to note that this problem doesn't happen when re-sending the order confirmation email from the order editing page.

### Screenshots
This is how the relevant part of an email for a test purchase on my staging environment looks now.
![Image](https://github.com/user-attachments/assets/813034a9-de72-4b5d-a52d-b4bdd21310a5)

### Additional context
It seems that [`is_checkout()` here](https://github.com/Automattic/woocommerce-payments/blob/22196f54091dc0d541fce1bd48d7200cefb2d26c/includes/class-wc-payment-gateway-wcpay.php#L584) here is returning `true` because the email is being sent from the checkout page. Perhaps an extra check can be added to prevent this happening for emails?

**Comment by frosso** [comment]
For posterity, I added some insight here: https://github.com/Automattic/woocommerce-payments/pull/9647#issuecomment-2491662204

I was trying to find a different approach to implement in the `get_title()` method, like checking if we're in an email context with something like
```php
		if ( did_action( 'woocommerce_email_header' ) ) {
			return $title;
		}
```

But that didn't seem to work. The payment method from the email is retrieved from the order, and it is set via the `WC_Order->set_payment_method()` method.

It looks like we might need to revisit the implementation of the "Test mode" badge on the shortcode checkout.
I'm not sure if we should implement a change in WC Core (to have better compatibility) or find another way of rendering the label (via JS, for example).

In the meantime, I added this filter that will land in WooPayments 8.6.0: https://github.com/Automattic/woocommerce-payments/pull/9783

A workaround to this issue with email templates could be achieved with the following code, using the filter mentioned in the previous paragraph:
```php
add_filter( 'wcpay_checkout_use_plain_method_label', 'is_ajax' );
```

**Comment by frosso** [comment]
CCing @pierorocca & @FangedParakeet on the above comment as well ☝

**Comment by pierorocca** [comment]
I'll catch up with you on DM to better understand how the badge is associated with the payment method label.

**Comment by raifd** [comment]
There is a report on this in 8658095-zen where Kadence WooCommerce Email Designer (a 3pd plugin) is displaying something similar. 

Here is a screenshot of what the customers see: 

![Image](https://github.com/user-attachments/assets/f41f97f5-34b3-448b-a186-a7aac8151c30)

And a preview of the email, on the customizer plugin:

![Image](https://github.com/user-attachments/assets/1b40c0fa-ed2d-40a1-8801-b29b688015e2)

cc. @frosso as discussed via DM

**Comment by frosso** [comment]
@morepurplemorebetter thank you again for the discussion and for logging the ticket!
We discussed within the team, and we'll be reverting the "Test mode" badge on shortcode checkout in the next patch release.
So you can ignore the `wcpay_checkout_use_plain_method_label` filter, for now.

We'll bring it back in a safer way in a future release.

Thanks for your patience!

**Comment by morepurplemorebetter** [comment]
@frosso thank you for taking the time to fix this issue and responding so kindly.
I'm looking forward to the next WooPayments version with which I can hopefully clean up my `functions.php` from its haphazard temporary patches.

**Comment by kaushikasomaiya** [comment]
#9073954-zen This is in the email as well as the order list page:
It occurs when a Afterpay or Klarna order fails:

![https://d.pr/i/qIPT1p](https://d.pr/i/qIPT1p+) 
Full Size: https://d.pr/i/qIPT1p
