### ISSUE TITLE
WooPay button shown in Apple Pay/ Google Pay preview in countries where WooPay is not eligible

### ISSUE THREAD

**Issue by pierorocca** [Automattic/woocommerce-payments#9787]
### Describe the bug
![Image](https://github.com/user-attachments/assets/25d815a7-4078-45fd-8d62-cdc773b9184c)

![Image](https://github.com/user-attachments/assets/a01dbd57-524b-48f4-a3c2-48961bb8ea18)

### To Reproduce
1. Setup a non-US store
2. Customize Apple or Google Pay settings
3. While on a US IP,  observe the WooPay button in preview

### Expected behavior
1. If the Merchant is not eligible for WooPay, WooPay is not shown in the preview
2. If the Merchant is eligible for WooPay AND has NOT enabled WooPay, WooPay is not shown in the preview
3. On the wp-admin side, there are no IP restrictions to being able to see the button unlike where it is IP restricted on the shopper client side.

cc @bborman22 @a-danae for awareness.

**Comment by bborman22** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Fractal-62a0f7b955648b001e1f5e1f/issues/Automattic/woocommerce-payments/9787?planning-poker) with Zenhub @cesarcosta99

**Comment by cesarcosta99** [comment]
@pierorocca, I wasn't able to reproduce this issue. I set up a Jurassic Ninja site and onboarded as a German store. WooPay was not eligible, exactly the same as shown in the second screenshot. However, the WooPay button was not displayed in the preview when using a US IP. @bborman22 tested as well and he got the same as me.

When looking at the code, [this logic](https://github.com/Automattic/woocommerce-payments/blob/dc35740e7b27d1368da9d1ee9ba7a8747a98d86b/client/settings/express-checkout-settings/payment-request-button-preview.js#L97-L104) indicates WooPay will only be displayed when it's active, which makes me infer that WooPay will only be displayed when it's eligible and enabled.

Do you have any examples of where this is happening and/or more details of how I can replicate this behavior?

**Comment by pierorocca** [comment]
Per our DM, I can replicate this when first onboarding as a US site and then switching to a non-US site through Payments > Overview > Reset Account action in wp-admin.

So this is unlikely a happy path bug but could be relevant for developer/builder led scenarios.
