### ISSUE TITLE
PMME text color should not be using the label color

### ISSUE THREAD

**Issue by gpressutto5** [Automattic/woocommerce-payments#9803]
### Describe the bug
In #9621 we fixed the Apparence API not being correctly applied to the PMME, however, we are using the label color as text color for this element. Because the Blocks Checkout uses floating labels, this color might not look good. We should update it to use the text color of a paragraph.

![Image](https://github.com/user-attachments/assets/f758dd2b-54a0-45c6-b6ad-a0e4c566e072)

### To Reproduce

1. Use a dark theme, or use CSS to update your background color to a dark color and the text color to a light color.
2. **Do not enable** Blocks Checkout dark mode.
3. Go to the blocks checkout and see the PMME does not look good.

### Additional context
p1731716238180769-slack-CU6SYV31A

**Comment by gpressutto5** [comment]
@pierorocca I think this should not be a high-priority ticket as it only looks broken when using a dark theme while not using the Blocks Checkout dark mode.

**Comment by pierorocca** [comment]
You'd be surprised how many sites do not use dark mode inputs. It's a really hard setting to find and I expect most sites would stick with white input field background.

A reminder to add focus labels when creating bug tickets to trigger the automated workflows for triaging.
