### ISSUE TITLE
When submitting dispute evidence the browser warns about unsaved data

### ISSUE THREAD

**Issue by brucealdridge** [Automattic/woocommerce-payments#9830]
### Describe the bug

When dispute evidence is submitted the browser warns about unsaved data. Clicking `Leave` allows submission to occur successfully.

![Image](https://github.com/user-attachments/assets/0b634220-cf90-4abd-ac30-3bef76989ea2)

### To Reproduce

Respond to an open dispute.

I was able to trigger with the following steps on a fresh site using `develop` branch.

1. View a dispute
2. Click `Submit Evidence` 
3. Select `Physical Product`
4. Enter `winning_evidence` in `Additional Details`
5. Click `Submit evidence`
6. See browser warning.

**Comment by brucealdridge** [comment]
Setting priority to `medium` as this is confusing and breaks the flow for submission of all disputes.

**Comment by nagpai** [comment]
Moving this issue to WooPayments 8.7.0 milestone, since we have hit the code freeze of 8.6.0
