### ISSUE TITLE
The variable $cart_contains_subscription isn’t defined

### ISSUE THREAD

**Issue by doublezed2** [Automattic/woocommerce-payments#9899]
### Describe the bug
Version 8.6.0 shows an error on the cart page. It says that in the file /plugins/woocommerce-payments/includes/class-wc-payments.php on line 1887 the variable $cart_contains_subscription isn’t defined. After checking the code I noticed that the variable is initialized inside the if.

### To Reproduce
Check screenshot.

### Actual behavior
The variable $is_subscription is initialized inside the if statement.

### Screenshots
https://snipboard.io/O7MThL.jpg

### Expected behavior
The variable $cart_contains_subscription should be defined outside the if statement like the $is_subscription variable.

### Additional context
Reported in ZD-9135335

**Comment by aheckler** [comment]
A fix for this was already merged in https://github.com/Automattic/woocommerce-payments/pull/9893

**Comment by c-shultz** [comment]
Per the above, fixed by https://github.com/Automattic/woocommerce-payments/pull/9893

thanks for catching that @aheckler !
