### ISSUE TITLE
Apple Pay Google Pay buttons not shown on products that don't require shipping and prices already include tax.

### ISSUE THREAD

**Issue by brettshumaker** [Automattic/woocommerce-payments#9921]
### Describe the bug
In #9080 these buttons were disabled due to the possibility of not having billing information available when the payment sheet opens and, therefore, we could potentially be showing an incorrect amount if tax is calculated based on billing address. However, an edge case came up in a ticket where the user _did_ have the tax set to be calculated on the billing address for non-shippable products **but** their prices were already entered inclusive of tax. Meaning that no tax calculations should be happening on checkout anyway. I think it should be safe to show the EPMs in this instance. The relevant logic is [here](https://github.com/Automattic/woocommerce-payments/blob/476c528c41c97c867cda9f0b1d3131b3c32fa505/includes/express-checkout/class-wc-payments-express-checkout-button-helper.php#L418-L433).

### To Reproduce
1. Go to `/wp-admin/admin.php?page=wc-settings&tab=tax` and select the radio button to "Yes, I will enter prices inclusive of tax."
2. Set "Calculate tax based on" to "Customer billing address" and save the settings.
3. Add a digital or non-shippable product to the cart.
4. Visit the checkout and the Apple Pay/Google Pay buttons are not added to the page.

### Actual behavior
Currently, with the described tax settings, the EPM buttons are not added

### Screenshots
<img width="660" alt="Image" src="https://github.com/user-attachments/assets/91d05d19-08e0-4afa-8758-2c99062f9f9f" />

### Expected behavior
With the tax settings as described above, accurate totals should be able to be sent to the payment sheet and EPM buttons should be enabled.

**Comment by timur27** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Heisenberg-63586f2ec60359001310fa6a/issues/Automattic/woocommerce-payments/9921?planning-poker) with Zenhub @FangedParakeet

The fix itself is pretty straightforward, what I found requiring attention is the current state of the unit tests. I think we need to refactor a few things there because it's pretty hard to unit test this area at the moment.
