### ISSUE TITLE
Zero dollar subscriptions fail without an error

### ISSUE THREAD

**Issue by leonardola** [Automattic/woocommerce-payments#9942]
### Describe the bug
When the cart contains a zero dollar subscription that will also renewal for free WooPayments gets added as a payment method but is hidden. This makes the checks for WooPay opt-in get triggered but the fields don't get rendered.

WooPayments should not be an available payment method for zero dollar orders with zero dollar renewals

### To Reproduce
- Make sure you're not logged in to WooPay nor the merchant site
- Create a 0 dollar digital subscription
- Add to cart
- Go to the blocks checkout page
- Type all the fields but leave the phone number empty. Don't use autofill as it might fill in a phone number
- Try to place the order
- It will fail without any warning or errors

### Additional context
Slack thread: p1734016378276979-slack-C02CCT3F1QA

**Comment by pierorocca** [comment]
@leonardola did you mention that you think this was an issue in core or did you later discover the issue is contained to WooPay only?

**Comment by leonardola** [comment]
Well I did say that I thought it was an issue on core but that ended up not being completely true. 

When a `cart.needsPayment` flag is set to false core should not try to load any payment methods IMHO but it currently is.
We also forgot to check that flag on our side which made the payment method get loaded but not rendered. Making it the selected payment method by default. 
Even when there was no payment method selected the opt-ins checks would still run making it impossible to place the order.

So this is how I see it:

Core should not load payments when `cart.needsPayment = false`
If core tries to load a payment method anyways the payment method should check the flag and bail instead of loading itself up (fixed in #9943)
If a payment method that is not WooPayments is selected then the opt-in checks should not run (fixed in #9943)
