### ISSUE TITLE
Document payment method deprecation

### ISSUE THREAD

**Issue by FangedParakeet** [Automattic/woocommerce-payments#9976]
When we have to deprecate payment methods and remove them from the plugin, there are generally a common set of tasks that we need to perform each time. See the similarities between #9055 and #9820. 

This issue is to document these steps, so that in the future this will essentially become a chore that requires significantly less effort to perform. 

Satisfactory outcomes of this issue would probably be a P2 page that we could include in one of our team pages to make the process more publicly known, streamlined, and predictable.

**Comment by mdmoore** [comment]
P2 posted at pbIwZe-2D7-p2 and added to our Tech Resources page at PaJDYF-20F-p2#tech-resources
